### ISSUE TITLE
Add more instruments.

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#1001]
[General Midi](https://en.wikipedia.org/wiki/General_MIDI) allows us to use up to 128 different instruments, but we're only using around 15 of them. Variety is the spice of life, so we should add more instruments. (This might require spriting.)

**Comment by FL-OZ** [comment]
The only thing holding me back on this front is spriting.

**Comment by UnderscoreX5** [comment]
Might give a try to this

**Comment by mirrorcult** [comment]
this is pretty much done, we have a ton
