### ISSUE TITLE
uniform printer does not use its directional sprites

### ISSUE THREAD

**Issue by Peptide90** [space-wizards/space-station-14#10022]
## Description

It has other states but does not use them.

**Reproduction**

1) place a uniform printer in mapping mode, notice how you can place it in any direction and it has a state.
2) notice that no matter what you do it always places it facing the same direction.

**Screenshots**

**Additional context**

Should be easy for someone new to look at, there's plenty of examples on other things that use their states.

**Comment by zerorulez** [comment]
The parent of UniformPrinter had a noRot property too.

**Comment by Peptide90** [comment]
> The parent of UniformPrinter had a noRot property too.

Fair enough, I'd check to see if this is going to be an issue for other machines too then, as if other Lathe / Machine parented structures have or will have them, I can't see why they need NoRot. Good job.
