### ISSUE TITLE
If you are pulling something you wont slip on banana peels

### ISSUE THREAD

**Issue by zerorulez** [space-wizards/space-station-14#10026]
If you are pulling something u wont slip on banana peels.

Reproduction:
1 - pull anything with CTRL+left click
2 - walk by a banana peel
3 - you wont slip

**Comment by HoidC** [comment]
is this just because your movement is slowed down when pulling things?

**Comment by zerorulez** [comment]
idk, but this happens even pulling lighter objects like carp plushies

**Comment by mirrorcult** [comment]
yes that is almost certainly why

**Comment by zerorulez** [comment]
Should i close this then?

**Comment by ElectroJr** [comment]
I guess it becomes a balance question of how high the "safe" speed should be for slipping. Maybe it should be lower, so you still slip when pulling small items?
