### ISSUE TITLE
Can't anchor/unanchor any entity that have the Lathe component (Autolathe, UniformPrinter, etc)

### ISSUE THREAD

**Issue by zerorulez** [space-wizards/space-station-14#10032]
## Description
You Can't anchor/unanchor any entity that have the Lathe component with wrenchs.

**Reproduction**
Pick up a wrench and try to anchor/unanchor an Autolathe. You can't.

**Comment by EmoGarbage404** [comment]
Uhh this is because the action for inserting the item into the lathe is being overridden and cancled which causes the action for the toolsystem to never actually run.

**Comment by EmoGarbage404** [comment]
fixed
