### ISSUE TITLE
Extreme difficulty picking up items while floating in space

### ISSUE THREAD

**Issue by AJCM-git** [space-wizards/space-station-14#1003]
1. Impulse yourself into space
2. Spawn items ahead of you
3. Try to pick them up

Its either impossible (i couldnt manage to do it) or more difficult than neccesary

**Comment by Zumorica** [comment]
This is most likely related to InRangeUnobstructed.

**Comment by InquisitivePenguin** [comment]
I've never been able to pick up items in space either, I think it's impossible.

**Comment by Clyybber** [comment]
which makes sense, you should only be able to pick up ones you already touch.
