### ISSUE TITLE
Implement Charcoal.

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#10042]
## Description
A "simple" chemical that removes chemicals from your bloodstream at a rate of 3u per tick, while healing toxin damage. Essentially, it's an injection anti-poison. Should heal one poison damage per unit.

You'll need to implement a simple chemical effect for this, look at implementers of `ReagentEffect` and at the function `Solution.RemoveSolution`. Make sure the amount to remove is specified on the new effect as a datafield, so that it can be configured easily later.

**Comment by WPRobson** [comment]
Does the current freezes for reagent effect this? https://github.com/space-wizards/space-station-14/issues/8524#issuecomment-1173707389 @moonheart08

**Comment by moonheart08** [comment]
No, that's for bartender drinks.
