### ISSUE TITLE
Scaled sprites have their large version for placement

### ISSUE THREAD

**Issue by Peptide90** [space-wizards/space-station-14#10045]
## Description

When trying to place an entity that's had it's sprite component scaled, the placement ghost uses the full scale version and not the scaled down version, making it hard to see where you're placing something.

Ideally the icon or placement mode should take scale into account, or the Icon component should have a scale value too (iirc this icon component shouldn't be necessary and should use the sprite comp but that's also not been working?
**Reproduction**

Place a scaled entity and notice how it's huge. Not sure there's examples in our codebase but there are in my fork as we use 64x64 sprites.
**Screenshots**

**Additional context**

**Comment by metalgearsloth** [comment]
Already a PR https://github.com/space-wizards/RobustToolbox/pull/3058
