### ISSUE TITLE
""Duplicating"" items with high latency 

### ISSUE THREAD

**Issue by AJCM-git** [space-wizards/space-station-14#1005]
When having around ~200ms of ping, sometimes, you can "duplicate" (i *think* other players cant see it) an item by simply picking it up, this might be a ilussion but its very confusing clicking in a item to pick it up and see its doppleganger in the floor.
an example of this:  https://cdn.discordapp.com/attachments/310555209753690112/714663108521623643/out.mp4

**Comment by metalgearsloth** [comment]
I play with 350ms ping and haven't seen this so I doubt it happens anymore.
