### ISSUE TITLE
Rat King should have funny names

### ISSUE THREAD

**Issue by EmoGarbage404** [space-wizards/space-station-14#10063]
## Description

I expect the best cheese puns.

**Reproduction**

**Screenshots**

**Additional context**

**Comment by zerorulez** [comment]
Since Rat King its not a game mode, it will be necessary to change GhostRoleSystem to not take the mob name when creating the mind? I was thinking on adding an if statement when the mob was the Rat King, but i think its not the best solution.

**Comment by EmoGarbage404** [comment]
Is there not just a component you can attach that randomly picks a name from a database/list?
