### ISSUE TITLE
Latejoining apparently doesn't work sometimes

### ISSUE THREAD

**Issue by Ablankmann** [space-wizards/space-station-14#10069]
## Description

Unsure if this happens anywhere else, but this happens anytime I play box.

**Reproduction**

Start up video game
Open Latejoin UI
See this:
![image](https://user-images.githubusercontent.com/103340990/181143984-b70521dc-210e-43b6-8c17-228a522972b0.png)
Cry

**Comment by mirrorcult** [comment]
this definitely isnt box-specific, it's happened on other maps and just seems to be random. presumably the station job list is getting cleared or the datum entity is getting deleted somehow.

**Comment by Emisse** [comment]
happened same merge time as box i believe though so taht should narrow it down

**Comment by Mirino97** [comment]
![image](https://user-images.githubusercontent.com/52474532/183229991-410833a5-c7ef-49a1-aa81-a6671db78adc.png)

You can also open multiple!
