### ISSUE TITLE
Misleading description or missing feature on instant ramen

### ISSUE THREAD

**Issue by EeveeTea** [space-wizards/space-station-14#10060]
Apparently the instant ramen is supposed to have a reaction when coming into contact with water. I'm guessing someone just forgot to add a reaction to turn 3 dry ramen and 1 water into hot ramen, as hot ramen already exists in the drinks prototype beneath the dry ramen one.

![Screenshot_20220726_160237](https://user-images.githubusercontent.com/108430699/181103269-4474a190-a542-4b3f-b095-ed6919c7a2eb.png)

**Comment by Peptide90** [comment]
`- type: reaction
  id: HotRamen
  minTemp: 323.15
  reactants:
    DryRamen:
      amount: 3
    Water:
      amount: 1
  products:
    HotRamen: 3 `

You need hot water

**Comment by AJCM-git** [comment]
The description is still misleading because it doesnt mention hot water and says that it self heats. Thus this is still an issue

**Comment by EeveeTea** [comment]
I propose we remove the temperature requirement. Self-heating instant ramen is a concept that seems futuristic enough to exist in this game.

**Comment by Peptide90** [comment]
> The description is still misleading because it doesnt mention hot water and says that it self heats. Thus this is still an issue

Fair enough, I must have ignored the title when I read the description. I’ll PR the removal of the temp requirement now.
