### ISSUE TITLE
There should be a way to remove body scans from the cloner.

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#10061]
## Description
The current meta regarding cloning is for medical to drag the cloning pod out to the medbay lobby for crewmembers to pre-scan themselves as soon as possible in case of the possibility of them dying later on in the round. Weather or not we consider this powergaming is up for discussion.

This makes it very hard for security personnel to keep a prisoner in perma, since the prisoner can easily kill themselves with lightbulbs or by hitting themselves. Additionally this makes it harder to keep a confirmed antag dead. This also effects traitors, since it makes it harder on those with kill objectives to keep their target dead for good.

If there was a way to erase body scans from the cloner, sec will be able to coordinate with medical to remove known traitors from the scan list to prevent accidental cloning of an antagonist or perma prisoner. 

This will also allow traitors to remove their target from the list to ensure their target stays dead.

I believe this will add to the depth of the game by increasing cross collaboration between departments as well as adding a new method for antagonists to non-destructively sabotage the station.

**Additional context**

Perhaps only the CMO and captain should have the authorization to remove players from the scan list?
Maybe allow emags or hacking to affect this as well in some way?
Should this only be implemented for MRP and keep it as it is for LRP?

**Comment by Elijahrane** [comment]
https://github.com/space-wizards/space-station-14/pull/8972 solves this by removing scans altogether
