### ISSUE TITLE
communications computer's 'announce' button stops working randomly.

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#10074]
## Description
Twice now ive witnessed the 'announce' button on the comms computer grey out and thus not allow any announcements to be broadcasted.

EDIT:  Apparently this also effects cargo's supply, request and recall consoles and protentionaly others as well.

**Reproduction**
Not sure, seems to happen randomly. Both times it happened after many announcements were broadcasted throughout the round and while the round was over 45+ mins long.

**Screenshots**

![coms console problem1](https://user-images.githubusercontent.com/106507028/181169079-efc83b9f-4c6c-4da0-95a2-e2fd33befaac.png)

![coms consule problem2](https://user-images.githubusercontent.com/106507028/181169933-ab28b674-e371-4a96-b363-4898fbb91882.png)

**Additional context
At times the button will light back up, but when you try to announce something nothing will happen.

Had a user(RighardTheRat) think the problem might be related to the station module being deleted? They also confirmed it happened to them multiple times and even had a related problem with the evac shuttle.

deleting and spawning in a new computer will not fix the issue.

**Comment by mirrorcult** [comment]
yes this appears to be the station getting deleted somehow again, same with the latejoin bug

**Comment by Kayek14** [comment]
ah okay good! i tried checking for related issues before posting this but that's good the problem is known about.

**Comment by Kayek14** [comment]
This issue seems to be resoloved.
