### ISSUE TITLE
Syndicate uplinks and initial infection should have a delay

### ISSUE THREAD

**Issue by Nairodian** [space-wizards/space-station-14#10072]
## Description

Recently it seems that as soon as a round starts something will go wrong whether it's the clown buying ten blocks of c4 and killing the HoP before they even have a chance to put on their cape or a zombie outbreak in the medical locker room while everyone is still going through their UIs. I personally feel that there should be a brief moment of grace to allow a shift to play out before anything goes wrong so people can actually equip their gear. Think about what's more impactful, a desperate struggle to survive against zombies with all your fellow cargo techs who you have gotten to know well over the past 20 minutes or a sudden zombie attack at your mess of a cargo bay because no one had anytime to prepare or even think for a second.

**Comment by mirrorcult** [comment]
initial infected should have a delay (or exclusively be midround) but i dont think uplinks need one

**Comment by Nairodian** [comment]
There was a shift that I had today where at about a minute or two in the common radio was immediately flooded with talk of a clown strapping a block of c4 to the HoP's office and killing Ian. There was also the time someone bought a fire axe and blood suit and started going on a killing spree in medbay three minutes into a round. Overall it's not enjoyable to have a shift start and be attacked before you can even do your job once and sec not be able to do anything since they haven't even been able to grab their gear. At some points it feels like a meta that a lot of people use to get green text early into a round before anyone can stop them.

**Comment by EmoGarbage404** [comment]
> initial infected should have a delay (or exclusively be midround) but i dont think uplinks need one

initial infected are becoming midrounds as soon as the code allows it.

**Comment by deltanedas** [comment]
since tators are now like this, initial infected action should be easy to implement
