### ISSUE TITLE
Fire helmet has no sprites for worn or in-hand

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#10082]
## Description
Fire helmet has no sprites for worn or in-hand. It does not render when worn or held in hands, unlike other helmets.

**Reproduction**
- Get fire helmet
- Wear it or hold it

**Screenshots**
There are three helmets on this picture, one worn, two held:
![fire_helmets](https://user-images.githubusercontent.com/108953437/181298563-63eff247-dd5d-46ee-a56e-10b835cf75d1.png)

**Comment by Peptide90** [comment]
Can we get a generic inhands and dropped entities like a little paper bag or something? Making specific inhands for every entity even when it’s similar to others is a pain and a waste.

Also this worked previously when worn so is it a casualty of recent clothing changes?

**Comment by Peptide90** [comment]
For reference, they do have inhands but see above, something broke it.
