### ISSUE TITLE
Something caused cargo shuttle to get stuck on cargo shuttle's dedicated map

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#10083]
## Description
Something caused cargo shuttle to get stuck on cargo shuttle's dedicated map. Absolutely no idea how to reproduce, calling and recalling shuttle using it's console did nothing, it stayed on it's own map. Then I think some admin forced it onto station map, but controls were not responding. Later on Retequizzle and/or moony managed to get cargo working shuttle, not sure if it was the same shuttle.

**Reproduction**
- Dunno! Play cargo!

**Screenshots**
Here some admin did try to fix the shuttle, it was not responding to controls:
![cargo_shuttle_woes](https://user-images.githubusercontent.com/108953437/181299728-d77b3e35-b36b-494b-b46e-7aec2b815aa7.png)

**Comment by retequizzle** [comment]
FTL component seems to be fucky, moony walked me through how to fix it mid-round. Doesn't always happen, but has been pretty frequent today.

**Comment by metalgearsloth** [comment]
Probably just https://github.com/space-wizards/space-station-14/issues/10074

Cargo doesn't use FTL.
