### ISSUE TITLE
Explosive grenades do not beep when primed

### ISSUE THREAD

**Issue by retequizzle** [space-wizards/space-station-14#10086]
## Description
Very easy to make someone go boom if they don't know they're a target for said boom.

**Reproduction**

Just arm an explosive grenade. Does not seem to affect modular grenades, did not test syndicate minibombs.

**Comment by Elijahrane** [comment]
Intended.

**Comment by Just-a-Unity-Dev** [comment]
> Intended.

how in gods name is this intended

**Comment by Elijahrane** [comment]
> > Intended.
> 
> how in gods name is this intended

I've never seen a beeping grenade. Have you?

**Comment by Just-a-Unity-Dev** [comment]
> > > Intended.
> > 
> > 
> > how in gods name is this intended
> 
> I've never seen a beeping grenade. Have you?

well we've already established to the player w/ modular grenades and minibombs that "on interact start beep then boom", feels shitty when you kill yourself because of something stupid

**Comment by Elijahrane** [comment]
The explosive rebalance tried to make all of these different options unique, and I think it's succeeded. Explosive grenades are more challenging to use than other grenades, as you can see by killing yourself, so they're fairly well balanced.

**Comment by Just-a-Unity-Dev** [comment]
tbh at this point just add an alert sound for when you prime a grenade, doesn't need to beep rapidly, just alert the player that "hey! you have a live grenade in your hand! good luck!"

**Comment by Elijahrane** [comment]
> tbh at this point just add an alert sound for when you prime a grenade, doesn't need to beep rapidly, just alert the player that "hey! you have a live grenade in your hand! good luck!"

that sounds ok
