### ISSUE TITLE
IdentityBlocker broke?

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#10081]
## Description
IdentityBlocker broke? No items seem to hide your appearance now.

**Reproduction**
- Wear face-hiding stuff like spacesuit helmet or gas masks

**Screenshots**
This one is _not_ toggled off:
![not_so_anonymous](https://user-images.githubusercontent.com/108953437/181297761-85fd6eed-827f-4085-b4de-3890fce3cd04.png)

**Additional context**
Related to issue #10080?

**Comment by Just-a-Unity-Dev** [comment]
I believe this is due to gas masks being broken on master, not the IdentityBlocker itself

**Comment by Just-a-Unity-Dev** [comment]
> Helmets don't seem to hide your identity too.

IIRC helmets never did

**Comment by Just-a-Unity-Dev** [comment]
oh shit i thought you were talking about the security helmets not the hardsuit helmets my bad
