### ISSUE TITLE
Suspenders has an inventory that doesn't exist.

### ISSUE THREAD

**Issue by LordEclipse** [space-wizards/space-station-14#10123]
## Description
If you have suspenders, the belt slot item, and you go to put an item inside of them, as they show having a "is a bag" icon, the item gets put into an "inventory" that doesn't really exist. The item "exists" still but is completely inaccessible.

**Reproduction**
1. Spawn as a role with suspenders, or find them.
2. Notice the bag icon
3. Attempt to "store" an item in them
4. Notice that you can't open any U.I. for this "inventory"
5. That item is now lost forever to the void.

**Comment by mirrorcult** [comment]
most likely doesn't have a `UserInterfaceComponent` specifying the storage UI. that, or the storage component should just be removed from these
