### ISSUE TITLE
There is no (server-side) way to stop sounds that are playing

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#1012]
Also known as #357 redux.
Ideally, you should be able to stop sounds from the server-side AudioSystem.
Check what #862 did with SoundComponent for inspiration, maybe.

**Comment by SweptWasTaken** [comment]
Fixed by https://github.com/space-wizards/RobustToolbox/commit/2a614e9c3de9f91f3661d2287c7e53271bc4a77a. Closing.
