### ISSUE TITLE
Entities with buckles like chairs, beds, vehicles delete their buckled entity when they are deleted.

### ISSUE THREAD

**Issue by Elijahrane** [space-wizards/space-station-14#10140]
## Description

Pretty bad.
**Reproduction**

1. Sit or lie down on something.
2. Delete that something.
3. You are deleted too.

**Comment by ElectroJr** [comment]
Entities are supposed to delete their children when they get deleted.
Straps and the like should handle DestructionEventArgs and eject buckled entities before deleting themselves.
If other things are directly deleting strap/buckle entities, that has to be handled similarly to DestructionEventArgs.
