### ISSUE TITLE
All duffelbags inhands appear like generic grey bag

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#10147]
## Description
All duffelbags inhands appear like generic grey bag. At least China Lake renders now. But as generic grey.

**Reproduction**
- Hold various duffels

**Screenshots**
Holding China-Lake and medical duffels, every other duffel also shows as generic grey:
![duffels_inhands](https://user-images.githubusercontent.com/108953437/181853822-3f18063f-300c-4a27-bff7-967dc05b7362.png)

**Additional context**
Introduced by PR #9956?

**Comment by EmoGarbage404** [comment]
this was certainly not introduced by #9956???
