### ISSUE TITLE
Horizontal bodies block hitscan bullets but only when in crit.

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#10143]
## Description
Bodies that are horizontal while in crit will block bullets from passing over them. 

In a gun fight its very op to take cover behind a body on the floor since they will tank all the shots for you.

It also not very consistent that the same body will suddenly stop blocking bullets once it is dead.

**Reproduction**
1.  Place a dead body on the floor.
2. Try to shoot behind it.
3. Observe how the body will only block bullets while it is alive or in crit.

**Additional context**
On a side note, it is also impossible to shoot directly at a body once it is dead. The bullet will instead continue on its trajectory instead of impacting and stopping at the body.

Is this a limitation of how hitscan works currently?

Should bodies on the floor have to be clicked on for the bullet to hit them while alive or dead?

Applies to both laser and physical hitscan bullets.

**Comment by metalgearsloth** [comment]
This is intended.
