### ISSUE TITLE
Traitor objectives can be duplicated or be mutually exclusive

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#10152]
## Description
Traitor objectives can be duplicated or be mutually exclusive. At very least, this happens from time to time when traitor is made via "Antag ctrl" menu. Not sure if this is happening with normal traitors.

**Reproduction**
- "Antag ctrl" self into traitor, maybe multiple time
- Get funny objectives

**Screenshots**
Stay alive _and_ die:
![wonky_objectives_1](https://user-images.githubusercontent.com/108953437/181856945-97eca568-c601-4a57-b19b-5d751f279b0c.png)
Die. Then again:
![wonky_objectives_2](https://user-images.githubusercontent.com/108953437/181857106-e0ca017f-b805-49ed-961d-71c86fd509bd.png)

**Additional context**
More objective woes: issue #9935

**Comment by benev0** [comment]
This has been reported again
