### ISSUE TITLE
Shotgun ammo boxes behave both as magazines and boxes

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#10155]
## Description
Shotgun ammo boxes behave both as magazines and boxes. Even separate inventories!

**Reproduction**
- Get shotgun ammo box
- Use it, bringing up box inventory _and_ dropping shell onto ground
- Click ammo box with shells you ejected
- Note that you cannot insert ammo back into "magazine" part of box

**Screenshots**
![shotgun_flare_box](https://user-images.githubusercontent.com/108953437/181859944-f7c8b38a-8b12-4e33-88cb-24653ff4d86c.png)

**Additional context**
Related to #9540?

**Comment by Vordenburg** [comment]
Fixed by #17311
