### ISSUE TITLE
You can rotate during sleep

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#10150]
## Description
You can rotate during sleep. Unless buckled to something, leftclicking stuff around you will make you spin on ground.

**Reproduction**
- Sleep, but not via bed (Memetic Amirmir/Chloral Hydrate)
- Leftclick stuff around you
- Watch self "face" clicked thing

**Screenshots**
![spin_in_sleep](https://user-images.githubusercontent.com/108953437/181854932-3c0bb96c-30e5-4e07-af84-6036d047a7a2.png)

**Comment by jessicamaybe** [comment]
this kind of feels like it should be a feature, sleeping should involve tossing and turning.

**Comment by lzk228** [comment]
cannot reproduce

https://github.com/space-wizards/space-station-14/assets/124214523/89978290-72c4-46cc-b7fe-f419ff5ff1ce
