### ISSUE TITLE
After clicking on an APC, you need to get out of range of it before you can click it again.

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#1015]
![2020-05-27_09-39-19](https://user-images.githubusercontent.com/49448379/83048167-af6d2580-a038-11ea-9498-1f1592820917.gif)

Pretty strange bug.

**Comment by SweptWasTaken** [comment]
PJB says this is an issue with the X window not closing properly

**Comment by PJB3005** [comment]
Fixes by https://github.com/space-wizards/RobustToolbox/commit/044eeb61f400f127a91803fadc14b86d2c56b8ba

**Comment by SweptWasTaken** [comment]
Not been fixed. Can still reproduce.

**Comment by SweptWasTaken** [comment]
Reproduced by multiple people on the Discord.

**Comment by PJB3005** [comment]
That would be because the submodule has not been updated yet.
