### ISSUE TITLE
pAI cannot hear owner's headset?

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#10159]
## Description
pAI cannot hear owner's headset? Pretty sure you can hear other people department channels when you are close to them, but not your own owner's headset, as pAI.

**Reproduction**
- Be pAI of someone with department radio, on live server
- Never hear that radio

**Screenshots**
I am pAI in this conversation (pAI of salvage specialist) and during that round I did not hear supply radio consistently, not even magnet, yet did catch occasional command channel chatter:
![pAI_owner_radio_woes](https://user-images.githubusercontent.com/108953437/181860623-faea99b8-6196-4f78-901c-891580cb9ef9.png)

**Comment by Insineer** [comment]
> Pretty sure you can hear other people department channels when you are close to them

Nope, I've tested, and it doesn't work too :(

**Comment by Insineer** [comment]
So it's not a bug, but a feature request, cause there are no such functionality to eavesdrop other character's radio.

**Comment by deltanedas** [comment]
something you could do now is give a pAI an encryption key to listen to radio (as opposed to making the pai a headset which is probably not the same thing)

**Comment by Visne** [comment]
Letting people in close range eavesdrop on radio channels is a very bad idea in my opinion. Making it possible to put encryption keys into pAI's could be an option, but I don't really expect anyone would ever actually do it?

**Comment by EmoGarbage404** [comment]
Is this even an issue? This isn't a bug and the feature suggested from this doesn't seem very popular.

**Comment by Insineer** [comment]
> Letting people in close range eavesdrop on radio channels is a very bad idea in my opinion. Making it possible to put encryption keys into pAI's could be an option, but I don't really expect anyone would ever actually do it?

So pAI would be able to listen any channels and retell communications to it's owner? I think the way how it is implemented in SS13 is good enough, and there are no any problems that characters hear each other's radio in close range.

**Comment by Visne** [comment]
> there are no any problems that characters hear each other's radio in close range.

[citation needed]

**Comment by GoodWheatley** [comment]
> there are no any problems that characters hear each other's radio in close range.

https://xkcd.com/285
