### ISSUE TITLE
VentClog event will trigger foam instantly

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#10153]
## Description
VentClog event will trigger foam instantly. It used to give long delay, enough to get away from vents into maintenance, warn people over radio about foam, question whenever that was FalseAlert, walk back and die to foam.

**Reproduction**
- Stand next to vent
- addgamerule VentClog
- Die

**Additional context**
Probably introduced by PR #9589.

**Comment by mirrorcult** [comment]
this is only caused by `addgamerule` and this is intended behavior for admin-enabled events to immediately start
