### ISSUE TITLE
Lasers aren't rendered if they don't hit anything

### ISSUE THREAD

**Issue by ComicIronic** [space-wizards/space-station-14#1016]
As described in the comments of #1014 , the effect of firing a laser will not be displayed if the laser itself doesn't hit anything.

The lines at fault are https://github.com/space-wizards/space-station-14/blob/1ad9a10050b0918ca576d7e4b245ca74b834b001/Content.Server/GameObjects/Components/Weapon/Ranged/Hitscan/HitscanWeaponComponent.cs#L99-L103

Specifically, `AfterEffects` is only called if there is some collision from the raycast, and it only uses the raycast collision's distance to draw the effect. It should be easy to change `AfterEffects` to take a distance argument, and call it with the maximum laser distance if no collision took place.

**Comment by tentekal** [comment]
I'll take this one up
