### ISSUE TITLE
Vent under floor tile will still warn you about high pressure in pipe despite you not starting doafer for unwrenching

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#10163]
## Description
Vent under floor tile will still warn you about high pressure in pipe despite you not starting doafer for unwrenching. At some point this used to spam you with massive wall of warnings, but this got somehow fixed and on current version it's mere single message popping up if you are unwrenching floortile-covered vent on high pressure pipe.

**Reproduction**
- Set up high pressure distro
- Try to unwrench vent without removing tile
- Note that you get warning, but still do not start unwrenching pipe

**Screenshots**
![high_pressure_distro_vent](https://user-images.githubusercontent.com/108953437/181862674-06816758-4e59-455f-bb75-939f64344630.png)

**Comment by keronshb** [comment]
Can someone try to replicate this again?

**Comment by IProduceWidgets** [comment]
Could not replicate on live. Closing as resolved.

Perhaps this fixed it? https://github.com/space-wizards/space-station-14/pull/11128
