### ISSUE TITLE
Cap Gun Cartridge Box has no UI

### ISSUE THREAD

**Issue by 5150Con** [space-wizards/space-station-14#10165]
## Description
This might be fixed, but I remember having this issue every time.  Basically, cap gun cartridge box has no UI, and spawns cartridges when you click on it instead of opening its UI.
**Reproduction**

1. Have cap gun
2. Have cap gun cartridge
3. try to open cap gun box
4. Have Cap gun cartridge spawn on ground/your free hand
5. Have no idea how many cartridges are left

**Screenshots**

**Additional context**

**Comment by metalgearsloth** [comment]
Did you try examining it

**Comment by 5150Con** [comment]
> Did you try examining it
I wasn't sure if this issue was fixed, as I have not had access to the items in over a week. If it is a non-issue anymore I can close the post. I remember just pressing E or left click caused it to happen.

**Comment by metalgearsloth** [comment]
It's not supposed to have a UI.

**Comment by Mirino97** [comment]
Yeah, the intended function is: You click on it, you get ammo. Working as intended then :D
