### ISSUE TITLE
Lighthouse crematorium is facing wall

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#10160]
## Description
Lighthouse crematorium is facing wall. You gotta remove the wall to use it.

**Reproduction**
- Load Lighthouse
- Check out chapel

**Screenshots**
![lighthouse_crematorium](https://user-images.githubusercontent.com/108953437/181861107-81cba99e-1fd0-41a3-a141-23576998b22d.png)

**Comment by JustinTrotter** [comment]
Fixed by #10229
