### ISSUE TITLE
Gas Mixers are rounding weirdly

### ISSUE THREAD

**Issue by LordEclipse** [space-wizards/space-station-14#10199]
## Description
If you set a gas mixer to say 98.6/1.4 the number doesn't end up 1.4 it ends up 1.40000015

**Reproduction**
1. Make a gas mixer
2. Set one of the ports to a number that includes a decimal (98.6)
3. Number on the other port ends up being a weird number

**Screenshots**
![image](https://user-images.githubusercontent.com/106132477/182039921-8ee91c1c-dbe9-4a6e-a22a-4c6c3a3caccd.png)

It's really weirdly inconsistent as to what numbers become a decimal, for instance: you could enter 50.1 or 50.4 into the primary port, and they turn out fine with the side port ending up being 49.9 and 49.6 respectively, but 50.2 and 50.3 end up with more strange decimals.

**Comment by PilgrimViis** [comment]
BTW, default output pressure is also looks weird. I know, it's 1 atm on Earth, but maybe it's better to be round up to 101?
