### ISSUE TITLE
Disposal Units not allowing Player entry

### ISSUE THREAD

**Issue by 5150Con** [space-wizards/space-station-14#10207]
## Description
Noticed today that players cannot enter disposal units anymore. There is a loading bar, option in the menu UI to do so, but once the action completes the player remains where they were. 

**Reproduction**

1. Make funny trash loop to Captain's room
2. Try to get in
3. Notice that you cannot get in
4. Seethe

**Additional context**
 My clown content has gone down 50% since this has happened.

**Comment by ElectroJr** [comment]
Ah I just made a stupid mistake and confused the drag-drop `DoInsertDisposalUnit()` with the hand-interaction insert function.
