### ISSUE TITLE
Mouse Eating Issues

### ISSUE THREAD

**Issue by 5150Con** [space-wizards/space-station-14#10211]
## Description
Starving mouse get a limit on how much they can eat in a time frame? It seems counter-intuitive that mice, whose purpose is either RP/Eat, are made to wait while eating, especially while starving. This was after eating 1 pizza pocket, and starting on the next.

**Screenshots**
![20220731235945_1](https://user-images.githubusercontent.com/104950325/182082303-8a83fee2-790e-45ca-a747-486e78aff030.jpg)

**Additional context**
This isn't really a bug or error, more of wanting to know if this is intended or not.

**Comment by Visne** [comment]
I think this is more or less intended, to avoid a single mouse eating all the food in a short while. Once a mouse has eaten two foods, they should be fully satiated, I think. If they're not, that's the real issue here.
