### ISSUE TITLE
Slimepeople shouldn't get stinky

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#10210]
## Description

Rotting dead lime shouldn't be stinky, shouldn't rot at all, also their damage overlay shouldn't be red
**Reproduction**

**Screenshots**

**Additional context**

**Comment by Just-a-Unity-Dev** [comment]
> damage overlay shouldn't be red

either make it green because or their slime color

**Comment by moonheart08** [comment]
Ideally instead of rotting they just leak goo everywhere. Maybe have them slowly leak out their bloodstream?

**Comment by Just-a-Unity-Dev** [comment]
> Ideally instead of rotting they just leak goo everywhere. Maybe have them slowly leak out their bloodstream?

and if theres no more goo do they just dissipate

**Comment by EeveeTea** [comment]
Bodies are already containers full of the subjects' blood/slime, so how about they leak out slime until it's out. Then we could have the body become a small pile of slime balls which are also leaky containers full of the subjects' slime. Next step would be complete dissipation. 

Possible recovery options would be to take samples of the slime balls or floor goo and insert it into the cloner.

**Comment by DogZeroX** [comment]
I'm thinking than cloning slimes should be a job of science with a different machine and requiring chems or actual slime extract from xenobiology

**Comment by Peptide90** [comment]
> I'm thinking than cloning slimes should be a job of science with a different machine and requiring chems or actual slime extract from xenobiology

Shrimply grow a new slime from their core and some goo. Like growing a new plant person with a cutting.

**Comment by Just-a-Unity-Dev** [comment]
> I'm thinking than cloning slimes should be a job of science with a different machine and requiring chems or actual slime extract from xenobiology

does this mean I cant do random bullshit such as set up the singulo without a hardsuit anymore
