### ISSUE TITLE
Telecrystal sprites are rough

### ISSUE THREAD

**Issue by EmoGarbage404** [space-wizards/space-station-14#10228]
## Description

The inhands in particular don't really match the actual sprite. making them a bit more red would be nice.

**Screenshots**

![image](https://user-images.githubusercontent.com/98561806/182242466-053c5c85-b885-41b7-89c0-271a02af241c.png)
![image](https://user-images.githubusercontent.com/98561806/182242374-0ac5db6d-ff42-4972-bf8e-ec4530362adf.png)

**Additional context**

**Comment by Peptide90** [comment]
Diamond in the rough. Please.

we have the technology now, make them sparkle or shimmer whoever takes this on.
