### ISSUE TITLE
Unable to view maint panel on doors

### ISSUE THREAD

**Issue by Just-a-Unity-Dev** [space-wizards/space-station-14#10243]
## Description

**Reproduction**

1. Screwdriver open airlock
2. Multitool

**Screenshots**
![image](https://user-images.githubusercontent.com/67359748/182357154-bc26a5d9-43b2-44a3-9fb2-194f0e597de4.png)

![image](https://user-images.githubusercontent.com/67359748/182357197-08424b2a-85e6-49bb-9ac0-b2abcc8b0cf2.png)

**Comment by Zylofan** [comment]
I had the same issue.

**Comment by Just-a-Unity-Dev** [comment]
Seems to be fixed now
