### ISSUE TITLE
device configurator tweaks

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#10263]
1. You have 0 feedback on operations so I have no idea if set /add / copy / clear work
2. If I swap hands it should close the UI
3. Tooltip timer should be much shorter (but this might be more of a global problem).
4. Multitools should have an examine explaining they can be used to configure device networks (I don't think anywhere mentions this in game). This also probably applies to machine linking.

**Comment by juliangiebel** [comment]
Point 1 and 2 got addressed already. The other two points should get their own issue if still relevant.
A list of devices is shown about the button so you see whats happening when you click them and there is a dedicate network configurator tool
