### ISSUE TITLE
Megaseed vendor in permabrig doesn't work with no id access

### ISSUE THREAD

**Issue by chesse20** [space-wizards/space-station-14#10275]
## Description

If you are in permabrig as priosnner with your id taken away you can't use the megaseed vendor 
**Reproduction**

1. use megaseed vendor in permabrig with no id

**Additional context**

if you are a prisonner in permabrig you probably don't have an id if security took it away but that doesn't mean you shouldn't be able to grow tomatos

**Comment by EmoGarbage404** [comment]
This is a mapping specific issue. This needs to say which map specifically has this issue.

**Comment by chesse20** [comment]
i dont remember

**Comment by EeveeTea** [comment]
I checked every map with a permabrig, and it does seem like a common issue. A couple even have a NutriMax that's inaccessible as well. Listing them here:

Lighthouse
NSS Pillar +nutrimax
Packedstation
Splitstation +nutrimax

**Comment by mirrorcult** [comment]
i dont recall if theres an unlocked variant prototype of the megaseed+nutrimax but there should be

**Comment by EeveeTea** [comment]
A temporary solution would be to provide all the tools and a seed crate instead. That is what's in the other mid-large stations that I checked.

**Comment by Peptide90** [comment]
Respectfully wtf? We all removed the access component from them so they can be used? Unless they’ve been remapped and got the Comp back.

I had suggested adding a variant without access so we have less vv stuff.

**Comment by Peptide90** [comment]
Megaseed vendor has a access free version now so closing.
