### ISSUE TITLE
Ore Processors cannot be unanchored.

### ISSUE THREAD

**Issue by Stealthbomber16** [space-wizards/space-station-14#10284]
Ore Processors are the only machine which, once assembled, cannot be moved.

Reproduction:
- Create an ore processor in an inconvenient location.
- Watch everyone cry.
- Block off major hallways with ore processors.
- Get banned.

**Comment by Stealthbomber16** [comment]
They also cannot be disassembled, so it is literally impossible to move them once they're down.

**Comment by EmoGarbage404** [comment]
fixed
