### ISSUE TITLE
Jetpacks don’t work on station

### ISSUE THREAD

**Issue by GoodWheatley** [space-wizards/space-station-14#10288]
## Description
Jetpacks won’t work while you’re on the station grid, even if gravity generator is off

**Reproduction**
1. Join server 2. Equip jetpack 3. Turn off gravity 4. Attempt to use jetpack 5. Still says jetpack won’t work under gravity 
**Screenshots**

**Additional context**

**Comment by metalgearsloth** [comment]
Intended.
