### ISSUE TITLE
Chat logs from vending machines that aren't being possessed need to die

### ISSUE THREAD

**Issue by juliangiebel** [space-wizards/space-station-14#10304]
## Description

![image](https://user-images.githubusercontent.com/8915246/182951581-c09ace9c-ef16-4f15-bfdb-c982e398c614.png)

Filling up admin logs with shit like that is bad for PostgresCoin

**Comment by Elijahrane** [comment]
![image](https://user-images.githubusercontent.com/60792108/188884385-6517bba2-9033-40b9-97a1-8fdef8f7e9bc.png)

**Comment by Elijahrane** [comment]
This was fixed in https://github.com/space-wizards/space-station-14/pull/10268 I think
