### ISSUE TITLE
Euphonium has no soundfont

### ISSUE THREAD

**Issue by Stealthbomber16** [space-wizards/space-station-14#10318]
The euphonium currently acts equivalent to a supersynth or DAW because its soundfont is invalid.

![image](https://user-images.githubusercontent.com/100171035/183004478-2d21874a-5a4a-468e-8bc9-f770c69b21c2.png)

Step~~s~~ to reproduce:
- Play a euphonium

**Comment by Stealthbomber16** [comment]
Update on this: It is actually acting as a piano on live currently.

**Comment by EmoGarbage404** [comment]
It has a custom midi soundfont. This relates to the issue with the golden bikehorn not playing correctly.

**Comment by Zumorica** [comment]
This is more of an engine issue, multiple people have reported the same issue with custom instruments but I can't reproduce it at all locally

**Comment by EmoGarbage404** [comment]
> This is more of an engine issue, multiple people have reported the same issue with custom instruments but I can't reproduce it at all locally

Is it possible that it could be OS specific?

**Comment by Zumorica** [comment]
> Is it possible that it could be OS specific?

Could be, actually. I only tested this on Linux as I don't have a Windows dev environment ready at the moment
