### ISSUE TITLE
Steal conditions should track components not prototypes

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#10325]
Prototype IDs are only for instantiation. Not using components mean it breaks with inheritance + if the prototype gets renamed there's no check for it.

**Comment by mirrorcult** [comment]
(use an `EntityWhitelist`)

**Comment by IProduceWidgets** [comment]
I think this was resolved by Ed for thieves. 
https://github.com/space-wizards/space-station-14/pull/21520

https://github.com/space-wizards/space-station-14/blob/0edc9218d655758f739d92f513b39fd8026e7ce2/Content.Server/Objectives/Components/StealConditionComponent.cs#L11
