### ISSUE TITLE
New field generators won't shut off

### ISSUE THREAD

**Issue by jessicamaybe** [space-wizards/space-station-14#10328]
## Description
If you turn off the little laser cannons to turn off the field generators they will stay on forever, you can't turn them off

**Reproduction**
1. Turn on field gens
2. Turn off emitters
3. Bask in your unstoppable field generator

**Comment by EeveeTea** [comment]
Could not reproduce. I have seen the mistake of people thinking this when turning off one emitter. The neighboring field generators will compensate for the off one by creating a connection between the two.

**Comment by jessicamaybe** [comment]
> Could not reproduce. I have seen the mistake of people thinking this when turning off one emitter.

When I was having this issue, I was just cutting the power wire to the emitters so they all shut off at the same time.

**Comment by keronshb** [comment]
> > Could not reproduce. I have seen the mistake of people thinking this when turning off one emitter.
> 
> When I was having this issue, I was just cutting the power wire to the emitters so they all shut off at the same time.

Check #10327 I need this to be replicated. Not sure who you are on the discord but there's a video there that shows the fields are draining as intended.

**Comment by EeveeTea** [comment]
The difference between my experience and your video is the existence of a singularity bouncing around in the center. The field does deactivate with all those red text messages and loss of glowing blue fence, but in reality it just becomes invisible and the singulo continues to bounce around. I'll make a video when I have a chance later.

**Comment by keronshb** [comment]
> The difference between my experience and your video is the existence of a singularity bouncing around in the center. The field does deactivate with all those red text messages and loss of glowing blue fence, but in reality it just becomes invisible and the singulo continues to bounce around. I'll make a video when I have a chance later.

Do you mean something like this?

https://user-images.githubusercontent.com/54602815/183498750-f1a0be86-2162-419b-a607-0e017da2b67e.mp4

It's somewhat intended. It purposefully can't eat the field generators unless it's higher than level 4 or else it'll just eat the field generators with a hitbox clipping through every now and then.

**Comment by EeveeTea** [comment]
Wouldn't that be a problem in areas where the field generators are closer together? Here's Split Station with the issue
![Screenshot_20220808_163927](https://user-images.githubusercontent.com/108430699/183510773-bba1b0ae-38f3-45cd-960f-1be9037d1aef.png)
:

**Comment by keronshb** [comment]
> Wouldn't that be a problem in areas where the field generators are closer together? Here's Split Station with the issue ![Screenshot_20220808_163927](https://user-images.githubusercontent.com/108430699/183510773-bba1b0ae-38f3-45cd-960f-1be9037d1aef.png) :

I could see where this can be an issue where someone can just spam field generators to prevent an escape below level 5.

I should be able to do a (Is Connected) check to make sure the field generators are not only just on but connected so there can't be any cheesing.
