### ISSUE TITLE
containment field gen wont degrade 

### ISSUE THREAD

**Issue by Emisse** [space-wizards/space-station-14#10327]
containment field gens once connected cant ever be disconnected from each other. even if emitters no longer fire on them. they can also not be switched off because they are connected
![image](https://user-images.githubusercontent.com/99158783/183024236-79851466-af8e-44d1-9c11-087224991f59.png)

**Comment by keronshb** [comment]
> containment field gens once connected cant ever be disconnected from each other. even if emitters no longer fire on them. they can also not be switched off because they are connected ![image](https://user-images.githubusercontent.com/99158783/183024236-79851466-af8e-44d1-9c11-087224991f59.png)

How long did you wait? Also the emitter is on the screenshot.

Can you replicate this? I just tested again on a local and it's fine. Check about 1:36 in the video on discord (too big for here)

**Comment by Emisse** [comment]
had this happen again

**Comment by keronshb** [comment]
> had this happen again

Can you please give a video and/or reproduction steps?

**Comment by Emisse** [comment]
![image](https://user-images.githubusercontent.com/99158783/184552240-06f4e942-b847-44b1-a266-2bc55b0f3ad0.png)
had it happen again. turn on emitters, let it link, turn off emitters
