### ISSUE TITLE
Atmos devices being able to work while occupying the same slot on the same pipent

### ISSUE THREAD

**Issue by Emisse** [space-wizards/space-station-14#10333]
seen this used with thermo machines and filters to great effect not sure how long this bug been in
![image](https://user-images.githubusercontent.com/99158783/183037376-4722f548-7cf0-46ce-9621-a3529b22920d.png)
in this image the freezer is cooling this pipnet while occupying the same slot and space as the L pipe

**Comment by Emisse** [comment]
![image](https://user-images.githubusercontent.com/99158783/183037866-20215b46-9618-46e1-9012-b9ca12d62dc9.png)
another example

**Comment by jproads** [comment]
we've been found. run for the hills

**Comment by 5150Con** [comment]
Quick, stockpile the Frezon and Trit, winter is coming.

**Comment by Emisse** [comment]
still issue
