### ISSUE TITLE
rooms where i mapped in new cloning console are getting unpowered on mapinit

### ISSUE THREAD

**Issue by Emisse** [space-wizards/space-station-14#10330]
![image](https://user-images.githubusercontent.com/99158783/183034146-2516a96d-b83b-4e73-aa84-1d01894d0db2.png)
cloning console is the only thing powered here. wires are all fine. seen this all day. seems to be depowering an area around it mapinit

**Comment by Elijahrane** [comment]
pretty odd because it doesnt happen when you add it midround

**Comment by Emisse** [comment]
wrenching and unwrenching it fixes it but on mapinit it depowers the space around it

**Comment by Emisse** [comment]
power drain on cloning console is 2x that of a thruster might have something to do with it, like an insane amount of power going to it

**Comment by Elijahrane** [comment]
that part works as an intentional part of the design, we just need to figure out the difference between midround and roundstart
