### ISSUE TITLE
containment field gen target priority issue

### ISSUE THREAD

**Issue by Emisse** [space-wizards/space-station-14#10331]
going over an anchored singulo gen instead of the shorter distance to the side most current setups use, again this wont be an issue when setups are changed but i still think this should be fixed 
![image](https://user-images.githubusercontent.com/99158783/183036040-19275a63-a9ea-45d6-97de-0a1f8b433aa6.png)

**Comment by Emisse** [comment]
did this when one was destroyed
![image](https://user-images.githubusercontent.com/99158783/183038934-8ec5a427-5dcf-40d3-830a-1fda617940c6.png)

**Comment by keronshb** [comment]
> did this when one was destroyed ![image](https://user-images.githubusercontent.com/99158783/183038934-8ec5a427-5dcf-40d3-830a-1fda617940c6.png)

This is an issue but why are you using 9 field gens? There should only be 4.

The upper left one is also off so that's why it didn't connect.
