### ISSUE TITLE
Singulo murdering station entity preventing latejoin/evac

### ISSUE THREAD

**Issue by Emisse** [space-wizards/space-station-14#10335]
99% now that this is how it happens. Not sure repro besides activating singulo and waiting. Once station entity is deleted there is no more latejoin menu for the station and evac shuttle will no longer show up.

**Comment by Elijahrane** [comment]
i had it deleted on atlas earlier which has no singulo

**Comment by Emisse** [comment]
was this on nyano

**Comment by Elijahrane** [comment]
yeah but it's fully up to date

**Comment by keronshb** [comment]
Repeat of #8487
