### ISSUE TITLE
Sometimes examine doesn't work

### ISSUE THREAD

**Issue by LordEclipse** [space-wizards/space-station-14#10349]
## Description
Sometimes when examining the little window flashes for a split second, and disappears before anything is loaded, and this consistently happens anything you try to shift+left click and/or right click on entities, until you reconnect to the server.

**Reproduction**
I have no idea how to reproduce this, but it appears to sometimes happen when loading into a round.

**Additional context**
Not many people seem to have this issue, but I personally have experienced it before.

**Comment by OctoRocket** [comment]
I have had this issue multiple times with headsets
