### ISSUE TITLE
Throwing something in a disposal bin is very unreliable

### ISSUE THREAD

**Issue by Visne** [space-wizards/space-station-14#10377]
## Description

When you throw something at a disposal it often just flies through.

**Reproduction**

1. Throw something into a disposal bin with Ctrl+Q.

**Comment by juliangiebel** [comment]
It's supposed to be unreliable

**Comment by OctoRocket** [comment]
its less fun that way

**Comment by EmoGarbage404** [comment]
> It's supposed to be unreliable

if it's supposed to be unreliable, that needs to be communicated to the player. As it stands, it just randomly doesn't go into the disposal for no visible reason.

**Comment by juliangiebel** [comment]
You're literally trying to throw something into it. Maybe we could add a popup but that's it

**Comment by Visne** [comment]
1. Indeed, there is no feedback which just makes it seem like a bug.
2. Accuracy should depend on range, such that if you are really close to the disposal bin you should always hit.
3. I'm not fully convinced it "should be unreliable" in the first place.

**Comment by metalgearsloth** [comment]
Been in since at least June 2021 and first comment about it afaik.

**Comment by Visne** [comment]
Items don't bounce off either, they just fly over.

**Comment by Visne** [comment]
I still think you should have much higher (up to 100%) chance to hit if you are closer to the disposal.
