### ISSUE TITLE
I'd rather go butt-ass naked.

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#1037]
Our jumpsuits look like shit.

I was in such a passionate rage after seeing our onions I accidentally posted this issue to the tgstation repo like an absolute idiot. This is **not my fault.** It's the fault of whoever thought these dumbass jumpsuits looked good in the first place.

![image](https://user-images.githubusercontent.com/49448379/83221885-9d89a080-a166-11ea-8f22-dbf53465e578.png)
![image](https://user-images.githubusercontent.com/49448379/83221896-a37f8180-a166-11ea-9cc1-ac9eb9562bc5.png)
![image](https://user-images.githubusercontent.com/49448379/83221904-aa0df900-a166-11ea-8a25-f7c96c5929f9.png)
![image](https://user-images.githubusercontent.com/49448379/83221929-bdb95f80-a166-11ea-8909-5286f4c56251.png)
(I know this one isn't used for assistants anymore but it still looks like garbage.)

Making this a discussion thread with a catchy title so that we can have a discussion which hopefully ends up in us switching to tg jumpsuits or a better alternative.

**Comment by FL-OZ** [comment]
bro stop crossposting from TGStation wtf

**Comment by AJCM-git** [comment]
They are literally the same sprite, except the assistant, wich  got changed to the TG sprite a while ago.
