### ISSUE TITLE
Emergency shuttle tile placement meta

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#10385]
Every. single. round. People extend the shuttle on the front and for gameplay reasons it would be better if they were inside. Currently bikeshedding the best way to address this.

**Comment by Emisse** [comment]
make them fall off somehow

**Comment by metalgearsloth** [comment]
2 ideas atm:
1. from flipp, just have specific tiles you can't build adjacent too or something else to avoid extending certain grids
2. Have an FTL drive machine and when it's enabled you can't extend a grid but you can FTL / build tiles inside of it and then lock it on the emergency shuttle.

They don't stop people just being on the front but when I code shuttle impacts they will explode into gibs anyway.

**Comment by OctoRocket** [comment]
is this a bad thing though?

**Comment by AJCM-git** [comment]
Another option is saving the grid bounds in a var at FTL/shuttle ComponentStartup and checking at launch that if the bounds differ from the start, split the grid to its original bounds (could also make this optional with a bool datafield in the component)
