### ISSUE TITLE
Cargo shuttle cannot be called

### ISSUE THREAD

**Issue by Stealthbomber16** [space-wizards/space-station-14#10391]
Issue currently on live. I don't know if something specifically broke it, or if it just doesn't work overall. Apparently it's been broken all day and nobody in the cargo department actually bothered to report it.

Steps to reproduce
- Press Call Shuttle
- watch as nothing happens

**Comment by ike709** [comment]
@metalgearsloth

**Comment by metalgearsloth** [comment]
It's because stations got moved to nullspace.

**Comment by Kayek14** [comment]
Is there any possible work around? Or is this something we need to put up with until a fix?

**Comment by OctoRocket** [comment]
you can ahelp and ask for a teleporter instead
