### ISSUE TITLE
Match boxes have a 6 size but can hold 10 sized item + other issues with match box

### ISSUE THREAD

**Issue by grondinW** [space-wizards/space-station-14#10390]
## Description

Match box size is 6, but they have a size 10 capacity. It's weird being able to put a complete mag or a crowbar in a match box.

**Reproduction**

Get a match box, put stuff in it.

**Screenshots**

https://imgur.com/a/VkzuG2k

**Additional context**

It's great to being able to hide stuff in a match box, maybe reduce the capacity to 6 and add some exceptions. Putting an Id other small stuff in it to hide them seems fine.

**Comment by Mirino97** [comment]
Should be as simple as going to the .yml file that contains the matchbox, then changing the size of the Storage accordingly and/or adding an item whitelist as well.
