### ISSUE TITLE
Lighthouse has "chr" chairs

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#10399]
## Description
Lighthouse has "chr" chairs. No idea what is causing those, normal chairs with normal name are seen there too.

**Reproduction**
- Load Lighthouse, look around

**Screenshots**
![chr](https://user-images.githubusercontent.com/108953437/183314728-73702f2d-550a-4294-8180-078d2b364d36.png)

**Comment by metalgearsloth** [comment]
All maps have these and it's intended.

**Comment by DogZeroX** [comment]
#8674
