### ISSUE TITLE
Drunk/SpaceDrugs shaders break Entity Spawn preview

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#10396]
## Description
Drunk/SpaceDrugs shaders break entity spawn preview. What used to be green thing turns into green square.

**Reproduction**
- Eat bicaridine or SpaceDrugs
- Once shader kicks in, spawn stuff from Entity Spawn Panel
- Notice green square

**Screenshots**
Expectations:
![entity_preview](https://user-images.githubusercontent.com/108953437/183314025-50cd9017-e315-4924-bdb0-c9d4cd1cd32b.png)
Reality:
![shader_broke_entity_spawn_preview](https://user-images.githubusercontent.com/108953437/183314033-b795ddf7-533b-4413-8d9e-216771a10f14.png)

**Comment by Elijahrane** [comment]
This has happened to me with basically every shader I've ported to the game

**Comment by metalgearsloth** [comment]
It's when overlays don't set the shader back to null it affects every other overlay assumes it to be null.

**Comment by Mirino97** [comment]
Porting over Electro's comment so I can close other issue:

`There's also a similar problem with the matrix transforms. I guess if the convention is to null shaders at the end of an overlay, the transforms should also be set to the identity at the end?`

**Comment by metalgearsloth** [comment]
Shoulda closed this one as the other one as it details the fix.
