### ISSUE TITLE
Game dice will "land" in void of space

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#10407]
## Description
Game dice will "land" in void of space. Minor, yet I think you should not be able to play D&D without gravity or even surface.

**Reproduction**
- Throw dice into space
- Watch dice "land" on some side and continue coasting into void

**Screenshots**
![space_dice](https://user-images.githubusercontent.com/108953437/183317599-f074536b-54ad-4446-a11d-4695ffd3f8ce.png)

**Comment by OctoRocket** [comment]
I have noticed many items "land" in space, so I think its a universal problem, maybe a check if there is gravity for the landing code.

**Comment by metalgearsloth** [comment]
1-line fix, I think this regressed.

**Comment by Jrpl** [comment]
PR for the fix was merged. This issue can be closed.
