### ISSUE TITLE
Healing mob's burn damage instantly breaks held shield

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#10405]
## Description
Healing mob's burn damage instantly breaks held shield.

**Reproduction**
- Spawn Urist McHands
- Brutalize Urist with lit welder
- Give Urist wooden buckler or riot shield via strip menu
- Apply single ointment or administer some Dermaline
- Watch in awe how shield instantly shatters

**Screenshots**
![ointment_broke_buckler](https://user-images.githubusercontent.com/108953437/183316281-508f7ec8-00f4-4099-aa9d-277ad0ebc0b4.png)

**Additional context**
Nominating this for "Bug of the Year 2022 Candidate". I don't even.

**Comment by wmann95** [comment]
Just a note that I am currently working on this.
