### ISSUE TITLE
Bible message popups meant for chaplain are seen by everyone

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#10403]
## Description
Bible message popups meant for chaplain are seen by everyone. Stuff like `Your familiar will arrive once a willing soul comes forth.` should be seen by chaplain only. It is not _my_ bat, chappy is summoning one, I am just watching.

**Reproduction**
- Watch chaplain fiddle with familiar summon

**Comment by IProduceWidgets** [comment]
Replicated.
