### ISSUE TITLE
Singularity's own acceleration impulses should be toned down

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#10416]
## Description
<strike>Containment fields should not bounce singularity</strike>. Or rather, singularity should not do those crazy acceleration impulses. Until issues like #10394 are fixed, this just leads to eventual singuloose that is not fault of engineers.

**Reproduction**
- Set up singularity
- Watch it bounce violently upon _it deciding to accelerate strongly and_ collision with field

**Screenshots**
This is live singuloose, reported to merely suddenly clip through field:
![singuloose_cause_bouncy](https://user-images.githubusercontent.com/108953437/183322864-498d9e0e-ffb4-47cf-8b91-336b7f205bc8.png)

**Additional context**
I am unable to reproduce clipping behavior on 60-tick localhost, yet this is definitely a danger. Does Lizard run at 30 ticks?

**Comment by Just-a-Unity-Dev** [comment]
> 30 ticks?
Yes it does since it reduces load heavily for both client an dserver

**Comment by keronshb** [comment]
They don't, well not the way you're thinking it does. It works as it normally does: it doesn't get thrown like players and such. Please give me steps to reproduce. I've tested it and was not able to reproduce this.

https://user-images.githubusercontent.com/54602815/183413634-bfaa1bea-74e0-4bce-a6f4-6bb6845e1112.mp4

**Comment by keronshb** [comment]
This will probably be fixed by substepping or some other cd addition to physics, instead of a bandaid fix of changing the values.
