### ISSUE TITLE
Audio Occlusion is not working.

### ISSUE THREAD

**Issue by Pangogie** [space-wizards/space-station-14#10419]
For nearly a week audio occlusion had been broken.

You can hear everything in PVS range with only distance filtering applied.
This means you can hear someone getting beat up in maint from a good distance.

**Comment by Elijahrane** [comment]
I can confirm it's pretty bad

**Comment by mirrorcult** [comment]
i thought something was off but i couldnt put my finger on it

**Comment by metalgearsloth** [comment]
Fixed in https://github.com/space-wizards/space-station-14/pull/10538
