### ISSUE TITLE
Energy dagger inhand sprite is wonky when user is facing left

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#10411]
## Description
Energy dagger inhand sprite is wonky when user is facing left. Namely, it will oscillate between two different sprites, making dagger wiggle 90 degrees.

**Reproduction**
- Hold active energy dagger
- Face left

**Screenshots**
Pictured: all Urists are holding energy dagger in right hand. Pay attention to bottom right one, it oscillates between those two states:
![edagger_facing_left_1](https://user-images.githubusercontent.com/108953437/183319016-cf143355-3e82-4fc7-b614-ef6b4c78a87e.png)
![edagger_facing_left_2](https://user-images.githubusercontent.com/108953437/183319029-dc3e437c-556c-462d-bc3d-d6f64382580b.png)

**Additional context**
Maybe also fix top left Urist clearly holding dagger in right hand yet having energy blade come out of left hand.

**Comment by Mirino97** [comment]
This should be rather easy to fix:

Take a look at the energy dagger RSI sprites, they'll probably be in the wrong order in the image file, or the .json file in the RSI folder and replace/change them accordingly.
