### ISSUE TITLE
Midi Support has broken again. (Windows 10)

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#1041]
Windows 10. Latest build.

Using any kind of instrument throws the "Midi Support not Available" screen.

Error in the client console.
![image](https://user-images.githubusercontent.com/49448379/83315435-83f06380-a20f-11ea-8ce2-f463546c665f.png)

**Comment by Zumorica** [comment]
Can you, or someone else, still reproduce this?

**Comment by SweptWasTaken** [comment]
Just reproduced on latest master.

**Comment by FL-OZ** [comment]
Just tested on latest [commit](https://github.com/space-wizards/space-station-14/commit/d724c56d38b33c787f6d13967287e55e03bcd188) on Windows 10. Works fine. 
**unable to reproduce**

**Comment by SweptWasTaken** [comment]
Fixed on latest master
