### ISSUE TITLE
Something caused decal thing overlay just float through CentCom

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#10413]
## Description
Something caused decal thing overlay just float through CentCom. I am not entirely sure what I am looking at here.

**Reproduction**
- Dunno! But this particular round had kudzu mess up station badly and also failed to restart the round.

**Screenshots**
This thing just been slowly floating through CC. I am not sure what it is even.
![decal_thing_just_floating](https://user-images.githubusercontent.com/108953437/183320107-4bbb0ea6-87cd-4d73-977d-6bf51cb33466.png)

**Additional context**
Round #13316. Maybe there's some surviving logs shining light on origin of issue.

**Comment by ElectroJr** [comment]
At a guess, you're seeing decals from some other grid, probably on some other map. There is an issue in the decal overlay where it doesn't check the map id of the viewport, which needs to get fixed. 

But aside from that, unless you have a "viewer" (e.g., camera window open) that is present on that other map/grid, the decals should have left your view and thus should have been removed from you client's overlay the moment you switched maps, so either there is also some other issue, or whatever caused this is something else entirely.
