### ISSUE TITLE
Panic bunker is just whitelist by another name

### ISSUE THREAD

**Issue by Elijahrane** [space-wizards/space-station-14#10417]
## Description

![image](https://user-images.githubusercontent.com/60792108/183323811-5ec33da7-4ad2-474f-a5c9-ba3c1a70d2ee.png)
Minimum age: 24 hours
![image](https://user-images.githubusercontent.com/60792108/183323836-1a5443da-4ef3-4f60-a3d7-6c1039bb3272.png)
Account age: over 2 months
![image](https://user-images.githubusercontent.com/60792108/183323874-6df7c0e9-56c4-43e8-8a43-2c5db910a675.png)
Whitelist enabled: false

Try connecting:
![image](https://user-images.githubusercontent.com/60792108/183323911-6fe0c611-7489-4b0a-84dd-10d8b4cb7821.png)

Surely this isn't intended behavior, right? What's the difference between this and just having whitelist then

**Comment by Visne** [comment]
Yes, it should let you in if your account has entered the server more than 24 hours earlier. While a whitelist is intended to only allow specified accounts, a panic bunker is intended to allow everyone except for people that have never visited the server before, to counter raiding.
