### ISSUE TITLE
Default strip menu vertical size is too small to accomodate right hand button

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#10424]
## Description
Default strip menu vertical size is too small to accomodate right hand button. Bit annoying having to resize it every time.

**Reproduction**
- Open strip menu for mob

**Screenshots**
![ghost_buckler](https://user-images.githubusercontent.com/108953437/183332083-6ae14e3e-dd1c-45f7-a6d1-32a562d07a73.png)

**Comment by wmann95** [comment]
I've made a pull request for this. Increased the size of the window to be 640 pixels rather than 600.

**Comment by wmann95** [comment]
Update to the previous: #10440 is now an automatically resizing based on how many inventory slots there are for the entity being stripped. Example:
![image](https://user-images.githubusercontent.com/57637101/183527369-ec5a3876-1748-403d-817e-41233fc09faf.png)
Both of these strip menus weren't resized.
