### ISSUE TITLE
Strip menu will not update upon item destruction

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#10423]
## Description
Strip menu will not update upon item destruction. I expect "None" to be there instead of now-gone item's name.

**Reproduction**
- Destroy item held by Urist as per issue #10405
- Open strip menu again, try to take away nonexistent item

**Screenshots**
![ghost_buckler](https://user-images.githubusercontent.com/108953437/183332083-6ae14e3e-dd1c-45f7-a6d1-32a562d07a73.png)

**Comment by deltanedas** [comment]
bug from old ui + it is fixed now, deleted items vanish from strip ui now

**Comment by lzk228** [comment]
fixeeed
