### ISSUE TITLE
Sandbox UI button is broken. 

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#1042]
You can press the sandbox button and it will bring up the menu, but once you close it you cannot bring it up again. Even if the button shows green.

![2020-05-29_17-52-27](https://user-images.githubusercontent.com/49448379/83315499-d7fb4800-a20f-11ea-98cd-77ada5852c01.gif)

**Comment by SweptWasTaken** [comment]
Reproduced by multiple people on the Discord server.

**Comment by Clyybber** [comment]
I think this has been fixed by https://github.com/space-wizards/RobustToolbox/pull/1097

**Comment by AJCM-git** [comment]
Yep, this was fixed by it
