### ISSUE TITLE
Getting sleeping mob out of crit will result in sleeping mob standing

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#10422]
## Description
Getting sleeping mob out of crit will result in sleeping mob standing. All while still sleeping.

**Reproduction**
- Spawn Urist
- Give Urist tons of Chloral Hydrate and Stellibinin
- Put Urist into crit
- Get Urist out of crit
- Watch Urist stand upright and snore

**Screenshots**
![standing_and_sleeping](https://user-images.githubusercontent.com/108953437/183330578-53575aca-2a67-4451-b5b6-0391d7b63371.png)

**Comment by lzk228** [comment]
fixed

https://github.com/space-wizards/space-station-14/assets/124214523/3233bc46-11ec-4e20-a0d3-b8ea2757c7b8
