### ISSUE TITLE
Entity Spawn Panel entries for cargo crates have `{???}` suffix

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#10438]
## Description
Entity Spawn Panel entries for cargo crates have `{???}` suffix. Don't see it in cargo consoles or on crates themselves, just Entity Spawn Panel.

**Reproduction**
- Search for `crate` in Entity Spawn Panel

**Screenshots**
![crate_question_marks](https://user-images.githubusercontent.com/108953437/183422920-db793e28-cd7b-45e5-abe4-39daf7f261d8.png)

**Additional context**
Probably introduced by PR #10248.

**Comment by Morb0** [comment]
The easiest way to fix this is to put after `.desc` - `.suffix = { "" }`.
All `ent-` locale strings require a suffix otherwise displayed `???`.

**Comment by Rinkashikachi** [comment]
Morb0s solution will work, but this is a lot of work not needed and frankly speaking a workaround by itself.

The problem comes from Fluent's way of treating default values and I've addressed it in [my PR](https://github.com/space-wizards/RobustToolbox/pull/3114) to the engine repo.
