### ISSUE TITLE
Mice can drag people onto tables

### ISSUE THREAD

**Issue by Visne** [space-wizards/space-station-14#10441]
I imagine that means they're also able to do some other stuff they're not allowed to, but I couldn't find anything.

**Comment by grondinW** [comment]
They can also spill a whole janitor mop bucket.

**Comment by Renlou** [comment]
Thats a feature, not a bug

**Comment by Visne** [comment]
Spilling an entire bucket is probably too much power for a ghost role.

**Comment by lzk228** [comment]
they doesnt have hands!

https://github.com/space-wizards/space-station-14/assets/124214523/289eefd0-74d8-45de-a330-9c2af632fb50
