### ISSUE TITLE
StationDataComponent deletion check causes errors when using `restart`

### ISSUE THREAD

**Issue by ElectroJr** [space-wizards/space-station-14#10452]
#10348 introduced an issue where using the `restart` command will throw an error.
Apparently the command will cause entity-manager to shutdown & delete all entities while game ticker is still has `RunLevel == GameRunLevel.InRound`.

So one fix is to just remove the exception altogether if the issue causing the station deletion ever gets resolved. Another fix is to maybe just have the content's `EntryPoint.Dispose()` tell game ticker that the round is over, as that gets called before entity manager shuts down?

**Comment by wmann95** [comment]
This also happens just when stopping the server.
