### ISSUE TITLE
Windoors should have a toggle button

### ISSUE THREAD

**Issue by Visne** [space-wizards/space-station-14#10462]
HoP gameplay is pretty annoying when a windoor constantly closes up in your face. I'm not sure whether a "toggle button" would be the best way to handle this though.

**Comment by mirrorcult** [comment]
SS13 handles this by making bump-opening windoors autoclose but windoors that are explicitly clicked on would not autoclose

**Comment by mirrorcult** [comment]
(which I think would be a decent way to do it)

**Comment by Visne** [comment]
That's nice I think.

**Comment by mirrorcult** [comment]
#11180
