### ISSUE TITLE
Spawned in medical as HoP on Pillar

### ISSUE THREAD

**Issue by Visne** [space-wizards/space-station-14#10464]
At least, it's Pillar according to someone in Discord. I wasn't able to check during the round. Should be a pretty easy fix assuming nothing more fucky is going on.

**Comment by asperger-sind** [comment]
"Should be a pretty easy fix assuming nothing more fucky is going on."

This, I doubt, spawns on Pillar from my experience are fucked as all roles, I remember spawning as a Detective in the Janitorial and Engi several times, and I also remember some HoP spawning in sec, so it's something deeper in the code or some issue with the map itself, so it might not be that easy.

**Comment by Emisse** [comment]
probably missing job spawners for those roles, pillar code is still cooked tho and peptide was working on remaking it
