### ISSUE TITLE
Smokeable recipes use the wrong construction graph step for materials

### ISSUE THREAD

**Issue by Visne** [space-wizards/space-station-14#10466]
Examples:

1. Get 5 ground cannabis, 1 cigarette filter, 1 rolling paper
2. Craft 1 joint
3. All 5 ground cannabis wil be gone, when only 1 is required

1. Have 2 stacks of 1 dried cannabis each
2. Try to craft ground cannabis
3. It doesn't work
4. Combine the 2 stacks into 1, of 2 dried cannabis
5. Craft ground cannabis, it works

**Comment by EmoGarbage404** [comment]
They use the prototype step rather than the material step. Should be an easy fix. Look at the construction docs for more info.

**Comment by Visne** [comment]
> They use the prototype step rather than the material step. Should be an easy fix. Look at the construction docs for more info.

Yeah, that seems to be true. Still, doesn't explain why crafting with 2 separate stacks of 1 does not count as 2 materials for a crafting recipe.

**Comment by Visne** [comment]
Since half of this issue will be fixed by #10497, I'm opening a new issue specifically for the "2 stacks of 1" issue.

**Comment by Zumorica** [comment]
> Still, doesn't explain why crafting with 2 separate stacks of 1 does not count as 2 materials for a crafting recipe.

Because crafting code sucks and that's not coded yet
