### ISSUE TITLE
You can hop between shuttles in FTL

### ISSUE THREAD

**Issue by asperger-sind** [space-wizards/space-station-14#10488]
## Description

Yes, you can jump off the emergency shuttle, fly to the right, and magically appear on the left wing of the nukie shuttle going alongside with it.
**Reproduction**

I honestly have no fucking idea, but the description should more or so count as a valid method.

**Comment by metalgearsloth** [comment]
This is intended

**Comment by EmoGarbage404** [comment]
At the very least, the shuttles shouldn't be directly next to each other.

**Comment by asperger-sind** [comment]
> At the very least, the shuttles shouldn't be directly next to each other.

It's... complicated, from what I've seen the nukie shuttle was 200~ tiles behind the escape shuttle in a really weird way.
