### ISSUE TITLE
No Grav table Jumping

### ISSUE THREAD

**Issue by Kromabae** [space-wizards/space-station-14#10483]
## Description
When in No Grav and you jump a table you get launched.
this is mostly becuase when you do jump a table in Grav you do a small quick step forward, this small step in No Grav causes you to get launch at high speeds.

you can combine this speed with getting slipped and go beyond light speed and just phase through walls.

this issuse is sorta similar to the one i made before about the soaps that sends you forward when you slip on them (omega and syndicate) that has the power basically make you no clip to areas you wouldn't get into otherwise.

all in all, game cannot handle fast speeds and it causes you to phase through walls, think this is like the third time i post this

**Comment by lzk228** [comment]
fixed

https://github.com/space-wizards/space-station-14/assets/124214523/b5658560-7639-4243-a16e-906caaa4e59c
