### ISSUE TITLE
Windows should prevent selecting things beneath

### ISSUE THREAD

**Issue by Clyybber** [space-wizards/space-station-14#1048]
Example of what shouldn't be:
![screen](https://imgur.com/Civ09RR.png)

**Comment by ComicIronic** [comment]
Does the window still prevent clicking on the object beneath?

**Comment by ShadowCommander** [comment]
Is it just highlighting or is input going through even with the window being clicked?

**Comment by Clyybber** [comment]
It's just highlighting AFAICT, so its really low priority; but it's a bit more confusing with windows such as the Hacking UI.
