### ISSUE TITLE
Remove kahlua

### ISSUE THREAD

**Issue by Visne** [space-wizards/space-station-14#10486]
Three issues:

1. It is misspelt in game (it's spelled 'Kahlúa')
2. It's [trademarked](https://trademarks.justia.com/720/80/kahlua-72080029.html)
3. It's main ingredients are [rum, sugar and coffee](https://en.wikipedia.org/wiki/Kahl%C3%BAa), which are all in the game already

I propose to remove 'kahlua' from the game and replace it with generic 'coffee liqueur', which is made by mixing 1 rum, 1 sugar, 1 coffee (or some other amount of parts).

**Comment by Visne** [comment]
Might be handled by #9410, I don't know if /tg/ has it.

**Comment by ZeroDayDaemon** [comment]
Will rename to coffee liqueur or something along those lines in my PR, pretty sure /tg/ has this.

**Comment by Visne** [comment]
Cool, thanks
