### ISSUE TITLE
HackUI interaction issue w/ objects held in hands.

### ISSUE THREAD

**Issue by Daracke** [space-wizards/space-station-14#1049]
After applying a screwdriver to an airlock door, you are not able to bring up the hackingUI window if there is any object in your active hand. I.e you can't look at the wire panel if you have a multitool in one hand, and wire-cutters in the other, without first putting away a tool and then switching to your empty hand.
 
A user in the discord was able to reproduce this issue.

**Comment by PJB3005** [comment]
Can you not press E to open the menu?

**Comment by Daracke** [comment]
Okay yeah, you can press E while hovering the mouse over the door, didn't know that.

**Comment by Akpotohor12** [comment]
Amazing update you have here I really appreciate it, thanks. Let me introduce myself Sir, my name is Sunday and I want to learn more from you, you can email at gratefulheart946@gmail.com. You can check this out  
https://www.makeoverarena.com/waptrick-games-videos-mp3-download-www-waptrick-com/
