### ISSUE TITLE
"Can't use jetpacks under gravity" feedback without gravity, off-station

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#10517]
## Description
"Can't use jetpacks under gravity" feedback without gravity, off-station. If intended (message name is `jetpack-no-station`, also issue #10288), this is communicated poorly, as I am not experiencing gravity or wearing magboots.

**Reproduction**
- Make lattices for new shuttle
- Turn off magboots
- Try to jetpack through lattice thing

**Screenshots**
![no_jetpack_for_you](https://user-images.githubusercontent.com/108953437/184184409-91579c4c-ac4d-4f87-b207-55a27928f570.png)

**Additional context**
Not sure why ban jetpacking on gravity-less station and what's the good handwavium for it.

**Comment by metalgearsloth** [comment]
Intended, makes stations messy to read with the sprites.

**Comment by EmoGarbage404** [comment]
considering this has been a repeated issue, why not change the text to "Can't use jetpacks on station"? It clarifies the actual mechanical function a bit better.

**Comment by metalgearsloth** [comment]
If someone thinks of a better interchangeable word between shuttle, station, salvage, asteroid, etc rather than just "grid" I'll update.
