### ISSUE TITLE
Suggestion: Empty syringe to start in "Draw" mode and locked in it until they have something, full syringes locked to "Inject" mode

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#10516]
## Description
Empty syringe to start in "Draw" mode and locked in it until they have something, full syringes locked to "Inject" mode. This QoL change probably will save you second or two per round if you are making use of them.

**Reproduction**
- Loot syringe box, notice syringes are in inject mode despite being empty
- Waste own time by switching full syringe into Draw mode

**Comment by lzk228** [comment]
solved i think

**Comment by deltanedas** [comment]
yes
