### ISSUE TITLE
Zombies when cloned retain their name, appearance, but are no longer zombies

### ISSUE THREAD

**Issue by EmoGarbage404** [space-wizards/space-station-14#10530]
## Description

After a zombie is killed and cloned, it will retain the zombie appearance (green skin, red eyes) and keep the zombified prefix in front of it's name, but will no longer be a zombie or have the zombieComponent. 

**Reproduction**

zombify man
kill man
clone man
zombie man

**Screenshots**

**Additional context**

The solution should either be transferring the zombie component while cloning or making zombies uncloneable.

**Comment by Elijahrane** [comment]
you could look into applying the 'zombified' part of the name via identity rather than changing the actual entity name

**Comment by EmoGarbage404** [comment]
doesn't fix the appearance part of it. I suppose they could always be modified to use a visualizer rather than modifying the humanoid appearance.

**Comment by EmoGarbage404** [comment]
seeing as this issue has come up for discussion again, ez fix is making zombies uncloneable. I really don't know how that would affect game balance, though.
