### ISSUE TITLE
borgs try to pathfind through closed doors

### ISSUE THREAD

**Issue by EmoGarbage404** [space-wizards/space-station-14#10556]
## Description

they don't seem to acknowledge that blast doors are solid.

**Reproduction**

make a mess on the other side of a blast door
watch as cleanbot rams its head into the door

**Screenshots**

![image](https://user-images.githubusercontent.com/98561806/184501383-7f8795a5-6326-4fe5-b8b7-8c76990533dd.png)

**Additional context**

**Comment by Elijahrane** [comment]
i'd just like to interject for a moment. What you're referring to as a borg, is, in fact, a bot, or as I've taken to ca-

**Comment by EmoGarbage404** [comment]
This was fixed a while ago between various pathfinding tweaks.
