### ISSUE TITLE
entitystorage collision can become desynced from client

### ISSUE THREAD

**Issue by EmoGarbage404** [space-wizards/space-station-14#10559]
## Description

it feels like garbage. It will probably require moving at least parts of entityStorage into shared.
**Reproduction**

join server
open locker
leave and rejoin
walk through locker, notice weird visual effect where you stop before teleporting to the opposite side of it

**Screenshots**

**Additional context**

**Comment by ElectroJr** [comment]
AFAICT this is just a bug in fixture component initialization/state handling, and I think can just be fixed by calling `component.SerializedFixtures.Clear()` in the state-handling function.

> moving at least parts of entityStorage into shared.

Though feel free to move all of it into shared anyways, there is no reason for it not to be.
