### ISSUE TITLE
The IFF console can be used whilst being unpowered.

### ISSUE THREAD

**Issue by asperger-sind** [space-wizards/space-station-14#10551]
**Additional context**

Bottom text

**Comment by OctoRocket** [comment]
By iff console do you mean mass scanner or shuttle console?

**Comment by moonheart08** [comment]
> By iff console do you mean mass scanner or shuttle console?

They mean the IFF console.

**Comment by lzk228** [comment]
![image](https://github.com/space-wizards/space-station-14/assets/124214523/1786ea18-cd9a-4fe3-83e7-6c313bce5ea8)
