### ISSUE TITLE
Nuke will disarm if the tile underneath is removed.

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#10561]
## Description
If the tile underneath the nuclear fission device is removed while the device is anchored and armed, the device will disarm. This was tested using both explosives and admin tools to remove the tile which both yielded the same result.

**Reproduction**
1. Acquire means to arm the nuke
2. Arm and anchor the nuke.
3. Remove the tile under the armed nuke.
4. The device will disarm.

**Screenshots**
Arm the nuke.
![nuke issue 1](https://user-images.githubusercontent.com/106507028/184505223-4755cc16-824f-41e0-9561-90d99f02fc87.png)

Remove the tile.
![nuke issue 2](https://user-images.githubusercontent.com/106507028/184505227-9128ba1d-af37-4a25-8481-9c8480a59270.png)

**Additional context**
Not sure if this is something funky with the grids or if the device is just disarming itself since it is no longer anchored.

**Comment by EmoGarbage404** [comment]
![image](https://user-images.githubusercontent.com/98561806/184505608-7f3575ba-8203-4e76-b414-4ab6f232cb3d.png)
this was an intentional choice.

**Comment by moonheart08** [comment]
@EmoGarbage404 This makes it possible to dodge the 30 second disarm timer. Let mirror review this.

**Comment by mirrorcult** [comment]
no it doesn't literally look at the code
