### ISSUE TITLE
Mail Units arent working as intended

### ISSUE THREAD

**Issue by Cheackraze** [space-wizards/space-station-14#10581]
## Description
Mail units arent working at all as intended. They are simply acting as blue colored garbage chutes that you cant jump in. They also accept anything other than live things. I could send my whole backpack through it, potentially filled with 120 worth of stuff.

**Reproduction**
Step 1: replace any two garbage units with mail units, place them properly on the chute trunks. Or just make a test system as seen below in the screen shots.
Step 2: name them with the multi tool
Step 3: watch your items disregard the mailing system and just follow normal disposal chutes routing, sending your stuff just into disposals or through whatever routing the pipes are set to

**Screenshots**
![20220814073342_1](https://user-images.githubusercontent.com/71046427/184535469-8066b9b2-2def-4884-b648-da4bec23b14a.jpg)
With this specific setup, the mail always ended up in the left unit. we tested multiple configurations of this setup and the mail just went where the pipes sent them.

**Additional context**
If the mail units are intended to use a separate line, distinct from the garbage chute system, I can see several issues.
Firstly, that's a lot of coveted tile space that mappers are going to have to reserve just for this mailing system, adding a whole other network of pipes running through the entire station. Secondly, there is no non-directional Y or T disposal pipe units, meaning these would either be forced direct 1 to 1 mail units, or your stuff will just get routed where the pipes say they do.

**Comment by juliangiebel** [comment]
What did you think how the mailing units are supposed to work? Of course you can put your backpack in.
Did set the routers filters properly?

**Comment by EmoGarbage404** [comment]
nothing about this shows that it isn't working as intended? The issue that you are having either needs to be clarified more or this issue needs to be closed.

**Comment by Cheackraze** [comment]
Well i thought that these werent supposed to be used for large items, about the back pack thing, and the use of the disposal router was not stated or mentioned anywhere. Regardless, I apologize for the post if it is as intended.

**Comment by juliangiebel** [comment]
I will add a sentence to the routers description that tells you to click on it for changing its filter.
