### ISSUE TITLE
Ghost roles no longer group correctly because of dataset names

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#10585]
E.g. carp (123) and carp (124) will create their own groups when they should be in the same group. Ideally this would also apply to stuff like nuclear operatives but that's probably harder without some kind of group override.

**Comment by IProduceWidgets** [comment]
Looks fine now
![image](https://github.com/space-wizards/space-station-14/assets/107586145/0fa972cb-6076-4c41-9a68-52044c8e8fcb)
