### ISSUE TITLE
Make the fuel tank explode if ignited with a welding tool

### ISSUE THREAD

**Issue by AJCM-git** [space-wizards/space-station-14#1060]
I think this is a nice feature to have, and is a good first  PR for begginers

**Comment by Jackw2As** [comment]
Correct me if i'm wrong, but this will require a new component which when a welding tool is being used will trigger the object to be destroyed.

**Comment by PJB3005** [comment]
Yes.

**Comment by ComicIronic** [comment]
You could also extend the `ExplosiveComponent` with this behaviour, since it would apply in general to things which would explode. For example, `ExplosiveComponent` already handles exploding when the entity is destroyed.

**Comment by Jackw2As** [comment]
What I think i'll do is link into the damage system then call an absurd amount of damage when a the componet is activated. I think this system offers a fantastic ability for reusability that other methods just don't(when ever you want something to take damage from interacting with it this component should be able to handle it). Then the damage system should just trigger the explosion. 

I'm just trying to figure out how to let people use YAML to choose which tool they want to use for damage. Right now i'm thinking about using prototype string name. But what if you want multiple objects to cause damage? Could I use an array?

**Comment by PJB3005** [comment]
I can think of only one interaction in SS13 that works like this, and it's the welding tank. Don't overcomplicate it. A dead simple "explodes when hit with welder" component is totally fine.

**Comment by Jackw2As** [comment]
Its not that complicated(I think). What i'm doing is using:

`var entityID = eventArgs.Using.Uid;` to get a reference to the using item id. then i'm comparing it to the YAML id given. If its true I do the damage. damage is checked to make sure it doesn't heal the object then I call the damage system using the ActionSystem.

It should work in theory. I'll test it out. Then i'll try to figure out how to support multiple objects dealing damage at the same time when they are used to interact with it.

**Comment by ShadowCommander** [comment]
So, the thing you need to look at is not `entities`, but `components` such as the `WelderComponent`. You'll probably want to just make a `FuelTankComponent` that handles `InteractUsing` by something with the `ToolQuality.Welding`.

Take a look at how `ToolQuality` is used and maybe see if `DamagableComponent` allows you to just set it to destroyed.

**Comment by PJB3005** [comment]
First, Entity UIDs are assigned at runtime to uniquely identify one object (across the network for example) as a number. They are not something you can use to do an ID comparison.

Secondly, comparing against YAML IDs is not kosher for various reasons (IDs can change when you have, for example, a different spawn preset but identical functionality). You should always compare against components (their data or even just their existence).

**Comment by DrSmugleaf** [comment]
Fixed by #1102
