### ISSUE TITLE
Rods place lattices below you (despite a floor being there)

### ISSUE THREAD

**Issue by Ablankmann** [space-wizards/space-station-14#10619]
## Description

Interacting a set of rods with another object in your hands creates a lattice below you, regardless if there's a tile there.

**Reproduction**

Get yourself some Rods
Take another stackable item (MUST be a stackable item. Steel, Plastic, Solid Plasma, the works.)
Click on other item while having the Rods selected

If done correctly, you should hear a placing sound, signifying you did it correctly. There will now be a gravity-less lattice in the area you did that in.

**Comment by Mervill** [comment]
Can't reproduce on 28cd7dc764d9c5deb2d3312aece4b3ae9198e900
