### ISSUE TITLE
Guns allow you to ignore the lack of gravity

### ISSUE THREAD

**Issue by Trash0077** [space-wizards/space-station-14#1062]
when continuously firing a gun you gain the ability to walk, even if there is no gravity around. This probably has something to do with the fact that the guns change/influence your movement speed whilst they are used.

**Comment by Jackw2As** [comment]
![SS14 Bug reported](https://user-images.githubusercontent.com/15194163/83451449-e08d9180-a44e-11ea-8ab6-252be2be4284.gif)

Its only when  the gun has ammo. I tested both the SMG and the Shotgun. Same results. When firing the gun you are able to use WASD inputs to move around as if you were in space. When the gun doesn't have ammo it has no effect,

**Comment by InquisitivePenguin** [comment]
Oh yikes, this is quite an issue. I'll get on fixing this.

**Comment by SweptWasTaken** [comment]
> 
> 
> Oh yikes, this is quite an issue. I'll get on fixing this.

![flushed](https://user-images.githubusercontent.com/49448379/94898334-e937b800-0480-11eb-9e4c-7b8518f6b9f8.png)

**Comment by ike709** [comment]
Fixed in #2272
