### ISSUE TITLE
Sprites such as toolbelts or crayon boxes aren't showing properly

### ISSUE THREAD

**Issue by jessicamaybe** [space-wizards/space-station-14#10622]
## Description
Something broke this recently, as this used to work 

Sometimes a full box of crayons will show as empty like this, until you open it
closed:
![image](https://user-images.githubusercontent.com/31836813/184726131-e36e7e86-fe98-43df-9dde-14a783b3303e.png)
after open:
![image](https://user-images.githubusercontent.com/31836813/184726260-4326e36f-5ef7-4ef5-be40-2b9c5c4b19be.png)

This also happens to toolbelts, it will show the sprite for a toolbelt without any tools in it until you open it.

**Comment by OctoRocket** [comment]
I would guess that the contents are checked after the sprite is set

**Comment by wrexbe** [comment]
Seems to work.
