### ISSUE TITLE
Nettle soup recipe is broken

### ISSUE THREAD

**Issue by Renlou** [space-wizards/space-station-14#10656]
## Description
So this should be an easy fix but nettle soup is screwed. You cant put a whole egg in microwave cuz it cracks it. So I guess this recipe has to change to instead of a solid type FoodEgg, it requires an Egg reagent of 6u (i believe thats 1 egg)

**Reproduction**
- Attempt to put egg inside microwave
- No egg in microwave 

**Screenshots**
![Screenshot_20220817-191913_Chrome](https://user-images.githubusercontent.com/13793667/185085792-c03f3411-fe0c-423c-b092-8c1591893476.jpg)

**Additional context**
❤️  u contributors and maintainers. This game is helping me through a real bad time irl

**Comment by JustinTrotter** [comment]
@me once this gets merged and I'll update the wiki for the recipe.
