### ISSUE TITLE
One of the female screams is way less loud than the other ones

### ISSUE THREAD

**Issue by Visne** [space-wizards/space-station-14#10669]
Haven't yet tried to figure out which one exactly.

**Comment by Visne** [comment]
In my opinion that scream kinda sucks anyways so in my opinion it can just be removed, but I'm glad to hear opinions.

**Comment by Visne** [comment]
It's `femalescream_3.ogg`:

https://user-images.githubusercontent.com/39844191/185245509-d56d828a-351a-45a3-9775-18d3befc7531.mp4

Who screams like this

**Comment by IProduceWidgets** [comment]
It is still a little quieter to the ear, but uh, I think its fine and freeeeeeeezeeeeeeee time.
