### ISSUE TITLE
Web admin logs overwrites ctrl-F

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#10677]
I want to find something in page and having this default to search is very annoying (and the reason I use find in page is because the search isn't robust enough yet).

**Comment by mirrorcult** [comment]
this should presumably be an issue on ss14.admin

**Comment by juliangiebel** [comment]
I can change it to ctr + shift + f but using the browser search probably won't help you.
Bug pjb about merging my PR for it because I wan't to improve it but I can't because the PR isn't merged yet.
Also, can you tell me how the search isn't robust enough yet if it isn't about it crashing?

**Comment by juliangiebel** [comment]
This is my mockup of how I want to improve the web admin logs

**Comment by metalgearsloth** [comment]
There's a lot of little things but the 2 main ones  are I can't search by round and the date column is cut off so I have no idea if is a time is AM or PM.
