### ISSUE TITLE
Ghost role vending machines have InputMover component enabled

### ISSUE THREAD

**Issue by retequizzle** [space-wizards/space-station-14#10679]
Found randomly during a round when a RoboDrobe was running around screaming that he was magic. Tested it on another vending machine and it appears to have been a default option for them.

Fun fact, can also add this option to pAI again for old school pAI flyin'.

**Comment by Just-a-Unity-Dev** [comment]
Reproduction steps (I was the RoboDrobe):

1. Run the sentient vending machine event
2. Spawn as a sentient vending machine
3. Tell someone to unwrench you
4. Become magic

**Comment by EmoGarbage404** [comment]
this got fixed ages ago
