### ISSUE TITLE
Disposal Conveyer Belts Not Moving Garbage

### ISSUE THREAD

**Issue by 5150Con** [space-wizards/space-station-14#10688]
## Description
I've noticed this issue across all maps for the last few weeks, in that the disposal conveyers will not move items that are sent to them by the disposal network. If a player picks up and drops the trash onto the conveyor, then it will now be moved.

**Reproduction**

1. Load up a map/Join a round
2. Flush some items into disposals
3. Check in the disposal room
4. Activate conveyer
5. Notice that trash doesn't move

OR

1. Join a round
2. Wait 20+ minutes
3. Visit disposal room
4. See the mass of trash that refuses to move

**Screenshots**
![20220818173608_1](https://user-images.githubusercontent.com/104950325/185513396-0e9eda9a-ec75-42e7-90b0-46d2eb9660a1.jpg)
**Additional context**
For the screenshot, the conveyers are on, and the people are having to manually pick up the item and drop it for the conveyor to affect the items.

**Comment by Partmedia** [comment]
I believe this regression was introduced in the most recent conveyors rewrite.

Also note that if you pick up the trash and put it back down on the conveyor, it will move again.

**Comment by metalgearsloth** [comment]
Disposals and/or containers should be waking bodies when it dumps them.

**Comment by 5150Con** [comment]
I've still seen the same issue in rounds yesterday, so I will be leaving this up still.
