### ISSUE TITLE
The eye damage filter makes me want to die

### ISSUE THREAD

**Issue by EmoGarbage404** [space-wizards/space-station-14#10717]
## Description

the current filter applies a permanent blur to your screen, which is unbelievably ugly.

It also seems to be permanent unless healed with specific chems, which makes it agonizing if there's no medical.

Welding already blinds you when it's active. This just seems like an unnecessary kick in the balls that makes the game look like ass.
**Screenshots**

![image](https://user-images.githubusercontent.com/98561806/185726668-fab55880-be1a-424f-b745-e92cdb0de863.png)

**Comment by mirrorcult** [comment]
i mean yeah. you're not supposed to want eye damage

**Comment by EmoGarbage404** [comment]
> i mean yeah. you're not supposed to want eye damage

the eye damage doesn't actually disadvantage you mechanically. It could instead be a vignette, a shadow around the screen, or a dim transparent layer on top of it. This serves no purpose except looking like ass.

**Comment by metalgearsloth** [comment]
The blur causes bad eyestrain and shouldn't just be permanently applied, it either needs to be timed or changed entirely.

**Comment by Visne** [comment]
Maybe make the vignette permanent, just like how you get permanent eye damage in real life, and the vignette temporary (less than 30 seconds) right after you sustain eye damage, to make it extra clear to the player that what they just did is really bad for their eyes.

**Comment by Elijahrane** [comment]
> > i mean yeah. you're not supposed to want eye damage
> the eye damage doesn't actually disadvantage you mechanically. It could instead be a vignette, a shadow around the screen, or a dim transparent layer on top of it. This serves no purpose except looking like ass.

must be pretty effective if it causes such strong reactions

**Comment by EmoGarbage404** [comment]
Please dont comment on github discussions if you're only gonna bring up bad-faith arguments that dont mean anything.

The effectiveness of it doesnt actually hinder my character in any way, it juet hurts my eyes.

If i want to feel empathy with my character, then how about you shoot me in the head when i die in game. 

Sometimes those additional materials for preventing it aren't available, especially when you're not playing upstream or at the beginning of a round. I dont know why that means i should get eye strain irl.

**Comment by Elijahrane** [comment]
> The effectiveness of it doesnt actually hinder my character in any way, it juet hurts my eyes.

you called it 'agonizing' and you're not hindered at all, okay

**Comment by EmoGarbage404** [comment]
Theres a difference between a mechanical hinderance to my character and actually causing me discomfort while playing. A flashbang makes my character unable to move and restricts my vision of the screen.

A permanent blur until healed doesnt affect me mechanically, but rather just causes me irl discomfort. I don't know how that's hard for you to understand

> okay

Lose the attitude.

**Comment by metalgearsloth** [comment]
Convo isn't productive atm.
