### ISSUE TITLE
Filter & Mixer sprites have offset pipes.

### ISSUE THREAD

**Issue by ElectroJr** [space-wizards/space-station-14#10718]
![unknown](https://user-images.githubusercontent.com/60421075/185726619-72fc4a3d-87e2-4560-bf5f-123e897fa56e.png)
Gotta love 5-pixel wide pipes on 32x32 sprites. If someone wants to fix this, make sure to test the sprites for all rotations & when looking at rotated grids (relative to the player's eye).

**Comment by UbaserB** [comment]
Mind if you clarify this?
