### ISSUE TITLE
Finishing a smoke leaves the butt in your mouth slot

### ISSUE THREAD

**Issue by PrPleGoo** [space-wizards/space-station-14#10725]
## Description
You should drop the butt.

**Reproduction**
Smoke a cig until it is a butt.
It remains in your mouth

**Comment by Visne** [comment]
In real life you use your fingers to take it out of your mouth right? Or do you spit it out

**Comment by tomasalves8** [comment]
Yeah I believe this is not an issue.

**Comment by EmoGarbage404** [comment]
this feels like one of those things that's super minor or whatever. I guess you could add like a sidebar action for spitting it out if you really wanted that?

**Comment by Visne** [comment]
> I guess you could add like a sidebar action for spitting it out if you really wanted that?

Only if you can come up with other uses of spitting.

Closing this for now because it doesn't seem like an issue to me. Feel free to add more comments though.

**Comment by PrPleGoo** [comment]
In real life you wouldn't keep the cig in your mouth from start to finish.

**Comment by Visne** [comment]
Then take it out with your hands, you can already do that.

**Comment by ike709** [comment]
In SS13 you automatically drop it to the ground. IMO we should replicate it, gives the janitor more work
