### ISSUE TITLE
Can't fit wires into toolbelts

### ISSUE THREAD

**Issue by PrPleGoo** [space-wizards/space-station-14#10720]
## Description
A toolbelt should be an engineer's bread and butter.
Right now it has room to fit all most tools.
Except t-ray and atmos scanners, and wires.

**Reproduction**
Grab a default filled toolbelt and try to add any of the 3 mentioned items.

**Comment by Visne** [comment]
I agree with the scanners, because they are tools, but wires are not tools but materials.

**Comment by lzk228** [comment]
can 

https://github.com/space-wizards/space-station-14/assets/124214523/bf694b63-7cde-415a-aaaf-a644c63d7613
