### ISSUE TITLE
Buckling doesn't properly detach when outside of PVS?

### ISSUE THREAD

**Issue by ElectroJr** [space-wizards/space-station-14#10746]
Basically, if you buckle yourself to a chair, teleport far away, and then teleport back to the general area where the chair is without having moved, the client shows you as being back on the chair? But this doesn't seem to happen when you only teleport short distances?

I'm not sure what the cause is. The title is somewhat of a guess, but the issue can be reliably reproduced. This seems to have nothing to do with recent PVS changes, as this can also be reproduced before those were merged. 

Example video:

https://user-images.githubusercontent.com/60421075/185775955-14c1fe24-26a1-48b9-b0c8-c36d1c53d628.mp4

**Comment by metalgearsloth** [comment]
Do you even get re-parented on tp?

**Comment by ElectroJr** [comment]
> Do you even get re-parented on tp?

Both client & server transform parent changes, the buckle alert disappears & the unbuckle sound plays.
