### ISSUE TITLE
Duplicate player mounted on vehicle

### ISSUE THREAD

**Issue by estacaoespacialpirata** [space-wizards/space-station-14#10745]
## Description
When you teleport a player mounted on a vehicle, the body got duplicated.

**Reproduction**
Put a player on a vehicle (Janicart), the player was offline, then i teleported him using admin menu, it ended up with two bodys, one where i teleported with all the itens, and another on the same place as before, but naked.

**Screenshots**
![image](https://user-images.githubusercontent.com/110949078/185772155-e65421b0-db3c-43b1-a040-7a62d1aaba42.png)

**Comment by rbertoche** [comment]
that one was not clientside, everyone was seeing them like that

**Comment by ElectroJr** [comment]
Was the naked duplicate still there after disconnecting and reconnecting? Was it an actual duplicate entity that could be interacted with?

space-wizards/RobustToolbox/pull/3155 fixes a separate bug related to teleporting, but that should only result in players seeing themselves as suddenly naked, and should definitely not create a duplicate entity.
