### ISSUE TITLE
Suggestion: Tone down space medipen's offensive potential

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#10752]
## Description
Tone down space medipen's offensive potential. Right now, it is roundstart gear of everyone that is rather strong weapon, provided you loot one or more spacepens from SSDs/morgue.

There is no easy counter. Will you vomit via Ipecac mid-combat or will you pop Dylovene pill, if you had either of those on you for _some_ reason? Introducing chem purging chem that is not awful Ipecac as per issue #10042 might provide much-wanted counter to this and poison hyposprays (which are similar degree of broken, but are antag/CMO only).

My PR #9926 did not introduce the issue, it merely swapped tiny bit of poisoning with burn while making non-OD much safer.

**Reproduction**
- Collect spacepens
- Stab stuff

**Screenshots**
8 total damage (burn part is subject to RNG) with one pen, 73.5 total damage with two pens, death with three:
![barozine_OD_stuff](https://user-images.githubusercontent.com/108953437/185785613-738c9fba-031c-4aa5-b3b1-eea3bfb98d34.png)

**Additional context**
Budget hypopen for absolutely everyone who is ready to scavenge a bit is bad.
Maybe let Epinephrine (another roundstart pen on everyone) hard-counter Barozine's harmful effects?

**Comment by UbaserB** [comment]
Space medipen got removed
