### ISSUE TITLE
Unbuckling causes a phantom body to appear

### ISSUE THREAD

**Issue by martin69420** [space-wizards/space-station-14#10750]
## Description
Weird phantom body appears when walking diagonally after getting up from bed

**Reproduction**
Get buckled to a bed
Strip
Get up
Put clothes on
You will have a phantom body attached to you when you move diagonally

**Screenshots**
![man diagonal error](https://user-images.githubusercontent.com/63034378/185781333-bed66da6-b55a-4315-a850-24d7ccc06284.PNG)

**Comment by metalgearsloth** [comment]
Dupe https://github.com/space-wizards/space-station-14/issues/10746
Dupe https://github.com/space-wizards/space-station-14/issues/10745
