### ISSUE TITLE
Revenants sometime respawn out in deep space.

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#10776]
## Description
Sometimes when a revenant is killed they respawn out in deep space on a different map level.

**Reproduction**
Had a revenant in an extended round die and respawn out in space, not sure how to replicate.

**Additional context**
This was during a very long extended round. Station was moved quite a bit away from its starting location. not sure if this was the cause.

**Comment by EmoGarbage404** [comment]
pretty sure this is due to how polymorphing doesn't dispose of the old entity when destroyed. Will require some changes to how that stuff works.
