### ISSUE TITLE
Cargo tech and QM icons are swapped

### ISSUE THREAD

**Issue by NicoSGF64** [space-wizards/space-station-14#10779]
Whoops

**Comment by EmoGarbage404** [comment]
Could you elaborate a bit more?

**Comment by NicoSGF64** [comment]
> Could you elaborate a bit more?

In most ss13 servers (for example [/TG/ station](https://tgstation13.org/wiki/HUD#Jobs)), the QM's icon is the current cargo tech icon and vice-versa. Swapping them would make sense since all of the head's icons are bordered and, considering the QM is a head now, the QM's icon would align with the other head's design.

How'd it look:
![tmp1](https://user-images.githubusercontent.com/74880554/186143627-af12594d-88ff-4b19-a1f7-2a8cd43e7ce5.png)
Head's icons for reference:
![tmp2](https://user-images.githubusercontent.com/74880554/186141781-6a487ccc-6529-4f7f-af4e-d9572411a79f.png)

**Comment by EmoGarbage404** [comment]
Seems like a quick fix. Ill have something up for this later today.
