### ISSUE TITLE
Add volume sliders to options menu.

### ISSUE THREAD

**Issue by ghost** [space-wizards/space-station-14#1077]
![image](https://user-images.githubusercontent.com/58238103/83847907-a9c7ad80-a6d2-11ea-83a4-46afa0e2232a.png)

Something like this would drastically improve QoL. I have a hard time testing things smoothly while having to open my OS volume mixer and make adjustments. _Which still sometimes results in game audio being too quiet (sneaker footsteps for example)._
Probably should group up buses or something and have sliders for them.

I believe **Minecraft** is a fair example of how it should work. (Not the layout specifically.)
![image](https://user-images.githubusercontent.com/58238103/83848256-2b1f4000-a6d3-11ea-85ac-65d0d9be6711.png)

**Comment by Akpotohor12** [comment]
Wow amazing content thanks bro really love I have learnt something new today

**Comment by metalgearsloth** [comment]
Fixed in https://github.com/space-wizards/space-station-14/pull/2642
