### ISSUE TITLE
Salvage hazard: walls / floors are lava

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#10790]
Not actually lava but "while touching wall take ticking damage". I think having people be careful with their movement, especially when weightless, would be an interesting mechanic.

This would also apply to floor hazards too (e.g. broken APC causes certain tiles nearby to be electrified).

**Comment by Peptide90** [comment]
Good feature for things like hot pipes in maints too to make people think twice about hugging walls in the dark.
