### ISSUE TITLE
Ghost Warping to "nuke disk" will parent you to mob holding the disk?

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#10804]
## Description
Ghost Warping to "nuke disk" will parent you to mob holding the disk? You still can move, but you will move in sync with person.

**Reproduction**
- Make belt thing
- Hold disk
- `aghost`
- Move around as ghost
- Perhaps smite mob with noclip+spacing thing

**Screenshots**
![parented_to_mob](https://user-images.githubusercontent.com/108953437/186298512-2c1b5402-2453-48aa-b295-43f870194548.png)

**Comment by Just-a-Unity-Dev** [comment]
i love parenting

**Comment by lzk228** [comment]
i think it's fixed
