### ISSUE TITLE
Dying and then exiting out of crit (cloned, healed or similar) makes a vignette appear and it doesn't disappear

### ISSUE THREAD

**Issue by ikamuse** [space-wizards/space-station-14#10805]
**Reproduction**
Enter crit and wait a bit, being healed out, cloned or being a ghost makes the vignette appear and it never disappears unless you rejoin. If you die quick enough and ghost then it doesn't appear

**Screenshots**
![lpMAT60CWx](https://user-images.githubusercontent.com/104636418/186298471-9942aca1-ba06-40ac-9855-a4cc708778ec.png)
there is no broken lights, the vigette makes it look dark

**Additional context**
I have compatibility mode on and  more than 190 ping and i think maybe the ping plays a role on it somehow

**Comment by metalgearsloth** [comment]
Dupe https://github.com/space-wizards/space-station-14/issues/10329
