### ISSUE TITLE
Until all free hands are exhausted, "Handcuffed" alert will not show up and all hands remain usable

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#10814]
## Description
Until all free hands are exhausted, "Handcuffed" alert will not show up and all hands will remain usable.

**Reproduction**
- `addhand` self into four-armed mutant
- Cuff self
- Fail to notice difference beside cuffs sprite

**Screenshots**
![4-armed_mutant_woes](https://user-images.githubusercontent.com/108953437/186325168-a9a773da-aafb-4f73-86fe-bd0fdf1c0b58.png)

**Comment by ElectroJr** [comment]
This probably gets fixed by #9768, but that is currently waiting on UI refactor.
