### ISSUE TITLE
Kudzu may slow you down excessively

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#10811]
## Description
Kudzu may slow you down excessively. No idea what causes it. In my two reproduction attempts resulting modifier was the same.

**Reproduction**
- Unleash the plant
- Touch the plant repeatedly
- Experience _extreme_ slowdown that will come suddenly at random

**Screenshots**
Reproduction attempt 1:
![kudzu_slowdown_packed](https://user-images.githubusercontent.com/108953437/186312309-741b082b-6a49-4e55-b216-84ede9409960.png)
Reproduction attempt 2:
![kudzu_slowdown_saltern](https://user-images.githubusercontent.com/108953437/186312323-4d6bae1a-fda7-485d-985d-ed7da139f268.png)

**Additional context**
Had this also happen to me some time ago on Lizard, I was extremely slow and some admin gave me gibs-on-contact-with-wall tier speed modifier to counterbalance slowdown from bug.

**Comment by ElectroJr** [comment]
I have no idea what caused the extreme slowdown, I suspect it was probably just some other slowdown stacking on top of it. The bug where the kudzu slowdown doesn't go away should be fixed by #10854

**Comment by IProduceWidgets** [comment]
I think Electro managed to solve this one. When I try it live the slowdown is correctly a *.2 modifier, which slows me by the correct amount.
