### ISSUE TITLE
"Ready Up" lobby button state is not communicated clearly

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#10829]
## Description
"Ready Up" lobby button state is not communicated clearly. I saw at least two people needing clarification on "green - readied up, grey - not readied up".

**Reproduction**
- Click the button
- Observe nothing happening beside color change

**Screenshots**
That thing, do I click it now to ready up?..
![green_ready_up](https://user-images.githubusercontent.com/108953437/186458152-013f0e6d-093e-40d3-8ba7-0f1844078412.png)

**Additional context**
Make button text change upon toggle and have text say somewhere something like:
- "Will remain in lobby upon round start, click Ready Up to change"
- "Will join game upon round start, click Cancel Ready to remain in lobby"

**Comment by Visne** [comment]
This form of on/off switch is used in more parts of the game, so it would all have to be reworked. Personally though it seems extremely clear what green/blue means (green is basically the universal color for yes/go), so I would need to have more evidence before someone puts in all the effort.

**Comment by ShadowCommander** [comment]
I think a text change "Not Ready" and "Ready" would probably clear it up.

**Comment by Visne** [comment]
And then you have the issue of not knowing whether it's currently "Not Ready" or clicking will make it "Not Ready".

**Comment by moonheart08** [comment]
A checkbox would look ass.

**Comment by EmoGarbage404** [comment]
i feel like just having it change to "ready" and turning green would be clear enough. Anything more verbose or complicated than that would probably conflict with the styling layout that's going on over there.
