### ISSUE TITLE
Suggestion: Introduce /succumb command and/or alert you can use to give up on life in crit

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#10835]
## Description
Introduce `/succumb` command and/or alert you can use to give up on life in crit. This would bandaid #9651. Would free player from dealing with logic present in `Content.Server/GameTicking/GameTicker.GamePreset.cs` (line 171 and below) when determining when it's safe to `/ghost`.

**Comment by keronshb** [comment]
There's both /suicide and /ghost to handle this, I'd imagine.

**Comment by EmoGarbage404** [comment]
/suicide and /ghost literally fill this exact purpose. The only thing worth implementing would be a sidebar action that just kills the player.

**Comment by Just-a-Unity-Dev** [comment]
> /suicide and /ghost literally fill this exact purpose. The only thing worth implementing would be a sidebar action that just kills the player.

And possibly a "last words" thing that allows you to whisper your last words

**Comment by Just-a-Unity-Dev** [comment]
I don't understand why `/suicide` forfeits revival in crit, but not `/ghost`??? Shouldn't those do the same thing?

**Comment by Just-a-Unity-Dev** [comment]
I'm willing to code this when I got the time

**Comment by thekaio123** [comment]
> /suicide and /ghost literally fill this exact purpose. The only thing worth implementing would be a sidebar action that just kills the player.

Its better for players who have played SS13 or to players that dont know how to use the console, adding this under the crit warning.
Its faster and useful (and i imagine, not so hard to code), it would also have the last words feature, which is good to have.
