### ISSUE TITLE
Blanked out job on agent ID will introduce extra space into mob's visible name, provided name is blank too

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#10831]
## Description
Blanked out job on agent ID will introduce extra space into mob's visible name, provided name is blank too.

**Reproduction**
- Blank out both name and job on your agent ID
- Conceal face
- Wear ID

**Screenshots**
Blank name, job provided:
![agent_ID_with_job](https://user-images.githubusercontent.com/108953437/186463683-0c7de31c-9107-496d-936b-cea485fccf04.png)
Blank name, job blanked (watch two spaces):
![agent_ID_with_blank_job](https://user-images.githubusercontent.com/108953437/186463849-a5424837-94d2-4233-8343-9f70d3770d17.png)
No ID worn, for comparison:
![no_agent_ID](https://user-images.githubusercontent.com/108953437/186463903-852c794c-e667-4230-9c0f-a3d4d99bcaaa.png)

**Comment by EmoGarbage404** [comment]
![image](https://user-images.githubusercontent.com/98561806/186548970-a3d751bf-f219-4af9-8f14-0048f7c099fa.png)
it doesn't sanitize whitespace either
