### ISSUE TITLE
Spear wielding messages are visible to everyone and say that you, observer, wield the spear

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#10833]
## Description
Spear wielding messages are visible to everyone and say that you, observer, wield the spear. Similar to issue #10403.

**Reproduction**
- Watch someone play with spear

**Screenshots**
I am pAI at center of image in bag of secoff:
![spear_wield_messages](https://user-images.githubusercontent.com/108953437/186468692-2aee3e30-7ebd-4d9d-a47d-339987b58fbe.png)

**Comment by EmoGarbage404** [comment]
The message being visible isnt an issue. Its moreso the popup being wrong.

**Comment by EmoGarbage404** [comment]
Not like it particularly matters tbh. Just some extra clarification on the action.
