### ISSUE TITLE
Bullets can phase through directional windows

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#10843]
## Description
Bullets can phase through directional windows. Might be merely a dupe of #10394. Unable to reproduce on 60 tick localhost.

**Reproduction**
- Laggy server gaming
- Make yourself shooting range with directional windows
- Notice bullets phasing through target

**Screenshots**
Reproduced live:
![bullets_vs_directional_windows](https://user-images.githubusercontent.com/108953437/186489267-627722a9-cb9a-4ddf-9af9-414eb797d2e9.png)

**Comment by ShadowCommander** [comment]
@metalgearsloth Is there anything that can be done about this?
