### ISSUE TITLE
Pillar has light tube inside wall in maint above arcade room

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#10846]
## Description
Pillar has light tube inside wall in maint above arcade room. TileRef 5,37. Duh.

**Reproduction**
- Load NSS Pillar
- Go to maint above arcade room

**Screenshots**
![pillar_light_inside_wall](https://user-images.githubusercontent.com/108953437/186500190-6962c2c2-a768-44e9-b998-0b5718d0ea80.png)

**Comment by EmoGarbage404** [comment]
yet another pillar bug that will just be fixed when the update comes out.

**Comment by EmoGarbage404** [comment]
the beginning
