### ISSUE TITLE
Cartridges render below protolathe printing them and below vents and scrubbers

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#10842]
## Description
Cartridges render below protolathe printing them and below vents and scrubbers. They should render on top of lathe printing them, vents and other stuff like tables, but below important stuff like mobs and those upcoming turrets producing them.

**Reproduction**
- Recognize that ammo is renewable through usage of protolathe
- Be annoyed that you have to use context menu to fetch produced cartridges
- Lose your newly made ammo by placing it on vent

**Screenshots**
![cartridges_below_lathe](https://user-images.githubusercontent.com/108953437/186487858-6693eba3-c000-45a3-ae79-4182ceee4444.png)

**Additional context**
Introduced by PR #10657.

**Comment by ShiftyRail** [comment]
Okay so I'm trying to fix this by making so you can control the `drawDepth` at which you want your spawned item to be drawn at, but I'm hitting a wall. All the variables at the `SharedSpriteState` are readonly. So how do you actually set the drawing depth of an item at runtime? Thanks.

**Comment by ElectroJr** [comment]
IMO, the change in #10657 should be reverted and replaced with client-side code that changes the drawdepth based on whether the cartridge has been spent.

`AmmoVisuals.Spent` appearance data already exists, so it would just involve modifying the client's `GunSystem.SpentAmmo.cs`, by either:
- Changing the event subscription to use `CartridgeAmmoComponent` and always update the draw depth to some constant number
- Adding a draw-depth field to `SpentAmmoVisualsComponent` and making sure that any problematic / spammable cartridges have that component.

**Comment by IProduceWidgets** [comment]
The main issue seems resolved for now.

![image](https://github.com/space-wizards/space-station-14/assets/107586145/f800a6b3-e908-4eb5-9f0d-9f2823dbbd9e)
