### ISSUE TITLE
NanoMed (VendingMachineWallMedical) cannot be used, as it's usually always obstructed by wall it's mounted on

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#10841]
## Description
NanoMed (VendingMachineWallMedical) cannot be used, as it's usually always obstructed by wall it's mounted on.

**Reproduction**
- Check out NanoMed vending machines of different maps
- Try to remove walls around them (but not one they are supposedly mounted on)
- Notice your inability to access the machine

**Screenshots**
Evac shuttle:
![nanomed_evac](https://user-images.githubusercontent.com/108953437/186486045-71ec28af-12e7-4784-ba71-3db5215e1bac.png)
Packed:
![nanomed_packed](https://user-images.githubusercontent.com/108953437/186486085-8d36fd1b-093c-4a89-8167-f2ab7d6fd4c9.png)
Box:
![nanomed_box](https://user-images.githubusercontent.com/108953437/186486130-6e5a36fe-dd66-48dd-a5d9-d7afe2e2b438.png)
Marathon (also note wonky rendering of wall blocking line of sight, related to #10830??):
![nanomed_marathon](https://user-images.githubusercontent.com/108953437/186486159-c0f31a9a-6d64-4ac5-9564-9a88d2ab029c.png)

**Comment by EmoGarbage404** [comment]
Is it not directional, being a wallmount?
