### ISSUE TITLE
"names_death_commando" nameSet is way too distinct from standard Operative/Agent/Commander name formula for NukeOps

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#10845]
## Description
"names_death_commando" nameSet is way too distinct from standard Operative/Agent/Commander name formula for NukeOps. Those reinforcement teleporter guys being prime material for stealthops - intended?

**Reproduction**
- Take reinforcement teleporter role
- Check out your name
- Evaluate your chances to blend in with normal crew, speech included

**Screenshots**
Why would you valid this guy?
![nukeop_reinforcement](https://user-images.githubusercontent.com/108953437/186496165-9b48b35f-7f4a-4bc7-987e-c221b2ca2429.png)

**Comment by EmoGarbage404** [comment]
I dont really see what the issue is? Theyre not even limited to nuke Ops, normal traitors can have them to. They just seem to have normal names.

**Comment by EmoGarbage404** [comment]
It just seems like a pretty fine stealth ops thing at least. Idk if there's really much of an issue in general.

**Comment by IProduceWidgets** [comment]
I'm going to close since this seems more like a niche balance thing that could probably just do with more discussion in a place where it will get more attention post-freeze.
