### ISSUE TITLE
Something caused items show up as attached to and outside their container

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#10849]
## Description
Something caused items inside duffel bag show up as attached and outside. No idea how to reproduce. Might involve bad network. Attempt to pick up item makes it "disappear" (and in reality it remains where they are actually are).

**Reproduction**
- No idea!

**Screenshots**
My pills got outside of duffel bag. Visible in context menu and to another player:
![duffel_with_pills_stuck_to_it](https://user-images.githubusercontent.com/108953437/186502766-6818a316-9ff3-4531-9b77-3f1a9e3ef249.png)
Other game, I get to see ChemMaster guts:
![chemmaster_guts](https://user-images.githubusercontent.com/108953437/186504177-0867f0e9-700c-4421-b3e8-4da22cbadf3a.png)

**Comment by ElectroJr** [comment]
How recent was this?

**Comment by ElectroJr** [comment]
Some container related bugs were fixed ~2 days ago, so if this was sometime in the last week I'm just gonna hope that this happened before then. If it is still occurring, reopen the issue.
