### ISSUE TITLE
Suggestion: Eliminate "O2" from "Toggle internals" alert

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#10851]
## Description
Eliminate "O2" from "Toggle internals" alert. It is not representative of actual gas you are breathing, and if you are slimeperson, you don't even want to breathe O2. Minor issue.

**Screenshots**
Slimeperson breathing nitrogen:
![nitrogen_o2_nitpick](https://user-images.githubusercontent.com/108953437/186507811-9b7d2f30-d285-4d35-84c9-770cb8012da7.png)

**Comment by EmoGarbage404** [comment]
I feel like the O2 generally just helps clarify to players that the tank depicted contains something they breathe. Even if it's not technically accurate in every single way, it helps convey the message.
