### ISSUE TITLE
High value items can be deleted from map using medibot crafting

### ISSUE THREAD

**Issue by dan6798** [space-wizards/space-station-14#10852]
## Description
By putting items inside a medkit and then crafting a medibot, you can delete them from existence

**Reproduction**
Get a health analyzer, borg arm, medkit, and proximity sensor. Put item of value inside medkit and craft medibot.

**Screenshots**

**Additional context**
Maybe have a way for high-value items to respawn or have admins spawn new ones in after they get deleted.

**Comment by dan6798** [comment]
I'd like to add this includes the nuclear disc.

**Comment by Elijahrane** [comment]
> I'd like to add this includes the nuclear disc.

There's dozens of ways to delete the nuclear disk, it needs a respawning component

**Comment by ShadowCommander** [comment]
To solve this, add an IGraphCondition that the container(medkit) storage is empty.

**Comment by ShadowCommander** [comment]
Actually, ContainerEmpty is a construction graph condition already. Just add it to the medibot recipe.

**Comment by Mervill** [comment]
This is actually a bigger problem. `HandleStartItemConstruction` (when you click 'craft') does not respect `IGraphCondition`'s at all. Second, the `ContainerEmpty` and the other graph conditions assume a single target entity. That works for where `IGraphCondition` is used currently. At the instant of crafting however, there's no target entity yet. We need a new kind of condition that can itself check for conditions on items inside the `item_construction` container.

**Comment by Zumorica** [comment]
> This is actually a bigger problem. `HandleStartItemConstruction` (when you click 'craft') does not respect `IGraphCondition`s at all. Second, `ContainerEmpty` and the other graph conditions assume a single target entity. That works for where `IGraphCondition` is used currently. At the instant of crafting however, there's no target entity yet. We need a new kind of condition that can itself check for conditions on items inside the `item_construction` container.

This is **intended**. Crafting/Construction recipes from the menu have their own conditions system. Use that instead.

**Comment by Mervill** [comment]
Since `HandleStartItemConstruction` evaluates the `IConstructionCondition` before `Construct`, it dosen't have knowledge of the specific ingredients to be used in the crafting. I think it might be better to just cause _all_ containers used in crafting to spill their contents before being consumed by the recipe.

**Comment by Partmedia** [comment]
Fixed by https://github.com/space-wizards/space-station-14/pull/18564, thanks!
