### ISSUE TITLE
Revenants get the teleporting ghost bug if they respawn when their ectoplasm is in a container on a different player

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#10865]
## Description
Revenants will get that ghost teleporting / tethered to a player bug if they respawn while that player is holding their ectoplasm inside their bag or in their hands or inventory.

**Reproduction**
1. Kill a revenant.
2. Pick up their ectoplasm and put it in your bag.
3. wait for the revenant to respawn.

**Screenshots**

![revant teleporting bug1](https://user-images.githubusercontent.com/106507028/186579538-2d60e4e2-8d92-4a93-b9de-6ad13e558d89.png)

**Comment by ShadowCommander** [comment]
For whoever works on this, take a look at `AttachToGridOrMap()` for when the revenant respawns.

**Comment by NkoKirkto** [comment]
How do you respawn as Revenant im trying to replicate it but dont know how becaus how the fuck should you respawn?

**Comment by ShadowCommander** [comment]
The respawning from ectoplasm state was removed, so this is no longer relevant.
