### ISSUE TITLE
Opening 2 EUIs on the same tick makes client tests fail

### ISSUE THREAD

**Issue by Elijahrane** [space-wizards/space-station-14#10879]
## Description

C.Cl/EUIManager.cs
![image](https://user-images.githubusercontent.com/60792108/186972484-3e6c4c25-8483-4159-83ef-5ec7f00faee8.png)
Here's the problematic function.
[message.txt](https://github.com/space-wizards/space-station-14/files/9435746/message.txt)
As you can see in this trace, it is trying to add the key '1' twice for some reason. (I added a new EUI, and it's fighting with an already existing EUI)

How does it assign the ID 1? 
C.S/EuiManager.cs
![image](https://cdn.discordapp.com/attachments/560845886263918612/1012794424696262739/unknown.png)
It just increments by 1.

I was able to make a quick bandaid patch, which seems to have not broken anything in game, but it looks kind of shitty and would possibly fail again if 3 euis opened on the same tick by doing this
![image](https://cdn.discordapp.com/attachments/560845886263918612/1012795791758336020/unknown.png)

**Comment by wrexbe** [comment]
I see two things that might cause this:
1. I don't see EUIManager cleaning itself up after a disconnect.
2. EUIManager doesn't seem to have any tolerance for being told to open the same window twice.

**Comment by wrexbe** [comment]
Here is a little test I made that shows EUIManager not cleaning up correctly.
```
using System.Linq;
using System.Threading.Tasks;
using Content.Server.Administration.UI;
using Content.Server.EUI;
using NUnit.Framework;
using Robust.Server.Player;
using Robust.Shared.IoC;

namespace Content.IntegrationTests.Tests.Utility;

public sealed class TestTest
{
    [Test]
    public async Task Test()
    {
        for (int i = 0; i < 2; i++)
        {
            await using var pairTracker = await PoolManager.GetServerClient(new PoolSettings{Dirty = true});
            var server = pairTracker.Pair.Server;

            var sPlayerManager = server.ResolveDependency<IPlayerManager>();

            await server.WaitAssertion(async () =>
            {
                var clientSession = sPlayerManager.ServerSessions.Single();
                var eui = IoCManager.Resolve<EuiManager>();
                var ui = new AdminAnnounceEui();
                eui.OpenEui(ui, clientSession);
            });
            await pairTracker.CleanReturnAsync();
        }
    }
}

```
