### ISSUE TITLE
Having a dead mouse in inventory slots causes issues.

### ISSUE THREAD

**Issue by retequizzle** [space-wizards/space-station-14#10899]
If it dies on your head, your movement is slowed and prediction gets fucked. Steps to repro, put live mouse on head, let it die. Enjoy cosplaying as an old man.

If it dies in pockets, that jumpsuit pocket becomes unusable semi-permanently. Steps to repro, put live mouse in pocket, let it die.

In both cases, the player is unable to remove the item from their inventory slot themselves and they need to be stripped in order to properly remove it/gain access to that slot again. May just be worth making it so you can't put mice into inventory slots and limiting them to containers only, such as backpacks or toolboxes.

**Comment by biometricPsychography** [comment]
Oh, this is why I was slowed as the habitual janitorial knight.
