### ISSUE TITLE
Make other creatures (like carps and animals) cremable

### ISSUE THREAD

**Issue by thekaio123** [space-wizards/space-station-14#10912]
They cant be cremated, making them occupate morgues or leaving their bodies in the disposal, creating miasma along the way.
Making them cremable will solve this annoying issue

**Comment by Elijahrane** [comment]
i dunno why you reopned it it's doubly redundant now that biomass is in

**Comment by Elijahrane** [comment]
![image](https://user-images.githubusercontent.com/60792108/187509333-39e943d1-f33b-4b3a-8b5e-2f5047539f27.png)
![image](https://user-images.githubusercontent.com/60792108/187509364-17d47a24-b03f-4370-88e5-1de441dc0445.png)
![image](https://user-images.githubusercontent.com/60792108/187509411-2baa10d3-30ca-4b45-9156-3c4591235172.png)
![image](https://user-images.githubusercontent.com/60792108/187509435-1ccf9c9d-51e4-4117-b167-fedf09197384.png)

**Comment by EmoGarbage404** [comment]
This seems to be unable to be reproduced?

**Comment by EmoGarbage404** [comment]
This seems to be unable to be reproduced?

**Comment by thekaio123** [comment]
looks that it fixed, probably after the biomass update, im closing this since it was in fact fixed, even if not directly (and now its rather obsolete after the biomass was introduced).
