### ISSUE TITLE
desoxyephedrine can't be created

### ISSUE THREAD

**Issue by GoodWheatley** [space-wizards/space-station-14#10921]
## Description
The wiki recipe for desoxyephedrine does not actually create desoxyephedrine in game, which either means the wiki is outdated or the chemical is unmixable.

**Reproduction**
1. Attempt to make desoxyephedrine according to the wiki
2. Fail
3. Cry in a corner over not being able to create the funny speed drug

**Comment by EmoGarbage404** [comment]
pretty sure it just needs to be heated up. idk if the wiki displays min reactions temps.

**Comment by GoodWheatley** [comment]
> pretty sure it just needs to be heated up. idk if the wiki displays min reactions temps.

the chemist I was working with tried microwaving it , didn't work.

**Comment by EmoGarbage404** [comment]
how long? it's like 30 seconds total iirc

**Comment by moonheart08** [comment]
It works just fine, heat it up.
