### ISSUE TITLE
Nukie planet parallax brokey

### ISSUE THREAD

**Issue by Just-a-Unity-Dev** [space-wizards/space-station-14#10946]
## Description

what

**Reproduction**
1. roll nukie
2. wtf spess???

**Screenshots**

![image](https://user-images.githubusercontent.com/67359748/187627027-12f04ff0-8922-47f8-a263-b502aae62ef2.png)

**Comment by metalgearsloth** [comment]
Gonna need more info

**Comment by Just-a-Unity-Dev** [comment]
> Gonna need more info

if you give me a few minutes i can get you the round number

**Comment by Just-a-Unity-Dev** [comment]
oh my god watchdog decided to update now
