### ISSUE TITLE
Hot ramen and desoxyephedrine are impossible to make

### ISSUE THREAD

**Issue by EeveeTea** [space-wizards/space-station-14#10971]
Here's another one for the microwave code: Dry ramen and water have to reach a minimum temperature of 323.15 (about 10-20 seconds in the past) to react and become hot ramen. Desoxyephedrine (meth) has to reach 370 (about 1:30-2 minutes). Both were normally able to reach those temperatures with the help of the microwave, but some recent update broke those effects.

Easy test:
Grab some ramen from a vending machine and add 10u of water. Stick it in the microwave for 30 seconds. A chemical reaction sound would normally play after it finishes the heating cycle. It usually takes about 10-20 seconds but I'm not completely sure about the time anymore, so I'm saying 30 just to be safe. Maybe someone can add the amount of time to the description while fixing it.

Possibly related to #8143 and #10921

**Comment by mirrorcult** [comment]
@EmoGarbage404 refactored microwaves entirely so probably related

**Comment by EmoGarbage404** [comment]
looking into this rn.
