### ISSUE TITLE
Items that can't be put in the trash bag

### ISSUE THREAD

**Issue by thekaio123** [space-wizards/space-station-14#10988]
There is a massive list items that can't be put in the trash bag, some of them are small common trash found around vending machines, others are empty drinks, organs/body parts, bottles, small packets, pills, kitchen trash and much much more.
it will need a considerable amout of time to look into it, but would make playing janitor much better and convenient.
I can exemplify a few of them, like:
- Empty coffee and teacup
- The majority of the soda machine drinks
- Small lighters and rolling paper packets
- Small packets of different liquids
- Empty drinks/glasses of the bartender vending machine
- Plastic tableware
And much, MUCH more.

**Comment by UbaserB** [comment]
Its a lot better now and i havent seen many issues with stuff not being able to be trashed so i will close this issue for now
