### ISSUE TITLE
UserBoundInterface states being sent twice?

### ISSUE THREAD

**Issue by ghost** [space-wizards/space-station-14#1099]
I noticed that my BodyScanner was displaying the body twice since I forgot to add Clear() on the update, so I did some testing and it would seem that when I call
_userInterface.Open(actor.playerSession);
on the server
protected override void UpdateState(BoundUserInterfaceState state)
is called twice on the client. Might be a new bug.

**Comment by mirrorcult** [comment]
no repro + 3 years old + almost certainly fixed or not an issue
