### ISSUE TITLE
There should be way more replacement lights available on station at roundstart.

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#11003]
## Description
Currently it is a pain trying to fix large amounts of broken lights. There are not enough light replacers or boxes of replacement lights on the station. The janitor doesn't even spawn with some on most maps. Only way to get any at all is to order some from cargo.
 

**Additional context**
It is good to be able to order some from cargo as it drives department interaction but there should be more replacement lights available on station at roundstart in the janitor's closet and maybe in each department's storage room.

**Comment by Peptide90** [comment]
This is partly a mapping issue but one quick fix would be adding the boxes of lights to the below maint spawner, found in entities/markers/random/maintenance.yml

MaintenanceToolSpawner

Otherwise people have to make a conscious decision to map them. I recall them being quite common in 13.

**Comment by Kayek14** [comment]
This issue is resolved.
