### ISSUE TITLE
Items inside your inventory can slowly drift away and become unreachable.

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#11012]
## Description
The fact unreachable checks apply to your inventory is funny, but combined with items somehow **moving inside your inventory**, there might be a few problems.

**Reproduction**
Play the game for a ridiculously long time with a lot of grid transitions.
Realize your fire extinguisher is somehow not at 0, 0.
Oh shit, I can't take it out of my pocket.
![image](https://user-images.githubusercontent.com/7806367/188317032-38a96ab0-6797-49db-b40e-da3a59884a55.png)
![image](https://user-images.githubusercontent.com/7806367/188317114-9dfbeece-9308-4247-a595-ace925d40f51.png)

**Comment by ElectroJr** [comment]
Might be fixed by space-wizards/RobustToolbox/pull/3219 (if it was the cause, and not something else).

**Comment by Elijahrane** [comment]
A few other things could use some freer sort of 'anchoring' where movement relative to parent is completely impossible

**Comment by ElectroJr** [comment]
For most situations, you should just be able to use a container with occlusion disabled

**Comment by moonheart08** [comment]
this got fixed
