### ISSUE TITLE
Pack of rolling papers contains too much stuff

### ISSUE THREAD

**Issue by Visne** [space-wizards/space-station-14#11013]
I'm pretty sure that because of #10497 the pack of rolling papers and filters is now filled with 8 stacks of 5 of both rolling papers and filters, instead of just 8. That means that instead of 8 of both, it now contains 40 of both which is way too much. Can be fixed by just putting two stacks in instead of 8.

**Comment by Mervill** [comment]
It's now 8 rolling papers and 8 filters. Closed?
