### ISSUE TITLE
Syndicate Reinforcement Teleporter feels horrifically jank

### ISSUE THREAD

**Issue by EmoGarbage404** [space-wizards/space-station-14#11029]
## Description

The way it currently works is that, you purchase the item. It looks like an uplink, but interacting with it yields no results.
This is apparently just a ghost role spawner, and creates a ghost role that may or may not be filled at some point. When this happens, a humanoid just spawns in at that location.

It overall lacks feedback, and looks/feels incredibly jank to use.

**Comment by Stealthbomber16** [comment]
There needs to be some sort of feedback that you have enabled the reinforcement spawner, and ideally some way to disable it. I got one from a surplus crate and turned it on without intending to and I had no idea until someone spawned literally right on top of me.

**Comment by DogZeroX** [comment]
In addition, they need to be made nukie because they get shot by syndie turrets.
