### ISSUE TITLE
Very slippery things should still slip on lower speed thresholds

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#11031]
## Description
It would be nice to have certain *very* slippery things such as space lube or omega soap to still be able to slip players who are slowed down by the following movement speed reducers: damage, hardsuits, hunger, dragging, etc.

Currently if your movement speed is lowered by any means you wont slip even if you are not using the walk key. This makes sense with things such as banana peels since your character is moving slower after all. Some things however (space lube, omega soap) should still slip you if your character is not being extra careful, i.e using the walk key.

**Additional context**
Not sure how it is currently coded but when you walk do you not slip because of your lowered move speed or because of the fact you are using the walk action?

**Comment by mirrorcult** [comment]
you can just change the movement threshold on `SlipperyComponent`
