### ISSUE TITLE
Admin testing area sometimes gets deleted with explosions

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#11032]
## Description
Sometimes, while testing explosions in the admin testing area, it will instantly disappear and delete your aghost and everything else inside it. If you try to recreate or go back to your personalized admin testing area it wont let you.
Ive had this happen to me with exploding fuel tanks to the explosion from the fireball wand. Not sure what really causes it. Doesn't happen 100% of the time

**Reproduction**
1. Use admin trick powers to send your aghost to your testing area.
2. Spawn in or create explosions
3. Eventually one will yeet the testing area to the backrooms

**Additional context**
Might have to fiddle around with it for a while before the bug will replicate. All i know is that exploding things inside the test area is the trigger.

**Comment by ElectroJr** [comment]
Were there any logs in the client or server console?

**Comment by Kayek14** [comment]
Nope, or errors in the log, just tested and recreated it by shooting explosives at the upper airlock door.

**Comment by ZeroDayDaemon** [comment]
I've encountered this as well
