### ISSUE TITLE
Guns spam missing component errors in console when fired

### ISSUE THREAD

**Issue by ZeroDayDaemon** [space-wizards/space-station-14#11042]
## Description

Guns spam errors in console when fired
**Reproduction**

Shoot a gun, disabler, cr 20
**Screenshots**

![image](https://user-images.githubusercontent.com/60460608/188487836-c884a177-aad7-4498-a9c0-d19f1935ad8e.png)

**Additional context**

**Comment by Stealthbomber16** [comment]
Also happens with turrets. 
![image](https://user-images.githubusercontent.com/100171035/188490592-1acc0a98-7fc3-4c08-ad7a-4f12fba2a659.png)
