### ISSUE TITLE
Belts showing no item overlays when inserting items

### ISSUE THREAD

**Issue by Carbonhell** [space-wizards/space-station-14#11051]
## Description

Belts (confirmed with a normal utility belt and a security belt) don't properly show the items overlay when inserting stuff into it.

**Reproduction**

1) Spawn a full utility belt
2) Notice how the overlays for the tools in it show properly
3) Remove a tool of your choice
4) Insert the tool again in the belt
5) The belt now looks empty, without tool overlays

In particular, removing an item somehow makes the correct overlays show up again.

**Screenshots**

Before inserting an item:
![image](https://user-images.githubusercontent.com/11891037/188507062-e26673a4-e2db-4750-9072-c3714af62c3d.png)
After:
![image](https://user-images.githubusercontent.com/11891037/188507095-2c3bbfce-5993-4a00-800e-560f22e9c36a.png)

**Comment by ElectroJr** [comment]
The problem is probably because the `SharedMapLayerData.ServerWhitelist` is server-only. It needs to be properly shared.
