### ISSUE TITLE
User-friendly way of rebinding keys.

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#1106]
We need an user interface for rebinding the keys

**Comment by Visne** [comment]
Personally I've always liked UI's where you can see the keyboard and then select keys better than a long list of actions to assign.

**Comment by SweptWasTaken** [comment]
![image](https://user-images.githubusercontent.com/49448379/94898155-9c53e180-0480-11eb-90f5-af645803beca.png)

Done, closing.
