### ISSUE TITLE
Rad storm event triggering during the evac shuttle kills the whole lobby.

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#11072]
## Description
It doesn't feel good when a rad storm aimbots players on the evac shuttle. Everyone is so confined in there and it is almost a 100% guarantee that everyone is going to be dead before the shuttle docks at centcom. The storm spheres were still triggering on FTL making it hopeless.

**Reproduction**
Have the rad storm trigger when the shuttle is docked.

**Comment by mirrorcult** [comment]
isnt rad storm disabled

**Comment by mirrorcult** [comment]
or like. literally not even in the code anymore

**Comment by Emisse** [comment]
someone brought a rad artifact on the shuttle and it killed everyone

**Comment by EmoGarbage404** [comment]
> someone brought a rad artifact on the shuttle and it killed everyone

Certified skill issue.
