### ISSUE TITLE
Large chunk of meta.json's have no attribution or license.

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#1108]
We should probably fix this.

**Comment by AJCM-git** [comment]
Im already re-organizing the textures folder, so i might as well do this

**Comment by SweptWasTaken** [comment]
Any update?

**Comment by SweptWasTaken** [comment]
> 
> 
> Any update?

I took it into my own hands, will progressively be updating the five quadrants of the textures folder.

Part 1 is #2539

**Comment by Peptide90** [comment]
@SweptWasTaken did your recent purge clear this issue?

**Comment by SweptWasTaken** [comment]
> yo

Most of this is done, and I know what needs doing so i'm closing this.
