### ISSUE TITLE
Clumsy component is seriously broken

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#11080]
## Description
The clumsy component is not working right now. I tested multiple different items, five apiece, and not **once** gotten a single clumsy interaction. 

Item tested  (x5)    |    Funni Clumsy interactions

 disabler : 0
 baton : 0
 handcuff : 0
 makeshift cuff : 0
 cobras : 0
 Python  : 0 
 Viper : 0
 CR-20 : 0
Bulldog : 0
L6 saw : 0

**Reproduction**
Get a clumsy component and test shooting guns, using stun batons, and cuffing.

**Additional context**
Last I heard, something about the gun refactor broke this?
Its time clowns start acting like clowns again. **HONK**

**Comment by Kromabae** [comment]
I reported this like 3 months ago

**Comment by ike709** [comment]
https://github.com/space-wizards/space-station-14/issues/9457
