### ISSUE TITLE
Pills should have more size

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#11110]
They're 1 atm but considering how much healing a pill can do it should weigh a bit more for balance reasons, maybe 5.

**Comment by lapatison** [comment]
Would be nice to have the pill size linearly scaled with pill reagent amount.
1-10u - size 1, 11-20u - size 2, etc

**Comment by metalgearsloth** [comment]
What's a screwdriver got to do with it

**Comment by 0x6273** [comment]
Nothing, just a random example. It makes no sense for a pill to be that big.

**Comment by rolfero** [comment]
I think size 5 feels too big
Aren't there other viable balancing measures?
Making pills expensive, less useful, or something else
Maybe pill bottles take up som additional space, but grabbing pills from anywhere other than pill bottles has a DoAfter, etc

**Comment by 0x6273** [comment]
I think reagents from the chem dispenser should be limited somehow.

**Comment by Kromabae** [comment]
if you do this, what about pill bottles?

**Comment by Visne** [comment]
Changing the size is a really weird way to balance this.

**Comment by Kromabae** [comment]
i'm thinking there's an invisible problem here that really isn't an issue, with pills you're still limited to stomach space. and most chemists are affraid people will be dumb and OD themselves so they jsut make bottles anyhow becuase bottles are pretty much OD proof mostly
some chems are better in pill form but it's like a minor difference really. I have never once met someone who has carried a ton of pills in their inventory to warrant a change like this.

**Comment by Illiux** [comment]
This is a bizarre way to attempt to balance this. It's a pill. Even large pills weigh practically nothing. It's already straining plausibility that you can only fit 12 in a canister.

If pills can pack so much healing that it's a problem, then the issue is our magic space healing drugs, not the delivery mechanism.

**Comment by Illiux** [comment]
There is a pretty big disparity in maximum dosage between bottles/syringes and pills though. Logically bottles and syringes could hold more active ingredients than a pill could dream of, yet right now a pill holds more.
