### ISSUE TITLE
Among Us art needs removing

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#11114]
If we're allowing licensed works under the guise of fair use then it should be discussed between maintainers again considering we already came to an agreement on this and purged existing works.

**Comment by Visne** [comment]
Related to #11115

**Comment by EmoGarbage404** [comment]
Nice to see that my latest contribution to the project is possible among us themed copyright violation.

**Comment by EmoGarbage404** [comment]
https://www.innersloth.com/fan-creation-policy/

this is the policy for use of the among us IP. as far as i can tell, there's no issue with having game assets using the IP so long as they are not intentionally vulgar, attempting to claim validity, or being used in marketing. I'm not a legal expert, but nothing in the policy states anything wrong with the way in which the assets are currently being used.

**Comment by moonheart08** [comment]
> https://www.innersloth.com/fan-creation-policy/
> 
> this is the policy for use of the among us IP. as far as i can tell, there's no issue with having game assets using the IP so long as they are not intentionally vulgar, attempting to claim validity, or being used in marketing. I'm not a legal expert, but nothing in the policy states anything wrong with the way in which the assets are currently being used.

The copyright for that painting in particular needs to link the fan creation policy. Can you make a PR?
