### ISSUE TITLE
Crowbar and Emergency Crowbar Changes

### ISSUE THREAD

**Issue by thekaio123** [space-wizards/space-station-14#11127]
There must be some balance regarding crowbars, since every individual has one in their pockets and can easily escape from any station danger (spaced places and antags traps).
The changes would make the crowbars to be the way crowbars are in SS13.
In SS13, there is the normal crowbar (the grey one, cant be put in pockets), and the pocket crowbar (which in SS14 is the emergency crowbar, this crowbar can be put in pockets and weigh less).

The changes would be the following:
- Normal Crowbars can't be put in pockets now
- Emergency Crowbar now is named Pocket Crowbar
- Emergency Crowbar now weighs less (around 5)
- The emergency crowbar sprite has changed (to be smaller or to be different from the normal crowbar)

**Comment by EmoGarbage404** [comment]
how does making one crowbar objectively worse than the other make this better balanced? It would really be the exact same thing, except the supply of pocket crowbars would be slightly less (not much, mind you, due to emergency lockers being everywhere). Besides, it wouldn't stop people from just keeping a regular crowbar in their bag or on a belt, which is very feasible for most players.

Personally, if I were to make an changes involving crowbars, the best change would just be allowing firelock prying with bare hands.

**Comment by thekaio123** [comment]
> how does making one crowbar objectively worse than the other make this better balanced? It would really be the exact same thing, except the supply of pocket crowbars would be slightly less (not much, mind you, due to emergency lockers being everywhere). Besides, it wouldn't stop people from just keeping a regular crowbar in their bag or on a belt, which is very feasible for most players.
> 
> Personally, if I were to make an changes involving crowbars, the best change would just be allowing firelock prying with bare hands.

The thing is, people always have crowbars, and i dont think everyone should have them, as i said, anyone trying to space places with people in there will be easily countered with a crowbar, crowbars should not be an item that everyone is carrying around in the station, since the crowbar is an easy tool to tamper with the station (breaking glasses, closing emergency door and such).
Emergency crowbars are rarer than normal crowbars, they must have some advantage above normal ones.
In any case, making emergency crowbars different from normal crowbars are needed, being it balancing or advantages/disvantages between them, 'cause besides the sprite and locations, they have no differences.

**Comment by EmoGarbage404** [comment]
i don't really understand the point you're trying to make. The reason people carry around tools (and crowbars specifically) is that if you get caught in a situation without them, there's a very good chance you die. If you want fewer people to have crowbars, you either need to decrease their supply or make them not as necessary. As it currently stands, if you don't want to get trapped in a room behind a firelock or in a power outage, carrying a crowbar is mandatory.

**Comment by thekaio123** [comment]
> i don't really understand the point you're trying to make. The reason people carry around tools (and crowbars specifically) is that if you get caught in a situation without them, there's a very good chance you die. If you want fewer people to have crowbars, you either need to decrease their supply or make them not as necessary. As it currently stands, if you don't want to get trapped in a room behind a firelock or in a power outage, carrying a crowbar is mandatory.

I will short my issue with the balancing of crowbars (also, sorry if im not being too clear here):
At the moment, there is two crowbars, the normal crowbar, the grey one, found in utility belts and in the tool machines. And the emergency crowbar, which is only found in emergency toolboxes, around maints or in emergency lockers. The thing is, the normal crowbar is easily found around the station, its a public use item in the tool machine, and some jobs even start with it, in belts found in their lockers or belts that start with them.

(And i was thinking about what i said, i dont think people should not have crowbars, i want less people with BETTER crowbars)

Since the emergency crowbar is harder to find, there should be a difference between their use, there is some alternatives to that, like making the emergency crowbar weigh less, opening doors faster, fit into pockets (and make the normal one don't, since is an easy to find).
The counterpart to that is making the toolboxes even harder to find in emergency lockers, but it would have advantages above other, making the scarcity of the toolbox worth.
One of them is destinated to use in emergencies (since is found in the emergency locker), used in power outages and spaced places, the other one, is destinated for engineering purposes, fixing doors, repairing, desconstructing or constructing machines.
Makes sense having a difference between another, because as it is, the emergency crowbar is just a copy of the normal crowbar with different sprite and a different location to be found, any change to that is welcome.
And if there is another point to argue, point me please.

**Comment by civilCornball** [comment]
Isn’t the emergency crowbar already lighter than the normal crowbar?
5 compared to the normal crowbar’s 10.
