### ISSUE TITLE
Uplink Not Giving Items But Still Takes TC [rare?]

### ISSUE THREAD

**Issue by Emisse** [space-wizards/space-station-14#11129]
Seen this reported in ahelp several times the past few days so thought I'd jot it down here. 
Repro from them seems to be, spend TC on item, no item appears.
If anyone has more info leave it below.

**Comment by Kayek14** [comment]
Can confirm, have seen players ahelping about this issue. Ive also personally seen, and gotten ahelps from players, where the uplink is just an empty blank screen.

**Comment by DummeHytteOst** [comment]
it happened to me once where i was a late join traitor, tried to buy something and got no item, i could also not withdraw any TC i had in my uplink

**Comment by Interrobang01** [comment]
This has happened to me as a new-round syndicate agent. I also died and got cloned before using the uplink, and might have never even opened the screen at all before dying. Starting there might get a reproduction.
