### ISSUE TITLE
Energy Pen showing damage type on examine even when turned off

### ISSUE THREAD

**Issue by LordEclipse** [space-wizards/space-station-14#11154]
## Description
So apparently you can figure out if a pen is an epen by examining it and seeing the damage type, and never needing to ignite it. Also apparently the damage it shows is bugged too.

**Reproduction**
1. Get an epen somehow
2. Examine the epen
3. Notice the damage type and damage it deals in the examine

Screenshots:
![image](https://user-images.githubusercontent.com/106132477/189468776-1da0cd1d-164e-42a8-8f30-72208336778a.png)

![image](https://user-images.githubusercontent.com/106132477/189468788-e81f6262-a446-4d03-94d4-e956f553b0e2.png)

![image](https://user-images.githubusercontent.com/106132477/189468798-d37b7222-8828-473f-becc-e8eaa8bb1f17.png)

![image](https://user-images.githubusercontent.com/106132477/189468811-b25129c8-c440-4666-963d-fb808aac77e5.png)

**Comment by Emisse** [comment]
![image](https://user-images.githubusercontent.com/99158783/189468875-9292d831-993f-43eb-850b-a44be59ed927.png)
for reference this is its normal damage
this parents off the e blade so its probably similar there too
