### ISSUE TITLE
The damage analysis should be optional.

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#11153]
## Description
You can analyze players, and also **the E-pen, allowing you to metagame what it is without opening it.**

**Comment by Androidonator** [comment]
Yes there should be a white list of items that can get scanned. I mean it's nice QOL, but ruining life of that one stealthy syndicate that didn't go fo the way of total shit storm is kinda sad. I mean in LRP you will beat up the guy with epen but in MRP shouldn't you pretend you don't know what it is except if you are a sec or command.

**Comment by Emisse** [comment]
maybe we could have it as a component on weapons and exclude it from concealed ones

**Comment by metalgearsloth** [comment]
Could make it a property on melee weapons then it's easy for forks to toggle if they don't want it?
