### ISSUE TITLE
Bodybags don't go in morgue trays

### ISSUE THREAD

**Issue by Veritius** [space-wizards/space-station-14#11172]
## Description

Apparently the game doesn't count it bodybags as things that can go in the morgue. Corpses are fine, though.

**Reproduction**
1. Spawn a Urist
2. Shoot the Urist
3. Bag the Urist
4. Fail to put the Urist in the morgue

**Comment by civilCornball** [comment]
I honestly thought that was a feature.
Why would you put the bodybag in there? It's reusable!
Just remember to open it.

**Comment by Visne** [comment]
From [Wikipedia](https://en.wikipedia.org/wiki/Body_bag#Uses):

> Body bags are not designed to be washed and re-used. Aside from the obvious hygiene concerns, re-use of body bags could easily contaminate evidence in the case of a suspicious death. As a result, body bags are routinely discarded and incinerated after one use.

Makes a lot of sense to be honest. We just need a way to easily create new body bags.

**Comment by EmoGarbage404** [comment]
> From [Wikipedia](https://en.wikipedia.org/wiki/Body_bag#Uses):
> 
> > Body bags are not designed to be washed and re-used. Aside from the obvious hygiene concerns, re-use of body bags could easily contaminate evidence in the case of a suspicious death. As a result, body bags are routinely discarded and incinerated after one use.
> 
> Makes a lot of sense to be honest. We just need a way to easily create new body bags.

Theyre printable at medical techfab, no?

**Comment by Visne** [comment]
> Theyre printable at medical techfab, no?

Idk, I don't play the game. /s

**Comment by Visne** [comment]
Can I close this? Doesn't seem like a bug.
