### ISSUE TITLE
Turret Mob Interactions

### ISSUE THREAD

**Issue by Kromabae** [space-wizards/space-station-14#11195]
Just posting a list of behaviors of turret incase some of them are unintended

All Xenos, carps, rat servants. Space Adder attack and get shot at
Holocarp gets shot at and attack but bullets pass through (cool feature btw)

Ticks, Space bear and Rat Kings get shot at but dont attack back

Space Dragon attacks but dont get shot at

All animals,Holoparasites (both normal holo and ifrit) and Tarantulas dont get shot at and dont attack

If this is intended i apologize for wasting reading time but i thought i'd make a list just incase of an oversight

**Comment by IProduceWidgets** [comment]
Replicated these, but I also think its probably fine. The things you would expect to get shot by the NT and syndicate turrets do, the hostile turret is a bit more mercurial, but its probably just faction things.

The neutral/NT animals do seem to have perhaps random faction alignments though.
