### ISSUE TITLE
Your mutilated body doesn't get unmutilated on Rejuvenate

### ISSUE THREAD

**Issue by Just-a-Unity-Dev** [space-wizards/space-station-14#11223]
pure visual bug

1. cave urist's skull in
2. rejuvenate urist
3. wtf urist? clean yourself up

**Comment by mirrorcult** [comment]
this is a dupe of something im too lazy to find the dupe

**Comment by mirrorcult** [comment]
#7543

**Comment by Just-a-Unity-Dev** [comment]
> this is a dupe of something im too lazy to find the dupe

dupe of a dupe apparently
