### ISSUE TITLE
restartroundnow no longer restarts the round now

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#11220]
It goes to lobby but it's supposed to just reset the round and bypass the lobby.

**Comment by wrexbe** [comment]
I think bypassing the lobby would cause confusion. It wouldn't be friendly on a live server anymore.

**Comment by metalgearsloth** [comment]
restartround is the one that goes straight to lobby but restartroundnow is mainly for debugging.

**Comment by Visne** [comment]
This is most definitely a feature to me, not a bug. Whenever I need to go to the lobby, I set the CVar `game.lobbyenabled` to true and then run `restartroundnow` to get to the lobby fast. If I had to wait for the `restartround` timer to run out every time I would go insane.

In my opinion you should just set `game.lobbyenabled` to false to get this behavior.

**Comment by metalgearsloth** [comment]
Also 2nd part of the issue is you can't start the game anyway from said lobby you get to.

**Comment by Visne** [comment]
How long has that been an issue? I swear that works fine for me.

**Comment by metalgearsloth** [comment]
Only noticed it yesterday.

Also latejoining isn't working for me in debug either. I tried using the respawn command on myself and tried joining but it didn't work (even with role timers off).

**Comment by Visne** [comment]
> This is most definitely a feature to me, not a bug. Whenever I need to go to the lobby, I set the CVar `game.lobbyenabled` to true and then run `restartroundnow` to get to the lobby fast. If I had to wait for the `restartround` timer to run out every time I would go insane.
> 
> In my opinion you should just set `game.lobbyenabled` to false to get this behavior.

I just learned `golobby` exists which does this, so it makes more sense to have `restartroundnow` bypass the lobby, and have use `golobby` if you want to immediately go to the lobby.

**Comment by moonheart08** [comment]
Could not reproduce.

**Comment by moonheart08** [comment]
Supersceded by #11550 which correctly describes the issue.
