### ISSUE TITLE
comfy chair can't be rotated

### ISSUE THREAD

**Issue by LordEclipse** [space-wizards/space-station-14#11257]
## Description
Unsure if this applies to other chairs, but I noticed this just now, you technically CAN rotate it by smacking it against a wall, however. you cannot rotate it through the context menu.

**Reproduction**
1. Find comfy chair
2. Unwrench comfy chair
3. Notice that comfy chair can't be rotated until you decide to smash it against a wall.

**Screenshots**
![image](https://user-images.githubusercontent.com/106132477/190048695-ad68ba4e-1c43-43ed-b24a-7cec5e13ab66.png)

**Comment by themias** [comment]
Good first bug I think. Also related to #11165
