### ISSUE TITLE
Evac shuttle doesn't interact players when it warps in on top of them

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#11263]
## Description
When the evac shuttle "spawns" in, it wont gib, kill, push or have any effect on players who are in its way. They just appear inside the shuttle. This has been abused by players orientating themselves just prior to the shuttle warping in and getting free instant access to the cockpit.

On other occasions, while its accidental or intentional, players also might also get stuck inside a shuttle wall and slowly die.

**Reproduction**
1. call the evac shuttle.
2. Space walk to the arrival location just before it arrives at the station.
3. Observe how you magically appear inside the shuttle unharmed.

**Additional context**
Is the evac shuttle still planned to actually fly up to the station like the cargo shuttle? If so then this wont be an issue.

**Comment by Kayek14** [comment]
This issue seems to be resolved. Incomming warping vessels will gib players that are in the way.

**Comment by Brandon-Huu** [comment]
> This issue seems to be resolved. Incomming warping vessels will gib players that are in the way.

Do you know what it was resolved by?

**Comment by Kayek14** [comment]
I believe I originally created this issue back in 2022 when warp had no blue circle indicator and then closed it when warping code was added/refactored. However I think only the arrival shuttle gibs players while the evac shuttle did not. Instead of reopening this I created a new #30210 issue to better clarify.
