### ISSUE TITLE
Bananas Cream Pies when thrown delete the pie tin all together 

### ISSUE THREAD

**Issue by Bolt-Lee** [space-wizards/space-station-14#11276]
Description explained in title.

**Reproduction**
Become Chef or have access to kitchen
Make a bananas cream pie in the microwave
Throw banana cream pie at someone, deleting the tin once it lands

**Screenshots**

**Additional context**
No other context my only suggestion is to make the pie tin drop when thrown, or something like that.

**Comment by EeveeTea** [comment]
Could take it a step further, the tin gets equipped on the face unless they have a mask or something, temporarily blinding them. Then the tin could either fall off after a few seconds or the player can unequip it as quick as they can.

**Comment by Kromabae** [comment]
with the new pie recipes it would be good if the pie tins didn't get deleted upon being thrown

**Comment by moonheart08** [comment]
> Could take it a step further, the tin gets equipped on the face unless they have a mask or something, temporarily blinding them. Then the tin could either fall off after a few seconds or the player can unequip it as quick as they can.

I'd go with this, for anyone planning to tackle the issue.
