### ISSUE TITLE
We need unique in-hands for all guns.

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#1127]
Most of our in-hands for guns are still using the same SMG in-hands sprite. This will change if [this](https://github.com/space-wizards/space-station-14/pull/1033) pr gets merged but we still need inhands for a lot of other guns.

Whoever wants to take on this issue should first identify what guns need a custom in-hand sprite, then go to the [CEV-Eris](https://github.com/discordia-space/CEV-Eris) or [tgstation](https://github.com/tgstation/tgstation) codebase and port the inhands sprite for that weapon.

You can use our handy [RSI Editor](https://github.com/space-wizards/RSI-editor) or do it manually if you know what you're doing. If you want to extract specific sprites from a DMI, remember you can open it up in dreammaker and right click on the specific sprite and export it as a dmi. 

If guns are similar like two different smgs then you can definitely just use the same sprite, since 32x32 doesn't give you much space to work with. 

If you find a inhand that you can't find a sprite for, put it on a list somewhere and we can find a sprite for it or have on made. Use #art-and-ui on the discord if you need help.

**Comment by metalgearsloth** [comment]
Partially resolved by https://github.com/space-wizards/space-station-14/pull/1033

We still need support for inhands being dynamically updated in code.

**Comment by SweptWasTaken** [comment]
90% complete, good enuff for me.
