### ISSUE TITLE
Chocolate bar is not as bad as promised

### ISSUE THREAD

**Issue by lapatison** [space-wizards/space-station-14#11279]
## Description

FoodSnackChocolateBar description claims that it tastes like cardboard, but flavour profile makes it taste like chocolate.

**Reproduction**

**Screenshots**

![image](https://user-images.githubusercontent.com/100279397/190267322-b945007a-111e-43a5-b98e-6ca0487f3af8.png)

**Additional context**

**Comment by EmoGarbage404** [comment]
do we change the description or do we change the flavor? 🤔

**Comment by Emisse** [comment]
sweet sweet chocolate... i remember when they first invented chocolate. I ALWAYS HATED IT
![image](https://user-images.githubusercontent.com/99158783/190268275-0a455e16-c9ed-4a17-8844-543c5f217c55.png)

**Comment by lapatison** [comment]
> do we change the description or do we change the flavor? 🤔

What if we add ability to eat paper (like spies, eating evidences), and paper'ish\cardboard flavour, both appliable for chocolate bars and paper sheets?

**Comment by rolfero** [comment]
I vote we change both - the description should be "Tastes like chocolate.", the flavor profile should be cardboard.
