### ISSUE TITLE
Parallax is not rendering on latest master.

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#1128]
Tested on Windows 10. On both Steam and locally built version of the game.

**Comment by Tomeno** [comment]
https://pastebin.com/0VqML0Qr trace

**Comment by PJB3005** [comment]
Fixed by 310e765502224acea20b3d06df817882201d6275. If it remains broken you'll have to remove the parallax cache in `%appdata%/Space Station 14`.
