### ISSUE TITLE
JaniDrobes should stocked with mops

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#11291]
## Description
The janidrobes are stocked with all kinds of equipment that the janitor needs, except for their most important tool, the mop. If more than one janitor spawns on certain mops, there wont be enough of them to go around. Similarly, if a janitor has their mop stolen or lost, they will be unable to do their job as their mop will be gone.

The only way to get a new mop is to order a janitorial supplies crate, as this will come with one mop. The janitors most important tool should not be gated behind this, and there should be more ways for a janitor to quickly replace a lost or stolen mop, or if a latespawn janitor arrives and has no way to do their job. Mops from cargo is good, but there should be more than at least one mop available at round start.

**Additional context**
As ironic as it sounds, on some maps the drone bay has more roundstart mops than the janitorial closet does.

**Comment by 0x6273** [comment]
> The only way to get a new mop is to order a janitorial supplies crate,

Not true, sci can print them
