### ISSUE TITLE
Add more types of lights.

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#1129]
Just go through the lights folder on [cev-eris](https://github.com/discordia-space/CEV-Eris/blob/master/icons/obj/lighting.dmi) or [tgstation](https://github.com/tgstation/tgstation/blob/master/icons/obj/lighting.dmi) and add some lights from there.

Look at [lighting.yml](https://github.com/space-wizards/space-station-14/blob/master/Resources/Prototypes/Entities/Buildings/lighting.yml) or [emergencylightcomponent.cs](https://github.com/space-wizards/space-station-14/blob/master/Content.Client/GameObjects/Components/EmergencyLightComponent.cs) if you're interested in an example of complex lighting behavior.

If you're gonna modify the map and add them in make sure you check with people in the discord first.

**Comment by ScumbagDog** [comment]
Here they are in rsi format:
[lighting-tg.rsi.zip](https://github.com/space-wizards/space-station-14/files/4777299/lighting-tg.rsi.zip)
[lightning-cev.rsi.zip](https://github.com/space-wizards/space-station-14/files/4777300/lightning-cev.rsi.zip)

**Comment by SoulSloth** [comment]
assign me to this please.

**Comment by Zumorica** [comment]
Assigned @SoulSloth

**Comment by SoulSloth** [comment]
> Here they are in rsi format:
> [lighting-tg.rsi.zip](https://github.com/space-wizards/space-station-14/files/4777299/lighting-tg.rsi.zip)
> [lightning-cev.rsi.zip](https://github.com/space-wizards/space-station-14/files/4777300/lightning-cev.rsi.zip)

Thanks. Is there also a dump that includes in-hand sprites?

**Comment by SweptWasTaken** [comment]
IMO completed by #1886 and #2141 

Closing
