### ISSUE TITLE
Basic reagents should be orderable from cargo

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#11316]
Didn't see an issue for it.

E.g. carbon, oxygen, silicon, sugar, anything for basic chems.

**Comment by deltanedas** [comment]
i locally implemented this by ordering groups of 5 chemicals, 1 large beaker containing 100u of every chemical in a regular dispenser.
its poorly balanced pricewise, the prototypes are broken but it exists i guess
should i make it a draft pr?

**Comment by QuietlyWhisper** [comment]
> i locally implemented this by ordering groups of 5 chemicals, 1 large beaker containing 100u of every chemical in a regular dispenser. its poorly balanced pricewise, the prototypes are broken but it exists i guess should i make it a draft pr?

I'd like to take a look at it, it might help me

**Comment by deltanedas** [comment]
https://github.com/deltanedas/space-station-14/tree/reagent-crates

**Comment by QuietlyWhisper** [comment]
This looks fine! What was wrong with the prototypes?

**Comment by deltanedas** [comment]
well it said it contained the reagent, but it can't actually be poured out

**Comment by Partmedia** [comment]
This is available from Mining Station 14. It would be a matter of copying the prototypes and cargo catalog entries over.
![image](https://user-images.githubusercontent.com/3229565/223575336-6da6ee5c-225e-4a78-8977-1a37d6e24800.png)

**Comment by deltanedas** [comment]
my issue with MS's implementation is that it takes up **way** too much space in cargo to have almost every reagent

**Comment by Partmedia** [comment]
> my issue with MS's implementation is that it takes up **way** too much space in cargo to have almost every reagent

We don't have to pay rent for space in cargo. The cargo menu is also sorted so it will be easy to find what you're looking for. If ultimately you think it's easier to find things by hiding them in arbitrary sub-menus, fine too.

I posted this because our prototypes aren't broken and actually can be poured out.

**Comment by deltanedas** [comment]
its mostly an issue for ordering chemicals in bulk as its 6 jugs per trip which is rather slow, combined with anything else the crew might need on top of that

**Comment by EmoGarbage404** [comment]
Done with #15211
