### ISSUE TITLE
Bottles?

### ISSUE THREAD

**Issue by Kromabae** [space-wizards/space-station-14#11314]
Get new chemmaster (looks great and works great)
but how do you get bottles to use with the chemmaster?
if i'm missing something, I'm sorry. But if I'm not, how did this get approved ?

**Comment by 0x6273** [comment]
Yeah, that probaly shouldn't have been merged before #11298

**Comment by Kromabae** [comment]
that wont solve the issue, still cant produce bottles *looks at the medifab*
