### ISSUE TITLE
Processing ores/materials into chemicals should be possible.

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#11320]
This provides the following chemicals:

- Iron (metal)
- Aluminum (metal)
- Sulfur (iron ores)
- Silicon (glass and quartz)
- Copper (does this even get used? Might need new ore.)
- Mercury (above)
- Lithium (above)
- Potassium (above)
- Phosphorous (above)
- Fluorine (Aluminium processing byproduct, might need new ore)
- Gold
- Silver
- Uranium
- Plasma
- Radium (component of uranium ores)
- Water (if you add ice to asteroids)
- Carbon (if you add ice to asteroids, it's part of Methane)
- Hydrogen (same as carbon)

**Comment by QuietlyWhisper** [comment]
Might I suggest allowing some of these to be grinded in the reagent grinder? This would allow you to extract liquid versions of these materials if someone was to add the recipes for it?

Also wouldn't add much to complexity, leaving it a way that makes sense, and most people used to doing it already.

**Comment by EmoGarbage404** [comment]
In my concept for destructive analyzer (it's in #ideamen somewhere) it has the extra ability to deconstruct items in materials/chems.

**Comment by QuietlyWhisper** [comment]
If you think that's a better route to go I'm all for it! 

You could still have less dense / strong materials be crushed by the reagent grinder after, if need be.

**Comment by Partmedia** [comment]
This is available on Mining Station 14 (ignore the part where it says "crystalline", it is carbon).
![image](https://user-images.githubusercontent.com/3229565/223575484-345873e8-9245-4a55-b0ca-a24d7e8dd716.png)

**Comment by greym0uth** [comment]
Not sure if there we're already ideas for where some of these materials could be sourced from but here are a couple ideas for one's I didn't see a source yet:

Potassium: plants (bananas)
Phosphorous: biomatter of some kind
Mercury: first thought would be introducing Lead ore to the game and Mercury would be a processing reagent of it; not sure what lead could be used for then.

**Comment by UbaserB** [comment]
Did this ever get implemented? I cant seem to find the PR that added this.
