### ISSUE TITLE
Able to pickup & drop items through windows

### ISSUE THREAD

**Issue by exp111** [space-wizards/space-station-14#1133]
Steps to reproduce:
1. Go to a window
2. Hover over the item
3. Move a bit up and till down the item is green (only works at a specific angle)
4. Pick up the item/drop an item there

![grafik](https://user-images.githubusercontent.com/17885980/84641771-d44c0e80-aefb-11ea-8282-e725c22dd764.png)
vs
![grafik](https://user-images.githubusercontent.com/17885980/84642949-7a4c4880-aefd-11ea-9e37-1840c7dc2581.png)

**Comment by ComicIronic** [comment]
Because windows don't occupy the full tile:
![image](https://user-images.githubusercontent.com/7339857/84643824-4588c300-aef6-11ea-8aa6-4c4e7e8e250f.png)
So you can click between the gaps between windows.
