### ISSUE TITLE
Electrolysis and distillation

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#11339]
## Description
In other words "you know how plants are made of compounds and not just pure carbon you can take?"

There should be ways to break down compounds into their components, i.e. electrolyzing water, cracking methane, and other "refining" activities. This effectively would be a new recipe system for allowing devices to transform chems. Ties into #11320, #11319, and #11317.

**Comment by Illiux** [comment]
Hey, please assign this to me.

**Comment by Partmedia** [comment]
This exists on Mining Station 14 as the CentriMax 2000:
![image](https://user-images.githubusercontent.com/3229565/223577026-051f0245-00de-41e1-a190-61a4e48d8a52.png)

**Comment by notquitehadouken** [comment]
going to make electrolysis

**Comment by notquitehadouken** [comment]
nevermind

**Comment by UbaserB** [comment]
Is distillation still going to be a thing?.. or is the centrifuge good enough.
