### ISSUE TITLE
Permanently altered perspective from rotating salvage

### ISSUE THREAD

**Issue by themias** [space-wizards/space-station-14#11343]
I was dragging a canister off of a salvage when it was bumped by the cargo shuttle.
I ended up with my perspective permanently rotated by 90 degrees for the rest of the round.

Screenshots taken on Bagel station

![bagel_rotated](https://user-images.githubusercontent.com/89101928/190544987-e8bbdfba-91d8-4eda-b6ea-3c8722f53e33.png)
![bagel_rotated2](https://user-images.githubusercontent.com/89101928/190544995-f1e446c5-676f-4c90-81ce-39e24b35625a.png)
![bagel_rotated3](https://user-images.githubusercontent.com/89101928/190545001-5a639e15-4d5a-42f3-9f9a-831baa9f1e67.png)

**Comment by metalgearsloth** [comment]
Did you press the camera reset button

**Comment by themias** [comment]
Ah, didn't know about that. I assume that would help. I'll close this.

**Comment by mirrorcult** [comment]
arguably this is an issue in the sense of 'the camera behavior and controls isnt explained super well and can feel incorrect even when its not'
