### ISSUE TITLE
Need a reliable way to extract reagents from puddles without wringing a mop

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#11351]
## Description

Mop should be the preferred/faster method (dont want to have perverse incentives with janitor stuff) but maybe a scoop item / dropper being able to pick stuff up etc.

**Reproduction**

**Screenshots**

**Additional context**

**Comment by BYONDFuckery** [comment]
i 100% want this..

**Comment by DrMelon** [comment]
A sponge, maybe?

**Comment by IamVelcroboy** [comment]
Straws? 😅

**Comment by IamVelcroboy** [comment]
Honestly though, we have droppers. Does that not work?

**Comment by TemporalOroboros** [comment]
If the puddle is deep enough is should permit scooping it up with a beaker, at the cost of mixing (some of) the contents of the beaker into the puddle.

**Comment by mirrorcult** [comment]
sponge makes the most sense to me. damp rag is basically this but it'd be good to have a sponge item too

**Comment by EmoGarbage404** [comment]
i'm pretty sure you can just use syringes and droppers now.

**Comment by mirrorcult** [comment]
that sucks, sponge is cooler

**Comment by Fahasor** [comment]
Add syringe ability to draw solution from puddles?

**Comment by mirrorcult** [comment]
this got done but im still sad its not cooler
