### ISSUE TITLE
Jittering component weird interactions with PVS

### ISSUE THREAD

**Issue by Emisse** [space-wizards/space-station-14#11360]
When an entity loses the jittering component out of pvs range it continues jittering if entering the observers pvs range again. I've seen this a lot the past week and not really sure how/why this happens but just jotting it here. Really obvious from electrical shocks, biomass reclaimer, and meth.

**Comment by Elijahrane** [comment]
Could it be that clients see the component is removed when it gets back into PVS range, but the shutdown event is only sent to clients within PVS range at the time that it's removed on the server?

**Comment by metalgearsloth** [comment]
This might be related to the activejetpackcomponent never being removed on the client as well.

**Comment by ElectroJr** [comment]
There are currently a couple PVS / component removal bugs, I'll have a PR up to fix them sometime today or tomorrow.
