### ISSUE TITLE
Round is failing to start sometimes (It's nukies again)

### ISSUE THREAD

**Issue by LordEclipse** [space-wizards/space-station-14#11396]
## Description
Okay so it looks like nukies are breaking the game again when a round tries to start with them as the gamemode.

**Comment by metalgearsloth** [comment]
Need at least:
- what gamemode was tried
- what map

**Comment by LordEclipse** [comment]
> Need at least:
> 
>     * what gamemode was tried
> 
>     * what map

Alright, I'll make sure to note that next time it happens.

**Comment by Leander-0** [comment]
Had this same issue yesterday, the round simply restarted once i forced the NukeOps gamemode, when i forced Zombies gamemode the round did not restart immediately.

**Comment by civilCornball** [comment]
I’ve had it happen twice for Nuke Ops. Paid no attention to the map, though.

**Comment by ElectroJr** [comment]
#11399 fixes a nukie bug, but I have no idea if that was the only one.
