### ISSUE TITLE
Gyroscopes are overtuned for smaller shuttles

### ISSUE THREAD

**Issue by retequizzle** [space-wizards/space-station-14#11393]
May be worth dialing back their responsiveness by default, even if it means we have to start mapping more gyros onto medium-sized shuttles to compensate. One gyro on a fully fleshed out 5x6 structure (thrusters, power supply, etc, even some flavor items) and it still spins like a top. Only way to get it even remotely pilotable is to hold down the space brakes when turning in any direction.

**Comment by metalgearsloth** [comment]
Dupe of https://github.com/space-wizards/space-station-14/issues/6249
