### ISSUE TITLE
Memory leak with power providers

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/space-station-14#1142]
![](https://cdn.discordapp.com/attachments/310555209753690112/722518978764996618/unknown.png)

**Comment by PJB3005** [comment]
@collinlunn any idea if your power rework fixes this?

**Comment by collinlunn** [comment]
I completely re-coded power providers (though I haven't yet verified that my replacement doesn't memory leak)

**Comment by Zumorica** [comment]
I'm pretty sure the power PR fixed this
