### ISSUE TITLE
Machine upgrading

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#11439]
Porting it from ss13, e.g. micro lasers.

Stuff like: Add the matter bin to a lathe and it becomes more efficient for materials or whatever.
Add a better micro laser to emitter and it uses less power / shoots faster.

**Comment by ElectroJr** [comment]
The basics for this already exist. E.g., see `GasThermoMachineSystem` and how it gets component qualities in `RefreshPartsEvent`.
However, AFAIK this is the only instance where component qualities are used. It might be as simple as just including these parts in more construction graphs and adding more `RefreshPartsEvent` subscriptions.

Thought it might also be worth reworking how the RefreshPartsEvent works, to avoid adding a bunch of boilerplate. E.g., the whole quality sum stuff in GasThermoMachineSystem shouldn't have to be repeated every time.

**Comment by EmoGarbage404** [comment]
#11528 will make this job sane.

**Comment by EmoGarbage404** [comment]
this issue has been entirely superseded by #11530
