### ISSUE TITLE
RotateToFaceSystem / rotation lerping issues.

### ISSUE THREAD

**Issue by ElectroJr** [space-wizards/space-station-14#11446]
Something is wrong with the `RotateToFaceSystem` or rotation lerping. This affects player rotations, but is easiest to see for sprites that are not no-rot. A pretty reliable way of seeing this is to just control something like a crowbar, set tick rate to 30/20, and then start clicking:

https://user-images.githubusercontent.com/60421075/191630441-b41a5b18-57d4-45d6-8067-c49c5e613d46.mp4

**Comment by metalgearsloth** [comment]
Pretty sure rotation lerping is still broken.

**Comment by metalgearsloth** [comment]
You can also do this with mobs, if you click near 45 degrees then you can clearly see your player do it on master.

**Comment by KIBORG04** [comment]
Another example. RotateToFaceSystem is also used.


https://user-images.githubusercontent.com/26389417/209438307-04019384-d302-4179-8541-96d13278663d.mp4
