### ISSUE TITLE
Fire damage and atmos hardsuits near-immune to lasers

### ISSUE THREAD

**Issue by rolfero** [space-wizards/space-station-14#11441]
## Description

The way damage from burning works currently, is that you both take heat damage from high temperatures (over a certain threshold), and you take additional heat damage while on fire (5 times the "amount" of fire, capped at 25 damage total)

Equipment meant for dealing with atmospherical issues, such as atmos hardsuits or fire suits, come both with temperature resistance and heat damage reduction, for this reason. Atmos hardsuits specifically come with 80% heat damage reduction, their helmets provide an additional 80%, and atmospherics gas masks come with an additional 20% heat damage reduction.

Since lasers deal heat damage, this means that wearing an atmos hardsuit with your helmet on provides 96% damage resistance to lasers - they will deal less than 1 damage per shot, reduced by 20% further if you decide to wear an atmospherics gas mask as well.

This should probably be rebalanced somehow.

Perhaps high temperatures should deal more damage, and being on fire should deal less damage, and then you could lower the damage resistance values on atmospherics gear - allowing you to better survive harsh environmental dangers, but won't make you as resistant to lasers coming in from every direction.

**Reproduction**

- Put on atmos hardsuit, put up your helmet and don your atmospherics gas mask.
- Get shot with laser 100 times, still stand.

**Screenshots**

https://user-images.githubusercontent.com/45628623/191480254-a3d47bc3-b3e6-470d-a42c-16526811fcef.mp4

**Comment by mirrorcult** [comment]
laser damage needs to be its own separate type is probably the easiest solution here

**Comment by mirrorcult** [comment]
or just a 'fire resistance' component and the heat armor can be nerfed significantly

**Comment by Elijahrane** [comment]
> or just a 'fire resistance' component and the heat armor can be nerfed significantly

We have stuff specifically for avoiding damage or insulating yourself from atmospheric temperature, and damage from that shouldn't be going through normal armor anyway

**Comment by mirrorcult** [comment]
> > or just a 'fire resistance' component and the heat armor can be nerfed significantly
> 
> We have stuff specifically for avoiding damage or insulating yourself from atmospheric temperature,

for being on fire, not for atmospheric temperature
