### ISSUE TITLE
Latejoin on NSS Pillar does not spawn you on the arrival shuttle.

### ISSUE THREAD

**Issue by Mervill** [space-wizards/space-station-14#11440]
## Description

Latejoin on NSS Pillar does not spawn you on the arrival shuttle. In fact it seems to choose a spawn location somewhat at random. This can lead to issues where people spawn in secure areas they otherwise wouldn't have access too.

## Reproduction
1. Latejoin NSS Pillar with a non-civilian role (could happen to them too but I don't usually play these roles).
2. You are not on the arrival shuttle

**Comment by Peptide90** [comment]
There is no arrivals shuttle only an arrivals area. I'll make sure to push an update soon with more late join spawn points etc as well as any other fixes.
