### ISSUE TITLE
Animated sprite states on clothing don't work when first equipped.

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#1144]
To replicate load into the game and spawn the "Cosmos Bedsheet". You'll see it's an animated sprite when you spawn it, but when you put it on your back or around your neck you'll see it isn't animated. Take it off and put it back on and you'll see the sprite is now animated. Do this with any animated clothing piece and you'll see the same behavior.

Tested on local and on the public server. The animated sprites will only work if you wear an animated one, take it off and put it back on. All animated sprites after that will work.
![2020-06-16_12-38-05](https://user-images.githubusercontent.com/49448379/84820296-ec5d8400-b008-11ea-96fa-38a3e289af42.gif)
(I know I recorded this with my neck slot pr but it's the same for all slots.)

**Comment by SweptWasTaken** [comment]
Another example of the same bug.

https://user-images.githubusercontent.com/49448379/107127060-79f92700-68ab-11eb-95c9-35c0286bfe2f.mp4

**Comment by Ygg01** [comment]
Ye I kinda want to deal with this one. I thought it was fixed when dealing with cigarettes.
