### ISSUE TITLE
Bioluminescent plants like to go thru doors

### ISSUE THREAD

**Issue by Just-a-Unity-Dev** [space-wizards/space-station-14#11450]
## Description
Dragging a plant allows it to go thru doors

**Reproduction**
1. Drag a bioluminescent plant
2. Push it into an airlock

**Screenshots**
![image](https://user-images.githubusercontent.com/67359748/191649475-86f8ab12-17d3-482a-8780-8f27ec598698.png)

**Additional context**

Discovered on salamander, with (i believe) the tickrate to be 30

**Comment by lzk228** [comment]
lol, even how
