### ISSUE TITLE
Tranquilizer rounds need balance

### ISSUE THREAD

**Issue by themias** [space-wizards/space-station-14#11463]
## Description

Now that tranquilizer rounds are working again, it was quickly discovered that they can be devastating with the right chemicals.
One or two shots can crit/kill someone, regardless of armor.

There needs to be a way to counter them. 
- Piercing resistance in armor could add a chance to avoid injection.
- Items like hardsuits and shields could block them
- The ammo could be made slower/less accurate

**Reproduction**

Load up a tranquilizer round with 15u of a toxin like lexorin and shoot some dummies

https://www.youtube.com/watch?v=fe-XFt-qxkw

**Additional context**

**Comment by EmoGarbage404** [comment]
maybe just nerf from 15u -> 5u

**Comment by Cheackraze** [comment]
the thing is 'tranquilizing' was already impossible at 15u, since chloral hydrate (sleeping chems) is only effective at 20u to begin with. The only 'non-lethal' chem that was even worth using in 15u was the new PAX. Now they will just go completely unused since no effective chem can be used in them at 5u. It would take an entire loaded kammerer and every shot hit with sleep chems just to work effectively now.

**Comment by civilCornball** [comment]
Might be a good idea to leave that on #11465 too.

**Comment by EmoGarbage404** [comment]
is the intent to even to be a tranquilizer? It's available in security techfab for crying out loud. Maybe it'd be better if it was like the emergency medipen, where the solution is predefined.

**Comment by Cheackraze** [comment]
I like that idea better, at least to keep them viable. Although it is a neat idea to fill them with whatever chems you want, I'm surprised we haven't seen alternating potassium/water shots to inject explosions

**Comment by EmoGarbage404** [comment]
tbqh, having a set solution is good. Ideas for syringe guns have been rejected in the past. Why are we allowing it now in the form of these bullets? It's the same concept.

**Comment by Cheackraze** [comment]
like the pnumatic cannon shooting pills for instance

**Comment by themias** [comment]
> tbqh, having a set solution is good. Ideas for syringe guns have been rejected in the past. Why are we allowing it now in the form of these bullets? It's the same concept.

I agree that having a set solution is for the best. I'll see about opening a PR for it.
