### ISSUE TITLE
Snow, Grass, Dirt, other 'turf' tiles need a solution for how to handle subfloor

### ISSUE THREAD

**Issue by Elijahrane** [space-wizards/space-station-14#11470]
## Description

As of https://github.com/space-wizards/space-station-14/pull/10984 they are no longer priable, which is an improvement, but now you can't run wires and pipes under them. I'm guessing this is a solved issue in SS13, but we need some solution for them to be able to be full floors with subfloors underneath. Maybe introduce a digging system?

**Comment by HoofedEar** [comment]
Digging you say...? :)
Should be easy enough, basically just mimic how tile prying works and give it to terrain tiles. 
I had a sloppy setup of this in my fork, haven't looked at it in a while, but I'll take a look

**Comment by IProduceWidgets** [comment]
I'm going to say this is mostly resolved by astro- variants, but it would be nice to have more options for removing the tiles including the welding or shovel/digging tool quality. Right now I could only get the prying or cutting qualities to work.
