### ISSUE TITLE
Selecting a new MIDI file while a song is playing doesn't switch songs

### ISSUE THREAD

**Issue by ShadowCommander** [space-wizards/space-station-14#1148]
When selecting another MIDI while an instrument is playing a song it just stops the current song. It should stop the current song and start the new one.

**Comment by Zumorica** [comment]
Can't reproduce on latest master, and I specifically fixed this a long time ago--
Can you try reproducing it again?

**Comment by ShadowCommander** [comment]
On the public server it always stops the current song, but sometimes it doesn't play the next song or it plays a few notes then gets stuck in eternal doot.

**Comment by Visne** [comment]
This has always happened to me, and when I asked in Discord someone else said it also happened to them.

**Comment by Peptide90** [comment]
This was specifically mentioned with the clown trombone but apparently not others.

**Comment by Visne** [comment]
Happened to me with piano too

**Comment by Zumorica** [comment]
Yes, all instruments share the same code so obviously this happens with all instruments

**Comment by Mith-randalf** [comment]
I often find I have to input a midi twice before it'll play, even if there's nothing playing at the time. Seems like some files are more prone to it, but I've not tested.
