### ISSUE TITLE
Handheld radios are broken again

### ISSUE THREAD

**Issue by Just-a-Unity-Dev** [space-wizards/space-station-14#11483]
It was fixe then brok then fixe but make a big crash and was brok again

Handheld radios don't work, they broadcast to the correct frequency (Common) but if you take your headset off you don't hear anything at all

Intended behavior should be to show Common to the person holding it instead of yelling it outloud

**Comment by mirrorcult** [comment]
just remove these god damn things

**Comment by EmoGarbage404** [comment]
> just remove these god damn things

Honestly yeah. They contribute nothing and are non functional.

**Comment by themias** [comment]
yea headsets are pretty much better in every way anyway. too many problems with handhelds

**Comment by GoodWheatley** [comment]
> just remove these god damn things

Disagree with this, think they're pretty cool for RP purposes and having a way to broadcast conversations to the radio.

**Comment by Elijahrane** [comment]
> just remove these god damn things

at least remove them until we have a sane way to collect nearby speech (PRs for tape recorders and voice activated triggers are up now)

**Comment by Just-a-Unity-Dev** [comment]
fixed some time ago due to radio refactor
