### ISSUE TITLE
Markings duplicate in the menu

### ISSUE THREAD

**Issue by EmoGarbage404** [space-wizards/space-station-14#11494]
## Description

Markings can be duplicated in the menu, such as having both one equipped and one left in the list.
**Reproduction**

- pick marking
- see it leave unused list
- pick different category
- return to first
- marking is back and selectable.

**Screenshots**

![image](https://user-images.githubusercontent.com/98561806/192109909-120c047b-bdfb-49b1-bf82-97fc54929f39.png)

**Additional context**

**Comment by Mervill** [comment]
@vulppine this issue wasn't properly closed with #11538

**Comment by vulppine** [comment]
this wasn't fixed in #11538, working on something to actually fix this now

**Comment by vulppine** [comment]
lmao i misread that as 'this wasn't fixed', sorry
