### ISSUE TITLE
Captain's antique laser size needs bumping

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#11491]
Right now it's 10 but should be the standard of 50. If someone wants to haul it around it should be a choice to do so (plus slots exist).

**Comment by Fellowsinspace** [comment]
50 seems a little bit too harsh. I think a bump up to 20-25 would be better so it cant be pocketable. Also this helps tots not pull their hair out if they have to steal the damn thing.

**Comment by metalgearsloth** [comment]
Bags hold 100 and stashes exist; traitors shouldn't be able to hoard every item.

**Comment by Fellowsinspace** [comment]
I can understand that but It seems stupid that a small pistol is almost the same size as an lmg (60). If we wanted captains to use it less I would increase the recharge time or reduce the damage. A 50 weight pistol is dumb but thats just my opinion.

**Comment by GoodWheatley** [comment]
Yeah I was going to say this earlier but the cap’s laser gun is clearly designed as a pistol. Doesn’t make sense to have it be the same size as a regular laser gun. I do think upping the weight to 20 is good, so captains have to decide between the saber and the laser gun on the belt slot.

**Comment by GoodWheatley** [comment]
Also ALL the captain’s stuff is deliberately downsized to help traitors, isn’t that why the jetpack only takes up 30 space?

**Comment by EmoGarbage404** [comment]
Both jetpack and laser should have size increased. Having them be able to be carried easily at all times just makes traitor gameplay worse.

Also, the captains laser should probably be in a display case instead of the locker. Would actually make it unique imo.

**Comment by civilCornball** [comment]
> Bags hold 100 and stashes exist; traitors shouldn't be able to hoard every item.

Oh, so *that’s* why people keep tossing out their internals boxes! They want the space!
