### ISSUE TITLE
Vector takes drozd magazines (naming issue for guns and their ammo)

### ISSUE THREAD

**Issue by Peptide90** [space-wizards/space-station-14#11501]
## Description

So someone reported that the vector does not infact take SMG magazines (.35) but takes .40 ammo. After some digging it turns out .40 ammo is named Drozd Magazines. We no longer have the Drozd so the following needs to happen:

1. Rename the Drozd Magazine to either .40 Vector Magazine OR .40 SMG Magazine.
2. Add either a suffix to each gun as to what ammo it takes for mapping purposes, or more logically, add the ammo calibre to the description of the gun so when you examine it you know what it takes.

**Comment by JazzGlobal** [comment]
Please close this issue if it has been corrected.

**Comment by HoofedEar** [comment]
Looks like it is fixed, closing
