### ISSUE TITLE
Botany scaling should be removed

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#11515]
The first time I saw the sprites being scaled I thought it was a bug because the sprites looked so out of place. After talking about mob sprite scaling on discord it's probably better that this gets reverted.

**Comment by Zumorica** [comment]
Just cap the sprite scale to a reasonable limit instead

**Comment by metalgearsloth** [comment]
I think ideal would be either:
1. Sprite variations (unlikely to get sprited)
2. Specific thresholds that at least look good at 1x scaling (e.g. x0.5, x2)?

**Comment by moonheart08** [comment]
Really needs to be 1 or nothing.

**Comment by Stealthbomber16** [comment]
botany scaling is the essence of "only a spoonful"

**Comment by EmoGarbage404** [comment]
this is unpopular plus we no longer have minifruit so all is well imo
