### ISSUE TITLE
Cable coils can be compressed

### ISSUE THREAD

**Issue by Rapidgame7** [space-wizards/space-station-14#11514]
**Description**
Normally, a coil of cable weighs 10 units. If you split the stack, the new stack will weigh 3 units.
You can then add more cable to the new stack and essentially tighten your cable pack.

**GIF**
![Awesome (real)](https://user-images.githubusercontent.com/14862618/192131309-cea48240-d9a7-4b87-887e-6a521317c08d.gif)

**Comment by themias** [comment]
Related to #8442

**Comment by Vordenburg** [comment]
Fixed by #17623
