### ISSUE TITLE
Add an option to disable cursor highlighting

### ISSUE THREAD

**Issue by partyaddict** [space-wizards/space-station-14#1152]
![image](https://user-images.githubusercontent.com/52793290/85069609-54989b00-b1ac-11ea-860e-204b926b6bfd.png)
or make the outline smaller

**Comment by F77F** [comment]
I'll add this.

**Comment by AJCM-git** [comment]
@PJB3005 are you okay with this?

**Comment by F77F** [comment]
It's just gonna be a client-side cvar. I think that eliminates any harm.
