### ISSUE TITLE
Text wrapping seems to be broke.

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#11539]
## Description
Text wrapping in popup windows seem to be broken. The text doesn't wrap properly and will be cut off by the edge of the screen. It seems to be effecting all popup windows. Changelogs, playernotes, adminlogs are some examples.

**Reproduction**
Open up the changelog for an example.

**Screenshots**

![image](https://user-images.githubusercontent.com/106507028/192378504-b0dc95b9-1f44-40e4-a8f4-1fddaf50ef6b.png)

**Additional context**
Resizing the window in anyway, even by one pixel, will immediately fix the wrapping issue.
Changelog cannot be resized so most lines will remain unreadable.

**Comment by Elijahrane** [comment]
Noticed this with admin notes recently

**Comment by Willhelm53** [comment]
![image](https://user-images.githubusercontent.com/97707302/193978957-01b4427b-502e-43f6-9f2d-6aac30cf11e4.png)
Seems to be pretty bad with Read-the-rules screens. Here's the one from USW-Lizard.
