### ISSUE TITLE
Droppers need to act like syringes

### ISSUE THREAD

**Issue by vulppine** [space-wizards/space-station-14#11546]
## Description

Droppers currently do not act like syringes, and instead act like a very, very small beaker that you need to use a syringe to put chemicals into. This should act more like a tool that lets you take precise amounts of chemicals from some reagent holder.

**Reproduction**

- Try to use a dropper by clicking a beaker
- See that it doesn't do anything
- Use a syringe to inject chemicals into it instead (inconvenient)

**Comment by Kromabae** [comment]
you can use beaker on the dropper and it transfers over, no need to use a three step process with syringe

**Comment by QuietlyWhisper** [comment]
Droppers currently work like this now, this issue can be closed

**Comment by DrSmugleaf** [comment]
Fixed in https://github.com/space-wizards/space-station-14/pull/12518
