### ISSUE TITLE
Fire extinguishers can't extinguish you.

### ISSUE THREAD

**Issue by asperger-sind** [space-wizards/space-station-14#11543]
**Reproduction**

1. Light yourself on fire.
1A. Light someone else on fire as well.
2. Grab a fire extinguisher, toggle the safety.
3. Attempt to extinguish yourself, fail miserably.
3A. Extinguish everyone with tremendously janky hitboxes.
4. Die of fire damage and cry.

**Additional context**

pleae i wnt thm to be usful please i hate rolling on the floor its a fuire extinguisher why doents it extgn8sh mee pleaeaaaaaaaaaaaaaaaaaaaa
In hindsight, it sorta makes sense, but in 13 you could spray it on yourself, and that's actually useful considering that fires never happen on MRP and on Lizard nobody is going to extinguish you.

**Comment by mirrorcult** [comment]
cant you spray it and then run into the spray

**Comment by mirrorcult** [comment]
not that thats a fantastic intuitive solution mind you. but im pretty sure its possible

**Comment by asperger-sind** [comment]
> not that thats a fantastic intuitive solution mind you. but im pretty sure its possible

Nope, tried several times in all the weird ways and forms you can do that, doesn't work.

**Comment by DummeHytteOst** [comment]
it should still work, i have used it many times the last couple of days to extinguish my self and other people, i have also seen other people use it and it worked, and being able to spray and run into it also worked last time i tried, which was yesterday

**Comment by EmoGarbage404** [comment]
this got fixed silently. Very cool!
