### ISSUE TITLE
Firelock construction bug

### ISSUE THREAD

**Issue by Emisse** [space-wizards/space-station-14#11567]
the step of building that requires you to wrench just unanchors it instead of completing the build

**Comment by themias** [comment]
I can't reproduce the wrench issue. That step seems to work fine for me.
However, I saw an issue with it not recognizing the firelock electronics, related to #11397.
Changing from tag to prototype in the recipe, and I can craft one just fine.

**Comment by Zumorica** [comment]
Just in case anyone tries to fix this, do **NOT** use a prototype step.

**Comment by themias** [comment]
> Just in case anyone tries to fix this, do **NOT** use a prototype step.

The linked cleanup PR from last week switched a bunch of recipes from tag to prototype. Was that wrong to do? Should that be reverted?

**Comment by Zumorica** [comment]
> > Just in case anyone tries to fix this, do **NOT** use a prototype step.
> 
> The linked cleanup PR from last week switched a bunch of recipes from tag to prototype. Was that wrong to do? Should that be reverted?

Yes, that was wrong and it should be reverted.

**Comment by themias** [comment]
Also will be fixed by #11611
