### ISSUE TITLE
Drinking glasses, plates and bowls can't be restocked if broken/missing

### ISSUE THREAD

**Issue by Renlou** [space-wizards/space-station-14#11580]
Chef needs plates and bowls to make meals, so some way to replenish those is by adding them to kitchen supplies crate.
Bartender can already get new Beakers from lathe but those don't change appearance to match the drink recipes. So it's not as cool.

Adding those 3 to supplies crate or having them be craftable in protolathe would fix the issue.

**Comment by Elijahrane** [comment]
dinnerware is a vending machine and there's a PR up for vending machine restocking

**Comment by Kromabae** [comment]
pretty sure the kitchen supplies crate has all that shit in it

**Comment by theashtronaut** [comment]
The CrateFoodCooking has plates and bowls, there is no cargo crate that includes drinking glasses.

The current vending machine PR (https://github.com/space-wizards/space-station-14/pull/11506) does not include restocking for the dinnerware machine, but once it is merged it should be trivial to add it and all the other missing vending machines.

I kinda feel like it might be nice to be able to lathe dishes, utensils, and drinking glasses too. I feel like they aren't complex objects. Probably a good beginner yml only PR for someone

**Comment by Elijahrane** [comment]
> I kinda feel like it might be nice to be able to lathe dishes, utensils, and drinking glasses too. I feel like they aren't complex objects. Probably a good beginner yml only PR for someone

port service techfab from downstream
