### ISSUE TITLE
Controlling a mob that isn't a player prevents the client from seeing the source of pointing

### ISSUE THREAD

**Issue by Rapidgame7** [space-wizards/space-station-14#11589]
## Description
Whenever you or someone else points to something and you're pretty much any ghost role, you don't get the "X points at Y" floating message that comes with the pointing arrow.

**Video**
https://user-images.githubusercontent.com/14862618/192927992-c7510592-84ce-492a-b7f6-718f8b4b0328.mp4

**Comment by IProduceWidgets** [comment]
Seems to be fixed for now.

![image](https://github.com/space-wizards/space-station-14/assets/107586145/c0bd29da-9314-47ef-b19c-2270945e7dcd)
