### ISSUE TITLE
Health analyzers can't be placed in medical belts.

### ISSUE THREAD

**Issue by Rapidgame7** [space-wizards/space-station-14#11598]
## Description
While a proper medic can use their PDA as an analyzer, new medics that started out on a non-medic role don't get to use their PDA as one. They should be able to store an analyzer in their belt.

**Screenshots**
![image](https://user-images.githubusercontent.com/14862618/192974141-fc8fbc81-b089-410c-952d-3d12a2377718.png)

**Comment by Just-a-Unity-Dev** [comment]
IIRC this is intended

**Comment by 0x6273** [comment]
Dupe of #11173, please search before making new issues.
This was discussed in PRs #11188 and #11405 and the change was rejected both times.

**Comment by Rapidgame7** [comment]
Oh whoops, I forgot to do that.
