### ISSUE TITLE
Remove prototype step from construction graphs

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#11607]
You know, I don't even care anymore. People keep using it instead of tags when they shouldn't so at this point I'd rather just remove it entirely.

![image](https://user-images.githubusercontent.com/6766154/193091286-27cbbbaf-6eae-42cd-93bd-63c9245378c8.png)
In the meantime, I hope this warning in the [construction doc](https://docs.spacestation14.io/en/content/construction/index) (yes, you know, the one that NOBODY fucking reads) is enough to deter people from using it.

**Comment by mirrorcult** [comment]
basado

**Comment by EmoGarbage404** [comment]
Will look into this in a bout to usurp vera from her construction throne.

**Comment by Zumorica** [comment]
> Will look into this in a bout to usurp vera from her construction throne.

good good
the TL;DR is: use tag/component steps instead (or material steps for stacks you know the drill)
