### ISSUE TITLE
Enabling pacifist still allows harm (does bug it out) to be turned on

### ISSUE THREAD

**Issue by KaiShibaa** [space-wizards/space-station-14#11619]
I enabled pacifist in one shift and I still saw harm. When I enabled it however I was permanently stuck in a limbo of harm but also not. 

I attacked things but nothing happened and could not damage anything. Even when an admin removed the pacifist component, I still could not fix myself from the harm being toggled on. 

[https://www.youtube.com/watch?v=8EN6pFfmvAs](url) Video evidence here aeughhh

**Comment by aklos** [comment]
This may be caused by having the PacifiedComponent but not the PacifistComponent.

**Comment by Froozigiusz** [comment]
Everytime I enable combat I get into the state of always shadow punching without doing damage (but still left-click interacting) and blocking myself from bing able to open right-click menu. The only time I was able to escape this state was a'helping
