### ISSUE TITLE
Carp can hit you through boxes

### ISSUE THREAD

**Issue by Scribbles0** [space-wizards/space-station-14#11636]
## Description

Carp hit me through the box when I had closed it in. I suspect this is a problem with the new melee system in general.

**Screenshots**

https://user-images.githubusercontent.com/91828755/193386116-7ef1f810-ca85-46f5-9d94-07a48927c6f2.mp4

**Comment by themias** [comment]
Seems to be still happening, in the reverse at least. Carps can attack you if you are in a locker.

**Comment by metalgearsloth** [comment]
There was a PR but it only fixed half the problem https://github.com/space-wizards/space-station-14/pull/13988

**Comment by Pangogie** [comment]
Fixed.
