### ISSUE TITLE
Eating Bananas off of the ground doesn't produce Banana Peels

### ISSUE THREAD

**Issue by Stealthbomber16** [space-wizards/space-station-14#11639]
This is an extremely grave situation that needs to be rectified immediately.

Steps to reproduce:
1. Place banana on ground or table
2. Alt + Click to eat it
3. Do you guys eat your banana with or without the shell

Thank you to AverageTaxPayer for reporting this

**Comment by rolfero** [comment]
I can't seem to reproduce this at all

**Comment by KiwiApteryx** [comment]
Ive managed to pull this off as a rat, ill see if it happens as a human too?
