### ISSUE TITLE
Voice changer gas mask doesn't function as a gas mask

### ISSUE THREAD

**Issue by NicoSGF64** [space-wizards/space-station-14#11641]
## Description
Title. If you wear the voice changer gas mask, you can't use it as a normal mask, meaning you can't connect it to a O2 tank and use it to breathe.

**Reproduction**

1. Buy the voice changer gas mask from the traitor uplink.
2. Wear the gas mask in an oxyless environment.
3. Slowly suffocate since you can't activate the gas mask as a breathing tool.
4. Die.

**Additional context**

N/A

**Comment by vulppine** [comment]
cannot replicate, wearing the voice mask gives you the correct action to turn on the mask which allows you to connect it and it allows you to connect the air through the internals icon on the side of the screen, and you can also connect through the in-game window when using the tank in-hand

**Comment by NicoSGF64** [comment]
Since this issue is pretty old, unreproducible and probably due to and old bug (or still active, I don't know) where action icons disappeared. Closing it.
