### ISSUE TITLE
Zombies after melee rework

### ISSUE THREAD

**Issue by asperger-sind** [space-wizards/space-station-14#11663]
## Description

You as a zombie on client-side look like you're punching instead of clawing things, the range is also really weird.
**Reproduction**

1. Zombify yourself
1A. Look at another zombie
2. Attempt to claw something, it shows up as a punch
2A. The other zombie attempts to claw something, it shows up properly.
3. Cry as you cannot claw, yet can only punch.

**Comment by metalgearsloth** [comment]
Pretty sure this was fixed.
