### ISSUE TITLE
Gas tanks should only fit in exo / pocket slots

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#11676]
And only the small versions fit in pockets. Anything else needs to be held or go in exo slot.

Apparently some go in belt slots.

**Comment by SpliTistiC** [comment]
Only small air tanks go in belt slots, completely normal -wearing a small air tank in your belt is literally a non issue. This even prevents players from having toolbelts or any other belt- its neat to have as it has a nice sprite. Maybe pair it with a jetpack and get more use out of your fuel but for the most part I'd say leave it as is.

**Comment by lzk228** [comment]
isn't that done?
