### ISSUE TITLE
We need a way to define UserBoundInterface close behavior

### ISSUE THREAD

**Issue by ghost** [space-wizards/space-station-14#1167]
Right now it just automatically closes if you get too far away from the entity the UserBoundInterface is on (i.e. too far away from the computer), but we should be able to override some function to write our own checks that run every tick (or something along those lines)
For instance, the reason I bring this up is that I want to make the scalpel UserBoundInterface close if you drop the tool or get too far away from the person you're operating on. Right now, it will only close if you drop the scalpel and walk away from it.

**Comment by mirrorcult** [comment]
activatableui handles most of this on the content side
