### ISSUE TITLE
Disarm should do stamina damage

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#11684]
Credit to Emo for the idea.

The issue atm is there's a hidden RNG chance to it so it feels kinda bad to use even as a last resort because you the receiver might go down in 1 disarm which doesn't feel fair on their end, or it might take you 10 tries. If it did consistent stamina damage it would be more of a conscious choice to use.

**Comment by keronshb** [comment]
How difficult would shoving be? I feel it could work well if that wasn't a potential physics nightmare.

**Comment by metalgearsloth** [comment]
Do you mean moving someone else? If so it's going to mispredict.

**Comment by keronshb** [comment]
Yeah using a "push" to move someone else.
