### ISSUE TITLE
Access Worn Inventories

### ISSUE THREAD

**Issue by Acruid** [space-wizards/space-station-14#117]
There needs to be the ability to access the inventories of worn items, like backpacks and tool belts.

Requirements:
- [x] Ability to access the contents of a worn inventory without unequipping it.

It is your choice how you want to implement this. The backpack or belt contents could always be displayed as a toolbar at the bottom of the screen, or you could open a UI element when clicking on the item in the character screen.

**Comment by Injazz** [comment]
it could use some little button that appears in inventory slot window only for worn inventories

**Comment by ShadowCommander** [comment]
I'm going to attempt to work on this.

SS13:
Click with empty hand
ActivateItemInHand while holding Storage item
Dragging Storage item onto character

SS14:
Click with empty hand
ActivateItemInWorld while hovering over the Storage item
ActivateItemInHand while holding Storage item
Click the small storage icon

**Comment by Acruid** [comment]
This appears to be completed. Nice Job!
