### ISSUE TITLE
Weapon swapping increases attack speed

### ISSUE THREAD

**Issue by Streaky-Haddock** [space-wizards/space-station-14#11700]
## Description
Rapidly swapping weapons allows you to avoid cooldown on weapons both ranged and melee. I'm told this has been an issue with ranged weapons for a while. However since the melee rework I have observed players tunneling through windows and in one case, a traitor with two eswords putting people multiple into soft crit before they could react. This seems like unintended behaviour which.

**Reproduction**
1) Equip a weapon in each hand.
2) Toggle Combat Mode On
3) Attack
4) press X quickly
5) Attack
6) Repeat steps 3-5

**Screenshots**

**Additional context**

**Comment by HoidC** [comment]
You can't avoid cooldowns, you can use the weapons independently of each other though, which means if you have two eswords as I did, you swing at twice the speed as you use one after the other.

**Comment by keronshb** [comment]
This is just hidden tech like wavedashing.


(No it isn't but it's funny)

**Comment by lzk228** [comment]
i remember merged pr for cooldown after swapping
