### ISSUE TITLE
In certain conditions midi instruments can crash the client

### ISSUE THREAD

**Issue by ProfanedBane** [space-wizards/space-station-14#1170]
It appears that some combination of playing midi instruments, stopping and restarting playback, replaying songs, walking away from the instrument, playing 2 instruments at once and closing the midi window can cause a crash with a "System.ObjectDisposedException: Cannot access a disposed object." error.

I've caused the crash 5 times while trying to, however I've had no luck getting a reliable reproduction path, instead here's 2 videos that start with me logging on and end with the crash.

https://www.youtube.com/watch?v=YncB46_3ZKY
https://www.youtube.com/watch?v=nMFDJqxrnw4

**Comment by Zumorica** [comment]
Fixed since MIDI renderers are now disposed on the MIDI thread itself.
