### ISSUE TITLE
Network messages don't get sent if you delete the calling object in the same tick

### ISSUE THREAD

**Issue by ghost** [space-wizards/space-station-14#1171]
Disclaimer: only tested with UserBoundInterfaceMessage, but I would assume it works the same for every network message.
Steps to recreate: 
1. Have server component
2. From that component, send a message to a UserBoundInterface then delete the entity that it is residing on
3. The message is never actually sent
In my case I had a DroppedMechanismComponent that would send a "CloseSurgeryUI" message to the UI then delete itself (since you're jamming the organ into the body). The message was never received by the client.

**Comment by PJB3005** [comment]
I'm not sure this could ever work sanely because net messages are processed *after* the game states are applied.

**Comment by moonheart08** [comment]
Still an issue? @PJB3005

**Comment by PJB3005** [comment]
No idea

**Comment by mirrorcult** [comment]
this doesnt matter anymore since we dont have comp messages
