### ISSUE TITLE
StackSystem: This function and it's callers need to be un-hardcoded.

### ISSUE THREAD

**Issue by Mervill** [space-wizards/space-station-14#11714]
https://github.com/space-wizards/space-station-14/blob/56722c0c381b4319a7e262930ab8cb1f64627240/Content.Server/Stack/StackSystem.cs#L90-L111

- Hardcoded data strings bad
- SpawnMultiple(...) is fine but needs to be generalized for use by something other then biomass
- Easy / Good for Beginners?

**Comment by EmoGarbage404** [comment]
Give me an hour.

**Comment by EmoGarbage404** [comment]
this will take more than an hour i'm doing general refactoring now
