### ISSUE TITLE
signal buttons cannot be interacted with on walls

### ISSUE THREAD

**Issue by Emisse** [space-wizards/space-station-14#11736]
players cant click buttons on walls as of today. seem to be obscured by the wall for some reason, no issue with other wall mounts.
![image](https://user-images.githubusercontent.com/99158783/194438725-2f09a626-ffb8-40f6-b3fc-f41c73d2aeb6.png)
![image](https://user-images.githubusercontent.com/99158783/194438744-d529ab04-b172-4c44-93a3-3f6d72a19cb8.png)

**Comment by Emisse** [comment]
this applies to buttons on the floor as well so its just buttons in general are fucked

**Comment by metalgearsloth** [comment]
It's likely the non-fixture codepath in InRangeUnobstructed is doing something funky because buttons aren't anchored.

**Comment by metalgearsloth** [comment]
Alright so buttons have fixturescomponent but no fixtures so it should just be a prototype update to fix.
