### ISSUE TITLE
No water in chemical dispenser.

### ISSUE THREAD

**Issue by gardenBanter** [space-wizards/space-station-14#11730]
Water should be available in a chemical dispenser. It's very strange that it isn't.

**Comment by moonheart08** [comment]
Not an issue, intended functionality and the dispenser is actually due for removal entirely.
https://github.com/space-wizards/space-station-14/milestone/3

**Comment by gardenBanter** [comment]
I won't put obstacles in the way of my players' fun. I'm sure that the work to redesign it will be worth it.

**Comment by mirrorcult** [comment]
> I won't put obstacles in the way of my players' fun.

make sure to make them all invulnerable and let them freely spawn any chemicals they want as well, then

**Comment by gardenBanter** [comment]
I of course don't wish to diss your design choices (as we all can always just fork off whenever we disagree) but I simply feel like some of them are too tedious to justify and in the end provide nothing but an obstacle in the way of fun. These include cloning requiring biomass or chemistry not having water. If the endgoal of ss14 is realism at all costs then go for it.

**Comment by mirrorcult** [comment]
like i said--if your main concerns are 'obstacles in the way of fun', you should start by removing the ability for players to die

**Comment by gardenBanter** [comment]
Pointless hyperbole.

**Comment by mirrorcult** [comment]
dying and being taken out of the round stifles a lot of the fun players might have; it can feel frustrating, even, to have such an obstacle to your fun. of course, the objection here is that the ability for players to die introduces much more depth and fun (medical system, the consequences of death motivating players to engage with mechanics that help them avoid it) than if the mechanic had not been there. this is true for the other 'obstacles to player fun' we intend to add as well

**Comment by gardenBanter** [comment]
interesting != tedious

**Comment by mirrorcult** [comment]
its good that our mechanics are interesting and not tedious, then

**Comment by civilCornball** [comment]
I… think this discussion’s over? You two have a knack for writing these comments in a really passive-aggressive way.

**Comment by gardenBanter** [comment]
Why are you being so pointlessly aggressive in such a tediously passive way? We're just talking. What I meant is that limiting basic functionality in this way is not interesting, it's just tedious. It's the equivalent of having to do *inhale and *exhale. When you die, you think "ugh, I could've prevented this by XYZ", when you have to go through hoops to get water as a chemist, you don't think that's interesting. All you think is the "ugh".

**Comment by civilCornball** [comment]
Please don’t continue this.

Could someone prevent further discussion here?
