### ISSUE TITLE
certain chairs consistently causing teleports to 0,0 of map

### ISSUE THREAD

**Issue by Emisse** [space-wizards/space-station-14#11738]
leave chairs found to have this property under this issue
![image](https://user-images.githubusercontent.com/99158783/194440173-79503ff4-f7d2-423f-ad2b-8efe380cd6ee.png)
syndie shuttle chair bagel
![image](https://user-images.githubusercontent.com/99158783/194440205-b7020465-17e7-4f86-84e3-157d04eac964.png)
arrivals nt office chair bagel

**Comment by ElectroJr** [comment]
Should hopefully be fixed by #11950. If not, reopen
