### ISSUE TITLE
You cannot recharge a disabler using a recharger on a table

### ISSUE THREAD

**Issue by Stealthbomber16** [space-wizards/space-station-14#11731]
I haven't tested this with anything other than a disabler yet, but I know for sure the table was the problem.

Steps to reproduce:
Enter an entity body (Urist) (This step is important, this bug cannot be replicated from admin ghost due to table spaghetti code)
Place an empty disabler in a recharger that is on a table
Watch as the disabler enters the recharger then gets picked back up again.

**Comment by ElectroJr** [comment]
I cant test this atm, but based on the description:
> Watch as the disabler enters the recharger then gets picked back up again.

The client is mispredicting that the insertion is allowed, in which case something else is also going wrong. Even if #11748 seemingly fixed the issue this should stay open until someone figures out what caused the mispredict.

**Comment by Kromabae** [comment]
this is the same as the batteries not able to recharge #11746

**Comment by Streaky-Haddock** [comment]
Last night, as Warden, I used a table recharger to recharge my laser gun. It appeared to work. I haven't attempted with a disabler.

**Comment by ElectroJr** [comment]
#11748 fixed the no-fixtures interaction bug, and space-wizards/RobustToolbox/pull/3301 fixed the mispredict, so I'll close this issue. However, the lack of fixtures for things like chargers is still an issue and shouldn't be closed (see #11760)
