### ISSUE TITLE
Putting batteries in Battery Recharger instantly puts them back in your hand

### ISSUE THREAD

**Issue by Kromabae** [space-wizards/space-station-14#11746]
## Description
Small issue with batteries (which never see the light of day because not enough items use batteries in a significant way anymore *cough* laser rifles)
**Reproduction**

1. print battery
2. attempt to recharge it
3. batter gets put in hand as soon as you put it in the recharger

**Additional context**
I dont know what got merged but something broke a ton of things

**Comment by mirrorcult** [comment]
dupe #11731
