### ISSUE TITLE
Unable to construct wallmounted gen, APU and sub

### ISSUE THREAD

**Issue by Kromabae** [space-wizards/space-station-14#11740]
## Description
Unable to get past the "insert 5x LV cables stage of the constuction

**Comment by BasedUser** [comment]
One workaround for this is to place those first, *then* place the wall

**Comment by Kromabae** [comment]
didn't even work when i took the walls off

**Comment by metalgearsloth** [comment]
May be related to https://github.com/space-wizards/space-station-14/issues/11736

**Comment by deltanedas** [comment]
gen apu and sub all work when constructing, there only seems to be the issue of deconstructing them now. might look at graph later.

**Comment by IProduceWidgets** [comment]
Seems fixed.
Constructed:
![image](https://github.com/space-wizards/space-station-14/assets/107586145/1b44d66a-c313-4f5d-94c4-7895f6b95d1d)
Deconstructed:
![image](https://github.com/space-wizards/space-station-14/assets/107586145/c3a9274e-d656-462a-aca9-291cc1ae8f31)
