### ISSUE TITLE
Station time is still bugged.

### ISSUE THREAD

**Issue by asperger-sind** [space-wizards/space-station-14#11761]
## Description

The station timer in the latejoin menu is still incorrectly showing time, as far as to never get updated and just get stuck at any number it wills to get stuck at, but commonly in the range of 1-2 minutes.

**Screenshots**

![image](https://user-images.githubusercontent.com/38016303/194685148-e6cc57b1-0194-48d6-b2d8-782e2cd95f52.png)

**Additional context**

Happens on lizden to me all the time, not sure about others.

**Comment by Mervill** [comment]
I was watching the lizard time for a while and it seemed accurate. The format here is `Hours : Minutes` which is a bit unintuitive. It could easily be changed to be more legible
