### ISSUE TITLE
Building/Machine UI Framework

### ISSUE THREAD

**Issue by Acruid** [space-wizards/space-station-14#118]
Most machines in SS13 have some sort of floating UI window that opens up when activated. We need a system in place that can manage opening up UI windows when a client activates an entity.

Requirements:
- [x] A generic ECS Component that can be added  to an entity that controls this system.
- [x] Ability to data bind a specific UI Class to this component through Yaml.
- [x] Opening the UI and pushing any required data to the client (Subscribing the client).
- [x] Detecting any Client events like button presses and pushing them back to the server.
- [x] Processing user events on the server.
- [ ] Detecting conditions for Unsubscribing the client from the Building UI System (like them dying, or moving out of range).

The specific UI classes bound to the components will be in charge of network communications, populating the UI with controls, and processing user events. There will probably be a specific class for every type of machine in the game.

The Inventory UI system is a decent working example of a similar system. You may want to research UI design patterns if you are new to UI programming, and you will need to know how to work with the Godot UI system exposed in SS14.

This issue requires https://github.com/space-wizards/space-station-14-content/issues/115 so that UI Windows are properly closed when the mob becomes incapacitated/blind.

**Comment by Injazz** [comment]
i think it can be closed

**Comment by Acruid** [comment]
The last checkbox will be resolved in https://github.com/space-wizards/space-station-14/issues/118. Regardless, there is no reason to reopen this issue.
