### ISSUE TITLE
Stealth boxes need to be balanced and added to uplinks.

### ISSUE THREAD

**Issue by ElectroJr** [space-wizards/space-station-14#11804]
#11569 added box entity prototypes, but they are not yet mapped anywhere or otherwise accessible.
The normal boxes should probably be craftable or added to maps, while the the stealth/cloaked variant should probably be added to the traitor uplink, though its stealth gain/loss rate might need balancing first.

**Comment by keronshb** [comment]
I'll be taking care of this after the implant PR.
