### ISSUE TITLE
Grafana error spam from grids

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#11806]
From what I can tell it looks like the emergency shuttle though I'm not sure if this was in the normal  course of a round or if an admin spawned it.

![image](https://user-images.githubusercontent.com/31366439/194782603-d282355b-f85e-467c-9f81-108af9e029eb.png)

**Comment by ElectroJr** [comment]
The `SaveLoadMultiGridMap` test also seems to be occasionally failing, though because of how they handle error logs they don't actually specify what the exception is, but chances are it is related.
