### ISSUE TITLE
Lizard claws can tear through everything that is damageable and isn't a reinforced window

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#11808]
## Description

A pack of lizards can clawn a normal wall and easily tear it down, with three lizards it takes around 30 seconds. 
I believe this happens because buildings are not resistant to pierce, humans use blunt so it bounces off
**Reproduction**

Toggle harm mode
Punch furniture, windows, walls
You will deal damage to them and with patience, destroy them
**Screenshots**

**Additional context**

**Comment by asperger-sind** [comment]
Correct, normal walls use the Metallic damage modifier, which has 5 blunt flat reduction.
Albeit I don't believe that this is actually a problem, and fixing it by just adding 5 flat pierce is going to cause problems for when people want to break walls with a better method that punching it 40 times.

**Comment by Golinth** [comment]
This was fixed by the structural rework and can probably be closed
