### ISSUE TITLE
Reinforced walls break faster than regular steel solid walls

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#11812]
## Description
Reinforced walls are quite easy to destroy with a number of melee weapons. They are also **Easier** to destroy than regular steel solid walls. While testing i found that a rwall would break in 29 toolbox hits. I hit a sold wall with the same toolbox over 60 times and it still didn't break

Edit: the solid wall broke in about 75 melee hits with a toolbox.

**Reproduction**
Hit walls with melee weapons and count the hits.

**Additional context**
Reinforced walls should take more hits to break than solid walls do. I'm not sure if solid walls are broke or if something funky is going on, but solid walls should not be harder to destroy.

**Comment by asperger-sind** [comment]
Pretty sure it is because rwalls don't have any flat or percentage resistances, or even a damage modifier, normal walls do, and they're especially good against blunt.

**Comment by Kayek14** [comment]
Hmm so is this just a case of the rwalls missing percentage resistances? You would think a wall made out of advanced plasteel would hold up better than regular old steel

**Comment by Mervill** [comment]
this can be closed (was not properly closed by the pr)
