### ISSUE TITLE
Items get stuck on firelocks when mapped over conveyor belts.

### ISSUE THREAD

**Issue by ChilbroBaggins** [space-wizards/space-station-14#11820]
Something I noticed while playing cargo on Lighthouse this weekend, the firelocks over the conveyor belts prevent things from passing over them. The items get stuck. I also just noticed this on a map I was testing on the Nyano fork. 

After round start, if you delete the firelock and replace it, the items pass over normally, so it's just on firelocks mapped before initialization.

**Comment by Carbonhell** [comment]
Maybe it's related to #11727 ?

**Comment by keronshb** [comment]
Can you replicate this? I've been trying to get items stuck on lighthouse, but haven't been able to do it. But I have been able to noclip crates through firelocks.

**Comment by ChilbroBaggins** [comment]
> Can you replicate this? I've been trying to get items stuck on lighthouse, but haven't been able to do it. But I have been able to noclip crates through firelocks.

So, I just tested on LH and Tortuga from Nyano server. (It was also happening on that map.) And it doesn't seem to be happening anymore. Perhaps the merged PR above fixed it? I'd say close the issue unless anyone else has noticed it happening since I posted it?
