### ISSUE TITLE
Explosions dont get affected by the DestructibleComponent damageValue

### ISSUE THREAD

**Issue by AJCM-git** [space-wizards/space-station-14#1182]
1. Modify a wall to have an absurd amount of "HP" (thresholdvalue)
2. Shoot that wall 
- Its impossible to break it like this, works as intended
3. Explode a grenade near it
- it breaks as if it had the default "HP"

This one is quite important to fix before the test

**Comment by ComicIronic** [comment]
This is a generic problem with stuff like `IExAct` - if you just hardwire interactions, they don't make sense.

**Comment by F77F** [comment]
> This one is quite important to fix before the test
I keep seeing this. What test?

**Comment by ShadowCommander** [comment]
We're doing a stress test on the 24th at [7 PM UTC](https://www.thetimezoneconverter.com/?t=7%3A00PM&tz=UTC&).

Also, if you aren't already you should join us on the [Discord](https://discord.gg/t2jac3p).

**Comment by F77F** [comment]
> We're doing a stress test on the 24th at 7 PM UTC.

Ah, okay. I'll be there.

> Also, if you aren't already you should join us on the [Discord](https://discord.gg/t2jac3p).

Eh, no thanks. That's not my cup o' tea.

**Comment by Injazz** [comment]
we also have IRC `irc.rizon.net#spacebus`, it has bridge with our dev channel on discord so you won't miss out on anything that matters

**Comment by Injazz** [comment]
I ported IExAct from ss13 codebase (/vg/), but it's trivial to make explosions to just deal damage directly. The only issue here is get the number right.
