### ISSUE TITLE
Getting stuck at the connection window connecting to WizDen servers

### ISSUE THREAD

**Issue by Partmedia** [space-wizards/space-station-14#11821]
## Description
This is an issue to collect multiple reports from players that they get stuck at the connecting window when connecting to WizDen servers after 76bd5e93b4c4d85.

Some affected have tried to connect to multiple WizDen servers in geographically distinct areas and failed to connect.

Clearing cached engine/client data does not fix the problem.

We probably need someone with WizDen server access to pull the logs and see if there are relevant errors.

**Reproduction**
Appears to be consistently reproducible for those affected. Unclear what makes people affected.

**Screenshots**
![2022-10-10_09-57](https://user-images.githubusercontent.com/3229565/194918309-d86829c2-b879-4bcb-b612-9d4a1335985f.png)
![2022-10-10_09-58](https://user-images.githubusercontent.com/3229565/194918316-1d617de6-46eb-42fb-84a3-17c30acc4c38.png)
![2022-10-10_10-01](https://user-images.githubusercontent.com/3229565/194918325-8cfa0996-d957-4026-a840-e80057087541.png)

**Additional context**

- PJB tried to debug the issue by changing some settings on one of the EU servers, no luck.
- Report with similar "getting stuck" symptom here: https://github.com/space-wizards/SpaceWizards.Lidgren.Network/issues/6, unclear if this is related.

**Comment by Partmedia** [comment]
@Morb0 would you be willing to try this patch against Lidgren.Network for me? This lifts the `return false` statement out of the if statements so that `ActuallySendPacket` correctly reports to the caller if an exception is ever raised.

```
diff --git a/Lidgren.Network/NetPeer.LatencySimulation.cs b/Lidgren.Network/NetPeer.LatencySimulation.cs
index ba3261d..3b4c5c9 100644
--- a/Lidgren.Network/NetPeer.LatencySimulation.cs
+++ b/Lidgren.Network/NetPeer.LatencySimulation.cs
@@ -189,19 +189,19 @@ namespace Lidgren.Network
 				{
 					// send buffer full?
 					LogWarning("Socket threw exception; would block - send buffer full? Increase in NetPeerConfiguration");
-					return false;
 				}
 				if (sx.SocketErrorCode == SocketError.ConnectionReset)
 				{
 					// connection reset by peer, aka connection forcibly closed aka "ICMP port unreachable" 
 					connectionReset = true;
-					return false;
 				}
 				LogError("Failed to send packet: " + sx);
+				return false;
 			}
 			catch (Exception ex)
 			{
 				LogError("Failed to send packet: " + ex);
+				return false;
 			}
 			finally
 			{
```

**Comment by Morb0** [comment]
@Partmedia I don't think it can be done easily, it requires own fork of the engine at least.

**Comment by Partmedia** [comment]
Bisected with one of the reporters affected, the first commit that started getting stuck connections was 386c7f922.

In case it matters, working commit (previous one):
```
[DEBG] szr: Finalized string mapping of size 88767 in 134ms
[DEBG] szr: Wrote string package in 32ms size 459.88 KiB
```

Broken:
```
[DEBG] szr: Finalized string mapping of size 88810 in 147ms
[DEBG] szr: Wrote string package in 33ms size 460.11 KiB
```

I fail to see how this commit causes this issue, but these are the bisection results.

**Comment by Partmedia** [comment]
Folks are able to connect after reverting the offending commit from master (76bd5e93b4).

Reverting that commit also brings this down to:
```
[DEBG] szr: Finalized string mapping of size 88767 in 147ms
[DEBG] szr: Wrote string package in 33ms size 459.88 KiB
```

Have we ever exceeded 460 KiB of mapped strings?

**Comment by PJB3005** [comment]
I can't imagine how that number is in any way special, what the hell.

**Comment by Just-a-Unity-Dev** [comment]
One user on discord had this issue and said they fixed it by turning off compatibility mode

![image](https://user-images.githubusercontent.com/67359748/194968754-cd9d0a8a-a813-4dd9-8b99-d68f93bf0e9d.png)

**Comment by Partmedia** [comment]
Sounds like the bisect might have been correct, and the shader introduced in the offending commit is not compatible, and not being able to compile shaders prevents the client from entering the lobby?

**Comment by ElectroJr** [comment]
Ah yeah the shader fails to compile. I'm pretty sure I tested it in compat but maybe subsequent changes broke it.

**Comment by ElectroJr** [comment]
#11833 Should fix the shader, but if this was causing the other connection issues that should have been apparent from the logs, so something else is probably also wrong?

**Comment by PJB3005** [comment]
I mean... did we ask anybody who had the issue for their logs..?

**Comment by Just-a-Unity-Dev** [comment]
I'm fairly sure we said the `!logging` command more than once

**Comment by Partmedia** [comment]
Closed since the reporter confirms they're able to connect. The exceptions seen on Corvax appear unrelated, but definitely still worth investigating. Sounds like this could have been fixed much easier if someone actually followed the `!logging` steps, but bisecting worked.

**Comment by PJB3005** [comment]
Well good thing I don't have to ask people to bear with me setting up Wireshark traces... for now.

**Comment by Partmedia** [comment]
Don't jinx it!

```
!wireshark
Install this fun unsigned kernel pcap driver...
```
