### ISSUE TITLE
Admin logs searching for chat are buggy

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#11831]
I'm not sure what exactly it's due to, e.g. other exceptions, search filter shenanigans, or what, but on round 16023 while playing the game it's not showing me chat I know people said (i.e. looking for slurs).

One of the slurs in question was at least on grafana so I had some evidence. Not sure if this happens to any other log category.

**Comment by metalgearsloth** [comment]
Okay I realised the search filter is case sensitive so maybe it shouldn't be?

**Comment by JazzGlobal** [comment]
Is this just for the sake of filtering / reviewing chat logs? Since this is useful for administration and punishing unwanted behavior, I would think you shouldn't have to match the exact phrasing / chat the user sent to make it appear in a search list.
