### ISSUE TITLE
Well now Nukies can't detonate the bomb on the station

### ISSUE THREAD

**Issue by Stealthbomber16** [space-wizards/space-station-14#11854]
Nukies need a way to get the codes for the nuke on-board the station as of #11665 since the codes are not available to them as-of roundstart.
![image](https://user-images.githubusercontent.com/100171035/195201453-696d4d9f-12e5-4ccd-8d37-a2319038079e.png)

**Comment by mirrorcult** [comment]
this is intended, they're supposed to use their own nuke

**Comment by EmoGarbage404** [comment]
I get that it might be intended, but it really brings the purpose of the on station nuke if its literally impossible to detonate.

**Comment by mirrorcult** [comment]
impossible to detonate without admin intervention

**Comment by GoodWheatley** [comment]
> I get that it might be intended, but it really brings the purpose of the on station nuke if its literally impossible to detonate.

That’s how it works in SS13, the codes for it doesn’t even exist unless an admin spawns them in. Only supposed to be detonated through admemes or a lone op
