### ISSUE TITLE
UI refactor issues with context menus and hotbars

### ISSUE THREAD

**Issue by GreenPartyhat** [space-wizards/space-station-14#11869]
## Description
The right-click options for survival boxes in bags seem to not work, as well as the "Close UI" options for bags. The "Close UI" did not work for the salvage bag, I am unsure about other bags. Lastly, emergency tanks in the pockets do not seem to have an icon that appears on the left hotbar, and breath masks seem to not appear either.

**Reproduction**
Attempting to right-click a survival box, no menu appears. Equipping an emergency oxygen tank and breath mask do not make the icons appear on the left for quick use. I have not tried with a normal-sized oxygen tank.

**Screenshots**
I do not have any screenshots that would suffice. 

**Additional context**
N/A

**Comment by metalgearsloth** [comment]
Already fixed in https://github.com/space-wizards/space-station-14/pull/11867
