### ISSUE TITLE
No sleep/wake up action

### ISSUE THREAD

**Issue by neoscav** [space-wizards/space-station-14#11870]
## Description
The sleep action doesn't show up in the toolbar when you lay in a bed, it also doesn't show up in the actions menu. Falling asleep trough the trait narcolepsy will make you unable to wake up due to missing wake up action both in the toolbar and action menu.

**Reproduction**
 Lay in a bed / Fall asleep trough Narcolepsy trait.

**Screenshots**
![unknown](https://user-images.githubusercontent.com/115652258/195395798-2125f1ba-0b2b-490c-9c0b-7ea56f02193c.png) ![Screenshot 2022-10-12 181329](https://user-images.githubusercontent.com/115652258/195394775-26536100-882a-43ab-a4a5-1deaa4a6d242.png) 
![unknown (1)](https://user-images.githubusercontent.com/115652258/195395961-e6cca01b-ad2b-4cd8-b47b-81692585f18d.png)

**Additional context**
This issue happened after the new UI got implemented

**Comment by mirrorcult** [comment]
added/removed actions appear to never actually affect the UI

**Comment by mirrorcult** [comment]
was this fixed?

**Comment by ElectroJr** [comment]
It should've been fixed by #11899 but I haven't actually bothered to test, I'll do that now.
