### ISSUE TITLE
PDA Interaction issues

### ISSUE THREAD

**Issue by Jezithyr** [space-wizards/space-station-14#11874]
## Description
Players are reporting some issues interacting with PDA. More specific info needed. Placing the PDA on the ground then interacting with it appears to fix the issue.

**Reproduction**
Needs more info

**Screenshots**
![Discord_xCD8oQEAyi](https://user-images.githubusercontent.com/6192499/195430726-7a89ce1b-886a-4e58-b7d5-0bcc79199eab.png)

**Additional context**
N/A

**Comment by mirrorcult** [comment]
1 report ive seen is that inventory slots dont react to activation with E which i can repro

**Comment by mirrorcult** [comment]
or rather, the PDA doesnt, other thing like backpack seem to

**Comment by mirrorcult** [comment]
actually no, this is a general thing. apparently slots just snowflake this behavior for backpacks in `ServerInventorySystem:43`
