### ISSUE TITLE
Equiping a hardsuit wont automatically put its assigned actions to your action bar

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#11883]
## Description
Usually if you equip a hardsuit it will automatically assign a key for 'Toggle Helmet' and 'Toggle Headlamp' 

Now however, if you equip one, none of these keys will be assigned. You will have to manually assign a key to it using the actions menu.

**Reproduction**
Equip a hardsuit that has a toggle helmet and toggle headlamp function.

**Additional context**
I think the new hud refactor broke this, but not 100% sure.

**Comment by civilCornball** [comment]
Quoting Mirrorcult, from the discord:
“the only time action buttons are updated is when a new actioncomp is linked”

It’s not just the hardsuit.
