### ISSUE TITLE
Action bar needs to be reworked

### ISSUE THREAD

**Issue by GoodWheatley** [space-wizards/space-station-14#11895]
## Description

This has been bugging me for a while now, and with the HUD refactor merged I think it's finally time to bring this up. I feel that right now, the action bar is fundamentally flawed and needs to be reworked. Just 10 actions per page isn't that annoying right now, but with the trend of antag abilities getting a place on the action bar, it eventually will become a problem. Case in point: An engineer wearing a hardsuit, gas mask, oxygen tank, and jetpack will have 11 actions by default on the bar, necessitating a swap between pages to use all their equipment. Not that much of a concern right now (except if they're also putting verbs on the bar) but what happens when a Changeling becomes an engineer with that same gear? It would mean they'd either have to keep swapping between action bar pages to use abilities and toggle combat mode, or have to set up the action bar for combat, which is unfun and immersion breaking.

Right now I see 3 solutions for this:
1. Move actions off the action bar and make them into verbs. (Should be easy but verb menu is already getting cluttered at this point)
2. Redo the entire action bar system to be less unwieldy (Probably going to be a lot of work)
3. Allow players to make custom hotkeys for certain actions (Yes I know the 0-9 hotkeys exist but I'm thinking of binding a key to a specific action, not an action bar slot)

I know this might not be a major concern right now, but with the HUD refactor finally merged it should be easier to fix this when it actually becomes an issue when Changeling is inevitably added.

**Comment by Jezithyr** [comment]
I second this, although overall the entire action system could use a proper rework. The whole point of the HUD refactor was primarily to rewrite the backend to be more modular and keep feature parity with the old hud. Redoing actions entirely was something I considered but ended up being waaaaay out of scope for an already massive refactor.

**Comment by Flareguy** [comment]
Fixed with #21352.
