### ISSUE TITLE
Demonstrate Weapons Actually Working

### ISSUE THREAD

**Issue by Acruid** [space-wizards/space-station-14#119]
Demonstrating guns and melee weapons actually doing damage will be a big milestone. This will show the there is actually some basic form of game to play, even if it is just endless deathmatch for now.

Requirements:
- [x] Guns consume their specific ammo when fired.
- [x] Guns will not work without ammo.
- [x] Guns damage other entities.
- [x] Melee weapons either swing in an arc or stab toward the target, doing damage to everything in the arc.
~~Unarmed mobs will punch with their hands, doing damage.~~ (Requires an intent system, out of the scope of this.)
- [x] Thrown objects will collide with entities and damage them based on mass.

This requires https://github.com/space-wizards/space-station-14-content/issues/115.

**Comment by ScumbagDog** [comment]
This requires #138 too

**Comment by Acruid** [comment]
Congrats, people can shoot and stab each other to death!
