### ISSUE TITLE
Revenant's Shock can make lights flicker forever

### ISSUE THREAD

**Issue by Mirino97** [space-wizards/space-station-14#11904]
## Description
Pretty descriptive title

**Reproduction**
1: Be Revenant
2: Shock area
3: Infinite drab white rave

**Screenshots**
(this has been going on for 5 minutes)
https://user-images.githubusercontent.com/52474532/195708878-e3ae07db-da7b-4faa-9a49-d16141c3e7ea.mp4

**Comment by EmoGarbage404** [comment]
Seems like a clientside component removal issue? Isnt this also an issue with jitter?

**Comment by metalgearsloth** [comment]
These components are getting iterated even without revenant I think.

See https://github.com/space-wizards/space-station-14/pull/11894 coz the component is showing up on a profiler.
