### ISSUE TITLE
Dangerous entsys bug that hangs inputs and lags server 

### ISSUE THREAD

**Issue by Emisse** [space-wizards/space-station-14#11914]
![image](https://user-images.githubusercontent.com/99158783/195796528-0f599010-ef18-4e23-8ea5-e8c755bd5ae0.png)
This occurred to me when an admin was following me, we were both aghost, it made my inputs hang and caused server to lag. It made me unable to right click inspect myself. Not really any more information yet. @vulppine might also have info about it

**Comment by ElectroJr** [comment]
The only way I can see that error happening is if someone set a sprite or layer's scale to zero, but that shouldn't lag the server. Was this the only error? I guess its also possible there was some other simultaneous issue?

space-wizards/RobustToolbox/pull/3339 should hopefully prevent this specific error.

**Comment by Emisse** [comment]
still issue but the cause for this is an obscenely small sprite being interacted via right click with so its probably not relevant anymore
