### ISSUE TITLE
You can turn containment field generators into lamps

### ISSUE THREAD

**Issue by Just-a-Unity-Dev** [space-wizards/space-station-14#11927]
## Description

AKA CFG lights persist even when off

**Reproduction**

1. Fire emitters at a CFG line
2. CFG line lightens
3. Turn off emitter
4. CFG line fades away
5. CFG is now a cool ass lamp

**Screenshots**

![image](https://user-images.githubusercontent.com/67359748/195970441-4b29a63d-0807-42e4-a97e-39c390d17bc5.png)
![image](https://user-images.githubusercontent.com/67359748/195970467-4f6626d9-ac1e-4d61-bc0f-4a9abb0db523.png)

**Additional context**

**Comment by Scribbles0** [comment]
wym this isn't an issue this is a feature:tm:

**Comment by keronshb** [comment]
Kind of a funny unintentional bug but it could be interesting to keep as a feature.

**Comment by moonheart08** [comment]
we need better lighting options
