### ISSUE TITLE
Speech Bubbles disappear behind game window

### ISSUE THREAD

**Issue by Mirino97** [space-wizards/space-station-14#11937]
![image](https://user-images.githubusercontent.com/52474532/196004275-3c510031-806c-4140-a98d-5ea6f6e0ba2c.png)

Don't know how this happened, I'll try to get some repro steps going.

**Comment by Mirino97** [comment]
Nabbed from our great Emisse from Discord, bringing it here for more visibility:

"Only happens after this nasty bug, persists between client restarts"
![image](https://user-images.githubusercontent.com/52474532/196005838-be096e9d-4cf3-4996-a8a7-287f575062de.png)

**Comment by ElectroJr** [comment]
AFAIK this has since been fixed
