### ISSUE TITLE
Mice can scream 

### ISSUE THREAD

**Issue by Zymem** [space-wizards/space-station-14#11947]
## Description

**Reproduction**

1) control a mouse
2) try to squeak
3) scream

**Comment by Mervill** [comment]
I have no mouse, and I must scream

**Comment by mirrorcult** [comment]
is it always screaming or is it doing a wilhelm scream sometimes because the latter is intended

**Comment by Zymem** [comment]
nope, straight up normal screaming, I even tested with different mice

**Comment by Zymem** [comment]
apparently squeaking is gone, you can only scream
![image](https://user-images.githubusercontent.com/97173622/196015379-63c51349-aa24-468e-9fe8-c1b7c3864a82.png)
