### ISSUE TITLE
Round start is not correctly marked as delayed if you join after it was actually delayed.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/space-station-14#1197]
Right now it just keeps doing the countdown.

**Comment by PJB3005** [comment]
@DrSmugleaf since you wrote the delay thing.

**Comment by DrSmugleaf** [comment]
> @DrSmugleaf since you wrote the delay thing.

That's strange, I can't replicate it on latest master myself. It changes to "Round Starts In: Paused" for me. Or should there be a message in the chat as well?
![image](https://user-images.githubusercontent.com/10968691/85447351-d0705a00-b595-11ea-8e1a-cd366ce7a2aa.png)

**Comment by PJB3005** [comment]
Yep, that's it.

**Comment by DrSmugleaf** [comment]
> Oh, I ran into this on the public server after Zumorica already paused it. Maybe it only happens if you connect _after_ the round was paused?

You make a fantastic point, on it.
