### ISSUE TITLE
Revolver speed loaders are broken.

### ISSUE THREAD

**Issue by Mervill** [space-wizards/space-station-14#12001]
## Description
They brokey. Also the mosin stripper clip (just acts like a speed loader).

**Reproduction**

- (developer mode)
- Spawn a revolver
- Empty the revolver (usually spawns loaded)
- Spawn a speed loader of the appropriate ammo type
- No worky 😞

**Comment by metalgearsloth** [comment]
Dupe:
https://github.com/space-wizards/space-station-14/issues/11837
https://github.com/space-wizards/space-station-14/issues/9896
