### ISSUE TITLE
Slipping INTO a wooden table and getting stuck

### ISSUE THREAD

**Issue by Errant-4** [space-wizards/space-station-14#12028]
Slipping on a banana peel towards a wooden table that is surrounded by "unoccupiable" tiles gets you stuck inside the table, presumably since you have nowhere to be moved off to when standing up. Visually it looks like you stand up on the table, but are not considered to be standing on it by the engine.
You can not move out of that specific tile, and you can not drag yourself off of the table. 
You can still drag yourself onto the table (either the one on your tile or an adjacent one) which transfers you into a normal state of standing on the table.
The first time, my character also started taking O2 damage while being "inside" the table, which ended when I dragged myself on top of it. I have not been able to replicate this part, however. Possibly, it ended up on the adjacent tile with the wall, instead of the table.

To replicate: Spawn on Omega, go to the break area, go through the glassed-off stage to enter the prop room under it, and  slip on the banana peel towards the table to the left
![slip](https://user-images.githubusercontent.com/35878406/196476148-3990a201-f942-401a-a557-e54f8a1e54f2.jpg)

**Comment by keronshb** [comment]
This is a repeat of known tunneling issues but thank you for the report!

**Comment by Visne** [comment]
This issue should probably just be closed right? As the issue is already known and probably tracked somewhere else

**Comment by dmnct** [comment]
I don't think it should be closed unless either the issue is resolved, or we have another specific issue to point at. If it's known, where is it

**Comment by Visne** [comment]
https://github.com/space-wizards/space-station-14/issues/10416 https://github.com/space-wizards/space-station-14/issues/9522 https://github.com/space-wizards/space-station-14/issues/8693 https://github.com/space-wizards/space-station-14/issues/11022
