### ISSUE TITLE
Remove map-specific jobs

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#12023]
AFAIK this is only boxer and https://github.com/space-wizards/space-station-14/pull/12020

They should be made clothes instead.

**Comment by moonheart08** [comment]
im going to implode

**Comment by S1ss3l** [comment]
Wait what is the current position on this topic ? Should map-specific jobs be a thing or not ?

**Comment by moonheart08** [comment]
> Wait what is the current position on this topic ? Should map-specific jobs be a thing or not ?

as per the fact it's closed, yes they should, someone let a few people out of the shed and i put them back in
