### ISSUE TITLE
All targeted actions don't function at all

### ISSUE THREAD

**Issue by Elijahrane** [space-wizards/space-station-14#12036]
## Description

**Reproduction**

1. Spawn smite spell book
2. Read it to gain smite action
3. Spawn urist
4. Try to smite urist using any method
5. Pressing the number assigned does nothing, clicking the action changes your cursor, but during none of these 'modal' interactions will clicking on urist do anything

Seems to apply to all entity target actions...? I confirmed on current upstream master with smite

**Comment by Elijahrane** [comment]
Confirmed also with:
- Stethoscope
- Devour
- All of my downstream ones

**Comment by DEATHB4DEFEAT** [comment]
experienced this issue with other spells too, fireball blink and carp

**Comment by Elijahrane** [comment]
> experienced this issue with other spells too, fireball blink and carp

seems to be all targeted actions then, not just entity target
