### ISSUE TITLE
Syndicate Reinforcements do not show up on Admin Tools as Antagonists

### ISSUE THREAD

**Issue by Streaky-Haddock** [space-wizards/space-station-14#12068]
## Description
Syndicate Reinforcements are not made Traitors, or antagonists of any sort. So they do not have objectives, do not show up as antags on Adminhelps or on Admin Overlay. So we only have equipment and the 'Roll Fizzlebeef' naming scheme to go by, which is not reliable. Sometimes admin logs doesn't track the purchase of reinforcements but i'll make a seperate issue for that.

![image](https://user-images.githubusercontent.com/93771043/196940911-da96d6c3-5d1b-44c4-8bcc-4276bbeb4536.png)

Seeing this outright can prevent a few Syndie Reinforcements from getting bwoinks/distractions that they don't actually require

Edit: This also means they dont get codewords and are targeted by syndicate turrets

**Comment by ZoldorfTheWizard** [comment]
related to #13519
