### ISSUE TITLE
Bolted unpowered doors can't be opened without power

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#12071]
If you accidentally bolt an unpowered door while hacking it stays permanently bolted until power is restored. Ideally you would still be able to unbolt even if it's unpowered.

**Comment by Streaky-Haddock** [comment]
I always understood this was intentional. This has always been the case in SS13, and figured it was because the multitool wasn't able to provide enough power to move the weight of the bolt down. 
In practice, this is a way to protect you or your department from people coming in with basic tools.

**Comment by PJB3005** [comment]
Yeah this has been a feature:tm: in SS13 for ages. It does make unpowered bolted airlocks a completely impassable obstacle AFAIK, but I don't think that's ever an issue in practice (go through walls).
