### ISSUE TITLE
Botany yaml needs fixing

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#12086]
- The locker includes some seeds. These should be in the seed vendor
- Cluster has botany tools mapped. These are already in the vendor.
- The locker includes just plant clippers. This is already in the vendor.
- Why are bananas and pineapples exotic seeds.

**Comment by Stealthbomber16** [comment]
Egg-Plant seeds need to be in the vendor if they aren't going to be in lockers on round-start anymore.

Tool vendor should have more tools or maps need to have no more than 2 botanists if botany tools shouldn't be mapped or in lockers.

**Comment by 0x6273** [comment]
Egg-plant seeds are in the exotic crate from cargo.

**Comment by lzk228** [comment]
So
1. Fixed in #22865
2. Is it really issue?? I think its ok to some tools to be mapped, as like engi tools
3. Fixed in #22865
4. Fixed in #22865

**Comment by lzk228** [comment]
@metalgearsloth waiting for respond

**Comment by UbaserB** [comment]
tfw sloth never responds

**Comment by lzk228** [comment]
oh sir sloth give us the answer
