### ISSUE TITLE
Mapped signs need improving

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#12087]
I've seen this across a few stations where you follow a sign and suddenly it stops at a fork and you have to guess where to go, or irrelevant departments will have signs but important departments (med / sec) don't have any. On one station it had the same sign at an intersection twice.

**Comment by Emisse** [comment]
WHICH STATIONS

**Comment by Just-a-Unity-Dev** [comment]
I think I spent around 8 minutes looking for the jani closet on cluster only to realize that the jani sign was on the same wall as the jani closet in a dimly lit area

**Comment by metalgearsloth** [comment]
Marathon: 90% of the station doesn't have any sec signage
Cluster: You have to walk on top of medical to know it's medical (and only because you saw the chemistry equipment).
Omega: There's no signage on the Eastern parts except towards HoP(?)
Kettle: Medical / Sci aren't signed on the West side of the station, Medical isn't signed on the East side.
etc.

**Comment by Cheackraze** [comment]
> I think I spent around 8 minutes looking for the jani closet on cluster only to realize that the jani sign was on the same wall as the jani closet in a dimly lit area

to be fair, there is only one janitor wall sign and it's the small directional one. The clean hands sign is what we all use to try to signify it but its not obvious in the slightest.

**Comment by Just-a-Unity-Dev** [comment]
> > I think I spent around 8 minutes looking for the jani closet on cluster only to realize that the jani sign was on the same wall as the jani closet in a dimly lit area
> 
> to be fair, there is only one janitor wall sign and it's the small directional one. The clean hands sign is what we all use to try to signify it but its not obvious in the slightest.

This is what I mean, Red is where the jani sign is (pointing left) and Blue is where I expected it to be

![image](https://user-images.githubusercontent.com/67359748/197114985-be730909-e336-4842-8f44-12318ffba773.png)

**Comment by Peptide90** [comment]
This issue could be extrapolated to we need more signs for stuff. I think atmos could do with a directional sign, as well as regular signs for some stuff (like jani, maybe court house, detective probably).

but yeah that’s a separate issue to existing ones not being mapped.

**Comment by Stealthbomber16** [comment]
Can you provide specific examples instead of "this is bad"

**Comment by Psychpsyo** [comment]
> The clean hands sign is what we all use to try to signify it but its not obvious in the slightest.

I'm pretty sure I've seen the clean hands sign in front of bathrooms on some stations while looking for the jani room.
So it's really not a good indicator, especially since the jani door is just a regular green door that's also used for other things. (like the bathrooms)

**Comment by IProduceWidgets** [comment]
I think I'm going to close this one since its not very specific about what maps, or to what degree the signage should be improved to.

I also think there's now 2 or 3 sets of different styles of most department signs, so there isn't really a lack of entities for this anymore outside of maybe a niche.

What would be very helpful is a system that aligns the directional signs on the wall and with eachother on the same wall, as well as maintaining order through rotation.
