### ISSUE TITLE
You can multitool bolt a door when it's unpowered but can't unbolt it

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#12103]
This means it's possible to permanently bolt a door until power is restored or it's reconstructed. Ideally you cold bolt or unbolt even if it's unpowered.

**Comment by mirrorcult** [comment]
you're supposed to cut and uncut it to fix i thought

**Comment by metalgearsloth** [comment]
I tried pulsing every wire and cutting but it didn't seem to do anything visually so I'll try it again.

**Comment by keronshb** [comment]
> This means it's possible to permanently bolt a door until power is restored or it's reconstructed. Ideally you cold bolt or unbolt even if it's unpowered.

This is how it is in SS13 at the moment. IIRC it was added to punish people who tried clicking through too many wires at once to brute force.

**Comment by IProduceWidgets** [comment]
I think this is intended as Keron mentions for similar reason to the unpowered bolted doors being unhackable. https://github.com/space-wizards/space-station-14/issues/12071
