### ISSUE TITLE
Using your storage should require it in your hand

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#12109]
I thought in ss13 you had to have the backpack in your hand to use it but here you can just leave all of your storage windows open all over your screen which is the meta.

I think from a gameplay perspective requiring it in your hand is better for gameplay as it means someone can disarm you and gives more weight to being smarter with inventory.

**Comment by metalgearsloth** [comment]
Apparently satchels let you do this in ss13 and backpacks don't. This is balanced around backpacks storing much more than satchels.

I think ideally:
- Belt slots let you do it
- Satchels in backpack slot let you do it

Anything in pockets / substorage / not in hands should be blocked.

**Comment by Emisse** [comment]
SATCHELS STAY WINNING

**Comment by Tyzemol** [comment]
> Anything in pockets / substorage / not in hands should be blocked.

What about things on the ground, you will have to pick up boxes/backpacks to open them?

**Comment by metalgearsloth** [comment]
> > Anything in pockets / substorage / not in hands should be blocked.
> 
> What about things on the ground, you will have to pick up boxes/backpacks to open them?

Yes

**Comment by mirrorcult** [comment]
you dont need it in your hand on 99% of servers, they just dont let you open nested storage

**Comment by metalgearsloth** [comment]
Just checked and neither goon or tg let you open multiple windows which is also better than what we have, it's exclusive, other servers kept crashing on me because byond is a great program.

**Comment by Mervill** [comment]
Can't currently open a bag in your hands by pressing E (right-click menu and clicking the spite do work). Also when you have a bag in your hands it does not show the storage icon.

**Comment by deltanedas** [comment]
you use Z to use an item inhand
E is for in world which also works

**Comment by IProduceWidgets** [comment]
Resolved by grid inv. maybe probably, multi window so I can use my belt and satchel one day please.
