### ISSUE TITLE
PA for Singularity continues firing even if computer controls are removed

### ISSUE THREAD

**Issue by retequizzle** [space-wizards/space-station-14#12122]
self explanatory, likely a bug since the PA won't start without it being in a specific position, so it makes no sense that it continues firing after the console is removed from that specific position

![image](https://user-images.githubusercontent.com/67210376/197250455-819a0f2f-65e9-4f12-9ea8-06a821a7a177.png)

(ironically singularity loosed almost immediately after i took this picture lol)

**Comment by IProduceWidgets** [comment]
Could not repro trying:
- unanchor the computer
- delete the computer
- teleport the computer
- deconstruct the computer

I'm assuming its been fixed in one of the many PA fix PRs.
Feel free to reopen if it happens again!
