### ISSUE TITLE
Mouses needs a proper burning sprite

### ISSUE THREAD

**Issue by thekaio123** [space-wizards/space-station-14#12129]
![197309214-17aa0a1b-ccbe-431f-a796-f07742df53cb](https://user-images.githubusercontent.com/61072165/197309552-c7c1cf95-c330-402a-9fd9-c5a6173322c4.png)

**Comment by PaigeMaeForrest** [comment]
sounds like a fun way to learn how to do things, let me see what i can do

**Comment by PaigeMaeForrest** [comment]
It's done, I'll do some tests and submit a pr once I'm off work

**Comment by Tayrtahn** [comment]
Fixed by #26759
