### ISSUE TITLE
Windoors on tables do not close automatically

### ISSUE THREAD

**Issue by Stealthbomber16** [space-wizards/space-station-14#12150]
Every single round the chem lab windoors get stuck open and do not close unless they're specifically forced close via interaction.

**Comment by mirrorcult** [comment]
are you sure this is about tables and not the fact that people are just clicking them directly, which forces them open until interacted with as intended

**Comment by Stealthbomber16** [comment]
> are you sure this is about tables and not the fact that people are just clicking them directly, which forces them open until interacted with as intended

if thats intended then the issue is actually that making contact with a windoor on a table doesnt open it anymore
