### ISSUE TITLE
Viewport renders on top of the rules popup

### ISSUE THREAD

**Issue by ShadowCommander** [space-wizards/space-station-14#12158]
## Description

From Discord:
threlo#9779
I seem to have encountered a strange UI bug. For some reason, the rules window is stuck behind the game window. I cannot scroll down on the rules or interact with it in any way at all. I think its a server-side issue because it happens on every computer I play on, and no one else I know has this issue.

**Reproduction**

1. Run `showrules <player username>`

Actual: The viewport renders over top of the rules popup. This prevents the players from seeing the rules while allowing them to play without pressing accept.

**Screenshots**

![image](https://cdn.discordapp.com/attachments/1033218174717542551/1033218174918860800/Capture1.PNG)
![image](https://user-images.githubusercontent.com/10494922/197375484-717abd25-89dd-48e0-aba8-95981081140e.png)

**Comment by Just-a-Unity-Dev** [comment]
Had this reported on my fork too

https://cdn.discordapp.com/attachments/996781138716667944/1032757317717999686/unknown.png

**Comment by ShadowCommander** [comment]
Checked commits before and after #7202. Layering got messed up by the hud refactor. And then further broken by some more recent commit.
After hud refactor it's
```
Background
Viewport
Rules
Hud
```

On master it's
```
Background
Rules
Viewport
Hud
```

**Comment by PJB3005** [comment]
In case it's relevant: I also changed the way the layering works in #11584, because it was on top of *everything* in the UI (including console/debug overlays)
