### ISSUE TITLE
Atmos hardsuit doesn't prevent from cold burns

### ISSUE THREAD

**Issue by MayneX** [space-wizards/space-station-14#12184]
The atmos hardsuit doesn't prevent a player from getting cold burns in the space.
Actions to replicate:
1. Completely suit up for getting out to the space.
2. Go out
3. Wait up to 3 seconds until noticing the cold effects
4. Wait up to 30 seconds until going into crit

**Comment by ElectroJr** [comment]
Should already have been fixed by #12182
