### ISSUE TITLE
Mime's door is unpowered at round start on the new Pillar

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#12211]
## Description
The mimes door is missing a LV cable nearby thus making it unpowered at round start. Mimes that spawn inside will be unable to get out without assistance.

**Screenshots**
The LV cable is missing above the poster.
![image](https://user-images.githubusercontent.com/106507028/197895572-2f2c1d80-a758-4371-9e3d-e7f9027d2845.png)

**Comment by eoineoineoin** [comment]
Was fixed by #12412

**Comment by Kayek14** [comment]
This issue was resolved.
