### ISSUE TITLE
Ahelp menu wont open on lobby screen for some players

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#12220]
## Description
I am unable to open up my ahelp menu during the lobby screen between rounds. This does not seem to affect all players since we can see ahelps coming in and going out during the lobby screen. Other players also seem to have this issue.

**Reproduction**
Try to open ahelps in the lobby.

**Additional context**
When I had the ahelp window open as the round ended it was forced closed on me and I was unable to reopen it. 
Before this issue, the ahelp window will remain open between the round end transition to the lobby.

 I tested this in both deadmin and readmin.

**Comment by metalgearsloth** [comment]
What are your settings?

**Comment by Kayek14** [comment]
Darn just logged for the night, ill get them to you ij the morning. 

Any specific settings you are looking for?

**Comment by Kayek14** [comment]
This issue seems to be resolved.
