### ISSUE TITLE
Add descriptions to all jobs, antagonists and traits

### ISSUE THREAD

**Issue by rolfero** [space-wizards/space-station-14#12227]
## Description

Add descriptions to all traits, jobs and antagonists, as made possible by #11661

**Comment by S1ss3l** [comment]
The job title class (Label) doesn't support tooltip apparently so I cant get to have them displayed. I've tried looking at the engine but I understood approximately 0bits of it so I'm outta luck. Can somebody with experience handle this please ?

**Comment by Scribbles0** [comment]
@S1ss3l i think that all you have to do is edit the prototype ymls with the description: tag, try looking at files changed within #11661

**Comment by S1ss3l** [comment]
I did ! Even learned a bit about localization along the way. It work fine for antag and trait description (since they arn't (yet ?) localized) but it deosn't for job title. I debugged for a while and found that while checkbox (like antag an trait) class support having a tooltip, apparently label (like jobtitle) don't.
Maybe I'm a turbodumbass and it got something to do with localization but I really don't think so.
For additional context : 
Begining of botanist.yml (I changed all other job.yml file likewise) : 
```yml
- type: job
  id: Botanist
  name: job-name-botanist
  description: job-description-botanist
  playTimeTracker: JobBotanist
  startingGear: BotanistGear
...
  ```
And I also created job-description.ftl by mostly copy-pasting job-name.ftl (I intend to make fully fledge description when they actually show up) like this : 
```job-description-warden = warden
job-description-security = security officer
job-description-cadet = security cadet
job-description-hos = head of security
job-description-detective = detective
job-description-scientist = scientist
...
```

**Comment by Scribbles0** [comment]
ah, okay. i misunderstood your first comment
looks good though, i might experiment with it too when i get home

**Comment by S1ss3l** [comment]
Sure ! I'll work on the job-description.ftl on my side then, I can at least do that.

**Comment by rolfero** [comment]
> The job title class (Label) doesn't support tooltip apparently so I cant get to have them displayed. I've tried looking at the engine but I understood approximately 0bits of it so I'm outta luck. Can somebody with experience handle this please ? EDIT : what got me to this error was adding this (for debug purpose) :
> 
> ```cs
> _jobTitle = new Label()
>                 {
>                     Text = job.LocalizedName,
>                     MinSize = (175, 0),
> +                   Tooltip="This is a tooltip",
> +                   TooltipDelay = 0.2f
>                 };
> ```
> 
> To Content.Client/Preferences/UI/HumanoidProfileEditor.xaml.cs

tooltip needs to be capitalized like so: ToolTip
TooltipDelay is correct still

**Comment by S1ss3l** [comment]
PJB on discord told me as such but it wasnt the only problem. They told me to add `MouseFilter = MouseFilterMode.Stop` and it made it work. I think I'll make that change (plus enabling localization for antag and trait) into a PR soon.

**Comment by ShadowCommander** [comment]
`MouseFilter = MouseFilterMode.Stop` or `MouseFilter = MouseFilterMode.Pass` depending on whether the parent controls should be able to also handle the input.

Pass passes along the input after checking if it can handle it.

Stop stops the input whether it handles it or not.

**Comment by lzk228** [comment]
solved?
