### ISSUE TITLE
Following unsummoned Holoparasites puts you in the void.

### ISSUE THREAD

**Issue by StormCurtis1** [space-wizards/space-station-14#12228]
## Description
So, as a ghost, I tried to follow an unclaimed Holoparasite via the ghost roles menu.
Dropped me (and ONLY me) in a black void with all the "says" text.

I attempted to follow another ghost role to get me out, but I was well and truly stuck.

**Reproduction**
> As ghost, attempt to follow an unclaimed Holoparasite via the ghost roles menu.

**Screenshots**
![image](https://user-images.githubusercontent.com/111147942/198106141-f5223ddf-6db5-4568-bff7-f7762d8c8e3f.png)

**Additional context**
Console was FILLED with this:
![image](https://user-images.githubusercontent.com/111147942/198106196-3caa1bdd-5be4-4806-912b-40423f444227.png)
There's also some other issues above it, but I don't know how to dump logs.

Still ingame, if you can tell me how to send logs before shift end I'll put it in the issue.

**Comment by StormCurtis1** [comment]
Requesting a ghost role fixed it.

**Comment by ElectroJr** [comment]
Has since been fixed
