### ISSUE TITLE
Aghost doesn't work

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#12241]
## Description
The ghost gets instantly deleted and you're put back in a normal ghost immediately.

**Comment by ElectroJr** [comment]
I think the issue is because when you aghost you ""visit"" the aghost, but if your original entity gets deleted you automatically un-visit and then get attached to the entity you are visiting??? Its a bit spaghetti.

temporary fix is to just take control of a non-ghost entity, and then aghost.
