### ISSUE TITLE
A player is able to move in space when next to walls even if CanMove is false

### ISSUE THREAD

**Issue by DrSmugleaf** [space-wizards/space-station-14#1226]
Put yourself in space touching a wall, have some component with IActionBlocker change CanMove to false, try moving.
You will be able to move until you touch a floor tile again (no longer in space), at which point your character will be unable to move anymore.

**Comment by exp111** [comment]
Probably [here](https://github.com/space-wizards/space-station-14/blob/017e5a8d717889feeec958fa0976ebfd78618973/Content.Shared/GameObjects/EntitySystems/SharedMoverSystem.cs#L85).

You could just remove the `&& !weightless`, but I don't know what side effects that could have. 
My testing showed none (you still can't move in space and float according to your previous velocity)

**Comment by metalgearsloth** [comment]
Fixed in https://github.com/space-wizards/space-station-14/pull/3485
