### ISSUE TITLE
Server (lizard) crashing frequently

### ISSUE THREAD

**Issue by Streaky-Haddock** [space-wizards/space-station-14#12262]
## Description
Server crashed at about 06:16 EST. OOC chat seems to suggest this is the third time it's crashed and <s>anecdotal evidence says it keeps happening on the shuttle. </s> I only joined for this crash. Only things i'm majorly aware of was someone in an engineer hardsuit throwing a bomb and hosing down the crew with an L6 SAW before I shot him with a flare gun. Probably unrelated because he got a good 20 secs of fire with no glitching. I also managed to make it to the other side of the shuttle so fire may also be unrelated.

Posting it here because no-one's been informed, and Selby told me he's only aware of what's on github. 

It just crashed again 06:21 EST
**Reproduction**

No Idea.

**Screenshots**
None, sorry.

**Additional context**

**Comment by Streaky-Haddock** [comment]
Lizard continues to crash every hour or so. There are no obvious common threads.

**Comment by Streaky-Haddock** [comment]
Still crashing about every hour. Explosions seem the best guess of the community, but its really hard to tell.

**Comment by metalgearsloth** [comment]
This is just https://github.com/space-wizards/RobustToolbox/issues/3402

**Comment by Streaky-Haddock** [comment]
Crashes on lizard remain frequent. This is related to #12281 , which are the symptoms which lead up to the crash. The server AND the client (ss14.loader) both slow down and freeze. I understand that the watchdog kills the server when it gets too crazy but the client itself will continue to lock up.

I have been able to find steps to reproduce this.

**Reproduction (On Live)**

- Send yourself to admin testing chamber.
-  Spawn yourself an Urist McHands and put yourself in it. 
- aghost. 
-  warp to the nuclear authentication disk. 
- Everyone starts locking up, freezing and sliding. 

There are probably ways  players can trigger it, but I can do this at roundstart and midround.
