### ISSUE TITLE
W i d e actions

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#12271]
I have no idea what I did to repro but I was trying to debug [#3402](https://github.com/space-wizards/RobustToolbox/issues/3402) by exploding stuff and then teleported to map 2 where I had stationstation loaded and I noticed this.

I normally run the game at 1920x1080 which occupies a quarter of my screen, at 150% UI scale.

![image](https://user-images.githubusercontent.com/31366439/198812891-9a33fb9c-5530-4119-b562-232dc6f17902.png)

**Comment by ElectroJr** [comment]
Moony ran into this earlier as well, I'm guess its just the one set of tiles with variants (num 7 in the actions bar) thats causing them all to be malformed.
