### ISSUE TITLE
ERT Mob Spawns don't automatically make ghost roles anymore

### ISSUE THREAD

**Issue by Streaky-Haddock** [space-wizards/space-station-14#12280]
## Description
While trying to place down ERT Engineers and ERT Commander, I had to manually make them ghost roles. Before last week (when I was adminning most days, i've been on break) this was the case. Making ERT's easier to deploy. Now, they don't do that. I've checked by spawning a couple of mice... they still ghost role normally. I've not checked with other mobs.

**Reproduction**

Observe, press f5 to open entity spawn panel. Type ERT. Spawn the EVA Hardsuited version (on live, not tested with the non-eva). Put them down, check ghost roles. They will not show up. YOu will need to right click and manually set them up.

**Screenshots**

**Additional context**

**Comment by Stealthbomber16** [comment]
Non-eva ones DO still spawn ghost roles, interestingly enough!

**Comment by lzk228** [comment]
fixed
