### ISSUE TITLE
Sleepwalking

### ISSUE THREAD

**Issue by Scribbles0** [space-wizards/space-station-14#12284]
## Description

Slipping on something then falling asleep will let you sleepwalk.

**Reproduction**

1. Slip
2. Fall asleep
3. Walk around after the stun is over

**Screenshots**

https://user-images.githubusercontent.com/91828755/198859786-9a76658c-aff9-4d64-acb2-ce6f5bac50db.mp4

**Comment by keronshb** [comment]
#12194 should fix this

**Comment by Scribbles0** [comment]
this was not fixed by #12194
do i have to open a new issue?
