### ISSUE TITLE
Cargo's shuttle is incapable of selling anything

### ISSUE THREAD

**Issue by Nairodian** [space-wizards/space-station-14#12286]
## Description
Anything inside the cargo shuttle will not be sold on recalling of the shuttle, no matter what it is or where it is. You put something on the pallet, recall the shuttle, call the shuttle back, the item is still there, didn't get removed and no funds were earned.

**Reproduction**
Put something on the cargo shuttle, recall it, call it back.

**Additional context**
One of the first mentions of this bug was on the 27th in the main discord, in the #bugs-feedback channel under the bug report "Cargonia's ship wont sell anything. but weirdly we can buy stuff."

**Comment by ElectroJr** [comment]
Should be fixed by #12306
