### ISSUE TITLE
Steel sheet laundering

### ISSUE THREAD

**Issue by kamilw25** [space-wizards/space-station-14#12293]
## Description
You can print infinite materials with the protolathe

**Reproduction**
Upgrade protolathe to t2 parts, the 25% discount applies to sheet printing, insert steel sheets for example, print out 25% more than what you inserted in

**Screenshots**

**Additional context**
I think this is funny and should be kept in the game, sci can become cargo.

**Comment by moonheart08** [comment]
moment
