### ISSUE TITLE
NPC Pathfinding null reference exception

### ISSUE THREAD

**Issue by ElectroJr** [space-wizards/space-station-14#12295]
Caught a local NRE error. A neighbour in `BuildBreadcrumbs()` -> `ClearTilePolys()` -> `ClearPoly()` was null. Happened while flying around and exploding things, though it seems to be pretty rare cause I've only encountered this once after blowing up 20+ stations for other debugging reasons. The poly two other non-null neighbours. Of those, one had 4 valid neighbours, the other had 2 valid & one null.

@metalgearsloth

**Comment by metalgearsloth** [comment]
https://github.com/space-wizards/space-station-14/pull/12355 should fix it and i'll keep an eye out
