### ISSUE TITLE
Restrict Placement/Spawning

### ISSUE THREAD

**Issue by Acruid** [space-wizards/space-station-14#123]
Now that we have a proper construction system, spawning entities and tiles should be restricted to admins.

Requirements:
- [ ] Prevent clients from using the placement system unless they are admins.

**Comment by Zumorica** [comment]
What's the status on this? I'm pretty sure it can be closed already.

**Comment by PJB3005** [comment]
This is handled now. You can only use placement if you're admin OR in sandbox mode.
