### ISSUE TITLE
Parents 'texture:' field overrides a childs 'sprite:' field.

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#1232]
For example if a parent had a 
```
- type: Icon
  texture: foo.png
```
And a child had a 
```
- type: Icon
  sprite: foo.rsi
```
The parent would still use the texture: field.

The best in-code example of this is in [power.yml](https://github.com/space-wizards/space-station-14/blob/master/Resources/Prototypes/Entities/Buildings/power.yml) with the APC. The APC's parent is WPP but setting the icon as a sprite doesn't override the parents texture: field.

**Comment by metalgearsloth** [comment]
@PaulRitter is specific case still an issue since your PR?

**Comment by PaulRitter** [comment]
update the submodule smh my head

yes, my pr fixes this

**Comment by SweptWasTaken** [comment]
> 
> 
> update the submodule smh my head
> 
> yes, my pr fixes this

Ok, closing preemptively.
