### ISSUE TITLE
Phasing through walls - Disposals

### ISSUE THREAD

**Issue by Mundaytheclown** [space-wizards/space-station-14#12342]
## Description
Bug using Certain disposal chutes lets you phase through walls forever unless you go into a new disposal machine and hit flush - not the one used to produce the bug

**Reproduction**
1. Get into bugged Disposal chute the map I know works is Saltern in the bar close to kitchen.
2. flush and reach the disposals.
3. bug is now active and you can walk through any wall u like.
4. to remove phasing through walls u need to go into a disposal that is not affected by the said bug so the one I used was in the medical front lobby.

**Screenshots**
cannot fit the vids into this so ill upload them to be viewed externally on medal - game recording software
https://medal.tv/games/undefined/clips/GRhrnZKIiWInB/d1337CbJpQOh?invite=cr-MSx2ak4sMTMxNjQ4NDYs
https://medal.tv/games/undefined/clips/GRhbx1BMYrhjn/d1337VNV44vw?invite=cr-MSxyeG4sMTMxNjQ4NDYs
https://medal.tv/games/undefined/clips/GRgSXF_McoUCe/d1337VUiIRrE?invite=cr-MSxSSDYsMTMxNjQ4NDYs
https://medal.tv/games/undefined/clips/GRdkqk27juKXH/d1337O8gTuta?invite=cr-MSx5eGUsMTMxNjQ4NDYs
https://medal.tv/games/undefined/clips/GRcZGUHBnF6fH/d1337DshRKDm?invite=cr-MSxBaVgsMTMxNjQ4NDYs

**Additional context**
Only Saltern has been able to produce this bug as of yet further testing is needed.

**Comment by Mundaytheclown** [comment]
further testing has shown that its on multiple maps not just isolated to saltern

**Comment by ElectroJr** [comment]
![welp](https://user-images.githubusercontent.com/60421075/199331887-bc2bc3c6-9643-4d8e-91ab-6e41ac16414f.png)
I probably should have double checked this.....

> further testing has shown that its on multiple maps not just isolated to saltern

Can't quite remember which caused it, but IIRC it depended on whether or not the pipe ends in a disposal trunk.

**Comment by Mundaytheclown** [comment]
Yeah issue is still present I think you're correct on the pipe ending as it was ONLY affected on certain disposal chutes lots of people are finding this bug as of my report.

**Comment by Mundaytheclown** [comment]
The testing that I did do was all on Saltern and bagel
