### ISSUE TITLE
Doors play a sound when going through them while unpowered

### ISSUE THREAD

**Issue by juliangiebel** [space-wizards/space-station-14#12360]
## Description

When you go through a door that doesn't have power and is open it plays a sound
**Reproduction**

1. Open door
2. Cut power
3. Go through

**Screenshots**

![grafik](https://user-images.githubusercontent.com/8915246/199598869-a1878445-5280-4ad5-ac3f-e8fe3d970dd9.png)

**Additional context**

Discovered on Outer Rim after cutting APC power

**Comment by Plykiya** [comment]
not  anymooore
