### ISSUE TITLE
Cursor highlighting doesn't respect your perspective

### ISSUE THREAD

**Issue by partyaddict** [space-wizards/space-station-14#1237]
![image](https://user-images.githubusercontent.com/52793290/86066634-9ce87080-ba6a-11ea-9c5c-8eb1fbabcb70.png)

**Comment by AJCM-git** [comment]
cant reproduce

**Comment by mirrorcult** [comment]
this is only no longer an issue because walls don't have interaction outline anymore

**Comment by AJCM-git** [comment]
i tried with airlocks and couldnt repro
