### ISSUE TITLE
HackMD Link Broke

### ISSUE THREAD

**Issue by civilCornball** [space-wizards/space-station-14#12397]
## Description
Exactly what it says on the tin: You can't open our HackMD documentation via the 'feature request' option.

**Reproduction**
Open an issue, and then click the 'feature request' option's "open" button.
![image](https://user-images.githubusercontent.com/48499004/200137175-1d502b36-5785-4322-a4b5-81a087468580.png)
This is supposed to open a HackMD link to our documentation, but it's a 404 page right now.

**Additional context**
(https://hackmd.io/@ss14/docs)

**Comment by Visne** [comment]
Seems to be changed already.
