### ISSUE TITLE
I can see low wall overlay through rightclick

### ISSUE THREAD

**Issue by partyaddict** [space-wizards/space-station-14#1239]
![image](https://user-images.githubusercontent.com/52793290/86067671-4cbedd80-ba6d-11ea-9000-83aa73111e24.png)

**Comment by SweptWasTaken** [comment]
![image](https://user-images.githubusercontent.com/49448379/94897854-01f39e00-0480-11eb-8bb4-92ec4810268c.png)

Replicated by clicking right in the middle of the window..
