### ISSUE TITLE
Uploading YAML prototypes to server causes AI subroutine to bug out.

### ISSUE THREAD

**Issue by ZoldorfTheWizard** [space-wizards/space-station-14#12402]
## Description
Uploading YAML prototypes to server causes AI subroutine to bug out.

**Reproduction**
Steps to reproduce: 
Create NPC using aI (Floppa)
Upload custom yaml file,
NPC stops moving. 

happens to all custom loaded prototypes, whether they get loaded or not. here is what i used

```- type: entity
  parent: BaseItem
  id: TESTCUSTOMYAML2
  name: TEST
  description: TEST
  components:
  - type: Sprite
    sprite: Objects/Misc/skub.rsi
    state: icon
  - type: Item
    sprite: Objects/Misc/skub.rsi
  - type: ItemCooldown```

**Comment by Insineer** [comment]
I couldn't reproduce it on current master. Tried with server-client on single machine running with Windows 11.

Maybe there are any exceptions in the server's console?

**Comment by metalgearsloth** [comment]
> I couldn't reproduce it on current master. Tried with server-client on single machine running with Windows 11.
> 
> Maybe there are any exceptions in the server's console?

We already know the why and there is a potential PR up https://github.com/space-wizards/RobustToolbox/pull/3609

**Comment by ZoldorfTheWizard** [comment]
resolved by https://github.com/space-wizards/RobustToolbox/pull/3609
