### ISSUE TITLE
Chair buckling is completely broken.

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#1243]
If you buckle yourself your will be locked to the center of the chair but have a radius of movement that you can swing around.
![2020-06-30_15-47-46](https://user-images.githubusercontent.com/49448379/86184428-bac5dc00-bb23-11ea-9880-2914e9d20f76.gif)

When you _unbuckle yourself_ you will be frozen in place and unable to move. You're basically stuck until you respawn.
![2020-06-30_15-48-33](https://user-images.githubusercontent.com/49448379/86184518-ea74e400-bb23-11ea-9850-26d43846ffa9.gif)

Looks like this is a prediction issue.

**Comment by Dropgunner** [comment]
You can unbuckle yourself if you right click the chair while you are moving

**Comment by Dropgunner** [comment]
and btw it crashes the server. Found that bug under a minute ingame and crashed it in 5. 

Accessing 2 lockers at the same time also crashes your server...
