### ISSUE TITLE
Opening a locker while pushing it into a wall causes it to phase into the wall

### ISSUE THREAD

**Issue by SoulSloth** [space-wizards/space-station-14#1244]
Reproduction steps:
1. Push a locker into a wall
2. While pushing on the locker, open it
Result:
Locker becomes one with the wall:
![image](https://user-images.githubusercontent.com/67545203/86196219-c4017980-bb20-11ea-9f4e-8ea357b95627.png)

**Comment by DrSmugleaf** [comment]
Related #965 (https://github.com/space-wizards/space-station-14/issues/965#issuecomment-632971870)

**Comment by AJCM-git** [comment]
fixed by #1181
