### ISSUE TITLE
Making the hotbar icons dragable and magnetic 

### ISSUE THREAD

**Issue by Dropgunner** [space-wizards/space-station-14#1247]
![Hotbar](https://user-images.githubusercontent.com/52992016/86250426-d925e900-bbb0-11ea-8ff9-ada482450839.JPG)

Cool implementation in general but since some UI elements are draggable it would be nice that the hotbar icons are dragable too and magnetic to each other. With magnetic I mean they stick together when they get close to each  other and with another click function (rightclick, Alt+click whatever... ) you can split them

**Comment by SweptWasTaken** [comment]
Good idea but confusing since hotbar is in and has dragging icons. I can't rename it so closing. Will remake.
