### ISSUE TITLE
Morty's sprite is hella ugly

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#12509]
It doesn't ever face left or right, it just looks like it's facing up or down, and it's also pretty ugly.

**Comment by Halalrc** [comment]
![possum](https://user-images.githubusercontent.com/115177362/200933032-ea5e6194-e199-48da-acc1-bcb5e688e190.png)
mb?

**Comment by metalgearsloth** [comment]
Also the raccoon one has the same issue but I rarely see it so I forget.

also it's an OPOSSUM.

**Comment by JustinTrotter** [comment]
> ![possum](https://user-images.githubusercontent.com/115177362/200933032-ea5e6194-e199-48da-acc1-bcb5e688e190.png) mb?

Do you happen to have the raccoon graphic as well? I'd like to update both.

**Comment by DogZeroX** [comment]
No you
