### ISSUE TITLE
torch does not heat air or consume oxygen

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#12515]
## Description
Torches (crafted with 2 wood, use to light) do not produce heat or turn oxygen into carbon dioxide.

**Reproduction**
1. Take apart table
2. Craft torch
3. Light it
4. Check gas analyzer, no increase in heat or decrease in oxygen

**Screenshots**
![torch](https://user-images.githubusercontent.com/39013340/200930980-46af8c85-7be1-4d8f-b806-a211290173a9.png)
![gas](https://user-images.githubusercontent.com/39013340/200930993-f794bfa0-5737-41d0-8a11-ca3cb1b54b00.png)

**Additional context**
Haven't seen how lighters affect/don't affect the air.

Haven't seen if torches can work in space, which would be odd.

**Comment by moonheart08** [comment]
Note that nothing heats the air except fires. SS14 only handles large temperature differentials so items creating small-scale ones would simply cause weird equalization behavior.

**Comment by Elijahrane** [comment]
What'd be a big enough heat source to be worth simulating? Should fireplaces give off heat?

**Comment by moonheart08** [comment]
> What'd be a big enough heat source to be worth simulating? Should fireplaces give off heat?

a 1500W space heater.

**Comment by deltanedas** [comment]
speaking of space heaters, if they existed that would've solved this problem i was trying to fix with a torch. (medbay was below freezing and spacing to let in hot air was Not A Good Idea)

**Comment by deltanedas** [comment]
that does exist, heater and passive vent

**Comment by Elijahrane** [comment]
> that does exist, heater and passive vent

it doesn't exist though, the heater thermomachine effects air in pipes, space heaters heat up the room they are in
