### ISSUE TITLE
Speedloaders need cleaning up

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#12539]
- It lets any ammo box function as a speedloader and not the actual intended speedloaders
- Comments next to code is gross, also a few are misspelt.
- It's doing updates every iteration of a loop instead of... outside of the loop
- Some whacky null suppression.

From https://github.com/space-wizards/space-station-14/pull/12417

**Comment by mgesser** [comment]
Do you still need someone to take a look at this?

**Comment by metalgearsloth** [comment]
Should be fine after https://github.com/space-wizards/space-station-14/pull/12697 and the other prs.
