### ISSUE TITLE
New Coughing...

### ISSUE THREAD

**Issue by Kromabae** [space-wizards/space-station-14#12532]
## Description

The new coughing doesn't sound right, and it always puts the sound in my right back speaker all the time no matter where my character faces. also the sound itself is rather... meeh, doesn't fit in the game at all. THere was nothing wrong with the old coughing so not sure why it was changed.

Edit: it's also loud as all hell
Edit2: after experiencing the coughing for a while i started getting nauseous irl, could be coincidence but it started happening just about a short while the coughing started in game
**Reproduction**

just cough

**Comment by Just-a-Unity-Dev** [comment]
Resolved by space-wizards/space-station-14#12533

**Comment by EmoGarbage404** [comment]
*cough cough*
