### ISSUE TITLE
Cooldowns should show the flash when the cooldown is done, not right before it is done.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/space-station-14#1254]
Right now the white flash on cooldowns is show *just before* the cooldown is actually done. This is really counter intuitive and it would be better if the cooldown was done when the white flash appears.

**Comment by AJCM-git** [comment]
Currently the flash is shown the frame _after_ the cooldown is done

https://user-images.githubusercontent.com/60196617/140628159-7fdad4f9-8f86-4e22-b2fe-d09f02a4ecf3.mp4
