### ISSUE TITLE
SpaceGarbageSystem is eating glass shards instantaneously.

### ISSUE THREAD

**Issue by Mervill** [space-wizards/space-station-14#12544]
## Description
- Bust out your favorite breaking and entering weapon
- Break a window
- Glass shards don't spawn

Actually the shards _do_ spawn, but they are being deleted instantaneously due to `SpaceGarbageSystem`. I guess the shards aren't technically attached to the station when spawned?

**Comment by Pangogie** [comment]
Fixed at some point.
