### ISSUE TITLE
Melee weapon hit sounds don't always play correctly?

### ISSUE THREAD

**Issue by ElectroJr** [space-wizards/space-station-14#12568]
E.g., if you give bikehorns to a basic hostile clown they don't make honking sounds while hitting you?

**Comment by metalgearsloth** [comment]
If something does 0 damage the preference is on the bap sound (0 damage) over the override. In other cases I think it's preferable (e.g. esword does 0 damage we'd prefer to show it does no damage rather than play the burn sound).

**Comment by ElectroJr** [comment]
In this case, I'd changed them to deal 3 damage per hit, and it was still playing normal hitting sounds.
