### ISSUE TITLE
SpaceGarbageSystem is eating unspent rounds.

### ISSUE THREAD

**Issue by Vordenburg** [space-wizards/space-station-14#12593]
## Description

Similar to #12544, `SpaceGarbageSystem` is eating unspent rounds when you cycle through ammo boxes or loaded weapons, making it impossible to reload them if you happen to cycle in the wrong spot on the map.

**Reproduction**

The armory in Lighthouse is an amazingly good place to do this. Good luck getting any rounds from those shotgun boxes.

**Comment by Pangogie** [comment]
Fixedat some point.
