### ISSUE TITLE
Riot Shield Text spam and Usability issues

### ISSUE THREAD

**Issue by OmerF-afk** [space-wizards/space-station-14#12609]
## Description
Hello, when I use the action of the riot shield, it sends multiple texts instead of just one

**Reproduction**
Riot Shield's action

![image](https://user-images.githubusercontent.com/104027832/201915352-b3d9bed4-58c6-4800-81ed-f8ea5c705eca.png)

**Additional context**
Also riot shields cannot be used near walls and doors, which makes them almost useless because the purpose of this tool is to prevent players from entering or passing you by turning yourself into a wall (it also gives you additional defense by doing so) Please allow riot shields to be used near walls and doors

**Comment by keronshb** [comment]
I can def check to see what's up with the spamming, that shouldn't happen.

> Also riot shields cannot be used near walls and doors, which makes them almost useless because the purpose of this tool is to prevent players from entering or passing you by turning yourself into a wall (it also gives you additional defense by doing so) Please allow riot shields to be used near walls and doors

This is intentional at the moment because they can be used to clip people through solid objects, which is not intended.

**Comment by keronshb** [comment]
> 

It already currently checks to see if there's a mob on the tile. There were also issues of preventing doors from closing, which is why they can't be used in doorways.
