### ISSUE TITLE
Right-facing slimes don't have a left hand when not wearing gloves.

### ISSUE THREAD

**Issue by Mervill** [space-wizards/space-station-14#12601]
![2022-11-14 17_01_43-Window](https://user-images.githubusercontent.com/6798456/201800922-c171dc74-f834-42a1-b81e-18801e05a42c.png)

Easy to see on the character customization screen. The partially-obscured left hand of slimes is not rendered when not wearing gloves and facing right.

**Comment by IProduceWidgets** [comment]
![image](https://github.com/space-wizards/space-station-14/assets/107586145/b33915c1-9d32-450e-b4aa-97ec1f996071)
