### ISSUE TITLE
Need cotton plant

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#12629]
## Description

- Should have some way to turn it into cloth
- Not edible (probably)

pretty easy plant to add for some material economy integration

**Comment by lapatison** [comment]
What might the process of turning cotton into cloth look like?

**Comment by EmoGarbage404** [comment]
> What might the process of turning cotton into cloth look like?

Cotten is spun into strands before woven into fabric. That could be done via some generic machine. Maybe call it an autoloom?

**Comment by Qulibly** [comment]
What if it was in some already existing machines? Like autolathe/protolathe?

**Comment by EmoGarbage404** [comment]
I mean, i feel like it'd be better to give it a dedicated machine that could be kept in botany. Even if its just a reskinned lathe, botany could use some more specific equipment.

**Comment by JustinTrotter** [comment]
https://en.m.wikipedia.org/wiki/Cotton_gin

**Comment by lzk228** [comment]
solved lol
