### ISSUE TITLE
Flashlights are manufactured with charged power cell inside

### ISSUE THREAD

**Issue by Qulibly** [space-wizards/space-station-14#12631]
Flashlights are made in protolathe with charged power cell inside. Not only that, but normally the cell itself is MUCH more expensive to make than flashlight itself, and requires gold!

Additionally making flashlight is cheap as hell from $$$ side (~38.38$ costs cargo to order materials for it) and sells for ALOT (168$, which means ~130$ for each sold flashlight)

![obraz](https://user-images.githubusercontent.com/52052459/202229109-e2fbd9b6-7eb9-4d30-a516-f48c5876de41.png)
![obraz](https://user-images.githubusercontent.com/52052459/202229192-dce49329-86ef-489d-8d95-087ae4a29241.png)
![obraz](https://user-images.githubusercontent.com/52052459/202230730-0205e28f-cebe-4a1d-9359-b35f8c2598eb.png)
![obraz](https://user-images.githubusercontent.com/52052459/202230816-7dbfbb4b-3643-4814-bd02-d306df25ada3.png)
![obraz](https://user-images.githubusercontent.com/52052459/202230876-71a14365-2087-43f6-af45-2b9abd6909b9.png)
![obraz](https://user-images.githubusercontent.com/52052459/202230944-c8763ec2-f81e-430f-9088-08762b2c17ff.png)

For additional context. I found it on my private test server. And then double checked on Wizard's Den Salamander if this wasn't fixed already

**Comment by Theomund** [comment]
I think the easiest solution to this problem would be to buff the material cost for manufacturing a flashlight. It should be something like this:

  * 400 steel
  * 400 glass
  * 200 plastic
  * 10 gold

This was calculated by adding the material cost of a power cell with those of a flashlight. I'll try to address this in my own branch.

**Comment by EmoGarbage404** [comment]
> I think the easiest solution to this problem would be to buff the material cost for manufacturing a flashlight. It should be something like this:
> 
>     * 400 steel
> 
>     * 400 glass
> 
>     * 200 plastic
> 
>     * 10 gold
> 
> 
> This was calculated by adding the material cost of a power cell with those of a flashlight. I'll try to address this in my own branch.

i would suggest just making a prototype variation of the flashlight that starts without a cell inside of it. Then, simply switch the lathe recipe result to be that prototype.

**Comment by mirrorcult** [comment]
just make it spawn without a cell

**Comment by Theomund** [comment]
> i would suggest just making a prototype variation of the flashlight that starts without a cell inside of it. Then, simply switch the lathe recipe result to be that prototype.

> just make it spawn from the lathe without a cell

Will do.
