### ISSUE TITLE
Standing still renders you immune to lightning

### ISSUE THREAD

**Issue by Elijahrane** [space-wizards/space-station-14#12644]
## Description

**Reproduction**

1. Stand still for duration of arc
2. Don't take damage or get electrified
3. Move during arc
4. Take damage or get electrified

@keronshb

**Comment by Elijahrane** [comment]
This is a general pattern of things that do something when they collide only checking for collision when things move into them, I think

Flammable has a basically identical issue

**Comment by EmoGarbage404** [comment]
this was fixed with an engine update. the linked issue in robust is more descriptive as to what needs to be fixed, but the actual issue with lightning is good now.

**Comment by Elijahrane** [comment]
> this was fixed with an engine update. the linked issue in robust is more descriptive as to what needs to be fixed, but the actual issue with lightning is good now.

I saw that PR and tested after the engine update and it's still broken

**Comment by EmoGarbage404** [comment]
https://user-images.githubusercontent.com/98561806/215000375-482eb83f-56f9-4308-8a89-346fa98f5ad7.mp4
works on my machine.

**Comment by Elijahrane** [comment]
![image](https://user-images.githubusercontent.com/60792108/215000702-4c529c61-66df-42dd-bdd1-da630aebdb86.png)


> https://user-images.githubusercontent.com/98561806/215000375-482eb83f-56f9-4308-8a89-346fa98f5ad7.mp4 works on my machine.

arcs have been working I noticed, but was it targeting you specifically in that clip?

Here's my code that isn't working, using direct targeting

![image](https://user-images.githubusercontent.com/60792108/215000899-449dfea2-0b7c-4ac1-8ced-90a239eeef89.png)
```[ERRO] root: Shooting lightning from glimmer prober (24465, GlimmerProber) to Charles Mcmullen (24431, MobHuman, localhost@JoeGenero) using beam prototype HyperchargedLightning```

Video of this log: 

https://user-images.githubusercontent.com/60792108/215001024-e0be856e-3782-42c8-aab3-638afe0a1dac.mp4

**Comment by Elijahrane** [comment]
I'll have to pull latest robust and check real quick, I think the change was in the version I updated to

**Comment by EmoGarbage404** [comment]
add this line (where `_broadphase` is a dependency for SharedBroadphaseSystem)
```
_broadphase.RegenerateContacts(physics, manager);
```
after line 96 in Content.Server/Beam/BeamSystem.cs
that should regenerate the fixtures on the lightning entities and make them collide properly.
