### ISSUE TITLE
Maintenance access doors cannot be bolted by any of the available door remotes (tested on Omega map)

### ISSUE THREAD

**Issue by sharkman** [space-wizards/space-station-14#12653]
## Description
Maintenance access doors cannot be bolted by any of the available door remotes.

**Reproduction**
Spawn all door remotes, switch them into "bolt door" mode, find any door with Maintenance access level, try to click it with door remotes. You will get "access denied" message.

**Screenshots**
![image](https://user-images.githubusercontent.com/113660/202522600-f9213fa4-5ff3-495b-aeea-bc285e3e9e5a.png)

**Additional context**
-

**Comment by mirrorcult** [comment]
im not really sure this is a bug, i assume they can still bolt the maintenance doors of their department (i.e. the ones that also require dept access?)

**Comment by sharkman** [comment]
Dept access ones, yes, but those ones which only have Maintenance cannot be bolted

**Comment by mirrorcult** [comment]
i dont see that as a bug, door remotes arent meant to bolt every door on the station

**Comment by sharkman** [comment]
ok, maybe I'm wrong here
