### ISSUE TITLE
Map fixes needed in Box Station disposals room.

### ISSUE THREAD

**Issue by Mervill** [space-wizards/space-station-14#12667]
![2022-11-17 23_42_51-Space Station 14](https://user-images.githubusercontent.com/6798456/202648439-816e7308-3eaf-4c70-8ec6-923d41d8800f.png)

The tile on the left outlined in red needs to have a conveyor belt on it, pointed in the direction of the arrow. This will allow garbage to properly land on the  conveyor. The recycler on the left needs to be rotated so that the blades are facing _toward_ the incoming garbage.

**Comment by lzk228** [comment]
i think solved
