### ISSUE TITLE
Burn mix "doesn't" ignite

### ISSUE THREAD

**Issue by Scribbles0** [space-wizards/space-station-14#12690]
## Description

Not exactly sure what the problem is, but it isn't showing that it's burning while it actually is.

**Screenshots**

https://youtu.be/TUQNTqVILR8

**Comment by Scribbles0** [comment]
will probably be fixed by #12692

**Comment by ElectroJr** [comment]
It should, as well as closing this discord post (which afaik doesn't have a GH issue) https://discord.com/channels/310555209753690112/1043375738490986617
