### ISSUE TITLE
Integrate Materials into Construction

### ISSUE THREAD

**Issue by Acruid** [space-wizards/space-station-14#1269]
The construction system was built before the material system, so all of the info about materials used to construct things is currently hard-coded into the construction system. The material system was added in https://github.com/space-wizards/space-station-14/pull/84.

- [ ] A construction step ingredient should either be an arbitrary entity with a defined `MaterialComponent.MaterialType`, or the recipe should define a specific prototype ID to use.

- [ ] Material prototypes need to define an entity that represents them in the world, so that explosions and deconstruction know what prototype ID to spawn. Right now it is a hard-coded dictionary in ConstructionSystem.

- [ ] The sprites that are shown inside the crafting UI for materials are hard-coded paths. These need to be defined inside the MaterialPrototypes.

- [ ] `StackComponent.StackType` should be removed, and stacks should be merge-able based on either full component comparison (minecraft compares NBT data) or require comparing just `MaterialComponent`s.

**Comment by SweptWasTaken** [comment]
@Zumorica Can this be closed?

**Comment by Zumorica** [comment]
Ironically the main issue here isn't resolved with the new system, but I'd just close this and open another one. (if there isn't already)
