### ISSUE TITLE
Maps shouldn't have machine parts greater than Tier 1 mapped.

### ISSUE THREAD

**Issue by EmoGarbage404** [space-wizards/space-station-14#12694]
## Description

Having parts greater than tier 1 invalidates a lot of the incentives for sci to research better parts. It also cuts out the important cycle of obtaining the resources for said parts. As such, they shouldn't be mapped anywhere as they just provide science the opportunity to memorize the location and enjoy free upgrades.

Feel free to map tier 1 parts inside science or maybe in maintenance. Anything beyond that is too much.

**Comment by Emisse** [comment]
ill update my maps wiht this oanf ohwn enoaw ial sfgeo tohyua gti i

**Comment by UbaserB** [comment]
Did you fix it emisse
