### ISSUE TITLE
Movement issue

### ISSUE THREAD

**Issue by Gorebull** [space-wizards/space-station-14#12726]
When I playing multiplayer, I have issue with my movement keys (wasd). On one servers this is happens 1 time in 5 min on others this happens much often.
For example: when my character is moving left then right I have issue that one key is jamming (one of wasd). On one servers this issue with button stuck can continue 3-5 sec on others it can continue much longer to 30 sec and more.
I faced this issue on many servers. My ping doesnt matter. Server with lowest ping below 35 have this issue much often and it had more lags  while another server with ping 80 have been much more stable without any lags except this issue with movement button stuck.

When I hosted my own local server I never had this issue
Tried enable/disable: Compatibility Mode, Experimental Performance Options in launcher. I changed game options on Network tab, doesn't seen any difference, except when I unmark "Client-side prediction" option, the delay gets much longer.

If you need, I can attach log files.

**Comment by jicksaw** [comment]
Does the jam get cleared if you press the key again? Then it might be this issue https://github.com/space-wizards/space-station-14/issues/1326

I get the same issue about once a round, and have had it happen in some other game I can't remember. Are you maybe running on Linux? Though your observation that it's server dependent suggests the OS doesn't matter.
