### ISSUE TITLE
Servers crashes after spamming disarm on AI

### ISSUE THREAD

**Issue by estacaoespacialpirata** [space-wizards/space-station-14#12737]
**Reproduction**
Spawn an AI
Active harm and spam right click on the AI to disarm it
Server crashes

**Screenshots**
![image](https://user-images.githubusercontent.com/110949078/203654674-6c74537c-f978-4f70-904e-044661b53ddd.png)

**Comment by metalgearsloth** [comment]
Which NPC is it because they likely have a null active hand.

**Comment by estacaoespacialpirata** [comment]
@metalgearsloth ive done it with Xeno Praetorian.
