### ISSUE TITLE
Ghosts in space are very hard to see

### ISSUE THREAD

**Issue by ike709** [space-wizards/space-station-14#1274]
Ghost on the station:
![image](https://user-images.githubusercontent.com/5714543/86529570-3eaafb80-be77-11ea-99ac-2e776bae3226.png)

Ghost in space:
![image](https://user-images.githubusercontent.com/5714543/86529556-1b804c00-be77-11ea-858d-bcc43921282e.png)

**Comment by ike709** [comment]
Players are dark too without a flashlight but that's understandable. Ghosts, however, do not have the ability to use flashlights.

**Comment by ShadowCommander** [comment]
Should be easy to fix by making the ghost sprite unlit.
