### ISSUE TITLE
Bullets can take out two turfs at once

### ISSUE THREAD

**Issue by partyaddict** [space-wizards/space-station-14#1275]
![](https://leopard.hosting.pecon.us/dl/klkww/2020-07-05_11-08-16.gif)

This is probably intended but looks weird.

**Comment by DTanxxx** [comment]
Hi partyaddict,
I am keen to solve this issue. Can you please assign it to me? Thanks.

**Comment by DTanxxx** [comment]
I have a question, how can I open the project for testing purposes? I have downloaded the launcher, server and client files for Mac and I can't seem to open the application accompanying the client zip file.

**Comment by ShadowCommander** [comment]
@DTanxxx Follow the getting started page here https://hackmd.io/@ss14/docs/%2FBZkI4RlUQbm09QWrXCZ3kg

**Comment by DTanxxx** [comment]
@ShadowCommander Thanks for the setup docs. Project is running smoothly now. As for this issue, should I change it so that the only turf destroyed is the one indicated by the red rectangle and not the adjacent one (even if bullet collides with adjacent turf)?

**Comment by ShadowCommander** [comment]
If you can, that would be nice, but it's probably easier to just only damage the first entity it collides with in the list of collisions.

**Comment by brndd** [comment]
I think this got fixed by 1912

**Comment by SweptWasTaken** [comment]
> 
> 
> I think this got fixed by #1912

Indeed.
