### ISSUE TITLE
Tranq shells need either more crafting requirements or chloral threshhold needs to be increased

### ISSUE THREAD

**Issue by retequizzle** [space-wizards/space-station-14#12754]
They're basically new instant-win buttons and as of late I'm seeing certain secoffs trying to get them at the very start of the round solely for dopamine chasing and validhunting, makes for very fucking boring gameplay where all sec does is fire one round and end any conflict that crops up.

it's either that or i start smiting secoffs who abuse it your call really

**Comment by Cheackraze** [comment]
Yea they are in a weird place balance-wise.  If you reduce their chloral content, you functionally just have bean bag shells.  I'm not sure if the 'sleep' is any more unique than a normal 'stun' at that point to justify their existence.  Maybe we just need resistance to instant injectors. So wearing any kind of armor would reduce the number of chems injected, from just a little with the vests to blocking lots of the chems in a jugger suit. This would theoretically balance out the hypo spray too to stop the cmos from near insta killing nukies with lex hypo

**Comment by retequizzle** [comment]
I'm starting to lean towards the fact that instant injectors just need to not be instant anymore period, hypo included. Leave the actions as is but have the chems build up in the chemstream gradually rather than immediate transfer of contents and having those contents immediately show up in chemstream.

Something like a 2u per second transfer to essentially outpace the metabolism tick rate by 2:1 while also allowing for a delayed onset mechanic specifically for shit like this might be the middleground.

**Comment by Cheackraze** [comment]
Yea that would also be a solution, and would also help reduce the hypo issues too

**Comment by Veritius** [comment]
I'm absolutely for some kind of delayed-release mechanism. It'd work for a whole load of other stuff, too. Being able to add reagents slowly instead of all at once allows a lot more flexibility with balance.

**Comment by IProduceWidgets** [comment]
Its been rebalanced at least twice, and I know the tranq reflection issues and fixtures issues were resolved.
