### ISSUE TITLE
Puddles no longer mix chems since after the liquid refractor

### ISSUE THREAD

**Issue by Kromabae** [space-wizards/space-station-14#12767]
## Description
Puddles act as if they are in cryostasis and no longer mix chems when on the ground, this started after the change in how puddles works and spread (i think)

**Reproduction**

Spill chems that mix
best result is probably potassium and water but anything that mixes works

**Comment by Ygg01** [comment]
Can you still reproduce this?

I've seen juices mixing and the puddles mixing as well; see the following video (water and potassium):

https://user-images.githubusercontent.com/1146204/213308976-a1f9776d-36bb-47b2-ba2a-05b09d62d976.mp4

**Comment by deltanedas** [comment]
doesn't occur anymore, spilling chlorine and fluorine makes a lot of explosions

**Comment by EmoGarbage404** [comment]
this was fixed (i mixed vinegar on the ground)
