### ISSUE TITLE
No visual difference between bullets and cartridges

### ISSUE THREAD

**Issue by partyaddict** [space-wizards/space-station-14#1276]
![image](https://user-images.githubusercontent.com/52793290/86530421-771afb80-beb0-11ea-8596-7b130f51c190.png)
Some of these are bullets and some of these are expended shells.

**Comment by metalgearsloth** [comment]
Should ping the art-and-ui channel for this I think as I don't believe cev-eris has a sprite to reflect it, only for the other ammo types (large casings, shells, grenades, etc.)

**Comment by clement-or** [comment]
Can someone assign this to me ?
