### ISSUE TITLE
Welding tank explosions shouldn't be big.

### ISSUE THREAD

**Issue by partyaddict** [space-wizards/space-station-14#1279]
As far as I recall in SS13, it takes a few hits with the welding tool to blow up a welding tank.

In SS14, it blows it up instantly.

**Also, the explosion is a bit big but whatever.**

**Comment by ShadowCommander** [comment]
Lit welding tools blow up fuel tanks instantly from what I can recall. Unlit welding tools shouldn't. Bullets should take a few hits or not ignite it at all.

**Comment by PJB3005** [comment]
> As far as I recall in SS13, it takes a few hits with the welding tool to blow up a welding tank.

I definitely recall the opposite.

**Comment by partyaddict** [comment]
Perhaps I haven't played enough /vg/, time to go on a welding tank pilgramage in every ss13 server.

**Comment by ShadowCommander** [comment]
The point is that you use a flame on a highly flammable liquid. In real life that usually ends badly.

**Comment by DrSmugleaf** [comment]
![welder boom](https://user-images.githubusercontent.com/10968691/86530834-7a1be900-bebc-11ea-999d-33b06ac7d0ea.gif)

**Comment by partyaddict** [comment]
honestly, i don't even remember the last time i played ss13
