### ISSUE TITLE
Misleading statement in rules

### ISSUE THREAD

**Issue by Interrobang01** [space-wizards/space-station-14#12799]
## Description

I've been told to not touch the rules, but I feel like at least an issue is necessary.

In the rules (both ingame and on wiki), there is a fairly misleading statement:
`[revolution, strike, ect] activities are antagonist-only and are strictly forbidden unless admin permission is obtained.`
While upon close inspection this clearly means "no cults unless both antag and perms", I feel like it's very easy to misinterpret it as an "or" statement, leading to antags starting strikes and quartermasters asking for perms on ahelp.

(Moony has confirmed that this is indeed an "and" statement)

**Reproduction**

Reproduction? uh...
\>find person unfamiliar with game
\>show them the following
>DO NOT DO ANY OF THE FOLLOWING: Departmental Revolutions (ex: "Cargonia" or any variations thereof, whatever you decide to call it), Cults, Strikes, or any similar behaviors that disrupt the station at large as a non-antagonist. These activities are antagonist-only and are strictly forbidden unless admin permission is obtained.

\>ask them to summarize

I have done this with a friend unfamiliar with the game, and his response was:
>a list of things to NOT DO unless if your an antagonist or permission from an admin is obtained

QED

**Additional context**

Moony seemed to dislike the idea of fixing this, but didn't provide any further information. If this issue is to be closed, I ask that I'm given a good argument first at the least.

**Comment by metalgearsloth** [comment]
> Department strikes, revolutions (ex: cargonia and any variation thereof), or cults are antagonist-only activites **and** are forbidden without admin permission.

I feel like this is unambiguous, spelling mistake not withstanding.

**Comment by mirrorcult** [comment]
this is literally not ambiguous, it says 'and'

**Comment by Cheackraze** [comment]
There is nothing unclear about the original statement though. It is proper English and well-defined.  There is no 'or' statement in the original text; if people are reading it that way, it's a reading comprehension issue on the user's part. And not even a complex one, that's some simple elementary school-level reading comprehension.  If anything, a simple comma after 'antaganist-only' would suffice but even then I think that's an oxford comma debate and not a rules debate

**Comment by Interrobang01** [comment]
It's obvious with the foresight of already knowing what the rules mean, following the reproduction steps are the only real way to get an unbiased answer.

**Comment by mirrorcult** [comment]
we are not responsible for sample size of 1 person having poor reading comprehension

**Comment by Interrobang01** [comment]
then get more samples... or I can get more samples. I'm sure the Rimworld discord will have many willing volunteers...

You can argue grammar and spelling all day, but in the end it's not how you read it, it's how the users read it. If the rules are badly worded and are then broken, then it's not entirely the user's fault.

...also, an easier fix to this would be to simply get rid of the "antagonist only" part and have it just be "admin permissions only", because if an admin is asked by a non-antag, they can just deny it.

**Comment by mirrorcult** [comment]
if you want the actual reason for why people try to start revolutions in game anyway: its not an 'ambiguous wording issue'! the players doing this haven't nobly read the rules and simply misinterpreted them, they just literally havent read them at all

**Comment by mirrorcult** [comment]
no amount of bikeshedding over the wording of already perfectly intelligible and unambiguous sentences can make people read the rules in the first place

**Comment by Interrobang01** [comment]
okay, that's fair, but it's not, I don't think, a good reason to not update the rules. Is there some bureaucratic roadblock to changing a couple words in the rules?

**Comment by mirrorcult** [comment]
we don't want to update them because THERE IS NOT AN ISSUE TO BE FIXED HERE

**Comment by Interrobang01** [comment]
Would you still agree that getting rid of the "antagonist only" part (keeping "admin permissions only") would be a net improvement in the rules?

**Comment by mirrorcult** [comment]
no, and that is why i have closed this issue

**Comment by Interrobang01** [comment]
I feel like the argument is as good as done here, but could you still elaborate on why it's not a net gain?

**Comment by Just-a-Unity-Dev** [comment]
because it seems like you're just nitpicking at nothing here

**Comment by metalgearsloth** [comment]
Continue it on discord if you want to bikeshed.
