### ISSUE TITLE
APC power does not function on planets.

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#12802]
## Description
Self-explanatory, if you place an APC and cables (on placed tiles, the bg obviously doesn't count as valid for this)nothing actually connects to them.

**Comment by metalgearsloth** [comment]
LGTM but I did spot another issue

![image](https://user-images.githubusercontent.com/31366439/222613575-284220c3-3e9a-4e58-9fc3-d943de7152b2.png)
