### ISSUE TITLE
Wall/table smoothing specifically does not work on planets.

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#12803]
## Description
Somehow carpet works just fine, but walls do not.

**Comment by metalgearsloth** [comment]
Steps to repro?

Looks fine to me and might just be the client anchoring desync which has an issue somewhere but I can't find it atm.

![image](https://user-images.githubusercontent.com/31366439/204455338-ccf73180-7672-4183-a926-7017616f481e.png)
