### ISSUE TITLE
`LinkBanner` isnt showing links from replicated cvars

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#12843]
## Description

The bug here is that when the infolinks cvar is only set on the server, it doesn't get replicated to the client before the `LinkBanner` (the lobby top link bar) ctor runs and fills it in with an empty link, and thus doesn't properly  fill the buttons

Other stuff which runs -after- the replication (like the escape menu UI controller) does properly get the button filled

Result of #12781 making these into cvars, debugged with Rane

**Reproduction**

1) Set an infolinks cvar (like wiki) directly in `CCVars.cs`
2) Run client, see that it works in lobby link banner
3) Set an infolinks cvar only with the `Content.Server` command line args
4) Run client, see that lobby linkbanner isnt filled

**Screenshots**

**Additional context**

**Comment by PJB3005** [comment]
Ah crap I only tested it with `golobby`. I assumed CVars would be replicated by the time the lobby is constructed..?

**Comment by mirrorcult** [comment]
when i breakpointed the linkbanner ctor for whatever reason it seemed to run even before i had connected to the server?

**Comment by PJB3005** [comment]
Apparently UI refactor constructs all `UIScreen`s ahead of time... uhhhh
