### ISSUE TITLE
Air Alarms tabs get stuck in a flickering state when multiple people are using them

### ISSUE THREAD

**Issue by tgrkzus** [space-wizards/space-station-14#12842]
## Description

Seems to be some sync problem, since the server tries to sync the viewed tab across clients.

**Reproduction**

- Get two clients to open an air alarm ui at the same time
- Get one client to swap between tabs quickly
- Will pretty much immediately get stuck in a weird flickering state.
- Everyone needs to leave the UI to fix it

**Screenshots**

![airlol](https://user-images.githubusercontent.com/7283010/205417687-c975949e-b364-4ccf-90fd-4db077e3851e.gif)

**Additional context**

**Comment by deltanedas** [comment]
can happen with just 1 person too, by pressing vents/scrubbers/sensors button in a weird way
