### ISSUE TITLE
Projectile Speed Not Relative To Grid It's Shot From

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [space-wizards/space-station-14#12852]
## Description

When you shoot a gun into space, on a shuttle that is currently moving, the projectile flies back into the shuttle, as it's speed is not relative to the shuttle.

**Reproduction**

1. Make hole in shuttle.
2. Move shuttle in some direction.
3. Shoot through hole in direction of movement
4. ???

Demonstration is made better by shooting something explosive like an RPG, as you can clearly see where the projectile landed.

**Additional context**

Shiptest literally impossible because of this.

**Comment by Dushess0** [comment]
https://user-images.githubusercontent.com/44201461/205448180-fd1e8e88-e230-42c3-8314-cb9554b31f22.mp4

**Comment by LudwigVonChesterfield** [comment]
(the bug is demonstrated in the end of the video)
