### ISSUE TITLE
do_after for actions

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#1288]
Basically, we need a way to make certain actions take a specified amount of time before being completed. This action would also be cancelled if the player were to move or interact with something else.
This would also show a cooldown bar to the players.

**Comment by metalgearsloth** [comment]
@Zumorica Mind assigning me? I'll give it a crack.

**Comment by ShadowCommander** [comment]
Assigned @metalgearsloth

**Comment by Zumorica** [comment]
Nice. My only request is that you can `await` this for convenience :pray:

**Comment by SweptWasTaken** [comment]
Closing since it got merged today.
