### ISSUE TITLE
APC breaker selectable

### ISSUE THREAD

**Issue by clusterfack** [space-wizards/space-station-14#129]
When you toggle the main breaker of apc on/off the UI gives the 'selected' box around the element. Pictured below:

![image](https://user-images.githubusercontent.com/8516830/48994140-3e794480-f107-11e8-9ad1-49aaaa59de1a.png)

Needs space-wizards/space-station-14#623

**Comment by PJB3005** [comment]
This happens with basically all UI elements. This one is bad though because of how poorly done it is.

The selection effect is nice though because it allows you to navigate menus with your keyboard etc.

Ideally this one can be fixed if/when I finish the new UI theme.

**Comment by Injazz** [comment]
Godot is dead, so does is this issue
