### ISSUE TITLE
will there be a user fix for windows 7

### ISSUE THREAD

**Issue by hentach228** [space-wizards/space-station-14#12907]
**Hi, I don't speak English at all. I'm sorry if I interrupted you.** 
Due to the fact that the game is no longer supported on win7, **I had the idea that someone could make a fix** that allows you to play on this system.
I'm a very ordinary person and I don't understand anything about programming. I really love this game. Many people will say  "just update the system" 
but I have a very weak PC - i 2350, gt520m and 4gb ram. I think a lot of people playing space station 14 have a PC no better than mine. 
**If someone can make a fix for the game, I will be grateful to him.** 
I apologize again

**Comment by mirrorcult** [comment]
no, we have no plans to support windows 7

**Comment by hentach228** [comment]
> no, we have no plans to support windows 7

I hope that ordinary users will be able to fix it

**Comment by mirrorcult** [comment]
the main issue with windows 7 users right now is that their OS literally doesn't receive security updates anymore because it's out of support

**Comment by goliv04053** [comment]
Update to Windows 8.1

**Comment by Simplehorror** [comment]
pretty sure ss13 will work
