### ISSUE TITLE
Some continuous noises sometimes don't stop playing

### ISSUE THREAD

**Issue by Rapidgame7** [space-wizards/space-station-14#12905]
## Description
For example, ghosts tampering with lights or emergency flares play a continuous noise for as long as their effect last.
Sometimes, if their effect is not allowed to finish (usually just by a round restart, but seldom happens just by going out of range or entering a different map), the noise will continue playing regardless of whether the source is still available.

**Reproduction**
- Ingnite flare
- Disconnect OR allow round to end
- Permanent flare noise ahoy

**Video**
https://user-images.githubusercontent.com/14862618/205847284-408f7787-fd2d-456b-b1d8-b13932a430f5.mp4

**Comment by Vordenburg** [comment]
I can confirm this frequently happens with flares and ghost light flickering and sometimes with the shuttle FTL ambient noise.
