### ISSUE TITLE
Eating while full should probably not cause the progress bar to appear

### ISSUE THREAD

**Issue by Rapidgame7** [space-wizards/space-station-14#12904]
## Description
Your body should probably not be able to willingly attempt to stuff itself with anything when you're not even able to!

**Reproduction**
- Be full
- Eat something

**Video**
https://user-images.githubusercontent.com/14862618/205842262-0a52d96c-8ba8-4b0e-9b94-5be8fc907fb0.mp4

**Comment by mgesser** [comment]
Is this still an issue?

**Comment by UbaserB** [comment]
Im pretty sure this was resolved

**Comment by UbaserB** [comment]
i will double check it....

**Comment by UbaserB** [comment]
> > Im pretty sure this was resolved
> 
> its still an issue

I just tested it in localhost. While it disappears surprisingly quick it does in fact stop a doafter from occurring and i also counted the number of bites against the popup, it works fine now.
