### ISSUE TITLE
chocolate bars spawn outside of lockers.

### ISSUE THREAD

**Issue by F77F** [space-wizards/space-station-14#1291]
![image](https://user-images.githubusercontent.com/66768086/86748068-d0df0b00-c001-11ea-8bc3-316a38715873.png)

**Comment by RemieRichards** [comment]
This is a travesty, they'll MELT.

**Comment by SweptWasTaken** [comment]
I feel like this is my fault since I made those lockers have emergency chocolate inside them.

**Comment by DrSmugleaf** [comment]
This has been fixed with the remap of saltern in https://github.com/space-wizards/space-station-14/commit/d35391c4e886078aa3f8a8dc445371e2015db2b5.
