### ISSUE TITLE
Vector needs a nerf

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#12910]
Shooting revolver bullets is okay but these things are mapped so they should be shooting pistol like the other smgs are.

**Comment by Fellowsinspace** [comment]
Wasn't the purpose of .45 magnum to separate the ammo of the vector and the revolver so they didn't share the same round?

**Comment by metalgearsloth** [comment]
> Wasn't the purpose of .45 magnum to separate the ammo of the vector and the revolver so they didn't share the same round?

We don't need 2 types of magnum rounds.

**Comment by Fellowsinspace** [comment]
> 

Thats fair but I think its a little bland if every gun in the armory uses the same bullet. Personally i think it just losses the variety of using different guns with different ammo types. It just ends up being "what gun fires the fastest" if every single gun shared the same bullet. But thats how I see it and its not going to affect the game too badly if sec only uses .35 auto and buckshot.

**Comment by metalgearsloth** [comment]
Removed.
