### ISSUE TITLE
late joining is still possible with zombies/nukies active

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#12924]
## Description
gamers can late join during a big crisis which kinda breaks immersion and with zombies really drags the game out

**Reproduction**
1. have 1 guy hiding out in some place about to die
2. johnny greytide, passenger, joins and delays round

**Additional context**
can be funny if spawning next to nukies but with zombies it dragged a round out by like 10 minutes since no admemes on to end it

**Comment by EmoGarbage404** [comment]
for nukies i don't really think this is a problem. For zombies, if it's really such a problem, you could just new players automatically zombify when they join.

**Comment by mirrorcult** [comment]
i dont think this is a problem for any gamemode
