### ISSUE TITLE
Rotting examine doesn't properly track how much has actually rotted

### ISSUE THREAD

**Issue by Elijahrane** [space-wizards/space-station-14#12966]
## Description

It uses time of death and no longer tracks how much of that time was actually spent rotting.

This body has not taken a single tick of damage from rotting and it's shown as "It's rotting!"

**Reproduction**

1. Leave body in space
2. Note how the examine text goes off of time of death alone even if the body never starts rotting

**Screenshots**

![image](https://user-images.githubusercontent.com/60792108/206879658-94911e90-0881-4e03-ae92-de29ab3d7bd1.png)

**Comment by Elijahrane** [comment]
I believe this regression was introduced by https://github.com/space-wizards/space-station-14/pull/12407

![image](https://user-images.githubusercontent.com/60792108/206879793-04a38fd9-5fc9-4555-a951-142ca65bf18a.png)

This check does not work.

**Comment by EmoGarbage404** [comment]
fixed as well
