### ISSUE TITLE
All NPC pathfinding sometimes stops working until restarted

### ISSUE THREAD

**Issue by Elijahrane** [space-wizards/space-station-14#12989]
## Description

This is from a live nyano round (npcs up to date with upstream and no modifications to NPC systems)
![image](https://user-images.githubusercontent.com/60792108/206973055-0bfae81f-175a-465a-a3ed-1c2f6ff788e6.png)

A salvage ahelps because none of the salvage mobs were moving. I placed a space tick on the station to see if it would move there. It tried to path, but wouldn't move to any of the paths it made. All of the various mice, salvage mobs, etc had the same behavior.

** The workaround **
The NPCs worked again after I did this:
```
sudo cvar npc.enabled false
sudo cvar npc.pathfinding false
sudo cvar npc.pathfinding true
sudo cvar npc.enabled true
```

** The hypothesis **
Something is crashing the pathfinder, and it's restricted to just the pathfinder. Changing the cvars off and on restarts everything and makes it work again. Could https://github.com/space-wizards/space-station-14/issues/12988 be related?

**Comment by metalgearsloth** [comment]
I suspect the async code being in parallel.for is causing threading issues so I removed it for now https://github.com/space-wizards/space-station-14/pull/13085

Worst case I get more info for debugging.

**Comment by Elijahrane** [comment]
was fixed when the multithreading was removed from steering i think
