### ISSUE TITLE
Pathfinding exception 

### ISSUE THREAD

**Issue by Elijahrane** [space-wizards/space-station-14#12988]
## Description

Note: cvar thread.parallel_count was set to 1
[pftrace.txt](https://github.com/space-wizards/space-station-14/files/10204917/pftrace.txt)

NPC / Pathfinding stuff was merged and unchanged up to commit https://github.com/space-wizards/space-station-14/pull/12743

## Reproduction
This happens when I turn NPCs on, even if I delete all but a simple wander AI like a mouse before enabling npcs.

**Comment by metalgearsloth** [comment]
Seems to be the distance checks being normalised in steering so I added 0-length checks in https://github.com/space-wizards/space-station-14/pull/12990
