### ISSUE TITLE
Vending machines have inconsistant destruction behaviour

### ISSUE THREAD

**Issue by ProfanedBane** [space-wizards/space-station-14#1299]
- The Youtool located in top left tool storage, when destroyed spews it's items out on the ground (double clicking on it might induce this behaviour I'm unsure). All the items are invisible until picked up.
- Newly spawned in  Youtools continue functioning correctly after being destroyed
- Ammovend cannot be destroyed by explosions
- Other misc vending machines become unusable after destruction

Being destroyed consists of having an explosive grenade detonated nearby.

I'd expect them to stop working or maybe spew some of their contents out, consistently between vending machine types and spawn method.

**Comment by SweptWasTaken** [comment]
>The Youtool located in top left tool storage, when destroyed spews it's items out on the ground (double clicking on it might induce this behaviour I'm unsure). All the items are invisible until picked up.
You're mistaken, it doesn't spew out it's inventory, the locker next to it breaks and drops it's inventory.

>Newly spawned in Youtools continue functioning correctly after being destroyed
Can't replicate

>Ammovend cannot be destroyed by explosions
I removed (And will readd) this and it will be fixed.

>Other misc vending machines become unusable after destruction
Can't replicate.
