### ISSUE TITLE
Attempting to join local server with one than one local client crashes

### ISSUE THREAD

**Issue by ThunderBear2006** [space-wizards/space-station-14#12992]
## Description
As the title says, when I attempt to join a server I started on my own computer with more than one client it crashes

**Reproduction**
> Start a server on the latest from upstream/master on your computer
> Start two or more clients on your computer
> Join said server

**Additional context**
I've joined with more than one client before without issue

**Comment by PJB3005** [comment]
What kind of error do you get? "it crashes" is not very useful.

**Comment by Elijahrane** [comment]
> What kind of error do you get? "it crashes" is not very useful.

usually stuff about IoC and threading and stuff

in my DMs with maintainers it's apparently common knowledge now you need to set the cvar "thread.parallel_count" to 1 if you are going to test locally

**Comment by PJB3005** [comment]
> usually stuff about IoC having no context on a thread

This is trivially fixable with a stack trace.

**Comment by Elijahrane** [comment]
> > usually stuff about IoC having no context on a thread
> 
> This is trivially fixable with a stack trace.

[threadingerr.txt](https://github.com/space-wizards/space-station-14/files/10212067/threadingerr.txt)

**Comment by ElectroJr** [comment]
I uhhh... confused the decal & gas chunking systems & applied the fix to the wrong system in #12789
