### ISSUE TITLE
Pasting a large amount of text into the chatbox crashes the client

### ISSUE THREAD

**Issue by ProfanedBane** [space-wizards/space-station-14#1300]
Expected:
- Bee movie script is cut off at X many characters.

Actual:
- Tries to paste the whole thing and client instantly crashes.

---------------------------
Space Station 14: Robust.Client.exe - Application Error
---------------------------
The exception unknown software exception (0xe0434352) occurred in the application at location 0x00007FFC5F189709.

---------------------------
OK   Cancel   
---------------------------

**Comment by PJB3005** [comment]
The actual bug here is https://github.com/space-wizards/RobustToolbox/issues/1170
