### ISSUE TITLE
Bloodstream exceptions

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#13018]
![image](https://user-images.githubusercontent.com/31366439/207464805-ebd01847-cc8f-4d1e-9eda-cb5d89343a74.png)

**Comment by keronshb** [comment]
I can't replicate this. I've tried forcing bloodloss with some medicine and forcing heals with more, but no luck.

**Comment by metalgearsloth** [comment]
> I can't replicate this. I've tried forcing bloodloss with some medicine and forcing heals with more, but no luck.

The field is non-nullable so you'll need to log it because you're not gonna be able to repro it in case it's an admin uploading malformed prototypes or the likes.
