### ISSUE TITLE
You get shocked by grilles even if they have glass on top

### ISSUE THREAD

**Issue by AJCM-git** [space-wizards/space-station-14#13025]
**Reproduction**
1. Put a powered wire under a grille, which itself has to be under a glass window
2. Go close to it 
3. You get shocked when the glass should protect you

**Comment by deltanedas** [comment]
not a duplicate, now it affects player collision and kills so many people

**Comment by deltanedas** [comment]
also the build order is messed up you have to do glass -> grille instead of grille -> glass
