### ISSUE TITLE
Clicking below the chat window limits how much text you can enter into the chat box

### ISSUE THREAD

**Issue by ProfanedBane** [space-wizards/space-station-14#1302]
Clicking in the area below the chatbox, at the same height as the All/Local/OOC button brings focus onto the chat box.
From here it seems to count l-click as being held down at that horizontal position on the chat box.
So if you type up to the horizontal area the cursor is it highlights the latest letter and constantly overwrites it.

Click on the red box area in these images.

[https://cdn.discordapp.com/attachments/675078881425752124/730148446840946828/unknown.png](https://cdn.discordapp.com/attachments/675078881425752124/730148446840946828/unknown.png)
[https://cdn.discordapp.com/attachments/675078881425752124/730148804648763462/unknown.png](https://cdn.discordapp.com/attachments/675078881425752124/730148804648763462/unknown.png)

**Comment by PJB3005** [comment]
Fixed in engine.
