### ISSUE TITLE
Minor Intercoms issues.

### ISSUE THREAD

**Issue by ElectroJr** [space-wizards/space-station-14#13023]
- [ ] They need on/off sprites. Maybe just make the little red light switch from red to green?
- [ ] They should automatically turn off when they lose power.

**Comment by ike709** [comment]
> They need on/off sprites.

Here you go: https://scrubby.melonmesa.com/icon/search/intercom

**Comment by ElectroJr** [comment]
Let me amend that: they need sprites for listening, not-listening, and not-powered, though I guess the latter two could just be the same sprite.
