### ISSUE TITLE
Grilles are shocking people through windows.

### ISSUE THREAD

**Issue by Elijahrane** [space-wizards/space-station-14#13028]
## Description

Something broke with an update in the past day or two. Was reported on Nyano and I verified locally on latest master of this repo.

**Reproduction**

1. Toggle subfloor and connect cable under a window
![Screenshot from 2022-12-14 15-20-40](https://user-images.githubusercontent.com/60792108/207706018-603517c8-c70a-4f09-b49c-6a901574c206.png)
2. Turn subfloor off. Run into the window, get shocked, and die. You don't even have to interact with it, just move near it.
![image](https://user-images.githubusercontent.com/60792108/207706057-ab176284-74fa-4bbc-b345-68c7331e5089.png)

**Comment by DiaAWAY** [comment]
Issues with glass and grilles are already noted:
#13025
#9129
#5162

**Comment by Elijahrane** [comment]
> Issues with glass and grilles are already noted: #13025 #9129 #5162

This new issue just started with the past 36 hours or so

**Comment by Elijahrane** [comment]
```git checkout f65510ca81cbeef77bb422a19c48ce0a5470c046```

This bug didn't exist as recently as https://github.com/space-wizards/space-station-14/commit/f65510ca81cbeef77bb422a19c48ce0a5470c046. I was not able to try the next few as they have compilation errors.

**Comment by Elijahrane** [comment]
seems fixed now
