### ISSUE TITLE
Using movement keys to exit a closed locker breaks prediction, ai mobs and direction facing

### ISSUE THREAD

**Issue by ProfanedBane** [space-wizards/space-station-14#1303]
Repro:
- Enter locker
- Close locker
- Move to get out

This makes you face right and have real funky movement/prediction.
Xeno AI mobs will ignore you.

Video:

[https://cdn.discordapp.com/attachments/675078881425752124/730162246705086574/2020-07-07_21-41-04.mp4](https://cdn.discordapp.com/attachments/675078881425752124/730162246705086574/2020-07-07_21-41-04.mp4)

**Comment by SweptWasTaken** [comment]
Could not replicate, even with situation recreated like in your video... closing?
