### ISSUE TITLE
Actions that require a welder still complete if the welder is turned off during the action

### ISSUE THREAD

**Issue by markozajc** [space-wizards/space-station-14#13040]
## Description
Welders can be turned off during an action, and it will still complete as long as the welder is turned on at the start and at the end.

**Reproduction**
1) Turn the welder on
2) Use the welder on a something that starts a timed action (eg. as a part of a tile's destruction procedure)
3) Immediately turn the welder off
4) Turn it back on just before the action completes

**Additional context**
While minor, this can be used to save a small amount of fuel.

**Comment by IProduceWidgets** [comment]
Seems like its fixed, at least for welding windows and doors that I tested.
