### ISSUE TITLE
Double clicking on a buckle-able object buckles you and instantly unbuckles you

### ISSUE THREAD

**Issue by ProfanedBane** [space-wizards/space-station-14#1304]
Seems the unbuckle request is processed immediately after.

Videos:
[https://cdn.discordapp.com/attachments/675078881425752124/730164759424401468/2020-07-07_21-53-48.mp4](https://cdn.discordapp.com/attachments/675078881425752124/730164759424401468/2020-07-07_21-53-48.mp4)

[https://cdn.discordapp.com/attachments/675078881425752124/730164156623486986/2020-07-07_21-51-26.mp4](https://cdn.discordapp.com/attachments/675078881425752124/730164156623486986/2020-07-07_21-51-26.mp4)

**Comment by DrSmugleaf** [comment]
Fixed in #1263

**Comment by ike709** [comment]
Fixes https://github.com/space-wizards/space-station-14/issues/1293 ?
