### ISSUE TITLE
Stun batons are wonky again

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#13059]
## Description##
If you hit someone with a charged, powered baton, it makes the damage sound effect instead of the stun sound effect. It also appears to do damage and displays brute damage to the character getting stunned.

Additionally, a health analyzer shows that after two charged stun hits, the character took 84 brute damage. after ten or so hits both the brute damage and visual damage gets reset.

Also, if you are out of charge but the baton is still toggled on, the player getting hit does a mini stutter stun animation despite the baton being out of charge. If you toggle the spent baton off this problem doesn't occur.

**Reproduction**
Wack someone with a powered stun baton. Observe their health levels with a health analyzer. Continue until their damage resets.

**Screenshots**

Two charged stuns show 84 brute damage
![image](https://user-images.githubusercontent.com/106507028/208264086-2c61bafd-9f07-4e88-be8d-e53415825cce.png)

Damage levels after 7 hits
![image](https://user-images.githubusercontent.com/106507028/208264327-1cfe221e-9e2f-48e6-9239-25c1588bb93c.png)

After ten or so hits, the players brute damage, and visual damage, resets
![image](https://user-images.githubusercontent.com/106507028/208264128-14771499-e9fb-4eb5-8d47-29ccdb42b7a3.png)

**Additional context**

**Comment by Partmedia** [comment]
My initial analysis of the sound issue is that https://github.com/space-wizards/space-station-14/pull/12569 introduced a regression where clients always play the predicted sound (standard melee hit) instead of the server-side stun baton overridden stun sound.

**Comment by metalgearsloth** [comment]
The sound one is just https://github.com/space-wizards/space-station-14/issues/14507

**Comment by Kayek14** [comment]
This issue is resolved.
