### ISSUE TITLE
Lobby character preview does not appear on startup

### ISSUE THREAD

**Issue by dmnct** [space-wizards/space-station-14#13067]
## Description

Character preview does not show up until you enter Customize and click Save on any character

**Reproduction**

Start the game on any server

**Screenshots**

![missing_preview](https://user-images.githubusercontent.com/35878406/208297797-d7d5e574-ec14-40a9-a327-4d1858eb2424.jpg)

**Additional context**

**Comment by Interrobang01** [comment]
This has been going on for, like, since Dwarf Fortress released. Thanks for reporting it.

**Comment by Elijahrane** [comment]
> This has been going on for, like, since Dwarf Fortress released. Thanks for reporting it.

I think it was introduced with the links PR that made lobby links go off of the CVars

**Comment by metalgearsloth** [comment]
Fixed in https://github.com/space-wizards/RobustToolbox/pull/4065
