### ISSUE TITLE
If you manage to get to 0 velocity in space you will never move again

### ISSUE THREAD

**Issue by ProfanedBane** [space-wizards/space-station-14#1306]
Repro:
- Have a decent sized area of space
- Create a chair in the center
- Buckle to it
- Unbuckle
- Can't move and throwing won't save you

Also been reported to happen if an explosion breach happens which you survive.

**Comment by metalgearsloth** [comment]
Fixed as of a PR I don't remember where controllers wake their body as long as they're moving.
