### ISSUE TITLE
Screen shakes on round start.

### ISSUE THREAD

**Issue by Vordenburg** [space-wizards/space-station-14#13086]
Probably related to recent changes to gravity: #12866

**Comment by mirrorcult** [comment]
i cant repro this, is it happening on a specific map?

**Comment by Emisse** [comment]
ive noticed that spawning a new grid postinit with a gravgen or adding one causes the horrific screenshake and gravity restored noise, maybe related?

**Comment by Vordenburg** [comment]
> i cant repro this, is it happening on a specific map?

My exact commands are:
```
golobby
readyall
forcemap Moose (or Box, or Bagel)
startround
```

When the round starts, I see the screen shake effect reminiscent of the gravity generator changing state. I don't hear the alarm though
