### ISSUE TITLE
Mob movement detaches the entity from the grid and makes them lose all velocity

### ISSUE THREAD

**Issue by Emisse** [space-wizards/space-station-14#13129]
as of last publish any mob movement will detach the entity from the grid for a bit and the mob will stay in one spot in reference to the map. the grid beneath them will move. this is extremely noticeable during evac shuttle because anyone who moves instantly gets the ship flown out from under them.

**Comment by LedinecMing** [comment]
This is very important to fix, but no one cares

**Comment by metalgearsloth** [comment]
> This is very important to fix, but no one cares as I see

We reverted the relevant PR so this comment is inflammatory for no reason.

**Comment by Emisse** [comment]
i believe this is fixed for now

**Comment by LedinecMing** [comment]
Sorry
