### ISSUE TITLE
All knives knock people down on first hit

### ISSUE THREAD

**Issue by keronshb** [space-wizards/space-station-14#13147]
## Description

Knives will knock someone over in one stab

**Reproduction**

Just stab a person

**Screenshots**

![image](https://user-images.githubusercontent.com/54602815/209262157-c17199b7-04ef-4a05-b721-2b6f364c337a.png)

**Additional context**

**Comment by JazzGlobal** [comment]
New to the game and codebase. How should this behave?

**Comment by ElectroJr** [comment]
Usually people should only ever go horizontal if they received enough damage to enter the crit/dead mob state. E.g., see `SharedMobStateSystem.EnterCritState()`, which calls `_standing.Down(uid)` and does the opposite when exiting crit.

I guess either the client is somehow mis predicting that an entity is entering crit and then not properly resetting afterwards (which might be hard to fix if you're new to the codebase), or there is just some bug somewhere in mob state code.

**Comment by mirrorcult** [comment]
from other reports it sounds like the downed state is only visible to the person who attacked with the knife--to the person being attacked they look normal

**Comment by metalgearsloth** [comment]
Makes me think IsFirstTimePredicted needs adding somewhere in stamina or damage code, easiest way to check would be to breakpoint IsDown I think.

**Comment by ElectroJr** [comment]
@JazzGlobal  #13304 should mostly fix it. It did turn out to be due to a quirk of how the game handled prediction, so in hindsight this probably wasn't a great issue to start with

**Comment by JazzGlobal** [comment]
> @JazzGlobal #13304 should mostly fix it. It did turn out to be due to a quirk of how the game handled prediction, so in hindsight this probably wasn't a great issue to start with

Not a problem, I saw that no replies had been made since the issue was made so I figured the issue description was not clear. Glad somebody was able to pick it up and run with it!
