### ISSUE TITLE
Better error handling for prototypes

### ISSUE THREAD

**Issue by clement-or** [space-wizards/space-station-14#13150]
## Description
Currently, when a prototype is badly defined, it throws an exception wherever in the code that prototype is parsed. This becomes really annoying if you account for the fact that there's pretty much no prototype reference other than having to dive into the code. This can prevent contributors from adding objects into the game if they're unfamiliar with the codebase.

Having some kind of way to generate prototypes references from docstrings in C# would also be great.

**Reproduction**
* Define a prototype with a missing required field
* A random exception is thrown
* Expected: "Missing [name] required field on prototype [id] : [file path]

**Screenshots**
![image](https://user-images.githubusercontent.com/29918611/209306390-f4fd75f4-cf82-4235-8465-5fc0d444cb38.png)

**Comment by PJB3005** [comment]
Prototypes are definitely parsed ahead of time. Are you sure this isn't an issue with markings failing to mark a datafield as required?

**Comment by clement-or** [comment]
This happened because a markings component was missing from a playable species I was trying to define. This seems more a problem towards how a specific system requires components from other entities rather than prototypes parsing.

imho, systems should be able to function even if a specific component is absent from a given entity, or at least throw relevant exceptions that point towards an issue with the prototypes rather than NullRef exceptions

**Comment by PJB3005** [comment]
I mean, yeah, they generally can. This just seems like a specific bug with marking code.

**Comment by moonheart08** [comment]
This is a bug with markings code and it failing to mark a field as required, not with prototypes.
