### ISSUE TITLE
Most sounds lenghts seem to have shortened

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#13174]
## Description

 Blender, lightning strike when an artifact spawns, the science upgrade thingy
**Reproduction**

**Screenshots**

**Additional context**

**Comment by mirrorcult** [comment]
wat

**Comment by DogZeroX** [comment]
So, the thing is that the sounds they make stop when the do-after finishes, which abruptly cuts it and makes it sound bad.
