### ISSUE TITLE
Anchored structures remain tilted

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#13183]
## Description

Dragged a structure out of a salvage grid, it ended up tilted inside the shuttle even after being anchored
**Reproduction**

**Screenshots**

![image](https://user-images.githubusercontent.com/43253663/209478650-1908b522-604f-47b8-9273-0ff23f994552.png)

**Additional context**

**Comment by mirrorcult** [comment]
probably fixed by https://github.com/space-wizards/RobustToolbox/pull/3634?
