### ISSUE TITLE
PA generator not scanning properly.

### ISSUE THREAD

**Issue by liltenhead** [space-wizards/space-station-14#13201]
Saw it in a live round, the particle accelerator doesn't scan parts correctly. I tested it with multiple orientations. Moving parts around seems to help a bit, but not enough to get the entire thing working. 
![PA](https://user-images.githubusercontent.com/104418166/209588675-fc58b8c9-9a24-4509-b9e0-35a58af375f9.PNG)
![pa2](https://user-images.githubusercontent.com/104418166/209588697-c5cb77bc-5eed-4137-af55-c7855d8ec180.PNG)

**Comment by liltenhead** [comment]
It however appears to be working in the next round, not sure what's up.

**Comment by retequizzle** [comment]
Can confirm this is still an issue and is on master currently, PA will register as active/connected properly when facing the same direction as the operational diagram but has a tendency to not work if built any other way.

**Comment by giuliano-marinelli** [comment]
I confirm this is buggy, we had the same situation as showed on first image yesterday.

**Comment by AruMoon** [comment]
When fix?

**Comment by DogZeroX** [comment]
when you fix it

**Comment by VelonacepsCalyxEggs** [comment]
Still a relevant issue.

**Comment by liltenhead** [comment]
Should be fixed now.

**Comment by VelonacepsCalyxEggs** [comment]
It still doesn't scan properly. It's highly inconsistent.

**Comment by Emisse** [comment]
i merged the actual fix 1 hour ago, not live yet, ill publish in a bit

**Comment by VelonacepsCalyxEggs** [comment]
> i merged the actual fix 1 hour ago, not live yet, ill publish in a bit

Nice!
