### ISSUE TITLE
You can toogle internals while in critical state.

### ISSUE THREAD

**Issue by AlexMorgan3817** [space-wizards/space-station-14#13207]
**Reproduction**
I got critical because of 4 bullets in belly and zombie bites. Then I was able to turn on/turn off gas tank connected to mask.
**Screenshots**
![image](https://user-images.githubusercontent.com/46600554/209637581-48fa3088-a8fc-41bc-8cf2-c667df39492c.png)
![image](https://user-images.githubusercontent.com/46600554/209637777-b0842619-7683-465d-b86b-caf7a0c6ba53.png)

**Comment by thekaio123** [comment]
You can do some more actions while in crit state, as far as i've seen, you can rotate in chairs too

**Comment by lzk228** [comment]
fixed?
