### ISSUE TITLE
I thought the medicne descriptions needed a rewritre

### ISSUE THREAD

**Issue by GoldyStuff** [space-wizards/space-station-14#13217]
sorry if i did something wrong, i dont use git often and dont know what to do in this case. i just thought the chemicals could use better descriptions and stuff. not sayin the others were bad, just old. and there were a large number of overdose effects that just... never actually happened.

reagent-name-cryptobiolin = cryptobiolin

  | reagent-desc-cryptobiolin = Not SDA Approved, Cryptobiolin has not yet been proven to do anything other than cause confusion, dizziness and violent depression. Although here at the 14th space station, we’ve been able to prove that Cryptobiolin in fact does not cause any effects.
  |  
  | reagent-name-dylovene = dylovene
  | reagent-desc-dylovene = Originating from 2260s Starfleet, Dylovene is known as a broad-spectrum anti-toxin which is warned by the SDA to cause vomiting and dizziness during an overdose, the SDA had never specified the amount required to overdose and no evidence of a Dylovene overdosing has ever existed leading many colonies, cosmonauts and space station staff to believe the SDA had been lying to them. But wait a second! the government wouldn’t lie to us!
  |  
  | reagent-name-diphenhydramine = diphenhydramine
  | reagent-desc-diphenhydramine = A drowsy antihistamine that reduces the effects of self harm inflicting allergic reactions caused by an increase of histamine, side effects may include a dry mouth or nose, double vision, rapid heart rate or difficulty disposing of bodily waste.
  |  
  | reagent-name-arithrazine = arithrazine
  | reagent-desc-arithrazine = Originating from Starfleet, this unstable chemical compound causes slight pain to the patient but heals hyperthyroidism and protects thyroid glands by absorbing radiation.
  |  
  | reagent-name-bicaridine = bicaridine
  | reagent-desc-bicaridine = The chemical compound known as bicardarine was named after the surname "Picardy" in northern France, It is now known for its ability to hinder internal or external blood hemorrhaging by increasing capillary endothelial resistance and promoting platelet adhesion.
  |  
  | reagent-name-cryoxadone = cryoxadone
  | reagent-desc-cryoxadone = A super medicine that can only work in temperatures under 170K, The space-cryo-organization suggests this as a constant life-blood for cryogenically frozen staff.
  |  
  | reagent-name-dermaline = dermaline
  | reagent-desc-dermaline = Dermaline is a skin care chemical using keratin to gather and group dead skin cells together while it uses allantoin and alpha hydroxy acids to moisturize the inner or outer layer of dead skin cells, forcing the cells to slowly wither and give a smoother new layer. The SDA Recently announced Dermaline might be more effective than Kelotane and is also recommended for general day to day skin care.
  |  
  | reagent-name-dexalin = dexalin
  | reagent-desc-dexalin = Increases the oxygen intake in your lungs by forcing your lungs to take in around 3-4u more of carbon dioxide.
  |  
  | reagent-name-dexalin-plus = dexalin plus
  | reagent-desc-dexalin-plus = Although rumored to cause a low mental state, These rumors were proven false, Said rumor started by a “Dr. Crusher” who had used an unspecified dosage on two patients that were already on many medicinal drugs. Dexalin-plus quickly heals asphyxiation damages through synthetic oxygen and hormones to induce a greater oxygen intake to dying cells with the added bonus of some bloodstream health benefits, much stronger than its inferior version, Dexalin.
  |  
  | reagent-name-epinephrine = epinephrine
  | reagent-desc-epinephrine = A cardio stimulating super medicine made with oil that can resuscitate patients in a critical state by restarting their heart rhythm, Gives an extreme rush of adrenaline causing higher muscular speeds, cramped hands and reduced stuns. The SDA has warned just 30u is enough to overdose on.
  |  
  | reagent-name-hyronalin = hyronalin
  | reagent-desc-hyronalin = A weak but cheap treatment for radiation, So weak in fact, all other medicinal drugs or just adrenaline could counter the radiation more than Hyronalin. Only really good if a patient can not produce or take adrenaline at the time.
  |  
  | reagent-name-ipecac = ipecac
  | reagent-desc-ipecac = Causes vomiting of anything in your chemical stream or stomach, ironically when in your chemical stream or stomach. Anything that has not yet metabolized comes out with ease, recommended if your name is gus.
  |  
  | reagent-name-inaprovaline = inaprovaline
  | reagent-desc-inaprovaline = A synaptic-cardiac stimulant that forces the brain to slow down the heart.
  |  
  | reagent-name-kelotane = kelotane
  | reagent-desc-kelotane = Saturates and disinfects the skin, this has an effect on the speed of skin cell regeneration which reduces the time needed to fully heal to 50 seconds.
  |  
  | reagent-name-leporazine = leporazine
  | reagent-desc-leporazine = Adjusts inner body pressure at high doses of around 110u and rapidly adjusts body temperature, seems to be negated by cryogenics
  |  
  | reagent-name-barozine = barozine
  | reagent-desc-barozine = A potent drug that prevents pressure damage. Causes extreme pain and jittering. Very poisonous when overdosed. Reduces effects of barotrauma and pressure damage at just 2u but causes extreme pain and jittering due to your tissues stretching and sometimes your bones breaking, onto of this you might have a hard time keeping all your bodily fluids in and will have a large amount of blood not reaching the rest of your body, deadly if over 30u.
  |  
  | reagent-name-phalanximine = phalanximine
  | reagent-desc-phalanximine = A 50 second cure for cancer assuming you metabolise 25u and are at 100 cellular damage, Phalanximine will also deal 2 Radiation for every 2 Cellular. The SDA Regulations demand at least 100u of a high strength radiation blocker nearby before treatment.
  |  
  | reagent-name-romerol = romerol
  | reagent-desc-romerol = Reverses the effects of miasma-induced cellular resuscitation.
  |  
  | reagent-name-pulped-banana-peel = pulped banana peel, reduces bleeding significantly.
  | reagent-desc-pulped-banana-peel = Pulped banana peels have some effectiveness against bleeding. Those monkeys know something we don’t.
  |  
  | reagent-name-siderlac = siderlac
  | reagent-desc-siderlac = A powerful anti-caustic medicine derived from plants that reduces the effects of acidic substances.
  |  
  | reagent-name-spaceacillin = spaceacillin
  | reagent-desc-spaceacillin = An antibiotic used to slow or even stop the progression of space diseases by blocking Voltage-Gated membrane channels.
  |  
  | reagent-name-stellibinin = stellibinin
  | reagent-desc-stellibinin = A Natural antitoxin oil with a strong immunity against amotoxin, typically used by 40 year old soccer moms.
  |  
  | reagent-name-synaptizine = synaptizine
  | reagent-desc-synaptizine = The SDA has banned this substance due to it’s ability to kill with just 2u. But we hate the SDA so it’s still legal here. Although deadly at 2u, at 1u it can remove hallucinations.
  |  
  | reagent-name-tranexamic-acid = tranexamic acid
  | reagent-desc-tranexamic-acid = An anti heamoragging medicine to reduce blood loss from brute trauma or bloody bad times.
  |  
  | reagent-name-tricordrazine = tricordrazine
  | reagent-desc-tricordrazine = A multi-purpose stimulator that branched from cordazine, It heals almost everything but very slowly and at a certain point, making other drugs are quicker and easier.
  |  
  | reagent-name-lipozine = lipozine
  | reagent-desc-lipozine = Causes a chemical lipo-suction by using a secret chemical to convert fat into… umm… you’ll find it in your toilet later.
  |  
  | reagent-name-omnizine = omnizine
  | reagent-desc-omnizine = A soothing milky liquid with an iridescent gleam. A well known conspiracy theory says that it's origins remain a mystery because knowing the secrets of its production would render most commercial pharmaceuticals obsolete. Consuming it gives a smooth and calming experience as you feel several types of damage and all of your toxicity fade away 4u at a time… ok we may have put a few illegal drugs in here but shush.
  |  
  | reagent-name-ultravasculine = ultravasculine
  | reagent-desc-ultravasculine = Removes all toxins in the body but comes at the cost of your veins possibly exploding.
  |  
  | reagent-name-oculine = oculine
  | reagent-desc-oculine = Heals eye damage and gives you 20/20 vision!
  |  
  | reagent-name-ethylredoxrazine = ethylredoxrazine
  | reagent-desc-ethylredoxrazine = Useful at bars, this drug cancels out the effects of booze. Basically never used though, the last time this was bought was when an admin wanted to get drunk and then drunk again over and over.
  |  
  | reagent-name-cognizine = cognizine
  | reagent-desc-cognizine = A mysterious chemical which is able to make any non-sentient creature sentient by giving it access to completely reliable and trustable google. Immediately terminate if said being attempts to google “google”, its gotten too smart. It’ll kill us all… run.

**Comment by moonheart08** [comment]
While we appreciate the enthusiasm, this is an issue, not a change. Additionally, I'm not sure we really want any of these descriptions, they read less like descriptions and more like someone (a speaker) trying to tell jokes about the chemical.

You're looking for https://docs.spacestation14.io/en/getting-started/dev-setup
