### ISSUE TITLE
Cluster map, missplaced console.

### ISSUE THREAD

**Issue by omegaGreeNya** [space-wizards/space-station-14#13230]
## Description
Map Cluster. Power console near dorms is unreachable IC without breaking/deconstructing walls/window.

Don't know how, but it's reachable when red marked window is deconstructed.

**Reproduction**
Go to mentioned console and try to use it.

**Screenshots**
![image](https://user-images.githubusercontent.com/86734901/210068448-0f529a27-344e-4369-9d84-ad80482c0609.png)

**Comment by 778b** [comment]
https://github.com/space-wizards/space-station-14/pull/13245
