### ISSUE TITLE
TPS performance is heavily reduced over 50-60~ players on good hardware

### ISSUE THREAD

**Issue by ProfanedBane** [space-wizards/space-station-14#1324]
Currently the game's performance is heavily kneecapped when large amounts of players are online. This is regardless of good or bad hardware.

**Comment by ProfanedBane** [comment]
@SweptWasTaken Reopen this coward.

**Comment by metalgearsloth** [comment]
Shouldn't be anymore and having a vague issue doesn't help heaps.
