### ISSUE TITLE
In low TPS situations items/players can phase through walls

### ISSUE THREAD

**Issue by ProfanedBane** [space-wizards/space-station-14#1327]
In low TPS situations running into a wall/table, and especially corners can cause you to phase through.
Lockers etc you push will also easily go through walls.

**Comment by ProfanedBane** [comment]
Crossposting from the duplicate issue which happens at the server default of 30 tps.

I've found lockers can be pushed through walls in many instances, mostly up and down but up is easier.
The best way to reproduce is to try to push one through the boundary of two wall tiles.
I've yet to be able to do it with water/welding tanks or crates, so it's either lockers are thin enough to make it through or there's some snowflake behavior on them.

Video: [https://cdn.discordapp.com/attachments/675078881425752124/731116771310043146/2020-07-10_12-50-43.mp4](https://cdn.discordapp.com/attachments/675078881425752124/731116771310043146/2020-07-10_12-50-43.mp4)

**Comment by cyclowns** [comment]
can reproduce with lockers on tps 60 as well, but the effect isn't as drastic. specifically only occurs when pushing lockers into the seam between two walls

**Comment by metalgearsloth** [comment]
New physics engine and this is significantly harder to do soooooo
