### ISSUE TITLE
Admins can't easily delete nuke disks

### ISSUE THREAD

**Issue by Chief-Engineer** [space-wizards/space-station-14#13274]
#12762 prevents nuke disk deletion, even when intended unless the component is removed first. Directly attempting to delete an item with the component using the context menu, delete command, or spawn menu's erase button should probably not cause it to respawn. Indirectly deleting it, by deleting an entity it is contained in, should cause it to respawn.

**Comment by mirrorcult** [comment]
this seems fine, you can remove the component before deleting it

**Comment by QuietlyWhisper** [comment]
(It was me, I forgot the disk could respawn)
That would be great for logs too, if the nuke disk manages to get destroyed by players or otherwise!
