### ISSUE TITLE
Can't pick up items dropped inside a Ripley.

### ISSUE THREAD

**Issue by Vordenburg** [space-wizards/space-station-14#13324]
## Description

I can drop items from inside the Ripley mech, and they go onto the floor below it, but I can't pick them up. It seems like one of these behaviors is incongruent.

**Reproduction**

1. Spawn mech.
2. Get inside.
3. Drop backpack.
4. Move away to see backpack on floor.
5. Click on backpack and find out that you can't pick it up.

**Comment by IProduceWidgets** [comment]
Seems fixed
