### ISSUE TITLE
Lockers (all pushables?) can be pushed through walls

### ISSUE THREAD

**Issue by ProfanedBane** [space-wizards/space-station-14#1338]
I've found lockers can be pushed through walls in many instances, mostly up and down but up is easier.
The best way to reproduce is to try to push one through the boundary of two wall tiles.
I've yet to be able to do it with water/welding tanks or crates, so it's either lockers are thin enough to make it through or there's some snowflake behavior on them.

Video: [https://cdn.discordapp.com/attachments/675078881425752124/731116771310043146/2020-07-10_12-50-43.mp4](https://cdn.discordapp.com/attachments/675078881425752124/731116771310043146/2020-07-10_12-50-43.mp4)

**Comment by ike709** [comment]
It's also pretty easy to push them onto a table.

**Comment by ProfanedBane** [comment]
Turns out this is a duplicate of https://github.com/space-wizards/space-station-14/issues/1327, only it's visible at the server default of 30 tps.

**Comment by DrSmugleaf** [comment]
This is a lot easier to replicate now.

**Comment by SweptWasTaken** [comment]
Tried for a while to replicate on current master, looks to be only present in very uncommon situations. (Really really bad TPS which there's already and issue for #1327 ) Or when there's like 50 pushables in the same area. Closing.
