### ISSUE TITLE
Character Preferences

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/space-station-14#134]
What it says on the thin. Should be stored client side in the user data directories so that we don't have to store them server side. Client's problems.

**Comment by RemieRichards** [comment]
I'm working on this.

**Comment by DamianX** [comment]
Still working on this?

**Comment by RemieRichards** [comment]
let's say yes

**Comment by DamianX** [comment]
Any progress?

**Comment by RemieRichards** [comment]
Heck no.
My motivation is down the toilet.

Feel free to leapfrog if you want to.

**Comment by DamianX** [comment]
I'm picking this up.

**Comment by DamianX** [comment]
Do you want to share any of the work you've done so far?

**Comment by RemieRichards** [comment]
I have some stuff, and had some discussions with others about how to best implement it, we can go over that later if you're around (4-5 hours from now?) otherwise I can write something up + push a branch for you to look at whenever.

**Comment by DamianX** [comment]
Both options sound good, I'll probably be available any time.
