### ISSUE TITLE
Item actions get duplicated

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#13408]
At least the magboots one is, just equip it and see it show up twice or disappear twice.

**Comment by Insineer** [comment]
From linked PR:

![image](https://user-images.githubusercontent.com/22466026/216205283-eabe855d-7089-49a1-ba8c-374dc9eb8e20.png)

Seems like the difficulty is underestimated.

**Comment by deltanedas** [comment]
this has been fixed, on miros magboots no longer acting sus!!!
