### ISSUE TITLE
ahelp relay disconnected

### ISSUE THREAD

**Issue by Chief-Engineer** [space-wizards/space-station-14#13411]
## Description

Lizard's ahelp relay disconnected randomly during round 19432. The only other time I've seen something like this happen was months ago, a server restart fixed it.

**Reproduction**

I have no clue how to reproduce it, Sloth requested an issue.

**Comment by DrSmugleaf** [comment]
Fixed by https://github.com/space-wizards/space-station-14/pull/13416
