### ISSUE TITLE
Bodies make constant thumping noise

### ISSUE THREAD

**Issue by liltenhead** [space-wizards/space-station-14#13461]
Crit or kill anything, they'll make the falling over sound constantly until the entity is deleted or healed. 
It also will spam logs with crit to alive state over and over. 
![image](https://user-images.githubusercontent.com/104418166/212448039-7a04f57d-f354-4448-9d14-695db75f5a6b.png)

**Comment by mirrorcult** [comment]
@Jezithyr

**Comment by Jezithyr** [comment]
Working on this!
