### ISSUE TITLE
Ripley unable to pick anything up

### ISSUE THREAD

**Issue by Ilya246** [space-wizards/space-station-14#13483]
## Description
Ripley hydraulic clamp does not work at all

**Reproduction**
Enter ripley, swap to hydraulic clamp, try to pick any item up, it does not work (tried with items of all sizes by several people)

**Screenshots**
![изображение](https://user-images.githubusercontent.com/57039557/212537437-4c002aa5-0221-4064-8569-54b397b33f31.png)
(tried clicking, ctrl-clicking, alt-clicking on several objects both in and not in harm mode)

**Additional context**
I believe this started happening since the update that prevented ripleys from picking up living things

**Comment by ZoldorfTheWizard** [comment]
Did the ripley have any power? if there is no battery installed it will be unable to pick anything up.

**Comment by EmoGarbage404** [comment]
works on my machine

**Comment by retequizzle** [comment]
ripley works fine, you have to have the following:

a) a battery in the ripley
b) a hydraulic clamp installed
c) hydraulic clamp SELECTED as your active peripheral (this can be cycled on your hotbar)

proof of the item in the hydraulic clamp storage from today, including hotbar so you see what icon you have to press (slot 8 in this case):
![7zfHtKL](https://user-images.githubusercontent.com/67210376/213060377-62609f72-6e1a-4c3e-928e-f4bb7eeda1d5.png)

**Comment by EmoGarbage404** [comment]
Multiple people have not been able to replicate this bug, so I think there might have been an unseen user issue. The steps listed on this issue do not produce a bug of any kind.
