### ISSUE TITLE
ID-examine verb needs a new icon

### ISSUE THREAD

**Issue by ElectroJr** [space-wizards/space-station-14#13505]
Currently its just a "?" which is fine, but will start clashing with "help" examine verbs which use the same icon. I guess the icon should probably be the outline of a person? Or an ID card?

**Comment by Vaaankas** [comment]
maybe just two letters [ID] ?

**Comment by deltanedas** [comment]
@ElectroJr pro

**Comment by Plykiya** [comment]
![image](https://github.com/user-attachments/assets/a9c5ccb2-2356-4311-8535-b5e1f51c7730)
