### ISSUE TITLE
Need more guidebook entries & help verbs

### ISSUE THREAD

**Issue by ElectroJr** [space-wizards/space-station-14#13506]
More or less what the title says. Ideally most game mechanics should at least have a basic overview of how they work. 

Guides documents should generally be put into `Resources/Server Info/Guidebook/`, with prototypes in `Resources/Prototypes/Guidebook/`. It should be relatively straightforward to figure out the guide document format by looking at existing guides. Also, when it comes to troubleshooting parsing issues, you should be able to just refresh the guide document by opening & closing the guide without needing to restart the client.

Additionally:
- Existing guides should probably be reviewed / improved
- Entities should link to relevant guides via the help verb (see `GuideHelpComponent` & how it is currently used to link to the the AME  guide)
- Guides could probably use better/more controls. In particular, maybe some sort of keybinding icon/control for the controls guide?

**Comment by mirrorcult** [comment]
see "Guidebook content" milestone if you want to help with this more specifically

**Comment by OttoMaticode** [comment]
#16287

**Comment by shadows643** [comment]
i am fairly new to helping with the game so how do i exactly make a guidebook page sorry prob not worth your time reading this

**Comment by OttoMaticode** [comment]
> i am fairly new to helping with the game so how do i exactly make a guidebook page sorry prob not worth your time reading this

https://docs.spacestation14.io/en/content/writing-guidebook-entries****

**Comment by shadows643** [comment]
what subjects don't have guidebooks yet?

**Comment by OrionTheOtter** [comment]
could we get a more complete reciepe guide like how there is for chem but with food?

**Comment by ElectroJr** [comment]
This issue is pretty vague and is the kind of thing that will probably never get closed. So I'm replacing it with something that is more specific #28615
