### ISSUE TITLE
Destroying a locker sends anyone inside to the shadow realm

### ISSUE THREAD

**Issue by ProfanedBane** [space-wizards/space-station-14#1352]
Shooting a locker to destruction inside of it causes you to become invisible and unable to move.
Having another locker moved over you and getting inside it allows you to escape via movement.

[https://cdn.discordapp.com/attachments/675078881425752124/731234673254072350/2020-07-10_20-41-07.mp4](https://cdn.discordapp.com/attachments/675078881425752124/731234673254072350/2020-07-10_20-41-07.mp4)

**Comment by DrSmugleaf** [comment]
This is because when a locker is destroyed or its component is removed no new component state reaches the client telling it to remove the entity from storage, which never updates the entity's occlusion. The state is never sent because the component or entity is deleted.
