### ISSUE TITLE
anomaly pulse/BWUUUUUUM sound plays repeatedly

### ISSUE THREAD

**Issue by retequizzle** [space-wizards/space-station-14#13535]
seems to happen more when the anomalies are off screen, sound will originate from 0 0 and will keep trying to play multiple times in a single second 

so instead of hearing the old bwuuuuuuum we're used to, it goes

BWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBW and drives me up a fuckin wall

**Comment by EmoGarbage404** [comment]
Is this clientside sound? If so, can you just fix it by making the sounds server only?

**Comment by EmoGarbage404** [comment]
gonna need replication steps for this or at least a concrete explanation of what's happening. the fact that it's persisting between rounds is also extremely worrisome.

**Comment by retequizzle** [comment]
this issue may be closed, we are no longer experiencing the issue listed here so it is safe to assume the other PR you mentioned also fixed this one
