### ISSUE TITLE
Being stunned while there's no gravity still lets you control your character

### ISSUE THREAD

**Issue by ProfanedBane** [space-wizards/space-station-14#1353]
Repro
- No gravity
- Slip on banana
- Zip around on an adventure

[https://cdn.discordapp.com/attachments/310780221156491265/731236779092606976/2020-07-10_20-51-26.mp4](https://cdn.discordapp.com/attachments/310780221156491265/731236779092606976/2020-07-10_20-51-26.mp4)

**Comment by ike709** [comment]
@Zumorica

**Comment by metalgearsloth** [comment]
Physics refactor fixed this pretty sure.
