### ISSUE TITLE
Banana peels block bullets

### ISSUE THREAD

**Issue by ProfanedBane** [space-wizards/space-station-14#1354]
The ultimate life form.
Lasers can shoot through them as normal.

Repro
- Place banana peel on ground
- Unload your ballistics dakka
- Get dunked

[https://cdn.discordapp.com/attachments/310780221156491265/731236834352431215/2020-07-10_20-53-00.mp4](https://cdn.discordapp.com/attachments/310780221156491265/731236834352431215/2020-07-10_20-53-00.mp4)

**Comment by ike709** [comment]
@Zumorica

**Comment by AJCM-git** [comment]
fixed in #1397
