### ISSUE TITLE
Unstable particle balance

### ISSUE THREAD

**Issue by liltenhead** [space-wizards/space-station-14#13545]
## Description
You can reach a point where shooting too many unstable particles into an anomaly, renders the anomaly impossible to stabilize. 
I spent 2 minutes shooting only unstable particles, then after like 12 stable shots, it died completely. 
## Before
![1 before](https://user-images.githubusercontent.com/104418166/212890427-1f204b15-33d0-4e42-bca3-422e9ca26047.PNG)
## After
![1 after](https://user-images.githubusercontent.com/104418166/212890432-b158d530-3e9c-4750-9314-f156f7049f1e.PNG)

It died after I swapped to only containment particles, it never reached stable and died in the growing phase.

**Comment by EmoGarbage404** [comment]
just as a clarification, the anomaly wasn't "overly unstable", but rather the "re-stabilizing" was too weak to be effective.
