### ISSUE TITLE
Animation speeds run slower when right-clicked

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#13540]
I have no idea if this is a content or engine bug. If you right-click your character its animation runs slower. Not sure if the normal fire one is sped up or the right-click one is slowed down.

https://user-images.githubusercontent.com/31366439/212875867-6115aa54-b411-4c84-8dfb-3b05cafae8dd.mp4

**Comment by moonheart08** [comment]
Does this occur with the (C)haracter menu open when burning as well?

**Comment by ElectroJr** [comment]
I can't seem to reproduce this, was this inadvertently fixed at some point?

**Comment by metalgearsloth** [comment]
Yeah so planetmaps were showing up twice in grid queries so animations were running twice.
