### ISSUE TITLE
Anomalies spawning at 0,0 on some maps

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#13543]
## Description

per emisse: anomalies were spawning normally on marathon

but on kettle anomalies spawned at 0,0 multiple times in a row, didnt seem to be anywhere else

**Reproduction**

1) force kettle
2) spawn nobbly with generator
3) ??? maybe it repros

**Screenshots**

**Additional context**

**Comment by EmoGarbage404** [comment]
This is probably due to the matrix tranform issues while spawning that sloth pointed out
