### ISSUE TITLE
Door electronics mapped on kettle are broken

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#13549]
## Description

repro'd in an ahelp

![image](https://user-images.githubusercontent.com/19853115/212965883-68cbeff5-866f-44a9-8870-9a863766e92c.png)

for some reason they are mapped with a tag component which is overriding the tags they need to be usable for construction

**Reproduction**

1) force kettle
2) take door electronics from tech storage (8.5, 33.5)
3) try to put in airlock
4) no work

**Screenshots**

**Additional context**

**Comment by mirrorcult** [comment]
@Cheackraze

**Comment by Cheackraze** [comment]
> @Cheackraze

I can't reproduce this, and those are the only door electronics prototype so I don't know what the issue is

**Comment by mirrorcult** [comment]
i mean, i explained exactly why its occurring

the door electronics normally have these tags:
![image](https://user-images.githubusercontent.com/19853115/212966621-0f3ff603-2c8b-40b7-a687-7852aec2feee.png)

the ones on kettle for some reason override the tags with this:
![image](https://user-images.githubusercontent.com/19853115/212966726-49fdec76-98f5-4c34-9241-3d78efd952d0.png)

**Comment by Cheackraze** [comment]
Ok, I'll try replacing them i guess, does this happen to other maps? I did nothing to those except place them so it's probably not a map specific thing

**Comment by mirrorcult** [comment]
didnt look like it happened on any other maps. no idea why. they might have just been broken at the time kettle was mapped?
