### ISSUE TITLE
anomaly generator ui sprite view is broken

### ISSUE THREAD

**Issue by EmoGarbage404** [space-wizards/space-station-14#13559]
## Description

using an offset makes it appear halfway out of the box.
@metalgearsloth

**Comment by metalgearsloth** [comment]
Fixed in https://github.com/space-wizards/RobustToolbox/pull/3708 probably

**Comment by Visne** [comment]
I checked and that makes it look like this: 
![image](https://user-images.githubusercontent.com/39844191/213567147-9efb60a8-2bc4-4372-bd2b-0189450e9992.png)

**Comment by jamessimo** [comment]
Fix for this is on this pending PR https://github.com/space-wizards/RobustToolbox/pull/3865

once it’s merged I will make a PR to this repo to add the fixed spriteOffset = false along with some minor improvements
