### ISSUE TITLE
Anomaly feature request issue

### ISSUE THREAD

**Issue by EmoGarbage404** [space-wizards/space-station-14#13560]
## Description

handheld APE that can be researched
- call it CHIMP or something funny like that
- make it lategame sci anomaly research

Way to move around anomalies
- small amount of movement in exchange for severity and stability
- GORILLA cannon
- mid-game anomaly stuff.

More anomalies
- like 6 good ones would be nice

**Comment by Visne** [comment]
It would be kinda funny if you could move them around but only very carefully, as otherwise they might become too unstable or something like that. No idea how you would actually implement that though.

**Comment by EmoGarbage404** [comment]
> It would be kinda funny if you could move them around but only very carefully, as otherwise they might become too unstable or something like that. No idea how you would actually implement that though.

The suggestion i was given was to have a variant of an APE that could move it around a little bit in exchange for increased severity and making it unstable.

If you wanted it to be *really* funny, dont just make it move a few tiles: make it ping pong around for a few seconds.
