### ISSUE TITLE
Playing lots of sounds generates exceptions

### ISSUE THREAD

**Issue by ProfanedBane** [space-wizards/space-station-14#1359]
While playing with around 1000 xenos running around making step sounds the game can drop to low fps and output exceptions.

[ERRO] clyde.oal: [SetPosition:492] AL error: OutOfMemory
[ERRO] clyde.oal: [SetPitch:510] AL error: InvalidName
[ERRO] clyde.oal: [SetVolume:429] AL error: InvalidName
[ERRO] clyde.oal: [SetPlaybackPosition:466] AL error: InvalidName
[ERRO] clyde.oal: [IsLooping:407] AL error: InvalidName
[ERRO] clyde.oal: [StartPlaying:374] AL error: InvalidName

https://pastebin.com/2fprfvag

**Comment by ElectroJr** [comment]
Engine issue space-wizards/RobustToolbox/issues/2388
