### ISSUE TITLE
Ahelp window needs to forget filter on close

### ISSUE THREAD

**Issue by Mirino97** [space-wizards/space-station-14#13604]
## Description

Everytime you filter and close the ahelp window, when you open it again, the filter stays there.

This is annoying because you have to manually remove it before you try to answer someone else. Also, if you try to admin message someone through the right click menu, it opens the ahelp window but keeps the filter applied, so you could accidentally bwoink the wrong person.
**Reproduction**

**Screenshots**

**Additional context**

**Comment by Visne** [comment]
I can recreate this, but not through the right click menu. Then the filter is actually removed.

**Comment by Visne** [comment]
Also I would be curious to hear whether others agree that this is a bug, I think personally I would prefer it (but it would be very nice if there was an X button on the right side of the text box to clear it completely).
