### ISSUE TITLE
Clicking yourself with a welding tool says you can't be deconstructed

### ISSUE THREAD

**Issue by MemeProof** [space-wizards/space-station-14#1361]
Repo:
-Grab a welding tool
-Click yourself (For me, it gave the message regardless if on or off)
![image](https://user-images.githubusercontent.com/43192081/87213971-f700f580-c2f6-11ea-900d-83aee1fabd89.png)

**Comment by RemieRichards** [comment]
Is it wrong? ;)

**Comment by MemeProof** [comment]
With better tools...
