### ISSUE TITLE
Cuffable/Handcuffs desperately needs to be refactored/cleaned up

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#13614]
## Description

- move all code out of the component
- no more random shitty properties and obsolete code
- just put everything in shared please
- use appearance data with the clientside system instead of the rsi and shit being in component state

**Reproduction**

**Screenshots**

**Additional context**

**Comment by metalgearsloth** [comment]
Isn't this https://github.com/space-wizards/space-station-14/issues/9965
