### ISSUE TITLE
Vending/other machine ghost role spam

### ISSUE THREAD

**Issue by AJimmyU** [space-wizards/space-station-14#13618]
## Description

Ghost role list gets filled up with vending machine roles in needless categories. These roles can all be summarized as "worse pAI" and don't need a separate category for each vending machine type. It leads to trouble finding actually desirable roles that can interact with the round in a way that's not just screaming from an immobile prison.

**Reproduction**

Play a longer round, check ghost roles.

**Screenshots**

![useless](https://user-images.githubusercontent.com/112694440/213773075-c64581f2-d8d5-4aaf-8a0d-6d35519142b0.png)

**Additional context**

Having an option to never see certain ghost roles would be a welcome addition. Does anyone actually enjoy this ghost role?

**Comment by Vaaankas** [comment]
No i hate it

**Comment by deltanedas** [comment]
putting all of them under the one category would remove almost all of the wasted space
