### ISSUE TITLE
central.spacestation14.io times out

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#13647]
## Description
central times out so have to go outside!!!!

**Reproduction**
`curl -v https://central.spacestation.14.io`

**Screenshots**
![17:19:00](https://user-images.githubusercontent.com/39013340/213930069-b42e28f6-414a-4367-9019-9e92303c6714.png)

**Additional context**
happens for me and another person

**Comment by PJB3005** [comment]
we're aware, this shouldn't go on github
