### ISSUE TITLE
Popped out ahelp windows need to be reopened after rounds

### ISSUE THREAD

**Issue by Chief-Engineer** [space-wizards/space-station-14#13664]
## Description
Ahelp windows which are popped out will stop updating after returning to the lobby after a round and need to be closed and reopened to be fixed.

**Comment by Visne** [comment]
I guess normally the ahelp window closes when a round ends, but the popped out ahelp window just stays while not updating anymore. So we should either close the popped out window at round end, or make ahelp windows not close after the round ends (probably preferred, but there is probably a technical reason they close).
