### ISSUE TITLE
Certain entities have visual issues for their spawn preview

### ISSUE THREAD

**Issue by Chief-Engineer** [space-wizards/space-station-14#13663]
## Description
On Wizden Lizard:

- trying to spawn any Urist gives no preview
- trying to spawn any ERT, CBURN, or centcom official makes the whole screen black
- not all ghost roles are affected, for example, mice work fine

All affected entities can be spawned by using the `spawn` command, or by ignoring the visual issues. All visual issues stop once you deselect the entity for spawning. The issue has persisted across restarts. I've tested this locally and didn't have any issues but I'm not sure if I was running the same version as lizard.

**Comment by metalgearsloth** [comment]
These entities need spritecomponent adding.

```
[ERRO] runtime: Caught exception in "UserInterfaceManager"
System.Collections.Generic.KeyNotFoundException: Entity c40 does not have a component of type Robust.Client.GameObjects.SpriteComponent
   at Robust.Client.Placement.PlacementMode.Render(DrawingHandleWorld handle) in D:\Programming\space-station-14\RobustToolbox\Robust.Client\Placement\PlacementMode.c
s:line 93
```

They incorrectly only have IconComponent which should also probably be removed.
