### ISSUE TITLE
BUG with Wrong styles for airlocks

### ISSUE THREAD

**Issue by 778b** [space-wizards/space-station-14#13670]
## Description
Selected style will never apply to your airlock by airlock painter, if you selected one game will set next of ur selected style

**Reproduction**
1)Get up a airlock painter
2)Select style that you want
3)Color the airlock
4)You get a wrong style on ur airlock

**Screenshots**
![image](https://user-images.githubusercontent.com/33431126/214129305-c37cf404-c281-4e5b-ab23-518d9e0ba229.png)
![image](https://user-images.githubusercontent.com/33431126/214129344-e28e1ef0-4739-4651-8662-edb684ca2acc.png)

**Comment by 778b** [comment]
I think its a bug of replication, because cant find any algorithm bug in code

**Comment by mirrorcult** [comment]
i looked at this earlier but the code was really ugly so i didnt feel like touching it. the issue is that dictionary ordering is no longer guaranteed to be insertion order for .NET 7, so the server and client differ

**Comment by 778b** [comment]
yep its logic on server work fine, but UI of player is wrong
