### ISSUE TITLE
Spider's webs appear over walls

### ISSUE THREAD

**Issue by Chief-Engineer** [space-wizards/space-station-14#13684]
## Description

Webs shouldn't be placed onto tiles with walls/windows, ideally the web that would be placed there should attempt to be placed in a slightly larger radius within line of sight.

**Comment by AJCM-git** [comment]
I think it makes sense that spiders can place webs over walls

**Comment by UbaserB** [comment]
I dont mind it personally

**Comment by IProduceWidgets** [comment]
I also think this is probably fine.
