### ISSUE TITLE
zombies lose names when cloned

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#13698]
## Description
 says: "Hi"

**Reproduction**
1. become zombie
2. get cloned
3. no name!

**Screenshots**
![13:44:17](https://user-images.githubusercontent.com/39013340/214310592-2b26f4f4-c3f6-475c-a97e-993b0bd9eb57.png)

**Comment by Elijahrane** [comment]
is there any reason not to just load the profile for the selected character? that's what I ended up doing

**Comment by deltanedas** [comment]
I assume that would erase any changes made by e.g. using rename trick on a player but it's much better than having no name at all

**Comment by Slava0135** [comment]
![image](https://user-images.githubusercontent.com/40753025/214632469-6cf17d5f-8a60-432b-9d0e-5dd86d66d06f.png)
it crashes the server when i kill an infected person

**Comment by EmoGarbage404** [comment]
> ![image](https://user-images.githubusercontent.com/40753025/214632469-6cf17d5f-8a60-432b-9d0e-5dd86d66d06f.png)
> it crashes the server when i kill an infected person

What is the species of this person that you just killed?

**Comment by Slava0135** [comment]
![image](https://user-images.githubusercontent.com/40753025/214632469-6cf17d5f-8a60-432b-9d0e-5dd86d66d06f.png)
it crashes the server when i kill an infected person

> > ![image](https://user-images.githubusercontent.com/40753025/214632469-6cf17d5f-8a60-432b-9d0e-5dd86d66d06f.png)
> > it crashes the server when i kill an infected person
> 
> What is the species of this person that you just killed?

tried to do with slime and a lizard i guess (first centcom is always lizard)

**Comment by ElectroJr** [comment]
The exception should be fixed by #13721, which will probably also fix the issue with the name not getting set properly.
