### ISSUE TITLE
Server Memory Leak

### ISSUE THREAD

**Issue by clusterfack** [space-wizards/space-station-14#137]
This leak seems to occur particularly after a client disconnects from the server. About halfway through this profile the client disconnected after which memory usage rose continually:
![](https://images-ext-1.discordapp.net/eyJ1cmwiOiJodHRwOi8vcHV1LnNoL3ZLMWJlLzhhOGEzNjgwMDgucG5nIn0.78jZ5h9I1tYg3y31p72KciG7pMI)

After using break all, comparison memory snapshots of before the client disconnected and at the end of profiling were taken. Below is the diff of the two memory snapshots:
![](https://images-ext-1.discordapp.net/eyJ1cmwiOiJodHRwOi8vcHV1LnNoL3ZLMUY3LzZkZDIyYTljNjAucG5nIn0.emkWAFfCc4k4TmrdzbA74SkBgMA)

As you can see in the snapshot the leak is caused by the continuous creation of new objects, in particular EntityState (along the variables it holds) which is presumably some information which is meant to be sent to the client to update the client with the server information.

This is the only known memory leak I know of in the code right now.

**Comment by CrAzYPiLoT-SS13** [comment]
I can imagine this happens because the server currently has no way of knowing when the client disconnected in an irregular way (and apparently, in this case, clicking the x in the corner is an irregularity) so the server just keeps sending EntityState objects to the client which cannot accept them and it somehow creates this leak. TL;DR fix client notifying server on crash or exit by X and not the in-game option.

**Comment by PJB3005** [comment]
@CrAzYPiLoT-SS13 that's not how netcode works at all. At all.

Sure the clients not being disconnected makes the leak worse but it'd probably happen regardless.

**Comment by psykzz** [comment]
Did a PR to disconnect the client when leaving.
Does still have a memory impact, which isn't cleaned up.

#157 is the PR.

Can you profile it again once that fix is in? @clusterfack

**Comment by clusterfack** [comment]
Of course

**Comment by Acruid** [comment]
I don't see a memory leak anymore, something in the last 2 months seems to have fixed it. Should this be closed?

**Comment by Silvertorch5** [comment]
@Acruid Please test some more to see if you can recreate it. if you are not able to recreate i will go ahead and close this

**Comment by clusterfack** [comment]
This was fixed by some PR

**Comment by PJB3005** [comment]
Still a problem.
