### ISSUE TITLE
Connecting sprites (walls etc) are completely gunked when placed in an ongoing round

### ISSUE THREAD

**Issue by ProfanedBane** [space-wizards/space-station-14#1373]
[https://cdn.discordapp.com/attachments/310555209753690112/731524036546396200/unknown.png](https://cdn.discordapp.com/attachments/310555209753690112/731524036546396200/unknown.png)

**Comment by MemeProof** [comment]
Seems this might have been fixed. Added in walls and everything connected properly.
![image](https://user-images.githubusercontent.com/43192081/88309481-5938fd80-ccdc-11ea-9ad8-eacc584b5a70.png)

**Comment by ike709** [comment]
Seemed to work fine for me too.

**Comment by ShadowCommander** [comment]
It looks like you may have accidentally pressed middle click which rotates the entity. Just middle click 3 more times and it'll probably be fixed.

**Comment by SweptWasTaken** [comment]
Should have been closed a while back??
