### ISSUE TITLE
all dead mobs turn sideways, even if the sprite shouldn't

### ISSUE THREAD

**Issue by EmoGarbage404** [space-wizards/space-station-14#13743]
## Description

![image](https://user-images.githubusercontent.com/98561806/214999511-ff25efcd-808d-4b65-9f7c-0deb0c5ba084.png)
this needs to be a datafield so that it can be enabled/disabled when needed

**Comment by metalgearsloth** [comment]
This still needs fixing as alive mobs are still rotated and moving around.

**Comment by metalgearsloth** [comment]
Also separately is that someone needs to audit all mobs for dead / crit states.

**Comment by themias** [comment]
Might even be easier to just remove RotationVisuals from non-humanoid mobs unless the buckling rotation is that desired.
