### ISSUE TITLE
You can block an airlock from closing by standing next to it

### ISSUE THREAD

**Issue by AJCM-git** [space-wizards/space-station-14#1376]
The bounding boxes collides with each other from way too far 
![image](https://user-images.githubusercontent.com/60196617/87227847-76301100-c36b-11ea-8b58-da5316dcc53a.png)
![image](https://user-images.githubusercontent.com/60196617/87227853-7c25f200-c36b-11ea-8b14-47f45612e7ac.png)

**Comment by ShadowCommander** [comment]
This isn't really a bug and in my view it's expected behavior. There's not really a way to fix this without breaking one thing or another.

Just think of it as an automatic airlock where it has a small sensor range.
