### ISSUE TITLE
the condiment station glows

### ISSUE THREAD

**Issue by EmoGarbage404** [space-wizards/space-station-14#13773]
## Description

![image](https://user-images.githubusercontent.com/98561806/215291035-4d8741a6-fb12-4c95-990e-b22009c9ecdb.png)

it probably shouldn't

**Comment by Emisse** [comment]
what did he mean by this

**Comment by EmoGarbage404** [comment]
IT'S GLOWING. IT'S LIT UP. IT'S EMISSIVE AND BRIGHTER THAN MY FUTURE

**Comment by ChilbroBaggins** [comment]
That's because it was initially setup to be a powered machine with buttons you push and a packet comes out. But you all wanted squeeze bottles n shit. So now it's lit up to draw attention to itself because it is lonely.
