### ISSUE TITLE
encryption keys "persist" - have access to medical + engineering with just an engineering key

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#13783]
## Description
can still hear channels that use encryption keys which were previously inserted

**Reproduction**
1. spawn as passenger
2. get medical headset from vendor
3. put its key into passenger headset
4. get engineering headset from vendor
5. put its key into passenger headset
6. still able to hear med radio? sending does not work however, had to use intercom for screenshot

**Screenshots**
![12:50:01](https://user-images.githubusercontent.com/39013340/215327375-c9c08f0b-5f1c-4c9f-8c5f-74c85999947b.png)

**Comment by deltanedas** [comment]
![12:49:56](https://user-images.githubusercontent.com/39013340/215327383-ed623f26-e181-4104-92ac-fa165fdc9e74.png)

**Comment by AlexMorgan3817** [comment]
WTF

**Comment by AlexMorgan3817** [comment]
Wait, did you removed medical before inserting engineering?

**Comment by AlexMorgan3817** [comment]
![image](https://user-images.githubusercontent.com/46600554/215331501-a8ce6bb2-128c-4441-a739-ef6723c5b399.png)
Can't reproduce

**Comment by AlexMorgan3817** [comment]
> Wait, did you removed medical before inserting engineering?

Because you can put med and engineering together

**Comment by AlexMorgan3817** [comment]
![image](https://user-images.githubusercontent.com/46600554/215334350-9f9de009-73f5-4bff-9aad-d6e7e32bf080.png)
Reproduced... shit
