### ISSUE TITLE
can scream and possibly toggle internals while sleeping

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#13800]
## Description
screaming (action and emoting) and toggling internals (probably) work while asleep

**Reproduction**
1. go sleep
2. hit 2

**Screenshots**
self explanatory

**Additional context**
possibly related to #13207 and #10761

**Comment by Vaaankas** [comment]
Still an issue

**Comment by K-Dynamic** [comment]
> No longer an issue? I can't repro

I recall being able to scream and emote while nocturined like two months back

**Comment by 0x6273** [comment]
> I recall being able to scream and emote while nocturined like two months back

Seems like emoting with `@` or `/me` is still possible. Only actions have been fixed.
