### ISSUE TITLE
Cell rechargers can't be pulled

### ISSUE THREAD

**Issue by Scribbles0** [space-wizards/space-station-14#13853]
## Description

Tried to pull a cell recharger one round. Stayed in place even though it was unanchored.

**Reproduction**

1. Unanchor cell recharger.
2. Try to pull it.

**Comment by deltanedas** [comment]
happens for weapon chargers too, but only if they are mapped and not spawned in

**Comment by deltanedas** [comment]
![sus](https://user-images.githubusercontent.com/39013340/216266696-271933c1-cf91-4996-bc76-89f5162899a6.png)

what's extremely cursed is that (map spawned) wall chargers can be unanchored :skull:

**Comment by UbaserB** [comment]
This was fixed somewhere along the line.

**Comment by deltanedas** [comment]
ya
