### ISSUE TITLE
cannot pet dehydrated fish

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#13870]
## Description
in /tg/ petting fish then hydrating makes him like you

**Reproduction**
1. hold fish
2. press z
3. nothing

**Additional context**
https://tgstation13.org/wiki/Syndicate_Items#Dehydrated_Space_Carp

**Comment by potato1234x** [comment]
needs to have voice activated attack follow and come commands too so you can stash them behind shutters and unleash them on unsuspecting tiders

**Comment by deltanedas** [comment]
fishops, just have water foam grenade and a signaller
alternatively do just that with voice grenade for it
