### ISSUE TITLE
Lockers can spawn phantom items and lose collisions

### ISSUE THREAD

**Issue by ProfanedBane** [space-wizards/space-station-14#1391]
It appears the oxygen locker in the default maps spawns a phantom oxygen mask, and has no collisions.
Attempting to interact with the mask will generate exceptions.
I've not had a chance to replicate this with other lockers.

https://pastebin.com/b8cverPB

https://cdn.discordapp.com/attachments/310555209753690112/732336106565271552/2020-07-13_21-40-43.mp4

**Comment by ShadowCommander** [comment]
This can potentially be another map loading problem. There have been problems in the past with the map having components from an old prototype saved.

**Comment by SweptWasTaken** [comment]
This has been fixed for a while now.
