### ISSUE TITLE
wirecutters instantly destroy reinforced walls

### ISSUE THREAD

**Issue by Emisse** [space-wizards/space-station-14#13919]
use wirecutter on wall
wall gone

**Comment by Scribbles0** [comment]
this needs Bug Of The Year 2023 Candidate

**Comment by Emisse** [comment]
![image](https://user-images.githubusercontent.com/99158783/216586671-e14ba13f-3f1f-4314-b0e8-a2afb31cd747.png)
urgent

**Comment by Scribbles0** [comment]
something broke in #13876 
whenever i try to decon an rwall i get an error or something
tested rwall decon in #13874 and it still worked

**Comment by Emisse** [comment]
how tf

**Comment by EmoGarbage404** [comment]
> something broke in #13876 (i'm sure of it)
> whenever i try to decon an rwall i get an error or something
> tested rwall decon in #13874 and it still worked

If #13876, a 2 line change to research code, broke construction: hang my body in a public forum for the plebians to admonish.

**Comment by Scribbles0** [comment]
wait
if i use gh pr checkout #, does it go to that pr + whatever master had, or only THAT pr's changes?

**Comment by metalgearsloth** [comment]
it goes to master as at that pr.

Use git bisect.

**Comment by Scribbles0** [comment]
okay i also got an error trying to decon a rwall in #13879 
i have no fucking clue what's going on or what i'm doing

**Comment by metalgearsloth** [comment]
Please provide logs in future
