### ISSUE TITLE
IDs can't be used inhand to open appropriate doors

### ISSUE THREAD

**Issue by Alekshhh** [space-wizards/space-station-14#13928]
## Description
It is not possible to open doors using an ID in your hand if said ID has access to the door. Throwing it works, from what I heard. You have to wear it in your own ID slot to open the appropriate door

**Reproduction**
Get ID, use ID on door inhand, cry

**Comment by crazybrain23** [comment]
I recall using Agent ID cards to inhand to open doors. Does this only affect normal ID cards? Also an ID card in a PDA works to open doors too.

**Comment by Alekshhh** [comment]
I tested it recently, and none of the ID cards open doors by clicking with them inhand. Tested it on syndicate ID, agent, and regular

**Comment by Alekshhh** [comment]
seems like they need a special C# thing to allow them to also be used in-hand instead of "bump" (being thrown at a door or bumped into while in the ID slot)

**Comment by deltanedas** [comment]
pressing e works (it uses hands for access) but clicking does not

**Comment by lzk228** [comment]
fixed, if i understand that issue correctly
