### ISSUE TITLE
taking keys out of headset in a container does not update its ui

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#13926]
## Description
screwdriving a headset in a container doesn't update its ui

**Reproduction**
1. put headset in bag
2. screwdrive it
3. no key.... right?
4. put screwdriver in bag, updating the ui
5. appears!

**Screenshots**
eeeeeeee

**Comment by QuietlyWhisper** [comment]
This might be old and fixed already but it applies to labeling things in your bag too

**Comment by deltanedas** [comment]
also happens when screwing your own headset... makes it "disappear"

putting key in "ear"
![16:44:40](https://user-images.githubusercontent.com/39013340/216779254-8e9e0672-c9f0-4edf-8b4e-7b523b0a6d79.png)

but its actually a headset!
![16:44:44](https://user-images.githubusercontent.com/39013340/216779251-2725e1ff-be0d-42e4-9dc4-f27623940c89.png)

**Comment by IProduceWidgets** [comment]
Seems fixed?

**Comment by lzk228** [comment]
yeah, fixed

https://github.com/space-wizards/space-station-14/assets/124214523/e787faf0-aab8-485c-ac61-242ad3afa16b
