### ISSUE TITLE
Diagonal shuttle walls don't block vision

### ISSUE THREAD

**Issue by ChilbroBaggins** [space-wizards/space-station-14#13947]
After this PR [#13259](https://github.com/space-wizards/space-station-14/pull/13259) Diagonal walls are see-through like windows. 
![Screenshot 2023-02-04 094605](https://user-images.githubusercontent.com/107660393/216851316-0e80b9b6-2602-47a5-9e82-e7412f4c9d9f.jpg)

**Comment by metalgearsloth** [comment]
Made a better engine issue https://github.com/space-wizards/RobustToolbox/issues/3753
