### ISSUE TITLE
Gunifying pneumatic cannon made it the best gun in the game

### ISSUE THREAD

**Issue by asperger-sind** [space-wizards/space-station-14#13986]
## Description

The videos explains it better than words can
**Reproduction**

1. Pneumatic Cannon
2. Put in anything a normal gun would fire (rockets, grenades, bullets, etc)
3. Discover the god-gun
**Screenshots**

https://user-images.githubusercontent.com/38016303/217349914-8146c6c1-ba5a-45ca-87f2-bede9c2ffc01.mp4

https://user-images.githubusercontent.com/38016303/217349928-4b4def62-d38a-4572-8d78-38fcbd3bd59d.mp4

https://user-images.githubusercontent.com/38016303/217349983-2fb2a1ad-0082-41d2-89fc-2fbca9893d02.mp4

https://user-images.githubusercontent.com/38016303/217350009-f4c55ba0-5544-42b3-aad9-6d74a451507e.mp4

**Additional context**

Originally discovered by Ilya246#9193 on Discord

**Comment by moonheart08** [comment]
Whoever fixes this needs to make this an admin item in return for fixing it.

**Comment by mirrorcult** [comment]
whoops

**Comment by Naive817** [comment]
Does being fired from a pneumatic cannon change the projectiles' damage, or it's just a firing speed/accuracy issue?

**Comment by mirrorcult** [comment]
pneumatic cannon should not be firing actual ammo/cartridges, it should be throwing everything. but gun code rn will default to firing it as actual ammo

**Comment by CaptainSqrBeard** [comment]
please fix

**Comment by deltanedas** [comment]
maaayyybeeeeee...

**Comment by deltanedas** [comment]
my idea is 2 admeme items 1 is gun as it is right now other is admeme with 1000 storage and hopefully no gas requirement
