### ISSUE TITLE
Syndicate hardsuit is not balanced for regular rounds

### ISSUE THREAD

**Issue by AJimmyU** [space-wizards/space-station-14#14006]
## Description

Syndicate hardsuit offers best-in-slot protection and mobility, compared to any equipment on station. Any syndicate agent can just buy it and become near unstoppable, while having spare TC to spend on weapons.

Syndicate hardsuit should be limited to nuclear operative gamemode, where murderboning everyone alive is the end objective.

**Reproduction**

1. Buy Syndicate hardsuit as regular syndicate agent
2. Murderbone with hands behind your back

**Screenshots**

**Additional context**

**Comment by GoodWheatley** [comment]
Just use a stun baton on them it’s not rocket science

**Comment by Gerkada** [comment]
> For comparison, security hardsuit has a 60% slowdown. Syndicate hardsuit has 0%. You cannot stunbaton someone when you can't catch them. "Just stun it" is not an argument.

You can use rubber bullets, bro, its that simple

**Comment by GoodWheatley** [comment]
> For comparison, security hardsuit has a 60% slowdown. Syndicate hardsuit has 0%. You cannot stunbaton someone when you can't catch them. "Just stun it" is not an argument.

Have you heard of disablers

**Comment by asperger-sind** [comment]
> For comparison, security hardsuit has a 60% slowdown. Syndicate hardsuit has 0%. You cannot stunbaton someone when you can't catch them. "Just stun it" is not an argument.

"Just stun it" IS an argument. It has been done before, I did it before, and said 2 parties will continue doing it in the future due to it being proven viable; baiting someone into engaging you instead of you engaging them, ambushing them, or just play outmaneuvering are a couple of valid ways to stunbaton someone even if they can outrun you.

Wearing hardsuits at all times is suboptimal for several reasons, the bloodred being one of the few exceptions, and it is required there as it would be quite frankly garbage if it slowed you down.

Besides, we've several other methods of stunning people away from you featuring but not limited to:
Disablers
Rubber bullets
Tranq darts
Slippery objects/liquids (the latter can be dispensed mid-interaction via a mop)

As a note, security hardsuits slow you down by 40% whilst running, not 60%.

**Comment by asperger-sind** [comment]
As someone who's played for quite a while and has proven to be proficient in all sorts of combat scenarios and digging github for stats I disagree with your take for several reasons.

tl;dr:
stuns are viable, you're valid(hunted) to(by) the whole station, there is good competition, you may or may not be biased and lack a full perspective on the subject, you still die fast af lol

- A bloodred hardsuit instantly makes you valid to the whole station, leaving you open to having a grand totale of 0 allies and/or causing confusion onto the mass of crewmembers as you're a big red target; this also leaves you extraordinarily vulnerable to all sorts of stuns as they are THE tool to be used against you if you do not have allies of sorts to get you out of the stun + cuff combo.

- Economically you won't be doing much either, whilst you can go for a fire axe or an e-sword as a reliable weapon off the uplink you're even MORE vulnerable to stuns, and the best you can buy with your spare 12 TC is a shitty pistol and some mags.

- Whilst the bloodred is a good option armor-wise, it's not really the best as you can achieve the same result or better by buying a web vest (4 TC and you get 10 storage units whilst not making you instantly validhunted) and putting on some decent helmet (fire helmet/bombsuit helmet/security helmet/atmos fire helmet for example)
(this point is just "it's good yea but it has good competition as well")
- Getting a bloodred does't just allow you to murderbone 1v74 with your hands tied behind your back, nor is it required to do so and that statement alone makes me question the validity of this issue at all regarding negativity bias and whether or not 
you're keeping track of all viable methods of combatting what you deem overpowered.

- Most weapons in the game currently deal A LOT of damage, leaving you limping and set for the grave within seconds if someone lands a few shots/hits on you, the only viable healing is medicine which you may not have, and wounds (when that gets merged) won't make the situation brighter either.
(basically: you still die real fast even with your fancy schmancy armor if you're up against someone competent enough to land hits/shots on you)

As a sidenote, no, nukies on the nukie side isn't a murderboning simulator, your objective is the nuke, not the crew dead.
~~to be fair most people do play it like a murderboning sim and i cant blame them really~~

**Comment by Cheackraze** [comment]
Shotgun bean bag shells stun in 2 hits, and every map comes with them, I don't think there's a reason to nerf.  The only real viable strategy a syndie has with a blood red is to raid the armory to take guns

**Comment by asperger-sind** [comment]
> Shotgun bean bag shells stun in 2 hits, and every map comes with them, I don't think there's a reason to nerf. The only real viable strategy a syndie has with a blood red is to raid the armory to take guns

I disagree really, there are a plethora of viable strategies and just bruteforcing people with pure combat skill and tenacity is still an option; but if we're talking strategies by far the best is just going into space with any jetpack.

**Comment by Cheackraze** [comment]
> > Shotgun bean bag shells stun in 2 hits, and every map comes with them, I don't think there's a reason to nerf. The only real viable strategy a syndie has with a blood red is to raid the armory to take guns
> 
> I disagree really, there are a plethora of viable strategies and just bruteforcing people with pure combat skill and tenacity is still an option; but if we're talking strategies by far the best is just going into space with any jetpack.

Any other strategy involves not using guns, putting you in melee range

**Comment by asperger-sind** [comment]
> Any other strategy involves not using guns, putting you in melee range

You can use this to your advantage by playing defensively and using slippery objects whilst they're running into you, instantly winning the fight if you have cuffs or can deal enough damage. (this is implying you're fighting someone with a stunstick)

This point is *somewhat* applicable to the whole melee range and stuns point in general, but it varies on what you're trying to achieve in a fight; to kill someone or to not get killed, I'm assuming you're addressing the latter so I'm stating this soapy argument.

**Comment by Elijahrane** [comment]
the downside for traitors is how extremely conspicuous it is, which is something that matters a lot more for them than nukies
