### ISSUE TITLE
Flesh monsters slip on and take damage from sharp objects

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#14010]
## Description
Flesh monsters from the flesh anomaly slip on glass shards and other sharp objects and take damage. This makes it very easy, and cheap, for the crew to effectually neutralize the threat of the anomaly. Simply line up and stack a few shards in a pile and the AI will insta die when crossing.

**Additional context**
While it might be an effective counter to the flesh anomaly I think it is too easy of a solution for what should be a very dangerous threat to the station.

**Comment by mirrorcult** [comment]
the issue isn't really that they take damage but that the AI doesnt pathfind around them

**Comment by deltanedas** [comment]
ignoring pathfinding, you can still cheese flesh monsters by placing glass under there feet, leaving no time for pathfinding to avoid it

**Comment by metalgearsloth** [comment]
Do shards not break after being stepped on?

**Comment by Emisse** [comment]
no

**Comment by deltanedas** [comment]
for that reason theyre also very useful for trolling rats and mice, renewable mouse trap

**Comment by Kayek14** [comment]
This issue seems to be resolved. Flesh monsters dont interact with glass shards on the floor.
