### ISSUE TITLE
origin disposals setup is horrible

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#14017]
## Description
disposals on origin is very sus in general but having a bunch of untagged routers is just why

**Screenshots**
one of them above grav
![10_110311](https://user-images.githubusercontent.com/39013340/218076751-1ec9927e-bf89-4799-b344-90876275afd4.png)

**Comment by deltanedas** [comment]
ok update there are at least 2 instances of junctions that dont do anything

in this image the router is originally a junction i changed it ingame
![23:58:15](https://user-images.githubusercontent.com/39013340/219818725-36c92f59-84a6-4f10-84ba-91fe61b7df0f.png)

stuff is somehow meant to come out of it???
![23:58:24](https://user-images.githubusercontent.com/39013340/219818711-7fca2079-9cf0-4150-bd30-338d296c6c91.png)

**Comment by lzk228** [comment]
@brainfood1183

**Comment by PJB3005** [comment]
Fixed by #26055
