### ISSUE TITLE
Gravity anomaly pulse can launch ghosts

### ISSUE THREAD

**Issue by TemporalOroboros** [space-wizards/space-station-14#14028]
## Description

I became a ghost and went to observe an anomaly in permabrig. It appeared to be a grav anomaly and pulsed. I lost control of my ghost and was flung the length of the security department before I regained control.

**Reproduction**

1. Become a ghost.
2. Loiter near a gravity anomaly.

**Screenshots**

**Additional context**

**Comment by lzk228** [comment]
fixed
