### ISSUE TITLE
Removing a blindfold allows you to see with the blind trait

### ISSUE THREAD

**Issue by MrBirdmann** [space-wizards/space-station-14#14020]
Putting on and removing a blindfold while having the blind trait allows you to see normally, tho you still can't examine items outside of regular blindness range.

![bug](https://user-images.githubusercontent.com/64282140/218125079-8f496524-1d04-4be8-b527-db415bc41e5c.PNG)

**Comment by Elijahrane** [comment]
Related:
https://github.com/space-wizards/space-station-14/pull/13720
https://github.com/space-wizards/RobustToolbox/issues/3732
