### ISSUE TITLE
Reloading GameRulePrototype makes running events never end 

### ISSUE THREAD

**Issue by AJCM-git** [space-wizards/space-station-14#14024]
## Description
What says on the title

**Reproduction**
1. Input the `addgamerule PowerGridCheck` command
2. While the event runs reload a GameRulePrototype
3. The event never ends even by trying to force it by inputting `endgamerule PowerGridCheck`

**Comment by EmoGarbage404** [comment]
this almost definitely got resolved in the gamerule refactor
