### ISSUE TITLE
Bolas don’t do stamina damage on hit

### ISSUE THREAD

**Issue by GoodWheatley** [space-wizards/space-station-14#14068]
## Description
What it says on the tin. A bola hitting someone doesn’t actually decrease their stamina, despite the code saying it should deal 80 stamina damage.

**Reproduction**
1.  Throw bola at someone
2. They don’t take any stamina damage

**Comment by QuietlyWhisper** [comment]
IIRC thrown items don't do damage at all currently, though they should

**Comment by metalgearsloth** [comment]
> IIRC thrown items don't do damage at all currently, though they should

Throwing needs a cooldown before that should happen because it's spammable.
