### ISSUE TITLE
You can resist nuke explosion with garbage

### ISSUE THREAD

**Issue by DocNITE** [space-wizards/space-station-14#14070]
## Description
So... If you hide in the trash, the explosion will not cause damage to the character. You can see more about this in the video.
Can you resist explosion with crate or something container - I don't know.

**Reproduction**
1. Disconnect some LV, HV and pipes (or just remove energy (it needs for remove auto-washing)
2. Jump in garbage before explosion. 
3. Wait until station has been destroyed.
4. Tadam. Now you alive! (if you equiped cosmo suit and oxygen before :D )

**Screenshots**

Video on youtube:
[https://youtu.be/31nS4DV36Rk](url)

**Comment by deltanedas** [comment]
clearly indiana jones reference, not a bug

**Comment by potato1234x** [comment]
this should unironically not be removed

**Comment by deltanedas** [comment]
![22:32:30](https://user-images.githubusercontent.com/39013340/233807540-5947f22a-1382-43e9-9465-9b719b67f30d.png)

slime in ripley, urist in bin, urist in locked freezer

urist in bin win every time
