### ISSUE TITLE
Crew manifest should be a program, not a pda setting

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#14076]
## Description

**Reproduction**

**Screenshots**

![image](https://user-images.githubusercontent.com/43253663/218343591-667d0b44-953b-4fc7-ad59-9c4e70ec7fc0.png)

**Additional context**

**Comment by juliangiebel** [comment]
That's a wyci moment

**Comment by ficcialfaint** [comment]
see #18420
