### ISSUE TITLE
escape objective doesn't trigger on cargo shuttle

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#14091]
## Description
if you are a traitor with escape objective, cargo shuttle in FTL doesn't count as a shuttle
neither do shittles

**Reproduction**
1. roll the objective
2. call shuttle
3. get on cargo shuttle and ftl
4. redtext

**Additional context**
been a while since i reproduced it, possibly fixed as per `Any emergency shuttle counts for this objective.` comment, not sure though

**Comment by metalgearsloth** [comment]
Only the emergency shuttle counts as an emergency shuttle.

**Comment by deltanedas** [comment]
what does the comment mean then? different shuttle designs?

**Comment by moonheart08** [comment]
Escape pods (when they're coded)

**Comment by deltanedas** [comment]
ah yeah forgot they were meant for more than just free shittle parts
