### ISSUE TITLE
/say and /me stopped existing

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#14095]
## Description
literally 1984, couldnt speak emote looc anything
just pointing screaming and in-world stuff

**Reproduction**
i dunno i was dragging an rtg when maybe relogged and could no longer speak

**Screenshots**
![18:06:20](https://user-images.githubusercontent.com/39013340/218537813-4b1733af-2650-4d62-959f-ce53c0492116.png)

**Additional context**
fixed by game restart

**Comment by Ilya246** [comment]
had same happen, fixed after restart

**Comment by deltanedas** [comment]
killer

**Comment by metalgearsloth** [comment]
> this actually applies to ALL commands that the client didnt have (server didn't register them?)

Are you on master, this should be fixed.

**Comment by deltanedas** [comment]
i havent seen this happen recently, pretty sure above is correct
