### ISSUE TITLE
Disconnecting stops your movement even in space

### ISSUE THREAD

**Issue by DrSmugleaf** [space-wizards/space-station-14#1412]
Related to #1208 and #1265

**Comment by PJB3005** [comment]
Is this really a bug? What happens to the client on disconnect should probably not be a big deal.

**Comment by DrSmugleaf** [comment]
> Is this really a bug? What happens to the client on disconnect should probably not be a big deal.

If you care about a client being able to stop their controlled entity from drifting away into space by disconnecting yes, otherwise no.

**Comment by PJB3005** [comment]
Oh wait, I thought this was about client side. Durr.. Yeah that should be fixed.
