### ISSUE TITLE
Dragon now deletes people that got eaten

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#14141]
## Description

People don't get dropped when the dragon dies
**Reproduction**

**Screenshots**

**Additional context**

**Comment by deltanedas** [comment]
if they are still intact, what is being digested? space magic?

**Comment by keronshb** [comment]
Vore destroyed, fixed by one of these:
https://github.com/space-wizards/RobustToolbox/pull/3901
https://github.com/space-wizards/RobustToolbox/pull/3902
