### ISSUE TITLE
opposite no damage text visibility

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#14150]
## Description
no damage text only shows when there is damage to be seen

**Reproduction**
1. spawn
2. look at yourself, no text

**Screenshots**
![114606](https://user-images.githubusercontent.com/39013340/219645932-73a573c3-317b-4c2b-bb55-9e29123b08c4.png)
![114556](https://user-images.githubusercontent.com/39013340/219645964-10023fa8-ed30-466c-9a92-bec24f086179.png)

**Comment by 0x6273** [comment]
Likely the same cause as #14151 since HealthExaminableSystem uses IsEmpty
