### ISSUE TITLE
no longer able to see upgrade stats on machines

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#14151]
## Description
yes

**Reproduction**
examine machine > no upgrade button

**Comment by 0x6273** [comment]
I think I found the cause. FormattedMessage was changed in an engine update, and it broke the `IsEmpty` method, so now my code thinks there are no upgrades and hides the button.

This looks sus: https://github.com/space-wizards/RobustToolbox/blob/f29f57aa7c24e2d08f09c33fd7a797639bb4026f/Robust.Shared/Utility/FormattedMessage.cs#L24-L27

**Comment by deltanedas** [comment]
yeah that should probably be ==...

**Comment by deltanedas** [comment]
fixed in engine
