### ISSUE TITLE
none of the planet floor tiles have names

### ISSUE THREAD

**Issue by EmoGarbage404** [space-wizards/space-station-14#14165]
## Description

![image](https://user-images.githubusercontent.com/98561806/219884609-708c7bb0-ed83-4b80-ab18-71a851a970d3.png)
![image](https://user-images.githubusercontent.com/98561806/219884619-88afa842-ddce-4236-8644-d03b1f4fbb8d.png)

**Comment by UbaserB** [comment]
they have names now
