### ISSUE TITLE
Banana isn't used up after making banana bread

### ISSUE THREAD

**Issue by Kerbiat** [space-wizards/space-station-14#14184]
## Description
On Wizard Den Lizard server each time i made banana bread in microwave using dough and one banana i had banana bread itself and one banana back. I made 6 banana breads with single banana, it never got used up. I'm not sure if it's intended so i guessed it was a bug.

**Reproduction**
Place dough and one banana into a microwave for (if i remember correclty) 15 seconds. I can't think of any additional condition to replicate it.

**Comment by Partmedia** [comment]
Are you sure that is producing banana-nut bread? If you microwave a banana and dough for 15 seconds, you will produce 1 *regular* bread, and the microwave will reject the banana.

**Comment by Kerbiat** [comment]
Sorry for wasting your time.
