### ISSUE TITLE
cryo's broke

### ISSUE THREAD

**Issue by Scribbles0** [space-wizards/space-station-14#14186]
## Description

can't get in the pod (+ you can't unanchor it and move it but that might be intentional)

**Reproduction**

1. try to place yourself or someone else into the pod

**Comment by Scribbles0** [comment]
this might be just me being delusional hold on

**Comment by Scribbles0** [comment]
no i was correct it doesn't work

**Comment by MilenVolf** [comment]
It can be temporary fixed by adding Climbable component to the Cryopod entity. It makes Cryopods usebale again and they work pretty fine, but it does not fix the problem in it's code part. So fixes must be done.
