### ISSUE TITLE
draw hit arcs when hitting with melee weapons with showbb

### ISSUE THREAD

**Issue by Injazz** [space-wizards/space-station-14#142]
so you can see the boundaries of melee hit

**Comment by clusterfack** [comment]
Yeah I wanted to do this, but couldn't figure out a good way to do it with a simple method

**Comment by PJB3005** [comment]
We kind of have melee weapon animations now, so this is less important.

**Comment by Acruid** [comment]
Blocked by https://github.com/space-wizards/RobustToolbox/issues/887

**Comment by PJB3005** [comment]
Well technically this is done now, because weapon arcs are tested using raycasts now, and there is a debug command for showing raycasts.
