### ISSUE TITLE
evac shuttle brokey wont show up

### ISSUE THREAD

**Issue by Emisse** [space-wizards/space-station-14#14207]
dont show up
i probably broke it but im not sure how considering i didnt even touch 1 of the shuttles in any capacity and it also doesnt show up
help

**Comment by Emisse** [comment]
also it worked when i tested the new shuttle pr for context

**Comment by deltanedas** [comment]
sloth fixed this in #14214

**Comment by QuietlyWhisper** [comment]
probably can be closed
