### ISSUE TITLE
Clean up saltern.yml

### ISSUE THREAD

**Issue by ShadowCommander** [space-wizards/space-station-14#1422]
Commit 23cc6b1d4ef82141d308f0dc5fee6ee922e913af seems to have added container contents to the map when it shouldn't have. Lockers and toolboxes shouldn't contain the items that ToolLockerFillComponent and ToolboxFillComponent fill them with. Removing them might fix some crashes when opening lockers and also some of the weird things like some toolboxes having duplicate items.

**Comment by DrSmugleaf** [comment]
Related to #1418

**Comment by Visne** [comment]
I'll work on this
