### ISSUE TITLE
Moving the station causes all players inside it to gain noclip

### ISSUE THREAD

**Issue by DrSmugleaf** [space-wizards/space-station-14#1423]
It also seems to not consider where the station has moved to, as you have control over your movement for longer than expected when moving out onto space.

**Comment by metalgearsloth** [comment]
I'm working on this by rewriting the entity + physics trees.

Problem is the WorldAABB for entities isn't updated when the station moves despite fps dropping to 0.1 to update the station's children.

**Comment by SweptWasTaken** [comment]
Isn't/Won't be a problem.
