### ISSUE TITLE
Freezers/heater sprites shouldn't be NoRot

### ISSUE THREAD

**Issue by ElectroJr** [space-wizards/space-station-14#14253]
See the last comment in #14225.

![Content Client_0GVeaRDDtN](https://user-images.githubusercontent.com/60421075/221070746-45ff4c23-3d3c-4843-92b1-a28fc8367f9f.png)

**Comment by Menshin** [comment]
Well, it happens :wink:

I'll implement your solution (please don't tell me i'll have to quadruple the many sprites of the animated working freezer ...) and reopen a PR to fix this situation.
