### ISSUE TITLE
The warden's job is not defined ingame anywhere.

### ISSUE THREAD

**Issue by Stealthbomber16** [space-wizards/space-station-14#14256]
New players are picking warden because it's just sec officer that gets to boss around sec officer, without actually sentencing or tracking a single prisoner. Warden's role on the station needs to be clearly defined ingame, either in the guidebook or somewhere else.

**Comment by QuietlyWhisper** [comment]
![image](https://user-images.githubusercontent.com/121047731/222160358-a3d04d7b-98f1-41a1-bfb6-4b151e59d570.png)
Is this not enough?

**Comment by lzk228** [comment]
fixed?
