### ISSUE TITLE
powercells use full state when first crafted even though they empty

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#14251]
## Description
title

**Reproduction**
1. research powercells
2. make one at lathe
3. see it has 0% charge but using full state

**Screenshots**
![21:19:11](https://user-images.githubusercontent.com/39013340/221032653-b1cd37bb-bed2-4f27-9257-9d15bc8c7401.png)

**Comment by h3half** [comment]
Looks like this is also a problem with other power cells:
![image](https://user-images.githubusercontent.com/1471542/221070971-4178f715-76cb-43df-8efb-e3c45da729fb.png)

And in the admin spawn panel as well:
![image](https://user-images.githubusercontent.com/1471542/221071046-2ef6d271-9354-458c-aab3-720144744dba.png)


I think I found why, and I'll make a PR for this in a few minutes
