### ISSUE TITLE
Doafters are currently broken.

### ISSUE THREAD

**Issue by QuietlyWhisper** [space-wizards/space-station-14#14273]
## Description

Doafters are currently broken now; not sure if this PR caused it. Linking a video for easier explanation.
Crowbaring an active fire airlock also does nothing now.

**Reproduction**

See video

**Screenshots**

https://user-images.githubusercontent.com/121047731/221356298-032ca3ea-ee38-4ffe-b243-c7e73c11dc11.mp4

**Additional context**

**Comment by deltanedas** [comment]
mopping also doesnt work and you can instantly drink drinks

**Comment by QuietlyWhisper** [comment]
Its worth noting this also allows mobs to eat infinite amounts of food at the same time; since doafters dont prevent others from being done

**Comment by QuietlyWhisper** [comment]
Another issue in medical; health analyzers can also be spammed
https://cdn.discordapp.com/attachments/1079013527513210934/1079013528477892658/Space_Station_14_2023-02-25_11-33-54.mp4

**Comment by QuietlyWhisper** [comment]
A user also reported screwdriver not functioning at the end of building machines.

**Comment by VasilisThePikachu** [comment]
Sterile swaps don't pick up the disease and stay sterile, making diagnosing and creating vaccines pretty much impossible

**Comment by keronshb** [comment]
Back into the mines I go...

**Comment by deltanedas** [comment]
> and medical supplies arent healing.
they are healing, so long as you dont spam all of them at once
you can use 9 bandages for instant heal but 10 will do nothing

**Comment by keronshb** [comment]
> mopping also doesnt work and you can instantly drink drinks

What's wrong with mopping? I'm not finding any issues.

**Comment by keronshb** [comment]
> A user also reported screwdriver not functioning at the end of building machines. May be unrelated, but worth writing down to be checked.

Was also not able to replicate this.

**Comment by deltanedas** [comment]
actually i think the reason meds dont work is ones from med vending machines do nothing

**Comment by deltanedas** [comment]
> > mopping also doesnt work and you can instantly drink drinks
> 
> What's wrong with mopping? I'm not finding any issues.

it simply puts nothing in the mop and, i believe, doesnt remove puddles

**Comment by keronshb** [comment]
> > > mopping also doesnt work and you can instantly drink drinks
> > 
> > 
> > What's wrong with mopping? I'm not finding any issues.
> 
> it simply puts nothing in the mop and, i believe, doesnt remove puddles

I need a video. I'm testing it and it's working as expected right now: Mop takes up puddle, can dump puddle into a bucket or if you don't it spills on the ground when you drop the mop.

**Comment by CartoonSC** [comment]
User are also reporting the following issues:
- Cryocapsule - placement inside a person is impossible. (Not sure what applies here).
- Recycling unit - it is impossible to empty the garbage from the garbage bag.

Regarding the use of a screwdriver. You need to interrupt the action before it ends.
The problem with the mop and bucket is also really there.

**Comment by Scribbles0** [comment]
>Cryocapsule - placement inside a person is impossible. (Not sure what applies here).
not a bug w/ doafters (see #14186, issue was opened before doafter refactor got merged)
