### ISSUE TITLE
You swallow the {$food}

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#14279]
## Description
it tastes bitter

**Reproduction**
1. make 25u derma pill "dermaline 25u"
2. eat
3. funny

**Screenshots**
lazy

**Additional context**
Loc.GetString probably missing `("food", uid)` or something

**Comment by h3half** [comment]
Couldn't reproduce

![image](https://user-images.githubusercontent.com/1471542/222057741-f2418761-9116-4c7b-8fd9-32a22f248b6b.png)

**Comment by Cheackraze** [comment]
i just had it happen on live as well but I couldn't reproduce it to get a screenshot. it happened with a pill though just like the original issue

**Comment by deltanedas** [comment]
yeah i dont know how to 100% guaranteed reproduce it, but it still happens regularly enough

**Comment by deltanedas** [comment]
ok from reading code the issue is it uses "foodComp" not "food"

**Comment by h3half** [comment]
A good reminder to sync your fork before looking into anything because my local copy still had `food` (it was changed to `foodComp` a week ago)

**Comment by deltanedas** [comment]
yeah ci wont warn you about those indirect conflicts
