### ISSUE TITLE
fast z spam can drink infinite drink

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#14290]
## Description
can of drink should have 6 sips, but you can spam fast and get 10-20 or if you use macro maybe hundreds
i think it even bypasses mouth limit of 50u somehow

**Reproduction**
1. get can from vendy
2. spam z fast as you can

**Comment by deltanedas** [comment]
most likely clientside since doing it with bicar didnt overdose

**Comment by CartoonSC** [comment]
Already exists. (see #14278)
