### ISSUE TITLE
Somehow managed to place walls using loadmapacts in a live sever

### ISSUE THREAD

**Issue by blueisdumb** [space-wizards/space-station-14#14324]
## Description
I was messing around with console and figured out you can loadmapacts in a live sever without admin. At first I tried to place walls and it wouldn't allow me and I continued trying to. It wouldn't let me place walls until at one random moment where I was spamming it and all of a sudden I played a ton of unanchored walls and grilles. After those few seconds I couldn't place walls again.

**Reproduction**
Not sure how I managed to do it but i'm assuming I did it during sever lag

**Screenshots**
![image_2023-02-28_195518288](https://user-images.githubusercontent.com/122710089/222017300-f8842ae2-c668-4452-920a-f11822e898b6.png)
![image](https://user-images.githubusercontent.com/122710089/222017407-27e6add7-71da-4da0-a2d5-1180a5665cc4.png)

**Additional context**
I was doing this during an admin spawning in something and after rejoining because my ghost strangely started teleporting and being flung everywhere

**Comment by Scribbles0** [comment]
this might've been the admin tbh

**Comment by Nairodian** [comment]
Alright, never mind, scrap this. Figured out the issue and has nothing to do with your actions, thank you for going through with it anyhow.
