### ISSUE TITLE
windows instantly get repaired

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#14347]
## Description

you can instantly repair windows without waiting for the doafter

**Reproduction steps**
1. almost break window with crowbar
2. use lit welder
3. repaired before doafter ends

**Additional context**
probably introduced by the doafter refactor

**Comment by QuietlyWhisper** [comment]
Can confirm, happened to me in game when repairing a cracked window via welder

**Comment by keronshb** [comment]
Please give repo steps.
