### ISSUE TITLE
Headset + screwdriver bug

### ISSUE THREAD

**Issue by QuietlyWhisper** [space-wizards/space-station-14#14346]
## Description

Using a screwdriver on a headset causes it to spam a handful of floating messages.

**Reproduction**
Any headset
Use screwdriver
Spam

**Comment by deltanedas** [comment]
i believe this was introduced by the doafter refactor

**Comment by keronshb** [comment]
Figured out the issue but it's the poor man's fix for now. #14352 looks at the broader issue
