### ISSUE TITLE
InteractUsingEvents gets spammed multiple times

### ISSUE THREAD

**Issue by keronshb** [space-wizards/space-station-14#14352]
## Description

In code, InteractUsingEvents gets sent multiple times on one click. Could be upward of 12 times.

**Reproduction**

Breakpoint InteractUsingEvent being raised in the SharedInteractionsSystem and you'll see what I mean. Line 772.
Alternatively, take the bools off of the headset encryption key system and you can see how it works in action.

**Screenshots**

**Additional context**

**Comment by metalgearsloth** [comment]
Is this on client?

**Comment by keronshb** [comment]
> Is this on client?

I think so. I previously did debugging on client + server, but when I debug+breakpoint server only and run client I get this many bars and I get 1 breakpoint hit

![image](https://user-images.githubusercontent.com/54602815/222623955-16b51f50-7185-4cef-863d-c65c9d7a6a1d.png)

If I run server and debug client, I get maybe 2-4 or more breakpoint hits but only bars showing for the amount of breakpoints.

**Comment by ElectroJr** [comment]
This just sounds like normal client side prediction. The client will re-run the same tick multiple times

**Comment by keronshb** [comment]
> This just sounds like normal client side prediction. The client will re-run the same tick multiple times

Is there anyway to prevent this or should I close the issue?

**Comment by ElectroJr** [comment]
Its intended behaviour, this is just how our client-side prediction works. Very roughly, for every server tick (e.g., tick 10), the client will apply a server state (10), run some number of ticks forward while replaying user inputs(11, 12, 13... ), then process a new tick with new inputs, and then reset back to the most recent server state. It then repeats, hopefully with a newly received server state for tick 11. The result is that any specific tick basically gets repeated a few times.
