### ISSUE TITLE
OOC messages aren't logged in the lobby

### ISSUE THREAD

**Issue by Chief-Engineer** [space-wizards/space-station-14#14366]
## Description

They're still sent to discord but ideally they'd be logged also. It probably makes the most sense for them to be in the next round's logs since there is always a next round, but there isn't really a previous round for the first round since server start.

**Comment by DrSmugleaf** [comment]
They should be getting added once the round starts.
![image](https://github.com/space-wizards/space-station-14/assets/10968691/6114ce97-34da-42e3-9119-1d59ee612b1b)
