### ISSUE TITLE
unable to move in no gravity due to low movement speed

### ISSUE THREAD

**Issue by DummeHytteOst** [space-wizards/space-station-14#14372]
A diona can't properly move in no gravity while thirsty, they sorta rubber band back and forward moving a tiny tiny bit

**Comment by Elijahrane** [comment]
Likely something to do slower movement speed? I got some reports for this on a species of mine that has a slower than default move speed too. And being thirsty makes you move slower.

**Comment by DummeHytteOst** [comment]
most likely, i sorta remeber this also happened while wearing the emergency suit, which slows you down a lot

**Comment by Elijahrane** [comment]
Yeah I can confirm that one, too

**Comment by DummeHytteOst** [comment]
throwing something stops the rubber banding, but it starts again when you slow down enough

**Comment by VasilisThePikachu** [comment]
I think this happens with lizards when very thirsty (and hungry?). A weird rubber band-like effect happens

**Comment by DummeHytteOst** [comment]
this is what it looks like for anyone wondering https://youtu.be/v8k1NOcU4sA

**Comment by VasilisThePikachu** [comment]
> Seems to happen with Emergency Suits as well.
> 
> ![Content Client_MfQM7h7pm3](https://user-images.githubusercontent.com/7543955/232343579-4e7544c9-c71d-43d2-921d-59476d1f19de.gif) [ ![Content Client_MfQM7h7pm3](https://user-images.githubusercontent.com/7543955/232343579-4e7544c9-c71d-43d2-921d-59476d1f19de.gif) ](https://user-images.githubusercontent.com/7543955/232343579-4e7544c9-c71d-43d2-921d-59476d1f19de.gif) [ ](https://user-images.githubusercontent.com/7543955/232343579-4e7544c9-c71d-43d2-921d-59476d1f19de.gif)

You don't even need a suit, just be very thirsty or hungry or hell even both. EVEN force if you also add the suit too now. Got killed once by rats cause i was literally unable to even run.

**Comment by deltanedas** [comment]
yeah it rubber bands and makes it so you cant move even though you should be able to

**Comment by DummeHytteOst** [comment]
this seems to have been fixed at some point, gonna do a few tests before closing
