### ISSUE TITLE
Bodies Rot In Space/Freezers

### ISSUE THREAD

**Issue by Alekshhh** [space-wizards/space-station-14#14399]
## Description
Like bodies in regular environments like halls, bodies in the cold of space and freezers will still actively rot and bloat at the same rate as bodies on station.

**Screenshots**
![image](https://user-images.githubusercontent.com/44923899/222903931-5b6a0c84-2262-4517-9823-fc83158c37d7.png) freezer
![image](https://user-images.githubusercontent.com/44923899/222904021-5046af48-3a33-434f-b363-696b5d1a77e9.png) space

**Additional Notes**
I noticed something, however, that cold spaces DO cause - they stop miasma from happening, as flies stop flying around bodies in cooled off places. It DOES have an effect on bodies, just not the desired one (stopping bloating)

**Comment by Biglulux** [comment]
I can confirm. I died in space a few times and watched my body rot. I was confused because it didn't make sense that bodies would rot in space.

**Comment by deltanedas** [comment]
space: space flies duh
freezer: ?????

**Comment by metalgearsloth** [comment]
Flies also persist forever.

**Comment by metalgearsloth** [comment]
There is code for this it just doesn't work.

**Comment by metalgearsloth** [comment]
Fixed I think.
