### ISSUE TITLE
modular mine bike horn is silent to the stepper

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#14404]
## Description
what it sounds (or does not) like
havent tested with chem/flash/explosive payloads
it's audible to other players but not the one that steps on it

**Reproduction**
1. make modular mine
2. put in bike horn
3. step on it
4. popup but no sound for you

**Comment by Slava0135** [comment]
hm, it works for me

**Comment by Slava0135** [comment]
I think i fixed it in #14391

**Comment by deltanedas** [comment]
probably
