### ISSUE TITLE
Turning on or off internals with the O2 button does not work

### ISSUE THREAD

**Issue by Flareguy** [space-wizards/space-station-14#14417]
## Description
Self-explanatory. When turning _on_ internals, it just doesn't work. When turning _off_ internals, it works until the do_after finishes, but then goes back to being on.
If this is fixed, the do_after for turning it on should also be removed, probably, as the action button does not have the same kind of delay.

**Reproduction**
1. Push the O2 button under the stamina bar
2. Get a do_after and the sound plays, but you still don't have O2
3. Die, maybe

**Comment by keronshb** [comment]
Fixed by #14609
