### ISSUE TITLE
cardboard box helmet doesn't hide your face

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#14436]
## Description

**Reproduction**

**Screenshots**

**Additional context**

**Comment by deltanedas** [comment]
cant you not see entities inside a box from the outside?

**Comment by DogZeroX** [comment]
egh, i forgot to add something

**Comment by deltanedas** [comment]
1 line pr might do

**Comment by QuietlyWhisper** [comment]
I'll add it to my todo list if no one is already on it
