### ISSUE TITLE
Slime hair isn't transculent

### ISSUE THREAD

**Issue by Just-a-Unity-Dev** [space-wizards/space-station-14#14430]
## Description

Title

**Reproduction**

1. Make a slime
2. Add hair
3. Oh no my hair

**Screenshots**

![image](https://user-images.githubusercontent.com/67359748/222994361-b1c11dd6-1faa-4309-8b47-5ecc0f48cc7d.png)

**Comment by CaptainSqrBeard** [comment]
uhhhh
