### ISSUE TITLE
Split UI incorrectly resizes when changing the size of the game window

### ISSUE THREAD

**Issue by DrSmugleaf** [space-wizards/space-station-14#14454]
## Description
**Reproduction**
- Put the game in fullscreen.
- Bring the split all the way to the right.
- Put the game back into a smaller window.

**Screenshots**
https://user-images.githubusercontent.com/10968691/223211857-08bfe480-2cc4-431d-ab85-b2689ed7f6f8.mp4

@vulppine

**Comment by vulppine** [comment]
i can reproduce this before the store chat size PR, so this may also be an engine issue since before that PR, the separated layout just used the engine SplitContainer widget
