### ISSUE TITLE
forensic scanner is an emag

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#14450]
## Description
forensic scanner can unlock locked lockers after scanning them, which will abort the actual fingerprint scan

**Reproduction**
1. get scanner
2. teleport into hop
3. emag his locker using scanner
4. free aa!!!!!

**Screenshots**
funny that happens when using scanner on an opened locker
![19:06:54](https://user-images.githubusercontent.com/39013340/223206697-df345f18-c390-4c11-abd5-5dc20067691a.png)

https://user-images.githubusercontent.com/39013340/223207254-297871be-c4f5-45e3-9bee-da7ce362aeff.mp4

**Comment by Naive817** [comment]
It's caused by Content.Server/Resist/ResistLockerSystem.cs I guess
