### ISSUE TITLE
Toggle internals button doesn't work

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#14463]
## Description

**Reproduction**

**Screenshots**

**Additional context**

**Comment by VasilisThePikachu** [comment]
You probably should provide more information, make sure you were wearing a mask before trying to activate your oxygen/nitrogen tank. Otherwise it will just do the cool down animation

**Comment by keronshb** [comment]
Might've been doafter related. Tested every possible UI button and did not have an issue. So fixed by #14609
