### ISSUE TITLE
Medibots broken again

### ISSUE THREAD

**Issue by Tunguso4ka** [space-wizards/space-station-14#14479]
## Description
medibots seems to be broken again. They just spam "Hold still please" and do nothing (even not trying to chase, poor guy)
![зображення](https://user-images.githubusercontent.com/71643624/223387938-2187cfe3-6216-41ff-9155-8fa6363ef842.png)

**Reproduction**
1. Get hurted
2. Find medibot
3. Get yelled by him if trying to move

**Comment by Naive817** [comment]
Did they ever do anything on upstream? I only remember seeing them doing something on nyano

**Comment by metalgearsloth** [comment]
They have a lot of snowflake logic which needs to be genericised significantly. Same with floorbots having draincomponent.
