### ISSUE TITLE
Godmode doesn't prevent bloodloss

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#14499]
I know coz you get the drunk shader effect still.

**Comment by AJCM-git** [comment]
the gods can bleed

**Comment by ElectroJr** [comment]
God mode in general just needs re-working. E.g., it stores data in the system rather than in components. It should also block all the negative effects that are reset by the rejuvenate verb.

**Comment by mirrorcult** [comment]
#14651
