### ISSUE TITLE
PhysicsComponent is deprecated

### ISSUE THREAD

**Issue by DrSmugleaf** [space-wizards/space-station-14#1452]
Need to replace all of its usages with CollidableComponent.

**Comment by Acruid** [comment]
Be careful with that. There is code that is using `TryGetComponent<IPhysicsComponent>` as an ad-hoc check for if the "body can be moved". You cannot blindly refactor out PhysicsComponent.

**Comment by DrSmugleaf** [comment]
Fixed by #1709
