### ISSUE TITLE
Anti-fingerprint c4 + lockers

### ISSUE THREAD

**Issue by kamilw25** [space-wizards/space-station-14#14544]
## Description
The syndicate have upgraded their anti-fingerprint technology on their c4 recently.

**Reproduction**
Try to scan c4 with a forensic analyser and no fingerprints will come up, (This is also an issue with lockers).

**Screenshots**

**Additional context**
Nerf the syndicate please :(

**Comment by Slava0135** [comment]
TL;DR make forensic scanner even more worthless

**Comment by Slava0135** [comment]
(oh i read it wrong nvm)

**Comment by Naive817** [comment]
C-4 can't have fingerprints is caused by server.sticky component

**Comment by ficcialfaint** [comment]
cant repro with both c4s and lockers. prolly been fixed alr
