### ISSUE TITLE
netprobe cartridge gets 1984d

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#14542]
## Description
when you click install it simply stops existing, until you eject > cartridge then put back in
after that it doesnt happen again

**Reproduction**
1. find netprobe cartridge on floor
2. put in pda
3. go into programs, click install
4. vanishes!

**Comment by Just-a-Unity-Dev** [comment]
cant repro on latest publish

**Comment by deltanedas** [comment]
mightve been fixed somehow overnight

**Comment by potato1234x** [comment]
did this 3 days ago and it worked fine

**Comment by deltanedas** [comment]
guess was just desync or something
