### ISSUE TITLE
Starting construction on a dirwindow and then moving makes you unable to construct that window.

### ISSUE THREAD

**Issue by Flareguy** [space-wizards/space-station-14#14555]
## Description
What it says on the tin.

**Reproduction**
1. Get a few sheets of reinforced plasmaglass
2. Try to make a directional reinforced plasmaglass window on a lattice
3. Fail the do_after
4. Realize that you cannot construct the window until you place it down again
5. Die?

**Additional context**
Discovered during a round on Wizard's Den Lizard

**Comment by keronshb** [comment]
Fixed by #14609
