### ISSUE TITLE
Containment field generators have trouble fitting through doors

### ISSUE THREAD

**Issue by Flareguy** [space-wizards/space-station-14#14556]
## Description
What it says on the tin.

**Reproduction**
1. Get a containment field generator from secure storage
2. Try to take it out of the department
3. Ass too fat

**Additional context**
It is not actually _impossible_ to get it through the door, with enough messing around it will eventually get through (or you can just wrench it and unwrench it for a much higher success rate.)

**Comment by potato1234x** [comment]
this happens with most machines and its infuriating

**Comment by Flareguy** [comment]
Fixed by #17849
