### ISSUE TITLE
Constructing grilles, then stopping the do_after takes the rods without making the grille

### ISSUE THREAD

**Issue by Flareguy** [space-wizards/space-station-14#14553]
## Description
What it says on the tin.
**Reproduction**
1. Make grille out of iron rods
2. Start constructing the grille, watch the count of your iron rods stack.
3. Step away from the grille to see that you have less materials than before

**Additional context**
Discovered during the previous round on Wizard's Den Lizard.

**Comment by keronshb** [comment]
Fixed by #14609
