### ISSUE TITLE
Using a flash without sunglasses flashes you

### ISSUE THREAD

**Issue by GoodWheatley** [space-wizards/space-station-14#14569]
## Description

Probably something to do with how the flash range is set?

**Reproduction**

1. Spawn in a flash
2. Take off sunglasses (if wearing any)
3. Use the flash
4. Observe how you just flashed yourself

**Comment by EmoGarbage404** [comment]
This seems intended? You're not wearing the protective gear.

**Comment by randy10122** [comment]
i dont think this is a bug

**Comment by GoodWheatley** [comment]
> This seems intended? You're not wearing the protective gear.

It says it’s a handheld bulb, so you have to be pointing it the wrong way to flash yourself.

**Comment by metalgearsloth** [comment]
This only affects non-sec so requiring sunglasses for the user is better.

**Comment by GoodWheatley** [comment]
> This only affects non-sec so requiring sunglasses for the user is better.

There's a PR up for giving all heads flashes in their backpacks, and 5 out of 7 heads don't have sunglasses. They *could* use the combat mode interaction to not flash themselves, but I doubt that most heads are going to know that interaction exists and will accidentally flash themselves instead.

~~Also headrevs~~

**Comment by randy10122** [comment]
> > This only affects non-sec so requiring sunglasses for the user is better.
> 
> There's a PR up for giving all heads flashes in their backpacks, and 5 out of 7 heads don't have sunglasses. They _could_ use the combat mode interaction to not flash themselves, but I doubt that most heads are going to know that interaction exists and will accidentally flash themselves instead.
> 
> ~Also headrevs~

i think i mentioned specifically in the changelog that you can hit people with flashes. if they dont learn after that it is their fault!!

**Comment by mirrorcult** [comment]
this is intended
