### ISSUE TITLE
Running out of fuel in a welder while deconstructing pipes or welding airlocks makes them impossible to deconstruct/unweld

### ISSUE THREAD

**Issue by DawBla** [space-wizards/space-station-14#14583]
## Description
Running out of fuel in a welder while deconstructing pipes makes them impossible to deconstruct

**Reproduction**
1. Find unanchored pipe or an airlock
2. Start deconstructing/welding it with low fuel
3. Make sure fuel runs out while the progress bar is still visible
In case of the pipes getting the welder below 10 units of fuel is enough

**Additional context**
Both starting to deconstruct a pipe with ~10 units of fuel in the welder so the passive fuel consumpion of a lit welder gets the fuel below 10 units needed to deconstruct and attempting to deconstruct multiple pipes at once while having enough fuel to only deconstruct some of them causes this bug to happen
Any pipe that had its progress bar visible when the fuel ran out becomes impossible to deconstruct
In case of the airlocks the bug only happens if the passive fuel consumption depletes all avaliable fuel in the welder while welding/unwelding the airlock
This can be abused pretty easily, since toggling on and off emergency welder depletes the 25 units of fuel it has very quickly and lets traitors sabotage important location and then bug out the door.
The only way to open door like that is to start deconstructing it and then reconstructing it back

**Comment by potato1234x** [comment]
this happens with any action involving welding

**Comment by deltanedas** [comment]
and same for moving to interrupt the doafter
