### ISSUE TITLE
no way to escape from wielded containers

### ISSUE THREAD

**Issue by Tunguso4ka** [space-wizards/space-station-14#14606]
## Description
looks like doAfter break wielded shut containers and you cant escape it now by yourself. The "breaking out" processbar do nothing, the container will be still wielded shut.

**Reproduction**
1. Get in the box/closet
2. Let the second person wield it shut
3. Congrats. You now trapped inside the container.

**Comment by ElectroJr** [comment]
I can't seem to reproduce this on latest master. Maybe this fixed by one of the previous rounds of DoAfter fixes?

**Comment by Tunguso4ka** [comment]
> I can't seem to reproduce this on latest master. Maybe this fixed by one of the previous rounds of DoAfter fixes?

![зображення](https://user-images.githubusercontent.com/71643624/225615654-422f0ae7-77e8-4714-abfe-1756ea9dfd49.png)
its seems you cant escape it if you dont have hands. :/
so its seems not a problem.

**Comment by deltanedas** [comment]
mouse should be able to chew its way out of a crate

**Comment by deltanedas** [comment]
:sob:

**Comment by keronshb** [comment]
Fixed by #14609
