### ISSUE TITLE
c20r missing auto eject function

### ISSUE THREAD

**Issue by Emisse** [space-wizards/space-station-14#14633]
c20r used to auto eject its magazine with a distinct beeping noise
this was cool and an interesting balance for the weapon since it let everyone know when it needed to be reloaded which can lead to some good gameplay from either the user/victims

**Comment by Flareguy** [comment]
It looks to be commented out (in Prototypes\Entities\Objects\Weapons\Guns\SMGs\smg.yml:)
![image](https://user-images.githubusercontent.com/78941145/224761885-ee905b58-36e0-4451-aa28-ed08950896a9.png)
No clue on if the issue mentioned here is actually fixed or not yet.
