### ISSUE TITLE
Throwing an item in a locker juts the locker downward, through walls etc

### ISSUE THREAD

**Issue by ProfanedBane** [space-wizards/space-station-14#1465]
What it says on the tin.

- Get item
- Go into locker and close it
- Throw it
- Go on magical adventure downwards half a tile

**Comment by SweptWasTaken** [comment]
Did multiple tests of this in debug, doesn't throw you through walls or downward anymore. Just a slight judder of the locker to the left. Honestly just disable throwing in lockers.
