### ISSUE TITLE
Solar flare can open/close curtains

### ISSUE THREAD

**Issue by DummeHytteOst** [space-wizards/space-station-14#14659]
Title

it can possibly also open wooden, paper, steel and other types of doors that it should have no way of affecting

https://user-images.githubusercontent.com/94384139/225115506-35e12183-3335-4046-aedb-4eeb4b133919.mp4

**Comment by deltanedas** [comment]
slava already has a fix open

**Comment by deltanedas** [comment]
this has been fixed
