### ISSUE TITLE
EVERY SINGLE DOAFTER IS BROKEN

### ISSUE THREAD

**Issue by Stealthbomber16** [space-wizards/space-station-14#14677]
## Description
Not clickbait. Doafters broke on the latest merge. 9/10 doafters do not complete.

Interrupting a doafter will give you the feedback "You fail to remove the cuffs."

**Reproduction**
Try any of the following:
1. swabbing a plant
2. swabbing a player
3. entering a disposal bin
4. using a syringe
5. **putting a player into the medical scanner**

I can't personally confirm that any of these work, but they've also been reported by other players.
1. Health analyzers
2. Mining rock
3. Butchering a corpse (or jumpsuit)
4. Forensic analyzers
5. Dumping a chem bottle or plant bag onto a table

Notably, I have noticed that crowbarring a tile _does_ still work.

The game is literally unplayable.

##See also
https://discord.com/channels/310555209753690112/1085264315998797966
https://discord.com/channels/310555209753690112/1085194573179011172
@Chief-Engineer feel free to link the ahelp relay conversation we had about this

**Comment by Emisse** [comment]
ill try repro on local in a couple hours if nobody else can

**Comment by ElectroJr** [comment]
By latest merge, do you mean master or the current server build?

**Comment by Stealthbomber16** [comment]
This is currently on lizard as of 15 minutes ago.

**Comment by ElectroJr** [comment]
#14669 should already have fixed disposals

**Comment by ElectroJr** [comment]
One of the probably causes is that after #14382 handcuffs now intercepting and erroring on other do afters that improperly specify event targets..
