### ISSUE TITLE
Biomass Reclaimer Does Not Work (DoAfter?)

### ISSUE THREAD

**Issue by Alekshhh** [space-wizards/space-station-14#14690]
## Description
Title explains it. Can't drag people into biomass reclaimers, it just cancels the bar when it reaches full

**Comment by Skyedra** [comment]
FYI this PR fixes it:  https://github.com/space-wizards/space-station-14/pull/14609/files#diff-29a1f0c3607b956992071ceee1f1dce8bd2c3604c3190a702f758c3565a53601  So hopefully it gets finished/merged soon ^.^
