### ISSUE TITLE
pathfinding broken (on debug?)

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#14708]
## Description
npcs simply stay still forever
happened on cluster in debug on rehydratable-refactor no idea why it happen

**Reproduction**
1. spawn a bunch of mobs
2. they dont move

**Screenshots**
![162149](https://user-images.githubusercontent.com/39013340/225686275-2d79f94a-fda6-410d-91cc-440f34a2bf0c.png)

**Comment by Scribbles0** [comment]
did you set npc.enabled to true?

**Comment by deltanedas** [comment]
????? why
anyway how can this be enabled i need to make sure fish petting works

**Comment by Scribbles0** [comment]
> ????? why
> 
> anyway how can this be enabled i need to make sure fish petting works

try sudo cvar npc.enabled true
