### ISSUE TITLE
nukies need roletimers

### ISSUE THREAD

**Issue by Stealthbomber16** [space-wizards/space-station-14#14711]
## Description
new players who have no idea how to turn on their internals, much less take a jetpack ride through space to the station or have a firefight with the crew, are getting nuclear operatives and nuclear operative commander roles.

nuclear operatives need a flat playtime roletimer
nuclear commander needs a playtime roletimer, timegates behind command roles, and a nukie playtime timegate.

**Comment by deltanedas** [comment]
i will try doing this

**Comment by lzk228** [comment]
fixed
