### ISSUE TITLE
Shuttle Arrival needs to check for occupied space before arriving

### ISSUE THREAD

**Issue by Emisse** [space-wizards/space-station-14#14718]
specifically centcom
evac shuttle and cargo shuttle often end up at centcom warped inside of each other
maybe have only evac shuttle warp to dock and make all other shuttles warp nearby area (like they used to)
hurg

**Comment by deltanedas** [comment]
![01:26:08](https://user-images.githubusercontent.com/39013340/235383372-8f942280-9f88-4883-970c-e3798d6f6e53.png)
happens for ftling to planets too, you can spawn inside a rock

**Comment by metalgearsloth** [comment]
The planet issue is something else entirely.
