### ISSUE TITLE
Cloning

### ISSUE THREAD

**Issue by DrSmugleaf** [space-wizards/space-station-14#1473]

**Comment by Auri3l** [comment]
Not necessary due to Tgstation removing the cloning system.

**Comment by Zumorica** [comment]
> Not necessary due to Tgstation removing the cloning system.

At least come up with a good reason, not just "they removed that so we should follow in their steps!!!"

**Comment by SoulSloth** [comment]
> Not necessary due to Tgstation removing the cloning system.

Not at all, leaving aside the fact that the decision tgstation made was controversial, consider that it already had borgs, PAI, mid-round antags, golems, and a plethora of other ways for players to re-spawn after death.

Robotics itself is currently in the [controversial and unimportant  ](https://hackmd.io/@ss14/docs/%2F%40ss14%2Froadmap#Controversialunimportant-jobs) category of the roadmap, so any other form of mid-round revival for SS14 is far off.

Personally though, I just like having a reason to bomb medbay.

**Comment by SoulSloth** [comment]
Dibs now that body rework is in.

**Comment by ike709** [comment]
https://github.com/space-wizards/space-station-14/pull/1932
