### ISSUE TITLE
kill target objective should be complete for afkers

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#14733]
## Description
if someone flies off into space with a full oxy tank with suit sensors off its guaranteed redtext since impossible to kill

it should instead be that if you arent on evac, or maybe just if you leave the game, you count as dead
this way theres less hunting for afk people as syndie

**Comment by SpeltIncorrectyl** [comment]
Perhaps kill objectives could be replaced somewhat with maroon objectives, where you have to stop your target from escaping on the shuttle, but they could be alive elsewhere.
Or have a traitor item that can track your assassination targets.

**Comment by deltanedas** [comment]
yes i tried implementing the former but gave up due to IoCManager chicanery
