### ISSUE TITLE
Using an emoticon at the start or middle of a message does not trigger an emote

### ISSUE THREAD

**Issue by VasilisThePikachu** [space-wizards/space-station-14#14748]
## Description

This may fit more of a "feature request" but i do feel like this is a bug. When you issue an emoticon at the end of a message (xd, :), :( as examples) it gets turned to an emote (laughs, smiles, frowns). However this does not happen if the emoticon is at the start or middle of a message.
**Reproduction**

1. Type an emoticon somewhere other then the end of your message ("xd cap lost the nuke disk", "Cap lost the disk xd. We are in trouble")
2. The xd will not become a "laughs" emote and will be displayed as the message.
**Screenshots**

Don't have access to the game as of currently, will supply soon
**Additional context**

You could maybe argue this is a feature? But i dont really see a reason for them as text instead of emotes either way

**Comment by moonheart08** [comment]
Intended behavior.
