### ISSUE TITLE
Morgues/body bags don’t stop bodies from rotting

### ISSUE THREAD

**Issue by GoodWheatley** [space-wizards/space-station-14#14760]
## Description
Title, observed on Lizard

**Reproduction**

1. Stick fresh corpse in morgue and close it
2. Wait 10 minutes
3. Open morgue tray
4. Body has rotted

**Comment by deltanedas** [comment]
i believe this worked before, something must have broken it recently

**Comment by metalgearsloth** [comment]
Dupe https://github.com/space-wizards/space-station-14/issues/14399
