### ISSUE TITLE
DoAfter progress bar visually flickers upon cancel

### ISSUE THREAD

**Issue by GoodWheatley** [space-wizards/space-station-14#14761]
## Description

This has been a thing for months, it only occurred to me now that this might not be intended behavior. The progress bar turning red makes sense, but the bar flickering weirdly doesn’t.

**Reproduction**

1. Start DoAfter
2. Cancel DoAfter through one of the various cancel methods
3. DoAfter progress bar turns red and flickers for a second before disappearing

**Comment by Naive817** [comment]
I think its intended to flicker? To give a better visual cue that the DoAfter is cancelled

**Comment by mirrorcult** [comment]
yeah im pretty sure this is intended
