### ISSUE TITLE
There's been layer exception spam lately

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#14771]
## Description

**Reproduction**

**Screenshots**

![image](https://user-images.githubusercontent.com/43253663/226971796-22911075-cf5c-4943-b135-be4ae03b49c8.png)
![image](https://user-images.githubusercontent.com/43253663/226971868-1efdc489-4fd4-4bd4-b72b-1b9a5a631c9d.png)
also this thing: 
![image](https://user-images.githubusercontent.com/43253663/226972025-f2d8eb98-2011-40a7-bd59-a0a92bc7dce0.png)

**Additional context**
Happens when I ghost around, sometimes this comes with PVS not loading stuff properly

**Comment by Elijahrane** [comment]
Cuffable seems to require sprite changes now where it didn't before; I had cuffable monkeys crashing the game when I merged the handcuff ECS stuff because they didn't have a layer
