### ISSUE TITLE
Round start countdown is inaccurate

### ISSUE THREAD

**Issue by GoodWheatley** [space-wizards/space-station-14#14774]
## Description

The round doesn't actually start until a few seconds after the timer ends, might be related to #14755 loading the station 15 seconds early

**Reproduction**

1. Forcibly end round
2. Wait for round start timer to tick all the way to 0
3. Round doesn't start
4. Round actually starts a few seconds later

**Comment by Emisse** [comment]
its because its spawning the map and setting up the mode

**Comment by metalgearsloth** [comment]
It's https://github.com/space-wizards/space-station-14/pull/14755 I'll fix in a bit.
