### ISSUE TITLE
Acronym & Logo have unfortunate connotations

### ISSUE THREAD

**Issue by bloche1871** [space-wizards/space-station-14#1479]
The acronym for this game, "SS14" can be interpreted as a Nazi dogwhistle as both halves of it are commonly used that way by nazi groups to signal their allegiance without drawing too much attention: the "SS" due to it being the acronym of the Schutzstaffel, and the number 14 in reference to a slogan they use: https://en.wikipedia.org/wiki/Fourteen_Words

**Comment by SweptWasTaken** [comment]
_Can be interpreted_ is easy to say. I can interpret anything to mean what I want it to mean. I can safely say for anyone officially affiliated with SS14 that it is **not** a nazi dogwhistle and will never be one.

**Comment by PJB3005** [comment]
At this point it's way too late to change the project name. I trust that people are level headed enough to keep the two separated.

**Comment by voidus** [comment]
To be very clear: I'm not trying to pressure or force anything here. I'm voicing my personal outside opinion and ideas with the hope that we can find something that doesn't leave anybody frustrated.

I didn't for a second assume that the logo was actually intended as dog whistle, and I also don't really think that fascists will read it as such. That said, I am uncomfortable to see it. I understand you aren't, and that's okay, we all have had different experiences in life.

It seems to me that the proposal was not about changing the name. I personally think it's great in that it signifies that this project aims to rebuild/extend space station 13 without fundamentally changing the gameplay, if that's accurate. As I read it (and would suggest to reconsider) this is about changing the Logo mostly. Acronyms are kind-of given, but the logo leaves room for more creative freedom.

How committed are you on the logo? Would you be open to talking to an artist about ideas and maybe looking at a draft?

**Comment by PJB3005** [comment]
I wouldn't have any problems looking at new logo designs (or ideas), but it would have to look at least as good as the current one.

Right now we use a slightly-edited (I poorly changed the 3 into a 4 with Inkscape) version of the branding of the "original" remake project formerly hosted at https://spacestation13.com (which this project is effectively a descendant of). For reference here is the original logo bundle they commissioned: [SpaceStation13-LogoBundle_v2.zip](https://github.com/space-wizards/space-station-14/files/7491163/SpaceStation13-LogoBundle_v2.zip). This design had a small logo that looked like this: 
![image](https://user-images.githubusercontent.com/8107459/140622505-aeb7798c-087b-44e5-b983-18fcc8d42d30.png)

I initially tried to turn the 3 into a 4 but the results did not turn out great at all (https://github.com/space-wizards/asset-dump/blob/master/ss14_logo.svg). Unusualcrow made the current logo and we all instantly agreed it looked great when we first saw it.

**Comment by SweptWasTaken** [comment]
If you'd like the logo to be changed your best bet is coming up with something that looks better than the current one. Personally my opinion is I don't think it's worth putting in the effort to change the logo. If the logo makes you uncomfortable maybe just don't look at it?

**Comment by PaulRitter** [comment]
> 
> 
>  If the logo makes you uncomfortable maybe just don't look at it?

probably the worst response you could give to something. don't

**Comment by Visne** [comment]
@voidus What exactly about the logo do you dislike? Is it the fact that the acronym is on the logo, or that the font looks sort of similar to the SS font? Or something else?

**Comment by voidus** [comment]
It reminds me a lot of the ss runes, and the 14 kinda supports that. Thank you for your answer @PJB3005, sadly I am not an artist but if someone with the necessary skills and drive finds this issue they might propose an alternative :)

**Comment by Visne** [comment]
> 
> 
> TBH I have just seen a lot of nazi stuff in my life and the combination of SS and 14 just feels like a little too much to ignore. Thank you for your answer @PJB3005, sadly I am not an artist but if someone with the necessary skills and drive finds this issue they might propose an alternative :)
> 
> Edit: Fixed wrong reference to the SS font, I don't think it looks like that at all

If you had an issue with the font then I would consider changing that, but the term "SS14" is used almost everywhere: in the logo, in the game, by the developers, and by people in the SS13 community. At this point it is really to late to change the name of the game, and changing the logo while keeping the name "SS14" everywhere else is nonsensical in my opinion.
