### ISSUE TITLE
People reporting the right side of the ui dissapearing

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#14834]
## Description

They can't see the health, hunger, etc
**Reproduction**

None found yet
**Screenshots**

**Additional context**

**Comment by deltanedas** [comment]
is it just alerts or is other stuff missing too (chat??? is there anything else even)

**Comment by DogZeroX** [comment]
Not chat, just alerts

**Comment by KostyaYaschuk** [comment]
As a player, I confirm that there is such a problem, if you try to resize the chat by dragging the mouse over the edge (this is possible on Corvax, I don’t know about other servers), then indicators of food, health, temperature, etc. immediately appear.

**Comment by QuietlyWhisper** [comment]
It's absolutely a reoccuring issue that nobody knows how to replicate it so far... it just sort of happens, you only notice its gone when you need it

**Comment by smilekrit** [comment]
i had problem with chat missing today

**Comment by potato1234x** [comment]
can reproduce

**Comment by KostyaYaschuk** [comment]
Video with a bug, in my opinion this bug appears from the beginning of the round.
https://user-images.githubusercontent.com/61995172/227728106-c8a088ac-3f4b-4081-8511-ccf68aad7fa0.mp4

**Comment by jamessimo** [comment]
This happens to me quite a lot (icons missing, not chat). Not sure what causes it but to fix I just resize my screen and they come back.

**Comment by Emisse** [comment]
resizing the chat window fixes this. im not sure if ui has a process to dirty things like components do but something like that could fix this.

**Comment by metalgearsloth** [comment]
Of note:
- This only happens with default hud layout
- The AlertsUI itself is pushed off-screen by the Y size.
- Pretty sure it was #14299
