### ISSUE TITLE
rd portal can be used across maps

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#14833]
## Description
not sure if this is intended or not but you can visit arrivals in 2 tiers:
- visiting when the shuttle is docked
- visiting anytime with a portal on the arrivals station

**Reproduction**
1. put portal on the arrivals shuttle
2. wait for it to leave
3. put portal on station
4. now have tier 1 access
5. go to arrivals station and remove portals
6. put portal on arrivals station
7. have a latejoin set up the other end on the station
8. tier 2 full access to arrivals station

**Additional context**
again i dunno if this is a bug or intended consequence of using portal across maps

also happens for cargo trading station i think

**Comment by tom-leys** [comment]
So if you place a second portal on a different map, the first portal closes?

**Comment by mirrorcult** [comment]
yes
