### ISSUE TITLE
Meta station telecom servers dont get enough power

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#14838]
## Description
The telecom servers are located in the AI satellite, on a different power grid than the station. The single generator there is not sufficient to keep all the telecom servers powered and thus the station will eventually lose coms.

 players can fix the problem by bringing in more generators or hooking up the sat to the main grid but this feels unintuitive.

**Comment by Emisse** [comment]
i have a fix for this but postmapinit tests are failing so cant merge rn

**Comment by VasilisThePikachu** [comment]
Would this also fix crew server dying after a bit of time? Made ahelps about this as it seems to only happen on meta

> i have a fix for this but postmapinit tests are failing so cant merge rn

**Comment by lzk228** [comment]
@Emisse

**Comment by Emisse** [comment]
this was fixed a while ago
