### ISSUE TITLE
Midi playback error

### ISSUE THREAD

**Issue by KostyaYaschuk** [space-wizards/space-station-14#14848]
## Description

There is a bug with midi music. When I want to change music, I have to choose 2 times. I have this bug on all musical instruments, but this is not accurate.
I will attach a video and 2 midi files for an example.

https://user-images.githubusercontent.com/61995172/227730440-5cbb8fb2-a60b-4fa5-bcc6-7dcce7c0ff97.mp4
[SS14MIDI.zip](https://github.com/space-wizards/space-station-14/files/11069443/SS14MIDI.zip)

**Comment by jamessimo** [comment]
+1 I have noticed this too.

**Comment by deltanedas** [comment]
its been reported already but cant find it

**Comment by metalgearsloth** [comment]
Do you know if corvax has done anything with midi

**Comment by VasilisThePikachu** [comment]
Fixed by #23339
