### ISSUE TITLE
Nuke being able to be taken to terminal from arrival shuttle

### ISSUE THREAD

**Issue by MysticPhantasm2** [space-wizards/space-station-14#14852]
Nuke was brought to terminal during a nukie round. 

**Reproduction**
As easy as putting the nuke onto arrival shuttle

**Comment by deltanedas** [comment]
arrival ops:
1. get dat fukken disk
2. get rd portal gun
3. visit arrivals and bring nuke onboard
4. nuke arrivals station
5. omega victory!!!!
