### ISSUE TITLE
You can point at pointing arrows

### ISSUE THREAD

**Issue by exp111** [space-wizards/space-station-14#1486]
1. Point at something
2. Right click the pointing arrow
3. Hover over the entry in the right click menu
4. Shift + middle-click

I think both pointing arrows and drag shadows shouldn't be shown in the right-click menu

**Comment by PJB3005** [comment]
Yeah we need some way to hide certain entities from right click. Another case is the overlay used by low walls I believe.

**Comment by F77F** [comment]
rofl

**Comment by DrSmugleaf** [comment]
Fixed by https://github.com/space-wizards/space-station-14/pull/1527

**Comment by DrSmugleaf** [comment]
> Yeah we need some way to hide certain entities from right click. Another case is the overlay used by low walls I believe.

Moved to #1528
