### ISSUE TITLE
Colorblindness trait is not applied in shift-click menu 

### ISSUE THREAD

**Issue by BRINGit34** [space-wizards/space-station-14#14878]
## Description
When colorblindness trait is selected shift-clicking on a crew member will show a full color image of the crew member 

**Reproduction**
1. Select colorblindness trait 
2. Shift-click crew member 
3. See full color image of said crew member

**Screenshots**

![Evedince](https://user-images.githubusercontent.com/67086183/227790972-ed264530-c68b-4cfe-ac43-4a1e2c8e81a4.png)

**Comment by moonheart08** [comment]
Not our bug. Talk to your server host, we do not have this trait.
