### ISSUE TITLE
Clown's sad trombone implants play both on crit and death

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#14904]
## Description

It's funny but also a bit wacky, since there are situations where they are between life and crit and the sound gets spammed. I also assume it's supposed to be just a death sound implant
**Reproduction**

**Screenshots**

**Additional context**

**Comment by DawBla** [comment]
This also applies to nukie bomb implant
It says on the tin "when user dies" but it detonates on crit
Seems like 
type: TriggerOnMobstateChange
      mobState: Dead
Just doesn't care about the Dead part
