### ISSUE TITLE
Taking batteries out of mechs is broken

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#14908]
## Description

**Reproduction**

Crowbar a mech with a battery on it
The battery gets deleted/the energy gets drained
Can't put a new battery in it
**Screenshots**

**Additional context**

**Comment by keronshb** [comment]
Fixed by one of these two engine PRs:
https://github.com/space-wizards/RobustToolbox/pull/3901
https://github.com/space-wizards/RobustToolbox/pull/3902
