### ISSUE TITLE
Broken posters don't obey the laws of physics

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#14911]
## Description

They basically float around when destroyed
**Reproduction**

**Screenshots**

![image](https://user-images.githubusercontent.com/43253663/228062360-21ee462a-eefa-43a6-8c63-795cb5afe24c.png)

**Additional context**

**Comment by Alekshhh** [comment]
anyone ever gonna get to this

**Comment by HoofedEar** [comment]
On it
