### ISSUE TITLE
Uniform Printer can't print non-head winter coats

### ISSUE THREAD

**Issue by Stealthbomber16** [space-wizards/space-station-14#14933]
## Description
Uniform printer can print the coats of the heads of departments, but not any normal winter coats

**Additional context**
Normal winter coats need to be added to the uniform printer
1. This gives HOP something to do in the event of an atmos issue
2. This means uniforms can be chopped up for winter coats
3. This means you no longer need durathread to make winter coats
4. This opens up funny gimmicks to the crew

**Comment by Stealthbomber16** [comment]
Inspired by the round on lizard where someone sabotaged the station with a freezer. In response I made a uniform printer, got cloth, and got cockblocked by the fact I was completely unable to make coats to supply to the crew.

**Comment by UbaserB** [comment]
This was fixed.
