### ISSUE TITLE
CBURN armour has no disease resistance

### ISSUE THREAD

**Issue by Myakot** [space-wizards/space-station-14#14950]
## Description
CBURN are a special squad designed to counter everything that's in their name, however their own hardsuits, masks and gloves are useless against their most hazardous threats - zombies and viruses.

**Reproduction**
Zombie infection has a 50% base transfer chance upon a bite, stacked disease resistance (clothing and race, like lizards) reduce that chance to up to 5% infection chance.

This means that a random intern is better protected against zombies than a whole anti-zombie unit is. Their clothing needs disease resistance comparable to that of CMO clothing or, at least, default doctor clothing.

**Comment by PuroSlavKing** [comment]
https://github.com/space-wizards/space-station-14/pull/14953

**Comment by PuroSlavKing** [comment]
Проблема решена, закрой :trollface:

**Comment by PuroSlavKing** [comment]
problem solved, close :trollface:
