### ISSUE TITLE
Artifact container lets you lock people inside of it and they have no way of escaping it

### ISSUE THREAD

**Issue by DawBla** [space-wizards/space-station-14#14971]
## Description

Artifact containers for XenoArcheology in science let you put people and other living creatures inside of them despite having the whitelist component Artifact in their yml.

**Reproduction**

1. Spawn in Artifact container
2. Put another person inside of it
3. Close and lock it
They have no way of getting out of it

**Additional context**

Changing the whitelist to blacklist indeed blocks you from putting the Artifacts inside, but whitelist seems to not work at all.
Adding ResistLocker component to the container or blacklisting everything except artifacts kinda solves it, but it seems like a bandaid fix.

**Comment by slarticodefast** [comment]
Just tested this and it seems to be fixed now. You can escape like from every other container.

![a](https://github.com/user-attachments/assets/fcb98d7e-fa32-4868-9af8-bc4dbf8ced3f)
