### ISSUE TITLE
Pulling someone who's buckled to something throws an exception.

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#1499]
To replicate
1. Buckle someone to a chair
2. ctrl click on _them_ not the chair
3. walk away

Tested with both anchorable and non anchorable chairs.

![image](https://user-images.githubusercontent.com/49448379/88502722-ed49e400-cfbe-11ea-9b42-b7da5aa33654.png)

**Comment by DrSmugleaf** [comment]
Bold of you to assume that I programmed both of the things at play
![image](https://user-images.githubusercontent.com/10968691/88584741-6b0aff80-d052-11ea-8dc7-7984578d396c.png)
