### ISSUE TITLE
Stealthy e-magging

### ISSUE THREAD

**Issue by Myakot** [space-wizards/space-station-14#15040]
## Description
It's still possible to e-mag doors bypassing the e-mag sound and visual effects.

**Reproduction**
1. Have no access to the door you're about to e-mag
2. Bump into the door to trigger "denied" sound and visual effect (or just click on it to do the same)
3. While sound and visual effect is playing - e-mag the door
4. It's now a useless e-magged door and you just stealthily infiltrated whatever you wish.

**Screenshots**
https://cdn.discordapp.com/attachments/1090584863649824878/1090584864299950150/Space_Station_14_-_Corvax_Station_RU_2023-03-29_13-31-11.mp4

**Additional context**
Bug was found by Lomcastar, Corvax discord.

**Comment by Pangogie** [comment]
Fixed at some point.

**Comment by exincore** [comment]
Whoops, this was fixed by #25836
