### ISSUE TITLE
Collision out of bounds error in "entsys".

### ISSUE THREAD

**Issue by EnefFlow** [space-wizards/space-station-14#15047]
## Description

Something is broken in robust collisions. More info in screenshot. This lags the server.
**Reproduction**

Collide two things?
**Screenshots**

![image](https://user-images.githubusercontent.com/104197232/229306453-f8dd563d-d04d-4055-8100-31a4351519fd.png)

**Additional context**

**Comment by metalgearsloth** [comment]
what engine version is this

**Comment by EnefFlow** [comment]
> what engine version is this

0.96.0.4
