### ISSUE TITLE
Can't select all text in ChatBox input LineEdit (Ctrl+A)

### ISSUE THREAD

**Issue by clement-or** [space-wizards/space-station-14#1505]
Currently it is not possible to select all text in the ChatBox input by pressing Ctrl+A, which is usual in other games/programs.
A workaround for now is to use `Shift + End + →`

**Comment by moonheart08** [comment]
Related: #1464

**Comment by StrawberryMoses** [comment]
Hm, I'm not able to reproduce this one: 

![controlA](https://user-images.githubusercontent.com/8854773/88852854-7aa25980-d1b4-11ea-94e7-f4e80a506452.gif)

**Comment by clement-or** [comment]
I just did some more testing. It happens on an AZERTY keyboard that the key combination to select all texte becomes Ctrl+Q instead of Ctrl+A

**Comment by ShadowCommander** [comment]
Hm, then that's expected behavior. The keybinds are based on position rather than the key currently. For AZERTY keyboards is it supposed to be Ctrl+A?

I'm not sure if we'll do anything about that directly, but we do have key rebinding half working, there's a file that people can use to change keybinds, we just need to get a GUI for it.

**Comment by clement-or** [comment]
Shortcuts on AZERTY keyboards are often the same and AZERTY users are used to their position. For example Ctrl+A is still Ctrl+A and has the same position as Ctrl+Q on a QWERTY. Same goes for Ctrl+Z, Ctrl+W and so on.

For game controls it's often the opposite, position is conserved.

It seems it would be best as a default behaviour to keep the actual _keys_ for keyboard shortcuts and _position_ for game controls, but as you said, rebinding is supported so it's just a matter of rebinding on future localized versions.

**Comment by PJB3005** [comment]
Supporting that kind of stuff is *really* annoying especially due to a lack of proper platform APIs for this crap.

Frankly whatever UI designer thought those shortcuts should change position based on keyboard layer was a moron.

**Comment by SweptWasTaken** [comment]
Closing as this issue has a sorta duplicate issue and the discussion here has been resolved.
