### ISSUE TITLE
(Debug Build Only) Using health analyzer crashes the server

### ISSUE THREAD

**Issue by VasilisThePikachu** [space-wizards/space-station-14#15075]
## Description

**Reproduction**
1. Build debug
2. Use health analyzer
3. ```Robust.Shared.Utility.DebugAssertException```

**Additional context**

Health analyzers may be used for debugging in scenarios, even if it only happens on debug builds it should be fixed

**Comment by keronshb** [comment]
> ## Description
> 
> **Reproduction**
> 
>     1. Build debug
> 
>     2. Use health analyzer
> 
>     3. `Robust.Shared.Utility.DebugAssertException`
> 
> 
> **Additional context**
> 
> Health analyzers may be used for debugging in scenarios, even if it only happens on debug builds it should be fixed

I'm sure this might've been related to doafters somehow. Please post the full Assert stack next time so we can be sure. I tested it on master with debugging on and I wasn't able to replicate.

**Comment by VasilisThePikachu** [comment]
Sorry for the wait, yeah it is a doafter thing
[error.txt](https://github.com/space-wizards/space-station-14/files/11149535/error.txt)

**Comment by keronshb** [comment]
> Sorry for the wait, yeah it is a doafter thing [error.txt](https://github.com/space-wizards/space-station-14/files/11149535/error.txt)

Can you try to replicate it again today? I'm not getting any errors on debug mode.

**Comment by ElectroJr** [comment]
Merge master into your branch, this should've been fixed by #14609

**Comment by VasilisThePikachu** [comment]
Forgot to clone this, fixed by #14609
