### ISSUE TITLE
You can no longer construct multiple windows at once

### ISSUE THREAD

**Issue by Flareguy** [space-wizards/space-station-14#15097]
## Description
What it says on the tin.

**Reproduction**
1. Make a few directional reinforced plasmaglass windows and click on multiple at once
2. See the plasmaglass fall on the ground and the do_after restart

**Comment by Emisse** [comment]
https://github.com/space-wizards/space-station-14/pull/14609

**Comment by keronshb** [comment]
> this was caused by the latest doafter fix patch, it added something that disables multiple doafters at once which should probably be rethought or reverted

There is an option to do multiple doafters at once. See: Mining, Stripping.
