### ISSUE TITLE
phantom items being unable to attack bug

### ISSUE THREAD

**Issue by Emisse** [space-wizards/space-station-14#15096]
happens with {some} premapped items being unable to attack with (doesnt happen with items that spawn on containers or init)
no clue what causes this
repro
go on a map with premapped items
some of the items you cannot attack with (latest example being barratry crowbar on floor and wrench)
help me understand

**Comment by metalgearsloth** [comment]
Look for meleeweapon component.

**Comment by Emisse** [comment]
![image](https://user-images.githubusercontent.com/99158783/229447259-10709f9b-d867-447e-a96a-f71cd88113d7.png)
theyve gottem but cannot attack with them
repro
barratry crowbar chapel below bridge (all the crowbars)

**Comment by metalgearsloth** [comment]
in the map file nextattack will be serialized as some arbitrary number

**Comment by ZoldorfTheWizard** [comment]
@Emisse pls retest this issue now that #15123 is merg
