### ISSUE TITLE
particle accelerator construction broken doafter?

### ISSUE THREAD

**Issue by Emisse** [space-wizards/space-station-14#15099]
you cannot put lv cable in it on lv cable step

**Comment by keronshb** [comment]
Unable to replicate, fixed?

![image](https://user-images.githubusercontent.com/54602815/229638317-e5492f39-37ec-4a25-8b01-68308597f3cc.png)

![image](https://user-images.githubusercontent.com/54602815/229638334-7c5375be-97a3-4c10-99d8-85944b2c5d8f.png)

**Comment by keronshb** [comment]
Unable to replicate
