### ISSUE TITLE
Tiles have a deconstruction option despite not being deconstructable

### ISSUE THREAD

**Issue by Flareguy** [space-wizards/space-station-14#15100]
## Description
What it says on the tin. Clicking the "start deconstruction" option on the tile item does nothing.
Should probably be actually deconstructable instead of the option just being removed.

**Reproduction**
1. Pry a floor tile
2. Right click the tile
3. Click Begin Deconstruction
4. Cry

**Additional context**
I was playing on barrantry so it could have been one of the funny tile variants instead of just the basic steel tile.

**Comment by Emisse** [comment]
steel tile basic has it as well

**Comment by slarticodefast** [comment]
Tested this with every single tile. Seems to be fixed now.
