### ISSUE TITLE
Lizards have x2 stomach volume

### ISSUE THREAD

**Issue by Myakot** [space-wizards/space-station-14#15108]
## Description
Prototypes/Body/Organs/animal.yml is the parent organ for Lizard organs and it has:

//      stomach:
//        maxVol: 100

Prototypes/Body/Organs/reptilian.yml is the actual Lizard organ and it has:

//  - type: Stomach
//    maxVolume: 50

IMO (not code-savvy) - the conflict is in "maxVol" and "maxVolume".

**Reproduction**
1. Force feed a lizard a lot of drinks/food or just 3 30u pills in a row and it'd eat all of them up, as if it had a 100u stomach capacity, instead of intended 50u.

**Screenshots**

**Additional context**

**Comment by mirrorcult** [comment]
this is an issue with the max volume being both a datafield on stomachcomp and also a datafield on the solution being serialized, i guess the stomach one should just be removed
