### ISSUE TITLE
cant deconstuct rods near the airlocks

### ISSUE THREAD

**Issue by Tunguso4ka** [space-wizards/space-station-14#15105]
## Description
cant deconstuct rods near the external airlocks, nor with wirecutter, nor with RCD

**Reproduction**
1. place rods/tile near the external airlock
2. Try to deconstruct
3. Cargo cant dock their shuttle/evac docks to the cargo/evac spawns somewhere in the space

**Screenshots**
![зображення](https://user-images.githubusercontent.com/71643624/229499520-ea2aae2a-f812-4ea9-b6ea-451efa0bb9ba.png)

**Comment by keronshb** [comment]
Can't replicate. Is it on a specific station?


https://user-images.githubusercontent.com/54602815/229636132-c557a9f5-d586-406e-9b3c-5fa09262419d.mp4

**Comment by deltanedas** [comment]
it has to be a shuttle airlock specifically

**Comment by ElectroJr** [comment]
The issue is the airlocks extra fixture which extends beyond its own tile. The current method for checking if a tile is "blocked" by other entities for the sake of things like RCD or lattice cutting is very crude.
