### ISSUE TITLE
People that selected foxes during april fools are now orange

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#15118]
## Description

@vulppine wanted to test what happens when species are removed from code so heres an example i suppose

**Reproduction**

**Screenshots**

![image](https://user-images.githubusercontent.com/19853115/229660285-2f63f299-21b4-4d04-9d2c-27dd67c63a3b.png)

**Additional context**

**Comment by moonheart08** [comment]
Most SS13 servers separate parameters for different species in their save files.

**Comment by DrSmugleaf** [comment]
feature
