### ISSUE TITLE
Repairing window doafter is broken

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#15111]
## Description
Using a lit welder to attempt to repair a window starts the doafter but immediately cancels it.

**Reproduction**
1. Use lit welder on a damaged window to repair it.
2. watch how the doafter starts then immediately stops

**Comment by keronshb** [comment]
Unable to replicate, seems fixed?

https://user-images.githubusercontent.com/54602815/229634067-da03d999-a8b0-43d7-89bb-6dadc99edeb0.mp4

**Comment by Kayek14** [comment]
Sorry i didn't test it fully enough, seems to only happen on reinforced full widows oddly enough.

![image](https://user-images.githubusercontent.com/106507028/229640042-18a2ade6-6c0a-415c-be06-2a4624ea2a3f.png)

**Comment by keronshb** [comment]
You're right. Regular and thindows can be healed. Any reinforced one's can't. Thanks!
