### ISSUE TITLE
Placing a mime wall while driving a vehicle causes wacky collision behavior

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#15129]
## Description

**Reproduction**

Be on the jani vehicle
spawn a mime wall
funny stuff happens
**Screenshots**

**Additional context**

**Comment by keronshb** [comment]
You probably shouldn't be able to use mime wall if you're driving or in something.

**Comment by EmoGarbage404** [comment]
Doesn't it just need to use map coordinates rather than EntityCoordinates?

**Comment by keronshb** [comment]
> @keronshb then mime could wall the jani/cargonians on atvs to troll them

What does that have to do with the mime not being able to use a wall while riding on the cart?

**Comment by deltanedas** [comment]
well whats stopping the mime from moving hands in a wall shape while sitting on a cart, nothing really
