### ISSUE TITLE
fire shouldnt burn through hardsuits

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#15136]
## Description
the only thing that should be happening is you get baked alive rather than your flesh burned since theres a hardsuit in the way

**Reproduction**
1. be nukie
2. get flaregunned
3. you are now charred corpse, somehow

**Comment by keronshb** [comment]
> ## Description
> 
> the only thing that should be happening is you get baked alive rather than your flesh burned since theres a hardsuit in the way
> 
> **Reproduction**
> 
>     1. be nukie
> 
>     2. get flaregunned
> 
>     3. you are now charred corpse, somehow

Nukies in SS13 had a separate hardsuit (elite) so they could go hellfire. If it's not in here, it should be added. Default Nukie hardsuit shouldn't be fireproof.

**Comment by HoidC** [comment]
there's an elite hardsuit with better burn protection but only the medic gets it
