### ISSUE TITLE
RCD is broken 

### ISSUE THREAD

**Issue by Owencarpenter** [space-wizards/space-station-14#15166]
Only 2 things I’ve found that’s wrong with it currently but there big issues one you can use it infinitely as it goes into negatives and you can dismantle people instantly killing then and deleting there items works with lockers and everything in them.

**Comment by deltanedas** [comment]
holy shit real happened on master


https://user-images.githubusercontent.com/39013340/230267518-67f57b56-7add-4724-990d-0c6bbb555a8b.mp4
