### ISSUE TITLE
Janitor has a hard time cleaning specific "messes".

### ISSUE THREAD

**Issue by Owai-Seek** [space-wizards/space-station-14#15162]
## Description
Without space cleaner, (or a crowbar) janitors can't clean grimy tiles or spray-painted graffiti.

**Reproduction**
Be a janitor while people are mucking up the station.

**Screenshots**

**Additional context**

This wouldn't be much of an issue if it was easier to replace floor tiles, but it's currently a tedious, time consuming task to pry them up and replace them.

The same goes for Space Cleaner, it's tedious to get, doesn't have enough reach, and only gets 10 sprays before being empty. (Along with the examine text not showing how much you even have left.) That, and actually trying to spray graffiti is a crapshoot, it feels like 50% of the time, it doesn't even hit the thing I'm spraying at.

Slightly outside the scope, I can't seem to figure out how to mop things under tables, using the mop on the tile (even if clicking somewhere other than the table) causes me to put the mop -on- the table instead.

**Comment by OctoRocket** [comment]
I thought that mobs did that, by putting water on the floor with the mob and picking it back up. Maybe at some point it stopped working?

**Comment by deltanedas** [comment]
maybe cool solution is to use soap for cleaning decals, since you cant soak clothes in blood (yet) have doafter of a second or two for removing graffiti or barratrys tiles, space cleaner being a higher grade instant + aoe solution leaving soap as poor tider's tool
