### ISSUE TITLE
Traitors should be able to identify if a pen is of the explosive, hypo, or e-sword variety

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#15179]
## Description
If a traitor buys a surplus crate and gets a pen in it, they will have no way of identifying the pen at first glance. With the addition of exploring pens this can be quite leathal to the traitor. If they attempt to use it to investigate, and its the exploding pen, they will either waste it, or end up blowing themselves up.

**Additional context**
Yes I know this is a skill issue, but we should find a way to remedy this since new players might kill themselves and waste their traitor round unintentionally.

Some ideas:

We can have them spawn with removable labels.
We can allow traitors to be able to identify what variety they are by examining them.
Remove exploding pens from surplus crates.

**Comment by deltanedas** [comment]
could mayyybe be used to tatorcheck but ill see about adding a thing for telling traitors what an item really is when examined
