### ISSUE TITLE
shark toy is not insulated

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#15173]
## Description
what it says on the tin, leads to accidents
shouldnt trigger electrocution since while it is technically a weapon it doesnt do damage

**Reproduction**
1. go shonking everything!!!
2. run into maint
3. shonk the hv wire
4. ansdjsnfanf

**Comment by mirrorcult** [comment]
probably ignore melee attacks on electrified things if its doing 0 damage
