### ISSUE TITLE
Click sorting is still cooked

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#15175]
1. Mouseover multiple ents
2. Bottom ent is prioritised over top
3. Cry

**Comment by TemporalOroboros** [comment]
Probably requires a priority on spritecomponent that's updated when the sprite is drawn. Last sprite drawn on the latest frame in the 'highest layer' that overlaps with the mouse position should probably work.

**Comment by metalgearsloth** [comment]
We have clicksorting code to do it it just needs tweaking.
