### ISSUE TITLE
Geiger Counters make no noise

### ISSUE THREAD

**Issue by Fellowsinspace** [space-wizards/space-station-14#15180]
1. Grab Geiger Counter
2. Get near Radiation
3. See visual indication that there are rads on the Geiger counter
4. No clicks heard
5. No uranium Fever.Jpeg
6. Cry

**Comment by Kayek14** [comment]
Hmm i could have sworn that this was working just a few weeks ago, however it only made noise if you were holding it in your hand. 

Just checked and can confirm that it is making no noise either in hand, or out.

**Comment by themias** [comment]
It seems to be mispredicting. Looks similar to #15658

**Comment by lzk228** [comment]
fixed in #18282
