### ISSUE TITLE
throwing mice over lava ignites them

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#15199]
## Description
shouldnt happen since you are throwing them *over* lava not *through* it

**Reproduction**
1. get mouse
2. chuck him over dev map lava
3. he fire

**Video**

https://user-images.githubusercontent.com/39013340/230610913-947a01b3-eed2-481e-828b-e8457e31c253.mp4

**Comment by slarticodefast** [comment]
Tested it, seems to be fixed now.
