### ISSUE TITLE
Broken cable cuffs and zipties can't be put in trash bags

### ISSUE THREAD

**Issue by DummeHytteOst** [space-wizards/space-station-14#15200]
Broken cable cuffs and broken zipties are missing the trash tag

**Comment by Tyzemol** [comment]
If by broken cables you mean when cables get ripped up from the floor by explosions, I, as an engineer, would prefer janitors not trash all of those cables forcing me to go grab a fresh roll (if i can find them at all/they are not taken already)

**Comment by DummeHytteOst** [comment]
> If by broken cables you mean when cables get ripped up from the floor by explosions, I, as an engineer, would prefer janitors not trash all of those cables forcing me to go grab a fresh roll (if i can find them at all/they are not taken already)

i am talking about cable cuffs, that snaps after uncuffing someone which turns into broken cable
![image](https://user-images.githubusercontent.com/94384139/230647764-801f4e31-7c42-490f-aa73-0f320a28b816.png)
![image](https://user-images.githubusercontent.com/94384139/230647794-bf6319f3-fce8-44fb-9bc1-e72f23481b26.png)

**Comment by DummeHytteOst** [comment]
edited to make it hopefully more clear
