### ISSUE TITLE
cryoxadone doesn't work with cryo injection

### ISSUE THREAD

**Issue by Scribbles0** [space-wizards/space-station-14#15223]
## Description

okay so cryoxadone doesn't work when injected into the patient via the beaker slot in a cryotube but it does work via pill??

update: it works after taking the beaker out and putting it back in?? i don't know what's going on at this point

**Reproduction**

1. get into cryo tube that has cryoxadone beaker in it
2. cryoxadone doesn't heal you but it's being injected??

**Comment by Pangogie** [comment]
Fixed at some point.
