### ISSUE TITLE
You can't pick up folded chairs.

### ISSUE THREAD

**Issue by EmoGarbage404** [space-wizards/space-station-14#15229]
## Description

the event for not being able to pick them up probably does a handle check when it shouldn't.

**Comment by liltenhead** [comment]
What's weird is if you wrench them and unwrench them, you can pick it up after.

**Comment by EmoGarbage404** [comment]
are folding chairs anchorable??

**Comment by liltenhead** [comment]
I'm guessing (#14489) might be the reason. I can probably test to see in a little bit.
