### ISSUE TITLE
Milk jugs shatter like glass

### ISSUE THREAD

**Issue by EmoGarbage404** [space-wizards/space-station-14#15230]
## Description

0/10 inauthentic milk experience

**Comment by Myakot** [comment]
Should be closed by #15250

**Comment by scrivoy** [comment]
Hi everyone,
I’ve checked the issue and I'm unable to reproduce it.
Could it be that the bug has already been fixed, but the issue hasn’t been closed yet?

**Comment by lzk228** [comment]
https://github.com/user-attachments/assets/e05aa87c-2bf8-4224-80d2-a5aa11320aed

**Comment by scrivoy** [comment]
Yeah, exactly the same for me.
And also for the other packages like Soy Milk.
