### ISSUE TITLE
Some idiot broke power 

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#1525]
https://github.com/space-wizards/space-station-14/pull/1515

Looks like it was this pr. FIXITFIXITFIXITFIXITFFIXITF

**Comment by collinlunn** [comment]
e#1196 should have fixed this

**Comment by DrSmugleaf** [comment]
> e#1196 should have fixed this

Need to update the submodule.

**Comment by DrSmugleaf** [comment]
Fixed by https://github.com/space-wizards/RobustToolbox/pull/1196 and https://github.com/space-wizards/space-station-14/commit/835940c4be05ff687f94da451669924b90908b47
