### ISSUE TITLE
artifact foam not spreading over puddles

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#15269]
## Description
something i found with an artifact last round, when it made funny foam it would only be 1 tile

possibilities:
A) the trigger only has enough foam for 1 tile, very odd
B) this has been fixed in master
C) brokey!!!!

I will test on master now

**Reproduction**
1. get artifact
2. spill water
3. end round, good chance of foam
4. probably 1 tile

OR THE BETTER WAY I HAVE NOT YET TESTED
1. blow up water tank
2. mix foaming agent and water in beaker or on the puddle
3. observe

**Screenshots**
![12:20:42](https://user-images.githubusercontent.com/39013340/230893758-111077e2-efa7-416c-93d5-321ef9304311.png)

**Comment by metalgearsloth** [comment]
Either connecting nodes or getneighbors on spreadersystem, one of the two.

**Comment by deltanedas** [comment]
![12:45:36](https://user-images.githubusercontent.com/39013340/230895589-7251cb77-4ebf-41fa-b670-b06ed78b9f40.png)

does not happen with beaker on master, either artifact foam brokey or was fixed entirely

**Comment by deltanedas** [comment]
![12:47:03](https://user-images.githubusercontent.com/39013340/230895810-6c198b41-7ace-4a34-8515-6b33645d63a3.png)
ok yes a bunch of artifacts on same tile only doing 1 tile foam when round ended
