### ISSUE TITLE
Cant slip on the space lube

### ISSUE THREAD

**Issue by Tunguso4ka** [space-wizards/space-station-14#15279]
## Description
space lube lost its magic slippery power.

**Reproduction**
1. get the Space Lube
2. spill it on the ground
3. no funny

**Screenshots**

https://user-images.githubusercontent.com/71643624/230947993-a5d07a6b-dd23-4d79-80ec-e4c6c698be03.mp4

**Comment by Tunguso4ka** [comment]
Interesting fact, adding water to the puddle returns space lube powers to slip everything.

**Comment by OctoRocket** [comment]
This seems to also happen when filling a container directly from a chem dispenser, such as filling a bucket with oxygen or mercury. This is fixed upon mixing it with another chemical it seems.

**Comment by Tunguso4ka** [comment]
fixed by https://github.com/space-wizards/space-station-14/pull/15442
