### ISSUE TITLE
Reinforcement teleporter goonie gets stuck in Arrivals

### ISSUE THREAD

**Issue by Myakot** [space-wizards/space-station-14#15271]
## Description
If you buy the reinforcement kit in Arrivals as Syndie (essentially to make a plan, yatta-yatta) - your summoned goon can't leave Arrivals without admin intervention.

**Reproduction**
- Spawn a ghost role using reinforcement teleporter
- Try to leave via Arrivals

**Comment by deltanedas** [comment]
this would likely apply to cerberus and holos as well
