### ISSUE TITLE
wringing mop sometimes overfills the container

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#15280]
## Description
sloth jani overhaul broke something i presume
i had a metamorphic glass with 60/30 from it

**Reproduction**
1. get mop full of water
2. mop up a bunch of blood til its nearly fully blood
3. wring into a glass full of water
4. overfills somehow and the mop has like 3u of water in it

**Screenshots**
i emptied the glass before i could screenshot it pro

**Comment by EmoGarbage404** [comment]
just for some reference, if the code uses the method on the solution class directly, it won't check for overflow. Using solutionmanagersystem methods will respect solution limits.

**Comment by deltanedas** [comment]
![17:41:29](https://user-images.githubusercontent.com/39013340/230948500-f5032442-6d90-4176-8fbd-6dbb44d472ca.png)

**Comment by deltanedas** [comment]
ok so repro is if your mop goes from this
![17:42:36](https://user-images.githubusercontent.com/39013340/230949046-abee487d-cafd-4a04-8f55-a27175ddda5e.png)
to this
![17:44:43](https://user-images.githubusercontent.com/39013340/230949049-b16536a6-29f5-42a3-be7c-feb2d9bee04d.png)
it will overfil
