### ISSUE TITLE
Player overlay is no longer working properly

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#15338]
## Description
Player overlay is not showing up on all players properly. Some only show their ckey, while others have no overlay at all.

**Reproduction**
1. Enable adminbus.

2. Toggle player overlay.

**Comment by freeman2651** [comment]
reupping this issue that now it doesn't work at all, I can't seem to get the overlay to work under any circumstance, even after readmin or deadmining

**Comment by ElectroJr** [comment]
One of my changes broke it, but should be fixed soon

**Comment by ElectroJr** [comment]
Actually apparently this GH issue is apparently much older than my recent changes, so there may also be some other issue.

**Comment by Kayek14** [comment]
This issue is resolved.
