### ISSUE TITLE
If you shoot while inside the medical scanner, you can kill yourself

### ISSUE THREAD

**Issue by exp111** [space-wizards/space-station-14#1534]

**Comment by metalgearsloth** [comment]
We seem to have the opposite problem now where you can shoot out of the scanner like a tank.

**Comment by SweptWasTaken** [comment]
Still an issue. It causes a debug exception on debug now.

**Comment by AJCM-git** [comment]
Doesn't kill you anymore

https://user-images.githubusercontent.com/60196617/140628338-17ca4bd4-78f6-45c8-b5c2-8ccf6c6f13c6.mp4
