### ISSUE TITLE
Preferences DB concurrency problems due to single DB context

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/space-station-14#1538]
Right now the preferences database keeps a single DB context around. On top of being discouraged by the EFCore documentation, this means we can only execute a single query at the same time (EFCore contexts are not thread safe) which is very problematic for EU servers since theres 150+ms of RTT.

**Comment by nok-ko** [comment]
Long been fixed, quoth PJB.

**Comment by PJB3005** [comment]
Long fixed.
