### ISSUE TITLE
Sprites bigger than 32x32 do not display well in right click menu icons.

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#1540]
![image](https://user-images.githubusercontent.com/49448379/88865222-d7266880-d1f6-11ea-8853-9a07eb848ced.png)

**Comment by juliangiebel** [comment]
That's fixed. This issue can be closed now.

![grafik](https://user-images.githubusercontent.com/8915246/165359967-448f4e29-ad61-4e0d-9933-4e1f0a3f400a.png)
