### ISSUE TITLE
Staff of healing doesn't heal bleeding and blood level

### ISSUE THREAD

**Issue by Kerbiat** [space-wizards/space-station-14#15413]
## Description
Staff of healing that you can spawn in sandbox doesn't heal bleeding and blood level.

**Additional context**
Staff of healing is quite easy to use to heal entities in sandbox mode. Though i need to treat bleeding and blood level separately. Not very convenient.

**Comment by EmoGarbage404** [comment]
just use the rejuvenate command?

**Comment by deltanedas** [comment]
or even the verb which is a bit faster

**Comment by mirrorcult** [comment]
its not supposed to heal bleeding, if you're trying to heal entities in sandbox just use rejuvenate
