### ISSUE TITLE
Suit sensors doesn't work if late joined

### ISSUE THREAD

**Issue by Kerbiat** [space-wizards/space-station-14#15412]
## Description
Bug. If you arrive late on station your suit sensor breaks. Crew monitor and handheld crew monitor don't show people who late joined. Fix is to change your suit to a new one. Only suit that you wore when arriving is broken.

**Reproduction**
Arrive late on station. Turn your suit sensors. You will not be shown on crew monitor. Get new suit and turn suit sensor on and you will be shown on crew monitor.

**Additional context**
I guess this is not the most important bug, but running around and making every late joined person get a new suit is time consuming.

**Comment by OctoRocket** [comment]
This is quite terrible so uh, if it could be fixed soon that would be nice

**Comment by deltanedas** [comment]
this still happens as of right now on lizard
![12:16:51](https://github.com/space-wizards/space-station-14/assets/39013340/5f79f317-f3f3-45bb-ba4f-8247a6b9a57a)


no mark o zack
![12:17:04](https://github.com/space-wizards/space-station-14/assets/39013340/96fcdd73-416d-4626-b399-1c394832120a)
