### ISSUE TITLE
Latejoiners should spawn on the arrivals shuttle

### ISSUE THREAD

**Issue by GoodWheatley** [space-wizards/space-station-14#15411]
We have the technology to kick AFKers off the shuttle, and forcing everyone to spawn at the arrivals station inevitably leads to having to stand around waiting for the shuttle for no real gameplay benefit. Having latejoiners spawn on a shuttle actively traveling to the station (with latejoins in quick succession spawning in on the same shuttle) maintains the immersion of actually arriving at the station while getting rid of the anti-mechanic of standing around waiting for the shuttle to arrive.

**Comment by deltanedas** [comment]
pretty sure thats a mapping issue, use the arrivals airlocks

**Comment by potato1234x** [comment]
i agree, and with the shuttle sound attenuation being reduced, most of the time i just miss the shuttle and have to wait another 5 minutes
