### ISSUE TITLE
[BUG] Multitool priority on doors

### ISSUE THREAD

**Issue by Myakot** [space-wizards/space-station-14#15450]
## Description
Multitool prioritises linking the door with an open maintenance panel, over opening the wire menu.

**Reproduction**
1. Use a screwdriver on a door
2. Click the ready-to-be-hacked-door with a multitool
3. See that it just links it, instead of opening UI
4. Use wirecutters on the door - menu opens
5. Can use multitool now, with wire-UI open

**Screenshots**
![image](https://user-images.githubusercontent.com/30875116/232290791-db42f2bf-d25d-41bb-825a-01c9d599132a.png)

**Comment by deltanedas** [comment]
you can also use E with multitool in hand to open the panel

**Comment by QuietlyWhisper** [comment]
using wirecutters also opens ui, this is simply a selection choice preference issue, not really a bug
