### ISSUE TITLE
Cannot unbuckle people from Janicart

### ISSUE THREAD

**Issue by Owai-Seek** [space-wizards/space-station-14#15462]
## Description

Cannot unbuckle people from the janicart, which if someone is in crit, can result in death due to the cart itself being too heavy/slow to move.
**Reproduction**

Buckle someone to the cart. Try to unbuckle. Scream in despair.

**Screenshots**

![Content Client_lF7FlqDhIL](https://user-images.githubusercontent.com/7543955/232345140-9cacc705-36cd-459c-8f05-59a2614e36e6.gif)
**Additional context**

**Comment by deltanedas** [comment]
happens for any vehicle

only 3 ways i know of to do it:
- stunbaton/disabler
- stamcrit from shove
- forcing player to vault a table

**Comment by Partmedia** [comment]
This seems to have been intended in the comment in `Content.Shared/Buckle/SharedBuckleSystem.Buckle.cs`:

```
            // If the strap is a vehicle and the rider is not the person unbuckling, return.
            if (TryComp<VehicleComponent>(strapUid, out var vehicle) &&
                vehicle.Rider != userUid)
                return false;
```

**Comment by Pangogie** [comment]
Vehicles removed awaiting better implementation.
