### ISSUE TITLE
Need a "jump-to-mob" command

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#15474]
## Description

/jumptomob "Entity name" 
Tpto only takes entityid and that smelly, need an ui for too
**Reproduction**

**Screenshots**

**Additional context**

**Comment by QuietlyWhisper** [comment]
You could make this, but I don't see it being useful as multiple entities have the same name?
If you want to teleport to a player, there is a command for that if that's what you were getting at
