### ISSUE TITLE
Meat kudzu spread might be too fast

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#15492]
## Description

Seems to be very difficult to handle this days, ontop of the touch damage
**Reproduction**

**Screenshots**

**Additional context**

**Comment by tom-leys** [comment]
Perhaps some better ways to handle it:

- Grows much slower in vacuum or a cold environment
- Takes damage from a hot or high pressure environment 

So space a section to slow the meat kudzu if you want to fight it. Then prepare a plasma bomb to clear it out.

Perhaps to slow it down / make it more interesting

- Feeding mechanic, where kudzu tiles have calories and need to feed (digest bodies / food sources) to get calories for growth. 
- Kudzu starts with a high initial calorie count 
- Kudzu naturally digests meat created by anamoly and food from say botany / kitchen digestion
- Calories used for growth

**Comment by metalgearsloth** [comment]
Smoke refactor got this I think
