### ISSUE TITLE
Mercury and Toxin have the exact same effects (Toxin needs buff)

### ISSUE THREAD

**Issue by Synthestra** [space-wizards/space-station-14#15494]
The only difference is that Toxin costs 8tc and will get you arrested/permad if caught. Toxin needs a buff.

**Comment by HoidC** [comment]
how do you buy toxin?

**Comment by Scribbles0** [comment]
> how do you buy toxin?

emag chem dispenser

**Comment by Interrobang01** [comment]
The best solution to this issue is just to remove toxin. Let's be honest, no matter how powerful, generic, or balanced you make it, naming a toxin "toxin" is inane. At least rename it to something cool and familiar like Arsenic or Cyanide.
