### ISSUE TITLE
Space Ninja Suit's abilities don't work unless you are marked as a Space Ninja Antag

### ISSUE THREAD

**Issue by LordEclipse** [space-wizards/space-station-14#15502]
## Description
On the tin, I don't know if this is intended behavior, but it will always say there "isn't enough charge in the suit" no matter what type of battery you insert.

**Reproduction**
1. Spawn in an Urist
2. Set Outfit to Space Ninja
3. Control Urist, 
4. You will notice that none of the abilities work
5. Give Urist Space Ninja antag
6. Abilities work

**Screenshots**

https://user-images.githubusercontent.com/106132477/232649493-7e0bbdbb-32eb-4501-bc34-a90698cc5aaa.mp4

I tested this live

**Comment by QuietlyWhisper** [comment]
Probably not hreat for sandbox scenarios, but for live games it's pretty good mechanic. It was intentionally coded like that so crew don't take the gear to use it. iirc all the abilities from the gloves and katana wont work either for the same reason.

**Comment by LordEclipse** [comment]
> Probably not hreat for sandbox scenarios, but for live games it's pretty good mechanic. It was intentionally coded like that so crew don't take the gear to use it. iirc all the abilities from the gloves and katana wont work either for the same reason.

I see, is this tied to any one component? What does the suit look for to work?

**Comment by deltanedas** [comment]
the urist needs the SpaceNinjaComponent, which the antag ctrl adds. as whisper said, its done so the crew cant rob a ninja and use the gear

you can also create a ghost role spawner somewhere if thats what you are trying to do
