### ISSUE TITLE
You can't extinguish yourself with a fire extinguisher

### ISSUE THREAD

**Issue by asperger-sind** [space-wizards/space-station-14#15501]
## Description

Title, you can't do it even if you use it and walk into the fire extinguisher spray or do it against a wall.

**Reproduction**

1. Fire extinguisher.
2. Get lit on fire.
3. Attempt to extinguish yourself.
4. Fail miserably and burn to death.

**Comment by deltanedas** [comment]
you can probably do this by attacking yourself with a cup of water

**Comment by asperger-sind** [comment]
i just realized i made this issue before and this is a dupe lmao
