### ISSUE TITLE
we should move station specific jobs to their own tab in role select

### ISSUE THREAD

**Issue by Emisse** [space-wizards/space-station-14#15500]
less confusion, say what stations theyre available on, etc

**Comment by VasilisThePikachu** [comment]
My idea is to have a tab with all station specific jobs all there. The description of the job will say what stations they exist in

OR have a tab for every station with specific jobs

**Comment by VasilisThePikachu** [comment]
Also any way to know what jobs are special to what maps? or do i need to manually find out
