### ISSUE TITLE
Mapped drinks don't become metamorphic glasses when empty

### ISSUE THREAD

**Issue by potato1234x** [space-wizards/space-station-14#15527]
## Description

Drinking a mapped glass of liquid wont turn it into a metamorphic glass as it probably should.

**Reproduction**

1. drink a mapped/spawned in drink
2. it stays visually full but is empty

**Comment by Emisse** [comment]
we could maybe just parent all these drinks to MetamorphicGlass

**Comment by potato1234x** [comment]
fixed by #25134
