### ISSUE TITLE
Loneop mapped hardsuit in shuttle has no helmet?

### ISSUE THREAD

**Issue by QuietlyWhisper** [space-wizards/space-station-14#15533]
## Description

the loneop shuttle has a mapped hardsuit that does not have a helmet when equipped. The loneop does spawn with their own hardsuit, however, reinforcements cannot utilize the hardsuit fully.

**Reproduction**
Spawn shuttle via event
equip provided hardsuit
no helmet

**Comment by Emisse** [comment]
mapped hardsuits in general dont have helmets because the toggleable helmet component isnt serialized

**Comment by deltanedas** [comment]
it works for deathsquad/ert hardsuits on centcom tho so that can be right

**Comment by Emisse** [comment]
check map file

**Comment by QuietlyWhisper** [comment]
this map was updated to contain a hardsuit locker thingy
