### ISSUE TITLE
APC access is toggled whenever the UI is opened

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#15563]
Looks like this PR https://github.com/space-wizards/space-station-14/pull/14258 does some cursed things. If person A opens the APC UI and then person B opens it it only considers person B's access which should not be handled like this. Ideally the access is only shown visually on the client and all the server does is validate the input.

**Comment by Winkarst-cpu** [comment]
Not a problem anymore since only one person can use the APC now?...
![изображение](https://github.com/user-attachments/assets/789ccf00-0883-48f3-bac3-92860dcde0b3)
