### ISSUE TITLE
Humans collide with each other when pulling them

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#1557]
![Peek 2020-08-01 03-15](https://user-images.githubusercontent.com/6766154/89090832-ab95b080-d3a5-11ea-957e-f980d80d5f81.gif)

**Comment by DrSmugleaf** [comment]
This only happens with non player controlled humans, as the collision flag is not disabled until someone controls them.

**Comment by SweptWasTaken** [comment]
Closing this to concatenate into #2387
