### ISSUE TITLE
foam has ~half range

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#15594]
## Description
basically the range of foam from mixing fluorosurfactant and water seems to have halved
im getting, anecdotally, 15u worth of foam from 30u of fluorosurfactant
using 15u which was basically the gold standard before ??? (i assume spreader stuff) gives tiny foam
30u is needed to give the previous 15u yeah see screenshots

**Reproduction**
1. make grenade to troll loneop
2. realise it has no range
3. die

**Screenshots**
15u
![21:58:27](https://user-images.githubusercontent.com/39013340/233486932-8ada98d2-e1ed-4b22-9063-903322d0da26.png)

30u, has roughly same range as old 15u
![22:00:07](https://user-images.githubusercontent.com/39013340/233486925-4d76dfd9-264b-4696-9b75-73e6ce39c39a.png)

100u, pretty much same as before
![21:59:17](https://user-images.githubusercontent.com/39013340/233486936-26e02747-d9ac-4679-bb72-5476dc67e54d.png)

**Comment by Synthestra** [comment]
is this the same case for foaming agent?

**Comment by deltanedas** [comment]
havent tested the metal foam reaction
