### ISSUE TITLE
Barratry/Detroit announcements are wierd sometimes

### ISSUE THREAD

**Issue by VasilisThePikachu** [space-wizards/space-station-14#15590]
Was this on ~~detroit~~ baretry? i always experience wierd announcement bugs on it in general

_Originally posted by @VasilisThePikachu in https://github.com/space-wizards/space-station-14/issues/15505#issuecomment-1516063063_

Thought this deserved its own issue.

Things i noticed at least once:
Announcements console messages do not show up on the person that sent the announcement and some people. This was persistent and i probably have video somewhere

Nuke announcement does not play, neither do the lights react. You will learn of your doom by the nuke music. Happened once to me as sec. No other sec had heard too

I have only noticed these on Barratry

**Comment by VasilisThePikachu** [comment]
maybe fixed by #16702

**Comment by Vordenburg** [comment]
We've had a similar issue with the Angle map on Nyanotrasen. If anything, the culprit may be `GetInStation` from `StationSystem.cs`. However I haven't looked into this too thoroughly. #16702 might fix the nuke announcement but probably not console announcements.

**Comment by deltanedas** [comment]
yeah while working on it i changed announcements to use the nukes thing and it was fucky so i undid it
