### ISSUE TITLE
license.txt files need be converted to RGA/yml

### ISSUE THREAD

**Issue by ElectroJr** [space-wizards/space-station-14#15607]
Each of these files just need to be converted into an `attributions.yml` file. For an example file, see [ Resources/Audio/Items/attributions.yml](https://github.com/space-wizards/space-station-14/blob/master/Resources/Audio/Items/attributions.yml). Instead of opening one giant PR, this issue should be fixed by several smaller PRs (e.g., one per category/folder).

- [x] [ Resources/Audio/Misc/license.txt](https://github.com/space-wizards/space-station-14/blob/master/Resources/Audio/Misc/license.txt)
- [x] [ Resources/Audio/Items/license.txt](https://github.com/space-wizards/space-station-14/blob/master/Resources/Audio/Items/license.txt)
- [x] [ Resources/Audio/Animals/license.txt](https://github.com/space-wizards/space-station-14/blob/master/Resources/Audio/Animals/license.txt)
- [x] [ Resources/Audio/Ambience/license.txt](https://github.com/space-wizards/space-station-14/blob/master/Resources/Audio/Ambience/license.txt)
- [x] [ Resources/Audio/Machines/license.txt](https://github.com/space-wizards/space-station-14/blob/master/Resources/Audio/Machines/license.txt)
- [x] [ Resources/Audio/Voice/Talk/license.txt](https://github.com/space-wizards/space-station-14/blob/master/Resources/Audio/Voice/Talk/license.txt)
- [x] [ Resources/Audio/Voice/Human/license.txt](https://github.com/space-wizards/space-station-14/blob/master/Resources/Audio/Voice/Human/license.txt)
- [x] [ Resources/Audio/Weapons/Xeno/license.txt](https://github.com/space-wizards/space-station-14/blob/master/Resources/Audio/Weapons/Xeno/license.txt)
- [x] [ Resources/Audio/Announcements/license.txt](https://github.com/space-wizards/space-station-14/blob/master/Resources/Audio/Announcements/license.txt)
- [x] [ Resources/Audio/Items/Medical/license.txt](https://github.com/space-wizards/space-station-14/blob/master/Resources/Audio/Items/Medical/license.txt)
- [x] [ Resources/Audio/Voice/Skeleton/license.txt](https://github.com/space-wizards/space-station-14/blob/master/Resources/Audio/Voice/Skeleton/license.txt)
- [x] [ Resources/Audio/Effects/Vehicle/license.txt](https://github.com/space-wizards/space-station-14/blob/master/Resources/Audio/Effects/Vehicle/license.txt)
- [x] [ Resources/Audio/Items/Handcuffs/license.txt](https://github.com/space-wizards/space-station-14/blob/master/Resources/Audio/Items/Handcuffs/license.txt)
- [x] [ Resources/Audio/Voice/Reptilian/license.txt](https://github.com/space-wizards/space-station-14/blob/master/Resources/Audio/Voice/Reptilian/license.txt)
- [x] [ Resources/Audio/Ambience/Objects/license.txt](https://github.com/space-wizards/space-station-14/blob/master/Resources/Audio/Ambience/Objects/license.txt)
- [x] [ Resources/Audio/Effects/Diseases/license.txt](https://github.com/space-wizards/space-station-14/blob/master/Resources/Audio/Effects/Diseases/license.txt)
- [x] [ Resources/Audio/Ambience/Temporary/license.txt](https://github.com/space-wizards/space-station-14/blob/master/Resources/Audio/Ambience/Temporary/license.txt)
- [x] [ Resources/Audio/Weapons/Guns/Gunshots/license.txt](https://github.com/space-wizards/space-station-14/blob/master/Resources/Audio/Weapons/Guns/Gunshots/license.txt)
- [x] [ Resources/Audio/Announcements/RoundEnd/license.txt](https://github.com/space-wizards/space-station-14/blob/master/Resources/Audio/Announcements/RoundEnd/license.txt)
- [x] [ Resources/Audio/Magic/licenses.txt](https://github.com/space-wizards/space-station-14/blob/master/Resources/Audio/Magic/licenses.txt)
- [x] [ Resources/Audio/Effects/licenses.txt](https://github.com/space-wizards/space-station-14/blob/master/Resources/Audio/Effects/licenses.txt)
- [x] [ Resources/Audio/Weapons/licenses.txt](https://github.com/space-wizards/space-station-14/blob/master/Resources/Audio/Weapons/licenses.txt)
- [x] [ Resources/Audio/Effects/Cargo/licenses.txt](https://github.com/space-wizards/space-station-14/blob/master/Resources/Audio/Effects/Cargo/licenses.txt)
- [x] [ Resources/Audio/Effects/Shuttle/licenses.txt](https://github.com/space-wizards/space-station-14/blob/master/Resources/Audio/Effects/Shuttle/licenses.txt)
- [x] [ Resources/Audio/Effects/Weather/licenses.txt](https://github.com/space-wizards/space-station-14/blob/master/Resources/Audio/Effects/Weather/licenses.txt)
- [x] [ Resources/Audio/Effects/Lightning/licenses.txt](https://github.com/space-wizards/space-station-14/blob/master/Resources/Audio/Effects/Lightning/licenses.txt)
- [x] [ Resources/Audio/Weapons/Guns/Hits/licenses.txt](https://github.com/space-wizards/space-station-14/blob/master/Resources/Audio/Weapons/Guns/Hits/licenses.txt)
- [x] [ Resources/Audio/Weapons/Guns/Misc/licenses.txt](https://github.com/space-wizards/space-station-14/blob/master/Resources/Audio/Weapons/Guns/Misc/licenses.txt)
- [x] [ Resources/Audio/Weapons/Guns/Miss/licenses.txt](https://github.com/space-wizards/space-station-14/blob/master/Resources/Audio/Weapons/Guns/Miss/licenses.txt)
- [x] Bonus issue: fix `emergency_meeting.ogg` licence (or just remove the effect altogether)

**Comment by VasilisThePikachu** [comment]
Question regarding attributions.yml in misc audio

emergency_meeting.ogg is claimed to be taken from tg station and licensed by CC-BY-NC-SA-3.0

Though from what i can hear [this is coming from among us and a bit cut ](https://www.youtube.com/watch?v=gVylTS6Y1Bs)

Unless this audio is copyright free then can we even use this?

**Comment by deltanedas** [comment]
among us has its own fan creation license thing somewhere

**Comment by ElectroJr** [comment]
Its probably just incorrectly attributed and the `CC-BY-NC-SA-3.0` just seems arbitrary. So it either needs to be fixed or replaced altogether if we can't use it. IIRC someone did email inner sloth at some point to ask if we could use some art/sprites and they were cool with that, but I don't remember the specifics & I have no idea if that extends to short audio clips like this.

**Comment by Emisse** [comment]
It was not specified to extend to audio clips, the clip needs to be removed until we can get proper attribution.

**Comment by HighTechPuddle** [comment]
I will do this one after school. So I just convert and format all the licenses.txt files to attributions.yml right?
