### ISSUE TITLE
Cow bricks the biomass machine.

### ISSUE THREAD

**Issue by Owai-Seek** [space-wizards/space-station-14#15621]
## Description
On round 23886 I tried to stick a cow in the biomass machine, said machine seemed to run indefinitely until an admin deleted and replaced it, it never produced any biomass.

**Reproduction**
Stick cow in biomachine, it's now haunted forever.

**Screenshots**

**Additional context**

**Comment by Slava0135** [comment]
It just takes very long time, and it produces 200 biomass

**Comment by QuietlyWhisper** [comment]
Yeah it's simply extremely long, biomass reclaimer time and produce is based on mass
