### ISSUE TITLE
Character preview in lobby doesn't show unless you click save

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#15649]
## Description

**Reproduction**

![image](https://user-images.githubusercontent.com/43253663/233774153-e2cebde0-f4c8-4937-a86d-41d7b657155c.png)
after clicking save
![image](https://user-images.githubusercontent.com/43253663/233774165-17320c88-9c91-4c1f-b4d3-d34eaa2c37e2.png)

**Screenshots**

**Additional context**

**Comment by deltanedas** [comment]
dupe of #13067

**Comment by metalgearsloth** [comment]
Fixed in https://github.com/space-wizards/RobustToolbox/pull/4065
