### ISSUE TITLE
item cooldown visuals break sometimes

### ISSUE THREAD

**Issue by Slava0135** [space-wizards/space-station-14#15651]
## Description

![Peek 2023-04-22 12-10](https://user-images.githubusercontent.com/40753025/233774969-8196dd37-32d0-4826-8865-01ff6f660413.gif)
**Reproduction**

No idea how to reproduce it 100% of time, just use some item with cooldown multiple times. It often breaks when using bible.
**Screenshots**

**Additional context**

**Comment by deltanedas** [comment]
ive had this happen with bike horn before too, thought it got fixed
