### ISSUE TITLE
thindows have wrong collision

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#15666]
## Description
for some reason thindows, at bridge on aspid at least, have a circle in the middle of the tile as hitbox

**Reproduction**
1. walk up to bridge
2. sus

**Screenshots**
hitbox drawn on, approximately correct
![02:52:22](https://user-images.githubusercontent.com/39013340/233815195-d3addec1-9622-4d2d-b1c3-4568354a2856.png)

**Comment by Scribbles0** [comment]
seems to happen with railings as well

**Comment by metalgearsloth** [comment]
Might be https://github.com/space-wizards/RobustToolbox/pull/3958 or https://github.com/space-wizards/RobustToolbox/pull/3957 but need to confirm

**Comment by metalgearsloth** [comment]
![image](https://user-images.githubusercontent.com/31366439/233819949-112e7646-1b7d-4b09-bd7d-67092423c56c.png)

oh yeah it was quickhull for sure.
