### ISSUE TITLE
Item dropping mispredicts

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#15676]
Probably 1/4 of the time when you drop an item you can see it flicker for a frame. It's probably some specific transform ordering code or the likes in engine but not entirely sure.

I'm also not entirely sure when it started but bisecting it shouldn't be hard.

**Comment by ElectroJr** [comment]
The issue appears to have something to do with interpolation or pickup animations when dropping items near the centre of grids. Sometimes it appears to be trying to lerp towards the grid, other times it seems to be animating a drop starting from the grid?

See the video in https://github.com/space-wizards/RobustToolbox/pull/3963

**Comment by Menshin** [comment]
Somehow related #15664 .

Can confirm the client is doing the dropping/inserting reconciliation dance a few time before actually dropping the item.
