### ISSUE TITLE
You can drag potted plants through airlocks

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#15680]
## Description
While dragging potted plants you can phase them through airlocks.

**Reproduction**
drag a potted plant and use the drag keybind to shove it into an airlock

**Screenshots**
![image](https://user-images.githubusercontent.com/106507028/233822482-75ec2aca-9b53-487e-83a1-8392b742db64.png)

**Comment by metalgearsloth** [comment]
Dupe https://github.com/space-wizards/space-station-14/issues/15332
