### ISSUE TITLE
Examine verb opens window "That entity doesn't exist"

### ISSUE THREAD

**Issue by exp111** [space-wizards/space-station-14#1568]
If you examine a entity that's out of range (a wall behind some others walls).
The shortcut (Shift + Left click) just doesn't open any window.
![grafik](https://user-images.githubusercontent.com/17885980/89102925-0f53c400-d40e-11ea-8a08-83fb38a324e1.png)

**Comment by SweptWasTaken** [comment]
Can't reproduce.
