### ISSUE TITLE
marathon telecomms not enough power

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#15704]
## Description
it only makes 3kw which isnt near enough for it

make it a uranium gen

**Reproduction**
1. be on marathon, solar gaming
2. telecomms dies
3. spend 20 minutes trying to find it since some idiot called comms a satellite when its 4 meters away from the airlock and youre flying around space looking for it
4. cross wire done

**Comment by Emisse** [comment]
ill fix this next updates

**Comment by Emisse** [comment]
fixed
