### ISSUE TITLE
You can only make one traitor with the antag panel

### ISSUE THREAD

**Issue by keronshb** [space-wizards/space-station-14#15710]
## Description

The antag panel won't let you make another traitor if you made one already. Might be per person since I could only test solo.

**Reproduction**

Repo 1:
Antag Panel > Make Traitor (self), control another mob then try to make that new mob into a traitor.

Antag Panel > Make yourself a nukie or a pirate, then try to make yourself a traitor.

**Screenshots**

**Additional context**

**Comment by deltanedas** [comment]
you can only do it once iirc, and it persists with mind so controlling wont work

**Comment by keronshb** [comment]
> you can only do it once iirc, and it persists with mind so controlling wont work

In comparison you can make someone a nukie a bunch of times or a pirate. Maybe this might need to be part of the mind refactor.

**Comment by deltanedas** [comment]
when refactoring should also change it e.g. if turning a syndie into a nukie they should lose syndie tasks probably

**Comment by tom-leys** [comment]
@keronshb As a true beginner I had a look at this. Here are a few issues.

1. Not familiar with admin tools. Where do I find the "Antag Panel" ?
2. A text search for "Antag panel" does not show up in the codebase. What is the actual (non abbreviated name) for this panel?
3. I could only find a way to make a user into an antag by right clicking on them and under admin. Is this what you meant?
4. Where is the code which defines menus and panels like this?
5. Can you point me to a .cs file which defines some part of the "Antag Panel" ?

Thanks

**Comment by DogZeroX** [comment]
I think they mean antag control, right click on a humanoid as an admin, you will see antag ctrl

**Comment by deltanedas** [comment]
i found a funny crash on debug where it tried to get prototype "traitor" and not "Traitor", could possibly be related (putting in uplink implant because yes)

**Comment by tom-leys** [comment]
@deltanedas was correct. That was the only bug (I'll submit a PR).

Can now 
1. Make self a mutie
2. Make self a traitor (hear sound effect & see instructions in log)
3. Create another entity (I used an ERT Janitor)
4. Make it a traitor
5. Take it over
6. Make it a nukie
7. Make it a traitor AGAIN (See instructions again)
