### ISSUE TITLE
Coordinates, Ticks, and allocation should not be visible to the player

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#15717]
## Description

Only to admins
**Reproduction**

**Screenshots**

![image](https://user-images.githubusercontent.com/43253663/233881407-bf705f89-f39e-43e8-844d-bcb1427dba7c.png)
![image](https://user-images.githubusercontent.com/43253663/233881415-7ecefe78-6357-4059-8fcb-07bd92bdd773.png)
![image](https://user-images.githubusercontent.com/43253663/233881421-f4a63609-cf94-40b5-ba63-c1b9b4a74884.png)

**Additional context**

**Comment by deltanedas** [comment]
ticks being visible is important since if its consitently -0.4 or so then i know that servers dying and its not just my internet

**Comment by lzk228** [comment]
fixed
