### ISSUE TITLE
Health analyzer DebugAssertException on use

### ISSUE THREAD

**Issue by Tyzemol** [space-wizards/space-station-14#15734]
## Description
Using a health analyzer throws an exception.
Glancing at the wall of text spit in console i think it has something to do with the PR #15373 adding battery cost to using a health analyzer.

**Reproduction**
Use health analyzer on the DEBUG build of the server, i found no problems using it on the RELEASE build.

**Additional context**
[exception.txt](https://github.com/space-wizards/space-station-14/files/11309465/exception.txt)
I have checked other handheld stuff that was modified to run on batteries in the PR mentioned above (handheld map and crew monitor), they don't throw an exception, but don't use battery power either (which i will write as a separate issue if i'm not lazy)

**Comment by tom-leys** [comment]
I've solved this. `PowerCellSystem::TryUseCharge` was not passing the battery's UID into `BatterySystem::TryUseCharge`

**Comment by EmoGarbage404** [comment]
There is a fix pr up already
