### ISSUE TITLE
Blood bags are broken.

### ISSUE THREAD

**Issue by Owai-Seek** [space-wizards/space-station-14#15737]
## Description
Can't use blood bags on people. (Observed as of round #24083 )

I think it might be related to #15613 ?

**Reproduction**
Try to use bloodbag on yourself or others, it no worky.

**Screenshots**

**Additional context**

**Comment by QuietlyWhisper** [comment]
Ensure the target you are applying a blood bag to actually needs it, as of that PR, you won't be able to waste medical supplies. If there actually is an issue though, its likely checking if the person has bleed related injuries rather than checking blood level, which would absolutely cause a problem

**Comment by QuietlyWhisper** [comment]
> but I don't think it checks blood level for bags. 

Pretty sure thats the case because blood bags dont heal the same way the other items do... I gotta look at the code but hopefully the code owner finds this too

**Comment by OctoRocket** [comment]
> Another thing to note (I'd have to reconfirm), but I believe I got a message that I had fixed someone's bleeding with bandages, but was still able to continue applying them (after auto-stopping, it allowed me to start applying again.) Granted, it was heat of the moment in-round observations, I'd have to properly test.

That is intentional, if you are out of brute packs and need to heal with gauze it still works, as gauze heals some brute.

**Comment by OctoRocket** [comment]
The issue seems to be that bloodloss is spelled "bloodloss" in the yml and not "Bloodloss"

**Comment by OctoRocket** [comment]
I don't think blood packs ever did anything, because they were never actually healing Bloodloss damage

**Comment by QuietlyWhisper** [comment]
They were actually intended to be used to restore blood level, healing bloodloss damage was just a minor add on :)
