### ISSUE TITLE
Breaking zipties spawns dozen of broken ziptie entities

### ISSUE THREAD

**Issue by Slava0135** [space-wizards/space-station-14#15730]
## Description

**Reproduction**

**Screenshots**

(Actually I broke 2 zipties in cell, but there are 10 stacked entities for some reason)
![Screenshot_2023-04-23_14-47-47](https://user-images.githubusercontent.com/40753025/233936493-6a377037-f079-442f-8b97-88c6bcc9901e.png)

**Additional context**

**Comment by deltanedas** [comment]
99% sure its client entities spawned by prediction
check _timing.IsFirstTimePredicted or something in cuff system uncuff code

**Comment by Menshin** [comment]
Agreed with deltanedas, it's probably the same prediction problem as item dropping or toolbar icon duplication.
With the (un)equippedhand events now properly sent, more like these are bound to appear while the misprediction is not fixed.

**Comment by ElectroJr** [comment]
Its not directly related to do afters, its just a problem with cuffable system spawning entities in shared code.
If entities get spawned in Content.Shared you need to make sure the client doesn't spawn any, usually either by wrapping it in `INetManager.IsServer`, or by making the function that does the spawning abstract & having a separate server & client system.

Checking IsFirstTimePredicted wouuld just make the client spawn only one client-side entity, but wouln't actually stop it from being spawned.

**Comment by Menshin** [comment]
Understood, i'm fixing that.

Thanks.
