### ISSUE TITLE
RMB fails to load a monkey

### ISSUE THREAD

**Issue by Tunguso4ka** [space-wizards/space-station-14#15742]
## Description
finded out (on the dev server) that by clicling RMB on any entity spawns an error "Failed to load RSI /Textures/Mobs/Animals/monkey.rsi"

**Reproduction**
1. Get on the test server
2. Press ~ (or look into the terminal if you on linux)
3. RMB on PDA/other thing
4. error

**Video**

https://user-images.githubusercontent.com/71643624/234047546-8e81d9b3-e031-4fb4-a32f-9f3f9d5a1551.mp4

**Comment by Tunguso4ka** [comment]
monkey spawns normally tho (and still fails to load monkey rsi)

![зображення](https://user-images.githubusercontent.com/71643624/234048150-3133232a-de53-48aa-a587-8684914d32bf.png)

**Comment by deltanedas** [comment]
BOTY?

**Comment by Tunguso4ka** [comment]
someone put a bracket here.

![зображення](https://user-images.githubusercontent.com/71643624/234048699-31454eab-37ae-48cf-a60f-34841a7c262e.png)

**Comment by Tunguso4ka** [comment]
so problem lies somewhere in #15674. I returned all files changed by it and it fixed RMB.
