### ISSUE TITLE
[Origin Station] Brig hallway has generic access airlocks instead of security access airlocks 

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#15759]
## Description
The airlocks on the right of warden's office that lead into the brig section of security are generic access airlocks. These should be security only access airlocks.

**Screenshots**
![image](https://user-images.githubusercontent.com/106507028/234140092-fb17d86e-ab52-4f6c-86ab-2510bbdb07d0.png)

**Comment by potato1234x** [comment]
apparently this is a feature, #15587

**Comment by Kayek14** [comment]
Ah my bad, I didn't see it was added in that feature. It does feel a little weird having that hallway open to the entire crew however. No other stations have security designed like this, and it is a massive headache to security when playing on this map.

**Comment by Kayek14** [comment]
This issue is resolved.
