### ISSUE TITLE
You can only replace ringtone code by selecting the letters 

### ISSUE THREAD

**Issue by AJCM-git** [space-wizards/space-station-14#15756]
Don't know if this was the case before but it makes setting the code very obscure @deltanedas 

**Reproduction**
1. Open PDA, go to Ringtone
2. Can't change the letters unless you select the old letter and insert the new one

**Additional context**
The way this should work is like a pin code, when you select any box it should wipe the whole code and put the cursor at the start, then when you insert the first character it goes to the second, insert the second, goes to the third, etc

**Comment by deltanedas** [comment]
could also just have it clear the fields when opening the ui / hitting set, then you can enter easily enough

**Comment by lzk228** [comment]
fixed
