### ISSUE TITLE
Splitting and Re-merging wires does not update storage weight

### ISSUE THREAD

**Issue by Endecc** [space-wizards/space-station-14#15769]
## Description

If a fresh full stack of 30 wire (10 weight) is split, the old stack will remain 10 weight, and the new stack will weigh 3, regardless if the new split is a higher stack. Affects all voltage wires, HV/MV/LV.

**Reproduction**

1. Acquire full stack of 30 cables (10 weight)
2. Split into any amount
3. New stack now has 3 weight
3.1. Merge in-hand 3 weight stack with 10 weight stack, now full stack weighs 3

**Screenshots**

https://user-images.githubusercontent.com/33369477/234187440-31e0db2d-0388-4969-a1d9-7b21ddf82865.mp4

**Additional context**

May affect any other stackable items like steel or glass

**Comment by deltanedas** [comment]
this has been reported already im fairlt sure

**Comment by Endecc** [comment]
> this has been reported already im fairly sure

I just saw someone report it in discord, and couldn't find an issue about it in GH from this year. Unless this has been something for longer than I thought to account for.

**Comment by deltanedas** [comment]
#11514

**Comment by Endecc** [comment]
Searched wire instead cable, I'm a dummy
duplicate of #11514
