### ISSUE TITLE
Wide swings can hit and break grills underneath fullwindows

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#15767]
## Description
Wide swing attacks somehow break grills that are underneath windows and you don't get shocked from it. This is a problem because it can nullify the added protection of an electrified grill. 

Oddly enough, this only seems to happen when fullwindows are placed *before* the grills in mapping or player construction.

**Reproduction**
1. Place down fullwindow.
2. Place a grill on top of the fullwindow.
3. Charge up a wide swing and attack it.

**Comment by metalgearsloth** [comment]
Dupe https://github.com/space-wizards/space-station-14/issues/9129
