### ISSUE TITLE
Holoparasites are not immune to bullets

### ISSUE THREAD

**Issue by liltenhead** [space-wizards/space-station-14#15789]
## Description
The description of the holoparasite claims they are immune to bullets, they are not. 
**Reproduction**
Shoot a holoparasite, the owner still takes damage.

**Comment by Tunguso4ka** [comment]
well, technically holoporasites are immune to bullet, but they're owner not.

**Comment by Geekyhobo** [comment]
Ill look into it

**Comment by metalgearsloth** [comment]
When they were immune to bullets they were extremely overpowered so I don't think it's as simple as touching collisionmask (also the logic that projectile = bullet and hitscan = laser isn't true).

**Comment by Geekyhobo** [comment]
Bullet damage reduction could always be a possibility, either way the pda description need to be changed

**Comment by SpliTistiC** [comment]
> When they were immune to bullets they were extremely overpowered so I don't think it's as simple as touching collisionmask (also the logic that projectile = bullet and hitscan = laser isn't true), they'll need rebalancing elsewhere.
They took increased lazer damage, and when they didnt get hit by bullets they were actually used at a normal amount instead of rarely ever seen.
