### ISSUE TITLE
Gravitational anomaly breaks hitsounds 

### ISSUE THREAD

**Issue by Gerkada** [space-wizards/space-station-14#15791]
## Description

Since hitsounds were added, some ppl really liked to play around tossing things into walls etc, and that can be annoying at times, but overall OK. Now imagine what happens when some random ass anomaly sucks a morbillion entities near a wall. I assure you, you won't unhear these satanic sounds, they will be carved into your ears for eternity.
**Reproduction**

1. Wait for le gravitational anomaly to spawn near a wall
2. Wait for it to succ some items
3. Enjoy the choir of Satan

**Comment by deltanedas** [comment]
you can also do this by dragging an item into the wall, it will spam sounds at a moderate rate (like mining)

**Comment by Pangogie** [comment]
Fixed at some point.
