### ISSUE TITLE
Implement Farting

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#1580]
With the new atmos implemented, farting should be implemented very soon. 

Hydrogen, carbon dioxide, and methane combined with hydrogen sulfide should be created when someone farts. This mixture should change depending on what the "farter" ate.

**Comment by unusualcrow** [comment]
![mem](https://user-images.githubusercontent.com/10257081/89131062-25c65200-d4d8-11ea-94df-d3b5db4360b7.jpg)

**Comment by PJB3005** [comment]
I missed this issue and it has stayed open for far too long.
