### ISSUE TITLE
Remove HandheldCrewMonitor

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#15800]
It shows you the location of almost every crew member which is slightly strong, plus is given to CMOs roundstart despite them having a console (which was also an antag obj in 13, don't recall in 14).

**Comment by OctoRocket** [comment]
Might be better as an item that science can research.

**Comment by keronshb** [comment]
Crew Monitors should be landlocked (consoles only) and sparse (CMO office, Nurse station, Warden)

**Comment by OctoRocket** [comment]
If they are removed then normal crew monitors should actually work. The only way I am able to find people is with the hand held one and cross referencing my cords and the patient’s because the arrows don’t work correctly. It also does help that GPSs use different coordinates than the monitor does.

**Comment by DawBla** [comment]
Without handheld monitor you could only guess where people are. 
Monitors also use relative coordinates, so GPS is either a pain to use or straight up useless when cargo slams the station and makes it drift.
Why are they op btw? Syndies can take jumpsuit off their victim to remove them from a crew monitor and theres enough people without coords on or with fried sensors to not make people without coords suspicious.
If it's an issue because syndies use them then maybe would be better if only CMO and Paramed had access to it and couldn't roll antag?

**Comment by keronshb** [comment]
> Without handheld monitor you could only guess where people are. Monitors also use relative coordinates, so GPS is either a pain to use or straight up useless when cargo slams the station and makes it drift. Why are they op btw? Syndies can take jumpsuit off their victim to remove them from a crew monitor and theres enough people without coords on or with fried sensors to not make people without coords suspicious. If someone staring at the monitor waiting for someone else to die and then rushing to save them before traitor has any chance to loot them or dispose of the body is an issue, then maybe the battery usage should be increased? They could stare at the console as well though and these don't have batteries. If it's an issue because syndies use them then maybe would be better if only CMO and Paramed had access to it and couldn't roll antag?

Crew monitors and security cameras are something that shouldn't be portable because they can give significant advantage. As static computers they are powerful but it requires someone to be standing statically.

**Comment by DawBla** [comment]
Then maybe with the removal of portable crew monitor we could add something to let doctors keep track of their relative station coordinates, so they can actually get to the place they want. Basically a GPS but with relative coords like the console instead of absolute

**Comment by metalgearsloth** [comment]
> Then maybe with the removal of portable crew monitor we could add something to let doctors keep track of their relative station coordinates, so they can actually get to the place they want. Basically a GPS but with relative coords like the console instead of absolute

GPS just needs fixing to use station co-ords so it's consistent and all problems go away.

**Comment by metalgearsloth** [comment]
This was done.
