### ISSUE TITLE
ban_exemption_update can crash the server

### ISSUE THREAD

**Issue by Chief-Engineer** [space-wizards/space-station-14#15816]
## Description

Removing an exemption via `ban_exemption_update` then trying to add one crashes the server.

**Reproduction**

1. `ban_exemption_update localhost@JoeGenero Datacenter`
2. `ban_exemption_update localhost@JoeGenero None`
3. `ban_exemption_update localhost@JoeGenero Datacenter`

**Screenshots**

**Additional context**

I tested this with SQLite, I don't know if PostgreSQL will make a difference

**Comment by nikthechampiongr** [comment]
Cannot reproduce with reproduction steps. Was this resolved?

**Comment by PJB3005** [comment]
Closing unless somebody has repro steps/stack trace.
