### ISSUE TITLE
Puddles sometime appear on top of or under other puddles.

### ISSUE THREAD

**Issue by Owai-Seek** [space-wizards/space-station-14#15813]
## Description

You'll end up with a big puddle on top, with smaller puddles underneath. I'm not quite sure how to reproduce it, but I was told to make a bug report, so I will.

**Reproduction**

Not -entirely- sure on this point. But I'm fairly certain that I've seen it during a vomit sickness outbreak, where I'd notice the tiny vomit puddles underneath other puddles. Personally I've just been right click cleaning the smaller puddles underneath bigger ones, or hell, maybe it's from someone vomiting on a water puddle that already exists, but as I said, I'm unsure of proper reproduction steps. 
**Screenshots**

**Additional context**

**Comment by mirrorcult** [comment]
think this got fixed for vomit
