### ISSUE TITLE
Ringer Uplink should be reverted or changed because it encourages metagaming

### ISSUE THREAD

**Issue by Emisse** [space-wizards/space-station-14#15811]
with the return of the feature from ss13, security is now once again pda checking anyone they deem mildly suspicious to test the default code on it to see if it opens an uplink. this is lame as fuck and extra administrative burden that was not placed on admins before the change.

**Comment by deltanedas** [comment]
what if automatically randomizes your code once you open uplink

**Comment by VasilisThePikachu** [comment]
> what if automatically randomizes your code once you open uplink
> 
> :trollface:

Sounds like pain to have to set a new code every time you want to access the uplink

**Comment by deltanedas** [comment]
you could just leave the store window open

**Comment by VasilisThePikachu** [comment]
The ui is pretty big though, i would not want to keep a giant ui on my screen obscuring my vision

**Comment by EmoGarbage404** [comment]
Can players not just input a different code when they finish purchasing?

**Comment by deltanedas** [comment]
they can and i even put warnings in like 3 places to do just that but bozos cant read

**Comment by VasilisThePikachu** [comment]
A little brainstorm i had, may still encourage meta but oh well

When entering a ringtone, it shows the uplink button like before and will be there until you set the code in the ringer (or maybe a dedicated hide/panic button) hides the uplink and changes the code to a new one.

If someone checks the pda while the uplink is unlocked it would show up there. If its hidden it wont show

**Comment by deltanedas** [comment]
yeah its very possible but would be the same issue of noobs leaving it unlocked, would be worse in thst regard since you dont even need to go ringtone -> set, its just there

**Comment by VasilisThePikachu** [comment]
Honestly at that point they should just learn to cover their tracks. Which is pretty much the point of a syndicate agent

**Comment by PJB3005** [comment]
Literally just do what sane SS13 servers do.

If you edit the ringtone to the uplink code, it opens the uplink menu and the PDA is uplink mode (can't be used normally) until uplink is explicitly closed. Code never gets saved to the PDA so stays as it was before.

If you forget to close your uplink and somebody finds your PDA that's on you, but once the uplink is closed there's no evidence.

**Comment by deltanedas** [comment]
the issue with that is you can see it not working as a pda and meta that its an uplink

**Comment by PJB3005** [comment]
That's a feature. Don't forget to press the big "close uplink" button.

If people forget THAT then just put a reminder message in the UI somewhere??

**Comment by deltanedas** [comment]
implementation:
- make ringtone change event be by ref and cancellable (easy)
- uplink cancels it if code is correct, opening uplink (medium)
- pda acts sus while any client has uplink open (hard)
- message below store in style of apc and stuff with syndicate fluff and telling you to close it when done (easy)

**Comment by Emisse** [comment]
this was addressed
