### ISSUE TITLE
All ghost actions except Boo! are gone

### ISSUE THREAD

**Issue by Flareguy** [space-wizards/space-station-14#15818]
## Description
What it says on the tin. They don't even seem to be in the K menu.

**Reproduction**
1. Join Wizard's Den Lizard
2. Observe
3. Realize that you can't see shit in the dark because disable lighting is gone
4. Cry

**Comment by VasilisThePikachu** [comment]
Fixed by #15805

**Comment by keronshb** [comment]
Above PR fixed this
