### ISSUE TITLE
aspid solar too strong

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#15830]
## Description
you never need ame just do solar gaming

it needs far less panels tho its not as bad as fland is/was

**Reproduction**
1. set up solar
2. good power is done for the round

**Comment by InverselyKinematic** [comment]
The syndie with a wirecutter in question:

**Comment by deltanedas** [comment]
yes even when a bozo cuts south solar northwest and northeast still fully provided for the station
