### ISSUE TITLE
spacebuck bar sign localization issue

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#15839]
## Description

**Reproduction**

**Screenshots**

![image](https://user-images.githubusercontent.com/43253663/234770083-6e7cead8-27b5-464b-825c-98434e57353f.png)

**Additional context**

**Comment by notquitehadouken** [comment]
was a typo
i made a pr for it

**Comment by InverselyKinematic** [comment]
probably should mention it's pr #15856

**Comment by keronshb** [comment]
Fixed from mentioned PR
