### ISSUE TITLE
Atmos mapping tools

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#1583]
We need a convenient way to add/remove/visualize gases without using commands.

**Comment by SweptWasTaken** [comment]
This is partially fixed since there's atmos tools in the admin menu. Should be trivial to add them to sandbox menu which I will do and then close this issue.

**Comment by Zumorica** [comment]
Originally, this issue was about having tools similar to the tile placement menu but for placing gases, setting temperature, etc. It's not a trivial issue, and it definitely isn't easily addressed. Just a heads up

**Comment by UbaserB** [comment]
Considering we now have ways to add gases to tiles in mapping, we can probably close this issue.
