### ISSUE TITLE
Fire locks red lights dont enable in spaced rooms

### ISSUE THREAD

**Issue by VasilisThePikachu** [space-wizards/space-station-14#15852]
## Description

title
**Reproduction**

1. Space a room
2. Watch fire locks drop
3. The 2 red lights on the side of the fire doors does not light up, which usually indicate that the room is spaced

**Screenshots**

![image](https://user-images.githubusercontent.com/34938708/234955937-d859ef9f-82ac-4798-817b-f1bc7f213f50.png)

How it's supposed to look like (I'm very good at art thank you)
![image](https://user-images.githubusercontent.com/34938708/234956401-714a0644-133f-4345-8e44-08a9d5226025.png)
**Additional context**

**Comment by Menshin** [comment]
Was it working before or is it a missing feature ?

**Comment by tom-leys** [comment]
Solved 
![image](https://user-images.githubusercontent.com/5285589/235295702-030cc666-4b46-4fb7-b07b-fb353afc72af.png)

**Comment by tom-leys** [comment]
![image](https://user-images.githubusercontent.com/5285589/235295717-50f48dba-cbc3-4bbe-a4c1-0c5c86a7b8f8.png)

**Comment by VasilisThePikachu** [comment]
> i recall it working before, the sprites are definitely used in some cases

it did work before, something broke it

**Comment by VasilisThePikachu** [comment]
closed by #15852
