### ISSUE TITLE
putting wielded weapon on back with shift b doesnt unwield

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#15855]
## Description
happened with fireaxe, i assume bat/spear also work

also this is on mining station so might be missing a fix idk ill test later

**Reproduction**
1. wield axe
2. shift b
3. sususus

**Screenshots**
![22:46:00](https://user-images.githubusercontent.com/39013340/234998414-795647f8-cd7d-4571-a33c-fb3c071b7acc.png)

**Comment by OctoRocket** [comment]
Can you still swing it?

**Comment by deltanedas** [comment]
im 99% sure you cant but ill see now

**Comment by deltanedas** [comment]
doesnt happen on master, mining station moment

**Comment by Partmedia** [comment]
> doesnt happen on master, mining station moment
> 
> @Partmedia yes

Mining Station moment, indeed. If you are able to identify when this was fixed upstream, we can cherry-pick the patch. We can move this discussion to Discord or our issue tracker.
