### ISSUE TITLE
Hotplates need an overhaul or should be replaced with chem heaters.

### ISSUE THREAD

**Issue by keronshb** [space-wizards/space-station-14#15909]
Currently with hotplates you just put a beaker on the hotplate and you hope you've waited long enough for it to heat up. There's nothing telling. It doesn't show you if it's on or off, doesn't tell you the temperature of the reagents and no estimate on how long it might take. Hotplates should have a UI or they should be replaced with chem heaters.

**Comment by 0x6273** [comment]
> There's nothing telling.

You can hear when the reaction occurs, and usually the color of the solution will have changed.

> It doesn't show you if it's on or off,

Isn't it always on when there's a beaker on it? There should probably be like a power LED on the sprite to indicate this.

> doesn't tell you the temperature of the reagents and no estimate on how long it might take.

It's a hotplate. It's not aware of what's in the beaker, it just heats it. If you want to know temperature, a thermometer makes more sense.

> Hotplates should have a UI or they should be replaced with chem heaters.

Not everything needs a UI. Hotplates are simple enough that they definitely don't need one.

**Comment by deltanedas** [comment]
> and usually the color of the solution will have changed.

the beaker's solution isnt visible when on the hotplate so you have to do the, alt click shift click click back onto hotplate because meth isnt ready, shuffle

**Comment by 0x6273** [comment]
> the beaker's solution isnt visible when on the hotplate so you have to do the, alt click shift click click back onto hotplate because meth isnt ready, shuffle

Yeah true. It should probably put the actual beaker entity on the hotplate instead of a sprite layer.

**Comment by keronshb** [comment]
> You can hear when the reaction occurs, and usually the color of the solution will have changed.

Yes but it's a guessing game of when it's going to happen.



> Isn't it always on when there's a beaker on it? There should probably be like a power LED on the sprite to indicate this.

There's no visual indicator to show there's a state change if it's on or off other than there's a beaker on it.



> It's a hotplate. It's not aware of what's in the beaker, it just heats it. If you want to know temperature, a thermometer makes more sense.

> Not everything needs a UI. Hotplates are simple enough that they definitely don't need one.

It's a game. Not everything has to be logical. Chem heaters showed you what the temperature was and allowed you to change target temperature/power.
