### ISSUE TITLE
Nukies cannot place withdrawn telecrystals into their PDAs

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#15920]
## Description

Probably the uplink pda change pr
**Reproduction**

**Screenshots**

**Additional context**

**Comment by deltanedas** [comment]
they dont have uplink pdas??? even commander and medic have radios

**Comment by lexs0sa** [comment]
It would seem the terminology is off, I believe they meant uplinks. Uplinks cannot take TC, disabling any pooling for Nukies.

**Comment by DogZeroX** [comment]
Apparently not even traitors can put their telecrystals back?
![image](https://user-images.githubusercontent.com/43253663/235340676-653845f5-e13c-49bf-b7a1-fc198e485c53.png)
It's latejoin traitor pretty sure

**Comment by crazybrain23** [comment]
> Apparently not even traitors can put their telecrystals back? 

They can, they just have to have the uplink ringtone set in order to so.
