### ISSUE TITLE
Hitting yourself is stupid when it comes to big mobs

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#15924]
## Description

Space dragons have a high chance to hit themselves while trying to fight people, since they're so big there's more chance that you will hit yourself rather than the person around you. They lack a wide attack so it's way more difficult.
**Reproduction**

**Screenshots**

**Additional context**

**Comment by deltanedas** [comment]
honestly only humanoids should be able to self attack at all
how the fuck is hampter or a fish gonna bite its head off
