### ISSUE TITLE
Wallslam

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#1592]
Hitting a wall (or something else) at high velocities should damage you.
Kinda related to atmos.

**Comment by ScumbagDog** [comment]
Would it be completely silly to extend DamageableComponent to also implement ICollideBehavior?

**Comment by Zumorica** [comment]
> Would it be completely silly to extend DamageableComponent to also implement ICollideBehavior?

Perhaps it'd be best that this is put in its own component?
