### ISSUE TITLE
Remove Patreon links when ran from Steam

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/space-station-14#1594]
This is necessary to comply with Valve's rules.

**Comment by Nickname863** [comment]
So should the game just check if it is running through steam, in that case i think we have to use the steam SDK to check (or maybe have a messy workaround, like starting the Client with a parameter like -steam or something like that ). Or should the Steam release get its own build, so the patron list is completely absent from the binaries?

**Comment by PaulRitter** [comment]
close pls
