### ISSUE TITLE
water draws above the shittle

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#15957]
## Description
yes

**Reproduction**
1. ftl to planet with rivers
2. get (un)lucky

**Screenshots**
![01:26:08](https://user-images.githubusercontent.com/39013340/235383431-63c7b8d6-71af-41a8-aa5a-57fff3f63985.png)

**Comment by deltanedas** [comment]
happens for lava too

**Comment by metalgearsloth** [comment]
Dupe https://github.com/space-wizards/RobustToolbox/issues/2191
