### ISSUE TITLE
living people rotting real;

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#15968]
## Description
encountered on lizard right now
everyone is rotting send help

**Reproduction**
![11:06:52](https://user-images.githubusercontent.com/39013340/235438781-9fbe4450-8cd0-4bde-9987-377c990f7d90.png)

**Comment by metalgearsloth** [comment]
Might be timeoffset? Needs debugging.

**Comment by deltanedas** [comment]
vving a person that shows it should be enough info to know

**Comment by EmoGarbage404** [comment]
fixed
