### ISSUE TITLE
Description Writing/Porting | ANYONE CAN DO THIS 

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#1596]
This is a very simple task that anyone can do if you have a text editor and some knowledge of GitHub. You don't even need an IDE, you could do this just with GitHub's inbrowser markdown editor.

A large percentage of items in SS14 have a `description:` line in their entity prototype. 

![image](https://user-images.githubusercontent.com/49448379/88871797-4eb0c380-d208-11ea-84ea-3facf9fbe852.png)

This description line determines what shows when you examine the entity in-game. 

![Content Client_2020-07-29_18-58-34](https://user-images.githubusercontent.com/49448379/88871866-71db7300-d208-11ea-9ad9-ac463414b048.png)

Most description boxes in SS14 are not filled out, usually because the coder who added them is lazy. However fixing them is very simple and anyone can do it. All you need to do is to find the YAML file where the entity is located, find the `description:` line and write something there. **(If the item is already in SS13, please use the description from in-game)**, you can usually find the description by opening the dreammaker file for the object and copy-pasting it from the field.

I'll walk you through the process for GitHub since i'm just that kinda ~~gay~~ guy and want this to be accessible to anyone who wants to help out. If you're using a proper Git setup this is probably self-explanatory and you don't need to read beyond this point.

1. Find an item that does not have a description. This can be done both in-game and by searching in the code. For example, it looks like the [mime mask](https://github.com/space-wizards/space-station-14/blob/master/Resources/Prototypes/Entities/Clothing/Masks/masks.yml) does not have a description.
![image](https://user-images.githubusercontent.com/49448379/88878171-d69dca00-d216-11ea-8b5e-3eee23508865.png)

2. Either open the file in your text editor if you've cloned the repo, or click the little edit button on the top right of the GitHub markdown
![image](https://user-images.githubusercontent.com/49448379/88980039-5f1d7880-d2b2-11ea-826d-3bbfda00f40c.png)

3. Input the description
![image](https://user-images.githubusercontent.com/49448379/88980360-14503080-d2b3-11ea-8a27-31263de4a45c.png)

4. Propose your changes with a legible title.
![image](https://user-images.githubusercontent.com/49448379/89368151-5241c000-d6ca-11ea-8b8e-f162ad5cf5b4.png)

5. Nice work!

**Comment by FrostMando** [comment]
I'm working on it.

**Comment by lajolico** [comment]
Just added more descriptions. I believe once Frost adds the Clothing Desc's we'll be caught up for the most part.

**Comment by BozoDel** [comment]
Hi, sorry to be that guy (especially since I'm probably not going to help), but what about attribution? Respecting the license and all that?

**Comment by SweptWasTaken** [comment]
> 
> 
> Hi, sorry to be that guy (especially since I'm probably not going to help), but what about attribution? Respecting the license and all that?

Do you mean specifically for descriptions? We have attribution embedded in our meta.jsons for assets and license.txts when that isn't applicable.

**Comment by BozoDel** [comment]
Yes, I mean the descriptions.

I'm sorry, but I didn't understand your reply. Do you mean that attribution is taken care of?

**Comment by Peptide90** [comment]
I've checked all clothing items, they all have a description now (or will do when my next PR goes through). Will keep looking through the rest.

**Comment by Visne** [comment]
Added descriptions to all empty `description:` tags I could find using the regex `description:$` in #3221. As far as I can tell every emtpy description node is filled in now.

**Comment by Visne** [comment]
I have marked all missing descriptions with TODOs in #3269. All help is appreciated.

**Comment by Peptide90** [comment]
Can this effectively be closed now since 99% of descriptions are in where they're needed?

**Comment by SweptWasTaken** [comment]
No

**Comment by SweptWasTaken** [comment]
I'd say this is mostly done thanks to good organizing by @Visne. However there's a few `TODO:`s left and stuff without descriptions. Plus this is a good guide for very basic contribution to SS14 so i'll leave it open for now.

**Comment by metalgearsloth** [comment]
Can be done as we see it.

**Comment by SweptWasTaken** [comment]
Could prob add this to the wiki in some form

**Comment by moonheart08** [comment]
> Could prob add this to the wiki in some form

Generating item info is expensive:tm:, but I have plans for it in a limited fashion. Biggest issue is simply going to be exporting sprites.
