### ISSUE TITLE
smoke might go through mask unintentionally

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#15972]
## Description
saw on lizard, a amatoxin lex **smoke** worked with internals on
its possible there was also polytrinic acid, i heard talks of it in deadchat
need to test thoroughly on master

**Reproduction**
1. get evac bombed
2. die with internals on real

**Comment by DummeHytteOst** [comment]
video of said smoke in effect
https://user-images.githubusercontent.com/94384139/235450139-87bf5cd3-8bc9-49dc-83ae-55f6e40a5503.mp4

**Comment by deltanedas** [comment]
look ma im on tv

**Comment by deltanedas** [comment]
pro

**Comment by deltanedas** [comment]
could not reproduce on master using lexorin foam and lexorin/polytrinic foam, neither went through internals
