### ISSUE TITLE
Angry slimes don't attack animal mobs

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#15988]
## Description
Angry slime AIs don't attack animal mobs such as Remilia or monkeys. This is a problem because players can ghost role the animals and get a free kill on the slime.

**Additional context**
The flavor text for slimes say they are irritable and attack everything due to their instincts. They should also attack random station animals.

**Comment by PuroSlavKing** [comment]
@Nimfar11

**Comment by Kayek14** [comment]
Closing since this seems to be fixed.
