### ISSUE TITLE
You cannot change your ringtone

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#15985]
## Description

Try to type anything in the ringtone menu and it doesn't work at all.
**Reproduction**

**Screenshots**

**Additional context**

**Comment by deltanedas** [comment]
it cant be your uplink code id thats what anything is

**Comment by deltanedas** [comment]
without an uplink this does not happen
(you clicked set right?)

video soon

**Comment by deltanedas** [comment]
also saves when its not your uplink code

@DogZeroX close
