### ISSUE TITLE
Janitor gameplay is still a slog and very frustrating, more so during ventclog events

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#15990]
## Description
With more and more messes getting added into the game; puddle rework, pills now breaking into liquid, the janitor gameplay loop has become very frustrating to play, even more so as late game janitor. despite many merges added to help elevate the issue, I feel like it has only gotten worse. I get that as the round goes on it gets more chaotic and thus more work for the janitor, cleaning should almost always feel like an uphill battle. Even with a full janitor team, rounds can be hell, more so if you are a single janitor. we don't really have the equipment or any relevant upgrades to help counterbalance said chaos, aside from the Advanced mop. After playing a few janitor rounds here is what I'm most frustrated with, and my proposed solutions that I see can be in the right direction of making the job a bit more rewarding to play as. 

**Problems**
 1. The drain still drains *way* too slowly. Especially when more than one janitor is in there. It can take minutes trying to empty your bucket by yourself, even longer if there is another janitor in there doing the same thing.
 2. Vent clog events with space lube are a NIGHTMARE! One vent spewing out lube literally takes 2-3 trips because your bucket gets full 30% of the way into cleaning it. Compound this with the drain draining slowly and the amount of vents that roll space lube you can easily see yourself doing nothing but cleaning space lube spills for the rest of the round and still not get it all.
 3. Advanced mops are not worth it. For major spills, witch in the late game the majority of the spills are major, it is quicker to bring a mop bucket with you because the advanced mop takes too long to replenish water and purge other liquids. For a late game item, it feels backwards to ignore it and use regular mops and buckets because they are more efficient and time saving than the late game item. There have been times where I click on a single tile in the middle of a major spill, only to be forced to wait ~15 seconds for the mob to refill/purge. Imagine this but with 20 tiles of lube. I have seen people dual-wield advanced mops because just one is too slow.
 4. This is more of a mapping issue, but a lot of janitor closets in maps are not stocked properly. Either they are missing water tanks and buckets. Or they only have one regular water tank witch gets used up in the first 10 minutes of the round.
 
 **Solutions**
1. Either add more vents to the janitor room, increase their capacity, or have them drain faster. (Perhaps an upgrade?) Alternatively, allow the janitor to again dump out their bucket(perhaps a long do after or in small units to avoid grief in the hallways) in the closet on top of the drain so they can get back to the action as the drain slowly does its job. Bonus points for this because the janitor closet will become a literal quagmire of chemicals, seeping under the airlock into the hallway, slowly getting drained out by the drain.
2. Allow the mop buckets to hold more liquid. The bucket can only hold 600 units i believe. One vent during the event can pump out 1000+ units of space lube. This will require many trips to clean. (Perhaps allow buckets to be upgraded? Bluespace mop buckets anyone?) Or reduce the amount of lube each event creates. 
3. Advanced mops should get their water generation and liquid purge speed increased by at least 50%
4. Normalize all janitor closets(maybe with the exception of Detroit) to always have buckets, the same janitor vendors, light replacers/space lights, and one or more high-capacity water tank or water source.
 
 
 
**Reproduction**
Play janitor on extended.

**Screenshots**
Taken from an extended round. Some tiles have 50+ units of lube on them. Each section would take 2-3 trips to clean. By the time you get back to the closet to empty your bucket again the drain would still not have completely emptied.
![image](https://user-images.githubusercontent.com/106507028/235714611-3499bff4-6149-43ab-897f-bc4b71e6bb7f.png)

**Additional context**
Make playing janitor feel like a rewarding job again!

**Comment by deltanedas** [comment]
lube just needs a fucking nerf its ridiculous how much every vent clog makes

**Comment by ChilbroBaggins** [comment]
One of those vacuum cleaners with the backpack capacity would be cool.

**Comment by keronshb** [comment]
This should have some discussion and testing but also this is fairly easy to change.

**Comment by metalgearsloth** [comment]
The only other thing remaining for janitor atm is prototypes for cleanfoam nades but blood + space lube seem to be common complaints due to how common they are.

**Comment by deltanedas** [comment]
blood is ok since you usally dont have several massive puddles of it soaking the station + it has no direct downside like lube which is denial of service

**Comment by metalgearsloth** [comment]
I think if you want to nerf vent clog the actual thing to do first is make smoke / foam not clone solutions which will reduce the volume significantly.

**Comment by deltanedas** [comment]
i think the main issue is not just volume but also the ridiculous spread
i will be nerfing both of these since spreading solutions exponentially is too hard for me idk

**Comment by Kayek14** [comment]
Closing as a majority of QOL updates went out since this was created. Janitor feels much better to play.
