### ISSUE TITLE
Gas overlay urgently needs optimization

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#1601]
Due to the lack of overlay bubbling and poorly performant gas netcode, the current gas overlay absolutely kills the client when there's a big fire or a lot of gas atmos changes.

![image](https://user-images.githubusercontent.com/6766154/89483124-a072c400-d79b-11ea-9926-fcc62dd8d8b7.png)
Notice the 5000+ Kb download and the big lag spikes.

**Comment by metalgearsloth** [comment]
@Zumorica I'll take this if you want, I assume we're just going to chunk the data and send the relevant chunks as they update.

**Comment by Zumorica** [comment]
> @Zumorica I'll take this if you want, I assume we're just going to chunk the data and send the relevant chunks as they update.

Indeed, this is pretty much what needs to be done

**Comment by Zumorica** [comment]
Fixed by #1678
