### ISSUE TITLE
Slimes and dwarves don't rot

### ISSUE THREAD

**Issue by EmoGarbage404** [space-wizards/space-station-14#16037]
## Description

They don't have perishableComponent.

**Comment by Emisse** [comment]
ok

**Comment by Just-a-Unity-Dev** [comment]
slimes not rotting is intentional

**Comment by Just-a-Unity-Dev** [comment]
also if you make it intentional i will stab you, slimes already suck ass let them have this one

**Comment by deltanedas** [comment]
give me an r, give me an s, give me a ROCK AND STONE

**Comment by notquitehadouken** [comment]
short people are immune to decomposition

**Comment by notquitehadouken** [comment]
see pr #16050
