### ISSUE TITLE
Paramedic needs nerfs

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#16034]
1. It's PDA is better than an MD for no reason, the scan time is over twice as fast.
2. It shouldn't have its own roundstart hardsuit. That's what EVA is for.

**Comment by keronshb** [comment]
IMO Paramedic was a mistake for ss13 and just detracted from allowing doctors to leave medbay.

**Comment by metalgearsloth** [comment]
> IMO Paramedic was a mistake for ss13 and just detracted from allowing doctors to leave medbay.

Yeah I'd prefer it were just a loadout reskin personally. Sec officers and engineering just have 1 role that can function in-department or out of department just fine.

**Comment by Emisse** [comment]
loadout would fix all of the games issues instantly

**Comment by metalgearsloth** [comment]
Also they start with EVA suits that should really be removed.

**Comment by BramvanZijp** [comment]
> loadout would fix all of the games issues instantly

It, infact, did not fix all issues.

**Comment by deltanedas** [comment]
pda buff was removed and how does point 2 make any sense:
- sec has roundstart hardsuits
- engi has roundstart hardsuits
- rd has a roundstart hardsuit
- salv has roundstart hardsuits

why shouldnt any of these roles go to eva for an eva suit when they have to go outside as well?

**Comment by VasilisThePikachu** [comment]
The first point has been addressed, the second point imo should be a new isssue.
