### ISSUE TITLE
Defib doesn't have a clear sign whether it's on or not

### ISSUE THREAD

**Issue by Just-a-Unity-Dev** [space-wizards/space-station-14#16030]
No visual indicator and the only thing I have is a popup that says "defib not on"

**Comment by EmoGarbage404** [comment]
the screen lights up?

**Comment by Just-a-Unity-Dev** [comment]
> the screen lights up?

didnt for me

**Comment by Just-a-Unity-Dev** [comment]
okay i think this is fizxed
