### ISSUE TITLE
Datacenter bans should have a more explanatory message

### ISSUE THREAD

**Issue by VasilisThePikachu** [space-wizards/space-station-14#16045]
## Description

The word "datacenter" as a reason with a link to the forums does not explain well that the ban is applied to just the ip and the fix is to disable your vpn. I cant figure out how this message is generated so im guessing its some backend vps stuff that us contribs dont have access to. Sorry if this is the wrong place to make such an issue
**Reproduction**

1. Turn on your favourite vpn
2. Connect to wizden
3. Be in the perspective of a new player, suddenly getting "banned" for this datacenter thing

**Screenshots**

![image](https://forum.spacestation14.io/uploads/monthly_2023_04/1558221889_Screenshot2023-04-30003514.png.f94f564c73c2422da63e5b8d3eccb342.png)
yoinked from one of the many ban appeals

**Comment by moonheart08** [comment]
This message is human written and doesn't affect this repo at all.

**Comment by VasilisThePikachu** [comment]
got it, sorry for making it then
