### ISSUE TITLE
Sillicon can bleed and be pale

### ISSUE THREAD

**Issue by VasilisThePikachu** [space-wizards/space-station-14#16053]
## Description

poor things

**Reproduction**

1. attack a poor silicon
2. It looks pale???? and is bleeding??? looks mauled???

**Screenshots**

![image](https://user-images.githubusercontent.com/34938708/235945755-090f557d-6384-4723-9368-b2efc0470a2c.png)
![image](https://user-images.githubusercontent.com/34938708/235945817-d3aa9ed6-da01-4d7f-88f8-b458c76606d9.png)

**Additional context**

Robots cant be pale so lets just, not make that appear or make it say something like "its not performing as well"
And instead of bleeding how about it says "It looks like its leaking oil"
as far having gashes/mauled, lets say something like "It looks dented"

**Comment by deltanedas** [comment]
and burns being damaged wiring

**Comment by VasilisThePikachu** [comment]
I was also thinking we just get rid of the bloodstream and health examination, in 13 they are powered by batteries so there is no reason for them to leak

**Comment by Ilya246** [comment]
literally ultrakill
