### ISSUE TITLE
heavy/crit swings doing the incorrect damage for some weapons

### ISSUE THREAD

**Issue by DummeHytteOst** [space-wizards/space-station-14#16117]
heavy/crit swining with a wieldable or on/off weapon, like welders, fireaxes and eswords does the wieldable/on damage instantly and then scales up to their off/ non wield damage, depending on how close to the green spot you hit

two examble videos, i did confirm that i happens to fireaxe, esword and welding tool. welding tool doing 10 heat and up to 10 blunt on perfect crit hits

https://user-images.githubusercontent.com/94384139/236465190-8345f412-83b9-42de-bc3a-4721f2b41f92.mp4

https://user-images.githubusercontent.com/94384139/236465358-b6437b1c-9f58-4bc5-a76f-a75579ebbca1.mp4

**Comment by deltanedas** [comment]
iirc it scales base damage then adds the wield bonus separately but havent looked at the code
