### ISSUE TITLE
Gamerule events start immediatly after announcing

### ISSUE THREAD

**Issue by Slava0135** [space-wizards/space-station-14#16114]
## Description

Some events like vent clog or power check start immediately after announcment (wasn't the case before)
**Reproduction**

**Screenshots**

**Additional context**

**Comment by EmoGarbage404** [comment]
You need to specify the specific events. This is due to regressions in the prototypes, not the system itself (like the issue suggests)

**Comment by Slava0135** [comment]
![image](https://user-images.githubusercontent.com/40753025/236452313-a724f38c-6861-414e-beef-6162ba841286.png)
![image](https://user-images.githubusercontent.com/40753025/236452432-5bab5f68-6b7e-42c3-9a14-bc83b08377db.png)
the problem

but even if I change `startAfter` to `startDelay` it still doesn't work correctly

**Comment by Slava0135** [comment]
closed by #16134
