### ISSUE TITLE
Welders should consume fuel more quickly

### ISSUE THREAD

**Issue by EmoGarbage404** [space-wizards/space-station-14#16130]
## Description

Currently, the rate of fuel consumption is so low for welding tools that there's never a need to refuel them. It should be significantly higher so that the limited fuel supply is actually something of consideration.

**Comment by Scribbles0** [comment]
to add to this i think the experimental welder that CE gets actually replenishes fuel faster than it consumes

**Comment by deltanedas** [comment]
why would you just have a welder on without welding anything?
on the flip side, could just make welding things not use fuel but just be a time doafter
so then the usage is whatever the passive lit usage is, which would be increased to compensate

**Comment by EmoGarbage404** [comment]
> why would you just have a welder on without welding anything? on the flip side, could just make welding things not use fuel but just be a time doafter so then the usage is whatever the passive lit usage is, which would be increased to compensate

combat, i would think. It also is a ghetto-ass light source. I don't think that the doafters should be longer, but maybe just have the doafters consume more fuel on completion?

**Comment by deltanedas** [comment]
as in doafters consume no fuel they just require you to have the welder lit for N seconds
then increase lit fuel usage a lot to compensate

**Comment by keronshb** [comment]
If this is for welders being passively on, no I don't think this has to be changed.

If it's for welders using fuel after being used to weld something then yeah go for it.

**Comment by Veritius** [comment]
I did some mass disassembly earlier, and I had to bring a fuel tank around with me because the welder did run out a few times.

**Comment by deltanedas** [comment]
thats not from passive lit drain

**Comment by deltanedas** [comment]
this should be closed
