### ISSUE TITLE
Station power out event should not let engis just flip ape back on for power

### ISSUE THREAD

**Issue by VasilisThePikachu** [space-wizards/space-station-14#16168]
## Description

you can just click "toggle" on the apc's and boom the powers back
**Reproduction**

1. do powerout event
2. toggle apc
**Screenshots**

**Additional context**

**Comment by deltanedas** [comment]
same with replacing the board

if this is not desired behaviour, have a station component for having apcs force disabled then check it along with toggled status

**Comment by keronshb** [comment]
Is this not the same event from SS13? I don't see the issue with this if it is.

**Comment by VasilisThePikachu** [comment]
From what I get from the events flavor text. There is wierd activity on the station power network, so central command turns off the power to prevent damage

Now how can an engi magically turn the power back on if central command shut off the power network?

**Comment by keronshb** [comment]
> From what I get from the events flavor text. There is wierd activity on the station power network, so central command turns off the power to prevent damage
> 
> Now how can an engi magically turn the power back on if central command shut off the power network?

It's more like a grid reset - central shutting off all of the apcs at once.

**Comment by DawBla** [comment]
the source of the power is on the station so engis are just manually overriding remote commands

**Comment by VasilisThePikachu** [comment]
i think its better if engis could not override central command actions, the point of the event is to temporary fully kill power. During the power off antags could sneak into places to complete their objectives. If engis can just toggle it back on or anyone can just remove and put in the apc board to reset power then that defeats the purpose of the event.
