### ISSUE TITLE
Nukies can get gacha chests (surplus crates)

### ISSUE THREAD

**Issue by Myakot** [space-wizards/space-station-14#16162]
## Description
Nukies have the uplink implant in their uplink. This allows them to spend 4 TK to get agent's uplink store, which opens up the options to buy surplus crates. 
I do not believe it was intended.

**Reproduction**
1. Have nukie uplink
2. Spend 4 TC for uplink implant
3. Transfer TC from nukie uplink to implant uplink
4. Buy surplus crate for 40 TC, get items worth 120+TC usually
5. ???

**Comment by deltanedas** [comment]
pro
