### ISSUE TITLE
Electric anomaly hardlocks the server

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#16164]
Only log before mass reconnections
![image](https://user-images.githubusercontent.com/31366439/236622530-41c940db-97f7-4fce-81ba-8509b73eefd9.png)

**Comment by deltanedas** [comment]
could be worth commenting out lightning from supercritical and seeing if server still dies, got a hunch thats what kills server
if it is then either reduce the amount or spread it out over multiple ticks as to not instantly kill it

**Comment by ElectroJr** [comment]
I think the current assumption is that it was somehow caused by the changes that were reverted in #16169, but afaik there are no reproduction steps & its just an assumption

**Comment by keronshb** [comment]
#16175 fixed this, well the revert before it did.
