### ISSUE TITLE
Invulnerable cardboard boxes

### ISSUE THREAD

**Issue by Myakot** [space-wizards/space-station-14#16187]
## Description
Both syndie and regular cardboard boxes are still indestructible to pretty much everything. 

You can even safely farm new ice anomaly by just simply dropping a box on it when it's stable.

**Comment by keronshb** [comment]
Syndie boxes should definitely be indestructible. It would be a huge waste of TC if they weren't.

Regular boxes should be destructible. Ideally there would be a base type for destructible boxes and indestructible boxes. You can still take damage in the box, despite not being able to destroy it.

**Comment by NonchalantNoob** [comment]
Someone needs to close this because this didn't autoclose.
