### ISSUE TITLE
Airlock + device network needs cleaning up

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#16199]
https://github.com/space-wizards/space-station-14/pull/14177 and https://github.com/space-wizards/space-station-14/pull/13645 seem to be going different directions for network data, I just want whatever is easiest to use for other systems.

**Comment by metalgearsloth** [comment]
Also UninitializedSaveTest because conflict hell. You may just be able to remove the prototypes now.

**Comment by juliangiebel** [comment]
I adapted the featured from #14177 to device linking. The logic state is sent as a payload now.
