### ISSUE TITLE
Examine box doesn't scale with large entity names

### ISSUE THREAD

**Issue by Tyzemol** [space-wizards/space-station-14#16217]
## Description
yea

**Reproduction**
examine a thing with loooooong name
alternatively use a labeler on something to give it a long label

**Screenshots**
![image](https://user-images.githubusercontent.com/85772526/236687495-741d53e2-89c9-432b-a9e5-5f1e50daf3e5.png)

**Comment by Tyzemol** [comment]
nevermind i am a retard and didnt chek if this issue was already posted, this is a duplicate of #15854 how do i remove this

**Comment by EmoGarbage404** [comment]
Dupe + dont use slurs por favor
