### ISSUE TITLE
Mice can push people onto tables. Including glass tables.

### ISSUE THREAD

**Issue by Owai-Seek** [space-wizards/space-station-14#16239]
## Description
The title mostly. This should not be possible, it enables shitter behaviors. Yes, I could just kill them, but they can go get another mouse ghost role and do it until they run out. Agony.

**Reproduction**
Be mouse, drag person onto glass (or any other kind) of table. Laugh because you're an awful person.

**Screenshots**

**Additional context**

**Comment by deltanedas** [comment]
make force vaulting require HandsComponent then a mouse would have to be very crafty
