### ISSUE TITLE
Defibs not working.

### ISSUE THREAD

**Issue by Owai-Seek** [space-wizards/space-station-14#16237]
## Description
Experienced in Miros 24835, Defibs don't work at all, you cannot interact with bodies while holding a defib. We were on Detroit/Barratry, bodies just piled up, and there was nothing we could do because roundstart cloning got yeeted.

**Reproduction**
Try to defib a body, yes, we got them below 200 damage. One person only had ~7 total injuries. Bodies were not rotting, and the power was on.

**Screenshots**

**Additional context**

**Comment by EmoGarbage404** [comment]
works on master.

**Comment by deltanedas** [comment]
yes that was fixed
