### ISSUE TITLE
New Saltern has a seriously out of date kitchen

### ISSUE THREAD

**Issue by Stealthbomber16** [space-wizards/space-station-14#16233]
## Description
Saltern's freezer has the wrong tiles, no fans or freezers, it's missing its kitchen supplies vendor and it's happy honk meal vendor.

**Comment by Scribbles0** [comment]
i'll get this fixed in #16226, give me a moment

**Comment by Scribbles0** [comment]
tiles look fine to me, i put in the new vending machines, some tinyfans and some freezer doors instead of normal airlocks
