### ISSUE TITLE
If you put a muzzle on a person, he can still scream

### ISSUE THREAD

**Issue by Ser11y** [space-wizards/space-station-14#16249]
## Description

If you put a muzzle on a person, he can still scream.

**Reproduction**

>Put a muzzle on the person
>The person screams.
>Be Caught by Security

**Screenshots**

![image](https://user-images.githubusercontent.com/99765361/236836253-e606b758-30a0-453f-8e68-a4bc2631736a.png)

**Additional context**

**Comment by deltanedas** [comment]
dupe of #14710 i think

**Comment by JoeTheJanitor** [comment]
> dupe of #14710 i think

I think that issue is specifically about screaming with the mute component, which muzzles don’t apply. They just give you the ‘mumble’ accent.

**Comment by deltanedas** [comment]
oh true

**Comment by VasilisThePikachu** [comment]
Fixed at one point
