### ISSUE TITLE
Combine device configurator into multitool

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#16241]
I think this is the preference as otherwise multitool would mostly be used for antag activities (hacking).

**Comment by juliangiebel** [comment]
Should we keep the standalone configurator after adding that functionality back to the multitool?
I've seen the argument that this allows people to have a tool for linking without the ability to hack things.

**Comment by deltanedas** [comment]
this is just adding back to multitool rather than removing standalone configurator
