### ISSUE TITLE
defib fake usedelay sprite

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#16256]
## Description
something happened when using defib, presumably happens with any two handed item that has a use delay

**Reproduction**
1. no idea but it involves defib and maybe switching hands

**Screenshots**
![21:04:40](https://user-images.githubusercontent.com/39013340/236922778-1567298c-2d04-4ae5-b974-922aaafd4080.png)

**Comment by metalgearsloth** [comment]
See https://github.com/space-wizards/space-station-14/issues/15651
