### ISSUE TITLE
cant link blast doors

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#16279]
## Description
using network configurator, blast doors cannot be linked like they used to
couldve been introduced by device overhaul or no crowbaring blast doors

**Reproduction**
1. get network configurator
2. link button, success
3. link blast door, nothing happens

**Comment by DawBla** [comment]
You can still do it if you alt click on them or right click > link defaults but the ui doesn't pop up so only default toggle link is possible
