### ISSUE TITLE
all mapped blast doors are broken

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#16280]
## Description
the buttons are linked to open and not toggle
verified on:
- meta disposals
- kettle xenoarch

**Reproduction**
1. open noor with button
2. cannot close noor

**Comment by Cheackraze** [comment]
machine linking in general seems to be broken. I cant link doors or shutters or gates, I cant fix it in mapping mode at the moment

**Comment by lexs0sa** [comment]
I tried to set an airlock to "Toggle" and it didn't work as per last night. I set it to both "Toggle" and "Closed" and it closed every time. Setting it to open/bolt/close work relatively well, but I've yet to get an airlock to toggle with the new linking.

**Comment by juliangiebel** [comment]
Machine linking is broken for shutters, blast doors and airlocks atm. Lights for example work

**Comment by deltanedas** [comment]
ok i found out why it happens
toggle and close on blast doors even when linked ingame do nothing, you can only open it

**Comment by juliangiebel** [comment]
I can take a look at fixing that tomorrow

**Comment by deltanedas** [comment]
actually might not be true, i checked meta disposals recently and it was linked to toggle (just toggle didnt work so i thought it was linked wrong)
