### ISSUE TITLE
Nukie Agent needs combat defibs

### ISSUE THREAD

**Issue by Emisse** [space-wizards/space-station-14#16299]
title
i dont want to give them regular defibs
combat defib not coded yet
todo

**Comment by VasilisThePikachu** [comment]
What is the difference with a combat defib? Guessing a different sprite first of all

**Comment by deltanedas** [comment]
probably smaller too since 50 storage gone automatically would be hell (especially for fishmedics :DDD)

**Comment by notquitehadouken** [comment]
~~any defibrillator is a combat defibrillator if you hit hard enough~~
what i've got for this is that it has a size of 15 (its just the pads), requires no battery but takes 30 seconds between uses, and cannot be turned off
the doafter takes the same amount of time and it heals the same amount of damage
it will show up in the agent's bag when i code it
please suggest balance changes
