### ISSUE TITLE
Attack modifier

### ISSUE THREAD

**Issue by Injazz** [space-wizards/space-station-14#163]
Currently we got nothing to differentiate combat/pacific interaction.
Melee component uses snowflake Arc searching, but it actually **should** be included in the interaction system's code.
suggested plan:
Pacific Interaction (help intent): Items are used according to their use, nothing ever attacks
Combat(Harm intent, Modifier key pressed once):Every item (except ranged weapons?) should hit in arc in the mouse direction
Press modifier key again to switch into Help Intent again.

**Comment by Acruid** [comment]
Completed in c4523a956da8d893297f8a46e4a9ef45bb10a6fa, yes it works for guns.
