### ISSUE TITLE
Certain shields make you less resistant to damage

### ISSUE THREAD

**Issue by liltenhead** [space-wizards/space-station-14#16302]
## Description
Shields like the buckler, take twice as much heat damage. I'm not sure it's intended to also make you take twice as much heat damage.

**Reproduction**
use a buckler, mirror shield, or clockwork shield.

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/104418166/bbd6a80e-6a80-46b0-adff-80d07b32d3c8)

**Additional context**

**Comment by deltanedas** [comment]
i think buckler makes sense since wood is flammable
the rest is probably wrong

**Comment by liltenhead** [comment]
But why would it kill you? If the shield caught on fire you'd just drop it.
