### ISSUE TITLE
Electric anomalies seem to cause massive lag.

### ISSUE THREAD

**Issue by Owai-Seek** [space-wizards/space-station-14#16301]
## Description
When electric anomalies fire off, they seem to consistently lag anyone connected. I'm not sure what exactly happens, but it seems restarting your client fixes it. Anyone else, however, will have massive performance issues until things catch up with them.

**Reproduction**
Let an anomaly have a big enough event, I guess? I'm not sure how anomalies work, I just know when the electric arcs fire off, it can freeze things for a decent amount of time, and/or cause severe lag. (Not sure if it's just FPS lag, or performance in general.)

**Screenshots**

**Additional context**

**Comment by metalgearsloth** [comment]
any console logs or profile

**Comment by TheShuEd** [comment]
Fixed after tesla update
