### ISSUE TITLE
replace no work

### ISSUE THREAD

**Issue by Emisse** [space-wizards/space-station-14#16330]
this one
![image](https://github.com/space-wizards/space-station-14/assets/99158783/63e27e1f-d7f9-4483-b0bd-7687c1a04f26)

**Comment by deltanedas** [comment]
it does work its for walls and windows (not grilles tho)

**Comment by Emisse** [comment]
jhust tested master no work

**Comment by Emisse** [comment]
lizard and local

**Comment by deltanedas** [comment]
ok well something broke it between saltern 4.3 and now since it worked then

**Comment by metalgearsloth** [comment]
> jhust tested master no work

works locally for me

**Comment by Emisse** [comment]
seems fixe
