### ISSUE TITLE
some sprites are drawn at wrong size

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#16340]
## Description
sometimes when examining people it happens
also happens to pinpointer as shown

**Screenshots**
![16:02:56](https://github.com/space-wizards/space-station-14/assets/39013340/a0bf3ff4-7e2c-42c4-a983-242e920237e7)

**Comment by deltanedas** [comment]
![12:11:37](https://github.com/space-wizards/space-station-14/assets/39013340/cff8b1f1-243e-48c8-a4e8-64507f0ed230)

lil pai

**Comment by Slava0135** [comment]
i guess this was fixed (we now have grid inventory anyway)
