### ISSUE TITLE
Refactor hotspots (fire)

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#1635]
Hotspot code is currently a hot mess.
At the moment, they're a struct inside `TileAtmosphere`. 
If `Valid` is set to true, then the hotspot is active.
This should be refactored urgently.

**Comment by DTanxxx** [comment]
Hi Zumorica,
I am keen to work on this issue. Currently Hotspot is being used in the HotspotExpose, ProcessHotspot and PerformHotspotExposure methods in TileAtmosphere class. In what ways would you like the Hotspot code to be refactored?

**Comment by Zumorica** [comment]
Honestly the current implementation is fine now and this should be closed, in my opinion
