### ISSUE TITLE
Gibbed brain travels forever

### ISSUE THREAD

**Issue by TurboTrackerss14** [space-wizards/space-station-14#16366]
## Description

Upon a person being gibbed their body will send gibs everywhere, for some reason the brain decides to ignore both gravity and air resistence and will continue going, banging into a wall repeatedly. 
it can also be redirected by the ghost reentering the brain and using a movementkey/looking (unconfirmed needs reproduction)

**Reproduction**

reporting at shift end, no real clue how to identify but I have seen it occur twice in just one shift today
**Screenshots**

https://github.com/space-wizards/space-station-14/assets/130304754/99059c9b-fe04-4e74-a05b-6709d9597f33

**Additional context**

**Comment by EmoGarbage404** [comment]
this got tucked into borg fixes
