### ISSUE TITLE
Saltern, Kettle and Moose need suit storage updating

### ISSUE THREAD

**Issue by AJCM-git** [space-wizards/space-station-14#16402]
## Description

I already notified mappers in discord but for @Cheackraze and @deltanedas , hardsuits are not available from lockers anymore so your maps need to have the new suit storage units for heads, engineering, and EVA, see this list for more info https://github.com/space-wizards/space-station-14/blob/master/Resources/Prototypes/Catalog/Fills/Lockers/suit_storage.yml

**Comment by lzk228** [comment]
solved i think
