### ISSUE TITLE
Gas tanks need nerfing

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#16420]
Jetpacks + breathing last way too long. Apparently breathing through one lasts an hour.

**Comment by deltanedas** [comment]
oxygen tanks specifically are stupidly op
using 20C air a full one lasts you like 4 hours, you never need to refill it
i have never used jetpack breathing since:
- decreases flight time slightly
- have to worry about forgetting to turn oxygen tank on when dropping

**Comment by Kayek14** [comment]
Can confirm, one regular large 02 tank found in the hardsuit containers lasted me for an entire round, about 40+ mins and i still wasn't even close to running out. Compared to the emergency airtanks you start off with, large airtanks have like +20x the capacity.

**Comment by Kromabae** [comment]
Jetpacks are balanced, maybe need some tweaking but they don't last very long if you just full blast all the time. 

large tanks last roughly 2-3hrs iirc so they are kinda fire and forget things, it's even so good that many people (including me) go find one at round start just because how far superior it is to emergency tanks. This can be solved by just restricting the suit slot to only work for hardsuits (kinda silly how a jacket has a suitslot for a large tank).

**Comment by deltanedas** [comment]
or better yet visually it has like 4-8x the capacity as emergency tank, so just make it last 20-40 mins
this will drive atmos to make supercooled oxygen tank shops which i saw ilya do once it was funny

**Comment by Kayek14** [comment]
While testing jetpacks i found out that on full blast they go from max capacity ~1013 kpa to 937 kpa. That is about 76 kpa used per minute. This means that at full blast, without stopping, a single jetpack will last roughly 13 minutes.  

The physics of using compressed air to move mass is very inefficient and would empty a tank of air *very* quickly, but this is a game and I understand some real world physics limitations should be ignored. However, I do think that a jetpack lasting 13 minuets is a little too long if we consider how strong jetpacks are.

**Comment by deltanedas** [comment]
thats not even taking gas cooling into account which makes that basically infinite

**Comment by metalgearsloth** [comment]
Apparently https://github.com/space-wizards/space-station-14/pull/17106 didn't go far enough.

**Comment by deltanedas** [comment]
if that wasnt enough then all the big emergency tanks need nerfing since double extended is 12L (large is now 15L so not much bigger)

**Comment by Kayek14** [comment]
Regular air tanks still last for an entire round. 

Just did some testing on live, one regular oxygen tank will lose about 1kPA of pressure every 30 seconds. Oxygen tanks start with788 kPa of pressure. Doing some quick math we can see that at this rate, one oxygen tank will become depleted in about 367 minutes, or in about 6 hours.

In comparison, an emergency oxygen tank will be depleted in just under 5 minutes. Regular oxygen tanks last about 73 times longer than an emergency tank.

Unless i am missing something or did some cringe math errors, it seems like oxygen tanks last even longer than before?

**Comment by deltanedas** [comment]
they only have like 6 times the volume so the inhaling might be sus

**Comment by Kayek14** [comment]
Something is a bit broky. Tested a new round with a brand new Urist and oxygen tank straight from a dispenser. 

Toggled internals and set a stopwatch, got to almost 2 hours before I had to close down the game for the day. I believe the intended change was to make regular o2 tanks last ~5x longer than emergency ones but something sus

**Comment by Vordenburg** [comment]
> Apparently #17106 didn't go far enough.

That PR only changed the volume on the empty tanks. The filled ones were left unchanged.

**Comment by deltanedas** [comment]
pro
