### ISSUE TITLE
empty puddle real

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#16436]
## Description
after drinking from puddle like 80 times it is empty
found on lizard

**Screenshots**
![18:49:20](https://github.com/space-wizards/space-station-14/assets/39013340/89d8404d-831f-469e-97ae-29c43caeb012)

**Comment by Tyzemol** [comment]
Are you sure drinking is related? Because i've not seen puddles say anything other than `Empty`

**Comment by deltanedas** [comment]
oh guess drinking doesnt matter

**Comment by EmoGarbage404** [comment]
i would imagine that examinablesolution is pointing to the wrong solution id.
