### ISSUE TITLE
cargo shuttle too big to dock in saltern

### ISSUE THREAD

**Issue by AJCM-git** [space-wizards/space-station-14#16458]
## Description
or so some dude in discord said, idk @deltanedas

**Comment by deltanedas** [comment]
im 99% sure i made the dock just big enough to fit it but ill see

**Comment by KaiShibaa** [comment]
Can confirm that the lattices block the front of the shuttle from docking. 

![image](https://github.com/space-wizards/space-station-14/assets/100050424/fdeb62c2-85c9-4126-a5b2-323ad5a49888)
