### ISSUE TITLE
examine menu poor performance

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#16486]
## Description
when examining large piles of items (see: me on botanist grindset) it can cause a slight lagspike
i have not profiled this in any way but its not related to the recent frame drops from a memory leak or something. spamming right click on a certain spot spams lagspikes

**i am purely guessing** but maybe its distance checks to each item causing the lagspike???? would need to profile it to be sure

also lagspike happens when **closing** the examine menu via left or right click
maybe closing the popup is really slow?

**Reproduction**
1. make shitload of wheat
2. spam right click
3. woah lagspike city

**Screenshots**
some f3 statistics while spamming right click, it seems to allocate a lot of memory in a loop? again would need to profile to be certain
![01:06:29](https://github.com/space-wizards/space-station-14/assets/39013340/238efc8b-f177-455d-9c46-e3845c84f7ff)

**Comment by metalgearsloth** [comment]
Profile from discord in regards to disposals though this only would cause a lag spike upon closing context menus.

![image](https://github.com/space-wizards/space-station-14/assets/31366439/afa72a12-3091-4ade-86e2-ddd75a2c7148)

**Comment by ElectroJr** [comment]
Easiest fix for this is probably to just pool the `EntityMenuElement`s instead of creating & disposing them.
Alternatively, the menu could be reworked to behave more like the entity spawn menu or storage lists, where only the currently visible controls actually exist.

**Comment by deltanedas** [comment]
visible like the hover > see all 200 individual tomatoes or each type of item

**Comment by ElectroJr** [comment]
Visible as in, visible as a UI element on screen. Things like the entity spawn menu don't actually have a thousand buttons, one for each entity prototype. Instead only the buttons that are currently visible actually exist.

But that would take significantly more work, pooling the controls would be quite a bit easier.

**Comment by metalgearsloth** [comment]
Video from whisper:

https://github.com/space-wizards/space-station-14/assets/31366439/11529363-fc05-4bd9-8291-f43cc0cbf0d9

Now I'm wondering if the lock contention is related considering it's happening on disposal?

**Comment by metalgearsloth** [comment]
Had a chat with delta and we confirmed it goes away on restart so I'm fairly sure it's some bad event unsub from 2 publishes go so going to take a look.

**Comment by deltanedas** [comment]
something fixed
