### ISSUE TITLE
Saltern Feedback Review

### ISSUE THREAD

**Issue by Emisse** [space-wizards/space-station-14#16482]
i didnt review it before it got put back into rotation and delta isnt on discord

robotics needs to be more accessible
![image](https://github.com/space-wizards/space-station-14/assets/99158783/6d0354b1-b3a6-4c17-b75f-37bc9ad78a3c)
probably just reorganize this whole area, remove lawyer probably

remove zookeeper its a map specific, wires also need to be changed to not go through the grass like this
![image](https://github.com/space-wizards/space-station-14/assets/99158783/8eb36207-b2c7-429d-9a96-3f3a23311e4a)

i know theres not a lot of spcae for suit storage but this isnt doing it for me
![image](https://github.com/space-wizards/space-station-14/assets/99158783/e956a82f-e10b-43e9-a7d8-a98c352ad6d3)

lobby could be made smaller and you could fit in 1-2 more exam rooms
![image](https://github.com/space-wizards/space-station-14/assets/99158783/876b3236-a0df-4140-9670-a144141fe5ea)

saltern doesnt really need detective
![image](https://github.com/space-wizards/space-station-14/assets/99158783/7d243657-5298-4db9-b4e7-0cfd424d4705)

this needs to be variantized/decaled
![image](https://github.com/space-wizards/space-station-14/assets/99158783/8555ccd3-e5c9-4e4c-9c62-7509965981d3)

crematorium should be moved to chaplains place and body mulcher should be put in here with drain
![image](https://github.com/space-wizards/space-station-14/assets/99158783/1ec556b9-57a7-4ebf-9dc7-8735a54ad382)

move rnd server to the left
![image](https://github.com/space-wizards/space-station-14/assets/99158783/c7b7072c-4db5-4bd5-ae93-909842d57ded)

what
![image](https://github.com/space-wizards/space-station-14/assets/99158783/a211af24-d450-4576-957d-536ed507ef67)

dont run wires under walls
![image](https://github.com/space-wizards/space-station-14/assets/99158783/6a2dc2e1-afc6-4d17-a181-e616d77e3144)

map this small shouldnt have mailing units, make people walk around
![image](https://github.com/space-wizards/space-station-14/assets/99158783/6909b634-250c-43ca-9ef0-411507442188)

**Comment by deltanedas** [comment]
real

**Comment by deltanedas** [comment]
@Emisse whats wrong with having station-specific jobs like zookeeper

**Comment by Emisse** [comment]
it was made for kettle, saltern was not built for this, tacking it into a random room in maints isnt good

**Comment by deltanedas** [comment]
oh ill remove then after current pr is merged

**Comment by deltanedas** [comment]
and @Emisse by not needing detective would that be the room itself or the role overall

**Comment by Emisse** [comment]
the role

**Comment by deltanedas** [comment]
@Emisse  what do you mean by variantized/decaled for cargo dock
