### ISSUE TITLE
Salvage expedition deletes you without warning and you cannot leave 

### ISSUE THREAD

**Issue by blueisdumb** [space-wizards/space-station-14#16493]
## Description
We used the cargo shuttle to do a salvage expedition and after we were done the shuttle wouldn't allow us to leave. We were just going to wait out the timer but the game never warned us of the timer running out and we all got despawned along with the cargo shuttle.

**Reproduction**
Go into salvage expedition with cargo shuttle
Try to leave

**Screenshots**
I've made a quick video on what happened: https://youtu.be/mdvMZTvbVHY

**Additional context**

**Comment by metalgearsloth** [comment]
shadowcommander reported that some of the announcements didn't play so it might've been the states desyncing somehow so it never progressed.

For the leaving bit I might just have it leaveable if everyone is onboard for now as previously you could leave at any time and abandon people.

**Comment by EEASAS** [comment]
> the exact same thing happened to my salv buddies on miros, and it can probably end the round due to.cargo not being available

**Comment by metalgearsloth** [comment]
Okay it's really stupid why it happens gonna fix it rn.
