### ISSUE TITLE
The solution currently has over 190 warnings.

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#1650]
We should probably address as many as we can.

**Comment by Zumorica** [comment]
I meant **BUILD WARNINGS**

**Comment by DrSmugleaf** [comment]
(He meant namespace warnings) 
![image](https://user-images.githubusercontent.com/10968691/89933212-097c9080-dc0f-11ea-8857-03828c652b60.png)

**Comment by Visne** [comment]
A lot of warnings are related to `IPhysicsComponent` being obsolete. `UpdateKinematics()` from `MoverSystem` however still it, so it would need to be changed before all warnings can be removed.
