### ISSUE TITLE
Duffel bag of holding slows you

### ISSUE THREAD

**Issue by liltenhead** [space-wizards/space-station-14#16500]
## Description
duffel bag of holding slows you and the other two don't. It probably should be an exception to the duffel speed nerf

**Comment by deltanedas** [comment]
better solution: duffel of holding has 120 storage :trollface:

**Comment by EmoGarbage404** [comment]
100019 storage space

**Comment by NonchalantNoob** [comment]
Someone can close this issue now. I think it should be patched!

**Comment by mirrorcult** [comment]
apparently "addresses" doesnt autoclose
