### ISSUE TITLE
You should not be able to instantly unbuckle yourself if you are handcuffed

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#16545]
## Description
If you are handcuffed, you can simply walk out of a chair or bed that you have been buckled to by clicking on the unbuckle icon. This makes it very hard for security to place someone into a brig cell if the prisoner is determined to keep walking out of the cell once they have been buckled to the bed.

This would be a major quality of life buff to security if they were able to secure handcuffed prisoners to beds and chairs. This would also make it easier to place prisoners into a cell. The only way to keep a determined escapee in the cell is to either stun them and quickly shut the door behind you before they get up, or to awkwardly drag and position them inside the cell while you are outside the sliding door.

**Reproduction** 
1. Handcuff a Urist.
2. Buckle the Urist to a bed.
3. Control the Urist.
4. Click on the unbuckle icon.

**Additional context**
Perhaps add a timed doafter that the cuffed person will have to wait out before unbuckling themselves.
I believe this is also how it works in ss13. You first need to resist out of the buckle to stand up and move around. Afterwards, you can resist out of the cuffs.

**Comment by forgotmyotheraccount** [comment]
as someone who isn't robust i'd love a solution to this, I hate having to soap/banana peel someone as a secoff just to ensure they don't beeline for the exit as soon as I stop dragging them

**Comment by Kayek14** [comment]
![image](https://github.com/space-wizards/space-station-14/assets/106507028/6af7500a-1b92-4fca-b8f9-631daf376691)

Seeing this now makes me think it is a bug and is unintended to be able to unbuckle yourself while cuffed.

**Comment by Just-a-Unity-Dev** [comment]
resolved
