### ISSUE TITLE
Tethergunning a locker youre in allows for extremely fast movement

### ISSUE THREAD

**Issue by AjexRose** [space-wizards/space-station-14#16567]
## Description

When inside a locker that you tethergun yourself, you move at extremely fast speeds, faster then the skeleton motorcycle. 
**Reproduction**

Step One: Get a Tethergun
Step Two: Get a locker
Step Three: Get inside Locker
Step Four: Tethergun the locker while inside it
Step Five: Point your mouse away from the locker
Step Six: Z O O M

**Comment by metalgearsloth** [comment]
Fixed in https://github.com/space-wizards/space-station-14/pull/16561
