### ISSUE TITLE
Nuke Cloning from roundstart

### ISSUE THREAD

**Issue by EmoGarbage404** [space-wizards/space-station-14#16563]
## Description

The power of nu-med marches steadily on.
We can now just replace with defibs and healing items.

Just remove these from all maps as you update them.

**Screenshots**

![Screenshot_20230518_071308_Discord.png](https://github.com/space-wizards/space-station-14/assets/98561806/8b7317ae-1b90-4630-a24e-14f3045fde54)
![Screenshot_20230518_071629_Discord.png](https://github.com/space-wizards/space-station-14/assets/98561806/5a463d7d-bfb6-4c18-a396-19b5530e12b3)

**Comment by EmoGarbage404** [comment]
> should we have boxes of t1 components like barratry

Tier one components are in vendomats and autolathes.

**Comment by deltanedas** [comment]
i think this can be closed now

**Comment by EmoGarbage404** [comment]
clonerheads stay mad
