### ISSUE TITLE
Placing down tiles mispredicts the sprite variant for the ground

### ISSUE THREAD

**Issue by EmoGarbage404** [space-wizards/space-station-14#16576]
## Description

it seems to cycle through every single variant for the tile.
**Reproduction**

- take tile
- place on plating
- watch the sprite bug out

**Screenshots**

![Content Client_JVuJiX6WUM](https://github.com/space-wizards/space-station-14/assets/98561806/5f72e3f7-c2f8-4c71-bbd7-58e6d18d4cbd)

**Comment by metalgearsloth** [comment]
Dupe https://github.com/space-wizards/space-station-14/issues/15124
