### ISSUE TITLE
Music instruments

### ISSUE THREAD

**Issue by Injazz** [space-wizards/space-station-14#166]
Similar to SS13, we can actually expand on that matter:
currently in state of research:
- [x] ability to play SMF (Standart MIDI File) platform-agnostic way
- [x] ability to connect MIDI devices
- [x] ability to stream MIDI events through network

The only package that can possibly help us achieve that is https://github.com/atsushieno/managed-midi

also what needs to be done:
- [ ] option to use SS13piano format as input (converting to MIDI ingame)
- [ ] visual editor for creating songs ingame
- [ ] recording feature for editor when using MIDI devices

Backup plan if everything is ogre:
- [ ] use ss13 piano system

**Comment by SweptWasTaken** [comment]
Instruments were disabled a while back for the CM test as they caused crashes and other problems. This issue has been reopened so we know to fix it. 

The PR that disabled instruments is #617 

We need to find a way to package fluidsynth builds with ss14 so that it works for all OS's.

**Comment by Zumorica** [comment]
Instruments were added back, so this can be closed again.
