### ISSUE TITLE
tether gun doesnt really work

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#16610]
## Description
it doesnt follow cursor at all
instead if you pull an item thats tethered then let go it applies a force or something its very weird
i think the force gun pr broke it with the locker troll fix

@metalgearsloth

**Comment by metalgearsloth** [comment]
Yeah force gun pr broke it after a bit, tstalker told me.

**Comment by deltanedas** [comment]
it seems from experimenting that the client isnt updating it with coords, it goes back to the original position
