### ISSUE TITLE
LOOC abuse by shitters

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#16622]
It's a double-edged sword because ghosts can talk to new players but also when an admin's not on for hours then you can get a shitter that can't be muted.

Not sure on the best solution but server votes or disable LOOC for dead players or something might be useful, even as a cvar.

**Comment by 0x6273** [comment]
There should be a way to mute other players.

**Comment by deltanedas** [comment]
ghosts cant looc, only crit players that arent dead yet
