### ISSUE TITLE
Saltern Issues, Requests and Feedback

### ISSUE THREAD

**Issue by luckyshotpictures** [space-wizards/space-station-14#16623]
## Description
- The bookshelfs are still empty, need to be BookshelfFilled
![Screenshot_440](https://github.com/space-wizards/space-station-14/assets/126210746/f783c9ee-6666-4210-b3a2-f27552d017e0)

- Once the Singulo runs, all the animals in the zoo die of radiation.
![Screenshot_441](https://github.com/space-wizards/space-station-14/assets/126210746/f932bad9-dbc7-403e-9fa6-2df5c014e53a)

- What is this budget kitchen at chapel, does it really need to be there?
![Screenshot_442](https://github.com/space-wizards/space-station-14/assets/126210746/0240dcbb-56b0-493c-a2fd-bc4679e65356)

- I think a Cryopod would be nice, especially once considered that there is no tech storage, and sci is forced to speedrun cloners to not *die*, which is a not optimal setup. The general lack of medicine lockers in the bay is annoying.
![Screenshot_443](https://github.com/space-wizards/space-station-14/assets/126210746/2c80d897-44df-4863-b960-cc2d4c6d6241)

- Telecomms is hilariously easy to break in, all it takes is to take out one wall and bam, you are in.
![Screenshot_444](https://github.com/space-wizards/space-station-14/assets/126210746/4ea0ef32-0cb2-4844-b67b-a4b9515631f5)

- This feels like the normal air setup, but with extra steps.
![Screenshot_445](https://github.com/space-wizards/space-station-14/assets/126210746/3c55c714-c816-45b1-bdbd-ad4895ad0aa8)

- Security has several issues:
1. There is not one, but two warden lockers. 
2. There is no detectives locker anymore.
3. The doctors locker should be replaced with a medicine locker.
![Screenshot_447](https://github.com/space-wizards/space-station-14/assets/126210746/4dba9164-186b-4bf3-8955-1ef7998490ec)

- Maints in general feels underwelming, any a bit too wide for me, but that is personal preference I guess

**Comment by Emisse** [comment]
agree with the posted

**Comment by deltanedas** [comment]
detective doesnt exist so should i just put a forensic scanner in hos room

**Comment by Emisse** [comment]
yea thats fine

**Comment by deltanedas** [comment]
also comms is piss easy to break in on any map, see:
- barratry, just hack 1 (one) door which is public or break 1 (one) wall
- moose, same deal
- kettle, hack 2 (two) doors
