### ISSUE TITLE
Disposals outlets

### ISSUE THREAD

**Issue by DrSmugleaf** [space-wizards/space-station-14#1663]

**Comment by Peptide90** [comment]
What's the purpose of this? Is it to drop the items on the floor like the trunk does? Or is it a reverse disposals unit that spits things out with some force (so they can be spaced or thrown towards a recycler / conveyor)

**Comment by deltanedas** [comment]
items not exiting a trunk are already flung

**Comment by IProduceWidgets** [comment]
I'm closing this as nondescript. I can't tell if we already have what this wants or not.
