### ISSUE TITLE
You can admin check with the restart vote panel.

### ISSUE THREAD

**Issue by Veritius** [space-wizards/space-station-14#16650]
## Description
You can see if an admin is online by opening the restart vote menu and checking if you can start one.
If there's no admins online, you can start a vote. If there's one online, you can't.
Nobody can see if you've checked like this.

this is based on my memory that it changes based on admin presence pls correct me if this is wrong

**Comment by deltanedas** [comment]
this is correct but how would you solve this without outright banning votes or making votes always allowed

**Comment by OctoRocket** [comment]
Make it so that it doesn't prevent you from running one, but when you try to start the vote it tells you you can't. This could still log the attempted start of a vote.
