### ISSUE TITLE
NukeOps AKMS

### ISSUE THREAD

**Issue by Myakot** [space-wizards/space-station-14#16668]
## Description
#16544 should not appear in nukie uplink
- It's a 1TC buy of 150 rounds for the gun that costs 12 TC
- Each nukie spawns with 40 TC, they can just **shoot** the station dead from the space, never having to step into it, with how much ammo that is.
- Now 0 reason to buy the expensive C20R or any other weapon, due to ammo advantage.

**Comment by deltanedas** [comment]
or better yet replace the .30 box with a single mag, maybe increasing price, so its 6tc for the same amount of ammo
as syndie you can still get 8 boxes for it

also in general it makes no sense that c20r bundle is 25tc but a akms "bundle" is 13tc for double the ammo

**Comment by Myakot** [comment]
It's not just the ammo issue, AKMS's caliber has more punch to it.
It's 19 damage (akms) against 16 damage (c20r).

**Comment by HoidC** [comment]
> It's not just the ammo issue, AKMS's caliber has more punch to it.
> It's 19 damage (akms) against 16 damage (c20r).

fire rate though

**Comment by Myakot** [comment]
> > It's not just the ammo issue, AKMS's caliber has more punch to it.
> > It's 19 damage (akms) against 16 damage (c20r).
> 
> fire rate though

Difference is 5>8 fire rate
Difference is 19>16 dmg
Difference is unlimited ammo>no ammo

**Comment by deltanedas** [comment]
meaning c20r has higher dps (lower ttk)
assuming ammo was fixed, the lower cost would be fine

**Comment by deltanedas** [comment]
meaning c20r has higher dps (lower ttk)
assuming ammo was fixed, the lower cost would be fine
