### ISSUE TITLE
Recycler works strangely with conveyors

### ISSUE THREAD

**Issue by Arteben** [space-wizards/space-station-14#16677]
## Description

I see that the developers attempted to make the recycler and the conveyor systems functional, but currently they are working very inconsistently. Sometimes items get stuck in the machine, other times the item does get processed but the result gets stuck in the device, and sometimes it works as intended. So, overall, it is functioning correctly in only one out of four cases.

**Reproduction**

Make conveyors and a recycler. There are 2 conveyors and the recycler between them and it should set right(reverse \ forward). Get some computer board and recycle it. I expect that on the begin of the conveyours I give the board and get a glass on end of the conveyours.
**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/2144635/ac8d834f-814d-41b8-83f6-bbddb3ad89a0)

[video.webm](https://github.com/space-wizards/space-station-14/assets/2144635/696d69fa-afa0-4156-85e9-3b17eab7cf73)

**Additional context**

I wanted to explore what could be done with conveyors and to what extent something similar to Factorio could be achieved. The idea of items moving through the conveyor, going through a recycler, and then being stored in a crate it is cool, and it could be expanded with funnels and material loaders into machines. However, currently, it is not working very well, and it is not possible to create even simple chains with it.
Maybe there are helped some buffers in the recycler and taking items not from the tile under the recycler, but from the tile in front of this.

**Comment by EmoGarbage404** [comment]
I think this is just the direction of the recycler not lining up with the conveyors. If you rotated it 180°, it should work fine.

**Comment by Arteben** [comment]
> I think this is just the direction of the recycler not lining up with the conveyors. If you rotated it 180°, it should work fine.
You're right, thanks!
I closed it!
