### ISSUE TITLE
nukies that are gibbed are counted as alive for greentext

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#16698]
## Description
if a nukie/loneop is gibbed it says minor victory even though they most certainly died

**Reproduction**
1. spawn loneop rule
2. gib loneop or invoke macrobomb's wrath
3. minor syndicate victory!!1!

**Screenshots**
![17:15:55](https://github.com/space-wizards/space-station-14/assets/39013340/3d28576f-64fb-483f-9865-2cd96704b823)

**Comment by EmoGarbage404** [comment]
This is a general issue with gibbing.
Gibbing doesn't actually count as killing an entity.

**Comment by deltanedas** [comment]
is it not that it removes the nukeop component thing so it doesnt think any operatives died

**Comment by deltanedas** [comment]
```
public static class A                                                                                                                                      
{                                                                                                                                                          
    //^.^                                                                                                                                                  
}
```
real
