### ISSUE TITLE
Initial Control Scheme

### ISSUE THREAD

**Issue by Injazz** [space-wizards/space-station-14#167]
We need to figure which actions must be bound to keys. And to which keys assign them initially. And how to press those keys and what to do actually with mouse and keyboard and trackball and VR headset and that pistol controller you took from NES. HOW TO CALL THIS ACTION?
I'll start picking actions from the top of my head(and current binds if there are any):
- Interact/Attack switch: `?`
- Examine: `Shift+click`
- Equip: `?`
- Drag: `?`
- Throw: `Ctrl+click`
- Drop: `Q - show with cursor where you want to drop`
- Grab: `?`
- Resist: `?`
- Interact with entity in world (locker,crate): `E`
- Interact with entity in hands: `Z`
- Switch hands: `Tab`
- Open inventory: `C`
- Sprint: `Shift`
- Crafting menu: `On-screen button`
- Target Doll Cycle (back and forth): `?`
- Focus Chat Window: `T`
- Console: `` ` ``
- Verbs: `Right-click on entity`
- Crafting window: `G`
- Tutorial: `F1`
- Action List: `?`
- Ghost Panel: `?`
- Admin Panel: `?`
- Sandbox Panel: `?`
### Note that this discussion is not only about "Which key should we assign by default", but also "What should user do with his keyboard and mouse to call an action".
For example, our superior platform gives us ability to perform various number of ways to handle input:
- Press key: 100+ keys, remember about laptops and Mac.
- Click: Right, Left, Middle, additional buttons
- Scroll: wheel up and down 
- Combination: Key+Click (like current examine)
- Combination: Key (visually changes the cursor's icon), then Click (like it's done for example in Starbound with tools)
- Press key while navigating the mouse on entity, without clicking (like it's done with lockers and crates currently)
- Pressing key switches the mode so click do different actions (Attack switch)
- On-screen button: like it's done with crafting menu currently
- Context menu: like verbs done currently

**Comment by Injazz** [comment]
My suggestion:
-     Interact/Attack switch: `SPACE`
-     Examine: `C` (navigate cursor on entity and press button)
-     Drag: `Ctrl+click` or `R`(navigate cursor on entity and press button)
-     Throw: `G`(navigate cursor on the direction and press button)
-     Drop: `Q` - *unchanged*
-     Grab: merge with Drag
-     Resist: `Z`
-     Toggle internals: `On-screen button when internals are equipped`
-     Interact with entity in world (locker,crate): `E` *unchanged*
-     Interact with entity in hands: `F` *unchanged*
-     Switch hands: `Wheel scroll`
-     Open inventory: `Tab`
-     Sprint: `Shift` (unchanged, maybe redo it to Walk/Run toggle like in SS13)
-     Crafting menu: On-screen button
-     Target Doll: On-screen element
-     Focus Chat Window: `T`- for talk (dropdown list to choose channels/local), `Y` for emote, `O` for OOC, `F1` for ahelp 
-     Console: `` ` `` *unchanged*
-     Verbs: `Right-click on entity` *unchanged*

**Comment by Injazz** [comment]
Resist is a status effect popup button on your HUD you can click
t.cluster

**Comment by praisenarsie** [comment]
muh hotkeys

**Comment by PJB3005** [comment]
How should we handle the distinction between activation (E) and using items?

Activation should always work, even when you have something in your hands. But would it make sense to have no distinction between attack hand and activation? So clicking with empty hand does activation, using e always does, clicking with item does not.

**Comment by Injazz** [comment]
Pretty much what you said, clicking with item does what item should do (tools, inserting materials or cards etc), but if there is no interaction between held entity and interactable entity, it should just say something like "you can't figure what can you do with <held entity> and <interactable entity>"

**Comment by PJB3005** [comment]
That's not what I meant. Should clicking without item in hand do the same thing as E (activate)?

**Comment by acvzy** [comment]
Moved [here](https://hackmd.io/96HHKT-VQ2KO91c9i75V8A?both#2019-04-07-Injazz-amp-PJB)
