### ISSUE TITLE
Need cryo

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#16716]
Not like the chem cryo, the "I'm going afk" cryo like from cit.

- Messing with SSD players is against the rules but nothing mechanically prevents this.
- This gives SSDs players somewhere to go if they want to come back besides just littering the station.

**Comment by deltanedas** [comment]
we already have this its called turning off a disposal unit and hopping in

**Comment by OttoMaticode** [comment]
> we already have this its called turning off a disposal unit and hopping in

this is EXACTLY why we need the ability to weld lockers/boxes from the inside
