### ISSUE TITLE
Clicking a seat to buckle yourself plays the buckling sound effect twice

### ISSUE THREAD

**Issue by Nails-n-Tape** [space-wizards/space-station-14#16751]
## Description

what it says on the tin. also plays when unbuckling.

**Comment by deltanedas** [comment]
the shared buckle code should only play the sound on client

**Comment by OttoMaticode** [comment]
> the shared buckle code should only play the sound on client

don't know man, when i buckle into a wooden or steel chair (or probably any other chair) it plays the sound twice.

**Comment by deltanedas** [comment]
yes im just saying a (potential) fix
