### ISSUE TITLE
Cardboard boxes can sometimes delete players inside when destroyed

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#16755]
## Description
Had an incident where a group of 3 players were inside a cardboard box. It got destroyed and somehow all entities inside the box were deleted. 

The player reporting the incident mentioned that the box closed right when they attacked and broke it. 

**Reproduction**
I was unable to recreate this via testing. All I know was that the box was being spammed opened/closed and someone inside wide attacked and when it broke everything inside was deleted. 

**Screenshots**
These were the last logs of the box
![image](https://github.com/space-wizards/space-station-14/assets/106507028/0a2922c9-421d-4926-a241-0dbc8b6aa6ce)

![image](https://github.com/space-wizards/space-station-14/assets/106507028/da27cf67-2569-4d3c-9e92-b38a6a523f96)

**Comment by deltanedas** [comment]
theres also an issue i think where if you kill someone by whacking the box it opens and does not have its colour reset even though the shader is disabled

**Comment by Mirino97** [comment]
I believe this is being abused by autoclicking an open/close command and an attack command at the same time, which apparently deletes the person inside the box reliably and easily.
Happened again on round #30762, I'll try to get the replay when it's ready.
