### ISSUE TITLE
Move Virtual Controllers to use Force instead of setting Linear Velocity directly.

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#1676]
So, here's a fun issue!

Right now, when you get moved around due to atmos pressure differences, the virtual controller for this sets a LinearVelocity. 
Of course, this linear velocity must be unset sometime, so in the update method it is deccelerated as long as you're not weightless.

Notice a flaw?

If you get spaced due to atmos and then try throwing items to get yourself back to the station... You'll quickly notice it doesn't work.
This is why we should move virtual controllers to use forces, so we can do newtonian movement.

**Comment by PaulRitter** [comment]
deprecated

**Comment by DrSmugleaf** [comment]
The fifth incursion was defeated by PJB
Good night

**Comment by Zumorica** [comment]
reeee momentum moment when?

**Comment by DrSmugleaf** [comment]
> reeee momentum moment when?

WYCI got em
