### ISSUE TITLE
salvage expedition anti troll is broken

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#16767]
## Description
nearly always it will say not all salvagers on shuttle even if they are

it counts unidentified humans i think

**Reproduction**
1. go expedition
2. see unidentified human
3. complete it duh
4. repro????

**Comment by metalgearsloth** [comment]
Ugh guess I need to track who shows up there if humanoidappearance isn't enough.

**Comment by deltanedas** [comment]
no it is enough i fixed it

even if you summon a reinforcement on an expedition, so long as he doesnt die, he is included in leave no dwarf behind
