### ISSUE TITLE
cant fill empty bucket by dragging

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#16766]
## Description

You cannot fill a bucket, mop bucket or trolley by dragging it if it is empty.
First, you need to fill the bucket once with a blue bucket, and then you will be able to fill it to the top by dragging.
**Reproduction**

1. Drag empty mop bucket on water tank
2. Dont work

**Screenshots**

**Additional context**

**Comment by thebadman4662** [comment]
Chemistry got hit by this bug/rework introduced 8-9 days ago too, as you no longer can jugmix by dragging either.
