### ISSUE TITLE
mouse is basically jetpack

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#16782]
## Description
throw mouse in space to go ftl

**Reproduction**
1. find mouse
2. go outside
3. throw him
4. nyoom

**Comment by deltanedas** [comment]
also happens to a more extreme extent with floodlights you actually go like 40m/s or something crazy

**Comment by metalgearsloth** [comment]
I made throwing scale by mass but apparently our mass is whacky so this just needs capping or adjust it so the thrown force is proportional.

**Comment by deltanedas** [comment]
also i cant imagine powersink i think it has the most mass for a throwable item
