### ISSUE TITLE
Spray bottle should probably cap transfer amount

### ISSUE THREAD

**Issue by liltenhead** [space-wizards/space-station-14#16794]
## Description
You can put polytrinic acid in a spray bottle, set transfer amount to 50. With a normal spray bottle you can two hit kill anyone, and with a mega spray you can one hit kill anyone.

**Reproduction**
Put polytrinic acid in bottle, set transfer to 50, click someone.

**Additional context**
Might be other ways to fix this problem. This was just the first thing I thought of.

**Comment by EmoGarbage404** [comment]
the transfer amount shouldn't be impacting how much liquid goes in each spray. It should affect things like pouring liquid into the bottle, etc.

**Comment by liltenhead** [comment]
Well it affects something, cause its spraying more chemicals.
