### ISSUE TITLE
Action buttons and quick bar

### ISSUE THREAD

**Issue by Injazz** [space-wizards/space-station-14#168]
As an antagonists, or different species, or with mutations, you often have the access to actual *abilities*, such as spells, powers, or just things you can do with equipped items without taking them into hands slot.
All those actions are on-screen buttons on top of the screen which is always an actual list of abilites you currently have.
But we can also make their usage easier, introducing players to customizable quick action panel, when they can assign ability a key in-game!
![Снимок экрана 2019-03-28 в 18 38 02](https://user-images.githubusercontent.com/43905364/55165001-6f898480-518e-11e9-8306-33bb10e199e2.png)
when the ability disappears (for example in concept-art above we unequip our radio), the icon becomes greyed out, the number became red, showing user this ability is not accessible now.
![Снимок экрана 2019-03-28 в 19 11 59](https://user-images.githubusercontent.com/43905364/55165164-b5dee380-518e-11e9-82f1-07e5c0833ee8.png)
also can visualize cooldowns and cast costs (concepts later)

**Comment by praisenarsie** [comment]
i present an alternative
action buttons will still exist however the quick/hot bar will be implemented into the action buttons
say you alt click a button and then press a number, then the action button is binded
you could also add a preference to remove the bind if the action button disappears (due to not holding items or etc)
or you can make this entire alternative a preference

**Comment by Acruid** [comment]
This is the Toolbelt/Hotkey feature in https://github.com/space-wizards/space-station-14/issues/18.

**Comment by Injazz** [comment]
@Acruid no, toolbelt doesn't even make sense since we implemented inventories already

**Comment by metalgearsloth** [comment]
Implemented in https://github.com/space-wizards/space-station-14/pull/2710
