### ISSUE TITLE
Salvage expedition loot needs balancing

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#16810]
Now that explicit rewards are coming back in I'm thinking

- Make rare loot the explicit reward to encourage finishing missions (e.g. the server board, rare chems)
- Mining should always be present as a side hustle
- Could potentially have chem plants as a side hustle in the future
- Loot on missions should be stuff like salvage gear, artifacts, tech disks or other medium-tier items that people won't lose sleep over leaving.

At least the above seems the easiest way to not turn it into too much spaghet and means salvage is less incentivised to open every single crate on a mission trying to find rare loot (plus means we can drop the timer slightly if we want).

**Comment by deltanedas** [comment]
@metalgearsloth im doing this right now and got some design questions:
- rewards should be a weightedRandom listing possible prototypes to send yes
- does every reward need to be in a crate? for example i have stacks of gold and silver as mid tier rewards but making a crate for each is a bit silly
- if not, should xray cannon and so on for high tier rewards (which i think you want removed from just finding randomly in dungeons?) be in armory crates like smg/laser or on their own?

**Comment by metalgearsloth** [comment]
> rewards should be a weightedRandom listing possible prototypes to send yes
yeah sure
> does every reward need to be in a crate? for example i have stacks of gold and silver as mid tier rewards but making a crate for each is a bit silly
No. Also I'd probably avoid ore given oreveins exist.
> if not, should xray cannon and so on for high tier rewards (which i think you want removed from just finding randomly in dungeons?) be in armory crates like smg/laser or on their own?
These can be on their own (xray should also probably be researchable if not).
> how to make cargo product not orderable
We just need a way to dynamically make cargo orders instead and bypass cargo product when it comes to receiving the product I think.

**Comment by deltanedas** [comment]
i had a look at the cargo system and i think orders would need separate data for requested orders and approved orders
getting this to play nicely seems out of my ability so i wont be doing rewards until that is
