### ISSUE TITLE
Get rid of 1 unit = 100 cm3 from lathes

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#16819]
## Description

Just make it say 1 unit, there's no point in this conversion and it's not consistent with stacks
**Reproduction**

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/43253663/58bf8a6d-a67b-4175-b425-e45647c6294c)

**Additional context**

**Comment by OttoMaticode** [comment]
agreed. very hard to communicate to new players unless they see the conversion directly.

**Comment by OttoMaticode** [comment]
then how will lathes print items that aren't integers of 100 material?

**Comment by deltanedas** [comment]
0.5 sheets

**Comment by OttoMaticode** [comment]
> 0.5 sheets

then we'd have to turn the item amount variable (for ALL items, possibly) from int to float, which from my experience is a VERY bad idea for something that's used so widely.

**Comment by deltanedas** [comment]
or better yet dont change anything codewise just have it be ui that divides by 100
so instead of Steel 1500cm3 be 15 steel

**Comment by CaptainSqrBeard** [comment]
> > 0.5 sheets
> 
> then we'd have to turn the item amount variable (for ALL items, possibly) from int to float, which from my experience is a VERY bad idea for something that's used so widely.

Chemistry already uses float values to store amount of reagents and has no issues with it

**Comment by metalgearsloth** [comment]
Chemistry uses FixedPoint2 which is an int.

**Comment by deltanedas** [comment]
is there any reason to not use fp2 since cm3 still needs to be rounded e.g. when upgrading matter bins so precision isnt an issue
