### ISSUE TITLE
belt price trollable

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#16814]
## Description
darin parker, quartermaster

:trollface:

**Comment by EmoGarbage404** [comment]
this issue needs more information

**Comment by OttoMaticode** [comment]
> ## Description
> darin parker, quartermaster
> 
> :trollface:

what did they mean by this?

**Comment by deltanedas** [comment]
you can print utility belts for money like wrenches/apc could

**Comment by deltanedas** [comment]
also i think intercom too

**Comment by DawBla** [comment]
If finished products sold for as much as the raw materials, factories wouldn't exist

**Comment by deltanedas** [comment]
a qm i saw quoted 12k of intercom boards for 1.5k plastic
clearly its too unreasonable
also a pr already nerfed most things just a few slipped through the cracks

**Comment by OctoRocket** [comment]
Factories shouldn't exist, they are alert being patched out.
