### ISSUE TITLE
Don't use DateTime for lobby timing

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/space-station-14#1681]
`DateTime` is used because I didn't quite know what the hell I was doing when I wrote it. It'd be better if it used tick timings instead.

**Comment by DTanxxx** [comment]
Hi PJB3005,
I am keen to work on this issue. There is a GameTiming class which is currently being used by Unit Testing and no other classes. If GameTiming is not exclusively for unit testing, can I replace all occurrences of DateTime (except those in RobustToolBox as they are used for logging date information) with GameTiming? I can start the timer as soon as ServerGameTicker and ClientGameTicker are initialised and work from there.

**Comment by DTanxxx** [comment]
So what is your take on this?

**Comment by metalgearsloth** [comment]
@DTanxxx Use IGameTiming instead which is used a lot.
