### ISSUE TITLE
manifest isnt updating job title if you change job preset and then title

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#16828]
## Description

If you change a job preset and change the name of the job, then this name will be saved only in the ID-card, and in the manifest will be the name of the preset
Also, if after that you change some access (add or remove), then the job name will change in the manifest

Works normally if you just change job name without changing preset

**Reproduction**

1. Change job preset on ID 
2. Change job name on ID, new job name not saved in manifest
3. Add/remove one access, new job name is now displayed in manifest

**Screenshots**

**Additional context**

this issue arose somewhere in january, before that the name was saved normally

**Comment by Synthestra** [comment]
Can replicate

**Comment by lzk228** [comment]
> Can replicate

can you please provide video?
1. change roundstart scientist to medic
2. show manifest
3. change job name to "genesist"
4. show manifest
(i cannot because haven't pc)

**Comment by lzk228** [comment]
oh nvm i thought you mean that issue resolved
