### ISSUE TITLE
Accent component that changes the font used for chat

### ISSUE THREAD

**Issue by juliangiebel** [space-wizards/space-station-14#16839]
## Description

![image](https://github.com/space-wizards/space-station-14/assets/8915246/dc05b11d-1f6a-4dbd-8729-fae1b1839fbc)

Accents need to be able to modify or add something to the message wrap for that.
```cs
name = FormattedMessage.EscapeText(name);
        var wrappedMessage = Loc.GetString("chat-manager-entity-say-wrap-message",
            ("entityName", name), ("message", FormattedMessage.EscapeText(message)));
```

**Comment by mirrorcult** [comment]
possible with speech verbs
