### ISSUE TITLE
mice and spoders can spawn on centcom

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#16836]
## Description
title
might affect other things idk

**Comment by Kayek14** [comment]
I think this only happens if the centcom map gets unpaused, but im not 100% sure.

**Comment by metalgearsloth** [comment]
It's unpaused now

**Comment by deltanedas** [comment]
previously it was only unpaused when evac arrived at the station so it wouldve been extremely rare to get centcom events

**Comment by deltanedas** [comment]
this also happens to evac, saw solar flare destroying all the lights on evac before it came

**Comment by deltanedas** [comment]
fixed by thing probably
