### ISSUE TITLE
carp ai should be smarter

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#16834]
## Description
- on salvage wrecks carp ignore anyone in space unless theyre within the same tile or so
- on expeditions carp dont try to break windows or anything to chase players (they cant pry doors so theyd have to break doors too if there are no windows) - would also affect fishops
- carp love to wander off of grids by flying off the edge for some reason???

**Comment by metalgearsloth** [comment]
- Their space movement needs to feel more like magboots, same with space bears
- space carps need the same stuff xenos have for breaking stuff (maybe just add it to simplemobbase)
- space pathfinding is hard for the last one but I might tackle it with pathfinder refactor.

**Comment by deltanedas** [comment]
adding to simplemobbase would probably make shiva/cats break windows to get to mice - not good
