### ISSUE TITLE
Carps can bite players through lockers

### ISSUE THREAD

**Issue by Flareguy** [space-wizards/space-station-14#16831]
## Description
What it says on the tin.

**Reproduction**
1. Jump in locker to escape angry space carp
2. Watch as the carp somehow bites through the locker and kills you, without damaging the locker at all

**Additional context**
Found on Wizard's Den Lizard US West

**Comment by metalgearsloth** [comment]
Dupe https://github.com/space-wizards/space-station-14/issues/11636
