### ISSUE TITLE
The nuke that spawns in the nuclear operative's shuttle requires the disk to be dragged or moved

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#16844]
## Description
The NuclearBombUnanchored in the nukie shuttle spawns anchored to the floor. You need to insert the disk and toggle bolts twice to "reset" it before moving being able to drag it.

**Reproduction**
Spawn in the NuclearBombUnanchored endid. 
You wont be able to move it unless disky is inserted. 

**Screenshots**
This is the bomb that spawns in the nukie ship. You can see it is the unanchored version and that the anchored button is toggled off. You still cant move it unless you first insert the disk and toggle the anchors twice.
![image](https://github.com/space-wizards/space-station-14/assets/106507028/d3f2f92a-9e1d-41f9-8c80-318da0d05009)

**Additional context**
Not sure if this was intended as a balance change, but with the removal of the turrets anyone can steal the shuttle now. If the shuttle gets stolen the nukies cant get back to their nuke and the round gets stalled.

**Comment by deltanedas** [comment]
![103238](https://github.com/space-wizards/space-station-14/assets/39013340/f10308dc-b3c3-4935-a461-5894ea7dd149)
something else thats weird, the ui is fucked on unanchored prototype (right)
