### ISSUE TITLE
Shuttle sounds playing at incorrect position

### ISSUE THREAD

**Issue by liltenhead** [space-wizards/space-station-14#16859]
## Description
Cargo shuttle crashing into the station seems to play the audio at 0,0 or near it. 

**Reproduction**
Crash a shuttle into the station, audio seems to play around 0,0 if you're not actually near the shuttle when it crashes.

**Additional context**
Decals also seemed to randomly show up at 0,0 but not sure that's related.

**Comment by metalgearsloth** [comment]
Audio rework fixes it.
