### ISSUE TITLE
holo speaking is too metagamable

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#16863]
## Description
a holo whispering 8 tiles away through meters of steel can still be instantly recognized as a holo, even if you have no idea what its saying
on lrp this is generally seen as a valid salad alarm and everyone starts screaming holo

possible solutions i have in mind are:
- when holo is hidden, anything it says has the name of the owner so it seems like the owner is talking to someone or themself which is much less suspicious than seeing HOLO-xyz
- a holo cannot speak, communicating only telepathically to its owner. this is a lot more powerful than above but more useful

**Comment by malchanceux** [comment]
Owner and holo should be able to speak telepathically to each other and it should not display the speech bubble when talking with holo

**Comment by Slava0135** [comment]
resolved by #17898
