### ISSUE TITLE
When buckled to some chairs, chair is render on top

### ISSUE THREAD

**Issue by Geekyhobo** [space-wizards/space-station-14#16877]
## Description

See Reproduction

**Reproduction**

Just sit in a pilots seat that is on the same axis as you, the chair will be rendered on top 

**Screenshots**

**Additional context**

**Comment by Geekyhobo** [comment]
Fat fingered enter

**Comment by lzk228** [comment]
screenshots?

**Comment by deltanedas** [comment]
try all rotations, one that occludes you will obviously draw above

**Comment by Alekshhh** [comment]
can confirm it does happen, notably on pilot seats but not sure if any other
