### ISSUE TITLE
handheld anomalies cannot be scanned

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#16871]
## Description

**Reproduction**

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/43253663/6603b9a4-0560-4949-bdf7-9204e49015c6)

**Additional context**

**Comment by deltanedas** [comment]
they can you probably just threw it beforehand, you have to pick it up and place it down again

**Comment by crazybrain23** [comment]
> they can you probably just threw it beforehand, you have to pick it up and place it down again

This is true, the issue is actually that thrown artifacts can't be scanned.

**Comment by EmoGarbage404** [comment]
> > they can you probably just threw it beforehand, you have to pick it up and place it down again
> 
> This is true, the issue is actually that thrown artifacts can't be scanned.

isn't this just like a component? Collision Wake or something
