### ISSUE TITLE
wrong item icon size reproduction

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#16898]
## Description
found a way to reproduce the wrong item icon size thing using banana

**Reproduction**
1. pick up a banana peel
2. pick up a banana and eat it
3. new banana peel is small
4. switch hands and drop other banana peel
5. the new banana peel gets correct size

**Screenshots**
![15:35:06](https://github.com/space-wizards/space-station-14/assets/39013340/63f94138-a74a-43e8-a0ec-14e70a60fbfa)
![15:35:12](https://github.com/space-wizards/space-station-14/assets/39013340/f70eff64-8827-4046-8e45-b5f8136228ed)

(ignore item cooldown thing its defib bug)

**Comment by ElectroJr** [comment]
Repro steps don't seem to work

Uploading Content.Client_xcGUnhcxth.mp4…

**Comment by deltanedas** [comment]
maybe it was an old thing in lizard idk
