### ISSUE TITLE
north star glove message should be truncated

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#16912]
## Description
shouldnt be able to put the whole ass gnu/linux copypasta in it

**Screenshots**
![21:08:55](https://github.com/space-wizards/space-station-14/assets/39013340/0409ab60-11fa-4537-bbdb-601e9d9ba405)

**Comment by metalgearsloth** [comment]
@HerCoyote23

**Comment by HerCoyote23** [comment]
Yeah I saw. On my way home from a trip, I'll fix it tonight or tomorrow.
I think I added a chat limit when I was making them, but lost it when I reverted to an earlier commit.
