### ISSUE TITLE
Salvage magnet not working correctly

### ISSUE THREAD

**Issue by liltenhead** [space-wizards/space-station-14#16924]
## Description
Seems the salvage magnet either fails to work at all, or only pull in tiny salvages right now. Noticed it while adminning earlier. The magnet was even moved to the outer edge of the station and was still failing. 

**Reproduction**
Use the magnet, and wait a few seconds.

**Comment by deltanedas** [comment]
![12:45:39](https://github.com/space-wizards/space-station-14/assets/39013340/2f4f4c73-252a-4c76-87dd-c59a90f2833f)
testing on master i got even station wreck

snopes factcheck: fake

**Comment by lexs0sa** [comment]
It's been happening literally all day yesterday. It's not that it won't pull in debris, it's just exceedingly rare. My entire shift last night was "failed to pull in a debris" then when it did, it was a crapshoot if it was even a real debris - most of them were the DnD room, tiny asteroid, and we got *1* medical/thruster debris. There is definitely something wrong with it.

**Comment by deltanedas** [comment]
i had magnet on aspid on miros fail to pull in a wreck today, probably something in engine that fucked its range check somehow

**Comment by metalgearsloth** [comment]
I'm like 70% sure https://github.com/space-wizards/RobustToolbox/pull/4094 will fix but need to confirm after versioning.

**Comment by metalgearsloth** [comment]
So to be clear is the salvage spawning or not spawning, coz small stuff doesn't show up on the magnet and if nothing spawns then the magnet would never go active.

![image](https://github.com/space-wizards/space-station-14/assets/31366439/3de1393e-4678-4d0f-bec2-e967ca60b89b)

(Also someone remove this shittle from the pool)

**Comment by liltenhead** [comment]
I think it was fixed, haven't seen complaints. It would say the magnet failed to pull anything in every time. Some times it would be a tiny one.
