### ISSUE TITLE
Fix mismatched case for Audio folders

### ISSUE THREAD

**Issue by ShadowCommander** [space-wizards/space-station-14#1693]
A bunch of the audio folders have upper/lower case when in the code it's different.

Find the correct case for the resource folders and apply that to the code references.

**Comment by Zumorica** [comment]
Still an issue for a bunch of paths, I imagine. So reopening.

**Comment by DTanxxx** [comment]
Hi Zumorica, 
I found the mismatched case. It was an audio file name that begun with an uppercase letter.
