### ISSUE TITLE
Xeno warding tower needs physics

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#16973]
Currently it's ignored on the pathfinding graph.

**Comment by Vordenburg** [comment]
I spawned one (XenoWardingTower) on master and it has a bounding box and is placing breadcrumbs appropriately. It has a Physics component with Fixtures defined. Seems to be working. Checking through the history of the file, I couldn't find a point at which it didn't have Physics & Fixtures.
