### ISSUE TITLE
Remove restart votes to be used by players. 

### ISSUE THREAD

**Issue by KaiShibaa** [space-wizards/space-station-14#16978]
People have been abusing this lately not for bugs or glitches or perhaps the server broke but instead use it because they don't like a certain map or other calls (dying and calling for restart)

It's become frequent and honestly sucks when someone selfishly calls for it when things don't go their way. 

If something happens to the server or some glitch happens to make it unplayable, there are other ways to restart the server than relying on random players.

**Comment by deltanedas** [comment]
apply for miros 24/7 admin :trollface:

**Comment by GoodWheatley** [comment]
agree with ninruB, this is needed as a failsafe
