### ISSUE TITLE
Salvage elimination needs nerfed versions of mobs

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#16989]
- Dragon still has all of its portal shit that should probably just be natural spawns (also it does the roar etc etc).
- Xeno queen I think I already nerfed way back when so is probably fine.

**Comment by deltanedas** [comment]
queen is fine yeah
surprisingly, on ecpeditions ive done, dragon is somewhat tame though most of the time it was ai???

**Comment by metalgearsloth** [comment]
I don't think the NPC faction is hostile to people NGL, at least it wasn't last year.
