### ISSUE TITLE
Saltern's evac shuttle can dock at salvage's dock

### ISSUE THREAD

**Issue by forgotmyotheraccount** [space-wizards/space-station-14#16999]
Not ideal if you don't have an EVA suit

![20230531185220_1](https://github.com/space-wizards/space-station-14/assets/133569389/6c7c7a7e-9132-4941-b976-d7a4bc6c5b66)

**Comment by deltanedas** [comment]
arrivals is meant to dock at arrivals but grilles or some shit blocks it ill probably just extend it

**Comment by Aisu9** [comment]
Salter just need a proper evacuation area

**Comment by deltanedas** [comment]
it needs a better arrivals area rather, it was made before arrivals shittle  was a thing
