### ISSUE TITLE
Stun baton seems to be broken

### ISSUE THREAD

**Issue by ike709** [space-wizards/space-station-14#1700]
Tried and failed to stun someone, nothing happened. Tried with combat mode enabled and disabled.

And yes the stun baton was turned on.

**Comment by Zumorica** [comment]
Was it powered?
Also stun batons have a chance to not stun. If they don't, they apply slowdown instead.
Trying to stun someone with slowdown has a greater chance of stunning.

**Comment by ike709** [comment]
Literally nothing happened and I tried multiple times. And yes it was, unless the on sprite and off sprite are switched.

**Comment by nuke-makes-games** [comment]
i'll take a look

**Comment by nuke-makes-games** [comment]
Seems fine to me. Spawned an urist and smacked him with it set to stun then possessed him, the stun status effect was active.

**Comment by Zumorica** [comment]
It's not broken.
