### ISSUE TITLE
Many ghosts spawning at (0,0)

### ISSUE THREAD

**Issue by exp111** [space-wizards/space-station-14#1701]
![grafik](https://user-images.githubusercontent.com/17885980/90322873-f3960500-df59-11ea-957e-a76f18840835.png)
Maybe only in SSS

**Comment by Visne** [comment]
I don't think it's just SSS, I've seen this before SSS was a thing

**Comment by Zumorica** [comment]
yes, it's not an SSS thing

**Comment by Acruid** [comment]
The ghosts of players in the lobby seem to not not get cleaned up when the round starts.
