### ISSUE TITLE
Expedition carps aren't the same faction

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#17022]
Means they stack.

**Comment by deltanedas** [comment]
the navigation avoidance thing, would it basically be copypasting xenos one

**Comment by metalgearsloth** [comment]
Yeah, if mobs are on the same faction they avoid stacking but if not they ignore each other.

**Comment by deltanedas** [comment]
@metalgearsloth from reading it they are all in the SimpleHostile faction (from base carp)
is there a htn task they are missing?
