### ISSUE TITLE
SSS role should be more prominently displayed to the player

### ISSUE THREAD

**Issue by ike709** [space-wizards/space-station-14#1702]
It's easy for it to get lost in chat. Maybe some kind of role indicator should be included in the HUD?

**Comment by exp111** [comment]
Maybe show in the "C"/Character menu?
![grafik](https://user-images.githubusercontent.com/17885980/90339789-75863c80-dff3-11ea-90f4-497800c84958.png)

**Comment by Zumorica** [comment]
My idea was adding a big label to a corner of the screen that says either "TRAITOR" or "INNOCENT" like in TTT.

**Comment by exp111** [comment]
yes, but we can also show it there (as we probably need that at some point too)

**Comment by Visne** [comment]
Could also include list of other traitors if you are one.

**Comment by AJCM-git** [comment]
Should also say if you are a traitor or an innocent every time you restart the client

**Comment by ShadowCommander** [comment]
It'd also be nice to have a title popup like where large text shows up in the center of the screen for a few seconds.

It'd make it clear to the player what role they have.

Bonus would be if it minimised into the Character menu if that's where it's also displayed.
