### ISSUE TITLE
Admin ghosts don't get feedback if they're too far away to open a UI

### ISSUE THREAD

**Issue by Chief-Engineer** [space-wizards/space-station-14#17060]
#16955 allows ghosts to bypass interaction range checks but doesn't bypass UI range checks, which happen in RT. The range check bypass causes everything to be highlighted green when hovered over and to have UI verbs added to context menus when there's a UI, even if the player is too far away to open the UI.

This isn't an issue for players since they can't currently open UIs as ghosts, but it does mean that admins don't get feedback about if they can interact with UIs. The ideal fix would be to allow them to bypass UI range checks, but doing something like adding another highlight color may be acceptable.

**Comment by Emisse** [comment]
i do think adding another highlight color would be useful for this

**Comment by PJB3005** [comment]
The better fix would obviously be to make the range checks flexible RT-side so this isn't an issue anymore.
