### ISSUE TITLE
Admins can't search station records

### ISSUE THREAD

**Issue by Chief-Engineer** [space-wizards/space-station-14#17086]
## Description

Admins don't have a way to search station records without creating or using a console on the station, which is not ideal. Either having one on centcom that can work or adding one to the admin actions menu would fix the issue. Spawning one on centcom doesn't let you access station records, I haven't checked but I'm guessing it's because it gets the station to check from the grid it's on.

**Comment by deltanedas** [comment]
is adding intrinsic ui as simple as copy pasting the 2 things then replacing or do you need to add a special action for it
