### ISSUE TITLE
Entering disposals doesn't break joints?

### ISSUE THREAD

**Issue by Chief-Engineer** [space-wizards/space-station-14#17083]
## Description

Info is based of an ahelp so may not be entirely reliable, but someone had the bug that causes them to stay connected to someone else. They tried to fix it themselves by going through disposals, but were then teleported back to the exit if they got too far away from it. I was able to fix it by deleting their joints so apparently going into disposals didn't.

I think going into disposals used to break all joints, I'm not sure if or why somethings changed. Making disposals break joints won't fix the root issue, but disposals not breaking joints might cause other issues.

**Comment by deltanedas** [comment]
do other things like buckling to a chair or entering a locker break joints?

**Comment by metalgearsloth** [comment]
So joints no longer implicitly break on container change (whether it did or not was inconsistent so engine just doesn't do it at all) and disposals should manually break it.
