### ISSUE TITLE
Segways interact weirdly with their riders wide attacks

### ISSUE THREAD

**Issue by TemporalOroboros** [space-wizards/space-station-14#17096]
## Description

There are a couple of issues here:
1. Using a wide attack in an segway will rotate the attack by however much the Segway is rotated. IE: if the segway spawned facing south, it is now facing west, and you try to attack to the north you will instead attack to the east.
2. Segways soak up their riders wide attacks. If you try to use a wide attack in one the Segway will take the damage and everything outside of it will be shielded from harm.
3. If the rider of a Segway destroys the Segway they are riding they will visually teleport to (0, 0, 0°) of the grid they were riding the Segway around. This effect is only visual as the transform component still maintains their actual location and their PVS bubble doesn't follow them. Any movement immediately snaps them back to their real location/rotation.

**Reproduction**

1. Buy a Segway.
2. Ride the Segway.
3. Wide attack with any weapon at any target other than the Segway.
4. Observe issues 1 and 2 in action.
5. Continue until the Segway breaks.
6. Observe issue 3.

**Screenshots**

**Additional context**

The last issue probably has something to do with the LastPosition/LastRotation vars for lerping in TransformComponent. VV indicated that they were 0, 0, 0° after the visual glitch and setting the component to actively lerp immediately fixed the issue.

It also appears to have some other condition for activating as destroying the Segway without first driving it around does not manifest the bug. Single light taps southward did not cause the bug*, but it manifested after rattling around in a single tile railing cage for a couple seconds*.  It might have something to do with rotation?

*Followed by wrecking the Segway with wide attacks.

**Comment by TemporalOroboros** [comment]
This effect works with any vehicle that currently shows up when you plug "vehicle" into the search field of the entity spawning panel.

The unicycle is a bit finicky, you can hit things other than the unicycle, but to do so consistently you need to be holding still and basically overlapping with the thing you're trying to hit.

**Comment by Pangogie** [comment]
Vehicles removed awaiting better implementation.
