### ISSUE TITLE
Aspid Station janitor closet has zero access to water

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#17112]
## Description
There are zero sinks or water tanks in located inside the janitor closet on aspid station. 

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/106507028/b3bbed84-dd98-4f37-8240-cb98413718ba)

**Additional context**
Janitors have to scrounge for regular water tanks in maintenance or bug other departments for water before they are able to clean up spills.

**Comment by lzk228** [comment]
is that already fixed?

**Comment by lzk228** [comment]
![IMG_20231108_143748](https://github.com/space-wizards/space-station-14/assets/124214523/8325eea9-f186-4e31-999a-c8e62509d81b)
yes
