### ISSUE TITLE
Janitor trolley is acting weirdly unintuitive or broken

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#17113]
## Description
Clicking on the janitor trolley with a filled bucket does nothing.
Clicking on a trolley with a empty mop wont wet the mop.
Clicking on a trolley with a mop with both water and spill liquids does nothing. 

Dragging a bucket onto a empty trolley gives you the message *The bucket is full* even when the bucket is not full.
Dragging a empty bucket onto a full trolley gives you the message *The bucket is empty*
Dragging a full trolley onto a empty bucket gives the message *The trolley is full*

Dragging an empty trolley onto a water tank will give you the message *the trolley is empty*
Dragging a not empty trolley onto a water tank will fill up the trolley.

So if you completely empty your trolley it gets bricked and you are unable to fill it up again.

**Screenshots**
Dragging a not full bucket onto a empty trolley.
![image](https://github.com/space-wizards/space-station-14/assets/106507028/f23941bd-91f2-49fa-b28d-6083f32b8a84)

Dragging an empty trolley onto a water tank:
![image](https://github.com/space-wizards/space-station-14/assets/106507028/0d379736-aaf9-4b03-8abc-05fad9ce7c1a)

Dragging a trolley filled with 10 units of water onto a water tank before/after
![image](https://github.com/space-wizards/space-station-14/assets/106507028/93b34508-ac66-4c6e-aed8-9296236a17b8)
![image](https://github.com/space-wizards/space-station-14/assets/106507028/167587f2-3d27-42c1-a79a-9daf0eb0d18b)

**Additional context**
Usually when you drag a container to a water source it will attempt to put what is in the container you are dragging into a water source. It is backwards with a trolley. When you drag a trolley onto a water source it takes the water from what you are dragging to and puts it in the trolley(if the trolley is not empty.)

**Comment by Luxzhv** [comment]
Really hope this gets fixed. This has been very annoying for a while.

**Comment by ChilbroBaggins** [comment]
Like Themias mentioned, it's related to the storage. You can confirm this by removing the storage comp. You will be able to wet the mop w/out it. 

Even though the mop and bucket are blacklisted, it only tries to put them in storage and when it can't it doesn't go further and look to the bucket of water container.

**Comment by Kayek14** [comment]
This issue seems to be resolved.
