### ISSUE TITLE
expeditions give way too many mats

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#17122]
## Description
you can get like 30 stacks of mats easily from a single expedition
gives no real reason to mine or buy materials

i think its a combination of 3 things:
- the rooms have too many loot spawners mapped
- loot spawners are usually mats
- "rewards" are usually just stacking like 4 mat crates in a row in a single room

once rewards exist mats should be made much rarer so 3 stacks of plasteel is a good find rather than something to nearly ignore

**Comment by Equivocateur** [comment]
Expeditions should ~~give rewards other than an nearly endless supply of mats~~ be reworked, as it stands they are too easy to do and are basically loot dispensers the moment salv obtains guns and ammo.
![image](https://github.com/space-wizards/space-station-14/assets/109166122/c01105c0-fd1d-423e-ac60-0b1fde9980aa)

**Comment by metalgearsloth** [comment]
> Expeditions lootgen should ~give rewards other than an nearly endless supply of mats~ be reworked, as it stands they are too easy to do and are basically loot dispensers the moment salv obtains guns and ammo. ![image](https://user-images.githubusercontent.com/109166122/243189572-c01105c0-fd1d-423e-ac60-0b1fde9980aa.png)

Lootgen is getting culled so that one's easy.

**Comment by deltanedas** [comment]
yeah that screenshot shows the stack of mat crates that spawns in a line, not very good

**Comment by Cheackraze** [comment]
Are crate spanners creating multiple copies of the crates? Could be a contributing factor. Similar to the double vehicle problem

**Comment by metalgearsloth** [comment]
Is this still an issue after new gen + loot stuff.

**Comment by deltanedas** [comment]
lolno
