### ISSUE TITLE
Make follow on items in inventories doesn't correctly orbit if you're moving

### ISSUE THREAD

**Issue by Chief-Engineer** [space-wizards/space-station-14#17133]
## Description

If you use the make follow verb on something, like a ghost soft toy, while you are walking and while it is held in your hands it gets stuck offset from you. I'm not sure what the exact requirements are for reproduction, but that works. The distance appears to be related to your movement speed. I'll try to look at it to fix it soon:tm: ;-;

**Comment by metalgearsloth** [comment]
Dupe https://github.com/space-wizards/space-station-14/issues/14078
