### ISSUE TITLE
Planet stations have no roof

### ISSUE THREAD

**Issue by Subversionary** [space-wizards/space-station-14#17158]
## Description
Having a station on planet during daytime eliminates the need for lights, as the sun illuminates every single room on the station because stations have no roofs to speak of

**Reproduction**

1. planet [mapid] [biome]
2. set the planet light to daytime
3. build a closed room with no lights in it
4. Room still has lighting despite being closed off from everything 

**Screenshots**
FoV on
![image](https://github.com/space-wizards/space-station-14/assets/109166122/666418ff-f93c-40b2-bfb9-52381bf7ea8f)
FoV off
![image](https://github.com/space-wizards/space-station-14/assets/109166122/62363f94-4a07-4096-af0d-438852d6b8e5)

**Comment by mirrorcult** [comment]
dupe
