### ISSUE TITLE
Cargo pads should be purchaseable

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#17175]
$250 or something idk, to encourage them to make the cargo shuttle bigger.

**Comment by deltanedas** [comment]
cant fan areas so this will troll cargo techies with no suits

**Comment by Emisse** [comment]
need portable fans for refilling shuttle atmos, will also give atmos more shit to play wit

**Comment by deltanedas** [comment]
then you have to deal with people making shittles that have fans for walls which may or may not be bad

**Comment by Emisse** [comment]
a portable fan is not at all similar to a tiny fan

**Comment by Emisse** [comment]
one is a machine that refills to ambient and the other is an atmos blocking entity

**Comment by deltanedas** [comment]
oh my bad

**Comment by metalgearsloth** [comment]
Okay now that I think about it not sure how this plays with trading post https://github.com/space-wizards/space-station-14/pull/14390 so uhhhhh may need to think on the trading post bit.
