### ISSUE TITLE
Multiple uplink implants should be blocked.

### ISSUE THREAD

**Issue by ElectroJr** [space-wizards/space-station-14#17173]
Currently you can add multiple traitor uplink implants, even though this will functionally render one of them useless because you can never add TC to them.

#17172 adds a new `AddImplantAttemptEvent` but doesn't actually block multiple uplink implants because there currently isn't an easy way of whitelisting/blacklisting uplink implants because they have no identifiable component, tag, or implant-prototype.

**Comment by EmoGarbage404** [comment]
fixed
