### ISSUE TITLE
Some airlocks on cluster have spaced tiles

### ISSUE THREAD

**Issue by Chief-Engineer** [space-wizards/space-station-14#17237]
## Description

Some airlocks on cluster have their tinyfans positioned in a way that causes tiles to be spaced. In the screenshot, the tiny fan is located  under the red airlock, so the tile with the docking airlock is always spaced. I'm pretty sure @Scribbles0 maintains cluster, sorry if I'm pinging the wrong person.

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/119664036/01576022-98c4-4498-a3b4-453be65934ec)

**Additional context**

Not usually an issue because of how short people normally spend in these tiles, but a newish player died because of it recently so I figured I'd report it

**Comment by Emisse** [comment]
just needs fixgridatmos ran next save
