### ISSUE TITLE
Anchorable needs predicting

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#17252]
Shouldn't be too hard, just move all the client / server stuff to shared.

**Comment by benev0** [comment]
this is my first one but it appears that this depends on a number of refactors.

1. popup needs to have a shared non-abstract class
2. namespace change Content.Server.Coordinates.Helpers -> Content.Shared.Coordinates.Helpers

**Comment by benev0** [comment]
looks like there will need to be code repetition for any method that contains a popup.

**Comment by benev0** [comment]
attempt present in pr #17422

**Comment by slarticodefast** [comment]
Fixed by #17422
