### ISSUE TITLE
The crew monitoring server has no power on the Aspid map

### ISSUE THREAD

**Issue by Ahion** [space-wizards/space-station-14#17251]
## Description

The crew monitoring console don't work because the crew monitoring server is un-powered on the Aspid map.

**Screenshots**

![Screenshot_1](https://github.com/space-wizards/space-station-14/assets/58528255/f99b357a-3e7f-4ae6-9c0b-03a4669968de)

**Additional context**

I don't know why, the LV cable is laid next to the server.

**Comment by Emisse** [comment]
might be an unpowered cable nearby overriding it?

**Comment by 0x6273** [comment]
The LV cable in the room below is unpowered, and it's connecting to that instead of the closest cable for some reason.

**Comment by Emisse** [comment]
any unpowered cable will override any powered connections in the area around it

**Comment by Ahion** [comment]
> any unpowered cable will override any powered connections in the area around it

If I lay an unpowered cable next to the equipment, will it turn off? Sounds like a bug.

**Comment by Cheackraze** [comment]
> The LV cable in the room below is unpowered, and it's connecting to that instead of the closest cable for some reason.

I've been searching for this, that might be the clue I needed thank you

**Comment by deepy** [comment]
Issue as a picture for visual learners:
![image](https://github.com/space-wizards/space-station-14/assets/905507/b36cad83-a110-4111-a60c-1a1d7a43fbff)
