### ISSUE TITLE
Auto-Drinking And Eating Doafter Bug

### ISSUE THREAD

**Issue by Alekshhh** [space-wizards/space-station-14#17254]
Not sure if it's limited to pockets or just drinks, but I noticed when drinking an MRE flask and putting it in my pocket, it continued to make me drink. Likely to work for food too, since they're the same thing, but not sure if it works for backpacks or anything similar too.

**Comment by deltanedas** [comment]
works in bag too yeah

**Comment by ElectroJr** [comment]
Mice and other simple mobs need some sort of component that enables them to eat without hands, then you can just use do-afters existing hand & held item checks.

**Comment by Alekshhh** [comment]
this also happens if you place it on the ground

**Comment by Plykiya** [comment]
fixed https://github.com/space-wizards/space-station-14/pull/29854
