### ISSUE TITLE
This shuttle is unpowered also pod fuckery 

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#17274]
## Description

**Reproduction**

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/43253663/6a82b5a9-726c-4500-aced-d1b05eface8b)

**Additional context**

**Comment by Just-a-Unity-Dev** [comment]
cluster evac shuttle

**Comment by deltanedas** [comment]
did that shittle have 2 gens if it did then ce lied
