### ISSUE TITLE
All hardsuit helmets should protect your eyes from welding

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#17294]
## Description

I'm pretty sure that welding helmets are rather scarce too, also the blind effect sucks.
**Reproduction**

**Screenshots**

**Additional context**

**Comment by asperger-sind** [comment]
Pretty sure this was both discussed and PRed and boiled down to "no because dont buff hardsuits more".

**Comment by DogZeroX** [comment]
Still think we need to add more welding protection, don't even know if we have welding goggles, that should project your eyes since you can't wear the helmet during eva

**Comment by liltenhead** [comment]
Mesons protect your eyes as well. Sunglasses give partial protection

**Comment by Aisu9** [comment]
just ask engi for protective glasses, powercreep for the sake of powercreep is not welcomed
