### ISSUE TITLE
Hardsuit should probably slow down bleeding rate

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#17295]
## Description

I vaguely remember some codebases making it so hardsuits decrease your bleeding amount when you're wearing them since they're tightly sealed around your body.
**Reproduction**

**Screenshots**

**Additional context**

**Comment by mirrorcult** [comment]
absolutely not

**Comment by Aisu9** [comment]
they don't seal your body they're airtight

**Comment by Emisse** [comment]
im gonna tightly seal my hands around your throat if you buff hardsuit
