### ISSUE TITLE
Shadows don't get updated on the client if a light goes out until the light itself is on screen

### ISSUE THREAD

**Issue by DrSmugleaf** [space-wizards/space-station-14#1729]

**Comment by PJB3005** [comment]
See https://github.com/space-wizards/RobustToolbox/issues/1198

**Comment by moonheart08** [comment]
Still an issue? @PJB3005

**Comment by PJB3005** [comment]
So the exact but doesn't happen since it got lost in a bunch of PVS rewrites, but the linked issue on RT is still something that needs fixing.

Close this keep the engine issue open.
