### ISSUE TITLE
[Feature Request] Make transporting artifacts actually dangerous

### ISSUE THREAD

**Issue by Myakot** [space-wizards/space-station-14#17297]
## Description
Alien artifacts are not nearly as dangerous as they should possibly be. I would like to focus on transportation of said artifacts.

What's wrong IMO:
- We have artifact containment boxes, which are basically useless and are just set pieces for RP purposes. You have to be incredibly unlucky to immediately activate an artifact via distro gasses upon bringing it to the ship.
- They should be one of the most hazardous items on the station. Hey, they even have a code for producing a singuloo (even though it's not really feasible), that's how dangerous they are.

What I ask for in this feature request:
- Picking up/starting to drag an artifact will start giving you radiation/cellular damage or straight up shock you, if an artifact has a corresponding node pre-generated in it. For an example if an artifact has pre-generated a depth 4 "energy release" node, then touching it (or being 1 tile around it) will irradiate you as hard as a broken RTG does per second. The deeper the effect is generated, the higher the consequences are. Only the deepest effect counts towards artifact's power.
- Add art cost multiplier if such an effect is present, depending on it's depth (not RD points, the sell cost - that'd make it actually worthwhile for salvage to bother with these and near useless for RND to use these artifacts, even if they have useful applications after completely investigated. Simply because they'd be too dangerous to use)

What would it change:
- Every found/bought art is now either a death sentence to all who handle it without preparation, or just the usual - some xeno toy.
- Small artifacts can still be handled with chests (unless blacklisted), while large artifacts *have* to be transported via containment boxes.
- Salvage would actually bother getting artifacts due to the price increase of the dangerous ones (if it's high enough).
- Dangerous radiation artifacts could become new RTGs that self-sustain the station, implying RTGs could be removed alltogether from maps (now you have to actually work to automate safe power instead of starting with it)
- A real reason to e-mag artifact containment boxes if a dangerous irradiated artifact is being transported to provide some chaos (this would require additional features, like the containment box lighting up different colours if it's transporting a dangerous-to-be-near artifact)

What is not well thought out:
- Probably everything, because I, for sure, have missed something.
- Irradiated artifacts would kill space carps, monkeys and gorillas as soon as they are spawned.
- Getting a single shocking or irradiated artifact would trivialize activation conditions for new artifacts. (electricity would matter if multitool becomes a rarity, as is being developed, as far as I understood maintainer-talk)
- Not enough effects to make it interesting. Perhaps there should be a positive effect to touching or being near some artifacts. Imagine the horror of medbay, when there're 8 beds placed around a hulking alien obelisk which, as RD says, "will help you recover faster".

Hope you didn't fall asleep after reading this wall of text and do agree with my intentions, at least partly.
Have a good day

**Comment by Just-a-Unity-Dev** [comment]
cc @EmoGarbage404

**Comment by mirrorcult** [comment]
not actionable rn
