### ISSUE TITLE
Errors in the source code of Space Station 14

### ISSUE THREAD

**Issue by AndreyMoskalev565** [space-wizards/space-station-14#17319]
Hello! I found several errors in your code with the help of the PVS-Studio analyzer.

**Issue 1**

```
private void OnStateChanged(...., MobStateChangedEvent args)
{
  if (   args.NewMobState != MobState.Dead 
      || args.NewMobState != MobState.Critical) // <=
  {
    return;
  }
  ....
}
```
[Here's the link to the code fragment with the error.](https://github.com/space-wizards/space-station-14/blob/662c83a8a299216f8c1dd55077130a7fa8cf9fc6/Content.Shared/DoAfter/SharedDoAfterSystem.cs#L49)
The conditional expression is always true here: if 'args.NewMobState' equals 'MobState.Dead', it can't be equal to 'MobState.Critical', and vice versa. It is probably worth using the '&&' operator here instead of '||'.

**Issue 2**

```
public GasTankWindow(GasTankBoundUserInterface owner)
{
  ....
  _spbPressure = new FloatSpinBox
  {
    IsValid = f => f >= 0 || f <= 3000, // <=
    ....
  };
  ....
}
```
[Here's the link to the code fragment with the error.](https://github.com/space-wizards/space-station-14/blob/662c83a8a299216f8c1dd55077130a7fa8cf9fc6/Content.Client/UserInterface/Systems/Atmos/GasTank/GasTankWindow.cs#L168)
This error is similar to the previous one. IsValid is always true, because if f > 3000, then f >= 0, and if f < 0, then f <= 3000. Perhaps it's better to replace the '||' operator with '&&'.

**Issue 3**

```
private void OnSmokeSpread(....)
{
  if (.... || args.NeighborFreeTiles.Count == 0)
  {
     ....
     return;
  }
  ....
  if (   args.NeighborFreeTiles.Count == 0 
      && args.Neighbors.Count > 0 
      && component.SpreadAmount > 0)
  {
    ....
  }
}
```
[Here's the link to the code fragment with the error.](https://github.com/space-wizards/space-station-14/blob/662c83a8a299216f8c1dd55077130a7fa8cf9fc6/Content.Server/Fluids/EntitySystems/SmokeSystem.cs#L128)
The 'args.NeighborFreeTiles.Count == 0' check is performed twice. However, if it will be true for the first time, a return from the method will be performed. Thus, the second check is always false, and the code in the second 'if' block will be unreachable. 

**Issue 4**

```
protected override void Dispose(bool disposing)
{
  MenuBody.OnChildRemoved -= ctrl =>            // <=
    _uiController.OnRemoveElement(this, ctrl);
  ....
}
```
[Here's the link to the code fragment with the error.](https://github.com/space-wizards/space-station-14/blob/662c83a8a299216f8c1dd55077130a7fa8cf9fc6/Content.Client/ContextMenu/UI/ContextMenuPopup.xaml.cs#L74)
```
public void OnRemoveElement(ContextMenuPopup menu, Control control)
{
  ....
  element.OnMouseEntered -= _ => OnMouseEntered(element); // <=
  element.OnMouseExited -= _ => OnMouseExited(element); // <=
  element.OnKeyBindDown -= args => OnKeyBindDown(element, args); // <=
  ....
}
```
[Here's the link to the code fragment with the error.](https://github.com/space-wizards/space-station-14/blob/662c83a8a299216f8c1dd55077130a7fa8cf9fc6/Content.Client/ContextMenu/UI/ContextMenuUIController.cs#L205)
In this code fragment, newly created anonymous functions are used to unsubscribe from events. This will not work. Even if the event handler body and one of these functions’ bodies are the same, they are still different objects.

**Issue 5**

```
public ThresholdBoundControl(...., float value, ....)
{
  ....
  _value = value;
  ....
  CBoundEnabled.Pressed = _value != null;
  ....
}
```
[Here's the link to the code fragment with the error.](https://github.com/space-wizards/space-station-14/blob/662c83a8a299216f8c1dd55077130a7fa8cf9fc6/Content.Client/Atmos/Monitor/UI/Widgets/ThresholdBoundControl.xaml.cs#L75)
'_value' is a meaningful type and is not Nullable. Therefore, it cannot be null. The true value will always be assigned to the 'CBoundEnabled.Pressed' property here.

**Issue 6**

```
public SuitSensorStatus? GetSensorState(....)
{
  ....
  // check if sensor is enabled and worn by user
  if (   sensor.Mode == SuitSensorMode.SensorOff 
      || sensor.User == null 
      || transform.GridUid == null)
  {
    return null;
  }
  switch (sensor.Mode)
  {
     ....                
     case SuitSensorMode.SensorCords:
       ....
       if (transform.GridUid != null)
       {
         ....
       }                   
       else if (transform.MapUid != null)
       {
         coordinates = new EntityCoordinates(transform.MapUid.Value,
                            _transform.GetWorldPosition(transform, xformQuery));
       }
       else
       {
         coordinates = EntityCoordinates.Invalid;
       }

       status.Coordinates = coordinates;
       break;
   }

   return status;
}
```
[Here's the link to the code fragment with the error.](https://github.com/space-wizards/space-station-14/blob/662c83a8a299216f8c1dd55077130a7fa8cf9fc6/Content.Server/Medical/SuitSensors/SuitSensorSystem.cs#L340)
Note that the 'transform'GridUid == null' condition is always checked at the beginning of the method. If it is true, a return from the method is performed. So, the 'transform.GridUid != null' check, which is stored in 'switch', will always be true. And the code that is stored in the 'else if' and 'else' blocks of the same condition will be unreachable.

**Comment by Emisse** [comment]
The code is perfect.

**Comment by deltanedas** [comment]
yeah im sure theres only 6 bugs in the entire codebase gj

**Comment by Slava0135** [comment]
> yeah im sure theres only 6 bugs in the entire codebase gj

I am surprised it found so few
