### ISSUE TITLE
Grappling gun use inside a locker allows moving through walls

### ISSUE THREAD

**Issue by AJimmyU** [space-wizards/space-station-14#17325]
## Description
Shooting a grappling gun from inside a locker/crate will move the locker with you inside through walls or other obstacles.

**Reproduction**
1. Get inside a locker (livestock crate f.e.)
2. Shoot grappling gun

Reproduction might not be accurate, I've only observed this bug performed from ghost perspective.

**Screenshots**

**Additional context**
Similar bug to https://github.com/space-wizards/space-station-14/issues/17161 but different execution

**Comment by deltanedas** [comment]
will also do this outside of locker with 2 grapples at opposite ends
