### ISSUE TITLE
machine linking broken

### ISSUE THREAD

**Issue by DummeHytteOst** [space-wizards/space-station-14#17333]
i have been unable to link door, buttons, blast doors, logic gates and more, i am only able to start linking and stop linking, never actually connect the objects or even open the 'wire connection' window.

will update with video below after round end

https://github.com/space-wizards/space-station-14/assets/94384139/c24d654f-b22a-4ca9-84a4-f5bd0dfd0c50

**Comment by deltanedas** [comment]
womm as of like 3 hour ago

**Comment by DummeHytteOst** [comment]
video uploaded

**Comment by DummeHytteOst** [comment]
seems fine now, and i am not able to reproduce, so closing
