### ISSUE TITLE
diona mass is too big

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#17330]
## Description
diona can reliably instantly stamcrit with shove on first try its stupid

**Comment by Slava0135** [comment]
only good thing about dionas

**Comment by QuietlyWhisper** [comment]
sounds like an upside, they're not built for combat anyway

**Comment by Emisse** [comment]
rare diona w

**Comment by deltanedas** [comment]
robust omnizine is already a w, being little known melee gods is highly unbalanced (example of holo diona can stamcrit then kill with holo in the time that youre down)
