### ISSUE TITLE
Win+Shift+S (snipping tool) lags the game for a few seconds after snipping/dismissing

### ISSUE THREAD

**Issue by Visne** [space-wizards/space-station-14#1735]

**Comment by Visne** [comment]
Does not seem to happen on my laptop (anymore?), I will check my desktop soon and close this issue if it doesn't happen there either.

**Comment by PaulRitter** [comment]
Seems like a driver(?) or smth fucking up, i don't really know how much we can influence this tbh. (altough i know close to nothing about this so take my opinion w/ a grain of salt)

**Comment by Visne** [comment]
@PaulRitter Does it happen for you? Let's first see if this is even still an issue

**Comment by PaulRitter** [comment]
haven't used windows for dev for some time now :/

**Comment by Visne** [comment]
Ah sure, I'll just check it out on my desktop next week and if it doesn't happen I'll just close the issue

**Comment by Visne** [comment]
Doesn't seem to be happening anymore, it causes a small spike in the debug tool but for gameplay it's barely noticeable.
