### ISSUE TITLE
Give janitor roundstart cleaning nades

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#17356]
## Description

We have the support for it, we just need the grenade item with the cleaning foam in it and make it so they spawn with two grenades+ make them orderable in cargo for mass cleaning
**Reproduction**

**Screenshots**

**Additional context**

**Comment by DogZeroX** [comment]
+ add the cluster cleaning grenade

**Comment by slarticodefast** [comment]
Fixed by #25444
