### ISSUE TITLE
medipens don't show correct volume values before injection.

### ISSUE THREAD

**Issue by EmoGarbage404** [space-wizards/space-station-14#17367]
## Description

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/98561806/6392729b-fb15-4224-8ca0-9482ae2ae3e6)

**Comment by deltanedas** [comment]
#12875 :trollface:

**Comment by slarticodefast** [comment]
![grafik](https://github.com/user-attachments/assets/a5ce9a69-05b9-44ef-bd5d-c502fc2a1753)

Seems to be fixed now. Although the margins of the text are still a little off.

**Comment by Plykiya** [comment]
all my love went into hypos and injectors
