### ISSUE TITLE
Expedition rewards changes

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#17372]
The window should say what the rewards are (just generate it in advance or determine the RNG in advance) so people know if something gives a cloner board or whatever.

Also the rewards should probably be scaled up a bit. My current estimate is 2 missions getting done an hour so maybe give out like 10 rewards or something (though 10 T3 parts for 30 minutes work might still be a bit low idk).

Or at least maybe scale some of the lesser ones by count (like 1 RnD server board is probably worth 5 T4 parts idk).

@deltanedas

**Comment by deltanedas** [comment]
its not 2 missions an hour its usually 4-6 :trollface:
i assume that scaling by count would mean making part crates and not spamming orders?
can put rewards in with seeding probably

**Comment by metalgearsloth** [comment]
I want 4-6 an hour so if they're doing that we can drop the timer a bit.

With loot reduction we can probably drop it to like 12-15, especially with the upcoming gen change https://github.com/space-wizards/space-station-14/pull/17121
