### ISSUE TITLE
[Feature request] Coms console passes down accents

### ISSUE THREAD

**Issue by VasilisThePikachu** [space-wizards/space-station-14#17383]
## Description

As i see it the coms console is like a microphone someone speaks into, meaning a lizards/dwarf/drunk accents should pass down when making announcements

**Reproduction**

1. Be me, lizard
2. Talk on coms console
3. My accent is magically fixed for that announcement

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/34938708/8886577b-f451-4452-a9d7-1514bb55f834)
As of now the s should be becoming sss like when speaking normally
**Additional context**

**Comment by GoodWheatley** [comment]
iirc the comms console isn’t using a microphone, the character is physically typing the announcement into the computer which is then broadcast to the station using TTS. SS13 has displays around the station that show the announcement text, reinforcing this theory. And if it is a microphone, how can mimes and mute people use it in the first place?

**Comment by VasilisThePikachu** [comment]
> iirc the comms console isn’t using a microphone, the character is physically typing the announcement into the computer which is then broadcast to the station using TTS. SS13 has displays around the station that show the announcement text, reinforcing this theory. And if it is a microphone, how can mimes and mute people use it in the first place?

Good points but i will bring some points as well

Seems kinda weird that it would be a tts reading it for EVERY person speaking into it
Speech-to-text can exist for it to show on displays
And ss13 has gloves that lets you use sign language on telecoms, i guess then tts can do its thing

**Comment by OctoRocket** [comment]
It would be funny to have actual TTS read out communication console messages, but it would probably have to be limited to MRP.

**Comment by VasilisThePikachu** [comment]
Some Russian forks have tts already but apparently its a memory-leaking heaven

**Comment by VasilisThePikachu** [comment]
Closing since people don't seem to want this
