### ISSUE TITLE
walls should be harder to construct

### ISSUE THREAD

**Issue by Nails-n-Tape** [space-wizards/space-station-14#17388]
## Description

steel and reinforced walls should be harder to construct. i feel like building an airtight, solid-steel wall should take more than 10 seconds to create, and should be more complex than just "steel wall = (2 steel)(2)".

- all doafters related to wall construction should take significantly longer. like 5-10 seconds.
- walls should require tools to make, like welding tools and screwdrivers. would make sense from a physical point and to make walls a bigger deal.
- you shouldn't be able to put together multiple walls at once. should probably be restricted to one doafter at a time.

**Comment by Equivocateur** [comment]
walling diskie in a filled 5x5 rwall box in 2 minutes is valid

**Comment by keronshb** [comment]
No, don't make the game a chore.
