### ISSUE TITLE
unicycle + disposals = oh no

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#17390]
## Description
very very sus

**Reproduction**
1. hop on a bmx
2. hop in a disposals unit
3. camera stays on bmx
4. flush yourself
5. ashdsahfbfbd

**Comment by brainfood1183** [comment]
This happpens with all vehicles

you can also not be unbuckled by another player on any vehicle
if you die on a vehicle you cannot go to ghost via movement input and must type ghost in console
