### ISSUE TITLE
Do reinforced windows break too easily?

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#17391]
## Description
Currently, regular reinforced windows break way too easily. Using common tools such as a crowbar, i was able to break one in ~15 seconds. A toolbox was able to break one in 10 seconds and a baseball bat was able to break one in ~7 seconds.

In comparison, when using tools the fastest I was able to deconstruct a reinforced window was around 25-30 seconds.

Should reinforced windows be able to be broken quicker by using common weapons, than it takes to deconstruct one properly using tools?

**Comment by keronshb** [comment]
Try the test again and let me know these stats:

How many hits does it take to destroy a reinforced window and a regular window with both a toolbox and a baseball bat. Just the number of hits this time.

**Comment by Kayek14** [comment]
Window:
Hits to break
baseball bat - 4 (2 wide swing)
toolbox -6 (3 wide swing)

Reinforced Window:
Hits to break
baseball bat -12 (6 wide swing)
toolbox - 22 (9 wide swing)

**Comment by Kayek14** [comment]
I also tested this with secure windoors.

took 48(25 wide) hits with a toolbox .
took 26(13 wide) hits with a baseball bat.

**Comment by keronshb** [comment]
How long does it take for wide attacks to hit vs regular attacks?

**Comment by Kayek14** [comment]
depends on the weapon, but i think but to get full damage its something like a little less than twice the time for normal attacks.

**Comment by keronshb** [comment]
I think the health is fine as they are then. If it takes 22 hits (seconds) with a toolbox and 18 seconds with a wide swing that's fine.
