### ISSUE TITLE
Expedition Balance

### ISSUE THREAD

**Issue by liltenhead** [space-wizards/space-station-14#17401]
## Description
Expeditions have received some new layers of difficulty in the form of hazardous atmosphere, and PKA being moved to a science tech. Salvagers now start off at a higher risk than before. Also change very recently was the reward system. Now, there is simply less loot on each expedition and borderline makes the lava dungeon not worth visiting. Certain dungeon pieces are now completely useless, and you can't find any form of weapons better than a spear. 

It is also worth mentioning navigating the lava place is very tedious if you didn't previously acquire insulated gloves due to the whole dungeon requiring security access. I believe removing weapons and resources from the dungeons makes expeditions less interesting to run overall. Salvage is still just gonna buy guns cause they are required to do extreme difficulty missions which involves killing dozens of fairly tanky mobs and usually a boss.

Also you can't get a biomass reclaimer board in any of the dungeon piece, or as a reward, so cloning is still severely limited even if you get lucky and get the pieces. So what I'm suggesting is either bring back the loot, make new pieces to replace the old ones, or simply make higher tier missions give even more loot as a reward for completing the expedition. Not just 3 "better" rewards. Or even a combination of all three would work.

Expeditions run the risk of every member getting permakilled down below, and if even one member falls the group typically has to bail or risk losing them forever as well. The risks are very high, so the rewards should be as well.

**Comment by Cheackraze** [comment]
The lava brig configuration can just have the door access changed, the intent was to have security help but they aren't working out like that.  As for the room pack itself, no idea why all the loot was removed, should have just kept it how it was because I agree, it makes it not worth the effort at all.  And now dungeons generated outside of the expedition system have literally 0 incentives with no loot in the dungeon template itself.

**Comment by deltanedas** [comment]
i think the main idea now is to have the dungeons just be a place for missions to take place in rather than something where you open 50 crates of loot, tho i have added some loot back to lava brig

**Comment by Cheackraze** [comment]
> i think the main idea now is to have the dungeons just be a place for missions to take place in rather than something where you open 50 crates of loot, tho i have added some loot back to lava brig

Take out the existing salvage loot spawners then, not the theme specific loot.  It makes non-expedition console dungeons pointless

**Comment by metalgearsloth** [comment]
Explicit rewards just need bumping, the only things that should be removed are stuff like ATVs or lasers or APEs, sheets or tech disks or the likes can stay.

**Comment by Cheackraze** [comment]
Rewards also shouldn't be relying on a completely separate system to be given to the salv team but thats a different issue

**Comment by metalgearsloth** [comment]
> Rewards also shouldn't be relying on a completely separate system

The issue is you have to balance across A) dungeon sizes B) templates, so if we ever want to tweak dungeon loot we have to tweak every template, compared to just having external callers handle it themselves and using markers or the likes.

**Comment by Cheackraze** [comment]
> > Rewards also shouldn't be relying on a completely separate system
> 
> The issue is you have to balance across A) dungeon sizes B) templates, so if we ever want to tweak dungeon loot we have to tweak every template, compared to just having external callers handle it themselves and using markers or the likes.
> 
> That's why I want high-tier loot like the cloner moved to explicit rewards as the only other solution is just making every room unique (though that limits in other ways).

Oh that I understand, I meant more the rewards spawning on the cargo shuttle, should be spawned onto the salvage ship or similar instead

**Comment by metalgearsloth** [comment]
NW, we could maybe just make cargo pallets to it and dump them on that? Not sure

**Comment by Cheackraze** [comment]
> NW my bad, we could maybe just make cargo pallets to it and dump them on that? Not sure
> 
> Also see #17403

Ye its just awkward that they are like, cargo orders and you have to pray cargo techs don't steal it.  Or in non conventional stations with no cargo, means no rewards

**Comment by liltenhead** [comment]
Gonna close this
