### ISSUE TITLE
Stripping allows instant stealing from containers with no warning

### ISSUE THREAD

**Issue by dmnct** [space-wizards/space-station-14#17424]
## Description
You can open containers in the strip menu and act on them as if they were on the ground, removing or placing items instantly and with no warning to the person wearing the backpack/belt (apart from the animation of the item swiftly moving to/from their sprite which is potentially easy to miss

**Reproduction**
Walk up to security
Open strip menu
Right click on their Security belt, "Open UI"
Acquire contents

**Screenshots**

**Additional context**

**Comment by deltanedas** [comment]
pretty sure that you can only see whats in someones bag provided:
1. its on the floor to begin with and you open it
2. they put it back on
3. they stay in ui range

and that doesnt let you take items out to my knowledge

**Comment by deltanedas** [comment]
cant reproduce on lizard

**Comment by dmnct** [comment]
Yes I tried it on Leviathan and it does not work, I did not consider that I might be seeing an admin power in use. Closing
