### ISSUE TITLE
Stimulants are overtuned

### ISSUE THREAD

**Issue by liltenhead** [space-wizards/space-station-14#17456]
## Description
Stimulants remain the most useful purchase in a nukies arsenal, and arguably even for a syndicate agent. Not even mentioning you can currently dupe them infinitely due to how smoke and foam mechanics are currently. The ability to move faster than any crew member, with instant stun recovery, and critical health recovery is just too insane. Five minutes is enough time to kill a third of the crew by yourself, not mentioning you can just buy more if you don't wanna dupe em. 

I've frequently seen stimulants used to great effect with any combo of weapon. The newest trick is to use it with the double bladed energy sword, meaning you are effectively immune to disabler shots meaning you must be stun batoned before being shot. This would work just fine with the normal esword or even best with the fists of the northstar since you don't drop them when stunned. 

I'm not sure if they should just have a price increase, a nerf, or a combo of the two. I'd argue they should either lose the speed buff, or lose the stun recovery effect. Nerfing the speed would probably be the better of the two options. I believe the experimental stim should be what you have to purchase if you want a combo of speed and stun recovery since the cost of that one is death.

**Comment by FacePluslll** [comment]
Think removing the stim purchases or giving all stims a damage debuff like the experimental stim and nerfing its speed boost is prob the way to do it. Right now, stims are just super meta as a nukie and the desword made it way worse to fight against (oops).

**Comment by keronshb** [comment]
I'd need to see the interaction with stimulates and stunning/disablers/etc and then also with dswords. FWIW dswords also take up two hands so the nukie will have to get into melee range to attack, which means you're highly susceptible to being stunbatonned.

**Comment by liltenhead** [comment]
It doesn't really matter that much if you stun baton someone on stimulants. You can't cuff them, so unless you have perfect reactions by stunning them, turning off harm mode, either spam clicking where the sword is or right clicking and finding the sword in a menu. A very skilled and lucky officer might get a few bullets in while they're flip flopping off the floor but that is really it. They run so much faster than a hardsuited security officer they shouldn't even be getting stunned in the first place if they're trying to kite. (Of course this is all in a 1v1 scenario which doesn't happen often, especially during nuke ops)

**Comment by liltenhead** [comment]
They were nerfed.
