### ISSUE TITLE
dead end nodes are heavily biased

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#17450]
## Description
its very likely to loop to a dead end over and over with artifacts fsr

tree so far:
0 -> 1, ?, ?
1 -> 0, 2
2 -> 1

with no traversal distorter so far i have never gotten from 1 to 0, 6 monkeys in and it keeps going back to 2

theres a 1.5% chance of this happening at random (not accounting for the first time new node bias)

**Comment by EmoGarbage404** [comment]
To be quite frank, I'm open to a complete redesign of how artifact nodes work. The current system is tolerable but it's very obtuse and kind of difficult to explain. Artifact effects are very weak and boring (which is honestly a separate issue) and there's so much RNG built into the system that it's difficult to navigate unless you're deeply familiar with how it works internally.

Maybe the solution is as simple as eliminating "depth" of nodes and turning it into a more cyclical structure? i'm interested to hear peoples' opinions on the topic.

**Comment by deltanedas** [comment]
ok as it turns out i could not repro the reported issue locally its fairly random
just average sci luck in real game

making it cyclical seems like it would eliminate any tediousness of killing a random number of mobs until it finally goes back to the right node, but it is an interesting mechanic that i like, when its fair and not bullshit rng that just wants blood
