### ISSUE TITLE
Artifact Fragment's recipe only using one piece of the fragment to a full artifact.

### ISSUE THREAD

**Issue by Beridot** [space-wizards/space-station-14#17451]
## Description
as the title above says, you can craft a artifact with only ONE artifact fragment despite the recipe calling for four.

**Reproduction**
get one artifact fragment, craft the alien artifact via g menu, congrats you have a artifact. 

**Screenshots**

https://github.com/space-wizards/space-station-14/assets/122707721/0c765e38-fc45-4ae3-bc08-cf403171600f

**Comment by EmoGarbage404** [comment]
i think this might be a construction issue? The single item might be fulfilling the requirements of all 4 of the steps.
