### ISSUE TITLE
Foam and Smoke Issues Part 2

### ISSUE THREAD

**Issue by liltenhead** [space-wizards/space-station-14#17455]
## Description
Weeks have passed since the last foam issue I created. It has become common place for all of medical to make healing foams or smokes in order to revive people as efficiently as possible. There are many different feedback threads now quoting different strategies in order to "duplicate" chems as effectively as possible. 

It's hard to state exactly what the issue is here. I have seen nukies now make omnizine smoke bombs, inhale as much as they possibly can. Inject themselves with stimulants and finally use ipecac to puke it out. All in order to keep making more and turn them into pill form. I don't know if the solution is to add more OD limits to things, mechanically fix smoke and foams to not inject more chemicals than is even in the foam or what exactly. Foam and smoke probably shouldn't multiply the chems inside is the most practical answer.

You could also make smoke and foam much harder to make, or some combination of all of this. Either way, the current state of foam and smoke is allowing for instant death grenades, or insanely good healing. I'm not sure what is intentional and what isn't so I'll just write this issue as a way to compound them all together.

**Comment by Matz05** [comment]
It appears that foam/smoke use old code that does not respect conservation of reagents in the least, spreading based on an abstract 'spread' quantity and applying their full inventory of chemicals to contacted entities repeatedly (and from multiple tiles of foam at once if you overlap multiple).
Aside from a minor container bug I just reported, puddles appear to rigidly obey conservation of reagents. I recommend re-implementing smoke/foam spread using the code from puddles as a guide. I could try to do so, but honestly it's far beyond my skill/code-familiarity level and I'd be happy for someone more competent and/or more familiar with the code to take it off my hands, or at least tell me more specifically what to do in some way.

**Comment by hord-brayden** [comment]
Another meta with this: a well-known diona I've observed multiple times makes what's essentially robust-harvest foam, every match, in the hopes of rolling syndicate. If Whiskey echo Whiskey - purchases a holoparasite from uplink and can outheal most combat encounters encased the various foam cocoons, while the holo does work. 

I've been thinking about this after being on the receiving side of this meta, first hand. It would be disappointing to punish ingenuity and clever uses of game mechanics with some across-the-board nerf to a fairly well known strategy. 

What if there's another reagent/Chem that's akin to ipecac - think NARCAN-esque. Purges active Chems in bloodstreams of humanoids?

**Comment by Matz05** [comment]
I'd avoid throwing in general chemical nerfs to bandage over the specific problem that foams/smokes cram your chemstream with a great many duplicates of the reagents in them over a short duration, allowing a person to consume (or feed others) a pretty much arbitrary amount of any mix of chems, without even _producing_ or _carrying_ that much on them, much less having any time taken to administer them.

**Comment by Kayek14** [comment]
![image](https://github.com/space-wizards/space-station-14/assets/106507028/dd3c9dd7-b95a-4d98-9c84-f8ca8dfae670)
behold a foam grenade found in the wilds of lizard. 

Basically an admin heal-all that lasts for a few mins, nothing too major.

**Comment by metalgearsloth** [comment]
1. Just make it not clone which I pointed out in the original PR and seems like a good example of 13 balance.
2. Make the alpha based on reagent density.

**Comment by Kayek14** [comment]
More examples of foam abuse:

![image](https://github.com/space-wizards/space-station-14/assets/106507028/b9db0179-32d7-467b-a110-af1cda6a2a92)
first picture is a chloral hydrate foam.
second picture is the bloodstream of who ever touches it.

You touch this for one tick and you instantly go down and get your entire bloodstream filled with the chemical.

**Comment by GoodWheatley** [comment]
Closed by #17693
