### ISSUE TITLE
Double bladed energy sword reflects while off

### ISSUE THREAD

**Issue by liltenhead** [space-wizards/space-station-14#17457]
## Description
The blade does not need to be on in order to reflect projectiles.

**Reproduction**
Shoot someone with a d-sword and watch bullet or laser reflect

**Screenshots**

![awerr](https://github.com/space-wizards/space-station-14/assets/104418166/0b238a88-327e-44e9-bf7a-f071d0706510)

**Comment by FacePluslll** [comment]
I just tried this, I couldn't recreate it and seems to work as intended. Could you explain a bit more on how it occurred?

**Comment by liltenhead** [comment]
Uhh the only thing I did was turn it on and off. I didn't do anything else.

**Comment by FacePluslll** [comment]
> Uhh the only thing I did was turn it on and off. I didn't do anything else.

did the exact same thing, and it worked fine

**Comment by liltenhead** [comment]
Hmm I guess I'll see if I can re-replicate it when I get a moment.

**Comment by liltenhead** [comment]
Yeah I can't reproduce it anymore just gonna close it

**Comment by Slava0135** [comment]
spawn someone with esword without turning it and shoot
