### ISSUE TITLE
Crusher should have leech

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#17466]
So the problem is ranged weapons win 100% of the time for salvage as you can kite mobs indefinitely (at least until we add faster mobs than players) so there's 0 reason to ever use melee unless you like getting killed slowly by bleed.

To balance this I think crushers should give you 10-15 hp back if you hit a marked target. This is how some other games like DOOM 2016 ended up balancing melee which I think is good.

**Comment by Nails-n-Tape** [comment]
ultrakill parry system :godo:

**Comment by deltanedas** [comment]
parry some bitches

**Comment by keronshb** [comment]
> ultrakill parry system :godo:



> parry some bitches

@silicons it's your time to shine
