### ISSUE TITLE
Protolathes/Circuit Imprinters have duplicate entries

### ISSUE THREAD

**Issue by hord-brayden** [space-wizards/space-station-14#17474]
## Description

Each time someone pushes sync in the UI, and there has been tech researched that's applicable to that machine, it adds all of the previous researched entries again. Resulting in quite a few duplicates over time. I would assume sec techfab is also affected.

**Reproduction**

Research new circuit/protolathe tech, sync. Rinse, repeat.

**Screenshots**

<img width="343" alt="Screenshot 2023-06-19 at 11 40 30 AM" src="https://github.com/space-wizards/space-station-14/assets/35241666/5cdecdcc-2d80-4379-bfef-5092804ec5a6">
<img width="547" alt="Screenshot 2023-06-19 at 11 40 23 AM" src="https://github.com/space-wizards/space-station-14/assets/35241666/7751ab97-e03a-45ea-8dd7-cdb6a69c9f9e">

**Additional context**

**Comment by EmoGarbage404** [comment]
fixed a minute ago with #17473
