### ISSUE TITLE
Printers can't change the reasearch server. 

### ISSUE THREAD

**Issue by Rozuzaken** [space-wizards/space-station-14#17470]
Printers cannot change the server. Protolathe, secfab, medfab, circuit imprinter, and so on. In their interface, the server list button simply does not work.  When you click sync, the recipes are duplicated.

**Comment by dolgovmi** [comment]
![Dupe](https://github.com/space-wizards/space-station-14/assets/96251346/c345f168-5312-44b0-8e23-e3dc8284f2e9)
he meant this

**Comment by EmoGarbage404** [comment]
huh

**Comment by EmoGarbage404** [comment]
i'll get to this later today. The changes were made in #17443 so if someone wants to snipe be my guest.

**Comment by EmoGarbage404** [comment]
uh this got fixed
