### ISSUE TITLE
LavaBrig Dungen needs a full rework

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#17479]
## Description

This can easily hand out security encription keys, clothing, armor, it's a part of the issue of why salvage is getting on level with security on gear, at least on the armor and headset side, also clothing. 
Instead it should be a full prison with orange jumpsuits and no sec gear.
**Reproduction**

**Screenshots**

**Additional context**

**Comment by Myakot** [comment]
It even has a secfab
