### ISSUE TITLE
Stop adding OP stuff to nukies, freeze and removal request

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#17484]
## Description

Currently, they can just pump themselves full of stimulants and run around with double e-swords and basically mow everything down effortlessly, this is a common issue of people adding and buffing stuff from them and they often just goes from hardly balanced to overpowered.
**Reproduction**

**Screenshots**

**Additional context**

**Comment by metalgearsloth** [comment]
5 minutes of 30% extra movespeed, stun resist, and healing seems balanced to me /s

**Comment by fidso** [comment]
seems balanced

isnt balanced

**Comment by deltanedas** [comment]
pro after sosa ops:

**Comment by Myakot** [comment]
Should this be closed, since stims are no longer 5 mins?

**Comment by deltanedas** [comment]
yes fishops is back baby
