### ISSUE TITLE
Master's been pretty laggy sometimes

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#17490]
## Description

It slows down to a crawl, there's no additional data.
**Reproduction**

**Screenshots**

**Additional context**

**Comment by metalgearsloth** [comment]
![image](https://github.com/space-wizards/space-station-14/assets/31366439/720dc327-dff7-4d3d-9dc9-253e7965225f)

This is on round-end, is it just artifacts taking a shit on physics.
