### ISSUE TITLE
Expeditions refactor

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#17492]
Bikeshedded on discord.

I've never been entirely happy with the rewards for missions that can be done in a good way.

Changes:
- Use gateway not shuttle (confirmed).
- Persistent area that can be returned to.
- Use weather as a timer like rain world, so people that stay behind are at least recoverable just fucked up.
- Limited area (just fade out to black if they go too far and delete).
- Random objectives to unlock new planets (e.g. get the board from a dungeon / nest or whatever).
- Node-based UI where you can choose 1 of multiple new planets to unlock, like barotrauma or the likes, and each planet has a couple of ores so you have to progress through multiple planets to get them all. More exploration based than combat (crashed pods, ruins, whatever else exploration based, just chuck it on some sort of timer so they have to come back occasionally).
- Mobs are just more natural spawns in like dungeons or around the place.

95% of the existing code is still re-useable it just removes some of the bugbears I have with it and means salvage are more inclined to return shit to the station for useage + fixes some of the balancing issues around explicit stuff.

Probably need some option in the gateway to re-roll an area after a period of time for really long rounds.

**Comment by deltanedas** [comment]
if a gateway room is added for it, will the salv shuttle be removed since it would serve next to no purpose

**Comment by Just-a-Unity-Dev** [comment]
> Limited area (just fade out to black if they go too far and delete).

sea of thieves red sea

**Comment by metalgearsloth** [comment]
> if a gateway room is added for it, will the salv shuttle be removed since it would serve next to no purpose

Can probably keep it for events. Map diffs are a lot less CBT than they used to be.

Also updated the OP.

**Comment by OctoRocket** [comment]
This sounds really fun!

**Comment by metalgearsloth** [comment]
Maint meeting
