### ISSUE TITLE
Remove static GasPrototypes array from Atmospherics class

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/space-station-14#1749]
`Content.Shared/Atmos/Atmospherics.cs` specifically. Storing data statically like this (and especially initializing it in a static constructor) is bad because of cross-instance issues (e.g. integration tests).

**Comment by metalgearsloth** [comment]
@DrSmugleaf I think you did this right.

**Comment by Zumorica** [comment]
> @DrSmugleaf I think you did this right.

Yes, he did

**Comment by DrSmugleaf** [comment]
Fixed by https://github.com/space-wizards/space-station-14/pull/1914
