### ISSUE TITLE
Absurdly long and unrealistic requirements for captain role

### ISSUE THREAD

**Issue by AJimmyU** [space-wizards/space-station-14#17497]
## Description
Recent command time requirement update in https://github.com/space-wizards/space-station-14/pull/17366
resulted in the following requirement for the captain role:
30 hours engineering (for CE)
30 hours medical (for CMO)
30 hours cargo (for QM)
30 hours science (for RD)
30 hours security (for HOS)
6 hours CE
6 hours CMO
6 hours QM
6 hours RD
6 hours HOS
6 hours HOP

Adding up to a total of  186 hour raw playtime requirement for captain, assuming no outside playtime and always having an opportunity to play the above roles. Realistically, this will be closer to 200+ hours due to lack of role availability, 300+ assuming the player is actually playing the game and plays the same roles for fun despite having already met the arbitrary hour requirement.

HOP has a similar problem, however HOP can be unlocked by just playing a command roles combined for 20 hours, instead of every command role for 6, which causes the absurd time required.

**Reproduction**
1. Click job screen in character select

**Screenshots**

**Additional context**

I propose that captain role gets a generic command playtime requirement instead of needing optimistic 200 rounds worth of playtime spread across every single role. It's not a jack of all trades role, it's a leadership role.

**Comment by MagnusCrowe** [comment]
36 hours in cargo to be familiar with how cargo works?

**Comment by deltanedas** [comment]
thats probably more intended to be salv than cargo techie

**Comment by MagnusCrowe** [comment]
I assumed that was including salvage...even still.

**Comment by ElectroJr** [comment]
Requiring the captain to have played 6 hours or ~ 3 rounds as each head seems generally reasonable, but IMO the 30 department hours to unlock a head role seems way too large. 10-12 department hours seems like it would be plenty to get competent heads, especially as it already requires them to have spent 6 hours as each kind of subordinate. If it really needs to be longer an overall playtime requirement could be added as well, because that at least makes it much more feasible to unlock multiple head roles.

Note that I don't really play the game and have no clue how competent the player base actually is, maybe I'm giving them too much credit.

**Comment by CloneTrooperSimp** [comment]
IIRC (don't quote me on this though), some SS13 servers required just as much, if not the same, amount of time to play command roles. Which in my honest opinion, though it feels a tad high, it's just fine as it is. If you have the time to play this game for long periods of time, then surely you have the time to put in those hours to play the role you want to unlock, yes?

**Comment by LankLTE** [comment]
> thats probably more intended to be salv than cargo techie

I don't know the exact requirements, but I do know that a large bit of that requirement _is_ on cargo tech, nearly a third of the time I have left to unlock QM is required to be on techie. I'm of a similar mindset the underlying issue isn't having 6 hours on head, but how hard it is to unlock heads, especially the simpler ones.

**Comment by EmoGarbage404** [comment]
30 hours in each department is a comically large amount of time. Combining this with needing playtime on specific subroles like detective means that even if you're going for the playtime, you'll have a hard time getting it. I'd rather just have a minimum TOTAL playtime requirement for heads, as then you would have a base level of experience.

**Comment by Emisse** [comment]
i think the head total is fine, the 3 most important for captain to know is sec, med, and engineering. if need be we could lower cargo and sci perhaps? or just the 30 hour totals to 15 or something. I do want to reiterate that 6 hours per head is fine though.

**Comment by EmoGarbage404** [comment]
> i think the head total is fine, the 3 most important for captain to know is sec, med, and engineering. if need be we could lower cargo and sci perhaps? or just the 30 hour totals to 15 or something. I do want to reiterate that 6 hours per head is fine though.

That sounds fine to me.

**Comment by lzk228** [comment]
> long and unrealistic

> ![image](https://github.com/space-wizards/space-station-14/assets/124214523/4c32efb2-7f97-49bb-b08f-6b1028df7785)

:trollface:

**Comment by LankLTE** [comment]
> Being able to use conditions like "X hrs each in at least Y of these Z roles"

I don't know exactly how the role timers are currently split up, but I know that head roles specifically require some times in specific, like CMO requiring chem, QM requiring salvage, etc. It seems to be generally agreed that the requirements for each head on Captain are okay, as #17578 addresses, but by having head requirements you now inherently have requirements for other roles. I know that's not exactly what you mean, but I think it's worth mentioning.

> I used to play on the one I did and it never had an issue with people not being able to unlock the roles.

I'm just going to be honest and say I've never played SS13, but I can personally confirm in the last like, 8 LRP games I've played, maybe 2 have had a Captain. Head roles generally fill out fine (though I have seen some issues), but unlocking _all_ of them individually takes over 150 hours of straight playtime, and I think it's safe to say most people aren't minmaxing that. I personally have 3x the "minimum" time required, 2x if you take off my time on one or two of the same roles on MRP, and I'm still about 20 hours of "optimal" grinding from getting Captain. 
I think it's important to consider just how many new, or "relatively" new, players there are compared to people who play often.
In regards to the first, nearly every round I see a not insignificant amount of "new" players, whether they're playing for the first time or evidently have probably less than 10 hours total. This is a total assumption, but I would honestly be willing to bet a fair bit over half of this game's average players don't have more than 200 hours on this game- and even people who have far more than that don't have Captain unlocked _still_. Combine this with the large amount of people who previously had roles unlocked with a significant amount of playtime on them and now have to play 15 more hours (x6 for Captain, at the most extreme) to re-unlock them, and it becomes a little different than "other servers have high playtimes". 

I do agree more complex (and automatic) ways of testing for head access is ideal in the future, but the truth is a lot of people have (valid) complaints about the head requirements, and I think the myriad of comments on discord and this thread proves it. Changing it to something more sensible and changing it in the future to some of the methods you outlined is probably the best way to go about it.

**Comment by PJB3005** [comment]
Sense of pride and accomplishment

**Comment by Emisse** [comment]
you should have to submit your SAT scores to play captain

**Comment by deltanedas** [comment]
speedrun giving a tider aa in a test environment, if below 5 seconds you can be cap
