### ISSUE TITLE
Toggle internals off on other has no doafter

### ISSUE THREAD

**Issue by Chief-Engineer** [space-wizards/space-station-14#17494]
## Description

There doesn't appear to be a doafter for turning off someone else's internals, unlike turning their internals on

**Comment by graevy** [comment]
Hey, I took a look at this, but I'm pretty new.

https://github.com/space-wizards/space-station-14/blob/master/Content.Server/Body/Systems/InternalsSystem.cs#L90

Isn't this what you're looking for?
