### ISSUE TITLE
Can't Insert Uranium Ore or Bananium Ore Into Ore Satchel

### ISSUE THREAD

**Issue by Alekshhh** [space-wizards/space-station-14#17509]
Title says it all

**Comment by deltanedas** [comment]
fake

**Comment by Alekshhh** [comment]
may or may not have been a limit on ore satchel space

**Comment by EmoGarbage404** [comment]
it's because the ores have custom tags that override the "ore" tag

**Comment by lzk228** [comment]
> it's because the ores have custom tags that override the "ore" tag

nope.
![image](https://github.com/space-wizards/space-station-14/assets/124214523/1213189e-98ce-46be-b632-d337f6e1349a)

**Comment by EmoGarbage404** [comment]
![image](https://github.com/space-wizards/space-station-14/assets/98561806/7053659d-0a22-4a9f-acc7-f82ab2649b7f)
either your bag was already full or you were mistaking the refined uranium and bananium for the ore variants. in any case: closing issue.
