### ISSUE TITLE
Attempting to take over a dummy ghost role as an aghost freezes your client

### ISSUE THREAD

**Issue by VasilisThePikachu** [space-wizards/space-station-14#17544]
## Description

Yeah, not sure if its even worthy to report but better report it i guess

**Reproduction**

1. Aghost
2. Get a dummy
3. Equip it
4. Try taking over the ghost role
5. What have you done

**Screenshots**

**Additional context**

Blame your admin Akira for this discovery

also, the server crashed at round end so maybe the server explodes too or coincidence

**Comment by forgotmyotheraccount** [comment]
me personally i don't think admins should be allowed to have fun
