### ISSUE TITLE
Add exploration gateway

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#17579]
## Description

It's pretty much an admin teleporter than they can link to another gateway for events.
**Reproduction**

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/43253663/ec1f9abd-7faa-48fa-b01b-d471d8854e2e)

**Additional context**

**Comment by EmoGarbage404** [comment]
did we not want this for expeditions? not for admin stuff.

**Comment by DogZeroX** [comment]
Both.

**Comment by deltanedas** [comment]
i have sprites ripped and start of some code, ill make draft at some point
