### ISSUE TITLE
APC popping is mid

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#17595]
Pros:
- Need to think on reconnecting cables (as much of a hassle as fixing power is RN).
- Less signal spam.

Cons:
- Shitters can easily connect LV cables together and suddenly pop the entire station (even stronger than cable cutting).
- It's pretty much just areas again because you need to run your map and see if shit pops which is unintuitive.

It seems to cause more trouble than it's worth for gameplay and IMO should be removed.

**Comment by metalgearsloth** [comment]
Relevant pr is https://github.com/space-wizards/space-station-14/pull/16903

**Comment by Yousifb26** [comment]
Rage cages easily and consistently pop beakers which is annoying because people see that and still keep it powered anyways. Engi fixes it just for it to happen 5 seconds later again

**Comment by Yousifb26** [comment]
So I agree it’s mid and can cause many issues long term and short term too easily for just getting a stack of Lvs

**Comment by CloneTrooperSimp** [comment]
Inclined to agree, it's really mid and just... doesn't work well currently, not with what can and can't be done, or with some people within the playerbase (namely shitters).
I remember some shifts ago, I accidentally punched an LV wire at the maints in Omega station, and that alone made an APC pop, which felt... kinda dumb, unsure if it was intended or not, but it just made me stare at the screen for a few moments.

**Comment by deltanedas** [comment]
pro ideas:
- making breaker pops automatically turn back on after a few seconds
- making shocking ignore breaker somehow which would make rage cage and budget testing no longer troll apcs at all

**Comment by metalgearsloth** [comment]
>pro ideas:
>    making breaker pops automatically turn back on after a few seconds
>    making shocking ignore breaker somehow which would make rage cage and budget testing no longer troll apcs at all

Won't that just keep cycling if it's over power

**Comment by PJB3005** [comment]
Real life breakers don't pop instantly, do that for the shocking thing.

**Comment by Emisse** [comment]
shouldnt multiple APCs on one net split the load or something, so it doesnt giga overload everything

**Comment by deltanedas** [comment]
yeah im not sure how to do it but if it divided supply by number of apcs on the network it would fix that

**Comment by Emisse** [comment]
in general i think apcs being unable to be turned back on by non engineers is just annoying and doesnt lead to any fun or interesting gameplay

**Comment by metalgearsloth** [comment]
> in general i think apcs being unable to be turned back on by non engineers is just annoying and doesnt lead to any fun or interesting gameplay

I'm fine with the ss13 style:
- Need ID to unlock it.
- AI can adjust it.
- Has 3 or so switches for shit.
- No popping.

Maybe just need AI to make switches flipped easier (though that detracts from engi gameplay).
