### ISSUE TITLE
Add gas tanks and masks

### ISSUE THREAD

**Issue by DrSmugleaf** [space-wizards/space-station-14#1759]
The game currently has no oxygen tanks that you can use with an oxygen mask to breathe with.
To accomplish this, LungComponent needs to be changed to look for the relevant source of air, as right now it just looks for the tile's atmosphere below the player.

Additionally:
![image](https://user-images.githubusercontent.com/10968691/90347560-8f467480-e031-11ea-866d-d80af6394fe2.png)

**Comment by Zumorica** [comment]
Fixed by #2409
