### ISSUE TITLE
Remove ordering materials from cargo

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#17601]
## Description

Makes mining kind of useless
**Reproduction**

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/43253663/c4c7a524-5b15-4379-90bc-02a4088fd453)

**Additional context**

**Comment by EmoGarbage404** [comment]
Do we keep plasteel?

**Comment by DogZeroX** [comment]
Plasteel is prolly fine since it's just walls right.

**Comment by Arendian** [comment]
Is plasma common enough on expeditions for it to not be purchasable?

**Comment by DogZeroX** [comment]
You can go to a cave expedition and mine it.

**Comment by 0x6273** [comment]
Mining isn't useless since it saves cargo from having to buy mats. I don't think this is a good change since if no one is doing mining, departments that needs mats have no way to get them.

**Comment by DogZeroX** [comment]
This gives them more reasons to do mining, yes.

**Comment by laok233** [comment]
RD's honest reaction:

**Comment by Flareguy** [comment]
If salv dies, then there will be no way to get materials. You COULD mine it yourself, yes, but that's a huge headache and requires going on an expedition. Mining still has purpose since (afaik) materials like gold and silver can't be ordered from cargo.

**Comment by Arendian** [comment]
Currently it's 333 credits saved per stack of glass or steel, 500 credits per stack of plastic, 1000 credits per stack of plasteel and 2000 for plasma. If you think that's not enough value you can always increase the cost of purchasing said materials a bit. This will make is so that salvage bringing in materials earns more credits indirectly by cargo not having to spend said credits on buying the more expensive materials, without removing the ability of purchasing materials in case no mining happens.

**Comment by DogZeroX** [comment]
They'll be mining in magnets soon enough, plus gateway in the future, won't require much hustle than shuttle travel is.

**Comment by EmoGarbage404** [comment]
Tbh techies should get promoted to salv anyway if they start kicking the bucket.

My main concerns are:
- plasteel and plastic aren't meaningfully replenishable
- mining isn't consistent enough yet.

Maybe salvage asteroids will change that but im not sure it will be to the necessary level of output to match the crates for a while.

**Comment by Cheackraze** [comment]
If they are removed, it would be nice to keep the actually crates as spawnables and just remove them from the list

**Comment by deltanedas** [comment]
i think mining should just be a side hustle that you can build cargos stockpile with rather than the sole way of getting mats
by that logic you shouldnt be able to buy laser guns since sci can unlock and make them
