### ISSUE TITLE
mapping needs to not serialize EmitSoundOnCollide

### ISSUE THREAD

**Issue by Emisse** [space-wizards/space-station-14#17619]
as much as i love using regex to remove 4500 instances of EmitSoundOnCollide daily i think id love it even more if this didnt happen

repro
pick up an item and put it down in mapping
suffer eternally

**Comment by deltanedas** [comment]
same with meleeweapon nextswing etc

**Comment by ElectroJr** [comment]
Theres a pr thats should fix that by just not serializing time offsets, but the fact that its preventing maps from being loaded in the first place is some other bug.

**Comment by ElectroJr** [comment]
Should be fixed by next engine update. Though as with all engine updates that modify map serialization: keep a backup of your maps.
