### ISSUE TITLE
Replay UI disappears if entering the round during recording

### ISSUE THREAD

**Issue by 20kdc** [space-wizards/space-station-14#17629]
## Description

The Replay UI disappears if, while recording the replay being played, the Observe button in the lobby is pressed.

**Reproduction**
1. While in the lobby, run `replay_recording_start`.
2. Press Observe in the lobby.
3. Wait long enough that you have something recorded, then end the replay with `replay_recording_stop`.
4. Watch the recorded replay. The game will change state and the replay UI will disappear.

*Notably, a workaround is to spectate a player, as that shifts you back into ReplaySpectateEntityState.*

**Screenshots**
Due to the "round the replay is from hasn't endeed" problem I can only really send this:
![image](https://github.com/space-wizards/space-station-14/assets/22304167/371d2e18-5505-43a7-954a-48c6bb27ec4c)

**Additional context**
I have an example replay of this, but it's a bit longer than it really needs to be and the round it's from hasn't ended.

**Comment by ElectroJr** [comment]
I think the lobby buttons raise network events that cause the UI state to change. Replay playback just needs to filter out those network messages and not replay them.
