### ISSUE TITLE
Debug > Rejuvinate should restore stamina to full

### ISSUE THREAD

**Issue by keronshb** [space-wizards/space-station-14#17645]
## Description

Right now it doesn't. It should to help testing.

**Comment by Geekyhobo** [comment]
Looked into fixing this, turns out I'm pretty sure it does. did some debug testing on the current build and it also works there, do you have a screenshot or anything?

in StaminaSystem.cs in Shared has it on line 122 if I'm not mistaken

**Comment by Vordenburg** [comment]
I had a look myself. Is this not actually working?

https://github.com/space-wizards/space-station-14/blob/9124c60db23710c012be30c49468e3b941cae07b/Content.Shared/Damage/Systems/StaminaSystem.cs#L131-L141
