### ISSUE TITLE
Salvage Expedition Rock Reappearing

### ISSUE THREAD

**Issue by crazybrain23** [space-wizards/space-station-14#17658]
## Description

It seems like rocks can appear where ore used to be on expeditions. Possibly caused by mining, leaving, and returning?
**Reproduction**

Quote from ahelp: "I finished mining the area, went back to get my bag and somehow all the rocks reformed, normal rocks this time."
**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/44417085/fcd254f9-deb8-4adb-88e2-86e426112bdd)

**Additional context**

**Comment by metalgearsloth** [comment]
I've been busy the past few weeks so something's gone wrong elsewhere in the diffing code.
