### ISSUE TITLE
Bug: Bags can be overloaded with new item size scale

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#17659]
## Description
Bags can be overloaded past maximum with new proportional stack size.

**Reproduction**
Add a smaller partial stack of an item/stack near full bag, I tested with plastic and steel. then put the rest of a stack back in to the bag and it will go beyond the maximum.

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/47093363/f9f8583c-ae10-4495-ab71-ce77616174c2)

**Additional context**
Pretty sure directly originates from this PR.
#17623

**Comment by EmoGarbage404** [comment]
Fixed by #17651
