### ISSUE TITLE
Rock guitar melee needs nerfing

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#17669]
It does 20 damage when wielded which is more than the captain's sabre.

**Comment by moonheart08** [comment]
just have it smash into pieces after being used as a weapon.

**Comment by Tyzemol** [comment]
[tf2 guitar smash](https://youtu.be/61VDsd8A3mw?t=54)
:)

**Comment by LankLTE** [comment]
> just have it smash into pieces after being used as a weapon with appropriate guitar destruction noises.

Thing is, it's really funny to see some musician attacking something with a rock guitar. I think having a guitar smash into pieces would fit better with an acoustic or electric guitar as those are more traditionally smashed- leave the rock guitar as the "axe".
