### ISSUE TITLE
Add the nervous system to manage a body's brain/consciousness

### ISSUE THREAD

**Issue by DrSmugleaf** [space-wizards/space-station-14#1768]
Just as CirculatoryNetwork (should) manage the bloodstream and RespiratoryNetwork (should) manage breathing, a NervousNetwork should be added that handles consciousness for the player and the transfer of the brain. As it stands right now however, the brain is just a souvenir, as it doesn't have any behaviors that do anything.

Related to #1757

**Comment by Zumorica** [comment]
Would you consider this fixed by #2284?

**Comment by DrSmugleaf** [comment]
> Would you consider this fixed by #2284?

Yes. More complicated brain behaviors can come later.
