### ISSUE TITLE
Medical scanner interface will be blank if nobody has entered it

### ISSUE THREAD

**Issue by SoulSloth** [space-wizards/space-station-14#1774]
Reproduction steps:
1. Click on a medical scanner before anyone has been put in it.
Expected results: The interface spawns with a message indicating that no patient is present:
![image](https://user-images.githubusercontent.com/67545203/90458448-6fb05a00-e0cc-11ea-9eb8-9e17392182a2.png)
Actual Results: Nothing is printed in the dialog:
![image](https://user-images.githubusercontent.com/67545203/90458407-55767c00-e0cc-11ea-9355-6c96c4090123.png)

`UpdateState` in MedicalScannerBoundUserInterface.cs is not called before someone has entered the scanner

**Comment by SoulSloth** [comment]
assign this to me as it can be handled along with #1473 .

**Comment by Zumorica** [comment]
Consider yourself asigned.
