### ISSUE TITLE
ame injection goes up in 1s

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#17752]
## Description
introduced by ecsification

**Reproduction**
1. find ame controllre
2. increase injection
3. 3!!!!

**Comment by AJCM-git** [comment]
@TemporalOroboros a

**Comment by TemporalOroboros** [comment]
> @TemporalOroboros a

Should I bother?

**Comment by AJCM-git** [comment]
> > @TemporalOroboros a
> 
> Should I bother?

i beg, it will literally kill our ocd community
