### ISSUE TITLE
AI visualizer's broken

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#1776]
BodyManagerComponent chucks a tanty when mobs try to use the DamageStateVisualizer.

**Comment by metalgearsloth** [comment]
@DrSmugleaf you fixed this right

**Comment by DrSmugleaf** [comment]
> @DrSmugleaf you fixed this right

Yes.
Fixed by https://github.com/space-wizards/space-station-14/pull/1840
