### ISSUE TITLE
Nuclear operatives are too weak compared to the station

### ISSUE THREAD

**Issue by DadeKuma** [space-wizards/space-station-14#17787]
## Description
Nukies are bad, like **really bad** compared to the station, which is getting stronger and stronger each day (salvage ops, new security tech tree...), plus they are getting nerfed too much (e.g. no more chem).

Right now, Nukies feel like a bunch of thugs that are trying to rob the station. They should feel like a group of elite, experienced, and **DANGEROUS** agents that are always a threat to the station, no matter what.

More detailed info is available on this Liltenhead [video](https://www.youtube.com/watch?v=Ds-882Y2PMc&t).

**Reproduction**
- Play Nukie
- Get rekt by the greytide unless you have an elite team and the station is full of brainless monkeys
- Cry in a corner

**Possible Solutions**
- Increase the number of TC available to operatives (double it, or +50%)
- Rework all the traitor weapons so they are all viable
- Nerf salvage/sci/sec (please don't)

**Comment by deltanedas** [comment]
fishops numero uno!!!!!! :trollface:

**Comment by lzk228** [comment]
just make the fucking rules about powergaming and validhunting

**Comment by Equivocateur** [comment]
> just make the fucking rules about powergaming and validhunting

Cue the rules lolyering about escalation rules regarding the fact that nuclear operatives are there to kill everyone on the station in nuclear fire therefore validhunting does not apply because everything done against nukies is self-defense

**Comment by Geekyhobo** [comment]
Opened a pr for this, I believe that the only solution here was to change the bundle prices because adding tc to Nukie would make them op.

**Comment by Emisse** [comment]
was nukie chem really powerful enough to be a boon

**Comment by Slava0135** [comment]
Nukies often forget their main objective is to get the disk as fast as possible, not kill everyone they see. There are also stealth options, like hiding with stealth box or using chameleon or taking crew suits with ID stolen.

I think nukies are too afraid to drop their red suits and try different approaches.

**Comment by Ilya246** [comment]
a big issue is that if you don't raid armory, the armory raids you
plus stealthops **always** get metagamed and just don't work because of that

**Comment by Slava0135** [comment]
How about giving nukies 10 more TC but don't give them blood red suits (except commander and agent)

**Comment by deltanedas** [comment]
1. fishops12345
2. follow pinpointer
3. open pandoras box
4. arm nuke
5. success

**Comment by HoidC** [comment]
> How about giving nukies 10 more TC but don't give them blood red suits (except commander and agent)

may as well give them 2 extra tc

**Comment by deltanedas** [comment]
all classes start with noslips no extra tc

**Comment by Myakot** [comment]
How about nukie players learn how to count, then count the number of hardsuits the station has, then just space the entire station with an axe or an esword. Why fight 5v50, when you can cut the number by 5 or more. (and emergency suits have SUCH RIDICULOUS movement penalty, even if they don't die - it's still strong)

**Comment by deltanedas** [comment]
again spacing the station isnt your goal getting the disk is
