### ISSUE TITLE
cluster speedloader .35 in detectives cabinet

### ISSUE THREAD

**Issue by DummeHytteOst** [space-wizards/space-station-14#17793]
there spawns a .35 speedloader in the detectives cabinet on cluster, the detectives revolver no longer use .35, it uses .45 

it was most likely forgot about, and never got removed when the change was made

https://github.com/space-wizards/space-station-14/blob/b4a89c009e68c03f7d0f036cd1b7265252bacd8b/Resources/Maps/cluster.yml#L70328

**Comment by Boaz1111** [comment]
adressed, should be closed
