### ISSUE TITLE
Syndicate codewords are not useful/used

### ISSUE THREAD

**Issue by DadeKuma** [space-wizards/space-station-14#17790]
## Description
Most people forget their codewords, so it would be really great to mark these in the chat with a *red/blue* color that is visible only to other Syndicates.

The issue is that no one remembers these codewords, so they aren't useful. But if they are shown as visible feedback this won't happen again.

**Reproduction**
- Play as a Syndie, find another Syndie
- Say a codeword to prove that you are also a Syndie
- Get shot and killed as the other one doesn't remember any codewords

**Additional context**
None

**Comment by dmnct** [comment]
If this is considered making it too easy to spot codewords on General Radio, alternatives would be to highlight them on the chat popup boxes only, or to introduce an easier way to keep them in your field of view such as an on-by-default setting to have them written at the top of your screen in a small overlay

**Comment by Equivocateur** [comment]
Whats the problem with making it easy to spot - you're the informed minority on the station and it should be easy to find each other roundstart.

**Comment by asperger-sind** [comment]
i think it's just not coded yet:tm:
everyone wants silly codeword highlighting

**Comment by KaiShibaa** [comment]
Just know that they could kill you even if they also know codewords. Syndie agents are not a team and it's always a risk to out yourself to another syndie because they might kill you for your equipment or TC if it benefits them. 

This won't change anything with what the other syndie will do.

**Comment by Myakot** [comment]
I find it rather amusing personally. Current list of codewords is so random you can't possibly ignore them in a conversation. They are so out of the left field you **have to** notice that something's wrong and it's not a sentence a sane human would say.

**Comment by deltanedas** [comment]
Well isnt this an old-fashioned issue.

**Comment by JustinTrotter** [comment]
> I find it rather amusing personally. Current list of codewords is so random you can't possibly ignore them in a conversation. They are so out of the left field you **have to** notice that something's wrong and it's not a sentence a sane human would say.

On several occasions I've dropped code words in conversation with players I've been tasked to work with, only for it to fly right over their heads. I had to break down and write a message explicitly telling them on a paper and hand it to them. On at least one occasion they didn't even realize they rolled syndie until I told them directly.

**Comment by Emisse** [comment]
I think having it highlight the word in text for other syndis would be good

**Comment by JustinTrotter** [comment]
Ive been looking into implementing this for a bit and am running into issues with getting ahold of the code words from the TraitorRole component (controlled server side) and handing it to the speechBubble system (controlled client side).

If I remember correctly, the Mind component/system is getting reworked. Should implementing this hold off until the rework is done or can anyone think of a clean way to send the code word data and if the user has a traitor to their speech bubble system?

**Comment by Interrobang01** [comment]
Depending on the fraction of people who miss codewords because they simply don't realize they're syndicate, I think just making syndicate membership more obvious is the best solution; currently the only way to know if you're a syndicate if you miss the message is if you press the dedicated "am I a syndie" button.

Putting codewords at the top of the screen makes sense.

**Comment by deltanedas** [comment]
if you are shooting up medbay you will probably not notice the codewords are the top of your screen, having text highlighted red so you know someones cool would help

**Comment by beck-thompson** [comment]
codeword highlighting has been added so this isn't an issue anymore (If anything they use them TOO much)!
