### ISSUE TITLE
Salvage Magnet Issues?

### ISSUE THREAD

**Issue by AjexRose** [space-wizards/space-station-14#17799]
## Description
Seems the magnet for salvages just.. doesnt work? While playing on Lizard, Ive tried to use the magnet multiple times with each time resulting in the "failed to pull debri message" Ive tried reconstructing it, reangling it, and relocating it, but it never pulls debria. 
**Reproduction**
1. Be salv
2. go to magnet
3. Press magnet to pull in
4. wait
5. Nothing

**Comment by EmoGarbage404** [comment]
this has been reported and i need more info than "it doesn't work" because it literally has 100% reliability while testing on the dev map.

**Comment by spectralSpices** [comment]
My guess is, they're attempting to use it on station. Even on a shuttle, I have to take the magnet out rather far-around 120-150 meters-from the station to make it work. 

Whatever you changed to make the magnet more reliable seems to have made it less so-it can't seem to generate debris at distances it was able to in the past. 
Can you show us what the area where the magnet looks like on the dev map? That may be useful in differentiating between what's allowing it to work there, while not working in-game.

**Comment by metalgearsloth** [comment]
Just report which maps it happens on.

**Comment by Emisse** [comment]
Happens on marathon for me 90% of the time

**Comment by spectralSpices** [comment]
I've also experienced it with the magnet in the default position of Saltern, Omega, and Cluster. Even on the cargo shuttle docked, it consistently can't draw a salvage.
