### ISSUE TITLE
rmobjective still does not work

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#17889]
## Description
title

**Reproduction**
1. tator antag ctrl
2. lsobjectives
3. rmobjective username 0
4. no

**Screenshots**
![01:48:58](https://github.com/space-wizards/space-station-14/assets/39013340/3851cdc1-a79f-4f15-a59d-32062b5a6c74)

**Comment by Vaaankas** [comment]
i fixed it yay 18033
