### ISSUE TITLE
The number of Nukies should be determined by total players in the lobby 

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#17903]
## Description
Currently, the number of nukies that get spawned is determined by how many people are readied up at round start. This can lead to a skewed disadvantage for the nukies, since there are always a good handful of people that deliberately choose not to ready up so they can late join as soon as the round starts. 

For example, if 26 people ready up there would be 2 nukies. 7 people then late join right after the round starts bringing the total station population up to 31, so in this case there should have been 3 nukies.

If we decided to determine the amount of nukies that spawn based on the number of players in the lobby this could help fix this issue. Of course this might work the other way around if people AFK in the lobby and leave the game, but i believe this will help make the population difference more fair and balanced. 

There is also the issue that more people would naturally join the game and become crew on the station as the round progresses. This puts the nukies at a even larger population disadvantage if they drag their feet getting to the station, but this is mostly a skill issue moment. Regardless it still impacts the round and should still be considered.

**Additional context**
Thoughts on this?

**Comment by deltanedas** [comment]
yeah every time its nukies i always see 2-4 operatives which isnt fair

**Comment by Aisu9** [comment]
can't there be just additional nukie spawn as people join the station?
it's unlikely to happen but imagine there is 80 person in the lobby, the gamemode start and there is the maximum number of operatives. but only X% of the players join / disconnect

**Comment by Mudsson** [comment]
I think this is a good change, having seen two nukies have to go against 40 or so crewmembers

**Comment by Peptide90** [comment]
> can't there be just additional nukie spawn as people join the station?
> 
> it's unlikely to happen but imagine there is 80 persons in the lobby, the gamemode start and there is the maximum number of operatives. but only X% of the players join / disconnect.
> 
> Progressive spawn of operatives doesn't sound bad because most of them take a while to prepare

Can't see how this would work. Would it pop up before the late join actually joins after clicking the open role? What if the nukie ship leaves? It would be easier and better to just use the total players in the game. Counting observers shouldn't impact much.

**Comment by EmoGarbage404** [comment]
might just make sense to have the ready up button defaulted to true. if a large percentage of people are late-joining, it might just be because of not remembering to hit the button.

**Comment by LankLTE** [comment]
> might just make sense to have the ready up button defaulted to true. if a large percentage of people are late-joining, it might just be because of not remembering to hit the button.

I'm like 90% sure it's just people wanting to select their role / backfill. Least I'd guess so.

**Comment by EmoGarbage404** [comment]
> I'm like 90% sure it's just people wanting to select their role / backfill. Least I'd guess so. Having the ready up button default to true would defeat the point. You aren't "readying up" if it's just putting you in. It'd also probably lead to a lot of SSD people being ingame.

if people are latejoining to just get in extra role slots, then we should adjust how those extra slots are added. Maybe have them only be opened if the server pop exceeds the max pop for the map.

**Comment by LankLTE** [comment]
> if people are latejoining to just get in extra role slots, then we should adjust how those extra slots are added. Maybe have them only be opened if the server pop exceeds the max pop for the map.

I don't mean extra role slots. I didn't even know it opened more slots when you latejoin. I just meant that there have been times where I don't want to play any specific role, so I latejoin and join a department that could use more people. I imagine sometimes people do the same. 

It's also possible that the noise on the roundstart lets people who were tabbed out know that a new round started, to which they join. I don't really see people latejoining as an issue, in all honesty, and think basing it on server pop is a fine workaround.

**Comment by keronshb** [comment]
> might just make sense to have the ready up button defaulted to true. if a large percentage of people are late-joining, it might just be because of not remembering to hit the button.

This is a massive issue on Citadel main where some of the population is less keen on antags and do a forced late-join to try an attempt to put them at disadvantage or prevent them from spawning.

**Comment by Kayek14** [comment]
Here is an example of a round. Game has 61 players but only 3 nukies. 

There was a total of 21 late joins within 15 mins of the round starting.

Not sure if this is a problem of people not readying up or if people notice a new round is starting and hop to the server. Perhaps the amount of nukies needs to be skewed in favor of them to help alleviate this issue, if its not a issue of people not readying up. 

![image](https://github.com/space-wizards/space-station-14/assets/106507028/fdbbd9de-e50c-4523-a6b6-151fe26eaf8a)
