### ISSUE TITLE
noslips chameleon broke

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#17974]
## Description
there is nothing in the menu
havent checked if it applies to other chameleon items

**Reproduction**
1. get crash round
2. buy noslips
3. cant change them

![01:18:26](https://github.com/space-wizards/space-station-14/assets/39013340/05405ecf-a390-4854-9348-3786404457ca)

**Comment by Equivocateur** [comment]
For some stupid fucking reason it works for me on dev but on lizard it uh killed itself

**Comment by crazybrain23** [comment]
I suspect #17759 might've affected something?

**Comment by Slava0135** [comment]
I suspect #17736, need to dive in

**Comment by crazybrain23** [comment]
> I suspect #17736, need to dive in
> 
> (i think actually no)

this is commit 8762d4a0e799ea44b8d8b5a67fe98677c2fb5e38
![image](https://github.com/space-wizards/space-station-14/assets/44417085/fe3bf9fb-f407-4865-b04d-02904d03c9ed)
