### ISSUE TITLE
expedition sometimes crashing server

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#17976]
## Description
keeps happening on lizard
when ftling it sometimes crashes
had it not crash 1 time, did crash 2 times

**Reproduction**
ftl to exped!!!
it was queen ops on both time so not sure of the actual cause with no logs

**Comment by metalgearsloth** [comment]
Can't repro need more info e.g. any stacktrace, server crash time, anything.

**Comment by deltanedas** [comment]
emo probably fix but one of them was like 3 rounds ago on lizard
