### ISSUE TITLE
Computer disassembly instantly strips computer entity down to frame

### ISSUE THREAD

**Issue by hord-brayden** [space-wizards/space-station-14#17987]
## Description

Was trying to steal cargo board, used screwdriver after it was unanchored and it instantly was transformed into a blank computer frame. Tried it with arcades and consoles of various types with the same result. Anchored or not has the same result

**Reproduction**

Run into bridge
See computers
Use screwdriver
Instantly gib bridge
Get banned 

**Screenshots**

**Additional context**

**Comment by EmoGarbage404** [comment]
Is this not just how computer deconstruction works? Idk if this is an actual bug.

**Comment by deltanedas** [comment]
its hsrd to notice but it uses the added wire sprite i think, still has the board

**Comment by hord-brayden** [comment]
You are both correct, and I'm mistaken. The sprite changed and it threw me off. Typically, it's the sprite with the darkened screen that I relied on to let me know there's still some kind of board in there. No issue here
