### ISSUE TITLE
In-game UI

### ISSUE THREAD

**Issue by ghost** [space-wizards/space-station-14#18]
Let's discuss what it should be. As Urist [wrote in his design doc](https://docs.google.com/document/d/1ULMW0b7rfKQBqrmp_SZ2ce4GpKmfry-U5HhGtN6qCyc/edit):

# UI
http://imgur.com/pxb4Dgd
- [X] Okay so all windows should be resizable and movable; viewport should be always stretching to hit the screen (horisontal or vertical depending on whether the height or the width is bigger) while maintaining square shape and the same actual viewing area.

### Some unobvious stuff:
- [X] Chat has filters you can switch on and off
- [ ] Toolbelt is a hotkey bar. Colour of hand in toolbelt slot shows that the currently selected item in that hand came from that slot in toolbelt and pressing that key again will stow the item back. Small bar on the bottom of the cell shows type of item that can go there (orange for engineering for example).
- [x] PDA modules are basically things you can turn on in the PDA having the appropriate module that provide you with some info at all times.

**Comment by Injazz** [comment]
it can be closed now i think

**Comment by Acruid** [comment]
None of this has been implemented besides the "basic window framework".

**Comment by Injazz** [comment]
okay this can be closed NOW i think
not sure we gonna make that toolbelt feature at all

**Comment by AJCM-git** [comment]
I think this should be closed too

**Comment by AJCM-git** [comment]
closed in favor of #272
