### ISSUE TITLE
welded and bolted airlock sprite

### ISSUE THREAD

**Issue by Fahasor** [space-wizards/space-station-14#18001]
## Description
If you bolt airlock and weld it after then it starts looks like a airlock that not bolted, but it still bolted.

**Reproduction**
Bolt airlock.
weld it.

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/70820551/2bf4f3c8-97f5-451d-9df2-2df54ef53aed)

**Comment by deltanedas** [comment]
are you sure its not an issue with that servers sprites

**Comment by benev0** [comment]
If they (the server from the screenshot) are using the same door sprite system the welds and blit are applied after the door sprite as another layer.

looks as if the blit (tested bolt only) status is mutually exclusive with the weld on the current main branch. Do I was also crashing while testing this passably related to hacking.

![20230713_12h59m15s_grim](https://github.com/space-wizards/space-station-14/assets/50087092/89fb11d2-15f0-45e6-93db-d6ce960a928d)

should probably test discuss the behavior for (edit the comment to bullet points if unnecessary)
- [ ] weld bolt
- [ ] weld access denied 
- [ ] weld emergency access 
- [ ] weld access grated

**Comment by Fahasor** [comment]
> are you sure its not an issue with that servers sprites

I'm not sure. I really bad in development now, sorry

**Comment by Slava0135** [comment]
> If they (the server from the screenshot) are using the same door sprite system the welds and blit are applied after the door sprite as another layer.
> 
> looks as if the blit (tested bolt only) status is mutually exclusive with the weld on the current main branch. Do I was also crashing while testing this passably related to hacking.
> 
> ![20230713_12h59m15s_grim](https://user-images.githubusercontent.com/50087092/253354141-89fb11d2-15f0-45e6-93db-d6ce960a928d.png)
> 
> should probably test discuss the behavior for (edit the comment to bullet points if unnecessary)
> 
>     * [ ]  weld bolt
> 
>     * [ ]  weld access denied
> 
>     * [ ]  weld emergency access
> 
>     * [ ]  weld access grated

it also seems like doors have different sprites (welded one doesn't have `E`)
