### ISSUE TITLE
Pinpointers only pointing down on marathon

### ISSUE THREAD

**Issue by Geekyhobo** [space-wizards/space-station-14#18019]
## Description

Pintpointer seemed to only point down no matter the screen direction for me and my teammates. happened on marathon station

**Reproduction**

Be me
be Nukie
pinpointer no work
teammates pinpointer no work
be confused
die to army of people because we waited too long to act

**Comment by deltanedas** [comment]
it is possible that cap fucked off in shittle, needs repro

**Comment by Emisse** [comment]
this isnt a map issue
