### ISSUE TITLE
Soap / thrown slipping prediction and abuse

### ISSUE THREAD

**Issue by AJimmyU** [space-wizards/space-station-14#18027]
## Description

Currently thrown slippery items like soap behind one self will always trip up whoever is chasing you, because the speed of the item and inherent network delay makes the thrown soap appear too late to be dodged. This combined with dozens of soaps spawning in maintenance, or just simple peel production, makes everyone onboard capable of performing long duration (enough to cuff) instant ranged stuns against people chasing them.

I propose that items that are in flight or otherwise moving, become non-slip.
Alternatively, make soap/peel slips not be a hard stun and just a slowdown without item drop.

**Reproduction**

1. Play one round of security

**Screenshots**

**Additional context**

Instant stuns are bad for the game. Syndicate soap shouldn't retain functionality.

**Comment by deltanedas** [comment]
sec malding git gud :trollface:
