### ISSUE TITLE
intercom speaker using wrong channel

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#18022]
## Description

**Reproduction**
1. find engi intercom
2. turn on speaker, set to engi channel
3. speak on common
4. the intercom says it!!!

![06:39:48](https://github.com/space-wizards/space-station-14/assets/39013340/e7d6ecdc-5fb3-4306-8aeb-f719361f6da9)

**Comment by Plykiya** [comment]
thank you emogarbage
