### ISSUE TITLE
Kudzu spreads absurdly fast

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#18021]
IDK what happened but it's like 5 tiles a second and is unbeatable even with 4 people going ham on it.

Also (totally not current round) 30 goats that are multiplying still can't successfully contain it.

**Comment by Anzarot121** [comment]
And it has either learned to grow through walls, or now, during an event, it spontaneously spawns several times in one place.

**Comment by HoofedEar** [comment]
Hm is there a preferred rate of growth that would be better? Half as fast, like 2/3 tiles per second?

**Comment by Bixkitts** [comment]
Was just hacking away at spreader system and kudzu specifically (pun intended),
it grows at 1 tile per second for the node group and can be quite easily contained with 5 goats and
some hitting
