### ISSUE TITLE
pAI and other speakers in inventory are hard to tell apart

### ISSUE THREAD

**Issue by AJimmyU** [space-wizards/space-station-14#18071]
## Description

pAI inside inventory of a character talking in local chat results in the same identical popup above a character as if the character itself was speaking, often overlapping with actual messages from said character. There should be a clear indicator that the mob is not speaking and rather something inside their inventory is speaking.

**Reproduction**

1. have talkative pAI in bag
2. observe confusion when talking

**Screenshots**

**Additional context**

Chat bubbles and/or colored text for multiple speakers could be a solution.

**Comment by slarticodefast** [comment]
Fixed by #21999
