### ISSUE TITLE
All doors should have per-department randomized wires.

### ISSUE THREAD

**Issue by keronshb** [space-wizards/space-station-14#18077]
Instead of globally randomized wires, the departments should have their own randomized wires.

EX) Currently - Command doors have the same bolt and power wires as Maint doors.

EX a) Change - Command doors would have their own bolt & power wire, Maint doors would have a different set, as would Security, Science, etc.

**Comment by keronshb** [comment]
#18078 

In conjunction for door security

**Comment by asperger-sind** [comment]
Pretty sure this was partially implemented a while ago where "secure" (sec, vault, command) airlocks have their own separate wireset, then vaults got their own larger maint panel and as per such a different wireset but I think command and sec should still have this property?

or i could just be gaslighting myself on a pr that went derelict or a discord discussion that never want anywhere

**Comment by HoidC** [comment]
> Pretty sure this was partially implemented a while ago where "secure" (sec, vault, command) airlocks have their own separate wireset, then vaults got their own larger maint panel and as per such a different wireset but I think command and sec should still have this property?
> 
> or i could just be gaslighting myself on a pr that went derelict or a discord discussion that never went anywhere

secure airlocks have a different wireset and vault has like 15 wires yeah

**Comment by Myakot** [comment]
> > Pretty sure this was partially implemented a while ago where "secure" (sec, vault, command) airlocks have their own separate wireset, then vaults got their own larger maint panel and as per such a different wireset but I think command and sec should still have this property?
> > or i could just be gaslighting myself on a pr that went derelict or a discord discussion that never went anywhere
> 
> secure airlocks have a different wireset and vault has like 15 wires yeah

Which, sadly, still has the same wire set, so basically no difference. Can't even think of anything interesting to add to those extra dud wires, besides just damaging the player for a reason...

Maybe implement a recently merged deathrattle setting to some of the vaults wires? So that the whole sec would get a message, that a door is getting cut apart.

**Comment by slarticodefast** [comment]
Fixed by #26247
