### ISSUE TITLE
Ghosts are affected by grav anomaly

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#18095]
I noticed that the gravity anomaly like, you know sometimes you cant move when it pulses? That happened even while i was a ghost. Silly as hell, but should be fixed.

**Comment by lzk228** [comment]
dupe, pretty sure

**Comment by deltanedas** [comment]
i think dupe too but cant find

**Comment by UbaserB** [comment]
Found it #14028, will close this issue then since its basically the same thing
