### ISSUE TITLE
admin notifications should has sound

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#18092]
## Description

Admin notifications like prays, centcomm or honkmother calls and explosions should has sounds like achat and centcomm faxes

**Comment by lzk228** [comment]
prayers do have sound, but explosions still not

**Comment by lzk228** [comment]
oh wait explosions too have a sound so closed

**Comment by IProduceWidgets** [comment]
> prayers do have sound, but explosions still not

This does not appear to be the case. If its a recent PR please link because maybe my search-fu is bad.
