### ISSUE TITLE
Grappling gun needs respriting

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#18118]
Artist doesn't want it on the repo anymore.

**Comment by UbaserB** [comment]
what specifically about it need reworking?

**Comment by Emisse** [comment]
it needs a new sprite

**Comment by UbaserB** [comment]
oh yeah, im dumb. I might try making a new sprite for it but ill see

**Comment by metalgearsloth** [comment]
Resolved in https://github.com/space-wizards/space-station-14/pull/18939
