### ISSUE TITLE
Moving around in macos causes AL errors

### ISSUE THREAD

**Issue by VasilisThePikachu** [space-wizards/space-station-14#18119]
## Description

**Reproduction**

1. Join with a device running a version of macos (in my case M1 Air With MacOS beta 14)
2. Move around with the console open

**Screenshots**

<img width="751" alt="image" src="https://github.com/space-wizards/space-station-14/assets/34938708/41960b2b-a77c-4a89-86aa-075a58d68faf">

**Additional context**

Probably a robust toolbox issue and may need to be moved there. Reproducible on upstream and downstream. Only tested playing a ghost but i assume it wont make a difference

**Comment by Krosus777** [comment]
I have the same problem.  After 10-15 minutes of spamming this error, the sound in the game disappears.
