### ISSUE TITLE
Hammy starves while in cage

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#18138]
Even when not controlled by a player, hamlet starves quickly and takes a lot of damage. When in a cage, they cannot wander around and eat food themselves.

I propose making it so that when hammy is in the cage their hunger wont drop, so it gives players a chance to wander around instead of being forced to eat food the moment they are taken out.

Not sure if this is applicable with other pets, but if it is this should be fixed asap.

**Comment by Emisse** [comment]
anything that isnt a player race is incapable of taking starvation damage

**Comment by EmoGarbage404** [comment]
are we sure mice don't take starvation damage?

**Comment by Emisse** [comment]
i never added it to them

**Comment by UbaserB** [comment]
oh ok, i just saw one of my friends take damage out of nowhere as hammy, with red hunger, so i assumed otherwise
