### ISSUE TITLE
Premature Nukie Loss Despite Them Being Alive

### ISSUE THREAD

**Issue by Alekshhh** [space-wizards/space-station-14#18145]
Somehow during a nukie round, both nukies disguised using a DNA scrambler were going after the captain in space. One nukie died from space while the other pursued the captain. While the last nukie was alive, the round summary tab popped up, ending the round in a nukie loss. I have no clue how this could have happened other than it somehow being related to DNA scramblers, but this is a guess.

**Comment by Equivocateur** [comment]
> are you sure the last one wasnt a reinforcement also scrambler uses polymorph so its possible the new entities count as dead

Nukie reinforcements count as nukies now

**Comment by Vaaankas** [comment]
> are you sure the last one wasnt a reinforcement also scrambler uses polymorph so its possible the new entities count as dead

The new entities probably dont have the NukeOperative component, and thats what counts for the victory condition.

**Comment by deltanedas** [comment]
tbh using polymorph for it is very brittle and more issues like this will pop up over time

**Comment by Vaaankas** [comment]
> tbh using polymorph for it is very brittle and more issues like this will pop up over time

yea, it really should change the humanoid appearance, not just polymorph into a human.

I just tested it and this implant can turn a carp into a man

**Comment by Alekshhh** [comment]
you're telling me a shrimp planted this nuke

**Comment by deltanedas** [comment]
bringing mouseops to a whole new level
