### ISSUE TITLE
DNA Scrambler implant can turn any sentient mob into a human

### ISSUE THREAD

**Issue by Vaaankas** [space-wizards/space-station-14#18147]
**Reproduction**
Spawn mob
Inject DNA Scrambler implant
Control mob
Activate the implant
Become a human!

**Comment by dmnct** [comment]
Kitsune Renault is real

**Comment by deltanedas** [comment]
Detroit: Become Human

fix:
- not allow scrambler implant to be used on non humanoids duh
- randomise the appearance directly and not use polymorph since that leads to other issues

**Comment by Arendian** [comment]
I think sentient mobs being able to turn into a human is fine since the transformed mobs still have to follow the ghost role rules they previously accepted. Being a mouse transformed into a human does not suddenly make you an antagonist.

**Comment by Equivocateur** [comment]
![image](https://github.com/space-wizards/space-station-14/assets/109166122/eaef70ca-56de-418b-a036-5bcc33c1ebec)
You somewhy can implant pAI's, they wont morph though.

**Comment by Arendian** [comment]
This means nukies can also implant them with microbombs, sentient grenades/mines!

**Comment by deltanedas** [comment]
pai ops real

**Comment by keronshb** [comment]
> 

LMFAO

**Comment by keronshb** [comment]
> This means a nukie can also implant their PAI with one or multiple microbombs now that they are purchaseable, sentient grenades/mines!

LMFAO

Make an issue with this video because PAI shouldn't be injectable with anything, implants especially.
