### ISSUE TITLE
gibbing ian wont give you the prime cut meat

### ISSUE THREAD

**Issue by JoeHammad1844** [space-wizards/space-station-14#18158]
## Description

if you gib ian, with either brute force or a minibomb there will be no prime cut corgi meat
**Reproduction**

just give ian a minibomb
**Screenshots**

N/A
**Additional context**

with how it is currently if you gib ian you will never be able to get the prime cut corgi meat, making the objective impossible

**Comment by EmoGarbage404** [comment]
how does exploding your target into a red smear constitute a "prime cut"

**Comment by mirrorcult** [comment]
well then dont explode a dog with a bomb

**Comment by JoeHammad1844** [comment]
now you see, the bomb's fragmentation acts as tiny knives that expertly cut the meat into kitchen-grade meat

**Comment by Aisu9** [comment]
i don't know what to say, hunter hunts with grenades and C4 in my country
