### ISSUE TITLE
pistols and the bulldog dont have the ammo UI

### ISSUE THREAD

**Issue by JoeHammad1844** [space-wizards/space-station-14#18157]
## Description

you know when you hold the C20R or the L6 or the lecter and you have that little UI showing the bullets above the inventory? that isnt present on any pistols or the bulldog
**Reproduction**

just hold a pistol or the bulldog
**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/130668733/25359667-a7dd-46fa-bcd3-7f4c7ba6ea29)
![image](https://github.com/space-wizards/space-station-14/assets/130668733/19f2fa51-75aa-41b6-ac2b-67506e5e48c6)

**Additional context**

it makes it harder to see how much ammo you have left without memorization, which sucks in combat

**Comment by Vaaankas** [comment]
Added counters to bulldog and china-lake in #18165
I dont think pistols need those tho, i think its much a cooler image having to manually check the ammo, especially since pistols are more often used in peaceful RP or stealth ops.

**Comment by GoodWheatley** [comment]
Closed by #18165
