### ISSUE TITLE
Salvage Shuttle should not be roundstart

### ISSUE THREAD

**Issue by Emisse** [space-wizards/space-station-14#18163]
the gameplay loop of salvage when they had even less content was centered around shuttle building which people really enjoyed, i think they should have to salvage their own shuttle before starting expeditions. this will do two things.

1. make people rushing to do expeditions and immediately dying stop by a lot
2. make people engage with the shuttle building mechanics of our game which are a lot of fun
3. skub

im not sure if we want to have a way to link salvage drone pilot console to their own shuttle or just remove it, maybe also a way to link the expedition to the shuttles computer once its built so random people dont show up on the expedition.
thanks for coming to my ted talk

**Comment by metalgearsloth** [comment]
Might need to make shuttle materials cheaper as well, like 1/4 price or the likes.

**Comment by HoidC** [comment]
will having to Hey! Assemble the Salvage Shuttle! And off to the Expedition! not get old after the first few times

**Comment by Emisse** [comment]
no because its fun, just need to make construction a bit easier maybe

**Comment by Interrobang01** [comment]
make it more fun with mandatory Shuttle Bonus Lootboxes! "not again, i already have 19 thrusters!"

or just map most of the essential shuttle equipment roundstart, boiling it down to a basic 5-minute assembly period should stay fun for a while

**Comment by Emisse** [comment]
we can figure out mapping later id rather just have the shuttle removed first tho to see what would be needed

**Comment by deltanedas** [comment]
noooo i dont want to use magnet

**Comment by UbaserB** [comment]
Are you going to remove the shuttle again or is it staying for good this time

**Comment by K-Dynamic** [comment]
You want to remove shuttle, then make magnets work closer to station (currently inconsistent, such as Aspid where extending it out doesn't seem to let you draw debris in)

**Comment by deltanedas** [comment]
iirc thats a bug related to using map AABB to check if a rock spawn will fit, which usually overlaps space a lot with random rotations

**Comment by dvir001** [comment]
As someone who used to build shuttles this gets very old very fast, and a lot of times people wont even get to finish building them before the round is over.

You can add the shipyard system and allow salvage to buy the ships to skip this hassle while they can still make the call to build one to save on money, then you can go and remove it and im sure no one will mind it that much.

**Comment by Emisse** [comment]
we have ideas but we r removing roundstart shuttle, we r gonna make building better and rebalance all of salvage from the ground up

**Comment by MilenVolf** [comment]
Should be closed by now, 'case salvage shuttle was removed.
