### ISSUE TITLE
Disposable Turret for syndie identification?

### ISSUE THREAD

**Issue by Interrobang01** [space-wizards/space-station-14#18171]
## Description

The Disposable Turret ignores syndies, meaning sec could in theory capture a turret and use it for identification.

**Reproduction**

1. Create a bunch of civilians
2. Control a civilian
3. Make them syndie
4. Cry because controlled civilians don't get a right-click context menu for some reason
5. Make an urist steal their clothes instead, THEN make them syndie
6. Slap down a turret
7. Watch as the turret totally ignores the syndie whilst mauling all the civilians

**Screenshots**

_I wonder who it is..._
![image](https://github.com/space-wizards/space-station-14/assets/113810873/46921583-e3c2-4525-a754-07c7398cace7)

**Additional context**

[sorry](https://en.wikipedia.org/wiki/Wikipedia:Don%27t_stuff_beans_up_your_nose)

**Comment by deltanedas** [comment]
this is only an issue while it has no ammo, then it can be used to validcheck easily without casualties
turrets shouldnt do anything when empty

**Comment by Interrobang01** [comment]
a couple of mildly shot innocents are pennies compared to the majesty of a perfect syndie identifier, plus the new changes allow sec to reconstruct the turret to refill its ammo if it gets empty

**Comment by deltanedas** [comment]
pingus can already be used for a more controlled validcheck and i actually havent ever seen it used
a turret seems far more dangerous than keeping a pingu locked in a crate
