### ISSUE TITLE
how to permanently brick an implant

### ISSUE THREAD

**Issue by JoeHammad1844** [space-wizards/space-station-14#18176]
## Description

in this guide I will tell you how to make it impossible to use an implant in two simple steps
**Reproduction**

step 1: alt click the implant
step 2: drop the invisible implant
**Screenshots**

N/A
**Additional context**

thanks for watching guys make sure to smash that like and ready button

**Comment by lzk228** [comment]
screenshot/video?

**Comment by keronshb** [comment]
Replicated. I thought I turned that functionality off.
