### ISSUE TITLE
pinpointer broke

### ISSUE THREAD

**Issue by JoeHammad1844** [space-wizards/space-station-14#18208]
## Description

pinpointers only point straight down
**Reproduction**

just turn it on
**Screenshots**

cant get a screenshot because I cant find captain right now, you know why? pinpointer broke
**Additional context**

I was playing nukie as i didn't realize it was was broken and it COMPLETELY threw me off and caused my death

**Comment by keronshb** [comment]
Which pinpointer? Medical/Suit Sensor, Nuke Disk?

**Comment by JoeHammad1844** [comment]
nuke disk
