### ISSUE TITLE
cvar to automatically deadmin on joining a round

### ISSUE THREAD

**Issue by Chief-Engineer** [space-wizards/space-station-14#18212]
Could use a cvar that, when set to true, forces a deadmin when someone joins round start or late joins. Doesn't prevent them from readminning and doesn't do anything when you hit observe. Mostly just a small QOL for trialmins and admins who still play the game.

**Comment by PJB3005** [comment]
PLEASE YES

**Comment by Partmedia** [comment]
I have a patch for this without the cvar. How important is it that this is a cvar, as opposed to always being set on Release builds, or hooked into an existing cvar like hub.advertise set to true?
