### ISSUE TITLE
need shuttle timer wallmounts for evac/travel time

### ISSUE THREAD

**Issue by Emisse** [space-wizards/space-station-14#18249]
ideally theyd be generic so they could be synced with arrivals shuttle as well

**Comment by graevy** [comment]
hey i built these (they work with evac and also travel) but i'm at a point where i need to know if they should be synced to individual shuttles or continue to be station-wide

![dotnet_flmjs5HA4E](https://github.com/space-wizards/space-station-14/assets/51971268/e2b80b8c-9aa5-493b-be5a-d07702149f5b)

**Comment by graevy** [comment]
@Emisse

**Comment by Emisse** [comment]
there should be prototypes for arrivals shuttle timers that can be placed at terminals/arrivals and also ones for evac shuttle

**Comment by graevy** [comment]
@Emisse #19471 got merged. there is an `arrivals screen` proto and a regular `screen` proto which gets escape shuttle updates
