### ISSUE TITLE
Core have traitor cap gun

### ISSUE THREAD

**Issue by Tunguso4ka** [space-wizards/space-station-14#18259]
## Description

Core have a traitor cap gun that shoots .45 magnum instead of normal cap gun / or it just loaded with magnum.

**Reproduction**

1. Grab a cap gun
2. Make a joke with officer.
3. He is now dead.

**Screenshots**

![photo_2023-07-24_17-56-50 (2)](https://github.com/space-wizards/space-station-14/assets/71643624/ef289209-80ea-437b-8722-1dfa18d9e6f5)

![photo_2023-07-24_18-08-36](https://github.com/space-wizards/space-station-14/assets/71643624/53c0935d-0c83-4317-9c0f-d3a3f9f23ef8)

**Comment by Tunguso4ka** [comment]
yeah, its traitor item. And cap guns don`t have suffix, so in spawn menu it just "cap gun" and "cap gun".

![2023-07-24_18-20](https://github.com/space-wizards/space-station-14/assets/71643624/4d3d0104-3817-4db1-a5ea-4aa5a0fea122)

**Comment by deltanedas** [comment]
`suffix: Fake` ops

**Comment by Kayek14** [comment]
Leathal traitor loot being mapped into stations is a bad idea. It insensitives metaknowldge and powergaming. Players will start rushing to grab it if its a guarantied spawn and it will only lead to trouble imo.

**Comment by deltanedas** [comment]
its most likely a mistake from them looking identical in f5
