### ISSUE TITLE
Mailing unit sprite needs fixn

### ISSUE THREAD

**Issue by Geekyhobo** [space-wizards/space-station-14#18275]
## Description

when the mailing unit is flushed it changes from the blue color to the disposal color.

**Screenshots**

![20230724214857_1](https://github.com/space-wizards/space-station-14/assets/66805063/0077af53-8864-40a1-b819-1f0de83e0b94)
![20230724214907_1](https://github.com/space-wizards/space-station-14/assets/66805063/a2d825eb-5189-4cfa-bc4a-d93c31e1ffed)
![20230724214924_1](https://github.com/space-wizards/space-station-14/assets/66805063/4468979e-bbad-44f5-b978-e579c641789a)

**Comment by UbaserB** [comment]
This should be closed since im p sure it got fixed with the recent resprite

**Comment by UbaserB** [comment]
turns out it wasnt resolved
