### ISSUE TITLE
Saltern docking at a port that is unpowered along with other misc silly willy things

### ISSUE THREAD

**Issue by KaiShibaa** [space-wizards/space-station-14#18284]
Not sure when but there's a third docking area below the main two original ones for Saltern. 

Arrivals shuttle ignores the two there and docks at the third one below. 

Docking doors on the third are unpowered and also do not align with each other well.

![image](https://github.com/space-wizards/space-station-14/assets/100050424/d5f4d97d-745f-4dd9-ae2a-37eba42b2bb4)

![image](https://github.com/space-wizards/space-station-14/assets/100050424/b3dc44be-3698-4879-aac1-600131772e66)

(Personally there's already good docking here) 

![image](https://github.com/space-wizards/space-station-14/assets/100050424/f3e225fb-caf7-4dbe-a228-5de424614db3)

**Comment by deltanedas** [comment]
pro wire
top is intended for evac so if arrivals docked there you dont get trolled and have to go to mining dock

**Comment by deltanedas** [comment]
arrivals has its own docking arm now so no longer relevant

**Comment by deltanedas** [comment]
@PJB3005 close
