### ISSUE TITLE
unpressurized mailing unit has disposal`s unit texture.

### ISSUE THREAD

**Issue by Tunguso4ka** [space-wizards/space-station-14#18293]
## Description

the same as in the title.

**Reproduction**

1. find mailing unit
2. send something

**Screenshots**

![2023-07-25_16-43](https://github.com/space-wizards/space-station-14/assets/71643624/a1f9ccb5-503b-4788-8af5-40894c047f84)

![photo_2023-07-25_16-43-55](https://github.com/space-wizards/space-station-14/assets/71643624/6090231b-12d5-414a-834a-d9a7c8f6cceb)

**Comment by UbaserB** [comment]
Dupe of #18275, also it might be fixed now im not sure.

**Comment by lzk228** [comment]
> Dupe of #18275, also it might be fixed now im not sure.

still not fixed

**Comment by UbaserB** [comment]
Still a dupe though
