### ISSUE TITLE
breeding inside crate parents offspring to crate

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#18328]
## Description
and when you screwdrive crate the offspring go bye bye
simple enough fix @EmoGarbage404 if you dont snipe i will do it in a bit

also same fix applies for milking, cheese isnt on the grid so you have to bump the grid with a shuttle to make the cows recognize the cheese exists

**Reproduction**
1. put 2 cow in box
2. play gaming music
3. screwdrive
4. baby cow vanish

**Video**

https://github.com/space-wizards/space-station-14/assets/39013340/82786a09-3c01-428f-809e-b8c2350b6776

**Comment by potato1234x** [comment]
bug of the year?

**Comment by EmoGarbage404** [comment]
> bug of the year?

parenting bugs are a dime a dozen. needs better bait-ier pr title.

I suggest "breeding inside of closets produces children with incorrect parents"
