### ISSUE TITLE
Convert Mass Media to Cartridge

### ISSUE THREAD

**Issue by Emisse** [space-wizards/space-station-14#18336]
mass media will need to be converted to cartridge. PDAs will need a new base prototype for "station/crew" PDA's so that nukies or other antags will not inherit this system.

**Comment by PrPleGoo** [comment]
https://github.com/space-wizards/space-station-14/pull/18251

**Comment by Emisse** [comment]
Formatting in the files should be cleaned up. Over abundance of new lines, old namespaces, weird condition format.

**Comment by Emisse** [comment]
NewsSystem should store fields in a news server component in a server entity and be a private static field.

**Comment by PrPleGoo** [comment]
> NewsSystem should store fields in a news server component in a server entity and be a private static field.

Should like also lock in a OriginStation.

**Comment by PrPleGoo** [comment]
#18345
