### ISSUE TITLE
Rat Servant Rules missing

### ISSUE THREAD

**Issue by ThePixel23** [space-wizards/space-station-14#18398]
When you request to be a rat servant, the role information is missing from from the ghost roles text box, replaced with placeholder text 

Reproduction
Become a ghost, either by observing or perishing.
Request to become a Rat Servant

Screenshot
https://files.catbox.moe/30nl5z.png

Pretty sure this happening with other ghost roles, I'll update the issue when/if i find them

**Comment by lzk228** [comment]
gonna check it today

**Comment by lzk228** [comment]
https://github.com/space-wizards/space-station-14/blob/e97e7f813766009a8feb6886b82c34a84202f653/Resources/Locale/en-US/ghost/roles/ghost-role-component.ftl#L47

**Comment by VasilisThePikachu** [comment]
I think in general ghost rules just don't appear sometimes for some weird reason

**Comment by ficcialfaint** [comment]
> I think in general ghost rules just don't appear sometimes for some weird reason

apparently ghost role rules do not use loc strings properly, will fix it tomorrow or later
