### ISSUE TITLE
Error on start server on MacOs

### ISSUE THREAD

**Issue by UFOS228** [space-wizards/space-station-14#18426]
Throws this on start:
[FATL] unhandled: System.IO.DirectoryNotFoundException: Specified directory does not exist: /Users/user/Downloads/bin/Content.Server/

**Comment by ficcialfaint** [comment]
Have you build the server?

**Comment by ficcialfaint** [comment]
The issue is closed since the problem is not related to the repository. If you still have any issues with setting up local server, ask them in #development or #howdoicode channels on Discord.
