### ISSUE TITLE
Crew manifest and News should be programs

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#18420]
## Description

What's the point of the program tab if you keep putting this in settings, if this are not even settings.
**Reproduction**

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/43253663/68225b56-93bd-4f68-9222-f40b342d90d0)

**Additional context**

**Comment by Phill101** [comment]
I will do
![Crew manifest program](https://github.com/space-wizards/space-station-14/assets/28949487/c04b3e62-6f19-4a52-ae5a-42e34617b7bd)
