### ISSUE TITLE
Admin ghost needs to see zombie icons

### ISSUE THREAD

**Issue by Vaaankas** [space-wizards/space-station-14#18438]
Preferrably other HUDs too (when they come)
bonus points if toggleable

**Comment by Titian3** [comment]
Admin ghosts can see zombie icons:


![Image](https://github.com/space-wizards/space-station-14/assets/47093363/6ef3e1e3-5c42-4bfb-9707-c9e9dc37611b)

**Comment by nikthechampiongr** [comment]
This was resovled a while ago. #22194 also made sure that ghosts will always be able to see zombie icons.
