### ISSUE TITLE
escape on emergency shuttle should require being inside

### ISSUE THREAD

**Issue by liltenhead** [space-wizards/space-station-14#18441]
## Description
Unwrenching a thruster on the emergency shuttle and sitting on the lattice shouldn't count as being on the shuttle. People are also RCDing floors down to escape on the outside

**Comment by Aisu9** [comment]
your still by definition on the shuttle

**Comment by liltenhead** [comment]
Okay definitions aside. It is not engaging gameplay. We removed building on the shuttle for this reason.

**Comment by Aisu9** [comment]
because designing the evacuation shuttle as a bombing area, designing the shuttle as traps for players and making greentext easier to achieve good designing choices?
why "everyone" by design are dead from the start?

**Comment by liltenhead** [comment]
I'm not sure what else to add, I just don't think this manner of gameplay is intended based off previous PRs.

**Comment by UbaserB** [comment]
honestly, its fun staying on the outside while you "feel" like you're safe from the chaos... if someone spots you they might catch you as a syndie

**Comment by KaiShibaa** [comment]
Honestly anyone outside of the shuttle should just be gibbed on FTL travel
