### ISSUE TITLE
AccessReader should also read from belt

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#18469]
so you can put pda on belt and be anonymous and can use doors and other

**Comment by ficcialfaint** [comment]
How does it make you anonymous if you still need to stick your PDA with your ID containing your data to the ID scanner?

**Comment by lzk228** [comment]
then you would cover your face, put pda with id on belt and be anonymous with accesses

**Comment by ficcialfaint** [comment]
wdym???? by covering your face you won't make your ID wipe out your info

**Comment by VasilisThePikachu** [comment]
It should read from the belt slot but it should not hide out your information. If it hid information then it would just be abused

**Comment by lzk228** [comment]
> It should read from the belt slot but it should not hide out your information. If it hid information then it would just be abused

it was in ss13, wher you can put your id in collar and put it on
then you're anon and has access
