### ISSUE TITLE
Ian can be used in zero grav to gain (pretty much) infinite speed

### ISSUE THREAD

**Issue by VasilisThePikachu** [space-wizards/space-station-14#18478]
## Description

I'm naming this ian-surfing

Well technically you can push will do and probably hamlet is better but saying ian is way funnier

I accidentally discovered this while goofing around in lizard waiting 20 mins for the shuttle

**Reproduction**

1. Grab ian
2. Disable gravity
3. Let go of your wasd keys
4. keep right-clicking on the direction you want to go, you will slowly gain more and more speed
5. CSGO surfing in ss14 real!

**Screenshots**

https://github.com/space-wizards/space-station-14/assets/34938708/4ac9542b-959f-4539-8a3d-c41c1af3a277

**Additional context**

**Comment by VasilisThePikachu** [comment]
I do not support using this in space

**Comment by deltanedas** [comment]
use ticke instead of dog

**Comment by VasilisThePikachu** [comment]
Fixed by pulling rework not letting you keep right clicking anymore
