### ISSUE TITLE
Make latejoining not hardcoded to presets

### ISSUE THREAD

**Issue by DrSmugleaf** [space-wizards/space-station-14#1848]
So that it can be enabled/disabled mid-game from other sources (e.g. disallow join after shuttle docks at CC, after cult wins, SM cascade, ...).

Originally posted by @PJB3005 in https://github.com/space-wizards/space-station-14/pull/1816#pullrequestreview-471679377

**Comment by DTanxxx** [comment]
Hi, I am keen on taking this issue, can you please assign it to me? Thanks.

**Comment by Zumorica** [comment]
Assigned.

**Comment by brndd** [comment]
This has been fixed by #2028

**Comment by SweptWasTaken** [comment]
Fixed by #2028. Closing.
