### ISSUE TITLE
Potted plants can noclip through doors

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#18481]
## Description
You can cause potted plants to phase through closed doors/airlocks while dragging it and when you push it into a door.

**Reproduction**
1. Find a potted plant
2. Drag potted plant to an airlock 
3. Use the hotkey to push the potted plant into the airlock
4. The potted plant will noclip through the airlock

**Comment by deltanedas** [comment]
also works with bodybags to smuggle people into somewhere

**Comment by Kayek14** [comment]
This issue seems to be resolved. I can no longer push potted plants through closed airlocks.
