### ISSUE TITLE
Human brain can move when gibbed

### ISSUE THREAD

**Issue by crazybrain23** [space-wizards/space-station-14#18503]
## Description
Human brains can move (like #14014). 
**Reproduction**

1. Spawn Urist McHands
2. Control Mob
2. Get gibbed
4. Move as brain
5. Return to body to do it again. 

**Screenshots**

https://github.com/space-wizards/space-station-14/assets/44417085/8bd20f72-9835-400b-bae3-284745723ba5

**Additional context**
Does not affect slime cores this time. Haven't tested others.

**Comment by EmoGarbage404** [comment]
there is a random fix for this in the borg pr (#18136) i'm pretty sure it's just removing inputmover from the brain.
