### ISSUE TITLE
A way to mute someone's chat

### ISSUE THREAD

**Issue by Chief-Engineer** [space-wizards/space-station-14#18527]
## Description

Can be just a command to start off, but having it easily accessible from ahelp would be ideal. Should mute people from all chat channels:
- Local
- Emote
- LOOC
- OOC
- Dead chat

Shouldn't mute people from ahelp. Should persist across mind transfers, round restarts, rejoins, and work in the lobby. Should not persist across server restarts. Ideally, it should periodically (10 minutes?) send an admin alert to remind admins that someone is muted.

**Comment by deltanedas** [comment]
would also be nice for players to use if someones spamming radio and theres no admins on

**Comment by IProduceWidgets** [comment]
@Chief-Engineer we have Freeze and Mute verb now. Resolved?
