### ISSUE TITLE
Players do not lose handcuffs when turning zombie

### ISSUE THREAD

**Issue by Vaaankas** [space-wizards/space-station-14#18529]
**Reproduction**

Cuff urist
Control a zombie and bite urist until they zombify
Control urist
Urist is unable to attack now as they are still handcuffed

**Comment by EmoGarbage404** [comment]
Do we maybe want this? It'd be good counterplay.

**Comment by LordEclipse** [comment]
Maybe an option for zombies to break cuffs?

**Comment by Vaaankas** [comment]
> Do we maybe want this? It'd be good counterplay.

The main issue is that it is uncounterable, thus permanently turning a zombie harmless and leaving them either bored and dead/ghosted or trying to befriend the crew.

... And the zombie attacks do the bite animation anyway, what would the cuffs even do...?

**Comment by EmoGarbage404** [comment]
Im pretty sure zombies are meant to be uncuffable via removing the comp so it should probably remove all the cuffs when the comp is removed.

**Comment by Vaaankas** [comment]
> Im pretty sure zombies are meant to be uncuffable via removing the comp so it should probably remove all the cuffs when the comp is removed.

The cuffable comp doesnt get removed, from my testing

**Comment by Tynobeard** [comment]
This could allow for chem to have a live source of zombie blood for a ambozol

**Comment by Veritius** [comment]
Recently people have been cuffing themselves when infected which completely disables the zombie. Like, they can't attack at all.
And the zombie can't do anything once cuffed, since they can't break out, or stop being pulled.
