### ISSUE TITLE
cluster using uranium gens

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#18556]
## Description
should use 15kw infinite gens now so comms doesnt lose power due to unfueled
probably happens to other maps too
@Emisse

**Comment by Eden077** [comment]
Can confirm that cluster also loses telecoms extremely quickly

**Comment by deltanedas** [comment]
might happen to origin too from what i remember

**Comment by deltanedas** [comment]
core also no comms power

**Comment by Emisse** [comment]
![image](https://github.com/space-wizards/space-station-14/assets/99158783/cfd9d293-780f-4607-851a-4b7b3d899555)
packed comms runs off the powernet what r u talking about

**Comment by Emisse** [comment]
ah meta uses a gen since its on ai core i can update that

**Comment by deltanedas** [comment]
ok i am a bit silly i meant cluster not packed

**Comment by Myakot** [comment]
> 

Why must you be so cruel, suggesting inf generators should make a return so soon.

**Comment by deltanedas** [comment]
because having comms die roundstart is bad and unintended
