### ISSUE TITLE
some core apcs missing cables

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#18563]
## Description
a few apcs on core are missing lv and mv

outside sci (i have fixed in this)
![04:45:35](https://github.com/space-wizards/space-station-14/assets/39013340/b5cb995a-41b2-417e-bac6-0d093bd39aec)

east maint above an escape pod (i have not fixed in this)
actually this apc wouldnt do anything and has no mv line so just remove it
![04:50:13](https://github.com/space-wizards/space-station-14/assets/39013340/cba94411-aecc-4137-9842-e46b7075f8eb)

**Comment by lzk228** [comment]
mapp it, noob

**Comment by deltanedas** [comment]
i dont maintain core :trollface:

**Comment by deltanedas** [comment]
turns out i maintain core :)))

**Comment by UbaserB** [comment]
huh, i thought i fixed that one. Sorry i didnt see this earlier, i would fix it myself but it seems you’re already doing it lol. Im still maintaining it you know

**Comment by deltanedas** [comment]
yes i joke
