### ISSUE TITLE
Animals absorb the 5g signals from door remotes

### ISSUE THREAD

**Issue by VasilisThePikachu** [space-wizards/space-station-14#18583]
## Description

Pls fix im topo lazy to drag ian to the side to bolt the maints door

**Reproduction**

1. Get an ian
2. Get a door and a door remote
3. Get the ian infront of door
4. Stand behind an ian
5. Try to bolt the door
6. The 5g signals get aborbed by an ian

**Screenshots**

**Additional context**

ian

**Comment by Vordenburg** [comment]
Should mobs be blocking these at all?

**Comment by dmnct** [comment]
The problem is that door remotes essentially use the laser shot's line-of-sight check. CLEARLY they use infrared signals

**Comment by Vordenburg** [comment]
@Emisse Do you have a solution in mind for how the door remotes should work? I.e. pass through all mobs and just work if you can see the door, or something else?

**Comment by EmoGarbage404** [comment]
Probably should just be visibility without checking for blocking mobs

**Comment by dmnct** [comment]
> Probably should just be visibility without checking for blocking mobs

Without the Opaque check, it will work from inside lockers as long as a LoS can be drawn from the locker to the door, though I suppose with the door remote that's not so much of an issue? I sort of remember where that code is, should I make that PR?

**Comment by dmnct** [comment]
Ah. A problem. If that check is taken away, then it will indeed work through mobs, BUT it will no longer work through glass. This is the best that can currently be done, without a new collisiongroup

**Comment by Plykiya** [comment]
I've created a PR that fixes this.

**Comment by VasilisThePikachu** [comment]
#25093
