### ISSUE TITLE
faster than faster than light travel

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#18585]
## Description
some fucked up thruster configuration made shittle have top speed of 100m/s when going in sus direction then braking
it can then be controlled with wasd while holding space, even if missing thrusters
giga sus

**Reproduction**
?

**Screenshots**
left and bottom thrusters always on, right flickers every frame
![214914](https://github.com/space-wizards/space-station-14/assets/39013340/27c6cd1a-9eb5-457c-be6f-3356c5dca25f)

unknown
![214952](https://github.com/space-wizards/space-station-14/assets/39013340/8cf18757-d039-4b30-a91e-d8a811c28265)

**Additional context**
happened on apocalypse

**Comment by EmoGarbage404** [comment]
Can this be reworded in a more comprehensible manner with reproduction steps included?

**Comment by deltanedas** [comment]
no and no

i have no idea what made the thrusters sus

anyway this is a braking bug braking should never made it exceed 20m/s

**Comment by moonheart08** [comment]
ok bye
