### ISSUE TITLE
Guidebook entries needed for various antagonists

### ISSUE THREAD

**Issue by EmoGarbage404** [space-wizards/space-station-14#18592]
## Description

We got nukies, now do the rest of them:

need guides for:
- [ ] traitors and their steal objectives
- [ ] zombies (subguide for initial infected)
- [ ] rat king
- [ ] space dragon
- [ ] revenant

also blob and revolutionaries when we get those

**Comment by Aisu9** [comment]
let's not forget cult of the flesh that looks pretty close to completion, and ninja that has been tucked in a crate somewhere.
(also a small disclaimer for traitors that their objectives albeit being objective they are also guidelines and they can commit any antagonist activity)

**Comment by deltanedas** [comment]
ninja has a eh guide already

**Comment by GoodWheatley** [comment]
Closed by #18632
