### ISSUE TITLE
INSANE lag with new update.

### ISSUE THREAD

**Issue by Warentan** [space-wizards/space-station-14#18596]
## Description
A day ago, I was able to play SS14 with zero issues at all. Now, with the new updates, I am running at literally 5 frames per second.

**Reproduction**
Play the newest update

**Screenshots**
[Screencast from 08-02-2023 09:56:19 PM.webm](https://github.com/space-wizards/space-station-14/assets/113652968/d0e78ad2-3676-47cb-90a0-67a9547d8649)

**Additional context**
Started as RD. Also started on previous shift as Passenger post-round.

**Comment by metalgearsloth** [comment]
send logs on discord

**Comment by StogWasNotAvailiable** [comment]
> send logs on discord

How do I access logs

**Comment by metalgearsloth** [comment]
%AppData%/Space Station 14/launcher/logs

**Comment by StogWasNotAvailiable** [comment]
> %AppData%/Space Station 14/launcher/logs

Linux. I'll figure it out. Gimmie a sec.

**Comment by StogWasNotAvailiable** [comment]
No logs.

**Comment by metalgearsloth** [comment]
Need more specifics on when on when this happened to know which publish it is (1, 2, or 6 hours ago)

**Comment by metalgearsloth** [comment]
Also do you have a dev environment setup coz git bisecting around the shader changes is easiest way to confirm if it's related or not.

**Comment by deltanedas** [comment]
cant repro on master debug build, void, gt 740, quad core i5

**Comment by StogWasNotAvailiable** [comment]
I've also heard of other people experiencing this. No I don't have a dev environment set up, and I have no Idea what git bisecting is. Lemme figure out how to run previous update so I can find exact build that causes lag.

**Comment by StogWasNotAvailiable** [comment]
Oh, I'm an idiot. I didn't have client logging on. Let me get back to you on discord with those logs.

**Comment by StogWasNotAvailiable** [comment]
Where should I send logs? Help or some dev ticket I have to open?

**Comment by Warentan** [comment]
Not sure if this is relevant: I got a private non-watchdog server running and it would seem that the terminal is sending off rapid debug commands claiming "Stuck NPCs."

**Comment by MilenVolf** [comment]
> Not sure if this is relevant: I got a private non-watchdog server running and it would seem that the terminal is sending off rapid debug commands claiming "Stuck NPCs."

Yea, that happens after pathfinder fix

**Comment by metalgearsloth** [comment]
> Not sure if this is relevant: I got a private non-watchdog server running and it would seem that the terminal is sending off rapid debug commands claiming "Stuck NPCs."

That's server-side whereas your video is showing client-side issues (also this isn't an issue).

**Comment by Warentan** [comment]
How do I access previous server versions? Can't pinpoint version unless I have previous versions

**Comment by Warentan** [comment]
Disregard this post. My driver randomly got corrupted for no reason, and caused everything to be slow...
