### ISSUE TITLE
Admin test areas run out of power

### ISSUE THREAD

**Issue by Chief-Engineer** [space-wizards/space-station-14#18624]
## Description

Generators need fuel now, admin test area shouldn't need to be refueled

**Comment by deltanedas** [comment]
send shitters to the testing area to keep it fueled

**Comment by Eden077** [comment]
> send shitters to the testing area to keep it fueled

"Send him to the admin fuel mines! Forced to mine uranium for the rest of the round!"

**Comment by deltanedas** [comment]
maybe i will add pickaxe and uranium ore to a room :trollface:

**Comment by Verslebas** [comment]
Maybe just replace the generator with rtg

**Comment by EmoGarbage404** [comment]
there's a 15kw variant of the basic generator. That's has the same output as the uranium gens did before, so it should be the perfect replacement.

**Comment by deltanedas** [comment]
nooo but forced labour

**Comment by Errant-4** [comment]
> nooo but forced labour

Force them to mine for _nothing_. Mine, Refine, toss it into Reclaimer. Repeat.
