### ISSUE TITLE
cargo backpack inhand-right sprite issue

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#18627]
left and right facing sprites should be swapped

**Comment by lzk228** [comment]
really? no one?

**Comment by DogZeroX** [comment]
Do it yourself if you are so worried then.

**Comment by RawToast225** [comment]
Hey, not part of the dev team, mod team, whatever.

Have some perspective. Look at how many pull requests are open right now, look at how many issues are open. Two sprites needing to be swapped is _not_ at the top of the priority list. If it bothers you that much, you can either wait or do it yourself.

**Comment by lzk228** [comment]
i personally play on server with resprites, but it strange so really no one didn't fix it

**Comment by Alekshhh** [comment]
I'll deal w it
