### ISSUE TITLE
sechud is night vision

### ISSUE THREAD

**Issue by JoeHammad1844** [space-wizards/space-station-14#18639]
## Description

job icons are visible in the dark
**Reproduction**

wear sechud and have nothing in your active hand to see job icons
**Screenshots**

![20230804152154_1](https://github.com/space-wizards/space-station-14/assets/130668733/93913fbf-b3e6-4d4f-85a6-bc7f3fc8a6f2)
![20230804152155_1](https://github.com/space-wizards/space-station-14/assets/130668733/70f65433-cd52-4969-8d9a-0ae2601e808f)

**Additional context**

additionally, secglasses arent hud, which seems strange to me as they did in ss13

**Comment by metalgearsloth** [comment]
Talked about it with emo but i'm like 80% it's another overlay not clearing its shader so

**Comment by ElectroJr** [comment]
IMO it makes sense for sechud icons to be visible in the dark. My interpretation was always that its an actual display built into a pair of smart glasses that scan for ID cards. The glasses don't require light to read ID cards, and the smartglasses can show you the information even in the dark.

However status icons should only be unshaded if it makes sense (i.e., HUD glasses), so the shading should probably be configurable per icon type. That way rev/cult icons can be obscured when someone is lurking in a dark room.

**Comment by JoeHammad1844** [comment]
its an unfair advantage to be able to see icons in pitch black

**Comment by Kayek14** [comment]
![image](https://github.com/space-wizards/space-station-14/assets/106507028/9743c19e-4b8f-4994-b9d8-98394949db8c)
do we want this to be a common occurence?

**Comment by LankLTE** [comment]
> ![image](https://user-images.githubusercontent.com/106507028/277552685-9743c19e-4b8f-4994-b9d8-98394949db8c.png)
> do we want this to be a common occurence?

Given headrevs have flashes and wearing a sechud doesn’t give you flash immunity, I think this is honestly fine. Gives sechud more of a purpose over the sunglasses (as a tradeoff) and gives an actual reason to wear a sechud during rev rounds

**Comment by JoeHammad1844** [comment]
> Given headrevs have flashes and wearing a sechud doesn’t give you flash immunity, I think this is honestly fine. Gives sechud more of a purpose over the sunglasses (as a tradeoff) and gives an actual reason to wear a sechud during rev rounds

#21218

**Comment by deltanedas** [comment]
icons should still be shaded like outlines are
