### ISSUE TITLE
Mismatch in throwing direction and the final direction of the thrown item

### ISSUE THREAD

**Issue by astriloqua** [space-wizards/space-station-14#18646]
## Description

Final direction of thrown items seems to be independent from the direction they were thrown at.

**Reproduction**

Walk along a straight line and throw items to left and right. Then repeat the same procedure but this time walk in the opposite way and throw items to left and right. Items thrown will face around the same direction.
**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/129308840/fe1a3974-1929-496c-84c0-344b5414826a)
Two blue gloves at the upper side were thrown while walking down, while the two down were thrown walking upwards.

**Comment by metalgearsloth** [comment]
https://github.com/space-wizards/space-station-14/pull/18578 should fix it

**Comment by slarticodefast** [comment]
Tested it, this is fixed now.
