### ISSUE TITLE
minimoog single stray pixel

### ISSUE THREAD

**Issue by TurboTrackerss14** [space-wizards/space-station-14#18657]
## Description

Minimoog has a single out of normal pixel that shows when hovering. 0/10 shit game uninstalling as we speak

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/130304754/9eeaa8a8-0f0c-4a0e-aee7-c26a29bca438)

**Comment by TurboTrackerss14** [comment]
cancel that there is alot of them, on various angles. video posted showing this. 

https://github.com/space-wizards/space-station-14/assets/130304754/a68d9e6e-8027-4fb9-949b-da6f4a367e7a

**Comment by potato1234x** [comment]
me when interactionoutline issue
