### ISSUE TITLE
energy swords can reflect in pockets

### ISSUE THREAD

**Issue by JoeHammad1844** [space-wizards/space-station-14#18666]
## Description

I was fighting nukies and the commander died, he had an esword in his pocket and when I shot him to finish him off a couple bullets got reflected and nearly killed me
**Reproduction**

place an energy sword in your pocket
**Screenshots**

https://youtu.be/yCKQ3xRj46U
**Additional context**

obviously this is suboptimal for gameplay purposes

**Comment by asperger-sind** [comment]
Why can you even put a lit e-sword into a pocket, if this implies that the e-sword isn't lit then this bug also implies that unlit e-swords can reflect stuff.

**Comment by JoeHammad1844** [comment]
it's not lit

**Comment by deltanedas** [comment]
reproduced:
- unlit esword never reflects
- unlit desword can reflect in hand and in pocket

**Comment by metalgearsloth** [comment]
The code should be checking for pocket slots as this won't work where someone has more than 2 pockets (even better using a mask instead of manual string checks).

**Comment by JoeHammad1844** [comment]
it happened to me again
