### ISSUE TITLE
Evac shuttle doesnt exist

### ISSUE THREAD

**Issue by JoeHammad1844** [space-wizards/space-station-14#18703]
## Description

the announcement said it warped north east of the station, so I went to cargo, hopped on the console and saw the evac shuttle doesnt exist
**Reproduction**

happens sometimes when the round isnt ended by nukies dying or exploding the station
**Screenshots**

![20230805203259_1](https://github.com/space-wizards/space-station-14/assets/130668733/b7b73e8d-7850-4a9d-9d2e-b914d1ed7be6)

**Additional context**

this was on marathon station, and in general the evac shuttle hasnt been docking right recently

**Comment by Emisse** [comment]
I saw this round, it warped above security

**Comment by Emisse** [comment]
an antag blocked evac

**Comment by JoeHammad1844** [comment]
doesnt explain why its not on the scanner
