### ISSUE TITLE
Prototype spawn loadouts are broken

### ISSUE THREAD

**Issue by Chief-Engineer** [space-wizards/space-station-14#18713]
## Description

Prototypes like CBURN and ERT which normally spawn with a loadout aren't spawning with any equipment

**Comment by JoeHammad1844** [comment]
im a little confused on what you mean by this, do you mean when spawned they're just naked?

**Comment by Vordenburg** [comment]
They are spawning naked if they're a RandomHumanoidSpawner using Loadout as an additional component.

**Comment by JoeHammad1844** [comment]
damn
