### ISSUE TITLE
grilles collide with people even with window

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#18737]
## Description
happening on leviathan rn

**Reproduction**
1. find shocked window
2. touch it
3. still shocked even tho there is a window

**Comment by metalgearsloth** [comment]
Is there a mapped one that's easy to test on

**Comment by metalgearsloth** [comment]
Alright nvm found one, should be fixed in a bit.

**Comment by deltanedas** [comment]
happened on core and meta dont think its map specific

**Comment by Partmedia** [comment]
Bisect and discussion with the author show that the commit that introduced this regression is d3aece12cb38d887edd2850708d9cf3167ee1643.

**Comment by metalgearsloth** [comment]
Was already fixed https://github.com/space-wizards/RobustToolbox/pull/4240
