### ISSUE TITLE
Click attacks should have the damage mod

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#18759]
I like lank's idea more but I didn't know it 6 weeks ago.

Move the damage mod to click attacks (making sure mobs can't break walls still) and remove stam cost from wide.

**Comment by LankLTE** [comment]
I’m flattered. 
Could making base wall damage resist 7.5 instead of 5 (in essence just multiply their flat damage reduction by the multiplier) work to solve that issue? Might break 1-2 weapons hitting walls with wideswings but I doubt that’s a huge issue.

**Comment by metalgearsloth** [comment]
yeah sure we can try it

**Comment by JoeHammad1844** [comment]
good idea, should reward precision without making wide swings useless
