### ISSUE TITLE
Bullets and bypassing crit people

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#18763]
Okay so the current issue is bullets hit crit people.

Solution:
- Bullets never collide with crit people.
- Anywhere near where you click to shoot (say 1-2m radius) the bullet can collide with crit people as per current, but outside of that don't.

Code-wise:
- Bullets have EntityCoordinates designating some kind of "deadzone".
- When they get in range their fixture adds on the relevant collision layer.
- When they get past it it gets removed.
- Hitscan stuff just needs to do something similar except in the collisionray you just each entity's position to see if it's nearby (maybe use CollisionManager for it?)

**Comment by Equivocateur** [comment]
Why not just register bullet hit on crit person if you are aiming at said crit person (and maybe also standinh near their body)?

**Comment by metalgearsloth** [comment]
> Why not just register bullet hit on crit person if you are aiming at said crit person (and maybe also standinh near their body)?

Recoil probably makes it a pain in the ass.

**Comment by Equivocateur** [comment]
> > Why not just register bullet hit on crit person if you are aiming at said crit person (and maybe also standinh near their body)?
> 
> Recoil probably makes it a pain in the ass.

Intentionally shooting a crit person is usually done point blank because of that? As in an execution or "I WANT IT DEAD NOW"

**Comment by metalgearsloth** [comment]
We can just try that then

**Comment by deltanedas** [comment]
also change crate layer to not collide with bullets it doesnt make any sense that if im aiming at your head an, at best, 1 meter tall crate can stop it

**Comment by Vaaankas** [comment]
i feel like #14373 can be part of this too

**Comment by Equivocateur** [comment]
> also change crate layer to not collide with bullets it doesnt make any sense that if im aiming at your head an, at best, 1 meter tall crate can stop it with similar aiming thing so you can pka gun crates as usual when wanted

I'd say just to judge which entities get shot or not by their mass - so something like a crate gets shot through when not aimed at while a generator tanks shots because its large

**Comment by dmnct** [comment]
> also change crate layer to not collide with bullets it doesnt make any sense that if im aiming at your head an, at best, 1 meter tall crate can stop it with similar aiming thing so you can pka gun crates as usual when wanted

Or, your shots should pass over a crate that is next to you, but collide with ones further out. Actual cover

**Comment by deltanedas** [comment]
that would function similarly to having to aim precisely, if you aim near the crate it hits that so you need to be smart about it
