### ISSUE TITLE
Ghost refactor

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#1878]
Related to #1701
We should refactor how ghosts currently work.
Ideally, ghost entities should get deleted once their mind is transferred/the player disconnects.
If the player disconnected as a ghost, this position should be stored somewhere (like in the player session, or a ghost system of sorts) so it can be applied again when they reconnect and their ghost entity gets created.

**Comment by Nukeuler123** [comment]
May try working on this, anything specific for how the position for DCed ghosts would be stored? Was just thinking of using a dictionary.

**Comment by RemieRichards** [comment]
> Ideally, ghost entities should get deleted once their mind is transferred/the player disconnects.
If the player disconnected as a ghost, this position should be stored somewhere (like in the player session, or a ghost system of sorts) so it can be applied again when they reconnect and their ghost entity gets created.

Why? what's wrong with just reconnecting a session to their existing ghost, like happens in 13?

**Comment by Zumorica** [comment]
Entity bloat, specially for hundreds of players. Alternatively, if we don't want to delete ghosts when players disconnect we should do the following:
1. Hide ghosts without a connected player.
2. Delete ghosts not being controlled by players (but whose players are still connected)
3. Fix the ghost stack bug at 0, 0 when rounds restart (fixed by 2, really)

**Comment by RemieRichards** [comment]
'Entity Bloat'

What cost does an entity not doing anything have? if it's anything significant then there's your real problem, not ghosts.

**Comment by Zumorica** [comment]
It doesn't have a significant cost, except just being there doing nothing when they're not really needed.
I honestly don't care how this is done as long as the three things I pointed out are solved. Deleting the ghosts entities of disconnected players is a way to solve it, but obviously not the only one.

**Comment by RemieRichards** [comment]
> Hide ghosts without a connected player.

Why is this an issue? Can't tell they're not logged in? add a description when logged out (like 13).
"They're not really needed" they store the location the player was at, probably their mind objects, maybe some other meta garbage. Storing that outside of the ghost and putting it back into the ghost on reconnect is work.

> Delete ghosts not being controlled by players (but whose players are still connected)

This is just a bug. If you're in another entity your ghost isn't needed.

> Fix the ghost stack bug at 0, 0 when rounds restart (fixed by 2, really)

So fix it, by 2 as you say.

> (edit: and 4, delete ghosts of players who have left in a past round and are not connected to the current one)

Again, sounds like a bug in its own right.

**Comment by Zumorica** [comment]
> This is just a bug.

....Well, this is exactly what this issue is for.

**Comment by RemieRichards** [comment]
Yes, it has nothing to do with 'Entity Bloat'

**Comment by Nukeuler123** [comment]
> Entity bloat, specially for hundreds of players. Alternatively, if we don't want to delete ghosts when players disconnect we should do the following:
> 
>     1. Hide ghosts without a connected player.
> 
>     2. Delete ghosts not being controlled by players (but whose players are still connected)
> 
>     3. Fix the ghost stack bug at 0, 0 when rounds restart (fixed by 2, really)
>        (edit: and 4, delete ghosts of players who have left in a past round and are not connected to the current one)
Would it be fine to just move disconnected ghosts to arrivals? As for 3 wouldnt it also be solved by just deleting the ghosts entities and kicking ghosts back to the round start screen when round ends?

**Comment by metalgearsloth** [comment]
Ideally also when the player entity is deleted for whatever reason a ghost spawns.

This came up with the crematorium for example where it deletes its contents when you put a person inside.

**Comment by Zumorica** [comment]
I think this can be closed already. No need for a refactor imo? d43ca2877a496507ede5b6c786a3aae167465f5d
