### ISSUE TITLE
setmind doesn't work on ghosts?

### ISSUE THREAD

**Issue by Chief-Engineer** [space-wizards/space-station-14#18796]
## Description

Haven't thoroughly tested but I don't think `setmind` is working on ghosts anymore. Expected behavior is for it to force the player to control the entity, I think what it does is reassign their body so they have to return to it manually.

**Comment by ElectroJr** [comment]
AFAICT the mind transfer still succeeds. i.e., if they use the return-to-body button they go the the new entity. I guess there should just be an option to also cancel any current "visits" when transferring.

**Comment by ElectroJr** [comment]
Ah nvm, thats already an option, the command just doesn't use it
