### ISSUE TITLE
speech bubble sprites are 64x64

### ISSUE THREAD

**Issue by EmoGarbage404** [space-wizards/space-station-14#18795]
## Description

this fucks up the sprite bounds and displays.

there's literally no reason for this it's a 32x32 sprite that just has a ton of white space around it.

**Comment by ThunderBear2006** [comment]
This speech bubble type or the one with actual text in it?
![alien1](https://github.com/space-wizards/space-station-14/assets/100388962/93619902-effa-4b58-9b7f-737f282929db)

**Comment by EmoGarbage404** [comment]
i saw the default ones. others might have it too.

**Comment by ThunderBear2006** [comment]
> i saw the default ones. others might have it too.

Okay, wouldn't changing the sizes mess with the ingame display size/offset?

**Comment by EmoGarbage404** [comment]
> > i saw the default ones. others might have it too.
> 
> Okay, wouldn't changing the sizes mess with the ingame display size/offset?

if it does then dear god save our souls from speech bubble shitcode

**Comment by ThunderBear2006** [comment]
I'm currently changing the alien speech bubble sprites and Ill check if it does, if it does then I ain't touching it lmao

**Comment by ThunderBear2006** [comment]
Yeah it does so good luck to whoever tackles this, might wanna change that difficulty label

**Comment by EmoGarbage404** [comment]
i did this, didn't i?
