### ISSUE TITLE
Walking while going to the lobby scrolls the screen in the background infinitely

### ISSUE THREAD

**Issue by Visne** [space-wizards/space-station-14#1882]

**Comment by Visne** [comment]
As far as I understand it this should be automatically fixed when:

1. Client is aware of Paused state (space-wizards/RobustToolbox#1553)
2. GameTicker.RestartRound() pauses the game
3. Physics actually takes pausing into consideration

Discussion: https://discord.com/channels/310555209753690112/560845886263918612/810356066634039316

**Comment by SweptWasTaken** [comment]
Done.
