### ISSUE TITLE
brute and burn auto injectors use the wrong sprites

### ISSUE THREAD

**Issue by JoeHammad1844** [space-wizards/space-station-14#18821]
## Description

I did an oopsie trying to fix the inject amount

**Screenshots**

current sprites (top, brute. bottom, burn.)
![salpen](https://github.com/space-wizards/space-station-14/assets/130668733/a83ce5f9-c1f8-40cf-bf21-6cb39866477d)
![oxapen](https://github.com/space-wizards/space-station-14/assets/130668733/eb0048be-3d2f-45ea-b9b2-50507bba9c30)
intended sprites (top, brute. bottom, burn.)
![bicpen](https://github.com/space-wizards/space-station-14/assets/130668733/bab62d5d-5d48-415f-ad07-3007ac5250e1)
![dermpen](https://github.com/space-wizards/space-station-14/assets/130668733/9f8135c1-453d-4d50-9d46-05c740ecb4e6)

**Comment by Partmedia** [comment]
Fixed in https://github.com/space-wizards/space-station-14/pull/18866, thanks!

**Comment by JoeHammad1844** [comment]
yes, i did that
