### ISSUE TITLE
Recharging laser guns don't update ammo UI

### ISSUE THREAD

**Issue by HerCoyote23** [space-wizards/space-station-14#18830]
## Description

Advanced/Antique laser guns' ammo counters don't update when they recharge, just when you fire them or swap to their hand.
**Reproduction**

Use all the charge in an advanced laser gun, keep the hand selected. Laser icon updates, but ammo counter doesnt.

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/131214189/21944bf0-db24-46aa-8072-4c71aec59d62)

**Additional context**

**Comment by metalgearsloth** [comment]
Dupe https://github.com/space-wizards/space-station-14/issues/14127
