### ISSUE TITLE
Space mobs moving too far away from salvage wreck

### ISSUE THREAD

**Issue by ThunderBear2006** [space-wizards/space-station-14#18836]
## Description

Mobs such as ticks, bears, carps and most other mobs spawned on salvage wrecks with AI tend to wander off the actual wreck, causing them to get stuck making them vulnerable and pointless to ghost role as.

I think a simple solution would be to check if the desired position actually has a tile or not when just wandering, but I haven't really touched pathfinding code so it may be more complex than that

**Reproduction**

Spawn any of the mentioned mobs (with AI) on an open platform, wait for them to path off of the platform, profit

**Comment by metalgearsloth** [comment]
I know https://github.com/space-wizards/space-station-14/issues/16834
