### ISSUE TITLE
Wheelchairs need fixing

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#18848]
- Sprite netsync needs removing we just purged them all.
- Don't Ensure on comp init.
- Don't RemComp in a component's startup eventbus.
- WheelChairBound should be MapInit not startup.

Also the localisation needs fixing.

**Comment by Emisse** [comment]
to add to this, layering on east and west directions needs implementation

**Comment by Fey-the-Bin** [comment]
Every time I go FTL with a wheelchair, it would turn the camera oblique. 
This can resolve itself by unbuckling and rebuckling.

![Oblique Wheelchair Camera](https://github.com/space-wizards/space-station-14/assets/117279562/1b17128a-84a5-41da-a3a3-d87b95afc24d)

**Comment by Emisse** [comment]
wheelchair really exposing the silly vehicle buckling parenting pulling code

**Comment by Fey-the-Bin** [comment]
There's also this weird issue of whenever I was trying to link the two machines (cloning console - Genetic scanner) while on top of a puddle of reagents, I won't be able to move my own wheelchair, nor unbuckle myself from it.

Someone has to drag to move me, and unbuckle me from the wheelchair to fix the issue.

![Chair Stuck](https://github.com/space-wizards/space-station-14/assets/117279562/ac0b9fee-1066-41ba-a057-6c1bd3df4cab)

**Comment by deltanedas** [comment]
the tilt thing happens on any vehicle
