### ISSUE TITLE
Add Emergency Nitrogen Tanks to Support Slime Species

### ISSUE THREAD

**Issue by MiraslauKavaliou** [space-wizards/space-station-14#18843]
## Description
The slime species within Space Station 14 rely on nitrogen to breathe. In the event of an emergency, the current system may leave them at a disadvantage when searching for nitrogen sources. To remedy this, I propose the addition of emergency Nitrogen Tanks and double emergency Nitrogen Tanks to all locations where these tanks typically spawn. An additional aspect of this would be to spawn Slimes with emergency Nitrogen tanks in their Survival Box rather than Oxygen.

**Proposal**
1. **Identify Locations**: Identify all areas where emergency tanks spawn within the game.
2. **Design Tanks**: Create both regular and double emergency Nitrogen Tanks. Ensure they comply with the game's visual design.
3. **Implement Spawning**: Add the tanks to the identified locations, ensuring that the spawn rate is balanced and doesn't impact overall gameplay.
4. **Testing**: Conduct thorough testing to ensure that the tanks are functioning as intended and that the addition doesn't create any unforeseen issues.

**Impact**
This change ensures that the slime species players are not disadvantaged during emergencies. It adds a level of fairness and provides additional resources that could enhance the overall gaming experience.

**Notes**
This issue is intended for implementation by the creator (myself). Any feedback or additional insights are welcome.

**Labels**
- `Issue: Feature Request`
- `Difficulty: 2-Medium`
- `Priority: 3-Not Required`

Please provide your thoughts or any additional requirements that may be necessary for this implementation.

**Comment by MiraslauKavaliou** [comment]
If the Space Station 14 team is in agreement with this proposed addition, I'm ready and willing to begin working on it myself. I look forward to your feedback and guidance.

**Comment by asperger-sind** [comment]
Why does this look like it's AI-written, either way emergency nitrogen tanks have been suggested for a while now and are just a wyci (when you code it) because nobody wants to code them, so as per your last comment I suggest you start work on it now.

**Comment by MiraslauKavaliou** [comment]
Thank you, I will get started on them then. And I wrote it myself from what I thought an Issue is supposed to look like, I have not contributed to any open-source projects before.

**Comment by Emisse** [comment]
if you do this make sure to remove nitrogen from all lockers and suit storages to take down clutter, if people want big tanks they can get one from a tank dispenser

**Comment by MiraslauKavaliou** [comment]
What do you mean? Where there is a large Oxygen tank there should also be a large Nitrogen tank (as there are now already) I am mostly looking to make it the same for Emergency tanks so they always spawn with the Nitrogen Counterpart

**Comment by Emisse** [comment]
no there shouldnt also be a large nitrogen tank wherever oxy tanks are

**Comment by Emisse** [comment]
its bloat and removes any facet of interesting gameplay from nitrogen breathers

**Comment by MiraslauKavaliou** [comment]
But there already are...?

**Comment by MiraslauKavaliou** [comment]
After a conversation in the discord, the consensus and plan is to:

- Make nitrogen-dependant species spawn with a nitrogen emergency tank instead of an oxygen one in their survival box
- Remove large nitrogen tanks from lockers? (I am on the edge about this, especially for reasons such as eva missions and salvage, where a large tank is basically required)

Thoughts?

**Comment by LankLTE** [comment]
> Thoughts?

Atmos has large nitrogen tanks available in their gas tank dispenser, so that's always an option for eva / salvage.

> Make nitrogen-dependant species spawn with a nitrogen emergency tank

This is a lot harder than it sounds. When / if someone codes it, I'm sure it'll be merged, it's just a matter of actually getting it done. That said emergency tanks really don't last that long, so if it's going to be their only (easily obtainable) source of nitrogen it should probably last longer so slimes don't end up even worse off.

**Comment by MiraslauKavaliou** [comment]
@LankLTE This is exactly what I thought! I thought it wouldn't be enough either, but @Emisse disagreed with me. I am new to contributing so I don't really know who to listen to when it comes to advice for this. I am more for putting emergency nitrogen tanks where emergency oxygen tanks are located. So it is the same way as with the big tanks.

**Comment by potato1234x** [comment]
bro fr wrote an essay 💀

**Comment by lzk228** [comment]
> no there shouldnt also be a large nitrogen tank wherever oxy tanks are

racism:trollface:

**Comment by potato1234x** [comment]
Why cant we just use air tanks

**Comment by dmnct** [comment]
> Why cant we just use air tanks

Because then you need to breathe higher pressure air to make up for some of the gas being useless to you. With a 50-50 mix a tans would be breathable to anyone but last half as long


The big issue no one coded yet is that we have no way to give different starting gear to a specific species, only jobs. And "just code it like how jobs work" is not feasible because then the two systems would conflict. We need a proper loadout system

**Comment by lzk228** [comment]
> Why cant we just use air tanks

spessmen need around 20 kPa to breathe, if you has clear oxy, you would set 20 kPa and breathe 30 mins i.e. but if there 50% oxy 50% n2, you should set 40kPa and breathe 15 mins

**Comment by lzk228** [comment]
> > Why cant we just use air tanks
> 
> Because then you need to breathe higher pressure air to make up for some of the gas being useless to you. With a 50-50 mix a tans would be breathable to anyone but last half as long
> 
> The big issue no one coded yet is that we have no way to give different starting gear to a specific species, only jobs. And "just code it like how jobs work" is not feasible because then the two systems would conflict. We need a proper loadout system

shit

**Comment by MiraslauKavaliou** [comment]
> The big issue no one coded yet is that we have no way to give different starting gear to a specific species, only jobs. And "just code it like how jobs work" is not feasible because then the two systems would conflict. We need a proper loadout system

Question becomes: should this issue turn into remaking the whole load out system for the game to consider more factors or just make emergency nitrogen tanks for now

**Comment by MiraslauKavaliou** [comment]
People still keep arguing about this, if I do reconsider this it will be in the far future.
