### ISSUE TITLE
armed nuke should get an emergency light

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#18861]
## Description
hiding nuke under items is an incredibly scummy tactic
giving it a small emergency light would mitigate it

**Comment by Emisse** [comment]
spinny yellow light probably

**Comment by JoeHammad1844** [comment]
how about pulsing red light?

**Comment by JoeHammad1844** [comment]
makes sense.
also, if there was any confusion, by pulsing I mean the light slowly grows and shrinks

**Comment by deltanedas** [comment]
yeah i know still sussy

**Comment by JoeHammad1844** [comment]
maybe even give it a small audio cue, like static or unique beeping

**Comment by deltanedas** [comment]
i am in pain

**Comment by dmnct** [comment]
A line of dominoes begin to topple. Light rotation code needs to be taken out of EmergencyLightSystem

**Comment by deltanedas** [comment]
yes thats exactly what im doing and im discovering how downright evil light code is
