### ISSUE TITLE
dna scrambler hugging validcheck

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#18873]
## Description
1. cuff commander who used scrambler
2. kill
3. defib and heal
4. hug to get out of bed
5. the girl not on manifest wearing operative suit is in fact commander psi wtf

**Comment by EmoGarbage404** [comment]
this issue is nigh-unintelligible: can you explain the specific issue being reported more clearly?

**Comment by Equivocateur** [comment]
> 2\. kill

DNA scrambler forcibly reverts you back to your original identity if you go into crit
![image](https://github.com/space-wizards/space-station-14/assets/109166122/8f9f7878-5c7c-4891-b7e5-7a3c8fd926dc)
