### ISSUE TITLE
Force container eject while on vehicle make content stuck

### ISSUE THREAD

**Issue by Morb0** [space-wizards/space-station-14#18885]
## Description

It title

**Reproduction**

1. Remove clothes while have PDA on it

**Screenshots**

https://github.com/space-wizards/space-station-14/assets/14136326/46a0f8e1-4b4a-4064-bb5e-48aed21a1bf4

**Additional context**

**Comment by Pangogie** [comment]
Vehicles removed awaiting better implementation.
