### ISSUE TITLE
Many doafters are broken when you're on a vehicle

### ISSUE THREAD

**Issue by Partmedia** [space-wizards/space-station-14#18902]
## Description
Moving away from light removal doesn't break the doafter when you're on a vehicle.

**Reproduction**

1. Be on vehicle
2. Start doafter to remove light
3. Move away -> light is removed even though you are away

**Screenshots**

https://github.com/space-wizards/space-station-14/assets/3229565/3f67248e-3870-4c8c-bb0b-003b869a3c1d

**Additional context**

**Comment by deltanedas** [comment]
a lot of doafters are broken on vehicles, like mopping when it used to be a doafter

**Comment by Partmedia** [comment]
Changing the issue title to reflect the sad state of reality.

**Comment by Pangogie** [comment]
Vehicles removed awaiting better implementation.
