### ISSUE TITLE
LightBehaviorSystem is named inconsistently

### ISSUE THREAD

**Issue by Errant-4** [space-wizards/space-station-14#18911]
## Description
Every single thing in the code related to lights is spelled as LightBehaviour, with a "u", except one System's name. This is from way back in 2020. Having a system named the "same" but spelled differently than a few adjacent light systems and all light behavio(u)r components is one of those things that probably should not be left unfixed

Possible fix 1: Remove all the u-s
I was told the US spelling is generally the preferred format, but in this case that would be a large change. Many files would need to be renamed, and if one was to go full ocd and want to rename even variables and comments, that would be a long list. Annoying for us and probably even more annoying for forks and especially hard forks. 

Possible fix 2: Add a single extra u
A significantly less disruptive option to resolve the difference would be to rename LightbehaviorSystem to spell it with a u too, as this one single change in one single file would make all light behaviour names consistent. Cementing the wrong spelling forever, but at least light stuff will be consistent with itself. Until someone adds something new to it and forgets the u

**Comment by deltanedas** [comment]
:gb::gb::gb::gb::gb::gb::gb::gb::gb::gb::gb::gb::gb::gb::gb::gb:

**Comment by Errant-4** [comment]
Nobody cares
