### ISSUE TITLE
Advanced laser gun should take up more bag space

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#18944]
## Description
The advanced laser gun takes up 10 units of bag space. It's damage and recharge speed is equivalent to the captains antique laser, but takes up as little space as a pistol and can fit in pockets. Granted that it is at the end of a tech tree, it should be powerful. However, it should take up more than 10 bag space to prevent people from carrying a whole armory's worth in their pockets and bag.

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/106507028/b1ee7251-f114-4a31-9051-a8ad4f617cf8)

**Comment by CrigCrag** [comment]
this is T2 tech iirc, not the end of the tech tree

**Comment by Errant-4** [comment]
Resolved, can be closed
