### ISSUE TITLE
Health and Stamina

### ISSUE THREAD

**Issue by ghost** [space-wizards/space-station-14#19]
[As Urist wrote](https://docs.google.com/document/d/1RRIkyoaaGXVVLMsl_e7FlhiHO4wDMqcxky5qsEcChKE/edit):

## Health
When a mob takes a certain amount of damage it goes into a criticial health state. At that point it loses all stamina without being able to restore it, falls down, starts taking small amounts of passive damage over time, every action, speech and movement inflict additional damage. At a certain damage threshold the mob falls unconscious, and at another dies completely.

## Stamina
Mobs have a _stamina_ value. Stamina passively acts as defense against disabling conditions (and something you need to inflict disabling conditions) and actively as a resource. Stamina regenerates over time, starting after a brief period of windup after each time you spend stamina. Stamina gets telegraphed somehow.

As a defense against disabling conditions, it makes it so whenever there’s a >0% chance that a disabling condition will be applied to you and you have 0 stamina, that chance becomes 100%. As something you need to inflict disabling conditions, when you wield a melee weapon that has a chance (including 100%) of inflicting a disabling condition and you have 0 stamina, that chance becomes 0%. So, if two people at zero stamina fight with melee weapons, they won’t disable each other.

### As a resource, stamina is expended on:
**Melee weapon attacks.** Even if you have 0 stamina, you can perform such attacks, but see above about the disabling conditions.
**Sprinting**. Mobs can increase the speed they move at by sprinting. Sprinting expends stamina. You can’t sprint if you have 0 stamina.
**Defense** against environmental hazards such as lack of oxygen and smoke. While in conditions where a mob can’t breathe, before actually taking damage or other negative effects from it, he’ll expend stamina first. Once stamina is at 0, that defense stops working.
**Adrenaline burst**. While at 90%+ stamina, a mob can perform an adrenaline burst. This reduces his stamina to 0 over a brief period of time but gives some benefits during that time - the mob sprints without cost, gets rid of all disabling conditions it currently has and becomes immune to them.

## Statuses
**_Statuses_** or **_conditions_** are temporary (or not) effects that affect a mob’s behavior inflicted on it with external forces. Those are disabling and restraining conditions, the former of which are affected by the stamina system, unlike the latter. Disabling conditions are almost universally temporary. Restraining conditions are often non-temporary, based on permanent damage or items used on the mob.

### Disabling conditions:
**Knockdown** - a knocked down mob can’t move normally, only crawl slowly.
**Stun** - a stunned mob can’t move or perform actions.
**Daze** - a dazed mob can’t move, perform actions, see any farther than a short range around him or speak. He drops the items he’s holding.
**Unconscious** - as daze, but can’t perceive anything at all and is knocked down.

### Restraining conditions:
**Blind** - the mob can’t see. Has different levels of severity, ranging from “no seeing at all” to “muddy vision”.
**Mute** - the mob can’t speak.
**Handcuffed** (or whatever to call it) - the mob can’t perform actions.
**Immobilized** - the mob can’t move.

**Comment by Injazz** [comment]
We implemented health, statuses are in the separate issue #42 
Do we need that Stamina thing?

**Comment by acvzy** [comment]
Moved [here](https://hackmd.io/96HHKT-VQ2KO91c9i75V8A?both#Health-amp-Stamina-Urist-2017-11-19)
