### ISSUE TITLE
Pickaxe is overtuned

### ISSUE THREAD

**Issue by liltenhead** [space-wizards/space-station-14#19006]
## Description
Easy to make, deals more damage than a large majority of the weapons in the game, fits in backpacks easily, does very high structure damage. I don't know which of these to nerf, if not a combination of all of the above.

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/104418166/1bfadf68-36a4-44df-9f43-9dd3f2439ccd)
![image](https://github.com/space-wizards/space-station-14/assets/104418166/55364c36-cbda-48a8-8dcd-8846e6c17dcb)

**Comment by CrigCrag** [comment]
increase crafting cost by 5x and give it the baseball bat treatment of being 80 size?

**Comment by liltenhead** [comment]
> increase crafting cost by 5x and give it the baseball bat treatment of being 80 size?

That'd probably work, yeah.
