### ISSUE TITLE
PVS can only be used for attached entity

### ISSUE THREAD

**Issue by Visne** [space-wizards/space-station-14#1900]
Currently, PVS only works for the attached entity. This means that camera systems are not possible. You can open a viewport to a specific location, but you will only see tiles and no entities.

PVS is completely client side right now. The server needs to be able to create EyeComponents and keep track of them, to send entities to the player that are not around the player.

**Comment by RemieRichards** [comment]
Add some kind of `ViewingEntities` list to `IPlayerSession` and make PVS happen on all of those, not just the attached one.

I think it's this method you'll need to update https://github.com/space-wizards/RobustToolbox/blob/d4fc0517c4d7bc4c86416da065a2bcb37591a8c9/Robust.Server/GameObjects/ServerEntityManager.cs#L337

**Comment by Visne** [comment]
```cs
    public class CameraTestWindow : SS14Window
    {
        public CameraTestWindow()
        {
            var clyde = IoCManager.Resolve<IClyde>();
            var playerMgr = IoCManager.Resolve<IPlayerManager>();
            var pos = playerMgr.LocalPlayer!.ControlledEntity!.Transform.MapID;
            var cameraPos = new MapCoordinates(Vector2.Zero, pos);
            var cameraEnt = IoCManager.Resolve<IEntityManager>().SpawnEntity(null, cameraPos);
            var eyeComp = cameraEnt.AddComponent<EyeComponent>();

            var vp = clyde.CreateViewport((400, 400), "CameraTest");
            vp.Eye = eyeComp.Eye;

            Contents.AddChild(new CameraControl(vp));
        }

        private sealed class CameraControl : Control
        {
            private readonly IClydeViewport _viewport;

            public CameraControl(IClydeViewport viewport)
            {
                _viewport = viewport;
            }

            protected override Vector2 CalculateMinimumSize()
            {
                return _viewport.Size / UIScale * 2;
            }

            protected override void Draw(DrawingHandleScreen handle)
            {
                _viewport.Render();
                handle.DrawTextureRect(_viewport.RenderTarget.Texture,
                    UIBox2.FromDimensions(Vector2.Zero, _viewport.Size * 2));
            }
        }
    }
```

PJB made this code which can be useful for testing.

**Comment by RemieRichards** [comment]
yeah that draws whatever is at those coordinates, but doesn't handle PVS.
I think it'll magically start working if you do (something like) what I said above/generally sort multi-PVS.

**Comment by Visne** [comment]
Yep, that's what PJB said too. Using that viewport you can test if your PVS implementation is working or not.

**Comment by Visne** [comment]
I just realized this should probably be an engine issue

**Comment by RemieRichards** [comment]
ye it 100% is.

**Comment by Visne** [comment]
Moved to space-wizards/RobustToolbox#1257
