### ISSUE TITLE
CORPSES can shoot if they have weapons in their hands

### ISSUE THREAD

**Issue by DjfjdfofdjfjD** [space-wizards/space-station-14#19018]
## Description

All corpses that have shooting weapons and the player who returned to the body can shoot!1!1!!
**Reproduction**

Step one: Kill someone
Step two: give him a gun / machine gun / blah blah blah
Step three: if the player returns to the body - he will be able to shoot

**Comment by Tynobeard** [comment]
This is feature

**Comment by Errant-4** [comment]
Good catch! Thank you
