### ISSUE TITLE
mute people can speak in their last whispers

### ISSUE THREAD

**Issue by spicyusername** [space-wizards/space-station-14#19019]
## Description
as the name suggests, the newly added last words feature allows mute people to say anything they want as their last words

**Reproduction**
go crit as a mute person
say your last words

**Screenshots**
i forgot to get a screenshot

**Additional context**

**Comment by Errant-4** [comment]
That's so poetic I almost wish it was kept

**Comment by Eden077** [comment]
I genuinely think it would be good because yeah it's poetic is hell, could dish out some good moments lol

**Comment by LankLTE** [comment]
my mute character may have canonically been unable to speak since birth, but in their last moments they suddenly gain the ability to talk and the knowledge how. it just makes sense.

**Comment by Errant-4** [comment]
> 
The game has space carp in it. Space. Carp. We are operating well beyond the realm of old world science

**Comment by mirrorcult** [comment]
honestly funny enough that i kind of want to keep it

**Comment by deltanedas** [comment]
good feature (mime is dead so cant be valid)
