### ISSUE TITLE
Some Emote sounds do not work

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#19027]
## Description
Some Emote sounds don't work eg cries, sigh Laughing and screaming via the hotkeys still work.

**Reproduction**
typing in sigh, claps cries etc

**Screenshots**
Its just the sounds so no screenshot.

**Additional context**
None

**Comment by lzk228** [comment]
it works with hotkey, but don't work with typing in chat?

**Comment by Titian3** [comment]
> it works with hotkey, but don't work with typing in chat?

Yep this is the case.

**Comment by Rapidgame7** [comment]
Adding to this, emotes that happen thanks to the chat filter (like capturing `lol` and instead making you laugh) work and play just fine.

**Comment by Titian3** [comment]
> Adding to this, emotes that happen thanks to the chat filter (like capturing `lol` and instead making you laugh) work and play just fine.

So i retested again in local and it is definitely still broken the `lol` one still works but i tested with the following:
[`claps`, `chitter`, `cries`, `sigh`, `laughs`].
I see they are all common to [speech_emotes.yml](https://github.com/space-wizards/space-station-14/blob/97d0fdca38251ea8383abcafef673e0297df5a6b/Resources/Prototypes/Voice/speech_emotes.yml#L4)
and this was recently updated for the deathgasp update #18993, which lines up with about when it started happening and getting reported.
@mirrorcult Do you have some idea what could be the issue here, it may have been side effect from the deathgasp addition?
I'm just reading through it now trying to find the issue.
