### ISSUE TITLE
Dev Environment Server DOES NOT make Client Bin data.

### ISSUE THREAD

**Issue by Warentan** [space-wizards/space-station-14#19033]
I have tried over and over to fix this, but it would seem that every time I fork, clone, build, and run my content.server folder, it NEVER creates a Client.Content bin folder. I am missing several dependencies because of this, and trying to play on the running server will just crash it.

**Reproduction**
Clone and Run Server Content. Attempt to play the server. (It is unknown if this is subjective to me.)

**Additional context**
I have the latest version of SS14 in my dev environment folder.

Last Fatal Message that gets thrown when trying to join the server before it crashes
unhandled: System.IO.DirectoryNotFoundException: Could not find a part of the path '/home/[username]/SS14DEV/space-station-14/bin/>>>>>Content.Client<<<<<<(**DOES NOT EXIST**)/Content.Shared.Database.dll'.

**IF** content.client doesn't contain any sensitive info, can someone loan me their content.client folder until I can fix my clone?

**Comment by ElectroJr** [comment]
The server shouldn't depend on content.client, so something else is going wrong there. If this is only happening when you connect, are you trying to join a dev server via the launcher? I'm not even sure that works but you'd still have to build the client at some point.

**Comment by Warentan** [comment]
> The server shouldn't depend on content.client, so something else is going wrong there. If this is only happening when you connect, are you trying to join a dev server via the launcher? I'm not even sure that works but you'd still have to build the client at some point.

Oh my god, I'm an idiot. I completely forgot that bin depends on BOTH content bundles to be built, not one. I just kept trying to run SERVER without building client. Thanks for the help!

**Comment by Warentan** [comment]
Also, the server does depend on the client being built, since it pulls some shared content .dll files and I assume some reference files.
