### ISSUE TITLE
Placing a light fixture instantly drains all power from the area

### ISSUE THREAD

**Issue by ancientpower** [space-wizards/space-station-14#1906]
Tried to place some fixtures (both "light" and "unpowered light") to light up engineering on Saltern and all the APCs immediately dropped to 0%.

~I also couldn't move after this happened but that only happened once out of the two times I replicated the issue.~ gravity generator turned off lol

**Comment by collinlunn** [comment]
Can't reproduce by spawning in lights. 

Unpowered lights have no power interaction iirc.

**Comment by ancientpower** [comment]
The issue turns out to be that if you delete the generator the APCs get drained nearly instantly, this is actually an issue with the depreciated powernet components so I'm just going to close it since replacing all of that stuff is a known mapping issue.
