### ISSUE TITLE
Medborg can get a free, empty hand.

### ISSUE THREAD

**Issue by NakataRin** [space-wizards/space-station-14#19072]
## Description

Medborg can get a free, empty hand. 
The issue is not about the medborg itself, but rather about the medborg health scanning module. This module has a health analyzer and a stethoscope. The stethoscope can be feed to a moth. After that, you get a free hand.

**Reproduction**

• Install the module into a medborg
• Medborg feeds a moth with a stethoscope
• Medborg gets an empty hand

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/45946146/426ace9f-8955-41e5-b593-23669364c788)

**Comment by deltanedas** [comment]
why does it have a stethoscope in the first place its useless

**Comment by LordEclipse** [comment]
Why can moths eat stethoscopes? Aren't they mosty plastic and metal?

**Comment by EmoGarbage404** [comment]
bigger issue is that if an item is marked as unremovable, you probably shouldn't be able to feed it to someone or eat it yourself.
