### ISSUE TITLE
borgs dont need power to move or speak

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#19096]
## Description
makes emp useless and battery charging an rp thing

**Reproduction**
1. take battery out of malf
2. malf can still move and talk

**Comment by EmoGarbage404** [comment]
the battery is for the modules 4head

**Comment by LankLTE** [comment]
battery charging isn't an "rp" thing, they still can't use their modules if they're dead. I think being EMPed should probably disable them for a bit, but running out of battery in a bad place and just being dead forever would kinda suck

**Comment by deltanedas** [comment]
still doesnt make sense that it can run back to a charger all on its own with no power, it should at least have to call for help

**Comment by LankLTE** [comment]
Call for help how, exactly? They have no radio and binary only works if there are other borgs (who are also smart enough to get help for you)

**Comment by deltanedas** [comment]
ok fair they need radio module for that to be feasible

**Comment by Morb0** [comment]
They should at least slow down when the battery is low

**Comment by EmoGarbage404** [comment]
> They should at least slow down when the battery is low

they do. Their movespeed is capped to their walking speed.
