### ISSUE TITLE
Entry job: Bring back table interaction.

### ISSUE THREAD

**Issue by PrPleGoo** [space-wizards/space-station-14#191]
When you attack a table with an item you expect the item to be placed down here.
I recommend adding a component to table which can later be added to closets and crates.
This component handles the logic of taking the item from the hand and into the world.
Once this is implemented the work around for dropping items under your cursor can be removed.

**Comment by clusterfack** [comment]
That wasnt really meant to be a work around, but a QoL improvement. Such a feature isnt even possible to do in byond which is why it doesnt exist there.

**Comment by Acruid** [comment]
Resolved in https://github.com/space-wizards/space-station-14/pull/195.
