### ISSUE TITLE
Remove species stat changes

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#19107]
I shouldn't have to wiki if a slime takes less or more heat damage than an arachnid or if one moves 0.5m/s faster or some other stuff, just standardise it as it doesn't lead to interesting gameplay.

**Comment by CrigCrag** [comment]
we could add it to the guidebook, stat changes gives antags a bit of a reward for scouting out their target and making a plan, like slipping a diona captain in welding fuel then lighting them ablaze discreetly as you pass by.

**Comment by metalgearsloth** [comment]
> like slipping a diona captain in welding fuel then lighting them ablaze discreetly as you pass by.

This isn't a stat change?

**Comment by CrigCrag** [comment]
diona take enough extra heat damage to where being set on fire is actually a threat. I'm assuming that's what you meant by stat changes.

**Comment by Emisse** [comment]
I think I disagree with this partially. I have seen a lot of interesting gameplay from certain races having different stats but I can see why standardizing it would make balance a lot easier.

**Comment by LankLTE** [comment]
I am actually totally willing to do this, and even tried to (or rather layed out some plans) right after moths came out. The main issue from there is giving each face a mechanical sidegrade or upside/downside to account for it, and I don’t really have ideas for any of the races as to what that might be.

**Comment by CrigCrag** [comment]
I'd be fine with removing stat differences if other races were made mechanically unique

**Comment by mirrorcult** [comment]
not actionable/agreed upon rn
