### ISSUE TITLE
VIM slowly suffocates its poor mouse passengers

### ISSUE THREAD

**Issue by Emisse** [space-wizards/space-station-14#19116]
repro
go in a vim
die after a while

**Comment by deltanedas** [comment]
the atmos shielding this is broken either that get fixed which id good for all mechs or its disabled so mouse can live

**Comment by deltanedas** [comment]
from looking at vv the air mixture is grabbed from the surroundings when you enter it, then slowly oxygen will deplete as mousie breathes
