### ISSUE TITLE
Mopped up chems broken

### ISSUE THREAD

**Issue by hord-brayden** [space-wizards/space-station-14#19156]
## Description

It seems over the past few days that it is no longer possible to mop up liquids from the floor and transfer them into a container. Currently when mopping (using damp rag or mop), once the mop is full and is used on a water source, the chems are voided and effectively gone. 

**Reproduction**

1. Spill Chems
2. Mop up chems using a beaker or whatever floats your boat
3. Notice that the chems are no longer transferred into beaker
4. Cry
5. Ask your parents why they don't invite you to christmas anymore

**Screenshots**

**Additional context**

**Comment by Titian3** [comment]
Got a fix for this will put the PR up shortly. 🎄🎅Just show up at you parents for Christmas, I'm sure they will forgive you!
