### ISSUE TITLE
Sericulture issues

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#19158]
1. Lack of docs.
2. Code conventions i.e. not in shared + no VV + no access.
3. IsHungry should be on hungersystem not sericulture.
4. This parenting code looks extremely sus and should attach to the grid not the player.

**Comment by metalgearsloth** [comment]
Also I'm pretty sure rats / dragon should've bene made to use this.

**Comment by PixelTheKermit** [comment]
Noted
