### ISSUE TITLE
engiborgs should be insulated

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#19174]
## Description
or have an insuls module so they can actually do anything

**Comment by Eden077** [comment]
Borgs don't need insuls iirc

**Comment by LankLTE** [comment]
They already are insulated? You can cut wires and pulse doors just fine as a Borg idk what you’re on about

**Comment by deltanedas** [comment]
they arent insulated i had an engiborg cutting a wire and got shocked

**Comment by deltanedas** [comment]
![155426](https://github.com/space-wizards/space-station-14/assets/39013340/d6f63cea-51c4-4b43-8b23-1201757ce795)

**Comment by LankLTE** [comment]
Last night I cut the HV cable under the AME so I have no idea why it’s doing that

**Comment by deltanedas** [comment]
on master, happens on both tool module and advanced tool module @mirrorcult reopen
most likely introduced by borg tweaks

**Comment by mirrorcult** [comment]
glub

**Comment by EmoGarbage404** [comment]
actually got fixed
