### ISSUE TITLE
The electrical output of the TEG depends on the number of connected high-voltage consumers.

### ISSUE THREAD

**Issue by Anzarot121** [space-wizards/space-station-14#19185]
## Description

A friend of mine was experimenting with generation and found that each substation/SMES gives 5 kW of power output from the TEG.
**Reproduction**

Start the TEG, connect the SMES to it, watch the Megawatts of electricity.
**Screenshots**

![image-10](https://github.com/space-wizards/space-station-14/assets/116586144/400eb742-3166-4bf2-8da0-34bed6cac978)
![image-9](https://github.com/space-wizards/space-station-14/assets/116586144/5820b3e4-6e43-48af-b4b2-502f34c44a29)
**Additional context**
The first screenshot is 90 SMES, the second is about 240.

**Comment by moonheart08** [comment]
Intended, the TEG won't overproduce.
