### ISSUE TITLE
teleporting wheel chair attach bug

### ISSUE THREAD

**Issue by DummeHytteOst** [space-wizards/space-station-14#19258]
teleporting with someone who is on a wheel chair (and other vehicles?) attaches you to the wheel chair

if someone is attached to a wheel chair, and said wheel chair gets moved, then the attached moves also, and rotates with the wheel chair

kinda hard to explain so here is a clip, keep an eye on the human scientist who switched place with me on the wheel chair

https://github.com/space-wizards/space-station-14/assets/94384139/04a7322a-c989-4d7e-8e1b-903da3200002

**Comment by Pangogie** [comment]
Vehicles currently removed awaiting a better implementation.
