### ISSUE TITLE
syndie guns are too inaccurate while NT guns are perfectly accurate

### ISSUE THREAD

**Issue by JoeHammad1844** [space-wizards/space-station-14#19277]
The C20-r, L6 and bulldog are all quite inaccurate for long range fights while the lecter and WT550 are slower firing but are perfectly accurate

**Comment by deltanedas** [comment]
wt550 and c20r have similar inaccuracy, at least while magdumping

**Comment by JoeHammad1844** [comment]
thank you for the correction

**Comment by metalgearsloth** [comment]
All guns in the same class have the exact same accuracy, ignoring firerate.
