### ISSUE TITLE
Observers can open and close guns bolts

### ISSUE THREAD

**Issue by MilenVolf** [space-wizards/space-station-14#19283]
## Description
They should not be allowed to do it. Observers can slowly unload a gun that has bolt.

**Reproduction**
As observer, right-click the gun that has bolt, then close and open bolt. That's it.

**Screenshots**

https://github.com/space-wizards/space-station-14/assets/63782763/06e8cbf8-3b62-49b0-a4fa-9198f772e9e9

**Additional context**

**Comment by Equivocateur** [comment]
Bug of the real material, could replicate on wizden servers right now.

**Comment by MilenVolf** [comment]
Closed in #19349
