### ISSUE TITLE
Explosions don't do massive damage if you hide in a locker

### ISSUE THREAD

**Issue by SoulSloth** [space-wizards/space-station-14#1929]
Reproduction steps:
1. activate a syndicate minibomb
2. jump in a locker(dropping the bomb outside is optional)
Expected result: You are now a pink mist
Actual: barely a scratch

This same effect will occur even if your holding the minibomb inside a locker. Other containers may have similar effects

**Comment by Fizbun** [comment]
Hold up. This isnt a bug, its a feature!
