### ISSUE TITLE
TEG ignores the law of conservation of energy

### ISSUE THREAD

**Issue by Anzarot121** [space-wizards/space-station-14#19300]
## Description

It is a closed system that consumes less than it produces and has an efficiency ratio of over 1000%. It clearly shouldn't work that way.
**Reproduction**

Assemble the system as in the screenshot. All pumps, heaters/coolers to maximum/minimum. Heaters and coolers with T1 components.
**Screenshots**

![BPdYJgg](https://github.com/space-wizards/space-station-14/assets/116586144/a9cafdd6-fd3a-4955-8434-4615851036f3)

**Additional context**

This system consumes 2 kilowatts and produces at least 5.5 megawatts. Perhaps it produces even more, the author of the scheme was simply too lazy to install even more empty substations.

**Comment by Errant-4** [comment]
It could well be that it's the heater/cooler that break thermodynamics

**Comment by deltanedas** [comment]
yes its the heaters and freezers that create more energy than they consume
