### ISSUE TITLE
Blast doors can not close over conveyor belts.

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#19316]
## Description
Blast doors do not close when conveyors are below them.
Is an issue on Meta map as it vents all of disposals and the surrounding maints area.

**Reproduction**

1. Create conveyor
2. place blast door on top
3. link to button - toggle on pressed
4. open blast door
5. try to close blast door.
6. push the button several more times while the door fails to close and you slowly suffocate crowbar less.

**Screenshots**
On Meta where the doors can not close:
![image](https://github.com/space-wizards/space-station-14/assets/47093363/272b093a-9b2b-429c-ad18-4b5c3c11d6d6)
With the conveyors removed:
![image](https://github.com/space-wizards/space-station-14/assets/47093363/1595571a-e458-4b4a-be53-4043317f8d4d)
Set up for local test:
![image](https://github.com/space-wizards/space-station-14/assets/47093363/aea1a4d3-bb1d-4241-acdf-8faad004840f)q

**Additional context**
Most other maps use some plastic flaps, so doesn't happen every round.

**Comment by IamVelcroboy** [comment]
Bump. Yeah, running into this issue too.
