### ISSUE TITLE
Particle Accelerator ISSUES

### ISSUE THREAD

**Issue by Emisse** [space-wizards/space-station-14#19342]
>building the PA is impossible from scratch from machine frames. it fucks up and wont accept mats.

>some maps have some sort of serialization error on their datafields or something that was never updated making the PA not work unless deleted and respawned by admins. 

>skub

**Comment by arimah** [comment]
Related comment: https://github.com/space-wizards/space-station-14/issues/18511#issuecomment-1687893199
