### ISSUE TITLE
Medbay has no way to tell what chemicals are in a patient

### ISSUE THREAD

**Issue by SpeltIncorrectyl** [space-wizards/space-station-14#19354]
## Description
Chemicals have small overdose thresholds, and when medbay cannot tell what chemicals are in someone, overdoses can happen, especially if two different medics are trying to treat one person.
Having to remember what chemicals are in someone, and guess how many have been metabolised adds unnecessary complexity.

**Comment by UbaserB** [comment]
true

**Comment by juliangiebel** [comment]
Just draw blood with a syringe, put the blood into a beaker and then put the beaker into a ChemMaster to check what's in the blood stream:
![image](https://github.com/space-wizards/space-station-14/assets/8915246/60901101-e4fe-4b5c-8bfa-53bca650e251)

**Comment by deltanedas** [comment]
me when doctors communicate and not just all inject bicar at the same time

**Comment by SpeltIncorrectyl** [comment]
> Just draw blood with a syringe, put the blood into a beaker and then put the beaker into a ChemMaster to check what's in the blood stream: ![image](https://user-images.githubusercontent.com/8915246/261856333-60901101-e4fe-4b5c-8bfa-53bca650e251.png) _(This is after injecting myself with a space medipen and doing what I described above)_

Imagine being a doctor, taking a blood sample of a patient, then passing it to chemistry for them to pour it into a beaker, put in the chemmaster or chemdispenser and relay it back to you, to not even know the numbers of chemicals in the patient - you have to extrapolate by looking at the total volume of blood in the patient, and then the size of the sample.

**Comment by Errant-4** [comment]
What I'm hearing is the ChemMaster should have Print

Also maybe medkits should come with pre-written sticker notes you can slap on the patient about the chem you gave them

**Comment by potato1234x** [comment]
bloodstream analyser.

**Comment by Anzarot121** [comment]
Just don't put bicaridine in one patient's mouth with the whole medical department?

**Comment by SpeltIncorrectyl** [comment]
Putting ability to scan chems on health analyzer is not balanced.

**Comment by SpeltIncorrectyl** [comment]
I suppose when they make the sleepers this issue will be resolved.

**Comment by lzk228** [comment]
> Putting ability to scan chems on health analyzer is not balanced.

a lot of ss13 builds have it
a lot of have that ability roundstart
what if we make health analyzer upgrades in some of technologies

**Comment by metalgearsloth** [comment]
Every day we get closer and closer to just putting sleepers back in lol.

**Comment by QuietlyWhisper** [comment]
scanning chems is either suggested in a way that makes it so out of the way that no one will bother to do it, or likely too late in the round to be relevant to gameplay. Someone needs to make a design choice here...

**Comment by NancokPS2** [comment]
This is the case for a lot of techs tbh.  
Science just unlocks things too slowly. But again, this is an issue with ALL researches, not this feature in particular.  
  
And overall this is fine atm. Scanning chems is not critical and this follows design choices with other departments.  
  
- Sec has advanced lasers, but you rarely if ever see the tech come into play due to being out of the way and the sec-lathe being in the armory most of the time.  
- Robotics depends on salvage, but nothing suffers if they can't make any borgs.   
- In the same way, getting borgs for a specific department requires a lot of effort and is rarely seen, but those departments don't NEED borgs to work.  
- Cloning...

**Comment by QuietlyWhisper** [comment]
Either way lank mentioned making this a seperate item from health analyzer was okay, it really isnt powerful enough to matter where the heck you get it from but at least it would be in the game

**Comment by Kelrak** [comment]
How about just adding charts to the beds? Or something similar which could be updated with what was injected? Also makes sense RP-wise I guess

**Comment by IamVelcroboy** [comment]
> How about just adding charts to the beds? Or something similar which could be updated with what was injected? Also makes sense RP-wise I guess

Patient charts would be amazing!
