### ISSUE TITLE
Spiders are comically strong

### ISSUE THREAD

**Issue by EmoGarbage404** [space-wizards/space-station-14#19359]
## Description

a single spider can crit in 4 hits + can proc max bleeding. This is a relatively common station event, why are they so strong??

**Comment by CrigCrag** [comment]
they are so strong because mobs are affected by the melee rework. AI mobs always do a direct hit (left click), so they always deal +25% damage

**Comment by Errant-4** [comment]
Tarantulas always had pretty strong stats, for the record. They deal 16! points of damage per hit, some of which is poison does that keep dealing damage? And they have 50% more health than a crewmember

**Comment by Myakot** [comment]
> Does that keep dealing damage? Or poison damage applied is just a number?
Just a number, unfortunately.

Well they **are** giant menacing vent-living spiders. They fall apart if you have anything ranged, but are a force to be reckoned with in melee. Although I can see the impending nerf to them, because nobody can have nice things.

**Comment by LordEclipse** [comment]
> Tarantulas always had pretty strong stats, for the record. They deal 16! points of damage per hit ((plus bonus)), some of which is poison. Does that keep dealing damage? Or poison damage applied is just a number? And they have 50% more health than a crewmember
> 
> Of course, a large damage means a more noticeable bonus from the click attack

Its 20 damage actually per hit, (5 poison, 15 piercing). Also effective HP of around 150 because of no crit state. (They are up and moving up until the moment their hp hits 0)

**Comment by Equivocateur** [comment]
![moment](https://github.com/space-wizards/space-station-14/assets/109166122/01e59bd7-656d-4a3b-91c7-98aae3fc66f2)
