### ISSUE TITLE
Inventory sorting issues

### ISSUE THREAD

**Issue by VektorZ1** [space-wizards/space-station-14#19376]
Right now there is no convenient way to arrange and group items within the vault (mostly bags, especially bluespace bags)
The only way is to take an item out and put it back in. There are only boxes for grouping, which opens a new window and is only effective when full.

**Comment by VektorZ1** [comment]
I think it would be cool to be able to create something like groups within the vault, as well as move items by drag and drop within it

**Comment by Emisse** [comment]
being able to swap items positions or drag them around in storage would be helpful
