### ISSUE TITLE
Chasm QOL

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#19386]
1. Chasms shouldn't chasm people grappling (or that have joints in general IMO).
2. Can't play catwalks on them apparently.
3. Shouldn't chasm weightless stuff.

Will need some changes to StepTrigger.

**Comment by CrigCrag** [comment]
stepping on the corner of a chasm also kills you which feels bad and unintuitive

**Comment by deltanedas** [comment]
joints check would mean pushing people across chasms would work???

**Comment by deltanedas** [comment]
new chasm meta have 2 people grab eachother then go across the chasm
