### ISSUE TITLE
kill random head objective can fall back to non humans

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#19408]
## Description
2 line fix but should i do it... having a very rare mouse kill objective might be ok

**Reproduction**
1. spawn and control pai
2. join and tator yourself
3. you might be told to kill pai
4. if not then add kill random head objective

**Comment by NancokPS2** [comment]
I could swear a check was added specifically to prevent this a while ago.  
Maybe it got reverted at some point or straight up broke again.

**Comment by deltanedas** [comment]
yes i forgot to add the component for killrandomhead and nobody is saying anything....
