### ISSUE TITLE
chasms should not appear with plasma atmospheres

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#19405]
## Description
nearly invisible round removal tile vs noob who would win

**Screenshots**
find the round removal tile:
![19:41:36](https://github.com/space-wizards/space-station-14/assets/39013340/c751d183-3d99-46eb-a002-ca3573c938d6)

**Comment by potato1234x** [comment]
round removal tile is too punishing imo

**Comment by mirrorcult** [comment]
gonna make them fully airtight i think to avoid this

**Comment by deltanedas** [comment]
round removal tile being removed from lava shortly so ig its fine
