### ISSUE TITLE
APE Flipping On Saltern

### ISSUE THREAD

**Issue by Alekshhh** [space-wizards/space-station-14#19404]
During a round on Saltern as an RD, I noticed two APEs I was using for anomalies periodically flipped the opposite way by themselves, facing away from the anomaly they were wrenched by. I don't know if it happens on other stations or why, but I saw it on Saltern specifically. I doubt a person did it, since I saw it happen before my own eyes once.

**Comment by deltanedas** [comment]
real

**Comment by Alekshhh** [comment]
haven't seen it happen since so it's probably fine
