### ISSUE TITLE
supermatter  grenade broken

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#19406]
## Description
- its first stage doesnt do anything
- its second stage is really small, looks like a minibomb explosion

**Comment by deltanedas** [comment]
@AlexMorgan3817 a

**Comment by AlexMorgan3817** [comment]
Wtf? What exactly "doing nothing"

**Comment by deltanedas** [comment]
theres no distortion and theres no item pulling

**Comment by AlexMorgan3817** [comment]
Do not panic, i found an issue

**Comment by AlexMorgan3817** [comment]
IT LIVE.
![image](https://github.com/space-wizards/space-station-14/assets/46600554/b7ff9f89-8a47-44bc-9a02-c8f3de6649de)
AGAIN.

**Comment by AlexMorgan3817** [comment]
Resolved
