### ISSUE TITLE
Singularity eats tiles under forcefield releasing itself

### ISSUE THREAD

**Issue by AJimmyU** [space-wizards/space-station-14#19426]
## Description

Singularity eats tiles under forcefield, releasing itself from containment.

**Reproduction**

https://cdn.centcomm.spacestation14.com/replays/lizard/2023/08/22/lizard-2023_08_22-09_46-round_31587.zip

Right at start of singularity creation, it eats west containment lattice.
At ~10:20 it eats northern containment lattice, breaking off the pylon and loosing itself.

**Screenshots**

**Additional context**

I suspect it's happening when singularity grows into a larger size when directly next to (and moving towards) the containment field.

**Comment by Eden077** [comment]
Singularity code strikes again

**Comment by JustCone14** [comment]
Watching the replay it definitely looks like as the singulo is moving upwards it transions from level 3 to 4 and destroys the latices holding the containment field, which breaks and looses the singulo.

**Comment by GoodWheatley** [comment]
This is intentional
