### ISSUE TITLE
Client may crash when chambering round from magazine

### ISSUE THREAD

**Issue by Volotomite** [space-wizards/space-station-14#19446]
## Description

If you take magazine and insert round in it by hand, insert magazine back and try to recycle the bolt - client will crash locally.
When playing on server, I noticed client will not crash, instead it'll cause big lag when chambering it

**Reproduction**

1. Spawn any gun with bolt (MK handgun will do)
2. Remove magazine
3. Remove bullet from magazine
4. Insert bullet back to mag by hand
5. Insert magazine back in gun
6. Recycle bolt

**Additional context**

I did some research, and noticed that this line causing bug:
https://github.com/space-wizards/space-station-14/blob/852b66dee6423531f615956cad583e93996d96fc/Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.ChamberMagazine.cs#L235C18-L235C18

I'm not familiar enough with game ids, but I noticed that same bullets have different ids on Client and Server.
On client it looks like this (added debug log):
![image](https://github.com/space-wizards/space-station-14/assets/43648983/9bd94fe2-2cf4-400b-8951-94c37d19ebd0)
And, as I understand, that line of code is supposed to delete bullets with such client side ids
However, once step 4. is done - bullets in mag will receive server-like id for client, and when calling del - client will crash because deleting server ids is forbidden:
![image](https://github.com/space-wizards/space-station-14/assets/43648983/b1ce5f23-5c3d-4157-92ec-0796b9006468)
 
 So, this is what causes this issue. If possible - it would nice to receive some explanation on how these ids work, because I wasn't able to fix it due to lack of understanding

**Comment by metalgearsloth** [comment]
Dupe https://github.com/space-wizards/space-station-14/issues/19165
