### ISSUE TITLE
Action Hotbar UI

### ISSUE THREAD

**Issue by Acruid** [space-wizards/space-station-14#1945]
The previous PR was #951, but it was closed for another redesign.

Here is the discord discussion about a new design utilizing the existing Verb system.
https://discordapp.com/channels/310555209753690112/560845886263918612/737403179876090026
https://discordapp.com/channels/310555209753690112/310555209753690112/744800790014591006

**Comment by chairbender** [comment]
also https://discord.com/channels/310555209753690112/310555209753690112/767129404177514497

**Comment by chairbender** [comment]
taking this on, it kinda overlaps with another ticket I've been working on in #272

**Comment by chairbender** [comment]
also https://hackmd.io/WS76qa1cR3qDqgEv1TXJuw?edit

**Comment by chairbender** [comment]
mroe convo, re: specifics of how auto-populating works https://discordapp.com/channels/310555209753690112/346743671787356160/775948277404532786
