### ISSUE TITLE
Hunger damage issues

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#19486]
## Description

There's no feedback that the person is dying of starvation, cold damage make it seem like they are freezing to death
Hunger damage kills people going afk, you want your character to be sleeping for a while in the round? Well they starved to death on their sleep
This doesn't fix any kitchen issues or people consuming junk food
**Reproduction**

**Screenshots**

**Additional context**

**Comment by slarticodefast** [comment]
Hunger damage has been removed in #24790
