### ISSUE TITLE
Kudzu Still Bugged

### ISSUE THREAD

**Issue by liltenhead** [space-wizards/space-station-14#19506]
## Description
Turns out slowing the speed by 4x didn't do anything. It doesn't seem to break in offline testing so it's something other than the speed.

**Reproduction**
Someone in botany is gonna dump 100 units of mutagen on a plant every other round to make kudzu. It seems to almost always bug and spread too fast.

**Comment by metalgearsloth** [comment]
Dog just re-open https://github.com/space-wizards/space-station-14/issues/18021

**Comment by liltenhead** [comment]
I didn't know I could do that, my bad.
