### ISSUE TITLE
flying mobs are vulnerable to pits

### ISSUE THREAD

**Issue by CrigCrag** [space-wizards/space-station-14#19516]
## Description

flying mobs can fall in chasms
**Reproduction**

1: be a flying holocarp fishy
2: go on a wondrous adventure on your lava planet home
3: **fly** over a chasm
4: suddenly lose your ability to fly and fall into an endless void
**Screenshots**

**Additional context**

flying mobs are also slowed by water

**Comment by GoodWheatley** [comment]
Should be fixed by #19707, and #19386 is a more detailed version of this issue
