### ISSUE TITLE
Disposal units do not currently take air from their surroundings

### ISSUE THREAD

**Issue by DrSmugleaf** [space-wizards/space-station-14#1957]
They should use the surrounding air to pressurize and send it in the disposals holder, transferring it to the destination.

**Comment by Aranclanos** [comment]
You can suffocate at some spots while traveling inside the disposals due to https://github.com/space-wizards/space-station-14/issues/2321
In fact, if you build a line of airlocks on top of a disposal tunnel you can kill or heavely damage players

**Comment by Zumorica** [comment]
Fixed by #2686
