### ISSUE TITLE
The "Superkudzu" Incident...

### ISSUE THREAD

**Issue by Warentan** [space-wizards/space-station-14#19584]
This post may only be for documentation, since I think this could have been a one-time thing, but i think its good to have documentation anyways.

Yesterday on Lizard, A kudzu appeared in sci while working on Barratry. Now, Unless I've been misinformed by a mod, I'm 90% sure that Kudzu is supposed to slow down when it gets to a certain size... 
This stupid weed did NOT slow down. 
The "Superkudzu" just kept spreading and spreading, never slowing down. I'm a hundred percent sure that this was a bug, because not even ERT and Goat teams could take it out. In fact, the goats couldn't even EAT the kudzu, because I think the abnormal... kudzu... npc... grow... I dunno. The goat AI broke because of Superkudzu. That's all I know. The Superkudzu grew to such extent that it took over ALL of the outside spacewalk , including singulo. We had atmos backpump a bunch of vapor through the vents only to have SOME kudzu pushed back, and many NT Employee casualties... Only a few survived to tell the tale of Superkudzu...

**Reproduction**
Unknown

**Screenshots**
If you want to see the replay, it is round number 31913. Download it [Here.](https://cdn.centcomm.spacestation14.com/replays/lizard/2023/08/26/lizard-2023_08_26-20_11-round_31913.zip) (The kudzu starts at Minute 18 Second 4.)

**Additional context**
shitsci

**Comment by metalgearsloth** [comment]
Dupe https://github.com/space-wizards/space-station-14/issues/18021

**Comment by Warentan** [comment]
mb
