### ISSUE TITLE
C4 dissapears when wall they were on got deleted

### ISSUE THREAD

**Issue by CaptainSqrBeard** [space-wizards/space-station-14#19596]
## Description
C4 dissapears when object it was planted on got deleted. Suprisingly, it works fine with crates.

**Reproduction**
1. Plant C4 on wall, girder, grille, tank
2. Deconstruct, delete or destroy the object it was planted on
3. C4 dissapears

**Screenshots**

**Additional context**

**Comment by deltanedas** [comment]
dupe

**Comment by deltanedas** [comment]
#14167
