### ISSUE TITLE
Stack listing

### ISSUE THREAD

**Issue by PrPleGoo** [space-wizards/space-station-14#196]
In space station it is a common occurrence that entities are piled onto a certain location:
- a corpse mess in the cloning area;
- stacks of paper work in the HoP's office;
- a blood vial catastrophe in virology;
- lockers;
- the blown up remnants of an armory;
- just a pizza box on top of a banana peel;

To deal with these situation effectively spacemen need to quickly make an inventory of all entities in a designated location.
SS13 implemented this through the ALT+click menu.
The proposal here is to implement ALT+click to scan for entities in a range and list them all, inventory style.
Any interactions with items on this list should relay through the interaction system and readjust the location of the mouse click to reflect a click on the entity in world.
This makes it possible to swing melee weapons, shoot guns, examine, pull, strangle and whatelsehaveyou, unimpeded.

**Comment by PrPleGoo** [comment]
The list should also update to any changes and close automatically when the player exits inventory range.

**Comment by PJB3005** [comment]
I think we should make the right click menu sufficiently well-implemented to serve this purpose as well.

**Comment by PrPleGoo** [comment]
Catch RMB in the world to spawn this menu.
Entries can then be RMBed to open up a single menu which is currently opened by RMBing and then choosing the entity.

**Comment by SweptWasTaken** [comment]
Pretty sure this is feature-complete, closing.
