### ISSUE TITLE
Stasis bed bug

### ISSUE THREAD

**Issue by Fromoriss** [space-wizards/space-station-14#19601]
## Description
Guide how to destroy body with stasis bed.

**Reproduction**
1. Kill somebody.
2. Put body on stasis bed.
3. Start deconstruction.
4. Use crowbar.
5. Body destroyed.

**Screenshots**

https://github.com/space-wizards/space-station-14/assets/106442259/2c5d2e58-5354-4463-917a-d9ea44d7ff92

**Additional context**
Fix it pls.

**Comment by lzk228** [comment]
definitely a dupe

**Comment by hord-brayden** [comment]
I've been seeing that laying someone in perfect physical condition on a stasis bed, they begin to take airloss damage. 

Wondering if it's suffocating them or latching into the oxengate system and effectively stopping that process from promulgating through the organ system?

**Comment by Emisse** [comment]
its slowing their metabolism which includes oxygen intake, although its generally fine and most doctors play around this
