### ISSUE TITLE
Gateways can't teleport between maps

### ISSUE THREAD

**Issue by LordEclipse** [space-wizards/space-station-14#19616]
## Description
Gateways "fizzle out" and both sides are deleted if you attempt to enter ome that goes to another map. They work with two gateways, on the same map, however.

**Reproduction**
1.) Place gateway one map, and the destination on another.
2.) Set up the destination gateway.
3.) Attempt to enter the non-destination gateway
4.) It fails to do anything, and both the entrance and exit are deleted.

**Screenshots**

**Additional context**
Makes events a little more arduous to set up. In my opinion.
Might have to do with the RD Hand Teleporter fix.

**Comment by deltanedas** [comment]
portal need a whitelist since gateways use portal

**Comment by mirrorcult** [comment]
its just a bool on the component you can change

**Comment by LordEclipse** [comment]
> its just a bool on the component you can change

guh really?

**Comment by deltanedas** [comment]
pro ops
