### ISSUE TITLE
cargo shuttle doesn't have access to trading post to sell/buy stuff

### ISSUE THREAD

**Issue by retequizzle** [space-wizards/space-station-14#19632]
seems like it's impossible to complete bounties or have anything beyond a barely functioning department after the first few minutes? was mentioned in passing to me and saw nothing was here for it yet

admins have been skating by with spawning a telepad in for cargo but idk why no one thought to just make a git issue for this sooner

**Comment by AjexRose** [comment]
More details about this, is that I tried just resetting consoles which didnt work, and another admin has tried taking away the Cargo Shuttle component and readding it, which apparently didnt work.

**Comment by TheArturZh** [comment]
I think trading post is being deleted right away after being spawned
I think it would be better to create trading post when first CargoShuttleComponent is initialized rather than to create it on round restart, at least it solved the problem for us
