### ISSUE TITLE
Make antagonist roles need time to play

### ISSUE THREAD

**Issue by nopeingeneer** [space-wizards/space-station-14#19641]
In case of situation when whole nukes squad have 0 hours in game

**Comment by asperger-sind** [comment]
Yea it's either a dupe or we've had 400 discussions about it on Discord and everyone collectively went "yea it's probably a gh issue already i wont make one myself" for every single discussion and outside.

**Comment by deltanedas** [comment]
theres a pr untouched for 3 weeks that does just that

**Comment by nopeingeneer** [comment]
> theres a pr untouched for 3 weeks that does just that

Link?

**Comment by nopeingeneer** [comment]
> Yea it's either a dupe or we've had 400 discussions about it on Discord and everyone collectively went "yea it's probably a gh issue already i wont make one myself" for every single discussion and outside.

Anyway I don't conversate in wiz den Discord in case of ban, so whatever

**Comment by deltanedas** [comment]
#17929

**Comment by nopeingeneer** [comment]
> #17929

If it was just requirements.. YAML litter check fail says that brilliant idea meat with brick wall
