### ISSUE TITLE
Putting down an item makes it wierdly jitter for a bit

### ISSUE THREAD

**Issue by VasilisThePikachu** [space-wizards/space-station-14#19673]
## Description

**Reproduction**

1. Place an item down

**Screenshots**

https://github.com/space-wizards/space-station-14/assets/34938708/0f68df35-3a10-404b-ba72-3e9f67750f75

**Additional context**

**Comment by PJB3005** [comment]
One day I'll get around to coding world line debugging...

**Comment by deltanedas** [comment]
this happens for putting clothes in hand too...

**Comment by VasilisThePikachu** [comment]
Closed by #19714
