### ISSUE TITLE
Loader crashes right after trying to connect

### ISSUE THREAD

**Issue by Warentan** [space-wizards/space-station-14#19671]
Game window (not launcher) crashes on start. From the terminal output, it looks like it's an unhandled audio exception issue.
Not sure if the log contains personal gunk so devs please DM me on discord (same username, in ss14 server)

Edit
Not sure if this helps 
![Screenshot from 2023-08-30 17-34-21](https://github.com/space-wizards/space-station-14/assets/113652968/7bf77036-4f5f-4f01-8939-7119e06dc9e1)
I run ubuntu linux

Edit:
Downloaded openal (Which was the problem) and now I get
[ERRO] clyde.oal: [_audioOpenDevice:102] ALC error: InvalidValue
[ERRO] clyde.oal: Unable to open OpenAL device! {1}

**Comment by deltanedas** [comment]
you need openal...

**Comment by Warentan** [comment]
> you need openal...

Where can I download this.

**Comment by deltanedas** [comment]
apt search openal

**Comment by Warentan** [comment]
nice

**Comment by Warentan** [comment]
Nevermind, Not nice, still crashes after downloading.

**Comment by Warentan** [comment]
NEW ERROR MESSAGES!

[ERRO] clyde.oal: [_audioOpenDevice:102] ALC error: InvalidValue
[ERRO] clyde.oal: Unable to open OpenAL device! {1}

**Comment by moonheart08** [comment]
OS issue, please configure your audio.
