### ISSUE TITLE
Syntax error in hcut.swsl, game cannot start

### ISSUE THREAD

**Issue by arimah** [space-wizards/space-station-14#19698]
#19695 has a shader language syntax error: `1.0f` should be `float(1)` according to everything resource I can find.

I'm also not sure this cast is even necessary, as it seems the shader language seems to automatically promotes integer literals to floats when necessary...

**Comment by metalgearsloth** [comment]
Is float(1) even valid glsl

**Comment by arimah** [comment]
It's literally one of the examples under [Shading language](https://docs.godotengine.org/en/3.0/tutorials/shading/shading_language.html#casting):

> Example:
> `float a = 2; // valid`
> `float a = 2.0; // valid`
> `float a = float(2); // valid`

Also tested locally, game runs perfectly fine.

**Comment by metalgearsloth** [comment]
> float(int) // converts a signed integer value to a float

I opened the spec. Seems like a conversion wouldn't be ideal to me.
