### ISSUE TITLE
Supply bot is just a taxibot copy-paste

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#19716]
Please just use a new parent and use composition...

**Comment by ItsMeThom** [comment]
Heya @metalgearsloth, could you elaborate a bit? I did implement supplybot based on taxibot yes. I parented it to `MobSiliconBase` as the other lesser borgs all seemed to be parented to that. Can you explain the reasoning behind a new parent? Im new to the codebase so any help is useful, thanks.

**Comment by lzk228** [comment]
ok, gonna working on it

**Comment by lzk228** [comment]
ok, gonna working on it

**Comment by ItsMeThom** [comment]
> So right now they both have a lot of similar stuff so ideally you'd just add another prototype to the file and have them both inherit it as you can specify multiple parents. That way you can remove half the components on them that are shared and get the file a lot smaller.

Thanks! Thats really helpful.
