### ISSUE TITLE
syndiemaintloot needs fixing

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#19723]
Abraham found this:

![image](https://github.com/space-wizards/space-station-14/assets/31366439/b3d3fbbd-6a8f-47dc-987b-1904d04399a4)

Spawning null entities is not the way to do it.

@Equivocateur

**Comment by Equivocateur** [comment]
null's there because an orgroup is guaranteed to spawn an item from the group.
Not sure of any other id's that can be just "nothing". Replacing the null with an actual entity would just spawn it every time unless it rolls a syndie item.

**Comment by metalgearsloth** [comment]
> null's there because an orgroup is guaranteed to spawn an item from the group. Not sure of any other id's that can be just "nothing". Replacing the null with an actual entity would just spawn it every time unless it rolls a syndie item.

Refactoring it to not spawn dummy entities is preferred over leaving it spawning a dummy entity every time.

**Comment by Equivocateur** [comment]
> Refactoring it to not spawn dummy entities is preferred over leaving it spawning a dummy entity every time.

Would "add probabilities in an or group together; subtract that amount from 100; the result is the chance of an orgroup doing nothing" be good enough?

**Comment by metalgearsloth** [comment]
That's not viable for the larger groups as it would become a significant maintenance burden, see https://github.com/space-wizards/space-station-14/issues/19724

**Comment by CaptainSqrBeard** [comment]
we should have proper loot tables that can refer to it's own prototype too

**Comment by slarticodefast** [comment]
fixed by #30579
