### ISSUE TITLE
Arrivals rotation issues

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#19721]
Since https://github.com/space-wizards/space-station-14/pull/17189 I think, pendingclockin isn't removed so your camera autorotates every time you walk off the shuttle instead of once which is very disorienting.

**Comment by photonicDog** [comment]
Trying to replicate this but getting very inconsistent results, haven't seen the rotation bug as you described but I can see PendingClockInComponent and AutoOrientComponent sometimes don't get removed when the shuttle departs if you walked off, but only sometimes. Is this still occurring?

**Comment by metalgearsloth** [comment]
AutoOrient is really bad and disorienting still a year on.
