### ISSUE TITLE
Wheelchairs are airtight?

### ISSUE THREAD

**Issue by QuietlyWhisper** [space-wizards/space-station-14#19745]
## Description

I was playing salamander for a while, starting getting the oxygen loss icon, and poison damage. Turns out I was suffocating from my own co2 buildup.

**Comment by Slava0135** [comment]
same for unicycle
i think its related to the fact they both inherit from foldable/base item?
![image](https://github.com/space-wizards/space-station-14/assets/40753025/bb685b06-01bf-4a1f-9166-14f54cdd3827)

**Comment by Slava0135** [comment]
i think i also had this issue with a roller bed

**Comment by UbaserB** [comment]
This was fixed ages ago.
