### ISSUE TITLE
implanter sprite in medfab evil

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#19754]
## Description
its using the fill layer fsr

**Reproduction**
1. open medfab

**Screenshots**
![15:54:39](https://github.com/space-wizards/space-station-14/assets/39013340/81a56165-b329-419a-90ed-e8f396099013)

disclaimer saw on deltav it mightve been fixed here

**Comment by slarticodefast** [comment]
![grafik](https://github.com/user-attachments/assets/df8e324c-6d90-4fb3-bc4d-1f741b6c53eb)

This is fixed now.
