### ISSUE TITLE
Wheelchairs have no obtainable source

### ISSUE THREAD

**Issue by QuietlyWhisper** [space-wizards/space-station-14#19753]
## Description

They can't be crafted or bought, for example.

**Comment by lzk228** [comment]
#19625

**Comment by deltanedas** [comment]
bruh i was gonna do that

**Comment by Aisu9** [comment]
would be good if we could **craft** them, something something cargo never fulfilling medbay's requests

**Comment by deltanedas** [comment]
add humans to vim whitelist then boom upgraded wheelchair courtesy of sci

**Comment by Slava0135** [comment]
can be made in protolathe now
