### ISSUE TITLE
Lobby songs shouldn't loop

### ISSUE THREAD

**Issue by Flareguy** [space-wizards/space-station-14#19773]
## Description
None of them were designed to loop, so they usually get annoying very quickly after looping. This is also how it worked in SS13.

**Comment by Fildrance** [comment]
One of the problems are that server is sending info on what to play for clients, and lobby is avaialble for late joiners always, meaning that there always should be soundtrack name served. So options as they seem now
* server should always send off next song for the whole round
* client should pick some random song by itself! (will it affect admin music? dunno)
* server should send off 
* server should track how long is soundtrack and send changes on its expected completion (very bad idea, as people will join in different times and will hear only part of track). I'd say that sending to late-joiners current time of track is questionable, as it's going to create extra complexity
* client should receive song, play once, then just stop.
Latter seems like combination of most reasonable and easiest to implement!

**Comment by Flareguy** [comment]
Fixed by #25530
