### ISSUE TITLE
Toolbox contents are defined via component rather than yml

### ISSUE THREAD

**Issue by nuke-makes-games** [space-wizards/space-station-14#1978]
This probably applies to most container entities. Instead of using a custom component to fill the entity, there should be the ability to define their contents in yml using some sort of generic ContainerFillerComponent or somesuch.

If there's a need for some degree of randomizing the contents of a toolbox (ie. electrical toolboxes) then the ContainerFillerComponent could be given that ability too, so you can handle that in yml

**Comment by ShadowCommander** [comment]
We have `StorageFillComponent` for filling of containers that don't have randomized contents. For randomized contents we have other components.
