### ISSUE TITLE
Add names for all SMES and Substations

### ISSUE THREAD

**Issue by daerSeebaer** [space-wizards/space-station-14#19798]
## Description
On some maps, the SMES and Substations don't have names. This makes it harder for the Engineering crew, since they a) can't tell at a glance what section a substation provides for when examining it, and b) makes the Power Monitoring Console much less usefull because there is just a long list with SMESs and Substations without any indication which one is which.

On some maps this is already partially done, for example most Substations on Marathon have a name.

This should include a descriptive name for the "primary" SMESs in Engineering to differentiate them from accidentally unnamed ones.

**Reproduction**
1. Go to a Power Monitoring Console on Barratry
2. Have no clue whats going on

**Additional context**
Checklist: Check the box when for a given station all Substations and SMES have a name (list from the game files)

- [x] Aspid
- [x] Bagel
- [x] Barratry
- [x] Box
- [x] Cluster
- [ ] Core
- [x] Fland
- [x] Kettle
- [x] Marathon
- [x] Meta
- [x] Omega
- [x] Origin
- [x] Packed
- [x] Saltern

**Comment by deltanedas** [comment]
also a cool idea using multi on one with panel open to rename it with quick dialog

**Comment by deltanedas** [comment]
@daerSeebaer saltern was done already

**Comment by TsjipTsjip** [comment]
Kettle is also coming but currently has a PR open on it, so not touching it yet.

**Comment by JustCone14** [comment]
#20689
Packed names have been merged now too.

**Comment by JustCone14** [comment]
#20411
Origin has also now been update to include infra names.

**Comment by TsjipTsjip** [comment]
All PR's relating to this issue have been merged. The only map that has not been updated yet is Core, but as it's been derotated, this issue can be closed.

**Comment by daerSeebaer** [comment]
Great work, thanks to everyone who has contributed!
