### ISSUE TITLE
Movement of ghosts affected by ice

### ISSUE THREAD

**Issue by Owlexandeer** [space-wizards/space-station-14#19804]
## Description
Ghost movement is affected by ice. Ghosts should not slide since they float 👻 

**Reproduction**
Be a ghost, move over icy ground.

**Additional context**
Noticed when moving around the map as a ghost on a mining planet as a ghost.

**Comment by deltanedas** [comment]
i think theres a fix for any inair mobs which should include ghosts?

**Comment by mirrorcult** [comment]
yea this is fixed by #19707

**Comment by Owlexandeer** [comment]
To be fixed by https://github.com/space-wizards/space-station-14/pull/19707.
