### ISSUE TITLE
Empty container size is displayed as zero 

### ISSUE THREAD

**Issue by Slava0135** [space-wizards/space-station-14#19815]
## Description

When empty container is opened its size is displayed as 0/0

**Reproduction**

* Spawn an empty backpack
* Open
* See "Stored: 0/0"
* Put any item inside
* Now it shows correct info

**Screenshots**

![Peek 2023-09-04 14-49](https://github.com/space-wizards/space-station-14/assets/40753025/9b4d8f01-86ef-46ad-8178-a6a959f32678)

**Additional context**

**Comment by metalgearsloth** [comment]
It's storage not container, also dupe https://github.com/space-wizards/space-station-14/issues/19356

**Comment by Slava0135** [comment]
ah ok cool
