### ISSUE TITLE
Game server admin API

### ISSUE THREAD

**Issue by Chief-Engineer** [space-wizards/space-station-14#19853]
An API that makes certain server specific information and actions available. Needs to require some form of authentication.

This would allow for a way for things like banning someone on one server to kick them from other servers, or banning someone from SS14.Admin to kick them from servers. Also would allow a dashboard to be created to let admins see things like which servers currently have no admins.

# Available information

- [ ] Round number
- [ ] Connected players
- [ ] Active admins
- [ ] Active game rules
- [ ] Active game preset
- [ ] Active map
- [ ] MOTD
- [ ] Panic bunker status

# Available actions

- [ ] End/restart round
- [ ] Kick player
- [ ] Add/remove game rule
- [ ] Set game preset
- [ ] Set map
- [ ] Set MOTD
- [ ] Set panic bunker status

# Explicitly unavailable actions/information
This is stuff that probably shouldn't be done through the API since it can be done some other way, so it should probably not be available through the API

- Anything you can get from the database
  - Bans
  - Notes
  - Playtime
  - Logs
  - Permissions
- Anything you can do from the database
  - Ban
  - Note

**Comment by crazybrain23** [comment]
If we had an API, could we use it for cross server commiunication? That could be useful for vouchers and playtime proof.

**Comment by Simyon264** [comment]
Working on this

**Comment by VasilisThePikachu** [comment]
> If we had an API, could we use it for cross server commiunication? That could be useful for vouchers and playtime proof.

Federation in a nutshell
