### ISSUE TITLE
PDA and pockets without uniform

### ISSUE THREAD

**Issue by Tunguso4ka** [space-wizards/space-station-14#19854]
## Description

You can fulton the uniform on yourself and everything in pockets and PDA will stay with you.

**Reproduction**

1. Get fulton, get fulton beacon
2. Fulton your uniform

**Screenshots**

![зображення](https://github.com/space-wizards/space-station-14/assets/71643624/411bec99-35e8-4884-a6c4-486393798572)
![зображення](https://github.com/space-wizards/space-station-14/assets/71643624/b7f7cd6f-55f4-4eea-b6d9-7eb7a8b464b1)

**Additional context**

dont fulton your uniform, Snake.

**Comment by hord-brayden** [comment]
I think to extend this, since my recent issue doesn't really fit with the theme - You can fulton the items in your pockets (or storage implant) to a beacon as well. Bluespace C4 basically

**Comment by deltanedas** [comment]
bluespace syndicate bomb beacon when
