### ISSUE TITLE
Un/welding door plates welds door closed/open instead

### ISSUE THREAD

**Issue by Varen** [space-wizards/space-station-14#19865]
## Description
Cannot remove the plate that prevents hacking on security doors and the likes.
Much the same, in construction, the plate can be added but not welded.
**Reproduction**
Go to door with plate, such as a security door. Unscrew the door. You will be told by the examine menu to use a welder to remove the plate. Using a welder welds the door instead. Door cannot be hacked.

**Screenshots**
N/A

**Additional context**
Tested on Salamander.

**Comment by deltanedas** [comment]
probably the same cause as the other thing

**Comment by deltanedas** [comment]
not the same cause
