### ISSUE TITLE
Vim/Hamtr suffucate user

### ISSUE THREAD

**Issue by Varen** [space-wizards/space-station-14#19863]
## Description
Mouse/Hammy in Vim/Hamtr cannot breathe after a while.

**Reproduction**
Get in Vim/Hamtr as lil critter, wait a while, gasping begins.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by TsjipTsjip** [comment]
Pretty sure this was fixed already by #19140 .

**Comment by Varen** [comment]
This happens currently on Salamander, and that commit is in the changelog. I think what's happening is that the oxygen is running out in the first place, but I can't be sure.

**Comment by Myakot** [comment]
Am I missing something? Was it not meant to be so? That you have to strap an oxygen mask to your pet to pilot a mecha.
