### ISSUE TITLE
Crates can't be deconstructed

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#19874]
## Description
Crates can no longer be deconstructed.

**Reproduction**

1. Build or get a crate.
2. get a screwdriver.
3. try to disassemble with said screwdriver by left clicking.

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/47093363/87bddfdb-d296-4477-a11d-2a9cb25fd90c)
Just drops screwdriver.

**Additional context**
Tried rolling back commits several days to a day I knew it was working but still nothing.
Also tried to do the begin deconstruct from the menu too, no difference.

**Comment by Partmedia** [comment]
I bisected this issue and identified db1ff07821472cfca979254572473159473c6eef as the problematic commit (from PR #19809).
