### ISSUE TITLE
Ban note expires in time wrong

### ISSUE THREAD

**Issue by Chief-Engineer** [space-wizards/space-station-14#19897]
Ban notes list both the time the ban expires, and the time until they expire. The time until is incorrect. May affect other places where a countdown is used. I'm guessing this is related to timezones, but I'm not sure.

Appears to happen only on postgresql

People talking about in wizden ga-general https://discord.com/channels/310555209753690112/811324338099585036/1149416423031054476

**Comment by crazybrain23** [comment]
![image](https://github.com/space-wizards/space-station-14/assets/44417085/689e900b-6bb4-463f-ab96-03883d81b1d7)

**Comment by deltanedas** [comment]
god i love iso whatever timestamp instead of seconds since unix epoch utc :trollface:
