### ISSUE TITLE
The bar will be named "The Engine Change"

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/space-station-14#199]

**Comment by praisenarsie** [comment]
something needs to the reference the curse

**Comment by tentekal** [comment]
A drink at the bar that causes you to slowly vaporise

**Comment by SweptWasTaken** [comment]
![image](https://user-images.githubusercontent.com/49448379/82742117-5f951280-9d49-11ea-857e-9d2fb828d7e9.png)

Mission complete boys...
