### ISSUE TITLE
Taxis can be infected by zombies

### ISSUE THREAD

**Issue by IProduceWidgets** [space-wizards/space-station-14#19917]
## Description

Taxies can be infected by zombie virus and will take blunt damage, as well as gain the relevant zombie components such as TurnOnDeath. May also cause the rider to become a zombie.

**Reproduction**

Be taxi, get bit and infected, wait.

**Screenshots**

**Additional context**

**Comment by mirrorcult** [comment]
feature

**Comment by PixelTheKermit** [comment]
Computer virus

**Comment by deltanedas** [comment]
zombie chicken meta has been outdone
