### ISSUE TITLE
Fuel costs for repairing don't seem to be used... anywhere?

### ISSUE THREAD

**Issue by PixelTheKermit** [space-wizards/space-station-14#19916]
You know repairing stuff, right? There's a value for anything repairable titled "FuelCost". 
Now I'm not sure if it's intentional or not, but the value itself is never actually used.
It's probably existed for a while (or maybe a new thing?), but I'd still like to see the variable completely removed or the functionality of welding costs implemented.

That's all, thank you.

**Comment by LankLTE** [comment]
Was used as repairing stuff used to take a set amount of fuel before #17476 changed it to be just a set fuel usage per second

**Comment by PixelTheKermit** [comment]
> Was used as repairing stuff used to take a set amount of fuel before #17476 changed it to be just a set fuel usage per second

Ah, that makes sense. This probably means the value should be removed now though, right?

**Comment by deltanedas** [comment]
yeah its unused just remove it

**Comment by slarticodefast** [comment]
Fixed by #27030
