### ISSUE TITLE
Ghosts can remove fultons from objects.

### ISSUE THREAD

**Issue by Warentan** [space-wizards/space-station-14#19923]
Ghosts can remove fultons from objects.

**Reproduction**
Die
See an object with a fulton on it
Remove it

**Comment by AgentWatson** [comment]
This is to add-on to Warentan's report (Video by admin Skarlet) - Further testing done with ghost roles. It looks like other entities can also remove the Fulton. Basically anything with the ability to right-click and open the interactions menu can do this.
https://github.com/space-wizards/space-station-14/assets/137844976/effd267b-2345-4f0e-aa90-f503dd758b90

**Comment by UbaserB** [comment]
I have been able to do this as well
