### ISSUE TITLE
Double Agent for nukies... again

### ISSUE THREAD

**Issue by AjexRose** [space-wizards/space-station-14#19962]
## Description
So, its happening again, where a player will be selected for nuclear operative and nuclear agent, and as a result it sets the agent as catatonic. 
**Reproduction**
1. NukeOps game mode
2. Go to nukieplanet.yml
3. See players around
4. See 2 duplicate player models, one of which being a catatonic agent. 

**Screenshots**
**Additional context**

**Comment by Equivocateur** [comment]
Was the double strike team bug caught and fixed?
