### ISSUE TITLE
Airlocks with plasteel are unhackable

### ISSUE THREAD

**Issue by LordEclipse** [space-wizards/space-station-14#19963]
## Description
If you wanted to hack open a high-security door, or just any door with a plasteel plate embedded inside, its impossible as all you do is weld the door.

**Reproduction**
1. Open the door panel
2. Notice that plasteel is inside the door
3. Attempt to weld to remove the plasteel
4. Congratulations! You just weld the door shut instead.

**Screenshots**

https://github.com/space-wizards/space-station-14/assets/106132477/681be1ba-8487-457f-abe8-c43100a81c91

**Comment by chromiumboy** [comment]
Yep, this is the same bug as reported in #19865
