### ISSUE TITLE
Ninja can have a bomb arrivals objective

### ISSUE THREAD

**Issue by Chief-Engineer** [space-wizards/space-station-14#19974]
The bomb objective picks warp points and arrivals is often a warp point. Since warp point names aren't standardized, the best options for solutions are probably:
- create a new marker for "bombing objectives" to be manually mapped and use that, or
- do a range search for nearby arrivals airlocks and reject the warp point if it is too close (idk how close is too close, it should be conservative)

**Comment by deltanedas** [comment]
range search is bad bombing objective better

**Comment by deltanedas** [comment]
actually @Chief-Engineer what about a blacklist component to add to arrivals warp points, would be easier than giving everything but arrivals a whitelist component

**Comment by metalgearsloth** [comment]
> actually @Chief-Engineer what about a blacklist component to add to arrivals warp points, would be easier than giving everything but arrivals a whitelist component

no noob just make a new component for it.

For https://github.com/space-wizards/space-station-14/pull/19388 I already need to make new prototypes for beacons rather than just using warp points as is.

**Comment by deltanedas** [comment]
ok done just adding a few to saltern because saltern gaming :trollface:
