### ISSUE TITLE
alt-e on PDA drops it

### ISSUE THREAD

**Issue by Tunguso4ka** [space-wizards/space-station-14#19972]
## Description

Alt - E on PDA in card slot drops PDA and anchors it to the character.

**Screenshots**

https://github.com/space-wizards/space-station-14/assets/71643624/2c015dca-721b-4ef0-8acb-8854478065ce

**Comment by Fromoriss** [comment]
Also, guns don't work. If you try to shoot, gun will be anchored to character :/. Not lasers.

**Comment by Nuggletto** [comment]
wanna add, that the pda drops and sticks to your character even if you just remove your ID or pen from it

**Comment by metalgearsloth** [comment]
Temporarily resolved in https://github.com/space-wizards/space-station-14/pull/19975
