### ISSUE TITLE
Ghost role debug button broken

### ISSUE THREAD

**Issue by AjexRose** [space-wizards/space-station-14#19993]
## Description
Basically, if you try making a custom role for a event as a admin, the ghost role debug option doesnt work. 
**Reproduction**

1. Create a urist/vox
2. Enter debug settings
3. Select make ghostrole
4. Make it
5. Nothing shows up in ghost role menu
**Screenshots**

**Additional context**

N/A as far as I know.

**Comment by Tegotia** [comment]
I will say from player perspective, I did see the roles appear in the ghost roles menu, but I could not enter them (The 'Request' confirmation button did not work), and they disappeared after a while though I don't know if that was the admin uncreating them to try to fix or what

**Comment by LordEclipse** [comment]
> I will say from player perspective, I did see the roles appear in the ghost roles menu, but I could not enter them (The 'Request' confirmation button did not work), and they disappeared after a while though I don't know if that was the admin uncreating them to try to fix or what

That was me attempting to add the ghostrolecomponent through VV, it didn't work.

**Comment by LordEclipse** [comment]
Somehow I didn't see this, so I'll just add the video here-


https://github.com/space-wizards/space-station-14/assets/106132477/8c4b4b5c-6b51-45ac-8fa7-18b38bdb94a6
