### ISSUE TITLE
SSD icons are shown for devoured entities that can't be seen

### ISSUE THREAD

**Issue by DrSmugleaf** [space-wizards/space-station-14#20019]
## Description
It's not checking for the entity being visible/not inside a container.

**Reproduction**
- Spawn a dragon
- Control it
- Devour one of the Urists that aren't player controlled in dev map
- Icon

**Screenshots**
![Content Client_KK90kiLhB6](https://github.com/space-wizards/space-station-14/assets/10968691/575be292-db6f-4a41-be89-39bee1cf6a82)

**Comment by metalgearsloth** [comment]
Similar https://github.com/space-wizards/space-station-14/issues/20018

**Comment by CaptainSqrBeard** [comment]
This probably an issue to any container and sechud too.
