### ISSUE TITLE
You can fulton wall lockers.

### ISSUE THREAD

**Issue by IProduceWidgets** [space-wizards/space-station-14#20010]
## Description

You can use a fulton on the wall lockers. This is probably not intended.

**Reproduction**

Setup fulton beacon with linked fultons, attach balloon to wall locker on a wall, get inside, wait.

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/107586145/4ddeafe7-6b90-41cf-87b8-0a5cd04a562e)

**Additional context**

**Comment by GeorgeGimme** [comment]
this doesent seem bad?

**Comment by deltanedas** [comment]
it is bad
