### ISSUE TITLE
Need cycling airlocks from SS13

### ISSUE THREAD

**Issue by Flareguy** [space-wizards/space-station-14#20013]
## Description
We DO have logic gates for this, but they're hilariously easy to sabotage right now (you just need a wrench) and also slow, which makes them unreasonable to use in almost every place that isn't engi (arrivals and sec come to mind.)

Cycling airlocks should (probably?) be set up via device linking, and auto-close the opposing airlock. They should also probably wait until the opposing airlock is fully closed for it to work since otherwise it might result in some weirdness with monstermos cvars enabled (ripping tiles for like half a second since the airlock was open for that long.)

**Comment by Errant-4** [comment]
Aren't they already directly device-linkable? [14177]

**Comment by Flareguy** [comment]
Oh. I legitimately did not know that existed.
