### ISSUE TITLE
Welders and lighters get stuck on

### ISSUE THREAD

**Issue by IProduceWidgets** [space-wizards/space-station-14#20040]
## Description

Welders and lighters get stuck in the active state once turned on. They also do not use up fuel.

**Reproduction**

Turn welder/lighter on, attempt to turn welder off. Check fuel level and see it does not go down.

**Screenshots**

**Additional context**

May be related to issue #20011 Solution manager not working.

Also, the welders still function, they just cant be turned off. So its not the most pressing bug.

**Comment by TsjipTsjip** [comment]
This issue extends #20039 .

**Comment by chromiumboy** [comment]
[Here is the full error message when you try to turn off the welder](https://pastebin.com/rWNdX3QP)
