### ISSUE TITLE
Metamorphic glasses no longer change based on their contents.

### ISSUE THREAD

**Issue by IProduceWidgets** [space-wizards/space-station-14#20042]
## Description

Metamorphic glasses no longer change to the fancy respites when you fill them with the relevant solutions.

**Reproduction**

Fill metamorphic glass with 20u rum and 10u cola from a booze and soda dispenser. Note glass does not change to cuba libre glass.

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/107586145/c78223a1-a030-46e7-badd-bd72e1c2c432)

**Additional context**

**Comment by deltanedas** [comment]
dupe of something

**Comment by IProduceWidgets** [comment]
Oh youre right. I missed #19895.
