### ISSUE TITLE
A bunch of locale is brokie

### ISSUE THREAD

**Issue by VasilisThePikachu** [space-wizards/space-station-14#20047]
## Description

Easiest to repro is trying to put something in a bag that is full

**Reproduction**

1. Fill up a backpack
2. try to overfill it
3. Get program speak

**Screenshots**

**Additional context**

Caused since #20023

**Comment by DrSmugleaf** [comment]
That's not the pr that broke it, as unless I deleted the wrong localization line for backpacks everything else is automatically localized.

This was the pr that broke backpacks: https://github.com/space-wizards/space-station-14/pull/19682/files#diff-e840d1a58d490e31e3ece4c85e40608d8ada92e74b3c4eab37683e9299b69519R575

It is fixed now in https://github.com/space-wizards/space-station-14/pull/20049
