### ISSUE TITLE
Camera gets stuck on ATV / Secway when unbuckling

### ISSUE THREAD

**Issue by IProduceWidgets** [space-wizards/space-station-14#20046]
## Description

If you get on an ATV or Secway and then unbuckle your camera will stay locked to the vehicle. Also applies to janicart

**Reproduction**

Drag yourself onto an ATV, right click unbuckle, walk around.

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/107586145/97cfab42-4685-4096-85cc-c54b9c7fad72)

**Additional context**

Not an issue for beds or chairs.

**Comment by IProduceWidgets** [comment]
Okay, for some reason I thought that screenshot would make more sense.

**Comment by TsjipTsjip** [comment]
This bug seems to appear for all vehicles including wheelchairs.
