### ISSUE TITLE
AME still glows and bonks after running out of fuel

### ISSUE THREAD

**Issue by daerSeebaer** [space-wizards/space-station-14#20113]
## Description
After an AME has used the last fuel in a bottle, or is started with an empty bottle inserted, the cores still glow and it still makes the injection sound.

It should somehow indicate visually or audio wise if it ran out.

**Reproduction**
1. build an AME
2. insert a fuel jar
3. wait until it is empty

**Screenshots**
![grafik](https://github.com/space-wizards/space-station-14/assets/61566539/a973a70b-e868-4d31-9a4b-4a291ea9c9c3)

**Additional context**
For example, if it tries to inject fuel but can't due to there being no fuel left, it can just disable injections.

**Comment by deltanedas** [comment]
this is pretty confusing for new players

the bonk sound should be quieter when theres no fuel, like how its louder when being blown up

**Comment by RIKELOLDABOSS** [comment]
im trying to figure this out, but i cant find the ame bonk audio

**Comment by deltanedas** [comment]
`InjectSound` on `AmeControllerComponent`

**Comment by daerSeebaer** [comment]
> the bonk sound should be quieter when theres no fuel, like how its louder when being blown up

Why would it even make a sound after having no fuel left to inject?

My suggestion is to just shut down the AME when it tries to inject fuel but has nothing left:
- At least in my headcanon, the noise is the antimatter reacting inside the reactor. Too much antimatter - louder noise. No antimatter - no noise
- Programming-wise it would be really easy to implement since it just uses existing states of the AME
- Gamebalance-wise it could be argued if the AME running empty should be made more subtle than just being "off" or how clearly we want to communicate to players when the AME runs out. In my opinion, having no noise is actually the more subtle choice since a player with some experience can instantly recognize the AME state from the noise, but having no noise will only attract attention after some time.

**Comment by deltanedas** [comment]
ok yeah, maybe no noise for no fuel, quieter when underinjecting so anyone can tell when bozos doing 4 core 4 injection

**Comment by daerSeebaer** [comment]
Closed by #20458
