### ISSUE TITLE
Packpack stored size not update when spilt stack in backpack

### ISSUE THREAD

**Issue by iacore** [space-wizards/space-station-14#20126]
## Description

**Reproduction**

Let's say you put 30LV wires in backpack, split it in half. The stored size (backpack) would still be 30.

**Screenshots**

https://github.com/space-wizards/space-station-14/assets/74560659/5391c4f3-c8b7-4722-bccb-4084e1a80df4

**Additional context**
If you take anything out and put it back in, it's fixed.

**Comment by Plykiya** [comment]
grid inventory
