### ISSUE TITLE
Specism / lizard smite does not function

### ISSUE THREAD

**Issue by IProduceWidgets** [space-wizards/space-station-14#20125]
## Description

The specism / lizard smite does not function. Or, at least it does not work as intended.

**Reproduction**

Try to smite Urist for being a spacist, see that he is still Urist.

**Screenshots**

**Additional context**

**Comment by Hmeister-fake** [comment]
Note, it does apply the Reptilian speech verb but doesn't change the species at all. Also it does "something" because the person who gets smited drops their things and if you follow them as a ghost you get stuck in limbo with a copy of them
