### ISSUE TITLE
VVing the station id returned by stations:list causes an InvalidCastException

### ISSUE THREAD

**Issue by DrSmugleaf** [space-wizards/space-station-14#20133]
## Description

**Reproduction**
- Start the round
- Type `> stations:list` into the console
- vv the id returned by it
- Error in console and blank vv window

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/10968691/df14d856-5594-410c-be0e-95848d04c157)

![image](https://github.com/space-wizards/space-station-14/assets/10968691/e33fcea8-a052-4a48-9cdc-ac48872d0a4c)

![image](https://github.com/space-wizards/space-station-14/assets/10968691/ab86d8fd-6496-4c6b-aa62-4f1c43538360)

**Additional context**
Happened on round 33289.

**Comment by deltanedas** [comment]
might be similar to dumpentities returning wrong id for vving
