### ISSUE TITLE
The space cat suffocates in space

### ISSUE THREAD

**Issue by DrSmugleaf** [space-wizards/space-station-14#20152]
## Description
**Reproduction**
- Spawn a space cat, in space
- The space cat dies in space
- The space cat died in space

![image](https://github.com/space-wizards/space-station-14/assets/10968691/ae6909c5-1b8d-4d76-bf95-1d3b2a320f13)
space cat gasping in space

**Comment by KingOnBudget** [comment]
unplayable

**Comment by deltanedas** [comment]
space cat has no internals noob you need to give
