### ISSUE TITLE
You cannot go back to being a normal ghost as an admin ghost

### ISSUE THREAD

**Issue by DrSmugleaf** [space-wizards/space-station-14#20153]
## Description

**Reproduction**
- `aghost` in console
- `ghost` in console
- Permanently stuck with admin ghost privileges (unless you delete yourself or control a mob and then ghost)

![image](https://github.com/space-wizards/space-station-14/assets/10968691/e6eeb153-c862-4c91-a8f6-7cd3014d4624)

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/10968691/4d10afb5-295e-4d33-b0b0-fd404e3ea6c9)
![image](https://github.com/space-wizards/space-station-14/assets/10968691/d626a5c8-5bf1-4723-99c1-c73c5ee12070)
![image](https://github.com/space-wizards/space-station-14/assets/10968691/051a7671-94f2-4f1c-8b79-7791bc282912)
![image](https://github.com/space-wizards/space-station-14/assets/10968691/5af897c9-159d-4542-83e7-171e08f64f14)
![image](https://github.com/space-wizards/space-station-14/assets/10968691/e5a547df-651c-4fcd-bc03-2338a48ce77c)
![image](https://github.com/space-wizards/space-station-14/assets/10968691/569d506a-48af-4a90-a19f-a7063f1fcb95)

please

**Comment by nikthechampiongr** [comment]
Doing aghost again will not work if your previous body was deleted.
