### ISSUE TITLE
Zombies don't get anything for their role in the character menu

### ISSUE THREAD

**Issue by DrSmugleaf** [space-wizards/space-station-14#20160]
## Description
- Spawn
- Antag ctrl become zombie
- Nothing in C menu
![image](https://github.com/space-wizards/space-station-14/assets/10968691/3a90e63d-e39f-445e-ac5b-c3a32dee6737)

**Comment by deltanedas** [comment]
RoleBriefing would be good for this

**Comment by slarticodefast** [comment]
Fixed by #29259
