### ISSUE TITLE
Zombie doesn't get anything in chat for what they have become

### ISSUE THREAD

**Issue by DrSmugleaf** [space-wizards/space-station-14#20161]
## Description
- Become zombie
- You get nothing in chat about this
- Somehow traitor manages to get 13 paragraphs of text about the same situation

**Comment by EmoGarbage404** [comment]
They used to have a popup? Did it break?

**Comment by slarticodefast** [comment]
This is fixed now. An additional entry to the objectives menu was added in #29259
