### ISSUE TITLE
Syndicate bombs have weird and spammy logs

### ISSUE THREAD

**Issue by Chief-Engineer** [space-wizards/space-station-14#20188]
I didn't review the code so I can't provide a complete list, but wire cutting/pulsing shouldn't appear in explosion logs, especially when it isn't causing an explosion

![image](https://github.com/space-wizards/space-station-14/assets/119664036/071af78c-a43c-468c-9b5c-8a3909d26a2d)

countdown/timer logs are typically in the trigger log type, which syndicate bombs also use, but don't pass an actor to:
![image](https://github.com/space-wizards/space-station-14/assets/119664036/2d9cf131-cdb2-4411-87cf-909513ed91e5)

it also spams logs for the actual explosion. Here you see the generic explosion log, a seemingly unnecessary detonation log, and a second detonation log with an actor
![image](https://github.com/space-wizards/space-station-14/assets/119664036/ce2321be-3453-47c6-ba0a-a7e2b4510e54)

iirc the generic explosion log automatically logs the actor though a parameter in the method that actually causes explosions, all 3 of those logs should be collapsed into that. All wire cut/pulse logs should be in the WireHacking log type. Nothing should be spamming out multiple logs that duplicate information:
![image](https://github.com/space-wizards/space-station-14/assets/119664036/ceaa4f82-afcd-4265-871d-bb646c78313a)

**Comment by LankLTE** [comment]
I don't know exactly how admin logs work, so I'll ask some questions to clarify then work on fixing it:
Pulsing / cutting wires shouldn't log unless it's the explosion / defuse wire? Or not at all? Or moved to the WireHacking log type?
 
I believe the 3 explosion logs are the generic one that's automatically made (doesn't pass an actor), one that the system makes manually when the bomb goes off (also doesn't pass an actor, that'd be the second one in that image) and then one for pulsing / cutting the boom wire (which does pass an actor). Would removing the manual one just stating detonation / defuse with no actor work? 

I'm not certain why no actor is passed to the trigger log type- if this is added, should the "begun a countdown on training bomb" log be removed? 

Anything else I've missed that should be changed?
