### ISSUE TITLE
Extended telescopic shield glows in the dark

### ISSUE THREAD

**Issue by liltenhead** [space-wizards/space-station-14#20199]
## Description
It's fine when it isn't extended

**Screenshots**
![baetdr](https://github.com/space-wizards/space-station-14/assets/104418166/cd674f18-2e5d-4e6b-aa71-a3a19f69d56c)

**Comment by keronshb** [comment]
For a minute I was confused because the image has the e shield but then I saw it. Looks like a lighting issue.
