### ISSUE TITLE
aghosts can be sold

### ISSUE THREAD

**Issue by Chief-Engineer** [space-wizards/space-station-14#20206]
## Description

**Reproduction**

1. aghost
2. fly over a cargo pallet next to a sale computer
3. appraise

**Screenshots**

**Additional context**

**Comment by TurboTrackerss14** [comment]
H-how much are aghosts worth, asking for a qm main friend :)

**Comment by IProduceWidgets** [comment]
If you're unlucky, they're worth the whole station.
