### ISSUE TITLE
Players cannot "doorbump" 

### ISSUE THREAD

**Issue by TurboTrackerss14** [space-wizards/space-station-14#20207]
## Description

Players can no longer walk into a door to open it. and must actively click each door to open. 
What is stranger still is I see no recent change to this... also punpun and other animals can doorbump just fine.
**Reproduction**

**Screenshots**

**Additional context**

**Comment by deltanedas** [comment]
organic composition thing missing the DoorBumpOpener tag :trollface:

**Comment by arimah** [comment]
As far as I can tell, in #19859, BaseMobOrganic was split into BaseMobSpecies and BaseMobSpeciesOrganic, and the `Tag` component appears to have been forgotten about. I'm not sure if it should go on BaseMobSpecies or BaseMobSpeciesOrganic, but adding it to either seems to fix the problem. It previously had the tags CanPilot, FoostepSound and DoorBumpOpener.

**Comment by EmoGarbage404** [comment]
Put it in BaseMobSpecies
