### ISSUE TITLE
Make more Fields VV for easier debugging

### ISSUE THREAD

**Issue by exp111** [space-wizards/space-station-14#2020]
Some I miss are SpriteComponent, AppearanceComponent in the engine and StatusEffects in content. 
There are probably more missing…

Also some existing vv should be made editable

**Comment by Zumorica** [comment]
Should be as easy as slapping `[ViewVariables]` (for read-only access) or `[ViewVariables(VVAccess.ReadWrite)]` (for read and write access) on the relevant properties/fields.

**Comment by Erisfiregamer1** [comment]
this issue is as bad as 2020

**Comment by SweptWasTaken** [comment]
> 
> 
> this issue is as bad as 2020

Goodbye

**Comment by PaulRitter** [comment]
So this is kinda solved since we need to rethink the VV system anyways. I will open a new issue in place of this that tracks vv system progress (#4587)
