### ISSUE TITLE
Players cannot pilot shuttle consoles

### ISSUE THREAD

**Issue by IProduceWidgets** [space-wizards/space-station-14#20218]
## Description

Players are unable to pilot shuttle consoles. The UI doesn't open. This applies to the nukie shuttle as well as cargo.

**Reproduction**

Be a player character, try to pilot a shuttle, see that the UI doesn't open and that you cannot.

This happens for either clicking the console or using the Toggle UI verb.

**Screenshots**

**Additional context**

For some reason aghost can still pilot the shuttle.

**Comment by arimah** [comment]
This is fixed by #20216 :)
