### ISSUE TITLE
objectives ecs something smugleasf refactor

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#20239]
@deltanedas 

Apparently someone rolled syndie but didn't get objectives even after checking with lsobjectives.

**Comment by deltanedas** [comment]
log!!!!!!!!!!!!!!!!!!!!!

**Comment by metalgearsloth** [comment]
i'm GAMING

**Comment by deltanedas** [comment]
i was gaming too NOOB

**Comment by AJCM-git** [comment]
dupe

**Comment by deltanedas** [comment]
the other was the dupe :trollface:
