### ISSUE TITLE
Light replacer allegedly cannot go into janibelt. (Fear not, the light replacer actually does not care.)

### ISSUE THREAD

**Issue by Psychpsyo** [space-wizards/space-station-14#20232]
## Description
When trying to put the light replacer into a janibelt, it shows the error message saying that that doesn't go in there but then puts it in anyways. (as it should)

**Reproduction**
1. Open janibelt.
2. Grab light replacer.
3. Place light replacer in janibelt.
4. Observe that you are told off for your decisions.
5. Light replacer is in janibelt.

**Additional context**
I did some looking into it and the light replacer is the only thing that the janibelt whitelists via its component, not a tag.

**Comment by TurboTrackerss14** [comment]
This is part of an overarching issue with other nonstandard bags/containers.
The plantbag will also do this for every type of plant. 

repoduction:
place plant into plantbag (inserting by hand or using bag on the plant both work)
recieve "this doesnt fit there" message
plant still inserted. 

uncertain if this needs anouther issue post or this one renaming/formating to highlight other containers with the same issue.

**Comment by Psychpsyo** [comment]
This doesn't seem to happen anymore. Closing as fixed.
