### ISSUE TITLE
Syndies spawning with no objs

### ISSUE THREAD

**Issue by Skarletto** [space-wizards/space-station-14#20243]
## Description

Round 33465 on lizard, two syndicate agents were spawned without any objectives, while the other agents had objectives as expected

**Reproduction**

**Screenshots**

**Additional context**

**Comment by deltanedas** [comment]
log

**Comment by Skarletto** [comment]
hOW

**Comment by deltanedas** [comment]
probably fixed it whatever

**Comment by Skarletto** [comment]
pro

**Comment by deltanedas** [comment]
logs would still help to know whats actually causing it for sure :trollface:

**Comment by deltanedas** [comment]
> with no additional info

what objective did it say it was for...

**Comment by deltanedas** [comment]
right before it theres a debug log saying Created objective prototype (uid) show them too

**Comment by deltanedas** [comment]
not logged in debug real, anyway the new logging will say it so if it happens again it will say the prototype that failed requirements. if it doesnt make sense then its bad (e.g. cap not being able to get disk objective is normal)

**Comment by deltanedas** [comment]
if nothing else happens this can be closed

**Comment by Plykiya** [comment]
antag refactor is based?
