### ISSUE TITLE
crusher flashlight turns off when shooting

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#20247]
## Description
should either remove the flashlight, the shooting light effect, or make it support both at the same time

**Reproduction**
1. get crusher
2. use light action
3. wield
4. shoot
5. light off

**Screenshots**

https://github.com/space-wizards/space-station-14/assets/39013340/f5b33085-abb8-43f3-8a93-a73415b1bc24

**Comment by 0awful** [comment]
Should be closed per https://github.com/space-wizards/space-station-14/pull/22483
