### ISSUE TITLE
Station Records Info Not Showing Up

### ISSUE THREAD

**Issue by Kezu02** [space-wizards/space-station-14#20258]
## Description

Other than the names on the left, the Station Records computer does not give you any information on the station's crew.

**Reproduction**

Find a Station Records computer and click on anyone's name.

https://github.com/space-wizards/space-station-14/assets/143474299/3ca99011-badc-46a5-94b8-7e92ff5aabf8

**Comment by TurboTrackerss14** [comment]
Worth mentioning that the search function will infact still work and pullup assoiated records, which can then be selected at will.
