### ISSUE TITLE
spears bounty cannot be done

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#20269]
## Description

spears cannot be placed in a crate
**Reproduction**

**Screenshots**

**Additional context**

**Comment by deltanedas** [comment]
dupe of my one :trollface:

**Comment by lzk228** [comment]
> also for players, it can actually be done you just need to move it onto the shuttle then rotate it to 0 degrees and then itll fit because aabb is small enough

what

**Comment by deltanedas** [comment]
the aabb it uses for checking if it can fit in a crate is map aabb not grid aabb so when grid is rotated its too big
