### ISSUE TITLE
Nukie Declaration of War Not Working

### ISSUE THREAD

**Issue by Kezu02** [space-wizards/space-station-14#20282]
## Description

Trying to send a message through the declaration has no effect at all.

**Reproduction**

Use the item to send a message. I saw them attempt a war at round start so it shouldn't have been the 6 minute timer. The item was tested on both Lizard and Spider.
![image_2023-09-17_155010288](https://github.com/space-wizards/space-station-14/assets/143474299/f84eea4b-4bc4-4d19-b216-7eeabfb1ce37)

**Comment by LankLTE** [comment]
I’d need to know what message the Nukies got to look into it further- the message you got is because the entity (in this case, the aghost) isn’t a nukie and therefore can’t use the remote

**Comment by Kezu02** [comment]
Same things shows up for other entities.

![image](https://github.com/space-wizards/space-station-14/assets/143474299/aedda628-810c-416f-a754-6685c6fbc876)
