### ISSUE TITLE
borg rcd module can farm materials

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#20302]
## Description
its suffix admeme for a reason...

it should be normal rcd with lingering rcd ammo as another item

**Reproduction**
1. rcd module and advanced tool module
2. build walls
3. weld them
4. wait for recharge
5. repeat
6. infinite steel

**Comment by EmoGarbage404** [comment]
is a BLISTERING 8 steel per minute really a balance concern? You already need like 2 full stacks of steel + other assorted goods to even make a borg capable of using the RCD module.

**Comment by LankLTE** [comment]
Pretty sure you can do this with the normal RCD by having Sci print RCD ammo, this is so slow it's not an issue.

**Comment by deltanedas** [comment]
printing ammo has lower profit margins

**Comment by LankLTE** [comment]
> printing ammo has lower profit margins

And it also doesn’t have the upfront cost of a chassis (about 45 steel and glass) so

**Comment by deltanedas** [comment]
ok noobs wait until cargo mains hear about this
