### ISSUE TITLE
Turn OOC rules to IC rules for MRP

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#20323]
Instead of having a million lines of rules for specific jobs in main Rules.txt, there's should be:
- SOPs - IC "rules", duties, rights and prohibitions for every department. [Example](https://paradisestation.org/wiki/index.php?title=Standard_Operating_Procedure)
- Really MRP space law, that including violations of SOPs

feature request, holy shit, needs discussion labels

**Comment by LankLTE** [comment]
I’m not sure if you’re just saying to add to it, but MRP already has a SOP and Space Law

**Comment by metalgearsloth** [comment]
This sounds like HRP.
