### ISSUE TITLE
Backpacks should only be useable in hands

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#20341]
How it works in ss13, ss14 players coddled too much.

Just need slot flags implemented so belts and shit still work as before.

**Comment by mirrorcult** [comment]
this is not how it works in ss13

**Comment by metalgearsloth** [comment]
Was when I played in 2012.

**Comment by LordEclipse** [comment]
On what servers does it work like this? Doesn't work like this on goon, or /tg/ pretty sure (the only two I've played)

**Comment by Just-a-Unity-Dev** [comment]
> On what servers does it work like this? Doesn't work like this on goon, or /tg/ pretty sure (the only two I've played)

CM requires you to have a doafter to open your bag, but that's the closest thing to this

**Comment by mirrorcult** [comment]
> Was when I played in 2012.

ive been playing ss13 consistently on all sorts of servers since 2013 and ive never encountered anything close to this so you are either misremembering or this was removed more than a decade ago

**Comment by mirrorcult** [comment]
either way not a good basis to add anything just because it was in an ss13 server 11 years ago

**Comment by MrGreen006** [comment]
I really feel like this would be terrible for the game. Like why are we removing a very useful QoL feature? It doesn’t make sense to me

**Comment by deltanedas** [comment]
le evil powergamers being able to instantly take item out of container nested 6 levels deep inside satchel

**Comment by VasilisThePikachu** [comment]
This is not how it works in 13 and I don't want it to work like 13

**Comment by Carolyn3114** [comment]
this was never in ss13, even back in like 2010 lol

**Comment by Endecc** [comment]
I'm in awe. To start, the initial point for this implementation being "it's how it works in ss13" is one I've seen dismissed time and time again with "SS14 is its own game". It's a point I've seen YOU argue with, sloth.

Following it's existence in SS13 not even being true in current day, the clarification that it's based off of a **decade** old user experience is absolutely mindblowing.

I would think that if a mechanic hasn't been in circulation for over ten YEARS, it's something people agreed needed change and moved on from. It could be a relic from a 10-year-younger Byond being even more shit, with such a massive time gap.

I'm suggesting to pass on implementing an anti-qol feature like this. Especially with reasonings like this.

**Comment by GoodWheatley** [comment]
@metalgearsloth can you please provide a legitimate reason for how you think that this feature would improve gameplay

**Comment by keronshb** [comment]
No, I don't think they will.

**Comment by keronshb** [comment]
oops forgor close

**Comment by keronshb** [comment]
(Feel free to discuss since it still would require a lot of discussion, I just don't want anyone working on this and potentially wasting their time with a PR)

**Comment by lzk228** [comment]
i think it shouldnt be openable only if on back slot, so you can open it on floor, and in hand, but not on back

**Comment by keronshb** [comment]
> i think it shouldnt be openable only if on back slot, so you can open it on floor, and in hand, but not on back

Why? It's highly antiquated, even by video game standards. It's your inventory. Imagine if most modern games made you pause, take out a sack item (into your hand or onto the ground) to be able to get something from your inventory, then you need to pick it back up and re equip it? That's terrible design.

**Comment by lzk228** [comment]
so, then neither

**Comment by lzk228** [comment]
> It's your _**inventory**_

It's not a really inventory, backpack its a thing that exist as item in game, and you can even play without backpack

**Comment by keronshb** [comment]
> > It's your _**inventory**_
> 
> It's not a really inventory, backpack its a thing that exist as item in game, and you can even play without backpack

It's literally your inventory.

The clothes & items you wear is your equipment. So that would be the equivalent to an equipment screen on a game.
The backpack you have on your back is your inventory. While yes you can store 2 very small items in your pockets, that doesn't count as your personal inventory. Your backpack is what gives you your inventory. There is no way to argue this sanely.

**Comment by lzk228** [comment]
i played a lot rounds without a backpack and i feel great
belt and coat is enough for needed items for job, so i know what im saying
