### ISSUE TITLE
Syndie bomb keeps putting people in walls

### ISSUE THREAD

**Issue by nikthechampiongr** [space-wizards/space-station-14#20368]
## Description

The syndicate bomb keeps putting people in walls.

Not sure if this can be fixed, although I am making this issue just in case.
**Reproduction**

1) Go to 1 square wide hallway.
2) Buy bomb.
3) Become one with steel.
**Screenshots**

N/A
**Additional context**

N/A

**Comment by Warentan** [comment]
Happened to me, lost my botany round.

**Comment by keronshb** [comment]
Sounds like previous mime wall issues if it's a structure clipping people into walls.
