### ISSUE TITLE
Air Scrubber stacking on the same tile

### ISSUE THREAD

**Issue by AJimmyU** [space-wizards/space-station-14#20365]
## Description

It's become a recent(?) trend for atmos techs to stack tens of scrubbers onto one tile.

**Reproduction**

1. Build an air scrubber
2. Repeat step 1 on the same tile

**Screenshots**

**Additional context**

Is it desirable gameplay to fill every burn chamber tile with air scrubber? Perhaps thought should be put towards allowing less repetitive methods of capturing tritium from an active burn, like increasing scrubber performance so they can actually capture all tritium from a chamber reliably without having to be mindlessly spammed.

**Comment by Ilya246** [comment]
this is only being done because scrubbers are **absolutely terrible** at their job, they should be buffed at least like 10 times if they were to become unstackable

**Comment by slarticodefast** [comment]
Partially fixed by #28308 
You can still stack up to 4 scrubbers if they have different orientations.

**Comment by deltanedas** [comment]
you cant it has device stack check like a few other things

**Comment by slarticodefast** [comment]
>you cant it has device stack check like a few other things

Oh, you are right. I was using the spawn menu. With the crafting menu it is impossible now.
