### ISSUE TITLE
PAIs can have micro bomb implants

### ISSUE THREAD

**Issue by nikthechampiongr** [space-wizards/space-station-14#20378]
## Description

PAIs can have microbomb implants implanted into them and they can trigger them.
**Reproduction**

1) Be PAI
2) Have your owner implant you with a microbomb implant
3) Accidentally gib your owner
**Screenshots**

N/A
**Additional context**

N/A

**Comment by deltanedas** [comment]
dupe

**Comment by nikthechampiongr** [comment]
> dupe

Where? I did a quick search of pai issues before making this. Nothing about pai getting micro bombs.

**Comment by deltanedas** [comment]
same cause as #16900, not checking whitelist before implanting (afaik only dna scrambler has a whitelist)

**Comment by nikthechampiongr** [comment]
Ok then.
