### ISSUE TITLE
FPS arent updated accordingly in the debug monitor

### ISSUE THREAD

**Issue by AJCM-git** [space-wizards/space-station-14#2039]
They dont update go like a counter instead of update instantly (for example, if you drop form 40fps to 10fps the fps meter will slowly count down to 10 instead of update instantly)

**Comment by SweptWasTaken** [comment]
Still an issue, also the FPS counter should be an int not a float, nobody cares about decimal framerates.

**Comment by PJB3005** [comment]
FPS is averaged over the last 50 frames which seems pretty reasonable to me.

**Comment by SweptWasTaken** [comment]
https://github.com/space-wizards/RobustToolbox/commit/3bf851a6cfa9e0cfb573cefe00e31e12b5938ccf

No longer shows a decimal and think this is not really an issue.
