### ISSUE TITLE
Ahelp Overlay Not Showing Antags

### ISSUE THREAD

**Issue by Kezu02** [space-wizards/space-station-14#20404]
## Description

The sword icon to indicate antagonists does not appear in the overlay.

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/143474299/e6f67156-94d0-4c23-977f-ee77ca1ab647)

**Comment by Titian3** [comment]
This seems ok now, maybe we can close?
![image](https://github.com/space-wizards/space-station-14/assets/47093363/9e1c2c7b-72c2-45de-bc0f-ebbe084c0a89)
Was it right at round start? they might not have been delegated yet.

**Comment by deltanedas** [comment]
yes it will only mark them as antag once they have an antag role like traitor
and thats only added at X+Y time not roundstart (and it shouldnt matter since if you are being an antagonist before then its selfantag, so its an accurate readout)
