### ISSUE TITLE
Aghost lights bug.

### ISSUE THREAD

**Issue by Fromoriss** [space-wizards/space-station-14#20403]
## Description
Some strange with lamps, when aghost.

**Reproduction**
1. Go aghost.
2. Touch the light, which is powered.
3. Get burned.

**Screenshots**

https://github.com/space-wizards/space-station-14/assets/106442259/30c89827-b57f-4593-9610-e7c13085fc74

**Additional context**
You can't die, but can be burned? :/

**Comment by lzk228** [comment]
feature:trollface:
