### ISSUE TITLE
Fultons work on Sinks (power, and kitchen!)

### ISSUE THREAD

**Issue by hord-brayden** [space-wizards/space-station-14#20412]
## Description

Was messing around with fultons in a fork (frontier), and noticed that sinks are fulton-able. They are locked in place, once they fulton, however there's nothing to stop one from just using it again and again in order to move sinks to where they please.

Additionally - they work with power sinks (unanchored, of course). Funny how that works out

**Reproduction**

Deploy a beacon, find sink (power sink or kitchen sink), fulton it!

**Screenshots**

<img width="844" alt="Screenshot 2023-09-22 at 10 59 20 AM" src="https://github.com/space-wizards/space-station-14/assets/35241666/154cf12d-d681-41f6-8818-10ac5cba95a4">

**Additional context**

**Comment by hord-brayden** [comment]
I should probably rename this issue - also works on wall lockers of every time.

**Comment by deltanedas** [comment]
wall lockers is a dupe

fultoning unanchored powersinks is ok, actual sinks is not

**Comment by hord-brayden** [comment]
@del

> wall lockers is a dupe
> 
> fultoning unanchored powersinks is ok, actual sinks is not
> 
> theres also a bunch of stuff that should be fultonable but arent (pacmen, rtgs, smeses, substations)

It doesn't track that powersinks are fultonable when syndicate bombs are not. Once found/unanchored by NT staff, I thought one of the mechanics of the power sink was that it must be drug/stored properly, which takes time and creates a diversion. Fultoning it into the armory seems pretty lame. Mechanics aside, functionally it **is** messed up , since you can unanchor it - attach fulton - anchor it, and it will send to the beacon. So regardless if it's okay, it's still kinda buggy and weird.

I believe they send through in their initial state (unanchored) but it is possible to time a power-sink explosion completion to a beacon.

**Comment by deltanedas** [comment]
> one of the mechanics of the power sink was that it must be drug/stored properly

you can just pick it up since its an item

> unanchor it - attach fulton - anchor it

this seems like a thing that if you anchor a fultoned item it removes the fulton or pauses its countdown

**Comment by hord-brayden** [comment]
> > one of the mechanics of the power sink was that it must be drug/stored properly
> 
> you can just pick it up since its an item
> 
> > unanchor it - attach fulton - anchor it
> 
> this seems like it should be a thing that if you anchor a fultoned item it removes the fulton or pauses its countdown

My mistake, I did not know you could pick up a power sink!! Thanks for catching that
