### ISSUE TITLE
Gibbing a Body With the Emagged Recycler Respawns the Disk Somewhere Random

### ISSUE THREAD

**Issue by Kezu02** [space-wizards/space-station-14#20426]
## Description

After a captain was gibbed in an emagged recycler, the nuke disk respawned on a medical bed instead of being around the body. The CMO later was gibbed by the recycler, and the disk respawned in the janitor's closet.

**Reproduction**

Gib someone with the nuke disk in an emagged recycler.

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/143474299/886a02b3-1c2b-44e2-b08c-5a490db6d285)

**Comment by keronshb** [comment]
I'm pretty sure this is intended behavior if the recycler also gets rid of items on the person.

**Comment by deltanedas** [comment]
it doesnt it just leaves them on the floor

**Comment by dolgovmi** [comment]
> it doesnt it just leaves them on the floor

Not sure if fixed recently, but i think gibbing stopped dropping people's items (they disappear), so it may be related to the disk spawning somewhere else

**Comment by deltanedas** [comment]
possibly introduced by #20202 then, before that gibbing definitely dropped items

**Comment by EmoGarbage404** [comment]
gibbing has always destroyed all items? idk what you all are talking about.

**Comment by deltanedas** [comment]
no it definitely left items on the floor i recall a round where ~10 people fell into emagged recycler and all their pdas and what not were on the floor to identify them

also the new gibbing code has no rng placement of gibs they always spawn at the exact center

**Comment by HoidC** [comment]
> gibbing has always destroyed all items? idk what you all are talking about.

it dropped clothes and pdas and stuff before

**Comment by keronshb** [comment]
> gibbing has always destroyed all items? idk what you all are talking about.

I think electro said they fixed a gibbing issue and then there was another fix put out for it right after so maybe those changes caused this?

IIRC the gibbing API has a bool to prevent item deletion and another bool to prevent organ deletion.
