### ISSUE TITLE
Gibbing causes organ duplication and victim loses access to their brain

### ISSUE THREAD

**Issue by TsjipTsjip** [space-wizards/space-station-14#20425]
## Description

Originally this issue was posted around the syndicate bomb, but this issue extends to any form of gibbing. If you get gibbed, organs duplicate and you cannot re-enter your brain.

If the brain is slotted into an MMI, it is "dead". (No eyes, borg equivalent of yellow lights.)

**Reproduction**

Reproduction steps used in the clip below:
1. Gib yourself in any way. Easiest being the gibber stick.
2. Observe how you can no longer re-enter your body.

**Screenshots**

https://github.com/space-wizards/space-station-14/assets/19798667/91fe5b34-6cf3-4640-b3f2-09cb28b48836

**Additional context**

n/a

**Comment by dolgovmi** [comment]
Gibbing in any way does the organ duplication, people's items they have on them disappear upon being gibbed too (PDA, nuke disk, clothing, bags, etc).

**Comment by TsjipTsjip** [comment]
> Gibbing in any way does the organ duplication, people's items they have on them disappear upon being gibbed too (PDA, nuke disk, clothing, bags, etc).

Issue edited to match this root cause.
