### ISSUE TITLE
Late Start Wheelchairbound Characters Stay Paralyzed When Picking Cyborg

### ISSUE THREAD

**Issue by Kezu02** [space-wizards/space-station-14#20428]
## Description

Any late round players who currently have a wheelchair bound character selected will remain paralyzed despite choosing the cyborg role. It could easily be avoided by switching to another character, but every now and then there's a player who forgets or didn't know about it.

**Comment by LankLTE** [comment]
This is an issue with every trait- mute latejoin cyborgs can't speak, etc.
