### ISSUE TITLE
Nitrus Oxide (NO2) no longer makes you sleep.

### ISSUE THREAD

**Issue by IProduceWidgets** [space-wizards/space-station-14#20449]
## Description

Nitrus Oxide (NO2) no longer makes you sleep. Whether in atmos, or in a gas tank, it just makes you laugh and suffocate.

**Reproduction**

Have lungs, breathe NO2, see that you are still awake.

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/107586145/a91f8c90-2dca-4943-be04-1eb884d2211e)

**Additional context**

**Comment by deltanedas** [comment]
likely same cause as #20434
