### ISSUE TITLE
Bowl needs to be opened before pouring liquid

### ISSUE THREAD

**Issue by dahnte** [space-wizards/space-station-14#20452]
## Description

Bowls need to be "opened" before pouring something into them.

**Reproduction**

- Grab an empty bowl
- Try to fill it with liquid/flour/rice
- Click/'Z' on bowl and then you can pour liquid into it

**Screenshots**

![Bowl](https://github.com/space-wizards/space-station-14/assets/70238020/88d13a02-53fb-4af3-8832-cab47784a931)

**Comment by deltanedas** [comment]
why is bowl parent sus...
