### ISSUE TITLE
deleteentity and adjstationjob been broken for a month and nobody notice

### ISSUE THREAD

**Issue by nopeingeneer** [space-wizards/space-station-14#20461]
Issue in title

**Comment by metalgearsloth** [comment]
Could you elaborate on what "deleteentity" means in context

**Comment by nopeingeneer** [comment]
command deleteentity deletes a role from station manifest.
It helpfull when you need depart some deleted bodys from station manifest

**Comment by crazybrain23** [comment]
`adjstationjob` has been moved to the toolshed equivalent `station:get jobs:job <job id> jobs:adjust <amount>`

**Comment by nopeingeneer** [comment]
> `adjstationjob` has been moved to the toolshed equivalent `station:get jobs:job <job id> jobs:adjust <amount>`

![image](https://github.com/space-wizards/space-station-14/assets/140444677/ff58ae17-8601-4b71-8f27-4e4a27e44e0d)

**Comment by crazybrain23** [comment]
> > `adjstationjob` has been moved to the toolshed equivalent `station:get jobs:job <job id> jobs:adjust <amount>`
> 
> ![image](https://user-images.githubusercontent.com/140444677/270164109-ff58ae17-8601-4b71-8f27-4e4a27e44e0d.png)

You need to start the command with `> ` to use toolshed.

**Comment by nopeingeneer** [comment]
> station:get jobs:job <job id> jobs:adjust <amount>

what about deleting man from manifest?

**Comment by moonheart08** [comment]
deleteentity just deletes an entity, it has nothing to do with the manifest.
