### ISSUE TITLE
Player-built shuttles not working correctly

### ISSUE THREAD

**Issue by Doru991** [space-wizards/space-station-14#20462]
## Description

When building a shuttle from scratch, in some cases it seems unable to move around as intended. When commanding the shuttle and pressing movement keys, the thrusters will appear to activate as intended but the shuttle won't actually move through space.

Reproduced both locally and on an official server (Lizard)

**Reproduction**

* Place down some rods in space, and add all the required components for a shuttle (console, gyro, thrusters, power source)
* Use the console and try to move the shuttle
* Expected behavior would be the shuttle moving, but it will remain in place

**Comment by Doru991** [comment]
Update: This appears to happen most often when the shuttle only has 2 available thrust directions

**Comment by deltanedas** [comment]
can reproduce:
1. load shittle
2. move around fine
3. delete north thruster
4. cant move

**Comment by Doru991** [comment]
I don't think thats normal
![image](https://github.com/space-wizards/space-station-14/assets/75124791/c19c4a33-cf19-4036-8cbd-856576907d06)
