### ISSUE TITLE
Replay feature request (The Trailer Park)

### ISSUE THREAD

**Issue by EmoGarbage404** [space-wizards/space-station-14#20478]
## Description

from the sacred mouth of bobda

- [ ] An easy way to tell what round number it is during a round as both a player and an admin, bonus points for it telling you round length too
- [ ] 16:9 viewport in replays
- [ ] hiding your ghost and other ghosts in replays
- [ ] lighting to not die when the camera is zoomed out slightly
- [ ] fast forward

**Comment by ElectroJr** [comment]
Merging this into #17170
