### ISSUE TITLE
Ghosts loose all their actions when using the "Ghost Role" menu to follow a mob.

### ISSUE THREAD

**Issue by NancokPS2** [space-wizards/space-station-14#20483]
## Description
All the 4 usual actions dissapear from both the quick action bar and the action menu.

**Reproduction**

- Join as Observer  
- Press "Follow" on any mob in the "Ghost Role" menu (in this case it was a salvage wreck Tick, but it doesn't seem to matter which mob is chosen so far)  
- All actions dissapear.

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/55665720/7d340141-b8f8-4b18-96c2-1fef8d3f3099)

**Additional context**
Only tested as late Observer join so far.

**Comment by NancokPS2** [comment]
Update: using command /resetallents fixes it.

**Comment by metalgearsloth** [comment]
Does anyone still get this

**Comment by crazybrain23** [comment]
> Does anyone still get this

I do sometimes, it doesn't consistent when it happens, but I get it sometimes, especially when teleporting to different maps/grids 

VV of my Client and Server Actions when they disappear:
![image](https://github.com/space-wizards/space-station-14/assets/44417085/58fc5073-b667-4b20-819a-d3af0f4797d0) ![image](https://github.com/space-wizards/space-station-14/assets/44417085/34f0a983-33e5-4d4c-aecf-d1feb1f3ccac)

Same as above but after `resetallents`
![image](https://github.com/space-wizards/space-station-14/assets/44417085/9c652ff1-d5ca-4219-97cc-d4303ab58427)
![image](https://github.com/space-wizards/space-station-14/assets/44417085/4e1cd76f-eb23-4bb8-ac55-e9e4ae15287a)

**Comment by metalgearsloth** [comment]
Need logs and timestamp of when it happens.

**Comment by metalgearsloth** [comment]
Actions state handling is being odd as somehow the entities aren't being updated correctly as the containers are still fine though it's not clear if this is due to prediction or the likes (e.g. specific actions only added in specific scenarios).

I also can't repro this locally or on live so one of the people who can needs to discern what's different.

**Comment by deltanedas** [comment]
i have never seen this locally just live, but it still happens to this day

**Comment by metalgearsloth** [comment]
I tracked it down with a debugger on live it's the action entities getting pvs detached and actionscontainer has no handling for when they get streamed back in.

**Comment by MACMAN2003** [comment]
this happens to non-ghosts, and something i've noticed is that it happens mostly when the power randomly flickers and when the evac shuttle docks to the station
