### ISSUE TITLE
Fire extinguisher needs refactoring

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#20497]
Whenever we get a generic itemtoggle component fire extinguisher should also be on the chopping block. It's just spray + item toggle.

**Comment by alwinnocom** [comment]
https://github.com/space-wizards/space-station-14/pull/21942/files

**Comment by alwinnocom** [comment]
https://github.com/space-wizards/space-station-14/pull/21972 I included a refactor.

**Comment by slarticodefast** [comment]
It uses a proper item toggle component now.
![grafik](https://github.com/user-attachments/assets/011728f8-b9d9-43b7-965d-c9c0da2f02f3)

FireExtinguisherSystem has been removed.
