### ISSUE TITLE
Every form of sleeping doesn't work

### ISSUE THREAD

**Issue by SinisterSamtaro94** [space-wizards/space-station-14#20527]
## Description
If you use the sleep button on a bed it doesnt work, if you are a narcolept you don't randomly fall asleep, if you try drugging yourself with chloralhydrate to sleep it wont put you to sleep and instead gives you only the debuff

**Reproduction**
test in any round.

**Comment by daerSeebaer** [comment]
Related issues: #20434 , #20449 , #20466 

Probably a common cause

**Comment by gusxyz** [comment]
should be fixed with #20514
