### ISSUE TITLE
Replays have stopped

### ISSUE THREAD

**Issue by nikthechampiongr** [space-wizards/space-station-14#20525]
## Description

Replays have stopped being posted on https://cdn.centcomm.spacestation14.com/replays/.
**Reproduction**

1) Be disappointed that replays stopped like 2 days ago.
**Screenshots**

N/A
**Additional context**

N/A

**Comment by Mirino97** [comment]
Probably related to this error message I saw showing up a few times yesterday?

I guess it could also be related to rounds stalling? Cuz I noticed the error only on stalled rounds, but I could be very wrong.
![replayerror](https://github.com/space-wizards/space-station-14/assets/52474532/e941c9d8-587d-439e-901e-268897f2f724)

**Comment by Veritius** [comment]
@PJB3005

**Comment by nikthechampiongr** [comment]
Yea this seems to have been fixed.
