### ISSUE TITLE
Lizard tail sprites clip over magboot sprites

### ISSUE THREAD

**Issue by DrSmugleaf** [space-wizards/space-station-14#20543]
## Description
**Reproduction**
- Spawn as a lizard
- Have a tail
- Equip magboots
- 
**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/10968691/e55a7427-ea08-4b02-b14a-b43d7ceb67a9)

**Comment by lzk228** [comment]
what if make tails a body parts?

**Comment by PixelTheKermit** [comment]
> what if make tails a body parts?

This will most likely not fix that.

**Comment by UbaserB** [comment]
dupe of #15132
