### ISSUE TITLE
not dead creatures should be able to get out of closed body bag

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#20554]
title

**Comment by notquitehadouken** [comment]
well the zipper is on the outside of the body bag

**Comment by deltanedas** [comment]
you can get out of a welded crate with a doafter

**Comment by notquitehadouken** [comment]
busy reusing ResistLockerSystem for this

**Comment by notquitehadouken** [comment]
they already can

**Comment by MilenVolf** [comment]
This issue should be closed, 'cause you can easily get out of the body bag.
