### ISSUE TITLE
Chemical dipped spears are overpowered

### ISSUE THREAD

**Issue by AJimmyU** [space-wizards/space-station-14#20580]
## Description

Chemical dipped spears are an easily made and spammable weapon that ignores armor and deals near permanent damage (toxin) that can't be healed without a medbay visit. It's a ranged hypospray.

**Reproduction**

1. Craft a spear
2. Counter nuclear operatives with a glass shard on a rod

**Screenshots**

**Additional context**

Strong weapons shouldn't be so accessible.

**Comment by Aisu9** [comment]
Cult have an idea to balance this, make injection embed time dependant (so if you take time to remove the arrow or spear you wont have much in ya)

**Comment by deltanedas** [comment]
wouldnt help for licoxide but would for 5u amatoxin arrows

**Comment by drteaspoon420** [comment]
Possibly reduce the spear/arrow solution amount slightly.
To be honest I believe the 'power level' of spears and arrows is heavyly overrated.
Yes, you can make them powerful. But:
- If you miss, you lose your weapon for current fight.
- If you hit, you lose your weapon for next fight (nukies work as a team so good luck with that)
- Travel time is relatively slow so it's easier to hit your team mates.
- You can only carry maximum of 3 spears, two occupy your hands and one your back (rarly optimal to use back slot for a spear).
- Arrows are such a pain to reload that they are irrelevant in most fights.
Over all, sec providing weapons when nukies declare war ops is much more effective.
Even though spears are not contraband, I would still want to check bags for toxins if I spot someone carrying around a spear when no threat to a station is announced.

**Comment by hord-brayden** [comment]
Pneumatic cannons push arrows over the edge, for me. You can fit 3, it's full auto, and the hotkey dance is much simpler than with a bow.

If you have arrows laced with toxins, it's pretty good.. if you have time to prep, 3 arrows per operative, and you don't need to wield the cannon.

**Comment by drteaspoon420** [comment]
wait... you can put them in pneumatic cannons?

**Comment by KingOnBudget** [comment]
> wait... you can put them in pneumatic cannons?

spears are too big to fit in those. Cannons are glorified throws anyways.

**Comment by hord-brayden** [comment]
> wait... you can put them in pneumatic cannons?

Yeah spears are 90, cannons hold 30. I was referencing the arrows though, not spears. The 'glorified throw' of the cannon still passes the threshold for arrows (glass shard and standard) to be interpreted as being at a high enough speed to consider it a projectile and apply all relevant damage and solution injection. Throwing it by hand doesn't pass that check. I'm assuming the same would be true of ninja stars (which are meant to be thrown as well), but those really wouldn't be abusable since they're so rare. Bolas, stun batons, etc.
