### ISSUE TITLE
Instaflushing needs a longer doafter

### ISSUE THREAD

**Issue by Eden077** [space-wizards/space-station-14#20609]
Instaflushing is being used to instagib people due to the emagged recycler, I personally believe that a longer doafter would stop the recycler from just being an 8 TC perma kill machine.

**Comment by LankLTE** [comment]
I think nerfing the recycler is a more interesting option- “instaflushing” is a lot of fun in other scenarios imo

**Comment by Keikiru** [comment]
The relevant Discord discussion thread:
https://discord.com/channels/310555209753690112/1156712857430413343

**Comment by Just-a-Unity-Dev** [comment]
isn't instaflushing a bug in itself?
