### ISSUE TITLE
Dropped items via clothing removal stick to secway

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#20629]
## Description
As the title says, If you remove your clothes while on a secway then the items in the pocket attach to the secway rather than to the floor.

**Reproduction**

1. Put some items in your pockets
2. Get on secway
3. Remove clothing that contains pockets
4. Observe items stuck to secway.

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/47093363/a465b457-24a5-4bfc-a31c-5c7d1366683f)

**Additional context**
Pretty low key issue, can still pick up items off secway, just looks a bit shit.

**Comment by Kromabae** [comment]
hey that's me, can confirm this is funny
