### ISSUE TITLE
Can't remove plasteel panel from door wiring

### ISSUE THREAD

**Issue by dolgovmi** [space-wizards/space-station-14#20636]
## Description
You can't remove the plasteel panel on door wiring because you can't perform the crowbar step.

**Reproduction**
1. Get a door with a plasteel panel, open up the panel
2. Weld it, then try to crowbar it
3. Get stuck at the crowbar step
4. Cry

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/96251346/d87f6dfe-955d-4515-b5bb-491f2696712c)

**Comment by deltanedas** [comment]
maybe caused by prying refactor

**Comment by chromiumboy** [comment]
This issur should be closed by #20664

**Comment by LankLTE** [comment]
ok
