### ISSUE TITLE
Cognizine does not work

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#20631]
## Description
Pretty simple cognizine doesn't work. Tried higher volumes 5,10,15u and no ghost role. Tested with Lisa, Morty and paperwork.

**Reproduction**
1. Inject or alter the solutions on animal/pet.
2. Check ghost role to see it didn't work.

**Screenshots**
N/A

**Additional context**
Been a while since I seen a sentient animal so probably broken a while.

**Comment by deltanedas** [comment]
might be caused by #19951

**Comment by deltanedas** [comment]
![15:40:36](https://github.com/space-wizards/space-station-14/assets/39013340/864ac813-2106-4eec-a355-cde9593fc658)

yep the mindcontainer check was evil since all mobs have it now
