### ISSUE TITLE
Kettle station has no roundstart borgs

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#20649]
## Description
On kettle station there are no roundstart borg options available.

Toggleing admin Shows Spawns reveals no borg spawns in science.

**Additional context**
Unless borgs spawn outside of science and something happend to the borgs, this is the second time ive seen no borgs available in Kettle station early into the round.

**Comment by LankLTE** [comment]
This is just them never being added. There aren't any spawners and there aren't any roles defined in the prototype.

**Comment by TsjipTsjip** [comment]
Self-assigning this, will PR this in soon.

**Comment by lzk228** [comment]
solved
