### ISSUE TITLE
closet skeleton bricks the game

### ISSUE THREAD

**Issue by JoeHammad1844** [space-wizards/space-station-14#20646]
## Description

I took a closet skeleton ghost role and was just put in a black void and i cant do anything anymore, i cant even ghost warp to anywhere else, the space music also starts playing

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/130668733/f4556c66-7db5-49b6-91b4-f93981e795b3)
![image](https://github.com/space-wizards/space-station-14/assets/130668733/05514772-2e1b-4142-a32f-93e2e091d150)

**Comment by Kayek14** [comment]
I think this is related to https://github.com/space-wizards/space-station-14/issues/20607#issue-1919822398
