### ISSUE TITLE
Role bans don't appear in adminremarks

### ISSUE THREAD

**Issue by Chief-Engineer** [space-wizards/space-station-14#20645]
Haven't personally verified it, but I think this is the 2nd time I've heard of it. Iirc, both role bans and game bans can have a hidden flag set, unless that flag is set they should be visible in `adminremarks` imo (assuming the cvar is enabled to let players see their notes)

**Comment by LankLTE** [comment]
#20388 should have fixed this- can you confirm this is still the case?

**Comment by LankLTE** [comment]
Wait nevermind this is something else- my bad
