### ISSUE TITLE
Game extremely dark

### ISSUE THREAD

**Issue by Warentan** [space-wizards/space-station-14#20644]
## Description
For whatever reason, my game has become the newest Dark Souls episode.

**Screenshots**
![Screenshot from 2023-09-30 19-59-18](https://github.com/space-wizards/space-station-14/assets/113652968/ca1c6daa-cb6e-4908-b368-f55c791f0ede)

**Additional context**
Ubuntu 22.04. I have already tried reinstalling.

**Comment by metalgearsloth** [comment]
How did compatibility mode go

**Comment by Warentan** [comment]
> How did compatibility mode go

Apparently compatibility mode WAS the issue. Turned it off and it works just fine.
