### ISSUE TITLE
Other players can see the floating text message when you emag something

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#20641]
## Description
When you emag a door a message pops above your head *The card zaps something in the airlock*. Everyone else can see the same message.

**Screenshots**
 
Zapping an airlock:
![image](https://github.com/space-wizards/space-station-14/assets/106507028/b2ac3062-40e5-4dfd-b612-adf7168e4f38)

**Additional context**
This is a problem because it can artifically give away the player using the emag. 
There are already physical clues that someone is using the emag:

1. The emag is held in your hand(might be another issue because the emag currently has no in hand sprite).
2. There is an audible zap and buzz when the emag is used.
3. The airlock lights up and then goes dark before opening.

Players should have to be aware and specifically looking for this happening if they want to catch someone using an emag. The blatent *The card zaps something in the airlock* is artfical and very easy to spot even if you are not looking for it.

emags are supposed to be a stealth option, having a large amount of text float above your head for a few seconds is anything but stealthy and offputting.

Open to sugestions and opinions!

**Comment by notquitehadouken** [comment]
good idea will pr

**Comment by deltanedas** [comment]
other players cant see the message, tested on #20725 branch but that just passes type so doesnt matter

emagger pov
![16:05:05](https://github.com/space-wizards/space-station-14/assets/39013340/6f598846-0397-4fe7-af18-4c3007f95332)

other pov
![16:06:42](https://github.com/space-wizards/space-station-14/assets/39013340/31ec8f12-c3cb-4568-87be-06df94f0e6b5)

**Comment by Kayek14** [comment]
This was an error on my part then. I assumed that everyone else could see the text popup, since everyone can see other popups such as spilling and building messages, and assumed it was the same. I neglected to test it with two different accounts and just switched over to a new body when i did the testing. Glad to hear it is working as intended!

**Comment by deltanedas** [comment]
ok so close it :trollface:
