### ISSUE TITLE
Heat/Cold status effect

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#2065]
Heat/Cold doesn't currently have a status effect like pressure does.
This causes confusion when you die of heat/cold.

**Comment by SonerSound** [comment]
Hello there, I wanna start contributing to this game! I'll pick this one up if nobody's got an issue with that :D

**Comment by Zumorica** [comment]
I apologize, in the end I ended up doing this myself in a PR :cold_sweat:
