### ISSUE TITLE
Disposal Bin Doafter Suggested Changes

### ISSUE THREAD

**Issue by PursuitInAshes** [space-wizards/space-station-14#20666]
Foreword: This isn't exactly an "issue", I just think its time for the discussion to move to a more organized place.

## Description
The original problem of the emag'd recycler instantly gibbing was brought up, but the discussion shifted to fixes that wouldn't involve changing the emag recycler mechanics directly. Here is what people seem to have settled on:

1) Trying to shove people into the disposal bin, while they are alive, should give them a notification. (Similar to when someone tries to take/strip something off of you.)

2) The doafter for putting alive people into the disposal bin, should be extended slightly, to where it is still possible to flush people, but not "instant" as some described it.

## Personal Opinion
I think both of these changes would help the issue that was brought up, extending the doafter to be closer to 1.2 seconds might be enough where its feasible that some people could react, but not everyone, so flushing unsuspecting people is still possible.

This isn't a bad way (IMO) of going about fixing the originally discussed issue, at least for a little bit to test and go from there.

**Comment by notquitehadouken** [comment]
will do
