### ISSUE TITLE
Cable coils weigh too much.

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#20668]
## Description
One cable weighs 1 unit. A stack weighs 30. This is equivilent to an entire stack of steel. It dosent make sense that a stack of cables weigh as much as a stack of solid steel. 

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/106507028/04fa94a6-3dfc-4c6a-877a-a8a6beadfc04)

**Additional context**
Since there are three types of coils, it seems reasonable to reduce the weight to 1/3 of the current value, that way it is easier to carry around some of every type of cable without breaking your back in the process.

its already bad enough that solid materials take one unit for each item. Cables taking the same space make it very frusterating for engineer's inventory management.

**Comment by NancokPS2** [comment]
This was asked in discord like a month ago, it is intentional for balance reasons.  
It reduces how easy it is for engineers to have everything in hand to fix whatever they find.

**Comment by deltanedas** [comment]
what is nonsense is tiles are 5 space per tile, but take 0.25 space of steel to make

**Comment by Kayek14** [comment]
Closing this since it was an intentional balance change.
