### ISSUE TITLE
Cyborgs do not lose battery power over time

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#20696]
## Description
I was in a round as a cyborg and my power level never went below 100% the entire time.

**Additional context**
I was not using any headlamp for the entire round. Borgs should still have a innate power draw for being active.

**Comment by Doru991** [comment]
That's odd, just earlier today I played a round and my battery was similarly seemingly stuck at 100%, but after doing... something(?) it started going down as usual

**Comment by Doru991** [comment]
Alright I see a bug happening, I think I can get to the bottom of this tomorrow if nobody else does

**Comment by Kayek14** [comment]
Just discovered that i was losing power over time while sitting in a cyborg charger. After re-entering it and charging back to full i never lost power again.

**Comment by Doru991** [comment]
After some debugging, the bug is actually weirder than I thought. It's calling a method that should normally be called when the battery is removed whenever you select/unselect a module, but I can't figure out why

**Comment by Kayek14** [comment]
Resolved.
