### ISSUE TITLE
RGB colors are solid black

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#20698]
## Description
RGB bees and emaged eswords are a solid blackd

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/106507028/55922de6-a29a-403d-a09e-9bbf038172da)

**Comment by Titian3** [comment]
Thought for sure this was intentional with the saber, like Mandalorian.
Bonus points for keeping the black color on the saber?
![image](https://github.com/space-wizards/space-station-14/assets/47093363/b6e73e95-c4d0-4571-a718-f28d0bf9c269)

**Comment by Eden077** [comment]
Yeah the e-sword is metal as fuck

**Comment by lzk228** [comment]
it should have been fixed in #20263

**Comment by CatMagic1** [comment]
Didn't know you could even emag eswords.

But that glitched sword does in fact look sick as hell.

**Comment by notquitehadouken** [comment]
> Didn't know you could even emag eswords.

wait, you can? what does that even _do_?

**Comment by CatMagic1** [comment]
> > Didn't know you could even emag eswords.
> 
> wait, you can? what does that even _do_?

I'm assuming it makes them rainbow, but according to this post that is not working.

**Comment by ElectroJr** [comment]
> it should have been fixed in https://github.com/space-wizards/space-station-14/pull/20263

It was definitely working in that branch, I guess it must've broken again?

> I'm assuming it makes them rainbow, but according to this post that is not working.

Yeah it just makes the light & sprite cycle through colours

**Comment by notquitehadouken** [comment]
when the bug is not reproducible on my machine! (aaaaAAAAAAAAA**AAAAAAAAAAAAAA**_**AAAAAAAAAAAA**_)

**Comment by ElectroJr** [comment]
People are apparently still having this issue, but I still have no idea how to reproduce it
