### ISSUE TITLE
gibber box

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#20706]
## Description

**Reproduction**

1. Instant open and close box with E and left-click
2. Person inside dissapears

From person inside view:
1. Black screen
2. Reconnect
3. You're ghost without body
**Screenshots**

**Additional context**

**Comment by lzk228** [comment]
> cant reproduce

try spamm clicking

**Comment by deltanedas** [comment]
yep
even bound left click and e to the same thing and spammed that didnt do anything

**Comment by deltanedas** [comment]
happened on deltav just now with cardboard box???
