### ISSUE TITLE
Playing and stopping midis causes short freezes

### ISSUE THREAD

**Issue by Olimbia** [space-wizards/space-station-14#20709]
### Description

Playing or stopping a midi, or being near one of these events will cause the console to display "error midi.fluidsynth: not a soundfont file" a few times and temporarily freeze the screen, though your character will still move in the direction you were holding down. The midi still plays.

**Reproduction**

1. Play or stop a midi, or be near a player who does the same
2. Screen freezes, midi.fluidsynth error

I apologise if I haven't used the correct terminology for what is occurring, but these videos of the issue should show the problem better than I can describe it.

https://github.com/space-wizards/space-station-14/assets/146871669/f46c45e2-b4f5-4cc3-8d88-b8aa3139ec03

https://github.com/space-wizards/space-station-14/assets/146871669/c715c8bd-bd89-401d-9991-f6df04e3be3c

**Comment by Slava0135** [comment]
Getting similar issues, its very bad if there is a band playing, literally 1 fps.

**Comment by metalgearsloth** [comment]
Dupe https://github.com/space-wizards/RobustToolbox/issues/4229
