### ISSUE TITLE
You can unanchor a syndicate bomb by removing the floor tile under it

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#20733]
## Description
Using a RCD or fireaxe to remove the floor tile under a syndicate bomb allows you to drag it away without having to cut any wires.

Intended?

**Reproduction**
1. arm a syndicate bomb.
2. use RCD or fireaxe to remove the floor tile under it
3. drag the bomb away.

**Comment by chromiumboy** [comment]
Resolved as of #22799
