### ISSUE TITLE
strange turning angles in combat mode

### ISSUE THREAD

**Issue by TheShuEd** [space-wizards/space-station-14#20731]
## Description

During the included combat mode, when the character turns after the mouse cursor, the rotation angles are very strange and it does not look like something planned
**Reproduction**

1) turn on the combat mode. 
2) Move the cursor.
**Screenshots**

https://github.com/space-wizards/space-station-14/assets/96445749/da25fe1e-52ca-4fcd-9e72-980057024284

**Comment by deltanedas** [comment]
its possible its using map based rotation not grid based, check in f3

**Comment by TheShuEd** [comment]
in this case, it is necessary to correct the error, because this difference in the character’s angle can vary greatly depending on the rotation of the grid

**Comment by metalgearsloth** [comment]
It might also just be using worldangle instead of the normal angle which is offset by Pi / 2.

**Comment by potato1234x** [comment]
can replicate

**Comment by metalgearsloth** [comment]
https://github.com/space-wizards/space-station-14/issues/24636 dumped the cause there for anyone who wants to fix it.
