### ISSUE TITLE
change netspeak into appropriate words issue

### ISSUE THREAD

**Issue by Emisse** [space-wizards/space-station-14#20745]
admins shouldnt have to enforce this its stupid when we can prevent this mechanically quite easily

**Comment by deltanedas** [comment]
#20180
fishops

**Comment by forgotmyotheraccount** [comment]
> So something to turn "thx" into "thanks!" Or something to stop and warn the players against using netspeak?

I imagine any solution that involves blocking messages isn't going to be extremely unpopular. best to stick to word replacement

**Comment by notquitehadouken** [comment]
we already have something that does something pretty similar to this
things like idk, lol, o7, xd, :/, etc. all make you emote

**Comment by Plykiya** [comment]
lol
