### ISSUE TITLE
Pressing toggle ghosts as a ghost removes all actions

### ISSUE THREAD

**Issue by DrSmugleaf** [space-wizards/space-station-14#20741]
## Description
**Reproduction**
- Ghost
- Toggle the toggle ghost action
- All actions are gone until you ghost again
![image](https://github.com/space-wizards/space-station-14/assets/10968691/7719097b-5ecc-43c4-93a8-cd23e4861b3d)

**Screenshots**

**Comment by LankLTE** [comment]
This happens to all ghosts, not just aghosts

**Comment by ryancwilliams** [comment]
I was able to replicate this issue a few days ago.

**Comment by ElectroJr** [comment]
This is the same issue as #20097, the ghost visibility toggling just needs to be changed to not use PVS visibility layers.
