### ISSUE TITLE
media console should have dedicated image upload

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#20756]
## Description
with a whitelist so no randoms spamming sussy image

killers script wastes huge amount of bandwidth and causes lag in extreme cases, just sending a png to clients would be much much much better

**Comment by BasedUser** [comment]
also with a size limit of 200kb per image and like 4 images max because reporters funny

**Comment by mirrorcult** [comment]
we are not doing this. only way anything like this is getting added is an IC camera that just takes snapshots of appearance data and doesnt rely on clients sending arbitrary images

**Comment by deltanedas** [comment]
could maybe maybe reuse map render stuff but using live game state and for a small viewport
