### ISSUE TITLE
Headrevs should innately have a sechud

### ISSUE THREAD

**Issue by GoodWheatley** [space-wizards/space-station-14#20755]
Would prevent those embarrassing moments of running up to a command member and flashing them, and once secHUDs show mindshields this would prevent accidentally flashing a mindshielded crew member

**Comment by LankLTE** [comment]
Just think about who you flash? If you aren’t seeing that someone is a command member before trying to convert them that honestly sounds like a you problem

**Comment by CatMagic1** [comment]
skill issue :trollface:

**Comment by mirrorcult** [comment]
no lol skill issue

**Comment by GoodWheatley** [comment]
guh
