### ISSUE TITLE
Sechuds should show if someone is mindshielded

### ISSUE THREAD

**Issue by GoodWheatley** [space-wizards/space-station-14#20750]
Just have a blue flashing border around the job icon like in tg.

**Comment by deltanedas** [comment]
would absolutely nuke someone pretending to be a secoff since they wouldnt be shielded instant kos

**Comment by GoodWheatley** [comment]
> would absolutely nuke someone pretending to be a secoff since they wouldnt be shielded instant kos

it should be difficult to successfully pull off an impersonation regardless.

**Comment by deltanedas** [comment]
this would mean you have to go to cargo buy a mindshield crate (if they have money) unlock it and use it

which would make revs impersonating sec **impossible** let alone bad for syndies

**Comment by GoodWheatley** [comment]
> this would mean you have to go to cargo buy a mindshield crate (if they have money) unlock it and use it
> 
> which would make revs impersonating sec **impossible** let alone bad for syndies

The alternative is security having no way to tell if someone is mindshielded or not, meaning they’d have to massacre the station to stop the revs. Impersonating a security officer should inherently be risky to do, and I don’t see the problem with an observant officer with a sechud being able to call someone out.

**Comment by HoidC** [comment]
> > would absolutely nuke someone pretending to be a secoff since they wouldnt be shielded instant kos
> 
> it should be difficult to successfully pull off an impersonation regardless.

chameleon gear becomes very garbage if you can’t impersonate anyone relevant

**Comment by Mudsson** [comment]
Since heads aren't convertible aren't they mindshielded too? What if instead of sechuds showing someone was mindshielded automatically, criminal records allowed you to add that to them? (I forget if criminal records is in, been gone a while). Then if you impersonate a mindshielded person, sec can't tell, but can still tell among the horde of station goers.

**Comment by Kayek14** [comment]
> this would mean you have to go to cargo buy a mindshield crate (if they have money) unlock it and use it
> 
> which would make revs impersonating sec **impossible** let alone bad for syndies

Adding in a cheap *fake mindshield implant* purchace from the uplink would be nice for situations like this if this change goes through. Would give a added layer of stealth and inflitration for players taking that route.

**Comment by UbaserB** [comment]
This should be closed
