### ISSUE TITLE
Flashes shouldn't cause slowdown

### ISSUE THREAD

**Issue by Flareguy** [space-wizards/space-station-14#20774]
## Description
Flashes really shouldn't cause slowdown:
1. It's fairly overpowered. Literally an instant, near-free followup for your stunbaton as long as someone doesn't have flash protection; the only reason it's probably not abused or more known is because you can't use it on nukeops.
2. They're intended to be defensive weapons first-and-foremost, not stunning ones - the screen flash lasts several seconds already and is enough to disorient an attacker to a large degree, so the slowdown both muddies this role and also makes them unfit for being more common then sec's other gear (they're given to heads and the like for this reason.)

Should probably not apply to flashbangs, which *are* intended to be stunning weapons.

An alternative to this could entail making the slowdown only apply when flashed while facing another player (like in /tg/,) but I'm not sure how feasible that is.

**Comment by notquitehadouken** [comment]
will PR

**Comment by mirrorcult** [comment]
in favor of this

**Comment by LankLTE** [comment]
Also in favor of this

**Comment by JoeHammad1844** [comment]
not in favor of this, its still hard to escape an attacker when they are still as fast as you and swinging wildly

**Comment by QuietlyWhisper** [comment]
Also helps non humanoid mobs escape flashes 👍

**Comment by notquitehadouken** [comment]
in favor of this

**Comment by Flareguy** [comment]
I was *actually* complaining about flashbangs here. Flashes had an absolutely pitiful effect at the time this issue was written, and are still probably in a fine state now.

I would be willing to wager that flashbangs are definitely not still fine, but that's grounds for a separate issue.
