### ISSUE TITLE
Hacking UI not opening

### ISSUE THREAD

**Issue by Kezu02** [space-wizards/space-station-14#20787]
## Description
Tested on doors, a syndie bomb, Booze-o-mat, and YouTool. Besides screwing it open/closed, the menu for hacking does not appear. Multiple players have reported this for the latest update.

**Comment by deltanedas** [comment]
you have to click it with a wirecutter/multitool after opening

**Comment by deltanedas** [comment]
![12:30:09](https://github.com/space-wizards/space-station-14/assets/39013340/ca358481-b8a5-4b05-814b-1ec50d9e3026)
![12:30:00](https://github.com/space-wizards/space-station-14/assets/39013340/24425f9a-beee-4147-b109-7b77108e4ab4)

**Comment by liltenhead** [comment]
Can't replicate the problem with airlocks. But I can't open vendors, windoors, or the hardbombs hacking ui.

**Comment by Equivocateur** [comment]
vends are not hackable, neither are bombs

**Comment by GoodWheatley** [comment]
> vends are not hackable, neither are bombs

Yes they are?

**Comment by Partmedia** [comment]
This was broken due to a regression in https://github.com/space-wizards/space-station-14/pull/20265 (found by bisection). @chromiumboy would you be able to investigate?
