### ISSUE TITLE
Bounding Boxes: Nitpick Madness

### ISSUE THREAD

**Issue by partyaddict** [space-wizards/space-station-14#2078]
Disposal Unit - https://i.imgur.com/m8W0huK.png
Vending Machine - https://i.imgur.com/v4igAm7.png
Lockers - https://i.imgur.com/NOpWymx.png
Welding/Water Tanks - https://i.imgur.com/LeSWdSp.png
Crates - https://i.imgur.com/sAKTBL3.png

@SweptWasTaken said he'll fix this

**Comment by partyaddict** [comment]
**BONUS**

There are some smaller objects that need some bounding box cleanup too.
One very noticeable thing I've noticed is bullet casings.
![2020-09-13_22-11-45](https://user-images.githubusercontent.com/52793290/93028811-3fe26c80-f60e-11ea-9b0c-6bcf3c58bbf4.png)
I could go all day regarding smaller objects but I think that's a thing you should look at yourself.

**Comment by SweptWasTaken** [comment]
Fixed most of these.
