### ISSUE TITLE
Perspective is jagged.

### ISSUE THREAD

**Issue by partyaddict** [space-wizards/space-station-14#2080]
![2020-09-13_22-13-51](https://user-images.githubusercontent.com/52793290/93028849-9c458c00-f60e-11ea-93e3-fc88426132ca.png)
Jagged pixels.
Of course this is not at all noticeable when showbb is off but it's still a thing to note. :eye:

**Comment by PJB3005** [comment]
Hey good thing you only reported the jagging instead of the massive warping that happens.

But yeah this basically cannot be fixed without a complete rewrite of the FOV system.
