### ISSUE TITLE
Aghosts Can't See Radio Keys In Strip Menu

### ISSUE THREAD

**Issue by Nairodian** [space-wizards/space-station-14#20805]
## Description
Aghost are unable to check a radio's encryption keys while on a person in the strip menu. Makes admining around it difficult.

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/110078045/80f53a08-9bd8-4897-8cbb-20a2d289a6f1)

**Comment by PJB3005** [comment]
This was fixed at some point.
