### ISSUE TITLE
rev dialog

### ISSUE THREAD

**Issue by Tunguso4ka** [space-wizards/space-station-14#20815]
people should have a choice to become or not to become a revolutionary.
Something like defib dialog with "yes" "no".

thats lame and stupid when headrev running through whole station and flashes everyone.

**Comment by LankLTE** [comment]
This defeats the entire point of revolutionaries. Imagine there being a yes / no option to become a zombie.

**Comment by EmoGarbage404** [comment]
Getting brainwashed? Just say no!
