### ISSUE TITLE
Button windows by default block the buttons.

### ISSUE THREAD

**Issue by partyaddict** [space-wizards/space-station-14#2081]
![2020-09-13_22-22-11](https://user-images.githubusercontent.com/52793290/93028979-a5832880-f60f-11ea-985a-b4f08c2026cd.gif)
Button windows by default block the buttons.
Now, good thing it saves the last position it was stored it when you pressed the button.
But this isn't good enough for me! Why doesn't it by default appear under the buttons! Shame on thee!

**Comment by SweptWasTaken** [comment]
After #3735 gets merged this will be closed since none of these windows open over the buttons anymore.
