### ISSUE TITLE
Remove Hydroponics Tray Ghost Role

### ISSUE THREAD

**Issue by EdenTheLiznerd** [space-wizards/space-station-14#20825]
I think I speak for a lot of people when I say I get excited at the number of ghost but get greeted to +12 hydroponic trays as a ghost role, it also does stop people from noticing the other ghost roles such as lone op or ninja

**Comment by UbaserB** [comment]
I dunno how other people feel about it but i do have to agree it's way too common

**Comment by K-Dynamic** [comment]
Either remove it or let us collapse/hide ghost roles

**Comment by UbaserB** [comment]
Thinking about it, there has still been *some* good roleplay with these hydroponics trays; especially new players. Making the role EXTREMELY rare may make this role wanted when it does pop up.

**Comment by slarticodefast** [comment]
The reason it is so common and shows up in large groups is that it can be copied from one tray to another by clipping the mutated plant. The mutation chance itself is rare enough. So just stop the mutation from being copied when clipping plants.

**Comment by UbaserB** [comment]
that makes sense actually

**Comment by slarticodefast** [comment]
> So just stop the mutation from being copied when clipping plants.

I just checked the code and it should only be 2-3 lines that have to be changed. I can cook up a PR for this later.
