### ISSUE TITLE
ammo techfab cant make mags like security techfab

### ISSUE THREAD

**Issue by JoeHammad1844** [space-wizards/space-station-14#20833]
**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/130668733/d9a11f0b-7cb9-4e37-8c1d-966c8f13e837)

**Comment by AjexRose** [comment]
Thats intended. The ammo techfab is meant to be a sort of sec techfab lite, only fulfilling the bare minimum.

**Comment by JoeHammad1844** [comment]
its supposed to be the techfab but only make ammo related things, magazines are ammo related

**Comment by deltanedas** [comment]
ajexrose is the one that made ammofab :trollface:

**Comment by JoeHammad1844** [comment]
damn
