### ISSUE TITLE
Chat spam detection

### ISSUE THREAD

**Issue by Chief-Engineer** [space-wizards/space-station-14#20845]
At a minimum, throttle chat messages. Throttled messages are not displayed, but generate an admin alert. Throttling variables should be configurable in cvars.

An extended implementation could allow the action on throttle to be configurable between some options:
- Drop and alert
- Kick and alert
- Temp ban and alert
- Ban and alert

**Comment by iacore** [comment]
is this limit per-person? is the rolling-window algorithm enough?
