### ISSUE TITLE
Movement prediction when gravity is off doesn't work well.

### ISSUE THREAD

**Issue by partyaddict** [space-wizards/space-station-14#2084]
Could not be a movement prediction thing but just move around with gravity on and you'll noticeably see it's jittery in some cases. I couldn't get a video of it.

![2020-09-13_22-29-34](https://user-images.githubusercontent.com/52793290/93029101-a1a3d600-f610-11ea-9e34-8b55c657e597.png)
This is what my latency was.

**Comment by metalgearsloth** [comment]
It's prediction doing it where the server's last state is being replayed when the mover thinks it should be stopped. I tried looking at it but I didn't know enough about the game state manager.
