### ISSUE TITLE
Cursor hitboxes are too big - again.

### ISSUE THREAD

**Issue by partyaddict** [space-wizards/space-station-14#2087]
Technically a duplicate of #601 and #674 which were supposedly fixed but wasn't.
![2020-09-13_22-41-20](https://user-images.githubusercontent.com/52793290/93029457-da44af00-f612-11ea-8088-1f059d6bfe45.gif)
There are a few other cases where the hitbox seems too big, as it also counts the highlighting as part of the object.

**Comment by partyaddict** [comment]
Thinking about this now, it probably isn't an actual issue as it probably doesn't overlap with anything. Though I wonder if trying to crowbar a tile with your cursor close to the wall will make you hit the wall instead.

**Comment by Zumorica** [comment]
Wasn't this intentional so small entities are less painful to click? Either way, this really seems like a non-issue to me

**Comment by RemieRichards** [comment]
I think it WAS intentional, yeah.

**Comment by SweptWasTaken** [comment]
Intentional.
