### ISSUE TITLE
small tidbits with handcuffs

### ISSUE THREAD

**Issue by sentient-ai** [space-wizards/space-station-14#2092]
1. ~~you get "you are too far away to remove the cuffs" no matter how close you are to the target.~~
2. ~~being cuffed leaves things in your hand slots, no forced drops.~~
3. no UI indicator in the hand slot itself that you are cuffed
~~no way to resist out of cuffs~~ - nevermind

**Comment by nuke-makes-games** [comment]
There's a verb to uncuff yourself or others, you have to stand still while doing it.

**Comment by sentient-ai** [comment]
Was testing this on corpses and I kept getting the too-far-away error.

**Comment by nuke-makes-games** [comment]
hm, it's also possible that the entitycoordinates changes might have broken something. this feature was written before that was a thing. also there were changes to the player-in-range utility functions so maybe that might be causing some issues.

**Comment by Zumorica** [comment]
2 fixed in 8e8744b38350102ce08c51369b145008faa9ac61

**Comment by SweptWasTaken** [comment]
All fixed.
