### ISSUE TITLE
Thermal machines do not have a maximum/minimum temperature threshold

### ISSUE THREAD

**Issue by Anzarot121** [space-wizards/space-station-14#20922]
## Description

Coolers and heaters have a bug with maximum/minimum temperatures, respectively. The bug is purely visual, because with such values ​​they simply do not work.
**Reproduction**

Take your cooler
set the temperature to 1000
press enter
the cooler doesn't work.
**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/116586144/4c8c4b02-ad61-4a9e-812f-c90df8f86eb9)
![image](https://github.com/space-wizards/space-station-14/assets/116586144/132ca611-7be0-4c14-a876-1d40894ebd5b)

**Comment by Ilya246** [comment]
not a bug, yes

**Comment by Anzarot121** [comment]
Ok
