### ISSUE TITLE
Can not see dead people from afar

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#20934]
## Description
From 3 tiles away I can see the dead text from 4 I can not.

**Reproduction**
- Make someone dead
- Get in to a mob
- Shift click the dead mob(examine)
- Do it from 4 and 3 tiles away to see difference.

**Screenshots**
3 tiles away
![image](https://github.com/space-wizards/space-station-14/assets/47093363/2c97bcd8-4393-4930-88db-980a4f716e05)
4 tiles away
![image](https://github.com/space-wizards/space-station-14/assets/47093363/8d9a2229-1d9b-46f4-8ddf-b599467d5378)

**Additional context**
Makes it really hard to know if you should go try save someone or not, it affects the soul text too.

**Comment by mirrorcult** [comment]
this is intended
