### ISSUE TITLE
Pneumatic cannon used as an automatic crossbow

### ISSUE THREAD

**Issue by Aisu9** [space-wizards/space-station-14#20936]
## Description

Pneumatic cannons can be use to rapid fire arrows

**Reproduction**

Load PC with gas tank and arrows
fire
unload a volley of arrows (probably coated with all sorts of funny liquid)

**Screenshots**

**Additional context**

**Comment by Ilya246** [comment]
feature

**Comment by deltanedas** [comment]
arrow damage should depend on velocity but otherwise why not

**Comment by Aisu9** [comment]
eh.... someone would like to say something
![image](https://github.com/space-wizards/space-station-14/assets/56479183/ec38aa4f-c75d-4323-8753-35c217c257e9)

**Comment by deltanedas** [comment]
shouldnt do full damage since its not firing from a bow but having an arrow thrown at you should still hurt somewhat

**Comment by Aisu9** [comment]
> shouldnt do full damage since its not firing from a bow but having an arrow thrown at you should still hurt somewhat

i'll be honest, the arrow damage isn't the main issue, it's the 5 units of chemicals EACH ARROW will inject you

**Comment by deltanedas** [comment]
straight up shouldnt inject anything if not shot by a boe to have enough speed
this would also mean you could use your ipecac arrows in an overclocked cannon as a metal bow that stuns you :trollface:

**Comment by Slava0135** [comment]
resolved by #21067
