### ISSUE TITLE
Shiva doesn't fight grenade penguins

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#20932]
## Description
Shiva the sec spider doesn't fight back against grenade penguins, but the pengu attacks them till death.

**Reproduction**
Put them both in a room and let em go for it.

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/47093363/dfc15622-00bf-4d90-b971-8ae2aaa158c3)

**Additional context**
N/A

**Comment by deltanedas** [comment]
shiva attacking pingu is guaranteed explosion, if left alone at worst shive dies at best someone disposes of the pingu with shiva still alive

**Comment by Aisu9** [comment]
aren't pets and animals supposed to attack back now?

**Comment by Titian3** [comment]
I'll close this off it doesn't seem too important.
