### ISSUE TITLE
Radiation Collector improvements

### ISSUE THREAD

**Issue by keronshb** [space-wizards/space-station-14#20953]
- [x]  Radiation collectors should have a new sprite to indicate full/empty plasma & maps should spawn a single plasma tank on one. #20956 
- [x] Engineering should be mapped with an oxy/plasma tank dispenser that has 10 oxygen tanks and 10 plasma tanks

~~- The old TG sprite could be used since it had a slot for an inserted plasma tank.~~
~~- An alert can be sent out over the engineering radio if the plasma is low/run out.~~

**Comment by chromiumboy** [comment]
I'm happy to take on the add on plasma tank sprite for the collector and the code to update its appearance

The clarify, should the collector spawn with a full tank inside it, or should a full tank be mapped on top of the collector? My recollection was the latter

Also, if you have a set up with 12 radiation collectors, it could get the radio could be spammed with a dozen messages if they all run low on gas within a short period of time

**Comment by keronshb** [comment]
> The clarify, should the collector spawn with a full tank inside it, or should a full tank be mapped on top of the collector? My recollection was the latter

Back in SS13 a plasma tank would be mapped to spawn on top of a rad collector. Sort of like a hint for the player to put it in the collector, and then do the same for the rest.



> Also, if you have a set up with 12 radiation collectors, it could get the radio could be spammed with a dozen messages if they all run low on gas within a short period of time

That's a potential issue since the likeliness of them all getting set at the same time is high. And then what happens if someone else outside of engineering makes a plasma collector. That shouldn't alert engineering if the plasma was low either.

The ones in engineering could be linked to the engineering/atmos channels and then the first one gets to report? It could start a timer or something so the others don't report within x amount of seconds of the first report, but that could get tricky.

**Comment by chromiumboy** [comment]
My feeling is that there shouldn't be a radio alert for radiation collectors. It'd be like if a portable generator ran out of fuel. You need to be proactive and keep an eye on it. There will be indicator lights on the collectors too, to show the amount of plasma left in the tank. So a cursory walk around the perimeter of the singulo will be enough to see if you need to top them up

**Comment by keronshb** [comment]
> My feeling is that there shouldn't be a radio alert for radiation collectors. It'd be like if a portable generator ran out of fuel. You need to be proactive and keep an eye on it. There will be indicator lights on the collectors too, to show the amount of plasma left in the tank. So a cursory walk around the perimeter of the singulo will be enough to see if you need to top them up
> 
> Edit: here's a mock up https://discord.com/channels/310555209753690112/346743671787356160/1158793295124770969

Sounds fine to me. This gives engineers a reason to check in on the engine again.

I do miss the old TG sprite but I can live with the one we have. The sprite edit looks fine to me, actually ends up being more noticeable than the old sprite.

**Comment by keronshb** [comment]
Now we just need someone to go through the maps and map a single plasma tank over one of the rad collectors. Low priority though.

**Comment by chromiumboy** [comment]
> Now we just need someone to go through the maps and map a single plasma tank over one of the rad collectors. Low priority though.

Mappers will also need to replace the default radiation collector with the version which has no attached plasma tank; at present they start with an attached (empty) tank

**Comment by UbaserB** [comment]
This should be closed
