### ISSUE TITLE
Butchering Ian/Lisa drops no corgi meat

### ISSUE THREAD

**Issue by Kezu02** [space-wizards/space-station-14#20964]
## Description

Butchering the doggos for objectives turns them into corgi hide but no prime-cut corgi meat shows up with it.

**Comment by deltanedas** [comment]
snopes factcheck: fake

![14:40:50](https://github.com/space-wizards/space-station-14/assets/39013340/3a5e6904-5763-40c7-b44a-de422ea108bc)

**Comment by CatMagic1** [comment]
can confirm I saw dat meat just the other day

**Comment by Titian3** [comment]
Have seen it happen on rounds too, but when I spawned it in to test the person hadn't messed it up it worked but logs showed no meat. Maybe station spawn Ian has issue?

**Comment by UbaserB** [comment]
Pretty sure this isn't an issue anymore.
