### ISSUE TITLE
Bolas + keyboard macros = instant ranged stuns

### ISSUE THREAD

**Issue by AJimmyU** [space-wizards/space-station-14#20994]
## Description

Players are abusing dual bolas + keyboard macros to have a ghetto ranged instant stun weapon.

**Reproduction**

1. have 2 bolas
2. throw both at the same time
3. instantly stun anyone at range

**Screenshots**

**Additional context**

Bolas should be reworked to not apply so reliably and to not cause a hard stun.

**Comment by deltanedas** [comment]
yes it should just be slowdown not batong

also bowling should be either rng or depend on the batongs orientation since being hit by the stick end shouldnt stun but getting lucky hit with the sparky end should stun

**Comment by Slava0135** [comment]
resolved by #21340
