### ISSUE TITLE
Paramedic suit helmet should probably be an equip action rather than an item

### ISSUE THREAD

**Issue by QuietlyWhisper** [space-wizards/space-station-14#21011]
## Description

Seems unnecessary to keep as an item.
Would need to be removed from the relevant vendors and lockers.

As a side note, it may be also worth removing it from the vender entirely and restricting it to the mapped locker? You can currently restock the medidrobe to get more paramedic eva, making it no longer a job unique equipment.

**Comment by Yousifb26** [comment]
Instead of removing it from the vendor, remove the restock. If i remember correctly not all stations have the paramedic job which could cause issues if a cmo would want one

**Comment by QuietlyWhisper** [comment]
> Instead of removing it from the vendor, remove the restock. If i remember correctly not all stations have the paramedic job which could cause issues if a cmo would want one

the vendor is meant to be a clothes vendor...
