### ISSUE TITLE
Micro-bomb explosion deaths deletes the  user's entity and does not ghost them

### ISSUE THREAD

**Issue by Arctic-Husky** [space-wizards/space-station-14#21038]
## Description

Deaths by activating a micro-bomb implanter simply deletes your body and prevents you from having a ghost upon death

**Reproduction**

1 - Implant yourself with a micro-bomb implanter
2 - Activate the bomb

**Screenshots**

https://github.com/space-wizards/space-station-14/assets/1398269/5d22f9dc-95ed-44cf-92fc-2244f4b3544e

**Additional context**

Server output: 
```
[WARN] system.mind: Entity "1961D" for Astor Tireman was deleted, and no applicable spawn location is available.
```

Client output:
```
[WARN] system.interaction: Client sent interaction with no attached entity. Session=Robust.Client.Player.PlayerSession
[INFO] system.interaction: Use input validation failed
```

**Comment by Arctic-Husky** [comment]
This also happens with the macro-bomb implant, since it uses the same logic as the micro-bomb

**Comment by Doru991** [comment]
Note: Manually /ghosting seems to allow you to spectate normally, though of course it'd be ideal if you didn't have to
