### ISSUE TITLE
Double target and overlapping objectives (syndie objective)

### ISSUE THREAD

**Issue by DummeHytteOst** [space-wizards/space-station-14#21042]
you can get a person to be your target for objectives twice on the same kind/overlapping objectives 

maroon/kill and kill objectives on the same person

![image](https://github.com/space-wizards/space-station-14/assets/94384139/77a05ac5-7e76-4d75-a5a0-ab72631ef8ff)
round nr was #35739

double maroon/kill objective on the same person

![image](https://github.com/space-wizards/space-station-14/assets/94384139/a81a3b87-3ee7-44f3-9045-83ba4f211924)
round nr #36139

double ensure another traitors objectives

![image](https://github.com/space-wizards/space-station-14/assets/94384139/48cff647-4f7e-480b-8342-d20cb499e0cb)
round nr #36421

**Comment by deltanedas** [comment]
you can also get regular kill/maroon target twice

**Comment by TurboTrackerss14** [comment]
Overlap between the killperson objective and killhead objective. 
Might be viable to remove the heads from killperson objectives considering they now have a dedicated objective for them.

**Comment by deltanedas** [comment]
kill person can still overlap with kill person
kill head can still overlap with kill head

**Comment by JoeHammad1844** [comment]
ive gotten 'protect this person' twice, the same person each time

**Comment by DummeHytteOst** [comment]
renamed to be more inline with the issue
