### ISSUE TITLE
Gibbing always deletes all inventory items

### ISSUE THREAD

**Issue by Doru991** [space-wizards/space-station-14#21045]
## Description

As the title says, gibbing will ignore the deleteItems parameter and delete all inventory items on the person regardless, including possible evidence, syndie objective items etc.

**Reproduction**

* I love my items
* Apply bang stick gibber to self
* Where are my items

**Additional context**

Initially introduced in #20202 presumably, as it changed the way the gibbing function looks for items to drop, making it ignore inventory slots and leaving the items to be deleted with the character.

**Comment by Carolyn3114** [comment]
discovered this the other day when I shoved a CMO into a recycler
