### ISSUE TITLE
Actions sometimes disappear when teleporting or connecting

### ISSUE THREAD

**Issue by VasilisThePikachu** [space-wizards/space-station-14#21063]
title

**Comment by keronshb** [comment]
What actions are missing?
Please explain more.

**Comment by Endecc** [comment]
> What actions are missing? Please explain more.

All of them, and it's not exclusively when joining. I've noticed they also vanish when making long distance ghost warps. The actions can be re-added by typing `resetallents` in the command window.

**Comment by VasilisThePikachu** [comment]
> > What actions are missing? Please explain more.
> 
> All of them, and it's not exclusively when joining. I've noticed they also vanish when making long distance ghost warps. The actions can be re-added by typing `resetallents` in the command window.

this exactly. never know that that commant fixed it but yeah

**Comment by ElectroJr** [comment]
It would be helpful if someone can figure out a way to reliably reproduce the bug on a local server

**Comment by moonheart08** [comment]
Very easy to reproduce if you teleport outside of PVS range (i.e. 50-100m)

**Comment by ElectroJr** [comment]
I'm guessing its one of those fun bugs that only happen on live servers or something like that, because locally things work fine


https://github.com/space-wizards/space-station-14/assets/60421075/b5e0bf98-bb02-4163-a328-5b8f7feca35f

**Comment by VasilisThePikachu** [comment]
FUCK IM A DUPE #20483
