### ISSUE TITLE
Drones should be unmapped and made uncraftable.

### ISSUE THREAD

**Issue by NancokPS2** [space-wizards/space-station-14#21066]
## Description
Currently drones are effectively disabled. It has been decided that they are not worth re-enabling as a role and there's good reasons for it.   
- They are too hard to moderate and prone to severe shittery  
- Encroach in engineering's gameplay and take away work from them  
- They do not contribute much to RP

Many maps currently have not only a fully fledged drone room that goes completely unused. But you can also unlock their tech and craft them wasting resources in a paper-weight.

**Comment by slarticodefast** [comment]
Fixed by #25372
