### ISSUE TITLE
MouseRotator spams errors

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#21080]
Check grafana, might be borg related?

`tried setting 4-dir rotation directly without a valid mouse rotator component attached!`

**Comment by mirrorcult** [comment]
pretty sure this is just me fucking up the logic of the error, think this happens when you enter combat mode and try to rotate before server learns that you entered combat mode

**Comment by mirrorcult** [comment]
error should probably just get removed entirely

**Comment by ShadowCommander** [comment]
Superseded by #27510 due to better reproduction steps.
