### ISSUE TITLE
Unstable mutagen unable to increase yield past 5.

### ISSUE THREAD

**Issue by Qiler** [space-wizards/space-station-14#21085]
## Description
Unstable mutagen is unable to increase yield of plant to higher than 5. Theoretically possible yield values are between 3 to 10, with chance of increasing or decreasing biased so it tends to drift towards 5, but due code error the chance of increasing yield when plant has yield of 5 is 0%, at yield 6 it is -20%.
Trying to mutate cocoa which has base yield of 6 will only decrease it to 5 or even on some builds crash the server with error "Chance must be in range 0-1. It was -0.20000005."

**Reproduction**

1. Plant cocoa seed.
2. Add 10u mutagen.
3. Wait 20 seconds.
4. Use clippers on the plant.
5. Inspect seed to see its yield.

**Additional context**
Bug is caused because of lack of mapping of val between min and max to probability of increasing value in [MutateInt](https://github.com/space-wizards/space-station-14/blob/b33b57509ede35658d05abf6b965f1858209469b/Content.Server/Botany/Systems/MutationSystem.cs#L178) function. [MutateFloat](https://github.com/space-wizards/space-station-14/blob/b33b57509ede35658d05abf6b965f1858209469b/Content.Server/Botany/Systems/MutationSystem.cs#L145) function has said mapping and is working properly.
I propose following change to code to fix it:
```C#
    private void MutateInt(ref int val, int min, int max, int bits, int totalbits, float mult)
    {
        // Probability that a bit flip happens for this value's representation in thermometer code.
        float probBitflip = mult * bits / totalbits;
        probBitflip = Math.Clamp(probBitflip, 0, 1);
        if (!Random(probBitflip))
            return;

	// Starting number of bits that are high, between 0 and bits.
        // In other words, it's val mapped linearly from range [min, max] to range [0, bits], and then rounded.
        int valInt = (int)MathF.Round((val - min) / (max - min) * bits);
        // val may be outside the range of min/max due to starting prototype values, so clamp.
        valInt = Math.Clamp(valInt, 0, bits);

        // Probability that the bit flip increases n.
        // The higher the current value is, the lower the probability of increasing value is, and the higher the probability of decreasing it.
        // In other words, it tends to go to the middle.
        float probIncrease = 1 - (float)valInt / bits;
        int valMutated;
        if (Random(probIncrease))
        {
            valMutated = val + 1;
        }
        else
        {
            valMutated = val - 1;
        }

        valMutated = Math.Clamp(valMutated, min, max);
        val = valMutated;
    }
```

**Comment by slarticodefast** [comment]
Resolved by #27210
