### ISSUE TITLE
Cyborgs can obtain a hand slot

### ISSUE THREAD

**Issue by Terraspark4941** [space-wizards/space-station-14#21090]
## Description

Medical Cyborgs can obtain a full hand slot by feeding a stethoscope to a moth, and they can keep this hand slot by deselecting the diagnosis module. Number of hand slots obtainable untested. Once a module is deselected by the affected cyborgs, they cannot reselect new modules, presumably until they are destroyed. 

**Reproduction**

1. Make a medical cyborg
2. Insert a Diagnosis cyborg module
3. Select the module, select the stethoscope
4. Force-feed the stethoscope to a moth
5. Profit 
6. (Optional) Deselect the hand slot 

**Screenshots**

**Additional context**

I think this is because the hand slot is not specialized, like the treatment slots, so replacing it should work here

**Comment by deltanedas** [comment]
did someone not blacklist stethoscope being eaten
