### ISSUE TITLE
drone`s issue

### ISSUE THREAD

**Issue by Ratyyy** [space-wizards/space-station-14#21104]
## Description

drone has no welder, omnitool and else
**Reproduction**

1. spawn drone
2. play drone
**Screenshots**

![изображение](https://github.com/space-wizards/space-station-14/assets/138193222/b5ec6a94-e260-4be7-90f8-c0fb7eca4696)

**Additional context**

**Comment by chromiumboy** [comment]
It doesn't really matter, since drones as a ghost role are disabled until they can reworked
