### ISSUE TITLE
Headrev revolutionary rounds seem to be broke

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#21114]
## Description
Not 100% sure on this one but from what i can tell the gamemode is revs but no headrevs get applied. The game picks people and spawns them with a flash and sunglasses but they dont get the "antag" status and are unable to convert.

I saw no antag status on admin pannel and thought it was just an extended untill i saw the end round report.

Round was Lizard 36026

**Screenshots**
Taken from a rev round that had this issue:
![image](https://github.com/space-wizards/space-station-14/assets/106507028/e8f01268-9e14-4355-b09c-68c1d6425918)

**Comment by EmoGarbage404** [comment]
got fixed with #21112
