### ISSUE TITLE
headrev blueball

### ISSUE THREAD

**Issue by JoeHammad1844** [space-wizards/space-station-14#21118]
## Description

get picked for headrev, recieve no gear, briefing overlay, or ability to convert crew. basically extended but you have to give out antag tokens for up to three ~un~lucky people

**Screenshots**

![20231020173331_1](https://github.com/space-wizards/space-station-14/assets/130668733/e99a5e24-7afc-440c-ace5-5818098ad0be)

**Comment by JoeHammad1844** [comment]
i cant see the metadata for your comment, my gamer

**Comment by JoeHammad1844** [comment]
nevermind, if i do quote reply i can see

**Comment by GoodWheatley** [comment]
Fixed by #21112
