### ISSUE TITLE
Cargo shuttle and Reclaimer thrusters/gyros start turned off.

### ISSUE THREAD

**Issue by IProduceWidgets** [space-wizards/space-station-14#21125]
## Description

the Cargo shuttle and Reclaimer thrusters/gyros start turned off with the shuttles positioned in deep space.

**Reproduction**

Start a new round, try to fly cargo shuttle back to cargo. See that you cannot.

**Screenshots**

**Additional context**

Also occurs for nukie shuttle.
Also occurs for loaded grids such as ERT Dart. Less of an issue though.

**Comment by deltanedas** [comment]
iirc its just the yaml has enabled set to false
