### ISSUE TITLE
Cyborgs can't toggle station intercoms

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#21145]
## Description
To use a wall mounted intercom you have to open the UI and then toggle the button. It will turn green and will remain active until toggled off. 

When a cyborg uses the intercom, they can toggle the button, it will turn green, but it wont auctually do anything. If you close and reopen the intercom the button will be off again.

**Reproduction**
1. Be a cyborg.
2. Open intercom UI.
3. Click on Mic. to toggle it on.
4. Say something.
5. Close and reopen intercom UI.

**Screenshots**

Cyborg using intercom to no effect
![image](https://github.com/space-wizards/space-station-14/assets/106507028/a9b284f4-6287-4b6b-a74d-d4f949edb7b6)

Crew member using intercom with effect
![image](https://github.com/space-wizards/space-station-14/assets/106507028/318f453b-a19c-4b4a-a6e8-61ef0ae3cd2f)

**Additional context**
Wall mounted intercomms only way for cyborgs to speak on radio. Not being able to use the intercom is quite painful.

**Comment by Doru991** [comment]
Are you trying to do it with no module selected? Borg interactions are kinda iffy, if you have no module selected it'll think you have no hands and prevent you from interacting with stuff, but if you have one active it should count as a hand and allow you to use intercoms etc.

**Comment by Kayek14** [comment]
You are correct, it works if you have a module toggled and a item selected

![image](https://github.com/space-wizards/space-station-14/assets/106507028/f7771fd4-7181-4154-bf68-38d9080b3e06)

Kinda wonky. It should work without having a module selected
