### ISSUE TITLE
There are no logs for teleporting when a bluespace anomaly goes critical.

### ISSUE THREAD

**Issue by IProduceWidgets** [space-wizards/space-station-14#21156]
## Description

Teleporting is usually logged, including when someone goes into a bluespace portal or anomaly, however, there is no log from teleports when a bluespace anomaly goes critical. This is not great, since it is also the least understandable way to be teleported, as the range is quite far and may not be due directly to the actions of the player. 

**Reproduction**

Stand near critical bluespace anomaly, teleport, check logs, see that there are none.

**Screenshots**

**Additional context**

This gets ahelped mildly frequently when people get unexpectedly shoved into a wall or space.

**Comment by tday93** [comment]
Working on this this morning, would you rather these logs appear under the "Anomaly" or "Teleport" log type? My first thought was teleport, as I'm assuming that would be what players are asking about.
