### ISSUE TITLE
Support for more complex alerts

### ISSUE THREAD

**Issue by gradientvera** [space-wizards/space-station-14#2116]
Status effects need a lot of improvements.
- [ ] RSI support, for animated status effects.
- [x] Layer support for complex status effects (complex body health doll with part-specific damage)

**Comment by chairbender** [comment]
note in the injazz mockups, it seems like health is not part of the status effects and is its own separate thing so I'm not sure what other statuses might need "layer" support. The RSI support would be needed though.

**Comment by chairbender** [comment]
nvm, I misread the mockups (was looking at the combat doll), I am not sure where the health doll is going to be based on those mockups

**Comment by Zumorica** [comment]
`LayeredTextureRect` essentially completes the second point of this issue

**Comment by AJCM-git** [comment]
They support RSI and animations now
