### ISSUE TITLE
Cargo bounties can be duplicated

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#21198]
## Description
If you have enough of a specific bounty material you can send out more than one crate of it and complete the bounty more than once.

**Reproduction**
1. Find a bounty asking for a specific set of items.
2. ship out multipule crates of the specific bounty
3. obtain money for each crate

Bounty calls for x5 shivs
**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/106507028/f4d603b8-8539-4337-b379-3b09b1a851a5)

Cargo shipping out seperate copies of the bounty
![image](https://github.com/space-wizards/space-station-14/assets/106507028/6ff7012b-4ecf-4260-a9a3-133ed68ee81a)

boom, 80K spesos 5 mins into a round
![image](https://github.com/space-wizards/space-station-14/assets/106507028/ef7c0911-0783-4e75-a11c-dd32e818478d)

**Additional context**
Not sure if this is intended since the bounty is asking for one specific instance of items. If you get a easy to duplicate bounty, players have been doing this obtain unreasonable amount of spessos very early in the round and it trivializes money generation.

**Comment by deltanedas** [comment]
yeah thats definitely bad

**Comment by Brandon-Huu** [comment]
Is anyone working on fixing this?

**Comment by EmoGarbage404** [comment]
> Is anyone working on fixing this?

give me an hour

**Comment by HoidC** [comment]
> > Is anyone working on fixing this?
> 
> give me an hour

will this take more than an hour
