### ISSUE TITLE
Removing people from the medical scanner deletes them

### ISSUE THREAD

**Issue by Skarletto** [space-wizards/space-station-14#21191]
## Description

Removing people from the medical scanner deletes them
**Reproduction**

Shove someone in the scanner to get cloned, be surprised at the lack of body when taking it out. Works on alive players too!
**Screenshots**

https://github.com/space-wizards/space-station-14/assets/122584947/1b27e8fb-0798-4789-82ae-7f95d5356fed

**Additional context**

is all

**Comment by 1Stepka1** [comment]
![image](https://github.com/space-wizards/space-station-14/assets/131589665/ff51673e-510a-4e4a-9a9d-28b2232b2dea)
and
![image](https://github.com/space-wizards/space-station-14/assets/131589665/adb6b76e-01b6-4649-b452-a4f5759d1757)
