### ISSUE TITLE
Replace Librarian with a Record Keeper role, merge Librarian with Service Worker

### ISSUE THREAD

**Issue by NancokPS2** [space-wizards/space-station-14#21208]
From all the RP roles in the game, librarian may be one of the least interactive of all. While psychologist is encouraged to talk about trauma or issue mental health diagnosis, reporter is supposed to communicate events to the crew and investigate, and zoologist has the job of keeping animals in good shape. Librarian is basically a cashier that doesn't sell anything, both in RP and a mechanical sense.  
  
No one goes to the library to read either, so even if someone wants to actually do librarian work and be at the counter, you MAY see someone once every 5 rounds tops. The role is pretty much decorative at best. Since literally anyone can host a DnD session in the rare case it happens.    
But if someone DOES want to read, they'll just fetch whatever book. Its not like library books have any specific topic that anyone would need help finding.
This makes the role almost an anti-slot which could be filled by literally anyone, specially Service Workers.    
  
"But you can make up your own objectives/make your own fun" Yes, everyone can do that, they don't need a role for it, however.
    
------------------------------------------------------------  

For those that like the part about writing stuff down and organizing papers. A record keeper role could be made that is actually intended to do so instead of having a librarian asking for access everywhere.  
  
**Objectives/Responsabilities**: no forced objectives, but they are overall meant to go around the station and document whatever they feel is important. Researched techs, orders from cargo, current prisoners, recent events, etc. Just anything they feel may be worth remembering.  
Unlike the Reporter, they are not supposed to share it publicly. People may request information to them directly or the Record Keeper may leave information at the library that it deems safe for public reading. Records could also be kept locked in the library where only people with service access could fetch (making being a librarian/service worker more enticing).  
  
**Autorithy**: they may not be denied any information when asked without a good reason, unless the Captain or Head of Security say otherwise. They are otherwise as powerless as any other service worker. In case of service workers in the library, the Record Keeper has final say on what documents the worker can give away and to who.   
  
**Access**: Science, cargo, engineering, medical, botany and service. Not theater access (professionals need to keep their secrets). They will need it to document stuff. But they have no access to security or command, they must ask the command personel if they want to know about anything happening behind those doors.  
  
**Interaction and RP opportunities**:  
- Can work with reporters as a source of information or even enter in conflict by withholding it from them.  
- Would pose an interesting role as an antagonist, being able to access so many kinds of information and using it as an advantage, or simply posing as someone wanting to do their duties while entering other departments.  
- Can help communication between departments, removing the need to constantly yell over commons for any little question. They're still just one person so it isn't like it becomes a be all-end all.
- Can help lawyers and other sec stuff get their facts straight and aid in investigations.  
- May assist other roles like cargo or HoP with keeping tabs on required materials or role changes respectively.  
- Can help engineering keep tabs on what needs fixing, specially with low priority stuff.  
- Can document dead crew (which is pretty useful for a variety of reasons)  
- They could be in charge of securing the previously proposed "financial documents" objective for syndies.
  
The role would probably require a time lock due to the access it has.

**Comment by keronshb** [comment]
Record Keeper or Curator could work (the latter exists in SS13).

Race language support isn't in yet but the Curator has a tome that they can read roundstart to understand all (non antag) languages.

There was also talks about giving some more of the magically-attuned crew some harmless spells after the rework. Like giving Chaplains smoke and Curators something similar.

**Comment by deltanedas** [comment]
> Can document dead crew (which is pretty useful for a variety of reasons)


derelict station black box in record keeper room :trollface:

**Comment by mirrorcult** [comment]
this should be a design document at https://github.com/space-wizards/docs, not an issue here

**Comment by NancokPS2** [comment]
> this should be a design document at https://github.com/space-wizards/docs, not an issue here

What is the usual procedure for submitting a design doc? afaik thats only for accepted features.

**Comment by mirrorcult** [comment]
https://docs.spacestation14.com/en/general-development/feature-proposals.html

**Comment by NancokPS2** [comment]
There's already a design doc PRd into the docs. Closing the issue.
