### ISSUE TITLE
Dead players can see rev icons as a ghost

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#21201]
## Description
This is me, deadmin'd on a regular player ghost. I can see rev icons.

![image](https://github.com/space-wizards/space-station-14/assets/106507028/74cb1926-b6b8-47d8-b2e7-dd09c880b7ff)

**Additional context**
Massive metagame info here. Even if we can trust players to "forget" when they get revived it ruins the gamemode. Just dont allow ghosts to see rev icons.

**Comment by GoodWheatley** [comment]
I feel like this vastly improves the quality of watching the round as a ghost, so I’m not really sure removing it is a good idea. Nukies have the same issue where a ghost can immediately see there’s nukies on the warp menu and yet we haven’t moved to remove that, and I haven’t seen any incidents of that being metagamed.

**Comment by Kayek14** [comment]
The reason for making this issue was because a revoultionary round was just metagamed by a security officer that got killed by an anomoly. They saw the rev icons and knew it was a rev round. After being revived they announced over comms.

Anyone could instantly confirm its revs by the shortest of deaths. Metagaming is almost impossible to enforce if there are no admins online to physically see it happening.

**Comment by chromiumboy** [comment]
> The reason for making this issue was because a revoultionary round was just metagamed by a security officer that got killed by an anomoly. They saw the rev icons and knew it was a rev round. After being revived they announced over comms.

Yeah, that should have been ahelped, even if no admins are currently on, it will hopefully be reviewed later and the offender bwoinked. The game explicitly states that you don't remember any of the time you spent dead

**Comment by Subversionary** [comment]
How would you even catch that to even ahelp in the first place, let alone prove to an admin.

I can propose two solutions that are not “outright remove” rev icons:

1) Show icons only if the player is either not participating in a round (Observer) or has been Round Removed (gibbed/incinerated). This ensures the player cant just get revived and start prepping to arrest and catch headrevs out of the blue.

2) Replace headrev icons for ghosts with revs only. This still reveals theres revs in the round (less complaining about getting mobbed) but it doesnt reveal the headrevs so they couldnt be targeted selectively by metagamers.

**Comment by asperger-sind** [comment]
This is just a general "ghosts can see tot" problem, you can do basically the same with any ghostrole antag, nukies, sometimes traitors.

**Comment by Jarmer123** [comment]
> I feel like this vastly improves the quality of watching the round as a ghost, so I’m not really sure removing it is a good idea. Nukies have the same issue where a ghost can immediately see there’s nukies on the warp menu and yet we haven’t moved to remove that, and I haven’t seen any incidents of that being metagamed.

I feel like this is different. You could die for just a split second and the game mode would be revealed, maybe you even see who the head rev is and even if you don't want to metagame there is no way to "Forget" that knoweldge

**Comment by deltanedas** [comment]
ive died before and saw nukies as ghost before being revived, its actually quite easy to just not start yelling NUKIES on common

**Comment by Kayek14** [comment]
Yes its not easy to yell over common that you obtained metaknowledge of nukies or revs. However if that happend to me id be upset because know i know about it, but ill have to pretend that i dont. It ruins the round for me personally.

 Also I dont trust the community to not yell over comms the moment they get revived, it can potentionally ruin the round for everyone if someone metagames it.
 
 Looking for nukies in the teleport menu is a few steps more involved from seeing floating rev symbols on the crew around your dead body. You almost need to go looking for nukies, where sometimes you cant help from not seeing rev symbols.
 
 A good point was brought up earlier here. Perhaps we should only make antag status symbols visable to the player if their character is removed from the round, or if they were antag before they died.

**Comment by Kayek14** [comment]
Closing as #21239 has resolved this issue.

**Comment by nikthechampiongr** [comment]
This is not resolved. #21239 was closed.
