### ISSUE TITLE
Supply comms (:u) not working properly

### ISSUE THREAD

**Issue by AgentWatson** [space-wizards/space-station-14#21205]
Attempting to use :u will result in your character saying "Ou"
-
**Reproduction**
Simply try to use supply comms.

**Additional context**
Using :h with a cargo headset will still allow access to Cargo.

**Comment by keronshb** [comment]
More than likely caused by: #20180

**Comment by keronshb** [comment]
One solution might be to bandaid "u" out of the original PR and then to freeze chat until it's reworked (a rework is in progress by smug)

**Comment by forgotmyotheraccount** [comment]
#21177
