### ISSUE TITLE
Atmos exceptions

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#21210]
![image](https://github.com/space-wizards/space-station-14/assets/31366439/6a7390e8-df3c-41d7-8d42-3f8b642e1830)

**Comment by metalgearsloth** [comment]
Holy moly these get spammed a lot

**Comment by daerSeebaer** [comment]
@metalgearsloth please start using the Issue template and provide context and reproduction steps. They exist for a reason. Because with just a screenshot of an error message, troubleshooting this is hard enough that it probably just won't be attempted.

**Comment by metalgearsloth** [comment]
> @metalgearsloth please start using the Issue template and provide context and reproduction steps. They exist for a reason. Because with just a screenshot of an error message, troubleshooting this is hard enough that it probably just won't be attempted.

I do not know how to replicate, nor have context or repro steps, as screenshot indicates it's from grafana logs.

**Comment by daerSeebaer** [comment]
Thanks for the clarification. Can you at least say which server that was from? Then the situation can be reproduced with the replay

**Comment by TGODiamond** [comment]
Issue probably because of this: #21732
