### ISSUE TITLE
Some lockers are flooded

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#21217]
## Description

Some lockers initially has more items than they can contain.

**Reproduction**

1. Open hop locker
2. Close it
3. Some items doesn't fit inside

**Screenshots**

**Additional context**

**Comment by deltanedas** [comment]
loadouts would fix hop lockers 90% meme items

**Comment by IProduceWidgets** [comment]
Hop needs a walk in closet.

**Comment by lzk228** [comment]
remade in #27741
