### ISSUE TITLE
Update credits workflow is failing due to protected branch rules

### ISSUE THREAD

**Issue by VasilisThePikachu** [space-wizards/space-station-14#21221]
## Description

https://github.com/space-wizards/space-station-14/actions/workflows/update-credits.yml

```
remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: Changes must be made through a pull request.        
To https://github.com/space-wizards/space-station-14
```

According to the documention of the tool used to commit and push the changes this can be fixed by using an PAT token belonging to someone who can directly push to the github (PJBot?). This will require a github secret of course cause why would it not?

https://github.com/stefanzweifel/git-auto-commit-action#push-to-protected-branches

**Comment by VasilisThePikachu** [comment]
@PJB3005 pretty sure you are the only one who has the power to do something here??

**Comment by PJB3005** [comment]
Just have the workflow make a PR automatically then it's 1-click to merge.

**Comment by VasilisThePikachu** [comment]
> Just have the workflow make a PR automatically then it's 1-click to merge.

Thats fine?? It's  kinda meant to be automatic but i can try that

**Comment by VasilisThePikachu** [comment]
Note it runs every week, a pr per week sucks
