### ISSUE TITLE
Nukies sometimes get stuck in place and cannot move.

### ISSUE THREAD

**Issue by IProduceWidgets** [space-wizards/space-station-14#21271]
## Description

Sometimes nukies get stuck and can't move, but they can turn/spin their character, interact with items, see others move, and chat.
I've tried to get logs, but the best I've been able to get teased out is:
"can't resolve robust shared physics components physicscomponet" 
If I were to guess at a source it would be something with changing grids or maps, that could be a wild goose chase though.
I tried many things to get them moving again. None of these worked:

- teleporting them
- sending them to admin test area
- putting them to sleep with nocturine
- FTLing them on the nukie shuttle to the station
- putting them in a new body in the admin test area, on the nukie shuttle, or on the station (if I entered the body I could move it.)
- having them use f10 > disconnect > reconnect
- having them relaunch the client.

**Reproduction**

Sorry, I don't have any repro steps.

**Screenshots**

**Additional context**

If you want to look in a replay (since I have seen people ask in previous issues) you could in round Levi 36595

**Comment by Holinka4ever** [comment]
I got a same problem with salvages, but it go fixed by crossing through fence.

**Comment by IProduceWidgets** [comment]
Railings could possibly have something to do with it. I'll come back and say something if I managed to repro that.

**Comment by dolgovmi** [comment]
Once my nukie buddy was unable to move after vaulting a railing on nukie planet, got fixed after i vaulted him again

**Comment by Skarletto** [comment]
This happened to a player that was on station and I tried: Teleporting them, putting them in a locker, shoving them over a table, sitting and unbuckling them. The player mentioned they had vaulted onto a table and tried diving in a trash bin, so maybe it's not the same bug? But the effect is similar, where they can't move and can only spin

**Comment by IProduceWidgets** [comment]
It does look like its the railings. Maybe its something to do with vaulting off of the grid into "space"? Not sure, but re-vaulting onto a table fixes it.

**Comment by deltanedas** [comment]
i had a similar thing happen and sitting on a chair fixed it

**Comment by deltanedas** [comment]
ok reproduced:
1. get on the infiltrator
2. jump out the back
3. drift towards a docking arm
4. **try to vault a railing**
5. **cant move**
