### ISSUE TITLE
Hotplate doesn't heat stuff up

### ISSUE THREAD

**Issue by Skarletto** [space-wizards/space-station-14#21274]
## Description

Try to heat something up with a hotplate; it doesn't work + the little hotplate light instantly goes out after putting a beaker on it. Microwaves do work however, so you can mix chems in there.
**Reproduction**

Try to heat something up with a hotplate
**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/122584947/a1fdd2e9-aa35-4f69-a387-9c7e7857c13e)

**Additional context**

**Comment by PokkeTigrex** [comment]
While it is possible to use a microwave, its painfully slow, requiring a good three or four times in 30 seconds just to get something to mix. Its not as simple to get a spare microwave either on most stations without service research, so this hotplate bug is pretty rough on chemists.

**Comment by deltanedas** [comment]
> self assign
> dont fix

:trollface:

**Comment by metalgearsloth** [comment]
> > self assign
> > dont fix
> 
> :trollface:

got side-tracked speedrunning packaging for audio rework :trollface:

**Comment by deltanedas** [comment]
evil evil packaging
