### ISSUE TITLE
Stun batons can instantly stun when dropped

### ISSUE THREAD

**Issue by AJimmyU** [space-wizards/space-station-14#21284]
## Description

Overlapping with a human holding a stun baton and stunning/critting said human that's holding a stun baton, will apply the stun on you when they drop it from their hand, potentially multiple times.

**Reproduction**

1. Equip stun baton and turn it on
2. Have someone stand where the baton would drop after you get downed
3. Observe how you have hit/stunned someone by being downed

**Screenshots**

**Additional context**

I've observed the stun baton applying multiple times, resulting in an instant stun, when the person being hit by the dropped/thrown stun baton is moving.

**Comment by slarticodefast** [comment]
Fixed by #30115
