### ISSUE TITLE
you cant make armor fireproof without making it laser proof

### ISSUE THREAD

**Issue by JoeHammad1844** [space-wizards/space-station-14#21290]
## Description

since fire does heat and lasers do heat, theres no way to distinguish between getting shot with a laser and being on fire so firesuits will make you nigh invincible when deathsquad comes knocking
**Reproduction**

spawn in a CBURN guy
spawn in a pulse rifle
shoot the CBURN guy until they go horizontal and count every blast

**Additional context**

firesuits should be fire resistant, but not pulse rifle resistant

**Comment by deltanedas** [comment]
shouldnt even resist fire since the hardsuit is on fire not your flesh
instead it should just insulate from fire heat and have fire damage be proportional to skin temperature, would also mean being on fire in frezon does nothing
