### ISSUE TITLE
Agent's ID should have ability like chameleon clothes

### ISSUE THREAD

**Issue by ElPidor** [space-wizards/space-station-14#21303]
So Agents ID card can change it's appearance to another ID cards 
It will give more possabilities to use it with chameleon kit

**Comment by CatMagic1** [comment]
You can change job icon, but I am unsure if that affects the id card look.

**Comment by deltanedas** [comment]
thats just sechud

**Comment by CatMagic1** [comment]
I would not put it past sec to check people's id's

**Comment by ElPidor** [comment]
> You can change job icon, but I am unsure if that affects the id card look.

t does not change the view of ID card, it always looks like a passanger card for everyone, so if i'd try to pretend being a sec. I first need to steal securiy PDA because all others make questions for everyother player, and then use my agent card, instead this i think it would be easier to let Agents card to change its view, so you can say that you forgot your pda or something else, and people will believe you becase in this situation they will see agents card that looks like sec's card but not like a passanger one

**Comment by lzk228** [comment]
resolved
