### ISSUE TITLE
Swinging sprite for axe is reversed.

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#21326]
## Description
When swinging the fire axe, its the wrong way. Pretty simple, if anyone knows any others like this add em below, I just don't want to check every weapon.

**Reproduction**
Tested with normal and syndi fireaxe.
Swing while in combat more/ right click.

**Screenshots**
Mid swing
![image](https://github.com/space-wizards/space-station-14/assets/47093363/8aefba75-de38-47bd-9fcc-5bc947c85790)

**Additional context**
Still works, just bit silly to not swing with the pointy end.

**Comment by notquitehadouken** [comment]
this is my fault entirely

**Comment by TheShuEd** [comment]
also pickaxe
