### ISSUE TITLE
Meta-actions

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#21348]
Taken from https://discord.com/channels/919301044784226385/1168618530359484476

If roundstart on the sidebar the icons are set correctly, it's extended or traitors.  If they go astray then it's nuke, zombie or rev.  This is due to the fact that agents are not selected by roundstart.  The icons for ghost roles also get confused, especially for ninjas.

**Comment by notquitehadouken** [comment]
so if my actions are fucked up when i join roundstart, it's nukies, zombies, or revs?
hmmmm

**Comment by lzk228** [comment]
should be fixed in #dunno
