### ISSUE TITLE
Wide Attack That Causes Explosion Before Hitting Tool Locker Throws Debug Exception

### ISSUE THREAD

**Issue by SoulSloth** [space-wizards/space-station-14#2135]
Reproduction steps:
1. Do 3 wide attacks that will hit a fuel tank before a locker. 
Expected behavior: Tank explodes, Locker contents are either destroyed or dropped on ground
Actual: Debug assertion fails, Tool Locker is deleted, probably by the welding tank explosion, before the wide attack affects it.

**Comment by SweptWasTaken** [comment]
Still an issue.

**Comment by AJCM-git** [comment]
Cant reproduce anymore because destroying a tank doesn't explode it anymore, and exploding it close to a closet just destroys the closet. No exception.
