### ISSUE TITLE
Storage Issues

### ISSUE THREAD

**Issue by liltenhead** [space-wizards/space-station-14#21359]
## Description
I don't really know what is, or isn't intended with the new storage system. Apparently you're not supposed to be able to hold multiple guns or something in a vest. 

Anyways, gun weights are all over the place as of right now. The bulldog weighs 2, but the enforcer weighs 16. 
Lecter weighs 16, Drozd weighs 4.

The large jump from 4 to 16 makes it so certain items fall into weird categories. Should a laser gun be the same size as an l6? Even though it doesn't require two hands to fire accurately. You have to balance items either taking up a 1/7th of a backpack or taking up over 1/2. 

~~Also the syndicate hardsuit bundle duffel bag is very confusing. There's no real way to understand what you're allowed to put in the backpack, it feels like you're intended to just ditch the bag even though that wasn't the case before.~~ #21362 Fixed this

The screenshots probably explain the issues better than I can. 

![vest](https://github.com/space-wizards/space-station-14/assets/104418166/75e8a1d6-6827-4039-b09e-65391365a440)

**Screenshots**
![shoulder holster](https://github.com/space-wizards/space-station-14/assets/104418166/a08846e9-61b9-46c2-b719-0d316cca0d0d)

![weight2](https://github.com/space-wizards/space-station-14/assets/104418166/97936983-61a1-4719-aa2d-f5a6c8a79553)

**Comment by GoodWheatley** [comment]
Additionally, the RD hardsuit no longer fits into bags, making it much harder to steal
