### ISSUE TITLE
Sprite set for the access configurator

### ISSUE THREAD

**Issue by chromiumboy** [space-wizards/space-station-14#21365]
## Description
The access configurator is currently using a palette swapped network configurator. Just wanted to request a proper set sprite for it

**Comment by notquitehadouken** [comment]
it is?

**Comment by chromiumboy** [comment]
> it is?

Yes, it is. I know, because I'm the one who made it :P

**Comment by UbaserB** [comment]
Ok im taking up completing this pull request, can you assign me?

**Comment by LordEclipse** [comment]
> Ok im taking up completing this pull request, can you assign me?

There is no assigning, you can just say "I'm gonna do this" and hope people see that. and then you do it!

**Comment by deltanedas** [comment]
pros can assign themselves to issues :trollface:

**Comment by UbaserB** [comment]
Ive technically finished making the sprite just finalising the PR now :3

**Comment by UbaserB** [comment]
[21423]
