### ISSUE TITLE
Stripping should be slower

### ISSUE THREAD

**Issue by liltenhead** [space-wizards/space-station-14#21379]
## Description
Being able to strip an entire body in less than five seconds is pretty crazy. I feel like you should only really be able to take one item off at a time. Being able to kill someone and strip them completely naked nearly instantly is kinda odd for gameplay and in general just looks wrong with thirty bars above your head. 

**Screenshots**

![menu](https://github.com/space-wizards/space-station-14/assets/104418166/e629a278-e42f-4572-88cb-6dd914b729f5)

**Comment by Eden077** [comment]
Realistically instead of making stripping slower, you can just make it so the doafter get's cancelled if you try to strip more than one thing

**Comment by asperger-sind** [comment]
Imo this isn't too bad, if anything you should be limited to 3 concurrent doafters at a time.

This doesn't affect that much for gameplay purposes, if you kill someone and opt to strip them you probably have enough time to strip everything you need even if you don't strip everything at once, but yes, this certainly doesn't make much logical sense, in what world can you strip an entire body in a hardsuit within some three seconds.

**Comment by keronshb** [comment]
No it was made this way because stripping was absolutely too slow.

**Comment by deltanedas** [comment]
when being cloned fast stripping is essential otherwise you 100% rely on the person cloning you to strip your stuff slowly

**Comment by Aisu9** [comment]
can't there be a tweak for the biomass reclaimer to spit out everyone not organic?

**Comment by TurboTrackerss14** [comment]
I am in agreement with lilten that basically instant stripping a body in ~5 seconds just feels lame. 
Adding an upper limit (3-5) would be sane as it would prevent a body becoming entirely nude in seconds. 
This limit would also help with searches, incentivising sec to strip pockets bag and backslots instead of dumping an entire bodies worth of loot on the ground mashing the drop key. 

@deltanedas While I can agree here, surely its a morticians/doctors to do this very basic task while the cloner is doing its job? (also what cloning :godo:)

Another viable, albeit "harder" solution would be to impliment different strip timers for different slots. 
I can cram my hand in your pocket and take whats in there in moments, but to yank your backpack or even hardsuit/jumpsuit... that would take a lot longer.

**Comment by deltanedas** [comment]
salv can find cloning stuff

**Comment by deltanedas** [comment]
idea i had is make concurrent stripping scale with hand count
jumpsuit bag and outer clothing take 2 hands to remove so cant remove suit and something else at the same time, but can empty both pockets at once
arachnids if/when they get 4 hands would be able to speedstrip better

**Comment by liltenhead** [comment]
I personally don't have much else to add overall. I think forcing a player to click as fast as they possibly can in order to strip more items is very odd for a game like this. I think of games like Tarkov that limit how many actions you can be doing at a second. For example, you can't be looting and healing in Tarkov due to your hands being "busy".

I think stripping should actually require your hands to be free, so pretty much like Delta's most recent comment.

**Comment by keronshb** [comment]
> Another viable, albeit "harder" solution would be to impliment different strip timers for different slots.

This is already in place as of a year ago.

> I personally don't have much else to add overall. I think forcing a player to click as fast as they possibly can in order to strip more items is very odd for a game like this. I think of games like Tarkov that limit how many actions you can be doing at a second. For example, you can't be looting and healing in Tarkov due to your hands being "busy".

It's _way too slow_ if you force 1 at a time. 1 at a time is more of a HRP gimmick than it is for NRP-MRP gameplay.

This is especially so if you're trying to be stealthy.

Let's say Cult is in and you need to strip & check someone for:
- A Radio Headset
- A PAI
- A handheld radio

Doing this one at a time will be exceptionally slow to the point where you'd have to stun someone multiple times, basically GBJing them, to be able to do a successful convert.

This is in comparison in being able to do a quick strip + convert.



> jumpsuit bag and outer clothing take 2 hands to remove so cant remove suit and something else at the same time, but can empty both pockets at once

This is a HRP mechanic

**Comment by liltenhead** [comment]
Taking 20 seconds to strip someone is considered an extreme crawl? If anything slowing it down would be nice in nukies where the second a nukie dies all of their equipment is pried off before they even hit the floor. 

I also don't know what you mean by having to restun people. You can just strip someone while they're buckled to a chair or something.

But I also don't know what you're talking about with cult mechanics either, I haven't ever seen a cult in my short time with 13, and we don't have cult mechanics here.

**Comment by keronshb** [comment]
> Taking 20 seconds to strip someone is considered an extreme crawl? If anything slowing it down would be nice in nukies where the second a nukie dies all of their equipment is pried off before they even hit the floor.

I'm planning on having nukies start with their microbomb implants, so this is covered.

> I also don't know what you mean by having to restun people. You can just strip someone while they're buckled to a chair or something.

People can still struggle to release from chairs/restraints or yell for help. Having longer stripping keeps them restrained for longer than needed.

> But I also don't know what you're talking about with cult mechanics either, I haven't ever seen a cult in my short time with 13, and we don't have cult mechanics here.

The flow is:
Stunhand (mutes & stuns for a few seconds) > Cuff > remove headset & other radios > convert

The process itself takes awhile on its own. If someone has something that blocks their head/ears, then the person will first need to remove that, THEN remove the headset.

It just makes the entire process a slog.

While we don't have cults in yet, I'm planning on working on clock cult sometime after Wizard (and atmos probably). Assuming it gets approved, it'd be with the current strip time in mind.

**Comment by Brandon-Huu** [comment]
> I'm planning on having nukies start with their microbomb implants, so this is covered.

Please no

**Comment by keronshb** [comment]
Asked some other maintainers, this could work as a cvar but not a standard because it just slows down gameplay.

**Comment by keronshb** [comment]
Wrong button
