### ISSUE TITLE
The context menu doesn't load for players that you haven't loaded as an admin

### ISSUE THREAD

**Issue by DrSmugleaf** [space-wizards/space-station-14#21386]
## Description
**Reproduction**
- Connect as an admin
- Right click a player that is far away from you through the F7 players panel or AHelp window
- Waiting for server permanently since they were never sent to the admin's client by the server
- Teleport to the player through the AHelp window
- The context menu now loads

**Comment by notquitehadouken** [comment]
pvs back at it again
