### ISSUE TITLE
Nothing is building due to issues with the Watchdog.

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#2138]
![image](https://user-images.githubusercontent.com/49448379/94356200-1cdaa280-007b-11eb-986c-d5936cafe789.png)

**Comment by DrSmugleaf** [comment]
Fixed by https://github.com/space-wizards/space-station-14/commit/ed3a3630b1e9c4c24c1b69e0a07614beb53b68a1
