### ISSUE TITLE
Cyborgs are missing a crit state and will break at 100 hp

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#21389]
## Description
Cyborgs get their shell destroyed too quickly. They have a total of 100 Health and no crit state. They simply break when hitting the 100 damage threshold. They should have the 200 total HP that all other playable races have. Perhaps they should go offline or lose the ability to move and use modules but reain the ability to speak when past the 100 damage instead of just breaking.

It is very frustrating to have your shell break when taking 100 damage. Borgs have no damage resistance that i am aware of and it feels as if they are too fragile. Often times when your shell breaks it is a round removal. People will often either ignore your MMI or science wont have the materials or want to dedicate the time to making you a new shell.

**Additional context**

**Comment by EmoGarbage404** [comment]
Resolved by #21307

**Comment by Kayek14** [comment]
darn i looked for an issue before making this but missed that one. Thanks! 

Closing since its resolved.
