### ISSUE TITLE
Cyborgs take structural damage

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#21390]
## Description
Cyborgs will take structural damge when hit with weapons that can apply that damage type. 

Not sure if this is intended, but it feels really bad to take extra damage when cyborgs have no way of getting any type of damage resistance that i am aware of.

**Reproduction**
Hit a cyborg with a weapon that does structual damage and use a health analyser to check the damage.

**Screenshots**
being hit with an emergency crowbar:
![image](https://github.com/space-wizards/space-station-14/assets/106507028/4aa19abc-fe8d-45b6-bf49-a669a2b7d36e)

**Comment by NeviNovat** [comment]
It kind of makes sense though.
Maybe make borgs take more damage before they break and keep things as is? Or make borgs have damage resistances to other types of damage but not structural?
But I think that if they are immune to poison and maybe radiation damage, being vulnerable to structural damage balances things out.

**Comment by KompaniLinge** [comment]
> It kind of makes sense though. Maybe make borgs take more damage before they break and keep things as is? Or make borgs have damage resistances to other types of damage but not structural? But I think that if they are immune to poison and maybe radiation damage, being vulnerable to structural damage balances things out.

Yea but borgs are already pretty fucking weak, like wet tissue paper level weak.

**Comment by notquitehadouken** [comment]
> > It kind of makes sense though. Maybe make borgs take more damage before they break and keep things as is? Or make borgs have damage resistances to other types of damage but not structural? But I think that if they are immune to poison and maybe radiation damage, being vulnerable to structural damage balances things out.
> 
> Yea but borgs are already pretty fucking weak, like wet tissue paper level weak.

you'd turn out to be weak too if people starting beating you to death with crowbars

**Comment by KompaniLinge** [comment]
> > > It kind of makes sense though. Maybe make borgs take more damage before they break and keep things as is? Or make borgs have damage resistances to other types of damage but not structural? But I think that if they are immune to poison and maybe radiation damage, being vulnerable to structural damage balances things out.
> > 
> > 
> > Yea but borgs are already pretty fucking weak, like wet tissue paper level weak.
> 
> you'd turn out to be weak too if people starting beating you to death with crowbars

Difference is, i'm not made out of pure steel and plastic. From both a balancing perspective and a gameplay perspective, having borgs their current HP is bad.
From a game balance sense due to how absolutely expensive borg parts are, and from a gameplay perspective because of how annoying it can be to play as a borg. The amount of times salv-borgs die to carps is absurd.

**Comment by IProduceWidgets** [comment]
> > > > It kind of makes sense though. Maybe make borgs take more damage before they break and keep things as is? Or make borgs have damage resistances to other types of damage but not structural? But I think that if they are immune to poison and maybe radiation damage, being vulnerable to structural damage balances things out.
> > > 
> > > 
> > > Yea but borgs are already pretty fucking weak, like wet tissue paper level weak.
> > 
> > 
> > you'd turn out to be weak too if people starting beating you to death with crowbars
> 
> Difference is, i'm not made out of pure steel and plastic. From both a balancing perspective and a gameplay perspective, having borgs their current HP is bad. From a game balance sense due to how absolutely expensive borg parts are, and from a gameplay perspective because of how annoying it can be to play as a borg. The amount of times salv-borgs die to carps is absurd.

I'm hopeful some of this will be partly remedied in [#21307]

**Comment by Kayek14** [comment]
This will be good because cyborgs literally die in 2 hits from a wielded fireaxe. Im not a structural engineer or game designer but something that is made out of steel shouldent be more vulnerable to an axe than flesh and bone.
