### ISSUE TITLE
Fingerless gloves not butcherable.

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#21394]
## Description
Title says it call, you cant butcher/break down fingerless gloves in to cloth. Tried with the regular ones in cargo vend and also the insulated one.

**Reproduction**
- get knife/ broken shard of glass
- attempt to butcher
- fail to do so as the action doesn't exist.

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/47093363/75e22903-77b9-48c3-89f2-2c074115e758)

**Additional context**
Looks easy, probably small change. Might be more gloves than just those standard fingerless ones.

**Comment by deltanedas** [comment]
no gloves can be turned into cloth 
would maybe be funny if cutting tips off gloves gave you a piece of cloth as well :trollface:

**Comment by Titian3** [comment]
> no gloves can be turned into cloth would maybe be funny if cutting tips off gloves gave you a piece of cloth as well :trollface:

This is true now i think of it. Should they be? was it just missed?

**Comment by UbaserB** [comment]
This got fixed so the issue should be closed
