### ISSUE TITLE
Double Order Bounties. 

### ISSUE THREAD

**Issue by KaiShibaa** [space-wizards/space-station-14#21395]
You are able to print two of the same manifest and package them in two different crates. 

Two breads, two crates and one bread in each. 

You get paid a double amount due to this if you send both at the same time.

**Comment by daerSeebaer** [comment]
Thanks for reporting this, but that issue is already logged under #21198

**Comment by daerSeebaer** [comment]
This issue was fixed in #21399 . @KaiShibaa you can close it now
