### ISSUE TITLE
Thieving gloves don't function.

### ISSUE THREAD

**Issue by QuietlyWhisper** [space-wizards/space-station-14#21396]
## Description

They simply don't do anything. People can see the do-after and also see the item transferring to your hand.

Edit: all they do is hide the text popup, which seems kind of pointless

**Comment by deltanedas** [comment]
they half the doafter duration
common tactic is to drink something while doing it so it doesnt look to sus, no popup and its fast so victim is none the wiser

**Comment by HoidC** [comment]
when an item is useful in essentially one location (the bar next to the counter) it probably needs a fix

**Comment by QuietlyWhisper** [comment]
Didn't it use to hide all interactions, the item visibly being transferred to your sprite, the doafter...?

**Comment by HoidC** [comment]
> Didn't it use to hide all interactions, the item visibly being transferred to your sprite, the doafter...?

nah I’m pretty sure it’s always been broken

**Comment by lzk228** [comment]
the main thing that a person doesn't see 
#  Urist McGreytide trying to take off your captain's PDA

**Comment by TemporalOroboros** [comment]
Even if it wasn't originally intended to work that way, the gloves hiding the progress bar/item move animation makes sense.
