### ISSUE TITLE
Cyborgs should be the only ones who have access to open their panel

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#21407]
## Description
Cyborgs should be the only ones who have access to their panel since it makes them extremely vulnerable.

At the moment, any crewmember with a screwdriver can open a borgs panel and remove the MMI in one button press and about one second. This makes it too easy to grief the cyborg. Players who feel slighted by the cyborg can easily remove them from their shell, and ion stormed cyborgs get their RP runied by one quick screwdriver and a button push.

**Additional context**
Perhaps make it so emags force open the panel or give crewmembers a longer or more complicated method of opening a panel. 

Getting your RP runied when the rare ion storm gives you a law 0 rule because you were too slow to notice the <1 second screwdriver animation and some random crewmember can force you out of your shell in one button press feels really bad gameplay wise.

This changes nothing in regular cyborg gameplay since a crewmember can law 2 it to open panel. It is more so to give a cyborg an added layer of protection against griefers or for their law 0 RP.

**Comment by mirrorcult** [comment]
just needs to be access locked like ss13

**Comment by deepy** [comment]
Or require some wrench action to remove the MMI after the panel is open

**Comment by EmoGarbage404** [comment]
This got implemented with the borg qol pr emisse made
