### ISSUE TITLE
ambuzol makes you unkillable by zombies

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#21402]
## Description
If you have ambuzol or ambuzolplus in your system, and in crit, zombie bites seem to heal you. They can be spam attacking you while you have the drug in your system and you will never fully die or convert while it is in your system.

Normaly ambuzol is supposed to prevent conversions, but it seems to also stop all damage taken when attacked by a zombie while in crit.

**Reproduction**
1. Inject ambuzol or ambuzolplus 
2. get crit 
3. have a zombie try to attack you
**Videos**

With ambuzol in your system:

https://github.com/space-wizards/space-station-14/assets/106507028/0962ad07-32c6-401e-9991-9c9d939c4c14

Same thing with ambuzolplus in your system:

https://github.com/space-wizards/space-station-14/assets/106507028/d78c1a27-69b1-4a87-a3cf-e0d0e9ccc5f5

**Additional context**
If a zombie attacks you when you have ambuzol in your system you should probally just take damage and die. Being 100% immune to zombie damage if you have it in your system is broken.

Sometimes a zombie attack seemingly heals you out of crit when they attack you. Ive seen a crit person stand back up and run away when getting attacked by zombies when they were in crit.

**Comment by themias** [comment]
I was unable to reproduce this with Ambuzol alone. Was the Urist in zombiebug2.mp4 given Ambuzol Plus at some point?

**Comment by Kayek14** [comment]
> I was unable to reproduce this with Ambuzol alone. Was the Urist in zombiebug2.mp4 given Ambuzol Plus at some point?

Yes i used ambuzol plus on the same urist, after it expired from the body soultion i added the ambuzol to test that as well.
