### ISSUE TITLE
You remove drag slowdown on bodies if you stam crit them while dragging

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#21400]
## Description
While draging a body you are met with a slowdown. If you shove spam them and put the body into stam crit you are able to remove the slowdown. This also applies to dead bodies as well.

**Reproduction**
1. Drag a body that is in crit or dead. 
2. Shove them untill they are knocked down.
3. You now have no slowdown while draging the body.

**Screenshots**
Pushing down a crit body while dragging it:
![image](https://github.com/space-wizards/space-station-14/assets/106507028/314376a9-32d1-45e9-bac2-bfa348557d4f)

**Additional context**
Dosent make much sence to be able to shove down a body that is already down and for it to remove drag slowdown.

**Comment by deltanedas** [comment]
i saw people do that and thought it was just funny not pro strat

**Comment by UbaserB** [comment]
its a pro strat lol, i know since i also abuse it

**Comment by Kayek14** [comment]
i see alot of people (ab?)using this strat. At first I dident know why, then i realized that people will often do this when draging someone into medical and the slowdown was gone. Paramedic mains despair when this gets fixed.

**Comment by UbaserB** [comment]
> i see alot of people (ab?)using this strat. At first I dident know why, then i realized that people will often do this when draging someone into medical and the slowdown was gone. Paramedic mains despair when this gets fixed.

literally though, body bags and roller beds are overwhelmingly better than simply dragging (even with this bug). It's just that most paramed mains are lazy and don't put in enough effort on what they want to specialise in.
