### ISSUE TITLE
electric grill needs good sprite

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#21439]
## Description
codersprite so bad :trollface:

**Comment by IamVelcroboy** [comment]
Maybe it's asking too much but would be nice if it was rotatable as well...

**Comment by ps3moira** [comment]
I think I can cook something up

**Comment by DogZeroX** [comment]
Personally I think they should be tables so you can expand the grill with smoothing, it would be neat

**Comment by ps3moira** [comment]
> ## Description
> codersprite so bad :trollface:
Here's the PR for the resprite I made
https://github.com/space-wizards/space-station-14/pull/21503
