### ISSUE TITLE
Nukies need to have more playtime requirements

### ISSUE THREAD

**Issue by Everturning** [space-wizards/space-station-14#21440]
A lot of nukies have no idea the controls of the game, and nukie commanders have criminally low playtime requirements. Only ten hours for nukie commander, and nothing is required in order to play nukie. I like the sound of 4 hours of sec for normal nukies, and 12 hours sec 12 hours general playtime for nukie commanders.

**Comment by deltanedas** [comment]
wyci just change a few numbers

**Comment by Brandon-Huu** [comment]
> A lot of nukies have no idea the controls of the game, and nukie commanders have criminally low playtime requirements. Only ten hours for nukie commander, and nothing is required in order to play nukie. I like the sound of 4 hours of sec for normal nukies, and 12 hours sec 12 hours general playtime for nukie commanders.

There should be a in-game tutorial you have to complete

**Comment by IProduceWidgets** [comment]
> > A lot of nukies have no idea the controls of the game, and nukie commanders have criminally low playtime requirements. Only ten hours for nukie commander, and nothing is required in order to play nukie. I like the sound of 4 hours of sec for normal nukies, and 12 hours sec 12 hours general playtime for nukie commanders.
> 
> There should be a in-game tutorial you have to complete

I do think it would be really cool to have nukies enter a virtual reality pod to do a practice attack first, but it would just take too long for an every round kinda deal.

**Comment by keronshb** [comment]
No more role timers please.
