### ISSUE TITLE
Mouse Punch Bug

### ISSUE THREAD

**Issue by ps3moira** [space-wizards/space-station-14#21448]
## Description

Pretty much whenever you punch a mouse while holding it with the other, your game freaks out then crashes.
**Reproduction**

Punch mice with bare hand while holding it with the other.
**Screenshots**

![mouse punch bug](https://github.com/space-wizards/space-station-14/assets/113228053/556fca82-4454-4749-8b0f-b9a7f16e13d2)

**Additional context**

**Comment by SebaenSah** [comment]
Does this crash the server as well or just your client?

**Comment by slarticodefast** [comment]
Tested it and it worked fine now. See #29703
