### ISSUE TITLE
rd hardsuit fits in toolbelt

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#21488]
## Description
saw in lilten video bruuuuuh

**Comment by notquitehadouken** [comment]
meta??????

**Comment by deltanedas** [comment]
cause: geiger counter component or tag letting hardsuits fit in toolbelt

**Comment by UbaserB** [comment]
![image](https://github.com/space-wizards/space-station-14/assets/134914314/90b4d5cd-17ac-4a26-8035-7deba6836e54)

Looks intended.

**Comment by deltanedas** [comment]
its because geiger counter component inherited

**Comment by UbaserB** [comment]
> its because geiger counter component inherited

No i mean, the suit description literally explains that it's able to compress itself so it fits into small spaces.

**Comment by deltanedas** [comment]
still doesnt make sense to hang off a belt (invisibly)

this is probably the only reason why bozosec search belts

**Comment by UbaserB** [comment]
> still doesnt make sense to hang off a belt (invisibly)
> 
> this is probably the only reason why bozosec search belts

i like to think of it as compressing itself into this small packet like those foldable bags.

**Comment by deltanedas** [comment]
then why is it normal not small/tiny :trollface:

**Comment by UbaserB** [comment]
> then why is it normal not small/tiny :trollface:

Because it's still a hardsuit and there's a limit to how much it can compress.

**Comment by deltanedas** [comment]
yet it can compress better in belt than bag :trollface:

**Comment by slarticodefast** [comment]
![Screenshot (199)](https://github.com/user-attachments/assets/3a69c2c1-0ecd-432e-8a6c-ca5567b4edc4)

This is fixed now thanks to grid inventory and item sizes.
