### ISSUE TITLE
Heat damage no longer seems to cauterize

### ISSUE THREAD

**Issue by QuietlyWhisper** [space-wizards/space-station-14#21491]
## Description

Normally this is something I would take care of because I know the code, but nothing's been changed in the system, I'm guessing something else broke it?

**Reproduction**

Any form of heat damage should cauterize bleeding.

bleed rate modifiers are unchanged...
![image](https://github.com/space-wizards/space-station-14/assets/121047731/ffc90ebc-4a1a-4261-878f-933c3bd315ca)

I can't however, find any usage of this modifier set anymore in mob yml, which might be why it's broken, unless this is the default regardless, in which case I have no idea where the issue is

**Comment by deltanedas** [comment]
confirmed
doesnt remove bleeding or the alert

**Comment by Hmeister-fake** [comment]
Someone do this (please I want a reason to carry a cautery again)

**Comment by metalgearsloth** [comment]
Pre sure it was from itemtoggle refactor.

**Comment by themias** [comment]
Looks like we ignore negative damage modifiers after #20820, so we might need to either allow that or handle cauterization another way.
