### ISSUE TITLE
Bullets/projectiles shouldn't hit people on the floor in crit, unless they're aimed at

### ISSUE THREAD

**Issue by keronshb** [space-wizards/space-station-14#21497]
Based on this discussion in discord (see pinned post): https://discord.com/channels/310555209753690112/1171134829253906432

SPECIFICALLY _**on the floor**_ and _**in crit**_

If they're in a chair/vehicle/etc and in crit it should 100% hit still

**Comment by notquitehadouken** [comment]
Corpse Shooting Simulator 2023 release cancelled????????????????????

**Comment by Kayek14** [comment]
https://github.com/space-wizards/space-station-14/issues/10143#issue-1322678177

From an issue from last year, Might be intended? 

Just wanted to post here for more info.

**Comment by NeviNovat** [comment]
There is still a need to be able to target people in crit at a distance, especially since some syndicates agents have "kill" objectives, and not "crit" objectives.
Like a good fix would be if you shoot specifically at them you will hit them even when in crit, otherwise it will pass over them.

**Comment by keronshb** [comment]
> There is still a need to be able to target people in crit at a distance, especially since some syndicates agents have "kill" objectives, and not "crit" objectives. A good fix would be if you shoot specifically at them you will hit them even when in crit, otherwise it will pass over them.

I actually forgor to put the rest of the title, what you said is intended.
