### ISSUE TITLE
revenant can hijack shuttle

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#21499]
## Description
fucking disgusting

**Comment by EmoGarbage404** [comment]
Can you be slightly more verbose in the issue

**Comment by deltanedas** [comment]
if a revenant uses the emag ability on evac it will hijack the shuttle and early launch

**Comment by notquitehadouken** [comment]
feature

**Comment by deltanedas** [comment]
its horrible it lets you instantly launch evac without anyone having time to get on

**Comment by dvir001** [comment]
> its horrible it lets you instantly launch evac without anyone having time to get on

From Discord:
![image](https://github.com/space-wizards/space-station-14/assets/39403717/5fd4e3d1-f436-4b5f-9939-72c3d86398b8)

**Comment by Geekyhobo** [comment]
New antag rev objective, hijack shuttle. Real
