### ISSUE TITLE
Winter boots require departmental sprites

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#21540]
## Description

As the person who originally made the winter boot sprites, it was originally going to have a version for every department so it can match with the coat variant, but i never got around to doing it. So, every department that has a winter coat should also have winter boots able to be dispensed.

**Comment by TheKilk** [comment]
Hey, is this post still relevant? I just made icons for some boots.
![WinterBootsAtmosIcon](https://github.com/space-wizards/space-station-14/assets/142771861/4d85d5b3-7b2d-4d8e-a9d6-c19765434a96)
![WinterBootsCapIcon](https://github.com/space-wizards/space-station-14/assets/142771861/661666b9-a876-42b2-8285-9d2d1e4139d4)
![WinterBootsCargoIcon](https://github.com/space-wizards/space-station-14/assets/142771861/9cb55f49-64c1-44f8-b763-d0a9d7123e9d)

**Comment by UbaserB** [comment]
Still relevant!

**Comment by TheKilk** [comment]
I have problems with launching the game and testing, can you help?
I get the following error
![Select C__Windows_system32_cmd exe 11_19_2023 11_11_22 AM](https://github.com/space-wizards/space-station-14/assets/142771861/1a348a21-22e1-486f-bd6b-52c7e7e3c952)

**Comment by UbaserB** [comment]
Im not great at debugging, you should probably go to the discord for this

**Comment by TheKilk** [comment]
How do I request a review of my PR?

**Comment by UbaserB** [comment]
on the discord
