### ISSUE TITLE
Moths need emergency cloth in their survival box

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#21544]
## Description

Moths currently cannot eat anything other than clothing and cloth. In an emergency where they have no access to food, they cannot eat their canned meat in their survival box. For such emergencies, they require moth-exclusive rations.

Some examples to solve this issue would be to provide a new item like condensed wool or fabric, or simply provide half a stack or less of cloth.

**Comment by CatMagic1** [comment]
Fun fact: slimes still have oxygen in their emergency tank.

this is the most wyci bs I have ever seen

**Comment by Hmeister-fake** [comment]
> Fun fact: slimes still have oxygen in their emergency tank.
> 
> this is the most wyci bs I have ever seen

Centcom in universe would not care about species specific boxes, they just give out the same to everyone without care

**Comment by BYONDFuckery** [comment]
> > Fun fact: slimes still have oxygen in their emergency tank.
> > this is the most wyci bs I have ever seen
> 
> Centcom in universe would not care about species specific boxes, they just give out the same to everyone without care

its gameplay issue, lore is secondary to fun gameplay

**Comment by thebadman4662** [comment]
Just replace emergency meal with bottle of slime at this point. Every race can eat it, Every race can get nutrients from it without getting sick.

**Comment by LankLTE** [comment]
I've said this before, but I think the best solution for this is to replace the canned meat with an MRE, then let moths eat the MRE's wrapper.

**Comment by UbaserB** [comment]
theres an mre or nutribrick or whatever so moths can eat now
