### ISSUE TITLE
Reagent Slime ghost role desc too friendly

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#21559]
## Description
When some of the reagent slime ghost roles spawn the description is too friendly, some players may think it is not an antag role.
Default behavior for the AI mob is to attack but the ghost role description makes it sound like they are friends of the crew.

**Reproduction**
Spawn a few reagent slimes check ghost description.
OR
Get a liquid anom to go crit.

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/47093363/beb621b5-88fb-49f4-ab0d-481a5415d718)

**Additional context**
Raising this as it is in conflict with the Friendly antag rule.

**Comment by TheShuEd** [comment]
they shouldn't have ghost roles at all

**Comment by Titian3** [comment]
Closing as ghost role was removed from reagent slimes.
