### ISSUE TITLE
ERT lector variant has a pistol magazine for no reason

### ISSUE THREAD

**Issue by gostt899** [space-wizards/space-station-14#21568]
## Description
When a ERT security/leader lector variant spawns in they have a pistol magazine but no pistol. 

**Reproduction**
Spawn in a ERT sec/leader lector variant and check the backpack.

**Screenshots**
![Screenshot 2023-11-10 170836](https://github.com/space-wizards/space-station-14/assets/137981496/6ee68193-a083-4521-81d4-c5899494b335)

**Comment by gostt899** [comment]
the pistol you see is from the other EVA variant of sec ERT that I was playing with before

**Comment by QuietlyWhisper** [comment]
This is because the base ERT sec have pistols, you'd need to make a second backpack with no pistol mag which seems like a waste of space

**Comment by gostt899** [comment]
> This is because the base ERT sec have pistols, you'd need to make a second backpack with no pistol mag which seems like a waste of space

I guess that makes sense. I don't know how the code behind it works after all.
