### ISSUE TITLE
Lose access to storage implant if off hotbar

### ISSUE THREAD

**Issue by SBBurzmali** [space-wizards/space-station-14#21569]
## Description
If you purchase a storage implant as a syndicate, and implant it, the icon shows on the hotbar on the left of the screen. If you then right-click the icon, it is removed. Normally, you can access all actions from the menu at the top of the screen and re-add them to the hot bar by dragging, but that doesn't seem to work for storage implants, the icon lights up when clicked, but can't be dragged.

**Reproduction**
1. As Syndicate member, buy storage implant
2. Use implant on self
3. Right-click on icon on left hot bar to remove icon
4. Lose access to storage implant as Actions menu can't replace it and you have no other way to open it.

**Comment by Yousifb26** [comment]
You can disconnect reconnect to get it back but it’s still an issue none the less

**Comment by TsjipTsjip** [comment]
Is this resolved temporarily by running `resetallents` in the console or `/resetallents` in the chat bar?

**Comment by ElectroJr** [comment]
The action can actually still be dragged, it just doesn't draw the dragged action because of a bug.
