### ISSUE TITLE
remote door prying on vehicle

### ISSUE THREAD

**Issue by Tunguso4ka** [space-wizards/space-station-14#21562]
## Description

Prying doesnt stops if you are moving in vehicle.

**Reproduction**

1. Get a PussyWagon
2. Find a door
3. Start prying.

**Screenshots**

https://github.com/space-wizards/space-station-14/assets/71643624/72cd732c-41c8-4c72-92e5-555df6e8eee8

**Additional context**

**Comment by Fromoriss** [comment]
Also, you can't drive through closed curtains for some reason
