### ISSUE TITLE
Emagged borgs, if emagged only once has a conflict in chassis vs. laws

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#21577]
## Description

I was an emagged engineering borg after i changed chassis from being a roundstart borg, while a janitorial robot was also emagged after me. Both chassis's had their law-governing internals damaged when examined and my law 0 looked normal. However, when i went afk irl and came back (did NOT go SSD) they moved me into the janitorial borg. I noticed that i was not emagged, however when i checked my chassis i was still emagged. The previous person in the janitorial robot also said that they also noticed the issue of laws not showing up. Also important to note that the locking mechanism on the borg was broken (nothing showed up on right click relating to locking access).

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/134914314/905ab7a9-1895-4351-8298-386a94d8771f)

**Additional context**

Round number #37871

**Comment by Veritius** [comment]
@EmoGarbage404
