### ISSUE TITLE
Glass firelocks have no wires to hack

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#21570]
## Description
Glass firelocks are missing wires when opening the hacking window. Regular ~firelocks~ airlocks still have them.

**Reproduction**
1. Open the pannel of a glass firelock.
2. Open the hacking window

**Screenshots**

Glass firelock:
![image](https://github.com/space-wizards/space-station-14/assets/106507028/469a601b-e167-472e-93a4-23114d910241)

Airlock:
![image](https://github.com/space-wizards/space-station-14/assets/106507028/14e03805-693d-4756-938b-30b66171a274)

**Comment by deltanedas** [comment]
thats an airlock not a firelock :trollface:

both kinds of *actual* firelock have no wire layout

**Comment by Kayek14** [comment]
Issue is is that firelocks should have wires and should be able to be hacked. They can be bolted with the atmos firelock remote i believe, with no wires you are unable to unbolt without the remote.

**Comment by Kayek14** [comment]
This issue seems to be resolved. You now no longer get a wire UI screen with glass airlocks.
