### ISSUE TITLE
Med-Sci encryption key only gives science radio access

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#21574]
## Description

Read title. It's supposed to give both med and sci but it doesn't.

**Comment by themias** [comment]
Hmm, I'm not able to reproduce this with either the medical research headset or manually inserting a med-sci key. Which scenario did you experience this?

**Comment by UbaserB** [comment]
> Hmm, I'm not able to reproduce this with either the medical research headset or manually inserting a med-sci key. Which scenario did you experience this?

In-game while trying to insert a med-sci key into a science headset

**Comment by beck-thompson** [comment]
I could not reproduce this! The key appears to work correctly now. (Tested in an empty passenger headset and a science headset, both could send and receive medical channel messages)
