### ISSUE TITLE
can get x-ray vision after ghosting and being revived

### ISSUE THREAD

**Issue by Slava0135** [space-wizards/space-station-14#21584]
## Description

happened in round #37903

**Reproduction**

1. Ghost (/ghost) when in crit (get a lot of bloodloss or asphyx or something, i dunno, i got shot many times)
2. Get revived
3. ???
4. Full FoV unlocked :rocket:

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/40753025/cde205f3-fb26-4059-ba1e-319a405d1199)

**Additional context**

i ghosted when crit twice this round (first time didn't cause the issue)

**Comment by ElectroJr** [comment]
Can you actually reproduce it using those steps or is it just a guess, cause I can't seem to reproduce it using those steps.

Also, in future its good to include the f3 debug overlay in screenshots. E.g., it makes finding the right time in a replay much easier (though the replay didn't help in this case, it seems to be some client-side bug).

**Comment by ElectroJr** [comment]
#21595 might have replication steps that work

**Comment by deltanedas** [comment]
ive experienced it before but never figured out how to reproduce. relogging fixed it

**Comment by Slava0135** [comment]
> #21595 ~might have replication steps that work~
> 
> Nope, doesn't seem to be enough to reproduce it either
> video.mp4

i guess for this to work, you would need to
1. Ghost
2. Get revived
3. Die before (or right when?) you return to body

i didn't get second prompt when this happened, I would try this:
gunning down someone (maybe around 125 dmg so they bleed out massivly), ghosting, get revived and use meds (not sure which ones were used, i guess dex+ and bic? watch replay maybe).

I think maybe client considered me dead for a moment (because damage is shared), but server didn't because chems are server-side (so basically i did not die on server). Just a guess.

**Comment by Slava0135** [comment]
Or you need high ping (around 100) to get this issue

**Comment by wouter215** [comment]
I have had this issue as well;

1. Join as observer
2. Be a ghost
3. Activate "toggle all lighting" (the sun icon in the action bar) I can now see around walls with no shadows.
4. Take a ghost role as pAI
5. Keep the Toggle all lighting! I can still see around walls with no shadows.
6. ghost out again
7. take ghost role as positronic brain.
8. Keep the Toggle all lighting! I can still see around walls with no shadows.

**Comment by wouter215** [comment]
I now have Video of this:
https://youtu.be/jeCh0TTDhdA

**Comment by ElectroJr** [comment]
The "toggle all lighting" was the step I was missing, now its easy to reproduce. In hindsight its pretty obvious that it could've been the cause.

**Comment by arimah** [comment]
I've done a touch of digging, and it appears the bug was introduced by 654cc7f0. I'm trying to figure out exactly what part of it caused the bug and how to fix it... No doubt someone more familiar with the intricacies of the game will locate the root cause faster, but might as well try.

**Comment by arimah** [comment]
@ElectroJr – I'm dumb and did not realise you were already trying to fix it. Good stuff!
