### ISSUE TITLE
Xray vision 

### ISSUE THREAD

**Issue by AjexRose** [space-wizards/space-station-14#21595]
## Description

Players under specific circumstances have been able to gain "xray vision" while alive, letting them see through walls and air locks
**Reproduction**

According to player reports:
1. Die
2. Get the Revivial Notification pop up numerous times
3. Use one pop up while dead and another while alive
4. X-ray powers Activate!

**Comment by ElectroJr** [comment]
Duplicate of #21584, but thanks for the possible replication steps, ill test them.
