### ISSUE TITLE
Taking a ghost role can sometimes give let you see through walls

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#21608]
## Description

I was gibbed as a human, then took a pAI ghost role after spectating the person holding it. All of a sudden, i was able to see through walls at a magnified distance. I never tried disconnecting to fix it that round.

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/134914314/75147b47-08c7-4b59-af52-be932bca3fe6)

**Additional context**

Round number #37947

**Comment by ElectroJr** [comment]
Duplicate of #21584
