### ISSUE TITLE
Microbomb confirmation

### ISSUE THREAD

**Issue by liltenhead** [space-wizards/space-station-14#21624]
## Description
I don't know how many nukies/ninjas I've seen accidentally blow themselves up now, but it's rather high. It's rather easy to accidentally fat finger or just press the wrong button and round remove yourself and potentially some teammates as well. So I think adding a second confirmation to detonating the bomb could be beneficial.

**Comment by deltanedas** [comment]
or just support having an action available in K but not added to the action bar so if you know what you want to do you can still do it fast

**Comment by liltenhead** [comment]
That'd work too, just anything that isn't an insta death from one button press

**Comment by Kayek14** [comment]
Perhaps make it so you can only trigger the microbomb while in crit?

**Comment by deltanedas** [comment]
that reduces its utility for intentional suicide bombing since you have to waste a c-4 to crit yourself first, then the microbomb after

**Comment by IProduceWidgets** [comment]
Could just make it require priming, so a quick double press sets it off, and a single mistaken press lets you know you done fucked up.
