### ISSUE TITLE
punpun cant become a rev

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#21627]
## Description
gamebreaking bug

**Comment by dolgovmi** [comment]
I think monkeys are immune to welding and flashing in general, which is also broken

**Comment by UbaserB** [comment]
As a headrev i tried flashing pun pun since i remembered that mobs could be flashed. It didn’t work so i panicked and murdered him. This should probably be cleared up lol.

**Comment by dolgovmi** [comment]
https://github.com/space-wizards/space-station-14/pull/20784 may be related, if i understand correctly mobmonkey inherits some stuff from simplemob?

**Comment by deltanedas** [comment]
should be simple as adding Flashable to monkey then

**Comment by notquitehadouken** [comment]
monkey too stupid to be rev
