### ISSUE TITLE
Laserguns are broken

### ISSUE THREAD

**Issue by PaulRitter** [space-wizards/space-station-14#2163]
- Lasers go through walls
- Lasers dont reach the point you targeted

**Comment by PaulRitter** [comment]
@exp111 didn't you fix this?

**Comment by exp111** [comment]
Gun Prediction PR fixes this, so I didn't push

**Comment by metalgearsloth** [comment]
Fixed @DrSmugleaf

**Comment by SweptWasTaken** [comment]
Fixed yet you didn't close the issue....
