### ISSUE TITLE
New action bar mouse click issues

### ISSUE THREAD

**Issue by MACMAN2003** [space-wizards/space-station-14#21649]
## Description

Left clicking on the new action bar icons either gets rid of the icon or activates it multiple times.

**Reproduction**

get a pda or gas mask and click on the action bar button associated with it

**Screenshots**

i don't know if a time-based thing can be shown in a screenshot but here's a result
![image](https://github.com/space-wizards/space-station-14/assets/20659419/37b6b95c-53d5-4d73-b5e8-5c72e34985c2)

**Additional context**

**Comment by EmoGarbage404** [comment]
i'm not able to replicate this. Do you have any further steps involved?

**Comment by PokkeTigrex** [comment]
I had this happened when I was messing around with my keybinds, I had Use set to left click and shift+left click, but when I removed the shift+left click bind, it fixed itself? But then when I rebound it, it didn't happen again.

**Comment by MACMAN2003** [comment]
the recent update fixed it (at least for me)

**Comment by MACMAN2003** [comment]
actually nevermind apparently it fixed the PDA's light action button and the gas mask toggle but not for the "toggle suit piece" button for hardsuit helmets, and also something related is that the action buttons in the action menu (the one opened with K) don't do anything when i click on them

**Comment by MACMAN2003** [comment]
it feels like the more rounds played in one session the amount of times the action buttons get activated with each click increases by 1

**Comment by MACMAN2003** [comment]
actually that may be what's happening, on an odd round i'm able to toggle, but on even rounds i'm not.

**Comment by EmoGarbage404** [comment]
> it feels like the more rounds played in one session the amount of times the action buttons get activated with each click increases by 1

Thank you so much for this information. This may very well lead directly to the solution.
