### ISSUE TITLE
Landmines should only explode after you step off them

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#21658]
Title.

**Comment by IProduceWidgets** [comment]
Maybe also a way to trigger them remotely? Throw something at them?

**Comment by enumerate0** [comment]
> Maybe also a way to trigger them remotely? Throw something at them?

Hmm I like this idea but should it only trigger when specific objects are thrown? For example, paper wouldn't trigger it but a fireaxe would. In other words, how fragile do we want them to be? Mayhaps this should be a separate issue?
