### ISSUE TITLE
resetalltalents no longer functional

### ISSUE THREAD

**Issue by TurboTrackerss14** [space-wizards/space-station-14#21651]
## Description
Since the talents ui change resetalltalents nolonger functions as intended and does not return actions, confirmed on ghosts.

**Reproduction**
>use talent until lost
>use resetalltalents
>talents not reset

**Screenshots**

https://github.com/space-wizards/space-station-14/assets/130304754/680984cf-37ff-4d44-b7e9-35964096117c

**Additional context**

Skip to 1:10 on video took serveral button mashes to get an action to dissappear (without just rightclicking, issue occurs with rightclick removed actions also)

**Comment by EmoGarbage404** [comment]
resetalltalents is not only not a command that has ever existed, but it's purpose isn't to "reset talents." Furthermore, it's purpose definitely isn't to reset all actions.

**Comment by deltanedas** [comment]
talent from fish game
