### ISSUE TITLE
Clicking on the action to turn on lights doesn't work

### ISSUE THREAD

**Issue by GoodWheatley** [space-wizards/space-station-14#21654]
## Description

Observed on master, hotkeys still work.

**Reproduction**

1. Try to turn on a light using the action button
2. Fail

**Comment by EmoGarbage404** [comment]
i'm not able to replicate this. Do you have any further steps?

**Comment by IProduceWidgets** [comment]
I also have this issue.

My steps are:
spawn as sec, pick up a seclite out of the lockers and place it in my pocket, try to click on the action to turn the seclite on that appears in my action bar. It does not turn on.

As a work around, I can press the action bar hotkey (1-0) and it works fine.

**Comment by TurboTrackerss14** [comment]
Seems very repoducable on my machine
Most any light action (including pda light) will double act instantly, both sounds played. 
PDA light UI works totally fine, just the action.

**Comment by PokkeTigrex** [comment]
This also happens with masks and suit pieces, or any action that doesn't have a cooldown.

**Comment by Geekyhobo** [comment]
for me its been very inconsistent, jetpacks work one round and then the next I cannot toggle the button
