### ISSUE TITLE
Disposals Deathloops

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#21688]
## Description
When you make a loop in disposals near the final exit it will catch and Gib everyone that goes in to it. With no possibility of escape.
It makes a awful spammy noise too as they are hitting the 4 corners so quickly.

**Reproduction**
- Make a 4 corner disposals loop.
- Jump in or throw a body in.
- Wait until it gibs, gibs in about 1min.
- All of the gibbed parts despawn, no brain drop.

**Screenshots**
Deathloop example
![image](https://github.com/space-wizards/space-station-14/assets/47093363/56f76d44-fda3-48d8-bf70-881510adfcc1)
There are alternatives to it like this but at least this there is a bunch of work required and a chance to escape.
![image](https://github.com/space-wizards/space-station-14/assets/47093363/e86f09be-93a5-43fa-84bc-9d2ec733ef22)

**Additional context**
Was mentioned in initial implementation for the corner damage on #21489 But it doesn't look like there is any mitigation for this.
The damage on corners its nice but maybe have it break after x hits to prevent deathloops, just a thought?

**Comment by ImWeax** [comment]
I will also note that the victim of the deathloop also ends up crashing around 30 seconds after being gibbed.

**Comment by UbaserB** [comment]
Since disposals damage was removed, this issue can be closed.
