### ISSUE TITLE
[server config] nuclear operative roles do not respect 'role_timers = false'

### ISSUE THREAD

**Issue by ChemistScript** [space-wizards/space-station-14#21689]
Latest version of official server is running locally. Added 'role_timers = false' option to server_config.toml. All roles are available except nuclear operative, which require in-game time.
![image](https://github.com/space-wizards/space-station-14/assets/60422744/d032ed69-5f67-4674-b111-dac19499cf4a)
![image](https://github.com/space-wizards/space-station-14/assets/60422744/dd7c57da-45ab-47b0-9b86-a034465128fc)

**Comment by lzk228** [comment]
dupe

**Comment by ChemistScript** [comment]
https://github.com/space-wizards/space-station-14/issues/21404
