### ISSUE TITLE
Lungs breaking as well as metabolism

### ISSUE THREAD

**Issue by DexProcter** [space-wizards/space-station-14#21717]
Description

As a slime this has happened to me twice recently and I heard about this happening from others but rarely. I'm pretty sure when dying via explosions? as a slime and then getting revived your lungs just break as well as your metabolism. When revived you can no longer breath even if everyone else is breathing fine and when you are given meds you metabolize them either super slowly or it just doesn't work. The only fix i've seen for the lung issue was to remove the lungs but you will still have the issue of metabolizing super slowly or not at all meaning that any damage taken will take a lot longer to heal.

Reproduction

I am not sure how to reproduce this issue, all i know is that it happened after dying by a super matter bomb the first time and the second time a grenade pengu and being revived after dying to them.

Additional context

I don't know if this is a slime only issue or if other species have had this issue occur to them, but so far from what i've seen it's only affected me as a slime while i watch other people die the same way and be fine.

**Comment by dolgovmi** [comment]
If this happens during explosions the most notable change that i guess can cause what's described is that explosions now hit the organs in your body too, perhaps, and maybe that does a thing

**Comment by Veritius** [comment]
Happened in round 38385, detonated 8 C4 on the CMO, got caught in the blast, and was subsequently impossible to save. ever.

also I think this can happen with other species as well, I saw it happen a few rounds ago, can't remember the ID.

**Comment by liltenhead** [comment]
I was able to reproduce it with slimes. I just planted 8 c4 at their feet, gibbed the body. And there is literally nothing left. Every single part of them gets destroyed upon gibbing.

**Comment by deltanedas** [comment]
yeah need to whitelist recursion that would be best solution

**Comment by GreyMario** [comment]
I think I found it, actually

Please compare https://github.com/space-wizards/space-station-14/blob/dcf0585345795c549eadd238876b7b7661cb2589/Resources/Prototypes/Body/Parts/slime.yml#L4 with https://github.com/space-wizards/space-station-14/blob/dcf0585345795c549eadd238876b7b7661cb2589/Resources/Prototypes/Body/Parts/human.yml#L5

**Comment by deltanedas** [comment]
that led to them being damageable but it still shouldnt explode organs regardless of species

**Comment by GreyMario** [comment]
Organ damage _should_ be a thing but let's save that for surgery--right now it's probably sufficient to fix this inconsistency in definitions
