### ISSUE TITLE
revenant emagging should be limited to doors

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#21719]
## Description
- would fundamentally prevent rev instant early launch
- no helpful rev emagging chem dispensers, dog book, autolathe

**Comment by Aisu9** [comment]
who thought it was a good idea to give revolutionaries emag?

**Comment by deltanedas** [comment]
rev**enant**

**Comment by BolloTea** [comment]
if you limit it with doors, then it will be easier to remove the revenant - since he will be completely killed. it’s better to make a white list of what exactly it can interact with (at least with a medical bot)

**Comment by deltanedas** [comment]
not having other tools is a symptom of no diseases
