### ISSUE TITLE
Cargo externals

### ISSUE THREAD

**Issue by SpaceyLady** [space-wizards/space-station-14#21723]
Recent PR removed externals access for cargo and QM:
Cargo techs and QM cannot access external airlock to cargo shuttle on some maps including origin and packed.

**Comment by deltanedas** [comment]
there is no external airlock with cargo access so this is bad for going to space
going onto docked shuttle still possible

**Comment by LordEclipse** [comment]
> there is no external airlock with cargo access so this is bad for going to space going onto docked shuttle still possible

Not every map has the red external airlock with cargo access.

**Comment by Emisse** [comment]
report which maps dont and i will update them

**Comment by SpaceyLady** [comment]
I know it is on atlas, origin and packed so far for the cargo externals so far. Lawyer access is also now broken on some maps as they can't access brig to even enter security. I'm not sure which other maps were changed.

**Comment by Emisse** [comment]
lawyer was fixed yesterday

**Comment by deltanedas** [comment]
cargo red doors on atlas are cargo the docks are externals since prototype doesnt exist yet
