### ISSUE TITLE
Stacks of artifact fragments are wasted when constructing alien artifacts

### ISSUE THREAD

**Issue by Colin-Tel** [space-wizards/space-station-14#21727]
## Description

This was reported by a player on DeltaV (a downstream of Wizard's Den). They discovered that, firstly, you *must* have artifact fragments in at least 4 separate stacks to be able to make them into artifacts. Also, if any of these stacks contain >1 fragment in them, they are totally wasted.

**Reproduction**

```
1. Have more than 4 artifact fragments.
2. Split the artifact fragments into 4 stacks.
3. Open the construction menu and craft an alien artifact.
4. Any stack of artifact fragments that has more than one fragment in it uses all of its fragments.
```

**Screenshots**

https://github.com/space-wizards/space-station-14/assets/113523727/1f5e47cb-6769-49ec-bbc0-41ed0465f8de

**Additional context**

**Comment by deltanedas** [comment]
ye ill fix i forgot to report before :trollface:
