### ISSUE TITLE
Can't construct Cargo pallets

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#21738]
## Description
Cargo is unable to rebuild cargo shuttle to a useable state if the Cargo Pallets are destroyed or removed from shuttle.

**Reproduction**
Cant see it in build menu or in research tree.

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/47093363/0d54085c-227a-40ba-b1a5-3d2a62e077a9)

**Additional context**
This was seen in the context of revs destroying all of them so cargo couldn't order mindshields It seemed to just accelerate the round ending early.

**Comment by UbaserB** [comment]
It's not QUITE a bug but there should be some alternative to fix this.

**Comment by deltanedas** [comment]
you can/could buy them for $250 each

**Comment by UbaserB** [comment]
> you can/could buy them for $250 each

if the cargo pallets are destroyed, then you cant actually buy more.

**Comment by deltanedas** [comment]
then ahelp clown griff trade station ban he

**Comment by UbaserB** [comment]
> then ahelp clown griff trade station ban he

there could be several reasons to be fair

**Comment by Titian3** [comment]
Closing this off, Has since changed to the ATS anyway so its not super relevant anymore.
