### ISSUE TITLE
you got all parts and organs of moth people if mothroach gibbed

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#21753]
1. gib mothroach
2. get moth limbs and organs
probably shouldn't be like that
https://github.com/space-wizards/space-station-14/blob/86c0a73c09bb835dc2db053718e911647d3b62a9/Resources/Prototypes/Entities/Mobs/NPCs/animals.yml#L435

**Comment by BYONDFuckery** [comment]
you should get part of the parts or just nothing/moth hide (this will break my pr)

**Comment by BYONDFuckery** [comment]
can i make it so you  get literally nothing
temporarily

**Comment by lzk228** [comment]
> can i make it so you get literally nothing temporarily

I don't think so
