### ISSUE TITLE
Atlas issues

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#21776]
![image](https://github.com/space-wizards/space-station-14/assets/31366439/89bf49e7-867b-41ad-bd35-ed5d4d444265)

I think @deltanedas made it and they're not on disc.

**Comment by TsjipTsjip** [comment]
Additionally, the following issues were flagged in [the same discord thread](https://discord.com/channels/310555209753690112/1175739963162251314):
- Botany has a normal water tank instead of a high-capacity one.
- Defibrillators are entirely absent from the map.

**Comment by TsjipTsjip** [comment]
Closes when #21781 is merged.
