### ISSUE TITLE
borg lock does nothing

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#21786]
## Description
you can open borg ui and remove mmi etc without unlocking /!\\

![16:07:38](https://github.com/space-wizards/space-station-14/assets/39013340/1e285bfd-3870-416d-9188-7398e0a64a89)

![16:07:43](https://github.com/space-wizards/space-station-14/assets/39013340/e423af2e-4d43-49ba-ab51-a46b937a5407)

**Comment by Emisse** [comment]
this was working when i implemented it recently
