### ISSUE TITLE
Chemists are pouring out all their chemicals

### ISSUE THREAD

**Issue by Brandon-Huu** [space-wizards/space-station-14#21789]
## Description

There is no way for chemists to create more jugs without relying on science to research it for them. ( they won't do it )
Some have resorted to pouring out entire jugs of chemicals just for the container.

**Reproduction**

Watch or play chemist.

**Comment by Emisse** [comment]
This problem fixes itself once chem dispenser is limited

**Comment by deltanedas** [comment]
they will still have no jugs just dumping in buffer rather than drain

**Comment by Emisse** [comment]
mfs need a chemistry kit these cowards need the comfort of the machine

**Comment by Aisu9** [comment]
why dumping in the drain when you can store it in the chem-master?

**Comment by Brandon-Huu** [comment]
> why dumping in the drain when you can store it in the chem-master?

Faster to drain then it is to put it into beakers then chem-master
