### ISSUE TITLE
The playtime required for chief engineer is confusing

### ISSUE THREAD

**Issue by Brandon-Huu** [space-wizards/space-station-14#21798]
## Description

You require more engineering playtime to unlock atmospheric technician than you do for the chief engineer.
Honestly so confusing how the only requirement for me to unlock CE is on a role that is locked behind engineering playtime.
Why does CE require less engineering playtime than a role that is required to play CE?

**Reproduction**

Play Engineering.
Look at playtime requirements.

**Screenshots**

Chief Engineer:
![Screenshot from 2023-11-19 19-21-37](https://github.com/space-wizards/space-station-14/assets/103440971/b449fd7e-e219-495c-8d52-a6493a638fb7)

Atmospheric Technician:
![Screenshot from 2023-11-19 19-21-48](https://github.com/space-wizards/space-station-14/assets/103440971/8646437c-0799-4eac-a327-24359ae8b7de)

**Additional context**

**Comment by UbaserB** [comment]
Isn't this hovering over senior engineer, not atmos tech?

**Comment by Brandon-Huu** [comment]
> Isn't this hovering over senior engineer, not atmos tech?

No, the hover is immediately above the role that is being moused over.
