### ISSUE TITLE
Salvage Technicians do not show up on the station records computer

### ISSUE THREAD

**Issue by Brandon-Huu** [space-wizards/space-station-14#21801]
## Description

Salvage Technicians do not show up on the station records computer.
Not sure if this is true or not but I had a round where a salvage tech was no in the station records.
They were also an antagonist, not sure if that matters
 
**Reproduction**

IDK

**Screenshots**

**Additional context**

**Comment by dolgovmi** [comment]
Maaaybe they used a DNA scrambler?

**Comment by Brandon-Huu** [comment]
Apparently its normal?
