### ISSUE TITLE
T-ray scanners do not show cables under tiles

### ISSUE THREAD

**Issue by Elysium206** [space-wizards/space-station-14#21817]
## Description

When using a tray which is on you cannot see cables under floor tiles. pipes and dispo pipes show up fine. but cables do not, causing you to have to pry up floor tiles
**Reproduction**

just use a tray
**Screenshots**

**Additional context**

was atmos trying to figure out why teg had no power and couldnt track cables

**Comment by ElectroJr** [comment]
This should've already been fixed by space-wizards/RobustToolbox/pull/4583, I'm assuming you ran into this before the engine was updated.
