### ISSUE TITLE
Can't VV Station Entity from admin panel

### ISSUE THREAD

**Issue by LordEclipse** [space-wizards/space-station-14#21818]
## Description
I don't know if there was ever an issue made about this, but the station entity (I think that's what it is at least) just never loads, and will eternally say "Waiting on server..."

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/106132477/5413d425-85be-42fa-89ec-1a51c3dd4c28)

**Comment by ElectroJr** [comment]
The admin panel needs to be updated to use net-entities instead of EntityUids
