### ISSUE TITLE
Credit based economy on the Station

### ISSUE THREAD

**Issue by BorjaUnizar** [space-wizards/space-station-14#21815]
## Description

This idea is a bit long but I would appreciate it if you could read it completely and give some feedback. Given the depth of it I don't think it could be implemented in the near future but I've been thinking about it for a while and I wanted to share it nonetheless.

Like the title suggests, it would be implementing a credit system similar to a combination of SS13's Goonstation and SS14's Frontier Station, with some tweaks to encourage more RP interactions and not just add a new obstacle for crewmates who want to drink a can of space cola.

**How would the system work?**

- Give the station a General budget. This budget would behave just like nowadays' cargo, having a natural tick (credits per second) growth and being increased via cargo's sales too. This budget would be divided into two subgroups: The Payroll budget and the Supply budget.

- The Payroll budget would be used, well, to pay the crew. Every crew member would have a certain salary depending on their job, which could be increased/decreased depending on their performance or other events.

- The Supply budget would be used almost just like it already is, to pay for materials and other items needed by the different departments, with the added difference that given that crew members now have their own money too, they could make personal requests to cargo, which would be a new way for them to increase their budget too (*summons interest rate demon*).
 
- The Head of Personnel would manage the General budget, deciding what portion of it is allocated to the two different subgroups, and the Payroll budget, being responsible for the crew members' salaries. The Quartermaster, obviously, would manage the Supply budget.

- The credit account of every crew member would be linked to their ID. The ID could be used to retrieve creditbucks at an ATM (which would need to be added) or at the HoP's office (using the ID console or a new machine would need to be added). Payrolls would be automatically added to everyone's account at the end of the shift, or manually by the HoP if a crew member needs to leave the round early, after notifying them. The amount would be stored for future rounds.

**What would the credits be used for?**

Let's take out the obvious one first, yes, vending machines. The credits used this way would flow back to the General budget, or even better, they could stay inside the vending machine.

- Besides that, as previously stated, crew members would be able to make personal requests to cargo, which wouldn't require any head's approval (as long as you're not ordering laser guns or other similar *"funny"* requests) . On top of that, cargo should never refuse these, as not only they can't lose money, but if they're smart enough they will win some. Also, uh, it's their job.

- Given that salaries in the Service department would typically be lower than those of other departments, these roles could charge credits for their products. For example, Chefs, Bartenders, or Botanists could have different prices for their offered items, and Clowns or Mimes could charge for their... *"performances"*. This way higher paid roles would use their salary to consume the products made by the lowered paid Service roles, evening it out.

- Looking at it from the antag(or not so antag) point of view, credits could be used in many malicious ways too. Need someone to do some risky tasks for you? Offer some credits. Want to bribe someone for something you shouldn't have? Nothing a couple of spacebucks can't do. "Whoops, your PDA fell into my thieving gloves, time to order 25 gorilla crates". The options are limitless. 

**What is the desired effect of the system?**

This may be more of a personal opinion but on MRP/HRP Servers the budget, compared to the station's power,structure,security,etc... is usually not a problem the crew has to deal with. With this change I wouldn't want to overshadow the rest of events that unfold on every unique shift of this great game, but add a new layer of complexity and most importantly, new RP opportunities. 

Power struggles between Command and Cargo over the general budget, crewmates asking the HoP for a permit to start their own shop, Command asking CentComm for a higher budget to fullfill the stations needs and all of the mentioned ideas above are examples of the new possibilities it would bring.

**The ugly but last part, the numbers**

If you're actually still reading, I'm amazed, thank you. This is the only part i haven't thought about in depth. To be fair I'd just try to follow a similar line to Frontier Station for the numbers, and tweak it a bit if needed, but that would need to have all of this implemented first, and this is just me presenting an idea, so I won't delve more into it.

**Comment by metalgearsloth** [comment]
This should be in discussions or #ideaguys, not under issues.

**Comment by BorjaUnizar** [comment]
My bad, changing it right now.
