### ISSUE TITLE
Skeleton occasionally will materialize in a black void with space music

### ISSUE THREAD

**Issue by Everturning** [space-wizards/space-station-14#21826]
## Description
See title. The ghost role Closet Skeleton will occasionally spawn in a black void that has space music playing. You will not be able to see the skeleton, and (possible variations) moving will not kick open a locker or open a crate. I am not a coding person, so I have no way to search the code to see any possible reasons for this. The role did not spawn on a salvage, as right clicking around showed nothing, not even the skeleton.

**Reproduction**
Spawn in a skeleton ghost role
Follow it
Eventually you'll find a skele spawning in the black void (this is not exaggeration, you couldn't see stars or shit, but the space music is playing)

**Screenshots**

**Additional context**
I had ahelped it and CptJeanLuc had seen the issue as well, and had teleported me onto the station. I do not know the round number, but they may.

**Comment by Kayek14** [comment]
Appears to be the same issue

https://github.com/space-wizards/space-station-14/issues/20607#issue-1919822398
