### ISSUE TITLE
dna scrambler revert back to original appearance doesn't work

### ISSUE THREAD

**Issue by 27alaing** [space-wizards/space-station-14#21829]
## Description
title

**Reproduction**
- use dna scrambler implant and activate it
- dna scrambler revert back to normal action doesn't appear

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/45323883/1b1fc146-64a3-4696-ae52-2727432b73af)
After using scrambler

**Additional context**
don't really know, action bar rework might've broke it

**Comment by EmoGarbage404** [comment]
from what i can see, the DNA scrambler has never had the ability to revert back to the original appearance. the description in the uplink might be incorrect.

**Comment by 27alaing** [comment]
oh weird
