### ISSUE TITLE
disabled people should be able to crawl

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#21861]

**Comment by Brandon-Huu** [comment]
Would this require making new sprites?

**Comment by FinnishPaladin** [comment]
> Would this require making new sprites?

Probably not, just need to keep them horizontal.

**Comment by dolgovmi** [comment]
You'd probably want to add proper crawling then, like in 13

**Comment by lzk228** [comment]
ok there is no more disabled people since removing wheelchairs :trollfaceL

**Comment by Brandon-Huu** [comment]
> ok there is no more disabled people since removing wheelchairs :trollfaceL

WHAT!?!?!?!? WHY

**Comment by lzk228** [comment]
> > ok there is no more disabled people since removing wheelchairs :trollfaceL
> 
> WHAT!?!?!?!? WHY

#24681
