### ISSUE TITLE
FYI:  Received legal threat from SS220 / SFX Licensing

### ISSUE THREAD

**Issue by Skyedra** [space-wizards/space-station-14#21869]
Hello,

Please be advised that [SS220](https://github.com/SerbiaStrong-220) has threatened to DMCA SSMV over White Dream allegedly using several of their PRs.  Apparently they did not contact WD directly, but now that WD is aware, WD are supposedly working to remove the contested PRs.

Relevant to wizden is SS220's threat to DMCA over [this PR](https://github.com/SerbiaStrong-220/space-station-14/pull/51).  That PR is regarding two contested SFX:  `pirate_start.ogg` and `zombie_start.ogg`.  These SFX were submitted and merged into WizDen's [repo](https://github.com/space-wizards/space-station-14/tree/master/Resources/Audio/Ambience/Antag) in #16864, [supposedly](https://github.com/SerbiaStrong-220/space-station-14/blob/master/Resources/Audio/Ambience/Antag/attributions.yml) under a creative commons license, and by now likely exist in many SS14 forks.

(Sidenote - The entire threatened DMCA is a bit unusual, given among other reasons, all PRs they claim as violations appear to have been opened *prior* to their CLA license [being instituted](https://github.com/SerbiaStrong-220/space-station-14/commit/81ff1cfd7e3c452b67a2867a4d059d3b44c1c916).)

Anyway, I am posting this here as WizDen may wish to verify the SFX in this PR are actually permitted for distribution or replace them with safely licensed sounds.  And everyone in the community in general may wish to be very careful using content / accepting PRs from SS220's staff in future.

# Legal Threat

![legal threat](https://github.com/space-wizards/space-station-14/assets/22365940/1c6c8f74-b6cc-4c7d-b969-cd2f99408367)

# Role

![roles](https://github.com/space-wizards/space-station-14/assets/22365940/da9a158f-e1a8-4164-9559-fed643a416dc)

**Comment by metalgearsloth** [comment]
Hi Skye,

The assets for the aforementioned PR are listed under CC-NC license which are covered under SS220's CLA, translated:
> Note that some assets are licensed under CC-BY-NC-SA 3.0 or a similar non-commercial licence, and must be removed if you wish to use this project for commercial purposes.

To our knowledge we don't have any code-related PRs violating any CLAs.

Additionally, if any project wishes their assets to no longer be used upstream, even if no license violations are found, we are happy to find replacements should they reach out to us.

**Comment by Skyedra** [comment]
Good point on the noncommercial usage, I hadn't realized that was part of this situation until you pointed it out; thanks
