### ISSUE TITLE
Ghost role earning remake suggestion

### ISSUE THREAD

**Issue by millionse** [space-wizards/space-station-14#21873]
*Is your feature request related to a problem/bug? Please describe.**
On 50+ players server it's really hard to earn some of ghost roles. You need to open ghost roles window, sitting AFK and watching the window, prepared for the wanted ghost role appearing and **attempt** to pick it. Any lost second - and funny ghost rp for another hour guaranteed - at 100+ players servers that problem at really bad state.

**Describe the command you'd like**
Menu at settings or at personalization with ability to "subscribe" to interested ghost role, like the antagonist menu.
When interested role appearing - you will be notified - something like icon within ghost roles button and sound effect that notifies you about role. From that moment there will be 15-30 seconds to register to the role, after timer ends - random player that registered will earn the role. If no players registered - everyone can pick the role instantly, like at the current system.

*Why?*

1. It will give people that don't want to play rp with ghost role window at least chance to get some interesting role besides mouse.
2. You also don't need to stare the window or open it every time that ghost role appears - now because of notification you will open the window only to wanted to you role.
3. Many other small QoL like that you can read description of ghost role when registration is going on instead of clicking "request" button.

**Comment by deltanedas** [comment]
wyci + this is nothing to do with toolshed bozo

**Comment by Hmeister-real** [comment]
If someone does add it, it should be kept to important ghost roles like Solo-op's, ninjas and revs etc. I don't think having to register to become a sentient vending machine or PAI is really necessary.

**Comment by ElectroJr** [comment]
The Toolshed label is for stuff related to the in game console & console commands, though I guess it's not clear if you don't already know what it is.

As for the ghost role idea, we've already decided in one of the maintainer meetinfs to rework the ghost role selection to use a lottery system, along with generally reworking the ghost role UI, character objectives UI, and ghost role notifications. As far as I know no one has started work on it yet.

**Comment by Plykiya** [comment]
I won the ghost role raffle
