### ISSUE TITLE
Medical hud isnt working

### ISSUE THREAD

**Issue by Adrian16199** [space-wizards/space-station-14#21897]
## Description

Medical hud isnt correctly working, No health is being displayed.
**Reproduction**

>Get medical hud
>Equip medical hud
>No health bars above people.
**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/144424013/65421a2f-75e7-425d-8355-015598127a3e)

**Additional context**

Hello!

**Comment by lzk228** [comment]
lmao

**Comment by lzk228** [comment]
dupe btw https://github.com/space-wizards/space-station-14/issues/4967

**Comment by GoodWheatley** [comment]
Medical HUD’s functionality is not coded yet.
