### ISSUE TITLE
Need a quick button to turn off sensors on clothes

### ISSUE THREAD

**Issue by TheKilk** [space-wizards/space-station-14#21890]
## Description
When you play as a sindicat, it's hard to take off all the clothes from a person when you kill them or put them to sleep, I think you need to add this button.

**Screenshots**

![Space Station 14 11_24_2023 10_19_05 PM](https://github.com/space-wizards/space-station-14/assets/142771861/121c4d8b-c736-4d65-826a-768b753b469d)

I think it should be added to this menu.

**Comment by deltanedas** [comment]
if this is implemented not just a button to turn off, but all options to make it easier for medics to turn peoples sensors on

**Comment by chromiumboy** [comment]
If IIRC, a patient's sensor blip will remain active on the crew monitor for about 10 s after the sensors are turned off (the patient's information doesn't update though). So it looks like the system is actually designed to give people watching the monitor a chance of spotting an assassination and cover up. Have to double check this though, could be misremembering
