### ISSUE TITLE
Audio rework known issues

### ISSUE THREAD

**Issue by VasilisThePikachu** [space-wizards/space-station-14#21925]
## Description

Fix issues will be striked out and eventually removed from this issue after they are fixed

~~3. Audio slider settings are not used until you open the settings window once or adjust em.~~ confirmed

~~4. Some audio sources keep playing in the lobby (flairs, anomalies etc)~~ claimed fix

~~5. InvalidValue keeps being spammed in the logs, no known reproduction~~ claimed fix

Engine side issues: https://github.com/space-wizards/RobustToolbox/issues/4614

**Comment by Uriende** [comment]
Since the update I cannot hear alert sounds or music anymore.

**Comment by Uriende** [comment]
For the music I see this error:
`[LoadAudioOggVorbis:114] AL error: InvalidName`
Not sure yet what the invalid name means wrong path maybe?

For the alert sounds I've created this PR I think it fixes it https://github.com/space-wizards/RobustToolbox/pull/4619

**Comment by MidgleyM** [comment]
When moving from left to right or the other way around, music that you are playing abruptly switches from the left ear to the right or vice versa. I am not sure whether this is an issue or not, but it is very jarring and annoying.

**Comment by metalgearsloth** [comment]
> When moving from left to right or the other way around, music that you are playing abruptly switches from the left ear to the right or vice versa. I am not sure whether this is an issue or not, but it is very jarring and annoying.

Already fixed in https://github.com/space-wizards/RobustToolbox/pull/4618

**Comment by Shadowtheprotogen546** [comment]
While moving, any music being played (by you) is distorted, even if you are just walking.  It sounds like you are on a shuttle.

**Comment by MidgleyM** [comment]
> While moving, any music being played (by you) is distorted, even if you are just walking. It sounds like you are on a shuttle.



> > When moving from left to right or the other way around, music that you are playing abruptly switches from the left ear to the right or vice versa. I am not sure whether this is an issue or not, but it is very jarring and annoying.
> 
> Already fixed in [space-wizards/RobustToolbox#4618](https://github.com/space-wizards/RobustToolbox/pull/4618)

same issue, so its already fixed, the PR just has to be reviewed and merged

**Comment by VasilisThePikachu** [comment]
> > While moving, any music being played (by you) is distorted, even if you are just walking. It sounds like you are on a shuttle.
> 
> > > When moving from left to right or the other way around, music that you are playing abruptly switches from the left ear to the right or vice versa. I am not sure whether this is an issue or not, but it is very jarring and annoying.
> > 
> > 
> > Already fixed in [space-wizards/RobustToolbox#4618](https://github.com/space-wizards/RobustToolbox/pull/4618)
> 
> From your description I think its the same issue I reported and metalgearsloth said its fixed, the PR just has to be reviewed and merged

This is only for midis. Not general sound effects

**Comment by Shadowtheprotogen546** [comment]
The issue I mentioned above has been slightly improved, but still peeks through.  Also massive audio latency issues.

**Comment by metalgearsloth** [comment]
> The issue I mentioned above has been slightly improved, but still peeks through. Also massive audio latency issues.

Do you have a video of latency issues?

As far as I'm aware every other issue raised was fixed besides potential user issues.

**Comment by Shadowtheprotogen546** [comment]
i usually get anywhere from 60-80 fps steady.  It's just the audio that gets choppy and sounds funky

**Comment by Slava0135** [comment]
> i usually get anywhere from 60-80 fps steady. It's just the audio that gets choppy and sounds funky

same

**Comment by Barrett-S** [comment]
> > > While moving, any music being played (by you) is distorted, even if you are just walking. It sounds like you are on a shuttle.
> > 
> > 
> > > > When moving from left to right or the other way around, music that you are playing abruptly switches from the left ear to the right or vice versa. I am not sure whether this is an issue or not, but it is very jarring and annoying.
> > > 
> > > 
> > > Already fixed in [space-wizards/RobustToolbox#4618](https://github.com/space-wizards/RobustToolbox/pull/4618)
> > 
> > 
> > From your description I think its the same issue I reported and metalgearsloth said its fixed, the PR just has to be reviewed and merged
> 
> This is only for midis. Not general sound effects

Can confirm, MIDI playback violently pans back and forth if you so much as turn 90 degrees, let alone try to run around with music playing.

**Comment by VasilisThePikachu** [comment]
https://github.com/space-wizards/RobustToolbox/issues/4614

Engine issue

**Comment by metalgearsloth** [comment]
which one's outstanding

**Comment by VasilisThePikachu** [comment]
I have confirmed myself (latest publish) that issues 1 and 3 are still not fixed

2 is only testable on live servers
4 i have not played a round to repro

**Comment by Kelrak** [comment]
A lot of audio still broken on Mac (Global and more). It reproducible locally so unrelated to the other global fix. I think my PR fixes that though.

**Comment by metalgearsloth** [comment]
4. Is fixed
5. Was FadeOuts applying on lobby which was also fixed.

**Comment by VasilisThePikachu** [comment]
For invalid values I also noticed they got spammed when I was following an admin going into an uninitialized map. Would that also be fixed?

**Comment by VasilisThePikachu** [comment]
Closing this for now since all my issues been crossed out. If theres still an issue i will reopen it
