### ISSUE TITLE
t-ray doesnt show wires

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#21936]
## Description
at least hv wires arent shown by t-ray
![05:29:25](https://github.com/space-wizards/space-station-14/assets/39013340/5a7f5125-f599-42ba-9a9d-1c46a3555a9d)

![05:29:35](https://github.com/space-wizards/space-station-14/assets/39013340/e0c5cbcd-0add-4e0a-a92f-9b8ace603b99)

**Comment by lzk228** [comment]
isn't it was fixed in some of engine's pr?

**Comment by deltanedas** [comment]
maybe idk

**Comment by deepy** [comment]
looks OK today
![image](https://github.com/space-wizards/space-station-14/assets/905507/c92f8e4d-8e49-4967-83ee-08b9cb027058)
