### ISSUE TITLE
Woodblock Not Counted As A Percussion Instrument

### ISSUE THREAD

**Issue by Kezu02** [space-wizards/space-station-14#21985]
## Description

The internet says it's a small drum yet it doesn't count when cargo sells it for a percussion instrument bounty. Just something pretty minor.

**Comment by Colin-Tel** [comment]
![image](https://github.com/space-wizards/space-station-14/assets/113523727/2c2981d0-0881-426a-8596-e4fba02b67c1)

this appears to be solved
