### ISSUE TITLE
Suspicion traitor allies are sometimes not synced

### ISSUE THREAD

**Issue by DrSmugleaf** [space-wizards/space-station-14#2199]
Because the client doesn't handle SuspicionAllyAddedMessage, or SuspicionAllyRemovedMessage.

**Comment by Zumorica** [comment]
And this issue is opened an hour before we run SSS... :witheredwojak:

**Comment by DrSmugleaf** [comment]
> And this issue is opened an hour before we run SSS... :witheredwojak:

I have a surprise trick that will help us later
![image](https://user-images.githubusercontent.com/10968691/95605761-b2057000-0a59-11eb-948b-a44b28f365e9.png)

**Comment by Zumorica** [comment]
:weary:
