### ISSUE TITLE
issues are enabled

### ISSUE THREAD

**Issue by hornygranny** [space-wizards/space-station-14#22]
@Silvertorch5

**Comment by astralenigma** [comment]
Well I would love to see a feature list of the features it currently has done, and the ones that are missing.

**Comment by gravypod** [comment]
Milestones should be setup. That way people know how to pitch in and what needs work

**Comment by Pangogie** [comment]
Well here's the [roadmap on their wiki](http://www.spacestation14.com/wiki/Roadmap). It's pretty much up to date on the progress of the various mechanics, as well as having a feature milestone list for the various stages of development.

**Comment by matrecs** [comment]
somebody still here and work?

**Comment by Silvertorch5** [comment]
I currently am. I am finishing graphics soon and will be updating my github branch

**Comment by wakeuphate** [comment]
While I don't have the knowledge (yet, possibly) to contribute, you guys could set up a public [Trello](https://trello.com/) board to handle all the the milestones and currently worked on stuff. I generally tend to set up columns like Todo 0.1, Doing 0.1, Ready for testing 0.1, Done 0.1 and then archive and create the same, only 0.2 for example, when each milestone is complete.

Might give everyone an overview of who's working on what at each time. Just my 2c.

**Comment by matrecs** [comment]
@wakeuphate maybe in future, it's useless at this time, as i think. now you can see all "todo"  at [Silvertorch5 repo](https://github.com/Silvertorch5/space-station-14/issues/15)

**Comment by wakeuphate** [comment]
Ah, I see, I'd not seen that yet, looks good enough for now.

**Comment by matrecs** [comment]
i'll help with server-side in few days. at now i prepare my mind to " java => c# " switch. I hope it doesn't take too much time.
