### ISSUE TITLE
Summoning dragon from Ninja target doesn't work

### ISSUE THREAD

**Issue by Anzarot121** [space-wizards/space-station-14#22095]
## Description

The Ninja may have a goal to summon an additional threat. For some reason, the dragon ghost role is not created despite the message in the chat.
**Reproduction**

1. Be a ninja with an aim to summon threats
2. Hack the communication console
3. Receive a message about a connection with a space fish
4. Dragon ghost role is not created

**Comment by deltanedas** [comment]
bruh
