### ISSUE TITLE
Prettier singularity 

### ISSUE THREAD

**Issue by AJCM-git** [space-wizards/space-station-14#2212]
- [ ] The singularity itself should be a shader
- [ ] It should have a "pull" effect that attracts the closest object and makes them orbit around itself before eating it, instead of simply deleting stuff.
- [ ] It should have a "warping" effect like pic related 
![sing](https://user-images.githubusercontent.com/60196617/95603631-11598500-0a46-11eb-918e-97054426ce3d.png)

**Comment by Matt07734** [comment]
- The "warping" effect could match [this](http://desmos.com/calculator/6y7vukam7r) on a smaller scale to better resemble a black hole

**Comment by GlassEclipse** [comment]
Orbit effect pending, I think the straight pull looks fine for now
