### ISSUE TITLE
Buckling other people needs a do-after.

### ISSUE THREAD

**Issue by IProduceWidgets** [space-wizards/space-station-14#22124]
## Description

There is no delay to buckling other people. Players abuse this by buckling people repeatedly to chairs so they cant run away or fight.

**Reproduction**

drag a player onto a chair, rinse, repeat. #GetRektScrub

**Screenshots**

**Additional context**

This is cancer.

**Comment by tgrkzus** [comment]
Probably want some sort of exemptions for any delay on:
- SSD/Sleeping/knocked out people
- Buckling to beds (otherwise medbay becomes annoying)

Otherwise +1

**Comment by dragonryan06** [comment]
this was fixed in #29621 earlier this week!
