### ISSUE TITLE
Thrown item damage needs a cooldown

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#22127]
That or throwing needs a cooldown because someone with an autoclicker can rack up a lot of damage very quickly by spam throwing.

**Comment by keronshb** [comment]
I think throw mode can help this, was planning on doing it sometime after the magic refactor.

Also if we can get someone to rework stamina on the hud we could implement stamina use per throw.

**Comment by mirrorcult** [comment]
just make throwing have a cooldown, no throw mode

**Comment by QuietlyWhisper** [comment]
please don't add extra intents/throw toggle, ss14 feels really fluid without it
