### ISSUE TITLE
Grid inventory borg items stuck

### ISSUE THREAD

**Issue by DummeHytteOst** [space-wizards/space-station-14#22156]
Attemping to place a borgs tools inside a grid inventory will "place" the item inside, after a little testing, it appears impossible for anyone to take out the items, you can as the borg, relocate the items inside.

the items update accordingly to those the borg has, as seen below.

https://github.com/space-wizards/space-station-14/assets/94384139/2be5d10d-65db-4242-bfc4-2461ead899f1

Clip showing how a borg can relocate, and place items in grid inventories. 

https://github.com/space-wizards/space-station-14/assets/94384139/f1b4891c-8007-4c11-85a0-c2618d3a07cf

we attempted to use the "transfer contents" option in the verb menu, or whatever it is called, and was unable to transfer the glitched items into another grid inventory.

we were also completly unable to remove the glitched items from the grid inventory, but i suspect you might be able to remove them, by deleting the original item, either with in game means (singulo, cremator, disposal grinder), or admin means, unsure if this might crash a server if attempted.

@EmoGarbage404

**Comment by EmoGarbage404** [comment]
found the fix. thanks for the report
