### ISSUE TITLE
combat boots are awkward to use now

### ISSUE THREAD

**Issue by JoeHammad1844** [space-wizards/space-station-14#22172]
## Description

since you cant have multiple storage UI's open, getting the knife out of boots is more complicated than it needs to, this can be solved by them using item slots like PDA's instead, meaning you alt click to take the knife out

**Comment by Emisse** [comment]
i was thinking you just use an item slot with a whitelist for sharp and size:small

**Comment by EmoGarbage404** [comment]
> i was thinking you just use an item slot with a whitelist for sharp and size:small

can't do whitelist based on itemsize but it'd be trivial to implement

**Comment by JoeHammad1844** [comment]
just make a new tag called "BootIt"

**Comment by Keikiru** [comment]
Having a single inventory slot for a handful of whitelisted items with said inventory slot only being able to hold a single item at a time is cumbersome. This was also the case before the inventory reworks.

Instead I propose it functioning more like how potted plants do when storing items. The boots have no inventory but can contain a single item that can quickly be grabbed or deposited without wranging with an inventory window.

**Comment by asperger-sind** [comment]
yea i was thinking making combat boots use a storage slot as opposed to an inventory, i have nfi if these accept tags and ill check and try fix this when i get to it (a week or two probably)
