### ISSUE TITLE
cigarette pack is too big inside

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#22182]
![2023-12-06_150819](https://github.com/space-wizards/space-station-14/assets/124214523/5994f4c4-d284-4721-b21f-7c38c9f15efc)

**Comment by lzk228** [comment]
maybe make only cigs whitelist?

**Comment by UbaserB** [comment]
> maybe make only cigs whitelist?

good idea

**Comment by IamVelcroboy** [comment]
Things people put in their cig packs irl... Cigs, lighters, matchbooks, joints, cash, IDs.

**Comment by Slardar0609** [comment]
i think you cn close it now
