### ISSUE TITLE
Traitors can buy death acidifiers

### ISSUE THREAD

**Issue by GoodWheatley** [space-wizards/space-station-14#22192]
Title.

**Comment by 27alaing** [comment]
was it not intended?

**Comment by KingOnBudget** [comment]
> was it not intended?

you can inject your targets with it meaning you get to gib people for 2tc

**Comment by deltanedas** [comment]
its not instant and you can easily see john syndicate is holding a **death acidifier**

and you can gib for 0tc using baseball bat

**Comment by Plykiya** [comment]
this issue was death acidified, powww
