### ISSUE TITLE
do_after bar sticks around indefinitely after completing.

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#2220]
![2020-10-10_12-49-52](https://user-images.githubusercontent.com/49448379/95663825-cfa60880-0b31-11eb-9ada-1cb103164e5b.gif)

**Comment by Zumorica** [comment]
@metalgearsloth

**Comment by metalgearsloth** [comment]
Weird, it doesn't affect welders but it affects the others, will looksy.
