### ISSUE TITLE
Explosion resistance on armor seems broken

### ISSUE THREAD

**Issue by Elysium206** [space-wizards/space-station-14#22212]
## Description
!-- in my admin testing area i ran multiple tests using various explosives under the feet of urist mchands. one with no armor, one with a sec hardsuit, one with rd suit, and one with a full bomb suit. an explosive grenade did 150 damage to ALL of them regardless of what they were wearing. --

**Reproduction**
-- Grab a pair of test subjects, one armored and one not, and blow em up. --
 
**Additional context**
-- not sure what the cause would be as I'm deathly allergic to code, but TLDR explosive resistance provides zero protection ATM .

**Comment by deltanedas** [comment]
may have been trolled by Worn stuff

**Comment by deltanedas** [comment]
#22165 maybe??? copying event or something which is evil

**Comment by deltanedas** [comment]
ok #20274 made it a struct then #22165 broke it for struct, and since it i think is the only struct relayed event thats why nothing else broke
