### ISSUE TITLE
Removing cuffs from another mob is broken.

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#2221]
![2020-10-10_13-01-27](https://user-images.githubusercontent.com/49448379/95663995-6f17cb00-0b33-11eb-8995-393e63e31f4b.gif)

**Comment by Zumorica** [comment]
I'm pretty certain this is related to EntityCoordinates, will take a look soon. Good catch!

**Comment by Zumorica** [comment]
Turns out a single `!` was missing. Pushing a fix soon.

**Comment by Zumorica** [comment]
Fixed in 30956a0fc8b1ea4218a81bf49cb84b991e92df08
