### ISSUE TITLE
Creatures without arms can no longer interact with inventory

### ISSUE THREAD

**Issue by Anzarot121** [space-wizards/space-station-14#22219]
## Description

Previously, as a mouse, hamster, carp, etc., you could open the inventory lying on the floor, for example, to eat pizza or donuts. Now this button does not perform any functionality.
**Reproduction**

Go get Hamlet.
Try eating donuts.
The "open UI" button does nothing.
You are very hungry.
Get killed by a clown because you couldn't escape him.

**Comment by deltanedas** [comment]
i think it was a bug
maybe to help mouse friends you have to manually close pizza/donut boxes
being able to open nested storages to get food inside is a bit silly

**Comment by EmoGarbage404** [comment]
I dont think it really makes sense that a creature that cant hold something can take it out of a container

**Comment by HoidC** [comment]
> I dont think it really makes sense that a creature that cant hold something can take it out of a container

animals 100 percent can and frequently do rifle through containers like bins for food

**Comment by deltanedas** [comment]
i cant see a mouse opening a relatively heavy pizza box, but if its open then fair game

**Comment by Anzarot121** [comment]
> I dont think it really makes sense that a creature that cant hold something can take it out of a container

You can't. You eat using the context menu or keybind.

**Comment by Anzarot121** [comment]
I found the problem, but I'm not sure why it exists. I'll close this one and write a new one..
