### ISSUE TITLE
minibomb primed sprite doesnt loop

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#22222]
## Description
it just goes beep then boop thats it

**Comment by deltanedas** [comment]
also pro

**Comment by EmoGarbage404** [comment]
The way the code is written makes this seem intentional. It has a specific animation for playing it once.

**Comment by deltanedas** [comment]
c4 loops so idk

**Comment by osjarw** [comment]
Nowadays the minibomb has a looping animation, so this issue can probably be closed.
