### ISSUE TITLE
Air tank noise spam

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#22251]
## Description
The air tank noise spam is back, people are now setting full tanks to 0.1 then opening valve to spam the noise.
Potential fixes:
- Would be really nice if the volume was maybe scaled to the output pressure.
- Audio hissing noise was not so clearly a small audio loop. 
- Audio file was a more mono toned hiss where the start and end are the same as to not hear the loop.
- It only activated the noise and the movement at a certain pressure threshold.  
Which would be more in line with reality in that the tank has mass that would need to be have a certain amount of air pressure to have sufficient force to move the tank from the air releasing. 

But alas it is just a game so doesn't need to be too crazy, if we can just make the noise spam stop. 🙏

**Reproduction**
- Get a full air tank
- Set to 0.1 release
- Open valve
- Mute the game because the noise spam is so much pain.

**Screenshots**
For the damaging issues in addition context, sub issue to the noise spam.
![image](https://github.com/space-wizards/space-station-14/assets/47093363/4434cfaf-ef05-4f84-aff3-ead67a3f2942)
![image](https://github.com/space-wizards/space-station-14/assets/47093363/271d8ab8-4aee-43c2-83b5-6d1e6be47320)

**Additional context**
The tank does fly around and can be used to bash windows/walls(screencaps) etc in a confined space very low damage though from the look of it took several minutes to break through those reinforced walls but might be faster than a normal mob doing it.

**Comment by TheEmber** [comment]
![Some more video](https://i.imgur.com/Fk0o3Bt.mp4)

**Comment by Titian3** [comment]
The main issue with the noise spam has been solved from #22401 Happy to close now. Thanks!
