### ISSUE TITLE
Marathon Chapel Access bypass

### ISSUE THREAD

**Issue by TurboTrackerss14** [space-wizards/space-station-14#22254]
## Description
The airlocks entering the chapel back room are not access locked. Allowing anyone to enter atleast halfway into what is otherwise their private area. 
The two glass windows are access locked to chaplin only.
**Reproduction**
>walk into chaplin back room through glass airlocks
>fail
>walk into chaplin back room through red airlocks 
>succeed
**Screenshots**
![chaplinaccessissue](https://github.com/space-wizards/space-station-14/assets/130304754/d9554caa-cd05-4dee-be23-62c17a4f1a93)

**Comment by UbaserB** [comment]
@Emisse did you get around to ever fixing this?
