### ISSUE TITLE
glorfcode isnt working

### ISSUE THREAD

**Issue by JoeHammad1844** [space-wizards/space-station-14#22257]
## Description

you know the thing where when you go crit or take damage you go "yo momm-ACK"? that doesnt work.

https://www.youtube.com/watch?v=14nfsmqCIH8 in this video at 5:33 you can clearly see he goes crit but doesnt go ACK like promised in the PR #20562

**Comment by nok-ko** [comment]
I have a fix but it may be bad, putting it in a draft for more experienced contributors to take a look at.
