### ISSUE TITLE
apparently there's audio issues after a recent update

### ISSUE THREAD

**Issue by retequizzle** [space-wizards/space-station-14#22265]
only being brought up now because no one knows to bring up functionality issues on github and they just vent about it in discord:

https://discord.com/channels/310555209753690112/1182501287716208650/1182501287716208650

supposed steps to repro:

1. have multiple instruments within range
2. open UIs for them
3. play midi on one instrument
4. join band from other instruments

this can be done with one or multiple people and apparently throws errors in the console, but as of now i do not have any info about the errors in question. trying to get more information about what the error is, if i find out i will update the issue.

**Comment by retequizzle** [comment]
one suggestion i'll field for a bandaid fix would be to limit how many instruments a person can play simultaneously to 2 and limiting how many can be in a single band to 4

**Comment by deltanedas** [comment]
see https://github.com/space-wizards/RobustToolbox/issues/4664

**Comment by deltanedas** [comment]
an actual bandaid fix would be disabling midi entirely since even just 1 instrument can kill depending on the midi

**Comment by metalgearsloth** [comment]
Dupe https://github.com/space-wizards/RobustToolbox/issues/4642
