### ISSUE TITLE
suit coords just dont work some times

### ISSUE THREAD

**Issue by JoeHammad1844** [space-wizards/space-station-14#22276]
## Description

sometimes when you select somebody on the suit coords thing it just snaps to the middle of the map even though they have coordinates on
**Reproduction**

it seems random
**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/130668733/36021bfb-c116-4ee4-8445-a196f47378b2)

**Comment by Simyon264** [comment]
I think thats because the person is offstation.

**Comment by JoeHammad1844** [comment]
![image](https://github.com/space-wizards/space-station-14/assets/130668733/4e578b1c-920f-455f-9f98-31e5a169ad40)
yup

**Comment by metalgearsloth** [comment]
Are they even on the same map

**Comment by Simyon264** [comment]
If they switch map they disapear from crew monitoring.

**Comment by JoeHammad1844** [comment]
gonna close this because the new crew monitor probably changed something
