### ISSUE TITLE
flashbang / flashes don't fit in the security belt without clicking on it

### ISSUE THREAD

**Issue by mushroomLavender** [space-wizards/space-station-14#22299]
## Description
When putting a flashbang into a security built with the new storage system- it says "This doesn't go in there!", and there is a slight delay before it goes into the security belt. You cannot put it in the security built with the UI open without clicking on the belt itself as it lacks a 2x1 inventory slot for putting them in.

**Reproduction**
1. Wear security belt.
2. Try to put flashbang or flash into the open security belt UI. 

It does not allow you to place either in the belt without clicking on the belt itself.

**Screenshots**
![SS14 Loader_RoBXBIns3B](https://github.com/space-wizards/space-station-14/assets/125529690/63cd2319-ccaa-4d07-a705-fd4267b0a46c)
![SS14 Loader_Tw5nuY8zmb](https://github.com/space-wizards/space-station-14/assets/125529690/01aec616-2b37-4752-b2f7-e61c06b6cd4b)

**Additional context**
This may affect other items. I have only found flashbang and flash so far.

**Comment by osjarw** [comment]
Can't replicate on the current version, this was probably fixed at some point. 
As such this can probably be closed.

**Comment by deltanedas** [comment]
server-only component in whitelist also applies to hand labeler, which fits in utility belt but client mispredicts

**Comment by K-Dynamic** [comment]
I feel like items should have extra text in which toolbelts they fit in

**Comment by osjarw** [comment]
> I feel like items should have extra text in which toolbelts they fit in

This would be quite useful. Like, how am I otherwise supposed to know that I can put power cells and cable coils in my belt?

**Comment by osjarw** [comment]
Somehow managed to move handlabeler component to shared, prediction seems to be working now.
I think that I'll clean this up a bit, and look for similar mispredictions, and then I'll make a PR.

**Comment by osjarw** [comment]
> server-only component in whitelist also applies to hand labeler, which fits in utility belt but client mispredicts

I've submitted a PR #26660 which fixes this specific issue.
I also went through the other belts and duffelbags etc. and didn't notice similar problems.
Though I did find a couple issue-worthy faults in the other belts. 
One which isn't really issue-worthy would be being able to store plungers in assault belts.

**Comment by Plykiya** [comment]
thank you osjarw
