### ISSUE TITLE
Arrivals shuttle can gib players

### ISSUE THREAD

**Issue by TsjipTsjip** [space-wizards/space-station-14#22341]
## Description

#21777 was meant, among other things, to make arrivals more beginner friendly, but it actually made it worse. Shuttle landing on top of you instantly gibs you with no warning.

**Reproduction**

- Stand where shuttle will dock
- Observe

**Comment by Emisse** [comment]
yea i forgot that behavior existed

**Comment by TsjipTsjip** [comment]
> I dont think this is that bad just put a really big warning on the ground.

Issue should be closed when a solution is in place. Any solution works.

**Comment by arimah** [comment]
I think it would make sense if there was an explicit "landing pad" for the shuttle – plating, maybe tiles, with all kinds of markings that make it abundantly clear you do not want to be there. And maybe a railing around it on the outside, so you can't get gibbed by picking a different airlock and walking around. It would make more sense than landing on grass...

**Comment by deltanedas** [comment]
yeah it should only gib if you are on plating (squish) or lattice (diced) otherwide fling like with ftling

**Comment by Kayek14** [comment]
gibbing is okay, there just needs to be a telegraped way for players to know its time to GTFO. 

additionally, its really easy for new players to get gibbed by the arriving shuttle. there is nothing showing that instant death is coming and new players can easily get their first round ended before even arriving on the station.

**Comment by ImRenQ** [comment]
https://github.com/space-wizards/space-station-14/pull/29402

**Comment by IProduceWidgets** [comment]
Intended, and now it has a thingymadoodad what lets you know youre fucked.
