### ISSUE TITLE
Paramedic Door

### ISSUE THREAD

**Issue by Skarletto** [space-wizards/space-station-14#22345]
## Description

We don't have paramedic access. Aspid starts with a paramedic door. No one can open that door, not even the captain or aghosts. It shouldn't be mapped right now.
**Reproduction**

Try to use a paramedic locked door.
**Screenshots**

https://github.com/space-wizards/space-station-14/assets/122584947/8991823d-9971-4ed6-8c41-2b406b4c6c90

**Additional context**

**Comment by Aexxie** [comment]
Looking into this one, I'll take care of it

**Comment by Aexxie** [comment]
fixed
