### ISSUE TITLE
Right clicking an action removes it, but right clicking again in the box without moving the mouse crashes the game

### ISSUE THREAD

**Issue by Darkenson** [space-wizards/space-station-14#22350]
## Description

Right clicking an action will remove it, as it should, but right clicking again in the empty box crashes the game.

**Reproduction**

1. Right click the PDA in the action bar on the left.
2. Right click in the empty box again.

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/4154895/2c1f9d81-6719-4d23-9b14-3ab058290e2a)

**Additional context**

**Comment by notquitehadouken** [comment]
dammit emogarbage

**Comment by AJCM-git** [comment]
no longer happens
