### ISSUE TITLE
hardsuits should be obtainable somehow

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#22364]
sometimes occurs lack of hardsuits, so

**Comment by deltanedas** [comment]
you can buy luxury hardsuit git gud

**Comment by EmoGarbage404** [comment]
they really don't need some kind of infinite way of obtaining them. Roles that need them are given them at spawn via suit storage, additional ones can be found in EVA, and emergency ones can be found in any emergency closet. We already have denied PRs for adding regular hardsuits to RND or cargo (with exception of the luxury suit).

**Comment by JoeHammad1844** [comment]
baystation voidsuits when :trollface:
