### ISSUE TITLE
Chat filter doesn't work anymore

### ISSUE THREAD

**Issue by Chief-Engineer** [space-wizards/space-station-14#22360]
Pressing the button to filter chat channels (local, whisper, radio, etc) doesn't do anything, no options pop up. I'm not sure how long this has been happening. I'm using the split chat view, where chat is more similar to SS13, I'm not sure if it also happens in the other view or not.

It can have a significant impact on adminning because many admins filter out local/whisper so their chat doesn't move at a million lines per second lol

**Comment by ElectroJr** [comment]
I thought this was fixed by #22255? see also #22216 and probably also #22346

**Comment by VasilisThePikachu** [comment]
This was fixed in #22255 and I could get the chat filter to pop up.

**Comment by VasilisThePikachu** [comment]
Apologizes i confused the chat filter with the chat dropdown

**Comment by PJB3005** [comment]
Since the offending code was copy pasted the fix is going to be as easy as applying the same fix as the PR.
