### ISSUE TITLE
Empty Hot choc mug has wrong sprite

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#22403]
## Description
Sprite for empty hot choc mug is the full one.

**Reproduction**
- spawn or get a hot choc mug from a solar best
- spill it all or drink it
- observe the cup still filled
- immersion broken

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/47093363/ddebaf13-ebfe-4ac2-94f3-9bc725322e10)

**Additional context**
N/A

**Comment by Kadeo64** [comment]
literally unplayable. !gamedied
