### ISSUE TITLE
Glorf code activates even when emoting

### ISSUE THREAD

**Issue by Hmeister-real** [space-wizards/space-station-14#22416]
## Description
If someone is emoting and they get hit, glorf code activates in the emote which makes no sense since you aren't speaking the emote.
**Reproduction**
start emoting, get hit
**Screenshots**

**Additional context**

**Comment by MACMAN2003** [comment]
i've had the glorfcode activate while loocing and oocing so maybe checking the prefix or the current selected channel first may solve it?

**Comment by nok-ko** [comment]
There should already be a check for this, that's odd. Will try to reproduce.

**Comment by nok-ko** [comment]
@mirrorcult do you know what this could be?

**Comment by nok-ko** [comment]
Ah, reproduced. Looks like the `SelectedChannel` is literally what channel has been manually tabbed-to or selected via dropdown, *not* the channel as resolved by looking at its prefix.

![image](https://github.com/space-wizards/space-station-14/assets/13428215/087583c3-4452-43ff-aa81-92106dd414d0)

**Comment by mirrorcult** [comment]
mfw
