### ISSUE TITLE
crusher dagger is a meme

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#22428]
## Description
there is no reason to pick it over anything else:

- knife does more damage
- actual crusher does more damage and has better light (i think)
- it cant mine

it should have some unique feature instead of being a meme

**Comment by CrigCrag** [comment]
it is a small lantern with no battery

**Comment by MACMAN2003** [comment]
the crusher knife is the best flashlight in the game

**Comment by deltanedas** [comment]
crusher has a light too (albeit due to bug you have to reenable it after shooting)

**Comment by Aisu9** [comment]
crusher dagger doesn't need an increase in light radius, it's already a lantern+ without battery.
if anything the crusher dagger light should be nerfed and every light source in the game that require a battery should be buffed

**Comment by Slardar0609** [comment]
delete it

**Comment by deltanedas** [comment]
crusher dagger now best knife in the game
