### ISSUE TITLE
When holding ghost sheet it has some stray pixels.

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#22434]
## Description
When holding the ghost sheet, the sprite has some stray pixels on the left and right facing sides in the top right top left, the circled section

**Reproduction**
- Spawn a ghost sheet
- Hold it
- Feel negative because you have a minus symbol above your head.

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/47093363/674c30f7-8fbc-4b77-bb0b-3f57c31a2581)

**Additional context**
NA

**Comment by The-Beebz** [comment]
In my experience trying to reproduce I have some more information.

The sprite sheets themselves are fine and appear to be correct. I didnt have luck reproducing this unless I held the sheet in BOTH hands and then I saw the minus sign as indicated. This might be a result of some improper layering and may be related to #20777

**Comment by Titian3** [comment]
Re-tested this appears to be fixed now:
![image](https://github.com/space-wizards/space-station-14/assets/47093363/09413aeb-15a2-47fb-b728-c7bf71e967f0)
In hand sprite seems to be different/ fixed now.
