### ISSUE TITLE
the station pinpointer is confusing

### ISSUE THREAD

**Issue by JoeHammad1844** [space-wizards/space-station-14#22432]
## Description

the station pinpointer has the same name and description as a regular pinpointer so without meta knowledge ninjas will think they are tracking the disk, and nukies who kill ninjas will also think they are tracking the disk. unless the guidebook clears things up, but i haven't read it :trollface:

**Comment by EmoGarbage404** [comment]
retexture it and give it a new name and desc. EZ PZ

**Comment by UbaserB** [comment]
can i be assigned to this?

**Comment by JoeHammad1844** [comment]
by the way the ninja has access to the nukie shuttle because it uses an agent ID, ill make a new issue for this

**Comment by UbaserB** [comment]
ok we can close this now
