### ISSUE TITLE
the space ninja can access the nukie ship

### ISSUE THREAD

**Issue by JoeHammad1844** [space-wizards/space-station-14#22433]
## Description

since the ninja uses an agent ID, which has syndicate access (importantly, not nuclear access) it can access the ship due to it using syndicate access airlocks

this can be solved in a few ways, both involving changing the doors access to nuclear

1. nukies can buy the nuclear agent ID they spawn with instead of the syndicate agent ID (2TC would be a better price to cut down on the cost for reinforcements)
2. give reinforcements a syndicate ID on spawn (not an agent ID, the one the commander and agent come with in their PDA)

**Comment by 0awful** [comment]
Given [this pr](https://github.com/space-wizards/space-station-14/pull/22476) was closed. This issue should likely be closed.
