### ISSUE TITLE
Firelocks are broken.

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#2244]
Firelocks collide with RPG shots and make you invisible to AI.

(There's probably more bugs to do with this)

![2020-10-13_12-35-03](https://user-images.githubusercontent.com/49448379/95907574-44c04a80-0d8b-11eb-91a2-d4b59681f609.gif)
![2020-10-13_12-35-25](https://user-images.githubusercontent.com/49448379/95907576-4558e100-0d8b-11eb-9f14-41183bd3c6fa.gif)

**Comment by Zumorica** [comment]
I wouldn't call this "broken" as they still do what they're supposed to do. Any bugs of this sort that happen with open firelocks, also happen with open airlocks.

**Comment by metalgearsloth** [comment]
There's a lot of stuff not checking for hard collidables which needs doing. I didn't do it with the pathfinder as it was removed at the time. Stuff like the InRangeUnobstructed also needs to check for it (for drag-drops etc.)

**Comment by metalgearsloth** [comment]
I had a think about it and it should probably just turn off CanCollide altogether rather than hard and that fixes everything. There's nothing currently / planned that relies on non-hard collision with doors.

**Comment by Zumorica** [comment]
Fixed by #2265
