### ISSUE TITLE
With static UI enabled, creatures without hands cannot use inventory

### ISSUE THREAD

**Issue by Anzarot121** [space-wizards/space-station-14#22466]
## Description

Everything can be seen in the screenshots. With Static UI Enabled, I can't see the storage inventory even though it is open. With it turned off, I can see it, I can even pull things out of it onto the ground, but it is in the upper left corner and cannot be moved.
**Reproduction**

Turn on static Ui, don't get food.
Turn off the static UI, get food, but your inventory is in the most inconvenient place.
**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/116586144/8324ac43-f1fc-4f92-8b22-71a38d2922da)
with static Ui
![image](https://github.com/space-wizards/space-station-14/assets/116586144/3d9448ea-73e9-43c4-b0b9-3e83d07a6042)
without static Ui
For some strange reason it appears on the top left and I can’t seem to move it.
**Additional context**

Why are things being merged into the base that have not been tested in any way?

**Comment by metalgearsloth** [comment]
If you want to remake the issue without the unnecessary sniping feel free.

**Comment by Anzarot121** [comment]
> If you want to remake the issue without the unnecessary sniping feel free.

What? The issue was simply ignored. I found what exactly the problem was, added screenshots of this problem, found another problem that was not listed there, added it and for some reason you close it?

**Comment by metalgearsloth** [comment]
> Why are things being merged into the base that have not been tested in any way?

Rule 1 is don't be an asshole.

**Comment by Anzarot121** [comment]
Oh. Sorry. Should I remove it and you will open it or should I create a new one without it? In any case, I'll edit it now. Sorry.
