### ISSUE TITLE
Feature request: Graves should speed up rotting

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#22474]
## Description

Graves have practically no purpose other than hiding a corpse temporarily. If they sped up rot, since well they're in the middle of the earth with worms and stuff; perhaps syndicates would use them more often! As a strat for permakilling instead of just gibbing :)

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/134914314/8012a7e6-94e7-4b16-aabb-56a3a91f3935)

**Comment by Kadeo64** [comment]
do we really need another way to permakill
just buy a syndicate toolbox and gib people

**Comment by HoidC** [comment]
> do we really need another way to permakill
> just buy a syndicate toolbox and gib people

how often are you going to have a lot of dirt and a tool to dig a grave 

this is a niche strategy

**Comment by UbaserB** [comment]
> > do we really need another way to permakill
> > just buy a syndicate toolbox and gib people
> 
> how often are you going to have a lot of dirt and a tool to dig a grave
> 
> this is a niche strategy

idk i thought this might give graves a purpose

**Comment by Hmeister-fake** [comment]
I like this, it would be good for chaplins who uh, don't want to cremate people for some reason(joke). This would actually work if you could only open graves by digging them up with a spade or shovel, that would actually be perfect for hiding bodies or stuff since it's a tool that not many people have on standby.

**Comment by IamVelcroboy** [comment]
They should leave skeletons behind that, when you give cognizine, well...you know...
