### ISSUE TITLE
the new pinpointer sprites dont work

### ISSUE THREAD

**Issue by JoeHammad1844** [space-wizards/space-station-14#22477]
the new sprites introduced in #22435 do not work
![image](https://github.com/space-wizards/space-station-14/assets/130668733/d1a17e63-462f-4ff6-bf11-fa5478f672b1)
![image](https://github.com/space-wizards/space-station-14/assets/130668733/389d71a2-3637-4ede-8859-ee8cb76f3f76)

**Comment by UbaserB** [comment]
close this

**Comment by VasilisThePikachu** [comment]
I think #23236 fixed this
