### ISSUE TITLE
Admin panel features appear to be brokey

### ISSUE THREAD

**Issue by IProduceWidgets** [space-wizards/space-station-14#22472]
## Description

Sorting in the players tab appears to do nothing, and you can no longer right click on the grids panel to use verbs on grids

**Reproduction**

Open admin panel > try to do admin things such as sort players or use verbs on grids > no can do admin things.

**Screenshots**

**Additional context**

**Comment by DrSmugleaf** [comment]
Player tab was fixed by https://github.com/space-wizards/space-station-14/pull/22431

**Comment by IProduceWidgets** [comment]
Grid / maps tab is still cooked, confirmed. It does not display the correct EntIDs and it also doesn't work properly when you right click and try to use verbs.
