### ISSUE TITLE
Can't open bags or similar containers when in harm mode.

### ISSUE THREAD

**Issue by Hmeister-fake** [space-wizards/space-station-14#22509]
## Description
When I'm in harm mode as sec for example, it doesn't let me open my belt to get cuffs out. 

**Reproduction**
Enable harm mode, try to open belt or other container with z or shortcut.

**Screenshots**

**Additional context**
Maybe it's because of my keybinds, but I asked another sec and he sayed he couldn't too. Also no screenshot cause I'm too tired and want to go mi mi mi.

**Comment by EmoGarbage404** [comment]
SharedStorageSystem line 148.

Just remove the check for being in combat mode.
