### ISSUE TITLE
Feature request: Clown Cuffs.

### ISSUE THREAD

**Issue by Hmeister-fake** [space-wizards/space-station-14#22511]
## Description
Re-use #22499 and make a variation of cuffs called clown cuffs. Make them a 1 tc Service job specific syndie item, also maybe make them craftable with a clown horn, cloth and handcuffs. They are normal cuffs, except they replace every normal cuff noise with a simple Honk! Good for "stealth" or at least being less suspicious when you hear it.

**Additional context**
Remove any mention of erp and maybe make some minor sprite changes aswell, I literally have no clue how to do any of what i am suggesting, I would if I could.

**Comment by Errant-4** [comment]
If it's a clown item, it could have funny/weird stuff happen when the person tries to take them off, perhaps by random chance

**Comment by lzk228** [comment]
but what is the difference between default handcuffs?
if its only for fun, then it looks not needed

**Comment by deltanedas** [comment]
so when clown kidnaps captain it doesnt sound sus
every validhunter has the cablecuff sound commited to memory

**Comment by EmoGarbage404** [comment]
this adds basically nothing and just invalidates makeshift cuffs.

**Comment by Hmeister-fake** [comment]
> this adds basically nothing and just invalidates makeshift cuffs.

It takes non-craftable sec handcuffs to make as a non-syndie, so no it doesn't really. And it fixes the same issue that the syndie snack box solves, lack of materials (food and drink with the snackbox), in this case lv wires to make makeshift cuffs.

**Comment by EmoGarbage404** [comment]
> It takes non-craftable sec handcuffs to make as a non-syndie, so no it doesn't really. And it fixes the same issue that the syndie snack box solves, lack of materials (food and drink with the snackbox), in this case lv wires to make makeshift cuffs.

using uplink listings to subvert craftable items just makes those items irrelevant. The syndie snack box is meant for nuke ops, anyways, since they're more likely to be in an extended situation with no food available. Service traitors don't need special cuffs for the basically non-existent situation where there's no _lv cable_ on the station.

**Comment by CatMagic1** [comment]
> but what is the difference between default handcuffs? if its only for fun, then it looks not needed

me when fun
![fbt-renvor](https://github.com/space-wizards/space-station-14/assets/135462166/3d5fb3cf-4086-4fe3-8fa3-2ee33c44fcd1)

**Comment by Hmeister-fake** [comment]
> > Service traitors don't need special cuffs for the basically non-existent situation where there's no _lv cable_ on the station.

It's not just for that reason, it's also to mask the sound of normal cuffs, as sec or anyone in general is going to find a clown horn noise less noteworthy than the normal cuffs or zips noise. Also it would help a lot with validhunting. Overall funny Honk Cuffs are funny.

**Comment by Hmeister-real** [comment]
This is still a cool idea and fresh

**Comment by EmoGarbage404** [comment]
yet it wasn't

**Comment by deltanedas** [comment]
erp team its joever

**Comment by Hmeister-real** [comment]
oh ye, Goobstation added clowncuffs. and it was a goobd idea

**Comment by GroggleG** [comment]
> oh ye, Goobstation added clowncuffs. and it was a goobd idea

goob idea for sure
