### ISSUE TITLE
A mob without hands can drag creatures with the clumsy tag onto tables.

### ISSUE THREAD

**Issue by Anzarot121** [space-wizards/space-station-14#22516]
## Description

You can, being any entity, even a mouse, except for some reason an artifact, kill a clown or Pun and they have no way to notice it.
**Reproduction**

1. Be Hamlet,
2. Drag the clown model onto the table
3. Watch the clown fall into crit after 10 repetitions.
**Screenshots**

**Additional context**

**Comment by deltanedas** [comment]
introduced by #16251 it should have a check to see if target == self
