### ISSUE TITLE
Feature Request: Red Phone For Nukie Outpost

### ISSUE THREAD

**Issue by Kezu02** [space-wizards/space-station-14#22528]
## Description

Since ahelping is the only way for them to ask for gimmick stuff, I don't see why the outpost shouldn't start with one. Would just need the admin notif changed from Centcom to Syndicate.

**Comment by Errant-4** [comment]
Blood-red Phone, you mean

**Comment by nikthechampiongr** [comment]
Have it be the blue phone it will be funny. NT gets the red phone while the nukies get the blue one.
