### ISSUE TITLE
Feature request: Functional envelopes

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#22535]
## Description

We have envelope sprites in the game but they aren't functional. I believe will help deliver important notes meant for specific individuals (perhaps being only able to open the package with your id card/PDA similar to how delta-v does it) and you could write who it's from and even stamp it for legitimacy. It would also have a lot of opportunity for roleplay too, like having to deliver top-secret documents.

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/134914314/a03b839e-7aca-427a-8414-12ae31ba8deb)

**Comment by Emisse** [comment]
been discussed before and its acceptable
