### ISSUE TITLE
Playing The Clown Recorder Crashes The Game

### ISSUE THREAD

**Issue by Kezu02** [space-wizards/space-station-14#22593]
## Description

Crashed once on the fourth recorder. A second time on the first recorder. The Honkmother's given them too much power.

**Comment by nikthechampiongr** [comment]
So anyways. I tested it and it seems this happens whenever the clown recorder tries to play sitcom_laugh2.ogg. I tested it several times with sitcom_laugh2.ogg disabled and it didn't crash at all and then tested it with only that one enabled and crashed every time.

**Comment by Mirino97** [comment]
Does this crash only the clown's client or every client around it?

**Comment by Slava0135** [comment]
2023 clown recorder incident

**Comment by nikthechampiongr** [comment]
> Does this crash only the clown's client or every client around it?

From my brief testing, it only crashed the person using it. However today on miros I crashed while roaming around as a ghost like twice and the ahelp reporting this came from miros. I suspect that this effects other things.

**Comment by nikthechampiongr** [comment]
@Mirino97 Why are you adding "Needs Replicating"? The bug has been replicated.

**Comment by Mirino97** [comment]
> @Mirino97 Why are you adding "Needs Replicating"? The bug has been replicated.

I know we have replicated the "this bug crashes the 'clown's client", but have we confirmed it crashes other people's clients too?
To tl;dr my thoughts is that: If this crashes only the user of the recorder, then it's not such a big issue. If it DOES reliably crash all clients in the audio range, then it's a big issue and needs to be addressed asap.

**Comment by nikthechampiongr** [comment]
> > @Mirino97 Why are you adding "Needs Replicating"? The bug has been replicated.
> 
> I know we have replicated the "this bug crashes the 'clown's client", but have we confirmed it crashes other people's clients too? To tl;dr my thoughts is that: If this crashes only the user of the recorder, then it's not such a big issue. If it DOES reliably crash all clients in the audio range, then it's a big issue and needs to be addressed asap.

I did spin up 2 clients when I was testing this. When I crashed the one with the recorder the other was fine. While I think there are other similar bugs I'm not sure they have anything to do with the recorder.

**Comment by nikthechampiongr** [comment]
Eh you know what I'm stupid. It's probably the same bug disguised as something else. It does need more investigation.
