### ISSUE TITLE
pneumatic cannon is broken

### ISSUE THREAD

**Issue by Ilya246** [space-wizards/space-station-14#22595]
## Description

you can't insert a gas tank into it, it tries to insert it into inventory instead at all times

**Reproduction**

get pneumatic cannon, attempt to insert gas tank

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/57039557/1d5d2144-79cd-4cd5-840f-f9e37267b9a3)

**Comment by EmoGarbage404** [comment]
can't you insert via the verb in the context menu

**Comment by Ilya246** [comment]
there is none

**Comment by deltanedas** [comment]
i will vv it while trolling and see if the slot is deleted or something

**Comment by deltanedas** [comment]
WOMM, thats probably you using the admeme cannon which doesnt use gas tanks

**Comment by deltanedas** [comment]
![16:59:13](https://github.com/space-wizards/space-station-14/assets/39013340/c3a59fe7-1279-48ec-b6b4-9995722457c7)
left is admeme
right is real

**Comment by EmoGarbage404** [comment]
trolled

**Comment by Ilya246** [comment]
> WOMM, thats probably you using the admeme cannon which doesnt use gas tanks

definitely was real cannon

**Comment by Ilya246** [comment]
okay it magically works for me too now somehow

**Comment by deltanedas** [comment]
evil killer
