### ISSUE TITLE
Bag content explosive resistance is applied to wearer

### ISSUE THREAD

**Issue by Arendian** [space-wizards/space-station-14#22601]
## Description

While wearing a bag the explosion resistance that's supposed to only be transferred to the contents of the bag are also applied to the entity wearing the bag.
This means everyone using a syndicate duffel bag has 90% explosive damage reduction, and people wearing any other bag have a 10% explosive damage resistance.

**Reproduction**

Explode an explosive grenade at the feet of a naked Urist: 50 blunt | 50 piercing | 50 heat damage
Explode an explosive grenade at the feet of a naked Urist wearing a syndicate duffel bag: 4.96 blunt | 4.96 piercing | 4.96 heat damage.

**Comment by GoodWheatley** [comment]
@deltanedas pro

**Comment by deltanedas** [comment]
????? how
