### ISSUE TITLE
Immovable Rod freezes game if it hits you

### ISSUE THREAD

**Issue by Varen** [space-wizards/space-station-14#22625]
## Description
Getting hit by the immovable rod crashes the game.

**Reproduction**
Get hit by immovable rod. Screen becomes glitchy and game locks, requiring a reconnection.

**Screenshots**
n/a

**Additional context**
n/a

**Comment by tutoumi** [comment]
it doesn't only remove you from existence, it remove your connection too, this should be a feature tbh

**Comment by UbaserB** [comment]
I got hit by the rod and this didn't happen.. can someone see if this can be replicated?

**Comment by Dutch-VanDerLinde** [comment]
> I got hit by the rod and this didn't happen.. can someone see if this can be replicated?

pretty sure it got fixed
