### ISSUE TITLE
slow fire ruined teg burn chambers

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#22655]
## Description
- slow burn 30.5% oxygen 69.5% plasma burned at an astonishing 0.2K/s
- adding a little more oxygen it caps out close to 3kK which will last a few minutes at best, assuming teg isnt slower to compensate
![09:10:32](https://github.com/space-wizards/space-station-14/assets/39013340/fd1ff2cf-ddf3-429c-9e00-367ea04b479f)

**Comment by Ilya246** [comment]
you have to make it make trit now yes
or use a chamber for the burn so you have more fire but that will eat plasma
