### ISSUE TITLE
Tear Gas Issues

### ISSUE THREAD

**Issue by Aexxie** [space-wizards/space-station-14#22658]
## Description

tear gas can be taken out of belt, but not be put back in.
**Reproduction**

**Screenshots**

**Additional context**

I WILL FIX THIS LATER, THIS IS JUST SO I CAN REMEMBER

**Comment by deltanedas** [comment]
pro

**Comment by Aexxie** [comment]
> pro

omw to fix it while playing warden on extended

**Comment by Aexxie** [comment]
ok this is actually weirder than I thought. You can click on the belt while holding one, get the message "this doesnt go in there!", but it will still be put in BUT you cant put it in from gridinv. peculiar..

**Comment by Aexxie** [comment]
closing in favor of a larger issue I discovered.
