### ISSUE TITLE
origin freezer is spaced

### ISSUE THREAD

**Issue by JoeHammad1844** [space-wizards/space-station-14#22665]
![image](https://github.com/space-wizards/space-station-14/assets/130668733/d45ac4c5-6f99-4884-84c9-356d97e70168)

**Comment by deltanedas** [comment]
should have freezer marker instead of space

**Comment by Errant-4** [comment]
The cooling system's is connected to the room with a passive went. But these pipes are directly connected to the waste loop, so the waste pump at atmospherics can directly drain the air from the freezer room

**Comment by brainfood1183** [comment]
ill fix it, thanks for posting this
