### ISSUE TITLE
Borgs may sometimes not have their laws updated once emagged.

### ISSUE THREAD

**Issue by nikthechampiongr** [space-wizards/space-station-14#22673]
## Description

In round #41171 on lizard borg Si-6191 was emagged but all their laws stayed the same.
**Reproduction**

I have no idea.

**Comment by deltanedas** [comment]
iirc if you have panel closed and emag it doesnt change anything but does have the examine

**Comment by Jarmer123** [comment]
One bug related to this is that if you emag the panel open it says that the internal laws are damage despite well... not being damaged

**Comment by deltanedas** [comment]
presumably a 1 line fix in OnEmagged

**Comment by UbaserB** [comment]
repeat of this issue #21577
