### ISSUE TITLE
Playing specific audio files can crash the game of clients that hear it

### ISSUE THREAD

**Issue by ElectroJr** [space-wizards/space-station-14#22676]
See #22593 and #22641 There are probably more audio files, and more might be uploaded, so it still urgently needs fixing.

**Comment by ElectroJr** [comment]
If somebody wants to start looking at it, maybe check if those same audio files also caused crashes prior to space-wizards/RobustToolbox/pull/4715 ?

**Comment by Mirino97** [comment]
Please ignore the last referenced issue, a mistake on my part.
