### ISSUE TITLE
Intermittent server fetch and auth issues after most recent client update

### ISSUE THREAD

**Issue by Derrek-Larson** [space-wizards/space-station-14#22682]
## Description
Launcher will fail to authenticate, fail to load master server list, and fail to fetch server manifest. 
Retries sometimes remedy the issue, though recently I had to go as far as re-installing the launcher and refreshing my authorization status.

**Reproduction**
Issues occur during regular use of the launcher - logging in, opening server tab, connecting to server.

**Screenshots**
![error connecting](https://github.com/space-wizards/space-station-14/assets/32825703/f5baf697-dadf-44b3-9545-91042bdf0571)
I will amend logs if the issue persists since most recent re-installation - sorry.

**Additional context**
Issues never occurred prior to the most recent client update, these issues feel different than servers going down or lagging and may be linked to the launcher itself. I also just found the buttons to clear server content and engines, and will amend this if those help.

**Comment by PJB3005** [comment]
This is just our server having issues AFAICT.

**Comment by Emisse** [comment]
this was just our server issues
