### ISSUE TITLE
RCD building effect doesn't disappear if the doafter is cancelled.

### ISSUE THREAD

**Issue by EmoGarbage404** [space-wizards/space-station-14#22717]
## Description

It remains on screen until the animation finishes.

**Reproduction**

- get RCD
- start building
- immediately cancel by moving
- animation continues playing.

@chromiumboy

**Comment by chromiumboy** [comment]
That's actually working as intended, there's no cancel animation

**Comment by EmoGarbage404** [comment]
> That's actually working as intended, there's no cancel animation

it should just disappear IMO. the animation continuing for 5+ seconds looks jarring. it's also easy to spam.

**Comment by chromiumboy** [comment]
It's only 3.2 seconds actually :P 

But alright. I can probably just make a list of effect entities and delete them if building is cancelled

**Comment by chromiumboy** [comment]
Resolved as of #22799
