### ISSUE TITLE
attacking transfers victims prints to the weapon

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#22714]
## Description
it does dna too, but prints should not be here

![17:12:54](https://github.com/space-wizards/space-station-14/assets/39013340/c53a65bf-4d4a-4809-b26b-6870f0cf8a42)
i stabbed urist
top prints are from urist (bad), fibers from me, dna from urist

**Comment by themias** [comment]
Was just about to open that myself! You don't even need to hit them, you can just touch them.

Looks like this was existing behavior. The ContactInteractionEvent gets triggered on all of these.

**Comment by deltanedas** [comment]
that shouldnt be a thing even when not fighting
if i use bruise packs on you for example, why would your prints magically appear on the bruise packs

**Comment by themias** [comment]
Absolutely, it is an awful bug. I meant existing behavior as in, existing bug.
