### ISSUE TITLE
feature request: wall clicking

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#22742]
saw a server in ss13, where if you click on wall, you heard a sound and message in chat "you click that wall. its motionless" or something like that
dont remember if it was local message or people around could see that youre clicking walls

makes sense when youre checking for fake wall

**Comment by Errant-4** [comment]
Tapping a wall and getting a tap back from the other side could have some niche uses, especially when opaque doors are involved

**Comment by OctoRocket** [comment]
It would be cool, but it seems like it could get annoying if you click on a wall accidentally.

**Comment by lzk228** [comment]
the pr is closed soo
