### ISSUE TITLE
Vehicles Gain Speed From Floor Ice

### ISSUE THREAD

**Issue by Kezu02** [space-wizards/space-station-14#22750]
## Description

Driving vehicles over ice permanently makes them go faster/takes out their friction.

**Comment by JoeTheJanitor** [comment]
More specifically it seems to remove their acceleration, so they dont have to speed up to top speed. I’m guessing when it goes on the ice, the game makes it have that same slow acceleration that players walking on ice would get, and then when it comes off the ice it removes that slowed acceleration, but in the process would remove the slow acceleration inherent to the vehicle.
Also fast wheelchair go brrrrrr

**Comment by Pangogie** [comment]
Vehicles removed awaiting better implementation.
