### ISSUE TITLE
Have flashlights project light in the direction the player is facing

### ISSUE THREAD

**Issue by SoulSloth** [space-wizards/space-station-14#2280]
Per BUSHBOY's suggestion in discord:  _have you tried flashlight as a cone? where behind you is not nearly as bright, like you have to point in direction for brightest side. like real life? you could still have some like radiation off the rear, but its brighter on front._

I think it's wroth considering since it would ramp up tension for blackouts. Would also be nice for it to have some trade-offs vs circular light sources like the lantern.

**Comment by metalgearsloth** [comment]
The problem with this is you're gonna be setting people's rotation every tick and it seems bad for epileptic people if someone can strobe them IMO.
