### ISSUE TITLE
Add back Fireaxe and Desword to the uplink

### ISSUE THREAD

**Issue by Hmeister-fake** [space-wizards/space-station-14#22819]
## Description
This change just removed flavour from nukeops and syndies, I liked it how it was before and I think so do a lot of people + with the new wall changes not being able to buy a fireaxe as a syndie is a huge pain. 

**Additional context**
Just add the 2 back to nukeops at the very least, maybe syndies aswell.

**Comment by Errant-4** [comment]
Nukeops now get one fire axe for free on their shuttle #22820

**Comment by EmoGarbage404** [comment]
> I liked it how it was before and I think so do a lot of people

unless you have an actual reasoning about why this should be done don't make an issue for it.

we're not gonna revert a balance change made two days ago because it "removes flavor"

**Comment by EmoGarbage404** [comment]
Both of these items were intentionally and specifically removed in addition to the wall changes.

> Without at least being able to buy an axe, the only option syndicates have of breaking into places is the emag, hacking, getting access and bombs, most of those being very loud and instantly mark you as an antag or at least a tider without giving you an option of self defense without other purchases.

you've listed off plenty of alternative methods of breaching that all work perfectly fine. The only issue, and part of the reason this item was removed, is because you not only get powerful breaching but also an extremely strong melee weapon.

> most of those being very loud 

since when was emagging, hacking, or _getting access_ loud?

> Also please don't close my issue before others have had a chance to discuss it,

this has been discussed to death in the discord.

**Comment by Hmeister-fake** [comment]
> you've listed off plenty of alternative methods of breaching that all work perfectly fine. The only issue, and part of the reason this item was removed, is because you not only get powerful breaching but also an extremely strong melee weapon.

For it's old price, it was very fair since you could still be disarmed, stunned or slipped if you didn't buy no slips. Now you have no breaching tools without first buying a second weapon.

> since when was emagging, hacking, or _getting access_ loud?
>>  mark you as an antag or at least a tider

**Comment by metalgearsloth** [comment]
github issues are for genuine bugs or stuff that should get implemented rather than for bikeshedding so further discussion is encouraged on discord instead.

**Comment by Hmeister-fake** [comment]
> does a giant valid syndie fireaxe not mark you as an antag?

Yeah but then you can defend yourself, I guess bombs and tools can too but the axe is more reliable
