### ISSUE TITLE
Feature Request: Salt Rocks in Salvage Ore

### ISSUE THREAD

**Issue by Kadeo64** [space-wizards/space-station-14#22825]
## Description
Salt Rocks should be added to salvage so sodium, chloride, and iodine are easier to obtain for chemistry. When ground or dissolved in a water container, they give 5u for each of these chems. Can also be used for making Saline solution in a pinch.

**Comment by Zadeon** [comment]
I would like to take a crack at this for more practice, if that is okay.

**Comment by Kadeo64** [comment]
> I would like to take a crack at this for more practice, if that is okay.

nobody else is doing it as far as I know so go ahead

**Comment by Zadeon** [comment]
Did you mean **chlorine** instead of chloride? Because chloride doesn't exist in game as a reagent.

**Comment by Kadeo64** [comment]
> Did you mean **chlorine** instead of chloride? Because chloride doesn't exist in game as a reagent.

I meant chloride (Sodium Chloride). Adding chlorine might make emergency saline a bad investment but I dunno.

**Comment by Zadeon** [comment]
> I meant chloride (Sodium Chloride). Adding chlorine might make emergency saline a bad investment but I dunno.
In game, chloride (Sodium Chloride) is table salt. It is made from heating sodium and chlorine together. The way I have it now is grinding salt "ore" gives sodium, chlorine, and iodine. So the ingredients are there for "chloride" (Sodium Chloride or table salt, however you want to call it) when you grind salt. Are you saying that grinding salt should give two reagents: table salt and iodine instead?

**Comment by Kadeo64** [comment]
salt rocks should probably just give the basic ingredients (sodium, chlorine, iodine) because science won't ever make an electrolyzer for salvage and we don't need salvage stealing more from medical.

**Comment by PolterTzi** [comment]
> salt rocks should probably just give the basic ingredients (sodium, chlorine, iodine) because science won't ever make an electrolyzer for salvage and we don't need salvage stealing more from medical.

I don't quite understand why salvage would want specifically sodium and chlorine over table salt. Could be me forgetting something, but feels like salt would be more useful.
And it just feels weird to have ground salt be already electrolised.
