### ISSUE TITLE
ten sided dice go from 1 to 10 and not 0 to 9 like they are supposed to.

### ISSUE THREAD

**Issue by a-man-of-soft-ideas** [space-wizards/space-station-14#22826]
its not a big issue, it can wait

**Comment by Tayrtahn** [comment]
Small issues are great for new contributors like myself! This should be an easy fix.

Also, I learned something new about dice today, so that's cool.

**Comment by a-man-of-soft-ideas** [comment]
@Tayrtahn oh thank you! 

> Also, I learned something new about dice today, so that's cool.

i should specify, most 10 sided dice go from 0 to 9, they are the most common and used in tabletop rpg's. there are 10 sided dice that go from 1 to 10, but they are rare or for specific games.

**Comment by 0x6273** [comment]
It should be 0 to 9. There's a d100 that rolls 00 to 90, and you are meant to be able to roll them together and treat 0 + 00 as 100.

**Comment by a-man-of-soft-ideas** [comment]
> It should be 0 to 9. There's a d100 that rolls 00 to 90, and you are meant to be able to roll them together and treat 0 + 00 as 100.

@0x6273 that's what this issue is about, to make it 0 to 9. I'm a non-native English speaker, so I may need help making it clearer! how else should I phrase the title of this issue?

**Comment by 0x6273** [comment]
> > It should be 0 to 9. There's a d100 that rolls 00 to 90, and you are meant to be able to roll them together and treat 0 + 00 as 100.
> 
> @0x6273 that's what this issue is about, to make it 0 to 9. I'm a non-native English speaker, so I may need help making that clearer! how else should I phrase the title of this issue?

The issue title is clear. I was responding to your previous comment where you seemed unsure if it should be changed or if a new die should be made instead.
