### ISSUE TITLE
Pointing arrows sync their transform to the client every tick

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#2282]
(low prio perf thing) All the client really should care about is the start to save on bandwidth. Plus it should probably not be an entity.

https://github.com/space-wizards/space-station-14/blob/ed1a96e536026046c4ad6c2c73f7968f09e1205c/Content.Server/GameObjects/Components/Pointing/PointingArrowComponent.cs#L73

**Comment by EmoGarbage404** [comment]
pretty sure this is completed? arrows just use an animation now.
