### ISSUE TITLE
Shooting near an object makes you hit it as well

### ISSUE THREAD

**Issue by clement-or** [space-wizards/space-station-14#2283]
Doesn't seem too hard to fix

![shoot ss14](https://user-images.githubusercontent.com/29918611/96333842-90654380-106c-11eb-928e-164554fd830c.gif)

**Comment by Zumorica** [comment]
Definitely not intended, but nice

**Comment by SweptWasTaken** [comment]
This should be fixed asap. Really annoying.

**Comment by SweptWasTaken** [comment]
Just meant to comment my B

**Comment by SweptWasTaken** [comment]
I am actually 减速

**Comment by clement-or** [comment]
Maybe you guys should add "Junior Job" label and a priority label ?
