### ISSUE TITLE
Weird glitch on the f3 overlay

### ISSUE THREAD

**Issue by nikthechampiongr** [space-wizards/space-station-14#22835]
## Description

See image
**Reproduction**

I have no idea, it just happens on my system.
Running Endeavouros with 6.6.7-zen1-1-zen
**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/32041239/0d3d19ef-8435-436d-8e98-b320626a54de)

**Comment by Emisse** [comment]
is your gpu running fine

**Comment by nikthechampiongr** [comment]
> is your gpu running fine

Seems so
![image](https://github.com/space-wizards/space-station-14/assets/32041239/2df82851-d0d6-41c8-8d4a-4a5d522e58d7)

**Comment by nikthechampiongr** [comment]
I don't have any other visual glitches.

**Comment by GoodDays13** [comment]
I have the same issue, but the issue also occurs in some other menus such as the map. Are you on Linux?

**Comment by GoodDays13** [comment]
https://github.com/space-wizards/space-station-14/assets/42877449/33627d19-7aa0-4571-b80b-1d231bfcf662

**Comment by EnrichUranium** [comment]
Having the same issue.  Radeon 6750XT, EndeavourOS running 6.7.4-lqx1-1-lqx kernel.  But i've had the issue since playing starting in like November/December?  The console's are where its most noticeable for me, the game looks fine apart from opening that f3 overlay or opening up any console or map.

**Comment by nikthechampiongr** [comment]
Surprisingly testing it now it works just fine. @GoodDays13 @EnrichUranium can you both try to upgrade your systems and see if it's still an issue?

**Comment by GoodDays13** [comment]
My system seems to be upgraded. Have you changed any of your system specs since you last had the issue?

**Comment by nikthechampiongr** [comment]
> My system seems to be upgraded. Have you changed any of your system specs since you last had the issue?

No

**Comment by GoodDays13** [comment]
Can you show your entire f3 menu showing all the specs?

**Comment by EnrichUranium** [comment]
> Surprisingly testing it now it works just fine. @GoodDays13 @EnrichUranium can you both try to upgrade your systems and see if it's still an issue?

I run my updates on Sunday morning and just patched everything again today to make sure some mesa update didn't come through.  Still having the issue.  I know the F3 menu was for nik, but here was mine.

![image](https://github.com/space-wizards/space-station-14/assets/157912147/e41e4c42-6435-42cf-8f0d-3c4d312be417)

**Comment by GoodDays13** [comment]
@EnrichUranium My F3 is actually fine right now. I haven't played for a few days so idk when it fixed. You should check yours.

**Comment by EnrichUranium** [comment]
Nope, just tried it, still the same issue.   Just ran all my updates on flatpaks & system packages as well and downloaded whatever the newest server build so I could test it locally.  
![image](https://github.com/space-wizards/space-station-14/assets/157912147/4ad2fa91-de55-451e-b44f-b7d5533d3dcb)

**Comment by EnrichUranium** [comment]
I'm not really sure what changed, since I don't run my updates until Saturday/Sunday, but everything works fine now and I'm not getting the glitchy f3 overlay or console glitches with text/dots.  Just noticed it yesterday playin a cargo tech.

**Comment by nikthechampiongr** [comment]
I guess it was just some random bug with a package.
