### ISSUE TITLE
PA sometimes broken Again.

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#22853]
## Description
On some round starts the port and starboard emitters are not detectable and require admin respawning the whole PA to get them to sync on the console.

**Reproduction**
Is hard reproduction as I am just seeing this every so often in aHelps:
But the screenshot illustrates the broken state. Its all wired and screwed down correctly, just cant sync those last two, even if they are independently respawned just the emitters.

**Screenshots**
<img width="505" alt="image" src="https://github.com/space-wizards/space-station-14/assets/47093363/ebf4e6c0-0eb6-4960-9e79-1f39759b7f47">

**Additional context**
This was an issue about 2-3 months ago now but it looked like it was resolved. Unsure it its map specific or corner case regression bug. This was on bagel map.

**Comment by PJB3005** [comment]
Just tested and it works, assuming fixed.
