### ISSUE TITLE
Barber scissors range issue

### ISSUE THREAD

**Issue by liltenhead** [space-wizards/space-station-14#22887]
## Description
Once you start editing someone's hair, you can edit it from any range.

**Reproduction**
Start working on someone's hair and walk away. 

**Screenshots**
![imagee](https://github.com/space-wizards/space-station-14/assets/104418166/a08e6a39-2857-49fb-826a-3c2aedb19515)

**Comment by Cyber-Finn** [comment]
it's not a bug, it's a feature (For a quick win/fix, rename the scissors to "Quantum entangled barber scissors")
