### ISSUE TITLE
The implementation of excited groups is broken

### ISSUE THREAD

**Issue by LemonInTheDark** [space-wizards/space-station-14#2295]
Yo, your implementation of excited groups, like all repos using tg LINDA past this pr https://github.com/tgstation/tgstation/pull/19189, is broken.

Because excited groups break down as soon as a turf within them is removed from active, this line breaks the core purpose of excited groups, slowly growing to represent the "processing" turfs in an area, then settling to equalize atmos diffs. https://github.com/space-wizards/space-station-14/blob/master/Content.Server/Atmos/TileAtmosphere.cs#L741

I'm not sure how relevant this is to your codebase, as you have monstermos's equalization to fill somewhat the same role, but I thought you'd want to know.

I've implemented a hellfix here: https://github.com/tgstation/tgstation/pull/52493, but it's a bit bloated (Isn't finished yet), and I only do what I do because I need to lower the active turf count as much as I can. In your case, removing the portion of the line that deals with timers, while it would make planetary turfs a lot laggier, will solve the issue. Or just remove excited groups, or keep them as they function now, as low group size settlers.

**Comment by Zumorica** [comment]
Thankfully, SS14 doesn't support planet atmos yet (and if we added support for it, it'd be a different component/implementation since we have the power to do that with entity grids) so I'm going to try to port your fixes. Thanks for letting us know!
