### ISSUE TITLE
cryo works slowly (due to atmos changes?)

### ISSUE THREAD

**Issue by Ilya246** [space-wizards/space-station-14#22958]
## Description

people in cryo cool down slower than they used to

**Reproduction**

1. put naked person in cryo with maximum cooled air
2. watch temperature
3. cools down very slowly

has been tested ingame

**Screenshots**

none
**Additional context**

i believe this has been caused by notafet's gas heat capacity adjustion PR

**Comment by deltanedas** [comment]
fake

**Comment by koteq** [comment]
Works on my machine, though I've heard from players that it used to work much faster in terms of cooling and healing per second.

https://github.com/space-wizards/space-station-14/assets/1192090/ff5d17c9-5bad-4130-bea4-edf70a66ba1e

I used 144af23 build for the recording

**Comment by Ilya246** [comment]
tested it myself, it successfully cools and heats players, however, i believe it does it significantly slower than before
i still believe there is an issue in said slowness existing, renaming the issue

**Comment by Ilya246** [comment]
been fixed
