### ISSUE TITLE
Use InvariantCulture instead of the system locale for consistent float to string conversion

### ISSUE THREAD

**Issue by koteq** [space-wizards/space-station-14#22965]
## Description

There are plenty of float-to-string and string-to-float conversions in the codebase. Notoriously, [C# uses the current system culture](https://learn.microsoft.com/en-us/dotnet/api/system.single.tostring?view=net-8.0) setting to do the conversion by default, which results in buggy serialization/parsing in certain cases.

I think it'd be wise to switch the default culture everywhere internally to the [InvariantCulture](https://learn.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.invariantculture?view=net-8.0) to avoid the bug altogether, limiting the current system culture usage to UI only.

**Reproduction**
Launch the game in a locale that uses something other than period symbol for [decimal separators](https://en.wikipedia.org/wiki/Decimal_separator), ru-RU or fr-FR, for example. Try to operate a pressure pump, inputting fractional values, such as `101.3` and `101,3`.

The issue isn't limited to a pressure pump alone. The other bug that I, personally, experience often is tied with how the `ui.separated_chat_size` console variable is serialized into `0,6,0` on my system, instead of the expected `0.6,0`. And because the parser logic uses `sizing.Split(",")` it results in a bug.

**Screenshots**
n/a

**Additional context**

Here is a good article on [using CultureInfo in .NET](https://phrase.com/blog/posts/all-you-need-to-know-about-cultureinfo-in-net-applications/)

**Comment by koteq** [comment]
As a quick and dirty solution, I can file a PR that adds `CultureInfo.DefaultThreadCurrentCulture = CultureInfo.InvariantCulture;` to the `Program.cs`. However, I'd like to hear some opinion on the approach.

**Comment by koteq** [comment]
Maybe my phrasing was a bit rough or incorrect, English isn't my mother tongue. I think the idea is to set DefaultThreadCurrentCulture to InvariantCulture right on the Client start, while keeping CurrentUICulture to the system default or deriving it from the current game's locale. This way, all the `ToString` and `Parse` calls become consistent, while still allowing to do UI i18n.

**Comment by mirrorcult** [comment]
> As a quick and dirty solution, I can file a PR that adds `CultureInfo.DefaultThreadCurrentCulture = CultureInfo.InvariantCulture;` to the `Program.cs`. However, I'd like to hear some opinion on the approach.

this would be a fine solution imo--it might break something for someone but cant think of anything off the top of my head

**Comment by PJB3005** [comment]
I do agree this is how it "always should have been", but we can't just quick and dirty change this as it'll definitely break existing localization.

For what it's worth, a long time ago I made a helper type called `Parse` so you can just do `Parse.Float()` and it's more brief and does invariant by default. We really should use it by default.

**Comment by koteq** [comment]
Interestingly, the FixedPoint2 implementation defaults to the InvariantCulture.
https://github.com/space-wizards/space-station-14/blob/aadc75a07abcbffeea292b61411838fbfd2777e6/Content.Shared/FixedPoint/FixedPoint2.cs#L272

---

Also, I've tried my suggested `CultureInfo.DefaultThreadCurrentCulture = CultureInfo.InvariantCulture;` approach locally, and it didn't work. Anyway, I'll create a bunch of tiny PRs to fix the places where the issue result in buggy behavior I'm aware of.

**Comment by koteq** [comment]
I think I've prematurely run to conclusions on how locales work in the game. Now, after seeing more code from different places, I believe ~~it can't be helped~~ a more precise work is required.

**Comment by koteq** [comment]
The LocalizationManager already does what I've been asking in the ticket. It sets culture application wide. There are, however, some blind spots that need to be fixed ad-hoc.
