### ISSUE TITLE
T-ray scanner doesn't penetrate carpets

### ISSUE THREAD

**Issue by LordCarve** [space-wizards/space-station-14#22970]
## Description

The t-ray scanner does not penetrate carpets. It should.

**Reproduction**

Put subfloor infrastructure, cover it with a tile and a carpet.

**Screenshots**

![tray](https://github.com/space-wizards/space-station-14/assets/27449516/d65993d7-d3be-4fcb-a91b-6c8dd63c5694)

(Pictured: t-ray off and on)

## Expected to be automatically fixed with tile smoothing here listed here: #5188

**Comment by graevy** [comment]
it doesn't get assigned `IsUnderCover` in `SubFloorHideComponent` because the carpets aren't flagged as floor tiles somehow. self-assigning this to hopefully finish on flight tmrw

**Comment by IProduceWidgets** [comment]
I always assumed this was intentional because its funny.

**Comment by graevy** [comment]
this is because the carpets are very different from the tiles internally, because there's no tile smoothing. afaict this will be automatically fixed when the tiles are smoothed and the carpets are internally represented as tiles, so the best thing to do is implement tile smoothing

**Comment by metalgearsloth** [comment]
Carpets are entities, you just need to change the drawdepth of t-rayed entities.
