### ISSUE TITLE
Console Commands Like StartRoundNow are not done instantly

### ISSUE THREAD

**Issue by Geekyhobo** [space-wizards/space-station-14#22973]
## Description

SSL, it seems like console commands are a bit delayed in doing their intended actions

**Additional context**

Done on my local server, can someone either confirm that it also takes a bit or is it just my computer being slow

**Comment by ElectroJr** [comment]
It should be basically instant, did you check if the "delay" is just be the server loading the map/entities?

**Comment by VasilisThePikachu** [comment]
Are you certain its not your game still loading? If after you run the command the console start printing round start stuff then its working as intended

**Comment by Geekyhobo** [comment]
closing this cuase i think it was just a me issue

**Comment by Geekyhobo** [comment]
closed
