### ISSUE TITLE
Thieves are combining with other antags

### ISSUE THREAD

**Issue by KaiShibaa** [space-wizards/space-station-14#22984]
I'm not sure if this is intended but apparently thieves can become syndie thieves and have a lot more equipment to start with PLUS 20TC. 

Headrev with thief was also reported.

**Comment by Rainbeon** [comment]
Antag-combining also occurs with rolling several nukie roles (which also tends to break the gamemode too, as this spawns a catatonic Operative/Agent)

**Comment by Dutch-VanDerLinde** [comment]
Syndie thief can also get 30 total TC By getting the Syndie thief bundle, you shouldn't be able to double antag

**Comment by VasilisThePikachu** [comment]
This is intended, and they are now pacific so they get a disadvantag. I will assume it's safe to close now

Please message me if you think so otherwise
