### ISSUE TITLE
Everyone on a salvage debris perma dies as soon as the debris vanishes

### ISSUE THREAD

**Issue by Boaz1111** [space-wizards/space-station-14#23008]
## Description

People on a salvage debris pulled in by the magnets vanish in the same way as if it were an exped, whereas before they just stayed in space.
**Reproduction**

Spawn/get on salvage debris.
Wait for the debris to vanish.
Everyone gone, no matter their health
**Screenshots**

**Additional context**

**Comment by nikthechampiongr** [comment]
I think that might be intentional although iirc in the past only crit/dead people disappeared.

**Comment by Boaz1111** [comment]
Yeah, and now it's everyone

**Comment by LordEclipse** [comment]
> I think that might be intentional although iirc in the past only crit/dead people disappeared.

Dead/crit people Disappearing is intentional, Alive people is not.
