### ISSUE TITLE
Crit white screen is affected by lights and shadows

### ISSUE THREAD

**Issue by Aranclanos** [space-wizards/space-station-14#2300]
makes it look rather strange

examples:
![image](https://user-images.githubusercontent.com/701959/96585646-41aaea00-12b6-11eb-96eb-ed29f4b170cc.png)
![image](https://user-images.githubusercontent.com/701959/96586056-cb5ab780-12b6-11eb-99a2-2dea92ddf9fb.png)

**Comment by Zumorica** [comment]
Fixed a while ago.
