### ISSUE TITLE
Debug health analyser in Bagel Medical Storage

### ISSUE THREAD

**Issue by Gotimanga** [space-wizards/space-station-14#23019]
## Description
There is a medical scanner mapped into the bagel storage room that does not require a battery and thus charge.
![image](https://github.com/space-wizards/space-station-14/assets/127038462/c84db8bc-893c-45d5-884b-904acd224a8a)

**Reproduction**
- Set map to bagel and spawn in as a medic
- Grab the health analyser on the table nearby

**Additional context**
The map architect probably just chose the wrong health analyser, and this isn't too big of an issue, but still worth reporting. This was found by the player "Gluttonous" and then investigated by myself. (I think that's their name, they weren't too sure)

**Comment by Emisse** [comment]
thanks lol
