### ISSUE TITLE
Can interact with the same APC from both sides of a wall

### ISSUE THREAD

**Issue by Aranclanos** [space-wizards/space-station-14#2301]
![image](https://user-images.githubusercontent.com/701959/96587046-32c53700-12b8-11eb-8ca3-c3ec0976bd3e.png)
this is in chem, I was able to see and interact with the same APC in both the hallway and inside the room

**Comment by PJB3005** [comment]
Yeah we really need a proper wallmount system.

**Comment by Peptide90** [comment]
Could close this in favour of #1238 as it's related.

**Comment by SweptWasTaken** [comment]
Closing in favor of #1238.
