### ISSUE TITLE
Shift click on screen causes examine of entity below it

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#23017]
![image](https://github.com/space-wizards/space-station-14/assets/124214523/629d0769-946c-4125-8296-e2b876882104)

**Comment by Geekyhobo** [comment]
Intended, this is not an issue, you can just inspect by shift clicking

**Comment by EmoGarbage404** [comment]
they're referring specifically to that screen entity, not the game screen as a whole.

**Comment by Geekyhobo** [comment]
My bad, that makes more sense now lol
