### ISSUE TITLE
Bold text formatting doesnt work in whisper

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#23018]
![image](https://github.com/space-wizards/space-station-14/assets/124214523/4dd15b5a-46f7-4101-a008-fc9d0acee544)

**Comment by FairlySadPanda** [comment]
Took this on as a good first issue (hah!), have replicated and whittled down the defect.

## Description
Intercoms speaking out the Science channel will spew out the `[bold]` tag when echoing the R&D computer's message when a tech is unlocked.

**Reproduction**
1. Spawn on Dev, wander over to the science room.
2. Insert le disk into le server
3. Use the sandbox spawn menu to spawn an Intercom (Science) somewhere nearby.
4. Open the intercom's menu and set the channel to "Science" and toggle speak on (green).
5. Open the research computer and unlock a tech.

**Expected outcome**
Unclear. This should either replicate the bold text in the radio broadcast, not be echoed on the intercom at all or not have any bold text or [bold] tags.

**Actual outcome**
The statement made by the research computer is replicated with the [bold] tags it uses to its nice formatting exposed.

**Screenshots**
See above.

**Comment by FairlySadPanda** [comment]
So as for why:

The research computer uses its RadioSystem dependency to message out about unlocks. There's specific handling in RadioSystem::SendRadioMessage to handle rich text messages where you want to bold things. This does not exist when intercoms _receive_ these radio messages in RadioDeviceSystem::OnReceiveRadio - ChatSystem::TrySendInGameICMessage is instead fired, which takes the `[bold]` tags existant in the original message and spits them out in plaintext for users to see.

From reading `ChatSystem` and `ChatManager` I agree with the comments that swear at them, but without knowing specifically what's correct here I can't fix this. Opinions wanted :)

**Comment by lzk228** [comment]
![Screenshot_20240203_235221](https://github.com/space-wizards/space-station-14/assets/124214523/4a80b202-9f76-49ee-9cfa-1671dbbca15c)
fixed
