### ISSUE TITLE
thieves can get steal ian objective?

### ISSUE THREAD

**Issue by Dutch-VanDerLinde** [space-wizards/space-station-14#23022]
## Description
in the thief design doc, it says that it can be any animal with a name except ian can be a steal objective
but you can get ian as a steal objective, unintended?

**Reproduction**
-become thief
-get ian steal objective

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/45323883/c9718e6b-2a33-48c5-ba08-dbfbdbae9cd4)

**Comment by lzk228** [comment]
intended
