### ISSUE TITLE
Mimes writing on paper should break their vow

### ISSUE THREAD

**Issue by GoodWheatley** [space-wizards/space-station-14#23025]
Tired of seeing low effort mimes just writing out everything they want on paper instead of trying to communicate through emotes. At least this way they're punished for doing that repeatedly by losing the invisible wall power.

**Comment by Moomoobeef** [comment]
LRP mimes will hate this so much lmao.
But I agree, it's super lame that they can do this and I see many mimes just do it constantly and not even bother with emoting, even sometimes on MRP.

**Comment by Emisse** [comment]
mimes shouldnt be able to write

**Comment by CMDR-Piboy314** [comment]
crayon meta

**Comment by Hmeister-fake** [comment]
> crayon meta

Cargo will cry

20,000 spessos per shift on crayons for the mime per shift lmao

**Comment by EmoGarbage404** [comment]
No lol

**Comment by Hmeister-fake** [comment]
> No lol

Not even gonna give it a chance? it makes sense, it forces mimes to actually do mime things and be creative instead of, pretty much talking but you just need to hold a pen and paper and then you get magical invincible barriers.

**Comment by CrigCrag** [comment]
then they just @motions that john syndie killed the captain with a fire axe and is exactly 30 tiles north by northeast of this location

**Comment by deltanedas** [comment]
then roleban for hrp mime

**Comment by deepdarkdepths** [comment]
I dont see this happen on MRP, the mimes I see actually try to communicate through actions before resorting to paper if what they're trying to say is impossible to act out. Mimes are already ignored enough when they try to properly RP, and people only pay attention if they feel like RPing with you.
