### ISSUE TITLE
Climbing a table can fail to move the character

### ISSUE THREAD

**Issue by Aranclanos** [space-wizards/space-station-14#2302]
![GIF 20-Oct-20 9-41-55 AM](https://user-images.githubusercontent.com/701959/96587298-8b94cf80-12b8-11eb-8df0-a8a319bf09c0.gif)

if your character sprite bumps a wall or window while trying to climb a table, it fails to move it and you still enter in a "tableclimbing" mode, being able to walk over them and unable to climb again

at the end of the gif I manually walked on the table

**Comment by metalgearsloth** [comment]
This is probably better by design IMO because if a physics object is blocking you you shouldn't necessarily move through it to get on the table.

**Comment by ShadowCommander** [comment]
Fix is to check if the player is on the table after the timer is done. We might be able to do something about moving onto the table once the player collider is not square.

**Comment by SweptWasTaken** [comment]
I couldn't replicate this, and as mgs said it's better by design for pixel-movement. Maybe new physics will make it better.
