### ISSUE TITLE
Borg ion laws mess up in chat

### ISSUE THREAD

**Issue by Pangogie** [space-wizards/space-station-14#23046]
## Description
When a borg states an ion law it will spew out the metadata with it.

**Reproduction**
Be borg.
Ion storm.
State ion storm law.

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/7548248/61623355-7a71-4ab5-8849-715f8156c70b)

**Comment by GoodWheatley** [comment]
@EmoGarbage404

**Comment by Pangogie** [comment]
This was fixed.
