### ISSUE TITLE
Clicking on different directions affects your sprite layer standing on top of a firelock

### ISSUE THREAD

**Issue by Aranclanos** [space-wizards/space-station-14#2305]
![GIF 20-Oct-20 9-49-42 AM](https://user-images.githubusercontent.com/701959/96588155-aa479600-12b9-11eb-9202-0ef8b25e1177.gif)

I dont know if this happens with other objects than the firelock, in the gif im clicking on the tiles around my character

**Comment by SweptWasTaken** [comment]
Bad y-sorting...
