### ISSUE TITLE
Feature Request: buff emergency toolbox contents 

### ISSUE THREAD

**Issue by Kadeo64** [space-wizards/space-station-14#23059]
## Description
Emergency toolboxes contain a crowbar, two flashlights (sometimes one), two breath masks, and two chocolate. With the addition of water bottles to survival boxes and emergency nitrogen tanks, I think emergency toolboxes should be updated to include said water bottles and emergency tanks. Would make these just a little bit more useful. It feels weird they don't have oxygen tanks when they have two breath masks, and since water bottles are now commonplace it would be a good idea to put them in a place where emergency food is stored as well.

**Comment by Tayrtahn** [comment]
While we're at it, maybe one of the chocolate bars could be replaced with something the reptilians crew members can eat?

**Comment by Partmedia** [comment]
Or groups are documented in [EntitySpawnEntry.cs]. Snippet:
```
    ///     orGroup signifies to pick between entities designated with an ID.
    ///     <example>
    ///         <para>
    ///             To define an orGroup in a StorageFill component you
    ///             need to add it to the entities you want to choose between and
    ///             add a prob field. In this example there is a 50% chance the storage
    ///             spawns with Y or Z.
    ///         </para>
    ///         <code>
    /// - type: StorageFill
    ///   contents:
    ///     - name: X
    ///     - name: Y
    ///       prob: 0.50
    ///       orGroup: YOrZ
    ///     - name: Z
    ///       orGroup: YOrZ
```
