### ISSUE TITLE
Pulling objects diagonally can damage you

### ISSUE THREAD

**Issue by Aranclanos** [space-wizards/space-station-14#2306]
![GIF 20-Oct-20 9-53-03 AM](https://user-images.githubusercontent.com/701959/96588501-1aeeb280-12ba-11eb-9565-b349612ae1c5.gif)

The dmg done isnt instant crit I just recorded it with low hp for comedic effect. It also seems to stun you a bit

**Comment by SweptWasTaken** [comment]
Closing this to concatenate into #2387
