### ISSUE TITLE
Shuttles are... not okay

### ISSUE THREAD

**Issue by AjexRose** [space-wizards/space-station-14#23073]
## Description

In the good words of a member of crew
"What moth cursed the shuttle?!"

Shuttles currently seem to be entirely invisible, with the exception of the floor tiles, and seem to strip players of all clothing and items when entering them.
**Reproduction**

1. Late Join
2. Wait for Shuttle
3. Bugged shuttle arrives
or
1. Be cargo
2. Pilot in shuttle for cargo reasons
3. witness the bugged cargo shuttle
**Screenshots**

![bugged shuttles](https://github.com/space-wizards/space-station-14/assets/112997230/dcccc777-0ed4-48eb-8118-f7b6021cf794)

**Additional context**

Started occurring after the most recent update on the Salamander server.

**Comment by Emisse** [comment]
appears to be happening with anything loaded as a grid in game
