### ISSUE TITLE
bad smes examine

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#23083]
## Description
it has powercell and light examine when it shouldnt

![02:05:22](https://github.com/space-wizards/space-station-14/assets/39013340/c5696700-2813-4a78-bfc2-ff3abcfd93fe)

**Comment by deltanedas** [comment]
happens to apc too same things

**Comment by osjarw** [comment]
This doesn't seem to be happening anymore, so this issue can be closed. 

![20240402_09h07m41s_grim](https://github.com/space-wizards/space-station-14/assets/62134478/7fb0174f-db67-4d8c-8ab5-e5d68771fcc1)
