### ISSUE TITLE
Human sprites layer on top of walls

### ISSUE THREAD

**Issue by Aranclanos** [space-wizards/space-station-14#2309]
![image](https://user-images.githubusercontent.com/701959/96589632-6d7c9e80-12bb-11eb-920f-b0dc8fa8e529.png)
the lower leg and shoes of my character show up above the windows and walls that are one tile below 

![image](https://user-images.githubusercontent.com/701959/96589658-740b1600-12bb-11eb-9196-19d882c99e41.png)
doesn't happen with doors

edit: doors happens sometimes, depending on your direction and maybe something else. See: https://github.com/space-wizards/space-station-14/issues/2305

**Comment by SweptWasTaken** [comment]
This is an issue with bounding boxes and was fixed by me, unfortunately PJB didn't like it so I guess this is how it'll be for now.
