### ISSUE TITLE
If combat mode is on, your pick up range is determined on the distance from your character to your cursor

### ISSUE THREAD

**Issue by Aranclanos** [space-wizards/space-station-14#2310]
![GIF 20-Oct-20 10-23-53 AM](https://user-images.githubusercontent.com/701959/96592065-5db28980-12be-11eb-9427-a9bd6e4faaaf.gif)
combat mode on, I cant pick up the belt unless I click the parts of the sprite closer to my character

![GIF 20-Oct-20 10-23-32 AM](https://user-images.githubusercontent.com/701959/96592082-61461080-12be-11eb-83b6-e4e3e0ef98b5.gif)
combat mode off, picking up objects works fine

**Comment by Visne** [comment]
This is still an issue, however it's not related to combat mode anymore. I think it's best to create a new issue.

**Comment by Visne** [comment]
New issue: #4303
