### ISSUE TITLE
sounds for SpawnItemOnUse are broken

### ISSUE THREAD

**Issue by EmoGarbage404** [space-wizards/space-station-14#23126]
## Description

the sound is spawned for the entity, which then immediately gets deleted, preventing the sound from being heard.
Also applies to AME parts and construction.

In the past, the sound would still play even if the entity was deleted. Now that this isn't true, these need to be changed.

**Comment by deltanedas** [comment]
soundsystem should have a thing for parenting to the grid not the entity since this seems like it would be used a lot (grenades too)

**Comment by slarticodefast** [comment]
Fixed by #27621
