### ISSUE TITLE
The bar doesn't have drinking glasses

### ISSUE THREAD

**Issue by Aranclanos** [space-wizards/space-station-14#2313]
![image](https://user-images.githubusercontent.com/701959/96594316-dca8c180-12c0-11eb-9f05-a9ea261f4cfe.png)

technically not a bug but having the booze dispensers make it feel more important missing feature

**Comment by SweptWasTaken** [comment]
Drinks need a major overhaul in quality-control which i'm ~~working~~ shirking on so it's not really worth doing anything with them currently, i'll fix all drink related issues when I push the pr.

**Comment by cyclowns** [comment]
this is fixed now 
![image](https://user-images.githubusercontent.com/19853115/103740977-7a08bd00-4fb5-11eb-823b-3cc677106385.png)
