### ISSUE TITLE
Nukeops Medic starts mindless

### ISSUE THREAD

**Issue by LordEclipse** [space-wizards/space-station-14#23135]
## Description
Pretty sure this was fixed before, but I'm assuming the game attempts to select the same player twice for nukie agent and operative, so the agent ends up mindless. I only came to this conclusion because the game will have the same player character for the medic/agent and an operative.

**Comment by deltanedas** [comment]
funnily enough on deltav ive never seen a nukie that doesnt have a player, though sometimes its a team of 4 not 5

**Comment by dolgovmi** [comment]
Is it possible in the agent pick, when there is someone in the agent list and it picks them, it forgets to remove said person from the normal operatives list and then it gets double picked later like that?

**Comment by Emisse** [comment]
yea the nukie code is awful

**Comment by lzk228** [comment]
i shitcoded :trollface:
