### ISSUE TITLE
Prevent ghost metagaming mechanically

### ISSUE THREAD

**Issue by Flareguy** [space-wizards/space-station-14#23138]
## Description
After dying, ghosts should be tethered to their body with a certain range they can move out a little in, and unable to hear deadchat or otherwise do any ghost interactions (ie. ghost roles, orbiting, toggling lighting, hearing all radio channels, etc.) Once the rot timer expires, that's it - you're dead dead.

In theory, this solves ghost "metagaming," which is basically unenforcable. Some tidbits of information *will* force a change in your playstyle unless you try to play like a complete idiot and ignore obvious signs of antagonism.
This would also probably let us give more dangerous information out to ghosts, like an antagonist HUD, which would probably improve the observer experience by a fair bit.

We're in a pretty good position to do this right now considering med already kinda works like this thanks to the rot timer. The only difference is that you can't ghost out across the entire station within the first 10 or 15 minutes to see what's going on, which should be perfectly manegable.

**Comment by GoodWheatley** [comment]
There should be a button to designate yourself DNR and become a full ghost

**Comment by deltanedas** [comment]
there already is, its called take mouse ghost role and /ghost immediately

**Comment by Tayrtahn** [comment]
A more intuitive way would probably be good too. Also displaying a warning when choosing a ghost role that taking the role will make the player unrevivable.

**Comment by deltanedas** [comment]
also opening the ghost roles menu might lead to metagaming, so a DNR button to open it at all solves multiple issues

**Comment by Kadeo64** [comment]
Another thing i'd like is, if you're in ghost but you haven't set DNR or you haven't taken a ghost role it should not show the yellow "soul is gone" text, because newbie medical doctors will sometimes ignore you because of this (resulting in very infuriating situations where med doesn't revive you because the one time they bothered to shift click you were out of your body)

**Comment by deltanedas** [comment]
it shows red text in that case not yellow
if you take a ghost role it becomes purple

**Comment by Flareguy** [comment]
> also opening the ghost roles menu might lead to metagaming, so a DNR button to open it at all solves multiple issues

I was trying to imply this with "you can't hear deadchat." The main crux of the idea is that you can spectate around your body in a certain radius, but not do anything else.

**Comment by Flareguy** [comment]
I had a discussion shortly after making this issue internally and the consensus was that the game probably didn't need it right now, so I'll close this for now.
