### ISSUE TITLE
UI in-hand description text oversteps on ID slot sprite

### ISSUE THREAD

**Issue by Aranclanos** [space-wizards/space-station-14#2314]
![image](https://user-images.githubusercontent.com/701959/96594689-45903980-12c1-11eb-9765-b883856a782b.png)

it happens more with stackeables and it doesnt block clicking on the ID

**Comment by metalgearsloth** [comment]
Doesn't this only happen if your UI is really small?

**Comment by SweptWasTaken** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/701959/96594689-45903980-12c1-11eb-9765-b883856a782b.png)
> 
> it happens more with stackeables and it doesnt block clicking on the ID

Not an issue anymore with new hud.
