### ISSUE TITLE
Failing crafting drops stacks of resources on the floor

### ISSUE THREAD

**Issue by Aranclanos** [space-wizards/space-station-14#2315]
![GIF 20-Oct-20 10-49-26 AM](https://user-images.githubusercontent.com/701959/96595338-eed72f80-12c1-11eb-88e5-a331d281fd56.gif)
I don't have glass so I can't craft a spear, but I drop 2 stacks of metal on the floor after each try

**Comment by Zumorica** [comment]
feature

**Comment by PaulRitter** [comment]
should this be a feature? i don't get why this should the this way

**Comment by SweptWasTaken** [comment]
Thy has been named "feature" by the grand creator.

**Comment by Zumorica** [comment]
Maybe the "not having glass" part, not. But that would mean checking all possible candidates at least twice 😰
I'll see if it can be improved, sonetime

**Comment by SweptWasTaken** [comment]
If crafting had a do_after this would be funny if you were shoved or slipped the stuff just falls outta your hands.

**Comment by Zumorica** [comment]
Crafting does have a do after tho, and that's pretty much what happens

**Comment by SweptWasTaken** [comment]
Blessed, now go to sleep. 💋
