### ISSUE TITLE
Clicking open lockers with objects wrong placement

### ISSUE THREAD

**Issue by Aranclanos** [space-wizards/space-station-14#2316]
![GIF 20-Oct-20 10-58-53 AM](https://user-images.githubusercontent.com/701959/96596775-76716e00-12c3-11eb-8001-b318632f36f6.gif)

seems like the locker becomes clickeable outside of the borders where it takes objects inside when closing, it also ignores objects placed on the open door sprite part

**Comment by PaulRitter** [comment]
this is due to a combination of #1341 and the locker collisionbox not changing when its opened

**Comment by SweptWasTaken** [comment]
Fixed by #2771.
