### ISSUE TITLE
The tesla is thrown by its own explosions

### ISSUE THREAD

**Issue by Veritius** [space-wizards/space-station-14#23164]
This means the tesla can cross the ENTIRE STATION in less than a second.
It's fucking terrifying. See round 42364 on Salamander.

**Comment by notquitehadouken** [comment]
feature

**Comment by retequizzle** [comment]
skill issue tbh

**Comment by Veritius** [comment]
this is a feature? oh god

**Comment by TheShuEd** [comment]
this is not a feature lol

**Comment by EmoGarbage404** [comment]
it got fixed anyways

**Comment by Veritius** [comment]
real
