### ISSUE TITLE
Artifact fragment bounties break on stack

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#23167]
## Description
When doing the artifact fragment bounty if they are stacked it doesn't count them properly and does not give the reward.

**Reproduction**
- Get arti fragment bounty
- Stack required fragments
- Send stack on cargo shuttle
- Get ripped off.

**Screenshots**
N/A

**Additional context**
@TheShuEd Just going to ping you in here if you might want to fix it 😅

**Comment by TheShuEd** [comment]
stupid stackable items. I'll fix that and add the ability for thieves to steal staked items.

**Comment by TheShuEd** [comment]
wha? I never fixed it. Somebody did?

**Comment by lzk228** [comment]
as i remember items works in stacks for bounties
