### ISSUE TITLE
Opening doors when walking on hallways

### ISSUE THREAD

**Issue by Aranclanos** [space-wizards/space-station-14#2317]
![GIF 20-Oct-20 11-13-41 AM](https://user-images.githubusercontent.com/701959/96598526-55aa1800-12c5-11eb-9f1c-14f99416f0d5.gif)

Didn't bump them yet they opened when I walked too close

**Comment by Zumorica** [comment]
Same as #1024

**Comment by metalgearsloth** [comment]
Fixed in an old PR that I forget as collisions weren't using exact BBs (in old physics).
