### ISSUE TITLE
Tesla coils and power monitoring

### ISSUE THREAD

**Issue by chromiumboy** [space-wizards/space-station-14#23172]
## Description

Tesla coils are missing a PowerMonitoringDeviceComponent, so they will not show up on the power monitoring console

**Reproduction**

N/A

**Screenshots**

N/A

**Additional context**

N/A

**Comment by deltanedas** [comment]
they only generate power for like half a second after being struck so its not useful to see it

**Comment by Errant-4** [comment]
It's useful to see that there are indeed tesla coils connected to your powernet
