### ISSUE TITLE
Ejecting materials needs to be generic and removed from lathes

### ISSUE THREAD

**Issue by EmoGarbage404** [space-wizards/space-station-14#23184]
## Description

It should just be a material storage thing. Make an event that checks whether or not ejection can occur (for things like ore smelter).

**Comment by FairlySadPanda** [comment]
Taking a look. Note: 
![image](https://github.com/space-wizards/space-station-14/assets/732532/6152218c-8e3c-405e-a943-3cc9e51622df)

**Comment by EmoGarbage404** [comment]
Also going to note that it would be good if updating the materials on an entity would automatically update the UI control but that isn't a requirement.

(Also im pretty sure the material ejection thing is its own control but if it isnt it really should be)
