### ISSUE TITLE
Cancelling the file picker crashes the game

### ISSUE THREAD

**Issue by SGSoraka** [space-wizards/space-station-14#23192]
## Description
I've found a small bug concerning the file picker on the default menu screen.
Also, i've looked and it seems that this hasn't been reported before.

Expected Behaviour:
- Graceful handling of no file being returned by the file picker.

Observed Behaviour:
- Game crashes

**Reproduction**
1. Open the game.
2. Click on "Run content bundle/replay".
3. Close the file picker by clicking "cancel", or any other action that results in no file being returned.
4. Observe the game crash.

**Screenshots**
N/A

**Additional context**
OS Version: Windows 10; 21H2; Build `19044.3208`
Game Version: **Steam Playtest**; Build-ID `5864008`
SS14.Launcher `System.Software.ProductVersion`: `0.25.0+97f0aa5b6b0a94dbf5cc153e35ab5c54be1d0d4c`

**Comment by deathride58** [comment]
This is a launcher bug and should be reported within [space-wizards/SS14.Launcher](https://github.com/space-wizards/SS14.Launcher)

**Comment by DebugOk** [comment]
> This is a launcher bug and should be reported within [space-wizards/SS14.Launcher](https://github.com/space-wizards/SS14.Launcher)

This was also fixed already https://github.com/space-wizards/SS14.Launcher/pull/123
Its just not in the latest version yet it seems

**Comment by ike709** [comment]
The fix for this is included in the latest version now. This issue can be closed.

**Comment by VasilisThePikachu** [comment]
Fixed by https://github.com/space-wizards/SS14.Launcher/pull/123
