### ISSUE TITLE
Bullets hit mobs who are lying down in crit and ignore them if they're dead

### ISSUE THREAD

**Issue by Aranclanos** [space-wizards/space-station-14#2319]
![GIF 20-Oct-20 11-34-51 AM](https://user-images.githubusercontent.com/701959/96603674-9e180480-12ca-11eb-9999-99d6a3b48039.gif)
bullets hit the mob as long as they're alive

 this report is kinda the opposite of https://github.com/space-wizards/space-station-14/issues/695

**Comment by metalgearsloth** [comment]
Intended
