### ISSUE TITLE
Initiator of communications console messages does not get feedback.

### ISSUE THREAD

**Issue by Admiral-Obvious-001** [space-wizards/space-station-14#23205]
## Description

The user of a communications console doesn't seem to be able to tell wether or not the alert level changed nor wether or not their messages send. Everyone else on the station is aware of said alerts however. 

**Reproduction**

Unknown but this happened to all command crew on Mander shift 42474.

**Comment by IProduceWidgets** [comment]
Hmmmmm. I wonder if it could be a radio jammer. Haven't tested it.

**Comment by deltanedas** [comment]
announcements dont use comms
