### ISSUE TITLE
Doors closing on top of mobs

### ISSUE THREAD

**Issue by Aranclanos** [space-wizards/space-station-14#2321]
![GIF 20-Oct-20 11-59-05 AM](https://user-images.githubusercontent.com/701959/96605274-614d0d00-12cc-11eb-8f94-f7e7d5335a26.gif)
some doors are closing and opening instantly, causing a jittery on the mob

![GIF 20-Oct-20 12-05-11 PM](https://user-images.githubusercontent.com/701959/96605377-85105300-12cc-11eb-9f80-bc3636e43a4f.gif)
some other doors close and do not re-open, causing the mob to suffocate
if they're opened, the mob gets pushed away

**Comment by metalgearsloth** [comment]
Fixed by https://github.com/space-wizards/space-station-14/pull/2348
