### ISSUE TITLE
Welders and cauterys should be able to cauterize bleeding

### ISSUE THREAD

**Issue by Hmeister-fake** [space-wizards/space-station-14#23234]
## Description
Using a welder on yourself when you are bleeding should make you scream, and begin a short/medium length do-after to stop the bleeding while adding significant burn damage and with a chance to fail, this could be done to others as well (allowing a doctor to stop the bleeding on a fresh corpse or crit person. When specifically using a cautery it should also make you scream, but have no do after and instantly stop the bleeding and do less burn damage. When using a lighter, it should do nothing since they are very common.

**Additional context**
It makes sense, and it would be useful for doctors and could easily accomodate the medical redux when it come out. Also it would make Paramedics have a reason to begin to carry a cauteriser and in turn consider carrying surgical tools when that fabled next week arrives...

**Comment by deltanedas** [comment]
heat damage not cauterizing is a bug

**Comment by Hmeister-fake** [comment]
> heat damage not cauterizing is a bug

I fucking knew it worked at some point, thought I was Mandela effect'ing myself. Il close this then

**Comment by deltanedas** [comment]
(#21491)
