### ISSUE TITLE
Pulling buckled mobs from beds

### ISSUE THREAD

**Issue by Aranclanos** [space-wizards/space-station-14#2323]
![GIF 20-Oct-20 12-12-11 PM](https://user-images.githubusercontent.com/701959/96606603-d705a880-12cd-11eb-9c85-d8d36f7e5188.gif)
after pulling off a mob from a bed, I was unable to make it lay down on it again. It still teleported the mob to the center of the bed and played the sounds

**Comment by Git-Nivrak** [comment]
#2374
