### ISSUE TITLE
Cargo Arbitrage Episode Morbillion - Sec techfab

### ISSUE THREAD

**Issue by nikthechampiongr** [space-wizards/space-station-14#23259]
## Description

The .35 ammo is worth more than the metal it's made with.
**Reproduction**

1. Get the HoS/warden to give you their secfab.
2. Put steel in it
3. Print money

**Comment by Emisse** [comment]
Security is gonna regret doing this when antags are in cargo

**Comment by K-Dynamic** [comment]
Warop nukies when sec moves their fab to cargo, sells ammo, and station is armed with laser raptors and thronglers:

**Comment by Holinka4ever** [comment]
Isnt there like, an ammofab, that salvages can earn in expeditions or smth?

**Comment by deltanedas** [comment]
yes but the issue is the bullet pricing

**Comment by nikthechampiongr** [comment]
Resolved by #23698.
