### ISSUE TITLE
Cartidges easily cause a right click hell

### ISSUE THREAD

**Issue by Aranclanos** [space-wizards/space-station-14#2326]
![image](https://user-images.githubusercontent.com/701959/96610091-a0319180-12d1-11eb-84c5-523bdfc03e0c.png)
I cant seem to be able to scroll through that to find the mob

**Comment by PaulRitter** [comment]
maybe have a component that toggles on an entity being grouped in the rightclick-menu?

**Comment by metalgearsloth** [comment]
Probably better for small items like cartridges to be grouped into a stack on the ground IMO. Ideally this would also let you cut down on entity count and physics objects in play.
