### ISSUE TITLE
When using a spray bottle, the particles attempt to enter disposal bins and miss

### ISSUE THREAD

**Issue by Terraspark4941** [space-wizards/space-station-14#23282]
## Description

Says right on the can. If you aim at a disposal bin and spray using a bottle, this causes the particle to constantly attempt to enter the disposal bin until deletion.

**Reproduction**

1. Take spray
2. Fill spray
3. Spray at disposals
4. ????

**Screenshots**

(will upload later)

**Additional context**

Just experienced this on Wizden's Miros, this is an extremely rushed report

**Comment by UbaserB** [comment]
oh yeah i remember this happening its kind of funny to see

**Comment by UbaserB** [comment]
Did #24175 fix this?

**Comment by Terraspark4941** [comment]
finally got around to checking; the answer seems to be no (in private testing with a large spray bottle)

**Comment by beck-thompson** [comment]
Yes I think my PR does resolve this!

https://github.com/space-wizards/space-station-14/assets/107373427/99556488-0a84-4f70-bb79-85534dab6ca5
