### ISSUE TITLE
Can't open storage inventories that are inside other storage inventories

### ISSUE THREAD

**Issue by Aranclanos** [space-wizards/space-station-14#2329]
![GIF 20-Oct-20 1-22-16 PM](https://user-images.githubusercontent.com/701959/96615196-5d72b800-12d7-11eb-9d19-ab32e1649ca7.gif)
Pressing "Activate item" while mouseovering the box inside my backpack does not open its inventory pop-up window
Clicking with an item on said box also does not store it, but if you have the pop-up window already open, you can store items in the box

**Comment by ElectroJr** [comment]
Fixed by #4525
