### ISSUE TITLE
Tesla Engine's Ball Lightning can be pushed by explosions when loose.

### ISSUE THREAD

**Issue by DrMelon** [space-wizards/space-station-14#23331]
## Description
When the Tesla Engine malfunctions (or is sabotaged) and the ball lightning is let loose, it can be pushed by explosions that it creates, allowing it to travel in erratic directions that are likely unintentional and far more chaotic than otherwise designed for. 

**Reproduction**
Create a Ball Lightning and cause explosions near it. Follow it with ghost, and you can see it gets kicked very far at enormous speeds before its movement code takes control again.

**Screenshots**
None taken.

**Additional context**
It's already an extremely destructive element, but the explosions can cause it to travel from one end of the station to the other in about a second - which is *definitely* worse than the singularity.

**Comment by DrMelon** [comment]
I'll probably try and tackle this tomorrow.

**Comment by Ilya246** [comment]
should be a feature

**Comment by DrMelon** [comment]
Definitely gets screwy when it blows up O2 tanks and things. Watched it clear half of Barratry in under a second and draw a massive line across the whole thing.

**Comment by deltanedas** [comment]
there should be a way to clamp the force from explosions, so the ball can be pushed a little but not flung at mach 8
