### ISSUE TITLE
Traquilizer hitbox is broken

### ISSUE THREAD

**Issue by Anzarot121** [space-wizards/space-station-14#23341]
## Description

For some reason, tranquilizer work within 3 tiles of the bullet's actual projectile.
**Reproduction**

Shoot past the target 2 times, the target will fall asleep.
**Screenshots**

https://github.com/space-wizards/space-station-14/assets/116586144/71148ba8-51e2-49c9-b6f0-702c1e26d50d

**Additional context**

Tested on a build with the latest merges.
Personally, I would like to see this issue given a high priority.

**Comment by mirrorcult** [comment]
this is a result of the collision not checking for the projectile shape rather than the flyby shape

**Comment by AlexandrSTG** [comment]
> this is a result of the collision not checking for the projectile shape rather than the flyby shape

So why do they continue injecting when "OnflyingBy" and still flying and do not "OnCollision"?
