### ISSUE TITLE
Fultons can kill if people + AI are inside the crate

### ISSUE THREAD

**Issue by mr-bo-jangles** [space-wizards/space-station-14#23344]
## Description
When on an expedition, the Human I was a pAI for was thrown into a box with attached fulton recovery device on a salvage mission to an asteroid

**Reproduction**
Have a player inside a fulton transported box when it transports? If that doesn't work, Try giving them a pAI as well. Might be related to that combination?

**Screenshots**
![Screenshot_20240102_005856](https://github.com/space-wizards/space-station-14/assets/291570/625e5828-6b0d-4c6e-bd18-727e9335f343)

**Additional context**

**Comment by Emisse** [comment]
dupe
