### ISSUE TITLE
need station anchors

### ISSUE THREAD

**Issue by Emisse** [space-wizards/space-station-14#23374]
physical machine or structure that when powered/activated makes the grid way more massive and very hard to move
good excuse for big space anchor as well, maybe some sort of animation where it lowers down into space or something whatever
this is needed so shitters in shuttles dont giga move the station around but also can be toggled for sabotage or whatever else
ive been requesting this for years but never amde an issue on it proper

**Comment by Errant-4** [comment]
Could this just be added to the big Gravity Generator?

**Comment by K-Dynamic** [comment]
I agree, station gets annoying to be near as both crew and nukies

Would thematically make sense to tie this to grav gen, but probably better to map multiple subspace anchors for redundancy

**Comment by UbaserB** [comment]
im excited to map these when they exist

**Comment by Peptide90** [comment]
Wonder if this is as simple as adding a structure with an absurdly large mass number...wonder if it passes it through to the grid or if grid weight is purely based on tiles. Not checking but nothing is ever simple :'(

**Comment by Errant-4** [comment]
> Wonder if this is as simple as adding a structure with an absurdly large mass number...wonder if it passes it through to the grid or if grid weight is purely based on tiles. Not checking but nothing is ever simple :'(

Motion damping for has already been added to ShuttleComponent on #18697 so I think this would only need to create a new device that can override that value for a specific grid

**Comment by metalgearsloth** [comment]
Also ideally you'd split out the gravity generator UI as I think that sort of "delayed turn-on / off" functionality is useful for here + IFF.

Will also need for the trade station.

**Comment by UbaserB** [comment]
okay after trade station got merged, we REALLY need this. People are literally driving the outpost to the station and then not even using the cargo shuttle to travel.

**Comment by UbaserB** [comment]
People have already started to dock them to the station permanently by adding a shuttle console the the outpost and extending the cargo dock.. omg.

**Comment by Errant-4** [comment]
Suppose we add an anchor to the trade outpost. Won't the same people just _turn it off_? If this is no longer a convenience feature but a gameplay limitation, it needs to be either added directly to the map prototypes (this can be done right now, I think), be a result of the station grid's "mass",  or there needs to be some compelling downside to turning off the anchors

**Comment by juliangiebel** [comment]
You could set the station anchor on the trade station to require centcomm access 😄

**Comment by Errant-4** [comment]
Make sure that the Station's anchor also requires Captain access so the QM can't turn it off :D

**Comment by Hreno** [comment]
We have anchors now.
