### ISSUE TITLE
Hitting a wall or a wallmount plays a muffled sound

### ISSUE THREAD

**Issue by Aranclanos** [space-wizards/space-station-14#2337]
If you punch or hit with an object a wallmount or wall, the "hit" sound will be muffled, like if it was on the room behind the wall

**Comment by metalgearsloth** [comment]
It'll be the occlusion raycast for audio, maybe it needs offsetting by half a tile if it's past a certain range or something?

**Comment by SweptWasTaken** [comment]
Couldn't replicate, think it's fixed.
