### ISSUE TITLE
Hardsuits slowdown should take only 50% of weared slowdown.

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#23392]
When carrying hardsuits, you really can move like normal, but when you wear it, its hard to move in them

**Comment by K-Dynamic** [comment]
Are you saying you hardsuits don't slow in your hand currently? Or that you want them to only slow 50% in-hand?

**Comment by lzk228** [comment]
> Are you saying you hardsuits don't slow in your hand currently? Or that you want them to only slow 50% in-hand?

the second one
its annoying when harduits slosing you inhand like when you wear them

**Comment by GreyMario** [comment]
ok but think on this for a moment, which is going to be more exhausting for you to do: hold a heavy object in your hands and run around, or wear that same weight across your entire body and run around?

i'd rather see holding the item have the greater slowdown

**Comment by lzk228** [comment]
its hard to move when you wear a really heavy and maybe not very comfortable suit

**Comment by Aisu9** [comment]
holding an hardsuit should use both hands, it's a full body suit(sometime minus the helmet) shit big and heavy

**Comment by lzk228** [comment]
now its "its a game, not a real life"-border

**Comment by keronshb** [comment]
I don't even believe Hardsuits should have slowdown in hand, but it shouldn't be more punishing carrying it around. By carrying it you're already a prime target for being slipped & your losing a hand slot.

**Comment by lzk228** [comment]
hey
