### ISSUE TITLE
Sprites randomly flashing

### ISSUE THREAD

**Issue by Aranclanos** [space-wizards/space-station-14#2339]
![GIF 20-Oct-20 4-20-40 PM](https://user-images.githubusercontent.com/701959/96645000-4d230300-1300-11eb-9109-8d5358521e3d.gif)
I left the run while I was afk in adminghost and after flying a bit I noticed some sprites flashing. I don't know what caused it or how to reproduce but recorded them

**Comment by Zumorica** [comment]
I'm pretty sure this is due to Clyde (our rendering engine) so this should probably go in the engine repo, but I'll leave it open here

**Comment by metalgearsloth** [comment]
I'm 90% sure this is fixed so I'm gonna close until told otherwise.
