### ISSUE TITLE
Round restart votes are being abused

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#23404]
## Description
Every game there are multiple frivolous restart votes, almost always failing and just derails the rounds sometimes.
Votes need to have some form of really long global cooldown or only allowed after or ever X min maybe something like every 30min. Or what ever better idea some genius here has.
The rounds sometimes require admin intervention to tell people to stop spamming it.

**Reproduction**
- Join a round, especially a full server
- observe a bunch of restart votes as soon as someone is round removed and doesn't want to wait out the rest of the round.

**Screenshots**
Not a issue directly but a feed back vote on a round about the constant restarts. it only a single data point so take with grain of salt but majority of people don't want constant restart votes.
![image](https://github.com/space-wizards/space-station-14/assets/47093363/bcbfd954-e13a-4ca0-9648-0dea01eec028)

**Additional context**
Have become more visible now that it runs when admins are on vs previous functionality but it used to be a minor issue too.

**Comment by EmoGarbage404** [comment]
is there not a global cooldown for restart votes or smth? I thought it was like once every five minutes.

**Comment by LankLTE** [comment]
There is an individual cooldown of 5 minutes, and a global cooldown of 4 minutes. The global cooldown timer uses the same cvar for all votes, which could probably be changed, and the individual cooldown could absolutely be upped to 30+ minutes.

**Comment by EmoGarbage404** [comment]
individual cooldown should 100% be longer. I'm not sure if global cooldown is super needed but yeah.

**Comment by GreyMario** [comment]
The problem is genuinely that people are literally instantly calling a restart vote the second they get round removed. It's particularly obnoxious during zombies rounds and people will even ragecall it _while evac is docked._

Restart vote calls need to be logged (and blocked while evac is en-route); I've been told that they're not.

**Comment by LankLTE** [comment]
> Restart vote calls need to be logged (and blocked while evac is en-route); I've been told that they're not.

They are logged.

**Comment by PJB3005** [comment]
The restart votes were absolutely made 3 years ago for the purpose of "allowing somebody to restart an empty server" or similar situations. Quite frankly there should probably be more requirements like "no restart votes if >20 people on the round and >75% of people alive".

**Comment by deltanedas** [comment]
i died pls restart

**Comment by IProduceWidgets** [comment]
Depending on how that PR goes, an alternative could be a "hidden counter" where 5 people to need to try to start a restart vote before one actually starts.

**Comment by Titian3** [comment]
fixed on 23453
