### ISSUE TITLE
Bolt lights show when door is open.

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#23413]
## Description
The bolt lights remain on even when the door is in an open state. does not seem to do the same with emergency lights.

**Reproduction**
Partial reproduction
- open door
- bolt the door with remote

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/47093363/4f8380bd-12eb-417d-89a0-7dfa50256ff0)

**Additional context**
In the reproduction it seems like the door makes a sound to auto close after the bolt and it removes the lights which also seems like a minor issue. Which removes the lights.

**Comment by Kadeo64** [comment]
welded airlock bug 2 electric boogaloo

**Comment by Titian3** [comment]
> welded airlock bug 2 electric boogaloo

What does this mean?
