### ISSUE TITLE
Incendiary grenades are too overpowered.

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#23421]
## Description
The fire that catches on people cant be put out by any obvious means and keep burning to round removal levels, fire extinguishers don't work. There is not fire suffocating mechanic apart from the drop, roll one. The fire burns for ages and essentially round removes anyone that this hits. 
2000-4500 Damage that cant be stopped, pretty brutal.

**Reproduction**
Put some people next to to an incendiary grenade and try and prevent them from burning up.

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/47093363/9818adf0-55bf-4390-ad8f-0bf7cd15fcec)

**Additional context**
The stop drop may reduce it a bit but it was too quick putting the mob in crit to attempt it.

**Comment by deltanedas** [comment]
shitty 1u water in a cup vs round removal who would win

**Comment by K-Dynamic** [comment]
> shitty 1u water in a cup vs round removal who would win

Yes, it's the person on fire who's at fault and should be effectively smited, very good mechanic

**Comment by deltanedas** [comment]
:trollface:

**Comment by GreyMario** [comment]
i can actually corroborate that fire extinguishers weren't working to extinguish fires on people when sprayed, at least once
