### ISSUE TITLE
Throwing is broken again.

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#2342]
![2020-10-20_16-36-52](https://user-images.githubusercontent.com/49448379/96655486-262ef600-132d-11eb-9483-8cdfda2c70e1.gif)

- Thrown items are extremely fast.
- They go through windows.

**Comment by PaulRitter** [comment]
duplicate (kinda) of #2332

**Comment by metalgearsloth** [comment]
1. I think WakeBody() needs to be spammed on the controller itself now.

2. My physics update made the speed go turbo (because mass is back in) which needs nerfing.

Would also be a good time to implement the speed limit on linear velocity.
