### ISSUE TITLE
Radiator isnt reacting with hot environment

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#23439]
Put radiator in hot place
Still 20C in pipes

https://github.com/space-wizards/space-station-14/assets/124214523/52f5c979-640a-4dd1-b768-74e40c8bbef3

**Comment by deltanedas** [comment]
radiator is flow based it does nothing on its own

**Comment by lzk228** [comment]
ok ill test

**Comment by Ilya246** [comment]
gas needs to flow through it for it to work yes

**Comment by lzk228** [comment]
ok then it should work like heater&freezer or something
