### ISSUE TITLE
Soapy water needs removing

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#23431]
It should just be space cleaner and soap should handle decals.

**Comment by IProduceWidgets** [comment]
I like the concept of soapy water, but I agree it needs to somehow be different from space cleaner to justify their simultaneous existence. Also because bleach and ammonia are also already a thing that also does what they do ( or should, bleach was broken and I haven't checked if it works :godo: )

**Comment by IamVelcroboy** [comment]
Soapy water seems more attuned to cleaning your body. Like, if you have blood on your hands, or, maybe in the future, diseases/contamination/etc.
