### ISSUE TITLE
Some maps have vendors named "vendorname"

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#23461]
Like hot drinks machine, named Hot Drinks Machine and it looks awful on downstreams with other language
![image](https://github.com/space-wizards/space-station-14/assets/124214523/e5bb3eb5-5c7d-4efa-ae25-5a3af16318c9)
Its mostly donuts, coffee and cigarettes

**Comment by EmoGarbage404** [comment]
Whichever map did this should be put to death ngl

**Comment by deltanedas** [comment]
i had to remove these when doing saltern and atlas i think its a meme from old maps

**Comment by Emisse** [comment]
artifact from old maps just replace if you see
