### ISSUE TITLE
microwaves can hold tons of stuff

### ISSUE THREAD

**Issue by themias** [space-wizards/space-station-14#23462]
## Description

You can put an insane amount of stuff into a microwave. Needs an item size/quantity check or something. 
You should definitely be able to hide non-food stuff inside there, but a reasonable amount/size.

**Reproduction**

1. casually approach microwave
2. insert three hardsuits, twelve lecters, six dufflebags and thirty oxygen tanks
3. marvel at NanoTrasen technology

**Comment by MACMAN2003** [comment]
the tardim (time and relative dimensions in microwave)

**Comment by Kadeo64** [comment]
while we're at it, please disable pet carriers being put into microwaves, doesn't make sense and also it instantly gibs whatever's inside it if they escape because of how microwaves function

**Comment by SpeltIncorrectyl** [comment]
How much space should they have?
I think a good size is twice the largest recipe.
