### ISSUE TITLE
syndi status icon should be at right

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#23478]
![image](https://github.com/space-wizards/space-station-14/assets/124214523/bc0b36ca-64a7-45ae-9b15-76540aa0103a)
hard to see typing indicator

**Comment by Rainbeon** [comment]
That'd make the right side fairly cluttered since it can see everything the SecHUD can see, both of which are on the right (Role Icons, Mindshields)

**Comment by Emisse** [comment]
typing indicator just needs to appear over any icons
