### ISSUE TITLE
Any animal with cognizine should be able to be converted to revolution

### ISSUE THREAD

**Issue by Stealthbomber16** [space-wizards/space-station-14#23470]
If it can have a brain, it should be brainwashable.

**Comment by Ilya246** [comment]
what about animals that already speak, such as dragons?

**Comment by Stealthbomber16** [comment]
No opinion this issue comes solely from having to get admin assistance to convert a sentient cow to the revolution.

**Comment by keronshb** [comment]
No, only actual mobs should be.
