### ISSUE TITLE
discord event votes relay does not correctly report all votes.

### ISSUE THREAD

**Issue by IProduceWidgets** [space-wizards/space-station-14#23472]
## Description

We use a template for feedback votes of the form
> customvote "<EVENT NAME>, 9 loved, 1 hated" 1 2 3 4 5 6 7 8 9
The custom vote message shows up in discord, but it does not correctly report all the votes (option 9 tested as broken).

**Reproduction**

make a customvote -> an option wins that is not 9, but some votes are for 9 -> the discord message does not show any votes for 9 -> everyone thinks you suck at events because no one liked it!

**Screenshots**

**Additional context**

I did not check what happens if 9 wins, or very accurately if the issue exists for any other vote 1-8.

**Comment by Pangogie** [comment]
This is now fixed. #23670 
![image](https://github.com/space-wizards/space-station-14/assets/7548248/93678fac-49bc-41e4-bfc9-d9d395937f8d)
