### ISSUE TITLE
Invalid audio settings cause clients to be stuck in connecting forver

### ISSUE THREAD

**Issue by VasilisThePikachu** [space-wizards/space-station-14#23491]
## Description

**Reproduction**

1. In your client_config.toml. set ambience.volume greater or negative to 1
2. Try to connect

**Screenshots**

**Additional context**

There's been a bunch of people getting this when trying to connect

The fix by faint is by modifying the file but it should not be the fix and we should be handling this by resetting the audio settings

https://discord.com/channels/310555209753690112/790656972801572905/1191790144638951454

**Comment by pulpocaminante** [comment]
It also crashes pipewire when the client is subsequently closed

**Comment by pulpocaminante** [comment]
What is the file edit to fix it? I don't have or use discord.
