### ISSUE TITLE
Puddles still tick and despawn in map editing mode

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#2349]
Easy to demonstrate, use the entity spawn panel to spawn a puddle.

**Comment by moonheart08** [comment]
Seems to be an issue for several objects, i.e. APCs still drain power.

**Comment by metalgearsloth** [comment]
Was the map paused? There's stuff that doesn't pause because it was expensive but apcs should definitely be pausing.

**Comment by moonheart08** [comment]
@metalgearsloth it might be the case that mapping mode doesn't auto-pause maps
let me look.

**Comment by moonheart08** [comment]
yep, map isn't paused.
seems the `mapping` console command doesn't pause the created map.

**Comment by moonheart08** [comment]
Puddles still tick though.

**Comment by DrSmugleaf** [comment]
https://github.com/space-wizards/RobustToolbox/issues/1445
