### ISSUE TITLE
Cargo trade should be on the same map on a station

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#23524]
So:
- Remove the cargo map and selling.
- Use GridFill to add 1-2 trade stations near station on roundstart.
- Add a console to the station to sell anything on pallets.

**Comment by deltanedas** [comment]
shamelessly stolen from frontier smh :trollface:

**Comment by lzk228** [comment]
im already seeing like salvagers will rob trade stations to the last tile :trollface:

**Comment by EmoGarbage404** [comment]
Trade station is like Lethal Company station. You fuck around while selling shit and they feed you to a jumbo space carp.

**Comment by deltanedas** [comment]
ahelp clown stole the selling console and ate it ban he

**Comment by K-Dynamic** [comment]
Somehow won't be abused at all :trollface: 

The following will never happen:
- Cargo punting the station closer to cargo via shuttle
- Cargo punting the station _away_ by accident
- Command chilling on trade station while revs kill everyone else
- Cargo using force guns to launch then catch crates to sell
- Meteors
- Cargo building a giant claw to catch the station
- Cargo building a giant line of rods to the station
- Cargonia
- Nukies hiding themselves in a crate and hitch a ride to cargo
- All of the above

**Comment by lzk228** [comment]
> * Cargo punting the station closer to cargo via shuttle
> * Cargo punting the station _away_ by accident

station anchors

**Comment by strO0pwafel** [comment]
> - Nukies hiding themselves in a crate and hitch a ride to cargo
ngl that sounds fun as hell

**Comment by UbaserB** [comment]
> - Cargonia
> - Meteors

Its supposed to be invincible/untouchable

**Comment by FairlySadPanda** [comment]
What if the Trade Station was Cargonia all along

**Comment by K-Dynamic** [comment]
Trade station is the homeland of all cargonians

Seriously tho, if salv is gonna have their salv shuttle removed, probably just have the trade station pallets itself be a part of cargo to avoid administrative mess

**Comment by Kadeo64** [comment]
> Or the slightly less fun option, outright no access to the station, just a connection point for the conveyor belt to feed stuff through and let it churn and filter out people to space.

tbh I think this is the best idea, invincibile plastitanium structure with a unique invincible airtight plastic flap entity and conveyors.

**Comment by deltanedas** [comment]
players can hide in crates

**Comment by Kadeo64** [comment]
> players can hide in crates

put a chasm behind the flaps so anyone that goes through instantly dies

**Comment by UbaserB** [comment]
Resolved by #23863
