### ISSUE TITLE
Strange lighting/physics bug when walking alongside walls.

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#2353]
![2020-10-21_13-29-06](https://user-images.githubusercontent.com/49448379/96780101-1de1c400-13dc-11eb-94a4-0bb5ad4cf2f1.gif)

The physics part is that when hugging walls like this, your body can seemingly get stuck on nothing.

BRING BACK OLD BBS.

**Comment by ShadowCommander** [comment]
It looks like it's because you can 'see' through the gaps between each wall entity when you're close enough to them.

**Comment by 20kdc** [comment]
Lighting/physics here are potentially separate bugs.
Lighting would kinda be the fault of polar coordinates, but if this only triggers this close to a wall that explains why I didn't catch it. Precision issues, yaaay

**Comment by ShadowCommander** [comment]
To clarify, we've had the physics bug where when the player is walking into a wall they clip into the wall and bounce back. This could make it so that the player is partially inside the wall and as such do something with lighting.

**Comment by metalgearsloth** [comment]
Physics getting stuck is because of floating point imprecision the normal of your collision is deemed to be horizontal rather than vertical (in this case). Easiest way to fix is circle BBs for players (I can work on it).

**Comment by 20kdc** [comment]
More insight into the sparklies problem
![image](https://user-images.githubusercontent.com/22304167/96856720-24148680-1456-11eb-859e-0befa7086945.png)

**Comment by 20kdc** [comment]
so basically, rendering-wise, blame the near clipping plane
I'll have a PR ready extremely soon, I think

**Comment by metalgearsloth** [comment]
Physics side should be more or less as good as it gets for the foreseeable future I think so closing.
