### ISSUE TITLE
Prayers / red phone etc should play a sound for admins.

### ISSUE THREAD

**Issue by IProduceWidgets** [space-wizards/space-station-14#23578]
## Description

While prayers being difficult to catch does lend in some ways to their spontaneous nature, it also encourages players to ahelp their prayers instead. This is annoying and bad. I propose that instead the prayers should play a sound when they send the chat message to admins in a similar way to the AME overload alert or fax alert.

**Reproduction**

Be admin > only pay half attention because reasons > prayer comes in > too busy being elected to lead not to read.

**Screenshots**

**Additional context**

**Comment by lzk228** [comment]
dupe #18092
