### ISSUE TITLE
Station Map Text Low Contrast

### ISSUE THREAD

**Issue by iacore** [space-wizards/space-station-14#23584]
## Description
![image](https://github.com/space-wizards/space-station-14/assets/74560659/090e75c3-42d0-420b-98d2-ab271f76ad71)

some of the dark red text have poor visibility

**Comment by Errant-4** [comment]
Are you talking about the Vault/command's color? That was already changed to yellow, it might just not have been deployed to Live yet. If not, please elaborate

**Comment by iacore** [comment]
> dark red
