### ISSUE TITLE
Conveyors are faster at lower server tick rates

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/space-station-14#2358]
Somehow??

**Comment by DFogify** [comment]
Looks like the move function of conveyors is determined by the _speed multiplied by frame time. Speed is a set value, so it must be frame time.
I'm still working on getting an understanding of all the Timing classes, so maybe I'll get a PR together for this.
Game Timing has a NumFrames = 60 value that's static, so I wonder if that's the issue.

**Comment by PJB3005** [comment]
You're completely on the wrong track there. Speed should not factor in frame time at all since the physics system already does.

**Comment by DFogify** [comment]
Thanks for clarifying. I suppose I should read more before I open my mouth.
