### ISSUE TITLE
ERT/DeathSquad/CBurn should be able to see if someone is mindshielded or not.

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#23602]
## Description

We had a revolutionary round recently where ERT was called on salamander, and there was a big issue of ERT arresting mindshielded individuals since they couldn't actually *tell* if someone was mindshielded or not, so they had to get security to assist.

**Comment by Simyon264** [comment]
They should be able to see that with a secHUD and IIRC they spawn with one

**Comment by K-Dynamic** [comment]
This would be resolved with secglasses for CC staff (sechud function pr merged)

**Comment by Emisse** [comment]
this is just giving them sechuds

**Comment by UbaserB** [comment]
but im pretty sure they dont have sechuds?

**Comment by Emisse** [comment]
they arent actual game roles admins can just spawn them for them, or someone can update their outfit loadouts
