### ISSUE TITLE
welding does not cause blindness anymore

### ISSUE THREAD

**Issue by Dutch-VanDerLinde** [space-wizards/space-station-14#23606]
## Description
title

**Reproduction**
-weld something
-notice that your vision doesnt decay

**Screenshots**

**Additional context**

**Comment by mirrorcult** [comment]
@deathride58

**Comment by deathride58** [comment]
We're on the verge of sleeping and lack the brainpower to properly investigate at the moment, but judging from some quick poking on local, it looks like the `RequiresEyeProtection` component on welding tools has `Toggled` completely reversed. When you toggle the welder off, the component will be toggled on, and you'll take eye damage by attempting to weld despite the welder not being on. And when you toggle the welder on, the component toggles off.

We *think* #23422 might have something to do with this? Though we're not sure at the moment
