### ISSUE TITLE
Sawn-off shotgun in saltern's bar is broken

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#2360]
Spawned sawn-off on the left, bar sawn-off on the right.
![image](https://user-images.githubusercontent.com/6766154/96885605-090c3b80-1483-11eb-85fe-0d77a2277a27.png)

**Comment by SweptWasTaken** [comment]
Will fix

**Comment by SweptWasTaken** [comment]
Done. Closing.
