### ISSUE TITLE
medhud health icons should show more states

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#23613]

**Comment by Errant-4** [comment]
I don't think it's a bad thing that only specialised equipment can quantify your health state immediately. Makes Medical feel a bit more "solid". In what scenario/use case would this be important / what's the gameplay argument for this?

(Maybe introduce a wall-based Health Scanner that can check you without needing to go to medical for that, and have a small number of them be available?)

**Comment by chromiumboy** [comment]
Why does it need more states? You know roughly how bad a state you're in,  as it stands. What's there to gain by having greater granularity?

**Comment by UbaserB** [comment]
I dont think it needs more states, but it would be nice to have a colour *transition*. It wouldnt change the text or something but instead makes it feel more fluid.

**Comment by lzk228** [comment]
Bruh. Just alive crit and dead, maybe dead+rotting. And viruses, borers etc when theyll be added

**Comment by UbaserB** [comment]
> Bruh. Just alive crit and dead, maybe dead+rotting. And viruses, borers etc when theyll be added

No. you have good, poor, okay, bad, bad!, critical, and dead. That is a lot of states.

**Comment by lzk228** [comment]
i mean mobstates

**Comment by chromiumboy** [comment]
What's this about mobstates? The issue is about health icons...

**Comment by lzk228** [comment]
i fucked up with title
updated

**Comment by UbaserB** [comment]
Solved by #26027
