### ISSUE TITLE
Robohands gloves needs a custom sprite

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#23623]
## Description

For a "unique" glove it looks exactly like a black one.

![image](https://github.com/space-wizards/space-station-14/assets/134914314/1a75cddc-e554-448a-8d30-763b594330f7)
![image](https://github.com/space-wizards/space-station-14/assets/134914314/6fd14aff-f163-4ec6-8c73-8a3ba3e6f407)

**Comment by Kadeo64** [comment]
iirc robohands WERE just black gloves with a custom name on some maps (I couldn't spawn them in sandbox mode) but then they got turned into a unique entity (which can be spawned in sandbox mode). they're literally just renamed black gloves for roboticists
