### ISSUE TITLE
ClosetMaintenanceFilledRandom fails arbitrage sometimes

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#23630]
I love test RNG.

**Comment by Tayrtahn** [comment]
Can Cargo even order filled lockers? Why is this getting tested for arbitrage?

**Comment by Tayrtahn** [comment]
But also, something should be done to remove the randomness of the test.

It looks like there are a lot of items that can potentially spawn in the locker, each with a small chance. So when the dice rolls work out that a large enough number of items get spawned, the total value can add up enough to fail the test. So, maybe we can force every random roll to succeed when spawning a randomized inventory for the test? That way it's always testing the worst case.

Poking around a little bit, it looks like that might require modifying EntityManager in RT, but maybe there's a clever way to get around that.

**Comment by metalgearsloth** [comment]
https://github.com/space-wizards/space-station-14/issues/22959
