### ISSUE TITLE
Debug > Solution Manager UI is not updating properly

### ISSUE THREAD

**Issue by IProduceWidgets** [space-wizards/space-station-14#23645]
## Description

The Solution Manager is not updating properly after adding new solutions or changing solution volumes.

**Reproduction**

open the solution manager for a jug > add a new reagent > the jug visibly gets the solution (and actually gets the solution) > the UI does not show that it has a solution. > add another new (different) reagent > See that the 1st reagent now shows in the UI but now the 2nd one doesn't

**Screenshots**

**Additional context**

**Comment by TemporalOroboros** [comment]
Issue is a result of the UI updates occurring before the solution state is applied on each gametick. Updates currently use a UI network event, but could probably be changed to hook into the component state post-handle event on the client.

**Comment by metalgearsloth** [comment]
SolutionsEui might be better off being a Bui using states.

**Comment by TemporalOroboros** [comment]
> SolutionsEui might be better off being a Bui using states.

IIRC that allocates a dictionary for every entity with a BUI component (on creation not first use) which seems heavy for solutions. I can still do it, but I can hear the profiler screaming from here.

**Comment by PJB3005** [comment]
BUI wouldn't fix it either way, actually.
