### ISSUE TITLE
Vehicles make you immune to conversion to a revolutionary

### ISSUE THREAD

**Issue by Veritius** [space-wizards/space-station-14#23652]
## Description
You can't be converted if you're on a vehicle. I discovered this when someone tried to convert me on an ATV.

**Reproduction**
- Get on an ATV.
- Swap characters to a headrev antag and try to flash them.

**Comment by Kadeo64** [comment]
I think this is a side effect of them being stunproof

**Comment by Pangogie** [comment]
Vehicles removed awaiting better implementation.
