### ISSUE TITLE
There should be some way to obtain more pAIs

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#23665]
## Description

There is limited stock on stations, and if borgs can be mass produced, why cant pAIs?

**Comment by Holinka4ever** [comment]
Ghost role spamability.
But if someone is try to make it with positronic brains, peps will just spit on culpit, cause making a ghostrole, that intended to be a helping hands of station, into non-walking speaking device, will kinda hit a guts.

**Comment by GreyMario** [comment]
potato AI:

**Comment by Holinka4ever** [comment]
Oh wait right, potatOS, my bad though.
By the way, them seems not so popular... just not popular, thats all. And thats why not a lot of people know them. I mean if the even know about it, what it gives you? Just a ghost role in a mere potato...

**Comment by UbaserB** [comment]
> potato AI:
> 
> no seriously, [the potato AI is exactly what you want and already exists](https://github.com/space-wizards/space-station-14/pull/21142)

but you cant put potatoes in your PDA

**Comment by mr-bo-jangles** [comment]
> > potato AI:
> > no seriously, [the potato AI is exactly what you want and already exists](https://github.com/space-wizards/space-station-14/pull/21142)
> 
> but you cant put potatoes in your PDA

You want ants in your PDA? because that's how you get ants in your PDA

**Comment by Errant-4** [comment]
Potato AI should be deep-fryable to turn it into Chips AI, which can then fit into a pda
