### ISSUE TITLE
Add trading goods for cargo

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#23682]
## Description

Crates or packages with the sole purpose of buying and selling for profit.
**Reproduction**

**Screenshots**

**Additional context**

**Comment by UbaserB** [comment]
Isn't the gambling crate pretty much that?

**Comment by metalgearsloth** [comment]
Wrecks will probably need loot piles that can be sold for money.

**Comment by deltanedas** [comment]
starbound weapons/food/medicine/parts trading money farm

**Comment by Emisse** [comment]
this feels too gamey
