### ISSUE TITLE
Request: Ability for maps to support custom cargo shuttles.

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#23683]
## Description

I was thinking about how Core and Barratry is really grimy.. and how the cargo shuttle is totally not grimy.. and the way to fix this would be to have custom shuttles for each map. Of course, they would have a standard but it'd be interesting for the shuttle to be customised based on station aesthetics and size. Like uh, Cluster's cargo shuttle being tiny and Fland's very large.

**Comment by metalgearsloth** [comment]
They do, you just need to use composition on the station ent.

**Comment by UbaserB** [comment]
what does this mean

**Comment by metalgearsloth** [comment]
Look at BaseStationShuttles prototype.

**Comment by UbaserB** [comment]
okay
