### ISSUE TITLE
Air canister air is unbreathable

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#23689]
## Description

You start suffocating very quickly. An exception to this would probably be slimes, since the nitrogen content in the canister is high.

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/134914314/def88a35-d354-437a-82d4-6c3cd7dbdedc)

**Comment by Ilya246** [comment]
intentional, it's air, you're only breathing 21% oxygen at normal pressure
need to set tank release valve to 5x the default pressure for it to work

**Comment by Errant-4** [comment]
Now you know why Air Tanks come pre-set to 101.3 kPa

**Comment by deltanedas** [comment]
this is krill issue not bug

**Comment by UbaserB** [comment]
guh

**Comment by K-Dynamic** [comment]
The rot consumes

Idk why air tanks exist outside of providing pressure, which is better served by air (white) canister anyways
