### ISSUE TITLE
teleport to in the admin menu objects tab does not function

### ISSUE THREAD

**Issue by IProduceWidgets** [space-wizards/space-station-14#23701]
## Description

the "teleport to" verb in the admin menu objects tab does not function.

**Reproduction**

Open admin menu object tab > try to teleport to a grid or map > stay where you are instead.

**Screenshots**

![teleport to](https://github.com/space-wizards/space-station-14/assets/107586145/1d98eabb-228a-4d86-a26d-c3e6b0232256)

**Additional context**

**Comment by IProduceWidgets** [comment]
expands on [#22472] because it was not clear enough

**Comment by Kayek14** [comment]
Oddly enough, teleport here does work
