### ISSUE TITLE
Mix above 377.5899963378906K - diphenhydramine

### ISSUE THREAD

**Issue by TheEmber** [space-wizards/space-station-14#23735]
## Description

Very accurate temperature in diphenhydramine recipe in guidebook. Other chemicals temperatures is fine.

**Reproduction**

Just type "diphenhydramine" in guidebook - chemicals.

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/40074315/d8236645-d813-41da-9b76-c65bbb3072a2)

**Comment by K-Dynamic** [comment]
We also can't reuse our beakers to make more diphenhydramine as the oil turns to ash, and ash into charcoal with carbon.

**Comment by deltanedas** [comment]
yes thats the troll, you need to constantly make new beakers to reset temperature

beakers should slowly cool in the environment to avoid the need for this

**Comment by K-Dynamic** [comment]
Or just make it so ash and charcoal reactions are bottom priority

**Comment by deltanedas** [comment]
that would remove any difficulty from producing it

**Comment by K-Dynamic** [comment]
Unless beakers cool down or you have a way to both read and adjust beaker temps, it's just artificial and obscure mechanic to chemists who would expect mixing above min temps to make diphenhydramine or epi

Keep in mind it's also a complex recipe with many reagents, so it's already kinda difficult

**Comment by GreyMario** [comment]
artificial difficulty has no place in game design

**Comment by IamVelcroboy** [comment]
So, when I tested this, if all the ingredients are added to the beaker before putting the beaker on the hotplate, it turns to Diphenhydramine. I did not run into this other issue of the oil burning first. 

This must be happening by placing the beaker on the hotplate first. If mixing the chems in the beaker before placing on the hotplate is the only issue here, I wouldn't call that artificial game design. 

Concerning the temperature decimals. I have no idea why it's doing that. The recipe in the .yml only has 2 decimals.

**Comment by thebadman4662** [comment]
Oil burning issue is because people make more than single batch of Dip(at least that is what you can make with sulfuric acid heating) or use a lava beaker in first place. Plasma, water and smartfridges will usually be needed to make more. If hotplate lets you heat beaker just enough to make more than single batch then perhaps it will have a good use other than being bad heating but easy to use option.

**Comment by IamVelcroboy** [comment]
Looking at oils boiling point(which I'm assuming is being used for the burn reaction) It's only at 300k which is like 26.85c/80.33. Very low. So, I think the solution is bumping that up to 250f/394.26k

**Comment by deltanedas** [comment]
The recipe in the .yml only has 2 decimals.

it may be using a float for some reason instead of fp2

**Comment by EmoGarbage404** [comment]
All the off topic comments aside, just convert to a fixedpoint2 before you display in the guidebook

**Comment by IamVelcroboy** [comment]
Honestly, a quick search shows me that only 1 other reaction(hot ramen) is using decimals anyway. I don't think it needs to be that hyper specific. So, I'll just bump it back to the integer.

(As for the oil-> reaction. I was wrong and that happens at 520k. So, I think that really is a matter of making the reactions in sequence and not overheating/skill issue.)
