### ISSUE TITLE
Feature Request: Paramedic Remote

### ISSUE THREAD

**Issue by ColdDead** [space-wizards/space-station-14#23743]
It's very frustrating when a wounded paramedic is lying behind a door and you can't get in because of access. On the other hand, not all command team people give a paramedic AA if he has it RP just in case.

Paramedic Remote with the following features:
Doors opener when crew behind the door are down.

Simply a modified form of the Atomos Remote Door Controll

Take it easy in the CMO if it doesn't work, it only works when someone is down/injured behind the door. To prevent abuse of the tool

**Comment by EmoGarbage404** [comment]
Paramedic does not need a free AA pass whenever they have to rescue someone. They should be collaborating with the people in the department instead of committing a glorified B&E

**Comment by deltanedas** [comment]
real powermedics get insuls roundstart for this purpose anyway

**Comment by ColdDead** [comment]
> real powermedics get insuls roundstart for this purpose anyway

And then a Admin see it as Powergaming, or sec arrested you for "contraband" *sighs*
