### ISSUE TITLE
I want to be able to rotate screens

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#23762]
## Description

For mapping, this hurts me. Yeah it usually should make sense upright since you wont be able to read but to be fair i just want to be given the option.

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/134914314/341e05a9-6275-4d1e-8c32-21d9814bdfba)

**Comment by EmoGarbage404** [comment]
i mean you acknowledge why you aren't able to rotate them: it makes the text difficult to read.

**Comment by UbaserB** [comment]
> i mean you acknowledge why you aren't able to rotate them: it makes the text difficult to read.

it hurts me so much though, and you can still rotate you camera.

**Comment by EmoGarbage404** [comment]
> it hurts me so much though, and you can still rotate you camera.

do the screens rotate to match the camera

**Comment by UbaserB** [comment]
> > it hurts me so much though, and you can still rotate you camera.
> 
> do the screens rotate to match the camera

lol i was under the assumption it didn't rotate to match your camera, this is jank-looking as hell we're literally distorting spacetime

**Comment by EmoGarbage404** [comment]
i really don't see a good reason to rotate the screen considering the game already auto-orients them to be readable at all rotations. i'm gonna close this.
