### ISSUE TITLE
aHelp menu broken

### ISSUE THREAD

**Issue by AjexRose** [space-wizards/space-station-14#23761]
## Description

Recently, some players that are in the round can show up as never having connected during the round, and I just had a case in which a player that was playing wasnt showing up at all. 
**Reproduction**

Unfortunately I have no clue how to reproduce the problem besides adminning and noticing the odditites.
**Screenshots**

I'll try getting some if I can. 
**Additional context**

N/A

**Comment by AjexRose** [comment]
![aHelppanelbug](https://github.com/space-wizards/space-station-14/assets/112997230/3330a370-07d6-4bbc-a55d-54d79bf19881)
image containing an example of the bug

**Comment by Geekyhobo** [comment]
LoL that's why you wanted me to hold still. I have a feeling that this is what is causing this or something along these lines #18906

**Comment by ShadowCommander** [comment]
Need reproduction steps or more info. Can you check player list and other spots that would show a player like warps when this happens again?
