### ISSUE TITLE
Machine Part code needs removing

### ISSUE THREAD

**Issue by EmoGarbage404** [space-wizards/space-station-14#23764]
## Description

Machine parts aren't a thing anymore so remove the unused code.
- upgrade examine
- overall logic for machine parts
- machine part prototypes
- individual implementations per component
- condense boards to just use tags instead of part prototypes
- move the upgrading guide into construction and make it more general (flatpacker addition)

**Comment by Hmeister-real** [comment]
It should be kept for downstream, no?

**Comment by metalgearsloth** [comment]
> It should be kept for downstream, no?

If upstream removes it they're not going to get conflicts and we're not gonna maintain a dummy system that will bitrot.

**Comment by EmoGarbage404** [comment]
oh hey i did this
