### ISSUE TITLE
Cloning Clears Paraplegic Trait

### ISSUE THREAD

**Issue by Admiral-Obvious-001** [space-wizards/space-station-14#23771]
## Description

See the title. When cloned people can walk regardless of their trait.

**Reproduction**

Die as a paraplegic and get cloned.

**Screenshots**

N/A

**Comment by Emisse** [comment]
its a miracle

**Comment by K-Dynamic** [comment]
The deafblind mute wheelchair-bound QM executed by CMO being hauled to cloner:

**Comment by Admiral-Obvious-001** [comment]
With the removal of wheelchairs and the trait, this issue is no longer relevant.
