### ISSUE TITLE
Meat duplication glitch

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#23774]
## Description

As i am trying to cook anything that has raw meat in the recipe, the meat cooks and pops out as steak before the recipe is completed. Example being a burger or sausage bread. I noticed it was inconsistent though as sometimes the meat would cook and sometimes it wouldn't.

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/134914314/50a1baf6-379b-44ab-b6fc-3ccbc29436ce)

![image](https://github.com/space-wizards/space-station-14/assets/134914314/2ee06acc-2da5-429f-8772-15d518bdfcaf)

**Comment by deltanedas** [comment]
recipe should check if any ingredients got deleted? or disable construction inside microwave somehow

**Comment by GreyMario** [comment]
this is a direct consequence of real-time heating in microwaves

**Comment by Tin-Man-Tim** [comment]
#23835
