### ISSUE TITLE
The empty space is pure black for satchel inventories

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#23784]
## Description

Im pretty sure this is a bug and it looks bad ingame. Either way, i want the black to be either removed or toggleable because as a satchel-only user i cant tolerate this.

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/134914314/ec91aba9-2f88-4091-9942-e3f21742b88f)

**Comment by degradka** [comment]
This can be easily fixed by changing the current satchel grid to `0,0,7,3`, but I'm not sure if this is a bug.

**Comment by EmoGarbage404** [comment]
Its intentional. It represents space in the bag that cant have items inserted. Is the issue the visual appearance in some way? How should it look?

**Comment by Hmeister-fake** [comment]
Maybe it should have a background dependant on the color of the bag? So med bag, white background. Stock bag, grey background etc. And maybe a patchwork sewing around the actual inventory boxes to represent fabric.

**Comment by degradka** [comment]
> Its intentional. It represents space in the bag that cant have items inserted. Is the issue the visual appearance in some way? How should it look?

> It looks bad ingame. Either way, i want the black columns to be either removed or toggleable because as a satchel-only user i cant tolerate this.

**Comment by GreyMario** [comment]
> Is the issue the visual appearance in some way? How should it look?

Didn't you show an example of an unusable grid tile in the mockup? The issue ends up being that unusable tiles are opaque black here.
![](https://docs.spacestation14.com/en/assets/images/grid-inventory/grid-example.png)

**Comment by EmoGarbage404** [comment]
They're opaque because this screenshot has the opaque window option enabled. They're translucent with the default mode.

**Comment by GreyMario** [comment]
Then the best I can offer is "make it the same/a slightly darker gray as the cell border gray".

**Comment by UbaserB** [comment]
> Its intentional. It represents space in the bag that cant have items inserted. Is the issue the visual appearance in some way? How should it look?

Right now, when you hover over the black you can see a faint outline saying you cant place items. I would prefer for the black to just not exist, be empty space you can interact with the background. That's how id love it (of course, it can be toggleable if needed) 👍🏻

**Comment by Tayrtahn** [comment]
I say either make it empty space or match the vertical bar on the left (the one with the close button).

**Comment by Emisse** [comment]
agree the black is a little visually inconsistent
