### ISSUE TITLE
Tranquilizer shots dont work

### ISSUE THREAD

**Issue by OliverOtter** [space-wizards/space-station-14#23807]
## Description

Shotting someone with tranquilizer shells dont affect them at all, even when shot by 8 in a row. Armor or no armor.
**Reproduction**

Shoot someone with tranquilizer rounds. No effect

**Comment by degradka** [comment]
I was able to reproduce this issue on my end.

**Comment by Anzarot121** [comment]
100% related to this
https://github.com/space-wizards/space-station-14/pull/23429
