### ISSUE TITLE
Rotating the grid makes lasguns do silly

### ISSUE THREAD

**Issue by Skarletto** [space-wizards/space-station-14#23813]
## Description

title
**Reproduction**

Rotate a grid and shoot lasgun while on lattice. 
**Screenshots**

https://github.com/space-wizards/space-station-14/assets/122584947/051675ef-2add-4f78-a9f9-56766163bfc0

**Additional context**

actually a copy of [[23699]](https://github.com/space-wizards/space-station-14/issues/23699)

**Comment by GoodWheatley** [comment]
Dupe of #23699
