### ISSUE TITLE
Players shouldnt be assigned more than one antag role

### ISSUE THREAD

**Issue by QuietlyWhisper** [space-wizards/space-station-14#23868]
## Description

- pacifist head rev thieves
- pacifist syndicate thieves
- several counts of ahelps to remove pacifist
- (Might) result in less antag players if the same player is being picked twice, which isn't fair to the rest of the players
- (might be) a cause of nukie medics being ghosted due to the same player being picked for multiple nuclear operative positions

Even if pacifism is removed from thief the last two issues need to be touched on

**Comment by deltanedas** [comment]
antag refactor will allow this, i think i have a shitcode version in turf war that can be copied once its changed to use new toys

**Comment by asperger-sind** [comment]
#23445

**Comment by Kadeo64** [comment]
>headrev thief gets noct hypopen
>ez captain kill

**Comment by IProduceWidgets** [comment]
> (might be) a cause of nukie medics being ghosted due to the same player being picked for multiple nuclear operative positions

Is this still happening after #23568

**Comment by nikthechampiongr** [comment]
> > (might be) a cause of nukie medics being ghosted due to the same player being picked for multiple nuclear operative positions
> 
> Is this still happening after #23568 ?

As of an hour ago we had an ahelp about someone saying they got syndie and thief.

**Comment by deltanedas** [comment]
that was intended but its probably best to make it exclusive now that weve seen it

**Comment by UbaserB** [comment]
gotta agree

**Comment by QuietlyWhisper** [comment]
The issue remains, there are likely people that want to be traitor OR thief, not both.

**Comment by QuietlyWhisper** [comment]
Reopen pls unless a pr has closed this
