### ISSUE TITLE
Pulling Issues [The Compendium]

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#2387]
I **will** be keeping this checklist updated, so never fear someone having to make another one of these in a couple days time. Just comment underneath this thread with new issues.

- [x] You can pull multiple items at the same time. 
- [x] Pulling currently doesn't take up a free hand
- [x] Humans collide with each other when pulling them
- [x] When pulling multiple items, clicking the "pull" icon only stops pulling the first object pulled and goes away. You need to control-click on the rest of the objects to stop pulling them.
- [x] Pulling collidables is very jerky and can even kill you when pulled diagonally.
- [x] When pulling something that is anchored, walking out of range of it will not stop pulling it and will stick you with the slowdown till you stop pulling.
- [x] Pulling speed can be inconsistent with pushing speed on the same object.
- [x] Pulling doesn't change the sprite direction of the pulled entity based on the direction it's being pulled.

![2020-10-25_11-52-40](https://user-images.githubusercontent.com/49448379/97116328-43304400-16f4-11eb-9b04-9a5373aa37b6.gif)
![96587931-5b99fc00-12b9-11eb-89d7-87d6eb12ff4c](https://user-images.githubusercontent.com/49448379/97116361-6bb83e00-16f4-11eb-9867-fd5e419c0518.gif)
![96587931-5b99fc00-12b9-11eb-89d7-87d6eb12ff4c](https://user-images.githubusercontent.com/49448379/97117012-07e44400-16f9-11eb-9e89-1c213a64b627.gif)
![89090832-ab95b080-d3a5-11ea-957e-f980d80d5f81](https://user-images.githubusercontent.com/49448379/97117019-1599c980-16f9-11eb-9cda-79054a294cb4.gif)

[metalgearsloth's comment from a previous issue about pulling letting you transcend space and time...](https://github.com/space-wizards/space-station-14/issues/1971#issuecomment-709699394)

Closing #2306, #1557, #2304, #1971, #1799 in favor of this thread.

**Comment by DrSmugleaf** [comment]
> * [ ]  Pulling currently doesn't take up a free hand
PJB asked about this on the original pulling PR (https://github.com/space-wizards/space-station-14/pull/850#issuecomment-628290617), I'm not sure if a decision has been made about it.

**Comment by PJB3005** [comment]
I have made the decision that yes it should be done.

**Comment by SweptWasTaken** [comment]
All issues fixed! Good job team!
