### ISSUE TITLE
Clowns appear crit to themselves while not crit when they get self-shocked after using defibs

### ISSUE THREAD

**Issue by Hmeister-fake** [space-wizards/space-station-14#23901]
## Description
If you try to defib someone as a clown, you can fail and zap yourself, and from limited personal experience this makes your health icon become crit and give you the 3 death options while you are still alive (they don't function)

**Reproduction**
Be a clown (or have clown clumsiness), use a defib on someone, become zapped

**Screenshots**
Can't get one right now, could get one tomorrow

**Additional context**
Idk if it happens everytime and has only happened to me a few times since I don't often med-clown let alone clown in general.

**Comment by themias** [comment]
Looks like the recursize Zap() call for clumsy self-zapping throws a debug assert since it passes some components from the initial patient entity (instead of null or from the new clown target entity). Not sure if that has to do with it, but probably needs to be fixed.

**Comment by Hmeister-fake** [comment]
Fixed by #23930
