### ISSUE TITLE
Explosions do not log grid relative coords

### ISSUE THREAD

**Issue by Chief-Engineer** [space-wizards/space-station-14#23929]
#23649 changed explosion coordinates to log map relative coords instead of grid relative coords. This makes the coordinates useless for determining where on the station an explosion happened if the station moves during the round. Stations frequently move during rounds due to being bumped by shuttles like the cargo shuttle

courtesy ping for @tday93

**Comment by tday93** [comment]
@Chief-Engineer ah my apologies! Will get a new PR to address this tomorrow.
