### ISSUE TITLE
Traitors can spawn with the singular objective of escaping to centcomm.

### ISSUE THREAD

**Issue by nikthechampiongr** [space-wizards/space-station-14#23924]
## Description

On a recent lizard round a traitor spawned with just one objective: "Escape to centcomm alive and unrestrained".

1. Become traitor
2. Win rng lottery.(Or lose it depending on your interpretation). 

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/32041239/202ba62d-7d89-408c-b579-805ff1a52d4c)

**Comment by deltanedas** [comment]
yeah check logs it will say what objectives it tried to add and failed, if theyre all steal and hit the limit then it wont give any

**Comment by nikthechampiongr** [comment]
Didn't know that left logs. Anyways they got the same objective thrice. 
![image](https://github.com/space-wizards/space-station-14/assets/32041239/31d5d5f3-ccea-4021-b697-bcb362e3c2d3)

**Comment by nikthechampiongr** [comment]
> it should still say in debug log level what objs it attempted to add, unless gamer was just obscenely unlucky

I went to check logs in game. As it turns out SS14-admin lied to me and all the mind logs appeared thrice.  There is a singular log of the person I mentioned just getting the escape objective. Later he did get a kill objective but that was due to admin intervention.

**Comment by nikthechampiongr** [comment]
Unless it is not in the mind logs I can find no logs about failing to add an objective.

**Comment by deltanedas** [comment]
its logged by SharedObjectivesSystem so probably as "system.objectives" or something

**Comment by nikthechampiongr** [comment]
In a recent leviathan round a traitor had no objectives at all, they had the mind role and the briefing however no logs showing objectives were added.

**Comment by deltanedas** [comment]
ill add more debug logging in a bit to help pinpoint the issue
