### ISSUE TITLE
prying rad shutter makes a ton of sounds

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#23935]
## Description
might happen on normal shutters and even doors idk

if you pry it it spams the same sound like 10 times

probably FirstTimePredicted stuff

**Comment by CatMagic1** [comment]
it happens on emergency airlocks too

**Comment by nikthechampiongr** [comment]
That's my bad, I introduced this bug in #23818 because my dumbass forgot that there are things that get pried open that aren't airlocks.
