### ISSUE TITLE
The decelerator is really unfair as a weapon

### ISSUE THREAD

**Issue by Veritius** [space-wizards/space-station-14#23956]
## Description
Rads through walls. Nukies have no counterplay except to shoot the wielder, especially when they're holding a point. Every other gun lets you take cover. See Round 43630 on Salamander for an example.

**Comment by Veritius** [comment]
also it bounces off shuttle walls which does unbelievable amounts of damage

**Comment by metalgearsloth** [comment]
25 damage on a 20 shot weapon that goes through walls is way too high yeah.

**Comment by mirrorcult** [comment]
needs to do way way way less damage and itll be fine i think

**Comment by Aisu9** [comment]
didn't Liltenhead's video's stated that it was not supposed to damage entities?

**Comment by deltanedas** [comment]
that got fixed
