### ISSUE TITLE
Admin fire smite is now too deadly

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#23963]
## Description
Currently the admin fire smite is doing way more damage than it used to. Something changed and now the fire smite is a guaranteed kill button. It crits the player in about 5 seconds.

Prieviously the smite was able to be used as a way to In character non-lethaly smite a player. It is now very leathal and will quickly make the corpse unrevivable due to the absurd burn damage it can apply in a quick timeframe.

**Reproduction**
use the "make the burn" admin smite

**Additional context**

**Comment by Admiral-Obvious-001** [comment]
This is because of the PR that made burn stacks significantly more deadly. It's not really the smite that's the issue.

**Comment by Aisu9** [comment]
> This is because of the PR that made burn stacks significantly more deadly. It's not really the smite that's the issue.

this is because of a PR that heavily reduced the temperature damage threshold, nothing touched Firestack

**Comment by Admiral-Obvious-001** [comment]
> > This is because of the PR that made burn stacks significantly more deadly. It's not really the smite that's the issue.
> 
> this is because of a PR that heavily reduced the temperature damage threshold, nothing touched Firestack

Didn't fire stacks get changed to 3.5 heat per tick instead of 1?

**Comment by Aisu9** [comment]
the firestack were buffed and temperature damage threshold were heavily nerfed, but not a single instance that cause temperature increases or decreases were tweak to accommodate.
It is as easy to boil a single room as before or dying of cold because of a freezon mutation of cryo anomaly went crit, nothing were done to improve how to deal with temperature issues because even 90 minutes of constant atmos distribution it wont reduce the temperature of the room

**Comment by Kayek14** [comment]
A variable scale would be the best option imo.

Having the choice to keep it as it is so its a gaurenteed death, or the choice to only apply a small firestack, one that still does damage but is removed easily by rolling.

If we cant make it variable, I would like to see it revert back to how it was.  where it is still damaging, but not a gaurenteed death. Ideally it would kill you in about 20 seconds, giving the player time to remove the fire by rolling a few times.

**Comment by Emisse** [comment]
this just needs someone to crack down and look at fire damage/lava across the spectrum. adjusting each instance individually is a bandaid

**Comment by deltanedas** [comment]
fire rework to increase body temperature with hardsuit on and bake people alive instead of charring their skin through a spaceproof hardsuit, when

then lava is less of an issue kinda
