### ISSUE TITLE
Some crates looks metal but drops plastic on deconstruct

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#23983]

**Comment by themias** [comment]
Can you specify which ones? I'd imagine we would just need to change the parent prototype in the YAML for those crates.

**Comment by Emisse** [comment]
which

**Comment by lzk228** [comment]
dunno!

**Comment by deltanedas** [comment]
i think some in engi are grey but drop plastic

**Comment by degradka** [comment]
All CrateEngineering drop plastic
