### ISSUE TITLE
Explosions originating from an embedded throwable can "miss" the target they are embedded in

### ISSUE THREAD

**Issue by Errant-4** [space-wizards/space-station-14#23995]
## Description
If an Exploding Pen is embedded in a target it's possible for the target entity and the pen to be on different tiles, causing the center of the explosion to miss the target. This means they take ~45 damage instead of 120 and survive 

Hitting a target with an embedded explosive should count as point blank range, whatever it takes to mechanically achieve this result. It's not intuitive that the target will survive or die based on where it was standing on the tile grid. The attacking player has made a dodgeable attack and they hit, they have succeeded, their attack should not fail due to external and more or less arbitrary conditions
If a player has to wonder "why didn't they die" and the answer is "they were on the other side of a magic line" that's an implementation issue

**Reproduction**
It's for some reason harder to reproduce this with an embedded pen, than with one thrown on the ground, but that's how the issue came up in the first place
Jan 12, Leviathan round 43694 
Cargo bay, at tick 615000 

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/35878406/e1da89b5-42be-4056-a0a4-972af260f365)
![image](https://github.com/space-wizards/space-station-14/assets/35878406/d588659d-6c45-4002-ab7d-75311f9f4576)
![image](https://github.com/space-wizards/space-station-14/assets/35878406/2bcc58d5-670a-4e1a-b022-75f6758e7086)
![image](https://github.com/space-wizards/space-station-14/assets/35878406/d833b2d4-431e-4e21-a630-4eca2d28223f)
![image](https://github.com/space-wizards/space-station-14/assets/35878406/230a0f09-97ee-4956-8391-1b75b3767bb0)

**Comment by deltanedas** [comment]
god damn that is creative...

perhaps before checking dist raise an event to have embedded projectiles set dist to 0

**Comment by Errant-4** [comment]
Seems to have been fixed by #30112
