### ISSUE TITLE
Request: HOS's dresser should contain neck gaiters

### ISSUE THREAD

**Issue by deepdarkdepths** [space-wizards/space-station-14#23998]
They look cool and fit HOS's style!
There was one in a locker by default before the whole dresser update happened but this was a month ago so I don't remember what map. 
Would PR this myself but I don't know how to work code.

![image_2024-01-12_180306123](https://github.com/space-wizards/space-station-14/assets/155149356/2e8d18c3-c1f6-45a0-a16b-f8a6d466a23e)

**Comment by degradka** [comment]
I agree on this!
