### ISSUE TITLE
Ninja midround antagonist can spawn on extended.

### ISSUE THREAD

**Issue by TurboTrackerss14** [space-wizards/space-station-14#24009]
## Description
title
**Reproduction**
Set round to extended
wait an eternity
Ninja ghostrole spawns

**Additional context**
feel free to close if intended but Extended is basically "no antagonists ™️" so feels strange to have a midround antag spawn in without admin intervention

**Comment by K-Dynamic** [comment]
Terminator can also spawn on extended

I _think_ extended still rolls random events and midround antags, you just don't get roundstart antags

**Comment by LankLTE** [comment]
Extended rolling random events is intended.

**Comment by EmoGarbage404** [comment]
introducing: boring mode. We removed all antagonists, midrounds, and possible threats. You are now free to RP in peace without the pesky disturbances of gameplay.

**Comment by metalgearsloth** [comment]
greenshift my beloathed.

**Comment by GreyMario** [comment]
So then how are you supposed to have a fully curated admin event that doesn't get interrupted by a mob of tarantulas or a zombie outbreak, hmmmm?

**Comment by LordEclipse** [comment]
> So then how are you supposed to have a fully curated admin event that doesn't get interrupted by a mob of tarantulas or a zombie outbreak, hmmmm?

part of the fun!

**Comment by mirrorcult** [comment]
> So then how are you supposed to have a fully curated admin event that doesn't get interrupted by a mob of tarantulas or a zombie outbreak, hmmmm?

`endgamerule BasicStationEventScheduler`

**Comment by it-joco** [comment]
> introducing: boring mode. We removed all antagonists, midrounds, and possible threats. You are now free to RP in peace without the pesky disturbances of gameplay.

Why do you have to be a dick about this? There are reasons for extended, from admin-driven round events to simply calmer rounds with more character interaction that isn't hampered by an antag sending the station into a death spiral.

There's no reason to be an asshole, man.

**Comment by Hmeister-fake** [comment]
> > introducing: boring mode. We removed all antagonists, midrounds, and possible threats. You are now free to RP in peace without the pesky disturbances of gameplay.
> 
> Why do you have to be a dick about this? There are reasons for extended, from admin-driven round events to simply calmer rounds with more character interaction that isn't hampered by an antag sending the station into a death spiral.
> 
> There's no reason to be an asshole, man.

Spiders, slimes and ninjas don't usually send the station into doom, just give literally a whole department a reason to exist other than shitters and anoms, security, and just make the round more interesting if theres no admin event going on.

**Comment by deltanedas** [comment]
if you want to disable events you can do just that as seen above

**Comment by deltanedas** [comment]
you could literally have a preset that has no event scheduler then make that 100% in secret :trollface:
