### ISSUE TITLE
Metamorphic glass shift click error

### ISSUE THREAD

**Issue by Everturning** [space-wizards/space-station-14#24011]
## Description
When shiftclicking a glass full of something that uses the metamorphic glass sprite and 'looks like something', it'll say something along the lines of '#u fullIt looks like a x chemical'

**Reproduction**
get moonshine
fill to brim
shiftclick
30u fullIt looks like a Strong-Smelling Chemical

**Screenshots**
![Screenshot 2024-01-12 220849](https://github.com/space-wizards/space-station-14/assets/146485322/3519cb42-3e0b-4552-8de3-17a947d85d5a)

**Additional context**

**Comment by dragonryan06** [comment]
Seems related to or the same as #23917
