### ISSUE TITLE
Port foostep_sounds from tiles to entities.

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#2403]
footstep_sounds determine what a tile sounds like when stepped on by a player. This should be ported to entities so stuff like stepping on a plushie, bikehorn etc. can make a sound. 

Also would tie nicely into stuff like landmines and mousetraps.

**Comment by metalgearsloth** [comment]
Sounds like it should be a component with an ICollideBehavior for it (for anyone that wants to attempt it). Ideally this would trigger an event so other components could implement behavior when stepped on.

**Comment by Ygg01** [comment]
Assign this to me, I'm working on it, but not at my dev comp ATM.

**Comment by SweptWasTaken** [comment]
Done by #2496 but never closed!

**Comment by SweptWasTaken** [comment]
Apparently still borked, reopening.
