### ISSUE TITLE
Super Bite Burger cannot be cooked

### ISSUE THREAD

**Issue by lapatison** [space-wizards/space-station-14#24034]
## Description

Microwaves have an item capacity of 10 items (After #23577).
SuperBiteBurger requires 13 items to be cooked.
https://github.com/space-wizards/space-station-14/blob/a97eb8dcdcf8cef67a8f2de4b4cfe375da509276/Resources/Prototypes/Recipes/Cooking/meal_recipes.yml#L290-L297

**Reproduction**

1. Try to stuff microwave with Super Bite Burger ingredients.
2. Get the `It's full.` message

**Screenshots**

no
**Additional context**

no

**Comment by lzk228** [comment]
increase capacity to 15?

**Comment by deltanedas** [comment]
unit test too

**Comment by EzequielHSacco** [comment]
To add to this now medicated sutures and Regen mesh cannot also be crafted. Same issue of the capacity

**Comment by AzureWildfire** [comment]
This also breaks medicated sutures and regenerative mesh recipes

**Comment by GreyMario** [comment]
> This also breaks medicated sutures and regenerative mesh recipes

1 cloth, 1 topical, 1 crop, 1 reagent container

no, this doesn't break these recipes.

**Comment by GreyMario** [comment]
for the record I've got a project that's going through and rebalancing food and

no

I'm NOT changing the Super Bite recipe

**Comment by AzureWildfire** [comment]
> > This also breaks medicated sutures and regenerative mesh recipes
> 
> 1 cloth, 1 topical, 1 crop, 1 reagent container
> 
> no, this doesn't break these recipes.

My bad this is not what's breaking the recipes.
