### ISSUE TITLE
healt says dead while I am alive

### ISSUE THREAD

**Issue by chadosmen** [space-wizards/space-station-14#24043]
## Description
so I am doing something an bang my health says dead can't take anything or inspect but I am alive still can move an open doors if I relog the bug is gone for some seconds an it comes back 
**Reproduction**
do something an bang health says dead

**Screenshots**
![20240113172235_1](https://github.com/space-wizards/space-station-14/assets/156548033/f19d445c-589a-4be6-ad04-3ddee3a55a39)

**Comment by deltanedas** [comment]
dupe
