### ISSUE TITLE
Cyborgs get Deleted on Salvage Magnet Wrecks when they despawn

### ISSUE THREAD

**Issue by Dynamiteside** [space-wizards/space-station-14#24058]
When a Salvage Magnet Wreck despawns / times out it deletes all Cyborgs, unlike Humanoids that just get dropped in space. 
Since there is no time warning for when they disappear anymore seemingly (or borgs dont hear it atleast) makes being a salvage borg really bad with magnet wrecks and asteroids, especially with some of the new BIG magnet wrecks.

**Comment by deltanedas** [comment]
also exped early ftl ignores borgs
make the thing also check for borgchassis

**Comment by K-Dynamic** [comment]
> also exped early ftl ignores borgs make the thing also check for borgchassis

What does exped early ftl do?

**Comment by deltanedas** [comment]
if you are dead or not a human you can ftl back to the station early
