### ISSUE TITLE
Entity<SolutionComp> cant be saved

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#24078]
## Description
have to delete every drain welder etc before it will save

its saying Entity<SolutionComponent> is not a datadefintion

probably needs engine change

**Comment by metalgearsloth** [comment]
You can't save components.

**Comment by deltanedas** [comment]
yes but it doesnt need to
it should only save the entity then get Comp on load

**Comment by ElectroJr** [comment]
> probably needs engine change
Yep, created an engine issue: space-wizards/RobustToolbox/issues/5580
