### ISSUE TITLE
Quantum spin inverter and mail tube are VERY bugged

### ISSUE THREAD

**Issue by Kadeo64** [space-wizards/space-station-14#24093]
**Description**
If you send the quantum spin inverter through a mailing unit and teleport to it before the quantum spin inverter has reached the end of the pipe, it COMPLETELY DELETES you. Freezing your game (much like a Ripley falling down a chasm) and forcing you to relog, to which you will find you are at the center of the station, as a ghost, because your body got completely deleted.

**Reproduction**
1: get two quantum spin inverters
2: send one down a mailing unit and flush
3: swap places with the spin inverter BEFORE it reaches the other end
4: watch as you arrive to the other end of the mail unit and your entity gets COMPLETELY deleted

**Additional context**
did this on round #43894, got deleted, ahelped that my entity got deleted
this seems like an issue with mail units not being able to fit living entities but instead of just force ejecting them it just deletes them

related to #24095 possibly, but this one stands out as it's own bug since it's probably something people will try and inevitably be round removed over

**Comment by mirrorcult** [comment]
![image](https://github.com/space-wizards/space-station-14/assets/19853115/bf81a71c-a662-4a87-a199-d525eea82045)
from disc

**Comment by metalgearsloth** [comment]
Content and transform system name a more iconic duo.

**Comment by asperger-sind** [comment]
This is just like old disposals all over again, dispose yourself off-grid and you're sent to the shadow realm.

**Comment by GoodWheatley** [comment]
Fixed by #24772

**Comment by Kadeo64** [comment]
bug of the year 2024 squashed
