### ISSUE TITLE
tail wag emote needs a cooldown or needs to be removed from chat log actions

### ISSUE THREAD

**Issue by retequizzle** [space-wizards/space-station-14#24091]
![image](https://github.com/space-wizards/space-station-14/assets/67210376/bbb253af-3c56-43e7-b8e6-3a6758abb1b2)

this is what you get if you spam the emote repeatedly, recommend either adding a cooldown to the emote or just removing the chat documentation for the emote itself considering the emote is already communicated very visually compared to any other emote in game currently

**Comment by Emisse** [comment]
i thought i brought this up as an issue before it was even merged

**Comment by EmoGarbage404** [comment]
doesn't need to have the start/stop IMO. just leave it as a "wags their tail" and play it once. beyond that it's just as spammy as any other emote.

**Comment by Emisse** [comment]
imo it shouldnt be an emote, just a species specific action
