### ISSUE TITLE
Cargo console needs a rework.

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#2410]
The cargo console currently pulls it's list of products from a hard-coded list in computers.yml

**Comment by Zumorica** [comment]
If it's a list in a prototype, I wouldn't really call it hard-coded :P
This is also how autolathes work, for example.

**Comment by SweptWasTaken** [comment]
> 
> 
> If it's a list in a prototype, I wouldn't really call it hard-coded :P
> This is also how autolathes work, for example.

w/e it's dumb and should automatically detect - type: cargoProduct

**Comment by PaulRitter** [comment]
<:thistbh:770722981093048350>

**Comment by PaulRitter** [comment]
<:thistbh:669088736042024960>

**Comment by Zumorica** [comment]
Closed in favor of #2717
