### ISSUE TITLE
Dynamic way to disable jobs depending on the map. Disable QM, Warden and Chaplain on saltern.

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#2413]
Also a dynamic way to set starting positions depending on the map.

**Comment by F77F** [comment]
this *does* only mean **starting** jobs right? or does this mean that, per map, the HOP should/should not be able to assign even the job title either?

**Comment by F77F** [comment]
@Zumorica  uh, king? 👑

**Comment by moonheart08** [comment]
@F77F Making both an option in the future could be nice (i.e. some map can absolutely not have cmo, for example.) but isn't necessary

**Comment by Zumorica** [comment]
Done.
