### ISSUE TITLE
Standardize prototype/resource naming.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/space-station-14#242]
Seriously it's a mess. A mix of all case types.

**Comment by Zumorica** [comment]
I propose using either PascalCase or camelCase as a convention.

**Comment by Injazz** [comment]
camelCase for both IDs and parameter names, PascalCase for component names, im gonna clean it up a bit

**Comment by AJCM-git** [comment]
Duplicate of #831

**Comment by Zumorica** [comment]
(Closed in favour of #834)
