### ISSUE TITLE
Shuttle and pod grids can end up overlapping

### ISSUE THREAD

**Issue by LordCarve** [space-wizards/space-station-14#24201]
## Description

This happened when evac launched into FTL. Probably caused by the shuttle size (first time I saw an escape shuttle this big). Probably due to pod locations being absolute rather than relative (not taking shuttle size into account).

**Reproduction**

Should be replicable 100% of the time with this map+shuttle combo, if it's the size of the shuttle that is indeed the cause.

**Screenshots**

![shuttle pod overlap](https://github.com/space-wizards/space-station-14/assets/27449516/e6081e75-56a4-483c-b86f-999d3a118607)

**Comment by metalgearsloth** [comment]
Found the issue, FTLing grids don't consider localcenter so depending how it was mapped it can cause overlap. Fixed in https://github.com/space-wizards/space-station-14/pull/24430
