### ISSUE TITLE
Terminators need to spawn with a mindshield or be unable to be converted.

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#24213]
## Description

When i was playing a terminator revolutionary round yesterday, i got converted immediately. When i saw my target, who was un-mindshielded and with the captain, captain questioned me about not having a mindshield. I had no idea if i was allowed to accept the mindshield and then have captain either metagame or ahelp me about accepting the mindshield as a revolutionary, or refuse it and risk failing my objective. I had to literally ahelp in the middle of it while captain shot me down on the spot and my round was ruined. Luckily that specific round they were like when i LOOC'd that i was in the middle of ahelping why i didnt respond, so they gave me a chance. Still, they really should have a mindshield and even Repo, the admin at the time, thought the same thing.

**Comment by GreyMario** [comment]
hey that naked guy we've never seen before has a mindshield that's kinda sus

**Comment by Hanzdegloker** [comment]
I suppose you could make terminators immune to being converted and having a mind shield implanted. They are a friend to neither the station nor revolution. Flash don't work because metal man, mind shield don't work because metal skull, simple as.

**Comment by lzk228** [comment]
it would be strange :trollface:
looks like we just need a component what gonna be like NotConvertable, you without mindshield but still cant be converted
