### ISSUE TITLE
Carrot Juice have Oculin, but don't treat blindness

### ISSUE THREAD

**Issue by gordod3** [space-wizards/space-station-14#24227]
When you metabolize Carrot Juice get 0.15 unit Oculin, but it's too few for treatment blindness from weld and no matter how much you drink it. Just make Oculin work from 0.15 unit, make more Oculin when metabolize Carrot Juice at least 0.50 Oculin or delete oculin from metabolize Carrot Juice.

**Comment by UbaserB** [comment]
![image](https://github.com/space-wizards/space-station-14/assets/134914314/905a85d3-7116-4ce4-94f5-0443389400a8)
turns out carrot has no more oculine anymore, weird

**Comment by Scribbles0** [comment]
> ![image](https://private-user-images.githubusercontent.com/134914314/297704440-905a85d3-7116-4ce4-94f5-0443389400a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NzMzMjEsIm5iZiI6MTcwNTU3MzAyMSwicGF0aCI6Ii8xMzQ5MTQzMTQvMjk3NzA0NDQwLTkwNWE4NWQzLTcxMTYtNGNlNC05NGY1LTA0NDMzODk0MDBhOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOFQxMDE3MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNDI1NzNhNzI5Y2NhNGZlNTgwOGFlNWU3N2IxYjFkMTU2ZjE3YTM0ZjdhODYwYjhlN2ExMTg5YjljNWQxY2RjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XBh0g5VU41e9-lhRbK027psqRr9o-Nom5EgCNqtyAIo) turns out carrot has no more oculine anymore, weird

![image](https://github.com/space-wizards/space-station-14/assets/91828755/8a94f907-34f1-4474-997d-b6032f32546f)
when you metabolize carrot juice you get oculine but its not enough to heal anything

**Comment by UbaserB** [comment]
Im going to make a PR fixing this
