### ISSUE TITLE
Disposals bins shouldn't be nuke-proof

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#24233]
## Description

If you can unanchor and deconstruct them, it makes perfect sense that you can also destroy them. People have been using the strategy to survive nukes too often and it subtracts from the experience of trying to run to a safe place (like a fridge, which is intended) to survive. Fear is fun, especially in a game like this.

**Comment by Kadeo64** [comment]
running to disposals to survive is still survival, especially on maps with disposals units sparsely mapped

**Comment by Kadeo64** [comment]
> > running to disposals to survive is still survival, especially on maps with disposals units sparsely mapped
> 
> yeah but they're like everywhere and you have 300 seconds.

you've only got like 120 seconds unless you give up hope the second the nuke turns on

**Comment by deltanedas** [comment]
30 seconds is plenty of time to walk 8 tiles to your local disposal unit, or make one

assuming no spacing / firelocks etc

**Comment by Kadeo64** [comment]
> assuming no spacing / firelocks etc

\>no spacing

\>_no spacing_

\>_**no spacing during nukies**_

**Comment by UbaserB** [comment]
> > assuming no spacing / firelocks etc
> 
> >no spacing
> 
> >_no spacing_
> 
> >_**no spacing during nukies**_

hence why they said 30 seconds.

**Comment by ZeroDayDaemon** [comment]
Disposals bins definitely shouldn't be nuke-proof

**Comment by UbaserB** [comment]
Solved by #29438
