### ISSUE TITLE
Feature request: Make closed drink containers injectable and extractable with syringe

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#24248]
title

**Comment by Tayrtahn** [comment]
This should probably be done on a case-by-case basis, since it makes sense for some drink containers and not for others. Glass bottles probably shouldn't work, for instance.

Also, realistically, if you injected a soda can with a syringe, wouldn't it leak?

**Comment by deltanedas** [comment]
chem dispensers can do this already so why not

**Comment by Tayrtahn** [comment]
This appears to already be possible. Droppers and syringes can inject/draw to/from drink cans and bottles, from my brief testing.

**Comment by hord-brayden** [comment]
> This appears to already be possible. Droppers and syringes can inject/draw to/from drink cans and bottles, from my brief testing.

I've been using this for some time, as well. Used to spike the pile of drinks in medbay with fourteenLoko during the great starvation change of '23.

**Comment by lzk228** [comment]
works from some point
