### ISSUE TITLE
Rotations are absolutely cooked

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#24274]
Both the muzzle flash and my character aren't rotating properly but this might just be a strafing moment again.

![image](https://github.com/space-wizards/space-station-14/assets/31366439/b88a44ea-b685-44a8-9182-35ac869bf697)

**Comment by deltanedas** [comment]
world rotation ops

**Comment by K-Dynamic** [comment]
Rotation and combat don't mix together well

**Comment by Plykiya** [comment]
this was fixed like five or six times at this point, with another one like two days ago
