### ISSUE TITLE
Ordering crates in bulk is broken

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#24285]
## Description

When you order more than 1 crate in a single order (like, 5x or something) it only spawns one crate. I dont know if this is true, but i heard a man speak about this while i was observing. Best form of bug report 💯

**Comment by metalgearsloth** [comment]
Dupe https://github.com/space-wizards/space-station-14/issues/24279

**Comment by UbaserB** [comment]
Damn they barely did it faster than me lol
