### ISSUE TITLE
Use momentum in physics

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#2428]
because PJB said so and he shot down our force controllers idea :pensive: 
also see https://github.com/space-wizards/RobustToolbox/issues/1364

**Comment by metalgearsloth** [comment]
(Cough put it on RobustToolbox cough cough)

**Comment by Zumorica** [comment]
> (Cough put it on RobustToolbox cough cough)

(Sure I'll open a mirror issue in the engine, but won't close this one since we have a bunch of VirtualControllers here)
