### ISSUE TITLE
Revolutionaries should be disabled

### ISSUE THREAD

**Issue by FairlySadPanda** [space-wizards/space-station-14#24288]
## Description
As noted by maintainer review on this document: https://github.com/space-wizards/docs/pull/132

Revolutionaries was introduced without a proper design document due to being an inherited SS13 mode.  However, it has significant design problems that the maintainers are unhappy with. Patching the current mode is fraught given the mode has several major flaws, such as a boring metagame and enforced round removal, and no design document to fall back on for guidance.

Rather than attempting to fix the mode mid-flight, and potentially disappointing players with discussions that go nowhere, Revolutionaries should be disabled until a design document to the satisfaction of the maintainers is approved and implemented.

**Comment by K-Dynamic** [comment]
Exile mechanics would go a long way (even using evac itself to exile non-revs and command would be funny)

**Comment by Rainbeon** [comment]
I would rather just keep it in until we get replacement Revs, the gamemode is flawed but still playable and can be enjoyable (I would also put Zombies in this same bucket)

**Comment by FairlySadPanda** [comment]
https://github.com/space-wizards/space-station-14/pull/24420 kermit_sipping_tea.jpeg
