### ISSUE TITLE
Trade Station needs a ghost warp point

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#24284]
## Description

I cant go check the state of the station without flying around until i find it or a cargo tech already being there, and it's kind of dumb to put a station beacon on the map so it's just more easily solved by adding a warp point kind of like how the nuke and nuke disks work (likely by attaching it to the station as a whole?)

**Comment by Emisse** [comment]
just put a warp point on it thats why we kept the warp points

**Comment by UbaserB** [comment]
> just put a warp point on it thats why we kept the warp points

oh

**Comment by UbaserB** [comment]
I guess i can do it later
