### ISSUE TITLE
You shouldnt be able to place a portal using the handheld teleporter on the Trade Station

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#24291]
## Description

Too abusable and invalidates the cargo shuttle.

**Comment by UbaserB** [comment]
Same thing with fultons actually i just dont know how you'd blacklist that

**Comment by K-Dynamic** [comment]
Maybe have both old and new system; old where you ftl to trade post, new where you manually offload and onload at trade post

Fultons would still bypass FTL but I think portals get deleted? (Seen conflicting results where a portal was used on station to expedition, and evac shuttle portals vanishing after certain distance)

**Comment by deltanedas** [comment]
fultons still work across maps but portals wouldnt work

**Comment by Kadeo64** [comment]
can't forget quantum space inverters 

maybe it would be possible to add some kind of invisible entity that blocks fultons from being opened but that's a lot of work

**Comment by UbaserB** [comment]
> can't forget quantum space inverters
> 
> maybe it would be possible to add some kind of invisible entity that blocks fultons from being opened but that's a lot of work

Yes i know about those, the reason why i didnt directly mention it is because for 1 it needs research, and 2 its actually harder to use than it sounds for cargo hauling.

**Comment by K-Dynamic** [comment]
Tangential but imo fultons shouldnt work across maps

**Comment by Kadeo64** [comment]
> > can't forget quantum space inverters
> > maybe it would be possible to add some kind of invisible entity that blocks fultons from being opened but that's a lot of work
> 
> Yes i know about those, the reason why i didnt directly mention it is because for 1 it needs research, and 2 its actually harder to use than it sounds for cargo hauling.

it's actually really easy to use for cargo hauling
step 1: put spin at trade station
step 2: have the linked spin in-hand
step 3: get in a Ripley
step 4: you can now teleport 30 crates/objects to the trade station

**Comment by BreadyToad** [comment]
Imo it would be the best to make portals from a handheld teleporter not work across plains, because with fultons you still need someone to actually get the cargo to a specific point and sell the stuff manually

**Comment by UbaserB** [comment]
> > > can't forget quantum space inverters
> > > maybe it would be possible to add some kind of invisible entity that blocks fultons from being opened but that's a lot of work
> > 
> > 
> > Yes i know about those, the reason why i didnt directly mention it is because for 1 it needs research, and 2 its actually harder to use than it sounds for cargo hauling.
> 
> it's actually really easy to use for cargo hauling step 1: put spin at trade station step 2: have the linked spin in-hand step 3: get in a Ripley step 4: you can now teleport 30 crates/objects to the trade station

that actually requires a ripley though and i dont see them often made

**Comment by UbaserB** [comment]
Either way, the sheer amount of effort it takes to use that technology is enough payout for what it does so it's balanced. Unlike hand-held teleporters, or fultons which are roundstart.

**Comment by Hmeister-real** [comment]
Imo teleporter should be limited to a single grid, so that you can't place it on a shuttle for example.

**Comment by Ilya246** [comment]
the station could simply have a long cooldown between separate buys and separate sells so that you can do fast transportation but it doesn't really boost your order roundtrip time

**Comment by MACMAN2003** [comment]
you could use the same logic to justify the removal of the cargo telepad

**Comment by EmoGarbage404** [comment]
> you could use the same logic to justify the removal of the cargo telepad

shame that the teleporter allows for full use of the ATS and is roundstart whereas the telepad only expedites purchasing (you cannot sell through it) and is only available like 40+ minutes into a round once t3 has been unlocked (and also can be permanently locked out by getting another discipline's t3)

**Comment by UbaserB** [comment]
> shame that the teleporter allows for full use of the ATS and is roundstart whereas the telepad only expedites purchasing (you cannot sell through it) and is only available like 40+ minutes into a round once t3 has been unlocked (and also can be permanently locked out by getting another discipline's t3)

its t2 last i checked
