### ISSUE TITLE
TerminatorSystem fixes

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#24314]
- The component stores the target when it should be on the gamerule and the component should store the attached gamerule.
- It should be exterminator not terminator (please no DMCA).
- It's removing components on mapinit

**Comment by deltanedas** [comment]
what would the alternative be prototypes cant remove components like maps

**Comment by deltanedas** [comment]
also doesnt make sense to store admin smite target on a gamerule anyway since after the objective initializes its never used again

**Comment by slarticodefast** [comment]
Closing this since exterminators got completely removed.
