### ISSUE TITLE
PKA should be moved to cargo

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#24326]
Remove from science too. Make it like $1k or $2k or something.

**Comment by K-Dynamic** [comment]
Cargo gaming

Soon cargo will be free from the tyranny of (lazy) science

**Comment by deltanedas** [comment]
pka is shit anyway crusher gaming

**Comment by EmoGarbage404** [comment]
conflicts with https://docs.spacestation14.com/en/space-station-14/departments/cargo-salvage/proposals/salvage-proposal.html so we should just do what it says here instead.
