### ISSUE TITLE
Right-clicking randomly becomes unavailable and actions in HUD disappears 

### ISSUE THREAD

**Issue by MeowVal** [space-wizards/space-station-14#24338]
## Description
As from the title, the HUD actions randomly disappear together with the ability to right-click or shift right-click after playing for long enough, though the right-clicking still functions where you are standing but as soon as you move your cursor outside that area it stops working, and does not even prompt anything. This can be temporarily fixed with the command /resetallents

**Reproduction**
Play on the same server for a couple of rounds or more without the client closing/relogging on the server. 

**Additional context**
Mostly happened to me while playing in the medical department, possibly because of my frequent use of right-click action.
Was using the experimental performance option when experiencing the problem and connecting to the US west/east server from Northern Europe.

**Comment by K-Dynamic** [comment]
I feel that's tied with the bug where you suddenly appear to be dead

**Comment by MeowVal** [comment]
possible as I sometimes also appear to be dead when I have that bug other times I appear as being dead after using the command /resetallents

**Comment by MeowVal** [comment]
Most likely related[ #23715](https://github.com/space-wizards/space-station-14/issues/23715) as mentioned above. Just now find it and it's very similar to my issue.
