### ISSUE TITLE
SCRAM implant shows "3 uses" in uplink, while only 2 uses are on the actual implant.

### ISSUE THREAD

**Issue by deepdarkdepths** [space-wizards/space-station-14#24332]
![image_2024-01-20_050457945](https://github.com/space-wizards/space-station-14/assets/155149356/4ab63a97-82f6-4377-b139-12db7b845980)
![image_2024-01-20_050504129](https://github.com/space-wizards/space-station-14/assets/155149356/634fc95d-779d-48c3-a6a6-a69d1f0391c3)

**Comment by Ilya246** [comment]
it was originally 3-use so i probably forgot to change it
