### ISSUE TITLE
Current PR restrictions

### ISSUE THREAD

**Issue by DrSmugleaf** [space-wizards/space-station-14#24346]
Merged with https://github.com/space-wizards/space-station-14/issues/8524

**Comment by deltanedas** [comment]
> woundmed coming

:rocket:

**Comment by keronshb** [comment]
Moved Wizard and Magic back to Freezes

**Comment by DrSmugleaf** [comment]
Moved to https://github.com/space-wizards/space-station-14/issues/8524
