### ISSUE TITLE
Not Tile varnish (not Decals)

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#2436]
In SS13, the way coloring tiles is handled is via an individual tile type for each variant.
For example, on /tg/, the tiles that line the halls of each department have a line of tiles on the edge colored by that department's color. Each variant needed is an extra tile type, which is unwieldy.
Alongside that, there are a _lot_ of these variants, as there's a lot of different ways map makers may want to color tiles.

In SS14, it's fully possible to both make it even easier for map makers to decorate the map, and to greatly cut down on the number of tile texture variants that need to exist, and the way I propose to do this is via a tile painting/varnishing functionality.
I propose attaching a 4x4px 255+1 color (255 colors and full transparency/no color) texture to each tile. This is pretty cheap, 4KiB per 16x16 chunk of tiles, and has the ability to be quite performant (blit the tile color data into a texture in VRAM, overlay that texture at some transparency level with the tile map. No entity overhead, no overhead from a large number of small textures in VRAM)
Even extremely large maps aren't particularly big with this idea. A 512x512 map that fills every single chunk with data would need 4MiB of tile varnish data in total.

Oh, yea, someone assign this to me.

Difference from decals: Decals are 32x32 textures you slap over the tiles, and they're pre-fabbed.
This is basically setting tints for the underlying tile with an extremely low resolution texture (4x4px, 256 colors), it doesn't let you add, say, caution stripes over a tile, it tints the tile it's on top of.

**Comment by ElectroJr** [comment]
Is this still something that would be useful, or do the decals (#5183 & #6548 ) just make this issue redundant?

**Comment by moonheart08** [comment]
They make it redundant.
