### ISSUE TITLE
puddles draw over t-ray

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#24378]
## Description
terahertz rays blocked by 1u of blood :trollface:
![21:22:08](https://github.com/space-wizards/space-station-14/assets/39013340/b1b87e58-c9ab-4f94-b1b8-27b48d6066ea)

**Comment by Nopey** [comment]
I feel like directly clicking with t-rays can already feel pixel searchy (especially for Pipes), and so would like to mention: you can interact with the entities via the right click menu with the same shortcuts as the entity in the world.

This is vital knowledge for the janitor who need to mop up the blood from under Cargo's newly grown tree (true story)

**Comment by Krunklehorn** [comment]
Carpets still do this as well.
