### ISSUE TITLE
Movement sprite state activates on pressing walk button

### ISSUE THREAD

**Issue by MilenVolf** [space-wizards/space-station-14#24387]
## Description
Title describes the issue.

**Reproduction**
Press walk button while standing still. Or if you use toggle walk setting just press walk button once and movement animation will play.

**Screenshots**

![Content Client_85ILnagEAa](https://github.com/space-wizards/space-station-14/assets/63782763/8e7e64ff-9d12-4a36-aa70-01d279ad5871)

**Comment by Krunklehorn** [comment]
Isn't this kind of unique and cool though? You can pretend to tap dance! We just got mothroach animations too...
