### ISSUE TITLE
Brains can point

### ISSUE THREAD

**Issue by Veritius** [space-wizards/space-station-14#24384]
what.

**Comment by Kadeo64** [comment]
it's funny
also lets you know if a brain is still connected because brains don't show SSD status

**Comment by Ilya246** [comment]
feature

**Comment by K-Dynamic** [comment]
Wouldn't it make sense to put a SSD or soul indicator on the brain?

**Comment by Hmeister-real** [comment]
> Wouldn't it make sense to put a SSD or soul indicator on the brain?

MMI shows if the brain is catatonic or not with the texture, so it is already checked. Probably easy to do

**Comment by deltanedas** [comment]
> MMI shows if the brain is catatonic or not with the texture, so it is already checked

source trust me bro?

ive always had to rely on pointing / putting in random brain and greeting them

**Comment by Kadeo64** [comment]
> > MMI shows if the brain is catatonic or not with the texture, so it is already checked
> 
> source trust me bro?
> 
> ive always had to rely on pointing / putting in random brain and greeting them

if the MMI has eyes then it's not catatonic (still can be yellow SSD), but if the MMI has no eyes then it's fully catatonic and should be sold at cargo.

**Comment by Ilya246** [comment]
the MMI description should explicitly tell you whether it has a soul

**Comment by Kadeo64** [comment]
> the MMI description should explicitly tell you whether it's catatonic

okay but the actual brain doesn't which is bad since most people don't have an MMI on standby
