### ISSUE TITLE
Electrified grille/fence using lv/mv cable does zero dmg

### ISSUE THREAD

**Issue by IamVelcroboy** [space-wizards/space-station-14#24399]
Electrifying grilles and/or fences with lv ~~or mv~~ cable no longer shocks or damages the player. 

https://github.com/space-wizards/SS14.Launcher/assets/107660393/48c7ce7a-42a1-49aa-8157-2d6e7bec6180
![image](https://github.com/space-wizards/SS14.Launcher/assets/107660393/0b4f7c83-bd76-4e4e-9a7d-dee55d154c29)

Can be reproduced by setting up grille or fence with lv ~~or mv~~ cable underneath, (hv cable still works,) and walking into it. Zero zappo.

**Comment by IamVelcroboy** [comment]
Update: MV and HV both work now. However LV still does nothing.
 
https://github.com/space-wizards/space-station-14/assets/107660393/ed561fe4-f6fc-4789-a897-13fd8d3e68c2

**Comment by Varen** [comment]
As of #24829 , damage is based on how much electricity goes through the cable. You won't be damaged by any wire that has less than 30kw going through it.
In other words: The LV going up to a few lamps won't be dangerous, the science one powering a bunch of high power machines will.

**Comment by IamVelcroboy** [comment]
> As of #24829 , damage is based on how much electricity goes through the cable. You won't be damaged by any wire that has less than 30kw going through it. In other words: The LV going up to a few lamps won't be dangerous, the science one powering a bunch of high power machines will.

OK, I see. I'll have to test some more. Thanks for the clarification.

**Comment by IamVelcroboy** [comment]
Ok, looked into this more and I do see that it was fixed as stated above.
