### ISSUE TITLE
Table mapping issue

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#2443]
You can "rotate" walls and tables and other `IconSmooth` entities while mapping with middle-mouse click. You can do this accidentally and be stuck with broken tables/walls etc. and not know what the issue is. **VERY FRUSTRATING ALERT.**

![Content Client_2020-10-29_12-47-22](https://user-images.githubusercontent.com/49448379/97624923-b224da00-1a1f-11eb-9473-a2fe2f34a018.png)

**Comment by Zumorica** [comment]
I wonder, would the solution here be force all entities with IconSmooth be forced to rotation angle 0, or fix IconSmooth so it works with different directions?

**Comment by moonheart08** [comment]
Fixing iconsmooth seems like the better option, due to plans for shuttle rotation.

**Comment by moonheart08** [comment]
But at the same time, maybe change the entity editor to restrict rotation angle on tables/walls/etc anyways.
