### ISSUE TITLE
Wheelchairs are cursed

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#24433]
## Description
I don't know a better title as it seems like several issues, I don't have reproductions but aHelp relay is always getting help calls for people bugging out in wheelchairs.
These are some of the following i have witnessed and players have reported via aHelp:
- Disappearing wheelchair:
    > Unsure of cause, but testing it, The wheel chair essentially goes non visible to everyone, it still exists as a server entity and I was able to TP it to my ghost which brought it back in to visible existence.
- Viewport centers on chair instead of body.
    > This was seen after a person in a wheelchair was stunned causing their screen to freeze then the camera/viewport centered on the chair instead of where they were else where in the station
- Players can attach a bunch of items/entitys on to the outside of the chair to bypass inventory
    > Last seen a hydro put 200 light emitting eggs on to the outside of the chair, funny, but still bug. Similar to #20629

**Reproduction**
I Don't have any, can update this if there are comments with it.

**Screenshots**
NA

**Additional context**
NA

**Comment by Titian3** [comment]
Here is a example of the entities attached to the chair 246 on there:
![image](https://github.com/space-wizards/space-station-14/assets/47093363/771d8b67-fa55-458e-86ce-b62fafd6cc0c)

**Comment by metalgearsloth** [comment]
https://github.com/space-wizards/space-station-14/pull/24681

no more mech + vehicle + cardboard box split.
