### ISSUE TITLE
https://github.com/space-wizards/space-station-14/pull/24381 needs reviewing

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#24447]
- Entites is spelt wrong
- There's a bunch of ToArrays which shouldn't be there
- Use DataRecord
- Don't use properties unless you need them
- There's a bunch of copy-paste between entity and tile anomalies, both for the records and for the spawning logic is entirely copy-paste with comments.

**Comment by VasilisThePikachu** [comment]
#24449 now
