### ISSUE TITLE
Hot platers still broken

### ISSUE THREAD

**Issue by Ilkepro** [space-wizards/space-station-14#24460]
## Description
Hot plates are broken and unable to heat anything.

**Reproduction**
Using the Hot plate

**Screenshots**
None since its not needed

**Comment by EmoGarbage404** [comment]
Fix was already merged

**Comment by thebadman4662** [comment]
Seemed to not work still, unless 4h after merge was still not enough for Leviathan to update and even now people report hotplate not doing anything.

**Comment by EmoGarbage404** [comment]
Servers havent updated yet

**Comment by Ilkepro** [comment]
People said the fix was merged earlier today and I saw salamander get a update earlier but it still wasnt working

**Comment by EmoGarbage404** [comment]
The last publish was 9 hours ago.
