### ISSUE TITLE
Morgue can cremate out of nothing, creating ash out of thin air. It can also cremate with the door open.

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#2446]
![2020-10-29_16-42-20](https://user-images.githubusercontent.com/49448379/97643718-659dc680-1a40-11eb-8d85-19cf5e60ea6e.gif)

**Comment by SweptWasTaken** [comment]
![image](https://user-images.githubusercontent.com/49448379/97643865-b6152400-1a40-11eb-8f3a-b0ccd7badd60.png)

You can also not cremate multiple loaves of cream cheese bread at the same time.

**Comment by Markek1** [comment]
I fixed the "ash being created out of nothing" issue by putting the for loop that destroys all items and adds ash, into an if statement that checks if the number of contained entities is > 0.

I fixed cremating being allowed while the crematorium is open by putting `if (Open) return;` at the start of `Cremate()`

Number of items that can enter the crematorium when closing depends on the assigned capacity in morgue.yml.

**Comment by Markek1** [comment]
#2473

**Comment by RemieRichards** [comment]
Sorry, never got the email for this.
(@SweptWasTaken ping me next time aswell please)
