### ISSUE TITLE
Arrivals should prio before cryo

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#24470]
It's a 2 line change to order the events, I got too much stuff to do otherwise I'd throw it up.

**Comment by Emisse** [comment]
Ideally it should be an option in customization

**Comment by deltanedas** [comment]
or be based off if you used cryo to delete yourself last round :trollface:

**Comment by metalgearsloth** [comment]
> Ideally it should be an option in customization

client cvar or server, either case you'd need to unify the spawning then and check it.

**Comment by Krunklehorn** [comment]
Ahh, was just about to ask. I'll see what I can do.
