### ISSUE TITLE
Navmap strings not loading properly

### ISSUE THREAD

**Issue by Krunklehorn** [space-wizards/space-station-14#24487]
## Description

Works for some, but not others.

**Screenshots**

![SS14 Loader_oVZlqZkRb4](https://github.com/space-wizards/space-station-14/assets/42424291/36845d70-b726-4f51-93dc-6b83eddaa91c)

**Comment by Errant-4** [comment]
I feel my sins crawling on my back

**Comment by jessicamaybe** [comment]
happened to me on salamander on packed
![image](https://github.com/space-wizards/space-station-14/assets/31836813/3fc6ff05-d7df-4941-a316-220a988cd415)

**Comment by Errant-4** [comment]
If anyone gets this issue again, can you please
- confirm with another player if they also see the bug at the same time
- get me the round number (you can see it on your PDA)

**Comment by Errant-4** [comment]
> Okay so here goes.

This was useful, thank you. Some of it confirms what I expected, some of it is giving me ideas.
Somehow it fails to localize at roundstart. As expected, this impacts all players. Then, even more puzzlingly, it somehow decides to localize later. It's only set to do that on mapinit

However that happens, it should not be possible for it to break a _second time_. If you ever positively confirm that has happened, definitely let me know

**Comment by Errant-4** [comment]
This issue is obsolete after #26713 . We get a different bug now that the code is completely different

Recommend closing
