### ISSUE TITLE
Entity ID Standardization 

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#2452]
Entity IDs are all over the place so I thought it would be prudent to get a standard to follow.

The current entity spawner window indexes by both name and ID, so if you searched up "Belt" everything with both belt in the name and ID would show up. This could be a bug or a feature, but I think making IDs very verbose could work in our favor with this system.

Having IDs like `ClothingBeltSecurity` or `WeaponGunPistol1911` is the kind of verbosity i'm suggesting. It would mean easier indexing by both users, admins and devs.

Obviously updating all the IDs in our content repo with this proposed standard would be pretty tedious but it's easy to do and can be done in the web editor so some ~scrubs~ new contributors could do it.

If we decide on something i'll writeup an issue like [the description one](https://github.com/space-wizards/space-station-14/issues/1596). (Although there is a slight risk that their PRs won't build due to entities missing in the map file.

**Comment by SweptWasTaken** [comment]
Assigned myself to this, #2539 is an example of it if anyone want's it.

**Comment by AJCM-git** [comment]
We decided that entities IDs would use PascalCase and most of the prototypes follow this
