### ISSUE TITLE
Beds make people sleep sideways

### ISSUE THREAD

**Issue by Carmell0** [space-wizards/space-station-14#24563]
## Description
I'm sure you've seen it. People in beds are at a 30 ish degree angle rather than laying flat
**Reproduction**
Buckle yourself to a bed, that's it

**Screenshots**
Will add later

**Additional context**
This has been in the game for like 2 months idk if someone has a PR to fix it but I can't find one.

**Comment by Kadeo64** [comment]
only one person has attempted to fix it and they disappeared off the game so i dunno if it's getting fixed any time soon

**Comment by bhenrich** [comment]
i'll take a look at it
