### ISSUE TITLE
Cargo Techs Are Taking The Sales Computer to Shuttle

### ISSUE THREAD

**Issue by Admiral-Obvious-001** [space-wizards/space-station-14#24578]
## Description

This is probably due to be addressed eventually but cargo techs seem to currently be removing the sales computers from the trade station and then moving it to the shuttle itself, selling bounties within the shuttle due to the fact that the shuttle still has pallets.

**Reproduction**

Take shuttle console from the trade station, install it on the shuttle (optionally next to a request computer) and you never need to go to the trade station again.
**Screenshots**

**Additional context**

This can probably be fixed my making cargo pallets a fixed map fixture and then remove them from the shuttles themselves.

**Comment by 0awful** [comment]
Is there a mechanism for a computer requiring access to a specific power grid to function?

Imagine a power grid monitoring computer for example. This could be connected to any power grid but shouldn't monitor any other grid.

If that mechanism exists we could use that same paradigm for cargo computers, needing to be on a trade station power grid to function.
