### ISSUE TITLE
Captain sword is too small

### ISSUE THREAD

**Issue by thebadman4662** [space-wizards/space-station-14#24573]
Sword sheath is no longer capacity/grid based belt but rather a slot one like combat boots so sword will fit now no matter the size. 2x2(Which I assume is how many sloths sheath gave when it was grid) is simply too small for such big item so I believe it makes sense to make it 2x4 or 4x4 like esword for example.

**Comment by Brandon-Huu** [comment]
Yeah but it's captain so its fine.

**Comment by deltanedas** [comment]
also related cap laser is 1x2 now (which would be ~10 size before) it should be bigger

**Comment by GreyMario** [comment]
cap laser is pistol shaped (2x2 3 tiles)

**Comment by thebadman4662** [comment]
Cap sword got nerfed into glorified cleaver so its fine I guess.
