### ISSUE TITLE
Chatbox Accessibility

### ISSUE THREAD

**Issue by SpaceyLady** [space-wizards/space-station-14#24587]
At the moment the chatbox is transparent so can be difficult to see the messages with things in the background of the chatbox blending in. 

![adcsf](https://github.com/space-wizards/space-station-14/assets/76712456/63a410d9-b313-43df-95a7-495ea87c7908)
 Current chatbox as you can see the text is difficult to read due to the objects and sprites in the background.

Fix: Add an option to either toggle full opacity on the chatbox or add a slider option for transparency to be 0-100% in the accessibility options in game.

**Comment by QuietlyWhisper** [comment]
Is this what you're looking for?
![image](https://github.com/space-wizards/space-station-14/assets/121047731/8368a2b0-501e-4b61-9545-c877684271a5)

**Comment by SpaceyLady** [comment]
Yes but still toggleable in the default layout and perhaps with a way to slider it from 0-100% opacity.

**Comment by deathride58** [comment]
>Is this what you're looking for?

There are genuine accessibility reasons why separated UI isn't desirable for some players; separated isn't at all what Spacey's asking for.

**Comment by UbaserB** [comment]
![image](https://github.com/space-wizards/space-station-14/assets/134914314/d8d1745e-4d57-4112-85d8-09975ad7d657)
I feel like there needs to be a border around the text, this blends in way too far and hurts my eyes
