### ISSUE TITLE
Admin logs missing from syndicate sponge transformations

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#24605]
## Description
When a syndicate sponge is watered there are no logs for the spawned mob, I've checked the player that made the spawn, the cube, or the new mob entity. 
It would be nice to have this information for when trying to track down where a mob has come from.
As seen in the screen cap of logs, it logs the transformation from the wrapped to unwrapped but not to the mob transformation from cube to mob.

**Reproduction**
- Water a syndicate sponge/Syndicate monkey cube
- Witness no logs

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/47093363/7419f4f3-8262-41ad-9551-092132a57c34)

**Additional context**
Unsure if worth but if Variant cube is the new default chef meat cube box should this sponge box also be variant cube box sprite to prevent metagaming the syndicate version by sprite.

**Comment by deltanedas** [comment]
same for fish
