### ISSUE TITLE
Window in Marathon medbay blocks table

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/space-station-14#24632]
![image](https://github.com/space-wizards/space-station-14/assets/8107459/956df549-6013-428b-a278-4eb2c78fda2e)

Just remove all the windows in this room, they're dumb.

**Comment by deltanedas** [comment]
agreed i hate windows in treatment rooms i usually break or deconstruct them

**Comment by Krunklehorn** [comment]
Anybody else deconstruct the center wall too? ✋

**Comment by K-Dynamic** [comment]
Marathon med has some other quirks like a single private patient room all the way at the bottom of med, as well as a whole psychiatric ward with a mre vendor and sec elements

**Comment by UbaserB** [comment]
@Emisse did you fix it

**Comment by PJB3005** [comment]
Entire medbay was remapped here so this is fixed.
