### ISSUE TITLE
Mouse rotator is cooked

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#24636]
Thought I made an issue but apparently not.

Either way it doesn't work most of the time and is entirely dependent upon grid rotation.

https://github.com/space-wizards/space-station-14/assets/31366439/f584cdde-f9b1-4459-8ec5-d83e014264ee

**Comment by deltanedas** [comment]
sometimes it only flips between left and right sprites when spinning, along with using map-based rotation
