### ISSUE TITLE
Action bar randomly deletes your actions and will "reorganize" your inventory as a result

### ISSUE THREAD

**Issue by deepdarkdepths** [space-wizards/space-station-14#24686]
Unable to properly reproduce as this seems to happen without warning/indication and about 1-3 times a round. Cannot find what triggers it. If this happens to me again I will attempt to capture a recording of it
1. Play game as normal
2. If an action is custom(such as storage implant and helmet toggle), might notice that its gone. Only the defaults such as scream, combat mode toggle, etc remain.
3. This also results in your inventory being reorganized. For example, my belt in one round had all its items shuffled. It is only when I put one of my tools back in the belt that everything moved back to their original places. 

I have a feeling this might be related to the "random death" bug, but it's just a guess.
Using command "resetallents" fixed it, similar to fixing the death bug.

Edited for further clarity.

**Comment by VasilisThePikachu** [comment]
#20483 ??

**Comment by GreyMario** [comment]
I can verify that inventory strangeness is itself an issue, and I believe it didn't happen _alongside_ actions being removed. It's probably the same _root cause_ overall though, especially if resetallents can fix the bugged inventory.

**Comment by Hanzdegloker** [comment]
The inventory getting bugged out issue has been happening to me, quite annoying. To a lesser extend the actions being removed bug likewise. both issues tend to happen after I have had been playing for a while.

**Comment by Anzarot121** [comment]
As far as we understand at Corvax, this is partly due to the sound system. If there are too many sources, then things in the inventory, walls, and the action panel begin to disappear. I was also almost shot by sec because I was not visible to them and seemed to appear out of thin air.

**Comment by deltanedas** [comment]
recently im getting openal errors saying out of memory and slowly all the sounds stop playing (swap was being ravaged at the time but it still shouldnt say out of memory or the whole thing would crash probably)

**Comment by metalgearsloth** [comment]
> As far as we understand at Corvax, this is partly due to the sound system. If there are too many sources, then things in the inventory, walls, and the action panel begin to disappear. I was also almost shot by sec because I was not visible to them and seemed to appear out of thin air.

Does anyone have any logs that it's state handling failing elsewhere or is this spitballing.

**Comment by metalgearsloth** [comment]
Also this is the same bug yeah.
