### ISSUE TITLE
Pressing shift while following a ghost will drop you off

### ISSUE THREAD

**Issue by VasilisThePikachu** [space-wizards/space-station-14#24713]
## Description

Cant repeatedly point at an among us plushie while following an admin

**Reproduction**

1. Follow headmin OliverOtter (I'm saying this to spite them :3)
2. Point at linux plushie while screaming "LINUX"
3. You get dropped off the ghost

**Screenshots**

**Additional context**

**Comment by Tayrtahn** [comment]
Dupe of #23918, fixed by #24715

**Comment by VasilisThePikachu** [comment]
Amogus
