### ISSUE TITLE
Gift events no longer function due to new cargo/Trade station

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#24729]
## Description
The normal gift events either triggered by admin or default event scheduler no longer work. 
Which I assume has to do with the method for packs arriving to station has changed to trade station instead of on next delivery warp from trade warp point.
Prevents the 10 gift event types in screenshot below

**Reproduction**

**Screenshots**
After calling the gift event, and it not showing up.
![image](https://github.com/space-wizards/space-station-14/assets/47093363/5c62a797-76e4-4140-95e4-a21eafcfd020)

The autofill list for the gift events types affected.
![image](https://github.com/space-wizards/space-station-14/assets/47093363/f3e4dcde-ef51-4142-b7a5-38f28b3ab15a)

**Additional context**
NA

**Comment by themias** [comment]
Should be fixed by #24701, but keep an eye on it when it gets patched to the servers.

**Comment by GoodWheatley** [comment]
Fixed by #24701
