### ISSUE TITLE
Cargo can just make trade station inside cargo.

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#24732]
## Description
A extension of this issue #24578 cargo techs can just rip up the pallets and bring in the computer and start selling at the front desk. 💸 

**Reproduction**
- Move Cargo sale computer and some pallets in to easy place for cargo to sell.
- Profit

**Screenshots**
Example in lobby of cargo: 
![image](https://github.com/space-wizards/space-station-14/assets/47093363/c194e366-5be1-4c55-8235-d0a96f3463d3)

**Additional context**
If money is involved they always find a more efficient way.

**Comment by Kadeo64** [comment]
step one: make it impossible to unanchor selling platforms/computer
step two: profit (less efficiently)

**Comment by Geekyhobo** [comment]
> step one: make it impossible to unanchor selling platforms/computer step two: profit (less efficiently)

This, and station anchors are coming

**Comment by lzk228** [comment]
already fixed
