### ISSUE TITLE
Some midi's cause epic lag

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#24740]
## Description
On a recent game, I noticed when I came close/ in audio range to a musician playing midis, it would lag immensely to the point the client locks up.
They were playing in band mode by them self, a piano and sax. I asked the player about the midis they were using in particular they mentioned it was a ported midi from another file type but had very high note counts, they mentioned 80K notes vs normal ones are in the hundreds. Maybe some midi guru can validate this, I have no idea.

I did a basic performance test just with task manager, screenshot, asked them to play then could see/feel the lag and watch my cpu go to max, then when they stopped, back to normal right away. In other parts of the song it was CPU maxed out until moving out of range or the song calms down a bit.
I was able to get some of the mid files for some of the songs from them and was able to replicate the bad lag locally.

**Reproduction**
- Get a piano and sax
- Start playing on the piano with the High note count midi (attached)
- Join band with the sax

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/47093363/fd6b30bd-69df-436b-b53f-c801d5cbff6c)

**Additional context**
I got a few Midis for testing with the attached one letgo.mid the one I used in local testing. If someone actually works on this I have a couple more if required.
[letgo_midi_test.zip](https://github.com/space-wizards/space-station-14/files/14101669/letgo_midi_test.zip)

**Comment by Kadeo64** [comment]
Midis cause MASSIVE performance issues, and it's been this way for a few months now. I'm of the opinion that midis should be completely disabled until the code is fixed/optimized since midis didn't use to lag this much. Also, if a musician is playing extremely laggy midis, tell them to stop. If they don't stop, it's your god-given right to beat their shit in with a toolbox.

**Comment by PJB3005** [comment]
https://github.com/space-wizards/RobustToolbox/commit/7275302639bec52ca18fbec244c2710c1e20477d should massively help with this, but I have another change coming up.

**Comment by VasilisThePikachu** [comment]
Engine changes have been merged to upstream and it seems like it has improved on stuff. Closing this

**Comment by VasilisThePikachu** [comment]
wrong close button but it works
