### ISSUE TITLE
Can't vault in low atmos

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#2474]
I assume because the atmos controller touches you it essentially prevents you from vaulting if you're in a depressurised area unless you spam it a lot.

Ideally there'd be some kind of threshold before it's cancelled.

**Comment by ShadowCommander** [comment]
Hm, would be cool to just allow people in zero-g to just float over VaultImpassable things, but still have them act as a hand hold like players are to other players.

**Comment by AJCM-git** [comment]
This is caused by atmos damage in low atmos. Superseded by #5203
