### ISSUE TITLE
Overlapping trees prevent direct attacks

### ISSUE THREAD

**Issue by thebadman4662** [space-wizards/space-station-14#24750]
## Description
Trees from floral anoms love to grow inside walls so you can't do anything about them without tearing it down, if you want to hit something directly behind tree from your camera POV you will be attacking tree in wall which you can't hit for obvious reasons.

**Reproduction**
Put 2 trees, one of them in wall, attack one not in wall 1 tile north.

**Comment by TheShuEd** [comment]
Fixed in #24783
