### ISSUE TITLE
Add borg console

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#24751]
High priority for admins you probably get maintainer or something.

Needs:
- Access lock.
- Ability to view borgs remotely (surveillancecameracomponent).
- Ability to disable / kill borgs remotely.

**Comment by Emisse** [comment]
context for this is either getting this soon or disabling borgs until AI is added

**Comment by deltanedas** [comment]
emagging should make the borg able to control its disabling/boom so it can fake tasks and suicide bomb like a boss

**Comment by Zap527** [comment]
Why isn't the current iteration of borgs fine?

**Comment by K-Dynamic** [comment]
> Why isn't the current iteration of borgs fine?

Probably something about them being too independent and creating admin headache because they either disobey orders or troll via announcements

**Comment by Kadeo64** [comment]
> Probably something about them being too independent and creating admin headache because they either disobey orders or troll via announcements

\>be shitter
\>get borged after execution (executed for mass shittery)
\>now you have AA and a full set of tools 
\>"but you need to follow your laws!!"
\>nothing mechanically preventing you from ignoring your laws and welderbombing/deconstructing walls/shocking doors/breaking generator
\>"but you'll get bwoinked!!"
\>do you think shitters care about bwoinks?
\>stun immunity so sec needs to arm lethals for a single borg

**Comment by deltanedas** [comment]
or as how the roboticists do, use a baseball bat on malf/shitter borg

**Comment by Kadeo64** [comment]
> or as how the roboticists do, use a baseball bat on malf/shitter borg

jaws of life 4 life

**Comment by Zap527** [comment]
Ok but can someone in the loop give us insight here? I haven't seen much discussion about borgs being problematic at all, so this is coming out of the blue for me.

**Comment by Kadeo64** [comment]
> Ok but can someone in the loop give us insight here? I haven't seen much discussion about borgs being problematic at all, so this is coming out of the blue for me.

borgs aren't usually problematic but I guess there has been an uptick in borg-related ahelps lately (due to certain people) so admins want a way for people to instantly destroy problematic borgs

**Comment by Zap527** [comment]
This could be it, but I'd rather wait for a maintainer to confirm whats going on before jumping to conclusions.

**Comment by deltanedas** [comment]
i might try it:

1. should the console be usable at all by sci readonly or just rd
2. should bodycam thing be in the console as a button separate window or on camera monitors
3. if on console should bodycam require access
4. when disabled should the button become enable or should it only be enable-able in person

**Comment by FungiFellow** [comment]
> 1. should the console be usable at all by sci readonly or just rd
> 2. should bodycam thing be in the console as a button separate window or on camera monitors
> 3. if on console should bodycam require access
> 4. when disabled should the button become enable or should it only be enable-able in person

1. The Surveillance should be accessible by All Science with only RD being able to use the Killswitch
2. Console as seperate window
3. Should Require Science Access
4. Might be easiest to just have it pop out the MMI/Posi

Theres a Variety of ways to disable it which consist of
1. Explode it 
2. Crit it (Apply Damage via Console but not enough to break it)
3. Eject the Brain (I find this the Funniest option)

Emagged Borgs should be able to Toggle their Surveillance and ignore the killswitch

**Comment by metalgearsloth** [comment]
> i might try it:
> 
>     1. should the console be usable at all by sci readonly or just rd
> 
>     2. should bodycam thing be in the console as a button separate window or on camera monitors
> 
>     3. if on console should bodycam require access
> 
>     4. when disabled should the button become enable or should it only be enable-able in person

1. Only matters that killswitch / disable is RD, rest can be whatever..
2. Maybe button so it opens in same window to the side like crew monitor. Easiest is probably separate console that is borg only if the bodycam PR is good enough.
3. Yes, at least science.
4. Should be enable and disable remotely.

IMO.

**Comment by LordEclipse** [comment]
> > 1. should the console be usable at all by sci readonly or just rd
> > 2. should bodycam thing be in the console as a button separate window or on camera monitors
> > 3. if on console should bodycam require access
> > 4. when disabled should the button become enable or should it only be enable-able in person
> 
>     1. The Surveillance should be accessible by All Science with only RD being able to use the Killswitch
> 
>     2. Console as seperate window
> 
>     3. Should Require Science Access
> 
>     4. Might be easiest to just have it pop out the MMI/Posi
> 
> 
> Theres a Variety of ways to disable it which consist of
> 
>     1. Explode it
> 
>     2. Crit it (Apply Damage via Console but not enough to break it)
> 
>     3. Eject the Brain (I find this the Funniest option)
> 
> 
> Emagged Borgs should be able to Toggle their Surveillance and ignore the killswitch

In this case, events like Ion storm, and hacking, amongst other potential ways, should also disable/remove a borgs remote camera as well, just so that a borg mysteriously vanishing from the display isn't instantly valid.

**Comment by tutoumi** [comment]
for the question of the accessibility of the console, make a roboticist job and let the console be usable only by roboticists and RD. less peoples to potentialy blow up the borgs because they want to.

**Comment by deltanedas** [comment]
only rd can blow up borgs not scientists
