### ISSUE TITLE
Add syringe gun

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#24773]
Got bikeshedded to not be stupidly overpowered, just needs syringes to embedded projectiles and be instantly removeable and only inject after a delay so it's not a free-win gun.

**Comment by Tayrtahn** [comment]
EmbeddedProjectileComponent has an EmbedOnThrow field for exactly that reason.

**Comment by deltanedas** [comment]
replace tranq shells with little syringes to shoot into animal :trollface:

**Comment by hord-brayden** [comment]
Very interested in this development - Would it also share the component/whitelist arrows and various ammo have, to limit their use in PnemoCannons? Additionally expanding the thought to the other types: cryosyringes, bluespace, would those need be included in the component or whitelist or explicitly omitted?

**Comment by deltanedas** [comment]
bluespace syringe gun after 2 seconds inject 1000u into bloodstream :trollface: :trollface: :trollface: :trollface:

**Comment by metalgearsloth** [comment]
It should just use pneumatic cannon code and where not possible split out because they're both identical in terms of functionality.

**Comment by Flareguy** [comment]
Closing since syringe guns are added (#32112.)
