### ISSUE TITLE
Antag role ban isn't working

### ISSUE THREAD

**Issue by 13lackHawk** [space-wizards/space-station-14#24781]
## Description
Well, it just isn't working.

**Reproduction**
Try to ban someone.
Choose any antagonist role or all of them.
Watch errors in console.

**Screenshots**
https://imgur.com/a/VfhMWH8

**Additional context**
Let me ban bad antags, please!

**Comment by metalgearsloth** [comment]
Antag bans don't exist.

**Comment by 13lackHawk** [comment]
> Antag bans don't exist.

Ehm... is that Corvax-only stuff? I was pretty sure antag bans were added in the game like 6-8 months ago.
