### ISSUE TITLE
Add CM to CMO's locker

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#24787]
Discussed and having 1 on station is fine.

If sci really want one it needs to be nerfed to shit.

**Comment by Emisse** [comment]
no this just means theyll give it to paramed roundstart

**Comment by deltanedas** [comment]
wrong again

what will happen is following:
- cmo will not give paramed their monitor
- cmo will not look at monitor for the entire round with 10 ghosts booing medical

**Comment by Ilya246** [comment]
colonial marines in CMO's locker let's go
