### ISSUE TITLE
secure crates doesnt show lights layer while open

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#24797]
![Screenshot_20240131_164958](https://github.com/space-wizards/space-station-14/assets/124214523/18598615-5138-40de-8c59-8b464e708b08)

**Comment by themias** [comment]
Looks like it works this way for all secure crates and is intended.
I assume it is this way since it doesn't matter if it is locked when it's already open, and you can't lock it when it's open.

**Comment by lzk228** [comment]
edited name

**Comment by Tayrtahn** [comment]
It would be simple enough to change, but it's definitely intentional.

```c#
args.Sprite.LayerSetVisible(StorageVisualLayers.Lock, !open);
```

https://github.com/space-wizards/space-station-14/blob/84c5057bb53eeabd308be364d968831d6feb124d/Content.Client/Storage/Visualizers/EntityStorageVisualizerSystem.cs#L80C13-L80C74
