### ISSUE TITLE
Trade station can spawn inside space wrecks

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#24798]
## Description
The trade station can seemingly spawn on top of other space grids and get stuck.

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/106507028/2f202591-2ea9-4604-b986-55780392f515)

![image](https://github.com/space-wizards/space-station-14/assets/106507028/9b6e738e-cf9b-4149-a506-5e9b0f22be4a)

**Additional context**
Sloth mentioned it might have something to do with ftl proximity

**Comment by UbaserB** [comment]
which round i want to see this

**Comment by Emisse** [comment]
ruins not wrecks

**Comment by Kayek14** [comment]
> which round i want to see this

This was Leviathan 45348

**Comment by metalgearsloth** [comment]
Is this still an issue

**Comment by Kayek14** [comment]
This issue seems to be resolved. I nor the adminteam have heard or seen this happening in months.
