### ISSUE TITLE
Flora anomaly stuff spawns in walls

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#24795]
![Screenshot_20240201_020639](https://github.com/space-wizards/space-station-14/assets/124214523/8ba6e995-8579-44fb-b38e-93be5b11b52d)
![Screenshot_20240201_022251](https://github.com/space-wizards/space-station-14/assets/124214523/e66a36e2-84d9-45b8-8d31-17d5c04e17a7)
i couldnt remove that fucking kudzu without some adminbuse

**Comment by TheShuEd** [comment]
Fixed in #24783
