### ISSUE TITLE
Anomaly can choose ghost as target

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#24796]
1. be ghost around pyro anomaly
2. get anomaly-ghostbuster

![Screenshot_20240201_000137](https://github.com/space-wizards/space-station-14/assets/124214523/fc5e01aa-dc75-4506-bbaa-31cff9f259a2)

**Comment by Ilya246** [comment]
aghosts or any ghosts

**Comment by lzk228** [comment]
dunno but pretty sure any ghosts

**Comment by lzk228** [comment]
seems fixed
