### ISSUE TITLE
Establish an API for Content Repositories

### ISSUE THREAD

**Issue by clusterfack** [space-wizards/space-station-14#248]
**Motivation**
Since we have established that the code in this repository is meant to solely be an engine for the game servers, we have created a separate content repository which includes the engine code as a submodule. But if we immediately start adding code to the content repository we will quickly encounter two problems

1. Spaghetti/Coupling 
2. Compatibility issues

We want to reduce to the smallest amount the coupling between the engine and content code, therefore we need a stable unchanging API that the content server can access, and that the engine code can implement.

Pictorally
![](https://cdn.discordapp.com/attachments/310555209753690112/326802011628765185/unknown.png)

**API**
The API needs (essentially) to be able to recreate most of what we could do in byond code right now using the base functions byond provides. Some examples

**(A note to collaborators feel free to edit this list if people add more useful suggestions for what we need to implement)**
Location
- Find objects within a set radius (bounds?)
- Find overlapping objects (bounds?)
- Find visible objects in a radius (view)
- Find all objects in a radius (range)

Collision
- Behavior for objects when they begin to overlap
- Behavior for objects when they stop overlapping
- Behavior for objects when they collide
- Behavior for objects on when they should collideable or not

Movement
- Moving something
- Moving something disregarding collision behavior
- Testing whether something could move without actually moving
- Some A* behavior might be useful to put on the backend instead of frontend as well

Lighting
- Get amount of light at a location
- Make an object a light
- Change lighting values on an object
- Removing light behavior from an object

**Comment by clusterfack** [comment]
I forgot to say this in my initial post but we need people to brainstorm what should be included into the API so we can make a fairly exhaustive list and solidify it.

**Comment by theOperand** [comment]
Is it possible that looking at other games with a similar (usually modding) system (such as KSP) might be useful to determine functions that are needed here?

**Comment by PJB3005** [comment]
I doubt it, since most of the API we'd be looking at would be similar to BYOND or SS14 specific.

**Comment by PJB3005** [comment]
Linking this since it hasn't been yet: https://docs.google.com/document/d/1Nd3eXlgi0jMj1ZsUWTWLyP7xKtbsWqTvS_68spQW46U/edit?usp=sharing

**Comment by optimumtact** [comment]
make sure you version your api

**Comment by clusterfack** [comment]
@optimumtact that's the idea, changes to the API are probably going to come in various major releases of the engine. Bugfixes and such are in minor releases which should be mostly compatible, and then any content repositories can point their engine to any version release.

**Comment by PJB3005** [comment]
Just use semver.

**Comment by clusterfack** [comment]
No duh, you idiot

**Comment by Acruid** [comment]
Because of the design process of this game, it is not possible to plan out the entire Content API beforehand. The main gateway between Content and Engine are the services in the IoCManager.  If somebody needs specific API functionality added to those, please open a new issue specifically about it.
