### ISSUE TITLE
Mirrors not working

### ISSUE THREAD

**Issue by 13lackHawk** [space-wizards/space-station-14#24812]
## Description
Yup.

**Reproduction**
Spawn a mirror.
Try to use it.
Cry because you can't.

**Additional context**
It might be intended because of adding scissors but then it seems that changing your look now is pretty hard now because you can't craft those scissors and its pretty hard to find.

**Comment by Kadeo64** [comment]
> **Additional context** It might be intended because of adding scissors but then it seems that changing your look now is pretty hard now because you can't craft those scissors and its pretty hard to find.

I have been able to use a mirror to change my hair after the scissors update came out so i'm like 75% sure that's not the problem. Needs more testing.
