### ISSUE TITLE
Biochemistry discipline is bad.

### ISSUE THREAD

**Issue by Kadeo64** [space-wizards/space-station-14#24832]
# The Problem
Biochemical is just bad. It doesn't really have anything interesting going for it. Out of the limited selection of Biochemical researches, there are exactly two relevant ones; chemistry tier 1 for the Liquid Anomaly Analyzer 4000 (chem goggles) and Mechanical Treatment for medical borgs. Maybe biofabrication if you want to do some meme gimmick like flooding the kitchen with mice cubes. 
 
Biochemical has always been.. uninteresting since cloning was removed, but now with the chem dispenser change I would say Biochemical is just terrible now. Most of Biochemical is just stuff medical has mapped round-start, like stasis beds, cryo, and surgical tools. Salvage is capable of finding all of the interesting stuff science is supposed to research anyway (Specifically extra stasis beds, cryostasis beakers, and bluespace beakers). 

Chem Dispensers USED to be a good enough reason to research Biochemical, however now chem dispensers are just reskinned booze dispensers which, are a civilian tier 1 unlock. 

## The (potential) Solutions
Adding more of the ~~unbalanced garbage~~ [fun gear from ss13](https://tgstation13.org/wiki/Research_items#Medical_Designs) to Biochemical would help make Biochem less useless. Stuff like the polymorph belt, bluespace bodybags, implants, and the oh-so coveted **[syringe gun](https://github.com/space-wizards/space-station-14/issues/24773)**. 

One of the best places to start might be implants, as right now the crew doesn't really have any useful implants besides tracking. Adding researchable implants like the welding shield, the various hud glasses, and the toolset arm would definitely add unique spice to Biochemical. There is already a [PR for creating implants](https://github.com/space-wizards/space-station-14/pull/23759), however it uses chemistry, and I don't get how certain implants would be designed around requiring chemicals.

### The Nuclear Option
The worst case scenario for Biochemical, is that the discipline gets nuked entirely. I've heard this suggested a few times but it's not exactly been an appealing concept. Basically, Biochemical gets removed and all of it's relevant researches spread across Experimental and Civilian. In the long term this is probably a pretty bad idea.

**Comment by deltanedas** [comment]
could have an unlimited chem dispenser in a t3 (and make chem dispenser/master boards roundstart since they dont do anything special and are roundstart)

**Comment by EmoGarbage404** [comment]
Unlimited chemicals for t3 is completely overpowered and ludicrous.

**Comment by deltanedas** [comment]
except that:
- bluespace beaker as a t3 is completely useless with finite chems, they can be found by salvage anyway
- if you are going to lock yourself out of ***bags of holding***, **microreactor cells**, **teleporter** and the validhunting stuff you should get something good and not a total joke, something that med will beg for every round and usually not get. but when they do get it it changes the round, like with teleporter

**Comment by EmoGarbage404** [comment]
Getting to invalidate chemical balance in a consistent manner doesn't create more interesting gameplay. It just shatters balance for little concrete gain. At least just make a medibeam or something so it doesnt have balance considerations outside of healing

**Comment by Hmeister-real** [comment]
> could have an unlimited chem dispenser in a t3 (and make chem dispenser/master boards roundstart since they dont do anything special and are roundstart)

Maybe a chem dispenser that replenishes basic chems at 1u a second? effectlvely infinite but it would take a while to refill

**Comment by Kadeo64** [comment]
> 30u tricord every 5 seconds for **a tier 3**

honestly seems balanced, gives medical an infinite way to heal minorly wounded patients while more roughed up patients get better treatment via the limited chems and advanced meds. Stops medical from wasting bruise packs on people with 20 blunt.

**Comment by deltanedas** [comment]
> gives medical an infinite way to heal minorly wounded patients while more roughed up patients

medibot pre impending nerf :trollface:
