### ISSUE TITLE
Shift-clicking while being held as a mothroach makes you start escaping

### ISSUE THREAD

**Issue by jessicamaybe** [space-wizards/space-station-14#24847]
## Description
Not sure if it happens while you're a mouse or hammy, but that probably shouldn't be happening. I think only movement keys should trigger the escape.

**Comment by metalgearsloth** [comment]
Rotating shouldn't trigger ghostonmove sounds like.

**Comment by jessicamaybe** [comment]
Ok actually I was wrong actually all you have to do is hold shift and you start trying to escape, you don't have to click

**Comment by metalgearsloth** [comment]
That would be walk modifier triggering inputmover events then.

**Comment by Emisse** [comment]
same fix as shift making you stop ghost orbiting bug probably

**Comment by Tayrtahn** [comment]
Yep, it's the same as both of those. I'll PR a fix.
