### ISSUE TITLE
Thief Communicator's Kit Has No Crew Monitor

### ISSUE THREAD

**Issue by Kezu02** [space-wizards/space-station-14#24843]
## Description

Either someone forgot to edit the description or it wasn't supposed to be removed from the kit.

**Comment by EmoGarbage404** [comment]
description wasn't edited.

**Comment by metalgearsloth** [comment]
Is that this kit https://github.com/space-wizards/space-station-14/pull/24768

**Comment by Kadeo64** [comment]
> Is that this kit #24768

that kit is for syndies, this issue is talking about [the voicemask kit](https://github.com/space-wizards/space-station-14/blob/59733412365ce4baee2389755f61691697b6f44a/Resources/Prototypes/Catalog/thief_toolbox_sets.yml#l82)
