### ISSUE TITLE
revs can spill jugs

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#24861]
## Description
had a shitter just go into med spill jugs then defile for the rest of its life its terrible

**Comment by UbaserB** [comment]
this tbh

**Comment by Anzarot121** [comment]
Wait. Weren't you the one who told me this was a planned feature?
https://github.com/space-wizards/space-station-14/issues/21554#issuecomment-1804892683

**Comment by QuietlyWhisper** [comment]
the solution is to not leave jugs of medicine everywhere imo

**Comment by Kadeo64** [comment]
> the solution is to not leave jugs of medicine everywhere imo 

where else are they supposed to go? there's no fridge to put the jugs in

>(why the fuck can revs spill things)

because revenants are really annoying

**Comment by Kadeo64** [comment]
> i would be fine with spilling if it made them corporeal so if they go on a shitter spree med has some recourse

what if chaplain could see revenants all the time and was alerted when one spawned? bonus points if bible banishes revenant (removing all of their points and abilities, if they get hit with no points they get round removed)

**Comment by Anzarot121** [comment]
> > i would be fine with spilling if it made them corporeal so if they go on a shitter spree med has some recourse
> 
> what if chaplain could see revenants all the time and was alerted when one spawned? bonus points if bible banishes revenant (removing all of their points and abilities, if they get hit with no points they get round removed)

Please no. Revenant is already the weakest antagonist. He needs a buff, not a nerf. You literally can hit him one time with crossbow and he disintegrate.

**Comment by thebadman4662** [comment]
> Solution: fix the chem fridge already

But chem dispensers are already a thing? What is it if not a chem fridge once you empty it out of basic reagent jugs?

**Comment by deltanedas** [comment]
its possible to make ghetto smart fridge but i have only personally seen it done once (by me) and its still no reason for rev to be able to do this in complete safety
