### ISSUE TITLE
Evac docking alerts could be improved using beacons

### ISSUE THREAD

**Issue by Krunklehorn** [space-wizards/space-station-14#24867]
Along with cardinal directions, evac docking failures could do a distance check to the nearest two beacons and get their names for the output.

Ex.
"The evacuation shuttle has docked to the Northwest, near Bridge / Medical."

**Comment by K-Dynamic** [comment]
They should really give coordinates too and park for an extra minute longer when warped away from station

**Comment by slarticodefast** [comment]
Fixed by #28164
