### ISSUE TITLE
Emags break deployable barrier

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#24860]
## Description
On emagging a deployable barrier there is a the zap text for unlock but it stays in the locked position but then it becomes not interactable, even

**Reproduction**
- set a deployable barrier up so its locked with a mob with access.
- Emag it.
- Try and unlock with the non access mob, or drop your id card
- attempt to unlock it with a mob/card that should have access

**Screenshots**
NA

**Additional context**
First report I'm hearing of this. Most likely a side effect from the recent update for deployable barrier to now have a doafter bar to lock/unlock.

**Comment by IProduceWidgets** [comment]
This might be intended since the alternative is a barrier you can't repair and can't lock.
