### ISSUE TITLE
Grilles OP

### ISSUE THREAD

**Issue by Everturning** [space-wizards/space-station-14#24879]
## Description
Description to Grille:
> A flimsy framework of iron rods

Actual Grille:

Sure, reinforced glass can break in like 5 hits with a moderate damage source. But a "flimsy" framework of iron rods? Yeaahhhh that'd be 10+ hits eaasy without any doubt. 

**Reproduction**
Break glass w/ grill under using fireaxe in three hits
Slap grille with fireaxe
Slap grille with fireaxe
Slap grille with fireaxe
Slap grille with fireaxe
Slap grille with fireaxe
Slap grille with fireaxe
Slap grille with fireaxe
Break in to where you were trying to break into 8 minutes ago

**Screenshots**

**Additional context**

**Comment by deltanedas** [comment]
i will nerf grille fuck grille ops

**Comment by Holinka4ever** [comment]
It will sound like diablo immortal announcement, but guys, you dont have wire cutters?

**Comment by deltanedas** [comment]
if a pair of sharp bits of metal can remove a grille in half a second surely a big strong sharp metal blade can cleave through it in a hit or two
