### ISSUE TITLE
Clown meals empty

### ISSUE THREAD

**Issue by Carmell0** [space-wizards/space-station-14#24873]
## Description

Happy honk meals, woeful cluwne means, nukie meals, and mime meals all have nothing in them aside from the toy
**Reproduction**

Go to vender
Click on happy honk meal
Open happy honk meal
Despair as it's empty save for figurine

**Comment by GreyMario** [comment]
I don't see how this is an issue; it just means it's up to the chef to fill up the boxes with whatever he likes.

**Comment by deltanedas** [comment]
thats how it has always been
you put in the food then give to someone

**Comment by mirrorcult** [comment]
its intended, you're supposed to put stuff in them
