### ISSUE TITLE
mice are eating paper

### ISSUE THREAD

**Issue by Kadeo64** [space-wizards/space-station-14#24893]
## Description

self explanatory
**Reproduction**

spawn maus and paper
**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/108914677/663c0c11-978f-4e53-8160-b26ceecf027c)

**Additional context**

funny but also bad

**Comment by deltanedas** [comment]
BadFood ops

**Comment by Tayrtahn** [comment]
https://github.com/space-wizards/space-station-14/blob/master/Content.Server%2FNutrition%2FComponents%2FBadFoodComponent.cs
