### ISSUE TITLE
Bartender 300u jugs are treated like beakers

### ISSUE THREAD

**Issue by thebadman4662** [space-wizards/space-station-14#24896]
## Description
You can get triple capacity beakers by yoinking jugs from bartender and using them for chemisty, this includes electrolyze, not just chemmasters and dispensers.

**Reproduction**
Get a jug, insert a jug.

**Screenshots**
![obraz](https://github.com/space-wizards/space-station-14/assets/152504929/749e1ee9-2251-475d-89be-a681b5945021)

**Comment by Hanzdegloker** [comment]
Interestingly, chem jugs cannot go into the booze dispenser or soda dispenser as I tried with a jug of meth just a day ago

**Comment by IProduceWidgets** [comment]
I think this is because the booze/soda dispenser is intended to accept bottles.
