### ISSUE TITLE
Throwing needs decoupling from hands

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#24891]
From https://github.com/space-wizards/space-station-14/pull/23996

This isn't the way to force the landtime you want.

**Comment by slarticodefast** [comment]
Fixed in #29726
I removed the bandaid stuff checking for the hands.
https://github.com/space-wizards/space-station-14/pull/29726/files#diff-b1e4188faa74f0cdb7bb2005aa4a22a61a6c272fb8599227b3eb76f0ca00f92aR174-L148

**Comment by Plykiya** [comment]
wtf I love throwing code now
