### ISSUE TITLE
Configuration Menu adds a "Namotion" dependency for reflection.

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#2490]
This dependency NEEDS to be removed. Content may NOT use reflection at all, unless it does so via the `IReflectionManager` dependency.

**Comment by juliangiebel** [comment]
Can you assign this to me?

**Comment by DrSmugleaf** [comment]
Fixed by https://github.com/space-wizards/space-station-14/commit/a7e7f20417bb9a39f14b3c37c0b62d37a5f31760
