### ISSUE TITLE
Sec glasses and all other job/role icon seeable in dark

### ISSUE THREAD

**Issue by gordod3** [space-wizards/space-station-14#24905]
## Description
Sec, Med glasses and role icon like revo or zombie seeable in dark placeses.

**Video**

https://github.com/space-wizards/space-station-14/assets/59264914/c4fd6a0a-cb11-44c7-b17c-6910af2e1cd8

https://github.com/space-wizards/space-station-14/assets/59264914/1cd89db6-89a3-4025-a8c9-805a578085a8

**Additional context**
It's like nightseeing glasses what makes hiding in dark just pointless or vice versa zombie and revo can be more confident when know how much they and where they in dark room.

**Comment by gordod3** [comment]
Don't get it - how .mp4 works here? Why one video working correctly, other needing go in other tab. . .

**Comment by Tayrtahn** [comment]
I think you'll need to reupload it and keep a blank line above it. For some reason, taking that blank line out breaks the embed.

**Comment by deltanedas** [comment]
need newlines around the link

**Comment by Krunklehorn** [comment]
I think this is intentional. The glasses are responding to the ID in your PDA which, although slotted, is considered clearly visible at all times. If you put it in your backpack, I'm pretty sure you go invisible again.

**Comment by GreyMario** [comment]
> I think this is intentional. The glasses are responding to the ID in your PDA which, although slotted, is considered clearly visible at all times. If you put it in your backpack, I'm pretty sure you go invisible again.

Kid called "No ID" icon:

**Comment by gordod3** [comment]
> I think you'll need to reupload it and keep a blank line above it. For some reason, taking that blank line out breaks the embed.

Thanks.

**Comment by gordod3** [comment]
> I think this is intentional. The glasses are responding to the ID in your PDA which, although slotted, is considered clearly visible at all times. If you put it in your backpack, I'm pretty sure you go invisible again.

It's absurd when glasses can't see in the dark but see id(or wheres "no id") also revo and zombie can somehow see in the dark where's the friends.

**Comment by PrPleGoo** [comment]
this is not intentional for the HUDs, there are some icons that just need displaying even when in darkness (downstream) so it was never changed to support both cases
