### ISSUE TITLE
pulling is completly fucked

### ISSUE THREAD

**Issue by potato1234x** [space-wizards/space-station-14#24900]
## Description

pulling is completly fucked

**Reproduction**

grab something
someone grabs it away from you (presumably)
game considerers you pulling that object and does not stop until round end
grabbing the object again does nothing, rejoining does nothing, clicking the pull icon does nothing

**Additional context**

only just started happening last server restart

**Comment by Just-a-Unity-Dev** [comment]
Might be related to #20906

**Comment by deltanedas** [comment]
another issue, if the thing you are pulling gets deleted (e.g. you push it into a chasm) you stay pulling it and hud dies

**Comment by thebadman4662** [comment]
1. Stop pulling hotkey no longer works.
2. When you stop pulling things the get stuck in your hand, you will need to quickuse another item with bugged hand selected.
3. When someone pulls something and you take it into backpack they will not stop pulling which causes both players to be stuck with eachother till item is again on ground, perhaps if pulling player stops doing it they also get released(mime was not nice enough alas).

**Comment by metalgearsloth** [comment]
> 2. When you stop pulling things they get stuck in your hand, you will need to quickuse another item with bugged hand selected.

Steps to repro?

**Comment by thebadman4662** [comment]
Its reverted for now but I was playing med and it made reviving people extremely annoying as I would have 2 diffetent players "in my hands" preventing me from picking up and/or using defibs...

**Comment by metalgearsloth** [comment]
okay but how do you reproduce it.

**Comment by thebadman4662** [comment]
Try putting people on rollerbed or into bodybags I guess?
