### ISSUE TITLE
Movement isn't constant

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#2492]
Possibly related to Acruid's issue #1261 

tl;dr is that if you're moving in a constant direction your speed oscillates up and down 0.05 units which I don't think it should do?

```
[DEBG] root: LinearVelocity dirty as (7.0282106, 0)
[DEBG] root: LinearVelocity dirty as (6.971044, 0)
[DEBG] root: LinearVelocity dirty as (7.0282106, 0)
[DEBG] root: LinearVelocity dirty as (6.971044, 0)
[DEBG] root: LinearVelocity dirty as (7.0282106, 0)
[DEBG] root: LinearVelocity dirty as (6.971044, 0)
[DEBG] root: LinearVelocity dirty as (7.0282106, 0)
[DEBG] root: LinearVelocity dirty as (6.971044, 0)
```

If you fix then bandwidth savings as you don't need to send physics state updates to the client every tick which is a big win.

**Comment by metalgearsloth** [comment]
Main reason to change is that you can get bandwidth savings not sending the state every tick for physics which is big.

**Comment by mirrorcult** [comment]
@metalgearsloth is this fixed?

**Comment by metalgearsloth** [comment]
Movement code is the same so I doubt physics branch fixed it but I'd need to re-investigate if it still happens.

**Comment by metalgearsloth** [comment]
Pretty sure it was fixed when I was logging movement
