### ISSUE TITLE
a holoparasite doesn't share harm with its host

### ISSUE THREAD

**Issue by icekot8** [space-wizards/space-station-14#24940]
## Description

A holoparasite can block all blows to its host with its body, making it simply immortal if the holoparasite is a professional. I believe that the holoparasite must transmit damage to the host. 
That doesn't seem fair or right. Any syndicate can just take a holoparasite being a dwarf and that one becomes immortal, since the holo hides the entire hitbox...
**Reproduction**

1. inject yourself with a holoparasite
2. take control of the holoparasite and put it in the trajectory of shots (the holo in the game has tremendous speed, it won't be difficult)
3. try shooting yourself in the third person.

**Screenshots**

![изображение](https://github.com/space-wizards/space-station-14/assets/93311212/a07a1672-54c4-432d-8114-ff08be333a80)
demonstration of desynchronization of a holoparasite and its host
![изображение](https://github.com/space-wizards/space-station-14/assets/93311212/e4eddcef-29bb-4edf-9836-91252b19ba95)
![изображение](https://github.com/space-wizards/space-station-14/assets/93311212/f04aeb98-380c-45ba-98f5-c147d5110708)
(melee attacks rarely go through)

**Comment by K-Dynamic** [comment]
To clarify, did you shoot your own holo as the holo user or have another mob shoot your holo

**Comment by icekot8** [comment]
> To clarify, did you shoot your own holo as the holo user or have another mob shoot your holo

I didn't quite understand the question. I injected a holo into myself, started dragging it and moving it to fit the trajectory of the shots, then entered the aghost and tried to do damage to the host, but nothing worked.
I think in general the problem can be solved if the holo shares damage with the host.

**Comment by K-Dynamic** [comment]
> I didn't quite understand the question. I entered the holo, started dragging it and moving it to match the trajectory of the shots, then entered the agghost and tried to deal damage to the host via the holoparasite, but it didn't work. I think in general the problem can be solved if the holo shares damage with the host.

Yeah that's weird then, holos are meant to share damage with host

**Comment by slarticodefast** [comment]
Fixed by #26541
