### ISSUE TITLE
Remove some LINQ

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#2494]
Linq as a one-off in a few areas is okay for code that is run rarely, but some stuff that gets called frequently has a lot of chained linq queries which isn't ideal. I've removed the ones that showed up at the top of the memory profiler but there's still some one-off ones hidden around that aren't cheap.

**Comment by Ygg01** [comment]
How would you search for LINQ queries?

**Comment by RemieRichards** [comment]
search the codebase for known LINQ methods, `Select()`, `SelectMany()`, `Where()` etc.

**Comment by brndd** [comment]
Possible alternative: look for `using System.Linq`

**Comment by RemieRichards** [comment]
That's good, but I wouldn't be surprised if we're importing LINQ in places it isn't used.

last I checked our imports are messy

**Comment by SweptWasTaken** [comment]
I checked in memory profiler and in my in-experienced eyes they seem to be negligible. Checked with Sloth and he said it's alright to close this.
