### ISSUE TITLE
Insuzine is underpowered

### ISSUE THREAD

**Issue by thebadman4662** [space-wizards/space-station-14#24950]
Despite being advanced burn chem its inferior to Derma as of course carbon bottleneck strikes again. Either derma needs to finally get a nerf or Insuzine needs to have benzene out of recipe, its bad enough that its a niche chem, being worse is just a final nail in the coffin.

**Comment by Arendian** [comment]
Kelotane is the basic burn chem and dermaline is already the advanced anti-burn chem.
Insuzine is a specialized anti-shock chem that heals shock 2.7x more per u and 2.7x as fast.
You only need 12u(OD limit) of insuzine to heal 96 shock damage.
10u(OD Limit) of dermaline only heals 30 shock.

**Comment by thebadman4662** [comment]
Derma OD does not really kick in till you use 40u though, at 120shock in one go you most likely treated it all.

Insu is doing way worse in carbon economy because of benzene.

**Comment by deltanedas** [comment]
recipe for insuzine and pyrazine were made with unlimited chems in mind, feel free to tweak if they are too heavy on carbon

**Comment by TokenStyle** [comment]
Did it. Made PRs
