### ISSUE TITLE
Event shipments never arrive on ATS

### ISSUE THREAD

**Issue by MissKay1994** [space-wizards/space-station-14#24955]
Whenever the game triggers an event shipment such as emergency pizza or janitor supplies, these shipments become stuck in the que on cargo request computers, and never arrive on the ATS. This happens any time one of the NanoTrasen shipment events occur

![20240124220202_1](https://github.com/space-wizards/space-station-14/assets/15877268/21590257-39f0-4ee9-84be-38379e002a94)

![20240127053809_1](https://github.com/space-wizards/space-station-14/assets/15877268/8a833e7e-98c4-4ce1-9d3b-b3aeccc62404)

**Comment by deltanedas** [comment]
dupe
