### ISSUE TITLE
Event subscriptions

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#2497]
Most stuff that uses BoundUserInterface subscribes to OnReceiveMessage but they never unsubscribe which seems like it'd cause a memory leak?

**Comment by metalgearsloth** [comment]
Now that I think about it, should BoundUserInterface have its own component to manage it like containers too? That way components can care less about the logic like they currently they and can just listen for component messages instead maybe?

**Comment by Zumorica** [comment]
> Now that I think about it, should BoundUserInterface have its own component to manage it like containers too?

That would be `UserInterfaceComponent`!

> That way components can care less about the logic like they currently they and can just listen for component messages instead maybe?

That sounds good to me, honestly.

**Comment by metalgearsloth** [comment]
This should also cover off power as well which is another one.

AFAIK the GC won't ever collect it if it's still subscribed.

**Comment by ElectroJr** [comment]
BUI stuff can use ECS events now.
