### ISSUE TITLE
Pirate Accent capitalization issue

### ISSUE THREAD

**Issue by TurboTrackerss14** [space-wizards/space-station-14#24996]
## Description
Pirate Accent will de-capitalize the first character sent. 

**Reproduction**
have pirate accent 
sent capitalized message
first character will be uncapitalized

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/130304754/15464cb8-fd83-4698-b55a-151b3587a9f3)

**Additional context**

**Comment by UbaserB** [comment]
Nearly forgot that this actually applies to all accents that have the same feature.
