### ISSUE TITLE
Bullet Proof Janitor Mop Buckets

### ISSUE THREAD

**Issue by PoorMansDreams** [space-wizards/space-station-14#24992]
## Description
The Janitor mop bucket can tank an unknown (possibly infinite) amount of bullets.

**Reproduction**
Shoot a Janitor mop bucket with an L6

**Comment by TurboTrackerss14** [comment]
free confirmation/reproduction video 
Holy christ its uh, yeah its a tanky lil bugger aint it. 
https://github.com/space-wizards/space-station-14/assets/130304754/9524ad72-30c2-4292-89a5-02e1d8a0b4e7

**Comment by vero5123** [comment]
should be an ez fix most likely, just look at the entity in the yml file.
