### ISSUE TITLE
Thief can be asked to steal non-existing mob

### ISSUE THREAD

**Issue by Varen** [space-wizards/space-station-14#25009]
## Description
Get asked to steal Bingus. Floppa spawned instead of Bingus from the cat spawner. Sadness ensues.

**Reproduction**
Be a thief on a map with variable cats and have one as objective.

**Additional context**
Happened to me on round 45822 on Salamander.

**Comment by Emisse** [comment]
steal objective needs to know if map has the objectives on it basically, this can let us have more unique steal objectives as well if implemented

**Comment by deltanedas** [comment]
could just iterate every mob and check if its prototype matches the objective, for mobs
would be better if there was a steal objective component then the query is much much faster and supports non-mobs, which would be even slower without it

**Comment by metalgearsloth** [comment]
> check if its prototype matches the objective

If you do prototype ID checks I will murder you.

**Comment by deltanedas** [comment]
guess what steal obj does :trollface:
