### ISSUE TITLE
Brig timer label display broke

### ISSUE THREAD

**Issue by nikthechampiongr** [space-wizards/space-station-14#25024]
## Description

Brig timers will not display inputted labels unless they were mapped with that label.

If they were mapped with a label, then if a timer is started then the time will display on top of the label which will be unreadable.

Timers additionally refuse to cancel. The only way to cancel them is to input a lower time and start the timer again.

**Reproduction**

- [ ] Scenario a:

1. Start Timer
2. Try to cancel it
3. It doesn't work and now your prisoner is stuck for the next 300 years.

- [x] Scenario b:

1. Input label
2. Label does not update
3. Cry

- [x] Scenario c:

0. Be on atlas where brig timers by default are labelled.
1. Start timer
2. Watch as it remains a garbled mess until it finishes. 

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/32041239/a2514dee-caf4-48e5-a589-0fdf9988ee0a)

**Additional context**
 

C.C.TextScreenSystem Seems to not properly handle brig timers.

**Comment by nikthechampiongr** [comment]
Apparently just making sure the key entered in the appearancecomponent is a string and not a string array fixes scenario c and b.

**Comment by nikthechampiongr** [comment]
Reopening because scenario a is still outstanding.

**Comment by graevy** [comment]
> Reopening because scenario a is still outstanding.

hey is this still an issue? it's my fault; i refactored for the hallway screens.

**Comment by nikthechampiongr** [comment]
> > Reopening because scenario a is still outstanding.
> 
> hey is this still an issue? it's my fault; i refactored for the hallway screens.

Most likely yea.

**Comment by graevy** [comment]
i'll take a look at it, thanks for reopening

**Comment by graevy** [comment]
> > > Reopening because scenario a is still outstanding.
> > 
> > 
> > hey is this still an issue? it's my fault; i refactored for the hallway screens.
> 
> Most likely yea.

do you want a cancel button or to just click on the existing timer label and have it cancel the timer

**Comment by nikthechampiongr** [comment]
> do you want a cancel button or to just click on the existing timer label and have it cancel the timer

I personally think a single button is nicer but you should do whichever you prefer.
