### ISSUE TITLE
The nuke instead of destroying everything, should fragment the station into several chunks and push away

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#25035]
## Description

I just suddenly had this idea out of nowhere. Instead of demolishing everything immediately, considering that we are in space the station would likely push apart with immense force and fling in all directions at tremendous speed. Of course there would still be a lot of destruction around the area the nuke exploded, but this would be a cool idea to implement. It would also allow for people to RP out surviving in remnants from the nuke. Maybe even have an in-built EMP effect to shatter all lights and kill power from the huge explosion.

Yes, the current way would make lots of sense on a planet or something, but we’re on a goddamn space station floating in space.

**Screenshots**

![IMG_2597](https://github.com/space-wizards/space-station-14/assets/134914314/7f4da353-9c80-4636-bc8e-bb20a03cb615)

**Comment by EmoGarbage404** [comment]
ideaguysing in my github issues smh

**Comment by UbaserB** [comment]
> ideaguysing in my github issues smh

isnt that what the feature requests tag is called

**Comment by metalgearsloth** [comment]
> > ideaguysing in my github issues smh
> 
> isnt that what the feature requests tag is called

For stuff that should be implemented rather than bikeshed.

The github issues should be trimmed at some point but bikeshedding ones are never gonna get done.

**Comment by UbaserB** [comment]
> > > ideaguysing in my github issues smh
> > 
> > 
> > isnt that what the feature requests tag is called
> 
> For stuff that should be implemented rather than bikeshed.
> 
> The github issues should be trimmed at some point but bikeshedding ones are never gonna get done.

fair

**Comment by metalgearsloth** [comment]
Also as to why:
- Nuke does a lot of explosive damage and is inherently going to destroy entities / tiles. You'd either need to make an entirely new system to fracture it, then explode later (probably looks bad) or that can somehow spread tiny explosions that do almost no damage. Either way is a lot of work for a small feature.
