### ISSUE TITLE
Admin Logs for Recycler Gib

### ISSUE THREAD

**Issue by Keer-Sar** [space-wizards/space-station-14#25036]
**Is your feature request related to a problem/bug? Please describe.**
There is no bug or problem. This is a QOL request for the admin logs.

**Describe the command you'd like**
There is no Gib log for players who are gibed by an Emag'd recycler.

**Additional context**
Example: 
![image](https://github.com/space-wizards/space-station-14/assets/144283718/2d349334-2b79-442d-8acb-2cba2518181a)

**Comment by deltanedas** [comment]
this isnt toolshed

**Comment by deltanedas** [comment]
just the normal issue report, that was for feature requests for toolshed scripting
