### ISSUE TITLE
Cargo Trade Station Guidebook entry doesnt show up on the guidebook

### ISSUE THREAD

**Issue by Hmeister-real** [space-wizards/space-station-14#25044]
## Description
I tried hotfixing it and it did nothing, i am lost on what to do to make it appear.

**Comment by veliebm** [comment]
Hi. Could you please provide some more context? Ideally, please follow this template:

```
## Description
<!-- Explain your issue in detail. Issues without proper explanation are liable to be closed by maintainers. -->

**Reproduction**
<!-- Include the steps to reproduce if applicable. -->

**Screenshots**
<!-- If applicable, add screenshots to help explain your problem. -->

**Additional context**
<!-- Add any other context about the problem here. Anything you think is related to the issue. -->
```

I think I might be able to help you, because I spent all last night working on guidebook stuff so it's fresh in my mind, but I need more info first.

**Comment by deltanedas** [comment]
you need to add it as a parent to the cargo section yml

**Comment by veliebm** [comment]
^^
if that's what you're asking about, you can use [my PR](https://github.com/space-wizards/space-station-14/pull/25040) as a reference. i also recommend reading [the page](https://docs.spacestation14.com/en/general-development/tips/writing-guidebook-entries.html) on the developer wiki about writing guidebook entries
