### ISSUE TITLE
Quantum Inverter deletes its twin when placed in storage implant

### ISSUE THREAD

**Issue by ThatOneGoblin25** [space-wizards/space-station-14#25056]
The title. Placing a Quantum Spin inverter into a storage implant and activating with destroy its pair and anything it was stored with (eg in crate with stuff). The original one is still paired to a now deleted link and just teleports the player to 0,0 when used after cool-down.

Reproduction, see video:

https://github.com/space-wizards/space-station-14/assets/145570657/acca4396-2d49-4622-aeb8-adebdbbb4d56

**Comment by ThatOneGoblin25** [comment]
Little testing before I sleep at 2am. They are basically discount holoparasites now. Entities and players quantum teleported into the storage implant can still interact with the map if in close proximity, including grabbing weapons and attacking nearby or the implant holder themselves. If the person with the storage implant gets gibbed it also causes a client crash. 
![Screenshot 2024-02-09 013511](https://github.com/space-wizards/space-station-14/assets/145570657/f4e33673-d1c8-4439-8ad4-72372e31621d)

**Comment by Kadeo64** [comment]
ss14 mythbusters: how many people can you fit in a single storage implant
