### ISSUE TITLE
Nettle sprites need to be improved

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#25052]
## Description

The nettle sprites are really blurry and poorly off-centered in your hands. There's literally transparent pixels on the edges too.

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/134914314/9f621575-5c20-44b5-a412-8bc26ba2ea64)

![image](https://github.com/space-wizards/space-station-14/assets/134914314/a85af3ee-d53d-4830-b631-28f00a2c8681)

**Comment by muburu** [comment]
even the nettle's hydroponics growth sprites are blurry like that, those definitely need a resprite as well
