### ISSUE TITLE
Yield mutation can't get above 5

### ISSUE THREAD

**Issue by mehx3** [space-wizards/space-station-14#25100]
## Description
Looking at the code "max" yield is supposed to be 10, but probability of yield increasing at 5 yield is 0%.
`MutateInt(ref seed.Yield                  , 3    , 10  , 5, totalbits, 2 * severity);` (where min yield is 3, max yield is 10, and bits is 5)
`float probIncrease = 1 - (float)val / bits;` (1 - 5/5 = 0)

**Additional context**
MutateInt method in general is broken, i believe, and is used only in yield mutation for some reason. Replacing it for MutateFloat should fix the problem, as it rounds up values anyway. Any plant with 6 yield is guaranteed to go down if yield mutates also.

**Comment by slarticodefast** [comment]
Resolved by #27210
