### ISSUE TITLE
WarOp

### ISSUE THREAD

**Issue by Aisu9** [space-wizards/space-station-14#25105]
## Description
When Nukies go for a WarOp, there is a surge of players Ghosting/Suiciding/Dying/Cryo

**Additional context**
When a WarOp happen(or just from the beginning of Nukie rounds), remove the ability from people that manually ghost/suicide/die/cryo to take a ghost role until10 minutes after the end of the additional preparation time granted by WarOp
(Basically allowing only the **observers** to take ghost roles)

**Comment by VasilisThePikachu** [comment]
Duplicate off one of the requests in #20064
