### ISSUE TITLE
Update ContainerHelpers to use new extension

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#2510]
Since this PR https://github.com/space-wizards/RobustToolbox/pull/1389 instead of writing

`ContainerHelpers.IsInContainer(Owner)`

we can now write

`Owner.IsInContainer()`

This should be updated across the codebase for all the ContainerHelpers extensions.

**Comment by Jackw2As** [comment]
This issue is now solved by #2530, correct? So it should be closed.

**Comment by Zumorica** [comment]
Correct.
