### ISSUE TITLE
pirate_start.ogg samples a part from the Sid Meier's Pirates! official soundtrack

### ISSUE THREAD

**Issue by MACMAN2003** [space-wizards/space-station-14#25111]
## Description

I don't know how to explain this in detail, it literally samples the music. It's a blatantly obvious copyright violation.
**Reproduction**

listen closely at "55:19" in the video https://youtu.be/FMUJgzMYLqw?t=3319 and then listen to pirate_start.ogg
**Screenshots**

n/a
**Additional context**

n/a

**Comment by jamessimo** [comment]
Thought this was already addressed last year in https://github.com/space-wizards/space-station-14/issues/21869

**Comment by UbaserB** [comment]
> Thought this was already addressed last year in #21869

im pretty sure thats related to ss220 not sid meier's pirates official soundtrack lol

**Comment by PoorMansDreams** [comment]
Uh Oh! it DOES. 
I scrapped this together with no copyright audio, 
https://soundcloud.com/user-983755196/ss14-pirates-quieter-beeps-more-arrrg?si=d9df3630fa4343469c6e5a52818468c4&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing

**Comment by PoorMansDreams** [comment]
attempt to fix with [#25111](https://github.com/space-wizards/space-station-14/pull/25153)
