### ISSUE TITLE
Logic gate broken

### ISSUE THREAD

**Issue by PowerKAT1** [space-wizards/space-station-14#25125]
## Description
When trying to block the gateway at the beginning of the round (using Logic gate (using NOR)), I ran into a very interesting problem - when initializing the card, Logic gate does not check its state. As an example, NOR gives 1 at 0 0 (Below is a screenshot for clarity). But either it issues this signal during card initialization, or it does not check its status after card initialization. Because of this, it is almost impossible to use them - you must give a signal to them so that they start working.

**Reproduction**
Create any logical element on the map (for example, XOR) and make sure. that he is obliged to give a signal at the very beginning. connect it to something that should switch the state (light bulb). When initializing the card, Logic gate will not change its state until any signal is given to it (for example, from a button).

**Screenshots**
![image (2)](https://github.com/space-wizards/space-station-14/assets/53919050/c41c5ee6-2bae-405a-b3b7-06414b19bbc5)

**Additional context**
Below is a link to a video from Google Drive where the bug is being played.

[Link](https://drive.google.com/file/d/1SYTDYlpbSv9t8A361YvVLmY59-uoetSp/view?usp=sharing)

**Comment by deltanedas** [comment]
i have a pr that does just this

**Comment by deltanedas** [comment]
can be closed

**Comment by mirrorcult** [comment]
pro
