### ISSUE TITLE
UI/Action bar disappearing example

### ISSUE THREAD

**Issue by Chillae** [space-wizards/space-station-14#25146]
As can be seen in the video the action bar seems to disappear whenever the power flickers, this might be a hint to as what is causing it. This is why I am sharing it here. Round #46264 on Lizard

I'm not sure how to reproduce this as it happens sporadically.

Video link:
https://www.youtube.com/watch?v=8DFUXkq-Mrk

Very serious issue, losing action bar during a pivotal moment can ruin the gaming experience.

**Comment by metalgearsloth** [comment]
dupe https://github.com/space-wizards/space-station-14/issues/20483
