### ISSUE TITLE
gravity gun is useless

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#25145]
it was created for easier crates transportating, but now it is faster to pull crates with your own hands than with a gravity gun

**Comment by K-Dynamic** [comment]
Wdym that thing flies with the flinging variant

**Comment by Kadeo64** [comment]
the gravity gun is capable of moving objects without you yourself having to move, think about meta's cargo bay, you can just sit on your ass and sort crates. I guess the movement speed of items grabbed should be buffed. 

don't touch force gun though flinging shit is still good
