### ISSUE TITLE
Feature Request: Anti-Polymorph Chemical

### ISSUE THREAD

**Issue by Kadeo64** [space-wizards/space-station-14#25156]
## Description
There probably needs to be some kind of anti-polymorph chemical especially when wiznerd is relatively close to completion. 

Right now the polymorph effects go away when you beat someone into crit usually, but it's probably a good idea to have a chemical that removes polymorph effects. 

Especially because I don't think medical doctors would like wasting healing supplies on everyone they beat up because they turned into parrots/frogs/runtime instead of getting that free space dragon antag token from polymorph wand

**Additional context**
it should probably use cognizine to make but be relatively cheap outside of that. Maybe cargo should be able to order autoinjectors for it in some kind of anti-magic kit in case of emergency.

**Comment by K-Dynamic** [comment]
Botany in ss13 grew holy melons for wizard magic immunity (had several charges and must be held)

**Comment by Boaz1111** [comment]
a lot of polymorphs don't last forever

**Comment by metalgearsloth** [comment]
Polymorph is a generic system used by a lot of things, make specific counters.
