### ISSUE TITLE
Departmental winter boot sprites need fixing

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#25151]
## Description

It's not that the sprites are bad, but there are some fundamental issues with the design that look bad in contrast such as line-art and clashing of colours. For example, the line-art on the security boots are lighter than the actual shading. Referencing PR #21810.

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/134914314/917d4835-2d57-482d-b8d9-5c1553ef4deb)

**Comment by MjrLandWhale** [comment]
Are you looking to only update the icon sprites, or do you hoping to have a pass done on the entire RSI for each boot type?

I took a pass at respriting some of the main icons as a first step. I only hit Sci, Engi, Med, and Sec. See below for all on gray then white tiles. Only the top row contains new sprites
![image](https://github.com/space-wizards/space-station-14/assets/12506666/da8f6b99-468c-43ec-a40c-a0167db6a74d)
![image](https://github.com/space-wizards/space-station-14/assets/12506666/264ab888-129f-4004-841e-3db21f90dae3)

**Comment by MjrLandWhale** [comment]
It would help if I toggled lights to get accurate screenshots....

![image](https://github.com/space-wizards/space-station-14/assets/12506666/826d9b4d-9ef0-436f-b45f-7b9b797a89de)

![image](https://github.com/space-wizards/space-station-14/assets/12506666/448a3c98-ae3a-4cda-874e-d4184036df75)

**Comment by UbaserB** [comment]
> Are you looking to only update the icon sprites, or do you hoping to have a pass done on the entire RSI for each boot type?

entire RSI ideally.
