### ISSUE TITLE
The thief objective to steal the detective's lighter is impossible if no detective room is mapped.

### ISSUE THREAD

**Issue by deepdarkdepths** [space-wizards/space-station-14#25180]
See: Saltern. Might apply to other lowpop maps. I know Packed has a room.

**Comment by Krunklehorn** [comment]
Spawns in their coat pocket. (which is not intuitive, a common theme in thief objectives)

**Comment by Krunklehorn** [comment]
Also not sure what you mean about Packed, the only mapped one is on Reach, which I don't even think is in rotation.

![image](https://github.com/space-wizards/space-station-14/assets/42424291/e11ac6b9-ecbc-44ae-8133-4946b7a3f2c7)

**Comment by Krunklehorn** [comment]
As for the coat itself, the only mapped one is on Origin. The rest are found inside a detective's locker, or on the detective themselves.

**Comment by deepdarkdepths** [comment]
> Spawns in their coat pocket. (which is not intuitive, a common theme in thief objectives)

If this is true I'll close this off. I inquired about it earlier and was told that it might've been an oversight or I misinterpreted.

**Comment by deepdarkdepths** [comment]
Although, if a detective never spawns, that effectively means any maps without a det room mapped are impossible for the thief to complete their objective. Least that's what happened to me.)
