### ISSUE TITLE
Enabling invulnerability, going beyond textures and teleporting things

### ISSUE THREAD

**Issue by kerisargit** [space-wizards/space-station-14#25181]
## Description
Quantum spin placed in a storage implant does amazing things. If you tie two spins, put one in some kind of storage, the other in an implant, then things disappear into the void, and the spin simply falls to the floor. But if you teleport someone inside the vault, it becomes an even funnier story. The teleported person becomes completely invisible and intangible, but at the same time he can interact with the world directly from under the floor (?). At the same time, physics continues to work on such an invisible person; in space he receives pressure, etc. No restrictions in structures affect it; it passes between all walls and ignores doors. Although when you are inside the wall, space acts. Well, in order to return from such a state, you need to activate one of the spins again, or create two new spins and teleport to another, or on a fulton. You can’t go through the teleporter’s portals, and you can’t install it yourself.

Teleported items can only be returned by activating the spin again. And this actually allows you to vaporize the nuclear authorization disk - teleport things, it will not be counted as destroyed and will not respawn. And the connected spin should be destroyed/broken.

**Reproduction**
1. Install yourself a storage implant
2. Link two spins, put one in the toolbox/bag (for teleporting things to nowhere) or give to a creature (for god mode)
3. Activate the second spin and quickly throw it into your implant

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/108146620/464585a9-bf92-47eb-9490-9c129e6010e7)

**Additional context**
(https://discordapp.com/channels/310555209753690112/1206735756782211082)

https://github.com/space-wizards/space-station-14/assets/108146620/946fd7ff-67aa-4f19-bf3e-b1a30efdb98e

**Comment by B1essedknight** [comment]
think this one is also related to this issue #25056

**Comment by kerisargit** [comment]
Yes, I think this is connected too, I checked from the point of view of such a “missing person”. It doesn't actually disappear, but starts working outside of textures.
