### ISSUE TITLE
Disablers cannot fit in armor suit storage slot.

### ISSUE THREAD

**Issue by Zadeon** [space-wizards/space-station-14#25202]
## Description
Disablers cannot be stored in the standard security armor vest's suit storage slot. 

**Reproduction**
1. Wear a security officer's armor vest.
2. Attempt to place a disabler into the armor storage slot.

**Additional context**
Items of the same shape and size like the standard pistol still fit in the slot just fine. I cannot remember exactly when this issue started, but I do remember that this was working fine with disablers directly after grid inventory was implemented. Looking at the disabler definition it seems to be missing the suitstorage tag under slots.

**Comment by Zadeon** [comment]
I have made a fix for this, but I'd like to confirm this is a bug before making a PR.

**Comment by thebadman4662** [comment]
Wait, pistols are supposed to fit on back slot for internals/2x4/4x4 guns?

Or you mean armor vests used to have storage like like jackets?

**Comment by Zadeon** [comment]
> Wait, pistols are supposed to fit on back slot for internals/2x4/4x4 guns?
> 
> Or you mean armor vests used to have storage like like jackets?

![image](https://github.com/space-wizards/space-station-14/assets/16091937/89c58778-487e-4367-8b2d-f11e8c6c9cb4)
This slot to the right of your pockets. Which can only be used when wearing something like an armor vest or hardsuit. Right now pistols fit in it but disablers don't, despite being the exact same shape and size.

**Comment by B1essedknight** [comment]
Considering that you could store more valuable things like a O2 tank or shotgun/more dangerous thing in that slot and that security can just take vesting (rigging?) or a belt for a more versatile storage; I would be inclined to think that this isn't a bug.

**Comment by Zadeon** [comment]
> Considering that you could store more valuable things like a O2 tank or shotgun/more dangerous thing in that slot and that security can just take vesting (rigging?) or a belt for a more versatile storage; I would be inclined to think that this isn't a bug.

If you can fit something a small as an emergency o2 tank (2x1 in inventory) or something as large as a lasergun (4x4 in inventory) then why couldn't you fit an L shaped disabler in there that takes up 3 tiles? Again, regular pistols that are also 3 tiles and L shaped already fit in the slot. Of course you should definitely be using an o2 tank there whenever the situation demands it, but early on in a shift it's nice to have a disabler readily available in an easy to access slot like suit storage.
It's the inconsistency between items that makes me think this is a bug because I remember disablers fitting in suit storage before. If disablers aren't supposed to fit there then why can pistols?

**Comment by B1essedknight** [comment]
I never knew that the disabler could fit in that slot or a pistol as I always assumed that slot was reserved for shoulder-slung weapons or gas tanks. I'm no coder so I have no say as to why the pistol can even go there in the first place. However, if I had to guess it is likely something related to what the suit storage is using to define what goes there.
