### ISSUE TITLE
Rat king ghost role duplicates

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#25218]
## Description

The last few times i have seen rat king, there have been at least 2 or even 3 at the same time. As far as I understand this is not intentional.

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/134914314/c30e3cde-7f5c-494e-a0c4-b0b7770825f4)

**Comment by deltanedas** [comment]
its a low % during mouse migration event so multiple can spawn at once

**Comment by themias** [comment]
Looks like this behavior is intended.
