### ISSUE TITLE
UI buttons not functioning

### ISSUE THREAD

**Issue by OliverOtter** [space-wizards/space-station-14#25210]
## Description

User in round reported that their UI buttons for crafting and piloting shuttles stopped working. Something to do with keybinds fucking with UI?
**Reproduction**

Was driving the cargo shuttle, then the bug happened. Nothing more that they know of.
**Screenshots**

**Additional context**

User reports rebinding the console keybind fixed it.

**Comment by Plykiya** [comment]
Something changed up my keybinds as well? I was opening up menus that I didn't have binded to anything in the 400+ hours I played

**Comment by metalgearsloth** [comment]
It's probably from https://github.com/space-wizards/RobustToolbox/pull/4841 but need much more info.

**Comment by OliverOtter** [comment]
I was just told as well that pressing the reset all keybinds option in the settings menu fixes the problem.

**Comment by VasilisThePikachu** [comment]
Intresting thing about keybinds. It seems like invalid hotbar values left from when minimalist action bar replaced the bind from "Loadout0-9" to "Hotbar1-9" seem to cause wierdness. This was causing issues from before too apparently. But something is causing more issues now

check out https://discord.com/channels/310555209753690112/1176862211482849384/1207241299678339093

**Comment by VasilisThePikachu** [comment]
Closed by https://github.com/space-wizards/RobustToolbox/pull/4903 and https://github.com/space-wizards/RobustToolbox/pull/4902
