### ISSUE TITLE
Agent ID chameleon seems to not be working correctly.

### ISSUE THREAD

**Issue by XxSWAG-MASTER-OVERLORDxX** [space-wizards/space-station-14#25219]
When using an agent ID the search function for the chameleon does not display the IDs you are searching for.

Pick up agent ID, use search, find nothing.

the only IDs i have been able to get it to change to are the QM, TA and RA cards by typing in "as" into the search, they do not show up if you search for them normally.

![Screenshot 2024-02-14 192015](https://github.com/space-wizards/space-station-14/assets/151447893/c0fadfa3-a261-4f91-a45f-dee5be3a9c2c)

**Comment by deltanedas** [comment]
quarterm**as**ter

it uses prototype id presumably so no acronyms

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
> quarterm**as**ter
> 
> it uses prototype id presumably so no acronyms

nope, you can type other parts of it but it still does not show, i did find another letter that works.
if you type "n" by itself it comes up with a ton of them
