### ISSUE TITLE
Incorrect async use in InteractionSystem.cs

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/space-station-14#2524]
It discards the tasks returned which means any exceptions will be rethrown in the finalizer thread. This *really* needs to be fixed.

**Comment by Zumorica** [comment]
Can you point the method where this happens, and how it should be fixed?

**Comment by PJB3005** [comment]
Every case of `_ = <some method that returns a Task>()`. The best way to fix it is to just make the surrounding method `async void` or something and await them. Then the exception will be rethrown in the task scheduler instead and correctly logged instead of crashing the entire program.
