### ISSUE TITLE
Chameleon UI just doesn't work

### ISSUE THREAD

**Issue by Skarletto** [space-wizards/space-station-14#25262]
## Description

Like #25219, chameleon gear just doesnt show any option when opening the UIs
**Reproduction**

Try to use chameleon gear
**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/122584947/b32470a2-9fb9-4a6c-a333-ca7aa6845745)

**Additional context**

**Comment by UbaserB** [comment]
could be *related* to #25219

**Comment by Jarmer123** [comment]
Yeah, we admins are getting a lot of ahelps regarding it.

**Comment by Plykiya** [comment]
pretty sure this is resolved as all chameleon clothes work atm

**Comment by slarticodefast** [comment]
Seems to be fixed now.
