### ISSUE TITLE
Singularity can currently move "root" of a grid.

### ISSUE THREAD

**Issue by GraniteSidewalk** [space-wizards/space-station-14#2528]
Not entirely sure what that means but singularity throws this error sometimes. How would I go about fixing it?
The exact error message is that it "attempted to move root node", but I'm assuming that's grid related.

**Comment by metalgearsloth** [comment]
Root node would be the mapentity I would think, would need the stack trace to confirm.

**Comment by GlassEclipse** [comment]
I did some more testing and it would seem the error is thrown in the FixClipping() function, which I assume moves entities with overlapping bbs away from each other. 
![Screenshot 2020-11-09 22 42 35](https://user-images.githubusercontent.com/32942106/98628753-e8464180-22dc-11eb-9adc-fe2306e22ce2.png)

**Comment by GlassEclipse** [comment]
And interestingly... checking out the variables of the collision indicates that it's between a water tank and a hydroponics table.

**Comment by metalgearsloth** [comment]
It's possible the singulo eats the grid-entity and thus any collision after that will probably implode. Would need to check.

**Comment by GlassEclipse** [comment]
Maybe not the case? Not entirely sure yet but I added a "non-grid-parent" check in the pull code through "if(_parent.IsValid())". That's actually the code that sends a "tried to move root node" error, so it might be a little misleading. Maybe the airlocks are being unparented and never reparented.
I will try doing adding the check for the collision delete and see what happens.

**Comment by GlassEclipse** [comment]
I added the non-grid-parent check on collide() and it still throws the error, so I'm guessing it's not reparenting some entities to space grid. This time the error was between a botanist locker and a hydroponics table.

**Comment by PaulRitter** [comment]
@metalgearsloth this still a thing? ik you worked on singulo

**Comment by metalgearsloth** [comment]
Lemme answer your question
