### ISSUE TITLE
Energy Shields are peak !!fun!! gameplay

### ISSUE THREAD

**Issue by FairlySadPanda** [space-wizards/space-station-14#25290]
## Description
![image](https://github.com/space-wizards/space-station-14/assets/732532/d3ebc836-429c-4849-9b6c-7138a5bf5bf2)
**Reproduction**
1. War-ops
2. Buy your entire team energy shields, throw in a Jugg suit and a syndie assault borg
3. Gamin'

**Screenshots**

![Screenshot 2024-02-15 222838](https://github.com/space-wizards/space-station-14/assets/732532/56aa2853-ffda-401c-8529-9ef8ac00062b)

**Additional context**
https://www.youtube.com/watch?v=GWBH7jGXhgc

**Comment by Aisu9** [comment]
where are the EMP grenade and chem mixt?

**Comment by metalgearsloth** [comment]
Nerf just got merged 2 hours ago
