### ISSUE TITLE
Bombs Removal Via Pie

### ISSUE THREAD

**Issue by Admiral-Obvious-001** [space-wizards/space-station-14#25307]
## Description

Normally, you can insert any explosive into a banana cream pie and then throw it to arm the fuse. However if you _eat_ the pie, then the bomb within gets deleted.

**Reproduction**

Cook/spawn banana cream pie, insert microbomb, throw pie, get an explosion. Repeat the same first two steps, but eat the pie. Your bombs is now gone.

**Additional context**

This was tested on a localhost instance, so it might work differently on live depending on the explosive, but it should probably still be fixed.

**Comment by themias** [comment]
Clown EOD real.

In the short term, we could probably have non-edible stuff drop at your feet if you eat their container.

In the long term (maybe after wound-med), it would be funny if you could eat the bomb. Maybe it would require quick surgery to remove it. "Doctor, why am I beeping?"

**Comment by JoeTheJanitor** [comment]
> In the long term (maybe after wound-med), it would be funny if you could eat the bomb. Maybe it would require quick surgery to remove it. "Doctor, why am I beeping?"

i’ve seen moths eating security boots with combat knives inside, they should digest into razorium :trollface:

**Comment by Errant-4** [comment]
Being able to feed a bomb to people via pie, and have it start beep as they try to rain away to no avail would be great

**Comment by deltanedas** [comment]
make stomach a container :trollface::trollface::trollface:

**Comment by Slava0135** [comment]
I made it specifically to activate bomb when you eat pie, but something broke I guess
