### ISSUE TITLE
The Other Keybinds Issue

### ISSUE THREAD

**Issue by Errant-4** [space-wizards/space-station-14#25309]
## Description
As of ~~a few days ago~~ [Robust Toolbox #4898](https://github.com/space-wizards/RobustToolbox/pull/4841), modifying the keybinds from the default causes a glitch that overwrites your control scheme. 
It's possible that the cause of this issue is related to [Robust Toolbox issue #4898](https://github.com/space-wizards/RobustToolbox/issues/4898) as they popped up around the same time
The bug still exists as of commit 0a64e086c

 - Upon any changes to keybinds, every control function that was not assigned a Secondary input will display the default value as it's secondary input. 
 - EVERY control function, even the ones that were assigned a secondary bind and do not show the previous "symptom", will react to their default key being pressed, on top of everything else that is bound. 
 - **This additional set of default keys does not exist in the keybinds file, the game appears to load the defaults on top of what it reads from the keybinds**
 
When the issue manifests, this means that every control input you did not overwrite or remove will also trigger twice on every keypress, once from the Primary Input and once from the "Bug Input".
 - Can't Ready at roundstart! (Every click is doubled, cancelling itself)
 - Esc will no longer open the menu, because the second press immediately closes it. 
 - F11 will toggle fullscreen mode back and forth, putting you where you started. 
 - Crafting menu GUI button won't work for some reason, while the other GUI buttons around still do
 
# Workaround
See my post below!

# Examples
You change WASD to ESDF. After you restart the game, pressing S will move the character both down and to the left. This will be shown as your keybinds:
![Screenshot from 2024-02-16 09-46-35](https://github.com/space-wizards/space-station-14/assets/35878406/07ad2b2f-7f4f-4fc5-81ce-df91ab1060ff)

You change WASD to ESDF, and set 1234 as secondary binds. After you restart the game, pressing S will STILL move the character both down and to the left. This will be shown as your keybinds:
![Screenshot from 2024-02-16 09-47-39](https://github.com/space-wizards/space-station-14/assets/35878406/dd8d2dcb-6d06-411e-9fa8-582551165f99)

**Comment by Hmeister-real** [comment]
yeah this happens to me almost every time i log on, and its really really annoying

**Comment by Synthestra** [comment]
Can reproduce

**Comment by Errant-4** [comment]
I will be very surprised if anyone can report that this does NOT happen to them, unless they stick to the defaults. It should be the universal and I'm honestly not sure how people are not rioting yet
I will mention it here again that there are options to get around this issue:

## Easy But Restrictive Workaround
Set `Toggle Walk` to whichever state you prefer. This will be preserved.
Press `Reset All Keybinds` in the controls menu, or delete your keybinds.yml
As long as you do not bind any keys, the defaults will keep working properly.

## Less-Than-A-Minute Custom Setup Workaround
0. If you have not wiped your controls in a LONG time, might want to start with deleting your keybinds.yml just to be sure.
1. Set up your preferred controls as the Primary binds exactly how you want them. Leave all Secondaries empty.
2. Every time you start the game, go through the controls and right-click every entry in the Secondary column to clear them. 
3. You could further speed up this procedure by working out which specific settings* are the ones that cause issues and which ones you can ignore. But even if you do ALL of them, a pre-game wipe should take less than a minute.

* Left Click being bound twice on use is, for example, the absolutely most disruptive thing, it will probably prevent you from even pressing Ready Up

## I Don't Want To Deal With This
That's fair. A fix has already been coded, hopefully no issues will be found with it and it will be deployed to live soon.
