### ISSUE TITLE
Interchangeable GameHud

### ISSUE THREAD

**Issue by exp111** [space-wizards/space-station-14#2531]
Would be great to be able to change the Game Hud easily to allow alternate ui designs (like the old ss13 stockholm ui) or something like huds for mapping.

**Comment by AJCM-git** [comment]
We now have examples with the HUD themes, is that enough to close this?

**Comment by mirrorcult** [comment]
no, this means hud layout not appearance

**Comment by exp111** [comment]
Impossible
