### ISSUE TITLE
Diona's transformation into a nymph is broken

### ISSUE THREAD

**Issue by foboscheshir** [space-wizards/space-station-14#25334]
Diona's transformation into a nymph is broken, when you get gib  you're going to another dimension  and the gibs will be lost

Die and click  gib button

https://github.com/space-wizards/space-station-14/assets/156405958/6fee7d7e-b6ef-4a98-9662-a9c603a61806

**Comment by LankLTE** [comment]
What the fuck this worked fine

**Comment by icekot8** [comment]
gibbing system update moment :trollface:
