### ISSUE TITLE
Double warden hardsuit on core

### ISSUE THREAD

**Issue by Clone0401** [space-wizards/space-station-14#25337]
## Description
It seems like the Warden's locker with a hardsuit is mapped alongside the warden's suit storage locker allowing giving the station two hardsuits instead of one.

**Reproduction**
load core station and open both lockers inside the warden's office

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/150492283/99e37356-e9dc-46a7-aaf8-820bc534e76f)

**Additional context**
this was on round 46661 of salamander

**Comment by UbaserB** [comment]
already reported ill fix it in next update
