### ISSUE TITLE
Disposal tubes allow wall hopping.

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#25341]
## Description
One can easily bypass locked areas by building disposal tubes under walls only from the side you have access to, eg maints.

**Reproduction**
- Build a disposal pipe under wall from the side you have access to
- Build a trunk and place disposals on it.
- Flush yourself and yeet in to the room.

**Screenshots**
<img width="287" alt="image" src="https://github.com/space-wizards/space-station-14/assets/47093363/0dae8f9e-787e-4e8a-8b32-03756f2023fc">

https://github.com/space-wizards/space-station-14/assets/47093363/eef623ae-b506-4598-b99b-8fe8c1f047e1

**Additional context**
Essentially need no tools needed or any secure gear to get through a wall in a couple of seconds.

**Comment by 0x6273** [comment]
This is intended

**Comment by deltanedas** [comment]
feature

**Comment by potato1234x** [comment]
feature

**Comment by Titian3** [comment]
Closing as feature not a bug 😅
