### ISSUE TITLE
EVA helmet can't be quickused

### ISSUE THREAD

**Issue by thebadman4662** [space-wizards/space-station-14#25379]
## Description
For some reason quick use when holding it in hand does not put it into head slot.

**Reproduction**
Get EVA in your hand, press Z or whatever is your hotkey for use of item in hand.

**Comment by Hmeister-real** [comment]
Its the same with welding masks

**Comment by thebadman4662** [comment]
Is it some kind of specific weldmask? grey/red ones work fine for me...
