### ISSUE TITLE
Problem with map render program being out of date

### ISSUE THREAD

**Issue by Starbuckss14** [space-wizards/space-station-14#25386]
## Description

When you run your map render on your map with the current version it dose not work. You get errors regarding new prototypes that the map renderer dose not know. Cyro sleep chambers, cyro sign, captains laser pistol box and rusted reinforced walls. (that's all i tested there is likely more)
**Reproduction**
Fire up map render on a map file that contains the afore mentioned things and *tu-da* errors.

**Additional context**

I was attempting to get a new map render for my map Phobos station but cannot because of this bug.

Thanks!

**Comment by VasilisThePikachu** [comment]
@juliangiebel something off the press for you

In the meantime, i would suggest grabbing and sending over the errors you receive when trying to render your map.

**Comment by MjrLandWhale** [comment]
I'm not getting the error you are. I ran the map renderer through basically all the current maps without issue. Hell, I even used the output to update the map files on the wiki. 

I went one step further and pulled in your phobos yaml files to my local environment (which is up to date with upstream master) and ran the renderer against your new station. See below:
![phobos-0](https://github.com/space-wizards/space-station-14/assets/12506666/fc284762-7e80-4caf-aee0-4954fa387127)

Your branch is pretty far behind, so you may want to just merge+fetch & rebuild everything. Its probable the ~130 or so commits adds something you needed.

**Comment by Starbuckss14** [comment]
Looks like I had mistaken this as  a bug. Good day!
