### ISSUE TITLE
Going out of the locker causes all your items to disappear

### ISSUE THREAD

**Issue by Injazz** [space-wizards/space-station-14#254]
- Get inside a locker
- Get out
- Fail to take off your clothes
- Try to put some clothes on, like hat or mask
- You're naked (except the thing you put on a previous step)

**Comment by raymoo** [comment]
I don't experience losing clothes, but I do lose my utility belt.

Steps:
1) Put on a utility belt
2) Enter a crate (Lockers are currently too small to fit humans)
3) Exit the crate
4a) Try to open the utility belt (rendering freeze)
4b) Try to grab the belt (nothing happens)
4c) Rejoin the server (the utility belt is gone)

Without rejoining, the utility belt is still shown to be in the belt slot. Any items in the utility belt are dumped along with the human.

**Comment by Injazz** [comment]
that's exactly what happens with clothing too
