### ISSUE TITLE
Pause more systems

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#2540]
EntityQuery now has an arg that lets you choose whether you retrieve paused components or not.

For compatibility's sake I retained the old settings but ideally we should go through and see what systems can be paused or not. Not everything should be paused (e.g. eyesystem, mover probably) which is why we can't just default everything to not retrieving paused.

**Comment by moonheart08** [comment]
This defaults to not include paused now. Issue solved.
