### ISSUE TITLE
Feature Request: Cryo Sleep Units Should Let You Know Someone's Inside

### ISSUE THREAD

**Issue by Kezu02** [space-wizards/space-station-14#25413]
## Description

Got an admin question asking if it's allowed to use cryo units for hiding.  There's no way to tell if a body's in it besides those in storage, and since you can't pull them out, it's a perfect hiding spot to evade sec. Could have an "in use" sprite like cryo pods or at least a description change.

**Comment by EmoGarbage404** [comment]
They do have a sprite tho? They open and close when something is inside.

**Comment by Kezu02** [comment]
I completely forgot about that lmao
