### ISSUE TITLE
Thieves continuously do not show up on EOR manifest

### ISSUE THREAD

**Issue by deepdarkdepths** [space-wizards/space-station-14#25414]
1. Be thief.
2. EOR.
3. Dont show up on manifest. You can only check if someone is thief via the uh.. other option. Forgot its name. The one to right of the manifest button.

The only time I've seen exceptions to this is during nukies. If its a syndicate or any other round, you do not show up. Sometimes it only selectively shows one thief out of however many there were during the round.

**Comment by deltanedas** [comment]
it doesnt show thieves own their own only if they are in roundend summary for other antags

**Comment by deepdarkdepths** [comment]
> it doesnt show thieves on their own only if they are in roundend summary for other antags

Reword/elaborate?

**Comment by deepdarkdepths** [comment]
That should be amended imo.

**Comment by TheShuEd** [comment]
Duplicate #22977
