### ISSUE TITLE
Trash spawns in space

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#25410]
## Description

It's weird.

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/134914314/976c3708-ccf5-4c2c-85d2-7956ea6ca923)

![image](https://github.com/space-wizards/space-station-14/assets/134914314/841f90d6-c1cf-46cb-a57a-b2f535c87699)

**Comment by Hrosts** [comment]
I think that was intentional #24788

**Comment by K-Dynamic** [comment]
Something about space trash near the station gives me depression

Like surely we could have other space doodads other than dan dan mian boxes or broken beer bottles

**Comment by UbaserB** [comment]
> I think that was intentional #24788

well they admitted it wasnt intentional, but are willing to keep it. Hence, i will be closing this issue
