### ISSUE TITLE
Support custom emoticons in chat

### ISSUE THREAD

**Issue by Visne** [space-wizards/space-station-14#2542]
I feel like custom emotes add a lot in applications like Discord, and while I understand SS14 is not a chat application I feel like it would definitely be fun to allow server owners to enable/disable it. Maybe it could also be implemented such that it's only possible to use emoticons outside of IC chat.

**Comment by Visne** [comment]
Also it allows server owners to name their "special gas" 🅱️lasma

**Comment by mirrorcult** [comment]
do we really need this

**Comment by Visne** [comment]
No, we definitely don't "need" it.

I still think it would be fun though, especially on LRP servers or OOC chat.
