### ISSUE TITLE
dragging over atmos pipes slows you down

### ISSUE THREAD

**Issue by MACMAN2003** [space-wizards/space-station-14#25430]
## Description

if you drag something over gas pipes, even if there's a floor tile covering them up, you get slowed down
**Reproduction**

1. get a t-ray scanner
2. get something heavy, like a freezer/heater 
3. try to drag it to somewhere
4. notice how you drag slower over pipes even if they're under a tile
**Screenshots**

not a screenshot, but a video should suffice

https://github.com/space-wizards/space-station-14/assets/20659419/1edeb8b4-b404-47ad-a243-ac6f03b499f3

**Additional context**

**Comment by Plykiya** [comment]
you're a fucking hero
I knew I wasn't crazy that I was speeding up and slowing down while dragging objects

**Comment by K-Dynamic** [comment]
Bug of the time

**Comment by notquitehadouken** [comment]
what the actual fuck

**Comment by Golinth** [comment]
Needs to be closed, fixed by #25629
