### ISSUE TITLE
Strange Orbiting bug

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#25435]
## Description

Taking a mouse and getting eaten forces you into ghost mode and any action from the entity causes you to move as well.

Teleporting to another person/spawner fixes the issue.

**Reproduction**

- Take mouse ghost role
- Get killed
- Pun-pun picks you up
- Get eaten

Now you are forced into ghost but it's almost as if you are glued to him. If he moves 2 tiles to the left, you also move two tiles to the left.

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/134914314/225bfd4b-d242-4dab-918e-325cdff6ad3b)

**Additional context**

Round #47010 on Lizard.

**Comment by metalgearsloth** [comment]
I imagine you're getting parented to them

**Comment by B1essedknight** [comment]
pretty sure this one is related #17742
