### ISSUE TITLE
Svalinn Laser Pistol doesn't show how much damage is dealt

### ISSUE THREAD

**Issue by SphiraI** [space-wizards/space-station-14#25447]
## Description
Other laser weaponry show how much hitscan damage they do, but the Svalinn is left out and leaves people wondering how much it takes to kill something.

**Reproduction**
- Inspect a Svalinn pistol
- Notice the lack of the "Examine damage values" button

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/145869023/0ba3dc09-3da1-408f-b7cd-2909ea1d0075)
![image](https://github.com/space-wizards/space-station-14/assets/145869023/261c426b-72bc-47a8-94cb-7c6335ef8b41)

**Comment by Kadeo64** [comment]
it's because the svalinn itself doesn't do any damage. The svalinn works like an actual ballistic gun and the AMMO has the damage values. Which is why inspecting a power cell shows damage.

**Comment by SphiraI** [comment]
> it's because the svalinn itself doesn't do any damage. The svalinn works like an actual ballistic gun and the AMMO has the damage values. Which is why inspecting a power cell shows damage.

I guess that makes sense. Still unintuitive, though. Had a couple people confused, lol.
