### ISSUE TITLE
Antag code is dogshit

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#25459]
The level of copy-paste / hacky code that has been added to this amorphous blob of 1,200 lines is just an absolute nightmare and I spotted several methods that barely even work.

Additionally adding new gamemodes like nukies should be trivial but this is just so hardcoded that you can't re-use any of it.

I'm going to go through for my next refactor and fix the code duplication so we can actually add new antag rules easily.

**Comment by Kadeo64** [comment]
time to disable nukies until refactor :trollface:

would be an improvement imo

**Comment by K-Dynamic** [comment]
Sometimes it be weird nukies outnumber sec, yes

**Comment by deltanedas** [comment]
merge antag refactor then "try" to make some of the giant pile of very clean nukie code reusable

**Comment by Hmeister-real** [comment]
Time to remove Syndicate and Nukies until refactor :trollface:

**Comment by Kadeo64** [comment]
> Time to remove Syndicate and Nukies until refactor :trollface:

24/7 zombies real

**Comment by metalgearsloth** [comment]
It's better but ongoing concern.
