### ISSUE TITLE
Thieves shouldn't have access to syndie pAI (aka syndies + nukies mode made a comeback)

### ISSUE THREAD

**Issue by K-Dynamic** [space-wizards/space-station-14#25471]
## Description

Thieves are increasingly purchasing syndie kits for syndie pAIs alone to message traitors but mainly nukies, the latter guaranteed to use syndie comms. 

This is causing the following issues:

1) Thieves will make a deal to steal the nuke disk at minimum, sabotage the station via bombings and cutting comms at the other end.

   [Round #47097 involved 2 of 3 thieves emagging a recycler to gib the captain, breaking comms and distracting sec so the armoury could be blown - evac was later called for the thieves so they could escape to CC and finalise their objectives.]

   Antag collabs are generally okay (such as ninja with nukies), but thieves are becoming too similar to syndies, who were removed from nukie gamemodes due to balance issues - even though it made sense lorewise, having syndies run around before nukies arrived was a nightmare.

2) Flipside is if a thief reveals to crew that nukies are arriving, which would be unfair for nukies - similar incidents with radio artifacts tuning into syndie comms gave the station crucial time to arm the crew and secure crew victory.

3) Thieves are becoming too tied with syndies or nukies as opposed to their own antagonist. They are slowly losing their identity as criminals with pacifist implants when they essentially help nuke an entire station and become honorary syndies

   Nuking the station is not consistent with their antag description, and is a hugely disproportionate response to steal several IDs, plants or the captain's cloak. 

Suggestions include removing syndie pAIs from thief syndie kits to limit contact with nukies. Thieves should also be discouraged making deals that swap kleptomania with terrorism (not without them meeting in-person first)

**Comment by Kadeo64** [comment]
https://github.com/space-wizards/space-station-14/pull/24517

**Comment by CatMagic1** [comment]
That sounds fun to me

**Comment by Anzarot121** [comment]
If the captain managed to die from a person with pacifism, this is a skill issue.
If the nukers could not fly to the station in 10 minutes without declaring war, then this is a skill issue. Let them declare war if they cannot act quickly.

**Comment by K-Dynamic** [comment]
> If the captain managed to die from a person with pacifism, this is a skill issue.

It's pretty easy to bypass pacifism with explosives alone but that's beside the point

**Comment by vanilia123** [comment]
I had like 4 runs destroyed by this in last 3 days. On LRP there is nothing nukies can do about inexperience newkies, talking on comms. From perspective of thieves it's a no-brainer to dont use pai as an easy way to get all objectives for free from Command. Trying to work with Nukies for thieves is a big risk, problems, and too much "RP" when on the other hand they can simply turn on pai, and go to security with info... 

Dont get me also started how nukies round looks like from perspective of someone who is trying to do stealth ops, 40 mins in, and whole station knows when & where they are going to strike. Also try to navigate and plan with nukie team splited between medic room, armory, bar, outside shooting range, and ship. Goooooooood luck

**Comment by Ilya246** [comment]
nukies could also just get their own dedicated second radio channel which nobody besides nukies can ever access, possibly together with the syndicate channel so they can still make use of it if they wish

**Comment by TheShuEd** [comment]
Intended
