### ISSUE TITLE
AME controller should probably not have "this doesnt go in there" text popup when using a tool to anchor/unanchor it

### ISSUE THREAD

**Issue by deepdarkdepths** [space-wizards/space-station-14#25482]
Just a little weird, not like you're trying to insert the wrench into it.

1. Get AME controller.
2. Wrench/unwrench.
3. Text pops up about the wrong item insertion.

**Comment by Plykiya** [comment]
this is a wide-spread bug that applies to every type of container-like structure, such as bookshelves
