### ISSUE TITLE
The bounding box of a grid lags behind by one update

### ISSUE THREAD

**Issue by DrSmugleaf** [space-wizards/space-station-14#2548]
Try adding and removing tiles from it, its bounding box will be what it should have been before the latest change.
If you have a 1x2 tile grid and you remove one of them, the bounding box will still be 1x2. Same happens if you add a tile, or add multiple at the same time.

![image](https://user-images.githubusercontent.com/10968691/99128811-22308400-260c-11eb-923f-e9ef3d5a5b31.png)
![image](https://user-images.githubusercontent.com/10968691/99128818-28befb80-260c-11eb-9c8c-2554cb325343.png)
![image](https://user-images.githubusercontent.com/10968691/99128827-31afcd00-260c-11eb-85c1-77398f4df3f3.png)

**Comment by moonheart08** [comment]
So *that*'s what causes that particular mapping annoyance.
this can cause some really big disparities if a lot of tiles are bulk-filled in at once.

**Comment by SweptWasTaken** [comment]
Still an issue.

**Comment by PaulRitter** [comment]
@metalgearsloth with grids recently getting some love, is this still a thing?

**Comment by metalgearsloth** [comment]
Don't think so
