### ISSUE TITLE
Centcom offical job is selectable in character  creation screen

### ISSUE THREAD

**Issue by Ilkepro** [space-wizards/space-station-14#25493]
## Description
You can select Centcom offical as a job in charachter creation menu.

**Reproduction**
joining any updated server

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/147644829/c04f10bb-2de2-4383-99a0-6b1410b8f2dd)

**Additional context**
While the job exist thanks to the fact they dont have any place to spawn they arent playable so they shouldnt cause major issues.

**Comment by UbaserB** [comment]
what the hell

**Comment by KompaniLinge** [comment]
intended feature

**Comment by VasilisThePikachu** [comment]
Handling this

**Comment by K-Dynamic** [comment]
Just imagine random CC officer yelling at cap every 10 seconds to do their job properly

**Comment by deepdarkdepths** [comment]
That's fucking funny.
