### ISSUE TITLE
UI scaling is broken

### ISSUE THREAD

**Issue by MACMAN2003** [space-wizards/space-station-14#25504]
## Description

UI scaling offsets things diagonally when it's not 100%
**Reproduction**

change the UI scale to not 100%
**Screenshots**

200%
![image](https://github.com/space-wizards/space-station-14/assets/20659419/2efa3520-143c-41fa-83dc-6c528d265b29)
75%
![image](https://github.com/space-wizards/space-station-14/assets/20659419/291018b0-b6f8-4944-afba-9b0d1014e6ea)
100%
![image](https://github.com/space-wizards/space-station-14/assets/20659419/e6b6f82e-1248-4e3f-9983-341255165b3e)

**Additional context**

**Comment by MACMAN2003** [comment]
may be related to https://github.com/space-wizards/RobustToolbox/issues/4919#issue-2150563312

**Comment by MACMAN2003** [comment]
it appears to be the "backgrounds", not the icons themselves.

**Comment by Eggexe** [comment]
Also appears to affect examine icons:
![image](https://github.com/space-wizards/space-station-14/assets/159236595/3b1583dd-7ba0-42a1-99f4-d2b3f6691762)

**Comment by VasilisThePikachu** [comment]
Closed by https://github.com/space-wizards/RobustToolbox/pull/4923
