### ISSUE TITLE
Tests should use their own testing prototypes instead of relying on the game's

### ISSUE THREAD

**Issue by DrSmugleaf** [space-wizards/space-station-14#2553]
Like TransformTest does https://github.com/space-wizards/RobustToolbox/blob/0a67cecfa5a0ebe5f06280e6f0c1c0438db9491b/Robust.UnitTesting/Client/GameObjects/Components/Transform_Test.cs#L25-L31

**Comment by DamianX** [comment]
Is there any test that currently does NOT do this? I looked and found none.

**Comment by Zumorica** [comment]
I can think of a few integration tests that do, but I think those don't apply here i m o

**Comment by DrSmugleaf** [comment]
> Is there any test that currently does NOT do this? I looked and found none.

InventoryHelpersTest, LegTest, LungTest, MechanismBehaviorEventsTest, BuckleTest, RejuvenateTest, DisposalUnitTest, DoAfterServerTest, AirlockTest, ClimbUnitTest, WeightlessStatusTests, GridTileLookupTest and HumanInventoryUniformSlotsTest all use HumanMob_Content directly.
CuffUnitTest, GravityGridTest and PowerTest also similarly use prototypes from the game.
ContainerOcclusionTest uses its own prototypes for example.
