### ISSUE TITLE
Having centcomm offcial in charatcer meun under job section.

### ISSUE THREAD

**Issue by Vova567810** [space-wizards/space-station-14#25539]
## Description
Before it got fixed, I selected centcomm official to see if it actually works. After fix, my character is just stuck with it, even after changing other job priorites to high.

**Reproduction**
Can't really be reproduced, since centcomm offiical only been for one version.

**Screenshots**
![Снимок экрана 2024-02-24 233917](https://github.com/space-wizards/space-station-14/assets/161185315/9067997c-eb76-4029-9889-caff417f7224)

**Comment by UbaserB** [comment]
a pr fixed this (forgor which one)
