### ISSUE TITLE
zombies from gamemode should know who all the IIs are

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#25565]
## Description
the II in zombies gamemode are presumably organized bioterrorists or syndicate operatives since they all know they are carriers and can turn at will, they should also know their fellow operatives so they can actually plan instead of 5s into the round someone turns in medbay and ruins any kind of plan others could have.

if zombies are told who the others are in character menu and/or the greeting message they are encourage to plan something with the others

**Comment by lzk228** [comment]
II also should have the zombie icon?

**Comment by Krunklehorn** [comment]
Seems like a good buff considering the recent removal of Command and Security II.

**Comment by deltanedas** [comment]
> But do they really? The players controlling them do, but the characters presumably don't. It's one of the cases where for gameplay reasons "it couldn't have been implemented any other way". Characters being II without player knowledge or turning without player input just doesn't make sense. Players knowing their character is II doesn't mean the characters themselves know about their condition.

they do know, since they are expected to act as antagonists before turning

**Comment by potato1234x** [comment]
the amount of times i have chosen another initial infected as a first target is insane

**Comment by Killerqu00** [comment]
implemented in #25934
