### ISSUE TITLE
Taco shells are impossible to make

### ISSUE THREAD

**Issue by Everturning** [space-wizards/space-station-14#25577]
## Description
you can't make a flattened tortilla dough

**Reproduction**
>make tortilla dough
>rolling pin attempt no. 1
>rolling pin attempt no. 2
>rolling pin attempt no. 3
>give up

**Screenshots**

**Additional context**

**Comment by themias** [comment]
It isn't communicated well, but you have to chop into dough slices and flatten those.

**Comment by UbaserB** [comment]
yeah what he said was right so im closing this
