### ISSUE TITLE
Cargo Tier 3 telepad does not work

### ISSUE THREAD

**Issue by thebadman4662** [space-wizards/space-station-14#25586]
## Description
I suppose it still goes to station, it certainly does not go to cargo.

**Reproduction**
1. Link telepad and cargo console
2. Order something, accept order
3. ?????
4. WHERE ARE MY PLUSHIES?!

**Comment by metalgearsloth** [comment]
Gonna use https://github.com/space-wizards/space-station-14/issues/26181
