### ISSUE TITLE
Crates have no collision with windoors

### ISSUE THREAD

**Issue by PotentiallyTom** [space-wizards/space-station-14#25603]
## Description

Crates can be pushed through windoors and secure windoors

**Reproduction**

1. Spawn a windoor and a crate
2. Push the crate towards the windoor
3. It goes right through

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/67602105/2b1e2689-a02a-4f8f-8166-bbe2fb5d11e5)

**Additional context**

* You can stop dragging the crate, and it will remain in the windoor
* No other object that I tested (Canisters, Items, Bodies, Lockers) will move through the windoor
  + Pushing items specifically cause the items to jitter against the windoor
* Happens whether or not the player has access to the door
* Happens even if items are in the crate, and it has a label on it

**Comment by Krunklehorn** [comment]
Related? #25457
