### ISSUE TITLE
Marathon Station - Unpowered APC

### ISSUE THREAD

**Issue by EnrichUranium** [space-wizards/space-station-14#25607]
## Description
The APC on Marathon in the hallway by the CMO's room has no MV cables connection, leaving it unpowered.  This leaves the hallway dark & the door into the CMO's Bedroom to be unpowered.  

**Reproduction**

**Screenshots**
I toggled on all lights to more easily show the issue, but normally this hallway is dark.  Just need to add two MV cables to actually connect this APC to the grid to fix.  The door that is circled is the one without any power when that APC is off.
![image](https://github.com/space-wizards/space-station-14/assets/157912147/9b57aaae-ae51-4e75-a3f7-8f9c4352040b)

**Additional context**

**Comment by Emisse** [comment]
i fixed this one
