### ISSUE TITLE
VendingMachineWallmount needs physics component removed

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#25625]
The only time dummy components are okay is for collisionwake because managing it otherwise is a mess, but this does not need it.

**Comment by IamVelcroboy** [comment]
![image](https://github.com/space-wizards/space-station-14/assets/107660393/766c3c7b-4068-4b08-a2d7-c189b73d287d)

**Comment by IamVelcroboy** [comment]
OK, I did a bunch more testing. I was mistaken about the comment above. I'm not sure why it was functioning different the first time but I repeated the tests quite a bit to be sure and it works as intended w/out the physics comp. So, I removed it. 

There is still some funny behavior with Fixtures->shapes that I've noticed with this testing. I'll make a separate issue for that.

**Comment by IamVelcroboy** [comment]
So this happens 

![image](https://github.com/space-wizards/space-station-14/assets/107660393/05e68eae-5bf2-4a98-b4ca-5a7db1f9f3b7)
