### ISSUE TITLE
Screens do not display the shuttle ETA on maps that aren't Dev or Packed

### ISSUE THREAD

**Issue by Flareguy** [space-wizards/space-station-14#25627]
## Description
Screens are supposed to display the shuttle ETA once you call the shuttle, but only seem to do so on Dev for some reason.
The broadcast option still seems to work, it's just the shuttle timer that doesn't.

**Reproduction**
1. Set the ``shuttle.emergency`` cvar to ``true``
2. While on dev, place a screen down, and then call the shuttle with the communications console, see that it works as intended and shows the shuttle ETA (and ETD once it docks)
3. Dock the shuttle (``dockemergencyshuttle``) and see that the ETD shows inside the shuttle as well
4. ``forcemap Box``, ``restartroundnow``
5. Call the shuttle with the comms console in bridge on Box, observe that it doesn't show the shuttle ETA like it did on Dev.
6. Dock the shuttle and observe that it still doesn't work

**Additional context**
These may or may not work correctly on Bagel as well for some reason, though I didn't test it. I remember seeing them functional ingame at least once.

**Comment by metalgearsloth** [comment]
Did you use loadmap or did you start a new round entirely.

**Comment by Flareguy** [comment]
I started a new round using ``restartroundnow``. I'm pretty sure that wouldn't matter though, afaik this is still broken in live.

**Comment by UbaserB** [comment]
Yes, this happens in live as well.

**Comment by Flareguy** [comment]
For some reason, I randomly saw these working on Round #52462? I don't know what map this was but it seemed like a lowpop one.
(Yes, the screen *is* displaying something, it's just very faint. Apologies for the bad image.)
![SS14 Loader_hNupU7gRg5](https://github.com/space-wizards/space-station-14/assets/78941145/503a7b0e-29dc-40df-bb9e-68d454573f14)

**Comment by Dutch-VanDerLinde** [comment]
> For some reason, I randomly saw these working on Round #52462? I don't know what map this was but it seemed like a lowpop one.
> 
> (Yes, the screen *is* displaying something, it's just very faint. Apologies for the bad image.)
> 
> ![SS14 Loader_hNupU7gRg5](https://github.com/space-wizards/space-station-14/assets/78941145/503a7b0e-29dc-40df-bb9e-68d454573f14)
> 
> 

The ETA screens only seem to work on certain stations (one of them is packed and I believe bagel)

**Comment by Flareguy** [comment]
> For some reason, I randomly saw these working on Round #52462? I don't know what map this was but it seemed like a lowpop one. (Yes, the screen _is_ displaying something, it's just very faint. Apologies for the bad image.) ![SS14 Loader_hNupU7gRg5](https://private-user-images.githubusercontent.com/78941145/326830121-503a7b0e-29dc-40df-bb9e-68d454573f14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNTgwODMsIm5iZiI6MTcxNTI1Nzc4MywicGF0aCI6Ii83ODk0MTE0NS8zMjY4MzAxMjEtNTAzYTdiMGUtMjlkYy00MGRmLWJiOWUtNjhkNDU0NTczZjE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDEyMjk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhZTEzNDg2MDAxNjYxMjE0OGQ5OGJmNjUwOTcxNmQxOWM3ZmJhZWQ4MzFmY2YxOWRiNTIzNjNlNTNkMjE5ZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dkSvZyRzpij8qn71CPqaULbcgxYufZ7wdQtTkJWU4yY)

Ok, after playing a round on Packed, I think this was on Packed. The shuttle screens worked as well, so it'd reaffirm that.

**Comment by Dutch-VanDerLinde** [comment]
maybe it's something with the evac shuttles on certain stations missing some kind of component? so the ETA screens dont work

**Comment by Dutch-VanDerLinde** [comment]
> maybe it's something with the evac shuttles on certain stations missing some kind of component? so the ETA screens dont work

![image](https://github.com/space-wizards/space-station-14/assets/45323883/cbeeec62-36ab-4a9b-be2f-10acdff05319)

think i'm right
this component is on emergency.yml and arrivals.yml but no other shuttle file

**Comment by Dutch-VanDerLinde** [comment]
> > maybe it's something with the evac shuttles on certain stations missing some kind of component? so the ETA screens dont work
> 
> ![image](https://private-user-images.githubusercontent.com/45323883/329245855-cbeeec62-36ab-4a9b-be2f-10acdff05319.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNTgzNjMsIm5iZiI6MTcxNTI1ODA2MywicGF0aCI6Ii80NTMyMzg4My8zMjkyNDU4NTUtY2JlZWVjNjItMzZhYi00YTliLWJlMmYtMTBhY2RmZjA1MzE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDEyMzQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0MGMyNzlkNzAzOWY2N2EyMGEzMWRhMDA3M2NiN2UwZDAzZmY3YWVhYTk5N2I2Mzk4ZWZjMjczNzY4NWQ2NzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DS3Nj374MFQpjsPUk3MAkSQNdynV9rNhtZYsyhG4dhI)
> 
> think i'm right this component is on emergency.yml and arrivals.yml but no other shuttle file

yep, packed is the only station using an emergency shuttle with this component (which is the default)
