### ISSUE TITLE
we need more arcade machines that are actually entertaining to play

### ISSUE THREAD

**Issue by potato1234x** [space-wizards/space-station-14#25630]
## Description
We need more arcade machines, think pacman or other arcade games since we have tetris

## Why
Space Villian is literally pressing 3 buttons randomly and is almost never entertaining. Tetris is ok but we need more

**Comment by metalgearsloth** [comment]
We should fix the existing ones so they're actually predicted before adding more.

**Comment by Hanzdegloker** [comment]
Space villains is good, I think it's fine, even spits out prizes! Block game is bad and works not quite right.

**Comment by Emisse** [comment]
more are blocked until existing ones are fixed, there an issue already on this somewhere

**Comment by Emisse** [comment]
also issues arent really a spot for ideaguysing anymore
