### ISSUE TITLE
Not being able to swap magazine into guns and batteries into borg.

### ISSUE THREAD

**Issue by Threnody44** [space-wizards/space-station-14#25633]
## Description
<Before the prior update, selecting a magazine and hover it over a gun and click will swap out the used magazine with the selected magainze. And for borgs clicking them with a battery will swap out their old battery as well. But now the magazine has to be manually taken out by right-clicking the gun and eject, then a new magazine may be inserted. For borgs, you have to go into the maintenance panel and click on remove battery button to remove the battery first, then insert a new one. Thus making things more complicated.  >

**Reproduction**

**Screenshots**

**Additional context**

**Comment by thebadman4662** [comment]
Same with defibs, centrifuge, electrolyze, cryo pods... In general swapping things is borked.

**Comment by lzk228** [comment]
i thought it was a feature.. and it was good feature!
