### ISSUE TITLE
Enter key creates newline instead of saving document

### ISSUE THREAD

**Issue by MACMAN2003** [space-wizards/space-station-14#25653]
## Description

When you're writing on a piece of paper, using the ENTER key does not save the document, instead it makes a newline.
**Reproduction**

get a pen, and a piece of paper, write something on it and press the enter key to save it
newline.
**Screenshots**

**Additional context**

for some reason ctrl+enter saves it, not sure why

**Comment by MACMAN2003** [comment]
i'd say that using shift+enter to make a newline is well known enough

**Comment by SphiraI** [comment]
> Unless someone can come up with a solution that gracefully allows both to coexist, we are forced to pick one of the two, and evidently there are situations where each is better than the other.

Would it be impossible to make it an editable keybind? Make the default what it was, but let people change it if they wish. As is now, a lot of people are seeing it as a bug, and not a feature.

**Comment by UbaserB** [comment]
this IS weird, huh.

**Comment by metalgearsloth** [comment]
https://github.com/space-wizards/space-station-14/pull/25853
