### ISSUE TITLE
CLF3 is missing form admin tools.

### ISSUE THREAD

**Issue by thebadman4662** [space-wizards/space-station-14#25658]
## Description
CLF3 is missing from chemicals to add to solution in container as admin.

**Reproduction**
Spawn container, debug, edit solution, type CLF3.

**Screenshots**
![obraz](https://github.com/space-wizards/space-station-14/assets/152504929/a43ef656-6fba-414c-b9c6-fbd7a0564fec)

**Comment by mirrorcult** [comment]
because its called chlorine trifluoride..

**Comment by mirrorcult** [comment]
the name is clf3 ingame, but im pretty sure this searches by ID, where it is `ChlorineTrifluoride`

**Comment by thebadman4662** [comment]
Its called CLF3 in guidebook and in chemmaster or other windows, including said debug tool once you pour it in.
