### ISSUE TITLE
Reverse engineer machine weak

### ISSUE THREAD

**Issue by UnicornOnLSD** [space-wizards/space-station-14#25679]
## Description
The reverse engineering machine exists, and no longers has ways to "upgrade" it's speed.
It also lacks an heat producing counterpart/upgrade, unlike the Ore processor, proto and autolathe.
It doesn't get as much uses but having an upgrade would overall just be nice 👍 

TL:DR, upgrade for the RE machine similar to the others ?

**Reproduction**
Look at RE machine
Slow
No way to make it faster

**Comment by EmoGarbage404** [comment]
Wrong repo
