### ISSUE TITLE
Fax machine print from text file doesn't appear to be logged

### ISSUE THREAD

**Issue by Chief-Engineer** [space-wizards/space-station-14#25694]
Feature introduced in #23262

Log should include:
- Person printing the file, labeled as "actor"
- Entity being printed, (the paper) labeled as "subject"
- Device used to print the paper, labeled as "tool"
- Text on the paper at the end of the log message with no trailing text/punctuation

Log type should be chat and severity should be low.

See how paper system logs writing, but imagine the paper is labeled "subject" instead of "entity":
https://github.com/space-wizards/space-station-14/blob/ba4188a8b4f1e268c193252e1151b548b2db6a0b/Content.Server/Paper/PaperSystem.cs#L161-L162

**Comment by metalgearsloth** [comment]
This also needs to include copying which has never been logged.

**Comment by noverd** [comment]
Ok, i do.
