### ISSUE TITLE
Spilling liquid out of a beaker instantly slips you

### ISSUE THREAD

**Issue by brndd** [space-wizards/space-station-14#2569]
Right-clicking on a beaker or other container and selecting "Spill liquid" to pour the liquid on the floor creates a puddle underneath you, and said puddle then instantly slips you even if you don't move.

Puddles created under stationary characters shouldn't slip them until they move.

**Comment by PaulRitter** [comment]
same issue with placing a soap under someones feet, should probably check for velocity before slipping
