### ISSUE TITLE
PDA modules

### ISSUE THREAD

**Issue by Injazz** [space-wizards/space-station-14#257]
PDA modules give your PDA additional functions.
I don't really remember what Urist meant by PDA modules, but it's definitely  something like Mail Module, Crew Manifest Module, Banking Module, Atmosphere Module, Uplink, Security/Medical/Employment Records Module, etc

**Comment by acvzy** [comment]
Moved [here](https://hackmd.io/96HHKT-VQ2KO91c9i75V8A?both#PDA-modules-2019-05-30-Injazz).
