### ISSUE TITLE
Bluespace/Invisible when teleported by Artifact

### ISSUE THREAD

**Issue by MasterFurrett** [space-wizards/space-station-14#25701]
So basically i've come to find a bug where if you get teleported by an artifact sometimes you would become invisible in certain places of the station. no one can see you. you basically become naked. and you're able to attack and move people around.

This can be fixed by getting teleported again, though has the outcome to break you again making you invisible in a different part of the station.

**Comment by destroyo123** [comment]
Can corroborate this issue. Just occured on Salamander to multiple different individuals.

Players are still able to manipulate inventory, and shift-clicking yourself shows you holding your items. You can still use your pockets and belt and backpack and such, even though you can't actually see any items there. 

Nor can anyone else see you while in that state, however you can pull things, grab (and store) things, open doors, and fully interact with the environment, despite zero visual cues of your existence.

I couldn't maesure the radius of the 'invisibility,' but it felt like 20-30 tiles?

**Comment by MasterFurrett** [comment]
here is the evidence (https://moon.spacestation14.com/replays/salamander/2024/02/29/salamander-2024_02_29-04_58-round_47652.zip)

**Comment by MissKay1994** [comment]
Corroborating this. Here's a video showing the "tears in reality" caused by this

https://github.com/space-wizards/space-station-14/assets/15877268/ac99251d-3b7a-4075-a601-0e4fa0b4957e

**Comment by hayitstheboi** [comment]
![20240229163840_1](https://github.com/space-wizards/space-station-14/assets/109502470/778cfe1d-3c5b-4e8c-977c-b23339a28b35)
this is me in RIFT mode

**Comment by thebadman4662** [comment]
> ![20240229163840_1](https://private-user-images.githubusercontent.com/109502470/308819907-778cfe1d-3c5b-4e8c-977c-b23339a28b35.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxOTE3MDQsIm5iZiI6MTcwOTE5MTQwNCwicGF0aCI6Ii8xMDk1MDI0NzAvMzA4ODE5OTA3LTc3OGNmZTFkLTNjNWItNGU4Yy05NzdjLWIyMzMzOWEyOGIzNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyOVQwNzIzMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZjJjNTBmNzRlNWNhOTI4ODJmNjAzZTdkMjIwNTBlZmQzNzMyN2YzYzYyMWU0MDQxM2ExMWIzMDkwYzc5YzdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Tv9ohDCz-bcNYiE1r95JQDuGfYAU9hKjXjvptWjQC2I) this is me in RIFT mode

https://github.com/space-wizards/space-station-14/issues/24842 Seeems like my kind of issue. 😦

**Comment by metalgearsloth** [comment]
Reading the code for all of the random teleports they just look broken to me so they either need removing or rewriting entirely.

**Comment by metalgearsloth** [comment]
Specifically RandomTeleportArtifactSystem and PortalArtifactSystem.
