### ISSUE TITLE
International Keyboard Alt Gr key issue

### ISSUE THREAD

**Issue by slarticodefast** [space-wizards/space-station-14#25747]
## Description

The Alt Gr key is a key on the german keyboard layout needed to type symbols like @ | { [ ] } \
The @ symbol is needed as a shortcut for emotes, others might be needed for playing borgs or labeling stuff.

When in the chat menu, pressing the Alt Gr key for 1-2 seconds without using a secondary key to type a character causes the game to be stuck in a weird state:
- Moving the cursor left and right moves it by word, not by character
- The chat menu cannot be left and the written text cannot be sent by pressing enter
- pressing the a key removes all written text
- The game settings cannot be clicked anymore and windows become unclosable
- This bugged state can sometimes be left by writing an @ sign, however i was not able to reproduce this consistently

**Reproduction**

Use a german keyboard and standard control settings. Type in the chat and press the Alt Gr key for 1-2 seconds. Just tapping it shortly does not cause this bug.
The operating system is Windows 10.
**Screenshots**

![keyboard_de](https://github.com/space-wizards/space-station-14/assets/161409025/ad8e3009-d546-483d-aa2c-7df2b9e98b20)

https://github.com/space-wizards/space-station-14/assets/161409025/b2229b61-ca7e-442c-8cf2-f3013a18c2d3

Edit: I seems like this is an issue for other international keyboards as well:

![grafik](https://github.com/space-wizards/space-station-14/assets/161409025/a5177495-5670-485b-afa7-f605e82cc4ef)

**Comment by lzk228** [comment]
just use qwerty :trollface:

**Comment by slarticodefast** [comment]
I did some more testing: Appearently the AltGr key is equivalent to pressing Alt and Ctrl at the same time. The control key gets stuck and pressing the control key once escapes the user from the bugged state.

**Comment by Errant-4** [comment]
This seems to only happen on Windows, though I also could not repro the "control stuck" behaviour _outside_ of Spess14, on Windows

**Comment by slarticodefast** [comment]
>This seems to only happen on Windows, though I also could not repro the "control stuck" behaviour outside of Spess14, on Windows

The AltGr key is a modifier key with no further effects once you stop pressing it. Outside the game it works as intended for me.

**Comment by slarticodefast** [comment]
Seems to be fixed now :)
No idea what was changed to do so
