### ISSUE TITLE
Sentient Artifacts That Become Storage Lose Activate Node Action

### ISSUE THREAD

**Issue by jrdensmore** [space-wizards/space-station-14#25755]
## Description
Upon becoming a storage container as a sentient artifact, you lose the action to activate your node. It is not in Actions Menu and does not re-appear on rejoin.

**Reproduction**
Be sentient artifact, have node that turns you into storage activate

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/9053754/9a8a81fa-6c91-4341-8d76-2e91fe46d5a8)

**Comment by slarticodefast** [comment]
Fixed by #33171
