### ISSUE TITLE
Can't put flasks into the booze dispenser anymore

### ISSUE THREAD

**Issue by Hanzdegloker** [space-wizards/space-station-14#25776]
## Description

We could  put flask into the dispensers for the longest time, all the sudden I cannot? How will I top off the detective's flask?

Vacuum flask as well as bar flask can no longer be inserted

**Reproduction**

Attempt to be a bartender

**Screenshots**

![image (1)](https://github.com/space-wizards/space-station-14/assets/41141796/4d3103f8-dd3f-4ce9-9e93-49f43bace88b)

**Additional context**

**Comment by Tayrtahn** [comment]
Looks like #25450 removed FitsInDispenser from DrinkBase (with good reason), and flasks were inheriting the component from there.

Fixing this should be as simple as adding FitsInDispenser to FlaskBase.
