### ISSUE TITLE
Firelocks act like they can be opened when they require a crowbar

### ISSUE THREAD

**Issue by Plykiya** [space-wizards/space-station-14#25788]
## Description

Previously when you tried to open a firelock that was unpowered, it would make no sound indicating you had to crowbar it. If you try to open a firelock now, it will make a "fwoosh" sound as if it was being opened, and you will be able to move into it for a fraction of second, but it will never open because it requires a crowbar.

**Reproduction**

1. Unpower a firelock door
2. Try to spam it open with E or click it
3. Actually open it with a crowbar instead

**Screenshots**

**Additional context**

**Comment by deltanedas** [comment]
i hate firelocks

**Comment by notquitehadouken** [comment]
client/server desync my beloved

**Comment by NakataRin** [comment]
One more thing to note: if your ping is high enough, you can look through the non-glass firelock for half a second, which can be abused

**Comment by Plykiya** [comment]
[25812] possibly related
