### ISSUE TITLE
Trying to open a locked firelock without a crowbar results in the opening noise but doesn't actually open

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#25805]
## Description

You can spam click it and there's this obnoxious firelock opening noise and there's no delay. Also, it shouldn't make an opening noise if its not actually opening.

**Reproduction**

- have something dangerous on the other side of the airlock like burning plasma
- have no access to open firelocks, like a passenger id
- left click the firelock
- watch as you can spam the noise.

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/134914314/f956707f-7f2c-464e-9466-015e200b8828)

**Comment by K-Dynamic** [comment]
Firelocks be rather wonky

**Comment by deltanedas** [comment]
fuck firelocks all my homies hate firelocks

**Comment by Plykiya** [comment]
#25788

you even commented on the same issue!
