### ISSUE TITLE
Bolted (command?) doors, once out of view, lose their bolt light

### ISSUE THREAD

**Issue by Plykiya** [space-wizards/space-station-14#25812]
## Description

I bolt my bedroom doors as CE. I walk away. I walk back and can't open my room despite the bolt lights being off. I check the wires, bolt light intact. I toggle the bolt with my remote, the light works again. 

**Reproduction**

**Screenshots**

**Additional context**

**Comment by Golinth** [comment]
I’ve had this happen with sec and engi doors recently, so I think type doesn’t matter.
