### ISSUE TITLE
Space Heater Locked Temperature on new grids

### ISSUE THREAD

**Issue by HolySSSS** [space-wizards/space-station-14#25827]
## Description
On any new grids created through command mapping or "Send to Admin Arena" the space heater manages to change the temperature of only one tile, not the whole room.

**Reproduction**
Be Admin Ghost!
Use "Send to Admin Arena" or Mapping to create a new map with atmosphere, whatever you prefer.
Don't forget to Mapinit the new map created through Mapping command!
Set up a Space Heater and turn it on.
Use Gas Analyzer or showatmos, whatever you prefer.
Observe that the room temperature doesn't change, only the tile with the space heater.
Attempt to remove the space heater, nothing changes as well.

**Screenshots**
![Image1](https://github.com/space-wizards/space-station-14/assets/81934438/3445ecff-3b04-4628-9f07-918cca0ac5d4)
![Image2](https://github.com/space-wizards/space-station-14/assets/81934438/32590828-9d11-4e07-bd7f-8ff99e7825c3)

**Additional context:**

**Attempts to fix the original grid**
Introduction of any new tiles for atmosphere does not change anything.
Making a hole or a lattice to space the whole room does not change anything.
_Fixgridatmos on a new map does fix this problem only for built space heaters._

**Checking manual creation of grids**
Creating a new grid manually on the starting map does not lead to this problem.
Creating a new grid manually on a new map does not lead to this problem.

**Comment by HolySSSS** [comment]
Here's a video reproduction on the latest version of the local server build.

Notice the stop of temperature change after another fixgridatmos. 

https://github.com/space-wizards/space-station-14/assets/81934438/94301411-2eaf-4f6d-a81a-092a43306546

**Comment by Menshin** [comment]
Ok, i see now what's going on. Thanks.
