### ISSUE TITLE
Menu button icons are not centered.

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#25852]
## Description
Very small mis-alignment since that big update that put all the ui a little out of alignment. See screen caps the icons are no longer centered in the ui button. Have a reference to an old one too.

**Reproduction**
Look at the top menu buttons and die inside a little.

**Screenshots**
Old, aligned icons on the buttons:
![image](https://github.com/space-wizards/space-station-14/assets/47093363/8a106df5-d0e9-4033-9439-bffaa14784ef)

Scuffed current version:
![image](https://github.com/space-wizards/space-station-14/assets/47093363/93b2b202-1514-4e6d-9187-d250c8d2a65e)

**Additional context**
NA

**Comment by metalgearsloth** [comment]
https://github.com/space-wizards/RobustToolbox/pull/4937 fixes probably?
