### ISSUE TITLE
Escape pods having.. various issues

### ISSUE THREAD

**Issue by deepdarkdepths** [space-wizards/space-station-14#25850]
Clipping, going absolutely berserk, etc.

https://github.com/space-wizards/space-station-14/assets/155149356/efb29f27-2634-40cb-8304-9aed00c68999

![image](https://github.com/space-wizards/space-station-14/assets/155149356/975738ee-2652-4c08-ba6f-5494c56f97f7)

**Comment by metalgearsloth** [comment]
got any more info
