### ISSUE TITLE
Station map UI controls are overlapping/ Broken

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#25851]
## Description
On UIs that use the map component the map toolbar/control panel for them are broken/overlapping. See screencaps.

**Reproduction**
Open any of the following:
- Station map
- Power Monitoring
- Crew monitor

**Screenshots**
<img width="1460" alt="image" src="https://github.com/space-wizards/space-station-14/assets/47093363/e2382589-9648-4852-a380-2a1fcfbd1b53">

**Additional context**
NA

**Comment by metalgearsloth** [comment]
I'll suss it out think I know where it was.
