### ISSUE TITLE
Some sounds stop abruptly when played with AudioSystem

### ISSUE THREAD

**Issue by Injazz** [space-wizards/space-station-14#259]
For example, this sound will stop halfway for some reason.
https://github.com/tgstation/tgstation/blob/master/sound/effects/suitstep1.ogg
Issue was replicated with AudioSystem.

**Comment by Injazz** [comment]
FUCK STEREO

**Comment by Sauberstaub** [comment]
2 channels is way to much. imagine using 2 channels, learn2optimize.

> 
> 
> FUCK STEREO

**Comment by PJB3005** [comment]
OpenAL doesn't seem to like stereo audio at least positionally. I implemented a warning for this with 58ac8f0dba4630326b47987025ccab1a1c1c6a65.

I'm too lazy to test whether this is an issue for stereo audio played back globally though. Let's hope it isn't.

**Comment by SweptWasTaken** [comment]
Is this really an issue or is it more a """feature""" of the engine. In my tests stereo .ogg files do not play well with anything in SS14. We should just warn people to convert their stereo .ogg files to mono before using them.
