### ISSUE TITLE
Damage flash effect gets stuck sometimes

### ISSUE THREAD

**Issue by Slava0135** [space-wizards/space-station-14#25904]
## Description

**Reproduction**

Hit someone fast enough, there is chance their sprite will remain red forever
**Screenshots**

**Additional context**

**Comment by deltanedas** [comment]
as a borg i had a shitter try to kill me over being red, red = valid

**Comment by Slava0135** [comment]
red = syndicate agent

**Comment by MACMAN2003** [comment]
caught this on video: 

https://github.com/space-wizards/space-station-14/assets/20659419/bdd3486b-70a5-4487-8e79-7e2f627f6b4b

not sure if this is related but this occured after i had tabbed out (exclusive fullscreen ew)

**Comment by Slava0135** [comment]
i am pretty sure its server-side, re-logging doesn't fix it

**Comment by MACMAN2003** [comment]
what about restarting the client?

**Comment by Slava0135** [comment]
i set animation length to 0.1 and used minigun, pretty consistent now, make sure you stop shooting for short periods of time. I think you need to hit at the same exact moment old animation stops.

**Comment by Slava0135** [comment]
set animation length to 0.07 (minigun firerate is 15 per second = 0.06666... sec between shots) and you get the effect in few seconds of shooting

**Comment by Slava0135** [comment]
pretty sure it is caused by #23553
