### ISSUE TITLE
Arrivals not docking.

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#25901]
## Description
Sometimes arrivals is not docking, players panic and aHelp generating quite a few aHelps, they get teleported to arrivals on the ship departing again so not too impactful.

**Reproduction**
I don't really have any yet... Will update if one comes up.
It seems intermittent, have not found root cause.
Last seen on meta, nothing blocking the arrivals area.
There was a slight station rotation, as in it was drifting a bit.

**Screenshots**
<img width="1001" alt="image" src="https://github.com/space-wizards/space-station-14/assets/47093363/f5614da8-5502-42e7-be7c-23248a492bba">
![image](https://github.com/space-wizards/space-station-14/assets/47093363/39605dbd-0c9c-4ab1-9ca4-527509aeb541)

**Additional context**
NA

**Comment by metalgearsloth** [comment]
Sounds like it might be GetDockingConfigAt probably needs to be less stringent.
