### ISSUE TITLE
Diagonal structures has half the tile depressurized despite the room being pressurized

### ISSUE THREAD

**Issue by deepdarkdepths** [space-wizards/space-station-14#25924]
1. Stand next to a diagonal structure
2. Use gas analyzer
3. Does not show pressure or gases in the room.

![image](https://github.com/space-wizards/space-station-14/assets/155149356/64002634-f0c8-4fb0-8dbd-01adcede644b)

**Comment by deepdarkdepths** [comment]
Been told that if you stand in that area of the tile, you will also start taking pressure damage and gasping. So it isnt just visual with the gas analyzers, it seems.

**Comment by Golinth** [comment]
I can confirm. The diagonal windows around HoP’s office on Train cause pressure damage when standing in them
