### ISSUE TITLE
2+ stations maps bugs

### ISSUE THREAD

**Issue by TheShuEd** [space-wizards/space-station-14#25942]
## Description
maps with more than 1 station, has the following error:
Having unique roles on stations that do not exist on other stations has a chance to break the logic of role distribution between players

none of the players may get this unique role and they will all stay in the lobby or become greytide, although the role will remain free.  

**Reproduction**
1. create a map with multiple stations.
2. Add a unique role to one of the stations that does not exist on the other station
3. Open 4 clients and connect to server
4. trying to get that unique roles all the clients (QM, CMO, CE and HOP for example)
???
some clients will remain in the lobby, although vacant roles for them exist at some stations

**Comment by K-Dynamic** [comment]
You can have multiple stations per map?

God forbid nukies have to choose which one to nuke
