### ISSUE TITLE
Climbing `CanVault` check is nonsense and can be bypassed

### ISSUE THREAD

**Issue by LordCarve** [space-wizards/space-station-14#25951]
## Description

In the `ClimbSystem`:
1. `CanVault` requirements are nonsense.
2. Using Vault verb bypasses `CanVault`.

Point 2. is self-explanatory.
**Point 1. needs a decision.** Currently the user needs a leg or (!) a foot in order to be able to vault which IMO is a total nonsense.
Vaulting is just renamed climbing (climbing when user is initiating the climb by themselves), and doesn't really have anything to do with legs or feet. Some creatures without legs or feet are able to climb (Slimes), and also some creatures with legs or feet cannot climb (Cockroach). Whether a creature can initiate climb on its own (vault) should be separate from having bodyparts[^1].

IMO it should be a separate "can climb on its own" bool data field in the `ClimbingComponent` and thus defined per prototype. Checking for foot or leg doesn't make sense.

### **Please preferably do not make a PR to fix point 2. before point 1. is fixed. Fixing both at once is fine.**
Fixing point 2. alone is easy but it also makes everything that hasn't got a foot or leg unable to vault, which surprisingly means disabling a lot of gameplay (looking at you, ghost roles).

[^1]: In the future - if anyone ever implements dismemberment - things like requiring body parts in order to climb could be supported, but that still should be a per-prototype setting. I.e. a humanoid can't climb without feet, but a slime can.

**Comment by Tayrtahn** [comment]
Point 2 is fixed by #24977, and I'll look into adding in a fix to point 1 as part of it.

**Comment by Tayrtahn** [comment]
Here's my plan:
- The presence of ClimbingComponent makes an entity able to be placed on surfaces like tables.
- ClimbingComponent.CanClimb controls whether it can climb onto surfaces by drag-drop or verb.
- ClimbingComponent.CanForceClimb controls whether it can move other entities onto surfaces.

Both fields default to `true`, but of course can be set false for entities that shouldn't have one or both.

It looks like the only prototypes with ClimbingComponent are BaseMobSpecies, SimpleSpaceMobBase, and BaseMobArgocyte, which seems like a bit of an odd arrangement, but I guess I'll keep it as is.
