### ISSUE TITLE
Shields can block asphyxiation damage.

### ISSUE THREAD

**Issue by Callmore** [space-wizards/space-station-14#25966]
## Description
Shields are able to block and mitigate asphyxiation while also not taking damage themselves. This means just holding a shield in your hand halves damage from not breathing, and raising it completely negates it, meaning you can just stand outside forever! No need to worry about oxygen, the shield doesn't care.

**Reproduction**
1. Get any shield
2. Suffocate
3. Congratulations you have found the secret to not dying outside

**Screenshots**
https://github.com/space-wizards/space-station-14/assets/22885888/5320c1ee-534a-4351-9680-63da4c49a3a5

**Additional context**

**Comment by Tayrtahn** [comment]
Hilarious. Bug of the year candidate?
