### ISSUE TITLE
Improve the placing of items in lockers. 

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#2596]
Placing items into lockers by clicking with the entity in hand is annoying, as with more than 3 items in the locker, it's hard to find a free "locker pixel" to click to place the entity onto. Another gripe is that sometimes placing entities on the locker and closing it will not close the items in the locker, as they were placed out of the bb of the locker.

Intended behavior: Clicking on any pixel of an open locker with an entity should always place the entity in the center of the locker.

Lockers currently have a `PlaceableSurface` component, which needs to retain functionality for tables, so you'll have to create a new component for this.

Instead of this.
![image](https://user-images.githubusercontent.com/49448379/99854378-9f17ac80-2b7c-11eb-98db-c002dcee5ef5.png)

It should look like this.
![image](https://user-images.githubusercontent.com/49448379/99854443-ba82b780-2b7c-11eb-95b5-d24637222cdc.png)

**Comment by BananaFlambe** [comment]
What if we add an offset attribute to the component that can be specified in the .yml file? If it's not set use ClickLocation, otherwise WorldPosition + Offset.
