### ISSUE TITLE
ServerNotifyManager tries to call component on a deleted entity

### ISSUE THREAD

**Issue by ghost** [space-wizards/space-station-14#2600]
Discovered and pic taken by Manel. Occurred after deleting clothing(?)
Error: Robust.Shared.Utility.DebugAssertException: 'Tried to get component on a deleted entity.'
![image](https://user-images.githubusercontent.com/32942106/99879248-31e23680-2bd1-11eb-8e6f-c895c280ea38.png)

**Comment by mirrorcult** [comment]
popup has been pretty much entirely refactored and the code that exists now does deleted checks in the update loop so
