### ISSUE TITLE
Throngler rsi file needs cleanup

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#26023]
## Description

There are two throngler files. Depending on if it's used or not, they should be merged or one should be deleted.
Located in Objects\Weapons\Melee.

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/134914314/b4a9752a-5e95-45e4-9213-18cde1a9e1a5)

**Comment by EmoGarbage404** [comment]
yeah this is not an issue

**Comment by UbaserB** [comment]
huh...
