### ISSUE TITLE
Can't FTL to Nukie planet.

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#26028]
## Description
Once the nukie shuttle warps to the station area its not possible to scan the location to go back see the screen caps for missing planet bit.

**Reproduction**
- warp nukie shuttle to station area
- try get back.

**Screenshots**
Before FTL to station zone:
![image](https://github.com/space-wizards/space-station-14/assets/47093363/7597a327-1cf8-42a9-b07d-99c1bb46ec30)
When in the station zone
![image](https://github.com/space-wizards/space-station-14/assets/47093363/194e0c36-2fcc-4366-b81c-29762b6ae222)

**Additional context**
NA

**Comment by Brandon-Huu** [comment]
Does anyone plan on solving this?

**Comment by potato1234x** [comment]
also i dont think its possible to ftl to centcomm when the round ends in a shittle
