### ISSUE TITLE
Add more types of suicides

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#2604]
When a player uses the suicide command it'll do something context sensitive near them (e.g. stick their head in a microwave). Having more types would be nice. The interface to use is ISuicideAct

**Comment by SweptWasTaken** [comment]
Would be cool if there was an actual UI thing for suicide. Even typing suicide in the text chat would be better than doing it in the console.

**Comment by PaulRitter** [comment]
https://www.youtube.com/watch?v=qkIf9M7G3vA
