### ISSUE TITLE
Marathon's Oxygen and Nitrogen miners have incorrect MaxExternalPressure values

### ISSUE THREAD

**Issue by MjrLandWhale** [space-wizards/space-station-14#26059]
## Description

The N2/O2 miners on Marathon station are set to a MaxExternalPressure of 300kpa instead of the standard 4500kpa used on all other stations. Over time this leads to a depletion of these gases (due to burn chamber/TEG useage and general spacings).

**Reproduction**

Spin up Marathon station and check the MaxExternalPressure value on the N2/O2 miner's GasMiner component. You can also remove the gas from the miner's chamber and gas analyze to see it stall out well below 4500kpa.

**Screenshots**

**Additional context**

**Comment by Brandon-Huu** [comment]
Are you planning on fixing this?

**Comment by MjrLandWhale** [comment]
Its a mapping issue and I dont know how to control how those variables are set per-map. The extent of my knowledge is "The code says the MaxExternalPressure is 6500, stations are somehow supposed to have 4500, and Marathon is at 300."
