### ISSUE TITLE
ReagentUnit can be negative

### ISSUE THREAD

**Issue by brndd** [space-wizards/space-station-14#2605]
I fail to see when a negative amount of a reagent would ever be useful and this could potentially lead to wildly unexpected behaviour or crashes, so I think it's a big bad idea.

To test, just spawn in a memory leek and check out its SolutionContainerComponent.

![2020-11-22_092932](https://user-images.githubusercontent.com/5822375/99897923-43e1d900-2ca6-11eb-986b-7619c2568068.png)

**Comment by Ygg01** [comment]
> I fail to see when a negative amount of a reagent
Anti-matter!!! I kid ofc.

**Comment by metalgearsloth** [comment]
I think we can close this? PJB said they also represent a change in units (mainly to specify rates?)

**Comment by brndd** [comment]
Yeah this only happens when things overflow as with the memory leek item so it's not really an issue.
