### ISSUE TITLE
quickequip something in container drops it outside of container

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#26061]
1. be in locker
2. take lantern
3. press Shift+E
4. lantern drops over the locker
5. try again via clicking on belt slot with lantern
6. it works

**Comment by deltanedas** [comment]
i had this happen outside of container too it dropped my tools on the floor, might be ping related when clicking and shift e close to eachother

**Comment by lzk228** [comment]
fixed at some point
