### ISSUE TITLE
Limbs, limb damage

### ISSUE THREAD

**Issue by Injazz** [space-wizards/space-station-14#261]
The part of mob health system which doesn't need reagents (which are still in development).
Basically, any Damage to mob should concentrate or spread on some of the mob's limbs. Limbs have separate thresholds and may cause different effects depending on which threshold is reached. For example - hand damage would cause you to drop items after some time when the damage is severe, eye damage would make you blind, feet damage would make you slower.
Probably the logic should be made in Species Component, and additional List with limb's thresholds should be added as well. What do you think?

**Comment by acvzy** [comment]
Moved [here](https://hackmd.io/96HHKT-VQ2KO91c9i75V8A?both#Limbs-2019-06-06-Injazz)
