### ISSUE TITLE
What's the story with the map loading?

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#2613]
It's pretty confusing where to specify the map file to load. 

We have server_config.toml, the MapFile string in GameTicker.cs, and a cvar. 

Just make it a config file only thing, because as of right now, changing it in the GameTicker and the server_config.toml doesn't stop saltern from loading.

**Comment by exp111** [comment]
The MapFile String was removed in [this commit](https://github.com/space-wizards/space-station-14/commit/2ded2163fede02574e4adece29402b2640d086c3).
So only the CVar should be the one to define the map.
The `server_config.toml` just sets cvars.

**Comment by PaulRitter** [comment]
Discussion? I find this very straight-forward tbh. just edit the server_config.toml that sets the cvars

**Comment by exp111** [comment]
Imo just keeping it open if someone/swept finds that it really won't read from the cvar or there is some other problem

**Comment by SweptWasTaken** [comment]
Not an issue/I don't care.
