### ISSUE TITLE
Hotbar actions are still bugged

### ISSUE THREAD

**Issue by thebadman4662** [space-wizards/space-station-14#26142]
## Description
Hotbar action with no cooldown trigger twice, effectively never working like PDA flashlight turning on and off, mask being put off and on, harm mode being turned on and off...

**Reproduction**
1. Equip actions on your hotbar
2. Click them with mouse.

**Screenshots**
https://youtu.be/S0lTa1iBq80

**Comment by wrexbe** [comment]
What did you do to your control shortcuts?

**Comment by Errant-4** [comment]
> ## Description
> 
> Hotbar action with no cooldown trigger twice, effectively never working like PDA flashlight turning on and off, mask being put off and on, harm mode being turned on and off...
> 
> **Reproduction**
> 
>     1. Equip actions on your hotbar
> 
>     2. Click them with mouse.
> 
> 
> **Screenshots** https://youtu.be/S0lTa1iBq80

Can you please check Options/Controls and show what you see in the second column of bound keys

**Comment by thebadman4662** [comment]
![obraz](https://github.com/space-wizards/space-station-14/assets/152504929/3be24afc-efd6-4dc2-a60f-d4eaf7c09fb2)

**Comment by Errant-4** [comment]
Is this the steam version or a branch? Are you up to date? I was not able to repro the issue. Can anyone? Difficult to come to any conclusions without being able to trigger the issue

**Comment by thebadman4662** [comment]
Steam version, wizden servers.

**Comment by Errant-4** [comment]
As a test, can you press Reset next to "Use", and see if this resolves the issue?

**Comment by thebadman4662** [comment]
It did work... 

Which is weird considering I had the bug for months and even had to fully reset keybinds because of recent hotkey bug. Time to see if it works on rebooting.

**Comment by Errant-4** [comment]
When you reboot, is shift+click bound as the secondary again, and the reset button is active again? I think your keybind file might be corrupted and maybe isn't properly saved. You could rename keybinds.yml to keybinds_backup and let the system generate a new file. If it does not fix your problem you can rename your previous file to keybinds.yml

**Comment by thebadman4662** [comment]
Use bind itself only matters, secondary bind or lack of it on reboot does not have any impact.

**Comment by wrexbe** [comment]
If you still have it, or can get it to happen again, can you upload your binding file?

**Comment by thebadman4662** [comment]
And I got the exact same bug again by setting same binds from scratch as last time, previous binds file was deleted so its not any kind of corruption of it.

My hotkeys:
![obraz](https://github.com/space-wizards/space-station-14/assets/152504929/42985962-3c7b-4e32-ae8d-01b4a22f88b1)
![obraz](https://github.com/space-wizards/space-station-14/assets/152504929/ed56697f-3dee-4f25-9ec3-5936ed25820e)
![obraz](https://github.com/space-wizards/space-station-14/assets/152504929/0172d02c-2bf1-4744-9bf0-e27ee9ae15b3)

**Comment by EmoGarbage404** [comment]
Did you turn off/on numlock or smth

**Comment by wrexbe** [comment]
@thebadman4662 Upload the actual file with the attach button (looks like a paper clip). I tried manually setting my keybindings to yours, maybe I messed it up, but I couldn't get it to happen.

1. What OS are you using, and does your keyboard, mouse, or a program on your computer have any kind of special macro/key things going on?

2. If you slowly reset the keybindings to default, which keybinding does resetting stop the problem on?

**Comment by thebadman4662** [comment]
> @thebadman4662 Upload the actual file with the attach button (looks like a paper clip). I tried manually setting my keybindings to yours, maybe I messed it up, but I couldn't get it to happen.

![obraz](https://github.com/space-wizards/space-station-14/assets/152504929/15f90ff7-71e5-42fa-a37c-6ae8419d2b40)


> 
>     1. What OS are you using, and does your keyboard, mouse, or a program on your computer have any kind of special macro/key things going on?
> 

Windows 10, no funny bussiness on my hardware.

>     2. If you slowly reset the keybindings to default, which keybinding does resetting stop the problem on?
> 

Went from bottom, "close recent window" can't be reset.
![obraz](https://github.com/space-wizards/space-station-14/assets/152504929/1f102bc3-5dbc-4eab-bee5-a103789af4d8)


Resetting move stored item or rotate stored item allowed me to use hotbar without touching use binds.
![obraz](https://github.com/space-wizards/space-station-14/assets/152504929/b13e00de-8698-4f97-ae11-9ec278031fea)



>     3. It may be a bad interaction with a different setting, do you have any other settings not the default?

I do not think so? Other than hotkeys I did not need to change anything except maybe MIDI sound when musicians are giving me ear cancer ever now and then.

**Comment by wrexbe** [comment]
Can be reproduced with this yml.
Current theory is some kind of problem with most bindings being priority 0's, and the user binding changing the order they get put into the list, and the new order happens not to work.
There are other weird things going on, but if the binding order/priority is maintained, maybe we can just pretend I didn't see anything.

```
version: 1
binds:
- canFocus: True
  key: MouseLeft
  function: MoveStoredItem
- canFocus: True
  key: MouseLeft
  function: Use
leaveEmpty: []
...
```

**Comment by thebadman4662** [comment]
Bug still present and even pointing at things requires rebind now.
