### ISSUE TITLE
Zombies cannot be stripped

### ISSUE THREAD

**Issue by TurboTrackerss14** [space-wizards/space-station-14#26144]
## Description
Zombie corpses cannot be stripped/looted. 

**Reproduction**
>be player
>find dead zombie
>try to steal loot
>cannot take items
No doafter, no nothing.

**Screenshots**

**Additional context**

**Comment by TurboTrackerss14** [comment]
unconfirmed report that this might also be affecting regular dead players.

**Comment by Krunklehorn** [comment]
Probably mine Just woke up, all strip related bugs are probably my fault, taking a look at it now.

#25994

**Comment by Dutch-VanDerLinde** [comment]
close this NOW
