### ISSUE TITLE
Stripping menu on animals does not work

### ISSUE THREAD

**Issue by Dutch-VanDerLinde** [space-wizards/space-station-14#26145]
## Description

**Reproduction**
- try to put mask onto animal or take
- nothing happens

**Screenshots**

**Additional context**
Tested with walter the dog

**Comment by Dutch-VanDerLinde** [comment]
i see an issue that doesnt let zombie strip either, so it probably just doesnt let you strip things without hand components

**Comment by Gyrandola** [comment]
Can confirm. 
Does work on monkeys though.

**Comment by Krunklehorn** [comment]
Just woke up, all strip related bugs are probably my fault, taking a look at it now.

#25994
