### ISSUE TITLE
Outdated usages of floor_carpet

### ISSUE THREAD

**Issue by DrSmugleaf** [space-wizards/space-station-14#2615]
https://github.com/space-wizards/space-station-14/pull/2141 removed the floor_carpet tile and made it an entity, Maps/Test/Pathfinding and Maps/Test/3by3-20oxy-80nit still have it serialized. Neither currently crash because 3by-20oxy-80nit.yml doesn't use them and simple.yml isn't loaded anywhere, but boxstation in #2105 does.

**Comment by SweptWasTaken** [comment]
So did you make an issue about my PR instead of just writing a comment on my PR.

**Comment by DrSmugleaf** [comment]
> So did you make an issue about my PR instead of just writing a comment on my PR.

If your box station pr is supposed to also fix 3by3-20oxy-80nit.yml and simple.yml then yes.

Also https://github.com/space-wizards/space-station-14/issues/2422

**Comment by metalgearsloth** [comment]
Nuke my pathfinding map as it's old af (pre-atmos and pre-gravity) and needs an update (one day I was gonna use it for benchmarking tm).
