### ISSUE TITLE
carp plushie is guaranteed in maints locker

### ISSUE THREAD

**Issue by Dutch-VanDerLinde** [space-wizards/space-station-14#26155]
## Description

**Reproduction**
- spawn maints locker
- notice how it will always have a carp plushie inside

**Screenshots**

**Additional context**
seems weird for maints loot, probably because of orGroup for carp

**Comment by Dutch-VanDerLinde** [comment]
> is there a way to have it only spawn 1 carp plushie but have it not guaranteed, if you just remove orgroup it can have multiple different carp plushies

this is how syndie maints loot does it
![image](https://github.com/space-wizards/space-station-14/assets/45323883/4cbdde13-fe00-486b-8340-cf603ad64fbc)

**Comment by deltanedas** [comment]
ooooooh thats easy fix then

**Comment by Ilya246** [comment]
feature billions must carp
