### ISSUE TITLE
Admins get admin logout notification for non-admin players.

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#2616]
Instead of only showing when an admin logs out.

**Comment by Nukeuler123** [comment]
Can you elaborate on the problem a bit more? You worded it a bit weirdly

**Comment by Zumorica** [comment]
> Can you elaborate on the problem a bit more? You worded it a bit weirdly

When you're an admin, you get messages saying when other admins log in or out.
Currently, the notification for when other admins log out is broken, as it notifies whenever ANY player, regardless of whether they're admin or not, logs out.
