### ISSUE TITLE
Agent Ids are Borken

### ISSUE THREAD

**Issue by Geekyhobo** [space-wizards/space-station-14#26169]
## Description

Poor nukies cannot buy them, it takes their tc and doesnt spawn the id card, the card cannot be spawned on the nukie planet either, however it can be spawned in the Admin testing area?

**Reproduction**

try buy id, no work scam your tc

**Comment by Titian3** [comment]
I did a couple more tests and it appears you can buy them everywhere except for the nukie base grid....
![image](https://github.com/space-wizards/space-station-14/assets/47093363/aaaf86bc-f69c-4cb9-9c82-1b6f948abd2a)
Can place it on the space but not on the platform.

**Comment by deltanedas** [comment]
might be logging an error when initializing it and failing to spawn

**Comment by deltanedas** [comment]
>aghost doesn't work due to MapInit on PresetIdCard.

probably

**Comment by VasilisThePikachu** [comment]
Closed by #26195
