### ISSUE TITLE
Certain announcements don't play sounds like they're supposed to 

### ISSUE THREAD

**Issue by baddiePRO** [space-wizards/space-station-14#26186]
## Description
when certain station wide announcements are sent, they do not play the bell sound like they are supposed to, also applies to the soundbytes for antag roles

**Reproduction**
join round, wait for command/centcomm/antag message in chat

**Comment by Dutch-VanDerLinde** [comment]
dupe of https://github.com/space-wizards/RobustToolbox/issues/4970, should be fiexd next update

**Comment by baddiePRO** [comment]
awesome, thanks
