### ISSUE TITLE
Skeletons are immune to saw blunt damage

### ISSUE THREAD

**Issue by thebadman4662** [space-wizards/space-station-14#26189]
## Description
Was testing how much milk heals and which milks do, noticed skeletons not taking blunt damage which you would expect least as immunity out of 3...

**Reproduction**
1. Attack skeleton with circular saw, or other similiar weapon with many different damage types including blunt.
2. Scan their health

**Screenshots**
![obraz](https://github.com/space-wizards/space-station-14/assets/152504929/1dbbbc9c-265e-4a1a-8c26-cf051ef0b041)

**Comment by nikthechampiongr** [comment]
This appears to be intended, skeletons have a flat reduction of 5 for blunt damage. The advanced circular saw does 5 units of blunt, 5 pierce, 5 slash. The blunt gets cancelled out by the reduction.
