### ISSUE TITLE
the operatives were: issue

### ISSUE THREAD

**Issue by Dutch-VanDerLinde** [space-wizards/space-station-14#26197]
## Description
![image](https://github.com/space-wizards/space-station-14/assets/45323883/91ab9a21-08bf-4c78-930f-7dbf9ca64b2e)

**Reproduction**
this appears in the round summary screen of every gamerule, during nukies it doesnt display the names of the operatives, just

The operatives were:

**Comment by VasilisThePikachu** [comment]
dupe
