### ISSUE TITLE
Pulling another player disables a bunch of collisions for players

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#2619]
And makes you immune to bullets, along other things.

**Comment by 20kdc** [comment]
This bug seems elusive. We saw it happen on the SSS last night, but...

**Comment by 20kdc** [comment]
The cause of the bug was located thanks to Eris Starmaster (in-game name, "Eris" OOC):
It's not soap, but caused by one player pulling another player.
Told by @Zumorica to ping @DrSmugleaf

**Comment by 20kdc** [comment]
Further experimentation suggests the bug *might* be more specific to when pulling is cancelled via distance.

**Comment by Erisfiregamer1** [comment]
I prove this finding. The easiest way to execute the bug is to get the person you are dragging stuck on a corner and have them stop being pulled, and their airlock collision is &*@#d.
