### ISSUE TITLE
Origin medbay issues

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/space-station-14#26220]
* LV wiring is a mess. Chemistry + cryo + treatment center + huge chunk of maint + lobby is all covered by one APC, this makes PACMANs unusable. Storage is covered by primary hallway APC.
* No cell charger
* There shouldn't be a crew monitor console in the main treatment center
* Useless "body scanner" console in what I guess is the paramedic's room?
* Why does cryo use a non-standard layout with TWO freezers instead of one?
* Chemfridge doesn't connect between chemistry and the exterior room.
* Need more NanoMeds
* Why does virology deserve its own substation?
* Actually why does medbay have THREE substations, not even counting the virology one?
* Can I point out that the loud big crew sensor server is in the CMO's BEDROOM
* half of the CMO's office doesn't have power
* The "maintenance" airlock in surgery should not go into the CMO's bedroom, it needs to be real maintenance access.
* There's an APC that covers exclusively maintenance but is visible from the "paramedic" room with the two stasis beds, which is confusing.

**Comment by brainfood1183** [comment]
cryo uses 2 freezers 1 for each cryopod, they have separate pipe structures so can be set different temperatures to each other.

**Comment by Golinth** [comment]
Also, this chem windoor is not locked to chem. Meaning any shitter can just hop the counter and get in 

![image](https://github.com/space-wizards/space-station-14/assets/22528949/7ba52ab6-fa2a-498a-ab5f-f611af8a312e)

**Comment by brainfood1183** [comment]
> Also, this chem windoor is not locked to chem. Meaning any shitter can just hop the counter and get in
> 
> ![image](https://private-user-images.githubusercontent.com/22528949/313561422-7ba52ab6-fa2a-498a-ab5f-f611af8a312e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NjQyMzIsIm5iZiI6MTcxMDc2MzkzMiwicGF0aCI6Ii8yMjUyODk0OS8zMTM1NjE0MjItN2JhNTJhYjYtZmEyYS00OThhLWFiNWYtZjYxMWFmOGEzMTJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDEyMTIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyMjUwNzhkMjdkN2M1ZTBlZjI4NGE2MWE2Y2NjMDE3NmU2MjBjNmZkMzIzOWEwMWFhNTZiYWUwOTQ2OTQ4NTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nyjtUSIItcO8VK0hcTs6ia2rYAAbkLn1UBdtCb8YrbI)

i fixed that in next update, thanks for posting
