### ISSUE TITLE
Syndicate clown bundle borken

### ISSUE THREAD

**Issue by Hmeister-real** [space-wizards/space-station-14#26228]
## Description
Buying it simply drops the items to the floor, with a lot missing, and no bag
h
**Reproduction**
 

> Be a Nukie/Syndi
> buy a clown bundle
> begin crying extremely hard

**Screenshots**

**Additional context**
 I haven't tested it cause I can't right now, but when i was a nukie i bought it twice and this happened.

**Comment by VasilisThePikachu** [comment]
Closed by #26195
