### ISSUE TITLE
GridTileLookupSystem does not update entities created within a grid's space.

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#2623]
Steps to reproduce:
1. Create wall in a grid's space tile.
2. Notice how it's not in the grid tile lookup system
3. Create a floor below that wall.
4. Notice how the wall is still not in the grid tile lookup system.

What should happen:
1. Create wall in a grid's space tile.
2. Wall is in the grid tile lookup system!
3. Create a floor below that wall.
4. Nothing has changed, wall is still in the grid tile lookup system!

Also relevant:
1. Create a non-space floor in a grid's space tile.
2. Create wall on that floor.
3. Notice how the wall is correctly in the grid tile lookup system.

**Comment by metalgearsloth** [comment]
To fix it: System should listen to parent changed events I think.

**Comment by Zumorica** [comment]
> To fix it: System should listen to parent changed events I think.

Oh yeah, and the walls themselves are always parented to the grid since they've been created within the area of it
