### ISSUE TITLE
Embeddable injectors aren't injecting

### ISSUE THREAD

**Issue by CatMagic1** [space-wizards/space-station-14#26233]
## Description

 When items like the hypodart, normal dart, and spear are thrown into people, they don't inject their contents.
The hypodart and spear still inject on melee swing.
**Reproduction**

Get hypodart
Fill with amatoxin
Throw at Urist
No poison damage, amatoxin is still in dart
**Screenshots**

**Additional context**

**Comment by deltanedas** [comment]
spear not injecting on throw is intentional afaik

**Comment by CatMagic1** [comment]
`  - type: SolutionContainerManager
    solutions:
      melee:
        maxVol: 2
  - type: MeleeChemicalInjector
    solution: melee
  - type: RefillableSolution
    solution: melee
  - type: InjectableSolution
    solution: melee
  - type: SolutionInjectOnCollide
    transferAmount: 2
    fixtureId: "throw-fixture"
  - type: SolutionTransfer
    maxTransferAmount: 2`

one of these components should be doing it but i've tried all of them and none of them inject on embed (although inject on collide sounds like it should)
is there any documentation for ss14 components n stuff? i don't actually know what things do half the time.

**Comment by Tayrtahn** [comment]
Ugh. Looks like I fixed one bug and caused another 

#26141 made SolutionInjectOnCollide only work with projectiles so it could be reflected. Didn't realize it was used for melee too.

I'm thinking this should be separate components for melee and projectile inject-on-hit.

**Comment by CatMagic1** [comment]
that sounds like it'd work
i really need this for something i'm making...

**Comment by Tayrtahn** [comment]
Thinking about this some more, they should only inject when they embed into the target, right?

I can make a SolutionInjectOnEmbed component pretty quickly and use it to replace the SolutionInjectOnCollide components on darts and spears.

**Comment by CatMagic1** [comment]
yes please! i believe improvised arrows would need it too.
