### ISSUE TITLE
Using VV on an empty implanter crashes the client

### ISSUE THREAD

**Issue by Tayrtahn** [space-wizards/space-station-14#26237]
## Description

This appears to only happen with the implanter that starts empty; an implanter that has been emptied by being used works fine.

```
Unhandled exception. System.InvalidCastException: Unable to cast object of type 'System.String' to type 'Robust.Shared.Prototypes.EntProtoId'.
```

**Reproduction**

- Spawn the empty "implanter" item.
- View Variables on it.
- Inspect the Implanter server component.
- Crash

**Comment by deltanedas** [comment]
should use string not String sus implanter code

**Comment by wrexbe** [comment]
Should be fixed
