### ISSUE TITLE
Origin Command bar has AP bullets

### ISSUE THREAD

**Issue by IProduceWidgets** [space-wizards/space-station-14#26246]
## Description

The Command bar on the south end of the bridge on Origin Station has 3 AP bullets on a table. This is bad because AP bullets are contraband and this entices players to break the no using contraband as command/security rule.

**Reproduction**

Play origin > Go to command bar > PwrGame

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/107586145/4026b755-c192-4840-983a-a32a28f1ecb4)

**Additional context**

**Comment by brainfood1183** [comment]
will change em.

**Comment by PJB3005** [comment]
Fixed by #26055
