### ISSUE TITLE
Hypospray should be able to go into medical belt

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#26303]

**Comment by bhenrich** [comment]
you're already able to? this can be closed.

**Comment by UbaserB** [comment]
wait really i have never been able to do that before and someone the other day was complaining how it didnt work when they tried

**Comment by Dutch-VanDerLinde** [comment]
it works tested last round

**Comment by nikthechampiongr** [comment]
> wait really i have never been able to do that before and someone the other day was complaining how it didnt work when they tried

It seems like the hypospray was whitelisted for the medical belt roughly 3 years ago.

**Comment by UbaserB** [comment]
really huh
