### ISSUE TITLE
Scram teleports someone holding

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#26301]
## Description
When someone is holding on to you then you hit the scram it also teleports them too. Making it almost useless as a escape option as its usually to escape sec and if they just teleport in next to you while you in cuffs, may as well not even have scrammed.

**Reproduction**
- 2nd player holds 1st player
- 1st player hits scram
- Both get teleported.

**Screenshots**
NA

**Additional context**
Also seemed to teleport multiple places including outside station in space before going to final destination.

**Comment by Ilya246** [comment]
shouldn't this also happen with other kinds of teleport?

**Comment by nikthechampiongr** [comment]
Oh my god. Ok I'll fix this later today.

**Comment by K-Dynamic** [comment]
This could be an interesting feature in the future, like scramming another perma with you or spacing a secoff that's grabbing you

**Comment by CatMagic1** [comment]
this is quite cool.
what if it stunned anybody other than the user of the implant?

**Comment by CatMagic1** [comment]
this is quite cool.
