### ISSUE TITLE
Human jetpacks - A broken physics story

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#26325]
## Description
Physics is a little broken. You can grab someone and they start spining up like a washing machine. and you push them in the direction you want to go and you have a human/mob powered jetpack. 

**Reproduction**
- Grab a mob
- Push them a direction
- Off we go, weeeee

**Screenshots**

https://github.com/space-wizards/space-station-14/assets/47093363/87166d02-67a1-4a20-ab40-b8c9937b743d

**Additional context**
NA

**Comment by MilenVolf** [comment]
Seems to be fixed after #28126. Cannot reproduce it.

**Comment by Titian3** [comment]
> Seems to be fixed after #28126. Cannot reproduce it.

Yeah haven't seen it recently, closing off.
