### ISSUE TITLE
Thief "steal cannabis" objective is nonsense

### ISSUE THREAD

**Issue by deepdarkdepths** [space-wizards/space-station-14#26321]
This relies on botany being nice to you and also wasting swabs on the cannabis so they have a better yield instead of only getting about 2 per harvest. The objective averages around 26-30 pieces of cannabis. If you _really_ feel like completing it, an invisible crate is almost required due to that amount needing about 2/2.5 duffelbags to haul it all around. Wasting a kit on a single objective due to its sheer size is inefficient and majority of the time it does not synergize well with the rest of your objectives.

If botany refuses and/or is a dick to you, no matter. On some maps there are trays or patches of soil to plant your own stuff in, but putting emphasis on SOME maps. If the map you have the objective on lacks one, oh fucking well. You may or may not have to go through the effort of asking science for a hydroponics tray board and cargo for an exotics seed crate, but once you get that set up, it takes time away from your other objectives, keeping in mind how shit the yield is for cannabis and the amount you need. If you've already gotten to this point, botany sure as hell isn't giving you a cocoa plant to swab. It is simply not worth doing this objective.

This is probably one of the only objectives that you cannot do solely on your own. Objectives that don't require help from other players aren't exactly the best, as the way the game plays out is to work with other players towards your goals, but cannabis in particular is ass. There is no way to get it without asking for external help, meanwhile stealing animals, cloaks, stamps etc can be gathered without doing so. 
Sorry for getting all up in arms about it, but man is it unfun.

**Comment by deltanedas** [comment]
it straight up isnt stealing its just begging or growing

and if you are a botanist its a non-objective

**Comment by UbaserB** [comment]
A while ago i discussed with shu (the guy who made thief) and we agreed that instead of cannabis, it should be any kind of plant (randomised), but he’s been busy

**Comment by metalgearsloth** [comment]
Getting any plant seems trivially easy considering what botany is like atm?

**Comment by deltanedas** [comment]
growing a plant still isnt theft why would it be an objective
its like an objective to "steal" a stack of plastic that you buy at cargo ultra engaging gameplay

**Comment by IProduceWidgets** [comment]
I dunno, I think "be a drug dealer" is pretty funny as a minor antag, but maybe it needs a more specific implementation separate from theif.

**Comment by ChaseFlorom** [comment]
Alright, I wrote a PR. I agree a drug dealer minor antag would be funny, but this is rough.
