### ISSUE TITLE
NPCs are so fucking stupid around railings

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#26330]
they just stop moving

![Screenshot_20240319_233322](https://github.com/space-wizards/space-station-14/assets/124214523/b9173360-ba66-423e-96ac-d280800ed466)

**Comment by Hmeister-real** [comment]
NPC's in general right now are fucking stupid, they get stuck in walking loops and just start walking and stop randomly in the centre of rooms for prolonged periods of time, i dunno what even changed it, they were fine before. They need a full behavior rework imo

**Comment by metalgearsloth** [comment]
> NPC's in general right now are fucking stupid, they get stuck in walking loops and just start walking and stop randomly in the centre of rooms for prolonged periods of time, i dunno what even changed it, they were fine before. They need a full behavior rework imo

Has nothing to do with this.

**Comment by Hmeister-real** [comment]
> Has nothing to do with this.

It does, i'm suggesting they need a rework and saying that they have become more stupid in general, not just around railings

**Comment by metalgearsloth** [comment]
> > Has nothing to do with this.
> 
> It does, i'm suggesting they need a rework and saying that they have become more stupid in general, not just around railings

This is coming from me, a 1-line change to pathfindersystem does not warrant throwing out 2k lines of code.
