### ISSUE TITLE
Zipties and makeshift handcuffs break after pulling

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#26331]
1. pull tiies
2. release
3. its broken

sounds like a feature but better to make a verb that would break ties

https://github.com/space-wizards/space-station-14/assets/124214523/629daf48-f4d3-405a-8252-2411610e865b

**Comment by IProduceWidgets** [comment]
I can't repro this on live

**Comment by lzk228** [comment]
still working on 266cc85f57c883b3a604a66da91d94bb1e18ec5d

https://github.com/space-wizards/space-station-14/assets/124214523/cf5509de-e7e9-4104-bf43-c3cf3e227388

here is more detailed video
