### ISSUE TITLE
Return of the arbitrary parenting bug

### ISSUE THREAD

**Issue by RandomDeathMatch** [space-wizards/space-station-14#26349]
## Description

Long ago I did funny things using a bug which let you parent objects to other objects
https://github.com/space-wizards/space-station-14/issues/6090

Now it is back, better than ever using **_quantum spin inverters_**!

**Reproduction**

To do the mostly harmless version:
-Simply put the spin inverter in an anchored container
-Use it to teleport yourself into it (but appear outside of it, now parented). 
-Then you can unanchor it and drag it around for extreme speed! WEEEEEEEE!! Hoverboard!

Harmful version:
-As above, except place spin inverter inside an holdable container, and then place that one inside the box. Now you are parented to the secondary object! You can also put the inverter in someone's pocket, and them inside the anchored box.
This lets you do all kinds of crazy stuff including walking invisible through walls, ignoring atmos, etc (can still pick things up, wide swing, fire guns)
Or... Parent yourself into the pocket of another person if you want to remain visible or make a clone / corpse army like the days of old! Create a bullet-proof forcefield out of monkeys! Carry your whole squad via a pizza box!

**Screenshots**

old screenshot but you can do the same thing
![voting](https://user-images.githubusercontent.com/97418313/148712031-04fdbffa-8857-4765-af52-7c4df275d8f8.png)

**Additional context**

Other notes: 
-You can delete entities this way by destroying their parent
**-You might be able to crash the server if you use this to make a parenting loop (BAD!). Not sure if parenting loops still crash the server, but it did a couple years ago.**

**Comment by metalgearsloth** [comment]
Probably better to just remove QSI in the interim until someone looks at it.
