### ISSUE TITLE
Wooden fence gates are mixed up.

### ISSUE THREAD

**Issue by KingOnBudget** [space-wizards/space-station-14#26363]
## Description
Small wooden fence gate will make a tall wooden fence gate and vice versa

[**Screenshots**

https://medal.tv/tr/games/space-station-14/clips/22Efnh0ciJR4Gj/d1337Li7pCA1?invite=cr-MSx5RFcsMjAyMDUyNjA0LA

**Additional context**
I hate medal!!

**Comment by wrexbe** [comment]
Was fixed in PR https://github.com/space-wizards/space-station-14/pull/26409
