### ISSUE TITLE
Authentication/Central API for global playtime

### ISSUE THREAD

**Issue by ilyamikcoder** [space-wizards/space-station-14#26360]
## Description
Job timers (playtime requirements) are currently bound to the local server's database, and nothing else. This essentially forces players to pick only one or two servers to hang around in, in order to actually make "career ladder" progress here.

It would be nice for the servers than Central has trust in (specific requirements are up for discussion, I guess being listed in The Hub for some amount of time may be a good call) to be able to report their player's playtime to that central server that authenticates everyone, and for other servers to be able to retrieve that data, and adjust job timers accordingly. 

## Algorithm Mock-up

- Perhaps the player is playing on some well-known server from the Hub, for example, our all-known Wizard's Den Lizard.
- Player plays for some time, and then leaves the server.
- The server, after the player leaves, takes their playtime data, and sends it to Central (provided the server has opted in for this).
- The Central records this data, marked with player's username and server's address/ID/whatever is used in the authentication for the Hub.

---

- Player joins another server. They have either never been there, or they have played there for a very short time.
- Provided that the server has opted in for this, during player authentication it also requests their overall playtime.
- The Central sums up all of the playtime that was marked with player's username (minus the playtime from the server that we are currently doing this from), and returns to the server the overall playtime, as well as the known playtime for that server (perhaps for recovery purposes, if the server somehow lost this data).
- The server adjusts the job timers accordingly.
- The player is happy, because they don't have to catch up on the 100H playtime again.

## Additional notes
- Perhaps something like this was already suggested and rejected. I tried to find a corresponding issue, but didn't find anything related. Maybe I didn't look well enough?
- The trust requirements for the Central to accept server's playtime tables are up for discussion. There **definitely** should be some, because nothing stops me from just putting up a local server, and running commands to make my playtime 9999H in everything.
- It may be reasonable to somehow differentiate between playtimes of different seriousness levels, e.g. LRP and MRP servers - either count them completely separately, or don't value them equally, e.g. on the MRP server LRP playtimes will be cut in half, and only then appended to the overall playtime.

**Comment by ilyamikheevcoder** [comment]
Also it may be worth nothing that I have very little understanding of how authentications of user with server, and server with the Hub work, so perhaps what I described is not technically feasible. Sorry if that's the case. ^^'

I am writing this under expectation that both are authenticated in a secure fashion.

**Comment by ilyamikheevcoder** [comment]
> Isn't this already in? In my experience all official servers (Wizard's Den) that I played on share the same playtime.
>
> It can't be just stored on local server's database. There appears to be a way to create trust-based clusters that server can join and share playtime among themselves.

I'm guessing there is some tooling to do this with your own servers if you have multiple. Either that, or Wizards did some database duct tape hacking shenanigans to get it to work.

I was talking more about creating a system to allow unrelated servers to easily share this info with each other, while still maintaining their own playtime databases, for flexibility of how server may sum this all up.

> And it should remain opt-in-only-with-permission for servers to join each cluster. Not every server wants to share play time with every other server.

Obviously, yeah, this should be opt-in.

**Comment by mirrorcult** [comment]
> Isn't this already in? In my experience all official servers (Wizard's Den) that I played on share the same playtime.
> 

this is just because they all use the same postgres db

**Comment by PJB3005** [comment]
The problem with this is that we'd need a way to prevent abuse. On part would definitely be that servers can tell *where* play time came from, but another factor is that it'd probably be best for the auth server to verify that you only get play time while you're actually connected to the server - something we cannot currently track.

**Comment by ilyamikheevcoder** [comment]
> it'd probably be best for the auth server to verify that you only get play time while you're actually connected to the server - something we cannot currently track.

My suggestion was - make the servers hit up the Central with statistics once the player disconnects.

I'm not sure how (un)effective that would be in terms of e.g. Central's resource usage, but it sounds like a solution to the connection tracking problem.

**Comment by PJB3005** [comment]
> My suggestion was - make the servers hit up the Central with statistics once the player disconnects.

The problem is that we need centcomm to keep track of the running game client to be able to validate that the server isn't lying. We'd need to have a permanent connection between auth server and game client. It's possible but complicated.

**Comment by ilyamikheevcoder** [comment]
> The problem is that we need centcomm to keep track of the running game client to be able to validate that the server isn't lying.

Ah, true!

I was kinda thinking about not keeping the constant track, but instead trustung servers on the basis of their existing good behavior (e.g. being listed in the Hub for some time, perhaps); as well as not mixing up the records, but instead keeping the individual playtime records per server, and then sum them up as needed (so that this info may be easily altered in case of abuse).

This will obviously work not for all servers, but for a good bunch, which is a lot better than nothing. I'm kinda thinking these are serving the overwhelming majority of the playerbase anyways.
