### ISSUE TITLE
small wooden fence gate cant be crafted

### ISSUE THREAD

**Issue by TheShuEd** [space-wizards/space-station-14#26369]
## Description
When crafting a small wooden fence gate, a large gate is crafted.

**Reproduction**
- Try craft small wooden fence gate
- Get Big wooden ffence gate

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/96445749/391b687e-ac17-424e-bb6d-d7d4e043e416)

**Comment by UbaserB** [comment]
Duplicate of #26363

**Comment by TheShuEd** [comment]
oops
