### ISSUE TITLE
Enter empty value in Set Bullet Amount window causes client crash

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#26362]
all on the video

https://github.com/space-wizards/space-station-14/assets/124214523/f1e2694b-cda0-478c-b206-65dc1c257db8

**Comment by IProduceWidgets** [comment]
The max is also incorrect, it can accept any amount.

**Comment by lzk228** [comment]
> The max is also incorrect, it can accept any amount.

looks like intended for admin reasons

**Comment by IProduceWidgets** [comment]
Ye, I left it in and just changed the wording of the text
