### ISSUE TITLE
Getting gibbed/deleted crashes your client

### ISSUE THREAD

**Issue by VasilisThePikachu** [space-wizards/space-station-14#26366]
## Description

Seen a bunch of people complaining about this, especially when they get deleted by an immovable rod mostly.

**Reproduction**

1. Get your character deleted somehow
2. crash
(not reproduced)

**Comment by VasilisThePikachu** [comment]
Personally cant repro this. Do notice immovable rod sends you to nullspace/"frezes" you one frame before the rod hits you. But not crashing the game. In both cases I was able to /ghost out

**Comment by Doctor-Cpu** [comment]
Can easily replicate it by standing where the arrival shuttle docks. Will just freeze the client.

What my clients terminal outputs:
`[INFO] system.map: Grid NT-Arrivals 1101 (115/n27070) changed parent. Old parent: map 9 (107/n25891). New parent: FTL (116/n27643)
[INFO] system.map: Grid NT-Arrivals 1101 (115/n27070) changed parent. Old parent: FTL (116/n27643). New parent: Station map (98/n14)
[INFO] system.map: Grid NT-Arrivals 1101 (115/n27070) changed parent. Old parent: Station map (98/n14). New parent: FTL (116/n27643)
[INFO] system.map: Grid NT-Arrivals 1101 (115/n27070) changed parent. Old parent: FTL (116/n27643). New parent: map 9 (107/n25891)
[INFO] system.map: Grid NT-Arrivals 1101 (115/n27070) changed parent. Old parent: map 9 (107/n25891). New parent: FTL (116/n27643)
[INFO] system.map: Grid NT-Arrivals 1101 (115/n27070) changed parent. Old parent: FTL (116/n27643). New parent: Station map (98/n14)
[INFO] player: Detaching local player from Amblyocarenum Gemmosum (124/n41420, MobArachnid, localhost@DoctorCpu).
[INFO] player: Local player is no longer attached to any entity.`

**Comment by potato1234x** [comment]
can repro by admin smite gibbing yourself

**Comment by Jezithyr** [comment]
> can repro by admin smite gibbing yourself
This might be due to minds breaking when your brain gets deleted during gibbing

**Comment by thebadman4662** [comment]
AFAIK its not crash but "freeze", heard you can just /ghost to unfreeze the game but I have yet to get round removed by something like rod or meatspike to test it.

**Comment by VasilisThePikachu** [comment]
In my opinion all the stuff you described should be actually gibbing. Hell it should gib by default. Especially rod

**Comment by VasilisThePikachu** [comment]
> > In my opinion all the stuff you described should be actually gibbing. Hell it should gib by default. Especially rod
> 
> I can just put add gibOrgans: true to all the things I listed in #27114 since it's already got one in there.
> 
> Though the meat spike might drop animal organs then from monkies if I do, just as a note. Could get messy when people butcher 6 animals at once. Lots of lizardpeople food I guess?

Keep it off for the meat spike ig that'd something to decide on another day
