### ISSUE TITLE
mailing unit sprite bug

### ISSUE THREAD

**Issue by Hanzdegloker** [space-wizards/space-station-14#26372]
## Description

Mail chute comically changes into disposals before switching back when flushed

**Reproduction**

use a mail chute

**Screenshots**

![image (2)](https://github.com/space-wizards/space-station-14/assets/41141796/fb913b6e-a73a-4506-8881-7c41085694e0)

**Additional context**

**Comment by lzk228** [comment]
im pretty sure its a dupe

**Comment by UbaserB** [comment]
> im pretty sure its a dupe

me too, tried searching it up but i couldnt find the issue

**Comment by nikthechampiongr** [comment]
> > im pretty sure its a dupe
> 
> me too, tried searching it up but i couldnt find the issue

#18275

**Comment by UbaserB** [comment]
ok im closing this one in favor of the old one
