### ISSUE TITLE
Recent pull has set cargo shuttle to be fixed spaced atmos

### ISSUE THREAD

**Issue by Admiral-Obvious-001** [space-wizards/space-station-14#26417]
## Description

Since the addition of #26382 the cargo shuttle has spawned round start totally spaced and can't be repressurized.

**Reproduction**

Spawn as cargo tech, dock the shuttle, board, die.

**Comment by deepdarkdepths** [comment]
This also apparently applies to evac shuttles too.
Specifically 49559 Salamander

**Comment by PJB3005** [comment]
> Since the addition of https://github.com/space-wizards/space-station-14/pull/26382 the cargo shuttle has spawned round start totally spaced and can't be repressurized.

That PR was merged **after** that already started happening, and in fact when you reported this bug that PR wasn't live yet.

I tested one of the maps I know this was happening on and it _was_ fixed, so I'm going to assume this issue is solved and invalid.
