### ISSUE TITLE
Air canisters not working on grids

### ISSUE THREAD

**Issue by Plykiya** [space-wizards/space-station-14#26438]
## Description

Some air canisters are unable to release air when on grids. I'm not sure if it's all of them, or just one station, but that's what I experienced. This means I could not refill my oxygen tank nor could I release air from the canister itself.

It worked when I took the air canister off-grid by moving it to space.

This doesn't happen to all canisters, and I'm not sure what the qualification is. The canisters I used were the ones found northeast on Origin, near the maze area.

**Reproduction**

Get canister, try to open it at a higher pressure to release air, nothing happens.

**Screenshots**

Lizard round 49613, Maeve Sparksong testing out air canisters for most of the shift.

**Additional context**

**Comment by deltanedas** [comment]
this is the opposite of an old bug that had canisters **only** able to release on a grid

**Comment by Plykiya** [comment]
I haven't been able to replicate this a single time since then so I'm just going to close it
