### ISSUE TITLE
Hypopen shouldn't display solution examine text

### ISSUE THREAD

**Issue by EmoGarbage404** [space-wizards/space-station-14#26439]
## Description

Hypopens and other stealthy injectors shouldn't be showing the contents on examination.

**Reproduction**

look at hypopen filled with JUICE

**Additional context**

There's a lot of jank and weirdness when it comes to examinable solutions so the components may need some refactoring to not be so scattershot.

**Comment by EmoGarbage404** [comment]
for the love of christ

**Comment by deltanedas** [comment]
valid
