### ISSUE TITLE
Grass & dirt sprites need to be replaced / resprited

### ISSUE THREAD

**Issue by Flareguy** [space-wizards/space-station-14#26449]
## Description
To be more specific, the offending sprites in question are ``Resources\Textures\Tiles\Planet\dirt.rsi`` and ``Resources\Textures\Tiles\Planet\Grass``.

![image](https://github.com/space-wizards/space-station-14/assets/78941145/5d915aa1-083a-4ddf-ad0a-e8553dbf020b)

Hilariously, these sprites are literally just straight up taken from Trials of Mana.
Outside of the obvious, these definitely do not fit the art style anyways (they're from an entirely different game, duh) and are pretty hueshifted & low in detail.

We have a few sprites in the repo to replace these already, namely ``grass.png``, ``grassdark.png``, and ``grasslight.png`` in the ``Resources\Textures\Tiles`` folder.. They are pretty noisy and likely won't look nearly as good, but should do the job alright.
If you can, you should probably add edge tiles to whatever one you decide to make the new "normal" grass, even if you suck at art and want to take this issue on. They are pretty important to making the grass biome look good.

**Comment by IProduceWidgets** [comment]
Ideally the grasses also need variants
