### ISSUE TITLE
Firelock wishlist.

### ISSUE THREAD

**Issue by nikthechampiongr** [space-wizards/space-station-14#26457]
Wishlist for making firelocks better made up from fragments of a discord conversation. I'm gonna be working on this but put this here for debate and in case anyone has something to add. If I end something with a questionmark then I am not sure I'll do it. 

~~- Delete the _visualUpdateInterval static that's currently used for periodic updates of firelocks.
	- Possibly move it to firelock component?
	- This might not be necessary if we just make firelocks work with fire alarms.~~
~~- Locked state gets properly synced to the client through a bool and do not do atmos checks every time you try to open them.~~
~~- Firelocks have a cooldown for auto close.~~
~~- Firelocks can be pried when unpowered without a crowbar?~~
~~- Instead just make them open and close instantly when unpowered?~~
~~- You can "hold open" firelocks so they can't close if you pry them open and you remain next to them.~~
- Make firelocks only collide when their animation finishes?

**Comment by deltanedas** [comment]
vs just remove them they suck :trollface:

**Comment by nikthechampiongr** [comment]
I'll close this as completed for now since all major items have been resolved and the only thing remaining is speculative and not sure we would even want it.
