### ISSUE TITLE
Gravity generator room walls need to be deleted and placed again

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#2646]
Currently, all tiles on the right are non-airblocking for some reason. I believe that deleting and spawning new walls should fix this.
![image](https://user-images.githubusercontent.com/6766154/100608389-9c4f5100-330c-11eb-96e7-3cd447a80d9c.png)
(notice how the walls on the right are missing the white line square)

**Comment by 20kdc** [comment]
Underlying issue behind this was https://github.com/space-wizards/RobustToolbox/pull/1440 so this is pretty much just waiting on someone to place the walls.
