### ISSUE TITLE
Uplink Holoparasite Dupe

### ISSUE THREAD

**Issue by Jonikibaka** [space-wizards/space-station-14#26471]
## Description
So the issue is that you can get free Holoparasite from uplink using refund system, using holo and then buying any usuless item and refund, heres your free Holo and full tk

**Video**

https://github.com/space-wizards/space-station-14/assets/153797633/fd78fa53-cc11-4931-9e9b-4b84a83bae48

**Additional context**
I think theres more bugs like that with uplink, but im not sure

**Comment by deltanedas** [comment]
refund has been removed
