### ISSUE TITLE
Atlas, Core, Saltern and Train are missing a second artifact spawn

### ISSUE THREAD

**Issue by FairlySadPanda** [space-wizards/space-station-14#26479]
The following is a note of which maps currently are missing a second artifact:

- [x] Atlas
- [x] Core
- [x] Saltern
- [ ] Train

Xenoarch needs two artifacts at roundstart, not one, because artifacts can be totally locked out of early in the round due to missing resources - e.g. the artifact gets stuck on a trigger needing rads (bananium/singulo) or magnets (magboots) and getting RNG'd out of being able to do an entire avenue of Sci even if said avenue is garbagio is lame.

**Comment by lzk228** [comment]
uhmm does emisse aprove this?

**Comment by Emisse** [comment]
yes

**Comment by Brandon-Huu** [comment]
Needs updating

**Comment by PJB3005** [comment]
What maps are done?

**Comment by Brandon-Huu** [comment]
> What maps are done?

Saltern has two artifact spawns

**Comment by PJB3005** [comment]
You posted that comment *before* your PR was merged. So no, it did not "need updating" at that time.

**Comment by 0x6273** [comment]
If two are required, the [mapping guildelines](https://docs.spacestation14.com/en/space-station-14/mapping/guidelines.html#research-and-development) should be updated to reflect that. It only says "artifact spawner" in singular form implying only one is required.

**Comment by Brandon-Huu** [comment]
> You posted that comment _before_ your PR was merged. So no, it did not "need updating" at that time.

It already had two before my PR was merged.
It has three now.

**Comment by Brandon-Huu** [comment]
> You posted that comment _before_ your PR was merged. So no, it did not "need updating" at that time.

Atlas needs to be checked off as well.
Just checked on https://map.spacestation14.com/?map=atlas and they have at least two

**Comment by Brandon-Huu** [comment]
Also should be removed from the mapping projects for saltern and atlas
