### ISSUE TITLE
Advertisements don't handle loading properly

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#26496]
System-stored data under `private TimeSpan _nextCheckTime = TimeSpan.MaxValue;`.

**Comment by Tayrtahn** [comment]
Would the correct fix be to just remove the system-wide nextCheckTime and check each component individually? Or is there a proper way to handle save/load for systems?

**Comment by deltanedas** [comment]
most good things have the TimeSpan stored on the component
it seems only ancient code has a system-wide time (usually accumulated frametime at that) then they query each component / iterate a hashset

**Comment by Tayrtahn** [comment]
Yeah, advertisements work by having a TimeSpan on each component with the next time they should activate, and then a TimeSpan on the system is kept updated with the minimum (soonest) time among all the components. The system waits until its own next time value is exceeded, then checks all the component times.

Simple enough to remove the system-wide TimeSpan and just check all the components every update.

**Comment by wrexbe** [comment]
The current design is fine. _nextCheckTime is just caching the soonest time, it doesn't need to be saved or loaded, as it'll automatically get changed as components init.
