### ISSUE TITLE
Reconnecting to server with active netgraph crashes the client

### ISSUE THREAD

**Issue by Injazz** [space-wizards/space-station-14#265]
### Steps to reproduce
1. Connect to server
2. Open netgraph (F3)
3. Disconnect
4. Netgraph is still open, don't close it
5. Connect again

**Comment by PJB3005** [comment]
This should probably go under engine.

**Comment by PJB3005** [comment]
Fixed in https://github.com/space-wizards/RobustToolbox/commit/04b14e92e7f4c8397fb3e0ba682cbe7f6bc3dabd, but I tagged the commit wrong because I forgot it was a different repo.
