### ISSUE TITLE
Some rounds immediately restarting

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#26521]
## Description
In the lobby the countdown reaches 0 and the game says its starting but returns to the lobby and the countdown starts again. I will try to add more details as they happen again.

**Reproduction**
- Hard only see it sometimes

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/47093363/b8e81242-fe88-42f5-9515-e74f06940443)

**Additional context**
Just before the round reset an ahelp message said it was (pre-round lobby for round 49880) but in the round it was 49879.

**Comment by UbaserB** [comment]
Has happened to several people including me

**Comment by metalgearsloth** [comment]
check grafana

> Has happened to several servers and i have seen it happen personally

when

**Comment by UbaserB** [comment]
> check grafana
> 
> > Has happened to several servers and i have seen it happen personally
> 
> when

it started a little while ago, at least a few days (i haven't been super active but i did play a bit recently)

**Comment by metalgearsloth** [comment]
Need timestamps as there's too many logs to comb through trying to look through days / weeks.

**Comment by UbaserB** [comment]
03/27/2024 9:03 PM

**Comment by metalgearsloth** [comment]
which server?

**Comment by UbaserB** [comment]
Leviathan
