### ISSUE TITLE
The game will spoil secret to you as a game admin if you let it automatically deadmin you

### ISSUE THREAD

**Issue by DrSmugleaf** [space-wizards/space-station-14#26528]
## Description
- Join after a round ends as a game admin, or join and wait for the round to end
- Ready up
- You will be sent what gamemode is actually chosen a few seconds before the game starts
- The game starts and deadmins you, and now you have to pretend like you didn't see anything

The admin message for secret gamemode should be sent after the automatic deadmin (probably easier), or the deadmin should happen sooner.

**Comment by TurboTrackerss14** [comment]
skill issue on behalf of admins who don't deadmin when they want to play

However maybe the solution is just to have clicking the ready up button automatically deadmin you instead of waiting for shiftstart?
