### ISSUE TITLE
Unbreakable thin firelocks

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#26531]
## Description

They can't be deconstructed OR destroyed with a fire axe, had to get an admin to delete it.

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/134914314/e75e6869-feff-4f62-bbe5-30b112b6a9b5)

**Comment by osjarw** [comment]
PR #26745 Makes firelocks deconstructable.
Also on the current build it seems that firelocks can be broken, but they seem to have some strong resistances.
A wielded pickaxe does 6-7 points of damage, and the firelock has 500 health. 
However, it did break once I reached that point.
