### ISSUE TITLE
Secret Wall doesn't appear as wall on station map

### ISSUE THREAD

**Issue by ElPidor** [space-wizards/space-station-14#26569]
Step 1 Make a secret hiding as syndi 
Step 2 Check station map 
Step 3 See that any crew member can see all other walls as wall but secret wall appear as nothing on it 
Step 4 Feel pain, kill all crew.
Secret wall is weak for it cost, so maybe make it cost less resources or make it appear on station map as wall but not a gap?

**Comment by Zealith-Gamer** [comment]
I was unable to reproduce this in the dev enviroment. The station map shows it as a normal wall
![image_2024-03-30_180034383](https://github.com/space-wizards/space-station-14/assets/61980908/9a8b7154-25a6-48eb-9b20-b8d003c8d1e8)

**Comment by EmoGarbage404** [comment]
looks good to me
