### ISSUE TITLE
Need lobby music

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#2656]
And probably a welcome announcement too.

**Comment by SweptWasTaken** [comment]
Should probably be more clear with this. It would be better to design a general system where server admins could configure a music file to play in the lobby.

**Comment by ProfanedBane** [comment]
I wonder if allowing streaming from some kinda CDN would be the way to go about this and generally playing long tracks at all in the game, rather than bundling it all in the content pack. Would ofc have an option to pre-download things like ambience/title stuff.
