### ISSUE TITLE
Emergency pens can be used as budget hypo

### ISSUE THREAD

**Issue by SphiraI** [space-wizards/space-station-14#26597]
## Description

Emergency pens are supposed to be inject only, but you can use the swap modes verb to bypass it and make it draw/inject.

**Reproduction**

- Get a epi pen
- Use it and inject something
- Take the now empty/used pen, and right click it
- Use the "Toggle Container Draw" verb
- Budget Hypo time

**Comment by Tayrtahn** [comment]
Fixed by #26595

**Comment by nikthechampiongr** [comment]
I can't reproduce this.
