### ISSUE TITLE
Catwalks over lava don't work but are mapped.

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#26608]
## Description
Pretty much the title, in a cave(i think) expo saw a lava with catwalks mapped over it but the fire still kills ya and wiped out salv.

**Reproduction**
- Spawn a cave map/expo
- Get cooked more than a tender medium rare.
- Serve Chargrill salv team at bar/kitchen for rave reviews.

**Screenshots**
w![image](https://github.com/space-wizards/space-station-14/assets/47093363/886a73ce-80aa-40be-8a63-29e4e6bc3757)

**Additional context**
NA

**Comment by Golinth** [comment]
Pretty sure this used to work, if I remember correctly from playing salvage a couple months ago.

**Comment by TheShuEd** [comment]
Dublicate of #26643
even though it was later than this one, it had more constructive dialog.
