### ISSUE TITLE
Syringe UI doesn't update on volume draw changes

### ISSUE THREAD

**Issue by QuietlyWhisper** [space-wizards/space-station-14#26621]
## Description

When swapping between volume toggles, the inhand ui (Draw _u) does not update.
When changing the volume of the syringe, the UI does not update.

**Reproduction**

Follow description.

**Additional context**

I have a feeling this might also effect similar items like the dropper, but was not able to test at the time.

**Comment by Plykiya** [comment]
Fixed by #26596
