### ISSUE TITLE
southern drawl trait doesnt change capitalized words

### ISSUE THREAD

**Issue by Dutch-VanDerLinde** [space-wizards/space-station-14#26637]
## Description
title

**Reproduction**
- use southern accent trait
- say "DOING" in all caps
- doesnt convert it to "DOIN'"

**Screenshots**

**Additional context**

**Comment by Golinth** [comment]
this is most accents I think. I know as a lizard, if I talk in all caps X's dont get replaced with KS

**Comment by UBlueberry** [comment]
uh oh!! okay, um, i'll see what i can do

**Comment by UBlueberry** [comment]
https://github.com/space-wizards/space-station-14/pull/26638
fixed

**Comment by UBlueberry** [comment]
nevermind i lied
#26639
waiting for it to merge
