### ISSUE TITLE
Catwalks over lava still burn you like normal lava.

### ISSUE THREAD

**Issue by Avocado-999** [space-wizards/space-station-14#26643]
During a salvage expedition inside the dungeon, if you walk over a catwalk tile over lava, you'll get set on fire as if it was just lava.
![image](https://github.com/space-wizards/space-station-14/assets/165635263/6031f09f-e36f-4807-8fb3-0f96bd647360)

**Comment by wrexbe** [comment]
I am unable to decide if this is a bug or a feature. On one hand, being on a platform above something gives a sense of safety. On the other hand, for as long as I can remember, a metal grill, over a heat source cooks things.

**Comment by dolgovmi** [comment]
It used to not burn you so I assume it would be a bug

**Comment by wrexbe** [comment]
Unless of course, not burning was the bug, and it got fixed.

**Comment by dolgovmi** [comment]
Then that whole dungeon room needs to be reworked because it's impossible to navigate normally now

**Comment by metalgearsloth** [comment]
StepTrigger is not supposed to be hit for this it just needs fixing.

**Comment by deltanedas** [comment]
Round Removal Tile :tm:

**Comment by Deatherd** [comment]
For someone who will start to fix it: [Here](https://github.com/space-wizards/space-station-14/blob/master/Content.Shared/StepTrigger/Systems/StepTriggerSystem.cs) is a bug in 
`private bool Update(EntityUid uid, StepTriggerComponent component, TransformComponent transform, EntityQuery<PhysicsComponent> query)`. New implementation of getting anchored entities in same tile through map system does not work properly. Have skill issue to fix it by myself.
