### ISSUE TITLE
Ashtray CigaretteSpent vs Cigarette

### ISSUE THREAD

**Issue by HolySSSS** [space-wizards/space-station-14#26659]
Reproduction:
Take cigarette with id "Cigarette"
Smoke it
Try to push it into ashtray
"Nope.sfx"
Oh well..
Find item with id "CigaretteSpent" 
Try to put it into ashtray
Yep now THAT cigarette goes in, but not THAT one

Should be easy to fix I guess

![image](https://github.com/space-wizards/space-station-14/assets/81934438/e76a11f0-e1b8-4602-ada3-860c2f42b2d9)

**Comment by Emisse** [comment]
should probably just let cigarettes/cigars go in there regardless like a normal ashtray
