### ISSUE TITLE
Ratking Husbandry

### ISSUE THREAD

**Issue by ARMOKS** [space-wizards/space-station-14#26669]
## Description
Make infinite rats for free today!

**Reproduction**
Summon baby rat
slash baby rat until all blood is outside him
drink up all the tasty blood
Summon baby rat * 5
repeat

**Additional context**
Easy Fix: replace blood in rats with "rat blood" with no nutritional value, tried to fix myself but cannot figure how to add chem.

**Comment by deltanedas** [comment]
Resources/Prototypes/Reagents then in one of the yml files with blood in it
