### ISSUE TITLE
How to become god

### ISSUE THREAD

**Issue by ARMOKS** [space-wizards/space-station-14#26670]
## Description
Want admin powers? Easy peasy

**Reproduction**
1) Get sci to T3 sci for inverters
2) Print two inverters
3) Place the first inverter inside any anchored container; eg. a wrenched locker, artifact crusher, ect.
4) activate the second inverter inside of your own backpack
5) Congrats you are now in the hell dimension. You're essentially a ghost with hands and some goofy abilities!

In ghost state you are able to:
Pick up any item and store it, 
Phase thru walls
Beat people to death
Shove people
Strip people
Invincible to damage
Unhittable by bullets
Pulling someone teleports them to where the inverter is stored
Speak over radio, speaking in person cannot be heard.
You can be seen by sec / medhuds.

Fix:
make inverters unable to activate inside of wrenched containers

**Comment by GoodWheatley** [comment]
Will be fixed by #26364

**Comment by EmoGarbage404** [comment]
Dupe issue

**Comment by ARMOKS** [comment]
my bad
