### ISSUE TITLE
Add destructible to many prototypes

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#2667]
I don't recommend working on this until after https://github.com/space-wizards/space-station-14/pull/2525 is merged.

A lot of prototypes don't take any damage when they should. Most things just need the relevant component to be added for destruction and a threshold set (either by looking at what its ss13 threshold is or coming up with a new one).

If you're really fancy you could add the different damage tier functionality (though most things won't need it).

**Comment by SweptWasTaken** [comment]
Sounds fun.

**Comment by Peptide90** [comment]
> Basically everything that needs it is destructible now. Does this issue need to remain?

Issue need to be more specific. I canvased for ideas the other week but didn't get far. APC is one, others mentioned vendors, disposals and freezers but I haven't verified these.

I'll do a quick PR now and link it in to auto close.
