### ISSUE TITLE
New pulling lets you infinitely fly in no grav and also is very unprecise

### ISSUE THREAD

**Issue by Hmeister-real** [space-wizards/space-station-14#26673]
## Description
As a salv, it took me like 5 minutes to pull a salv magnet through a 1x1 door because it wouldnt fit, but thats unrelated and cope, if your in space and pull something ahead of you you can fling yourself fast and literally fly, the heavier the object the better

**Reproduction**
Be in space, grab a thruster or any large object, start pulling the thuster in the direction you want to go, fly

**Screenshots**

**Additional context**

**Comment by lzk228** [comment]
also dupe #26325

**Comment by Hmeister-real** [comment]
> also dupe #26325

thanks
