### ISSUE TITLE
Combat gloves should have a seperate sprite from black gloves

### ISSUE THREAD

**Issue by Hmeister-real** [space-wizards/space-station-14#26676]
## Description
 Theres no reason for them to be exactly the same + would look way cooler

**Comment by deltanedas** [comment]
valid

**Comment by lunarcomets** [comment]
so apparently we already have a [combat gloves sprite](https://github.com/space-wizards/space-station-14/tree/70ec12f4f7ba0063e108c36b8da89b474d91acf6/Resources/Textures/Clothing/Hands/Gloves/ihscombat.rsi) that is seemingly unused for anything other than being the icon for an admin antag smite? would be nice to use them for the sprite

**Comment by lunarcomets** [comment]
(the clothing sprite probably needs redoing for this purpose though cause it kinda looks badddddd on usual black colors for hos and such)

**Comment by CatMagic1** [comment]
i may do this
