### ISSUE TITLE
Newton's Cradle is loud and can be heard from far away

### ISSUE THREAD

**Issue by crazybrain23** [space-wizards/space-station-14#26681]
## Description
Despite #25357 changing the parameters for the newton's cradle, it is loud and can be heard from long distances.

**Reproduction**
Use a newton's cradle, hear loud clicks even if you walk away.

**Comment by lzk228** [comment]
i think its the general issue with sound going through walls

**Comment by crazybrain23** [comment]
I think this was been fixed, it's not as bad as it was originally.
