### ISSUE TITLE
Infinite foam duplication using scoopable foam

### ISSUE THREAD

**Issue by Plykiya** [space-wizards/space-station-14#26685]
## Description

probably need to revert or disable #25832 cause I don't see any easy way this gets balanced or fixed

- the foam will apply reagent effects to people without affecting the solution content of the foam (free healing or whatever you want, just scoop it)
- the foam will attempt to spread to a set distance regardless if scooped causing it to continue to spread on scooped tiles (duplication)
- each tile of foam contains the total reagent solution payload including the component to make more foam reactions (even greater duplication)

you can just infinitely farm the contents to create more foam reactions and extremely rare chemicals by doing this, with as little as 1u of content, people who want to abuse it can ruin entire stations if they want to with space lube oceans, infinite omnizine healing, etc etc 

**Reproduction**

just scoop the foam, lol
https://youtu.be/0VALFTo1O34

**Comment by TemporalOroboros** [comment]
I'd say the actual issue here is the reagent duplication thing smoke/foam/etc have going on. As long as that exists this issue will reappear whenever people manage to find a way to extract reagents from foam/smoke. Half a fix would be making foam either share its reagents across the entire puddle or making foam split its reagents when it spreads. The other half has to deal with how foam add reagents to affected mobs and is a bit harder to deal with.

**Comment by metalgearsloth** [comment]
@deltanedas

**Comment by Plykiya** [comment]
> I'd say the actual issue here is the reagent duplication thing smoke/foam/etc have going on. As long as that exists this issue will reappear whenever people manage to find a way to extract reagents from foam/smoke. Half a fix would be making foam either share its reagents across the entire puddle or making foam split its reagents when it spreads. The other half has to deal with how foam add reagents to affected mobs and is a bit harder to deal with.

this technically opens up the way for infinite space lube oceans regardless of how much you want to divide the contents of the foam since I believe space lube foam leaves puddles on tiles, giving you even more space lube to begin with as long as you continue to keep scooping

**Comment by TemporalOroboros** [comment]
> > I'd say the actual issue here is the reagent duplication thing smoke/foam/etc have going on. As long as that exists this issue will reappear whenever people manage to find a way to extract reagents from foam/smoke. Half a fix would be making foam either share its reagents across the entire puddle or making foam split its reagents when it spreads. The other half has to deal with how foam add reagents to affected mobs and is a bit harder to deal with.
> 
> this technically opens up the way for infinite space lube oceans regardless of how much you want to divide the contents of the foam since I believe space lube foam leaves puddles on tiles irrelevant to the foam contents, giving you even more space lube to begin with as long as you continue to keep scooping

This is more an issue with space lube. The puddles it leaves behind should probably be based on the amount of lube left in the foam when it dissipates. Scooping should remove the reagents from the foam so less of it is left to puddle afterwards.
