### ISSUE TITLE
Mop Buckets don't show if they have liquid in them

### ISSUE THREAD

**Issue by Vermidia** [space-wizards/space-station-14#26712]
## Description

Before you could see the water in the bucket, now you can't.

**Reproduction**

Fill up a mop bucket

**Screenshots**

![Capture](https://github.com/space-wizards/space-station-14/assets/32827189/aec73e3f-9e13-4a27-a048-06ac1cc54778)

**Additional context**

**Comment by osjarw** [comment]
According to git bisect, this issue was introduced in commit 29d7b73da72e066436933f869ff7adbee1d24f45, which seems to be PR #26601.
Haven't decided if I'll try to solve this.
