### ISSUE TITLE
RGB staff doesnt work

### ISSUE THREAD

**Issue by GeneralGaws** [space-wizards/space-station-14#26722]
## Description
It doesnt add component RGBController (does it should?), checked at previous game version and that worked

**Video**

https://github.com/space-wizards/space-station-14/assets/122978178/5467b3de-26f4-4bf1-bbad-bb65ff12acf4

**Additional context**

Maybe troubles with with Action OnInteract, EntityTargetAction or ChangeComponentsSpellEvent idk

**Comment by keronshb** [comment]
This should be fixed with the magic refactor #22568
