### ISSUE TITLE
When i place stuff down, it faces the rotation of the station?

### ISSUE THREAD

**Issue by Hmeister-real** [space-wizards/space-station-14#26732]
## Description
So when i place something. it gets placed straight with the station, and not myself, leading to it being turned in the direction the station is facing, i think.

**Reproduction**
Place an item, its all wonky

**Screenshots**

https://github.com/space-wizards/space-station-14/assets/118129069/b56cf7c0-035a-4e3c-bcce-45bc8fe505c0

**Additional context**
 Throwing is not affected, nor is having items fall out of your hand

**Comment by Tayrtahn** [comment]
Duplicate of space-wizards/RobustToolbox#5020

**Comment by Hmeister-real** [comment]
> Duplicate of [space-wizards/RobustToolbox#5020](https://github.com/space-wizards/RobustToolbox/issues/5020)

cheers
