### ISSUE TITLE
Bluespace anomaly teleports borg positronic brains out the chassis

### ISSUE THREAD

**Issue by crazybrain23** [space-wizards/space-station-14#26738]
## Description
When a bluespace anomaly pulses near a cyborg with a positronic brain, the positronic brain is teleported separately from the chassis. This does not appear happen to MMIs.

**Reproduction**
Bluespace anomaly pulse next to a cyborg. Positronic brain is no longer in chassis.

**Screenshots**

https://github.com/space-wizards/space-station-14/assets/44417085/cd2cdbcb-208c-4b8b-a0e6-063ca22e4670

https://github.com/space-wizards/space-station-14/assets/44417085/9a5b8f18-1897-47d2-a76f-1a2fb2c7ca89

https://github.com/space-wizards/space-station-14/assets/44417085/f3f8e45a-ff97-4851-829a-bf44acba574b

**Comment by Randomplayer2or3** [comment]
It’s pretty insignificant until bluespace anom caused assault borg’s brain to teleport out of the chasis
