### ISSUE TITLE
The borg shuttle ion law needs to be changed.

### ISSUE THREAD

**Issue by Golinth** [space-wizards/space-station-14#26766]
## Description

For reference, this is about the "THE SHUTTLE CANNOT BE CALLED BECAUSE OF {$joined} {$subjects} ON THE STATION" borg ion law.

As it is now, borgs with this law are incentivized to round stall for as long as possible, by any means necessary. This leads to a somewhat conflict of interest between the IC borg who is forced to make people stay and the OOC player who just wants to leave already, and doesnt end in very interesting scenarios. If played well, the borg will either create a fortress hidden in maints where its practically impossible to find, or hide somewhere off station, and recalls the shuttle no matter what, making a shift last 30-40 minutes longer than it needs to. This is especially annoying when a large majority of the crew wants to go or is dead and now that round restarts are practically disabled, is a major dick move. I'd also say this breaks the "forbidden from needlessly prolonging rounds" rule.

As a solution, maybe change the law from "THE SHUTTLE CANNOT BE CALLED BECAUSE..." to "THE SHUTTLE _MUST_ BE CALLED BECAUSE..." as it still potentially leads to the same borg hunt as before, but with the added benefit of preventing unwanted round stalling.

**Additional context**

See Lizard Round #50591.

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
I was wondering when you were going to make this, yea not the most fun to deal with

**Comment by superjj18** [comment]
Just kill the borg?

**Comment by Golinth** [comment]
> Just kill the borg?

hard to do when the borg hides behind 2 layers of walls with just a communication console

**Comment by superjj18** [comment]
> > Just kill the borg?
> 
> 
> 
> hard to do when the borg hides behind 2 layers of walls with just a communication console 

Just cut its power supply :trollface:

**Comment by northerndakotas** [comment]
Huh. When I got that law as a borg, I interpreted it as the crew being prevented from leaving by the quadrillion chemists aboard the ship. So I developed a conspiratorial hatred for chemists and wanted them gone so that everyone was able to leave.

Are there random combinations that would imply instead that the borg needs to stop the crew from evacing, rather than that the borg needs to fix the problem so that the crew can evac?

**Comment by Golinth** [comment]
> Are there random combinations that would imply instead that the borg needs to stop the crew from evacing, rather than that the borg needs to fix the problem so that the crew can evac?

that’s a good way of looking at it. Unfortunately, in the round I linked my law was because of “eighty bazillion viruses” and was impossible to do anything about because viruses aren’t real.

**Comment by northerndakotas** [comment]
> > Are there random combinations that would imply instead that the borg needs to stop the crew from evacing, rather than that the borg needs to fix the problem so that the crew can evac?
> 
> that’s a good way of looking at it. Unfortunately, in the round I linked my law was because of “eighty bazillion viruses” and was impossible to do anything about because viruses aren’t real.

Well I suppose so, though in my case the chemists weren't real either. (Ironically there were actually no chemists on the station at all, not even the normal ones.) But it was still fun to run around like a lunatic screaming about how the chemists were causing crew harm by keeping us all hostage. I'm sure ranting to anyone that will listen about viruses would be more fun than forcefully recalling the shuttle over and over again. You didn't. . . actually do that, right?

**Comment by slarticodefast** [comment]
It was decided by maintainers and admins that this law should be kept. See the comment in the PR linked above.
