### ISSUE TITLE
items in lockers will appear rotated

### ISSUE THREAD

**Issue by Dutch-VanDerLinde** [space-wizards/space-station-14#26777]
## Description

**Reproduction**
make sure the station is titled
put the item in the locker, close it, and then open the locker
the item will be rotated

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/45323883/7bc76dd3-5f5a-4d7c-9378-26d667e1f532)
![image](https://github.com/space-wizards/space-station-14/assets/45323883/7636697c-3538-4206-912d-c513b220a296)

**Comment by deltanedas** [comment]
i think an engine change did this

**Comment by Dutch-VanDerLinde** [comment]
> i think an engine change did this

someone made a pr fixing it but its still broken in lockers

**Comment by Dutch-VanDerLinde** [comment]
has been fixed
