### ISSUE TITLE
Being eaten as a ghost role mouse in crit tethers your ghost to the person who ate you

### ISSUE THREAD

**Issue by Admiral-Obvious-001** [space-wizards/space-station-14#26781]
## Description

Simply, if you're eaten as a mouse while crit your ghost will follow the movement of the person that ate you as well as follow relative rotation.

**Reproduction**

Be ghost role mouse, get crit on your own accord in some capacity (typically by poisoned foods), get eaten by a mob or player. Your ghost movement will work but any time the person that ate you moved, your ghost will mirror their movement as well.

**Comment by eoineoineoin** [comment]
Seems this is fixed now, so I'll close this issue. Thanks for the report.
