### ISSUE TITLE
Can't FTL back to nukie home planet

### ISSUE THREAD

**Issue by Plykiya** [space-wizards/space-station-14#26807]
## Description

You can accidentally strand your fellow nukies with no way to get back as a result of the change to FTL disks. This also gets rid of the "nuke the nukies" win condition.

**Reproduction**

**Screenshots**

**Additional context**

**Comment by Golinth** [comment]
Can confirm. I was left behind as an agent, and no admin was online to allow them to come back for me.

**Comment by MACMAN2003** [comment]
you also can't give the syndicate back their bomb ;-;

**Comment by Ghagliiarghii** [comment]
I remember fondly the two or three times I blew up nukie homeworld as/with captain of the station on a nukie round, definitely should be in the game that stuff was awesome

**Comment by ScarKy0** [comment]
I believe this is now outdated. If something like this happens again feel free to reopen the issue.
