### ISSUE TITLE
Postgre database error

### ISSUE THREAD

**Issue by 13lackHawk** [space-wizards/space-station-14#26800]
## Description
Adminnotes command not working on older notes like if there were any notes for player before 2024 year then its 99% won't load.
Probably [that](https://github.com/space-wizards/space-station-14/pull/25280) was the fix so I am pretty sure I did merge it and well some notes are still broken.

**Screenshots**
(https://imgur.com/lpF85wY)
(https://imgur.com/8k74n2x)

**Additional context**
It probably is my personal problem with database but the thing is I didnt actually change anything in my db besides doing manual migration adviced by PJB:
https://discord.com/channels/310555209753690112/1010977110933901323/1196579541892730922

I also tried to manually delete all notes via db and yeah it didn't help.

P.S. Notes working correctly on newer accounts like if they have no notes before Jan-Apr 2024 then their notes are ok to watch/edit/etc.

**Comment by PJB3005** [comment]
What do these notes' time fields look like in the database?

**Comment by 13lackHawk** [comment]
> What do these notes' time fields look like in the database?

![Безымянный3](https://github.com/space-wizards/space-station-14/assets/26493665/018cfd6a-23b1-497f-9ec0-094e7e2d494f)
(no idea if its ok to show admins/players user id's so I did hide them)

**Comment by PJB3005** [comment]
Honestly I've got no idea then. That looks fine

**Comment by 13lackHawk** [comment]
Also I did mention that after deleting all my notes they were still broken. 
Just guessing, but maybe the actual problem might be hiding in "server_ban"/"server_role_ban" table?
Also screenshots of them:
![Безымянный4](https://github.com/space-wizards/space-station-14/assets/26493665/6bba42e5-067f-4d68-93ca-0d7005db04ac)
![Безымянный5](https://github.com/space-wizards/space-station-14/assets/26493665/c0821e5e-d74d-42c1-a8e5-51035fd48637)

**Comment by 13lackHawk** [comment]
![Безымянный](https://github.com/space-wizards/space-station-14/assets/26493665/f1bb04e3-c689-4fce-b927-ea58eafb6e8b)

**Comment by PJB3005** [comment]
Figured out the problem, it happens if the note was made on a round that doesn't have a start date in the database, i.e. before #21153. For the wizden database we ended up backfilling these at some point from admin logs so that's likely why this didn't come up before on our servers.
