### ISSUE TITLE
Box Station should have a burn chamber air alarm

### ISSUE THREAD

**Issue by slarticodefast** [space-wizards/space-station-14#26818]
## Description
Most station maps have an unused air alarm for the burn chamber in atmos to use for scrubbers. Box station should have one, too.

**Screenshots**
![Unbenannt](https://github.com/space-wizards/space-station-14/assets/161409025/286e1d5b-0f98-4f87-acf1-3c7b8ec98e53)

**Comment by UbaserB** [comment]
i have no idea specifically which maps have or don't have a functioning air alarm so i'll put it in box for now, i know core has one though.
