### ISSUE TITLE
Borg cryo abuse

### ISSUE THREAD

**Issue by SoulFN** [space-wizards/space-station-14#26815]
## Description

Borg can be put into cryo storage unit and all his items from active module can be ejected
**Reproduction**

Put borg with any active module in cryo storage unit
**Screenshots** (From Russian Corvax Build)

![image](https://github.com/space-wizards/space-station-14/assets/164462467/1521e37d-d5e9-408b-b750-8d4c554ef17d)
**Additional context**

With this issue you can get an experimental RCD or borg hypo

**Comment by Simyon264** [comment]
Broken borg hand systems strike again

**Comment by deltanedas** [comment]
shouldnt be able to cryo a borg regardless
