### ISSUE TITLE
Monkey and Kobold duplicating from cubes

### ISSUE THREAD

**Issue by PyteOakOal** [space-wizards/space-station-14#26816]
## Description
Once you pour water into a cube, two specimens come out, with the first one being inanimate and the second one being the actual NPC. Inanimate clone is invisible to other players and fall over when hit.

**Reproduction**
In Cluster, pour water on either a Moneky or Kobold cube.

**Screenshots**
![20240408043015_1](https://github.com/space-wizards/space-station-14/assets/145092881/4af09051-cf3b-4504-85fe-c6fd8b882c41)
![20240408043018_1](https://github.com/space-wizards/space-station-14/assets/145092881/59877017-6f57-4aba-97e4-bfde7bf882d3)

**Additional context**

Client ping was over 100ms and i believe this could be the cause of this issue.

**Comment by UbaserB** [comment]
I have replicated this ingame, and the "ghost" version also doesn't attack back, move OR is pullable.

**Comment by deltanedas** [comment]
because its clientside, client shouldnt be predicting spawn
