### ISSUE TITLE
Rooting through plants spams rooting notification and sound effect

### ISSUE THREAD

**Issue by Terraspark4941** [space-wizards/space-station-14#26853]
## Description

Title says it all

**Reproduction**

1. Join map
2. Root through plant
3. Loss

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/85469138/a3c3787d-cc56-4bcf-8eca-7a2af84cb0d4)

**Additional context**

Seems to be related to the shield popup spam (similar phenomenon)

**Comment by Tayrtahn** [comment]
Looks like #22133 moved PottedPlantHideSystem from Server to Shared but didn't adjust the behavior to account for prediction. 

Simple enough to fix:
- The call to _popup.PopupEntity should be changed to _popup.PopupPredicted (or PopupClient depending on whether other players are intended to see the message).
- The call to _audio.PlayPvs should be changed to _audio.PlayPredicted.

Both will need to have the user's uid passed as an additional parameter, which means the method signature of Rustle will need to be modified.
