### ISSUE TITLE
new rcd issues

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#26850]
## Description
- rods take ~5 matter and 5 seconds when its ~0.5s doafter with wirecutters it should just be free considering it destroys the rods, and the actual useful part of removing plating costs less and is faster

**Comment by chromiumboy** [comment]
Confirmed, line 178 of RCDSystem.cs should read 

```var protoName = !deconstructedTile.IsSpace() ? _deconstructTileProto : _deconstructLatticeProto;```
