### ISSUE TITLE
Anomaly behaviour "Impermanance" lies to the scanner

### ISSUE THREAD

**Issue by Terraspark4941** [space-wizards/space-station-14#26855]
## Description

Impermanance reported particles do not match the behaviour of the particle when it is applied to the anomaly.
Can result in unintended supercrits when the containment is sigma but next roll of sigma turns out to be danger 

**Reproduction**

1. Make anom
2. Scan anom
3. Impermanance
4. Hit anom with particle
5. Chance particle does what it should not do

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/85469138/707a9588-baed-4c94-8d76-cd61fd0adbee)
Hit with sigma particle:
![image](https://github.com/space-wizards/space-station-14/assets/85469138/d2b24370-33cc-4d9e-910b-ca5650f779f4)
Hit with zeta particle:
![image](https://github.com/space-wizards/space-station-14/assets/85469138/a02d6564-d720-48c5-881d-302eea3ecfcc)
Hit with epsilon particle:
![image](https://github.com/space-wizards/space-station-14/assets/85469138/d52fdd2c-687a-4620-8bc6-79815e340df5)
Hit with sigma particle:
![image](https://github.com/space-wizards/space-station-14/assets/85469138/b6aeb91d-c05e-4ea8-86ac-f0b226bb18a1)

**Additional context**

Seen atleast 2 anomalies go supercrit due to this bug on WizDen, seems to be inconsistent to trigger
Code seems to calculate changed particle types before applying particle type and updating the scanner

**Comment by Terraspark4941** [comment]
@TheShuEd please tell me this is unintended behaviour

**Comment by TheShuEd** [comment]
Yeah, unintented. Need fix

**Comment by Terraspark4941** [comment]
i am testing this in dev
it seems to be working as normal
but i swear i have seen atleast 2 anomalies on wizden go crit due to this

**Comment by Terraspark4941** [comment]
Okay i got it to do what it did, see issue

**Comment by Terraspark4941** [comment]
Hey, can someone double check if this is still closed or if it is an issue again?
