### ISSUE TITLE
Door electronics access assigning broken

### ISSUE THREAD

**Issue by Terraspark4941** [space-wizards/space-station-14#26869]
## Description

- Door electronics cannot have their access configured by network configurators
- Door electronics can have their access configured by hand (with no tools)
- Door electronics can have unavailable accesses configured (e.g. captain access with only a passenger card). This includes being able to configure accesses without any card whatsoever (this may be intended behavior)

**Reproduction**

1. Grab door access
2. Poke the wires (interact)
3. You can change access without tools???

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/85469138/b76372b5-e438-44a6-a47c-d0cb9132d158)

**Additional context**

**Comment by SoulFN** [comment]
I think 1 and 3 is okay, but 2 is bad

**Comment by Terraspark4941** [comment]
![image](https://github.com/space-wizards/space-station-14/assets/85469138/aef1266a-4289-41c1-b183-14af8d493789)
1 is definitely intended

**Comment by Zealith-Gamer** [comment]
> Door electronics can have unavailable accesses configured (e.g. captain access with only a passenger card). This includes being able to configure accesses without any card whatsoever (this may be intended behavior)

99% sure this is intended, its a way for antags to mess with doors and a way for engi to fix doors and set them to the proper access without HoP or CE's tool. The tool is now only used for already constructed doors w/o having to deconstruct them.

The other two i think are bugs but arnt really to bad imo
