### ISSUE TITLE
BUIs need an easy way to sub to compstate changes

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#26866]
Ideally BUISystem or whatever would have some helper method so the BUI can sub to afterautohandlestate for specific component states. This would easily let us take advantage of component networking instead of either checking every frame for data changes or using UI states even when not appropraite.

**Comment by PJB3005** [comment]
Just like item status I'm really not sure this is practical. You're gonna have what, 4 BUIs open at once? Each reading worse case a dozen or two properties?

**Comment by metalgearsloth** [comment]
There's technology for this already.
