### ISSUE TITLE
Dragging lets you fly in space

### ISSUE THREAD

**Issue by SphiraI** [space-wizards/space-station-14#26876]
## Description
*I swear I already saw a report for this, but can't find it, so hopefully just insane and not dupe*

Grabbing an item, then Ctrl+Rclick-ing something while weightless lets you move around quickly in space, and in some cases can replace a jetpack.

**Reproduction**
- Grab something
- Ctrl + Rclick to move it the direction you want to go
- Fly far into the cosmos for as long as your patience lasts

**Comment by UbaserB** [comment]
I am pretty certain i have seen this as well so im adding a replicated tag for now

**Comment by VasilisThePikachu** [comment]
Welp that sounds like my #18478

**Comment by UbaserB** [comment]
That’s because it **WAS** fixed, it just got reintroduced.

**Comment by SphiraI** [comment]
Dammit, there was an earlier one. #26276
