### ISSUE TITLE
nerf hamlet/buff shiva

### ISSUE THREAD

**Issue by Everturning** [space-wizards/space-station-14#26884]
## Description
nerf hamlet, mf should NOT be able to kite shiva from under a table, or renault

**Screenshots**

**Additional context**
had a hammy shitter start killing all the other station pets? why? fuck you thats why

**Comment by superjj18** [comment]
Ahelp would have nerfed that hammy way faster than a PR would

**Comment by Ghagliiarghii** [comment]
definitely a certified Ahelp moment
