### ISSUE TITLE
Zombies Don't Recognize II As II or Zombie After Turn

### ISSUE THREAD

**Issue by Admiral-Obvious-001** [space-wizards/space-station-14#26885]
## Description

This issue happened approximately 3 hours ago from the writing of this issue on Vulture (I forgot the round number, sorry). The zombie horde attacked an II but never received a zombification notice or icon on the person who was turned.

**Reproduction**

As a zombie, attack an initial until they turn. They won't get the zombie skull marker shown to them as a zombie, but ghosts will be able to see the II and skull marker.

**Comment by eoineoineoin** [comment]
Looks like this has been fixed. Zombified players will see IIs get a skull icon as expected. Are you able to confirm, or can I close the bug?

**Comment by Admiral-Obvious-001** [comment]
I've seen it work correctly in a recent shift, so this can be marked as resolved.
