### ISSUE TITLE
Stack refactor

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#2690]
Currently with this code every time you want different items to be stackable you need to add them to an enum on the shared stack component which is icky and means anything dealing with stack code needs to be aware of it which is especially dirty in construction.

I'm not sure what the ideal system would look like but ideally 
a) you'd just be able to mark something as stackable and be able to stack them with the same prototype(?). Whether there is a wrapper entity for the stack or whatever I don't know.
b) be able to have common stack groups for stuff that really needs it (e.g. different types of boards).
c) Have a helper so you can easily spawn either an individual entity or a stack as required. #2675 has helpers for this but it requires the stacktype enum.

Material has some oldcode that could probably do with a lookover at the same time (e.g. it has blunt damage on it).

**Comment by RemieRichards** [comment]
Make `StackType` a string, not an enum. Job done.

**Comment by Zumorica** [comment]
Ironically, `StackType` is already of type `object`, which means it could be an enum, a string or something else

**Comment by RemieRichards** [comment]
Oh well the entire point is moot then, you don't have to update the enum to make things stack.

**Comment by Zumorica** [comment]
Indeed. Although we should probably refactor stack code anyway and use prototypes or something...

**Comment by PJB3005** [comment]
Do not check prototype IDs for equality.

**Comment by Zumorica** [comment]
By my last comment, I meant having some sort of `stack` prototype with IDs. Those would hold certain useful information (icon to refer to the stack/material, default entity prototype ID perhaps, max count possible, etc) and stack components would set their stack type to those.

**Comment by SweptWasTaken** [comment]
Please please fix this.

![108477656-67a7c180-728b-11eb-9d54-5feba00358cb](https://user-images.githubusercontent.com/49448379/108477878-b5242e80-728b-11eb-88b9-bbef2ee0dad6.png)

**Comment by SweptWasTaken** [comment]
Pretty sure this was fixed by Smug. Closing.
