### ISSUE TITLE
Network UI will stay even if you throw multitool away

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#26904]
1. open network UI
2. hide multitool in belt
3. still can connect

**Comment by metalgearsloth** [comment]
probably https://github.com/space-wizards/space-station-14/pull/26888 ?

**Comment by lzk228** [comment]
still not fixed on https://github.com/space-wizards/space-station-14/commit/c8f75d99186301810a3c16d99ad138107637e723
![image](https://github.com/space-wizards/space-station-14/assets/124214523/906fb603-b773-4a8c-9316-6200a79521c0)

**Comment by eoineoineoin** [comment]
Seems this is fixed; putting the tool in an inventory closes the window, placing the tool on the ground within a small distance keeps the window open, but throwing the tool far away as in your screenshot will close the window. OK to close?

**Comment by lzk228** [comment]
yeah, tho it's weird i can do stuff on the video, the main issue is fixed

https://github.com/user-attachments/assets/85f1a2ec-8020-4c95-bd34-85be3f0bf203
