### ISSUE TITLE
Cryo messages seem to break when a player affected by a clerical error goes to cryo

### ISSUE THREAD

**Issue by lunarcomets** [space-wizards/space-station-14#26913]
## Description

the new system that makes records get removed from the manifest when someone cryos seems to clash with clerical error events due to how the system uses existing records for the messages.

**Reproduction**

1. have multiple characters on a station with at least one captain
2. add clerical error gamerule
3. stuff person affected by the error into cryo (not the captain)
4. message spits out 'Urist McHands (Captain) has entered cryogenic storage!' when the character isn't the Captain. removes the actual Captain's record from the manifest.

**Additional context**

probaly has something to do with defaulting to that record? checking to see if the record exists in the first place should fix the issue

**Comment by Tayrtahn** [comment]
I'm guessing the issue is on line 228 of CryostorageSystem: https://github.com/space-wizards/space-station-14/blob/master/Content.Server%2FBed%2FCryostorage%2FCryostorageSystem.cs#L228

Using the default value for unit (0) is probably where the captain is getting selected.

**Comment by Tayrtahn** [comment]
Can also be reproduced by putting anyone who isn't on the crew manifest into cryostorage (like any of the Urists on Dev).
