### ISSUE TITLE
Honkbot AI behavior broken

### ISSUE THREAD

**Issue by superjj18** [space-wizards/space-station-14#26929]
## Description
Honkbot AI behavior has been broken in some way.  It simply stands still and honks consistently on honk-cooldown.

**Reproduction**
Spawn honkbot

**Screenshots**
https://github.com/space-wizards/space-station-14/assets/8095092/b7c457ef-ea7d-4f6e-80b0-7a13dca7a849

**Comment by K-Dynamic** [comment]
Pretty sure this is fixed as of now

source: trying to fix a different bug and watching honkbots zoom around

**Comment by Tayrtahn** [comment]
Fixed by #26939
