### ISSUE TITLE
Cannot link doors to signal buttons while the map is uninitialised

### ISSUE THREAD

**Issue by Kukutis96513** [space-wizards/space-station-14#26923]
## Description

You can't link doors to signal buttons while the map is uninitialized.

**Reproduction**

Load a uninitialized map and try to link a door to a signal button.
**Screenshots**

![Screenshot_295](https://github.com/space-wizards/space-station-14/assets/146854220/269c27a6-229e-4d24-9efe-7ddd0d432e62)
**Additional context**

I think this was caused by the PR that made it so you can manage door access by simply interacting with the door electronics.

**Comment by lzk228** [comment]
dupe of https://github.com/space-wizards/space-station-14/issues/26802
