### ISSUE TITLE
Monkey handheld item displaced wrong

### ISSUE THREAD

**Issue by BellwetherLogic** [space-wizards/space-station-14#26940]
## Description
This originally began with me noticing that the caual red jumpsuit (and presumably the other casual jumpsuits) don't have a monkey sprite ... but monkeys can still equip them anyway, along with the colorful costumes. It looks extremely silly (which is not necessarily a bad thing, but it's definitely unintended). I was going to report that, but then I noticed that my toolbox sprite was hanging much lower than it should, down near my feet. 

Having tested this multiple times, however, it's not just the casual jumpsuit that does this - even a naked monkey that has never interacted with clothing has this problem. I gave a quick look at the issue tracker and didn't see anything about this, and I've never seen this happen before, so I have to assume it's a new bug. 

**Reproduction**
1) Be a monkey 
2) pick up a toolbox, stack of materials, etc. It doesn't seem to affect every item but smaller items might just not get displaced as much. 

**Screenshots**

![2024-4-13_19 22 12](https://github.com/space-wizards/space-station-14/assets/157836624/fafaa221-e9ea-4ec0-aa74-2eef20a4c0fc)

![2024-4-13_18 44 19](https://github.com/space-wizards/space-station-14/assets/157836624/bc71eec2-f62a-42ca-a43f-ff4594e08c50)

**Comment by UbaserB** [comment]
Repeat of #26940 actually
