### ISSUE TITLE
Clown shoes waddling animation bugs out when slipping

### ISSUE THREAD

**Issue by Killerqu00** [space-wizards/space-station-14#26950]
## Description

If you slip in clown shoes, you do not actually look like you slipped. Instead, you waddle in place.

**Reproduction**

1. Wear clown shoes
2. Slip yourself

**Screenshots**

https://youtu.be/fcd6ShpTZGk

**Additional context**

**Comment by dragonryan06** [comment]
These shoes are the buggiest thing in the game right now I don't even understand how this PR made it through

![image](https://github.com/space-wizards/space-station-14/assets/71857681/ec162efd-41ce-4feb-994e-8b0092871361)

Even a dead clown wearing clown shoes will dance around if buckled to a bed.

The walk-detection being used to stop the animation is also very imperfect, and often times while standing still the animation will continue.

I really like the idea, but please test your code before submitting it!!

**Comment by superjj18** [comment]
> I really like the idea, but please test your code before submitting it!!

You clicked “join playtest” when you downloaded the game, we ARE testing their code :trollface:

**Comment by FairlySadPanda** [comment]
Pretty much, especially because getting this working involves bolting the animation on top of empty space - there's no animation state machine for mob movement.

**Comment by slarticodefast** [comment]
waddling has been reverted and will need a proper re-implementation with an animation system
