### ISSUE TITLE
clown sleep mimimimimni is so fkin loud

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#26962]
## Description

Really annoying
**Reproduction**

**Screenshots**

**Additional context**

**Comment by DogZeroX** [comment]
Honestly should really quiet it down or split it into smaller sounds so it's not so long

**Comment by UbaserB** [comment]
i agree

**Comment by Hmeister-real** [comment]
intentional :godo:

**Comment by tosatur** [comment]
This issue can be closed
