### ISSUE TITLE
clowns don't waddle in replays

### ISSUE THREAD

**Issue by Mangohydra** [space-wizards/space-station-14#26964]
## Description
clowns don't waddle in replays and instead walk like normal, not sure why its just saddening to not see clowns waddling in the replays

**Reproduction**
open a replay

**the**
https://github.com/space-wizards/space-station-14/assets/156087924/90072a15-0149-49a0-a69c-61ebc0bbc0f0

**Additional context**
outrageous and a crime, honk

**Comment by slarticodefast** [comment]
waddling has been reverted and will need a proper re-implementation with an animation system
