### ISSUE TITLE
people wearing clown shoes keep waddling on crit/death

### ISSUE THREAD

**Issue by baddiePRO** [space-wizards/space-station-14#26977]
## Description
clowns and other people wearing clown shoes continue to wake when they're crit or dead

**Reproduction**
>wear clown shoes 
>get brutally murdered 
>watch your lifeless corpse dance for all eternity

**Screenshots**
https://github.com/space-wizards/space-station-14/assets/46608342/c9acd650-ec83-4057-85e7-d45b1f3f6747

**Additional context**

**Comment by K-Dynamic** [comment]
Definitely feature not bug :trollface:

**Comment by luizwritescode** [comment]
AFAIK When I managed to ghost role as pAI close to my lifeless waddling body, it stopped waddling. Which lead me to belived this is Client-side.

Try to check if crit/dead clown keeps waddling from other player's perspectives

**Comment by engineer-pearl** [comment]
I can confirm they do. That dead waddling zombie clown gave me a few scares.

**Comment by slarticodefast** [comment]
waddling has been reverted and will need a proper re-implementation with an animation system
