### ISSUE TITLE
Syring after syringing blood discards collected blood's DNA

### ISSUE THREAD

**Issue by TokenStyle** [space-wizards/space-station-14#26973]
## Description
Syring removes DNA from the entity's blood it took. No DNA on blood after spill liquid action on ForensicScanner.
On image with number 1 - took blood with syringe and spill it on floor, you can see DNA was removed
On image with number 2 - original blood had DNA

**Reproduction**
Get blood from Urist, make sure he really has DNA by using ForensicScanner.
Take syringe and took his blood (from his or from the floor) and spill liquid on the ground.
Scan blood with ForensicScanner, and you see that's no DNA on the blood.

**Screenshots**
![snapshot syringe](https://cdn.discordapp.com/attachments/1229352457294057483/1229352457952559124/image.png?ex=662f5eb2&is=661ce9b2&hm=41d11db9e51daec06dcf7548b8ba9939281d75a11d41421f698fffbb77794b72&)

**Additional context**
Discord post: https://discord.com/channels/310555209753690112/1229352457294057483/1229352457294057483

**Comment by 0x6273** [comment]
This is being fixed in https://github.com/space-wizards/space-station-14/pull/26699

**Comment by TokenStyle** [comment]
> This is being fixed in #26699

Hi, could you please mention my issue? So it issue'll close after PR is will be finished #26973
Thanks!

**Comment by eoineoineoin** [comment]
Confirmed fixed; thanks for the report.
