### ISSUE TITLE
Everyone on the crew monitor is marked as "Good" when they are not

### ISSUE THREAD

**Issue by MarzieK** [space-wizards/space-station-14#26979]
## Description
Everyone on a crew monitor is showing up as in "Good" health when they are in fact not.

**Reproduction**
Have someone be in a health state that is Bad, Poor, or Okay and they will still show up on a crew monitor as "Good" (works on CMO's handheld too)

**Screenshots**
https://i.gyazo.com/f7a66c02fd0a403cd808780c113b9565.png

**Additional context**
There was a dead body from Salv that showed up as "Dead". I don't believe it was showing Crit people either, I think they were also being labeled as "Good".
I waited 5+ min to see if it would fix/update itself and also relogged, did not fix it.

**Comment by Hanzdegloker** [comment]
I have seen this before also, tis very annoying
