### ISSUE TITLE
TypingIndicatorClothing removes species-specific typing indicator when taken off

### ISSUE THREAD

**Issue by pissdemon** [space-wizards/space-station-14#26984]
## Description
If you put on a piece of clothing that changes your typing indicator as a non-human species and take it back off, you lose your species specific typing indicator and go back to the generic human one.

**Reproduction**
1. Be a moth, lizard or anything else with a species specific typing indicator
2. Talk: you see the special typing indicator
3. Wear a clothing item with TypingIndicatorClothing, e.g. "cardborg helmet"
4. Talk: you see the overridden typing indicator set by the clothing you wear
5. Take item off again
6. Expectation: It shows your species specific typing indicator again
    Actual behavior: It shows the generic human talking icon

**Additional context**
https://github.com/space-wizards/space-station-14/blob/faba129e780859336cfa1a97bb492e7044348ed2/Content.Shared/Chat/TypingIndicator/SharedTypingIndicatorSystem.cs#L36-L42
This is setting it to the "default" typing indicator but it should set it to the previous/species specific one instead. Alternatively, establish a way to set a typing indicator override that doesn't touch the original indicator setting.

**Comment by eoineoineoin** [comment]
Was fixed by https://github.com/space-wizards/space-station-14/pull/29492, thanks for the report!
