### ISSUE TITLE
Medical Doctor Loadout's Senior Physician PDA starts with a blank medical-trim ID

### ISSUE THREAD

**Issue by MjrLandWhale** [space-wizards/space-station-14#27015]
## Description

I set up a loadout for my medical doctor, and chose the senior physician PDA option. I then loaded into the round as a doctor and my ID was blank with no name, no permissions, etc.

**Reproduction**

Set up a loadout for my medical doctor, and chose the senior physician PDA option. Spawn in and remove the ID from your PDA. Observe suffering
**Screenshots**

**Additional context**

Caused by #25715

**Comment by lzk228** [comment]
I tested giving a preset for ID - isnt working
place medical id in physician pda - still isnt workng

if someone want to fix that in the easiest way - just remove this loadouts

**Comment by Dutch-VanDerLinde** [comment]
> I tested giving a preset for ID - isnt working
> 
> place medical id in physician pda - still isnt workng
> 
> 
> 
> if someone want to fix that in the easiest way - just remove this loadouts

Probably something with the PDA then? Maybe check it out
