### ISSUE TITLE
Jobs that have ID card loadouts don't set the ID to the character's name

### ISSUE THREAD

**Issue by Dutch-VanDerLinde** [space-wizards/space-station-14#27024]
## Description
title

**Reproduction**
- Use a loadout with an ID (scientist, engineer, sec)
- look at ID card

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/45323883/e6cd918d-01dc-4588-8dba-2a2bd7d0fb60)

**Additional context**
i'm guessing this is because the startingGear will apply the ID card a name when applied to an entity, but loadouts don't do that

**Comment by Dutch-VanDerLinde** [comment]
> that what i was talking about in [#27015 (comment)](https://github.com/space-wizards/space-station-14/issues/27015#issuecomment-2059544588) and ##27017 that was supposed to fix that, did ABSOLUTELY NOTHING

no it was supposed to fix the crew manifest and job title being invalid

**Comment by Dutch-VanDerLinde** [comment]
which it did

**Comment by Dutch-VanDerLinde** [comment]
![image](https://github.com/space-wizards/space-station-14/assets/45323883/0a6c08b2-3a6b-4693-9bab-8486a68f4a3a)
this

**Comment by MjrLandWhale** [comment]
Ahh, so it fixed an issue that I didn't even notice at first. What's interesting, is that it appears permissions work with the senior PDAs, but the ID card itself still doesn't have a name attached to it.

**Comment by Dutch-VanDerLinde** [comment]
> Ahh, so it fixed an issue that I didn't even notice at first. What's interesting, is that it appears permissions work with the senior PDAs, but the ID card itself still doesn't have a name attached to it.

The name doesn't appear for normal science IDs too (any loadout with selectable IDs)
