### ISSUE TITLE
Secoffs spawning without armor and boots.

### ISSUE THREAD

**Issue by thebadman4662** [space-wizards/space-station-14#27059]
## Description
Despite having them selected in my loadout, I started(latejoin) shift without those.

**Comment by Dutch-VanDerLinde** [comment]
Is this only for sec, or every job

And is it only for latejoining or spawning

**Comment by lzk228** [comment]
cannot reproduce

**Comment by thebadman4662** [comment]
> Is this only for sec, or every job
> 
> And is it only for latejoining or spawning

Happened only for latejoin seccie and only once so far.

**Comment by thebadman4662** [comment]
Resolved I think...
