### ISSUE TITLE
Prevent late-joining while evacuation shuttle is docked or in flight to CentComm

### ISSUE THREAD

**Issue by ilyamikcoder** [space-wizards/space-station-14#27053]
## Description
Title. CentComm shouldn't send anybody to the station while it is actively evacuating - this leads to extremely awkward situations.

**Reproduction**
1. Late-join on your favorite SS14 server
2. Arrive at the station
3. Wonder where everybody is
4. Get an announcement saying that evacuation shuttle leaves in 10 seconds
5. Guess I'm screwed

or

1. Late-join on your favorite SS14 server
2. Arrive at the station
3. Round end screen appears
4. What?

**Screenshots**
N/A

**Additional context**
Could gray out the join button during evacuation, with a tooltip explaining the problem.

**Comment by keronshb** [comment]
This is kind of a funny old staple in space station, I don't really see it as a need.
