### ISSUE TITLE
teg shouldnt need power to make power

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#27085]
## Description
because teg needs power and every map has it on the same apc net as a bunch of other stuff **including freezers** teg regularly gets browned out from apc load drops, which then troll the entire station

teg needing power bad:
- see above
- as a sabotage vector theres much easier ways to sabotage it that dont need insuls/turning an apc off
- for bootstrapping a jr pacman on 1kw can power it
- if you want to power it properly to avoid spikes you need to make a floating apc on it which is cringe
- **no other generator in the game does this**
- power outage event has no impact since it doesnt ramp down to 0 production when off, it just gets back off where it was once power is back

**Comment by PJB3005** [comment]
Rename this issue to "somebody map radiators on the TEG setups already, or figure out why radiators can't be mapped on the TEG setups yet"

**Comment by deltanedas** [comment]
radiators help but if the apcs load is more than 1kw its still bad

**Comment by PJB3005** [comment]
> radiators help but if the apcs load is more than 1kw its still bad, and apc in atmos almost always is a few kw more

As we all know, all standard Nanotrasen engines can be bootstrapped with less than 1 kW of pow-
![image](https://github.com/space-wizards/space-station-14/assets/8107459/0e6bb3fd-c631-4977-abb7-c62dcfe0d997)

**Comment by PJB3005** [comment]
No, seriously, you aren't supposed to be able to bootstrap a fucking engine with a JRPACMAN. That is not what they are for. Now if we're discussing REGULAR PACMANs with their 30 kW capacity we're talking.

**Comment by Partmedia** [comment]
As discussed on this linked PR, I don't think this is an issue with the TEG, but rather a specific issue with mapping and/or how the engineers choose to setup power.
