### ISSUE TITLE
shiva can pry bolted doors

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#27087]
## Description
wtf real

**Comment by nikthechampiongr** [comment]
Unfathomably based. Anyways that's because Shiva inherits from the spider proto which has the prying component with pryPowered(pry powered doors) and force(pry bolted doors) bools to true.

**Comment by nikthechampiongr** [comment]
See #23449

**Comment by Brandon-Huu** [comment]
Should this issue be closed?

**Comment by eoineoineoin** [comment]
Duplicate of https://github.com/space-wizards/space-station-14/issues/30157
