### ISSUE TITLE
Most maps fail to load the entities inside entities

### ISSUE THREAD

**Issue by VasilisThePikachu** [space-wizards/space-station-14#27089]
## Description

Bisect leads to #27077 and #26994

what I noticed is that any entities that are inside another entity like

- Items inside lockers
- Light bulbs in light fixtures, 
- Chems inside the chem master are not appearing
- Solutions in remapped liquids and foods

Just dont appear
I have seen the following and heard
- Auto proto fabricator lathes animation is broken (eric156)
- Arcades and vending machines say their advertisements all at the same time.

**Reproduction**

1. Be on master (before #27090)
2. Start any map that is not Europa, Omega or Reach (https://discord.com/channels/310555209753690112/770682801607278632/1230514404383133726)
3. Observe

**Comment by Plykiya** [comment]
#27184 
Nukies are apparently dying instantly to their map being unitialized

**Comment by ElectroJr** [comment]
> Nukies are apparently dying instantly to their map being unitialized at round start

#27201 should've fixed nukies

**Comment by UbaserB** [comment]
This might be related? [27193]
