### ISSUE TITLE
How to invisibility 

### ISSUE THREAD

**Issue by ARMOKS** [space-wizards/space-station-14#27092]
## Description
Step 1) Apply cham projector to cigarette in pocket
Step 2) Youre invisible now for some reason
Mystery step) Sometimes perma breaks the projector for some reason

**Comment by deltanedas** [comment]
cant repro this, at least outside of pocket with any kind of cigarette either burned unlit lit or spawned burned

**Comment by hitomishirichan** [comment]
we experienced this bug with the chameleon projector the first time we used it actually. the invisibility was desynced between players so it was just us who saw us as invisible as far as we could tell

**Comment by deltanedas** [comment]
wont matter with rewrite

**Comment by beck-thompson** [comment]
Think this is another duplicate!
