### ISSUE TITLE
RDs hardsuit storage issue

### ISSUE THREAD

**Issue by DummeHytteOst** [space-wizards/space-station-14#27091]
## Description
You can place the RD hardsuit in a tool belt, and its for some reason only 2x2 which is ridiculously small for what it is, it should at the very least be increased to 3x3 or 2x4 just so you can still carry in a bag for that green text

**Reproduction**
Place the RD hardsuit in a belt

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/94384139/7f7b7be5-a56a-4f6a-bc11-f3d1678045d9)
**Additional context**
Too small 🤏

**Comment by Dutch-VanDerLinde** [comment]
Just blacklist it from the belt, it's supposed to be small because it's a steal objective

**Comment by DummeHytteOst** [comment]
> Just blacklist it from the belt, it's supposed to be small because it's a steal objective

2x2 still feels way too small even if its a steal objective, 3x3 or 2x4 feels more appropriate

**Comment by Dutch-VanDerLinde** [comment]
Survival box sized?

**Comment by DummeHytteOst** [comment]
> Survival box sized?

yes, survival box is 3x3 so yeah

**Comment by Djungelskog2** [comment]
it seems like an odd thing to have as an objective in the first place

**Comment by Djungelskog2** [comment]
I meant in that its a hardsuit/piece of clothing, and how common it is to just be worn by the RD with such a noticeable sprite change once being taken

**Comment by Dutch-VanDerLinde** [comment]
> I meant in that its a hardsuit/piece of clothing, and how common it is to just be worn by the RD with such a noticeable sprite change once being taken

just shoot the RD, no need for thieving gloves

**Comment by Djungelskog2** [comment]
for an objective thats supposed to be stolen its doing everything that makes it hard to steal which kinda limits your options and makes it a glorified kill objective and a waste of space in your bag
