### ISSUE TITLE
Server lag at 9:33PMUTC on Lizard

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#27106]
I think it's 18/04/2024 in nerd time.

Making an issue that performance fucking died with allocations spiking but let's be real no one's following up on this anyway.

**Comment by lzk228** [comment]
bruh

**Comment by slarticodefast** [comment]
> let's be real no one's following up on this anyway.

I guess you were right and I doubt anyone will look into it now after this much time has passed. Hard to say if the issue still exists. Therefore I'm closing this issue, if it comes up again we can make a new one.
