### ISSUE TITLE
Dice bags do not correctly spawn at start of round

### ISSUE THREAD

**Issue by Plykiya** [space-wizards/space-station-14#27101]
## Description

They dump all their contents and the dice bag itself is completely missing

**Reproduction**

**Screenshots**

**Additional context**

**Comment by Lamrr** [comment]
I could not reproduce this, using Core as a test I found the dice bag mapped in the bar remains extant on round start. Something I did find though is that Box does not use any dice bags, but instead uses a stack of dice piled on top of each other. Could this be the issue you were having?
![Screenshot from 2024-04-28 19-43-06](https://github.com/space-wizards/space-station-14/assets/96937466/135ec92f-f239-49ec-90b9-6405f5ad5aef)

**Comment by Plykiya** [comment]
ah... that does seem to be the case
