### ISSUE TITLE
the crew monitoring console is broken

### ISSUE THREAD

**Issue by Redfire1331** [space-wizards/space-station-14#27146]
## Description
 when cords are on the only state that is shown is dead bad (crit) and good, meaning if some one has 97 damage the crew monitor will still show good. 

**Reproduction**
 turn on cords, beat yourself to near crit, and look at the crew monitor, itll show you as good. 

**Screenshots**

<img width="623" alt="ss14 bug report image" src="https://github.com/space-wizards/space-station-14/assets/125223432/1c29cd0b-270d-4f9b-9687-2f9acda31484">

**Additional context**
image is me im sam wise, my condition is bad but the console is showing good

**Comment by Rainbeon** [comment]
Pretty sure this was caused by #26658 which messed with the rounding and how it grabs. Critical states also do not display correctly and only display as "BAD!" instead.
