### ISSUE TITLE
evac shuttle never arrives but it leaves

### ISSUE THREAD

**Issue by Everturning** [space-wizards/space-station-14#27147]
## Description
title. syndies with escape objectives stay losing

**Reproduction**
>be captain
>call shuttle
>wait 10 minutes and then some
>EVAC SHUTTLE LEAVING IN 10 SECONDS
>WH-
>EVAC SHUTTLE HAS LEFT THE STATION

**Screenshots**

**Additional context**

**Comment by MjrLandWhale** [comment]
Duplicates #27140, already fixed by #27144. Please close
