### ISSUE TITLE
Evac shuttle doesnt arrive

### ISSUE THREAD

**Issue by Tyzemol** [space-wizards/space-station-14#27140]
## Description

Announcement about shuttle docking never comes.
Nor does the shuttle.
However the announcement about shuttle leaving (the one that never spawned) does come

**Reproduction**

I personally only played on miros and it happened there twice in a row so _probably_ consistent bug on any wizden server.

**Screenshots**

**Additional context**

**Comment by Kayek14** [comment]
Can confirm that this is also happening on levi

**Comment by Erisfiregamer1** [comment]
Occured on round 51527, can confirm.

**Comment by MjrLandWhale** [comment]
Almost certainly caused by #27126

**Comment by ElectroJr** [comment]
> Almost certainly caused by #27126

I'll double check in about an hour, but I did check that both of the initialization methods still get called when starting a round, so not sure how that would've broken things.

**Comment by MjrLandWhale** [comment]
Is the station initialized before centcomm? Is there some weird scenario where we attempt to initialize the shuttle on an uninitialized map or station and it shits the bed?

**Comment by ElectroJr** [comment]
#27144 should've fixed it
