### ISSUE TITLE
Unable to eat food with bandana on

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#27163]
## Description

"You need to take off the black bandana first!"

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/134914314/c47f417a-99d3-48c1-b1d8-d35ef694012d)

**Comment by lzk228** [comment]
usually it happens after you wear bandana as a mask and then the same bandana on head

**Comment by UbaserB** [comment]
I had nothing in my mask slot, only bandana on head.

**Comment by Winkarst-cpu** [comment]
I think this is should be closed, because it's no longer an issue...

**Comment by UbaserB** [comment]
> I think this is should be closed, because it's no longer an issue...

The fix hasn't gotten merged yet

**Comment by Winkarst-cpu** [comment]
> > I think this is should be closed, because it's no longer an issue...
> 
> The fix hasn't gotten merged yet

https://github.com/user-attachments/assets/7540a9e0-8995-4431-8d0f-0604933c5ec4

**Comment by stalengd** [comment]
@Winkarst-cpu Have you tried to reproduce the error in the way shown in my PR? Just wearing a head bandana does not produce a bug, its a bit complicated.
