### ISSUE TITLE
RCD is blocked by open shutters, blastdoors and directional windows

### ISSUE THREAD

**Issue by Lamrr** [space-wizards/space-station-14#27167]
## Description

The RCD considers open shutters, open blast doors and directional windows as occupied space. You cannot use it construct, grilles, windows, etc. underneath these tiles. This can make repairing windows that are under open shutters more difficult.

**Reproduction**

1. Attempt to use RCD to build a grille underneath a blast door.
2. Receive "You can't build here, the space is already occupied message!".

**Screenshots**

![Screenshot from 2024-04-20 22-20-07](https://github.com/space-wizards/space-station-14/assets/96937466/33cc84a7-3f4a-4738-a7c9-b438a231b40c)
![Screenshot from 2024-04-20 22-20-22](https://github.com/space-wizards/space-station-14/assets/96937466/bcdca4ad-08a5-462a-8758-aace4fef464f)

**Additional context**

We probably want the RCD to be able to build at least windows, grilles, machine frames and other non-wall things underneath open shutters, open blast doors and directional window so engineers can fix these things that are commonly under these tiles. We may or may not want to be able to build walls with the RCD under these tiles.

I have not checked fire doors and airlocks, they may have similar issues.

**Comment by deltanedas** [comment]
thindows shouldnt make a tile occupied anyway so you can anchor things, remove tiles etc

it should have a fixture check or something for building then so you cant stack them, then it can also allow making multiple thindows on different sides of a tile
