### ISSUE TITLE
Cargo system bugs

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#2717]
A general thread for improvements to the cargo system. 

- [ ] The way icons for the cargo console listings are formatted in YAML are bad. You have to explicitly point to the sprite for the icon in the menu. It would be better if the console randomly chose an item in the crate as a sprite, or didn't show an icon at all, without expanding the view to show more details.
- [ ] The cargo console currently gets a list of all it's products from a [list defined in it's entity YAML](https://github.com/space-wizards/space-station-14/blob/master/Resources/Prototypes/Entities/Constructible/Power/cargo_console.yml). This is bad practice and should be it's own file. 
- [x] Cargo crates should not spawn on top of the cargo console. At the very least before shuttles are in, there should be a simple "crate teleportation spawner" that takes 20 seconds to spawn in the crate.
- [ ] A way to generate points. Again, if shuttles aren't implemented, just make a teleporter you can put stuff into and activate that  will give you points. (The addition of this system will also require all objects to have an export_value. You could do it easy mode and just add a component to every object prototype, or dynamically generate the export_value like [tgstation does it](https://github.com/tgstation/tgstation/blob/master/code/modules/cargo/exports.dm).

(I will keep this thread updated)

**Comment by SweptWasTaken** [comment]
#2579 knocks one of these off the list.

**Comment by Peptide90** [comment]
Can #2410 be merged with this?

**Comment by Zumorica** [comment]
I'm closing #2410 in favor of this

**Comment by Peptide90** [comment]
Cargo console list of products is now with the cargo console in [computers here (Resources/Prototypes/Entities/Structures/Machines/Computers/computers.yml). (Above link on point 2 invalid).

Having a list of cargo products not in the catalog where the products actually are seems silly and is easy to miss. Maybe the solution is revamping the cargoProduct component to have a market datafield, then revamp the galacticmarket component to have a corresponding datafield so if the two match you can access all products on that market. (This is if we want different markets for different stations, ships etc like syndi market, black market)

**Comment by mirrorcult** [comment]
these are all pretty much done
