### ISSUE TITLE
Department icons not visible

### ISSUE THREAD

**Issue by Crazygamer2332** [space-wizards/space-station-14#27178]
## Description
I am unable to see the department names when I look at the map I have "show departments" on but they aren't visible.

**Screenshots**
![Screenshot 2024-04-20 183442](https://github.com/space-wizards/space-station-14/assets/167641504/14feca18-daf7-48fe-b2d8-95d01c0ae6b0)

**Comment by Crazygamer2332** [comment]
Its working now

**Comment by Mirino97** [comment]
![image](https://github.com/space-wizards/space-station-14/assets/52474532/0f20bdd5-1401-4a4e-88da-640a74ae9d12)

Confirmed locally, currently working.
Reopen if problem reappears :D
