### ISSUE TITLE
Bible is not healing

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#27185]
## Description
The bible seems to be broke. Ive seen two seperate reports today of the bible going on cooldown but not applying the heal to the target.

**Reproduction**
Be chap
Use bible on a target

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/106507028/d8b925b6-f742-4c05-8b4a-6959e7b30ad9)

![image](https://github.com/space-wizards/space-station-14/assets/106507028/28df28f2-7f19-4312-8537-74eabb411029)

**Comment by Vermidia** [comment]
Affects sizzles too
Caused by #25970 I think (Bible is storage, and since that resets it's delay well...it just doesn't work. Making the bible not store anything makes the bible work again)

**Comment by Tayrtahn** [comment]
> Affects sizzles too
> Caused by #25970 I think (Bible is storage, and since that resets it's delay well...it just doesn't work. Making the bible not store anything [aka parent off of base item and such] makes the bible work again)

Nice sleuthing! I think you found the problem - both the Bible and the storage system are trying to use the same UseDelay. Now, how to fix that...

**Comment by Tayrtahn** [comment]
Oh hey, look at that.

UseDelayComponent.cs:
```
/// <summary>
/// Timer that creates a cooldown each time an object is activated/used
/// </summary>
/// <remarks>
/// Currently it only supports a single delay per entity, this means that for things that have two delay interactions they will share one timer, so this can cause issues. For example, the bible has a delay when opening the storage UI and when applying it's interaction effect, and they share the same delay.
/// </remarks>
