### ISSUE TITLE
hands are too far from the other ui even without item

### ISSUE THREAD

**Issue by Everturning** [space-wizards/space-station-14#27216]
## Description
title

**Reproduction**
>play the game
>hands wide from far to backpack
**Screenshots**
![Screenshot 2024-04-21 115142](https://github.com/space-wizards/space-station-14/assets/146485322/9e15831b-ee01-4dd6-bada-d9f151244c65)

**Additional context**

**Comment by Dutch-VanDerLinde** [comment]
this is intended

**Comment by ShadowCommander** [comment]
Intended behavior #22986
