### ISSUE TITLE
UI scaling woes

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#2721]
Been a while since I've run master but now:
1. Stuff that's supposed to track to your entity position (do_after and popups are two easy ones) aren't in the correct position
2. do_after bar texture width doesn't align with bar now
3. UI is hilariously massive. I guess it chooses scaling based on monitor size (I have a 4k monitor) rather than window size which is a bit of a problem if you don't run it fullscreen.
4. Vending machine entries don't align with where you click.
Edit 5. Items in inventory / hand slots don't have their textures scaled (this one might be tricky with current inventory code?)
![image](https://user-images.githubusercontent.com/31366439/102003122-79368f80-3d57-11eb-8012-ff5b441a5881.png)

Screenshot taken after I made the window a bit bigger.

![image](https://user-images.githubusercontent.com/31366439/101447624-afe86080-3979-11eb-8d5c-db9df3c78913.png)

**Comment by SweptWasTaken** [comment]
Smh flexing with your 4K monitor...

But seriously, are you sure that's not just your settings?

This is my 1440p monitor after I made the window bigger. I also cannot see the vending machine UI bug you're mentioning.

![image](https://user-images.githubusercontent.com/49448379/101447919-1770c280-391e-11eb-8917-3738b737e437.png)

**Comment by metalgearsloth** [comment]
I've never touched the scaling. Currently in client_config.toml it has:
uiScale = 1.0
fontdpi = 96

I tried deleting it but no dice.

**Comment by metalgearsloth** [comment]
Also what's your UI Scale at ingame? It's fine on 100% but this is defaulted to 150%.

**Comment by PJB3005** [comment]
> Currently in client_config.toml it has:

Which `client_config.toml`? I recently moved the data directory for the client so you're probably looking at the wrong one.

> UI is hilariously massive. I guess it chooses scaling based on monitor size (I have a 4k monitor) rather than window size which is a bit of a problem if you don't run it fullscreen.

We're just using the scaling factor the OS gives us so... I guess not much we can do here?

> But seriously, are you sure that's not just your settings?

Literally the whole point of the issue is that UI scaling is broken, which is a setting...

**Comment by metalgearsloth** [comment]
It was under the root directory for AppData\Roaming\Space Station 14\client_config.toml and also the one under .\data\client_config.toml (which I figure is the new one)

3. Is probably okay if the game defaults to being the full window size (probably make an issue for a cvar for it?). For debugging I'll just set the client_config.toml under data for scaling.

I see AAA games routinely screw this up so I'm used to it but it probably should be fixed before playtesting.

**Comment by PJB3005** [comment]
> For debugging I'll just set the client_config.toml under data for scaling.

You can change the scaling in the options menu.

**Comment by rneuser** [comment]
I am working on fixing the do_after and popup notification positions

**Comment by rneuser** [comment]
Looks like the vending machine issue runs real deep into RobustToolbox and I can't really make much sense out of all this UI code to be honest

**Comment by metalgearsloth** [comment]
In case anyone's wondering who hasn't had scaling problems in a game before I've outlined the hitbox of the bottom item on this vendor which means you'll probably misclick what you want:

![image](https://user-images.githubusercontent.com/31366439/102003030-87d07700-3d56-11eb-9814-bf5edbe94d3b.png)

**Comment by chairbender** [comment]
the issue with tiny items in inventory is because the control used for those, SpriteView, doesn't scale with UIScale, as mentioned by PJB:
"yeah we need proper game world scaling including that
I figured doing awful nearest neighbor would be worse than simply leaving them unscaled"

**Comment by AJCM-git** [comment]
@metalgearsloth this probably needs some updating in the main issue (the current problems are the popup messages and UI starting massive if not in fullscreen)
