### ISSUE TITLE
Loading and watching replays uses way too much RAM

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#27217]
## Description
While loading and playing a replay, i found that it was allocating all of my computer's ram. It eventually ground itself down and stoped responding. 

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/106507028/f28f07e3-9cac-4586-9caa-9029eb1d7e0b)

First ss14 is the replay
Second ss14 is a round i was connected to at the time of loading a replay.

**Additional context**
Round reaply that i downloaded and played was Lizard 51680

**Comment by deltanedas** [comment]
same on linux it ate all my ram and 3gb swpa before i killed it

**Comment by AJCM-git** [comment]
Some replays do that, IIRC the """fix""" is unzipping the replay, deleting  X number of parts, fixing the manifest and zipping again (May have skipped a step here). Otherwise gotta wait until someone makes the player only play the requested timespan

**Comment by Kayek14** [comment]
Seems to be resolved
