### ISSUE TITLE
Feature request: Disable explosives on shuttle

### ISSUE THREAD

**Issue by Everturning** [space-wizards/space-station-14#27215]
## Description
people keep saving all their TC until shuttle and bombing it, leading to uninteresting gameplay during the round. why have fun when you can get the sweet green by doing fuck all

**Screenshots**

**Additional context**
shuttle bombing is hated pretty commonly in game, but never talked about here. this will both make shuttle destruction more interesting and leave more room to act during the round.

**Comment by EmoGarbage404** [comment]
1. this is barely a feature request
2. this has been discussed multiple times at length: even if we did want to get rid of general shuttle bombing (which is generally not what maints are going for right now) disabling all explosives is absolutely not the way to do that.

**Comment by Djungelskog2** [comment]
the best way to go about it (I THINK) is either making it more clear where escape pods are for safe evacs and making syndi bombs not completely luck oriented
