### ISSUE TITLE
Examining hand slots will examine the item underneath the UI

### ISSUE THREAD

**Issue by Plykiya** [space-wizards/space-station-14#27221]
## Description

Examining any other hotbar slot will work properly, it's only the hands that allow you to examine underneath them. Extremely annoying.

**Reproduction**

1. Have item in hand
2. Try to examine item in hand
3. Notice that you will often examine what is underneath the UI

**Screenshots**

**Additional context**

**Comment by Clone0401** [comment]
i was going to put it in github but completely forgot
this is what i posted about in the bugs and feedback on discord: https://discord.com/channels/310555209753690112/1225217945056313364

**Comment by PJB3005** [comment]
In the area dealing with item status so guess I'll fix this real quick.
