### ISSUE TITLE
Slimes cant be cuffed outside of combat mode, neither can they be healed

### ISSUE THREAD

**Issue by Just-a-Unity-Dev** [space-wizards/space-station-14#27238]
Title

**Comment by Just-a-Unity-Dev** [comment]
Correction, no interactions (mindshields, cuffs, etc) work if you click on it because storage takes priority over interactions

**Comment by MjrLandWhale** [comment]
I know its your PR, but for general tracking I'm gonna mention: Caused by #23425

**Comment by AJCM-git** [comment]
This is no longer the case
