### ISSUE TITLE
If someone leaves the game for more than 3 minutes, they should have their body deleted

### ISSUE THREAD

**Issue by Erisfiregamer1** [space-wizards/space-station-14#2724]
When you leave a game of SS14, you get put in an AFK state. However, these bodies are super annoying to get rid of, without recycling.
I propose that all AFK or dead bodies rot after a 3-minute timeout, to make map cleanup easier.

**Comment by metalgearsloth** [comment]
In SS13 they go SSD which is kind of a thing.

> to make map cleanup easier.

How so? Do you mean in terms of performance or...?

**Comment by Erisfiregamer1** [comment]
performaance, and map travel. You dont want to smack into the face of an AFK guy in a gun chase, riiight?

**Comment by metalgearsloth** [comment]
Mobs don't have collision with other mobs anyway.

This is a feature from ss13 so this is probably a wontfix and also I doubt it'll be a performance issue as someone who profiles the game occasionally.

**Comment by Zumorica** [comment]
This shouldn't really be a thing imo. I can see it for sandbox mode and the like, but... *why*
