### ISSUE TITLE
gas tank ui header should use entity name

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#27242]
![image](https://github.com/space-wizards/space-station-14/assets/124214523/40c666f3-dc66-4d08-a06d-ddc334de75e8)

**Comment by Laneron** [comment]
Also, I would consider refactor this part of UI - since mostly all objects having this window it would be much easier for maintainability to emerge header logic into BaseWindow, or to introduce another abstract in between (HeaderBaseWindow for example) to handle all those cases in one place
