### ISSUE TITLE
You can FTL any grid in the game

### ISSUE THREAD

**Issue by WarMechanic** [space-wizards/space-station-14#27253]
## Description

I FTL'd the ATS to the station in a DeltaV round. Asked if it was allowed, got a response of no. 
**Reproduction**

Put some thrusters and a cargo shuttle console on the ATS, you're all set.

**Screenshots**

**Additional context**

FTL should have requirements, perhaps an FTL engine device or thruster/mass threshold.

**Comment by metalgearsloth** [comment]
There is a mass limit and FTL engines are planned but not implemented.
