### ISSUE TITLE
T e l e p o r t i n g  l o c k e r   s o f t l o c k .

### ISSUE THREAD

**Issue by Erisfiregamer1** [space-wizards/space-station-14#2725]
There is a gray locker below the research area. If you enter it, you get TELEPORTED somewhere else.
If the locker is locked, however, you got soft locked.
Can we make it so if someone is in a locked locker, they can break out?
Plus, they could open the locker on the way.
Seems logical someone inside a locker could force it open?

**Comment by Zumorica** [comment]
So *that's* where the cursed locker is, in saltern...

**Comment by Zumorica** [comment]
Also
> If the locker is locked, however, you got soft locked.

Intended. This cursed locker simply needs to be removed from the map, it should be an admin-only entity, really.

**Comment by exp111** [comment]
This is secret content
Delete this

**Comment by Erisfiregamer1** [comment]
n o
