### ISSUE TITLE
Slimes can cure their zombification by turning to Giras

### ISSUE THREAD

**Issue by Admiral-Obvious-001** [space-wizards/space-station-14#27261]
## Description

We noticed on Round #51813 where a slime was infected and turned into a zombie, but they turned into a Giras which seemed to remove the zombification. When they turned back, they turn into their zombifjed form.

**Reproduction**

Infect a slime person with the zombie virus and turn them. Once they're infected, select the transform option. The slime will be able to speak and move as normal.

**Additional context**

Zombies can attack the slime as a giras, and if they revert to their zombified person form, they will seem to go into crit as a result of the damage.

**Comment by Just-a-Unity-Dev** [comment]
Not intended at all, fixing in an upcoming PR

**Comment by slarticodefast** [comment]
Closing this since Geras were removed.
