### ISSUE TITLE
Radiation pulses need a shader

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#2726]
The green circle looks like dog poop (as the person who made it) and ideally it'd be a shader instead.

**Comment by Efruit** [comment]
[I wrote one](https://github.com/Efruit/SS14/tree/fancy-radiation-shader) and it looks nice [citation needed]. Unfortunately it's based off the singulo code, so multiple instances of it become completely broken, and it includes a wonderful black screen flicker when one spawns remotely near you.


https://user-images.githubusercontent.com/602406/143833341-df18e2ac-0e26-4eea-ae7a-2bd5a643ce06.mp4

**Comment by Efruit** [comment]
(Also there was a second version that's entirely the same, but uses a smooth gradient instead.)

https://user-images.githubusercontent.com/602406/143834173-5a5b286b-870b-4c8d-9baf-c9cdb372fb83.mp4

**Comment by Efruit** [comment]
Update: It's FoV-aware *and* supports multiple instances now!


https://user-images.githubusercontent.com/602406/143866733-446fff33-a806-4314-9083-db63de01f4f6.mp4
