### ISSUE TITLE
Shotguns get reloaded even if the do-after does not complete

### ISSUE THREAD

**Issue by Plykiya** [space-wizards/space-station-14#27279]
## Description

This allows someone to run and reload at the same time. Works even better if they click and spam to reload.

**Reproduction**

**Screenshots**

**Additional context**

**Comment by metalgearsloth** [comment]
When did shotguns get a do_after?

**Comment by Plykiya** [comment]
> When did shotguns get a do_after?

sorry, the act of inserting shells into a shotgun
