### ISSUE TITLE
Primed explosives freeze their countdown when placed in slime internal storage when swaped into geras form

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#27272]
## Description
If a explosive is primed, and placed into a slime internal storage, the countdown will freeze when swaped into geras form. Countdown will resume after transforming back.

**Reproduction**
1. Prime explosive
2. Place explosive in slime internal storage
3. Transform into geras 
4. Countdown will stop
5. Countdown will resume when transforming back into slimeperson

**Comment by deltanedas** [comment]
i assume it uses polymorph so that exposive gets sent to nullspace and paused, it would need to polymorph then swap container out of nullspace

**Comment by Tayrtahn** [comment]
Presumably related to #27250 as well

**Comment by JIPDawg** [comment]
Sort of fixed by #29731

I assume timers still stop when in (nullspace?) but I'm uncertain of any other consistent way of doing so.

**Comment by beck-thompson** [comment]
Closing because they have been removed!
