### ISSUE TITLE
Winter Clothing Bounty Doesn't Work

### ISSUE THREAD

**Issue by Admiral-Obvious-001** [space-wizards/space-station-14#27302]
## Description

The value scanner doesn't seem to recognize the contents of a crate with the winter clothing bounty stuck to it as a part of the bounty. 
**Reproduction**

Insert the entire contents of a winter drobe into a crate with the winter clothing bounty label stuck to it. The pricing gun will only show the base value of the contents.

**Comment by eoineoineoin** [comment]
Closing as seems to work now; probably was expectations fixed by https://github.com/space-wizards/space-station-14/pull/29779
