### ISSUE TITLE
Antag objectives are weird

### ISSUE THREAD

**Issue by Dutch-VanDerLinde** [space-wizards/space-station-14#27312]
## Description
People are getting tons of objectives and antag safe roles are getting antag

And too many objectives for the difficulty 

**Reproduction**
Become syndie 

![image](https://github.com/space-wizards/space-station-14/assets/45323883/7f0f3b94-0fbc-4ced-9f7a-b9749e4d743e)

![image](https://github.com/space-wizards/space-station-14/assets/45323883/c13a1233-be84-45a5-823e-8732033cdfdb)

Research assistant syndie and ensure fellow TRAITOR secoff objective 

**Additional context**

**Comment by LordEclipse** [comment]
"Hey, we're gonna need you to kill like half the station, good luck!"

**Comment by thebadman4662** [comment]
Looks like "Die a glorious death" is back on the menu boys.

**Comment by Dutch-VanDerLinde** [comment]
> 
> 
> > weird bug caused by the mega ultimate super antag refactor making them have 4x more objectives than usual
> 
> 
> 
> The bug is called i swapped two values and now the objective difficulty is like 4 times higher than usual
> 
> 

Do u know why antag safe roles are getting antag?

**Comment by deltanedas** [comment]
99% sure its because people that are opted out get added to fallbackList and thus get picked if theres not enough people opted in. this behaviour should be disabled by default for most gamerules
