### ISSUE TITLE
Cluster security has rubbers mapped

### ISSUE THREAD

**Issue by TheDoctor1977** [space-wizards/space-station-14#27328]
## Description
unless i am stupid (likely) i'm pretty sure rubbers were meant to be removed from everywhere

**Reproduction**
1. go to cluster's armory
2. look on the table where the lecter is stored
3. despair
alternatively
1. go to cluster's sec locker room
2. look on the table
3. despair

**Screenshots**
![20240425224653_1](https://github.com/space-wizards/space-station-14/assets/108845723/d0165546-5d5e-41d2-a4e8-6a39ce31a5b0)
![20240425225236_1](https://github.com/space-wizards/space-station-14/assets/108845723/026cb804-2717-4e19-9c07-0ec82ba49bf1)

**Comment by thebadman4662** [comment]
Completely going to ignore 3 rubber mags + drozd in sec locker room, huh? :trollface:

**Comment by TheDoctor1977** [comment]
> Completely going to ignore 3 rubber mags + drozd in sec locker room, huh? :trollface:

i may be stupid

**Comment by Boaz1111** [comment]
Handled, close it
