### ISSUE TITLE
Unable to see Antags Via Admin Menus

### ISSUE THREAD

**Issue by GalaxyCad** [space-wizards/space-station-14#27323]
## Description
Admins are once more unable to see antags through the Menus, Unsure whats going on! When we open the Ahelp menu we are unable to see antags by the Knife icon by their names and when someone explodes something we also cannot see it in the admin logs chat. We have to manually check by using Coding/commands. 

**Reproduction**

**Screenshots**

**Additional context**

**Comment by EmoGarbage404** [comment]
is this after the publish like an hour ago

**Comment by GalaxyCad** [comment]
yes, we just checked. It has not been fixed
