### ISSUE TITLE
Books not being books

### ISSUE THREAD

**Issue by GalaxyCad** [space-wizards/space-station-14#27327]
## Description
So uh.... Books are loading words, it is instead loading the codes for the words. We have seen it on a few books now. Screenshot to show what it does. 

**Reproduction**

**Screenshots**
![image_2024-04-25_193338521](https://github.com/space-wizards/space-station-14/assets/168132390/4280545f-7fed-4f28-b013-e96767b24a0f)

**Additional context**

**Comment by K-Dynamic** [comment]
Something wrong with the NT printers or their (not actual) AI ghostwriters :trollface:
