### ISSUE TITLE
Belt slot webbing needs to be resprited 

### ISSUE THREAD

**Issue by Flareguy** [space-wizards/space-station-14#27334]
## Description
This all includes [security webbing](https://github.com/space-wizards/space-station-14/tree/master/Resources/Textures/Clothing/Belt/securitywebbing.rsi), [military webbing](https://github.com/space-wizards/space-station-14/tree/master/Resources/Textures/Clothing/Belt/militarywebbing.rsi), [medical military webbing](https://github.com/space-wizards/space-station-14/tree/master/Resources/Textures/Clothing/Belt/militarywebbingmed.rsi), and [merc webbing.](https://github.com/space-wizards/space-station-14/tree/master/Resources/Textures/Clothing/Belt/mercwebbing.rsi)

Unlike any other belt item in the game, these items completely obscure the chest, making armor often completely impossible to actually identifiy. This is not good, since a lot of armor is very specialized - you could easily magdump a guy wearing bulletproof armor and be none the wiser, whereas if it did not cover the chest before, you would have been able to kill him.

Something like the salvage webbing is a good frame of reference for how this should look, if you are not sure what to do.

**Comment by Dutch-VanDerLinde** [comment]
this isn't completed as only the security webbing is resprited

**Comment by DieselMohawk** [comment]
I'm working on it, it'll be slow though
