### ISSUE TITLE
The github builds should export the build as an Artifact

### ISSUE THREAD

**Issue by Erisfiregamer1** [space-wizards/space-station-14#2733]
See Anuken/mindustry for what I mean.
The GitHub builds should upload the final product to GitHub, allowing for MUCH easier tests of things without manually compiling. Just make the PR and grab the client it exports.
I guess this could count as a Quality Of Life thing? idk

**Comment by metalgearsloth** [comment]
It already gets uploaded to jenkins and is usable by the watchdog https://builds.spacestation14.io/jenkins/job/SS14%20Content/

**Comment by PJB3005** [comment]
> The GitHub builds should upload the final product to GitHub, allowing for MUCH easier tests of things without manually compiling. Just make the PR and grab the client it exports.

Just check the code out locally with git if you want this. It'll be 10 times easier.
