### ISSUE TITLE
Too many damn syndies!

### ISSUE THREAD

**Issue by Plykiya** [space-wizards/space-station-14#27340]
## Description

Ever since the antag refactor, I've had about four shifts in a row on Lizard where there were 12 syndicates total. It used to only be a max of maybe like, nine? but closer to eight or seven on average.

**Reproduction**

**Screenshots**

**Additional context**

**Comment by Plykiya** [comment]
![image](https://github.com/space-wizards/space-station-14/assets/58439124/083ec9cb-15fe-4de6-be76-e3110da7c2cb)

this is getting a little silly

**Comment by Golinth** [comment]
![image](https://github.com/space-wizards/space-station-14/assets/22528949/a72fda87-6a55-4823-aab4-900f63fb2466)
one last fuck you from this issue

**Comment by EmoGarbage404** [comment]
The logic is still broken
