### ISSUE TITLE
Sec webbing whitelist

### ISSUE THREAD

**Issue by thebadman4662** [space-wizards/space-station-14#27363]
I guess some things were not added to https://github.com/space-wizards/space-station-14/pull/27303 as webbing says about being able to store all combat essentials yet you can't put something like gauze, combat medicine pill canisters or emergency injectiors in there which seem rather essential in middle of combat to like not die? 

Luckily tourniquets did make it to the whitelist but they are very limited for sec.

**Comment by FungiFellow** [comment]
PR-Maker-Here, This is a non issue.

It cloned the SecBelt. I did this as the webbing was getting powergamed because of no whitelist, if you want a belt slot item that can carry meds get a Med-Belt, Merc or Syndie webbing.

**Comment by thebadman4662** [comment]
Yeah, update would be better if its meant to be cosmetic now. 

Merc webbing is gamer loot that sprobably going to get erased from map spawns, syndicate webbing gets you banned as sec/command so they are not exactly solutions for that.
