### ISSUE TITLE
Randomized books no longer pull text from the localization things

### ISSUE THREAD

**Issue by Plykiya** [space-wizards/space-station-14#27378]
## Description

![image](https://github.com/space-wizards/space-station-14/assets/58439124/326b9b0b-462e-4ac2-9624-df8694d0ec49)

**Reproduction**

**Screenshots**

**Additional context**

**Comment by metalgearsloth** [comment]
I took a look, the problem is books do this bad thing of duck typing strings and prototype IDs so no wonder it broke so easily.

It should just use a new data structure that actually types it properly so it doesn't break in future.

**Comment by Plykiya** [comment]
#27390
