### ISSUE TITLE
Core Station, Arrivals Atmos, Mapping Issue

### ISSUE THREAD

**Issue by Willzile1** [space-wizards/space-station-14#27371]
## Description
Core station arrivals has scrubbers and vents swapped.

**Reproduction**
Load Core station, check arrivals

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/69917862/212971d9-1f59-4433-9a72-1dfe2cc564ce)
![image](https://github.com/space-wizards/space-station-14/assets/69917862/3a7533b4-92be-4d82-a6f7-610b447345bd)
![image](https://github.com/space-wizards/space-station-14/assets/69917862/3895054d-6f99-4b8a-a10c-82ec9be99a5a)

The vents in question, after we fixed them. The color still shows how they were improperly installed.

**Additional context**
This was on Salamander so I don't think a greytide messed with it.

**Comment by UbaserB** [comment]
gotcha, ill check it out. based on the colouring though, it really does look like it was switched.

**Comment by UbaserB** [comment]
![image](https://github.com/space-wizards/space-station-14/assets/134914314/9720fd74-a88e-4a37-87d5-91fb28bbf9b2)

They seem perfectly fine, someone must have switched them in-game

**Comment by deltanedas** [comment]
the vents being red means theyre on the waste network, and vice versa

**Comment by UbaserB** [comment]
pfff nevermind yeah i mis-saw
