### ISSUE TITLE
Bags wont open and after reconnect naked and game completely broken

### ISSUE THREAD

**Issue by SHOTbyGUN** [space-wizards/space-station-14#27372]
## Description
When the bug is triggered:
- Bags wont open.
- Inventory wont open.
- Lag becomes severe, from 1 to 15 second delay after movement inputs.

After reconnect
- Naked
- Can't see own items at all
- Inventory items might be visible and following character, picking them up is possible but they are still not visible on hands or when dropped to ground.

**Reproduction**
Go to an area which has desynced / despawned entity

Round #52118 - I was janitor Baldric Dean
https://moon.spacestation14.com/replays/leviathan/2024/04/26/leviathan-2024_04_26-16_42-round_52118.zip
Problem originated for me at science artifact area below I have selected few lines from log that might be the cause:

```
[ERRO] state: Server entity threw in Start: ent=alien artifact (78077/n1203027, SimpleXenoArtifactItem)
[ERRO] entity: Caught exception while trying to detach parent of entity 'alien artifact (78077/n1203027, SimpleXenoArtifactItem)' to null.
[ERRO] system.physics: Found deleted entity 78077/n0D on map!
KeyNotFoundException: The given key 'default' was not present in the dictionary.
```
The given key 'default' was not present -- error repeats thousands of times

I was unable to reproduce this again with replay since I ran out of RAM processing the replay.

**Screenshots**
Bug reported on discord on many threads by many people:
https://discord.com/channels/310555209753690112/1233579040351195157
https://discord.com/channels/310555209753690112/1233557978326634557
https://discord.com/channels/310555209753690112/1233353295263699015 
https://discord.com/channels/310555209753690112/1233416806870548480
https://discord.com/channels/310555209753690112/1233418151299911773
https://discord.com/channels/310555209753690112/1233531306743300126

**Additional context**
After bug is triggered game is unplayable.

Bug triggered to me today on three consecutive rounds on Leviathan. Game worked flawlessly 24 hours ago.

**Workaround**
Leave the area where bug was triggered and reconnect few times until everything loads up properly.
Going to that area again will trigger the bug.

**Comment by Plykiya** [comment]
Someone fixed this issue by dragging somebody.... but like, that gives no clues to the actual issue

**Comment by Hanzdegloker** [comment]
had this happen today, even my UI started to delete itself, had an admin gib me because I couldn't even do anythin

side note all of my items from within my storage implant were just, floating next to me and following me.

**Comment by metalgearsloth** [comment]
Probably fixed in engine pr, even 1 log would be nice.

**Comment by SHOTbyGUN** [comment]
Might be another trigger

[ERRO] system.joint: While adding joint pull-joint-2866028 to entity piano (10704/n2866028, PianoInstrument), the joint already existed for the connected entity Tim Kilgore (48318/n3001901, MobHuman).
[ERRO] runtime: Caught exception in "GameLoop Tick"
System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)

**Comment by metalgearsloth** [comment]
That's completely unrelated

**Comment by SHOTbyGUN** [comment]
Possibly fixed for next server restart: https://github.com/space-wizards/space-station-14/pull/27401
