### ISSUE TITLE
Ambient sounds

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#2738]
Discussed on discord before: https://discord.com/channels/310555209753690112/310555209753690112/747093264045309962

With that being said there's 2 parts.
1. Find free licence sounds to put on objects that loops (LoopingSoundComponent should be able to do it) for a bunch of things.
2. Add a client system that can play ambient sounds (might need to be on RobustToolbox?). IIRC ss13 does it via checking the current tile. Though with that said based on the discussion it won't be a 1-1 port of the existing sounds, more just to have stuff like ship groans randomly play contextually.

**Comment by PaulRitter** [comment]
a

**Comment by mirrorcult** [comment]
this is done though

**Comment by SweptWasTaken** [comment]
> 
> 
> this is done though

This isn't completely done. We still need the randomly played ambience system that I think should be client side mostly since it would be unique for each player?

I think i'll make a separate ambience issue though.

**Comment by mirrorcult** [comment]
ambient music sh ould be something like this https://discord.com/channels/310555209753690112/310555209753690112/885952153649315860
