### ISSUE TITLE
Command is open for antag selection from Zombie mid round event.

### ISSUE THREAD

**Issue by PolarTundra** [space-wizards/space-station-14#27382]
## Description
Head of Security and presumably other members of Command (and maybe Security) can currently become ii in a mid round zombie event.

**Reproduction**
Mid round zombie event with Command.

**Comment by Dutch-VanDerLinde** [comment]
this is false, people who are infected with zombie infection just get the "turn into zombie action" like an II even if they aren't an inital infected
