### ISSUE TITLE
Displacement map bug

### ISSUE THREAD

**Issue by TheShuEd** [space-wizards/space-station-14#27407]
## Description
- [x] Displacement map layers is visible when dragging, 
- [ ] Sprite border under cursor selecting also select insivible displacement layers

**Reproduction**
1) Spawn Vox
2) equip captain jumpsuit
3) try put Vox in trashbin

**Screenshots**

https://github.com/space-wizards/space-station-14/assets/96445749/cad67a2c-6212-4996-8123-acb396fb6965

**Comment by metalgearsloth** [comment]
Looks fixed on master.
