### ISSUE TITLE
NUKIES CAN ROLL THIEF

### ISSUE THREAD

**Issue by Dutch-VanDerLinde** [space-wizards/space-station-14#27402]
![image](https://github.com/space-wizards/space-station-14/assets/45323883/4afa802b-b09f-457a-8bcd-7076726229f2)

**Comment by deltanedas** [comment]
pacifist run :trollface:

**Comment by EmoGarbage404** [comment]
Need to configure nukeops role to either be an exclusive antag or change the theif selection to check for existing antag  status

**Comment by mirrorcult** [comment]
based

**Comment by deltanedas** [comment]
why would nukeops role *not* be exclusive

**Comment by Dutch-VanDerLinde** [comment]
double antag shouldnt be possible in the first place imo because you're taking two antag slots instead of letting someone else be antag

**Comment by Golinth** [comment]
thief should be the one exception IMO. Syndie thief and headrev thief are interesting combinations that should be allowed to exist
