### ISSUE TITLE
nuclear operatives roundend text doesn't appear

### ISSUE THREAD

**Issue by Dutch-VanDerLinde** [space-wizards/space-station-14#27403]
when the round ends, the text saying who the operatives were does not appear

I believe this also applies to inital infected too

**Comment by Graded5** [comment]
Also if I remember correctly, it also doesnt show head revs.

**Comment by Dutch-VanDerLinde** [comment]
> Also if I remember correctly, it also doesnt show head revs.

yeah all the team antagonists or ones that don't have traditional objectives like syndies
