### ISSUE TITLE
Set outfit is broken

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#27409]
## Description

Only shows clothing not sets
**Reproduction**

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/43253663/e3d9e377-979d-4dad-b4c5-a5d41f85fa38)

**Additional context**

**Comment by lzk228** [comment]
dupe #27276

**Comment by beck-thompson** [comment]
thanks for the report and yeah its a duplicate!
