### ISSUE TITLE
Non-humanoids can be cryod

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#27410]
## Description

This is rather strange, i think this shouldn't be possible
**Reproduction**

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/43253663/f8951b52-46c5-49aa-bea0-45976cdbfa86)

**Additional context**

**Comment by deltanedas** [comment]
it shouldnt make announcement but i think its fine for pets like remi when they ghost to be cryod

**Comment by osjarw** [comment]
![20240428_01h36m26s_grim](https://github.com/space-wizards/space-station-14/assets/62134478/ab24e03c-76e6-442c-81bc-df043dd6fc24)

**Comment by lzk228** [comment]
is it possible to make a whitelist for cryo?
