### ISSUE TITLE
Can't state laws

### ISSUE THREAD

**Issue by Vermidia** [space-wizards/space-station-14#27412]
## Description

Not sure why, but when trying to hover over the buttons for stating laws (I was ioned with a law 0 and 4 other laws) I could almost never press any of the buttons to say the laws. It worked fine for the default laws.

**Reproduction**

Be a normal borg
Get Ionned
Try to state laws  but be unable to press the buttons

**Screenshots**

**Additional context**

Round #52255 if that helps

**Comment by ulramite** [comment]
I have had the same issue, Round #52286. My laws were not tampered with in any ways. Relogging helped a couple times, but not always. The buttons would appear highlighted while moving the mouse, but would un-highlight when I stopped moving the mouse.

**Comment by thebadman4662** [comment]
Similiar issue, no need to even get ioned. Latejoined from cryobeds.

**Comment by UbaserB** [comment]
I have also replicated it.

**Comment by arimah** [comment]
I encountered this when playing a borg, too. I eventually discovered that turning off my light drastically reduced the UI flicker rate, allowing me to state laws again.

**Comment by Synthestra** [comment]
Can still replicate

**Comment by Synthestra** [comment]
However unlike OP this happens with normal laws and occurs around 15~ after being a borg

**Comment by Synthestra** [comment]
Possible this could be reopened?

**Comment by thebadman4662** [comment]
True, it was never fixed AFAIK.
