### ISSUE TITLE
antag latejoins not respecting max player count

### ISSUE THREAD

**Issue by Plykiya** [space-wizards/space-station-14#27423]
## Description

![image](https://github.com/space-wizards/space-station-14/assets/58439124/3e684547-05a2-4c4c-8d90-5b2d400eb9c2)
even with the maxPlayers for traitors set to 12, it's still possible to exceed the number of antags by latejoining

**Reproduction**

**Screenshots**

**Additional context**

**Comment by Brandon-Huu** [comment]
Does this mean at least 150 players joined throughout the round?
