### ISSUE TITLE
antag selection is selecting people to be nukies even with it unselected and locked

### ISSUE THREAD

**Issue by Plykiya** [space-wizards/space-station-14#27425]
## Description

https://discord.com/channels/310555209753690112/1233970230749954068
person reported to have gotten both operative and commander
![image](https://github.com/space-wizards/space-station-14/assets/58439124/ecd950b4-9e32-4aa7-9750-009830b3db30)

**Reproduction**

**Screenshots**

**Additional context**

**Comment by Zealith-Gamer** [comment]
Can confirm, I have this happening too. I queued as a Medical intern and was thrown into Nuke medic. I also had my sci profile (that has no antags selected) get syndi agent a few minutes AFTER we started. (the round started, it said I was a sci and nothing else, i completed 2 borgs then i got the sound and antag role)

**Comment by deltanedas** [comment]
why is fallback list even a thing, when would you want to select people that both havent opted or dont meet the requirements for an antag

**Comment by Plykiya** [comment]
this continues to be an issue with people being selected for the antag role when there are plenty of other people with it enabled

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
This may now include other antags such as traitors, unsure if its the same issue but i have one confirmed case of this happening so i thought it was worth the comment

**Comment by TheDoctor1977** [comment]
> This may now include other antags such as traitors, unsure if its the same issue but i have one confirmed case of this happening so i thought it was worth the comment

I can confirm, just in the past week I've rolled traitor three times when I had it off.

**Comment by Zealith-Gamer** [comment]
Just to make sure, This does **NOT** include sleeper agent. This is Round start/Round join.

**Comment by engineer-pearl** [comment]
Now imagine being a new player in that position (I do not have to)! A player who doesn't know how jetpacks, maps, helmets, or guns work probably should not be a Nukie. 

Btw all those things are describing me as a Nukie this weekend.
