### ISSUE TITLE
Ghost cannot read papers

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#27421]
Earlier it was possible via verb, now there is no verb for ghosts.

**Comment by slarticodefast** [comment]
I did some debugging and found the code piece that is causing this.
Here is some kind of stack trace:

We start in ActivateableUISystem.cs
![grafik](https://github.com/space-wizards/space-station-14/assets/161409025/78287bbc-550f-4442-89b3-8e94a33014ac)
which leads to SharedUserInterfaceSystem.cs
![grafik](https://github.com/space-wizards/space-station-14/assets/161409025/b7c3d52e-1fa9-45ba-9315-65f4436f7355)

![grafik](https://github.com/space-wizards/space-station-14/assets/161409025/5751dfd6-b62c-4975-bcbc-d4cddee4c731)

BoundUserInterfaceMessageAttempt leads to SharedInteractionSystem.cs

![grafik](https://github.com/space-wizards/space-station-14/assets/161409025/c296ec80-547e-4e3c-8306-2ebf1dfa388e)

which calls CanInteract(...)
![grafik](https://github.com/space-wizards/space-station-14/assets/161409025/03ff059f-be4a-4c7f-9887-a561a3259c1d)

This function returns true for Mobs or Aghosts, but false for ghosts.

This is already checked earlier in ActivateableUISystem.cs:

![grafik](https://github.com/space-wizards/space-station-14/assets/161409025/00805380-73a7-48d0-9482-f6626bf376f2)

Simply removing the second check would probably break more stuff and I have no idea how to properly fix this, but I hope this will safe someone else some time.

**Comment by slarticodefast** [comment]
Ok, I came up with something that works but looks super hacky in my opinion. Maybe someone else finds a better solution with this as a starting point:
https://github.com/slarticodefast/space-station-14/commit/e5b750a0b5bb80ae51305cfd3f674263a9b5fd7b

**Comment by ShadowCommander** [comment]
The code is currently hard to understand, so it's a good time to write out the cases in which a player can interact with an ActivateableUI and what the end result should be.
```
If not CanInteract
    Deny interaction
If not in the same container
    Deny interaction
If IsAdmin
    Allow interaction always
If not in range unobstructed
    Deny interaction

If ActivatableUIComponent does not exist
    This was not triggered by an activatable UI so there should be neither deny or allow.
    Return exit early
If user is a ghost and the ui allows ghosts to view
    Allow interaction
If UI requires hands and user does not have hands
    Deny interaction
```
---

And sorting it by priority
```
If ActivatableUIComponent does not exist
    This was not triggered by an activatable UI so there should be neither deny or allow.
    Return exit early

If IsAdmin
    Return Allow interaction always
If user is a ghost and the ui allows ghosts to view
    Return Allow interaction

If not CanInteract
    Deny interaction
// Slighly higher because the container and in range check are slightly more expensive
If UI requires hands and user does not have hands
    Deny interaction
If not in the same container
    Deny interaction
If not in range unobstructed
    Deny interaction
```
