### ISSUE TITLE
Borgs Cannot See Laws Properly

### ISSUE THREAD

**Issue by Kezu02** [space-wizards/space-station-14#27439]
## Description

Had a few reports of players unable to open their laws when pressing the hotkey. One said they were able to make it show but only while their maintenance/module screen was open.

**Comment by Kayek14** [comment]
Can confirm. Apparently you can only open your law screen if you have a module selected.

**Comment by VasilisThePikachu** [comment]
Experienced this myself just now. Seems like you need a module selected in order to open the laws page

**Comment by Errant-4** [comment]
As noted on 28582, this also impacts opening computer UIs like the Crew Monitor or wall maps
