### ISSUE TITLE
Quantam spin inverters can apparently noclip people

### ISSUE THREAD

**Issue by Just-a-Unity-Dev** [space-wizards/space-station-14#27437]
# Description
[Uploading Video_2024-04-28_04-23-28.mp4…](https://github.com/space-wizards/space-station-14/assets/67359748/380c9974-e718-49d1-a058-7045a53eb4db)

Reported by crasg (705880810070343741) on Discord

## Reproduction
Looking at the video, it seems like:
1. Get two QSIs
2. Put one QSI in a duffelbag and the other outside
3. Put the duffelbag inside of someone, and put that someone in cryo
4. Activate the QSI you have
5. bam, noclip

**Comment by Just-a-Unity-Dev** [comment]
github are you actually messing with me

**Comment by Just-a-Unity-Dev** [comment]
https://github.com/space-wizards/space-station-14/assets/67359748/380c9974-e718-49d1-a058-7045a53eb4db

Reported by crasg (705880810070343741) on discord

**Comment by K-Dynamic** [comment]
wait you're not even in the discord right now :trollface: 

I think it's a duplicate of https://github.com/space-wizards/space-station-14/issues/27432, given the person who posted the vid described it as follows:
![image](https://github.com/space-wizards/space-station-14/assets/20566341/89c2f242-a220-4ccd-aced-21cf030088c4)

**Comment by Just-a-Unity-Dev** [comment]
https://github.com/space-wizards/space-station-14/assets/67359748/8fc1c442-72af-4cc1-b22d-4fdf93fa4830

**Comment by MissKay1994** [comment]
Tagging for tracking, #26364

**Comment by Scruq445** [comment]
Also I should tell you guys that bringing a person out of the cryopod doesn't de-noclip you

**Comment by Just-a-Unity-Dev** [comment]
Fixed in #26364
