### ISSUE TITLE
Chem dupe

### ISSUE THREAD

**Issue by CoffeePoweredPHD** [space-wizards/space-station-14#27440]
## Description
You can duplicate literally any chemical using only a toilet

**Reproduction**
Get a toilet, make sure its filled with water, get a container with any liquid you want, right click and empty it into the toilet.
It will say its full, pour it out onto the ground, but also keep it in the container. Then just syringe it up 

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/122668708/9fad08c5-3275-4ae8-b003-e0261d4749db)
pictured: a flood of pyrazine created from a single unit

**Additional context**
I swear we did not abuse this.... except maybe for a bit of carpetium... sorry

**Comment by beck-thompson** [comment]
Replicated. This ONLY works with the empty toilet the dirty toilet is broken
