### ISSUE TITLE
Zombie containers can't be looted.

### ISSUE THREAD

**Issue by thebadman4662** [space-wizards/space-station-14#27451]
## Description
I have latejoined as sec and there were plenty of zombies, I was unable to loot their backpacks or belths though. When opened they would stay closed, when I walked away, they would open but it would be impossible to interact with items inside.

**Reproduction**
1. Kill zombified urist.
2. Strip them of gear.
3. Try to take out that ambuzol+ from the chemist satchel.

**Comment by thebadman4662** [comment]
Had it happen on normal players as a syndie too, I was stripping crit person and after they said last words I was unable to interack with backpack that now was on floor.

**Comment by Dutch-VanDerLinde** [comment]
seems to be a prediction issue, i've replicated this
