### ISSUE TITLE
Unable to place construction ghosts

### ISSUE THREAD

**Issue by Jorc224** [space-wizards/space-station-14#27457]
## Description
On round #52349, I was unable to place any construction ghosts.

**Reproduction**
1. Open crafting menu
2. Attempt to place down ghost
3. No ghost is placed

**Screenshots**
![20240428205114_1](https://github.com/space-wizards/space-station-14/assets/159604101/b69c12b0-eec8-4eb6-9ac4-d417a8b6622a)
![20240428205118_1](https://github.com/space-wizards/space-station-14/assets/159604101/f91c8158-f355-40d4-b271-4c150eb73aac)

**Additional context**
I first noticed it when trying to build windoors, but on trying to place any other construction ghosts it did not allow for placement. I attempted to reconnect. I toggled eraser mode on and off. It seems to be a lasting issue as it continued into the next round.

**Comment by osjarw** [comment]
Did you try using the Clear All button?
I've had a similar issue in the past, and pressing Clear All had fixed it.

**Comment by Jorc224** [comment]
> Did you try using the Clear All button? I've had a similar issue in the past, and pressing Clear All had fixed it.

I did try that a few times

**Comment by Jorc224** [comment]
Resetting my keybindings fixed the issue

**Comment by Jorc224** [comment]
Entirely possible I unbound this key
![image_2024-04-28_210602577](https://github.com/space-wizards/space-station-14/assets/159604101/912e0426-248e-4f03-9380-e5ca6fbe4771)
