### ISSUE TITLE
Neutral mobs cannot be pulled -- they escape pulling when unangered.

### ISSUE THREAD

**Issue by IProduceWidgets** [space-wizards/space-station-14#27460]
## Description

Even when not angry, neutral mobs refuse to be pulled.

**Reproduction**

Try to pull Renault, even as aghost, the little bastard runs away.

**Screenshots**

**Additional context**

Not sure if because of #26868  or just happenstance.

**Comment by VigersRay** [comment]
Renault not want to be pulling)

**Comment by luizwritescode** [comment]
If Willow the Roo is downed while angry, and then revived, it still keeps breaking away from pulling. Usually just results in medbay having a few idling pets inside with no way of dragging them out.

**Comment by UbaserB** [comment]
Goats and iirc cows are the same too

**Comment by IProduceWidgets** [comment]
For some reason the pulling TryStopPull(...) call triggers the AttemptStopPullingEvent for both the ai and the player, and when it happens on the player it succeeds even through handcuffs. without knowing why it causes the second trigger I dunno how to fix it.

**Comment by IProduceWidgets** [comment]
I did the thing I said was gross. Theyll still escape when unangered however unless handcuffed & they must have hands, or otherwise unable to interact with themselves.

**Comment by osjarw** [comment]
#30066
Here's another PR trying to fix this issue, but this one just makes the mobs/NPCs unbuckle/unpull only when angered.

**Comment by IProduceWidgets** [comment]
> #30066 Here's another PR trying to fix this issue, but this one just makes the mobs/NPCs unbuckle/unpull only when angered.

mfw you dont link your bug fixes

**Comment by osjarw** [comment]
> mfw you dont link your bug fixes. 

For the handcuff issue, my PR isn't really solving it.
And I noticed this issue just today.

They mostly work together, with there being a bit of jank in the NPC/planner logic, causing situations where the NPC thinks it can unbuckle itself, and then tries it and fails ad infinitum. 
I guess I could go and fix it at some point, I don't believe it's that big of a problem currently.

**Comment by IProduceWidgets** [comment]
> They mostly work together, with there being a bit of jank in the NPC/planner logic, causing situations where the NPC thinks it can unbuckle itself, and then tries it and fails ad infinitum. I guess I could go and fix it at some point, I don't believe it's that big of a problem currently.

Yeah I considered this, but they also can't do anything else useful while cuffed, so I didn't see any big downside? Maybe its worth the perf gain though? idk.
