### ISSUE TITLE
Construction system does not prevent overlapping objects

### ISSUE THREAD

**Issue by 20kdc** [space-wizards/space-station-14#2747]
![image](https://user-images.githubusercontent.com/22304167/102290931-e43fbc00-3f39-11eb-9feb-be12eb8e0850.png)

How to reproduce:
1. Place a girder construction ghost.
2. Complete that girder.
3. Place another girder construction ghost.
4. Complete *that* girder. Keep in mind you can use the right-click menu to ensure you pick the ghost.
5. Turn both girders into walls.

Does not affect #2736 directly but is arguably one reason (the other being: I'm lazy) that I ended up having it prevent AME part overlap via it's own methods rather than by transitioning the thing to construction system. That PR is only mentioned so metalgearsloth knows I've written an issue about this.

**Comment by Zumorica** [comment]
The construction system *does* prevent this, the issue is that most recipes weren't actually making use of the feature.
