### ISSUE TITLE
Removing PermanentBlindnessComponent doesnt actually remove the blindness

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#27499]
https://github.com/space-wizards/space-station-14/assets/124214523/f510d134-231b-4f99-b581-5845e0c2ee67

**Comment by slarticodefast** [comment]
If you compare [DrunkSystem.cs](https://github.com/space-wizards/space-station-14/blob/master/Content.Client/Drunk/DrunkSystem.cs) and [PermanentBlindnessSystem.cs](https://github.com/space-wizards/space-station-14/blob/master/Content.Shared/Traits/Assorted/PermanentBlindnessSystem.cs), you see that the latter does not subscribe to OnPlayerAttached and OnPlayerDetached. Maybe that is the reason?

**Comment by IProduceWidgets** [comment]
iirc BlindnessComponent and PermanentBlindnessComponent are different, and the latter just ensures the former.

**Comment by lzk228** [comment]
closing because https://github.com/space-wizards/space-station-14/issues/33146 has more info
