### ISSUE TITLE
Borgs are taking damage walking on Glass Shards

### ISSUE THREAD

**Issue by FungiFellow** [space-wizards/space-station-14#27492]
Description

#26764 Seems to have made them take damage but not slip. Compared to not doing either before
**Reproduction**

1. Be entity with `StepTriggerImmune`
2. Walk on glass
3. Observe your damage

**Comment by keronshb** [comment]
They probably shouldn't be StepTriggerImmune either. 

Should they slip or get damaged by glass? No. 
Get effected by traps or runes? Yes.

**Comment by FungiFellow** [comment]
`- ShoesRequiredStepTriggerImmune`
Borgs should probably get switched to this one?

And `StepTriggerImmune` needs some touching up

**Comment by Plykiya** [comment]
ShoesRequiredStepTriggerImmune doesn't exist anymore, ClothingRequiredStepTriggerImmune is only intended for things that wear clothing, and StepTriggerImmune uh... should theoretically work since it uses basically the same check as the other one

**Comment by FungiFellow** [comment]
It might be fixed by giving both ``ClothingRequiredStepTriggerImmune` and `StepTriggerImmune` 

Heres a snippet of glass, I think it leaves StepTriggerImmune out
```
 - type: StepTrigger
    intersectRatio: 0.2
  - type: ClothingRequiredStepTrigger
  - type: Slippery
```

**Comment by FungiFellow** [comment]
`StepTrigger` is used for mines and that jazz while `ClothingRequiredStepTriggerImmune` is for glass. I am gonna just go add `ClothingRequiredStepTriggerImmune` to attempt to fix this
