### ISSUE TITLE
S.yndicate C.ode W.ords

### ISSUE THREAD

**Issue by ElPidor** [space-wizards/space-station-14#27502]
**Lee problem** 
It's kind of hard to find syndies because some of them don't respond properly. 
So code verbs that would be highlighted by colors like red or blue would make it easier to see in chat, instead of scrolling through it all to find a fellow agent trying to find a brother. 
Also, just seeing a syndie who only says a word without a second thought, and others saying the same thing, is pretty suspicious.

**Le solution** 
Highlight code verbs in chat to make it easier for new players to find a partner syndi. Include code responses with code verbs to make it less obvious to find a syndie.

**In two words**
 Code verbs must be highlighted 
 Agents must have code responses

**Comment by beck-thompson** [comment]
fixed with codeword highlighting!

**Comment by ArtisticRoomba** [comment]
The second half of this issue - codeword responses - is still relevant and extremely needed. This issue should either be reopened or split into a second issue.

**Comment by beck-thompson** [comment]
> The second half of this issue - codeword responses - is still relevant and extremely needed. This issue should either be reopened or split into a second issue.

Really? At least where I play the agents have zero issue finding each other. The response would be cool, but from what I'm seeing, not important for collaboration. If you think its important just open up another issue!
