### ISSUE TITLE
You can obtain barozine through botany mutation

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#27503]
## Description

Reported by erisws on discord, supposedly you can obtain barozine through RNG plant mutation. This is not intended as barozine should not be obtainable last i checked with maintainers, and should be as easy as changing one line.

![IMG_4418](https://github.com/space-wizards/space-station-14/assets/134914314/de04feb5-7cba-449e-b069-b67a0db72515)

**Comment by lzk228** [comment]
why is barozine shouldnt be obtainable? can you please send link for the discussion

**Comment by UbaserB** [comment]
updated description

**Comment by MACMAN2003** [comment]
why shouldn't barozine be obtainable?

**Comment by deltanedas** [comment]
space immunity juice aka bruizine and internals
