### ISSUE TITLE
Dwarf alcohol healing seems to stop working at times

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#27516]
## Description
I was testing how much Dwarves heal when consuming alcohol and noticed that they eventually stopped healing. Not sure what caused it, but Im assuming something broke since the healing somehow stoped working after i passed around 20 total damage.

**Reproduction**
Put alcohol in dwarf
Damage dwarf with blunt, slash, and heat
Get total damage to around 25
They should stop healing

**Screenshots**
the dwarf stopped healing even with alcohol in their system.
![image](https://github.com/space-wizards/space-station-14/assets/106507028/10d11bcb-f96b-44db-8f97-9a7ca91a5e5a)

**Comment by thebadman4662** [comment]
20 damage is the cutoff for brute and heat passive regens, sounds like dwarf alcohol healing was not working in first place for you.

**Comment by Tayrtahn** [comment]
Additionally, it looks like dwarven alcohol healing only works on Brute damage types.
![Screenshot_20240430-110538.png](https://github.com/space-wizards/space-station-14/assets/85356/5ebe8a28-ed3a-4dac-8907-d9ca18c944cc)

If you were seeing burn damage getting healed too, that was definitely the passive regen and not dwarf-specific.

**Comment by Kayek14** [comment]
You are right, after some testing it seems to be healing brute damage at 15 units of ethanol. I was under the assumption it was 15 units of any alcohol. Ill be closing this issue as it was made in error.
