### ISSUE TITLE
Detective office has the wrong crew records computer in their office

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#27517]
## Description
On box station, the detective office has Station reords computer, instead of the criminal records computer

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/106507028/d4e4ddbd-414c-440e-9e17-9cba4ec40f48)

**Additional context**
Other stations has the criminal records computer. Having the wrong records computer makes it impossible for the detetive to manually enter their own investigation info while in their office.

**Comment by deltanedas** [comment]
should have both not just 1

**Comment by Kayek14** [comment]
This issue was resolved.
