### ISSUE TITLE
Getting ate by singulo can nullspace you and prevent reconnecting.

### ISSUE THREAD

**Issue by ProfanedBane** [space-wizards/space-station-14#2754]
Got eaten, no ghost and no map.
Trying to reconnect got stuck on syncing gamestate.

**Comment by 20kdc** [comment]
This might be actually universal to "entity deletion" deaths.

**Comment by 20kdc** [comment]
Specifically: I get the same issues when deleted by a recycler, including syncing gamestate issues - so this is has the same underlying cause between this and #2696

**Comment by Zumorica** [comment]
Fixed by f8d4d4b8d7795f7b8e377c4fcb5fe2a8bd121b23
