### ISSUE TITLE
immovable rod announcement should be announced after the rod strikes

### ISSUE THREAD

**Issue by Dutch-VanDerLinde** [space-wizards/space-station-14#27544]
centcom seeing the future is really weird

this is the announcement text btw
![image](https://github.com/space-wizards/space-station-14/assets/45323883/45688c8c-c314-47f4-a505-705497657579)

**Comment by maylokana** [comment]
i dunno how i feel about this text in general, it's such a weird change

**Comment by ImWeax** [comment]
> i dunno how i feel about this text in general, it's such a weird change

This is the announcement text used in SS13

**Comment by Golinth** [comment]
> This is the announcement text used in SS13

We aren’t ss13

**Comment by thebadman4662** [comment]
> > This is the announcement text used in SS13
> 
> We aren’t ss13

What do you mean? We are SS13 fork, aren't we???

**Comment by Dutch-VanDerLinde** [comment]
> > This is the announcement text used in SS13
> 
> 
> 
> We aren’t ss13

This is the announcement text used in SS14

**Comment by Golinth** [comment]
> > > This is the announcement text used in SS13
> > 
> > 
> > We aren’t ss13
> 
> What do you mean? We are SS13 fork, aren't we???

Literally, no. SS14 started as its own thing. Based on ss13 for sure, but not beholden by it.

**Comment by mirrorcult** [comment]
you dont need to go 'ohh but its from ss13' i merged the text because it was funny in ss13 and its funny here too
