### ISSUE TITLE
Already constructed gas filter instructs me on how to construct it

### ISSUE THREAD

**Issue by ilyamikcoder** [space-wizards/space-station-14#27547]
## Description
When I construct a flipped gas filter with 2 steel, it already works just fine, but tells me how to construct it. Apparently I need to unwrench it?

**Reproduction**
1. Construct a flipped gas filter.
2. Examine it.
3. Get confused.

**Screenshots**
![изображение](https://github.com/space-wizards/space-station-14/assets/37904672/96edcda9-5286-48c2-96ea-20279510c2f7)

**Additional context**
I am not being dumb in atmos, am I? I know I am pretty novice, but this just does not feel right.

**Comment by ilyamikcoder** [comment]
Anomaly observed only when dealing with flipped gas filters.
![изображение](https://github.com/space-wizards/space-station-14/assets/37904672/1c8d61e2-b853-4824-a872-bdc882d8a227)

**Comment by Lukasz825700516** [comment]
It looks like the this bug was introduced together with the ability to flip construction ghosts during construction 3f93b11e4acb9af9468bf1111cbbcade0a459f59.
