### ISSUE TITLE
Traitor HUD/Progress bars persist above people's heads and are visible through walls

### ISSUE THREAD

**Issue by ProfanedBane** [space-wizards/space-station-14#2755]
This effect remains until the person is viewed again.

Video: https://www.youtube.com/watch?v=lWcVB27qrPY

**Comment by Zumorica** [comment]
(Extra info: This happened in raspberry station with PVS disabled)

**Comment by ProfanedBane** [comment]
Traitor HUD was with PVS enabled.

**Comment by AJCM-git** [comment]
superseded by #2825 and  #2824
