### ISSUE TITLE
You have to be deceitfully close to someone to cuff them

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#27566]
## Description
In order to cuff someone, you have to be closer to them than normal. I can hug, attack, strip, or otherwise interact with someone from much farther away from someone than I have to be when cuffing.

**Reproduction**
1. Get close enough to someone untill their sprite turns green
2. Try to cuff them (you cant, but you can still attack or hug them)
3. inch closer untill you are finally able to cuff.

**Video**

https://github.com/space-wizards/space-station-14/assets/106507028/38c575be-416d-48c2-8b8c-ed6df55fca55

**Additional context**
If you are too far away, the sprite is green and the animation goes off but the cuff doafter will not progress. This can lead to confusion and frustration when trying to cuff someone since you have to be much closer to them than normal.

**Comment by deltanedas** [comment]
same when uncuffing

**Comment by thebadman4662** [comment]
> same when uncuffing

Which makes core so sad considering there are no holobarriers in sec lockers(I believe there is a chance at best, they should be guaranteed!) and you pretty much need armory access for something so basic as uncuffing prisoners in cell if you do not want to start building steel tables in front of the doors.

**Comment by IProduceWidgets** [comment]
at some point the uncuffing through windoors was patched as well, and I wish it were brought back as a feature.

**Comment by ShadowCommander** [comment]
> > same when uncuffing
> 
> Which makes core so sad considering there are no holobarriers in sec lockers(I believe there is a chance at best, they should be guaranteed!) and you pretty much need armory access for something so basic as uncuffing prisoners in cell if you do not want to start building steel tables in front of the doors.

> at some point the uncuffing through windoors was patched as well, and I wish it were brought back as a feature.

This can be made into a separate issue discussion of prisoners escaping too often when uncuffing. Might be fixed by mapping double windoors on cells or some other way.

**Comment by Ghagliiarghii** [comment]
It feels bad to do but sometimes with certain prisoners you have to stun baton them down while uncuffing and then leave before they can get back up otherwise they'll always tailgate you out and try to flush themselves :/

**Comment by keronshb** [comment]
> It feels bad to do but sometimes with certain prisoners you have to stun baton them down while uncuffing and then leave before they can get back up otherwise they'll always tailgate you out and try to flush themselves :/

I feel this is fine. It gives someone a chance to escape if the guard isn't careful enough.

**Comment by Golinth** [comment]
> It feels bad to do but sometimes with certain prisoners you have to stun baton them down while uncuffing and then leave before they can get back up otherwise they'll always tailgate you out and try to flush themselves :/

Just use a flash. Hold one in your hand as you uncuff, then hit them with the flash them as soon as you finish and need to leave.

**Comment by Kayek14** [comment]
Resolved by #28576
