### ISSUE TITLE
Mob pathing seems to be causing lag now

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#27561]
## Description
Apparently the server gets alot of lag whenever there are alot of killer tomatos about. I think something may be broken with mob pathing as the server noticeably slows down whenever they start pathing.

**Reproduction**
spawn alot of killer tomatos
watch lag happen as they path

**Comment by metalgearsloth** [comment]
do you have a profile

**Comment by Kayek14** [comment]
sorry i dont know what a profile means

**Comment by Kayek14** [comment]
apparently shadowcommander was notified of this by an admin in VC the other day and they may have more info about this

**Comment by metalgearsloth** [comment]
I'm gonna take this with a heap of salt without some level of proof.

**Comment by Kayek14** [comment]
Ill try to get a recording of it. Ive personally seen it happen twice so far and people in the round have also been affected by the lag. Only thing i can think of causing it would be the 50+ kliller tomatos since the lag noticabally stoped as soon as they were killed.

**Comment by metalgearsloth** [comment]
Is getting 50 killer tomatos a regular occurrence because 50 of them pathing isn't going to be fast and they should be removed or nerfed if that's the case.

**Comment by Kayek14** [comment]
Its been happening quite often over the past few days on the times ive been on. Id say in the past 20 rounds ive seen 50+ tomatos in about 5 of them

**Comment by Kayek14** [comment]
this issue seemed to be caused by the massive (50++) amounts of killer tomatos. It seems to be resolved.
