### ISSUE TITLE
You can not cancel someones self-uncuffing doafter by dragging them if there is no gravity

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#27562]
## Description
Usually if someone is uncuffing themselves you can drag them to stop the doafter. However, if there is no gravity then moving them will not stop the do after.

**Reproduction**
Start the self-uncuff do after while in no gravity?
Drag them with a different character
The doafter will not stop

**Comment by keronshb** [comment]
It's intended that people can uncuff themselves in zero g so they can't get permastuck by floating endlessly.

**Comment by thebadman4662** [comment]
But that basically forces sec into executing them. They should still be able to uncuff just fine by stopping the momentum or hitting a wall in case of being buckled.

**Comment by deltanedas** [comment]
its supposed to be if you arent accelerating you can cuff, moving should accelerate so ????

**Comment by Kayek14** [comment]
> But that basically forces sec into executing them. They should still be able to uncuff just fine by stopping the momentum or hitting a wall in case of being buckled.

Indeed, this was the exact issue i had in a round that prompted me to create this issue. I was HoS, i had two crewmembers cuffed in the evac shuttle. Shuttle lost gravity, i couldent stop them from uncuffing so i was forced to shoot them into crit.

I do agree that this is better than the alternative where it is impossible to uncuff due to floating endlessly, but there should still be a way for you to easially stop someone from uncuffing while in zero G.

**Comment by Dutch-VanDerLinde** [comment]
> > But that basically forces sec into executing them. They should still be able to uncuff just fine by stopping the momentum or hitting a wall in case of being buckled.
> 
> 
> 
> Indeed, this was the exact issue i had in a round that prompted me to create this issue. I was HoS, i had two crewmembers cuffed in the evac shuttle. Shuttle lost gravity, i couldent stop them from uncuffing so i was forced to shoot them into crit.
> 
> 
> 
> I do agree that this is better than the alternative where it is impossible to uncuff due to floating endlessly, but there should still be a way for you to easially stop someone from uncuffing while in zero G.
> 
> 
> 
> 

why did you shoot them into crit hitting them once would've cancelled it

**Comment by thebadman4662** [comment]
Yeah, shoving might not work but a simple punch/bite/slash in face should do the trick.

**Comment by Kayek14** [comment]
Thats true that a punch will stop the uncuffing do-after, however it feels wrong to have to resort to harm since thats the only way to stop someone from uncuffing in zero G

**Comment by Kayek14** [comment]
This issue seemes to be a design choice due to the difficulty of cuffing players in zero-G.
