### ISSUE TITLE
replay files simply fail to load when drag/dropped to the client

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#27572]
## Description
Ive been having problems with replays simply failing to load. I drag the zip file to my laucher and the launcher closes. No error, no black screen, no jump in processing power, no nothing. It just closes.

Both files that caused this to happen were 
- leviathan 52505
- leviathan 52439

**Video**

https://github.com/space-wizards/space-station-14/assets/106507028/8500f494-761f-41d7-bc9f-48107f498421

**Additional context**
potentially related to #27217 

EDIT: the files load fine when i use the client search feature. Only when drag/dropping the files does the client crash.

**Comment by metalgearsloth** [comment]
Might be a loader issue, not sure, need to run the launcher in debug and find out.

**Comment by VasilisThePikachu** [comment]
This is a bug in the launcher and has been fixed as part of #136

The issue is having spaces on the path
