### ISSUE TITLE
Slippery comp not working

### ISSUE THREAD

**Issue by XxSWAG-MASTER-OVERLORDxX** [space-wizards/space-station-14#27579]
## Description
The slippery component does not make someone slip when they walk over the object that is "slippery".

**Reproduction**
1. Give object or person slippery component.
2. Walk over them
3. Don't slip

This effects Honk bots and only honk bots as far as i know but this is a critical issue for them as its not only their only purpose in life BUT also their only means of self defense.

**Comment by K-Dynamic** [comment]
I think jonkbots and killer tomatoes with slip mutation are also meant to slip

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
> I think jonkbots and killer tomatoes with slip mutation are also meant to slip

true, i forgor 💀

**Comment by K-Dynamic** [comment]
I've done some testing on honkbots but I haven't been able to find much 

The slippery component isn't triggered at all on mobs (breakpoint didn't activate), so it might be an issue with either the collision or fixture component (systems?)

**Comment by Vermidia** [comment]
#27684 partially fixes this, you still need the fixture with slips defined + steptrigger components for slipping to work.
