### ISSUE TITLE
Everything flickering, game basically turned turn based on top of buggy.

### ISSUE THREAD

**Issue by thebadman4662** [space-wizards/space-station-14#27592]
## Description
I latejoiner like 2 hours into the shift as hos on round 52555 Miros and during zombie outbreak reality started to break apart. Kept getting some kind of error loop but I could not expand ~ window to show more in screenshot.

**Screenshots**
![obraz](https://github.com/space-wizards/space-station-14/assets/152504929/14770d38-2ffd-4bac-a28b-08d4938fd76e)

**Comment by Erisfiregamer1** [comment]
Same happened to me on a Leviathan admeme shift as a Botanist. Can confirm.

**Comment by Kayek14** [comment]
Same thing happened to me, I was able to record a video of it. Was getting console error spam with my jumpsuits entID. Issue seemed to resolve after i relogged.

https://github.com/space-wizards/space-station-14/assets/106507028/f7642c9e-92ee-49fb-8520-546570f96789

**Comment by metalgearsloth** [comment]
It's probably Container being null when the state comes in.

It needs https://github.com/space-wizards/RobustToolbox/pull/5073 but also the storage UI gets mega cooked when doing it so that also eneds fixing.
