### ISSUE TITLE
borg ui opening mispredicts when locked

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#27594]
## Description
lock and maint panel are in shared so no reason this cant be checked

**Comment by liltenhead** [comment]
Was about to make an issue, but saw this exists. Yeah, being able to accidentally see a borg has a syndicate module by clickin on them while they're locked is no good.

**Comment by ShadowCommander** [comment]
- Go up to borg
- Press E (ActivateItemInWorld) on the borg
- Modules UI pops up for half a second
