### ISSUE TITLE
ChemBag/PlantBag can't pick up items when using in-hand.

### ISSUE THREAD

**Issue by Keer-Sar** [space-wizards/space-station-14#27608]
## Description

ChemBagss and PlantBags used to be able to start a do-after and pickup all nearby storable entities. Another do-after would let you dump them out onto a table. Now you have to place all items inside them by hand and dumping is instant.
**Reproduction**

- Aquire item `chemistry bag (Chembag)` or `plant bag (PlantBag)`
- Click on storable item that is on the floor
**Screenshots**

https://github.com/space-wizards/space-station-14/assets/144283718/facac532-215f-46e6-bf86-f2d42d1263bf

**Additional context**

May be related to #22831

**Comment by Tayrtahn** [comment]
Fixed by #27601
