### ISSUE TITLE
Click dragging items "tosses them" into bins

### ISSUE THREAD

**Issue by B1essedknight** [space-wizards/space-station-14#27604]
## Description
Seemingly click dragging items into disposal bins attempts to "throw" them into the bin and seems to ignore the size of the object as i managed to "toss" a water tank into a bin. 

**Reproduction**
-grab an item, large seems to work best.
-click drag into a disposal bin

**Screenshots**
N/A

**Additional context**
It also would allow people to drag others into disposals with little warning aside from being suddenly dragged.

**Comment by deltanedas** [comment]
even grav gens fit

**Comment by beck-thompson** [comment]
Looks like this was fixed!
