### ISSUE TITLE
Nanotrasen Block Game seems to be broken.

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#27615]
## Description
Nanotrasen Block Game arcade game doesn't load

**Reproduction**
See screenshot

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/47093363/edda1d2a-f702-40df-ae10-b5852fe2f670)

**Additional context**
NA

**Comment by liltenhead** [comment]
*Nanotrasen Block Game™️

**Comment by Lukasz825700516** [comment]
duplicate of https://github.com/space-wizards/space-station-14/issues/27347 ?
