### ISSUE TITLE
Suit storage whitelist needs implementing

### ISSUE THREAD

**Issue by Flareguy** [space-wizards/space-station-14#27614]
## Description
In SS13, suit storages had a whitelist that functioned similarly to belts (ie. hazard vests and the engi hardsuit could hold engi items, and EVA suits could hold guns.)

Adding this system would add a lot of depth and challenge to item storage that our current system completely misses. I.E, "Do I wear a firesuit to carry a big O2 tank, or do I carry it around / settle for my emergency internals instead."

It is also worth noting that, in comparison to SS13, the lack of a whitelist means that suit storage is *massively* powercrept and completely lacking in any of the choices like the above situation. It may as well be a secondary back slot in its current state.

**Comment by Lamrr** [comment]
Ideally this should also have parenting support so you can define a couple of things in a base whitelist and 'add on' with the child outer suits, so we avoid having a repeat of #24762.

When implemented, the whitelists from SS13 can be used as a starting point, i.e. the `allowed = list(..)` in these [dm](https://github.com/tgstation/tgstation/tree/a99b36893c75c6e4ab32795b3d1e2a4efda6666a/code/modules/clothing/spacesuits) [files](https://github.com/tgstation/tgstation/tree/a99b36893c75c6e4ab32795b3d1e2a4efda6666a/code/modules/clothing/suits).

**Comment by Flareguy** [comment]
Fixed by #29332
