### ISSUE TITLE
Paper prioritizes eating over reading.

### ISSUE THREAD

**Issue by Aexxie** [space-wizards/space-station-14#27623]
## Description

It's a dark day. The station is in shambles. CentComm has sent you - the captain - a fax containing an urgent warning. They request confirmation that the situation is under control. Lest you do not respond, they will send over a firing squad to eliminate remaining crew. You pull the paper out of the fax machine with shaking hands. You frantically hit Z to read the paper. The world fades to black. When you regain consciousness, you find a paper stuffed into your mouth - the fax. The alarms blare, bearing a maroon color - all contracts have been terminated. And it's all your fault.

**Reproduction**

Hit Z while holding a paper - you will eat it rather than read it.

**Screenshots**

**Additional context**

Nukies keep eating the nuke codes lmao

**Comment by ElectroJr** [comment]
Its very likely caused by a PR of mine. If no one else gets around to it I'll fix it in a few hours
