### ISSUE TITLE
You can insert almost anything into disposals.

### ISSUE THREAD

**Issue by Admiral-Obvious-001** [space-wizards/space-station-14#27635]
## Description

You can unanchor the gravity generator and insert it into disposals, as well as probably a bunch of other full machines.

**Reproduction**

Unanchor a machine, drag/push it over disposals and it will insert into disposals and can be flushed.

**Comment by Nopey** [comment]
Same as #27604, although phrasing differs.

**Comment by B1essedknight** [comment]
yeah, I was mainly just talking about the dragging itself in my report. I didn't test how far one could go with it.
