### ISSUE TITLE
Geras shock interaction

### ISSUE THREAD

**Issue by TurboTrackerss14** [space-wizards/space-station-14#27633]
## Description
Geras seem to not take shock damage when attacking shocked grilles, unconfirmed for other types of shock damage.

**Reproduction**
>Be slime
>become geras
>hit shocked grille
>no damage/stun

**Screenshots**
n/a

**Additional context**
n/a

**Comment by TurboTrackerss14** [comment]
unable to confirm via testing but its possible it was during a power outage. incase someone wants to double check my working.

This occured when a geras broke *pic related* grilles on bagel
![image](https://github.com/space-wizards/space-station-14/assets/130304754/f7cc9831-1832-4ece-a369-93bdecab782b)

**Comment by Lamrr** [comment]
> unable to confirm via testing but its possible it was during a power outage. incase someone wants to double check my working.
> 
> This occured when a geras broke _pic related_ grilles on bagel ![image](https://private-user-images.githubusercontent.com/130304754/327570713-f7cc9831-1832-4ece-a369-93bdecab782b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2OTk5NTMsIm5iZiI6MTcxNDY5OTY1MywicGF0aCI6Ii8xMzAzMDQ3NTQvMzI3NTcwNzEzLWY3Y2M5ODMxLTE4MzItNGVjZS1hMzY5LTkzYmRlY2FiNzgyYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwM1QwMTI3MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04Y2QzNzViNTkwYjM2NTI5YjM2YjEzMTRmY2UxYjQyYjNhYzJkNDY2MzdkZjFkNmE1MjY4OWI1ZjIzNzQ1MzMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hMTq196Yf3t2L4t5Tr5En4UkMgVhgNhEYpyANIf0L1s) maybe related to hitting with an entity "between"? (the thinglass)

I did some local testing and I can confirm that the issue is directional windows block the shock effect from working, no matter what species you are, no matter what angle you approach from. As long as a grille has a thindow on it, you cannot get shocked.

**Comment by TurboTrackerss14** [comment]
Closing due to reclassification in above mentioned post
