### ISSUE TITLE
Syndicate sleeper agents might not appear in  round end summary

### ISSUE THREAD

**Issue by PolarTundra** [space-wizards/space-station-14#27648]
## Description
Sleeper agent syndicates don't appear to wind up in the round-end summary.

**Reproduction**
Unsure if there were any extraneous circumstances, but after a round a syndicate sleeper agent was not present in the round end summary.

Worth taking a look at to prevent false reports of self-antagonism.

**Comment by Dutch-VanDerLinde** [comment]
for some reason they only appear when the game preset was traitor, in any other game preset they don't appear
