### ISSUE TITLE
Players without nuclear operative antag enabled can be selected as nuclear operatives

### ISSUE THREAD

**Issue by squatporcupine** [space-wizards/space-station-14#27657]
## Description

Was selected as a nuclear operative commander with zero previous rounds as a nukie and the nukie antag selection disabled. Another member of the squad mentioned that they believed they had it disabled as well.
**Reproduction**

**Screenshots**

Replay at https://moon.spacestation14.com/replays/leviathan/2024/05/03/ 52738

**Additional context**

**Comment by deepdarkdepths** [comment]
Dupe of #27425

**Comment by VasilisThePikachu** [comment]
dupe
