### ISSUE TITLE
Grid collisions/ overlaps at roundstart

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#27667]
## Description
Some of the round start ships and shuttle grids are colliding with the station or wrecks when spawned in at round start. Appears to have increased in frequency recently.

**Reproduction**
NA Round start, seems to have a random element to it.

**Screenshots**
Not the worst but have seen the syndie ship on bagel round start intersected with station now several times.
![image](https://github.com/space-wizards/space-station-14/assets/47093363/abc01219-5811-4e39-9690-a5dcb7e96dd5)

**Additional context**
Can happen with other ships, namely salvage and ATS mainly.

**Comment by Titian3** [comment]
![image](https://github.com/space-wizards/space-station-14/assets/47093363/400f2ffe-db19-4988-b691-3b47b264729b)

**Comment by thebadman4662** [comment]
These overlaps can happen even in very middle of station while also being invisible and causing spacing... And we had it in medbay to make matters worse.

**Comment by Kayek14** [comment]
![image](https://github.com/space-wizards/space-station-14/assets/106507028/fa8f0322-56ff-4ef3-a450-ca592f9cbff2)

just had an instance of this happening on Levi 53739, marathon station

The ATS overlaped an asteroid

**Comment by Titian3** [comment]
This is getting quite bad:
![image](https://github.com/space-wizards/space-station-14/assets/47093363/437ea517-8a17-42ab-b7bc-b97233b43960)
Seen last 3 rounds straight.

**Comment by metalgearsloth** [comment]
I remember looking at it before break but the ftl-travel bounds needed fixing I think.

**Comment by UbaserB** [comment]
I’ve had one of the mining asteroids be glitched inside the reclaimer before

**Comment by metalgearsloth** [comment]
Okay most of the problems are StationRandomTransform being terrible so that needs fixing.
