### ISSUE TITLE
Entity rename mechanics are incompatible with each other

### ISSUE THREAD

**Issue by SlamBamActionman** [space-wizards/space-station-14#27670]
## Description

There is no proper support for renaming entities in a way where multiple systems are compatible with each other. Examples of these systems include gluing/lubing, labeling, metamorphic glass names and pAIs. Conflicts between these systems can cause an item to lose one name change if another system changes it under certain circumstances.

As an example, the label system saves the pre-label name in the entity's LabelComponent. This is the name that the entity gets reset to when the label is removed. That means any other system that changes an object name gets overwritten if the label is removed:

- You can remove the pAI's name and return it to "personal ai device" by labeling it before a role joins, and then removing the label after.
- You can remove glue and lube tags from an object by labeling it before applying the substance and then unlabeling it after.
- Depending on implementation, this can happen in reverse.
  - For glue/lube, if you apply the substance to a labeled object and then remove the label, the object gets the label back when the effect wears off.
  - For pAIs the label gets hidden when a pAI role joins and remains hidden once the role leaves as the entity gets reset to its prototype name.

Metamorphic glasses is another system that has this same problem.

**Reproduction**

1. Apply a label (e.g. "test") to an object.
  - Resulting name: "object (test)"
2. Apply space glue to the object. 
  - Resulting name: "Glued object (test)"
3. Remove the label (by leaving the label text field blank). 
  - Expected name: "Glued object"
  - Resulting name: "object"

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/83650252/5464f7e1-226c-4ec5-a0e4-2f4dda04cf62)

Example of how a metamorphic glass can be disguised using this method by applying a label while being a beer glass, changing its contents and then removing the label.

**Additional context**

Found in PR #26749

**Comment by Tayrtahn** [comment]
Got a fix in the works for this.
