### ISSUE TITLE
False alarm rule sucks and most of the time doesnt do anything

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#27720]
## Description

false alarm
- picks a random event
- if the event doesnt have an announcement it doesnt do anything
- if it does it plays that events announcement

most of the time this will just literally do nothing and most of the other time it will just pick the ventcritters announcement or some shit

ideally false alarm is lower frequency but only picks high severity announcements where it's obvious like 10-15 minutes after that it wasnt real like kudzu meteors sleeper agents etc.

**Reproduction**

**Screenshots**

**Additional context**

**Comment by slarticodefast** [comment]
Fixed by #27721
