### ISSUE TITLE
Uplink Improvements

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#2772]
- Physical tele-crystals you can buy in uplink and plug into PDAs to increase uplink budget.
- Job-specific traitor items.
- Player-count specific traitor items.
- Nuke-ops/Traitor/Clown-ops specific traitor items purchasable in the uplink. (Nuke-ops can't buy energy crossbow etc.)
- Random item selection.
- Discounted items.
- Lobby traitor preferences if they want their uplink to be in a pen, PDA or headset.
- Bundles such as the "Surplus Crate" which randomly spawns 20 TC worth of random items into a crate.

For projectile weapons bought from uplinks, better UI management when selecting ammo types should be implemented. Descriptions for items purchased from the uplink should also be improved similar to the advice in #2717.

**Comment by EmoGarbage404** [comment]
Points 3, 5, 6 are not implemented in the new store system, but could be easily added. The only one not addressed i the uplink in pda/pen/headset
