### ISSUE TITLE
addgamerule Nukeops isnt making the nukies

### ISSUE THREAD

**Issue by XxSWAG-MASTER-OVERLORDxX** [space-wizards/space-station-14#27762]
## Description
Addgamerule Nukeops does not make the ghost roles its meant to. in the past it has made a commander, agent and at least three other operative ghost roles, it no longer does this leading to have to manually make each nukie

**Reproduction**
use, addgamerule Nukeops and see the lack of ghost roles

**Comment by Plykiya** [comment]
duplicate #27377, pain

**Comment by Tayrtahn** [comment]
Duplicate of #27377

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
that's strange since for me it would make the map, but not the ghost roles anyway its still prob the same issue
