### ISSUE TITLE
PortableFlasher needs destructible component or another solution

### ISSUE THREAD

**Issue by QuietlyWhisper** [space-wizards/space-station-14#27780]
## Description

It blocks movement, bullets, and is indestructible currently.

**Comment by deltanedas** [comment]
it definitely shouldnt block bullets
blocking movement maybe only when anchored

**Comment by QuietlyWhisper** [comment]
they should be destructible if you can't move through them tbh, they become makeshift indestructible barricades otherwise, and I saw this happen unintentionally in game.

**Comment by slarticodefast** [comment]
Fixed by #29564

**Comment by Plykiya** [comment]
I just mald PR'd it and it turns out there's an issue hahaha
