### ISSUE TITLE
Chameleon projector is really strange

### ISSUE THREAD

**Issue by ElPidor** [space-wizards/space-station-14#27805]
Be Syndicate buy a Chameleon 7 tk projector
Full health, pretending to be a chair or something else.
Get hit.
Now you can't disguise or do anything with it because only the code god knows how this item behaves.
Make a bunch of clicks on object and pray for gods that you'll transform into one.
Even if you have the lowest health level, you cannot disguise yourself as any object, but some objects can be used because ???
This item doesn't have any word about cooldown or something in uplink, that makes really unreliable
If you buy a chameleon disguise kit and have the UI while you use chem projector, it will all disappear and then reappear after you turn back into a human, but it will all be in one place of the screen.
_Le solution_ 
It would be better to have the chem projector scan an object and remember it rather than have the agent transform into something, rather than having to take a cigarette or other junk into the backpack and then click on it.
 **The current design of this item is highly questionable.**

**Comment by deltanedas** [comment]
yes

**Comment by beck-thompson** [comment]
sweet! Looks like #27111 fixed it 🫡
