### ISSUE TITLE
Soap should degrade per-slip

### ISSUE THREAD

**Issue by Hmeister-real** [space-wizards/space-station-14#27802]
## Description
Each slip should be equal to one bite, or maybe more, but it really should degrade, soap being an infinite slip + not rubbish makes it a pain. maybe instead it could become crushed after a few slips, and become rubbish? but that's more work than necessary.

**Additional context**
 Decrease slips, decrease tiding, increase sec. Simple!

**Comment by K-Dynamic** [comment]
This be a feature request

I vaguely remember a pr to make slippable objects (bananas peels, soap) fly off when stepped on, which sadly got closes or left derelict

**Comment by metalgearsloth** [comment]
See attached PR.
