### ISSUE TITLE
Syndicate Human Reinforcement should have syndicate throwing knife in their boots

### ISSUE THREAD

**Issue by ElPidor** [space-wizards/space-station-14#27809]
Having a gun with one mag is not enough for these guys.
 They should have  a cool knife as a last weapon instead of NT combat knife is much more cool and balance.

**Comment by Dutch-VanDerLinde** [comment]
1 throwing knife is horrible

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
I support this, since it would be funny and that's it

**Comment by FungiFellow** [comment]
This honestly just sounds like powercreep.

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
I mean the knife isn't that good, if anything, I personally would say it's a downgrade, but it adds some flare to reinforcements

**Comment by neutrino-laser** [comment]
@XxSWAG-MASTER-OVERLORDxX I did it
