### ISSUE TITLE
Left control key issue

### ISSUE THREAD

**Issue by ScrazymanX** [space-wizards/space-station-14#2782]
When I hold my left control key, I can't move to my left. However, I can move to my right, up, and downwards. The link I'll attach shows me trying to move left when I'm not holding left control and then when I am holding left control down.

https://gyazo.com/272cabbfc6dc8e4e6d549c0476bc3b8e

**Comment by ShadowCommander** [comment]
Needs a change in the TextSelectAll to not return true or set args.Handled so that MoveLeft can be triggered after.
