### ISSUE TITLE
Vim breaks your game if you open control panel

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#27822]
## Description
Im not sure how to explain it so ill post a video. Essentally if you right click > open control panel on a vim. It will disapear and  your game starts flickering/reloading objects randomly as you move away and back to its location.

**Reproduction**
Spawn a vim
Right click on it
Open control panel

**Screenshots**
At 0:28 you can see the screen stutter as i move back to the location.

https://github.com/space-wizards/space-station-14/assets/106507028/b512ba6f-ab75-4362-b65c-3ab96f1f984b

**Comment by deltanedas** [comment]
logs prob have a missing rsi state error or something will look at it in a bit

**Comment by deltanedas** [comment]
![06:10:25](https://github.com/space-wizards/space-station-14/assets/39013340/58ca8e35-cfe0-4819-8a17-f8299b87a47c)

womm

**Comment by deltanedas** [comment]
wait control panel not maint panel im idior
