### ISSUE TITLE
Robotics console needs mapping

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/space-station-14#27832]
#24855

Put in RD room

**Comment by deltanedas** [comment]
should be in robotics so anyone can see available borgs, its locked by default so no trolling

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
If its not in robotics its just going to be dragged into robotics for them to use anyway

**Comment by PJB3005** [comment]
Absolutely should not be in Robotics, that's way too high-traffic of an area for an item that is usually very high-value.

**Comment by deltanedas** [comment]
in order to troll borgs with it youd need an emag or rd access, with either you can just go into rds room so doesnt matter

**Comment by FungiFellow** [comment]
To quote the Original PR
>"since all of sci has uses for it, it should be mapped in robotics not rds room"
The Disable/Explode is Access Locked to RD, putting it in RD's office just prevents whoever decide to be a Robotocist from being able to effectively manage Borgs. It's just gonna be moved to Robotics by RD every shift.

**Comment by UbaserB** [comment]
I assume all maps have the robotics console now?

**Comment by PJB3005** [comment]
![image](https://github.com/space-wizards/space-station-14/assets/8107459/2b7e2554-21d4-470c-9159-3830bf051ba6)

I see extremely little in the way of people actually bothering to link back to issues they are solving so probably not.

**Comment by Doctor-Cpu** [comment]
Atlas has it mapped.

**Comment by Flareguy** [comment]
Not actually fixed yet. Still needs mapping on most maps.

**Comment by deltanedas** [comment]
which maps pro

**Comment by lzk228** [comment]
- [ ] Europa (but who really cares)
- [ ] Meta

**Comment by UbaserB** [comment]
> * [ ]  Europa (but who really cares)
> * [ ]  Meta

europa isnt maintained and can probably be removed now considering that planet map support is basically done.

**Comment by Brandon-Huu** [comment]
```
Resources/Maps/cog.yml:67018:- proto: ComputerRoboticsControl
Resources/Maps/reach.yml:6437:- proto: ComputerRoboticsControl
Resources/Maps/marathon.yml:52230:- proto: ComputerRoboticsControl
Resources/Maps/omega.yml:31110:- proto: ComputerRoboticsControl
Resources/Maps/oasis.yml:77343:- proto: ComputerRoboticsControl
Resources/Maps/packed.yml:35016:- proto: ComputerRoboticsControl
Resources/Maps/core.yml:60959:- proto: ComputerRoboticsControl
Resources/Maps/train.yml:37259:- proto: ComputerRoboticsControl
Resources/Maps/meta.yml:62184:- proto: ComputerRoboticsControl
Resources/Maps/saltern.yml:27892:- proto: ComputerRoboticsControl
Resources/Maps/fland.yml:96351:- proto: ComputerRoboticsControl
Resources/Maps/box.yml:69409:- proto: ComputerRoboticsControl
Resources/Maps/bagel.yml:60142:- proto: ComputerRoboticsControl
```

Close this issue?

**Comment by Brandon-Huu** [comment]
oh wait, origin is missing

**Comment by Brandon-Huu** [comment]
origin is no longer a map

**Comment by Brandon-Huu** [comment]
Yeah, issue should be closed
