### ISSUE TITLE
Robotics Console can be used to emag check cyborgs

### ISSUE THREAD

**Issue by Zap527** [space-wizards/space-station-14#27848]
Title, mostly. Liltenhead included this in his video so it got a lot of visibility, so it's bound to get abused.

Pressing the "disable" button normally plops out the brain of a cyborg, meaning that you can't disable them again (since their brain is already out), so the disable button is disabled. On emagged cyborgs, plopping out the brain fails, so the button does not gray out and the cyborg is effectively confirmed to be emagged.

This is most likely an oversight and unintended behavior, considering the destroy button mimics an emagged cyborg being destroyed.

**Comment by HelpTheSteak** [comment]
This is intended look at the console pr

**Comment by AJCM-git** [comment]
> This is intended look at the console pr

It is intended that the brain doesnt plop out but disable should have the same behavior as the normal one for consistency

**Comment by Zap527** [comment]
Looking at the PR itself, this behavior does not feel intended. The "Destroy" functionality on emagged cyborgs pretends like the cyborg is destroyed and even removes said borg from the console altogether. I don't see why the other option would provide more feedback.
And to be honest, even if it is intended, we should try to cut the number of instant emag checks as much as possible.

**Comment by deltanedas** [comment]
yeah ill make it report removed brain in a bit so cant validcheck borgs remotely

**Comment by superjj18** [comment]
> This is intended look at the console pr

It is not intended, if it were “destroy” would not remove the cyborg from the list or feign a “cyborg has been destroyed” message.  It’s not intended to be used as a emag checker
