### ISSUE TITLE
Doors on Packed doors between med and sci are dual access

### ISSUE THREAD

**Issue by MissKay1994** [space-wizards/space-station-14#27868]
On Packed station, I've noticed that the maints doors between med and sci are dual access, meaning both med and sci can open them. This seems compared to other stations to be unintentional. Med people and antags also seem to frequently abuse these doors to do whatever they want in science and come and go as they please.

![20240509181517_1](https://github.com/space-wizards/space-station-14/assets/15877268/590ff9e7-5e8a-4081-8b1c-c0563635710d)

**Comment by UbaserB** [comment]
I'm pretty sure this is intentional

**Comment by MissKay1994** [comment]
Interesting, since it feels very inconsistent with other maps where med and sci are beside each other like that but the doors aren't like that

**Comment by thebadman4662** [comment]
Yeah, its so sci can hop into cryopod the second they get deathfoamed or are crit. And if sci is understaffed medical staff can always have at least a look at them.

**Comment by Brandon-Huu** [comment]
Is this an issue that needs to be fixed?

**Comment by thebadman4662** [comment]
Its a map feature, not issue.
