### ISSUE TITLE
Nukie commander antag role selection bugged

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#27864]
## Description
When selecting no to the nukie antag command role it looks like its not respecting the selection and will put you in the role even if you have it selected.

**Reproduction**
Might be hard with how nukies are selected
Did reproduce with player in game, they were chosen as commander, got them to validate their selection by respawning them and checking the antag selection.

**Screenshots**
NA

**Additional context**
Unsure if it is with other antag roles too or just the nukie commander currently.

**Comment by Dutch-VanDerLinde** [comment]
this has been reproduced

**Comment by SoulFN** [comment]
I also reproduced it, i haven't unlocked nukie commander (Not enough command playtime) but i became nukie commander

**Comment by ShiroGX** [comment]
It happens to other roles. I became Nukie Agent even tho it was locked

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
This happens with all nukie roles, can the title please be changed to reflect that
