### ISSUE TITLE
Ninja teleport will not Teleport over certain objects that you can normally see over

### ISSUE THREAD

**Issue by Sandman3323** [space-wizards/space-station-14#27870]
## Description
Ninja cannot teleport over certain objects like computers and machines that you can normally see over these objects act as if they obscured line of sight and can lead to unfortunate deaths. From what I see if bullets cannot go through an object you cannot teleport through it either except for glass.

**Reproduction**
to reproduce this you just have to attempt to teleport over any computer or machine like the communications computer.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by B1essedknight** [comment]
Coulda sworn that #27793 was suppose to fix that.

**Comment by Plykiya** [comment]
issue was resolved
