### ISSUE TITLE
Chameleon projector absolute invisibility

### ISSUE THREAD

**Issue by dolgovmi** [space-wizards/space-station-14#27874]
## Description
When i used it on an oxygen tank i had on my back, i was completely invisible, I didn't look like no oxygen tank, worked with some trash in my pockets too. (also it worked with shoes i was wearing)

**Reproduction**
Put an oxygen tank on your back, or an MRE wrapper in your pockets (probably works with a lot of other stuff too), try to copy their appearance from said slots.

**Comment by deltanedas** [comment]
fixed by rewrite someone merge it...

**Comment by mirrorcult** [comment]
where

**Comment by dolgovmi** [comment]
#27111 i guess

**Comment by beck-thompson** [comment]
Duplicate issue! Thanks for the report 🫡
