### ISSUE TITLE
Object stuck to cursor when grabbed in quick succession

### ISSUE THREAD

**Issue by XxSWAG-MASTER-OVERLORDxX** [space-wizards/space-station-14#27873]
## Description
This bug can lead to combat and even general gameplay to feel terrible and overall unenjoyable

**Reproduction**
Grab an item, then quickly swap hands and grab something else.
To fix you need to either close the inventory OR place it back where it was before hand

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/151447893/8379392e-171d-4685-b0b1-a3b382a5b3c7)

**Comment by deltanedas** [comment]
happens the most for me when quickly grabbing tools for deconstructing stuff

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
grabbing anything quickly one after the other will bug it 100% of the time, its to a point where i have to wait between grabbing stuff and its tedious as hell

**Comment by MjrLandWhale** [comment]
Fixed by #27960 ?

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
does seem so
closing since it seems fixed <3
