### ISSUE TITLE
Warden and HoS armour should have suit storage slots.

### ISSUE THREAD

**Issue by PolarTundra** [space-wizards/space-station-14#27884]
## Description
The recent change to suit storage slots removed them from jackets but kept them for armour. However, despite being armour, the Warden's armoured jacket and the HoS' Armoured trenchcoat as well as their winter coat variants lack suit storage slots. This feels like an oversight as these are all armour items and should thusly have suit storage slots.

**Reproduction**
Equipping anything in the suit storage slot of the 4 listed armours does not work.

**Additional context**

I do not know if this was intentional, but I just want to re-iterate that it feels like an oversight, as I don't see much reason Warden and HoS' armour would lack this ability, whilst a standard issue armour vest from Security or even the slim form that the Bartender gets have suit storage.

**Comment by websitejanitor** [comment]
The detective trenchcoat and probably their armor vest should have suit storage slots too, as they are also armor.
