### ISSUE TITLE
Med Borgs needs med and chem glasses, to may not break they laws and know who's injured

### ISSUE THREAD

**Issue by gordod3** [space-wizards/space-station-14#27880]
## Description
Borgs need to know sure what cure he use and who need help, especially then someone poisoned and can't be shift+clicked for examine. 

**Reproduction**
Crewmate in crit? Give him inaprovalin - he died. . . . That was lexorin, lol you break laws now go to borg jail in artifact crusher! 

![Whoops](https://github.com/space-wizards/space-station-14/assets/59264914/2578340b-621d-4337-b2e8-f7ee3d4110fe)

**Additional context**
This is cyborg! He must know everything around and be robot-servant ready make everything for crewmate monkey batrhender,

**Comment by muburu** [comment]
maybe https://github.com/space-wizards/space-station-14/pull/27843 could add medhud to their PR as well

**Comment by gordod3** [comment]
> maybe #27843 could add medhud to their PR as well

That would be nice.

**Comment by marboww** [comment]
> maybe #27843 could add medhud to their PR as well

ok

**Comment by marboww** [comment]
close issue please

**Comment by lzk228** [comment]
was resolved
