### ISSUE TITLE
Feature Freeze is in effect until June 14th

### ISSUE THREAD

**Issue by ShadowCommander** [space-wizards/space-station-14#27898]
We are instituting a feature freeze in the time between MAY 10 - JUNE 14. 

The game has grown considerably in the last year thanks to the efforts of our many contributors, players, and maintainers. We cannot thank everyone enough. 

The purpose of this freeze is so that we can push the game to as stable a point as possible as we prep for official release out of playtest. During this freeze we will be focusing on code cleanup, optimization, code refactors, bug fixing, and admin tool work. Several maintainers have committed to working diligently during this time to improve the game's stability. 

If you have a feature PR active during this time it will be closed until the freeze is over. Simply ask for it to be unfrozen after June 14th. Thank you.

---

Pull Requests that are allowed:
- Game stability
  - Bug fixes. With priority on crash bugs and ones that cause the player to be unable to play the game.
  - Optimization of code found using benchmarks or server logging.
- Codebase quality
  - Adding documentation to fields and methods.
  - Refactor of EntitySystem methods for ease of use when coding.
  - Converting old UIs to XAML.
- [Admin tools and QoL](https://github.com/orgs/space-wizards/projects/8)

If you're not sure if something you want to work on is allowed, then feel free to ask either here or on Discord.

**Comment by mirrorcult** [comment]
feature freeze has ended as of 2 hours ago

**Comment by deltanedas** [comment]
the tide
