### ISSUE TITLE
UI Glitch Syndie

### ISSUE THREAD

**Issue by Sreffn** [space-wizards/space-station-14#27903]
## Description
Bought an EMAG from syndie store for 12 telecrystals, dropped an singulo beacon right in front of QM - a UI glitch?
**Reproduction**
Was playing as diona, had just turned traitor a short moment after round start, see description.

**Screenshots**

**Additional context**

**Comment by mirrorcult** [comment]
are you positive you didnt just click the wrong button

**Comment by Boaz1111** [comment]
> are you positive you didnt just click the wrong button

Yeah that's what I'm thinking, Emag costs 8, not 12. Singu beacon costs 12 so...(is also right below emag)

**Comment by deepdarkdepths** [comment]
I'm thinking this is another case of misinterpreting which button purchases which item

**Comment by Sreffn** [comment]
There were actually two options for emag I should mention, one cost 20 if I looked it up in the search bar, the other cost 12 if I found it by hand in disruption I think. I clicked on the one costing 12 after checking all the sections by hand. I'm certain I bought what was listed as an emag for 12 telecrystals. I had previously bought the syndie pAI and could not afford the 20 option.

**Comment by deepdarkdepths** [comment]
> There were actually two options for emag I should mention, one cost 20 if I looked it up in the search bar, the other cost 12 if I found it by hand in disruption I think. I clicked on the one costing 12 after checking all the sections by hand. I'm certain I bought what was listed as an emag for 12 telecrystals. I had previously bought the syndie pAI and could not afford the 20 option.

There is no 20tc emag and there is no 12tc emag. It's 8 and there's only one.

**Comment by Sreffn** [comment]
If I get syndie again I'll try get a screenshot.

**Comment by mirrorcult** [comment]
going to assume this is user error
