### ISSUE TITLE
Pathological liar breaks zombie accent

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#27902]
![Screenshot_20240511_002239](https://github.com/space-wizards/space-station-14/assets/124214523/2993182e-5a01-40a4-8fbc-900d34a4e431)

i think i can fix it, but just want to specify the better way to do it
- set ReplacementChance in ReplacementAccentPrototype to 1 in ZombieSystem.Transform.cs
https://github.com/space-wizards/space-station-14/blob/40802738ec84496cb55ad824bf0f94ed7a7916c6/Content.Server/Zombies/ZombieSystem.Transform.cs#L110-L113
- make ReplacementChance applied only to wordReplacements, not FullReplacements
https://github.com/space-wizards/space-station-14/blob/40802738ec84496cb55ad824bf0f94ed7a7916c6/Content.Server/Speech/Components/ReplacementAccentComponent.cs
https://github.com/space-wizards/space-station-14/blob/40802738ec84496cb55ad824bf0f94ed7a7916c6/Content.Server/Speech/EntitySystems/ReplacementAccentSystem.cs#L25-L31

would like to hear any other proposals

**Comment by Tayrtahn** [comment]
Seems to me like ReplacementChance should be a field in ReplacementAccentPrototype, rather than ReplacementAccentComponent.
