### ISSUE TITLE
Blue space anomalies can teleport corpses out of dragon's stomach

### ISSUE THREAD

**Issue by KingOnBudget** [space-wizards/space-station-14#27901]
## Description
Title kinda explains it all 👍 

**Reproduction**

**Screenshots**

**Additional context**

**Comment by muburu** [comment]
i kind of like this being a feature, but it can easily be abused by bluespacing the bodies out of your stomach as a dragon and then devouring them again and again to get HP back forever

**Comment by thebadman4662** [comment]
To be fair, dragons barely heal from fearing bodies(less than a single bullet) so you would need to devour A LOT of people to have any meaningful passive healing from it.
