### ISSUE TITLE
An energy drink can be found in the snack vendor

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#27914]
## Description

Drinks go in drink vendor, snacks go in snack vendor. This is an anomaly.

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/134914314/ef07c598-f9e2-47a8-bc69-e4f76a2885fe)

**Comment by deltanedas** [comment]
ciggies are snacks too you heard it here first :trollface:

i think knockoff red bull goes well with the theme of the vending machine

**Comment by Hanzdegloker** [comment]
Tis the vending machine of questionable discount products, the people yearn for red bool plus Dan's soaked smokes and boritos.

**Comment by EmoGarbage404** [comment]
I dont really think mixing snacks and drinks is bad and this fits well enough
