### ISSUE TITLE
Lockable buttons don't work on Meta

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#27915]
## Description

The buttons in med specifically don't seem to be linked or functioning, even when unlocked.

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/134914314/de5c3636-43e2-48b4-8699-c74f20f852b4)

**Comment by Emisse** [comment]
theyre unlinked atm because the bug where you cant link stuff due to access is still in

**Comment by deltanedas** [comment]
you can vv the thing and toggle Enabled on accessreader to link stuff

its annoying as fuck but better than being unlinked
