### ISSUE TITLE
Items from your bag sometimes get stuck on your cursor

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#27918]
## Description

Sometimes when you open your bag and tap an item in your inventory, there is a chance that it can get stuck on your cursor, unable to interact with anything. It's not the item itself that sticks to your cursor, but the entire item grid (so like a cigarette would be the cigarette + a 1x1 grid behind it). It's immediately fixed when you close the bag and open it again, but otherwise it's really annoying.

**Reproduction**

1. Try to take out item from bag by clicking it.
2. Item now stuck on cursor.
3. Try tap on hand, doesn't work.
4. Try tap on empty space in bag, doesn't work.
5. Close bag and open again.
6. Item was in the same place it was before you picked it up.
7. Works now, but may happen to any item in bag.

**Comment by Kadeo64** [comment]
this bug is slightly annoying therefore it should be priority 1 and holy shit :trollface:

**Comment by Dutch-VanDerLinde** [comment]
also opening a bag sometimes mispredicts

**Comment by Dutch-VanDerLinde** [comment]
this is also replicated it's so annoying

**Comment by deltanedas** [comment]
unbelievably annoying
possibly related, had a storage implant refuse to open until i relogged after handling someone elses duffel with a survival box in it

**Comment by EmoGarbage404** [comment]
@UbaserB in the future, don't tag issues as replicated if they don't actually contain meaningful steps to replicate the bug. simply stating that clicking on the item causes the issue is untrue. A replicated issues should actually have the steps that lead to the consistent reproduction of that behavior.

**Comment by UbaserB** [comment]
> in the future, don't tag issues as replicated if they don't actually contain meaningful steps to replicate the bug. simply stating that clicking on the item causes the issue is untrue. A replicated issues should actually have the steps that lead to the consistent reproduction of that behavior.

Oh I didn’t know that, I thought the replicated tag means the issue has been confirmed by a large enough group of people. My bad.
