### ISSUE TITLE
The gravity generator sprite is weird.

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#27921]
## Description

If you look at it closely, it is 3 prongs around a ring that is kept in place which likely provides gravity for the Station. But... it's asymmetrical. For something intended for "containment", this is an insecure design. Once i noticed this, it bothers me a lot. I would be fine if it was 3 prongs but in triangle formation, or with an extra added prong so it's boxy. You can see the sprite in the image below, and how it currently looks like vs. what it should ideally look like. The sprite seems really hard to make though because it's extremely high quality, so i don't expect this to be done any time soon.

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/134914314/593b1e59-870e-443e-86d2-aa8912bac5a0)

![image](https://github.com/space-wizards/space-station-14/assets/134914314/fd1b797d-c464-4777-9b5c-182c48b6f0d5)

**Comment by moonheart08** [comment]
I figure the fourth prong is omitted (or the three prongs are not angled) for a very simple reason: This design works good with 3/4ths and allows you to see the fancy glowy ring, instead of obscuring it. Sprites should look good first, make perfect sense second imo.

**Comment by EmoGarbage404** [comment]
agree with moony. the sprite is fine and i don't think something like this is really a reason to be respriting anything
