### ISSUE TITLE
The UI of the dispensers is too small

### ISSUE THREAD

**Issue by Pok27** [space-wizards/space-station-14#27943]
## Description

The user interface of the dispensers is smaller than other machines, making the text of the reagents difficult to read.

**Media**

https://github.com/space-wizards/space-station-14/assets/113675512/592fa547-2e70-4edc-81f8-fe2838c18e1f

**Additional context**

It can be difficult to understand the problem from the video, it's better to see it in game.

**Comment by UbaserB** [comment]
I agree with this, it's a little small and a little too much empty space for me personally

**Comment by Pok27** [comment]
Fixed in #27958
