### ISSUE TITLE
Can't save character changes in 1024x768

### ISSUE THREAD

**Issue by BozoDel** [space-wizards/space-station-14#27945]
It is no longer possible to save changes made in the character setup screen on a small resolution (1024x768).

There are two sets of buttons in the upper right corner. The large buttons are okay, but the small buttons are all squashed together, and have been for a while. There used to be two save buttons, one large, one small. The large one seems to have been removed, and I can't access the small squashed one.

![Captura de tela_2024-05-11_22-58-10](https://github.com/space-wizards/space-station-14/assets/1218859/13a061d9-541b-4a05-a321-fd3935c54e5d)

**Comment by bruhmogus** [comment]
this also happens on other small resokutions with different effects

**Comment by VasilisThePikachu** [comment]
![image](https://github.com/space-wizards/space-station-14/assets/34938708/1c5a480c-09cf-45d4-a2e6-2dc9209dfbbd)
![image](https://github.com/space-wizards/space-station-14/assets/34938708/0e569f14-035c-48d9-9327-3c2143f24a1d)

1920x1080

I'm able to reproduce this by making my window smaller

I also found i can reproduce this by increasing my ui scale to 150%

**Comment by BozoDel** [comment]
Oh, nice! I can work around this by downscaling the UI!
