### ISSUE TITLE
Toilet can be used to noclip

### ISSUE THREAD

**Issue by HelpTheSteak** [space-wizards/space-station-14#27955]
## Description
Toilets have no collision and can be wrenched in walls and be sat on to no clip pass

**Reproduction**
Grab a toilet and wrench it into a wall and then sit on it

**Comment by HelpTheSteak** [comment]
The toilet has to be facing the way you want to noclip as well

**Comment by TurboTrackerss14** [comment]
resolved by https://github.com/space-wizards/space-station-14/pull/27994
(whoopsie)
