### ISSUE TITLE
Evacuation pod event ship cant dock

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#27953]
## Description
The shuttle from the UnknownShuttleDisasterEvacPod cant dock once it gets to the station as its only thruster pushes it away from the docking airlock.

**Reproduction**
Try and dock in the evac pod shuttle.

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/47093363/92f1110f-370e-4d7c-a1d4-6b397945ce61)

**Additional context**
NA

**Comment by deltanedas** [comment]
ive docked to a wreck even with this shittle it just takes mad skill

**Comment by Errant-4** [comment]
It's a lifepod. Can it really be expected to be able to dock? Either attract the attention of an actual ship and let *it* dock to you, or if your only option is an airlock, position the pod as close as you can and then jump over Bowman-style

**Comment by Titian3** [comment]
Closing, skill issue if they cant dock or figure out to take a little space walk or go chat to salv/cargo lurking around.

**Comment by Ilya246** [comment]
yeah it's dockable i've docked pod shittles to station before
