### ISSUE TITLE
Changes that are needed to slipping

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#27966]
## Description

- [] A cooldown that begins just as an item is placed down so you don’t slip while walking by
- [] You need to move a minimum distance while running to slip
- [] A percentage chance to drop the item in your hand instead of being 100% of the time

This is to make slipping less harsh, especially for people with high ping

**Additional context**

Further discussion on the discord can be seen here: 
https://discord.com/channels/310555209753690112/770682801607278632/1239405469911744583

**Comment by thebadman4662** [comment]
I was wondering, does walking have to cut our speed down to 50% or it would be fine to simply make it reduce down to slip speed(75% or less is safe to walk if not lube), that way antags engaging in loud slip warfare do not have such opressive home turf advantage as magboots are not that much different to walking anymore, unless its the dreaded lube of course.

**Comment by mirrorcult** [comment]
i dont think any of these changes are agreed upon enough that we need an issue for it
