### ISSUE TITLE
lasers hit crit mobs that aren't aimed at

### ISSUE THREAD

**Issue by Dutch-VanDerLinde** [space-wizards/space-station-14#27988]
considering that lasers are also ranged i believe they should work the same like guns do in #27905

**Comment by Dutch-VanDerLinde** [comment]
the same should apply to wideswings too maybe?

**Comment by EmoGarbage404** [comment]
Lasers arent projectiles

**Comment by PolterTzi** [comment]
I mean, projectiles avoid crit targets to represent the character aiming above them, I don't see why the same shouldn't apply to laser weapons.

**Comment by Dutch-VanDerLinde** [comment]
dupe
