### ISSUE TITLE
Instant and UNINTENDED round removing (by turning into ash, see desc in details) 

### ISSUE THREAD

**Issue by UnicornOnLSD** [space-wizards/space-station-14#27983]
## Description

I, playing as Bethany Bobberson, on Round #53542 salamander, was a security officer. I was fighting the dragon, backed off after set on fire, and ran into one of a ratking's servant, then at that VERY MOMENT, for a SPLIT second, the fire sprite on me went from very light (just a few flames) to the MAX (body engulfed) and I got turned into ash in an instant

What was left other than my stuff was TWO ash, me and a rat servant, I presume

What I can only assume is a collision bug of the sort that stacked the fire on me so bad it fucking ashed me instantly

**Reproduction**

/!\ I have no fucking clue HOW to reproduce it PRECISELY but here is my best guess

1. be on fire
2. run into entity (in this case it was a rat servant, perhaps multiple)
3. ???
4. get set ablaze like the sun, turned into ash INSTANTLY

**Additional context**

It could be the new way fire damage is calculated, uncertain
I strongly advise watching the replay of the round considering (near the end of the round when dragon was at HOP) how BIG and gamebreaking an insta gib can be for the game

If any more context is needed or precision do not hesitate

**Comment by lzk228** [comment]
providing a video (there was like 6-9 rat servants in one tile)
https://github.com/space-wizards/space-station-14/assets/124214523/db3a5dd3-935d-43f1-ae2e-e218b76823db

**Comment by QuietlyWhisper** [comment]
I touched fire damage and scaling a while ago but I have no fucking clue how my changes could have caused that, maybe @deltanedas knows because they touched fire transfer

You need 1500 heat to ash, so even if it wasnt a round removal it would still be a shit ton of damage

**Comment by deltanedas** [comment]
maybe the rat mass is negative?????

**Comment by Dutch-VanDerLinde** [comment]
Maybe try it with a different entity
