### ISSUE TITLE
Many Humanoid Ghost Roles don't have a random appearance

### ISSUE THREAD

**Issue by Vermidia** [space-wizards/space-station-14#27991]
## Description

Mostly affecting ERT and all the new shuttle roles (which has made this more obvious), they all spawn with the same skin color with no randomization applied.

**Reproduction**

Spawn a bunch of ERT/Lost Shuttle Ghost roles, see how they have the same color.

**Screenshots**

![NoRandom](https://github.com/space-wizards/space-station-14/assets/32827189/e1e18b8e-b46b-45dd-80d9-6caf4e3c3509)

**Additional context**

**Comment by ShadowCommander** [comment]
To fix this, make sure that the YAML of each ghost role has the `RandomHumanoidAppearance` component.
