### ISSUE TITLE
nearsighted trait makes you immune to flashes.

### ISSUE THREAD

**Issue by Redfire1331** [space-wizards/space-station-14#27992]
## Description

having the nearsighted trait makes you immune to flashes
**Reproduction**

have the nearsighted trait, and get flashed
**Screenshots**

**Additional context**

**Comment by slarticodefast** [comment]
The short-sighted trait adds the PermanentBlindnessComponent to the player, which cancels the FlashAttemptEvent. I am currently reworking the flash system to use the status effect system and can fix this bug while I'm at it. Should be a single line fix to check the Blindness integer in the component.
