### ISSUE TITLE
Attempting to steal a hot potato out of someone's hand produces a system/coding message.

### ISSUE THREAD

**Issue by JIPDawg** [space-wizards/space-station-14#27993]
## Description
I attempted to steal the "hot potato" out of someones hand's while they were crit. Attempting to do so gave what I would call a system code message? Something that'd you'd see in console. Uncertain if person being in crit is relevant or not.

**Reproduction**
Person has hot potato and is stuck on them(may or may not have to be critted). Strip them and attempt to take/steal hot potato. See weird system message.

**Comment by beck-thompson** [comment]
Replicated:

![image](https://github.com/space-wizards/space-station-14/assets/107373427/6817942c-ebfb-4801-bc7e-b56565fe25a6)

I'll try to fix this!

**Comment by Tayrtahn** [comment]
@beck-thompson Should be a pretty simple one - that's an Entity<HandsComponent> getting printed, when it should be using the EntityUid. Should be able to just do .Owner on the Entity.

**Comment by Tayrtahn** [comment]
Ah, I didn't realize it wasn't using Identity before. Yeah, your fix is the right way to do it.

**Comment by beck-thompson** [comment]
OK sounds good! Thanks for the help ❤️
