### ISSUE TITLE
Cant drag monkeys in makeshift cuffs

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#28006]
## Description
Title says it all pretty much when attempting to drag a monkey in makeshift cuffs it just drops of the hand indication every split second.

**Reproduction**
- Cuff a monkey in makeshift cuffs.
- Try and drag em.

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/47093363/12860103-e792-42b9-b2be-99fa8a9c2871)

**Additional context**
As ghost or player/humanoid.

**Comment by Titian3** [comment]
Might be the AI movement, not so much the cuffs, same happening with willow.

**Comment by Kukutis96513** [comment]
Monkeys that aren't holding anything can be pulled until they pick up something, i'm not sure why its like that though.

Maybe because of the monkey being cuffed, it thinks it's hands are occupied which lets it resist out of pulls? unsure.

**Comment by UbaserB** [comment]
cursed

**Comment by osjarw** [comment]
This PR is related to some extent, but I believe it still lets the monkey unpull when attacked. 
#30066
