### ISSUE TITLE
Ninja criminal records sabotage does not add the icons

### ISSUE THREAD

**Issue by XxSWAG-MASTER-OVERLORDxX** [space-wizards/space-station-14#28013]
## Description
While it does make everyone wanted inside the console, It does not add the wanted icon to people when wearing sechuds.

**Reproduction**
1. As ninja hack the criminals records computer
2. get a sechud
3. look at the person that should be wanted not have the icon

**Comment by Tayrtahn** [comment]
Looks like this is addressed by #28021
