### ISSUE TITLE
You can play instruments when you ghost

### ISSUE THREAD

**Issue by notquitehadouken** [space-wizards/space-station-14#28018]
## Description

If you ghost while playing an instrument, you don't stop

**Reproduction**

1. Play any instrument
2. Ghost
3. You do not stop playing

**Screenshots**

**Additional context**

**Comment by Tayrtahn** [comment]
Related to #24766 and #10761

**Comment by notquitehadouken** [comment]
staler than that bread i left in my pantry 6 years ago
