### ISSUE TITLE
Singularity bugs

### ISSUE THREAD

**Issue by YellowKingThe** [space-wizards/space-station-14#2802]
Singularity effects ghosts, objects through walls, and other things it probably shouldn't

**Comment by daniel-cr** [comment]
If you don't fight against the pull as a ghost you kind of rotate around it. Sometimes it doesn't work and throw you far, this can probably be tweaked. In regular SS13 it affects objects through walls too

**Comment by SweptWasTaken** [comment]
Closing due to ambiguity.
