### ISSUE TITLE
Linking devices in mapping is broken

### ISSUE THREAD

**Issue by IProduceWidgets** [space-wizards/space-station-14#28037]
## Description

Devices refuse to link due to access issues in mapping mode. This prevents many linked devices from being mapped in a working state including external airlock setups, buttons, remote signalers, recyclers, and more.

**Reproduction**

Enter mapping mode, attempt to link an airlock to a signal button, despair.

**Screenshots**

**Additional context**

**Comment by lzk228** [comment]
dupe #26802
