### ISSUE TITLE
Fuel ignites

### ISSUE THREAD

**Issue by Pok27** [space-wizards/space-station-14#28035]
## Description

https://github.com/space-wizards/space-station-14/assets/113675512/b5e9f30c-8f8e-43e1-9227-3742660053b5

**Reproduction**

1. Apply some fuel to yourself
2. You are on fire

**Additional context**

A while back you had to set fire to a man doused in fuel, now the fuel is setting fire to itself. I don't think this was planned.

**Comment by deltanedas** [comment]
dupe of other issue

**Comment by Pok27** [comment]
That's right, I didn't notice
