### ISSUE TITLE
Ninjas can have the objective to bomb arrivals on Core station

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#28043]
## Description
Ninjas can get the objective to plant their spider bomb at arrivals. This bomb can only be planted in the location it calls for in your objective. Bombing arrivals is aganist our rules and should be blacklisted from the possible locations to roll for bombing.

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/106507028/7bbc0cd7-687f-4c99-869d-bccb2622a0fe)

**Comment by UbaserB** [comment]
I thought this was fixed ages ago

**Comment by Kayek14** [comment]
Just had a round today on Core where a ninja was able to place the bomb on the upper left section of arrivals. Perhaps its a mapping issue? 
![image](https://github.com/space-wizards/space-station-14/assets/106507028/7c4ecb4b-ed4b-4c17-8697-c86f77c6ddc6)

**Comment by rosieposieeee** [comment]
things like this really need to show a radius for mappers

or we could just add zoooooooones

**Comment by lzk228** [comment]
maybe it would be better to like remove arrivals bombing at all?

**Comment by deltanedas** [comment]
that would require mapping, and this is a mapping issue to begin with

**Comment by UbaserB** [comment]
> Just had a round today on Core where a ninja was able to place the bomb on the left section of arrivals. Perhaps its a mapping issue?

I will check the map to see if its still there, but from memory i removed it.

**Comment by Kadeo64** [comment]
i thought there was already a discussion about this months ago why is this still an issue

**Comment by UbaserB** [comment]
> i thought there was already a discussion about this months ago why is this still an issue

there was, which is why im confused

**Comment by Kadeo64** [comment]
> > i thought there was already a discussion about this months ago why is this still an issue
> 
> there was, which is why im confused

i'm going to chalk it up to a miscommunication with the 'new' admins
i remember there was a round like this where a ninja bombed arrivals on saltern and got away with it because it was their objective and there was a discord thing about it, admin team clarified that yeah it's an intentional game mechanic or whatever
new admin team wasn't notified of this edge case leading to this 

should probably just be removed to prevent this shit from happening every two months

**Comment by Kayek14** [comment]
>
> should probably just be removed to prevent this shit from happening every two months

Yes, we should have arrivals blacklisted from the possible areas rolled for the spiderbomb objective pool.

**Comment by deltanedas** [comment]
just dont make an arrivals bombing target

**Comment by UbaserB** [comment]
I just checked arrivals, there is no ninja bombing point. It should be completely fine.
