### ISSUE TITLE
Lizard Tail Pull Slowdown non-existant

### ISSUE THREAD

**Issue by TurboTrackerss14** [space-wizards/space-station-14#28058]
## Description
Lizard Tail pull doesn't "pull" (haha) the movespeed modifiers from inhand holding.

**Reproduction**
>be lizard
>hold Emergency EVA suit in hand
>snail crawl
>hold Emergency EVA suit in tail
>100% movespeed.

**Screenshots**
n/a

**Additional context**
n/a

**Comment by LankLTE** [comment]
Is this not an issue with pulling in general?

**Comment by TurboTrackerss14** [comment]
Reconfirmed my suspicions on Human Urist. 
Yes its Pulling in general 💀 
god damn it.
