### ISSUE TITLE
Can't interact with mirrors on walls

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#28068]
## Description

Looks like a collision issue.

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/134914314/c6306faf-cc9e-49d9-854c-6783a6706e86)

**Comment by IamVelcroboy** [comment]
They are directional. Are you sure they're oriented the right way?

**Comment by UbaserB** [comment]
nope but either way it needs to be fixed

**Comment by IamVelcroboy** [comment]
I'm like 82.3% sure they're facing the wrong way.

**Comment by UbaserB** [comment]
yeah i messaged repo about it and he gave me scizzors
