### ISSUE TITLE
Musician Not Spawning in Musicians Room on Core

### ISSUE THREAD

**Issue by Cojoke-dot** [space-wizards/space-station-14#28067]
## Description
As a musician, you spawn in the middle of the bar instead of the musician's room in shifts on the Core map

**Reproduction**

1. Spawn in as Musician on core
**Screenshots**

The video is of me spawning in the bar

https://github.com/space-wizards/space-station-14/assets/83733158/344d2309-ad9f-40da-ac25-34e8880e19a8

**Comment by UbaserB** [comment]
yes, that is intended. You're supposed to be able to spawn in your room and optionally near the place where music plays
