### ISSUE TITLE
Chat message spams when trying to use the power monitoring computer while someone else is using it.

### ISSUE THREAD

**Issue by JIPDawg** [space-wizards/space-station-14#28066]
## Description
If someone is actively using the power monitoring computer and you attempt to use the same console it spams the message. Similar to https://github.com/space-wizards/space-station-14/issues/26853 but the sound does not spam.

**Reproduction**
1. Have someone use the Power monitor console.
2. Try to use it while they are on it.

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/51352440/a2c6144e-81db-4df5-8564-9021278a885c)

**Comment by deltanedas** [comment]
needs popupclient

**Comment by JIPDawg** [comment]
Sorry are you asking me for something?

**Comment by beck-thompson** [comment]
Nah delta is just saying how to fix it! Its using the wrong poup command and poupclient probably will fix it 👍

**Comment by Tayrtahn** [comment]
Here, specifically, if anyone wants to do a quick fix: https://github.com/space-wizards/space-station-14/blob/master/Content.Shared%2FUserInterface%2FActivatableUISystem.cs#L218
