### ISSUE TITLE
Wall girders have no collision.

### ISSUE THREAD

**Issue by Jan-Blasiak** [space-wizards/space-station-14#2808]
Wall girders have no collision and don't stop people from being sucked into space on decompression.

**Comment by Zumorica** [comment]
Wall girders do have collisions, this is a greater problem.

**Comment by SweptWasTaken** [comment]
Closing this as this is actually an issue with atmos that's known, not something to do with collision.

**Comment by Zumorica** [comment]
(technically an issue with physics but-)
