### ISSUE TITLE
Dark green jumpskirt looks too similar to green

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#28092]
## Description

Make dark green darker, or light green lighter.

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/134914314/412e7e0d-c128-456e-a53e-a95fb9975ee8)

**Comment by Ghagliiarghii** [comment]
How do we feel about #427311?

![image](https://github.com/space-wizards/space-station-14/assets/68826635/54580ab7-8ab7-4b81-a2bf-83b79b92ac8c)

**Comment by MACMAN2003** [comment]
i like 427311, could be a bit more saturated though

**Comment by Ghagliiarghii** [comment]
![image](https://github.com/space-wizards/space-station-14/assets/68826635/d30a08d3-33f4-4a5f-8ff1-452b9a15dce7)
The light brown and brown look kinda close as well

**Comment by Flareguy** [comment]
> How do we feel about #427311?
> 
> ![image](https://private-user-images.githubusercontent.com/68826635/331756782-54580ab7-8ab7-4b81-a2bf-83b79b92ac8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5OTYyMTMsIm5iZiI6MTcxNTk5NTkxMywicGF0aCI6Ii82ODgyNjYzNS8zMzE3NTY3ODItNTQ1ODBhYjctOGFiNy00YjgxLWEyYmYtODNiNzliOTJhYzhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDAxMzE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmYzk0MDNmOWFjZWFkYjYzMzMzMjhiODNiMDY5NTM2OWM2M2M4MTg5MTU1OGJhYWJkMzdmNDgxOGZmM2Q5MjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qjixqoP2SNIbCYDp5JGlFoHpWk0yvgxXT1dUT4JX2Lg)
> 
> (centcom stuff for comparison, this is a bit darker than most of the centcom stuff, a nice foresty green)

I'd suggest making this a lot more saturated. The contrast on this color compared to the floor tiles isn't great.

I haven't tested this ingame or compared it to light green, but #166600 is moreso what I'd envision for this.

**Comment by Ghagliiarghii** [comment]
156906:
![image](https://github.com/space-wizards/space-station-14/assets/68826635/b0a28ccb-a73e-4d5f-bcec-d046de674be5)

> I haven't tested this ingame or compared it to light green, but #166600 is moreso what I'd envision for this.

16660:
![image](https://github.com/space-wizards/space-station-14/assets/68826635/d340dd65-5cdc-4e41-a98a-e7e6a511b6fc)

**Comment by MACMAN2003** [comment]
as a green enjoyer i like seeing all these green

**Comment by Ghagliiarghii** [comment]
> as a green enjoyer i like seeing all these green

I enjoy a green as well I just feel I'm too unskilled in the ways of color theory to appreciate a 1/255 difference in an R a G or a B value right now

**Comment by Ghagliiarghii** [comment]
![image](https://github.com/space-wizards/space-station-14/assets/68826635/ebd32c91-02d8-411a-947e-fed6d18da44b)
#166600 on grass

**Comment by UbaserB** [comment]
also you will probably need to edit the gloves and shoes to match if you havent already

**Comment by UbaserB** [comment]
resolved.
