### ISSUE TITLE
role_timers cvar does not account for antags and loadout items

### ISSUE THREAD

**Issue by Killerqu00** [space-wizards/space-station-14#28091]
## Description
nukies and items like cigar cases etc. still require playtime

**Reproduction**
1. Set cvar game.role_timers to true
2. nukies still locked
3. cigar case still locked

**Screenshots**

**Additional context**
these probably could be separate cvars, at least for loadout items

**Comment by lzk228** [comment]
dupe #27169 and im pretty sure there is already an issue about antags

**Comment by lzk228** [comment]
about antags seems to be fixed a long time ago #21404

**Comment by Killerqu00** [comment]
> dupe #27169 and im pretty sure there is already an issue about antags

Should it be role_timers or a separate cvar?
