### ISSUE TITLE
Thief Toolbox Desc Still Mentions A Syndie Crew Monitor

### ISSUE THREAD

**Issue by Kezu02** [space-wizards/space-station-14#28102]
## Description

Title. Crew monitor got taken out a while back but the description wasn't changed.

**Comment by K-Dynamic** [comment]
Will be fixed by #27771 after feature freeze ends

**Comment by UbaserB** [comment]
> Will be fixed by #27771 after feature freeze ends

@K-Dynamic cant you split the rebalance and description clean-up, so that the clean-up gets merged during the freeze and you can do the latter half later

**Comment by K-Dynamic** [comment]
> @K-Dynamic cant you split the rebalance and description clean-up, so that the clean-up gets merged during the freeze and you can do the latter half later

Not really because the description changes go beyond just removing reference to crew monitor

It's just yaml changes anyway - I'll be free in like 4 hours to do it, maybe someone else will remove the reference before then

**Comment by Dutch-VanDerLinde** [comment]
fixed, close pls

**Comment by Tayrtahn** [comment]
Fixed by #27771
