### ISSUE TITLE
Bandito makes monkey sounds

### ISSUE THREAD

**Issue by Everturning** [space-wizards/space-station-14#28105]
## Description
title. prolly just placeholder, but still a bit weird

**Reproduction**
>pet bandito
>ook ook
**Screenshots**

**Additional context**

**Comment by taurie** [comment]
Although it sounds like a monkey, the noise Bandito makes is in fact, a ferret's call :)
 See https://youtu.be/th3_zv-5UVQ?si=xM2k2eVrcNKnYYUH&t=205

**Comment by EmoGarbage404** [comment]
hooray for ferrets

**Comment by FairlySadPanda** [comment]
Peak scrungle content
