### ISSUE TITLE
Disposals chute can store structures (infinite storage + Entity crushing)

### ISSUE THREAD

**Issue by TurboTrackerss14** [space-wizards/space-station-14#28116]
## Description
Disposal chutes have "recently" got the ability to have basically anything stored inside them. 
Leading to them becoming Bluespace Backpacks 2.0. 
Originally this wasn't to much of an issue but it seems we have reached a point where someone will spend half the shift collecting monsterous sized items and putting them into disposals. 
Only for them to be all released on the same tile, and immediately fly in all directions trying to fill the space. 

**Reproduction**
Pull disposals chute
put anything with a hitbox into it
repeat until prepared
Eject contents
Pic related

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/130304754/78a3041a-a16d-4e5b-abf0-3be130b8f6ef)

**Additional context**

**Comment by MilenVolf** [comment]
I tested and found out that it's realated to #27487

**Comment by metalgearsloth** [comment]
https://github.com/space-wizards/space-station-14/issues/26547

**Comment by metalgearsloth** [comment]
> I tested and found out that it's realated to #27487

It's not.

**Comment by MilenVolf** [comment]
> > I tested and found out that it's realated to #27487
> 
> It's not.

My bad, was not aware that it's because of the pullController problem
