### ISSUE TITLE
Changing character description does not light up save button.

### ISSUE THREAD

**Issue by pigeonpeas** [space-wizards/space-station-14#28112]
## Description
If you edit your character's description, then go to hit the save button, you'll find you just.. can't.

**Reproduction**
1. join mander
2. go to edit character description
3. cry when you realize you can't.

**Screenshots**

![death](https://github.com/space-wizards/space-station-14/assets/147350443/468dad41-39c6-42b0-86ab-97e6e2c5a79c)

**Comment by UbaserB** [comment]
Replicated, i was gonna post this myself but i forgor

**Comment by lzk228** [comment]
dupe #28089

**Comment by UbaserB** [comment]
> dupe #28089

the save button is lit, but when you click it it doesnt do the saving. this issue and that issue are seperate, and considering the nature of that one i will be closing it

**Comment by pigeonpeas** [comment]
oops! sorry
