### ISSUE TITLE
FTLing is buggy sometimes

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#28129]
## Description

Watched in real-time someone (that i assume) was FTLing to the ATS, merge inside of it.

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/134914314/9cbda1fa-8e7c-40bb-9b3c-d34da4dfc87b)

**Comment by liltenhead** [comment]
You can't park there

**Comment by metalgearsloth** [comment]
dupes
