### ISSUE TITLE
Map "Reach": Atmos non-fuctional

### ISSUE THREAD

**Issue by luckyshotpictures** [space-wizards/space-station-14#28135]
## Description
Atmos is non-functional due to missing vents in the miners itself. Replacing the ports with vents fixes the problem.

**Reproduction**
Load the map.

**Screenshots**
![Screenshot_589](https://github.com/space-wizards/space-station-14/assets/126210746/02f8ca57-369f-4e93-a815-559462d83292)

**Additional context**

**Comment by Bibbly10** [comment]
this was fixed months ago in #26224
![image](https://github.com/space-wizards/space-station-14/assets/18370339/381ac90d-9ab3-4291-9ece-03003c723123)
(screenshot of map as it is currently)
