### ISSUE TITLE
Setting the game.lobbyduration cvar doesn't seem to work

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#2816]
I've tried setting it locally and on live but it doesn't seem to actually affect lobby duration unless I'm dumb.

**Comment by DrSmugleaf** [comment]
It only works if changed before the lobby countdown starts.

**Comment by metalgearsloth** [comment]
I tried changing it in a round but it didn't apply for the round after but I'll suss it out again.

**Comment by moonheart08** [comment]
Long since fixed.
