### ISSUE TITLE
Arivals telecomms is vulnerable to shitters.

### ISSUE THREAD

**Issue by Willzile1** [space-wizards/space-station-14#28163]
## Description

The AA Telecomms server is not locked, at all. 
**Reproduction**

Late join or load the arrivals map. The maints door in arrivals is unlocked. Smash the Telecoms server. get AA radio.
**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/69917862/058e5c80-958a-4752-8250-c44f4dc1c43e)

**Additional context**

Not a big issue, just worried about people being shitters and powergaming with AA radio.

**Comment by TurboTrackerss14** [comment]
Can confirm, this is annoyingly an admin workload issue. 
Periodically having to check for 
1) people stealing an/all encryption keys 
2) people stealing the entire tcomm server as a "spare" 

Having it be much more locked down or even off the terminal entirely would be much more preferable
also Why is there even a requirement to have it in the firstplace? it doesn't communicate with station tcomms so its just dead weight right?
