### ISSUE TITLE
hypodart's don't inject contents on people that have armor

### ISSUE THREAD

**Issue by Dutch-VanDerLinde** [space-wizards/space-station-14#28171]
throw a hypodart at a guy with armor/hardsuit/wintercoat, doesn't inject contents
this isn't how it worked before

**Comment by Dutch-VanDerLinde** [comment]
> intended :trollface:

normal darts yes, hypodarts no

**Comment by Tayrtahn** [comment]
Simple to change. Just set `pierceArmor` to true on the `SolutionInjectOnEmbed` of hypodart.

**Comment by Dutch-VanDerLinde** [comment]
> Simple to change. Just set `pierceArmor` to true on the `SolutionInjectOnEmbed` of hypodart.

Pretty sure it's because normal darts have a outerclothing block slot and since hypodart inherits from the normal dart it doesn't pierce armor, the block flag being set to none was removed in the inject on embed refactor

**Comment by Tayrtahn** [comment]
Ah, you're right. I removed the YAML setting it to NONE since I made it the default value, but I didn't take inheritance into consideration.
