### ISSUE TITLE
Unanchored microwaves have no collision

### ISSUE THREAD

**Issue by thebadman4662** [space-wizards/space-station-14#28182]
## Description
They pretty much behave like grav-fucked artifacts - fly thru walls and so on.

**Reproduction**
1. Unanchor microwave.
2. Throw drag it into wall.
3. Microwave is now in wall, if you let go of it, chances are you will need to take down the wall to be able to grab it again.

**Comment by lzk228** [comment]
pretty sure caused by #28026
ill try to fix it later if i can

**Comment by lzk228** [comment]
looked up on this and i think there should be collision group that would passable for items and tables but not passable for mobs

**Comment by ShadowCommander** [comment]
TabletopMachineLayer is probably what you're looking for.

**Comment by lzk228** [comment]
> TabletopMachineLayer is probably what you're looking for.

no, it has HighImpassable and ItemMask and ThrownItem also has HighImpassable

**Comment by ShadowCommander** [comment]
Looking at the microwave YAML, it seems like someone set hard to false, which is what's causing this.

**Comment by lzk228** [comment]
> Looking at the microwave YAML, it seems like someone set hard to false, which is what's causing this.

yes, `hard: false` should be removed and we need to set proper layer for tabletop items that i described few comments earlier
