### ISSUE TITLE
Cannot edit some jobs loadouts seemingly arbitrarily specifically for my character

### ISSUE THREAD

**Issue by LordEclipse** [space-wizards/space-station-14#28185]
## Description
I have zero clue as to the result of why this happens, and it occurs even when I delete my character and import him, but if I were to just delete and remake the character this bug wouldn't get fixed. But as I attempt to change SOME loadouts, no window is opened, nothing happens aside from the button turning green. Stranger still is that I used to be able to edit all loadouts, so this is new.

**Reproduction**
????

**Screenshots**

https://github.com/space-wizards/space-station-14/assets/106132477/6e9265bb-0e4e-4e73-b4e4-dc00863936a3

**Additional context**
This is a file of my character

[Drew Morgan.zip](https://github.com/space-wizards/space-station-14/files/15392837/Drew.Morgan.zip)

**Comment by lzk228** [comment]
dupe #28137
