### ISSUE TITLE
Ctrl-selection tile placing crash client if cancelled

### ISSUE THREAD

**Issue by TheShuEd** [space-wizards/space-station-14#28201]
**Media**

https://github.com/space-wizards/space-station-14/assets/96445749/c1124ea5-ef76-4960-ae4e-c057ce4f4eba

![image](https://github.com/space-wizards/space-station-14/assets/96445749/73a6b638-9050-4f85-92c5-0642de3f06c9)

**Reproduction**
1) Open Tile menu
2) Select any tile
3) Try Place tile with ctrl, select big square and cancel it
4) Sometimes it crash the client

**Comment by VasilisThePikachu** [comment]
Post error please

**Comment by TheShuEd** [comment]
![image](https://github.com/space-wizards/space-station-14/assets/96445749/52dea12f-bff9-40a2-9a78-48314b0ecb46)

**Comment by TheShuEd** [comment]
![image](https://github.com/space-wizards/space-station-14/assets/96445749/00ef90dc-bd16-41e8-9e16-ea72e6260518)

also crashing decal RMB removing
