### ISSUE TITLE
Loneops uses your original job and role information

### ISSUE THREAD

**Issue by Everturning** [space-wizards/space-station-14#28214]
## Description
if you become a loneop, you will retain almost EVERYTHING from your past life. this includes your appearance, job, and ghost warp job

**Reproduction**

> be job with job-specific syndie items (syndie or non-syndie)
>die
>become loneop
>retain your appearance
>retain your job specific syndie items (i was RD, so i got science uplink)

**Screenshots**

**Additional context**

**Comment by Everturning** [comment]
titled it wrong :agony:

**Comment by deltanedas** [comment]
antag selection is reusing mind i think instead of creating a new one with GhostRoleAntagSpawner

**Comment by UbaserB** [comment]
Have confirmed this, you even see your old antag menu and objectives if you open it up
