### ISSUE TITLE
Remove policy that violates privacy

### ISSUE THREAD

**Issue by incrediblyimpressiveusername** [space-wizards/space-station-14#28215]
## Description
It's bad enough that one needs to create a whole separate account with Space Wizards Federation, but when creating that account it demands your E-mail address without any legitimate reason, threatening: 'Do not sign up with "temporary" or "burner" email addresses. Your account may be banned if you do.' What bizarre and evil privacy violation. And there's no good reason for it either. If you're going to force people to sign up, then at least just let them use temp mail.

**Reproduction**
https://central.spacestation14.io/web/Identity/Account/Register

**Comment by Emisse** [comment]
raiders use temp mail to create accounts en masse is why. if you dont want to sign up with an email just dont play

**Comment by ShadowCommander** [comment]
We have plans to add auto steam account creation in the future, but until then it's very hard to stop raider/spammers from signing up without also banning burner emails.

**Comment by Emisse** [comment]
are you a 17th century pirate
