### ISSUE TITLE
Rubberbanding

### ISSUE THREAD

**Issue by Reznc** [space-wizards/space-station-14#2822]
I find myself getting rubberbanded about the map every single time I take a step.

**Comment by metalgearsloth** [comment]
We're gonna need more details to diagnose this. If you have a video that'd help otherwise you'll need to be very specific in what's going on.

**Comment by Reznc** [comment]
To be a little more specific, I find myself walking down a hallway and then my model will be suddenly shot forwards when in actuality I haven't moved at all. It seems to be happening with every step I'll take, my model will appear on the map either further in front or farther behind where they're actually supposed to be.

**Comment by metalgearsloth** [comment]
Still need more info my dude:
* Is this locally or on live
* What's your framerate
* What's your network conditions like
If on live:
* which server
* was it after a fresh round restart

**Comment by Reznc** [comment]
Live (which I assume means server)
FPS: Uncertain
Network Conditions: Solid
Server: Wizard's Den [US West]
After fresh round restart: Yes, even after multiple restarts.

**Comment by SweptWasTaken** [comment]
Closing because this appears to be a network issue.
