### ISSUE TITLE
Connecting to any server yields response code 401

### ISSUE THREAD

**Issue by notquitehadouken** [space-wizards/space-station-14#28229]
## Description

When I try to connect to any server, I can't connect because of a 401.

**Reproduction**

1. Connect to any server
2. Response code 401

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/45953835/5850d103-9be9-4689-bf11-78d6de5624d7)

**Additional context**

The server list loads just fine, and I was able to connect earlier today, I don't know what has changed since then.

**Comment by Randomplayer2or3** [comment]
Auth servers are down I think

**Comment by metalgearsloth** [comment]
There was an announcement so.

**Comment by lzk228** [comment]
updating the launcher helped me
