### ISSUE TITLE
mop wield gets wierd if you are pulling something

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#28233]
## Description
If you wield a mop while pulling something, you still wield the mop dispite your other hand being full. Additionally, you can put the mop in your bag in this wielded state. You are then able to pull it back out wielded.

**Reproduction**
Drag something
hold mop in other hand
wield mop
put mop in bag
pull mop back out

## Video

https://github.com/space-wizards/space-station-14/assets/106507028/2733c590-a0b3-418f-87cd-1c1128ab0fe6

**Comment by Lamrr** [comment]
I can reproduce this with the steps above, additional things to note:

- Applies to all wield able items (notably, guns)
- While the items come out of the bag wielded, their sprites use the unwielded state (pressing Z still unwields them)
- Putting items down and picking them back up also works the same as putting them in your bag i.e. they will be picked up wielded still

**Comment by Hrosts** [comment]
Reproduced it today as well.

With guns you still get the accuracy penalty of an unwielded gun, despite the sprite changing.

With melee you get the damage of a wielded weapon, though.
