### ISSUE TITLE
Gun cycling mispredict when wielding

### ISSUE THREAD

**Issue by Errant-4** [space-wizards/space-station-14#28246]
## Description
Wieldable firearms mispredict a bolt close/cycle action when Z is pressed

**Reproduction**
Load Dev
Pick up the AKMS and press Z
Gun gets wielded, but also plays a bolt close sound
Gun did not actually bolt, it jumps back to open
(If Unwielding is disabled, as on #28002,  subsequent presses of Z will cycle the gun correctly)

**Comment by WarMechanic** [comment]
there is a new misprediction issue
it wasn't the case when i first implemented it, but now when you wield a gun, it will mispredict cycling as you wield
i will need to investigate other changes to guns to find the cause
