### ISSUE TITLE
Popups shouldn't show if the entity is occluded

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#2825]
Not sure if it worked and was broken like do_after but currently it's possible to see popups through walls which is less than ideal.

**Comment by EmoGarbage404** [comment]
This is still broken.

**Comment by mirrorcult** [comment]
death

**Comment by Willhelm53** [comment]
Still broken, I saw this in-game with anchored/unanchored messages on the other side of walls.
