### ISSUE TITLE
Epipens try to inject disposal units

### ISSUE THREAD

**Issue by Mith-randalf** [space-wizards/space-station-14#28259]
## Description
You cant put epipens in a disposal unit; I'm assuming its trying to inject it. To get it inside you gotta throw it until RNG puts it in which is ANNOYING.

**Reproduction**
1. Try to put emergency injector pen in disposal bin
2. Do not succeed

**Screenshots**

**Additional context**

**Comment by Sirionaut** [comment]
Until this is fixed, a workaround tip: you can right-click the disposals unit and select insert item for things that don't want to go in with left click.
