### ISSUE TITLE
Forcebuckling needs a do-after

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#28257]
## Description

You can buckle people midcombat to throw them off and prevent them from moving and get easy hits
**Reproduction**

**Screenshots**

**Additional context**

**Comment by ninruB** [comment]
This takes considerable skill and shouldn't be changed imo. If you're fighting near a chair and someone rapidly buckles you to the chair mid-fight while both of you are moving and trading damage I think it's pretty fair they get some free hits off for doing that.

**Comment by Mith-randalf** [comment]
+1 to this being a fun mechanic that adds a little changeup option to combat that a doafter would remove. It's kind of a fiddly input as-is, I defo think it should stay as-is.

**Comment by SlamBamActionman** [comment]
Is it somewhat skillful? Sure. I can agree with that.

Doesn't mean that it isn't stupid though. Not only doesn't it make sense in-universe, but it's also a fairly capable movement stun which has the counterplay of "don't stand next to chairs" which is a ludicrous ask.

Want fun combat mechanics? Make fun _combat_ mechanics.

**Comment by UbaserB** [comment]
IMO it should only be like 2 seconds though

**Comment by ninruB** [comment]
"Don't stand next to chairs" while silly and ludicrous isn't actually too hard considering you or your opponent only have to be a tile and a half away from it or so to not get chaired while chairs aren't an ever present entity mapped into every single corner of the station.

While I agree that this most likely isn't intended and that proper combat mechanics should be implemented instead, I don't see a reason to not keep this until we get proper mechanics.

**Comment by Killerqu00** [comment]
implemented

**Comment by MilenVolf** [comment]
Feature implemented. This issue should be closed
