### ISSUE TITLE
Hamlet can do the wipe brain action on positronic brains

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#28263]
**Reproduction**
Be hamlet
find active positronic brain
right click
click on `wipe brain`

**Additional context**
not sure if all  player controlled mobs/animals can do this or just hamlet.

**Comment by B1essedknight** [comment]
As a zombified morticia I was able to also wipe a posi-brain (they asked me to kill them and it was after end of round) 
So good chance player controlled mobs can just wipe poor borgo brains.

**Comment by deltanedas** [comment]
should probably use complex interaction with interaction rework

**Comment by slarticodefast** [comment]
Fixed by #30149
