### ISSUE TITLE
Items in belt/backpack/jacket are refusing to comply.

### ISSUE THREAD

**Issue by thebadman4662** [space-wizards/space-station-14#28277]
## Description
There is something veeeery weird going on with storage, you can't properly inspect items you have, you can't interact with them sometimes, you can't open nested storage...

**Reproduction**
A)
1. Try to open your survival box in your backpack

B)
1. Put your sec pistol in backpack
2. Try to eject magazine from your mk58

**Screenshots**
![obraz](https://github.com/space-wizards/space-station-14/assets/152504929/993f1e07-80e1-4969-8f51-9abf787ba25d)

**Comment by slarticodefast** [comment]
To add to this, you can no longer see the stack size of items upon inspecting if they are in your bag.
