### ISSUE TITLE
Medical PDAs can no longer scan people

### ISSUE THREAD

**Issue by XxSWAG-MASTER-OVERLORDxX** [space-wizards/space-station-14#28275]
## Description
All PDAs that were able to give a readout of peoples health state, no longer work.
It still makes the sound but no Hud comes up with the damage numbers
the one exception to this is the Health analyzer.
**Reproduction**
Spawn as Med, Nuclear Agent or Admin, and attempt to scan a living creature

**Screenshots**
All items affected as pictured below
![image](https://github.com/space-wizards/space-station-14/assets/151447893/40392dae-ae2c-41bf-a07f-70efe7b37380)

**Comment by TsjipTsjip** [comment]
Discord thread: https://discord.com/channels/310555209753690112/1243898349787287563

Potentially useful note from discord: The health scanner UI does appear to work if you have a health scanner UI already open from a regular health analyzer.

**Comment by slarticodefast** [comment]
Similar thing happening with the gas analyzer. If you use it on an entity, it will scan and then refuse to open the window. If you instead use it on the environment, it will work. When keeping the window open, other objects can be scanned without problem.

**Comment by Randomplayer2or3** [comment]
Apparently you have to open the pda ui before you can scan now
