### ISSUE TITLE
darts box is a tardis with no whitelist

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#28271]
## Description
![07:45:28](https://github.com/space-wizards/space-station-14/assets/39013340/962dcc1e-ddd4-44a1-91cf-534297d7928f)

its bigger on the inside...

**Comment by Lamrr** [comment]
This is also a problem with;
- candle box (10x3 unwhitelisted!!)
- deathrattle implant box (6x4 unwhitelisted)

There are some other boxes that are bigger on the inside e.g. the lightbulb boxes but at least they are whitelisted.
