### ISSUE TITLE
Firelocks sometimes permanently have red lights

### ISSUE THREAD

**Issue by thebadman4662** [space-wizards/space-station-14#28276]
## Description
They also give you warning area is spaced if you try to close them, despite being literally open.

**Screenshots**
![obraz](https://github.com/space-wizards/space-station-14/assets/152504929/9fedaeff-b9f7-464f-af4e-8e1f5186a06c)

**Comment by nikthechampiongr** [comment]
Need reproduction steps if possible.

**Comment by thebadman4662** [comment]
> Need reproduction steps if possible.

I wish I would have them but there were like only 2 our of 100 firelocks that had it... And I did not bother to pry them entirely because I just wanted to see if they are bolted.

**Comment by Dutch-VanDerLinde** [comment]
> Need reproduction steps if possible.

seems like it randomly gets stuck on red lights when a firelock is in the "locked state" (one of the sides is spaced) and it becomes unlocked

**Comment by thebadman4662** [comment]
Did not see it happen in a while now I think? Guess ill close.
