### ISSUE TITLE
pAI's thoroughly suck (need more functionality)

### ISSUE THREAD

**Issue by PotatOverlord** [space-wizards/space-station-14#28286]
## Description

pAI's are currently just a satnav, MP3 player and a way for a pitiful ghost to alert binary to your death. They lack any fun gameplay barring you being paired with someone who deliberately goes out of their way to make your round enjoyable. Additionally, they can't even speak over common.

One idea, like #16709 suggests, is to give them the system from PD station. This also has the effect of letting some features that a future AI core might have being sneakily implemented.

**Comment by Clone0401** [comment]
a design doc for a pai expansion slot which you can insert any computer board into im pretty sure has been merged.
no idea if it's being currently worked on or if someone is planning on working on it after the freeze though
(also not sure how to link so)

**Comment by deltanedas** [comment]
yes its closed for feature freeze
