### ISSUE TITLE
antags to new players

### ISSUE THREAD

**Issue by GalaxyCad** [space-wizards/space-station-14#28289]
## Description
shocked this isnt reported yet being its been a big issue for a lot of people but new people are getting antags, for example. this perons who played 43 minutes is an operator for nukies....

**Reproduction**

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/168132390/33e08a36-ca76-445c-8164-b930b667ff08)
 
![image](https://github.com/space-wizards/space-station-14/assets/168132390/74829d3c-ce40-4ef0-a4c0-7a8ef0b74843)

**Additional context**
seriously shocked no one reported this yet....

**Comment by deepdarkdepths** [comment]
This has been reported already. 
#27425
