### ISSUE TITLE
cant use items on slime people AS AGHOST

### ISSUE THREAD

**Issue by XxSWAG-MASTER-OVERLORDxX** [space-wizards/space-station-14#28300]
## Description
As Aghost you can no longer use the health analyzer in the PDA to check their health or use any item on them as it puts it in their internal storage instead, strangely enough it works as intended as a normal player

**Reproduction**
1 Use any item on hurt slime
2 Be sad as the item in now in them

**Comment by Boaz1111** [comment]
Did you experience this just now on wizden?

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
Updated the Issue to better reflect whats going on
