### ISSUE TITLE
Nukies not getting operators.

### ISSUE THREAD

**Issue by thebadman4662** [space-wizards/space-station-14#28312]
## Description
Apparently loneops gamemode got added, poor nukies got outnumbered 40 to 1.

**Screenshots**
![obraz](https://github.com/space-wizards/space-station-14/assets/152504929/b75030f7-c7e9-42ae-8c2a-a96a3a5c3a10)

**Comment by deltanedas** [comment]
operative definition has no minimum so the game thinks its perfectly valid to have 2 v 78

**Comment by thebadman4662** [comment]
I thought operatives scaled to population, why game thinks 2v78 is okay just like 25v5?

**Comment by EmoGarbage404** [comment]
are you sure this is players not having the role enabled and not just the count for it being off

**Comment by EmoGarbage404** [comment]
> its technically possible only 20 people readied up but realistically its just people not opting in

would need the round number maybe it was just low startpop -> lots of latejoins but if this is a common occurrence its going to be hot ass to play nukie even if ghost roles get added in soon.

**Comment by thebadman4662** [comment]
> are you sure this is players not having the role enabled and not just the count for it being off

I have agent and commander enabled so thats at least one operator missing, surely we could find 1-2 mroe among other 77 crew.

**Comment by thebadman4662** [comment]
78 pop single tratior, looks like something is wrong with antags in general.
![obraz](https://github.com/space-wizards/space-station-14/assets/152504929/69b41da4-0beb-4cc7-867f-7b824176cff4)

**Comment by EmoGarbage404** [comment]
Oh I know what it is

**Comment by GroggleG** [comment]
Yeah seen this multiple times over even with Headrevs and II every antag is just generally smaller pop.
