### ISSUE TITLE
Marathon Station gas miners should be Large Station miners

### ISSUE THREAD

**Issue by TurboTrackerss14** [space-wizards/space-station-14#28326]
## Description
Large station should really have large gas miners, with pending pipestacking changes, setups are much more likely to be affected and Distro will likely be unable to keep up.

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/130304754/f6293746-92ed-4739-a707-4f2a40f815a4)
![image](https://github.com/space-wizards/space-station-14/assets/130304754/b5f735df-c82a-4745-8ac0-22415c13fe7a)

**Additional context**
Marathon is less in need of a largestation gasminer then meta https://github.com/space-wizards/space-station-14/issues/28325
However their similar station size would make this change comparable.

**Comment by MACMAN2003** [comment]
ohhhh this explains a lot of rounds where marathon's oxy prod isn't enough
