### ISSUE TITLE
Network tab missing in options

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#28337]
## Description
The networks tab is now missing.

**Reproduction**
open the game options ui from main menu

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/47093363/0c0ce758-29c6-4aa1-8b14-b9c44b39615c)

**Additional context**
I had all my PVS stuff set incredibly high to admin under lag, now the game is unplayable because I cant change them back down. 😩

**Comment by Lamrr** [comment]
The network tab was removed in #28231

For your current issue;
> if a user needs to change these settings they are free to modify their cvars manually via the clientconfig.toml file or via the cvar command.

**Comment by ShadowCommander** [comment]
1. Open the launcher.
2. Go to options.
3. Click open log directory.
4. Go up two folders.
5. Open the data folder.
6. Open client_config.toml in a text editor.
7. Change cvars there or remove them to reset to default.
