### ISSUE TITLE
Jaws of Life doafter continues when not held

### ISSUE THREAD

**Issue by SlamBamActionman** [space-wizards/space-station-14#28334]
## Description

Jaws of Life's doafter continues even if you put away the item after starting to use it, allowing you to break open doors without visibly holding the item.

The doafter should break if the Jaws is no longer in the user's hand.

**Reproduction**

1. Start opening a door with Jaws of Life
2. Put Jaws of Life in your backpack
3. Watch doafter bar continue despite not holding the Jaws

**Additional context**

Syndicate Jaws of Life obviously have this problem too.

**Comment by Lamrr** [comment]
Reproducible using either  jaws of life. Using a crowbar to pry a firelock or an unpowered door also has the same issue.

**Comment by lzk228** [comment]
its prying in general, and im pretty sure its a dupe

**Comment by Lamrr** [comment]
> its prying in general, and im pretty sure its a dupe

Not sure about that, prying while deconstructing for example, does not have this issue (the doafter cancels if you put the crowbar into your bag). In that regard, it might be related to #27745
