### ISSUE TITLE
Interdyne packets are half-filled

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#28336]
## Description

I forgot to fix it when i made the PR changing how many cigs are in each packet by default.

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/134914314/0abc5f3f-34d4-4772-b5f9-633937724026)

**Comment by KonstantinAngelov** [comment]
okay,if no one has done anything about this im gonna take a look at it.

**Comment by lzk228** [comment]
> okay,if no one has done anything about this im gonna take a look at it.

right above your comment you can see there is already open pr for this

**Comment by KonstantinAngelov** [comment]
> > okay,if no one has done anything about this im gonna take a look at it.
> 
> right above your comment you can see there is already open pr for this

oh sorry im not very familair with github :(

**Comment by Willhelm53** [comment]
This one needs closing
