### ISSUE TITLE
Bags will brick if you move out of range of a bag while having it open

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#28388]
## Description
If you open a bag and then move out of range before closing it, it will break in such a way that you will be unable to open any other bags. No one else will be able to open the bag you left open, until you move back into range and close it.

**Reproduction**
- aghost
- right click to open someone's bag
- move out of range until bag UI disapears
- try to open another bag
- move back into range and close bag to fix

**Video**

https://github.com/space-wizards/space-station-14/assets/106507028/09ed4958-7c24-4042-8f0d-ef2f344ea72b

**Additional context**
Very similar to #27954 but with bag inventory.

**Comment by metalgearsloth** [comment]
Admins should know about PVS also there's a PR up.
