### ISSUE TITLE
Atmos gas filters need a logical inverse.

### ISSUE THREAD

**Issue by WarMechanic** [space-wizards/space-station-14#28390]
## Description

With atmos pipestacking changes, it takes a much larger profile and more metal to invert an atmos filter to only output a specific gas in a direction.

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/69510347/30f30fd8-40e4-4675-b349-0ccb1f815fb7)
![image](https://github.com/space-wizards/space-station-14/assets/69510347/7165c3cf-7904-41a2-873a-b1f4225cd508)

**Comment by EmoGarbage404** [comment]
Flipped filters do exist. I'm like 99% sure you can craft them too

**Comment by WarMechanic** [comment]
![image](https://github.com/space-wizards/space-station-14/assets/69510347/09a5542a-6441-47c4-acb7-cc87880e1a30)
if you're talking about filter mirroring, that wasn't what i was trying to describe
if you're talking about logically inversed filters, then i haven't seen a way to obtain them ingame

**Comment by deltanedas** [comment]
it actually costs the same amount of steel

**Comment by mirrorcult** [comment]
just design your setup better

**Comment by WarMechanic** [comment]
> it actually costs the same amount of steel

the increased profile might not be suitable for smaller stations if you dont want pipes running into eachother

**Comment by UbaserB** [comment]
> just design your setup better

mirror... it's really annoying sometimes even with good setups
