### ISSUE TITLE
Transform error making console unusable, logs huge and client crashes.

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#28408]
## Description
Unsure if this is a robust error or cause from in game. But it spams out these errors a few minutes after joining in game.

```
[ERRO] resolve: Can't resolve "Robust.Shared.GameObjects.TransformComponent" on entity 24267!
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
```
Occasionally when opening the console after long admin session it will crash the client too.
Console becomes unusable and my log file goes to insane size 1.5GB might be bigger but have restarted several times.

**Reproduction**
- Join game and wait 5-10min should be happening.
- Open in game console and see errors spamming out.

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/47093363/8bcd6b77-c607-470a-b961-4a4a7c768831)
<img width="269" alt="image" src="https://github.com/space-wizards/space-station-14/assets/47093363/b7d74c1f-098d-4816-bfcb-8c548f36357e">

**Additional context**
I can give the full log but it doesn't look particularly helpful.

**Comment by Mirino97** [comment]
Thank you for your very detailed report!

An issue and a PR have already been made in engine https://github.com/space-wizards/RobustToolbox/pull/5175 , so I'll be closing this issue.
