### ISSUE TITLE
Fire just doesn't

### ISSUE THREAD

**Issue by bruhmogus** [space-wizards/space-station-14#28401]
## Description
Fire will almost immediately die out in almost every condition.

**Reproduction**
Step 1. Smite someone with the fire smite, set them on fire with alcohol/lighter, put them in liquid plasma, whatever
Step 2. Watch them shrug it off.
Step 3. Cry.

**Screenshots**
![20240529210541_1](https://github.com/space-wizards/space-station-14/assets/104110869/9a40749d-ee68-4585-b506-9328763469d1)

**Additional context**
It might be a problem with max firestacks.

**Comment by deltanedas** [comment]
fire spread trolled somehow

**Comment by bruhmogus** [comment]
this was fixed, closing
