### ISSUE TITLE
Chem dispenser eats jugs

### ISSUE THREAD

**Issue by Mirino97** [space-wizards/space-station-14#28410]
1. Grab jug
2. Click on dispenser
3. Game says "you can't put that in there"
4. Jug disappears
5. Open chem dispenser
6. No jug
7. OH GOD MY JUGS

**Comment by aspiringLich** [comment]
Chem dispenser my betrothed.

**Comment by aspiringLich** [comment]
I think I was able to reproduce this on an earlier build, but now I can't. Still shows the "you can't put that in there!" message incorrectly though, so I'm fixing that

**Comment by beck-thompson** [comment]
Tried to recreate this but couldn't, looks like it was fixed in that linked pr!
