### ISSUE TITLE
FoodContainerComponent needs improvements 

### ISSUE THREAD

**Issue by AJCM-git** [space-wizards/space-station-14#2841]
- You cant re-insert something into the container once you pulled it off
- There are cases like the pizza where if you have one you either cut it into pizza slices or eat it, since pizzas are food containers for slices you can't  eat them without getting the slices first
- You use the entity to get the food they contain
- I have no idea what the number that every prototype inside the prototypes field needs is or does

**Comment by cyclowns** [comment]
> I have no idea what the number that every prototype inside the prototypes field needs is or does

probability that an entity of that type is dropped, this is only really used in pizza boxes since they can spawn 1 of 4 pizzas
