### ISSUE TITLE
welding fuel/flammable substances will put out fires

### ISSUE THREAD

**Issue by Dutch-VanDerLinde** [space-wizards/space-station-14#28445]
instead of just increasing the firestacks on an entity like it did before, it'll increase the firestacks but also put out the fire

**Comment by Dutch-VanDerLinde** [comment]
update, splashing any reagent in the game will put out fires

**Comment by Kadeo64** [comment]
> update, splashing any reagent in the game will put out fires

even the ones that are supposed to cause firestacks (clf3/phlog)?

**Comment by Dutch-VanDerLinde** [comment]
> > update, splashing any reagent in the game will put out fires
> 
> even the ones that are supposed to cause firestacks (clf3/phlog)?

if mixed with other reagents, yes, it will extinguish, but if its pure phlog it'll ignite someone

**Comment by Brandon-Huu** [comment]
Still an issue.
[Screencast from 07-27-2024 06:18:40 PM.webm](https://github.com/user-attachments/assets/a2dd7145-a051-40d3-b5da-9fa52c4743a2)
