### ISSUE TITLE
Packed lacks meds in med lockers

### ISSUE THREAD

**Issue by bruhmogus** [space-wizards/space-station-14#28459]
## Description
The Packed map has no meds in the med lockers that are by the beds.

**Reproduction**
1. Play Packed
2. Open any of the 3 lockers by the beds in medbay
3. EXPLODE RAAAAH

**Screenshots**
![20240531223341_1](https://github.com/space-wizards/space-station-14/assets/104110869/0ef304d3-d3f7-4849-ae59-7fa6275d0fd3)

**Additional context**
There is only one medicine locker with things in it.

**Comment by thebadman4662** [comment]
I always thought they are meant for patient items? I dunno like validhunter lemme strip em and drag gear to sec kind of one?

At very least thats where we could be putting insulation like security hardsuits of people we are going to treat via cryopods if we, the doctors were not so lazy and drop it right on the floor.
