### ISSUE TITLE
Opening uplink changes the game window title to Uplink

### ISSUE THREAD

**Issue by ficcialfaint** [space-wizards/space-station-14#28454]
Thanks to \@netwy on Discord for finding this.

## Description

Opening uplink changes the game window title to Uplink

**Reproduction**

1. Spawn uplink
2. Open it
3. Now your game window title is Uplink until you relaunch the client

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/46868845/611a3542-e22a-4e4c-9074-f1b9a88fcf57)

**Additional context**

![image](https://github.com/space-wizards/space-station-14/assets/46868845/bf687aed-5122-4371-9015-21f9a6267015)

**Comment by moonheart08** [comment]
OH SO THAT'S WHAT THAT WAS

**Comment by PJB3005** [comment]
Incredible.
