### ISSUE TITLE
Rat Kings can spawn at 0pop

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#28455]
## Description

I’ve been a huge fan of playing low-pop recently, and I really don’t like how many rat kings we get since it’s really hard for us to take care of them. On average, it’s at least 1 rat king and we usually have up to 3 or 4 in a 2-3 hour round. I would make it minimum 15pop, because then you might get the captain or a secoff.

**Comment by Dutch-VanDerLinde** [comment]
Status: Untriaged

**Comment by z9ctn4fn** [comment]
I'll try and find a fix for this.

**Comment by Tayrtahn** [comment]
Probably from the rat migration event? Might need to be restricted to higher pop and possibly limited in number of times it can happen. 

Alternatively, it could be split into two versions, with and without the rat king, and given different restrictions.

**Comment by Tayrtahn** [comment]
Actually, no, it's something stupider than that. Hang on.

**Comment by z9ctn4fn** [comment]
Thanks for the help.
I'll get on this.
