### ISSUE TITLE
Mailing unit in core hydro has not destinations.

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#28468]
## Description
Mailing unit in core hydro has not destinations.

**Reproduction**
Try use it on core

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/47093363/2f015185-306f-43b4-8ae1-9bfba6c529a1)

**Additional context**
NA

**Comment by UbaserB** [comment]
The fix was already merged before and it should work now. If it STILL doesn't work, feel free to reopen
