### ISSUE TITLE
Soap verb should have a different sprite

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#28477]
## Description

PR #28101 added a new verb for cleaning evidence, but it is reusing the current soap sprite. Compared to other verb icons, it is wildly out of style and should probably have a new custom sprite following the current standards.

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/134914314/e9bdabe4-4a6b-46d5-b72c-26e8add9eed6)

**Comment by dragonryan06** [comment]
Just fixed this in my PR #28898 if you want to mark closed.
