### ISSUE TITLE
Sundowner meta, AKA reflect land

### ISSUE THREAD

**Issue by UnicornOnLSD** [space-wizards/space-station-14#28476]
## Description

To be short, I have seen while playing on salamander a reocurring build that can be purchased by syndies, loneops and nukies at the cost of 24 TC.

It's composed of the following: Juggernaut suit (12TC), E-sword (8TC), E-dagger (2TC), EMP implant (2TC) at bare minimum.

### Why ?
 Because this build gives crazy survivability to the person running it, and has BARELY any counter.  What you are looking at is a guy that can, while standing still, reflect any projectile (stuns, bullets, ANY and all of them) thanks to the recent reflect chance change giving for example the E-sword 50% reflect chance while standing still. This stacks with the E-dagger. Then it has 80% resistance to most damage, and short range stun doesn't work due to the EMP implant. And the reflect doesn't stop when they move, it is lower yes but still present and quite high, near 50%
TL:DR a player can buy for 24TC gear that makes him able to deflect all projectiles, is immune to stun and if you do manage to hit them will not take any kind of damage.

### Counters ?

I did mention a few counters, they go as follows:
-stinger grenades (works only when they are standing on top of it, or two are hit in quick succession)
-hypospray, with narcs, or poison (need to get in close range and the only person who has it likely won't be fighting, and well, shouldn't be the one dealing with it)

Some may mention truncheons, but truth is you need to land 28 continouus hits to down them with it, since truncheon stun damage is based on the blunt damage dealt.

This is not theory crafting, it's been run before on mander and has proven to be an easy way to get a loneop victory without any effort, strategy, or preparation, just at most a bit of button pressing. See round #55095.

### TL:DR
What we are left with is a build that can be ran easily by loneops and nukies, and requires to kill renault for syndies, requires no prep, is flat immune to most takedown manners present in the game nor requires much skill.
The way I see the ISSUE at is in reflect chances, way to fix it would be to hopefully make dual wielding reflecting weapons not stack for crazy reflect chance, or just reducing their max reflect chances individually.
Alternatively, make energy blades affect by EMP, this would ensure it isn't that easy to just get crazy deflect and close range stun immunity.

**Reproduction**

1. launch your local dev env
2. spawn a dude and give him the afromentioned items
3. try to shoot them while they are standing still
4. you die of your own bullets before they can take any damage

3bis. get a buddy to be the juggy
4bis. try to stun them in close range
5bis. you got EMP'ed and they will cut you up with E-sword

**Comment by ElPidor** [comment]
Holy fuck, its so much of a skill issue and soy-gaming that everage graytide would cry. 
Just dont come close wtf 
le solution 
le pipegun + bolas 
stamina crit 
gg 
what the fuck, use your mind for goodies
