### ISSUE TITLE
Mop bucket can be placed in inventory

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#28475]
## Description

You can try place a mop bucket in your inventory, but it glitches out and forces you to stop pulling. During the act of actually clicking the inventory to place it inside, a bunch of your UI temporarily disappears as well on the right hand side of your screen.

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/134914314/33e14ca3-3d3c-4d49-814f-2244753f4e11)

![image](https://github.com/space-wizards/space-station-14/assets/134914314/380dc405-83fe-44a8-ad46-58accf107d20)

**Comment by Randomplayer2or3** [comment]
Actually this works for all pulled structures.
