### ISSUE TITLE
Mouse migration event always spawns a rat king

### ISSUE THREAD

**Issue by Tayrtahn** [space-wizards/space-station-14#28480]
## Description

The rat king spawn is listed as a special entry with a probability of 0.001 on the vent critters rule component.
But the way the vent critters rule works is to _always_ spawn one of the special entries (ignoring the probability) and then do another pass through the special entries for each spawn location (this time using the probability).

So there's always going to be at least one rat king added by the event, with a very small chance of another one for each vent.

**Reproduction**

Ghost and run `addgamerule MouseMigration` repeatedly. Watch the ghost roles list increase every time.

**Screenshots**

**Additional context**

Noticed while investigating #28455

**Comment by deltanedas** [comment]
rat king should just have its own rule (like on deltav) so it can have min pop etc independent of *mouse spawns*

**Comment by LordJike** [comment]
So create a new rule for spawning the rat king individually then have it referenced in Mouse migration rule only if the pop is higher than a threshold?

**Comment by Scruq445** [comment]
but how many players should there be for the rat king event?

**Comment by Scruq445** [comment]
We've agreed in the server that the player amount should be 15, making a PR now
