### ISSUE TITLE
Emote Reagent effect does not work anymore

### ISSUE THREAD

**Issue by slarticodefast** [space-wizards/space-station-14#28490]
## Description
See title.

**Reproduction**
- Inject yourself with honk or juice that makes you weh.
- Nothing happens
- Doing the emote by writing "*honk" in the chat window still displays the sound effect as intended.
- Laughin syrup and laughter still trigger their emote just fine

**Additional context**
See [toxins.yml](https://github.com/space-wizards/space-station-14/blob/master/Resources/Prototypes/Reagents/toxins.yml)
Maybe something in #26702 broke it? I remember it working before.

**Comment by Cojoke-dot** [comment]
Doing my own tests and reports from other people it seems that Juice That Makes You Weh is broken too. It seems like the same bug.

**Comment by slarticodefast** [comment]
> Doing my own tests and reports from other people it seems that Juice That Makes You Weh is broken too. It seems like the same bug.

I tested it again and it seems you are right. Weh juice and honk are both broken, however laughter still works.
