### ISSUE TITLE
Server Version

### ISSUE THREAD

**Issue by SandPoot** [space-wizards/space-station-14#285]
Client is not aware that they're outdated!

**Comment by PJB3005** [comment]
Not sure what the problem here is. This IS an issue.

**Comment by SandPoot** [comment]
i had a older version from the website, i guess they updated it quickly, it now has a version checker

**Comment by PJB3005** [comment]
The launcher always had an auto updater (it's only now graphical), but still the server/client don't do version checks. Usually this is fine though.
