### ISSUE TITLE
QSI-Geras Nullspace Issue

### ISSUE THREAD

**Issue by WHITED4WN** [space-wizards/space-station-14#28507]
## Description
If you use a QSI while the other end is in the internal storage of a geras, you will be sent to nullspace.
In some cases i have even gotten my playermorph out from bluespace while as a geras.

**Reproduction**
- Player Into Nullspace
1: Put a linked QSI into a slimeperson
2: They geras
3: Activate your end
4: You are now in Nullspace

- PlayerMorph from Nullspace
1: cause this Bug
![20240601222934_1](https://github.com/space-wizards/space-station-14/assets/75489803/8c635936-81b5-403b-874b-53641362a07b)
2: Geras
3: 
![20240601222909_1](https://github.com/space-wizards/space-station-14/assets/75489803/7be71f52-8e24-4597-856b-550d4fd3c232)

**Additional context**
Player Into Nullspace replication test Round Number: Salamander - 55167, Player Hope Kirkson (Reporter) - 1:33:00 (+/-1 minute)
Player From Nullspace test Round Number: Salamander - 55159, Player Hope Kirkson (Passenger) - 1:40:40
This bug is caused entirely by the same thing that causes bomb timers to pause in a geras and sentient roles in a geras to be nullspace'd, the fact the inventory isnt moved to the geras when the morph happens

**Comment by EmoGarbage404** [comment]
Clarification: are you actually in nullspace (i.e. your camera freezes) or is the player just teleported into a paused space map?

**Comment by WHITED4WN** [comment]
It could be either or. I am unsure as to where they coded geras to send the players body.
![image](https://github.com/space-wizards/space-station-14/assets/75489803/bad7ee1f-c7be-4ec2-8a36-66a1f4750998)
however, the infinitely negative usetimer might answer the question more definitely

**Comment by beck-thompson** [comment]
Gera gone 😔
