### ISSUE TITLE
Marathon lacks a PA control computer board

### ISSUE THREAD

**Issue by XxSWAG-MASTER-OVERLORDxX** [space-wizards/space-station-14#28512]
## Description
you are forced to order one from cargo despite having every other board to construct the PA emitter
and while i understand marathon having a DIY PA setup its missing critical parts that other stations have (should prob have a empty AME fuel too but that's another issue)

**Comment by Cojoke-dot** [comment]
https://forum.spacestation14.com/t/marathon-station-lacks-a-pa-computer-board/8333
