### ISSUE TITLE
Damage Overlay disappear after reconnection

### ISSUE THREAD

**Issue by PilgrimViis** [space-wizards/space-station-14#28559]
## Description
Damage overlay with bleeding and white circle disappear after you disconnect and reconnect again.

**Reproduction**
1. Give yourself a few good punches until red overlay appears
2. Press Escape, press Disconnect
3. Press Retry and connect again
4. Bleeding overlay disappear. 

**Screenshots**
(gif created on Miros server)
![DamageOverlayDissappear](https://github.com/space-wizards/space-station-14/assets/6408195/0ca55a89-325c-47c9-a8f9-15e70047b5f8)

**Additional context**
1. If you completely restart the game by closing the client app, the overlay showing again
2. I tried to debug this and found out that _protected override void Draw(in OverlayDrawArgs args)_ method doesn't get called after reconnection. Also, **Initialize** method on **DamageOverlayUiController** would get called when you restart the client, but don't get called when you reconnect. Seems like it get called once with reflection in Robust.Client. If you'll give me a tip I could try to investigate and try to fix this further.

**Comment by metalgearsloth** [comment]
See attached issue.
