### ISSUE TITLE
Gas masks don't work after unequiping helmet

### ISSUE THREAD

**Issue by Plykiya** [space-wizards/space-station-14#28567]
## Description

Gas masks don't work for toggling internals after taking helmet off

**Reproduction**

1. Have gas mask on
2. Try to toggle internals (will work)
3. Toggle helmet from a hardsuit on
4. Toggle helmet from a hardsuit off
5. Try to toggle internals (will not work)

**Screenshots**

**Additional context**

**Comment by Errant-4** [comment]
The problem is that when you remove anything with internalscomponent on them (like a hardsuit helmet) the game marks you as "not having internals" even if you do have a mask on you still. See #27643
