### ISSUE TITLE
Main clothing slot broke for me, forced to be somewhat naked

### ISSUE THREAD

**Issue by Bloomyex** [space-wizards/space-station-14#28563]
Went to get a change of clothes, found myself unable to put clothes on after removing them. I tried multiple different kinds of jumpsuits, jumpskirts and even costumes and none of them would go on my main clothing slot. Kept telling me it wouldn't fit there.

I'm pretty sure this could've just been a single bug for me specifically, so I have no idea how it would be replicated. Maybe mess around a bit?

I had to spend the whole round with most of my stuff (including my ID) in my backpack. It kind of sucked.
Ofc I put on an outerwear dress to cover up at least.

**Comment by Plykiya** [comment]
Just tested putting on clothes with every single species, it worked with every single species

**Comment by Bloomyex** [comment]
That's odd.. I've been told it only happened to Harpies by others.

**Comment by Bloomyex** [comment]
Apparently some sort of mistake in coding. It's being fixed though.

**Comment by mirrorcult** [comment]
harpies are not part of upstream code, file the issue to whatever fork you're playing on

**Comment by Bloomyex** [comment]
Gotcha. I was told to come here for the issue, I'm just confused and following the instructions I'm being given. My bad.
