### ISSUE TITLE
Mailing Units Broken

### ISSUE THREAD

**Issue by IamVelcroboy** [space-wizards/space-station-14#28568]
## Description
- The player-side destination UI does not show up when clicked on, or in the context menu.
- It seems to have reverted to a non-functional disposals unit
- It has a "Flush" option

**Reproduction**
Try to mail anything

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/107660393/e930bd72-4dfd-4aec-9e3a-04a46974426f)

**Additional context**
n/a

**Comment by UbaserB** [comment]
i got it to work through a really convoluted method but it's definitely buggy

**Comment by Moomoobeef** [comment]
as far as replicating goes, I have the same problem
