### ISSUE TITLE
Maints book names are broken

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#28579]
**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/134914314/2d150258-ba66-4afe-8264-998100855470)

**Comment by UbaserB** [comment]
i dont actually remember if it was maints or normal books but one or both of them were broken

**Comment by RadioAndrea** [comment]
> i dont actually remember if it was maints or normal books but one or both of them were broken

Both are broken.

All books everywhere I've looked.
