### ISSUE TITLE
Space ninja shoes' magnetic suction cups aren't magnetic

### ISSUE THREAD

**Issue by dolgovmi** [space-wizards/space-station-14#28585]
## Description
It says in the item's description: "A pair of nano-enhanced boots with built-in **magnetic** suction cups."
The shoes are not magnetic however and a ninja has to rob engineering or some other place for magboots when there's no gravity.

**Comment by deltanedas** [comment]
with item toggle refactor it should be as shrimple as adding MagbootsComponent without toggle so theyre always on :trollface:

**Comment by QuietlyWhisper** [comment]
It'd probably a bugfix if anything if it was simply not imported to 14 entirely correctly, surely...
