### ISSUE TITLE
Borg UIs are broken if the borg does not have a module active

### ISSUE THREAD

**Issue by engineer-pearl** [space-wizards/space-station-14#28582]
## Description
While a borg does not have a module open, most UIs do not work

**Reproduction**
Spawn as borg
Close the default module
Attempt to open the laws UI. (it will not open)
Attempt to read a map. (it will not open.)

**Additional context**
I am new to borg so I can't speak to how long this issue has existed,, but others were sufficiently confused that this might be a new problem.

**Comment by Psychpsyo** [comment]
I got borged the first time like two days ago and got asked for law 2.
I didn't have any modules installed yet so it took me like a solid five minutes of fucking around before asking in OOC what the hell I am supposed to do and getting it explained as well as getting a module installed.

**Comment by Errant-4** [comment]
Thank you for reporting the issue. I think this is already tracked by #27439 albeit with less detail
