### ISSUE TITLE
Agent ID card can no longer change appearance

### ISSUE THREAD

**Issue by PoorMansDreams** [space-wizards/space-station-14#28599]
## Description

The Agent ID card usually has an action that allows it to change appearance. But lately, the action just does not show up when holding the Agent ID.
**Reproduction**

Hold onto the Agent ID card
**Screenshots**

**Additional context**

**Comment by deltanedas** [comment]
you have to put it in your id slot (the slot itself, not in your pda) not hands

**Comment by PoorMansDreams** [comment]
holy shidd

**Comment by AJCM-git** [comment]
> you have to put it in your id slot (the slot itself, not in your pda) not hands

okay thats very unintuitive, should at least open the menu when you interact with it
