### ISSUE TITLE
Supermatter nade not working quite right

### ISSUE THREAD

**Issue by XxSWAG-MASTER-OVERLORDxX** [space-wizards/space-station-14#28608]
## Description
currently the super matter pulls people to the side of the blackhole and not through it in a vortex, also it lacks any admin message when it detonates.

**Comment by Cojoke-dot** [comment]
Every bomb set off seems to have a vortex in the same place relative to the center per session, but the point is different between sessions.

**Comment by MilenVolf** [comment]
Closed by #29617
