### ISSUE TITLE
site not working

### ISSUE THREAD

**Issue by simsonek** [space-wizards/space-station-14#2861]
[https://spacestation14.io/](https://spacestation14.io/) is not working

![image](https://user-images.githubusercontent.com/5715907/103306846-d5afd500-4a0e-11eb-9509-eea65c32b6e5.png)

**Comment by AJCM-git** [comment]
Its currently under maintenance

**Comment by simsonek** [comment]
Oh, is there any way to download the client? I was reading some info about it and was unable to follow [https://hackmd.io/@ss14/docs/%2FtlnDiutATZafjSmAkGEbDQ#Play](https://hackmd.io/@ss14/docs/%2FtlnDiutATZafjSmAkGEbDQ#Play) instructions

**Comment by AJCM-git** [comment]
You can download the launcher in here https://github.com/space-wizards/SS14.Launcher/releases

**Comment by Zumorica** [comment]
Also, please note that this is not the place for these kinds of reports. Next time, let us know on Discord.
