### ISSUE TITLE
Can't change loadout for any jobs set higher than none

### ISSUE THREAD

**Issue by Plykiya** [space-wizards/space-station-14#28619]
## Description

Title is the reproduction, clicking loadout does nothing for me except when I sets the job priority to none
Although it might happen in some other cases...?

Have had a few people who say their CE loadout can't be edited and they don't have a backpack anymore

**Reproduction**

**Screenshots**

**Additional context**

**Comment by slarticodefast** [comment]
I remember I had this happen quite a while ago, but I just tested this again on a current build and it seems to be fixed now.
