### ISSUE TITLE
Projectile reflect should have an upper limit (Energy shield and energy sword reflect stacking)

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#28620]
## Description
Reflect is too strong when stacked with an esword and eshield. 30 out of 33 shots were reflected when i shot a laser at an urist wielding a eshield and esword.

Granted this is when standing still. However this combied with nukies absurd damage resistance it makes these two items extremely overpowered. I killed myself with my own reflected shots before i killed my target in testing.

We had an issue like this in the past where eshields were reflecting too much and because of this they were a MUST BUY for nukeops due to how overpowered they were. We have approached this issue again where 9/10 nukies are using eswords and eshields due to how overpowered they are together. 

I believe it is bad game design when you are better off getting into melee combat aganist items that excell in melee combat

**Video**
https://github.com/space-wizards/space-station-14/assets/106507028/ea53dd25-b0d5-4802-b9b7-40c781c028d8

**Comment by Vermidia** [comment]
Already solved by #28539

**Comment by Kayek14** [comment]
argh I missed that, thank you.

Closed due to #28539
