### ISSUE TITLE
Map re-renders on bag Closing.

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#28630]
## Description
On opening then closing the bag, the map/game looks like it re-renders, flashes black for a moment.

**Reproduction**
- Open Bag
- Close bag
- Should happen after you try to close.

**Screenshots**

https://github.com/space-wizards/space-station-14/assets/47093363/82e04909-82ea-4983-87c8-89d229274596

**Additional context**
Error when it happened.
[clientlog.txt](https://github.com/user-attachments/files/15586795/clientlog.txt)

**Comment by ElectroJr** [comment]
Newest engine version should have fixed it (#28632)
