### ISSUE TITLE
Moths can eat jackboots / combat boots with the knife inside 

### ISSUE THREAD

**Issue by aspiringLich** [space-wizards/space-station-14#28646]
## Description

title

**Reproduction**

\>be me
\>a moth
\>get jackboots
\>put knife in jackboots
\>eat jackboots
\>somehow dont die of having-eaten-a-knife-itis

**Comment by deltanedas** [comment]
it should give you 10u of lacerinol :trollface:

**Comment by Hmeister-real** [comment]
> it should give you 10u of lacerinol :trollface:

eating a whole knife should give 25u at least

**Comment by Sh18RW** [comment]
https://github.com/space-wizards/space-station-14/pull/30019

**Comment by Sh18RW** [comment]
PR has been merged, so the issue should be resolved
