### ISSUE TITLE
Air vents do not unlock at 1kpa of pressure in room

### ISSUE THREAD

**Issue by civis18** [space-wizards/space-station-14#28640]
## Description
Air vents do do not unlock themselves from the under-pressure lockout when there is more then 1 Kpa as intended

**Reproduction**
-Space a room to empty all pressure
- Undo spacing
- Introduce any gas into the room and examine the air vent while viewing the environment via a gas analyzer
- Ask why

**Screenshots**

![Screenshot 2024-06-05 142501](https://github.com/space-wizards/space-station-14/assets/49328686/bdc73904-2182-45f4-be97-0ca88d61279c)

**Additional context**

**Comment by dolgovmi** [comment]
Pretty sure this happens like every other round making distro barely function after some accidents

**Comment by Just-a-Unity-Dev** [comment]
Intended: https://github.com/space-wizards/space-station-14/blob/7ba26f4592e9bc6cc281ab861a27c3a9526e7fe7/Content.Server/Atmos/Piping/Unary/Components/GasVentPumpComponent.cs#L42
Someone must've tweaked it, the original PR says its at 1kPA (#9824) but now its 60 kPA

**Comment by Tayrtahn** [comment]
> Someone must've tweaked it, the original PR says its at 1kPA (#9824) but now its 60 kPA

Recently changed by #28370. @Partmedia, is this working as intended?

**Comment by Partmedia** [comment]
Unfortunately the old threshold of 1 kPa only works with instant spacing. The new threshold is needed to make sure lock-out always works (otherwise, it leaks all of distro into space). You need to drag a canister in the spaced area, or open a firelock to let air in from other areas to get it out from lock out.
