### ISSUE TITLE
Flatpacker is busted

### ISSUE THREAD

**Issue by AjexRose** [space-wizards/space-station-14#28657]
## Description

Whenever using the flatpacker, it both does not consume the circuit board, and provides a base flatpack instead of the flatpack of whatever you wanted.
**Reproduction**

-get flatpacker
-fill it up with material
-put a circuit in 
-flatpack it
-get a base flatpack
-look inside flatpacker
-circuit not flatpacked. 
**Screenshots**

https://github.com/space-wizards/space-station-14/assets/112997230/65fcde0f-d9e3-4a30-a1da-8c61f959c92b
**Additional context**

N/A

**Comment by deltanedas** [comment]
probably has an exception thrown between spawning the flatpack entity and setting its prototype to spawn when unpacked
