### ISSUE TITLE
Construction Rotation seems to be bugged

### ISSUE THREAD

**Issue by Kadeo64** [space-wizards/space-station-14#28665]
## Description
Round #55538 on leviathan
While the green construction graph railings were rotated, when I built them with rods, they were not rotated, meaning I had to use an ugly artifact containment setup.
**Reproduction**
Try and build construction graph rotated railing
**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/108914677/457b646e-5e92-451a-a8c6-00ced6d32e52)
![image](https://github.com/space-wizards/space-station-14/assets/108914677/f60e9b62-b59c-42e3-8435-b3a26e2d8b53)

**Additional context**

**Comment by Kadeo64** [comment]
I did not attempt to restart, and it may not always be reproducable.

**Comment by EmoGarbage404** [comment]
dupe issue
