### ISSUE TITLE
Suture/mesh recipes require 1000% bruisepacks/ointments

### ISSUE THREAD

**Issue by thebadman4662** [space-wizards/space-station-14#28667]
## Description
https://github.com/space-wizards/space-station-14/pull/28225 seems to have done a whoopsie. Those recipes were balanced about using a single piece of basic medicine, and even had to receive 60% cost reduction to make them viable again after chem changes. https://github.com/space-wizards/space-station-14/pull/24948

With bruise pack requirement increased to ten per one set of sutures, its no longer worth it to craft them really. We all know how unrobust atmos are alas, at that point its better to just bother cargo for steel + plastic stack sets instead.

With ointments its similiar issue but you also have another good reason to not cook meshes, you can cook aloe cream instead and save Sig for injections.

**Reproduction**
1. Put stack of brute packs, cloth, 3 poppies and 60u of Tranexamic Acid + Cryptobiolin each.
2. Set timer for 30s.
3. Get 10 sutures, 29/30 cloth, 2 poppies and 40u of each chem back instead of 30 sutures, 27 cloth, 7 bruise packs, empty containers.

**Comment by blueDev2** [comment]
It's supposed to be 1 brutepack -> 10 medicated sutures?
It doesn't make sense IC, but I understand that balance-wise.

Before it was 1-10 brutepack -> 10 medicated sutures, so I wasn't sure what was supposed to happen, balance-wise

**Comment by thebadman4662** [comment]
If you are willing to dig all the way down rabbit hole to the truth, you could find the guy adding original recipe saying it was meant to be only one used, yes. Problem is, I do not even remember if theyd did so on discord, issue or one of pull requests...

In unlimited chem era, I do not think anyone would care, we are still getting double healing and 666.(6%) on meshes vs caustic. In limited chem though, its pretty much vanity product rather something sought after, especially with cargo being so ridiculously powerful then can mass buy it anyways, its just that most of time they don't.

**Comment by blueDev2** [comment]
https://github.com/space-wizards/space-station-14/pull/24948#issuecomment-1925973358
I assume this is what was meant?
In any case, I will make the PR to rebalance it anyways and see what maintainers say.

**Comment by thebadman4662** [comment]
I believe it was some even earlier thing somewhere, but again. It was long enough to be just vague memory other than brutes/oints turning into 10 more sutures/meshes being part of balancing and intended.

**Comment by blueDev2** [comment]
Honestly, it looks like people are just being confused cause before, when using this recipe, a stack of 1 brute packs and a stack of 10 brute packs are treated the same.

**Comment by deltanedas** [comment]
with the "correct" usage of 1:1 pack to suture its completely uneconomical to make it now, better off using the chems to make bruizine et al for much more efficient healing. i would prefer it use 1 pack, and if theres multiple in the stack leave the rest (which is now supported)
