### ISSUE TITLE
Morgue glass airlock doesnt exits

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#28666]
but should

**Comment by thetolbean** [comment]
As morgue access no longer exists and morgue doors use the default medical skin, there is no need for a specific glass airlock for morgues. I recommend using a Glass Airlock [Medical, Locked] for the same effect.

**Comment by lzk228** [comment]
> As morgue access no longer exists

there was no morgue access, this door has medical, chaplain and detective accesses, so it just should be good to have glass variant
