### ISSUE TITLE
Maptext with richtext support for the tutorial map

### ISSUE THREAD

**Issue by juliangiebel** [space-wizards/space-station-14#28677]
## Description
Allows the use of tags like `KeyBindTag` for tutorial "decals"
This is used for tutorial text that looks like decals on the tutorial map.
### Example
![tutorial_text_example](https://github.com/space-wizards/space-station-14/assets/8915246/171be6b5-7aa4-4c00-acc5-a8ca71ad0f7e)

**Comment by FairlySadPanda** [comment]
Hello
