### ISSUE TITLE
Saltern power mapping issues

### ISSUE THREAD

**Issue by collinlunn** [space-wizards/space-station-14#2868]
Power fails across the station after a while on saltern because there aren't enough generators to fully power all the substations.

Also, the smes units are set to not draw or supply any power, need to adjust the BatteryDischargerComponent.ActiveSupplyRate & BatteryStorageComponent.ActiveDrawRate in the SalternSmes prototype.

**Comment by SweptWasTaken** [comment]
Well power fails because people are ideally supposed to setup power-generation. I'll look into adjusting those though.

**Comment by collinlunn** [comment]
I figured that since saltern was the default map, having the power fail eventually could cause dev annoyances, though I understand that there is a gameplay reason.

**Comment by ike709** [comment]
@SweptWasTaken Saltern doesn't even seem to have any of the parts for the antimatter engine. Secure storage is just a bunch of empty crates and an emitter.

**Comment by Peptide90** [comment]
#3170 is related and should give players an easy way to setup power generation.
As is #2878 so that SMES can be changed on station.

I think the station needs more SMES units by default (double?) so that it has the power storage to use the PA.

**Comment by SweptWasTaken** [comment]
Lots of power gen is now available on saltern. Closing this.
