### ISSUE TITLE
pais fall out of your pda upon being near a bluespace anomaly pulse

### ISSUE THREAD

**Issue by UBlueberry** [space-wizards/space-station-14#28714]
## Description

**Reproduction**

1. put a pai into your PDA
2. stand next to a bluespace anomaly
3. when it pulses, the pai will drop at your feet even if you aren't bluespaced elsewhere
**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/161545003/015ee0b2-2985-4ab2-a671-27046363f1c3)
![image](https://github.com/space-wizards/space-station-14/assets/161545003/c1d28df9-d62c-49af-a4aa-5c965e808eb3)

**Comment by UBlueberry** [comment]
some guy dropped a syndicate pai at his feet when i was standing next to him lmao

**Comment by slarticodefast** [comment]
Oh, that's where it went lol.
