### ISSUE TITLE
Linking anything with access broken in mapping 

### ISSUE THREAD

**Issue by IamVelcroboy** [space-wizards/space-station-14#28710]
## Description
(This might be a dupe but I couldn't find another issue)
When trying to link things together(airlocks, buttons, etc) anything that has access will be denied.  

**Reproduction**
* Map 2 external airlocks
* Attempt to link them
* Access denied!

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/107660393/2ff37761-6c74-4d18-942f-b8f2f19b7cee)

**Additional context**

**Comment by IProduceWidgets** [comment]
copy of 28274
