### ISSUE TITLE
Unlit airlock sprites should have transparency

### ISSUE THREAD

**Issue by Flareguy** [space-wizards/space-station-14#28725]
## Description
SS13:
![image](https://github.com/space-wizards/space-station-14/assets/78941145/58304ccd-bf98-498f-80f5-3b904142ab0e)
SS14:
![image](https://github.com/space-wizards/space-station-14/assets/78941145/9f95a6f3-286e-491e-8ffc-88836e24bb77)

Whoever ported these half-assed them and removed the transparency instead of adjusting it.

/tg/station should have overlay versions of these sprites ready-to-go (provided you're not reading this after their wall resprite has happened,) however, as alluded to in the above line, you will need to adjust them to blend properly. BYOND does not handle srgb blending correctly and makes it look significantly darker then it should normally be, resulting in the transparency looking really blown-out if directly ported.

**Comment by luizwritescode** [comment]
Find the respective textures here:
Resources/Textures/Structures/Doors/Airlocks/*/*/deny_unlit.png

I can see why. The access denied red lights have their own .png 

I quickly added a high opacity red tint around the lights using a pixel editor. Don't know how this would look in-game, can someone test this?


![door_deny_with_opacity_lighting](https://github.com/space-wizards/space-station-14/assets/33888056/6fcd41ca-c10c-475b-91a7-c2280e7acc70)

**Comment by Flareguy** [comment]
Closing this since I was kinda wrong. The unlit shader does not in fact work well with transparency in any capacity, unless you neuter the hell out of it.
