### ISSUE TITLE
Borgs say text formatting on scrambled laws

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#28739]
## Description
When the borg says, clicks its law in local, it is also saying the text formatting.

**Reproduction**
- Scramble borg laws
- talk in local/ say the law in local.

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/47093363/a977c266-2c31-44b5-8322-ac57d669c698)
But in radio it doesnt.
![image](https://github.com/space-wizards/space-station-14/assets/47093363/925c8f49-63e1-471b-93fd-67fffc455d5f)

**Additional context**
NA

**Comment by mirrorcult** [comment]
dupe #28673
