### ISSUE TITLE
Level 2 and 3 PA still singuloosing

### ISSUE THREAD

**Issue by liltenhead** [space-wizards/space-station-14#28733]
## Description
Singularity still grows too large on the intended settings. #28720 intended for a level 2 or 3 PA to not loose, but level 2 still will end up loosing over time. 

**Reproduction**
Fire up a singulo with the PA at level 2, it will eventually loose.

**Additional context**
I believe the singularity may sometimes be eating the emitter shots through the barrier, otherwise I don't know why sometimes the energy levels jump up without the singulo eating anything.

**Comment by Flareguy** [comment]
Really odd. In my testing with a 6x6 containment field, it seemed like the singulo would always flucuate between 480 - 520/570 (with level 2 & 3 respectively.)
