### ISSUE TITLE
Singularity beacon should not require power

### ISSUE THREAD

**Issue by slarticodefast** [space-wizards/space-station-14#28745]
## Description
I just tried it out on a localhost server and the current way the singularity beacon works is flawed and makes it almost useless.
You could theoretically install a local power supply (pacman) for it, but I think at its current cost of 12 TC this is too much work causing it to be used very rarely.

**Reproduction**
- Load a larger map, for example core
- place a singularity beacon next to a department of your choice, for example med
- start up a singularity and set the particle accelerator to level 4 to let it loose
- watch the singulo move towards the beacon, immediately eat a bunch of wires in engineering and cause a power outage
- the beacon deactivates and the singulo completely forgets about where it was moving

**Comment by Plykiya** [comment]
Almost useless? Every single time I've seen it used it makes a straight shot across the entire station no problem

**Comment by PJB3005** [comment]
This is literally just a skill issue. God forbid I have to work for my guaranteed station destroyer.

**Comment by slarticodefast** [comment]
> Almost useless? Every single time I've seen it used it makes a straight shot across the entire station no problem

Oh, ok. The few tests I did it always powered off before the singulo was even half the way there. May be map dependend though.

> This is literally just a skill issue. God forbid I have to work for my guaranteed station destroyer.

The station destroyer is the singulo itself and it will destroy the station with or without a beacon. Does the beacon cause the singulo to get loose on its own? Otherwise the main part of the preparation is somehow letting the singulo loose.

**Comment by PJB3005** [comment]
> The station destroyer is the singulo itself and it will destroy the station with or without a beacon.

Most of the time you loose a singulo it like, destroys engineering at most. The worst-case scenario of "the singulo eats the entire station" does not regularly happen. Unless you have a singulo beacon.

**Comment by B1essedknight** [comment]
Make a shittle then add a beacon, loose the singulo and profit i suppose.
