### ISSUE TITLE
Saltern (and probably more) need a bigger ame.

### ISSUE THREAD

**Issue by VasilisThePikachu** [space-wizards/space-station-14#28742]
## Description

The temporary ame buff was reverted. Stations like Saltern cannot power themselves with one ame core.

I know some other stations provide 1 ame core when they should not, so check other maps as well

You need at least a 3 core assuming you have solars to power saltern

![image](https://github.com/space-wizards/space-station-14/assets/34938708/7465644f-c328-4e20-98ae-ba60c2fd5b1b)

**Comment by deltanedas** [comment]
> The temporary ame buff was reverted. Stations like Saltern cannot power themselves with one ame core.

just use teg

and the ame buff was done after 1 core ops, the idea was having ame bootstrap power until you set up power properly

**Comment by UbaserB** [comment]
> just use teg
> 
> and the ame buff was done after 1 core ops, the idea was having ame bootstrap power until you set up power properly

saltern is lowpop and in my experience you never get anyone actually setting up the teg if the pop is low enough to get the map

**Comment by VasilisThePikachu** [comment]
Honestly... I would rather not have the teg be the main power source. Only yesterday did i found out you only need ONE either hot or cold input. Not both at the same time

**Comment by deltanedas** [comment]
you can and should have extreme loops not just using a miner like a caveman, theres no downside to it it just increases max power output

**Comment by LankLTE** [comment]
We agreed when the AME was initially nerfed that lowpop maps should be able to maintain power off of solely the AME. Unless that's changed, which I don't think should be the case, Saltern should get more cores.
