### ISSUE TITLE
Loneops shuttle can recall evac.

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#28744]
## Description
Feature or bug. 🤷‍♀️
The evac shuttle can be recalled from the loneops syndicate comms computer.

**Reproduction**
- Spawn loneops
- Call evac shuttle normally
- Check out the syndicate computer comms
- Click recall shuttle

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/47093363/520a322b-cc67-4685-bce0-14c4c35da365)

<img width="545" alt="image" src="https://github.com/space-wizards/space-station-14/assets/47093363/223f6f4a-6152-4bc5-81b9-d00c517b21c3">

**Additional context**
Pretty sure it just needs the CanShuttle set to false

**Comment by lzk228** [comment]
i might be not right but i think the system takes default component state, but not the state for current prototype
![image](https://github.com/space-wizards/space-station-14/assets/124214523/86ba9474-0272-49cb-97df-cdcf1ab21f7a)

**Comment by Aexxie** [comment]
Amazing

**Comment by Tayrtahn** [comment]
https://github.com/space-wizards/space-station-14/blob/master/Content.Server%2FCommunications%2FCommunicationsConsoleSystem.cs#L204

Looks like `CanShuttle` is only checked for calling the shuttle, and not for recalling.
