### ISSUE TITLE
lock popup doesnt use PopupClient

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#28746]
## Description
0. have no access
1. get a borg
2. press e
3. Access denied + It's locked x60

also it shouldnt show locked popup if it does access denied too but dont know if that can be handled

**Comment by Tayrtahn** [comment]
This is an easy one: line 368 of Content.Shared/Lock/LockSystem.cs should be changed to use PopupClient instead of PopupEntity.
