### ISSUE TITLE
Server rules open when starting a dev client

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#28769]
## Description
It would be nice if we can put this off for dev instances of the startup.

**Reproduction**
- Startup local/dev client/server.
- Get shown empty rules

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/47093363/a531df9e-98c7-44e7-8b41-0519a4c26c35)

**Additional context**
NA

**Comment by UbaserB** [comment]
Yeah it was kind of silly when i loaded it up and saw that

**Comment by AJCM-git** [comment]
fixed in #28752
