### ISSUE TITLE
fullvision on cameras when sleep

### ISSUE THREAD

**Issue by TheShuEd** [space-wizards/space-station-14#28806]
## Description
- Fullvision on the cameras while you sleep

https://github.com/space-wizards/space-station-14/assets/96445749/c4a5b7ce-2216-4f08-8819-a78039cf59b1

**Comment by Cojoke-dot** [comment]
This looks like more of an issue with the telescreen. The regular camera monitor console closes when you sleep and says you can't use it when blind. Blindness should also probably not give Fullbright at all though... It does that to simulate "feeling" I guess? So even if its dark you have a radius around you that you can see.

https://github.com/user-attachments/assets/bc03e9a4-cf53-4cd6-8f4d-f1554f48d8bf
