### ISSUE TITLE
The goddamn station news console can use motherfucking text commands WHAT THE HELL

### ISSUE THREAD

**Issue by ARMOKS** [space-wizards/space-station-14#28802]
## Description
Title

There is a new bug going around with station news which needs to be fixed ASAP.
You can crash any client and possibly even a PC if its bad enough.

REPRO:
1) Get ur hands on the news manager console
2) put "[font="Monospace"][scramble rate=250 length=99999999 chars="@@###$$&%!01"/][/font]**" in the body.
3) publish.

**Comment by ARMOKS** [comment]
@EmoGarbage404 
Sorry for ping this is bad and was publicly posted on ss14 servers like a hour before the PC tide

**Comment by juliangiebel** [comment]
Scramble shouldn't be whitelisted for player input rich text

**Comment by Tayrtahn** [comment]
Yeah, definitely shouldn't be usable for anything player input, otherwise this is going to keep popping up in more places.

Might also be good to put a sensible limit on the length of scramble text.
