### ISSUE TITLE
Ninja's spider clan charge let's you plant it anywhere.

### ISSUE THREAD

**Issue by Radezolid** [space-wizards/space-station-14#28816]
## Description
The ninja's spider clan charge right now doesnt disclose a place for the bombing, it just lets you plant it anywhere.

**Reproduction**
1. Open Dev
2. addgamerule NinjaSpawn
3. Grab ninja role.
4. See your objectives not saying where to plant the bomb (It lets you plant it anywhere.).

**Screenshots**
Dev:
![image](https://github.com/space-wizards/space-station-14/assets/170836000/31698ac4-93ac-4432-8b64-51946bf76437)
Downstream server (DeltaV) has this problem too:
![image](https://github.com/space-wizards/space-station-14/assets/170836000/d08b3e66-21e2-4980-8e27-23b9736da70c)

**Additional context**
None.

**Comment by UbaserB** [comment]
This also happened to me when i played ninja today

**Comment by dolgovmi** [comment]
Happened like every time i played ninja the past week or two

**Comment by GroggleG** [comment]
As someone who has played ninja both often recently and in the past something happened to the mapping where it either just is removed or isnt being mapped for some reason.

**Comment by dolgovmi** [comment]
Still lets you complete the objective so it's not too bad

**Comment by thebadman4662** [comment]
> Still lets you complete the objective so it's not too bad

Finally ninja is not forced to bomb arrivals. :trollface:

**Comment by deltanedas** [comment]
might as well just remove the objective and have the ninja bomb whatever they want, its not exactly hard to do

**Comment by GroggleG** [comment]
> ninjabomb doesnt have restrictions if you dont get the objective

+Fron what im seeing thats the problem, its not assigning the objective right

**Comment by UbaserB** [comment]
> might as well just remove the objective and have the ninja bomb whatever they want, its not exactly hard to do

Actually, i prefer the bombing location challenge. I would increase the radius since it's a bit stressful, but I still really enjoy it.

**Comment by GroggleG** [comment]
> > might as well just remove the objective and have the ninja bomb whatever they want, its not exactly hard to do
> 
> Actually, i prefer the bombing location challenge. I would increase the radius since it's a bit stressful, but I still really enjoy it.

It adds round variety which is what I strive for as it overall makes for a more fun game, I am sad that it broken right now.
