### ISSUE TITLE
The cool trailer music isn't in the game

### ISSUE THREAD

**Issue by FairlySadPanda** [space-wizards/space-station-14#28825]
## Description
be me
fairly mcpanda
on the discord
a cool custom bit of music is posted that's like three minutes long
it's what was used for the trailer
it sounds much poggers
it isn't in the game
why isn't it in the game
it would be perfect for a nukie countdown song

**Comment by ps3moira** [comment]
Isn't the reason no more music is being added is because there's a wait till someone makes a system where music can be played without it being directly in the games files?

**Comment by marboww** [comment]
#29345 i'm done, close it
