### ISSUE TITLE
Fire Axe sprite is not rotated

### ISSUE THREAD

**Issue by K-Dynamic** [space-wizards/space-station-14#28847]
## Description
Fireaxe sprite was updated to have 45 degree angle, the syndicate version (Fire Axe) was never resprited to match however.

https://github.com/space-wizards/space-station-14/pull/22805

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/20566341/21c011e8-73e1-4750-9413-83f25dd2b6c0)
Fireaxe (correctly rotated 45 degrees), Fire Axe (incorrectly straight)

**Additional context**
Should be easy enough practice for new contributors

**Comment by Flareguy** [comment]
Fixed by #28866
