### ISSUE TITLE
ID Card machines will now force the icon of a card to passenger if it has additional access

### ISSUE THREAD

**Issue by bruhmogus** [space-wizards/space-station-14#28851]
## Description
When you attempt to add additional access to a card, even if using job preset menu, it will force the icon to the passenger icon.

**Reproduction**
Step 1. Put both cards in a machine
Step 2. Attempt to add any access to the second card
Step 3. Put the second id in your ID slot
Step 4. Wear secglasses
Step 5. Die after seeing you're now greytiding

**Additional context**
Probably related to the default job preset change, it appears to always force to passenger no matter what

**Comment by TsjipTsjip** [comment]
Potentially related: `ShowSecurityIconsComponent` on admin ghosts appears to render the job icon of Head of Security as passenger all the time. (There is other roles for which this happens too, but I am unsure which at this time.)

**Comment by bruhmogus** [comment]
this got fixed, dunno when but it did, closing
