### ISSUE TITLE
Station announcements actively say the wrong direction?

### ISSUE THREAD

**Issue by dolgovmi** [space-wizards/space-station-14#28864]
## Description
If you look at the screenshot, it says southeast, while in reality it was northwest. Pretty sure it happens with tracking implants too and stuff. Seems to happen consistently with the nuke though, saying the complete opposite direction.

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/96251346/f595e0fe-43aa-485b-b535-07336800162d)

**Comment by deltanedas** [comment]
same with evac

**Comment by Tayrtahn** [comment]
Huh, sounds like someone subtracted the final position from the initial position instead of the other way around.
