### ISSUE TITLE
[QoL] Adding a To-do list for "requests" for Kitchen, Botany and Chemistry just like Cargo's

### ISSUE THREAD

**Issue by luizwritescode** [space-wizards/space-station-14#28862]
## Description
On busy shifts, it is easy to have 10+ crewmates on a given department asking for resources. It is actually hard to keep track and not something players should Alt+Tab to take note of somewhere else. Given the game has the functionality to keep "requests" for the Cargo department, why not add similar (but limited) functionality to other departments that handle crew requests?

This quality of life change is supposed to be tiny. Essentially it is a simple to-do list. The motivation is to just keep track and tally requests. Discussion on how this can be achieved with as little coding as possible is encouraged. 

This is not supposed to be a new feature, it is just an optional addition to the current gameloop for taking care of bounties and personal requests by crewmates. Even though the game is set during "space-age", crew only has pen and paper as tallying tools?

## Possible solution (core idea)
Ideally we don't want to create new entities like a "Request Computer" for each specific department. Just have a generic machine act as a literal To-do list for filling "Requests". It is way easier to implement if it's a "one-way" request system. Example:
1. Chef takes a verbal order at front desk of kitchen 
2. Fills out request to keep track of it
3. Finishes request and marks it as completed
4. Currently no need to "save" completed requests, it gets deleted, we only care about "uncompleted" requests
 
There is no need for other departments to check or modify this to-do list as it would deafeat the purpose of the front desk. It is just for the department's internal control.

### Elaborating on harder to implement concepts (optional)

- Have the to-do list entity machine in-take bounty papers and auto parse them into readable orders, instead of manually adding them
- For bigger departments, possibly add monitors with Read-Only display of current department orders for lower ranks to check, leaving inserting orders to higher ranks

**Comment by lzk228** [comment]
we already have boards for papers so

**Comment by IamVelcroboy** [comment]
A kitchen console that acts as an ordering system would be baller. Food made to order with actual interactions between chef/customers like the bartender has, so much better than counter full of cafeteria style food banquet.

**Comment by luizwritescode** [comment]
closing this because it is not an "issue" and will probably never be implemented. it is just cluttering issues page.
