### ISSUE TITLE
Incorrect listed numbers on .30 Ammunition Box

### ISSUE THREAD

**Issue by Graded5** [space-wizards/space-station-14#28879]
## Description
The .30 Ammunition box in the uplink is listed to have 50 rounds, but when you purchase it, it has 60 rounds.

**Reproduction**
- purchase a box of .30 ammo and inspect it

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/156205427/0ba0743b-c27d-4165-bb4b-74a4ad47fd8a)

**Additional context**

**Comment by Cojoke-dot** [comment]
already fixed by someone
![image](https://github.com/space-wizards/space-station-14/assets/83733158/e7878121-348d-4488-bcc0-7647485c8e7c)

**Comment by Cojoke-dot** [comment]
wait, thats me being silly, whatever, I'm making a fix
