### ISSUE TITLE
Screen shake effect acts strangely, sometimes allows you to see through walls/doors

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#2887]
Only tested with screenshake from toggling the gravgen, may work differently for other instances of screenshake

https://user-images.githubusercontent.com/19853115/103450135-173ebb00-4c6f-11eb-98af-d4ba35099e7c.mp4

**Comment by cyclowns** [comment]
slightly unrelated but theres no delay to toggling the gravgen so you can spam the button and its really annoying

**Comment by AJCM-git** [comment]
This isn't the case anymore.
