### ISSUE TITLE
You can walk through plastic flaps by vaulting a table

### ISSUE THREAD

**Issue by Graded5** [space-wizards/space-station-14#28877]
## Description
Title, the game lets you walk through plastic flaps while you are on a table.

**Reproduction**
- Place a table close to or next to a plastic flap
- Vault the table
- Attempt to walk through the plastic flap
- Congratulations, youve just broken into science or cargo with this simple trick 

**Screenshots**

**Additional context**

**Comment by lzk228** [comment]
there already the same issue

**Comment by beck-thompson** [comment]
wow dupe but its really old 😆
#9660
