### ISSUE TITLE
Harm mode direction is based on the rotation of space rather than the current player orientation.

### ISSUE THREAD

**Issue by Blackern5000** [space-wizards/space-station-14#28891]
## Description
Ever notice how the direction you face in harm mode sometimes changes based on strange points that don't make sense? It's because the station was rotated and you were oriented to it.
If you go into space, orient yourself, and turn on harm mode, you'll see that your harm mode rotation fully follows your cursor.
If you then go onto a grid rotated 45 degrees, orient yourself, and turn on harm mode, you'll see that your harm mode rotation acts incredible wonky with turns happening directly above you, below you, and directly to your sides rather than at a diagonal angle from you.

**Reproduction**
- Board a rotated grid
- Orient yourself
- Turn on harm
- Proceed to face _right_ when your cursor is at an 8 degree angle from your character

**Screenshots**
https://github.com/space-wizards/space-station-14/assets/140123969/6e742ad4-f34f-403a-98a5-104c8c8969d9

**Comment by Plykiya** [comment]
fascinating

**Comment by metalgearsloth** [comment]
https://github.com/space-wizards/space-station-14/issues/24636 dupe
