### ISSUE TITLE
As cleanbot there is no max range for cleaning puddles

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#28894]
1. play as cleanbot
2. try clean puddles
3. you can clean puddles on any range, even if you cannot see them

**Comment by deltanedas** [comment]
cleanbot godmode enabled :trollface:

**Comment by gorgogor** [comment]
skill issue

**Comment by lzk228** [comment]
hm, ill check again

**Comment by lzk228** [comment]
fixed, somehow
