### ISSUE TITLE
Admin feature request: Strip ui pocket visibility 

### ISSUE THREAD

**Issue by TurboTrackerss14** [space-wizards/space-station-14#28890]
## Description
Currently admins have to speedily strip and replace the items inside a players pockets to see what they have in their inventory.

Any perceptive player will see either the item disappear/reappear or see things like the internals action replace itself at the last point in the list, leading to "oh there is an admin watching me" behavior 

The Hidden entity feature really shouldn't exist for all seeing admins ™️ 
![image](https://github.com/space-wizards/space-station-14/assets/130304754/992086c7-e0a1-40e8-a7c9-83d0a9bd9b39)

**Comment by lzk228** [comment]
dupe #17300

**Comment by TurboTrackerss14** [comment]
Pain unimaginable.
