### ISSUE TITLE
Crit gasps show up in chat

### ISSUE THREAD

**Issue by Madformoose** [space-wizards/space-station-14#28900]
## Description
When a person or animal goes into crit and gasps, their gasps show in chat as they would if it was from an emote.

**Reproduction**
Crit a person or an animal, observe how their gasping shows up in chat.

**Additional context**
If there're a lot of crit creatures, their gasping fills the chat and makes it hard to keep track of actual important messages, for admins in aghost and such.

**Comment by bruhmogus** [comment]
im really hoping this isnt intentional because the entire server was lagging from how many crit gasps messages were happening
