### ISSUE TITLE
You can no longer change a character's outfit with admin tooling after the update to loadouts.

### ISSUE THREAD

**Issue by Madformoose** [space-wizards/space-station-14#28938]
## Description
Before the change to loadouts, you could give someone all the gear for a job really quickly with the set outfit verb. Now every item of clothing appears to be its own section in the menu and using an option not only only gives you that tiny subset of items, it also deletes anything else you might have had on.

**Reproduction**
Be an admin, use the set outfit verb, note that whatever you press will only give you one thing and delete anything else you might have had on, making giving people job outfits a huge pain in the ass.

**Additional context**
I think this has something to do with the loadout change a while back, as it was fine before then I recall. It works fine with CC official and ERT outfits though.

**Comment by lzk228** [comment]
dupe

**Comment by Tayrtahn** [comment]
Duplicated of #28785
