### ISSUE TITLE
Fire alarms and panic wire do not work at all.

### ISSUE THREAD

**Issue by thebadman4662** [space-wizards/space-station-14#28940]
## Description
For some reason activating fire alarms no longer triggers firelocks, as if it was emagged from start of shift.

Likewise panic wire on air alarms does nothing because connected firelocks do not want to close either.

**Reproduction**
A) Press button on fire alarm connected to firelocks
B) Snip panic wire on air alarm, probably other panic settings that atmos have access to also do not trigger firelocks.

**Comment by Partmedia** [comment]
Fixed by https://github.com/space-wizards/space-station-14/pull/29172
