### ISSUE TITLE
door remote rebalance idea

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#28950]
## Description
instead of a door remote just providing access or using all of your id access, it can do both

so captains remote would provide captain command maybe, and allow using any access cap id would have
then say service remote would provide service command and allow using specific service accesses maints etc

but if you have AA and a service remote then you still cant bolt caps room because service remote doesnt allow using it

would fix the antags getting one item from cap being able to bolt any door, theyd need both of them. and caps would actually be able to control """their""" station

**Comment by Golinth** [comment]
This was implemented in [26996] but was shot down by maintainers.

**Comment by deltanedas** [comment]
welp
