### ISSUE TITLE
character flickering and going invisible

### ISSUE THREAD

**Issue by Aranclanos** [space-wizards/space-station-14#2896]
![GIF 02-Jan-21 6-19-25 PM](https://user-images.githubusercontent.com/701959/103466832-79f38d80-4d27-11eb-9a05-c12d2006d0fe.gif)
just now on the steam game

**Comment by SweptWasTaken** [comment]
https://cdn.discordapp.com/attachments/675078881425752124/789627181982023740/weird_SS14_disappearing_thing.mp4 another example

**Comment by PaulRitter** [comment]
iirc when this was mentioned on discord, someone suggested it might have something to do with batching? I have 0 knowledge about the renderer, so im just gonna be paging @PJB3005

**Comment by PaulRitter** [comment]
ok this might also be due to pvs/networking. bumping the prio down for now
