### ISSUE TITLE
Throwing knives aren't blacklisted in the pneumatic cannon

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#28978]
## Description

#26628 was supposed to blacklist throwing knives from entering pneumatic cannon but i just heard from someone that they tested it and it doesn't work as intended.

It is FAR too powerful in the cannon right now, and is not how i intended it to be balanced around.

**Comment by UbaserB** [comment]
Just looked into it further #26878, there should still be some sort of nerf in the cannon such as allowing it to just one knife at a time.

**Comment by ElPidor** [comment]
This adjustment could potentially be the death knell for the art of utilizing the throwing knife. 
The predominant allure of the cannon, despite its occasional glitchiness in shooting in reverse, lies in the scripted cooldown for projectile throws.
 If a manual were to exist that provided instruction on advanced throwing techniques, the cannon would likely fall out of favor among those in the know.

**Comment by UbaserB** [comment]
really?

**Comment by lzk228** [comment]
blacklist was removed from pneumatic cannon, but its storage was reduced to 2x2, afaik

**Comment by ninruB** [comment]
> really?

The pneumatic cannon is pretty bad already it doesn't need *more* nerfs, that'd be borderline absurd.

**Comment by UbaserB** [comment]
I didnt realise that sorry
