### ISSUE TITLE
Bullets spawn behind you while running

### ISSUE THREAD

**Issue by Aranclanos** [space-wizards/space-station-14#2898]
![GIF 02-Jan-21 6-20-26 PM](https://user-images.githubusercontent.com/701959/103466844-95f72f00-4d27-11eb-99cb-b93a630f4b1c.gif)
worth to mention its 240ping

**Comment by Zumorica** [comment]
Due to #1839.

**Comment by AJCM-git** [comment]
We have gun prediction now
