### ISSUE TITLE
Small teleport while running against opening doors

### ISSUE THREAD

**Issue by Aranclanos** [space-wizards/space-station-14#2900]
![GIF 02-Jan-21 6-29-36 PM](https://user-images.githubusercontent.com/701959/103466935-83c9c080-4d28-11eb-9be3-99b677db0e02.gif)
playing on steam, 240ping

**Comment by Zumorica** [comment]
This is due to airlocks not being predicted

**Comment by metalgearsloth** [comment]
PR doesn't fix it at my ping but I was in the minority on that opinion 
![image](https://user-images.githubusercontent.com/31366439/107583756-8389e280-6c4f-11eb-9309-0532c5ec9f3f.png)

**Comment by DrSmugleaf** [comment]
> PR doesn't fix it at my ping but I was in the minority on that opinion
> ![image](https://user-images.githubusercontent.com/31366439/107583756-8389e280-6c4f-11eb-9309-0532c5ec9f3f.png)

There's prediction and then there's australian prediction
