### ISSUE TITLE
Mag boots let you walk in space now.

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#29029]
## Description
When you are walking around in space magboots magically walk around like you were on a grid.

**Reproduction**
- mag boots on
- walk around in space away from station.

**Screenshots**

https://github.com/space-wizards/space-station-14/assets/47093363/caff721e-d88d-4590-bccd-44dcb8cfd8fa

**Additional context**
NA

**Comment by Titian3** [comment]
Probably related to this new PR?
#29009

**Comment by UbaserB** [comment]
ABSOLUTELY NO WAY

**Comment by deltanedas** [comment]
t3 gravboots that keep this behaviour :trollface:

**Comment by Boaz1111** [comment]
honestly giving every discipline a type of timbs would be great
