### ISSUE TITLE
Throwing distance is weird

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#29053]
I did some testing and you cannot throw items exactly to your cursor
![image](https://github.com/space-wizards/space-station-14/assets/124214523/b48ff580-7bab-42b6-a3fe-2880177111df)
Here i was throwing one meatball per every marking and as you can see first 3 landed at same place, all other meatballs landed 1 tile further than my cursor

Earlier (like in feb 2023) i remember i could throw items exactly at the same place as my cursor

**Comment by Plykiya** [comment]
yeah, I experimented with this
the throwing system doesn't calculate some exact way to get the object from point A to point B, you throw with the exact same power at all distances and it kind of hopes for the best that the force works out at all points
