### ISSUE TITLE
Meteors spawn on the nukie planet

### ISSUE THREAD

**Issue by Vermidia** [space-wizards/space-station-14#29060]
## Description

The nukie planet can get hit by meteors. Usually it doesn't hit anything vital but it can damage the ship.

**Reproduction**

**Screenshots**

**Additional context**

**Comment by Kayek14** [comment]
Can confirm this happens. Had a round where the meteor was one tile off from destroying the shuttle console and thus round stalling the entire round. 
![image](https://github.com/space-wizards/space-station-14/assets/106507028/bf49c71b-6cc9-4501-bc76-24ec08e6cd9f)
