### ISSUE TITLE
Duplicate module update removed the ability to put multiple modules in a borg

### ISSUE THREAD

**Issue by bruhmogus** [space-wizards/space-station-14#29067]
## Description
The recent PR that made it so that borgs can't have two of the same module (this is without me checking) likely due to it checking the type of module and not the prototype? i havent checked but it is not possible to put any modules in a borg after the first

**Reproduction**
Step 1. Make a default borg
Step 2. Install tool module
Step 3. Try to install any other generic module like cable or GPS
Step 4. Realise robotics is useless
Step 5. Cry
Step 6. Declare war on Italy for the third time

**Screenshots**
![20240615200359_1](https://github.com/space-wizards/space-station-14/assets/104110869/98ddf86a-4d6f-473f-9de4-afda001df749)

**Additional context**
Again, the most likely reason I can come up with for how this happened is the duplicate check looking for the type of module (generic, medical, engineering) instead of the actual module prototype

**Comment by EmoGarbage404** [comment]
the fix is up already so wait for merge
