### ISSUE TITLE
Speech traits limit is bypassed by character import

### ISSUE THREAD

**Issue by LeIronGoat** [space-wizards/space-station-14#29075]
## Description
The trait system is designed to limit how many speech traits you can have by points, however, this system is bypassed by character imports.

**Reproduction**
Import a character save with extra accents added. You can see them selected in the character designer. Testing in game I was also able to activate more than two accents.

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/3360880/439ac040-bdb6-4fb7-99e7-ca4f4b6778b2)

**Additional context**
Does it matter? Eh. But still bypasses restrictions meant to exist nevertheless.

**Comment by metalgearsloth** [comment]
dupe.
