### ISSUE TITLE
Can't insert multple modules of same type into a borg

### ISSUE THREAD

**Issue by TheDoctor1977** [space-wizards/space-station-14#29073]
Attempting to do so gives the message "This module is already installed in this cyborg."
Seems to be a consequence of #28943 
The module tested was attempting to insert a GPS module into a borg with a tool module
![image](https://github.com/space-wizards/space-station-14/assets/108845723/aea3f3f2-5906-440b-8064-8444b65bd5a8)

**Comment by EmoGarbage404** [comment]
good shitpost but the fix was already merged
