### ISSUE TITLE
Cannot insert more than one cyborg module (even of different types)

### ISSUE THREAD

**Issue by LeIronGoat** [space-wizards/space-station-14#29077]
## Description
Cannot insert more than one cyborg module. Tried with normal and engineering chassis. Tried with basic tool and construction one in cyborg (two different types) failed. Tried a tool & extinguisher module in normal borg, also failed. Also experienced by another player at the same shift.

**Reproduction**
Put a module in a cyborg. Try inserting another. It says the borg already has it installed, despite it being a different module and matching chassis type.

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/3360880/2583c242-b3b1-4b2a-a486-3eea322655eb)

**Additional context**

**Comment by Plykiya** [comment]
fixed by https://github.com/space-wizards/space-station-14/pull/29038
