### ISSUE TITLE
The janitor's trolley gets stuck in the railing.

### ISSUE THREAD

**Issue by gogenych** [space-wizards/space-station-14#29089]
## Description

The janitor's cart has a much larger hitbox than the texture, which is why it gets stuck in such places
**Reproduction**

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/172140058/e0d4eb90-0197-4261-a055-61d22c4ca087)

**Additional context**

**Comment by IProduceWidgets** [comment]
Closing since this looks like the wrong repo and there appears to be an issue on the correct one.
