### ISSUE TITLE
Ghosts are rendered below some effects like fire

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#2909]
https://user-images.githubusercontent.com/19853115/103476928-ffeaf500-4d76-11eb-8b1b-c95fd1fd9755.mp4

**Comment by metalgearsloth** [comment]
Looks like it might be intended given ghosts have a drawdepth lower than world-space overlays (though the gas-tile overlay doesn't use that specific DrawDepth) https://github.com/space-wizards/space-station-14/blob/master/Content.Shared/GameObjects/DrawDepth.cs

At the very least if a change were being made I'd hold off working on this if https://github.com/space-wizards/RobustToolbox/pull/1387 ever gets merged given it'll change world-space overlays

**Comment by SweptWasTaken** [comment]
Since https://github.com/space-wizards/RobustToolbox/pull/1387 got merged can this be worked on?
