### ISSUE TITLE
Moon boots should allow you to use jetpacks in gravity

### ISSUE THREAD

**Issue by WarMechanic** [space-wizards/space-station-14#29090]
## Description

This would make moon boots a super nice research for engineers that perma-suit.

**Comment by MilenVolf** [comment]
I think the same could be applied to usual jetpacks. Would be pretty cool to use jetpack on the station that has no gravity.

**Comment by Emisse** [comment]
it is intended that this doesnt happen for nukie balance

**Comment by MilenVolf** [comment]
> it is intended that this doesnt happen for nukie balance

Got it.
