### ISSUE TITLE
Extended fails to start under 25 players due to meteors

### ISSUE THREAD

**Issue by VasilisThePikachu** [space-wizards/space-station-14#29106]
#28974 seemed to have accidentally made extended require 25 players due to meteors requiring it. 

https://github.com/space-wizards/space-station-14/pull/28974/files#diff-0b2783a8b6f2617fdebc3dcf1a266fb09be2ddd7f9bfc4e587f89c9e62fe1b58R33-R35

**Comment by EmoGarbage404** [comment]
Will be fixed by #29044
