### ISSUE TITLE
Gas miners should be indestructible.

### ISSUE THREAD

**Issue by ninruB** [space-wizards/space-station-14#29107]
## Description

Right now gas miners have [100HP](https://github.com/space-wizards/space-station-14/blob/ee2769ed9f4d075bb280d4c86c6ccf7c2f2fe741/Resources/Prototypes/Entities/Structures/Piping/Atmospherics/miners.yml#L19) each and are not constructible, along with the fact that they are one of a kind roundstart and their functionality isn't replaceable by any other implemented mechanic, leads to the problem of having one broken O2/N2 miner permanently gimping atmos and all of distro for the rest of the round and only being solvable by admin intervention.

## The Why
Sabotaging gas miners as an antag is kind of a no-go in the current ruleset, and isn't really fun or engaging for either side, while being disproportionally strong as a sabotage strategy.

Atmos miners are irreplaceable, ordering canisters from cargo/salvage isn't feasible at all because the amount of gas in them is pitiful to the degree where you need a dozen to refill a decently sized room, now imagine a large-scale spacing from something like meteors and the station is basically doomed to collapse without admin intervention.

This is one of the few cases where I've seen admin intervention being administered, so why bother the admins when miners can just be indestructible?

## The solution(?)

Making gas miners not break from damage is an easy one and is very much so implied, but this still leaves issues like the gas miner being removed from the tile by some means or the tile the gas miner is on vanishing.

Ideally(?) we don't have miners at all but that's far-fetched and I think a bandaid like making miners more robust is a pretty good thing to have for now.

**Comment by Radezolid** [comment]
Realistically how often do they break? And as long as you have the CO2 miner still you can make oxygen using a recycler.
I would love if stations stopped using O2 miners and forcing more the recycler to be used.

**Comment by deltanedas** [comment]
because of heaters being dogshit you need to run a burn chamber for recycler to have more than 5% uptime and while yes it works it still needs a lot of oxygen to bootstrap

**Comment by MACMAN2003** [comment]
one of the problems of making them indestructible is that if they get disconnected from the station, they'll be effectively destroyed because there's no way to connect pipes across grids

**Comment by deltanedas** [comment]
make them reanchorable (but not unanchorable)

**Comment by WarMechanic** [comment]
the plasma gas miner in medbay :trollface:

**Comment by slarticodefast** [comment]
I agree that they should be indestructible. I was playing on grasshopper recently to teach new players and a few consecutive rounds each time they would get destroyed by someone resulting in the whole station suffocating. I am not sure if it was a raider or just an antagonist. While they could also just sabotage some pipes, this is something atmos can repair at least.

>the plasma gas miner in medbay

The plasma miner got removed and the chamber has a finite amount in it.

**Comment by ampethamine** [comment]
This is a big issue considering the recent meteor rework too #29108

**Comment by lzk228** [comment]
btw Jezithyr said
![image](https://github.com/space-wizards/space-station-14/assets/124214523/dec9979b-09b3-4890-ac31-4b053dbba83e)
https://discord.com/channels/310555209753690112/310555209753690112/1252272368349614225
so i think they also will discuss gas miners destructibility
