### ISSUE TITLE
Random sentence event resurrection 

### ISSUE THREAD

**Issue by TheShuEd** [space-wizards/space-station-14#29110]
## Description

In #28982 we remove this event from game.
it needs to be returned with some changes:
- remove all vending machines and other boring roles that do not provide any gameplay to the player from the list of possible event targets
- limit the event area to a station. No sentinent bots on centcom

**Comment by Psychpsyo** [comment]
I feel like instead of removing vending machines, it'd be better to just pick a type of thing to give sentience to, then picking a random one from those.
That way, a sentient vending machine is just as likely as a sentient clean bot.

**Comment by Psychpsyo** [comment]
Looking into improving this now.
