### ISSUE TITLE
Raffle Is Unfair Towards Long Waiting Ghosts

### ISSUE THREAD

**Issue by TheOneWhoIsManyFrame** [space-wizards/space-station-14#29119]
Raffle should provide more weight to people who've been dead for longer time over the ones whos recently deceased.

**Comment by TheOneWhoIsManyFrame** [comment]
I propose the following change
- People who started the raffle have slightly more weight in it
- People who's been dead for a long time have more weight in it

**Comment by BolloTea** [comment]
RoleHunter :trollface:

**Comment by TheOneWhoIsManyFrame** [comment]
> RoleHunter :trollface:

role hunter being someone new and wants to try out a role for once

**Comment by TheOneWhoIsManyFrame** [comment]
it is completely fair for someone who been ghost a longer time to have higher chance of getting a role? Or what youre supposed to just quit after being round removed?

**Comment by BolloTea** [comment]
Hmm, I apologize.  But, do not forget that many people specifically wait for convenient roles in ghosts from the beginning of the round or prescribe suicide/ghost after about 40 minutes of playing as a passenger

**Comment by TheOneWhoIsManyFrame** [comment]
> Hmm, I apologize. But, do not forget that many people specifically wait for convenient roles in ghosts from the beginning of the round or prescribe suicide/ghost after about 40 minutes of playing as a passenger

It is also fair for people waiting for it to get it though? The longer theyre waiting the more reason they should get the role over the recently dead

**Comment by BolloTea** [comment]
The problem is different.  Many people deliberately go into ghosts and it happens that 20 people with 50 online sit in ghosts for the sake of the role of an operative

**Comment by BolloTea** [comment]
Giving the person who started the lottery a little more chances sounds quite fair, so I completely agree with you here

**Comment by TheOneWhoIsManyFrame** [comment]
A system thats less rng dependent would be nice, like the longer someone goes without getting certain role, they gain higher chances (but thatd involve effort coding it)

**Comment by QuietlyWhisper** [comment]
Better weights for longer times spent as a ghost would be okay probably, but whoever snipes the raffle first should not be a factor, that is not in fact fair.

Alternatively we also could drop raffling entirely and implement xeno role queue as cm13 intended, which is the most likely solution to this.

**Comment by TheOneWhoIsManyFrame** [comment]
> Better weights for longer times spent as a ghost would be okay probably, but whoever snipes the raffle first should not be a factor, that is not in fact fair.
> 
> Alternatively we also could drop raffling entirely and implement xeno role queue as cm13 intended, which is the most likely solution to this.
Idk cm13 but role queue sounds great

**Comment by deltanedas** [comment]
role queue would be great for fish so theres no raffle or sniping just ready up to be fish

**Comment by TheOneWhoIsManyFrame** [comment]
I hope rng factor is removed in the near future and so everyone get a fair chance at the role

**Comment by TheOneWhoIsManyFrame** [comment]
> I had suggested this in the original raffle PR as well #26629. The reason it was rejected was that in SS13 people would abuse this to farm ghost roles.
> 
> > best way is to add a tracker of time since someone gotten X role, give it to one with the highest time
> 
> Here people could use multiple accounts to log on different servers and AFK for a while to get a maximal chance for the role.

isnt there an anti afk system in place?

**Comment by mirrorcult** [comment]
mald issue, the raffling system making it harder for people to afk from the start of the round and snipe ghost roles is intentional, you should not be handed ghost roles because you clicked on the button first

**Comment by QuietlyWhisper** [comment]
I thought this was an issue in cm my bad
