### ISSUE TITLE
Cyborgs can only have one module after most recent update

### ISSUE THREAD

**Issue by SkippyMcSkips** [space-wizards/space-station-14#29113]
## Description
Title. When you try to load any kind of compatible module after an initial one, a tool-tip pops up saying the Borg already has that module, even when it doesn't.

**Reproduction**
Build/find a borg
Unlock it
Open panel
Attempt to insert additional modules

**Comment by EmoGarbage404** [comment]
was this reproduced as of today? the fix for this bug should've gone live this morning

**Comment by SkippyMcSkips** [comment]
> was this reproduced as of today? the fix for this bug should've gone live this morning

I was playing on a server that syncs with upstream once a day, so depending on when it went live upstream the server may not have received it. What time was the fix pushed? I can check with the server admins if the sync happened before or after.

**Comment by EmoGarbage404** [comment]
> I was playing on a server that syncs with upstream once a day, so depending on when it went live upstream the server may not have received it. What time was the fix pushed? I can check with the server admins if the sync happened before or after.

~ 6 AM EST or 10 AM UTC

**Comment by SkippyMcSkips** [comment]
Ah that'll be it then, this server merges earlier in the day. So should hopefully be fixed tomorrow after the next merge.
