### ISSUE TITLE
People are randomly getting revolvers

### ISSUE THREAD

**Issue by XxSWAG-MASTER-OVERLORDxX** [space-wizards/space-station-14#29148]
## Description
Everything from janitors, doctors, security and at any point in the round it seems too.
the only thing that can be tracked between cases is that it appears in their pockets.

No clue what could be causing inspectors to spontaneously appear.

**Comment by liltenhead** [comment]
Garbage man day

**Comment by mirrorcult** [comment]
its just janitors its garbage day

**Comment by Slava0135** [comment]
Guys really think they are on America Station 14 :eagle:
