### ISSUE TITLE
ChemVend jugs names issue

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#29140]
![image](https://github.com/space-wizards/space-station-14/assets/124214523/35824112-c8ec-43d8-a6e3-19c4f7c3d99d)
#29137

**Comment by Tayrtahn** [comment]
Aw man.

**Comment by lzk228** [comment]
i was thinking about adding prototype suffix in this menu, if prototype has specific component, but i couldnt figure this out
here is some absolutely not working WIP 
https://github.com/lzk228/space-station-15/commit/2c144d7ed1d4c4fe7a4f3b2c9778247f251433df

**Comment by Brandon-Huu** [comment]
> Aw man.

Did you not test your PR?

**Comment by Tayrtahn** [comment]
> Did you not test your PR?

I did, but apparently not thoroughly enough. It fixed the issue with the ChemMaster, but created this issue with the ChemVend.

I have a plan for how to fix this, and I'll give it a shot tomorrow.
