### ISSUE TITLE
Lanterns blink forever without battery, switched off

### ISSUE THREAD

**Issue by RadioAndrea** [space-wizards/space-station-14#29144]
## Description
Lanterns blink forever after running out of battery. 

**Reproduction**
Be one of 3 people ever to pick up a lantern and use it until it is fully depleted and enters the flashing stage. 

Wait a while and notice it keeps blinking. 

Turn off the lantern and notice that your dead, off lantern is still blinking. 

Throw/drop your lantern and it blinks for all eternity. 

**Screenshots**
https://github.com/space-wizards/space-station-14/assets/7978519/37e8c44f-0da8-4302-a88e-a721cee3e564

**Additional context**
Encountered on Salamander, around 2300 UTC and on, Jun 17th

**Comment by MrMothman** [comment]
I'll give this a look

**Comment by slarticodefast** [comment]
I think this is a problem with all flashlights currently. Even happened to me as a borg when my battery was empty.

**Comment by LittleNyanCat** [comment]
Can confirm it happens on the blue flashlights as well. 

I thought this was an intended feature (to help you find it in the dark), since it's only a small radius light and not the large light beam the flashlight usually produces when turned on.

**Comment by RadioAndrea** [comment]
Video added to show issue

**Comment by diraven** [comment]
Yes, same with borgs and blue flashlights.
