### ISSUE TITLE
Quantum inverter to microwave inventory

### ISSUE THREAD

**Issue by XxSWAG-MASTER-OVERLORDxX** [space-wizards/space-station-14#29157]
## Description
allows you to place yourself into a microwave or any other thing that accepts QSI's

**Reproduction**
1.Place QSI in microwave
2.Use QSI to swap places
3.Now in microwave

This can also be done in a way to remove someone from the round
If they jump into a crate that is QSIed into a microwave they will be trapped forever (unless they have a screwdriver)

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
this can be done with any item that has an internal storage and is able to be moved (unanchored)
![image](https://github.com/space-wizards/space-station-14/assets/151447893/ba19fa0a-6d6f-4d4a-a82d-f1b8f0256b3e)

**Comment by deltanedas** [comment]
RemoveFromContainer gameplay
