### ISSUE TITLE
QSI Pipe Sealing People

### ISSUE THREAD

**Issue by Cojoke-dot** [space-wizards/space-station-14#29158]
## Description

Seal yourself in a pipe forever with a qsi
**Reproduction**

1. flush I linked qsi
2. swap
3. drop qsi in hand
4. get out of pipe and use qsi
5. you are now forever sealed in the pipe that you dropped the qsi in
**Screenshots**

https://github.com/space-wizards/space-station-14/assets/83733158/e021d153-df68-491a-8d32-b9dfb372f7f7

**Additional context**

Making a PR to disable the qsi till less buggy, I spent 5 minutes to find this bug without any prior knowledge of this kind of interaction

**Comment by metalgearsloth** [comment]
Make it check CanInsert on the target container.

**Comment by metalgearsloth** [comment]
Dupe https://github.com/space-wizards/space-station-14/issues/29157
