### ISSUE TITLE
Salvage on Marathon doesn't get oxygen/nitrogen tanks

### ISSUE THREAD

**Issue by Blackern5000** [space-wizards/space-station-14#29171]
## Description
Salvage on marathon has to either hope cargo spawns with an oxygen crate, or go hunting for some in maints.

**Reproduction**
- Open server
- loadmap 2 /Maps/marathon.yml
- Go to salvage
- Where oxygen?

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/140123969/21778bc2-6ef3-4b57-947a-143d91f4c3de)

**Comment by HelpTheSteak** [comment]
I think a very easy fix to this is just to change the salvage locker to have o2 tanks on all maps. Slimes don't really need nitrogen tanks since they take so little airloss so it isn't a big deal for them.

**Comment by Erisfiregamer1** [comment]
Maybe move the gas tank dispenser in the bottom left corner to Salvage's room?
