### ISSUE TITLE
Every single door on the meta evac shuttle is all-access

### ISSUE THREAD

**Issue by Blackern5000** [space-wizards/space-station-14#29188]
## Description
Mapper did a whoopsie and forgot to use the locked versions. Any random passenger or clown can run into the bridge/sec and cause problems.

**Reproduction**
- Play meta station
- Wait for evac
- Watch as 8 self-antags run into sec to uncuff the syndie who gibbed the QM.

**Comment by Brandon-Huu** [comment]
Replicated in dev environment. 
I will work on this.
