### ISSUE TITLE
Rat Controlled Hammy

### ISSUE THREAD

**Issue by Cojoke-dot** [space-wizards/space-station-14#29189]
## Description

Not entirely sure if this is intended or not, but you can make a rat control Hammy body with the new chef hat functions. It's funny but also just does not make sense size-wise.
**Reproduction**

1. Put a mouse in chefs hat
2. Put a hat on Hamlet/any other animals head
3. The mouse can now control that animal

**Screenshots**

https://github.com/space-wizards/space-station-14/assets/83733158/7803ac9f-0b9d-4fde-8e5f-1ca3ca066793

**Comment by Simyon264** [comment]
bug of the year

**Comment by Tayrtahn** [comment]
I noticed this while testing and intentionally didn't prevent it. 

If people want, I can add a check to prevent it, but I think it's kinda funny.

**Comment by MACMAN2003** [comment]
hamptertouille

**Comment by mirrorcult** [comment]
this is not an issue lol this is what the game is about baby

**Comment by LordEclipse** [comment]
Make this into an actual feature

**Comment by deltanedas** [comment]
mouse controlled medibot borg and mannequin :trollface:
