### ISSUE TITLE
Prisoner Jumpskirt female mask is still broken

### ISSUE THREAD

**Issue by bruhmogus** [space-wizards/space-station-14#29196]
## Description
Despite the fix to female masks for jumpskirts, the prisoner jumpskirt wasn't fixed

**Reproduction**
Step 1. Play female character
Step 2. Get arrested for tax evasion
Step 3. Wear prisoner jumpskirt

**Screenshots**
![20240618223039_1](https://github.com/space-wizards/space-station-14/assets/104110869/5b09732f-af23-4ea5-87df-a7935bc1bbbf)

**Additional context**
Prisoner jumpskirts probably borrowed from the orange for their sprite, then got overlooked in the sprite fix

**Comment by Flareguy** [comment]
Very likely fixed by #30093, considering displacement maps work on layered sprites.

**Comment by beck-thompson** [comment]
![image](https://github.com/user-attachments/assets/ccdc4a96-79e6-4f23-a8e7-a7f54fd544c7)

Is this fixed? I can't tell...

**Comment by lzk228** [comment]
yes it is, was some kind of layering issue
