### ISSUE TITLE
Fix remaining DataReadWriteFunction

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#2920]
Looks like the pr got most of them but there's still some floating around, e.g.

`serializer.DataField(this, mod => SpeedModifier, "speed", 1);`

Should be
`serializer.DataField(this, mod => mod.SpeedModifier, "speed", 1);`

**Comment by PaulRitter** [comment]
don't bother cause serv3 will make this deprecated. do keep it open tho, i will close this if all goes well when i refactor content

**Comment by metalgearsloth** [comment]
You're right I'm dumb
