### ISSUE TITLE
Deconstruction examine text is worded badly

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#2922]
![image](https://user-images.githubusercontent.com/19853115/103692592-3716fd00-4f55-11eb-9309-aa774622753a.png)

"To create start" (presumably comes from name of graph node) should probably read like "To begin deconstruction". Or the node can be given a better name

**Comment by PaulRitter** [comment]
@Zumorica

**Comment by nigel-gott** [comment]
Looks like this has already been fixed/changed and this issue can be closed? 

This is what the same tooltip now looks like, no longer with the confusing "To create start..." text

![image](https://user-images.githubusercontent.com/820678/183296156-4832da3f-879a-4d33-a473-7f58ccc8218b.png)

**Comment by mirrorcult** [comment]
yes, because you haven't used the verb to show the graph steps

**Comment by Jrpl** [comment]
This appears to be fixed.
![image_2024-01-12_003631708](https://github.com/space-wizards/space-station-14/assets/30051988/8edb1bcb-b122-4c89-9724-4c380ebc5f96)
