### ISSUE TITLE
Asteroid events still happen in greenshift

### ISSUE THREAD

**Issue by Madformoose** [space-wizards/space-station-14#29233]
## Description
In greenshift, asteroid events still happen, which is not a good thing if you like your station untarnished by entropy for when you need to do something

**Reproduction**
Start a round in greenshift. Wait. Eventually observe asteroids slowly destroying your station. Cry. Make an issue on github

**Comment by bruhmogus** [comment]
can confirm, additional context: this happened on greenshift, not secretgreenshift. might be fixable by just making the meteor scheduler not start in greenshift and secretgreenshift
