### ISSUE TITLE
There should be a specail syndicate mouse for chef 

### ISSUE THREAD

**Issue by ElPidor** [space-wizards/space-station-14#29253]
Since mouse can pilot humans, it's possible to imagine a scenario where you can buy a special "Mouse Operative Agent" package that includes a chef's hat and a mouse. This package could come with either a standard chef's hat or a unique, special hat designed specifically for the mouse operative agent.

The interesting aspect of this concept is that unlike regular mice, operative mice have the ability to use inventory and hands, making them unique and humorous characters. Here's an example of how the process could work:
_The item might be job restricted only for chefs_
1 Buy the mouse operative agent package,
2 Cuff a person and give them guns and muzzle
3 The mouse kills someone, then ejects from the head and disappears.
4 As a reward, give the mouse operative a piece of cheese.
![image](https://github.com/space-wizards/space-station-14/assets/49343726/574d5627-251a-4554-b078-4f0b6b2497d8)

**Comment by Hmeister-real** [comment]
Delta-V already has funny syndie mice

**Comment by GoodWheatley** [comment]
This isn’t the place for feature requests.

**Comment by Simyon264** [comment]
![image](https://github.com/space-wizards/space-station-14/assets/63975668/ddf59f21-00ad-4fd6-ac6d-4e89e6721ee0)

Theres a label for those...?

**Comment by ShadowCommander** [comment]
We're moving feature requests to the forums and Discord to be hashed out more easily and to keep the issue list as more of what needs to be worked on.

Currently the only approved usage of the label is for issues created for admin tooling, map tooling, or features discussed and decided by maintainers.
