### ISSUE TITLE
Midround initial infected have no icons or character menu information

### ISSUE THREAD

**Issue by slarticodefast** [space-wizards/space-station-14#29254]
## Description
Midround initial infected do not see the II icons above their heads.

The briefing is shown in the chat as intended, but not in the character menu where antag status is usually shown.
![ii](https://github.com/space-wizards/space-station-14/assets/161409025/ab1bd67f-af2c-473f-bca1-464487fdd77a)

**Reproduction**
Hard to test on a local server since you cannot run the ZombieOutbreak event without enough players. It happened to me twice on wizden servers though.

**Additional context**
I think in the [event](https://github.com/space-wizards/space-station-14/blob/master/Resources/Prototypes/GameRules/events.yml) the [InitialInfectedComponent ](https://github.com/space-wizards/space-station-14/blob/master/Content.Shared/Zombies/InitialInfectedComponent.cs)might be missing. Anyone know how to properly test this event without running a bunch of clients?

**Comment by Tayrtahn** [comment]
For local testing, you can remove the minimum players requirement from the game rule yml.

**Comment by slarticodefast** [comment]
Thanks, I was able to fix it. Now I only need to add the missing briefing.
