### ISSUE TITLE
Robotics cyborg parts proper ordering

### ISSUE THREAD

**Issue by diraven** [space-wizards/space-station-14#29270]
## Description

Change
![image](https://github.com/space-wizards/space-station-14/assets/108279/386ca014-e20d-44b1-bc05-0021966305df)

To
![image](https://github.com/space-wizards/space-station-14/assets/108279/72b78bda-f815-41ac-9e25-91cb6f8844ed)

Pretty much like the rest of borg types.

**Comment by deltanedas** [comment]
borg arm and leg have different ids because they used to exist for drones and shit before borging existed so it trolls the sorting

**Comment by diraven** [comment]
Sorting seems to work fine if names are changed to be consistent. Ordering happens by name, not by id. See PR for details.

**Comment by Brandon-Huu** [comment]
damn, I was too slow
