### ISSUE TITLE
Wardens Cap does not look right

### ISSUE THREAD

**Issue by XxSWAG-MASTER-OVERLORDxX** [space-wizards/space-station-14#29286]
## Description
As it currently is there is a black band that's going through the sprite that's not meant to be there

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/151447893/baf380dd-f7e3-40f8-92cf-410d14cd3778)
![image](https://github.com/space-wizards/space-station-14/assets/151447893/4c14aad1-bce0-4ee6-8ad4-5431f20ef662)
![image](https://github.com/space-wizards/space-station-14/assets/151447893/9f09ea5c-4eac-4fdb-bc47-3b7db5e965a6)

**Comment by TeaMakiNL** [comment]
Made a new asset
![equipped-HELMET](https://github.com/user-attachments/assets/d4780bc6-c6a0-460c-a370-5bfd698cfe2b)

**Comment by DieselMohawk** [comment]
#32253
