### ISSUE TITLE
Remove .vscode from version control

### ISSUE THREAD

**Issue by diraven** [space-wizards/space-station-14#29285]
## Description
[.vscode settings](https://github.com/space-wizards/space-station-14/blob/master/.vscode/settings.json) being in VCS forces everybody to use them and prevents customization. Workspace settings [override](https://code.visualstudio.com/docs/getstarted/settings#_settings-precedence) user settings. Which means you effectively can't customize workspace settings for this project at all without your changes ending up in VCS, which is very likely an undesirable outcome.

I believe the right thing to do here would be:

* Renaming .vscode to something like sample.vscode in VCS and ignoring .vscode itself.
* Possibly also adding automatic copying of sample.vscode to .vscode if .vscode does not exist into [RUN_THIS.py](https://github.com/space-wizards/space-station-14/blob/master/RUN_THIS.py).

That way we can still distribute configuration changes/templates if need be with devs retaining the ability to change their local workspace settings including settings.json, tasks.json and launch.json.

**Comment by diraven** [comment]
I'll make a PR for it later if there are no hard objections to this.

**Comment by PJB3005** [comment]
Doesn't VSCode have a "default workspace settings" system exactly for this purpose?

**Comment by osjarw** [comment]
Not an expert on these particular settings, but stuff like formatter settings definitely should belong in the workspace settings.

**Comment by diraven** [comment]
> Doesn't VSCode have a "default workspace settings" system exactly for this purpose?

Didn't find such functionality in VSCode. Only thing I find is [this ancient issue](https://github.com/microsoft/vscode/issues/40233), which was not worked on yet it seems.

> Not an expert on these particular settings, but stuff like formatter settings definitely should belong in the workspace settings.

It probably should. But that's a bit out of scope for this issue.
