### ISSUE TITLE
Remove Passable collision layer

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#2928]
The only reason it exists is for the singulo's area queries but it's a dirty hack that ideally shouldn't exist.

**Comment by PaulRitter** [comment]
What would be an alternative for the singulo to collide with passable objects like items?

**Comment by metalgearsloth** [comment]
Probably better to check all entities in range of the singulo rather than physics.

The main reason for this is stuff like items will have its collision turned off when not moving and (as an optimisation soon) won't be returned from physics queries.

**Comment by PaulRitter** [comment]
> 
> 
> Probably better to check all entities in range of the singulo rather than physics.
> 
> The main reason for this is stuff like items will have its collision turned off when not moving and (as an optimisation soon) won't be returned from physics queries.

this again will have problems like ghosts being sucked in :/ Its a tricky issue tbh, but i agree that it should probably not be handled through physics

**Comment by Zumorica** [comment]
(We need a component for entities that can be sucked into singulos imo)

**Comment by GraniteSidewalk** [comment]
I don't see why we would need that... but if we really do, make it the inverse. Can't be sucked component.

**Comment by Zumorica** [comment]
> I don't see why we would need that... but if we really do, make it the inverse. Can't be sucked component.

No, that's bad. The default should be to NOT interact with the singulo in any form. What if someone forgets to add the "can't be sucked into singulo" component to spawn points? Late joins break? Yeah, this should be opt-in.

**Comment by Zumorica** [comment]
Also, fyi atmos has its own equivalent for this, called `MovedByPressureComponent`

**Comment by PaulRitter** [comment]
Yeah, a component for being affected by the singulo is probably the best course of action here

**Comment by metalgearsloth** [comment]
> 
> 
> Probably better to check all entities in range of the singulo rather than physics.

I looked at singulo code and turns out it actually does check all entities in range regardless, so you should just be able to drop the component in place.
