### ISSUE TITLE
All jugs in chemvend look the same

### ISSUE THREAD

**Issue by XxSWAG-MASTER-OVERLORDxX** [space-wizards/space-station-14#29291]
## Description
All the jugs in the chemvend are labeled "jug" and there is no way to tell what chem they have inside

**Screenshots**
Hmm, today i will get carbon from the chemvend :godo:
![image](https://github.com/space-wizards/space-station-14/assets/151447893/5b685c2d-ad3d-4d2e-977c-2396bac8bcf4)

**Comment by lzk228** [comment]
dupe #29140

**Comment by thebadman4662** [comment]
No worries, fix is waiting... for something. https://github.com/space-wizards/space-station-14/pull/29178

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
> dupe #29140

guh, forgive me ill close this as a dupe and lets hope it gets fixed soon
