### ISSUE TITLE
Turn off netsync for server-only components

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#2930]
It only functions as a minor PVS optimisation but should still be done. Pretty much nothing is doing it atm.

Someone just needs to go through and set the bool (NetSyncEnabled) on the relevant components to false.

**Comment by SweptWasTaken** [comment]
Will do this in the morning.

**Comment by metalgearsloth** [comment]
@Acruid do you think it'd be worthwhile automating this with a source generator or the likes?
