### ISSUE TITLE
did not spawn with a survival box as bartender

### ISSUE THREAD

**Issue by Dutch-VanDerLinde** [space-wizards/space-station-14#29300]
reproduction:
pick bartender
open bag, no survival box

**Comment by Errant-4** [comment]
It worked prior to release, and I couldn't repro now either with any species. I need more data to fix this but I don't know what the data I need _is_...
What species were you?

**Comment by Tayrtahn** [comment]
Hopefully fixed by #29336. Please let us know if it happens again!

**Comment by Dutch-VanDerLinde** [comment]
> It worked prior to release, and I couldn't repro now either with any species. I need more data to fix this but I don't know what the data I need _is_... What species were you? Does it happen every time with a specific character/loadout? What backpack-type and optional picks is the loadout using?

happens for every job, but its like a 50/50 chance, sometimes i spawn with a box, othertimes i dont

**Comment by Dutch-VanDerLinde** [comment]
will see if this issue is still valid

**Comment by Errant-4** [comment]
You are the first person to say it actually changes on the same character/loadout, and if that is the case, then I probably did not fix it... But we'll see after tomorrow's publish at noon
