### ISSUE TITLE
wieldable guns description is kinda lying

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#29316]
it says `This weapon has improved accuracy when wielded.` but you even cant shot if its not wielded

**Comment by Dutch-VanDerLinde** [comment]
``GunWieldBonusComponent`` has this field
![image](https://github.com/space-wizards/space-station-14/assets/45323883/a9c525f5-869a-44a8-ab76-d08727006a82)


so if you want to make shotguns have a text such as "This weapon can only be fired when wielded." then you could
