### ISSUE TITLE
Brigmedic ID card lacks any access

### ISSUE THREAD

**Issue by bruhmogus** [space-wizards/space-station-14#29339]
## Description
The Brigmedic ID card lacks both an title and accesses.

**Reproduction**
1. Spawn brigmedic ID
2. Try to open your OWN locker
3. Die

**Screenshots**
![20240622055741_1](https://github.com/space-wizards/space-station-14/assets/104110869/e188cb61-a90c-4725-aa51-4023e158dfb4)

**Additional context**
It's probably because it's basically inattainable

**Comment by deltanedas** [comment]
brig medic is unused

**Comment by PJB3005** [comment]
Not attainable, not a bug.
