### ISSUE TITLE
Explode-smiting a nukie makes the station announce all nukies are defeated.

### ISSUE THREAD

**Issue by Keer-Sar** [space-wizards/space-station-14#29352]
## Description

I was an aghost on a nukie round. They did not announce war. The operator was AFK from the round-start. They didn't move or talk or interact at all but still had a connection to the server. I spawned in a nukie reinforcement radio and once the ghost role was filled I explode-smited the AFK operator. As soon as the operator exploded, the announcement for all nuclear threats being eliminated was announced and a 3 minute shuttle was called.

**Reproduction**

1.  Gamemode must be Nukeops
2.  Have an operative be AFK (not ssd)
3.  Call in a nukie reinforcement
3.  Use Explode smite on AFK  operative after the reinforcement spawns

**Screenshots**

Round ID is 57308 if you wish to see the round replay.

**Additional context**

**Comment by Tayrtahn** [comment]
I'm going to guess that the issue isn't the explode smite, but rather that reinforcements might not be getting tracked for the round end condition. Needs testing though.

**Comment by Kayek14** [comment]
I had this happen one round where the nukies killed a reinforcement on their planet.

This also just happened on the round 58117. Apparently meators stuck the nukie ship, killed the reinforicement borg and the crew got the message that all nukies were defeated. 

![image](https://github.com/space-wizards/space-station-14/assets/106507028/97f9b0fa-7378-44f0-94db-77a76af736d9)

**Comment by Tayrtahn** [comment]
Steps to replicate in local dev: 

- set the minimum players for nukeops to 2 (edit the YAML)
- launch server and two clients
- `golobby`
- `addgamerule NukeOps
- enable nukeops agents in both clients' antag preferences
- ready up both clients
- `startround`
- both clients should spawn as nukies at the nukie base
- delete or kill either nukie
- round ends
