### ISSUE TITLE
Chef book name is a bit meta

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#29374]
## Description

"Chef gaming" implies that you playing chef is "gaming", uhh it's pretty weird for something that's supposed to be IC. Not the most important issue, just something small I noticed.

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/134914314/12df53c2-db0a-4359-83e4-5fed2f661124)

**Comment by ElPidor** [comment]
its just funny description, why not, you have power gamer drink or smth :trollface:

**Comment by KonstantinAngelov** [comment]
what new name whuld you like?

**Comment by deltanedas** [comment]
How To Cook For Forty Spacemen

**Comment by Tayrtahn** [comment]
To Serve Man
