### ISSUE TITLE
Players become syndicate agents after 5 minutes instead of roundstart antag

### ISSUE THREAD

**Issue by ElPidor** [space-wizards/space-station-14#29382]
Players get thief or head rev antag from the start of the game, but to become agent you need to wait for 5 minutes which is very strange, so most people cant do the preporation for some funny things.

**Comment by Golinth** [comment]
This is intended, to help curb antag rolling afaik

**Comment by ninruB** [comment]
That and to discourage strats where you rush your objectives within the first couple of minutes with little-to-no resistance.

**Comment by ElPidor** [comment]
> That and to discourage strats where you rush your objectives within the first couple of minutes with little-to-no resistance.
People should know atleast there're agents and after a time get a code i guess, or just making server rules to wait 5 minutes or smth, because you need to make 5x more actions for your traitor  gameplay, because of just some people rushing objectives

**Comment by deltanedas** [comment]
so make thief have random offset too

**Comment by Brandon-Huu** [comment]
This issue should be closed

**Comment by Aexxie** [comment]
Intended feature to prevent antag rolling.
