### ISSUE TITLE
Add a Yaml Linter.

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#2939]
Apparently GitHub Actions virtual environments have yamllint [built-in](https://github.com/actions/virtual-environments/issues/1142). Otherwise i've had success with [this one](https://github.com/marketplace/actions/yaml-lint). (Although i've had to turn off a bunch of the stupid shit like comment indentation and line length).

Would help with shit like #2911.

**Comment by ike709** [comment]
Pretty sure this can be closed? Didn't serv3 add this?
