### ISSUE TITLE
Multiple component wire actions on the same component creates issues

### ISSUE THREAD

**Issue by EmoGarbage404** [space-wizards/space-station-14#29398]
## Description

Caused by #29094

the log wire and the access wire both reference accessreader. players have reported that this makes the light on the UI now show up. it probably does more weird stuff too.

common wires skill issue

**Comment by deltanedas** [comment]
panel lights have been fucky for so long but ive never found out what causes it

**Comment by EmoGarbage404** [comment]
this was unrelated to the comp stuff but it got fixed
