### ISSUE TITLE
Packed has way too many AME cores

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/space-station-14#29409]
## Description
![image](https://github.com/space-wizards/space-station-14/assets/8107459/cfa1cdfc-07ef-4290-92fc-9dcec5370b4c)

This is a low-midpop station, and for some reason the AME is so absurdly big that it can power the entire station itself. This is on top of the singularity, TEG and *three* solar arrays the station has.

**Comment by thebadman4662** [comment]
Were lowpop maps not supposed to be powerable off AMEs alone?

**Comment by LankLTE** [comment]
When the AME was initially nerfed we agreed lowpop stations should be able to be powered with the AME alone since they may not have the pop to sustain other engines reliably (assuming they have any engineers at all).
