### ISSUE TITLE
Oasis still hasn't been updated for the non-stacking atmos pipes change

### ISSUE THREAD

**Issue by Plykiya** [space-wizards/space-station-14#29418]
## Description

You'll find pipes scattered around the station unanchored and it's a bit concerning...

**Reproduction**

**Screenshots**

**Additional context**

**Comment by osjarw** [comment]
Took a fast look and can confirm, there are some unanchored pipes. 
However the few spots I managed to find were ones where there were multiple pipes placed down, like, a T junction on top of another T junction. 
So I can't confirm yet the existence of rooms without air conditioning.

**Comment by deltanedas** [comment]
you dont need to find just grep for anchored

**Comment by IProduceWidgets** [comment]
Should be fixed in my next PR. If you find more doubled entities though please let me know. Its really easy to accidentally spawn two of something.

**Comment by IProduceWidgets** [comment]
I got as lot, but I found some more I missed. Gonna reopen to remind me later since its not a particularly big issue.
