### ISSUE TITLE
AME injection rate needs to be capped

### ISSUE THREAD

**Issue by nikthechampiongr** [space-wizards/space-station-14#29423]
## Description

Overcharging to the level of hundreds of units per time is only used by raiders to drain AME fuel. The extra power that you get from it is worthless because you'll only get it once. It does not make the ame more dangerous either. 

**Reproduction**

- Insert fuel into built ame
- toggle injection
- Spam the increase button
- You have now drained 1000 units of fuel in a few seconds

**Comment by thebadman4662** [comment]
Would that not simply make raiders blow up AME and by extension engineering making matters only worse? If you think about it you are foolproofing it for raiders...

**Comment by nikthechampiongr** [comment]
> Would that not simply make raiders blow up AME instead and by extension engineering making matters only worse? If you think about it you are proposing foolproofing it for raiders...

The ame already has protections to not blow up in the first 30 minutes, and even after that its decay rate is unfathomable slow and is in most cases just stopped. Raiders can do a lot more harm by just draining the fuel supply.

**Comment by thebadman4662** [comment]
AME blows up in 200 seconds above 12 fuel
In 340 seconds above 6 fuel
In 1000 seconds to never(50% of the time AME dodges damage every time :godmode:) at 4-6 fuel

Assuming single core of course.

**Comment by JIPDawg** [comment]
I'm fairly certain that if you set the injection rate to 1000 the next tick of fuel usage will instantly use it all up.

**Comment by thebadman4662** [comment]
Yes, and thats preferable outcome to there being engi sized hole in engineering if there is nobody to stop the raider. Gods(or centcom via shipments) can always bestow new jars, but whole department repairs require quite bit more of divine goodwill.

**Comment by EmoGarbage404** [comment]
> instantly using up all the fuel in one tick is preferable.

Are you smoking crack?

If you just cap it to a reasonable level, then you simultaneously can't instantly deplete the fuel *nor* can you crank it up high enough to blow up a single core as fast as possible.

Wasting 30 minutes worth of fuel instantly is still a problem and "just get admins to give you more" isn't a solution.

**Comment by thebadman4662** [comment]
Well, if syndies are supposed to have option of dangerously overclocking for 3/5 damage then, yes, it is preferable. If removal of Tier 2/3 overclocking is within scope of this issue then 1-2 cores should be capped to 6 fuel and 3+ cores should not be overclock at all.

**Comment by Brandon-Huu** [comment]
> Also ordering AME jar does not require admin intervention at all. Getting new AME though? We need flatpacks from gods or ERT.

Could just do what they did with the PA, dangerous levels can only be reached with emag.

**Comment by nikthechampiongr** [comment]
This was completed in #29587.
