### ISSUE TITLE
Remove Magic Lamp from snowy_labs

### ISSUE THREAD

**Issue by ShadowCommander** [space-wizards/space-station-14#29437]
## Description

Remove the Magic Lamp that is mapped into snowy_labs. It's an Ifrit Holoparasite injector. [Discord chat](https://discord.com/channels/310555209753690112/771041304108072961/1243959024144089129)

**Reproduction**

**Screenshots**

**Additional context**

**Comment by Brandon-Huu** [comment]
> ## Description
> 
> Remove the Magic Lamp that is mapped into snowy_labs. It's an Ifrit Holoparasite injector. [Discord chat](https://discord.com/channels/310555209753690112/771041304108072961/1243959024144089129)
> 
> **Reproduction**
> 
> **Screenshots**
> 
> **Additional context**

![image](https://github.com/user-attachments/assets/866e0d85-55ec-452d-87a8-56dbaba3ff62)

What?
