### ISSUE TITLE
Salvage Shuttle Console makes you wait FOREVER (sometimes) before letting you FTL to a planet.

### ISSUE THREAD

**Issue by Aexxie** [space-wizards/space-station-14#29452]
## Description

Title says it all. No clue how this seemingly hasn't been reported yet. First started appearing after the shuttle console refactor.

**Reproduction**

1: Accept an exped
2: Insert disk into shuttle computer
3: Click "Scan" under the "Map" menu on the shuttle console. FTL for the planet should take a while to show up. The time for it to show up can range anywhere between 30 seconds and 10 minutes if you're unlucky.

**Screenshots**

**Additional context**

Seems to be caused by the scan gradually revealing objects that are further away.

**Comment by ShadowCommander** [comment]
Duplicate of #26348
