### ISSUE TITLE
There is no brazen bull in the game.

### ISSUE THREAD

**Issue by Brandon-Huu** [space-wizards/space-station-14#29465]
## Description

The game is missing the best torture method known to man, the brazen bull.

**Reproduction**

Step 1: Try to execute CE for failing to manage the stations power
Step 2: Be unable to burn them alive inside the bull

**Screenshots**

![sddefault](https://github.com/space-wizards/space-station-14/assets/103440971/3bc05b9d-6371-4fa8-8458-648e9857e435)

**Additional context**

**Comment by deltanedas** [comment]
what did you think the burn chamber was for bozo

**Comment by TurboTrackerss14** [comment]
This is just #ideaguys... not an issue post?

**Comment by mirrorcult** [comment]
do not spam issues like this
