### ISSUE TITLE
forcemap command can't unforce the map.

### ISSUE THREAD

**Issue by IProduceWidgets** [space-wizards/space-station-14#29470]
## Description

New validation doesn't accept an empty string to unforce the map.

**Reproduction**

Force a map for one round > Panic when you can't take the server off rimworld.

**Screenshots**

**Additional context**

~~doing a mapvote does work, but its inelegant.~~ < have not confirmed that actually. mapvotes after forcemap *may* also be borked.

**Comment by Tayrtahn** [comment]
Things I didn't even know were a feature, volume 263

I'll fix this up.

**Comment by deltanedas** [comment]
clearforcedmap or unforcemap would be more obvious
