### ISSUE TITLE
Antag control verbs commonly fail

### ISSUE THREAD

**Issue by bruhmogus** [space-wizards/space-station-14#29481]
## Description
When playing as a non-crew human, the antag control functions commonly fail.

**Reproduction**
1. Start a round
2. Observe
3. Use spawn here on yourself
4. Attempt to force traitor on yourself
5. Fail
6. Cry.

**Screenshots**
![20240625214043_1](https://github.com/space-wizards/space-station-14/assets/104110869/20c402f8-6c94-4077-827c-bf5953db096a)

**Additional context**
It adds objectives, but fails to actually make the character an antagonist.

**Comment by bruhmogus** [comment]
This appears to be literally random, as it fails on normal crew too.

**Comment by beck-thompson** [comment]
Yeah I've had this happen a lot to me as well

**Comment by Errant-4** [comment]
@beck-thompson can you provide repro steps, because I think the original issue was actually fixed by #31318
Do you have the issue where antag control verbs fail if you try to add a specific one the second time?
