### ISSUE TITLE
Atlas missing drain

### ISSUE THREAD

**Issue by Boaz1111** [space-wizards/space-station-14#29490]
## Description

The freezer on the station known as Atlas does not have a drain in the freezer
**Reproduction**

look at Atlas, see no drain
**Screenshots**

**Additional context**

**Comment by UbaserB** [comment]
Atlas has a drain in the freezer, and i confirmed it ingame as well. See: #28514

**Comment by Boaz1111** [comment]
nvm axolotl was just running an outdate build that's on me
