### ISSUE TITLE
ALL borgs can burn themself on lights

### ISSUE THREAD

**Issue by bruhmogus** [space-wizards/space-station-14#29502]
## Description
Every borg can burn themself on a light bulb. They must have their module unequipped (none/manually unequipped)

**Reproduction**
Step 1. Control ANY borg chassis (syndie, role, science created)
Step 2. Manually unequip your module if you have one
Step 3. Click on a light
Step 4. Die

**Screenshots**
![20240626191724_1](https://github.com/space-wizards/space-station-14/assets/104110869/4908c15b-337a-4d75-b351-e1848e9fe713)

**Additional context**
It does deal damage to the borg and it does say that you burn your HAND

**Comment by Plykiya** [comment]
perhaps this shouldn't even be a feature
this is like the only thing you can spam click within 2 seconds to kill yourself, and for some reason only black gloves and some of the higher tier gloves let you unscrew them safely

**Comment by Plykiya** [comment]
![image](https://github.com/space-wizards/space-station-14/assets/58439124/f284e6d2-df03-4ab8-b026-a52f9616499c)
hmmmm
removed in what way I wonder

**Comment by bruhmogus** [comment]
i just realised im a bit vague on this, this is a BUG REPORT

**Comment by Plykiya** [comment]
> i just realised im a bit vague on this, this is a BUG REPORT

I'm aware, the fix for this just requires thinking about what actually needs to be done without ignoring the TODO comments

**Comment by bruhmogus** [comment]
> > i just realised im a bit vague on this, this is a BUG REPORT
> 
> I'm aware, the fix for this just requires thinking about what actually needs to be done without ignoring the TODO comments. We don't want to add a component that just makes some entities immune from getting burned on lightbulbs, especially since the TODO comment implies the glove component shouldn't even exist
> 
> But there's also the fact that borgs somehow have hands with no modules...

this might be fixable by just checking light bulbs for which component makes it burn you, maybe just add a check that also asks if the entity has a hand

**Comment by IProduceWidgets** [comment]
Ill be honest, I just always thought it was whether youre gloves were insulated or not. I would just use that if you dont plan to rip it out completely.
