### ISSUE TITLE
Zombies can be put to sleep by chloral hydrate

### ISSUE THREAD

**Issue by Blackern5000** [space-wizards/space-station-14#29519]
## Description
Chloral hydrate is certainly one way to shut down an initial infected.
CMO can just hypo an II before they kill anyone and they can't do anything.

Zombies should probably instantly wake up when they turn as well.

**Reproduction**
- Roll II midround
- Try to kill the CMO to start
- Get hypod and killed
- Be unable to wake up when you turn
- Die again
- Open mald PR to remove chloral hydrate

**Additional context**
Midround zombies sucks

**Comment by Emisse** [comment]
this isnt an issue

**Comment by mirrorcult** [comment]
..why not?

**Comment by UbaserB** [comment]
> ..why not?

they're dead and cant metabolise stuff probably
