### ISSUE TITLE
Syndicate shuttle doesn't have enough power to operate

### ISSUE THREAD

**Issue by Anzarot121** [space-wizards/space-station-14#29537]
## Description

The problem is that people may not be able to take on the role before the substation runs out of power and will be stuck on the shuttle without power.
**Reproduction**

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/116586144/14a8bb0c-89cb-4af6-9c32-57e1544d68fd)

**Additional context**

This is the amount of energy remaining after 5 minutes.

**Comment by TurboTrackerss14** [comment]
This appears to be from a separate fork looking at the sprites and language. 

Does this issue appear on upstream (this github) or just on the fork itself?

**Comment by Anzarot121** [comment]
This is Corvax, the shuttle design has not changed. Apparently, instead of one of the wall-mounted APUs, there is just a wall-mounted generator, so there is not enough power.

**Comment by TurboTrackerss14** [comment]
Best to send off an issue report there then. As this issue is not an upstream issue.

**Comment by Dutch-VanDerLinde** [comment]
> Best to send off an issue report there then. As this issue is not an upstream issue.

this is an upstream issue

**Comment by Savsj** [comment]
> Best to send off an issue report there then. As this issue is not an upstream issue.

Our version(if any different) also have power issues

**Comment by IProduceWidgets** [comment]
Not an issue for this repo 
![image](https://github.com/space-wizards/space-station-14/assets/107586145/3449096a-20b3-4f1f-a2fe-bcc3b663e985)

**Comment by IProduceWidgets** [comment]
I stand corrected.
![image](https://github.com/space-wizards/space-station-14/assets/107586145/29e361db-e85c-4c80-9cf5-ff0249c14246)
