### ISSUE TITLE
The Space adder cannot be butchered

### ISSUE THREAD

**Issue by Janiano** [space-wizards/space-station-14#29547]
## Description

The space adder cannot be butchered, but there is raw snake meat in the game

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/109560345/d3d47783-2f78-4cba-97af-b7074401153d)

And when the snake is butchered, it gives raw meat and not raw snake meat.

![image](https://github.com/space-wizards/space-station-14/assets/109560345/c0da350b-e88a-480f-a46d-27802fc7eae3)

**Comment by KonstantinAngelov** [comment]
so is droping 5 meat okay?
