### ISSUE TITLE
Client config breaks if server has different from default interface sound cvar

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#29561]
Happened to me when i
1. connect to sunrise
2. connect to any other server
3. client crashes
exeption for me
```
[ERRO] res: Exception while loading resource Robust.Client.ResourceManagement.AudioResource at '/Audio/_Sunrise/UserInterface/buttonclickrelease.ogg', no fallback available
   at System.Environment.get_StackTrace()
   ```
checked client config file and found that interface.click_sound and interface.hover_sound cannot be overwritten or something

**Comment by cfif126** [comment]
How to fix this?

**Comment by lzk228** [comment]
> How to fix this?

remove interface.click_sound and interface.hover_sound from client config

**Comment by cfif126** [comment]
Where can i find the client config?

**Comment by PJB3005** [comment]
> Where can i find the client config?

`%appdata%/space station 14/data/client_config.toml`
