### ISSUE TITLE
Typing while asleep causes you to stand up with a chat bubble

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#29563]
## Description
When you are asleep, if you start typing in chat your character will stand up with a chat bubble even though you are supposed to be sleeping.

**Video**

https://github.com/space-wizards/space-station-14/assets/106507028/ade59890-f9ed-4966-9779-0e6c2a65cb01

**Comment by themias** [comment]
I can't reproduce standing up, but the chat bubble does appear for me.
