### ISSUE TITLE
Nuke Core Container Radiation Bug

### ISSUE THREAD

**Issue by DummeHytteOst** [space-wizards/space-station-14#29568]
## Description
The nuke core container prevents the plutonium core from emitting radiation, while the container is **open**, when it should only stop the radiation when it is closed.

**Reproduction**
Put a plutonium core in the nuke core container, and watch the radiation stop while the container is still open

**Video**

https://github.com/space-wizards/space-station-14/assets/94384139/d2a5c48a-52c4-49c1-840d-c499284d7465

**Comment by Brandon-Huu** [comment]
Isn't that a demon core?

**Comment by Brandon-Huu** [comment]
would the fix be to make it explode when closed?

**Comment by DummeHytteOst** [comment]
> would the fix be to make it explode when closed?

the fix would be to make it emit radiation, only when it is open, and prevent it from emitting radiation while closed.

currently it prevents the core from emitting radiation altogether, even while the container is open, which should expose you to the radiation, since nothing is shielding the radiation in.

**Comment by DummeHytteOst** [comment]
didn't get solved, but #29578 reverted #26786, which caused the issue.
