### ISSUE TITLE
Debug uplink doesn't have the nuclear core steal kit

### ISSUE THREAD

**Issue by bruhmogus** [space-wizards/space-station-14#29575]
## Description
Similar to the other issue where debug uplinks, used for debugging, don't have job items.

**Reproduction**
Step 1. Open debug uplink
Step 2. Fail to steal the nukes catalytic converter

**Screenshots**
![20240629090442_1](https://github.com/space-wizards/space-station-14/assets/104110869/a7ce6013-56c7-47b1-a9f7-c706389eb71f)

**Additional context**
N/A

**Comment by Plykiya** [comment]
https://github.com/space-wizards/space-station-14/pull/29578
