### ISSUE TITLE
The section of Marathons maints under chem is unpowered

### ISSUE THREAD

**Issue by bruhmogus** [space-wizards/space-station-14#29570]
## Description
Title. Two doors do not receive power for some reason.

**Reproduction**
Step 1. Load Marathon Station
Step 2. Check maints (under/around chem)
Step 3. Slam face first into a door

**Screenshots**
![20240629073857_1](https://github.com/space-wizards/space-station-14/assets/104110869/e59efb71-7dc5-477e-959e-e8e17468fc9e)

**Additional context**
The station was completely default, no wiring changes. Power is NOT a concern, as the SMES had the StationInfiniteBattery components.

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
This is an issue of some missing LV right?

**Comment by lzk228** [comment]
why all maints should be powered tho

**Comment by bruhmogus** [comment]
it looks like the cables there are just unconnected to any APC, they're just kinda there

**Comment by Brandon-Huu** [comment]
I thought this was a feature.

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
> I thought this was a feature.

the feature of being able to raid chem round start as a tider
