### ISSUE TITLE
Nuclear fission explosives can't be armed even if the core is put back (despite it working in the pre-disarmed state)

### ISSUE THREAD

**Issue by bruhmogus** [space-wizards/space-station-14#29588]
## Description
Putting the core back after fully deconstructing a nuke will still not allow the nuke to be armed, despite the nuke being able to be armed as long as the core has not been removed (even if it's on the pry to remove state of deconstruction)

**Reproduction**
Step 1. Fully deconstruct a nuke
Step 2. Place the core back
Step 3. Be unable to arm the nuke.

**Screenshots**
![20240629141814_1](https://github.com/space-wizards/space-station-14/assets/104110869/e1362cdc-ed13-4fe1-bafa-40c5babf4c3c)

**Additional context**
This should probably be added since it works perfectly fine as long as it hasn't been removed before

**Comment by Emisse** [comment]
we should probably just revert this since making a nuclear device inert is bad for antag gameplay

**Comment by EmoGarbage404** [comment]
shit was already reverted
