### ISSUE TITLE
WindowsComponent needs to use destructible threshold

### ISSUE THREAD

**Issue by AJCM-git** [space-wizards/space-station-14#2959]
Right now it uses maxDamage to calculate the visual window cracking, it should pick up its prototype destructible threshold instead

**Comment by bhespiritu** [comment]
So do we just want to change visual window cracking to rely on the destructible threshold or should I change it so that all the relevant methods rely on the damage threshold?

If it's the latter, I don't see much of a point to having the maxDamage variable at all.

**Comment by SweptWasTaken** [comment]
Fixed by #3051.
