### ISSUE TITLE
thief objectives are asking for way too many items

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#29595]
## Description
![01:56:41](https://github.com/space-wizards/space-station-14/assets/39013340/b100a432-44e4-4baa-bd99-363d4398bacd)

objective: embezzle cargo out of 15 grand

**Comment by EmoGarbage404** [comment]
Please change your issue name to something coherent and add a proper description

**Comment by deltanedas** [comment]
its physically impossible to steal 46 items without bluespace storage and figurines specifically isnt theft

**Comment by Plykiya** [comment]
> its physically impossible to steal 46 items without bluespace storage and figurines specifically isnt theft

STEAL LAMP
(collect four flashlights)
