### ISSUE TITLE
Crit indicator showing up as observer

### ISSUE THREAD

**Issue by chairbender** [space-wizards/space-station-14#2961]
Not sure on exact repro, but this is what happened.

1. Started round.
2. Got shot, entered crit, didn't leave body. Crit indicator (white circle thing) shows up.
3. Round ended while in crit.
4. Back to lobby, new round started, forgot to ready up. 
5. Spawned as observer.

Crit circle was present around my observer ghost.

**Comment by AJCM-git** [comment]
Cant reproduce
