### ISSUE TITLE
Name in examine is mispredicting as ???

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#29626]
## Description

i assume this is because of the name changes for glued stuff idk @Tayrtahn 

**Reproduction**

fakelag
examine something

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/19853115/f17aca45-64ee-41a1-a7ef-62d0631a92ff)

**Additional context**

**Comment by EmoGarbage404** [comment]
Did you take eye damage

**Comment by mirrorcult** [comment]
wait yes i did

**Comment by mirrorcult** [comment]
although thats still a mispredict im pretty sure

**Comment by EmoGarbage404** [comment]
> although thats still a mispredict im pretty sure

A piece of cursed knowledge: getting eye damage intentionally causes a mispredict when you examine things (im pretty sure the delay scales)
