### ISSUE TITLE
Cant stay still in bed.

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#29632]
## Description
You keep standing up and lying down repetitively when lying in the bed.

**Reproduction**
Lie down on bed, watch the animation glitch.

**Screenshots**

https://github.com/space-wizards/space-station-14/assets/47093363/1af94102-1170-49be-b20a-9b25ddca5041

**Additional context**
NA

**Comment by lzk228** [comment]
i think it's a dupe issue, an even more a have seen a fix pr for it

**Comment by Plykiya** [comment]
https://github.com/space-wizards/space-station-14/pull/29520

**Comment by Tayrtahn** [comment]
Fixed by #29653
