### ISSUE TITLE
Clown can break grapling hook

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#29635]
1. Be clown
2. Shoot grapling hook
3. You can no longer shoot from grapling hook

**Comment by IProduceWidgets** [comment]
pretty confident [it just needs the clumsyproof flag](https://github.com/space-wizards/space-station-14/blob/11034a098626980e1990b0a962fd23eb6bb825f0/Resources/Prototypes/Entities/Objects/Weapons/Guns/Launchers/launchers.yml#L247C1-L249C20)

**Comment by Over-Time** [comment]
It doesn't seem that I can reproduce this error. I have shot the grappling hook many times to make sure I triggered "clumsy" but I could reload and fire normally each time.
