### ISSUE TITLE
Super door remote can't control syndicate doors

### ISSUE THREAD

**Issue by bruhmogus** [space-wizards/space-station-14#29658]
## Description
Title. They don't have access to them.

**Reproduction**
Spawn a Syndicate locked door
Attempt to bolt it with a super door remote
Fail

**Screenshots**
![20240701194118_1](https://github.com/space-wizards/space-station-14/assets/104110869/39a086ea-55fa-49e5-bd42-ef729f1f500f)

**Additional context**
none

**Comment by bruhmogus** [comment]
i just realised that it might be better to add a different remote that has AA since reach has a super door remote

**Comment by ThatOneGoblin25** [comment]
> i just realised that it might be better to add a different remote that has AA since reach has a super door remote

That sounds like something that shouldn't be there.
