### ISSUE TITLE
Two syndies on fullpop Lizard

### ISSUE THREAD

**Issue by Plykiya** [space-wizards/space-station-14#29650]
## Description

when tha antag code doesn't hit
Thought antag selection was resolved a while ago, but I guess there are some hellbugs with it still left

**Reproduction**

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/58439124/938085c7-fb4f-4099-b761-6b7507bb7aa5)

**Additional context**

**Comment by Kayek14** [comment]
This looks like it was a survival round i think? Those two syndies were two seperate sleeper agent roles 40 minutes apart. Agent Oscar was a lone op

**Comment by Dutch-VanDerLinde** [comment]
Yes, sleeper agents not appearing on round summary was fixed recently, this is 100% a survival round

**Comment by Plykiya** [comment]
> This looks like it was a survival round i think? Those two syndies were two seperate sleeper agent roles 40 minutes apart. Agent Oscar was a lone op

ah, was it? kind of strange we got no dragon or ninja. I'll close the issue then.
