### ISSUE TITLE
Distracting tutorial button.

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#2966]
![image](https://user-images.githubusercontent.com/49448379/104111527-c49e7800-52da-11eb-81f6-5065d0bbfe7c.png)

This should switch from bright red to the basic colors after being pressed once.

@chairbender

**Comment by metalgearsloth** [comment]
I think it's supposed to be the ahelp button (when we get it).

**Comment by SweptWasTaken** [comment]
> 
> 
> I think it's supposed to be the ahelp button (when we get it).

Opinion ain't changed and it should be changed while it's ig.

Maybe it could be red when you actually have an a-help to answer?

**Comment by metalgearsloth** [comment]
Sounds good to me.

**Comment by PJB3005** [comment]
Fixed by  #2984
