### ISSUE TITLE
Detectives no longer spawn with engraved flippo lighters, causing impossible objectives on maps that do not have them placed on the map

### ISSUE THREAD

**Issue by bruhmogus** [space-wizards/space-station-14#29689]
## Description
Title.

**Reproduction**
1. Spawn as a detective on a map like Saltern
2. Check your office
3. No lighter
4. Check your bags and coat
5. No lighter
6. Get ahelped for destroying an HVI

**Screenshots**
![20240703114816_1](https://github.com/space-wizards/space-station-14/assets/104110869/178515a7-ed7e-466a-9962-739d142a5b7e)

**Additional context**
Mark as completed if the lighter was moved to a different role

**Comment by GoodWheatley** [comment]
It’s in the trenchcoat that spawns in the locker.
