### ISSUE TITLE
Hair customization scroll/selection breaks at UI scales larger than 100%.

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#2968]
![2021-01-09_16-41-41](https://user-images.githubusercontent.com/49448379/104116403-275e3680-5310-11eb-9219-eee2b16605b3.gif)
![2021-01-09_16-42-53](https://user-images.githubusercontent.com/49448379/104116402-26c5a000-5310-11eb-8f9f-5c0245dcd50e.gif)

**Comment by AJCM-git** [comment]
This has been fixed
