### ISSUE TITLE
Vox chat bubbles broken by Lawyer Badges

### ISSUE THREAD

**Issue by Keer-Sar** [space-wizards/space-station-14#29719]
## Description

Equipping a lawyer badge as a Vox changes your speech bubble sprite to the lawyer's as expected. After removing the badge however, it defaults to the default instead of going back to the Vox speech bubble.

**Reproduction**

1.  Spawn Urist McVox
2.  Control Mob: Urist McVox
3.  Equip Lawyer badge
4.  Drop Lawyer badge on the floor
5.  Default speech bubble aquired

**Screenshots**

![Screenshot 2024-07-04 153757](https://github.com/space-wizards/space-station-14/assets/144283718/4275571f-0abd-448e-9118-bd0ebd31af03)
![Screenshot 2024-07-04 153856](https://github.com/space-wizards/space-station-14/assets/144283718/ef294c49-69c4-4582-99e3-4041487abb6e)
![Screenshot 2024-07-04 153917](https://github.com/space-wizards/space-station-14/assets/144283718/48564b91-f406-4791-b45d-a0073698460c)

**Additional context**

**Comment by lzk228** [comment]
dupe issue

**Comment by beck-thompson** [comment]
Yeah this is for all species and its fixed in #29492
