### ISSUE TITLE
Cursor offset near singularity

### ISSUE THREAD

**Issue by BRINGit34** [space-wizards/space-station-14#29724]
## Description
I am unsure if this is intended behavior but when near a singularity the cursor is offset from its position in game leading to difficulty selecting the intended object near the singularity. 

**Reproduction**

1. Be near the singularity
2. Attempt to move your cursor over something

**Screenshots**

https://github.com/space-wizards/space-station-14/assets/67086183/e0120281-4465-449d-b4dd-634a2b449b20

**Additional context**
This only appears to happen as a ghost

**Comment by muburu** [comment]
cursor isn't offset actually, it's the weird distortion around it making it look like you're selecting something else, without the distortion what you're selecting is what's underneath the cursor

**Comment by BRINGit34** [comment]
> cursor isn't offset actually, it's the weird distortion around it making it look like you're selecting something else, without the distortion what you're selecting is what's underneath the cursor

Is this intended? It appears to only happen when you are a ghost from my small bit of testing

**Comment by lzk228** [comment]
probably an issue of https://github.com/space-wizards/space-station-14/issues/19224

**Comment by BRINGit34** [comment]
I'll close this as Izk228 pointed out it's a dupe of #19224
