### ISSUE TITLE
Spraying dirty tiles does not clean, switch to clean sprite.

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#29727]
## Description
In the past spraying tiles that had the dirty sprite would clean them, prying them up and placing them down would also reset the sprite to the clean state.
It would be nice if the spray still worked.

**Reproduction**
Attempt to space cleaner a dirty tile.

**Screenshots**
Dirty tile left, clean normal tile right.
![image](https://github.com/space-wizards/space-station-14/assets/47093363/538a7e40-5508-4942-9b6f-906e0983e300)

**Additional context**
NA

**Comment by Cojoke-dot** [comment]
Back to Detroit… so many tiles to pry in order to make the floors clean… so many tiles…

**Comment by themias** [comment]
I think the intention is for some grungy-looking tiles to not be cleanable. Dirt decals were added and mapped a while back, so those can be cleaned. I guess it's more of a mapping/design topic at this point.
Some previous posts: #20711 #20575

**Comment by beck-thompson** [comment]
Yeah looks like its a duplicate!
