### ISSUE TITLE
Shuttle consoles allow you to see and FTL to every grid on the map, including the escape pod, evac shuttle, wrecks, yourself, and the dungeon that generates on station map

### ISSUE THREAD

**Issue by bruhmogus** [space-wizards/space-station-14#29744]
## Description
Title.

**Reproduction**
1. Open a shuttle computer
2. Look around at the names of beacons
3. Look in FTL

**Screenshots**
![20240705124234_1](https://github.com/space-wizards/space-station-14/assets/104110869/e3b22363-f58f-4ae8-85c0-cbb0ce8ec9d1)

**Additional context**
How the fuck

**Comment by IProduceWidgets** [comment]
The dungeons are intended features #27659

**Comment by metalgearsloth** [comment]
intended.

**Comment by hivehum** [comment]
just checking, this is intended behavior? the amount of entries makes it extremely difficult to find the ftl entry you actually want
![07-04-2024-20-56_SS14 Loader_AaDUIhWyFE](https://github.com/space-wizards/space-station-14/assets/26695058/cc493bce-6ebf-4b7c-8767-2833accf7ad7)
