### ISSUE TITLE
Planet dungeons now generate on the station map somehow

### ISSUE THREAD

**Issue by bruhmogus** [space-wizards/space-station-14#29745]
## Description
Title. Dungeons will generate in the middle of space for no reason at round start, tied to gateways most likely

**Reproduction**
Step 1. Start a round
Step 2. Look around via shuttle console/objects menu

**Screenshots**
![20240705124416_1](https://github.com/space-wizards/space-station-14/assets/104110869/97741a29-6aef-4ccb-a9f3-c53e32269fdc)

**Additional context**
The dungeon will adopt a planet name, does not infinitely generate like a planet map, will spawn enemies, and is viewable in shuttle consoles. It is also capable of spawning in chunks that are named "grid"

**Comment by IProduceWidgets** [comment]
Intended feature
