### ISSUE TITLE
Can't repair ATS

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#29754]
## Description
ATS grid doesn't allow you to place rods down to repair, probably more necessary now with the random meteor strikes.

**Reproduction**
- Smash up the ATS, so it has enough damage to remove floor tiles and base floor grid
- Try place new one down with metal rods.

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/47093363/ec34bf06-bb1c-460d-b9cc-a3245708de74)

**Additional context**
Probably off for abuse potential shipify'n the ATS but seems important to repair now.

**Comment by 0x6273** [comment]
Dupe of #27620

**Comment by Titian3** [comment]
> Dupe of #27620

Thanks, that one has better details ima close this one.
