### ISSUE TITLE
Vox Ghost Role Spawns Have No Nitrogen Tank

### ISSUE THREAD

**Issue by LeIronGoat** [space-wizards/space-station-14#29756]
## Description
If a Vox spawns as a ghost role, (I'm assuming all) they spawn without nitrogen, and die.

**Reproduction**
Have a Vox spawn in a ghost role, like traveling chefs.

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/3360880/3d1fd4b8-7b76-4166-876f-9c88581dfea9)

**Additional context**
They dead, Jim.

**Comment by Errant-4** [comment]
Thank you for reporting the issue! The good news is that a fix has already been submitted for this
