### ISSUE TITLE
Setting a custom solution transfer volume does not update the item status panel

### ISSUE THREAD

**Issue by themias** [space-wizards/space-station-14#29773]
## Description

We do not see the confirmation popup or the panel status updated if we set a custom amount versus a default/preset amount.

**Reproduction**

1. get a beaker
2. right click > Set Transfer Amount > Custom
3. enter custom value and click Set Amount

Expected: see popup and item panel 'Transfer: xxx' updated
Actual: no popup and item panel shows old value

**Screenshots**

https://github.com/space-wizards/space-station-14/assets/89101928/7e3dd905-2c43-44a2-aeea-65e52d18582b

**Comment by Over-Time** [comment]
I can't seem to reproduce the error because when I try to set a custom transfer value, the variable does not update at all. I think that the popup doesn't appear because the popup code only executes serverside.
