### ISSUE TITLE
Devmap crew monitor broken

### ISSUE THREAD

**Issue by Errant-4** [space-wizards/space-station-14#29787]
## Description
Crew monitor on the dev map is broken (works on other maps)
Spawning a new crew monitoring server on Devmap fixes it. Not sure what's wrong, there IS a server and it's anchored and powered

![image](https://github.com/space-wizards/space-station-14/assets/35878406/ccd3851c-a40f-442e-ae4c-d3b0508f6a27)

**Comment by thebadman4662** [comment]
Are you sure its powered despite being connected to power? Machines been sometimes acting weird and have to be deconstructed and reassembled to work despite being anchored on power as they stay or go unpowered for some reason.

**Comment by Errant-4** [comment]
In retrospect, I don't know why I claimed replacing the crew monitor fixes it, because it does not (or at least it does not fix it on the _current_ live, maybe the situation was different in July)
