### ISSUE TITLE
Bounty for warm clothes does not work properly 

### ISSUE THREAD

**Issue by laok233** [space-wizards/space-station-14#29780]
## Description

Most of the winter coats are counted as 2 warm clothes, so with only 4 winter coats the bounty is marked as completed.

**Reproduction**

1. skip bounties until the warm clothes bounty appears.
2. spawn a steel crate.
3. print and attach the bounty to the crate.
4. spawn 4 winter coats.
5. check the bounty status with a appraisal tool.
6. bounty marked as completed.
7. money glitch real.

**Screenshots**

https://github.com/space-wizards/space-station-14/assets/72604018/2b0bf785-3077-4511-ae15-80ab088fcaec

**Additional context**

Some winter coats are not affected.

The bounty works as intended for winter boots.

**Comment by thebadman4662** [comment]
A lot of winter clothing also does not count as it for some reason, scarfs for example...

**Comment by deltanedas** [comment]
its counting the hoods as clothing

also i imagine it would count firesuits hardsuits etc as winter clothing, should just be changed to a tag all sensible items have
