### ISSUE TITLE
SS14: The Ghostbusters Update

### ISSUE THREAD

**Issue by ARMOKS** [space-wizards/space-station-14#29799]
## Description
By using the reporter console to briefly make them visible, ripley can kidnap ghost players into its backpack

**Reproduction**
Break rules so an admin ghost follows you
Create station news report
Click ghost with ripley pneumatic hand 
SCP Neutralized

**Comment by lzk228** [comment]
can you please provide detailed info? i didnt understand a thing

**Comment by Golinth** [comment]
> can you please provide detailed info? i didnt understand a thing

this is really two separate bug reports. First is that using the reporter console makes aghosts (or maybe all ghosts?) visible for a second or two.
Second, the ripley can pick up ghosts with it's hydraulic clamp. This can be tested at the end of the round with the ripley, you can pick up ghosts, and they cant do anything about it.

**Comment by HelpTheSteak** [comment]
It would not make all ghosts visible since non admin ghosts don't get a pda

**Comment by UbaserB** [comment]
If you see a ghost, you can also pick it up with the force gun for eg round end (this was only tested downstream though so it needs replication)
