### ISSUE TITLE
Tiles under low walls without windows can be destroyed by an explosion

### ISSUE THREAD

**Issue by daniel-cr** [space-wizards/space-station-14#2979]
At the moment explosions don't damage tiles if there is an entity in that tile that has CollisionGroup.Impassable, this works for machines, computers, walls and other things.

This is not the case for low walls as you are able to vault over them. (They don't have CollisionGroup.Impassable). If the window on the low wall is destroyed, the explosion can damage the tile underneath.

**Comment by moonheart08** [comment]
Should probably introduce a *component* that tells explosions not to do this, instead of depending on collision groups. This is a more robust (pun not intended) solution to the problem. Carpets aren't impassible either, but they should be stripped up by an explosion before the tile under them is too.

**Comment by PaulRitter** [comment]
yes, the component should specify the following things
1. priority, so for example we know to run the walls logic before the floortiles logic
2. wether or not to further go down the tile, example (walls -(if destroyed)> flooring), maybe also how much to reduce explosion intensity by
3. explosion behaviour, my idea would be to merge this into the explosionact interface (and possibly merge points 2 & 3 together, not sure if its a good idea tho(probably is))

**Comment by AJCM-git** [comment]
We dont have low walls anymore, so I will make a new issue about the component
superseded by #5200
