### ISSUE TITLE
Succumbing to death is too beneficial

### ISSUE THREAD

**Issue by Plykiya** [space-wizards/space-station-14#29798]
## Description

Succumbing to death immediately is the correct option 9/10 times to prevent yourself from taking additional damage in harder to heal categories.

For example if you get poisoned by rads or toxins, you limit half of your damage to easily healable airloss damage if you succumb instantly. Your body continues to process out the chemicals even while dead, so when you revive they are no longer in your system.

**Reproduction**

**Screenshots**

**Additional context**

**Comment by deltanedas** [comment]
chems in corpses shouldnt metabolise
would allow for pro play like kill someone then inject body with mutagen so if they get defibbed they die

**Comment by osjarw** [comment]
Stopping the metabolism would also make my preferred way of defibbing easier, that is, to put them on stasis, pump in some amount of meds, and then defib. 
I'm not entirely sure, but IIRC back in SS13 chems didn't metabolize in dead patients.

**Comment by thebadman4662** [comment]
Stopping metabolism would kill Opp, Nec and Alox medicines.
It would greatly diminish value of stasis bed.
It would make stealthy permakilling way too easy.

That said, yes, succumbing on demand can mitigate a whole lot of damage you could be taking from antag if you are aware of what they are doing.

**Comment by osjarw** [comment]
> Stopping metabolism would kill Opp, Nec and Alox medicines. 

I can't imagine letting `worksOnTheDead: true` get metabolized as the others are frozen being that hard. Well, I'm not that well versed with the reaction/metabolism code.

> at some point only way to purge bloodstream would be to use HUNDREDS of blood packs in order to draw ONLY 15% of bloodstream as poison chems should someone really try to fill someone with poison, no matter how easy it is to get it.

From what I can tell, there's a bug that's causing this. So, the way that drawing blood works is that if you try to draw 15u of blood, you get a solution of 85% blood, and 15% chems, assuming theres chems in the patient. 
I think there's a bug here that makes the amount of drawn chems proportional to the amount of blood drained, that is, if the patient has 1u blood left, but 200u of chems, you get just 0.85u blood and .15u chems. 

I guess the hundreds of bloodpacks part could be solved by making injected blood go straight into blood levels.

**Comment by thebadman4662** [comment]
> > It would make stealthy permakilling way too easy, at some point only way to purge bloodstream would be to use HUNDREDS of blood packs in order to draw ONLY 15% of bloodstream as poison chems should someone really try to fill someone with poison, no matter how easy it is to get it
> 
> Or you can just use charcoal and purge whatever was put inside the bloodstream.

You can't use charcoal on filled bloodstream. You need 25u of charcoal to purge 200u bloodstream and nothing is stopping antag from injecting even more. Patient will simply die before charcoal can save them unless they succumbed early enough.

**Comment by Dutch-VanDerLinde** [comment]
if chems dont metabolize when dead then i think health analyzer should show you what chems are in bloodstream so med can properly heal you

**Comment by Plykiya** [comment]
> if chems dont metabolize when dead then i think health analyzer should show you what chems are in bloodstream so med can properly heal you

this is just useful in all scenarios to prevent ODs
