### ISSUE TITLE
Lone Ops aren't showing as "Unknown" and are instead showing as the job they once were

### ISSUE THREAD

**Issue by MarzieK** [space-wizards/space-station-14#29866]
## Description
Usually,  Lone Ops would show up as "Unknown" when searching for them through ghost warp. I ASSUME it's showing as Scientist here because that was probably their job before they joined the role. However, does this mean they get the permissions of the sci? I have no clue. I just know it's supposed to say "Unknown". 

**Screenshots**
![33c7766794cf0c474815ed14f0eaf125](https://github.com/space-wizards/space-station-14/assets/93346283/fac159d7-b17b-47a5-8be7-d3473ebb1925)

**Comment by thebadman4662** [comment]
This bug also causes kill objectives not work because captain is a loneop now so it totally makes sense that syndies retext.

**Comment by deltanedas** [comment]
antag selection antag spawner bug
