### ISSUE TITLE
Custom Transfer Amount does not work over 50u

### ISSUE THREAD

**Issue by githubuser508** [space-wizards/space-station-14#29902]
## Description
When transferring reagents through the Custom Transfer Amount, the amount transferred cannot exceed 50u. If you enter a number over 50, the transfer will only transfer 50u, no more. Tested with jugs and large beakers.

**Reproduction**
1. Take a jug or large beaker with more than 50u of a reagent in it.
2. Set the custom transfer amount to any number over 50.
3. Attempt to transfer to another large beaker or jug.

**Screenshots**

https://github.com/space-wizards/space-station-14/assets/140472900/47fd166f-77b7-4bad-bc66-9b50bfbea159

**Additional context**

**Comment by deltanedas** [comment]
i think custom amount mispredicts

**Comment by Brandon-Huu** [comment]
Doesn't work for anything under 1u as well

**Comment by Brandon-Huu** [comment]
It's happening because of this.
![image](https://github.com/user-attachments/assets/1b53d1da-2245-417a-8d69-d4ba235b03a5)
