### ISSUE TITLE
bandana on head hides reptilian's snout

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#29914]
it looks horrible
![image](https://github.com/space-wizards/space-station-14/assets/124214523/a0a7add7-96d4-46e1-8a15-16d2a179393f)

**Comment by luizwritescode** [comment]
#25716 might have introduced this inside `bandanas.yml`  in the `ClothingMaskBandanaBase` entry:

```
- type: HideLayerClothing
  slots:
  - Snout
```
I don't know why it's here in the first place but removing slots: Snout seems to fix and not break any other bandana

![imagem_2024-07-12_173412477](https://github.com/user-attachments/assets/64840a48-2838-485e-9828-8a54b4f30eba)

**Comment by themias** [comment]
Bandanas have special behavior when they convert between head/mask. Check out #24597. Chances are there needed to be extra logic when the snout hiding functionality was added.

**Comment by luizwritescode** [comment]
> Bandanas have special behavior when they convert between head/mask

Because of  this any Head bandana will have it's Mask equivalent as a parent in the .yml

Adding this override in the `ClothingHeadBandBase` fixes the bandana on spawn.
```
 - type: HideLayerClothing
   slots: []
```

 but further logic is required to change the `HideLayerClothing` component upon folding/unfolding

**Comment by lzk228** [comment]
> Bandanas have special behavior when they convert between head/mask. Check out #24597. Chances are there needed to be extra logic when the snout hiding functionality was added.

i think replacing the inheritig from maks bandana to head bandana to inheriting from head to mask would fix all that
