### ISSUE TITLE
Borgs are missing their flashlight after a recent update

### ISSUE THREAD

**Issue by SkippyMcSkips** [space-wizards/space-station-14#29916]
## Description
I'm not sure when this started, but I noticed a few days ago that Cyborgs no longer spawn with flashlights equipped, and as a result have no way of producing light. This makes them useless in maints, and helpless when power goes out.

**Reproduction**
1. Spawn as a Cyborg
2. Realize you are missing flashlight
3. Cry

**Screenshots**
![346783966-99747bb1-245d-4b3b-85e5-77c95c72ce09](https://github.com/space-wizards/space-station-14/assets/107330854/ac95ff0e-2c8d-470a-a557-4b23ce0bad6c)

**Comment by deltanedas** [comment]
most likely trolled by item toggle rework

**Comment by Katzenminer** [comment]
I cannot Replecate The Bug maybe This was mostlikley fixed elsewehre

**Comment by SkippyMcSkips** [comment]
It seems like this was fixed briefly but is once again an issue.

**Comment by SkippyMcSkips** [comment]
This is resolved now.
