### ISSUE TITLE
QSIs allowing containers to be placed in pockets

### ISSUE THREAD

**Issue by LankLTE** [space-wizards/space-station-14#29929]
## Description

When done, the bug allows you to have a crate in your pocket that can be opened and closed (and locked), effectively kidnapping people. 

**Reproduction**

- Have two QSIs linked
- Place one inside of a crate or locker
- Get inside of a disposal bin
- Activate the QSI
- Place it in your pocket before it swaps

**Screenshots**

![image](https://github.com/user-attachments/assets/62ad0dc6-4482-49ab-b846-d136f8fd1c5b)

**Comment by thebadman4662** [comment]
Gotta ask it before Kadeo - Can we have pocket ripleys to kidnap people? :trollface:

**Comment by IProduceWidgets** [comment]
Spin inverters are so constantly fucked lmao.

**Comment by EmoGarbage404** [comment]
was this fixed with the recent PR or is this still a problem

**Comment by Cojoke-dot** [comment]
I never checked pockets while making the pr but it does prevent stuff from getting teleported into your hands so I would imagine this is fixed.

**Comment by deltanedas** [comment]
hands and inventory are separate systems so probably not if you are using hands for logic and not containers

**Comment by Cojoke-dot** [comment]
> hands and inventory are separate systems so probably not if you are using hands for logic and not containers

The fix used container logic
#29200

**Comment by Cojoke-dot** [comment]
well... I tested this and its still a bug so I guess I can try and fix that...

**Comment by Cojoke-dot** [comment]
Silly... yeah, it looks like its the ordering of how it decides what to teleport. It gets its parent container, then the top most container. If the topmost container is anchored, then it just swaps the QSI instead of trying to swap the first container that is not anchored.

https://github.com/user-attachments/assets/031aecee-bae7-4422-9d5d-a6471e7401ef
