### ISSUE TITLE
Secure windoors should be punch proof

### ISSUE THREAD

**Issue by IProduceWidgets** [space-wizards/space-station-14#29925]
## Description

The secure windoors are often used in security for the jailcells, and it doesn't make much sense that you can't break the glass with your hands, but you can break the door.

**Reproduction**

Get arrested > mald > punch secure windoor until it breaks for some reason > seethe > no way to prevent this as sec.

**Screenshots**

**Additional context**

I mean, yes you can just execute them, but that seems kinda nrp when they really just need a good timeout.

**Comment by thebadman4662** [comment]
> no way to prevent this as sec

Breach of custody is permable crime and you do not have to stand there and wait for windoor to break down.
Give a warning. Flashbang and stun the fucker. Crit and straitjacket them if you have to.

**Comment by IProduceWidgets** [comment]
> Making windoors indestructible would mean sec can dump prisoner in and never bother to check on them again.

I don't think this argument holds water because if they were just regular airlocks, like they are on a couple maps, its just not possible.

**Comment by thebadman4662** [comment]
> > Making windoors indestructible would mean sec can dump prisoner in and never bother to check on them again.
> 
> I don't think this argument holds water because if they were just regular airlocks, like they are on a couple maps, its just not possible.

Yeah thats mapping issue on core and on... are there are any other maps not using windoors in normal cells?

**Comment by IProduceWidgets** [comment]
Train core reach and saltern

**Comment by JIPDawg** [comment]
I'm pretty sure like all brigs use windoors. At least the max pop ones.

**Comment by deltanedas** [comment]
secure windoors just cost fancier materials for no benefit if they have no damage reduction compared to normal windoors

**Comment by Cojoke-dot** [comment]
The reason its like that is so if sec just forgets about you in a cell or your an antag that was left alone you can escape. Its meant to make the warden actually do their job, if they are breaking it punish them by restricting their movement. You could totally say that them punching a glass window is a risk to life and limb.

> Prisoners must be granted freedom of movement, and should not be restrained with handcuffs or other devices after incarceration unless there is an undue risk to life and limb.

**Comment by IProduceWidgets** [comment]
My issue is there is no practical way to do that.

**Comment by thebadman4662** [comment]
Well, stairjackets exist but there aren't many maps with them mapped. You also have to crit/tranq someone to wear it.

**Comment by Cojoke-dot** [comment]
> My issue is there is no practical way to do that.

Do what? Cuff them? Its a 30-second doafter to uncuff yourself and if they keep doing it then you can perma them for repeated attempts to break out or any of the crimes associated with them.

> Repeated crimes are when someone is released for a crime and then goes to commit the same crime within the same shift. Repeated crimes can be charged with tacked-on time; first repeat: 3:00, second repeat: 6:00, third repeat: permanent confinement.

If they keep breaking out of cuffs and hitting the window, enforce space law. Most of the laws are very easy to manipulate within reason to fit your needs.

**Comment by Errant-4** [comment]
This is not just a Sec issue, secure windoows are used in other places. Places where they are less likely to be actively guarded. They should be at least minimally secure

**Comment by lzk228** [comment]
seems easy to fix, just add 5 flat damage reduction

**Comment by Errant-4** [comment]
Secure Windoors inherit the base Windoor's damageablecomponent unmodified

**Comment by lzk228** [comment]
create a new one :godo:

**Comment by regenpower** [comment]
if they try to break out repeatedly, put them in perma, shrimple as that
good luck breaking the reinforced glass in there

if they do break out, they're now AOS and will go to perma, which is worse than just sitting out their < 15min sentence, so it is arguably better as a secoff to have someone try to break the glass

**Comment by Brandon-Huu** [comment]
> Crit and straitjacket them if you have to.
Beating someone into critical conditions because they punched a window is psychotic

**Comment by Errant-4** [comment]
The point of this PR is not to tune security procedures
