### ISSUE TITLE
Bagel has a tit you can warp to.

### ISSUE THREAD

**Issue by IProduceWidgets** [space-wizards/space-station-14#29920]
## Description

Just a funny typo for teg, I assume.

**Reproduction**

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/107586145/04160103-5a48-4fde-9d23-7a434dce17b9)

**Additional context**

**Comment by lzk228** [comment]
issue of the year

**Comment by lzk228** [comment]
@IProduceWidgets noob, some of atmosians renamed the beacon :trollface:
![image](https://github.com/user-attachments/assets/365d4766-aae7-4b1a-b605-af1ff0bced24)

**Comment by IProduceWidgets** [comment]
Me!? The fool!
IMPOSSIBLE!!!!
