### ISSUE TITLE
Tool usage artifact trigger is impossible since the scanner occupies the tile it needs to anchor on

### ISSUE THREAD

**Issue by bruhmogus** [space-wizards/space-station-14#29936]
## Description
Title.

**Reproduction**
1. Try to anchor artifact to same tile as scanner
**Screenshots**
![20240711231939_1](https://github.com/user-attachments/assets/e67e92ae-ffee-43b6-ae8d-54e133524405)

**Additional context**
Related to the recent fix that made the scanner go through walls.

**Comment by JIPDawg** [comment]
Correct me if I'm wrong, but you don't need to anchor it ON the scanner, it can be anywhere and you can anchor it. I also think you can use a multi tool to trigger it.

**Comment by thebadman4662** [comment]
> Correct me if I'm wrong, but you don't need to anchor it ON the scanner, it can be anywhere and you can anchor it. I also think you can use a multi tool to trigger it.

You do need it on the scanner for traversal to work... assuming it got fixed and science is not flipping coins every time only TRUE nodes are within jump reach.

**Comment by JIPDawg** [comment]
By traversal do you mean setting it up or down on the console? Or it just jumping to a different node at all

**Comment by thebadman4662** [comment]
> By traversal do you mean setting it up or down on the console? Or it just jumping to a different node at all

Setting and then weight being applied while on scanner.

**Comment by bruhmogus** [comment]
yeah, it can be triggered via anchoring NEAR but the multitool is something else

> Correct me if I'm wrong, but you don't need to anchor it ON the scanner, it can be anywhere and you can anchor it. I also think you can use a multi tool to trigger it.
