### ISSUE TITLE
Foam counts as a connection for walls

### ISSUE THREAD

**Issue by bruhmogus** [space-wizards/space-station-14#29951]
## Description
Title. I'm not sure if this works for normal plastitanium too.

**Reproduction**
Step 1. Throw a cleanade, trigger a biochemical disruption artifact, etc while near a plastitanium wall

**Screenshots**
![20240712075647_1](https://github.com/user-attachments/assets/eb746155-09f8-4720-b3f8-c2ccde09d337)

**Additional context**
None

**Comment by TheDoctor1977** [comment]
I'm pretty sure this applies to every wall.

**Comment by IProduceWidgets** [comment]
https://github.com/space-wizards/space-station-14/blob/a94f1f0fe0b985236b508da25311d21aa92130b5/Resources/Prototypes/Entities/Effects/chemistry_effects.yml#L73

This would probably be why.
