### ISSUE TITLE
aloe cream uses ointment inhand sprites

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#29955]

**Comment by bruhmogus** [comment]
im 90% sure all meds use the same inhand

**Comment by JIPDawg** [comment]
Looks like this can be closed (if I'm reading this right)
![image](https://github.com/user-attachments/assets/fd3557ec-90b6-4bbf-b591-a0dd171f8668)

**Comment by TeaMakiNL** [comment]
Yeah close it, spent waaaaaaaaaaay too much for it to just be aloe
