### ISSUE TITLE
Examiner components allows to drop items from containers

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#29950]
https://github.com/user-attachments/assets/6391697a-4d74-41de-8d33-b4624d8c797a

**Comment by luizwritescode** [comment]
I had trouble replicating this one. While controlling a mouse, clicking open storage will open the toolbox but it won't shot the item grid.

**Comment by Hreno** [comment]
Same as @luizwritescode

**Comment by lzk228** [comment]
yep, fixed
