### ISSUE TITLE
IRecyclable and the Recycler

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#2996]
Just an idea for solving the Recycler problem once and for all: 
An interface that handles an item being recycled. A standard "SimpleRecyclableComponent" that just... recycles the entity into the specified prototype (i.e. wrench becomes scrap) would be good for most things. IRecyclable would supply two functions, one that checks if the Recycler can recycle this thing (it should be provided a bool specifying if the Recycler is in unsafe mode), and one that actually does the recycling when called.

Probably a beginner job.

**Comment by RemieRichards** [comment]
Agree with this approach.

**Comment by PaulRitter** [comment]
same, this seems like a good idea, could even be introduced into the constructioncomponent(?) (that part would not be a junior job :P)

**Comment by Zumorica** [comment]
FYI this is kinda already a thing with RecyclableComponent (it's literally just like the SimpleRecyclableComponent you mention) but it could use some polish and an `IRecyclable` interface as you said!

**Comment by Peptide90** [comment]
Related to #2232 (can be merged or closed).

Also for reference #2667 (although this deserves to be it's own issue as it's prototype related not recycler).

**Comment by Peptide90** [comment]
Update 2 years later. Recycler needs to be able to handle storing materials until it can produce a full sheet.

E.g. it breaks down a bottle or syringe which only yields a partial refund of say 0.1 glass / plastic. It stores this until it gets to 1 sheet, and spits it out. This way tiny items aren't lost. 

Adding the stacker downstream to catch sheets and stack them would also be ideal for ORM and this.
