### ISSUE TITLE
Machine's Remote Control (I/O SHIT)

### ISSUE THREAD

**Issue by ghost** [space-wizards/space-station-14#30]
Since powernet need **machines** to work let's throw another Urist's concept to your consideration! Urist read thousands game design's books after all!

## Overview
**Devices** (possible for other entities too but mostly devices; the gates, for example, probably wouldn’t be devices) send signals to each other using two components, RCInput and RCOutput (**RC** for Remote Control). Most complex interactions involve this standartized system - have the entity’s own code operate what it sends via **RCO** and how it behaves on receiving signals via **RCI**. A supplemental RCOutputUI component is used for when you need to provide the player with the means to edit which RCInputs an RCOutput is connected to.
Signals can be instant or continuous and contain a string as their value.
<img width="657" alt="2018-02-04 0 55 09" src="https://user-images.githubusercontent.com/28573306/35770918-69b18c38-0946-11e8-986a-90afce13ee2a.png">

## RCOutput component
An RCOutput’s properties are its range, connected RCInputs and current continuous signals being output. It can have any number of RCInputs connected to it at a time. When the entity or another component tells **RCO** to output a signal, it informs all connected **RCIs** of its value. If it’s a continuous signal, the RCIs remember it, and the **RCO** will tell them if it gets disconnected, the continuous signal stops or its value changes. If an **RCI** is connected to an **RCO** while the **RCO** is outputting a continuous signal, it gets told about the signal.

## RCInput component
An RCInput’s properties are its connected RCOutputs and current continuous signals being input.
It can have any number of RCOutputs connected to it at a time. When it receives a signal or an update on a continuous signal it informs other entities/components that rely on that information about it.
An RCInput component can have a flag that on interaction with its entity requests the one performing the interaction to automatically try to perform an interaction with all the connected **RCOs** in its reach. This can be helpful for things mobs often interact with, like doors - a mob bumps into a door, the door asks it to press the connected button, the mob does so because it’s inside the mob’s reach, the door receives the signal and opens; all without the player doing anything sans bumping into the door.

## RCOutputUI
A simple UI that gets all the **RCIs** within an **RCO’s** range and lets a player using it connect/disconnect them.
<img width="384" alt="2018-02-04 0 59 42" src="https://user-images.githubusercontent.com/28573306/35770938-b2f60568-0946-11e8-9574-af25887f9f8c.png">

## Examples of usage (Content?)
- Logic gates - **RCI**, **RCO**.
- **AND**: outputs an instant “true” signal when receives signals from all connected RCOs within a certain timeframe (property) and at least one of them isn’t continuous. Outputs a continuous “true” signal when all connected RCOs output continuous signals.
- **XOR**: relays a signal from one of the connected RCOs while all other connected RCOs aren’t outputting signals.
- **OR**: outputs an instant signal defined by a property when one of the other connected RCOs outputs an instant signal and not outputting a continuous signal. Outputs a continuous “true” signal when one of the other connected RCOs outputs a continuous signal.
- **NONE**: outputs a constant signal defined by a property while none of the connected RCOs are outputting a signal.
- Signal splitter - **RCI**, **RCO**. When it receives a signal, based on the signal’s string and the splitter’s settings, sends it to a specific connected RCI. For example, a splitter could be connected to an ID reader and send a signal to a door when it receives a “passed” signal and to a turret when it receives a “failed” signal.
- Button - **RCO**. Sends instant signal defined by a property when used.
- Switch - **RCO**. When used, switches between on/off. While on, maintains a constant signal defined by a property.

**Comment by imw-Oculus** [comment]
This is good, but how about instead of designing the circuit, you design code contained in a processor object instead?

**Comment by captkirk88** [comment]
So one could create many opposing logic gates that loop infinitely possibly clogging up server CPU.  I would exclude NONE if I were you since a looping NONE->OR combo would be possible.  Given that NONE creates a output according to your description of that logic gate above.

**Comment by zty8212000** [comment]
Might be solvable by limiting the speed of logic gates, ie, a gate won't detect a change in signal until the start of next tick. You'd still be able to slow down the server somewhat by spamming them, but that's true for pretty much any object.

**Comment by acvzy** [comment]
Moved [here](https://hackmd.io/@ss14/docs/%2FVu6JlrdsRCSh5D7yOSp5kA)
