### ISSUE TITLE
Wristwatch has an OOC description

### ISSUE THREAD

**Issue by Madformoose** [space-wizards/space-station-14#30046]
## Description
The wristwatch item's description reads "How much time did you waste playing ss14?". This is a NO NO!!

**Screenshots**
![image](https://github.com/user-attachments/assets/25c3fc4e-7991-4820-8714-3aaee379f738)

**Additional context**
This change would be in line with ones such as the one to chef's cookbook #29467

**Comment by lzk228** [comment]
already fixed by #30036
