### ISSUE TITLE
Metaphysical displacement artifacts can teleport anyone from anywhere on the map

### ISSUE THREAD

**Issue by bruhmogus** [space-wizards/space-station-14#30057]
## Description
Title.

**Reproduction**
Step 1. Trigger metaphysical displacement
Step 2. Watch as the 800 meter away salv appears in a plasmaflooded room

**Screenshots**
Couldn't get a good screenshot

**Additional context**
Probably a broken/not existant check for distance

**Comment by thebadman4662** [comment]
Nukie portal is certified SS14 classic and needs to be protected at all cost. :godmode:

**Comment by mirrorcult** [comment]
isnt this the point

**Comment by mirrorcult** [comment]
like i dont see how this is a bug

**Comment by TheShuEd** [comment]
the only bug here is that the artifact does not teleport to the place where the player was

**Comment by bruhmogus** [comment]
i feel like it might be a small problem if a person trying to do their job just gets summoned into a room filled with plasma for no reason other than unlucky

**Comment by thebadman4662** [comment]
Surely science is overpressurizing a single tile with normal gassess instead of filling test chamber with plasmafire and said unlucky guy isn't instantly getting ashed, surely...

**Comment by bruhmogus** [comment]
> Surely science is overpressurizing a single tile with normal gassess instead of filling test chamber with plasmafire and said unlucky guy isn't instantly getting ashed, surely...

no, they're getting near instantly annihilated by plasma poisoning since it had gaseous plasma trigger

**Comment by EmoGarbage404** [comment]
i dont think there's anything here to fix
