### ISSUE TITLE
Clearing multiple people of wanted status is awful.

### ISSUE THREAD

**Issue by JIPDawg** [space-wizards/space-station-14#30087]
## Description

Ninja hacks Criminal records computer and sets everyone to wanted. Begin to go through to try and reset everyone. Scream at it being a horrible mess.

**Reproduction**

Scroll through computer and set someone to no longer wanted
scroll down to select next person. It jumps around and resets again.

**Screenshots**

https://github.com/user-attachments/assets/542cef30-7a70-4305-906a-949e3170abfa

**Additional context**

**Comment by thebadman4662** [comment]
Franklly, if it was possible to easily clean ninja mess, whats the point other than bit of lame greentext? 
Or we should not be able to fix records after ninja hacking? :trollface:

**Comment by deltanedas** [comment]
the jumping shit specifically is a ui thing
i imagine fix would be similar to the research console fix long ago

**Comment by Tayrtahn** [comment]
While it shouldn't be *super* easy to fix ninja hacking (like a "clear all" button would be too powerful), you definitely shouldn't have to wrestle with the UI while doing it.

**Comment by magelfik** [comment]
What about a "clear all" button with a delay proportional to the number of connected players ? That would seem fair IMHO.

**Comment by lzk228** [comment]
> While it shouldn't be _super_ easy to fix ninja hacking (like a "clear all" button would be too powerful), you definitely shouldn't have to wrestle with the UI while doing it.

no, the jumping thing should be fixed
