### ISSUE TITLE
Exploding pens are inconsistent

### ISSUE THREAD

**Issue by Plykiya** [space-wizards/space-station-14#30103]
## Description

You can activate then embed the pen by throwing it at someone to explode the person

But there are times when the pen is embedded at an awkward angle in such a way that causes the explosion to happen on a different tile than the one the person is standing on

**Reproduction**

**Screenshots**

**Additional context**

**Comment by Plykiya** [comment]
![image](https://github.com/user-attachments/assets/683d9892-99a3-4ad6-93c1-f1521ade59aa)

The pen doesn't have a fixture that properly matches the size of the pen, so you end up with the embed super far away

**Comment by Plykiya** [comment]
https://github.com/user-attachments/assets/53e8425b-19db-4006-bee7-226bdd83941b

**Comment by wafehling** [comment]
This happened to me like 6 months ago, I knew I wasn't crazy... Thank you
