### ISSUE TITLE
health analyzer popup problems

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#30119]
- popup when you try to cancel doafter with another click
- popup when scanning yourself

https://github.com/user-attachments/assets/37613016-cf4c-4259-89ce-86cf3eb4239b

**Comment by IProduceWidgets** [comment]
This should be an easy fix. Just a couple ifs thrown in around the popup to check target/source and play on client/server.

**Comment by IProduceWidgets** [comment]
#30120
