### ISSUE TITLE
Health Analyzers as an Admin Ghost.

### ISSUE THREAD

**Issue by thebossdude22** [space-wizards/space-station-14#30114]
## Description

Scanning people with Health Analyzers as an Admin Ghost gives them a notification, when it shouldn't. It also ends up putting our PDA's/Analyzers in slime body storage. This makes it difficult to check people's health quickly during issues without giving things away or being annoying to handle.
Not much else to add here, It's pretty self-explanatory.

**Comment by lzk228** [comment]
tried to fix it right now but check for ghost component just doesnt work properly

**Comment by Tayrtahn** [comment]
I kinda think that admins should be able to examine (and edit?) someone's health from the context menu or something. Having to use an item seems clunky.

**Comment by IProduceWidgets** [comment]
> I kinda think that admins should be able to examine (and edit?) someone's health from the context menu or something. Having to use an item seems clunky.

And edit the crit / dead / whatever state thresholds as well as max health please.
