### ISSUE TITLE
healing shows popup when you try to cancel doafter with another click

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#30120]
https://github.com/user-attachments/assets/fe7aac36-3e5f-495f-b4e5-febc663437f9

**Comment by Winkarst-cpu** [comment]
Bro finds a lot of bugs every day.

**Comment by lzk228** [comment]
> Bro finds a lot of bugs every day.

i actually created this one :trollface:

**Comment by Winkarst-cpu** [comment]
> > Bro finds a lot of bugs every day.
> 
> i actually created this one :trollface:

Smart. Create a bug and ask someone else to fix it...

**Comment by IProduceWidgets** [comment]
> Smart. Create a bug and ask someone else to fix it...

Don't give away my development secrets.
