### ISSUE TITLE
jetpack (bug)

### ISSUE THREAD

**Issue by ImRenQ** [space-wizards/space-station-14#30146]
The player cannot move against the wall, although he can usually do so. Touching the floor solves the problem.

1. Start flying on a jetpack.
2. Accidentally drop the jetpack
3. Fly to the wall
4. You can't move

https://github.com/user-attachments/assets/7d4d068a-a582-48dd-bab3-54aad87868b0

Expected behavior

https://github.com/user-attachments/assets/e44c2ec9-9ebc-483e-9d24-a814a35ddb38

**Comment by ImRenQ** [comment]
Throwing a jetpack has this problem too

https://github.com/user-attachments/assets/8ce83aaa-1624-482d-a883-d67f8c6c9505

**Comment by ImRenQ** [comment]
![изображение](https://github.com/user-attachments/assets/88a43359-57b8-4f7d-91a7-ad9d565e4f0a)
The game thinks the player still has the jetpack

**Comment by Cojoke-dot** [comment]
This is a pretty funny bug...

https://github.com/user-attachments/assets/3d79a5e8-825f-4516-8d23-8d7395262d02

**Comment by Cojoke-dot** [comment]
Found the issue, it looks like DropNextTo that drops the item is not raising the DroppedEvent, I'll make a pr to fix it
