### ISSUE TITLE
Zombies can wipe positronic brains.

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#30142]
## Description
Zombies still have verb to wipe positronic brains.

**Reproduction**
Get a player in to a positronic brain then as a zombie right click it and wipe brain.

**Screenshots**
![image](https://github.com/user-attachments/assets/67a309dc-0ddc-4be4-a3f3-342727f58868)

**Additional context**
NA

**Comment by slarticodefast** [comment]
I was a borg recently and had a spider destroy me and wipe my brain. This action really needs a check for hands.
