### ISSUE TITLE
News reports with [] Crash PDAs when reading them.

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#30152]
## Description
When a news article is written with [] in it, when the PDA attempts to open the article it the parser breaks and the PDA glitches out.

**Reproduction**
- Make article, See last image for replication text.
- Open article in news reader app on the PDA
- PDA window glitches and rendering seems to flicker.

**Screenshots**
![image](https://github.com/user-attachments/assets/371c0f26-db3b-4722-8ace-0a8588f0299e)

![image](https://github.com/user-attachments/assets/0ef70a27-8e3b-4e0b-be35-7f6bc964ec79)
![image](https://github.com/user-attachments/assets/d1579a20-4052-451d-ab91-928bb2d97053)
![image](https://github.com/user-attachments/assets/ac2412bc-6076-4e72-8ab8-27e60d1ef0a0)

**Additional context**
I swore I had made another one of these but not sure where it went and I didn't have a replication.

**Comment by Tayrtahn** [comment]
I'm pretty sure this can be fixed by changing this line to use `SetMarkupPermissive`:

https://github.com/space-wizards/space-station-14/blob/master/Content.Client%2FCartridgeLoader%2FCartridges%2FNewsReaderUiFragment.xaml.cs#L34
