### ISSUE TITLE
Right-clicking moving targets is awful

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#30165]
I think ideally dynamic entities would use a larger bounds like 1x1, or maybe just moving entities, and static entities use a separate smaller bound.

**Comment by metalgearsloth** [comment]
Bonus points for if you right-click examine on a wall but it fails the raycast even for stuff on your edge.

![image](https://github.com/user-attachments/assets/1876caf4-8752-4075-a32f-1d55a8fd99d6)


Corrosive acid not showing up may just be an RMC14 issue.

**Comment by deltanedas** [comment]
i am purely guessing but it could be related to fixtures, acid is basically fake it just has a sprite and no fixture

**Comment by metalgearsloth** [comment]
I'm also having the same issue with cameras upstream, I think client just needs to do a spritesystem check instead of entitylookup.

**Comment by metalgearsloth** [comment]
Examine uses sprites now to largely fix this problem and if I get moving target issues again I'll just bump lookup size.
