### ISSUE TITLE
BoundUserInterface.OnReceiveMessage subscribers directly casting messages

### ISSUE THREAD

**Issue by PaulRitter** [space-wizards/space-station-14#3017]
i have now found two(2) instances of BoundUserInterface.OnReceiveMessage subscribers directly casting messages which would lead to a runtime on server if ANY different message gets sent. Someone needs to go through the codebase & look for this, since i suspect this was copypasted over alot.

**Comment by nok-ko** [comment]
PJB says this shouldn’t be an issue anymore because we use LocalEvents now.
