### ISSUE TITLE
PDA's and Jumpsuits can be added to the device configurator and be saved into air alarms

### ISSUE THREAD

**Issue by VasilisThePikachu** [space-wizards/space-station-14#30178]
## Description

Reported to me by someone in help

**Reproduction**

1. Get multitool
2. Click on pda
3. Click on airalarm
**Screenshots**

![image](https://github.com/user-attachments/assets/1ea6320d-d39d-435c-a605-3f818fde7066)

**Additional context**

**Comment by CookieMasterT** [comment]
This also applies to cyborgs, no idea why you can list those with the multitool

**Comment by deepdarkdepths** [comment]
The real question is if you can configure the jumpsuit in the air alarm

**Comment by deltanedas** [comment]
this has been a thing for ages and said line being drawn is the only thing ive ever seen it used with, and maybe it shows up in netprobe, idk some ss13 shit that never got properly ported
