### ISSUE TITLE
Mark components as player-only

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#3018]
Once https://github.com/space-wizards/RobustToolbox/issues/1255 is done we'll need to go through and update the components that need this to use it. If you see any dump them into this issue but off the top of my head 2 I know of are the flashable and alerts components. 
The easiest way to tell is if it checks if the player is the currently controlled entity in state updates e.g.:
```
private void UpdateAlertsControls()
{
    if (!CurrentlyControlled || _ui == null)
    {
        return;
    }
```

Advantages are less data sent to irrelevant clients (helps with bandwidth and cheating).

If my [PVS PR](https://github.com/space-wizards/RobustToolbox/pull/1478) gets merged as-is then this is as easy as setting a bool server-side.

**Comment by PaulRitter** [comment]
so both referenced prs for this were closed. this still valid?

**Comment by metalgearsloth** [comment]
GetComponentState(ICommonSession session) replaced this
