### ISSUE TITLE
Thin firelocks built only facing south 

### ISSUE THREAD

**Issue by saga3152** [space-wizards/space-station-14#30194]
## Description

No matter how you rotate them In building mode, they always spawn facing south

**Comment by IProduceWidgets** [comment]
I'm 90% certain this has another issue that all constructions don't obey rotations, but it is alluding me.

**Comment by themias** [comment]
Constructions can obey rotation. I think the issue is that the firelock frame doesn't rotate, so just gotta deal with that (while making sure the regular firelocks don't rotate.)
