### ISSUE TITLE
Particle Accelerator Computer Broken

### ISSUE THREAD

**Issue by RyanStrudfelt** [space-wizards/space-station-14#30196]
## Description
You can put it together, It lights up and progresses through construction steps properly, But the UI will not open when interacted with. 
This has at the time of posting, occured on both Salamander, And lizard across multiple rounds. 

**Reproduction**
Try using the PA computer

**Screenshots**
Logs from the console show this: 
![image](https://github.com/user-attachments/assets/73eb6bf3-1139-4ad1-be6e-914c48c13467)

**Comment by huntergregal** [comment]
I've seen this as well

**Comment by Brandon-Huu** [comment]
Broken by https://github.com/space-wizards/space-station-14/pull/28399

**Comment by JIPDawg** [comment]
Fixed by #30219
