### ISSUE TITLE
Interacting with subfloor objects doesn't check if you can actually do so

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#3020]
[BUG]
## Description
If you modify the game to always show subfloors, you can always _interact_ with subfloors, even if you're not supposed to, like in Suspicion.

**Comment by moonheart08** [comment]
Also reproducable by having enabled subfloors in sandbox, then transitioning to some other mode. They will be visible and interactable.

**Comment by mirrorcult** [comment]
going to attempt some refactor of SubfloorHideSystem so I can get T-rays working nicely so I'll try and fix this in that

**Comment by mirrorcult** [comment]
this was fixed by electro at some point
