### ISSUE TITLE
RCD UI Doesn't Show Up

### ISSUE THREAD

**Issue by Nairodian** [space-wizards/space-station-14#30201]
## Description
When attempting to change the mode of the RCD the menu options just simply doesn't appear. The only thing that'll be there is the X to close the menu.

**Reproduction**
Grab RCD.
Hit Z.

**Screenshots**
![image](https://github.com/user-attachments/assets/8257478f-b0e2-48e5-8e20-747ed40465d1)

**Comment by JIPDawg** [comment]
Possibly related to #30177 ? Although I've tested both the rcd[empty] and regular RCD from the spawned menu and they both work fine.

**Comment by Brandon-Huu** [comment]
Caused by https://github.com/space-wizards/space-station-14/pull/28399

**Comment by Brandon-Huu** [comment]
![image](https://github.com/user-attachments/assets/9c1eb7ea-d693-4288-9331-f96b79a860d0)
Got it working
