### ISSUE TITLE
RCDs can't place wires on the same tile as opened doors

### ISSUE THREAD

**Issue by bruhmogus** [space-wizards/space-station-14#30255]
## Description
Title. If I recall correctly it allows you to physically place them under doors, so the RCD should be able to do so as well.

**Reproduction**
Step 1. Open a door
Step 2. Use an RCD to try to place a wire under it
Step 3. Cry

**Screenshots**
![20240722161757_1](https://github.com/user-attachments/assets/7d1e5441-94ac-4671-b20a-5c2d36924787)

**Additional context**
It is the most annoying bug possible for engineers

**Comment by LankLTE** [comment]
RCDs can't place wires on a tile with basically anything on it, despite you being perfectly able to do so with normal cable

**Comment by bruhmogus** [comment]
> RCDs can't place wires on a tile with basically anything on it, despite you being perfectly able to do so with normal cable

exactly, for example
![20240722162345_1](https://github.com/user-attachments/assets/e19f5c36-6b98-45c5-b2cb-8541f4d99904)
