### ISSUE TITLE
antag selection spawners reuse the mind

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#30258]
## Description
regular ghost role spawners create a brand new mind, antag spawners seem to reuse the previous one leading to funnies:
- round end summary shows blatantly wrong names for antags
- loneop with a job real
- maybe objectives staying??? not sure

**Comment by IProduceWidgets** [comment]
Yeah, I honestly don't know what the point of having them reuse your character is. It feels out of place imo. At least for the nukeop agents It seems like a sort of joke.
