### ISSUE TITLE
Infinite QSI link range

### ISSUE THREAD

**Issue by Cojoke-dot** [space-wizards/space-station-14#30268]
## Description

Title 
**Reproduction**

1. click on a QSI with any QSI at any range

**Screenshots**

https://github.com/user-attachments/assets/81653bae-f987-4ac8-a7ad-705cd68c03b8

**Additional context**

I was working on another PR when I realized that I could link my item with an infinite range using the `AfterInteractEvent`

**Comment by a-person5660** [comment]
This seems fine to me since your just linking the networks together, there's no logical reason for you to need to be holding both of them.

**Comment by Cojoke-dot** [comment]
> This seems fine to me since your just linking the networks together, there's no logical reason for you to need to be holding both of them.

little red outline makes my brain say I should not be able to interact with the item

**Comment by a-person5660** [comment]
> little red outline makes my brain say I should not be able to interact with the item

Then remove the outline :trollface:
