### ISSUE TITLE
chameleon projecter invisible glitch

### ISSUE THREAD

**Issue by GuySome1** [space-wizards/space-station-14#30271]
## Description
use a chameleon projector ON a item your wearing, and you will become invisible to yourself and anyone around you, BUT if someone walks out of their screen or someone else who was not around when you turned invisible sees you, your just a item.

**Reproduction**
use chameleon projector on item you are wearing, anyone near you that stays near you can not see you, and you can not see yourself, and for some reason, is not working on my test server.

**Screenshots**
cant get screenshots because its not working on my test server

**Additional context**
found this by accidently click my gloves when trying to put it in my coat

**Comment by Cojoke-dot** [comment]
Yeah, I can't recreate this locally either... someone with more access is going to have to try this in-game

**Comment by deltanedas** [comment]
wait for maints to remember rewrite pr exists

**Comment by Binbagg** [comment]
was able to recreate locally

**Comment by Cojoke-dot** [comment]
> was able to recreate locally

Can you record it? I tried a couple things and could not get it to work.

**Comment by Binbagg** [comment]
> > was able to recreate locally
> 
> Can you record it? I tried a couple things and could not get it to work.

https://streamable.com/b23rfd

**Comment by beck-thompson** [comment]
Maybe the same as #27092?

**Comment by deltanedas** [comment]
you can no longer project as items in containers

**Comment by beck-thompson** [comment]
Looks like this is fixed then!
