### ISSUE TITLE
Holding down an arrow key to traverse the pointer in chat just does not work

### ISSUE THREAD

**Issue by VasilisThePikachu** [space-wizards/space-station-14#30285]
Making it in engine to be safe but feel free to move it to content

~~On other platforms I used the left and right arrow keys while focused in the chat to go back and fix mistakes. Also using control and shift to highlight and jump between words~~

~~On macos this feature does not seem to work~~

This happens on all platforms apparently lmao

**Comment by PJB3005** [comment]
It's because ArcadeLeft has input priority above TextCursorLeft and such, I think.
