### ISSUE TITLE
Pulling a chair and then buckling yourself to it allows you to phase through walls

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#3028]
## Description

1) Unanchor a chair
2) Start pulling it
3) Buckle yourself to it
4) Ctrl+rightclick to move the pulled object
5) Profit

**Screenshots**

https://user-images.githubusercontent.com/19853115/105093349-d2cd6080-5a5f-11eb-8aa6-e8b0fa51d1cf.mp4

**Comment by mirrorcult** [comment]
actually this was on a slightly old branch, might need to retry on master but idk if any changes to pulling have been pushed since

**Comment by mirrorcult** [comment]
also, you can ctrl+rightclick chairs into walls regardless of whether you're buckled to them so that's probably the main issue to fix, moving objects while buckled to them is probably okay

**Comment by 20kdc** [comment]
honestly, I suspect the reason a lot of objects don't have collisions when they should is because of issues with how physics prediction causes massive amounts of client lag...

**Comment by metalgearsloth** [comment]
Can probably fix this particular issue by giving chairs the appropriate collision mask.

**Comment by 20kdc** [comment]
...which will unfortunately cause massive amounts of client lag

**Comment by PaulRitter** [comment]
why don't we just assure that the pull breaks when buckling?
