### ISSUE TITLE
Shelfs deletes items on disassemble

### ISSUE THREAD

**Issue by BombasterDS** [space-wizards/space-station-14#30295]
## Description
New Shelfs are exterminating items when got disassembled/destroyed

**Reproduction**
1. Spawn any of new shelf (chem/metal/cooking/glass shelf)
2. Place items in it
3. Disassemble the shelf
4. Items disappeared

**Comment by Brandon-Huu** [comment]
Replicated with deconstruction but not c-4

**Comment by BombasterDS** [comment]
> Replicated with deconstruction but not c-4

Yeah, looks like i blew empty shelf when tested it

**Comment by JIPDawg** [comment]
in the future putting "Fixes #30313" will automatically close this issue when the PR get's merged.

**Comment by BombasterDS** [comment]
> in the future putting "Fixes #30313" will automatically close this issue when the PR get's merged.

Thanks for adivce
