### ISSUE TITLE
Glue Zipties, Makeshift Handcuffs

### ISSUE THREAD

**Issue by HolySSSS** [space-wizards/space-station-14#30303]
## Description

Applying glue to zipties, makeshift handcuffs and then restraining someone with them leads to the unability to unrestrain the person by themselves or with someone's help, maybe even admins.

**Reproduction**

Apply glue to zipties, makeshift handcuffs and then restrain someone with them.

**Video**

https://github.com/user-attachments/assets/f7f8bc6c-1e16-4d6b-8c0b-7f81a9724ca7

**Additional context**

Welp, I s'pose I'll go on dusty road now, cause someone's surely will start abusing this..

**Comment by Brandon-Huu** [comment]
Based
