### ISSUE TITLE
mobs with handcuffs can unbuckle themselves

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#30312]
1. cuff monkey
2. buckle it
3. it unbuckled itself!

**Comment by themias** [comment]
Possibly related to #28006?

**Comment by lzk228** [comment]
yes

**Comment by osjarw** [comment]
It looks like the operator for unbuckling just calls Unbuckle directly without doing any checks, I believe one can just replace that with TryUnBuckle or whatever that method was called, which contains some checks

**Comment by Brandon-Huu** [comment]
> It looks like the operator for unbuckling just calls Unbuckle directly without doing any checks, I believe one can just replace that with TryUnBuckle or whatever that method was called, which contains some checks

Tried to fix this a while ago.
TryUnBuckle doesn't fix it
