### ISSUE TITLE
The inventory button is still appearing even if entity has no slots

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#30336]
1. become a ghost
2. press inventory button
3. it dissapears
https://github.com/user-attachments/assets/fbf2c16d-49d6-4289-aed9-f091a5b6727a

**Comment by IProduceWidgets** [comment]
Can confirm I get this bug a lot. No idea how to repro it though, seems mostly random, or maybe related to trying to open a UI someone else has open / is wearing.
