### ISSUE TITLE
cant put fire extinguisher back in place

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#30335]
https://github.com/user-attachments/assets/62d3ae18-cbfe-4ca0-a1d6-4583db78b985

**Comment by deltanedas** [comment]
fire axe cabinet still works so this is very sus

**Comment by IProduceWidgets** [comment]
https://github.com/space-wizards/space-station-14/blob/af47cbd7b0389098d263248ca380b1940e400821/Resources/Prototypes/Entities/Structures/Wallmounts/extinguisher_cabinet.yml#L33
Component got removed and changed into something generic.
Needs a tag and set here. probably shouldn't accept the pocket extinguisher.
https://github.com/space-wizards/space-station-14/blob/af47cbd7b0389098d263248ca380b1940e400821/Resources/Prototypes/Entities/Objects/Misc/fire_extinguisher.yml#L73

**Comment by deltanedas** [comment]
i love whitelist not existing silently beinhg ignored by tests :trollface:
