### ISSUE TITLE
space dragon traitor in custody

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#30351]
i dont know how
![image](https://github.com/user-attachments/assets/2a42d2fb-2a82-4997-9bbe-a0f22142f665)

**Comment by muburu** [comment]
pretty sure they rolled sleeper somehow, even though this is supposed to be fixed and not happen in the first place

**Comment by dolgovmi** [comment]
Is it possible it was a syndicate who later got a space dragon by ghosting or something

**Comment by Dutch-VanDerLinde** [comment]
they did not roll sleeper 

Reproduction:
- roll traitor
- die
- win space dragon raffle
- ghostroles like loneops and space dragon re-use the mind, so you'll have both traitor and dragon objectives
- if your old body was arrested, then you'll appear "in custody"

**Comment by Dutch-VanDerLinde** [comment]
so just create new mind for space dragon ghostrole

**Comment by Brandon-Huu** [comment]
The syndicate are hiring space dragons now!?!

**Comment by baddiePRO** [comment]
> ghostroles like loneops and space dragon re-use the mind, so you'll have both traitor and dragon objectives

same goes for space ninja
