### ISSUE TITLE
Box station TEG is designed to troll players

### ISSUE THREAD

**Issue by RadioAndrea** [space-wizards/space-station-14#30364]
### The Box Station TEG is designed to troll (especially new) players due to:

1. Burnbox is tiled in floorthat when crowbared turn into in individual steel rods that are very hard to pick up without replacing the floor, and you can often accidentally click on them if you don't pick them up as they leave diagonal jail bars. Additionally this floor hides the pipes to anyone not using a T-Ray, and obscures the fact that the burnbox radiator does absolutely nothing. This is FRUSTRATING.

2. The burnbox radiator does nothing. Nothing at all. Radiators require flow in order to do the temp delta, so a radiator on a random pipe loop doesn't do anything. If you have no experience with radiators you will get very frustrated why the way the game shows you to use them doesn't work.

3. The external cooling loop also does nothing! Did radiators used to work on still gas? This is a trap for new players as they will assume they can just slap radiators on and they will work. They will get frustrated because the game lied to them about how a mechanic functions.

4. Time to setup a functional TEG is extended significantly due to the scutt work of having to crowbar up floor, collect all the tiny rods one by one, unwrench all the bad pipes, weld them all down to bare steel, ghostplace and build your real setup, realize you need more steel and run out and look for it while the whole station yells at engineering for not making power etc. etc. Obviously frustrating.

5. There is a one-click grief valve for your atmosyndie/shitter to open and equalize the hot and cold sides if you don't remove, which is HILARIOUS and therefore should NOT be changed, no cap.

**Reproduction**

1. Go to Box station as an atmos/engi
2. Set up the TEG under time pressure, don't worry the whole station is counting on you
3. Drag the welding fuel in from engilounge just so you can finish welding your hoard of pipes.
4. Realize that it is, indeed, frustrating for literally no reason

**Screenshots**
![image](https://github.com/user-attachments/assets/0d038cc8-a870-4b01-b29f-0e546051f66d)
Why

**Additional context**
Honestly this wasn't as troublesome before the AME nerf, but now it's more important to have secondary power running, and important to have it faster. Because of this, the pain of this setup is really obvious and honestly needs rework.

If suggestions are welcome, I would like to present an alternative bare setup that encourages rather than trolls the players:

![image](https://github.com/user-attachments/assets/60ce212e-cfb0-448f-8ebd-b8aba8ced4d3)

I would be happy to update map with permission from the map-master.

**Comment by Emisse** [comment]
go ahead

**Comment by deltanedas** [comment]
every ss13 ported map is like this

**Comment by RadioAndrea** [comment]
> every ss13 ported map is like this

I did not realize this. That would fully explain why the layout is how it is, as I believe radiators didn't need flow in SS13.

After quick investigation I noted maps that need a TEG rework because of the same issue:
- [ ] Fland
- [ ] Bagel
- [ ] Marathon
- [ ] Packed

All the others appear to not have the same issue and are updated/originally made to be radiator-aware!
