### ISSUE TITLE
THE in emoting should use CAPITALIZE

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#30377]
it just looks bad
![Screenshot_20240726_184917](https://github.com/user-attachments/assets/9dc6dce4-db3f-4028-82af-82fc69c2b79e)
![Screenshot_20240726_175444](https://github.com/user-attachments/assets/37b2f5d7-202e-412b-8abc-75f2241be9c2)

**Comment by deltanedas** [comment]
shouldnt use the in either case since theyre proper nouns

**Comment by lzk228** [comment]
> shouldnt use the in either case since theyre proper nouns

mice also use the

**Comment by deltanedas** [comment]
mouse isnt a proper noun
