### ISSUE TITLE
Box station probably needs a SMES for the singulo area

### ISSUE THREAD

**Issue by Plykiya** [space-wizards/space-station-14#30375]
## Description

Seen a few singularity loosey gooseys because it didn't have enough initial starting power to maintain the emitters

![image](https://github.com/user-attachments/assets/13bfe210-87dc-46fe-9175-4a34cce0c078)

**Reproduction**

**Screenshots**

**Additional context**

**Comment by southbridge-fur** [comment]
I'll look into this. I feel like the issue may be the fact the primary SMESes are kind of far away from the power generation room relative to other maps.

**Comment by southbridge-fur** [comment]
Turns out that is not the issue, the primary SMESes are disconnected from the containment field network. I'm working on a couple solutions to this.
