### ISSUE TITLE
oxygen and nitrous oxide have the same color in gas analyzer

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#30382]
bad accessability
![Screenshot_20240726_213046](https://github.com/user-attachments/assets/f258232d-a0e4-4c7b-aa86-2bbb4099804c)

**Comment by slarticodefast** [comment]
[gases.yml](https://github.com/space-wizards/space-station-14/blob/master/Resources/Prototypes/Atmospherics/gases.yml) is for setting the gas color if someone wants to change this.

**Comment by dbrezack** [comment]
![main-qimg-5737fb0d086de60cfbc750224f996bb7-lq](https://github.com/user-attachments/assets/cc68bc3e-73b7-4bbc-b4eb-ff08a51d90ff)
Happy to fix. Anyone object to using the standard US colors ?
