### ISSUE TITLE
Zombie Cuffing Broken Again

### ISSUE THREAD

**Issue by dbrezack** [space-wizards/space-station-14#30396]
## Description
Cannot un cuff once you become a zombie
Could be because I was initial infected and not converted
https://github.com/space-wizards/space-station-14/pull/21021

Could also be with makeshift cuffs Possibly related to https://github.com/space-wizards/space-station-14/issues/30312

**Comment by themias** [comment]
Fixed by #30321, just wasn't published yet when this was opened.
