### ISSUE TITLE
Thief selection might still be cooked

### ISSUE THREAD

**Issue by Plykiya** [space-wizards/space-station-14#30409]
## Description

I'm intending it to always try to select up to three thieves but I've had some rounds with zero thieves and some round with three thieves. Zero shouldn't happen because the minimum is set to one...
https://github.com/space-wizards/space-station-14/pull/30393

I'll probably work on making a command to simulate antag selection at this rate so we can figure out what the distribution is like. At this moment I'm just viewing replay round end summaries to figure out if we have more than one thief or not.

**Reproduction**

**Screenshots**

![image](https://github.com/user-attachments/assets/c52157de-04c8-48ea-b78b-9b933c0d37d3)

**Additional context**

**Comment by EmoGarbage404** [comment]
Thief isnt guaranteed to always be picked so thats why you can have 0 thieves

**Comment by Plykiya** [comment]
guh maximum

**Comment by Plykiya** [comment]
Alright I've seen enough round-end summaries, we're GOOD.
