### ISSUE TITLE
under-pressure lock out cannot be disabled without setting air alarm to fill mode

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#30401]
probably should be button like "Ignore pressure lock out" for vent settings
https://github.com/user-attachments/assets/8580be8d-6040-4b0c-b041-3ab21fcc8072

**Comment by Magicalus** [comment]
Isn't this the point of air alarms? All the vents on a station are connected to air alarms, and if you leave auto mode on it'll just return to filter mode after filling the room.

**Comment by lzk228** [comment]
it will give more flexibility, because if you change mode - ALL connected devices will be affected
