### ISSUE TITLE
non-antag monkey event on syndicate station

### ISSUE THREAD

**Issue by jamilnielsen** [space-wizards/space-station-14#30418]
## Description
was a ghost, watching the nukies prepare, suddenly a monke event triggered, on syndicate station, they accepted me and gave me everything i could have wanted, anyway non-antag monke should proably not happen there.

**Reproduction**
get the 1 in a million event.

**Comment by JIPDawg** [comment]
You sure it was a monkey reinforcement?

**Comment by jamilnielsen** [comment]
> You sure it wasn't a monkey reinforcement?

i do actually read the text, it was green and said something like non-antag, i was at the pen with moneys, i was not spawned.

**Comment by Dutch-VanDerLinde** [comment]
> You sure it wasn't a monkey reinforcement?

there are monkey cubes on nukie planet

**Comment by JIPDawg** [comment]
Ah yeah that makes sense. I feel like it's so rare to happen it's probably fine? But I'm not an admin.

**Comment by jamilnielsen** [comment]
they might slaughter the nukies while they are prepping instead of disregarding team and helping em.
its a 1 in a million, but it COULD happen.
but yea figured i would report it, im not expecting a fix.
