### ISSUE TITLE
Napalm fire can be extinguished with napalm

### ISSUE THREAD

**Issue by Brandon-Huu** [space-wizards/space-station-14#30417]
## Description

Pouring napalm on someone who is burning alive from napalm will extinguish them.

**Reproduction**

1. Pour 10000000000000000000000000000u of napalm on someone
2. Light them on fire.
3. Extinguish them with more napalm

**Screenshots**

[Screencast from 07-27-2024 06:18:40 PM.webm](https://github.com/user-attachments/assets/dc2564a9-f610-4815-8774-3b7764bd1632)

**Additional context**

**Comment by Dutch-VanDerLinde** [comment]
dupe #28445

**Comment by Brandon-Huu** [comment]
> dupe #28445

That's crazy why has no one fixed that yet
