### ISSUE TITLE
Generic storage tanks are useless

### ISSUE THREAD

**Issue by pigeonpeas** [space-wizards/space-station-14#30416]
## Description
You can't fill empty storage tanks with liquid no matter how hard you try

**Reproduction**
Find an empty storage tank.
Try to add liquids to it.
You can't.

**Screenshots**
![image](https://github.com/user-attachments/assets/4a7046b5-8c49-4de2-b0bb-024f243489e0)

**Additional context**
The storage tank i tried this on was mapped onto a station. I am unsure if that makes a difference.

**Comment by IProduceWidgets** [comment]
What station? And this is probably intended and should just be a base item.

**Comment by lzk228** [comment]
> And this is probably intended and should just be a base item with hideSpawnmenu.

useful for mapping when you want to feel the tank with certain fluid

**Comment by IProduceWidgets** [comment]
> > And this is probably intended and should just be a base item with hideSpawnmenu.
> 
> useful for mapping when you want to feel the tank with certain fluid

I'm pretty sure refilling them will break welders and stuff though

**Comment by pigeonpeas** [comment]
> What station? And this is probably intended and should just be a base item with hideSpawnmenu.

Core

**Comment by UbaserB** [comment]
I do remember mapping it, but I literally cannot find it anywhere no matter how hard I search. I'll check it out manually in the file by searching up the id afterwards, otherwise i guess it was migrated out or something?

**Comment by UbaserB** [comment]
Yeah, I believe it's gone
