### ISSUE TITLE
sometimes venging machines maintance panel doesn't have the access light

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#30421]
happened with me few times
![Screenshot_20240728_014458](https://github.com/user-attachments/assets/31d2bb26-89ee-46bb-9855-2b5845ac84d0)
![Screenshot_20240723_193015](https://github.com/user-attachments/assets/40f12dbf-1172-40b2-96c9-57ab7e957467)

**Comment by deltanedas** [comment]
log wire trolling it somehow

**Comment by lzk228** [comment]
have to add, its an issue with all vending machines

**Comment by deltanedas** [comment]
actually why are there 6 wires theres only 5 actions

**Comment by lzk228** [comment]
> actually why are there 6 wires theres only 5 actions

read the title noob, you forgot about the access wire, as i said the access wire doesnt want to display
