### ISSUE TITLE
differences between monkeys and kobolds

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#30451]
- kobolds has less hp
- kobolds give 2 meat, monkeys give 3

**Comment by Brandon-Huu** [comment]
kobolds faster?

**Comment by Brandon-Huu** [comment]
kobolds aren't clumsy?

**Comment by UbaserB** [comment]
This was intended on PR creation, unsure if it's an issue.

**Comment by beck-thompson** [comment]
I'm pretty sure this is intended from the original PR!
