### ISSUE TITLE
Lathes have screen animations that are hidden by thier non-animated glow layer

### ISSUE THREAD

**Issue by snebl** [space-wizards/space-station-14#30470]
## Description

The proto/auto lathe animations also animate the little screens on their sprites, but you never see it in-game because the screen background glow is placed over it. This is likely an oversight made while porting them from ss13.

**Screenshots**

Currently the screens on all four lathes remain blank weather idle **or while building**.
![image](https://github.com/user-attachments/assets/fafe2268-7695-4cad-a244-5077ec57c275)

The screen is supposed to animate while building but its always hidden by the non-animated unlit texture for each lathe.
![image](https://github.com/user-attachments/assets/4b299b27-e78e-42de-9a81-c297746846cc)

**Comment by EmoGarbage404** [comment]
ive been aware of this for ages but ive been too lazy  to go do it :P

guess ill do it now
