### ISSUE TITLE
Train needs a SpawnPointParamedic

### ISSUE THREAD

**Issue by slarticodefast** [space-wizards/space-station-14#30477]
![grafik](https://github.com/user-attachments/assets/e79b3cf0-70b6-41e3-be07-c4a0a39d249e)

We have the room and the locker for them, but no spawn point in there.

![grafik](https://github.com/user-attachments/assets/8486341d-93c5-4d10-9b6b-94d9c82d0b88)

Currently Train has no job slots for paramedics, but we can probably exchange one of the medics for the paramedic.

**Comment by Brandon-Huu** [comment]
If no one else is doing a map PR for train I can do this.
1 minute PR
