### ISSUE TITLE
SolutionContainerManager is cooked

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#30485]
just look at handheld text and count of reagent

https://github.com/user-attachments/assets/96d12818-9aa2-481e-834e-11571489c55e

**Comment by Veritable-Calamity** [comment]
@Jezithyr I think you're replacing `SolutionContainerManager` entirely in the chem refactor?

**Comment by Jezithyr** [comment]
> just look at handheld text and count of reagent
> 2024-07-30_07-58-21.mp4

Reagents/Solutions/Reactions is being rewritten as part of #30254
SolutionContainerManager is being effectively removed with it's functionality being moved to SolutionSystem (Or possibly into ChemistrySystem). I will be keeping SolutionContainerSystem around to serve as a redirect to the new functionality for backwards compatibility.
