### ISSUE TITLE
N/S/W recylcer sprites are missing

### ISSUE THREAD

**Issue by IamVelcroboy** [space-wizards/space-station-14#30500]
## Description
Rotating the recycler any direction other than East is bad.

**Reproduction**
Rotate the recycler any direction other than East

**Screenshots**
Wha!? 
![image](https://github.com/user-attachments/assets/9d54f236-473b-49bf-912a-8ebe6308054d)

**Additional context**
I'm not a great spriter. Just hoping someone will make proper sprites for all directions

**Comment by slarticodefast** [comment]
Tg has the sprites in all rotations and in a bloody variant [here](https://github.com/tgstation/tgstation/blob/master/icons/obj/machines/recycling.dmi).

**Comment by godtierprogrammer** [comment]
![grinder-o1](https://github.com/user-attachments/assets/e193f816-8b51-4137-9159-1a4778f29797)
![grinder-o1bld](https://github.com/user-attachments/assets/0809ba29-09d9-47cc-aec7-dd2b12589a4c)
![grinder-oOpen](https://github.com/user-attachments/assets/4d666fa4-3308-40e7-8720-da37cac4394b)
I did the conversion, I'm just too stupid to understand how to get the project to build. Hope someone can actually merge this.

**Comment by EmoGarbage404** [comment]
i'm working on recycler stuff rn so i'll handle the sprites
