### ISSUE TITLE
Slimes (from influx event) drops brain on gibbing

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#30521]
1. wait for slimes influx event 
2. gib a slime
3. free brain

**Comment by IProduceWidgets** [comment]
Hmmmm. Im not sure what the right solution to this is. afaik it needs a mind container, which the brain is.

**Comment by IProduceWidgets** [comment]
I'm struggling to see if this is problematic.

**Comment by lzk228** [comment]
> afaik it happens to lots of gibbed mobs

no, only humanoids

**Comment by Brandon-Huu** [comment]
What is the event actually called?

**Comment by IProduceWidgets** [comment]
> What is the event actually called?

https://github.com/space-wizards/space-station-14/blob/bb2981400cb34d476dd7f6f90aba4d0209dab047/Resources/Prototypes/GameRules/events.yml#L364
