### ISSUE TITLE
Uplink description of Sus toolbox lies, no toolbelt included.

### ISSUE THREAD

**Issue by TurboTrackerss14** [space-wizards/space-station-14#30559]
## Description
https://github.com/space-wizards/space-station-14/blob/1fcbaa132fd942a4ec042ff9230ef17e7ce424c1/Resources/Locale/en-US/store/uplink-catalog.ftl#L248

**Reproduction**
>Buy Toolbox
>No Toolbelt 
> 😢 

**Screenshots**
![image](https://github.com/user-attachments/assets/98d5d76c-04fa-4173-ac11-85e144eb0f67)
![image](https://github.com/user-attachments/assets/aa50a9bc-641a-46f5-81b4-a27be020ae73)

**Additional context**

**Comment by JIPDawg** [comment]
So we should make it include the belt right and not just remove it from the description?

**Comment by NakataRin** [comment]
Utility belt was firstly added into the toolbox in #14802, but later it was removed in #21250. Emo probably just forgor about locale tweaking, I'll fix in in a few (so, no belt, sorry)
