### ISSUE TITLE
Battery weapons with BatterySelfRecharger tends to not recharge to max capacity, instead stopping at max - 1

### ISSUE THREAD

**Issue by bruhmogus** [space-wizards/space-station-14#30558]
## Description
Title.

**Reproduction**
Step 1. Fire a bunch of antique laser pistols or advanced laser pistols until it "jams" at 9.

**Screenshots**

https://github.com/user-attachments/assets/dfa8b2d8-6e43-482e-a49f-929ec0f92fde

**Additional context**
My best guess is that it recharges mid-firing and breaks

**Comment by Nootaro** [comment]
I had this happen on Frontier yesterday. But it seemed to only be a visual bug and the max charge was actually still 10 shots.

**Comment by Brandon-Huu** [comment]
> I had this happen on Frontier yesterday. But it seemed to only be a visual bug and the max charge was actually still 10 shots.

It wasn't at 10 shots. It was at 9 but extremely close to 10. close enough that it near instantly reached 9 shots again after you shot it.
