### ISSUE TITLE
Problem with audio devices

### ISSUE THREAD

**Issue by qrwas** [space-wizards/space-station-14#30569]
## Description
If you turn your audio device off and on while playing, the sound will disappear until the game restarts.
**Reproduction**
Connect an audio device
Enter the game 
Hear the sounds
Turn off the audio device
Connect an audio device
Do not hear sounds

**Additional context**
I wouldn't say it's a big problem if you have good headphones that don't disconnect on their own, you'll hardly notice this bug until you have to change the output device for some reason. But the ability to change the output device during the game will be a good feature

**Comment by metalgearsloth** [comment]
https://github.com/space-wizards/RobustToolbox/issues/3295

also engine stuff.

**Comment by qrwas** [comment]
2 years, sad...

**Comment by metalgearsloth** [comment]
Last time I looked it needed an OpenAL update to cleanly support context switching.

**Comment by little-meow-meow** [comment]
Backlinks to space-wizards/RobustToolbox#4737
