### ISSUE TITLE
Science radio text is too vibrant

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#30573]
## Description

It physically hurts my eyes looking at it for too long.

**Screenshots**

![image](https://github.com/user-attachments/assets/b4ff5408-8d02-42ee-8b86-3f1ee163c144)

**Comment by JustCone14** [comment]
@Moomoobeef

**Comment by Errant-4** [comment]
I had enough of these issues, I'm gonna make the colors user-adjustable

**Comment by Moomoobeef** [comment]
Sorry. 
Also about it being too similar to ghost chat color I was going to fix that and I said I would but then I forgot and it was merged before I got around to it

**Comment by Moomoobeef** [comment]
I'd offer to make a PR fixing these things but I'm about to be away from home for 2 weeks so I can't

**Comment by Moomoobeef** [comment]
(still away from home :P)
