### ISSUE TITLE
Honki Unknown shuttles are fratricide boxes.

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#30598]
## Description
The Honk clowns that spawn with the clown ghost roles have AIs in them and their factions are not aligned so a common outcome of a honkmother unknown shuttle event is that all the clowns get murdered from the spiders then the spiders cant fly to station.

**Reproduction**
- addgamerule UnknownShuttleHonki
- Let the clownspiders have clean path to clowns.
- Watch em all kill each other.

**Screenshots**
NA

**Additional context**
Pretty sure this can be solved by putting both of them on a new Honki faction or similar. Same with the clowns. Clown spiders currently inherit the Xeno faction from the parent proto and the clowns are in Nanotrasen.
Would be really nice if the other honk related things(behonker, cluwne, etc) also had this faction for events etc too. so they don't murder each other....

**Comment by UbaserB** [comment]
I've often, infact *very* often seen clown spiders break out of their enclosure and kill all of the clowns on the shuttle before anyone takes the roles. Even if someone takes the roles, this doesn't stop the spiders from killing them either way.
