### ISSUE TITLE
Ghost roles will fail people's kill objectives

### ISSUE THREAD

**Issue by Plykiya** [space-wizards/space-station-14#30596]
## Description

![image](https://github.com/user-attachments/assets/be283425-8eee-4e04-a7bb-44c210d8eb1a)

**Reproduction**

**Screenshots**

**Additional context**

**Comment by deltanedas** [comment]
fixed by spawner pr

**Comment by Plykiya** [comment]
fixed by https://github.com/space-wizards/space-station-14/pull/30354
