### ISSUE TITLE
Kobold Reinforcements wrong UI icon

### ISSUE THREAD

**Issue by Errant-4** [space-wizards/space-station-14#30608]
## Description
On the Genetic Ancestor REinforcement Beacon's UI, Kobold Reinforcements don't have their own icon, they use the traitor monkey sprite. Probably same for the nukie version

**Screenshots**
![image](https://github.com/user-attachments/assets/88837852-e51a-42f8-9dad-9140b1898ed0)

**Comment by Plykiya** [comment]
kinda confused by that one personally since the icon comes from the entity, I chose to look away and not fix it lol

**Comment by Errant-4** [comment]
Can probably look at the regular Reinforcement Beacon to see how that one gets/sets the icons
