### ISSUE TITLE
Station Nuke cannot be armed multiple times.

### ISSUE THREAD

**Issue by jamilnielsen** [space-wizards/space-station-14#30619]
## Description
just had a round were all Heads armed the station's nuke just to defuse it, clearly abusing the fact that a nuke that has been defused cannot blow up, this seems lame and boring to me, please patch this.
to be specific im talking about the station's nuke, and there was no threats revealed at the time.

**Comment by lzk228** [comment]
so the issue is defused nuke cannot explode anymore? if it is, please change the name of issue to something more precisely

**Comment by EmoGarbage404** [comment]
How can they arm it without the code?

**Comment by deltanedas** [comment]
i have seen a loneop arm a nuke, crew disaem it then loneop rearm because crew left disk in. snopes factcheck: fake
