### ISSUE TITLE
Spamming click on a chair while holding movement keys.

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#3063]
## Description

I'm not sure if this is a bug, but it looks pretty janky. Could probably just put a cooldown on it.

1. Buckle to chair.
2. Spam click chair while holding movement keys.

**Screenshots**

![2021-01-31_11-03-29](https://user-images.githubusercontent.com/49448379/106394900-22fcd900-63f7-11eb-8c88-41274ebe7061.gif)

**Comment by PaulRitter** [comment]
AFAICT this is due to buckling not being predicted

**Comment by AJCM-git** [comment]
Cant reproduce anymore, i dont thing buckling is predicted yet but thats something for a new issue.
