### ISSUE TITLE
command intercom should be secured as the sec one

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#30637]
#29580
security intercom has more protection than command

**Comment by ZombieChibiXD** [comment]
What you mean by secure or protection?

**Comment by lzk228** [comment]
> What you mean by secure or protection?

check related pr

**Comment by ZombieChibiXD** [comment]
Seems like Emo missed it before the PR got pulled. Shame. I don't think it's such a high security thing however, I've never seen command intercom mapped anywhere, and if it exist, it stays within the bridge outside of public area.
