### ISSUE TITLE
Folded folding chairs damage values cannot be inspected

### ISSUE THREAD

**Issue by Spessmann** [space-wizards/space-station-14#30663]
## Description

Folded folding chairs damage values cannot be inspected despite being able to do damage and be used and swung like a weapon
**Reproduction**

1. Fold any folding chair
2. attempt to inspect damage values
**Screenshots**

![Screenshot 2024-08-04 210435](https://github.com/user-attachments/assets/d5d66ecf-067c-45f0-afe6-d4ab8a96983a)

![image](https://github.com/user-attachments/assets/4b5502ff-e3a1-4b6f-a782-b77a29fee10b)

**Comment by lzk228** [comment]
it was removed iirc

**Comment by TurboTrackerss14** [comment]
https://github.com/space-wizards/space-station-14/blob/f7d8b4e7d469c03f4adab33307af4a44e44b0319/Resources/Prototypes/Entities/Structures/Furniture/chairs.yml#L343
seems to still be there 🤷
