### ISSUE TITLE
Banana cream pies reveal identity

### ISSUE THREAD

**Issue by slarticodefast** [space-wizards/space-station-14#30676]
## Description
See title

**Reproduction**
- Give a mask to an Urist without an ID so they get an unknown identity
- Throw a banana cream pie at him
- The popup will say "Urist McHands ..."

**Screenshots**
![Screenshot (219)](https://github.com/user-attachments/assets/579e1963-77df-4acd-a6a9-20872d1caa53)

![Screenshot (221)](https://github.com/user-attachments/assets/8a145088-cf2b-4f85-b371-fc4925d07327)

**Additional context**
It should use the Name function in Content.Shared.IdentityManagement instead.
Good for a beginner PR.

**Comment by Brandon-Huu** [comment]
I'll fix

**Comment by Brandon-Huu** [comment]
Also that is a weird asf LOC, cream-pied-component-on-hit-by-message-others

**Comment by slarticodefast** [comment]
Has to do with this I think #18540

**Comment by Brandon-Huu** [comment]
> I'll fix

I wont fix.

**Comment by Brandon-Huu** [comment]
I'll fix

**Comment by tosatur** [comment]
I can take this one on if @Brandon-Huu is no longer working on it

**Comment by Brandon-Huu** [comment]
> I can take this one on if @Brandon-Huu is no longer working on it

Yeah, do that.
