### ISSUE TITLE
(re)joining the game makes every tile become space on the client

### ISSUE THREAD

**Issue by adamc295** [space-wizards/space-station-14#3068]
## Description
title, if you join a game while a round is going on, every tile becomes space, and it prevents you from making new grids

**Screenshots**
![2021-2-01_16 27 58](https://user-images.githubusercontent.com/18663194/106487832-fd310c00-64aa-11eb-8258-a1f4d5f0e129.png)

before: 
![2021-2-01_16 32 46](https://user-images.githubusercontent.com/18663194/106488014-2ce01400-64ab-11eb-97f5-fb7105cb3707.png)

after: 
![2021-2-01_16 32 53](https://user-images.githubusercontent.com/18663194/106488034-30739b00-64ab-11eb-85fe-d0bbc863d20f.png)

**Additional context**
this was on EU West, might be on other servers too but haven't tested it

**Comment by adamc295** [comment]
this *might* be an engine issue, and i've also had two other players (complete randos) confirm this as well. it also prevents picking up items.

**Comment by adamc295** [comment]
probably should make the title a little less clickbaity-ish

**Comment by PaulRitter** [comment]
yeah this seems like a render-bug, since you don't actually suffocate. at least as far as i could tell from your bug report

**Comment by Zumorica** [comment]
I can't replicate this. Has anybody experienced this lately?

**Comment by Zumorica** [comment]
Probably fixed by d00c71a092be2694616a5fb0ec0036a2942abc2a, if it wasn't fixed already.
