### ISSUE TITLE
Creatures that die while pulled allows them to be pushed from any range

### ISSUE THREAD

**Issue by Spessmann** [space-wizards/space-station-14#30698]
## Description
I wrote a very bad title for this but I have no idea how to make it more readable. So if a mob (human, mouse, cat, etc) is getting pulled and dies they are still "pulled" despite not getting pulled behind the user, which then allows them to move that pulled object (ctrl + RMB) from any range, however they cannot push AWAY from them farther than normal, but can pull it from anywhere TOWARDS them
**Reproduction**

Step 1: drag a mob (human, mouse, cat, etc)
~~Step 2: increase their flammability(I found welding fuel works)
Step 3: set them ablaze (I used a basic lighter in the videos)
Step 4: wait for them to die~~
Step 2: Have them die
Step 5: walk away from the corpse while still pulling them (they should stay in one spot)
Step 6: Press the keybind to "Move pulled object"(ctrl + RMB)
Step 7: They should now move towards you as if you were pushing it (you may have to press multiple times)
**Screenshots**

(videos show it working on both human and mouse)
https://github.com/user-attachments/assets/44b8c90c-e5ce-4666-98ef-de6e7546ee8d

https://github.com/user-attachments/assets/203c80f5-b48a-4ff7-a7b7-613c540dc468

**Comment by bruhmogus** [comment]
this happens with basically every death method

**Comment by Spessmann** [comment]
If thats the case ill change the title

**Comment by lzk228** [comment]
the fix isn't merged  yet #30532
