### ISSUE TITLE
Saltern janitor closet needs a space cleaner dispenser

### ISSUE THREAD

**Issue by Plykiya** [space-wizards/space-station-14#30692]
## Description

**Reproduction**

**Screenshots**

**Additional context**

**Comment by bruhmogus** [comment]
it HAS one

**Comment by Brandon-Huu** [comment]
![image](https://github.com/user-attachments/assets/e93dc113-9209-447a-b282-6a2a21c4ed37)
Yeah it already has one

**Comment by Plykiya** [comment]
man I'm blind as hell
