### ISSUE TITLE
Movement prediction breaks apart at poor connections.

### ISSUE THREAD

**Issue by AJCM-git** [space-wizards/space-station-14#3077]
## Description
When certain poor networking requirements  are met (exactly which is unknown but i have experienced this more when there are many ping spikes between 350-430ms, but it still happens less frequently at ~200ms sometimes) you start moving at ~800 tiles per second (approximate) when moving due unknown reasons (my guess is that the client gets sent too many states at once).
If movement prediction was working correctly you would move normally and teleport when the server corrects your position, instead we have these weird laps.
Any idea why this happens and how to fix it would be appreciated.

**Videos**
At 390-450ms: https://cdn.discordapp.com/attachments/310555209753690112/791151042729213952/output.mp4
at 150-200ms: https://cdn.discordapp.com/attachments/770682801607278632/792492551567048744/simplescreenrecorder-2020-12-26_16.40.16.mp4

**Additional information**
- CPU:  Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz (4 cores)
- OS: Linux
- Discord discussion about this: https://discord.com/channels/310555209753690112/310555209753690112/806673379474014228
- At least one other person has experienced this
- `net.interp_ratio` doesnt seem to do much

**Comment by metalgearsloth** [comment]
Is this still an issue? I play at ~300ms and it seems okay to me.

**Comment by AJCM-git** [comment]
This doesnt seem to be an issue anymore
