### ISSUE TITLE
You can tell who's a syndie as an observer.

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#30779]
## Description

When someone is selected as a syndicate through sleeper, round-start, or late-join, then there will be an immobile ghost spawned and their job shows up as unknown in the menu. Supposedly it's been like this for a few days, but I just experienced this in round #62022 on hopper.

**Screenshots**

![image](https://github.com/user-attachments/assets/15a413e9-b03e-45a2-b1aa-96585def9143)

![image](https://github.com/user-attachments/assets/57eb2a5b-d898-4071-9db1-ba3c30511993)

**Comment by Plykiya** [comment]
still?? didn't this get fixed?

**Comment by Errant-4** [comment]
Can't repro on the patched master

**Comment by slarticodefast** [comment]
I think hopper is not automatically updated to the current build, so it might take a few days to get patched there.

**Comment by Errant-4** [comment]
I'm told it gets restarted automatically now, but also I see the issue on Vulture too

**Comment by UbaserB** [comment]
i havent seen it anymore so
