### ISSUE TITLE
Singulous is broken on station NTVG PACKED PR-021

### ISSUE THREAD

**Issue by YetiYetYet** [space-wizards/space-station-14#30791]
## Description
On this station, for an unknown reason, we can't set up any singulous. This makes this station unstable with power when people don't know how to set up the TEG (and that append a lot).

**Reproduction**
Normal setup like all other stations.

**Additional context**
A lot of players (me too) try to set up it correctly and don't understand why it didn't work on this station, even robust players don't understand why.

**Comment by PJB3005** [comment]
> for an unknown reason, we can't set up any singulous. 

What do you mean cannot set up? There are many components to the singulo and you did not elaborate what you were having an issue with.

For reference, I just tested and was able to start the singulo on Packed just fine on a local server.

**Comment by YetiYetYet** [comment]
I'm going to try again when I will be engineered on this map on a server and try to show you a video

**Comment by JustCone14** [comment]
Also how many is a lot of players? I set up a singulo on packed on Tuesday on my own and it was fine.

**Comment by YetiYetYet** [comment]
Ok, I just understand, it works, but I don't know if it's on purpose or not. MV cable is not set up on this station, and a lot of players forgot to put it.  On other station the MV cable are already set up but not on this one.
If it's on purpose, maybe you should add more MC at the start near of the singulous so other player can understand.
If it's not, maybe you should just add them because a lot of players get confused by that, in other station it set up but not on this one...

**Comment by IProduceWidgets** [comment]
actually Im just going to rename this for packed because it probably just didn't get updated when the singulo changed.

**Comment by PJB3005** [comment]
What? No. The problem is that the emitters don't have an MV wire set up already, which is pretty damn obvious. The PA itself is fine.
