### ISSUE TITLE
"Antag Rolling" appears to have been removed from the written server rules.

### ISSUE THREAD

**Issue by Admiral-Obvious-001** [space-wizards/space-station-14#30804]
We just noticed this on Discord.

Not sure where it went, but we assume it's still a rule in place?

**Comment by Jarmer123** [comment]
![image](https://github.com/user-attachments/assets/42508f04-91b1-4b1d-80e3-84cca7eba81e)

Covered under "Do not abandon your role"

**Comment by IProduceWidgets** [comment]
Full rule text here: 
![image](https://github.com/user-attachments/assets/c959d540-0a73-41a0-830b-1324c658a472)
