### ISSUE TITLE
Replays can't open

### ISSUE THREAD

**Issue by VasilisThePikachu** [space-wizards/space-station-14#30801]
## Description

Replay loading fails due to some asteroid missing a component or something.

**Reproduction**

https://moon.spacestation14.com/replays/lizard/2024/08/09/lizard-2024_08_09-00_30-round_62078.zip
https://moon.spacestation14.com/replays/lizard/2024/08/08/lizard-2024_08_08-20_58-round_62063.zip

Replays after Aug 8, 2024, 12:01 PM GMT+2 (#30764 (publish version hash f24949a0b0cf2adace76bbfefa9f6df91303f67a))

**Screenshots**

![image](https://github.com/user-attachments/assets/47ca9d53-4972-4a07-8518-6f39bc759311)

**URGENT DISTURBS ADMIN WORK AND PLAYER EXPIRIENCE**

**Comment by metalgearsloth** [comment]
Probably the broadphase change if physicsmap isn't getting serialized, needs a dev to look at it.

**Comment by Hrosts** [comment]
They actually open. You need to wait and keep closing the popping Error windows. It will go through "Reading Files" 8 or less times and then will load the replay as usual. Don't press the "lower exception treshold" button, just close the pop ups.

**Comment by Titian3** [comment]
> They actually open. You need to wait and keep closing the popping Error windows. It will go through "Reading Files" 8 or less times and then will load the replay as usual. Don't press the "lower exception treshold" button, just close the pop ups.
> 
> With each popup it will increment the entity ID, each being a kind of asteroid or a wreck.
> 
> I went through a replay of a round of mine almost from start to finish and saw no major issues, but that is a very small sample.

Thank you for this!

**Comment by VasilisThePikachu** [comment]
Should be fixed by a commit in engine, engine updated at PR #31297
