### ISSUE TITLE
Bows create light upon firing, despite that not being how bows work

### ISSUE THREAD

**Issue by bruhmogus** [space-wizards/space-station-14#30841]
## Description
Title. They will create a lightsource (and i believe a muzzleflash) upon the arrow being fired.

**Reproduction**
Step 1. Load an arrow into a bow
Step 2. Fire

**Screenshots**
![20240809230225_1](https://github.com/user-attachments/assets/121d2b4a-a3d7-416e-b8a0-4b1b8bcc2cc4)

**Additional context**
Probably something wrong with the gun component.

**Comment by Hreno** [comment]
I don't see any light in the latest master commit.

[Peek 2024-08-10 18-18.webm](https://github.com/user-attachments/assets/f4ece214-0ae6-42c6-ad63-c97fb5358223)

**Comment by IProduceWidgets** [comment]
Yeah looks fine on live today.
