### ISSUE TITLE
New Item Design the HandheldPowerMonitor

### ISSUE THREAD

**Issue by maximus-not** [space-wizards/space-station-14#30866]
## Description
i want to make a new Handheld; called the handheld power monitor
it would be like the handheld crew monitor 
but; 
-would only be for the CE
-and it would act like the handheld crew monitor but would display the power monitor console instead
-this way the CE can quickly diagnose power and structure issues on the fly without having to run to a station map monitor or carry around a map monitor that only really gives the CE half of the info.

the new sprite for now would jsut be a recolored handheld station map (eng yellow)

im a little new to C# and GIT so any advice here would be great

and plz lmk if anyone has already started on something like this

any new ideas, hints, and potental pitfalls to look out for on the code and yaml stuff will all be appreciated.

**Comment by deltanedas** [comment]
someone already tried and it was closed

**Comment by maximus-not** [comment]
ah do you know the PR for that?

**Comment by deltanedas** [comment]
https://github.com/space-wizards/space-station-14/pull/25828

**Comment by maximus-not** [comment]
ah ty

**Comment by lzk228** [comment]
github issues is not a place for such ideaguys

**Comment by maximus-not** [comment]
> github issues is not a place for such ideaguys

ah sorry ive been told to put it here is all i was gonna make it a PR but at the time i handnt started coding
