### ISSUE TITLE
RCD usability is scuffed 

### ISSUE THREAD

**Issue by Krovotushka** [space-wizards/space-station-14#30878]
If you try to place anything using RCD on a tile that is occupied by airlock/firelock/shutter/window shutter/blastdoor "tile occupied" pop up will appear, however if you place same thing you wanted to place with RCD, but using construction menu it works just fine

**Comment by keronshb** [comment]
I think this is a bug with the construction menu and not the RCD so much. You shouldnt be able to stack these things.

**Comment by Krovotushka** [comment]
> I think this is a bug with the construction menu and not the RCD so much. You shouldnt be able to stack these things.

What about wires? Players cant even place wires if tile is occupied with one airlock. Or you cant place windows if there is shutter/blastdoor on the same tile

**Comment by deltanedas** [comment]
they should be using the same logic to be consistent, imo construction is right because obviously doors dont block wires
