### ISSUE TITLE
There is oxygen inside mapped lockers

### ISSUE THREAD

**Issue by Brandon-Huu** [space-wizards/space-station-14#30882]
![image](https://github.com/user-attachments/assets/e4e20080-3e3c-4593-806d-15d95fead503)

Probably from people opening them while mapping.

Should the air be removed?

**Comment by TheDoctor1977** [comment]
This is probably insignificant enough where it's fine. How long can you survive inside one?

**Comment by UbaserB** [comment]
I don't think this is an issue? Like, once you open it all the air is going to escape anyway.
