### ISSUE TITLE
Borg buckling do-afters don't work

### ISSUE THREAD

**Issue by Plykiya** [space-wizards/space-station-14#30898]
## Description

When you try to buckle someone into a bed or chair as a borg, the do-after will start but not actually do anything.
Like, the do-after literally does nothing. You can see the do-after bar, sure, but it literally does nothing despite starting the do-after with all the correct arguments.

Typically when you start the buckle do-after, you are expecting the BuckleDoafterEarly() checks to be constantly running every tick to try and cancel the do-after, and then once it finishes it'll call OnBuckleDoafter() to actually buckle the person into the chair or bed.

Doing this as a human, that's what happens. But when done as a borg, neither of these do-after functions get called when I set up breakpoints in the code to try and figure it out.

https://github.com/space-wizards/space-station-14/blob/master/Content.Shared/Buckle/SharedBuckleSystem.Buckle.cs

I honestly have no clue how to debug it from here or how to fix it.

**Reproduction**

**Screenshots**

**Additional context**

**Comment by Hreno** [comment]
I've gotten to the point of figuring out that in `EntDispatch`, when buckling as a human, `eventTable.EventIndices` does contain `BuckleDoAfterEvent`, but as a borg it doesn't contain it and returns.

![image](https://github.com/user-attachments/assets/b1551248-2030-4119-a87a-d976defe5b59)

Why borgs don't have the `BuckleDoAfterEvent` in their EventIndices I don't know.

**Comment by Hreno** [comment]
Looks like it's as simple as adding `- type: Buckle` to the borg's YML.
