### ISSUE TITLE
When flashed you can see through walls

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#30902]
## Description

I've only had this happen to me once and I have no idea how to replicate it.

**Screenshots**

![image](https://github.com/user-attachments/assets/37cf8f7b-f997-4b5b-b234-e16348842b96)

**Comment by Hreno** [comment]
Duplicate of #30772

**Comment by UbaserB** [comment]
> Duplicate of #30772

i forgor i already made an issue on this im an idiot
