### ISSUE TITLE
Throngler plushie should look more like a plushie

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#30906]
## Description

right now it's taking from the normal throngler sprites and looks intimidating... 
related: #29978

**Comment by Moomoobeef** [comment]
This is intentional. I specifically wanted people to think it's an actual throngler at a glance.

**Comment by Hrosts** [comment]
>right now it's taking from the normal throngler sprites and looks intimidating...

>This is intentional. I specifically wanted people to think it's an actual throngler at a glance.

Better to just rename it into something like Throngler replica or throngler balloon/inflatable throngler, as we already have a precedent of hyper-realistic balloons (nukie decoys).

**Comment by Moomoobeef** [comment]
That works for me, I just don't want to touch the sprite
