### ISSUE TITLE
Red crowbar should not be able to be placed in pockets

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#30910]
## Description

It was never intended for the red crowbar to be placed in the pockets in #28988 and even when i checked the prototype, I still don't see anything wrong. It's bizarre. Could be something due to the tags but i doubt that considering how tags work...

**Screenshots**

In `Resources/Prototypes/Entities/Objects/Tools/crowbars.yml`:

![image](https://github.com/user-attachments/assets/214f0ec1-b8d5-4649-9038-8953b6ab2c49)

**Comment by lzk228** [comment]
A pocket crowbar

**Comment by lzk228** [comment]
though emisse (who started the thing as you said in https://github.com/space-wizards/space-station-14/pull/28988#issuecomment-2169538660) merged pocket emergency crowbars in #30828

**Comment by UbaserB** [comment]
> though emisse (who started the thing as you said in [#28988 (comment)](https://github.com/space-wizards/space-station-14/pull/28988#issuecomment-2169538660)) merged pocket emergency crowbars in #30828

oh what, nevermind then huh
