### ISSUE TITLE
Self execution results in being removed from body

### ISSUE THREAD

**Issue by bruhmogus** [space-wizards/space-station-14#30926]
## Description
If you execute YOURSELF, you will be unable to return to body even if revived. This is a problem because on MRP someone may try to kill themself to avoid security or whatnot. It kinda sucks.

**Reproduction**
Step 1. Take a sharp weapon
Step 2. Die
Step 3. "wait fuck i cant return"

**Screenshots**
![20240811210112_1](https://github.com/user-attachments/assets/28178679-7297-4e44-a8f5-2d241c5c729e)

**Additional context**
it sucks for rp despite just being a more ic /suicide

**Comment by UbaserB** [comment]
I believe this was intended

**Comment by bruhmogus** [comment]
it was, but imo it's a bad decision for rp

**Comment by UbaserB** [comment]
Checked with other maintainers, we want to keep this feature.
