### ISSUE TITLE
Crew monitor sabotage feels impossible to fix

### ISSUE THREAD

**Issue by Plykiya** [space-wizards/space-station-14#30940]
## Description

I don't even think it's possible to set up a replacement server based on some very unskilled testing

**Reproduction**

**Screenshots**

**Additional context**

**Comment by deltanedas** [comment]
just buy new server at cargo

**Comment by Plykiya** [comment]
> just buy new server at cargo

I've not had any success actually rebuilding it after that

**Comment by TyAshley** [comment]
Salvage can find new ones in dungeons as well, though it is a bit less reliable

**Comment by Plykiya** [comment]
https://github.com/space-wizards/space-station-14/pull/31677
