### ISSUE TITLE
Syndie Pens are automatically ousted by the new Syndicate Contraband PR

### ISSUE THREAD

**Issue by Zalycon** [space-wizards/space-station-14#30949]
## Description

If a player has an hypo-pen or e-pen it is normally hidden from Security provided no pre-requisites are met. Unfortaunley the recent Contraband PR will oust these pens even if they aren't activated. Which is an issue seeing as though these items are not meant to be metagamed.

**Reproduction**

1. Buy/Spawn in an E-pen or Hypo-pen
2. Shift Click the pen
3. Realize it says its contraband
4. Get searched by security and die

**Screenshots**

![image](https://github.com/user-attachments/assets/e0b5d49d-d0f0-4379-bd60-f74694f5fdc3)

**Additional context**

#30937 is the PR related to this as its the one causing this issue. Otherwise N/A

**Comment by Plykiya** [comment]
It's only the e-pen, also a known issue.

**Comment by nok-ko** [comment]
(Previously reported in #30927.)
