### ISSUE TITLE
Pulled items not being dropped when going into crit.

### ISSUE THREAD

**Issue by themias** [space-wizards/space-station-14#30977]
## Description

A bug was opened on discord here: https://discord.com/channels/310555209753690112/1272944041138327652/1272944041138327652

The root cause is that going into crit is not correctly dropping pulled items.
The virtual item in your hand appears deleted, but the item is still pulled.

**Reproduction**

1. pull something
2. crit the creature from step 1
3. pull the crit body with another creature

Expected: pulled item was dropped
Actual: item still pulled

**Screenshots**

https://github.com/user-attachments/assets/616a7d8b-17ff-4a1f-8a78-4a275758adee

**Additional context**

I think it is related to line 513-514 in PullingSystem.cs from #30728.

**Comment by deepdarkdepths** [comment]
This also happens with those with narcolepsy. I was being dragged by someone while I was cuffed, and they fell asleep.. I was still being held by them.
