### ISSUE TITLE
Pet and Bear Hospital now contains an outrageous fortune

### ISSUE THREAD

**Issue by XyyxShard** [space-wizards/space-station-14#30975]
## Description
The Salvage Magnet wreck "Pet and Bear Hospital" has always contained a stack of (worthless, at time of implementation) diamonds in its vault. With the recent change of diamonds being 2,000 spesos each, this stack is now worth 60,000 spesos making it hilariously valuable.

**Reproduction**
Step 1. Pull in the Pet and Bear Hospital wreck on the salvage magnet
Step 2. Go buy the whole team golden hardsuits and advanced meds

**Screenshots**
![image](https://github.com/user-attachments/assets/9243a173-3648-4265-bc29-a9ec5077e782)

**Additional context**
This does require a bit of luck in actually getting it, but it's probably expected to appear as an option on the magnet at least once a shift

**Comment by UbaserB** [comment]
It's known, and yes this is an important issue that needs to be fixed; everything that has manually spawning diamonds should be greatly cut down from a whole stack like that. This includes dungeons as well.
