### ISSUE TITLE
Crew monitoring console does not update names if admin renaming is used

### ISSUE THREAD

**Issue by XxSWAG-MASTER-OVERLORDxX** [space-wizards/space-station-14#30992]
## Description
as title

If the admin rename trick is used it does not update it for any systems like crew monitor

**Comment by Just-a-Unity-Dev** [comment]
Does using the `rename` command in the console work?

**Comment by Hreno** [comment]
I see that `rename` in console does work.

However, both `rename` in console and right click -> Tricks -> Name do not change the name in the description (shift+left click).

**Comment by TheDoctor1977** [comment]
> However, both `rename` in console and right click -> Tricks -> Name do not change the name in the description (shift+left click).

I believe this is a separate bug, I've noticed it happening but it updates itself after 5 seconds or so.

**Comment by Just-a-Unity-Dev** [comment]
> I see that `rename` in console does update the crew monitor.
> 
> However, both `rename` in console and right click -> Tricks -> Name do not change the name in the description (shift+left click).

This is related to identity updating. Wear and then take off a gas mask/any identity blocker to update identity

**Comment by IProduceWidgets** [comment]
Someone should probably just have the verb UI alias the console rename command if it doesn't already. Its also weird that the rename command will update the PDA/ID card but the verb doesn't.

**Comment by IProduceWidgets** [comment]
wait no!
