### ISSUE TITLE
Puddles slip regardless of reagents contained.

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#3103]
Spill sugar on the floor? Whoops, get slipped.
Ideally, we should be able to define puddle behavior on reagents themselves.
This is most likely gonna require YAML `!type` knowledge, knowing how the chemistry/puddles system works, etc.

**Comment by Willhelm53** [comment]
I'll take this one on! Yeah sugar should neither slip people nor evaporate. This ties in well with some other stuff I'd like to add for Janitor. I'll have a look and probably add a "powder" type on some different reagents.

**Comment by Matz05** [comment]
Perhaps use the melting and boiling points? A reagent below its melting point shouldn't slip (much? it's kinda assumed to be a powder, and powders can still be kinda slippery IRL) or evaporate, a reagent above its boiling point should evaporate very quickly.

**Comment by metalgearsloth** [comment]
> Perhaps use the melting and boiling points? A reagent below its melting point shouldn't slip (much? it's kinda assumed to be a powder, and powders can still be kinda slippery IRL) or evaporate, a reagent above its boiling point should evaporate very quickly.

Is there a way to performantly subscribe to these changes in atmos?

**Comment by Peptide90** [comment]
Alternatively if reagents can have like an evaporation field where:
- if it's blank it doesn't evaporate. 
- If its 1 it loses 6/10 units per minute (so puddles after mopping last a minute, big puddles take up to 10 minutes unless you want to add a check for units in a puddle).
- This should scale against temperature (if you want to subscribe to atmos, could be handy for increasing reagent temp anyway so plasmafires remove puddles and melt / smoke reagents).

You could do something similar for powders I'd say with a slip coefficient. 1 = slippy (default), 0.1 = needs 90u on a tile to be slippy etc etc or something similar just as an idea. All of this I'm assuming under a puddle system. (Apologies if this is ideaguysing git, just offering guidance on direction)

**Comment by Willhelm53** [comment]
Loving the discussion here! This ties in very well with my future ideas for janitor. Sometime soon I'll compile these notes, do up some pseudocode, and take my questions to the discord. Thanks all!
