### ISSUE TITLE
Make sentient verb crashes the game if used on a AI'ed mob or doesn't work properly

### ISSUE THREAD

**Issue by DmitriyRubetskoy** [space-wizards/space-station-14#3105]
Examples include: Civilian (no effect), animals (no effect), carps (crashes the game), xenos (crashes the game)
@metalgearsloth said he would deal with this, so by request..
![image](https://user-images.githubusercontent.com/75271456/107148746-f81a0400-6965-11eb-9334-9d1c4eb4eefc.png)

**Comment by metalgearsloth** [comment]
This was fixed at some point.
