### ISSUE TITLE
Pacifists can throw Items that Hurt People

### ISSUE THREAD

**Issue by Cojoke-dot** [space-wizards/space-station-14#31062]
## Description

Pacifists have no block if the item deals damage on hit, IE: Can kill someone by cutting them with glass shards
**Reproduction**

Thow a glass shard as pacifist

**Comment by slarticodefast** [comment]
Yeah, pacisfism is in need of some rework on what they should and should not be able to do. Right now throwing is just blocked by a few specific components attached to the item.
