### ISSUE TITLE
Recent changes to the Event Scheduler cause lots of station events to happen at roundstart. 

### ISSUE THREAD

**Issue by Mervill** [space-wizards/space-station-14#31072]
## Description

![2024-08-15 19_55_57-Select FPS_ 342 47 SD_ 2 73ms _ Net_ (Send_ 1 KiB_s, Recv_ 1 KiB_s) _ Memory_ 1,](https://github.com/user-attachments/assets/c66a87af-ddb4-44aa-95af-f98ae8a3a534)

Following https://github.com/space-wizards/space-station-14/pull/29320 lots of station events are fired immediately after roundstart. This was not the previous behavior, or at least these messages are new. Is this an intended change?

**Comment by Brandon-Huu** [comment]
That looks normal to me.
Most of them just make the station look dirty / disable some electronics?
Let's jani clean?
let's engineering fix?

**Comment by deltanedas** [comment]
yeah thats all fine, theres multiple types of event schedulers now
