### ISSUE TITLE
Recipes that call for raw meat cutlets cannot be made.

### ISSUE THREAD

**Issue by Sentient3780** [space-wizards/space-station-14#31083]
## Description
See title. Food recipes that require raw meat cutlets cannot be made in the microwave.

**Reproduction**
So far, I have seen two recipes fail to work. Try following the recipes for beef tacos and meat kebabs. Watch as the microwave spits out cooked cutlets and your other ingredients.

**Screenshots**
I am unable to provide screenshots.

**Additional context**
There's no additional context that I can provide.

**Comment by themias** [comment]
All previous recipes for tacos and kebabs were removed in #30905.

Were there any other recipes that weren't working?

**Comment by Sentient3780** [comment]
Ah, that'll do it. It's a shame that the PR removed the normal taco and kebab recipes that were on the wiki. I didn't notice.

Just to make sure that the other recipes were working, I pulled up a private server with the most recent changes. I made enchiladas, a bowl of hot chili, and meat bread without issue. I am going to assume the other recipes are working perfectly.
