### ISSUE TITLE
Aghosts cannot buckle

### ISSUE THREAD

**Issue by TheDoctor1977** [space-wizards/space-station-14#31109]
## Description
title

**Reproduction**
1. try to buckle a mob to a chair/bed/whatever as an aghost
2. they do not get buckled
3. weep

**Screenshots**
https://github.com/user-attachments/assets/58378a95-db7d-4695-bf36-6d8dbe28ae87

**Comment by Plykiya** [comment]
https://github.com/space-wizards/space-station-14/issues/30898 same issue, likely

**Comment by TheDoctor1977** [comment]
> #30898 same issue, likely

I don't think so, the doafter doesn't even begin, like it's not recognizing the action at all.
