### ISSUE TITLE
MAP_MARATHON: Janitorial Service button has a non-obvious use/function

### ISSUE THREAD

**Issue by Brandon-Huu** [space-wizards/space-station-14#31102]
![image](https://github.com/user-attachments/assets/986d086a-220f-46d3-9bc9-da9d0a39a44e)

What does this even do?
Turn on a light?
Where?

If this actually has a use, It's description should probably be changed to describe its function.

**Comment by Brandon-Huu** [comment]
Apparently it actives this light

![image](https://github.com/user-attachments/assets/bf63906a-466c-4253-a440-3a3c277e8582)

**Comment by Brandon-Huu** [comment]
Apparently it turns on this blinking light at the front of medbay.

![image](https://github.com/user-attachments/assets/224d97ee-b1fe-45ac-835d-6941d053d03d)

**Comment by Brandon-Huu** [comment]
It should be replaced with a switch.
A button shouldn't be used to switch something on and off.

**Comment by Emisse** [comment]
this is fine
