### ISSUE TITLE
Holiday System

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#3113]
A system that keeps track of IRL holidays for the purpose of fun events and interactions on certain holidays.

**Comment by SweptWasTaken** [comment]
Mmm isn't this done manually in SS13?

**Comment by Zumorica** [comment]
Nope, some holiday dates are hardcoded, others are calculated, etc, but it's not manual

**Comment by ike709** [comment]
[Bee's holiday file, for reference](https://github.com/BeeStation/BeeStation-Hornet/blob/a1446c197773fd9590d087469b39b02945623d6f/code/modules/holiday/holidays.dm).

**Comment by Zumorica** [comment]
> [Bee's holiday file, for reference](https://github.com/BeeStation/BeeStation-Hornet/blob/a1446c197773fd9590d087469b39b02945623d6f/code/modules/holiday/holidays.dm). (Does not include a lot of the effects).

thank you, I'll use it as inspiration
