### ISSUE TITLE
Entities that are deleted with no prototype set in SpecialRespawn tear holes into reality and portals to nullspace

### ISSUE THREAD

**Issue by bruhmogus** [space-wizards/space-station-14#31139]
## Description
If an entity that has SpecialRespawn but no prototype set is deleted, it uhhhhhhhh kinda just tears reality into shreds and deloads everything around it, it also doesn't generate a log like the disk does

**Reproduction**
Step 1. Add SpecialRespawn to an entity
Step 2. Remove it
Step 3. death.jpg

**Screenshots**
![20240817181701_1](https://github.com/user-attachments/assets/fb177055-f6f0-44d9-8f7d-d4b39322ae3e)

![20240817181239_1](https://github.com/user-attachments/assets/7b070d19-72c0-4b81-8cf4-ac8e685f4736)

**Additional context**
how

**Comment by Brandon-Huu** [comment]
I don't see what's wrong.
can you attach a video

**Comment by Brandon-Huu** [comment]
One line fix.
I'll do it
