### ISSUE TITLE
Prisoner uniforms are broken again how the fuck

### ISSUE THREAD

**Issue by bruhmogus** [space-wizards/space-station-14#31190]
## Description
They're missing the stripes and turned into orange clothing

**Reproduction**
1. Spawn prisoner clothing
2. wear it
3. cry

**Screenshots**
cant rn

**Additional context**
Only tested on jumpskirt

**Comment by TheDoctor1977** [comment]
This may be linked to whatever’s causing #30565.

**Comment by beck-thompson** [comment]
Looks like its fixed!
