### ISSUE TITLE
Item stack refills to max when picking up any other stack item

### ISSUE THREAD

**Issue by ShadowCommander** [space-wizards/space-station-14#312]
When holding a single item (e.g. Ointment) that can be stacked, if you click on any item that has a stack component (e.g. Ointment, Brutepack) the item in hand will refill to the maximum stack count without picking up the item on the ground.

I found the bug by throwing the stack items and trying to pick them back up.

**Comment by Miniwoffer** [comment]
I am not able to reproduce this

**Comment by PJB3005** [comment]
Can't reproduce it either.

**Comment by ShadowCommander** [comment]
Here's a gif of what I mean.
https://gyazo.com/64946e259e58e05684cf79244c882e1f
