### ISSUE TITLE
Disaster victim [escape pod event] too often command.

### ISSUE THREAD

**Issue by jamilnielsen** [space-wizards/space-station-14#31220]
## Description
the event with disaster victims randomly in space in an escape pod, this event got a tendency to roll command roles 90% of the time, as something anyone can join, its probably for the best to have command roles be rare on these?

**Comment by UbaserB** [comment]
I'm pretty sure it's command roles only on purpose...

**Comment by Golinth** [comment]
that just makes it a bureaucratic error but flavored differently honestly

**Comment by Everturning** [comment]
Actually it's 100% command. Because thats all that can spawn. Pls close

**Comment by Everturning** [comment]
> > Actually it's 100% command. Because thats all that can spawn. Pls close
> 
> I’ve seen skeletons spawn from them, you sure it’s 100% command?

That's a bug that's already been reported

**Comment by Moomoobeef** [comment]
honestly there should be a chance for other roles to spawn too imo :/

**Comment by deltanedas** [comment]
wyci

**Comment by Everturning** [comment]
> honestly there should be a chance for other roles to spawn too imo :/

Iirc the reason it's just command is so that syndies can pass into command easier
