### ISSUE TITLE
You can hit grilles through thindows

### ISSUE THREAD

**Issue by Plykiya** [space-wizards/space-station-14#31250]
## Description

Without electrocuting yourself, and it actually damages the grille as well. Easily done on the new bagel perma.

**Reproduction**

**Screenshots**

**Additional context**

**Comment by TurboTrackerss14** [comment]
https://github.com/space-wizards/space-station-14/issues/25933
https://github.com/space-wizards/space-station-14/issues/27660
I hate it here.
