### ISSUE TITLE
Dead people sometimes stand up

### ISSUE THREAD

**Issue by PaulRitter** [space-wizards/space-station-14#3126]
Dead people sometimes stand up and confuse everyone, they can still be stunbatoned or rekilled but they will still stand back up after a moment

Reported by @"Herbert Falsevor"#3037

**Comment by AJCM-git** [comment]
I'm 99% certain that it was a player/admin rejuvenating themselves or stunned. Also without any steps to reproduce/concrete proofs like screenshots/videos this isn't very useful.
