### ISSUE TITLE
Brig windows can be broken by prisoners themselves

### ISSUE THREAD

**Issue by PaulRitter** [space-wizards/space-station-14#3130]
It takes about 20 seconds worth of hitting.

Reported by @"Herbert Falsevor#3037"

**Comment by metalgearsloth** [comment]
On vgstation from what I can tell it pulls a random number from 0-hand max damage (humans being 5) and does that. If it rolls a 0 then it plays a miss sound. We could probably use that + bump up window health to something like 50 instead maybe?

**Comment by PaulRitter** [comment]
iirc reinforced windows just cannot be attacked by hands on /vg/

**Comment by metalgearsloth** [comment]
even better

**Comment by PaulRitter** [comment]
closed in favour of #3174
