### ISSUE TITLE
There is no air pressurization system at the station exits.

### ISSUE THREAD

**Issue by PaulRitter** [space-wizards/space-station-14#3131]
It vacuums out anyone brave enough to open the second door.

Reported by @"Herbert Falsevor#3037"

I think by this he meant in the intermediate room. There should probably be some sort of cycling system used here, altough we don't have that yet.

**Comment by mirrorcult** [comment]
nonissue, just open/close them one at a time and it's fine

**Comment by moonheart08** [comment]
@mirrorcult We have fastmos, so no matter how you dice it, even if you do it one at a time you will be blasted out the airlock at mach speed. I think this is still an issue.

**Comment by Zumorica** [comment]
> @mirrorcult We have fastmos, so no matter how you dice it, even if you do it one at a time you will be blasted out the airlock at mach speed. I think this is still an issue.

not true, if you close the internal airlock then open the external one it's fine

**Comment by moonheart08** [comment]
![image](https://user-images.githubusercontent.com/7806367/126206691-01cff3bb-08f2-4bc8-9c7f-8670e2bb3ee0.png)
This airlock causes enough of a pressure difference to rip up tiles inside.

**Comment by Zumorica** [comment]
In no way is that near enough to "blast anyone out the airlock at mach speec". Tiles being ripped is not that important.
Aside from that, this is part of piping so it can stay closed anyway.

**Comment by SweptWasTaken** [comment]
Since piping is in shouldn't we map vents and stuff into these airlocks?

**Comment by Zumorica** [comment]
> Since piping is in shouldn't we map vents and stuff into these airlocks?

piping is in no way stable for mapping, it doesn't even hide in subfloor right now (it's a complicated problem to solve as not all layers need to be hidden)

**Comment by SweptWasTaken** [comment]
> 
> 
> > Since piping is in shouldn't we map vents and stuff into these airlocks?
> 
> piping is in no way stable for mapping, it doesn't even hide in subfloor right now (it's a complicated problem to solve as not all layers need to be hidden)

How does piping work in SS13 again? I would think that when placing piping down you could have a mode where you can do above tile/below tile.

**Comment by ike709** [comment]
Smh just steal advanced airlock controllers from yogs/bee and have properly cycling airlocks.

**Comment by SweptWasTaken** [comment]
> 
> 
> Smh just steal advanced airlock controllers from yogs/bee and have properly cycling airlocks.

When you code it
