### ISSUE TITLE
Nuke disk left behind even when not left behind

### ISSUE THREAD

**Issue by Plykiya** [space-wizards/space-station-14#31323]
## Description

Lone ops always seem to get the display message wrong even when the crew has the nuke disk at CentCom

![image](https://github.com/user-attachments/assets/8de6dad2-bdf4-4e42-8cba-91ff87829eb1)

**Reproduction**

**Screenshots**

**Additional context**

**Comment by themias** [comment]
I was able to debug this locally. The issue is that at the moment the results are evaluated, the nuke disk resolves as still being on the FTL grid, so it isn't considered on CentCom.
