### ISSUE TITLE
Nothing at cargo has a cost.

### ISSUE THREAD

**Issue by PaulRitter** [space-wizards/space-station-14#3133]
Reported by @"Herbert Falsevor#3037"

**Comment by PaulRitter** [comment]
AFAICT cargo orders do have costs, maybe they
a) don't get properly subtracted OR
b) the starting amount is just too big & the player didn't notice it

**Comment by komunre** [comment]
I've seen starting amount subtracted in the previous month so I think the player just didn't notice it because of the big value.

**Comment by AJCM-git** [comment]
The cargo points are working as intended and subtracting the cost of the item purchased. The player probably didnt notice because of how many points there are.
