### ISSUE TITLE
Always lying on the ground

### ISSUE THREAD

**Issue by Winkarst-cpu** [space-wizards/space-station-14#31349]
## Description
People always lie on the ground (if they will not buckle at something) after slipping on an item.

**Reproduction**
Throw something slippery under someone.

**Screenshots**
![изображение](https://github.com/user-attachments/assets/f70023f1-49a7-408e-957e-69c6aae4322f)

**Additional context**

**Comment by slarticodefast** [comment]
Duplicate #29859
