### ISSUE TITLE
Medical system does not allow the healing of airloss damage.

### ISSUE THREAD

**Issue by PaulRitter** [space-wizards/space-station-14#3134]
Reported by @"Herbert Falsevor#3037"

Paging Mr. Bodysystem @DrSmugleaf

**Comment by DrSmugleaf** [comment]
It doesn't allow healing anything other than blunt and heat but the academy hasn't found out yet

**Comment by RemieRichards** [comment]
Don't lose air, idiot.

**Comment by DrSmugleaf** [comment]
Fixed by https://github.com/space-wizards/space-station-14/pull/3194
