### ISSUE TITLE
Clown can't fall when in crit or dead

### ISSUE THREAD

**Issue by Winkarst-cpu** [space-wizards/space-station-14#31352]
## Description
Title.

**Reproduction**
Be in crit or dead as a clown.

**Screenshots**
![изображение](https://github.com/user-attachments/assets/8d111439-7861-4c7f-b609-3062b5adf8c1)

**Additional context**

**Comment by lzk228** [comment]
i am pretty sure it's a dupe issue

**Comment by UbaserB** [comment]
Dupe of #26977

**Comment by Winkarst-cpu** [comment]
> Dupe of #26977

Oh, someone needs to set labels to it...
