### ISSUE TITLE
Some replays still not loading (Unexpected type)

### ISSUE THREAD

**Issue by Evige** [space-wizards/space-station-14#31364]
## Description

I was following the previous issue (https://github.com/space-wizards/space-station-14/issues/30801) and trying to load replay after the fix was released and was mentioned in the previous issue. But I am still getting errors and the replay isn't loading or starting.  The error happens at least in this replay (62341). It was played 2024/08/11. 

**Reproduction**

Start the Space Station 14 launcher, drag the replay zip normally. 
- Try to close errors either from the big red "Try load with.." button or from the corner close X-button. It gives the first errors here, but it seems to progress further with the load of the replay (see Screenshot 1 and Screenshot 2). 
- It proceeds to "Direct Connect" menu and after clicking the "Direct Connect" it tries to connect to the host, but fails (Screenshot 3). 
- After that it starts the 1/5 loading. It first throws some errors which have increasing id or coordinate numbers (Screenshot 4) so it looks like it is still progressing with the actual replay load process? 
- But when it gets to the 2/5 loading phase it seems to get "stuck" it looks like the loading process is looping from the start, passing 1/5 without errors and ending up to the same error in the phase 2/5 (Screenshot 5).

**Screenshots**

Screenshot 1: 
![image](https://github.com/user-attachments/assets/51f265d3-8dbf-4232-80f4-b5de60b25c02)

Screenshot 2:
![image](https://github.com/user-attachments/assets/610cc1de-7922-44bf-b21d-0601fa68b88b)

Screenshot 3:
![image](https://github.com/user-attachments/assets/3cddb82b-08a7-42b7-9a8e-f1b44e2f5e06)

Screenshot 4:
![image](https://github.com/user-attachments/assets/12617ebf-e415-4714-be0e-07c75460ef97)

Screenshot 5:
![image](https://github.com/user-attachments/assets/5ff0edd4-2045-417f-a971-eb96ca869ff5)

**Additional context**

(https://github.com/space-wizards/space-station-14/issues/30801) <- might have fixed some replays? But it seems to me that some issues still exists while trying to load replays.

**Comment by metalgearsloth** [comment]
> 2024/08/11

The pr isn't going to fix old replays unless you manually backport a fix.
