### ISSUE TITLE
Being spaced is basically permadeath right now

### ISSUE THREAD

**Issue by PaulRitter** [space-wizards/space-station-14#3136]
upon being spaced walls get stretched out  (appears they grow tall to the sizs of burch khalifa or smthn) and shadows/lighting glitch out so it looks ugly, bullets are only fired in the direction of the station, its not possible to save yourself after being spaced out. Placing walls in front of yourself doesnt help neither.

Reported by @"Herbert Falsevor#3037"

**Comment by AJCM-git** [comment]
I cant really reproduce any of the visual glitches, player might have been confused because everything is super dark in space.
The real issue here is that throwing items/firing guns doesn't impulse back to the station. So this is a duplicated of #880
