### ISSUE TITLE
ChemVend and the nuclear operative "Syndiejuice" have unlabelled jugs

### ISSUE THREAD

**Issue by Blackern5000** [space-wizards/space-station-14#31373]
## Description
Read title, it's the same issue that the chemvend used to have.

**Reproduction**
- Be nukie agent/chemist
- Open the syndiejuice/chemvend to start mixing drugs
- *Screams!*

**Screenshots**

![image](https://github.com/user-attachments/assets/ea09b5f6-e39e-450d-a512-f7f8967925ae)

**Comment by Sparlight** [comment]
Worth noting this is happening to the regular ChemVend too again.

**Comment by JIPDawg** [comment]
Possibly due to #30064 ?

**Comment by slarticodefast** [comment]
Can confirm this on master for both chemvends. Looks like #30064 completely removed the dummy spawning responsible for checking labels.

**Comment by EmoGarbage404** [comment]
mfw core behavior built on undocumented and strange code

**Comment by PJB3005** [comment]
> mfw core behavior built on undocumented and strange code

More like mfw code randomely deleted from PR with no justification or testing.
