### ISSUE TITLE
ItemToggleComponent is hard coupled to PowerCellDrawComponent

### ISSUE THREAD

**Issue by EmoGarbage404** [space-wizards/space-station-14#31377]
## Description

The battery won't even drain if you don't have both components on the entity. what the fuck, man.
why do we make events if we're not going to use them.

make a new component that interfaces between both of them.

christ.

**Comment by EmoGarbage404** [comment]
@deltanedas

**Comment by deltanedas** [comment]
it should still draw when missing the component, very sus
