### ISSUE TITLE
Hardsuit light battery dies super quickly, and makes it close to useless.

### ISSUE THREAD

**Issue by PaulRitter** [space-wizards/space-station-14#3138]
Reported by @"Herbert Falsevor#3037"

**Comment by Peptide90** [comment]
Should hardsuit battery be a different entity if it can be removed? Instead of putting the biggest small cell in and science removing it for research.

Otherwise can buff it and make it non removable but slowly self charges. Thoughts?

**Comment by SweptWasTaken** [comment]
> 
> 
> Should hardsuit battery be a different entity if it can be removed? Instead of putting the biggest small cell in and science removing it for research.
> 
> Otherwise can buff it and make it non removable but slowly self charges. Thoughts?

I think you should do the 2nd option for now.

**Comment by Peptide90** [comment]
Will add it to my to do when I'm next free
