### ISSUE TITLE
sentient artifact can completely lose the ability to self-activate

### ISSUE THREAD

**Issue by Ilya246** [space-wizards/space-station-14#31396]
## Description
seemingly randomly, the following become gone:
- the activate action in the action bar
- the activate action in the actions menu (no way to readd it)

can't self-activate at all this way

**Reproduction**
unknown, happened in #63626 on lizard when:
1) i was a handheld artifact
2) i was being held by QM
3) i activated a node that set everyone nearby on fire
4) i got dropped
5) actions disappeared

**Comment by Everturning** [comment]
this has been in the game for so long now, has no one reported it

**Comment by slarticodefast** [comment]
Likely fixed by #33171
Two certain node effects deleted the artifact's ContainerManager, which also included the action entity.
Let me know in case it still happens and I will reopen this issue.
