### ISSUE TITLE
AI (Xeno) Issues

### ISSUE THREAD

**Issue by PaulRitter** [space-wizards/space-station-14#3139]
AI xenos often get stuck on doors. ~~If too many are spawned only a few remain active and attack the players while the rest just turns into vegetables.~~ Intended, the getting stuck however is not.

Reported by @"Herbert Falsevor#3037"

**Comment by metalgearsloth** [comment]
1st is coz of sliding which physics might help, 2nd is because someone spawned more than 64 which is silly.

**Comment by PaulRitter** [comment]
silly man

**Comment by AJCM-git** [comment]
Duplicate of #2838
