### ISSUE TITLE
Station AI Interaction Whitelist List

### ISSUE THREAD

**Issue by Emisse** [space-wizards/space-station-14#31410]
Need to compile a list of everything on the station that the AI can interact with so we can put the comp on each of them. So far in station AI pr we just have airlocks + apcs. If anyone could assist with a comprehensive list that would be ideal.

**Comment by LittleNorthStar** [comment]
Off of my top of by head
-Air alarms
-Firelocks (might be included in airlocks thought I would list it just in case)
-Atmospheric pipe components? (pumps, filters, mixers, etc)
-Buttons and Levers
-Disposals bins
-Mail shoots

**Comment by Cojoke-dot** [comment]
-Fire alarms
-intercom? (maybe?)
-timers? (maybe?)

**Comment by EdenTheLiznerd** [comment]
-Consoles
-Science Equipment?
-Power Equipment (AME and PA interface and so on?
-Alert System

**Comment by ThatOneGoblin25** [comment]
-shutters?
-blastdoors?

**Comment by Tyzemol** [comment]
-thrusters and gyros

**Comment by lzk228** [comment]
imo should only be things that have wire panel
with wire panel they can have AI wire, and if you cut the wire, AI can't access the device

**Comment by ArtisticRoomba** [comment]
Cargo purchase terminal
Communications terminal? Or are we still holding off on having AI make announcements?
Solar panel control
Emitters and containment field generators (?) would be cool to have AI handle the containment wall for Oasis' perma exile shuttle, not sure how we feel about it when it comes to emitter sabotage
News manager console
Cargo and salvager shuttle control
Buttons!


Power monitor, crew monitor, station records, criminal records would be extremely useful as dedicated actions

**Comment by ScarKy0** [comment]
A.P.E
AI Upload Computer (And Other AI Related Computers, Dunno The Names)
Air Alarm
All Vending Machines
Analysis Console
Anomaly Generator
Anomaly Vessel
Artifact Container
Autolathe
Body Scanner Computer
Buttons / Blast Chamber Buttons
Camera Monitor
Camera Servers (If AI Can Unpower Things)
Cameras
Cargo Bounty Computer
Cargo Request Computer
Cargo Shuttle Computer
ChemMaster 4000
Chemical Dispenser
Circuit Imprinter
Communications Computer
Containment Field Generator
Crew Monitor Servers (If AI Can Unpower Things)
Crew Monitoring Console
Criminal Records Computer
Disease Diagnoser
Dispensers
Duster
Electrolysis Unit
Emitter
Fax Machines
Freezer
Friendship
Gas Filters
Gas Mixers
Gas Pump
Gas Recycler
Heater
Hellfire Freezer
High Security Doors
ID Card Computer
Industrial Ore Processor
Lamps
Lecter Afe (Lock/Unlock)
Lockers(Locking Unlocking, Not Opening)
Mass Scanner Console
Medical Records Computer
Microwaves
Morgue
News Manager Console
Ore Processor
PA Control Computer
PTK-800 Matter Dematerializer
Pacmans
Perforator
Power Monitoring Computer
Protolathe
R&D Console
Radar
Radiation Collectors
Reagent Grinders
Rechargers
Robotics Control Console
Salvage Expeditions Computer
Sheet-Meister 2000
Shuttle Computers
Signaler And Remote Signaler
Soda Dispenser
Solar Control Console
Station Beacons
Station Map
Station Records Computer
Suit Storage 
Svalinn Machine Gun
Tabletop Centrifuge
Tech Disk Terminal
Techfabs
Telecomm Servers (If AI Can Unpower Things)
Trash Chute
Vaccinator
Volumetric Gas Pump
Wireless Cameras

**Comment by Everturning** [comment]
> Cargo purchase terminal Communications terminal? Or are we still holding off on having AI make announcements? Solar panel control Emitters and containment field generators (?) would be cool to have AI handle the containment wall for Oasis' perma exile shuttle, not sure how we feel about it when it comes to emitter sabotage News manager console Cargo and salvager shuttle control Buttons!
> 
> Power monitor, crew monitor, station records, criminal records would be extremely useful as dedicated actions

not the purchase terminal.

"AI order 50 weh crates"
"AI order 1 million beers"
"ai order 12 smg crates"

**Comment by ArtisticRoomba** [comment]
> not the purchase terminal.
>
> "AI order 50 weh crates"
> "AI order 1 million beers"
> "ai order 12 smg crates"

You can already try to get a Borg to do this and they will probably not do it. 

1 and 2 are unreasonable orders and can be safely ignored.
3 can technically violate the crew harm rule but otherwise it's still unreasonable, of course given most circumstances.

**Comment by slarticodefast** [comment]
Fixed by #31730
