### ISSUE TITLE
Vocal emote menu icon should be white

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#31426]
## Description

It bothers me that the other two options are white and then one is blue for the main categories. 

**Screenshots**

![image](https://github.com/user-attachments/assets/05fc747f-5d38-4e2e-a400-3300c0628b11)

**Comment by Hreno** [comment]
It's hard to even notice the items in all the clutter. I think the circle should have a dark background or something.

**Comment by UbaserB** [comment]
> It's hard to even notice the items in all the clutter. I think the circle should have a dark background or something.

it should probably be toggleable in accessibility settings instead, its fine for me personally
