### ISSUE TITLE
Allow taser to be attached to pocket slot

### ISSUE THREAD

**Issue by PaulRitter** [space-wizards/space-station-14#3143]
dunno how to feel about this one tbh. they'd probably fit?

Reported by @"Herbert Falsevor#3037"

**Comment by Peptide90** [comment]
Probably OP since the laser is a long range weapon rather than a close range taser like IRL. As long as it can be quick accessed off the belt don't see why it needs pockets.

Pockets are for flash and pepper spray in my opinion.

**Comment by PJB3005** [comment]
Yeah tasers should be belt slot (or belt) not pocket.
