### ISSUE TITLE
Jetpack now working while wearing moon boots within station

### ISSUE THREAD

**Issue by murolem** [space-wizards/space-station-14#31431]
## Description
Jetpack doesn't work while wearing moon-boots (which give you «anti-gravity»), with error being "Can't use jetpacks under gravity".

**Reproduction**
Wear moon boots, get a jetpack and try to enable it whilst under station gravity.

**Screenshots**
![mr8nJ6DiD9](https://github.com/user-attachments/assets/215fab05-d41f-4d89-8ed3-0b68f2c54b1e)

**Comment by UbaserB** [comment]
Intended, you can't use a jetpack while gravity is off altogether as well only off-grid.
