### ISSUE TITLE
Industrial Grinder is not able to capture reagents.

### ISSUE THREAD

**Issue by JIPDawg** [space-wizards/space-station-14#31441]
## Description

When you give the industrial grinder any kind of plant with chemicals, it eats the plant or food but does not capture the chemicals within the plant. 

**Reproduction**

1. Link Industrial Grinder to level
2. Flip on
3. Feed stuff with chemicals.
4. Be sad you can't easily harvest the 1000x of .5omni within the ambrosia deus.

**Screenshots**

https://github.com/user-attachments/assets/868c6b71-8c48-4168-8f89-fefcb5d891b5

**Additional context**

I'm not sure how long this has been broken, but the only recent change to "recyclers" is in #30802 but I'm not really familiar if the Industrial Grinder shares some of the same code.

**Comment by Boaz1111** [comment]
hmm, this is odd. Let me look into how I made it again

**Comment by UbaserB** [comment]
got fixed
