### ISSUE TITLE
Syndicate sleepers announcement should be dynamic

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#31457]
## Description

When it is already blue alert or above, it should not say "Security alert elevated"

**Screenshots**

![image](https://github.com/user-attachments/assets/1efd3305-5519-4c97-8676-886d2888f4d8)

**Comment by Dutch-VanDerLinde** [comment]
dupe issue

**Comment by UbaserB** [comment]
> dupe issue

which issue, please link it here

**Comment by Dutch-VanDerLinde** [comment]
#28016
