### ISSUE TITLE
Trying to drag someone while holding a rifle always causes the rifle to be dropped, no matter the active hand combination

### ISSUE THREAD

**Issue by PaulRitter** [space-wizards/space-station-14#3145]
Reported by @"Herbert Falsevor#3037"

**Comment by Zumorica** [comment]
Isn't this due to drag/pull taking up a handslot? And I'm pretty certain this isn't specific to rifles

**Comment by AJCM-git** [comment]
This is not the case anymore, you cant pull if both of your hands are full and pulling takes the free hand
