### ISSUE TITLE
Opening belt then opening inventory bag will close the window instead of swapping windows

### ISSUE THREAD

**Issue by Plykiya** [space-wizards/space-station-14#31466]
## Description

or vice versa

**Reproduction**

**Screenshots**

**Additional context**

**Comment by Plykiya** [comment]
Also reports of this happening with toolboxes as well

**Comment by Titian3** [comment]
Happens with everything, belts, bags, medkits any inv item from look of it. Stayed closed for me until i close it and reopen if a few times via the verb menu, its very painful to do.

**Comment by Winkarst-cpu** [comment]
It looks like [RobustToolbox 5382](https://github.com/space-wizards/RobustToolbox/pull/5382) is breaking it.

**Comment by SkippyMcSkips** [comment]
Adding some screenshots to better show this issue:

First inventory opened:
![362449624-d2a82686-108e-446b-b362-4df4ee02e33d](https://github.com/user-attachments/assets/7fb819f7-2210-49ad-b480-192fd1997e41)

Second inventory opened:
![362449755-f03b9753-8335-49f5-a9bf-4903cac4382e](https://github.com/user-attachments/assets/8132042a-aca4-4fb4-ab47-84ad173bb000)

A split second later, the second inventory is now invisible (no buttons pressed):
![362449850-362817aa-e78e-406c-a4c4-cb5df73d2692](https://github.com/user-attachments/assets/96855115-439b-4841-90a0-5dd4582b9ea3)

If you right-click the second inventory, you can see it shows "Close Inventory", meaning it's still open but just not visible:
![362450249-90a24084-d0f2-431c-92d0-8fa8cdf2323d](https://github.com/user-attachments/assets/5b9eeb7b-9f6d-4b72-9664-e540126c32f0)
