### ISSUE TITLE
Medical belts in doctor's lockers start empty?

### ISSUE THREAD

**Issue by Plykiya** [space-wizards/space-station-14#31469]
## Description

I mean, security has dozens of fully loaded secbelts in every locker, I don't know if this is intended or unintended

**Reproduction**

**Screenshots**

**Additional context**

**Comment by slarticodefast** [comment]
Other lockers like the botanical one also have empty belts in them. Filling the medical belts with topicals would increase round start availability a lot. So maybe rather remove them from the lockers since they can also be found in the vendomat?
