### ISSUE TITLE
Using the chameleon projector to disguise as your own clothing makes you invisible

### ISSUE THREAD

**Issue by Veritius** [space-wizards/space-station-14#31476]
## Description
I think the title does it justice. I don't know if you're invulnerable but you certainly can't be targeted in melee.

**Reproduction**
1. Get clothes.
2. Get a chameleon projector
3. Open your clothing UI and use the chameleon projector on a hat or something.

**Additional context**
Discovered in round 63820 on Salamander.

**Comment by beck-thompson** [comment]
Dupe of #30271! Thanks for the bug report 🫡
