### ISSUE TITLE
Use Key (E) on belt while bag is open instantly closes belt UI.

### ISSUE THREAD

**Issue by TurboTrackerss14** [space-wizards/space-station-14#31489]
## Description
title

**Reproduction**
Open Bag anyway you choose
try to open belt with use key
belt will open for a split second and be stuck closed until you use context menu to "close ui"

**Screenshots**
https://github.com/user-attachments/assets/1c51befe-1479-404a-854e-e6187b652a79

**Additional context**

**Comment by lzk228** [comment]
dupe of https://github.com/space-wizards/space-station-14/issues/31466 ?

**Comment by TurboTrackerss14** [comment]
Agony.
