### ISSUE TITLE
Ignited Energy melee weapons are not showing as ignited

### ISSUE THREAD

**Issue by TurboTrackerss14** [space-wizards/space-station-14#31487]
## Description
All sprites assosiated with Energy melee weapons are not changing
**Reproduction**
Ignite energy weapon
No change
**Screenshots**

https://github.com/user-attachments/assets/a247fd42-8554-4e11-9804-6dd751290762
(video has no audio but they are infact ignited I am too lazy to rerecord)

**Additional context**

**Comment by Dutch-VanDerLinde** [comment]
dupe issue

**Comment by TurboTrackerss14** [comment]
so link the og?

**Comment by Dutch-VanDerLinde** [comment]
its already fixed #31478
