### ISSUE TITLE
Ion Stormed law order change persists onto new borgs and between rounds

### ISSUE THREAD

**Issue by ScarKy0** [space-wizards/space-station-14#31485]
## Description
Borg laws 1 and 3 are swapped since roundstart, persists between rounds and has been reported to happen to all borgs, all borgs ive seen at least.

**Reproduction**
1. Play borg
2. Check laws

**Screenshots**
![image](https://github.com/user-attachments/assets/3533ed42-a788-48e9-aedd-f340400bcc59)
![image](https://github.com/user-attachments/assets/50794aee-f4b3-487f-9da9-babcb5c0d365)
![image](https://github.com/user-attachments/assets/980c1fb0-9ee2-4897-bab5-d8cf721b7a72)

**Additional context**
Not Ion laws or anything, saw it between rounds and with multiple people.

**Comment by UbaserB** [comment]
I saw this today as well, yes

**Comment by Golinth** [comment]
Similar (or exact same?) bug was reported with #24354 if anyone needs more information

**Comment by ScarKy0** [comment]
Turns out this was because Ion Stormed laws would persist between rounds if the order was swapped

**Comment by GoldenCan** [comment]
Reproduction method that i used:
Affect cyborgs with Ion storms a lot of times (spawn in a lot of cyborgs so many cyborgs are affected each time you use /addgamerule IonStorm.)
After this you might notice that if you check your laws as AI in the CURRENT AND LATER ROUNDS that they order will have been altered. You can also see that newly generated cyborgs in both the current and later rounds will have their law order changed.

**Comment by deltanedas** [comment]
line 93 it clones the lawset so this should be either impossible or a c# funny from not being like rust clone

**Comment by ScarKy0** [comment]
> line 93 it clones the lawset so this should be either impossible or a c# funny from not being like rust clone

Removing that line from the else{} is what fixed it actually

**Comment by GoldenCan** [comment]
> line 93 it clones the lawset so this should be either impossible or a c# funny from not being like rust clone

Line 93 is inside of an else{} statement, and therefore only clones it sometimes. Moving the cloning to outside of the else{} statement solves this.
You can see this in commit https://github.com/space-wizards/space-station-14/commit/4b633fde9c84778e2817025b1d38bd2549202c52.

**Comment by deltanedas** [comment]
i thought GetLawset deep copied everything but oh well
