### ISSUE TITLE
[new]Borg random resets and other RECENT issues.

### ISSUE THREAD

**Issue by jamilnielsen** [space-wizards/space-station-14#31493]
## Description
at random intervals, happens 3-10 times in a round, borg gets reset, flashlight incorrect setting, etc.
this also messes with hotbar on the left(resets it)
this is new, happened due to changes today or late yesterday.
im sure there was other things that broke, but i cant recall em, pretty sure it was 3 things or more...
Edit: default borg state got reverted to broken again, they start with wrong state, flash light,module.
edit2: starter borgs having near infinite power until downed/etc appears fixed(probably accidental)

**Comment by Chubbicous** [comment]
If I press E on myself I get this bug. Flashlight toggles, hotbar messed up, etc.

**Comment by UbaserB** [comment]
It's when you click yourself or "deactivate"

**Comment by BramvanZijp** [comment]
Resolves by #32485, issue can be closed.
