### ISSUE TITLE
Matches don't ignite fires

### ISSUE THREAD

**Issue by PaulRitter** [space-wizards/space-station-14#3153]
reported by @"Grandma#0105"

**Comment by Zumorica** [comment]
Matches need to call `HotspotExpose` on their current `TileAtmosphere` regularly for this to be a thing. Currently, matches don't have an update method so they might need one specifically for this.

**Comment by Ygg01** [comment]
Yeah, matches probably need a way to start chemical reactions like fire etc.

**Comment by Peptide90** [comment]
Just to add to this for key words sake. Matches also don't ignite plasma / phoron (as established above).

We also need to add the flip lighter in. I'll take a look at both issues.
