### ISSUE TITLE
Door Hacking Popup Not Opening

### ISSUE THREAD

**Issue by environmentalSlimePreference** [space-wizards/space-station-14#31554]
## Description

When trying to hack a door, you are able to open the panel with a screwdriver, but **when clicking on it with wire-cutters, or a multi-tool, the window with the wires does not pop up.** 
There is no message popping up saying anything is wrong, instead it just does nothing.

**Reproduction**

Open the panel of a door with a screwdriver, then **attempt to hack** it by clicking on it with a multi-tool or wire-cutters.

**Additional context**
The panel was visibly open, when examined, it said it was open. There was no plate or anything covering the wires.
A different engineer tried this and confirmed that there was a problem.

**Comment by Doctor-Cpu** [comment]
graytiders in shambles

**Comment by slarticodefast** [comment]
I had this as well, but I'm pretty sure it is fixed by now. If you have it happen again, please comment and I'll re-open this issue
