### ISSUE TITLE
reach map has no scientist or RD role despite having an area dedicated to science that requires the access

### ISSUE THREAD

**Issue by lunarcomets** [space-wizards/space-station-14#31552]
## Description

as described on the tin

**Screenshots**

![image](https://github.com/user-attachments/assets/50eb81e2-2514-4857-be42-63fa41e25267)

**Comment by JustCone14** [comment]
Don't know if a RD is needed but at least one scientist definitely

**Comment by lunarcomets** [comment]
updated title
