### ISSUE TITLE
Recycler no longer stacks material it grinds

### ISSUE THREAD

**Issue by Plykiya** [space-wizards/space-station-14#31572]
## Description

**Reproduction**

**Screenshots**

**Additional context**

**Comment by UbaserB** [comment]
yea it was cursed

**Comment by lzk228** [comment]
huh? it worked for me yesterday
at least in my pr
https://github.com/space-wizards/space-station-14/pull/31518

**Comment by Tyzemol** [comment]
Same for lathes when ejecting mats so not just recycler

**Comment by Plykiya** [comment]
> huh? it worked for me yesterday at least in my pr #31518

I just reporta the issues, I do not understand why the issues exist

**Comment by UbaserB** [comment]
this is what it looks like in practice:

![image](https://github.com/user-attachments/assets/d77f43b2-f7f2-4aa7-942b-26fe72cef496)

**Comment by Plykiya** [comment]
This also applies to fabs...

**Comment by lzk228** [comment]
fixed by https://github.com/space-wizards/RobustToolbox/pull/5415
