### ISSUE TITLE
Escape pods are using directional fans

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#31578]
## Description

It was an oversight in #31495. The thrusters means it will now get spaced, and the fix to this would be to replace it with the normal tiny fans.

**Screenshots**

![image](https://github.com/user-attachments/assets/b33348d3-fa66-464d-a6cb-39995154fc57)

**Comment by lzk228** [comment]
what about place three directional fans to all three space sides?

**Comment by UbaserB** [comment]
> what about place three directional fans to all three space sides?

I'm not sure what the best idea is in this case but it's probably better to make it like it was before

**Comment by JustCone14** [comment]
I agree that a tiny fan would probably be better. Three directional fans might look a bit messy.

**Comment by UbaserB** [comment]
fixed by #31601
