### ISSUE TITLE
Tesla just not hitting anything with it's lightning for a really long time

### ISSUE THREAD

**Issue by Krovotushka** [space-wizards/space-station-14#31579]
Tesla just tend to not hit with objects with it's lightnings like its supposed to be

How to reproduce: just set up tesla idk

Happened on Salamander round 64019 (I cant send a video with size larger than 10MB so i will send it into discord forum)

**Comment by themias** [comment]
I think this has to do with [#5400](https://github.com/space-wizards/RobustToolbox/pull/5400).

EntityLookupSystem.ComponentQueries.GetEntitiesIntersecting() seems to return empty when hitting the else statement.

This also seems to be the cause of #31572.

**Comment by themias** [comment]
I did some testing and it looks like this was fixed by [#5415](https://github.com/space-wizards/RobustToolbox/pull/5415).
