### ISSUE TITLE
You can "deactivate" borgs

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#31585]
## Description

Both the borg themselves and outside people can tap this button. What ends up happening is that all modules/hand slots on the screen turn invisible for a split second and sometimes it breaks the borg lights.

**Screenshots**

![image](https://github.com/user-attachments/assets/5fb73c73-6a94-490e-8269-2d377e9319bc)

**Comment by Cojoke-dot** [comment]
Borg also just deactivates themself every once and a while and every time you get into a Borg charger.

**Comment by deltanedas** [comment]
borgs should have not have had a verb added when that pr was made

**Comment by Chubbicous** [comment]
Seems like similar issues to #31493

**Comment by UbaserB** [comment]
> Seems like similar issues to #31493

Yeah it's exactly the same

**Comment by BramvanZijp** [comment]
Resolved by #32485
