### ISSUE TITLE
There's an unpowered light on Bagel

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#31580]
## Description

It's just above arrivals.

**Screenshots**

![image](https://github.com/user-attachments/assets/12b92f8f-5418-4c55-8d97-6bdf47976078)

**Comment by lzk228** [comment]
is it the newest version? there was a wire fix in https://github.com/space-wizards/space-station-14/pull/31566

**Comment by UbaserB** [comment]
This was like two rounds ago yea
