### ISSUE TITLE
AI non-verb-menu door bolting (feature request)

### ISSUE THREAD

**Issue by Everturning** [space-wizards/space-station-14#31598]
I think AI should be able to bolt doors without needing the verb menu, and I've got two ideas as to how this may be done:
Alt-shift-e
Alt-click twice (the one I prefer)
These controls require two steps to bolt a door, which makes it (in my opinion) feel more active, while also being easier than going down the verb menu. we could also make it a keybind in settings

**Comment by Emisse** [comment]
it can already alt click to bolt
