### ISSUE TITLE
Stacks should prob have some sort of count indicator next to its sprite (in inventory)

### ISSUE THREAD

**Issue by PaulRitter** [space-wizards/space-station-14#3160]
Do a count indicator OR do the stackvisualizer idea like original ss13?

reported by @"Grandma#0105"

**Comment by SweptWasTaken** [comment]
Nah

**Comment by metalgearsloth** [comment]
Doesn't IItemStatus already have the count?

**Comment by SweptWasTaken** [comment]
> 
> 
> Doesn't IItemStatus already have the count?

Yeah but I think they meant an overlay over the sprite when in your hand which is ???

**Comment by ShadowCommander** [comment]
They meant a stack number/indicator when inside a StorageComponent like a backpack.
