### ISSUE TITLE
Feature Request: Spinning In Harm Too Much Makes You Vomit

### ISSUE THREAD

**Issue by Kezu02** [space-wizards/space-station-14#31636]
## Description

Dunno if it's even possible. Spessmen aren't immune to feeling sick so it'd be funny if it works.

**Comment by Cojoke-dot** [comment]
WHY!!! GUAH!!! THIS IS EVIL!!!

**Comment by thebadman4662** [comment]
Clown walks into medical, vomits 10 medicals worth of puddles slipping everyone.

**Comment by EthanQix** [comment]
> Clown walks into medical, vomits 10 medicals worth of puddles slipping everyone.

if the clown manages to survive, that would be an impressive prank

**Comment by engineer-pearl** [comment]
This could screw with attack-mode dancing.

(It's not uncommon, at least on DeltaV, for people to use attack mode to make their character "dance" in place)

**Comment by Everturning** [comment]
yeah no "realistic" and "fun" have a point at which they conflict. this is REALISTIC but not FUN.

**Comment by EthanQix** [comment]
Maybe replacing "spinning too much" with "spinning too fast" would solve it ? I've seen some people spin so fast on bar stools they're basically phasing through reality, that should warrant some dizziness at least ^^

**Comment by Ilya246** [comment]
this would mean if you're poisoned you can just spin to vomit it out

**Comment by thebadman4662** [comment]
> this would mean if you're poisoned you can just spin to vomit it out

Extract brain matter on demand from gibbed brains too. :trollface:

**Comment by Kadeo64** [comment]
its funny but ideally it shouldn't actually be a gameplay affecting change, just visual

like, keep the vomiting on spin, but don't actually cause the spaceman to vomit, just have the vomit popup and sound effect play while a banana cream pie-like face entity that needs to be washed off spawns (except it's a bit of vomit on your shirt)

this way we have the funny spin vomit but without the ability to on demand unpoison yourself

**Comment by Hreno** [comment]
It'd be cool if vomiting immediately after consuming poison does unpoison yourself, but after a while, as the poison gets absorbed through the stomach, that doesn't work any more.

**Comment by Kadeo64** [comment]
> It'd be cool if vomiting immediately after consuming poison does unpoison yourself, but after a while, as the poison gets absorbed through the stomach, that doesn't work any more.

I mean then this just leads to metagame where successful direct poison attacks become useless against any player with the spin knowledge, since if they get injected or hit they'll just spinvomit and then retaliate. You would have to inject then follow up with melee which is a lot less sneaky than poison

**Comment by UbaserB** [comment]
i dont like this idea

**Comment by Kadeo64** [comment]
also kojima did it first (mgs3)

**Comment by ArtisticRoomba** [comment]
If you really want to discourage spinning you can probably just have the flash effect act as a motion sickness consequence for spinning for too long. Not sure if you can "ramp up" the flash effect to achieve this with more spinning, not just having a random "flash" happen when you spin too much. 

But do we really _want_ to remove something so iconic from SS14? Harm mode spinning? That's funny!

**Comment by bruhmogus** [comment]
this is a bad idea because this'll probably end up occurring during actual combat
