### ISSUE TITLE
Liquid oxygen cannot be metabolized

### ISSUE THREAD

**Issue by ScarKy0** [space-wizards/space-station-14#31642]
## Description
Liquid gasses cannot be metabolized and are just stuck inside of the playable character forever.

**Reproduction**
1. Inject yourself or drink 250u of any liquid gas that has no effect.
2. You can't be injected with any meds anymore.

**Screenshots**
![image](https://github.com/user-attachments/assets/7f5f97f1-4338-49cc-a4b5-09cba42ed241)

**Additional context**
Some of the gasses go away when bleeding, meaning if you bleed yourself enough you can still inject SOME form of medicine after.

**Comment by deltanedas** [comment]
same for every condensed gas like n2o

**Comment by ScarKy0** [comment]
Yeah, I just checked
Every condensed gas that has no effects in liquid form just is stuck there

**Comment by UbaserB** [comment]
Oh god

**Comment by ScarKy0** [comment]
> Duplicate of https://github.com/space-wizards/space-station-14/issues/25467 I think?

Oh yeah thats literally it, my bad

**Comment by ScarKy0** [comment]
Since its a duplicate ill close this, but I think this gives me a good excuse to try to learn how to make a PR and fix it
