### ISSUE TITLE
Trying to anchor a plant fails because the tool is hidden in the plant instead

### ISSUE THREAD

**Issue by magelfik** [space-wizards/space-station-14#31646]
## Description

There are many potted plants around most of the stations. Should you want to anchor one, you would typically use a wrench. Trying to do so starts the action, but stops in the middle because the wrench gets hidden into the potted plant.
Given two actions are being done at the same time, I'd suggest linking one of them to an auxiliary action (ALT + Click).

**Reproduction**
* Find potted plant
* Try to anchor it
* Smile at the progress bar being shown, anchor time is nigh
* Loudly sob at your wrench being hidden in the potted planted instead

**Screenshots**
https://github.com/user-attachments/assets/b80fc6c5-569e-4e9a-bc74-a8c8524f4239

**Additional context**
Clearly not an issue that prevents playing, but I found that the other day.

**Comment by UbaserB** [comment]
I feel like this is a dupe

**Comment by JIPDawg** [comment]
As a workaround put something else in the plant first, then anchor.

**Comment by magelfik** [comment]
> I feel like this is a dupe

Well...about that... it's definetly related to https://github.com/space-wizards/space-station-14/issues/31455

**Comment by godisdeadLOL** [comment]
the same problem with toilet's secret stash
