### ISSUE TITLE
The AI eye can use the Arrivals shuttle 

### ISSUE THREAD

**Issue by 8Redacted8** [space-wizards/space-station-14#31683]
## Description
If the AI eye is on the Arrival shuttle as it leaves it stays on the shuttle on it way back in contrast to other player character that get left behind if they are on the shuttle when it leaves.

**Reproduction**
As AI position your eye on the shuttle and wait for it to depart. You should then be on the shuttle as it is in FTL and a bit later you should arrive at the Arrival terminal.

**Additional context**
Im not 100% sure if that is an oversight or if its intentional but in case its the latter im making this report.

**Comment by muburu** [comment]
works on any shuttle going into FTL

**Comment by slarticodefast** [comment]
Fixed by #32094
