### ISSUE TITLE
do_after is eternal.

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#3168]
## Description

do_after doesn't go away again on certain stuff. Also it doesn't stack anymore.

**Screenshots**

**Additional context**

**Comment by Peptide90** [comment]
Is #2813 related now? There's a few do_after related issues around that time.

**Comment by Zumorica** [comment]
Those issues are very related if not the same, ye

**Comment by metalgearsloth** [comment]
Replicating is hard and apparently it still happens so if anyone can reproduce (or alternatively just bulldoze the client's DoAfterGui / DoAfterSystem...)
