### ISSUE TITLE
Wideswinging a blunt weapon does not trigger blunt stamina damage.

### ISSUE THREAD

**Issue by Blackern5000** [space-wizards/space-station-14#31693]
## Description
Weapons that deal stamina damage through BluntStaminaDamageModifier do not deal any stamina damage if you are wideswinging. This means the truncheon and disabled stunbaton cannot stun people if they are wideswung.

**Reproduction**
- Get a truncheon
- Wideswing a urist to crit in 5 hits
- M1 a urist to stun in 4 hits, watch them get up
- _screams!_

**Screenshots**

https://github.com/user-attachments/assets/342a302c-994b-4c3c-97fa-793b21505c3e

**Comment by ScarKy0** [comment]
I think its solved? You can close it
