### ISSUE TITLE
Hotbar actions go out of the screen boundaries

### ISSUE THREAD

**Issue by godisdeadLOL** [space-wizards/space-station-14#31717]
## Description

Too many actions overlap inventory ui and then go out of the screen. I'd suggest displaying actions in multiple columns.

**Reproduction**

1. Became space ninja or find some other way to get too many actions in the hotbar.

**Screenshots**

![output](https://github.com/user-attachments/assets/6a705380-4a56-4500-9c38-526a66f1cb4a)

**Additional context**

quite inconvenient

**Comment by bruhmogus** [comment]
given the dead space on the edge of the screen i'd say using multiple columns is the best choice
