### ISSUE TITLE
Reach should have salvage slot

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#31711]
## Description

They have a magnet and all the stuff needed for salv and cargo is a bit of a separate job so its often split up from my experiences in deadpop.

**Screenshots**

![image](https://github.com/user-attachments/assets/7ed4f7f4-1eed-48ae-bf48-d6e32086ec3b)

**Comment by thebadman4662** [comment]
Cargo tech gets salvage access on skeleton crew, so in crew of 5(target of Reach) it should be fine?

**Comment by UbaserB** [comment]
> Cargo tech gets salvage access on skeleton crew, so in crew of 5(target of Reach) it should be fine?

I wasn’t able to open the external docking airlock and assumed it was because i was missing access

**Comment by Boaz1111** [comment]
yeah they don’t get external access on skeleton crew

**Comment by JustCone14** [comment]
This can be closed now
