### ISSUE TITLE
airlock wire ui is kinda broken

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#31734]
![Screenshot_20240902_010529](https://github.com/user-attachments/assets/8aeea8ab-40a0-4799-b0a5-a55532ad4e78)

**Comment by slarticodefast** [comment]
Happening to me as well. Same with vending machines.
I assume the addtion of the new AIA light for the AI access did not move the wire graphics downwards, so it is now overlapping.
![grafik](https://github.com/user-attachments/assets/cbf289a6-1c50-49f5-aec6-4be05e650427)
