### ISSUE TITLE
AMEs bigger than two cores produce less power

### ISSUE THREAD

**Issue by ondrej008** [space-wizards/space-station-14#31758]
## Description

If you increase an AME's size to three cores, it will produce less power than an AME with two cores.

**Reproduction**

Build an AME with 2 cores, set injection to 4, note down the power produced (~180 kW).
Add one more core to the AME, making it 3 cores, set the injection to 6, note down the power produced  (~174 kW).
Add one more core to the AME, making it 4 cores, set the injection to 8, note down the power produced (~152 kW).

Notice that **by adding more cores & injecting more fuel, the power produced has gone down**.

**Screenshots**

Here is a graph of the power produced by an AME assuming optimal injection (injecting two fuel for every core).

![image](https://github.com/user-attachments/assets/963f33df-1fc0-4057-bc0c-1c3ca89a9042)

![image](https://github.com/user-attachments/assets/847a6d26-6048-41c6-9a3f-fc3330774b2f)

`200000f * MathF.Log10(fuel * fuel) * MathF.Pow(0.75f, cores - 1)`

Here is the graph of the power produced before the change made in #29587 assuming optimal injection (injecting two fuel for every core).

![image](https://github.com/user-attachments/assets/b95e7fbe-0bb4-4b0a-ad92-0695d3e05cd5)

![image](https://github.com/user-attachments/assets/23296929-b901-471f-b144-30736ccbcfbc)

`20000f * fuel * fuel / cores`

**Additional context**

This was introduced in #29587

**Comment by UrPrice** [comment]
What's the problem?
Literally: 
![image](https://github.com/user-attachments/assets/7d61162b-5373-458e-b1a6-f941e1b66fa4)

**Comment by ondrej008** [comment]
> What's the problem? Literally: ![image](https://private-user-images.githubusercontent.com/107646133/363777004-7d61162b-5373-458e-b1a6-f941e1b66fa4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMDk1NTMsIm5iZiI6MTcyNTMwOTI1MywicGF0aCI6Ii8xMDc2NDYxMzMvMzYzNzc3MDA0LTdkNjExNjJiLTUzNzMtNDU4ZS1iMWE2LWY5NDFlMWI2NmZhNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMlQyMDM0MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NGMzNGY3NTk4ZDE5ZWZmYTQ4YmJlZDg1M2ZkZWQ4Zjg0Y2M3MWI2NjFjZDBmN2VkMTkyNjljZjU4NGIzNmQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SZzCMrZQ5aotWZR5pC-W23m4PXcW6zAwy3_Jg3Dn1OQ)

The information that an AME bigger than two cores is useless is never communicated in-game, on the wiki (which has completely outdated information).

I do not understand what you mean by the image you posted, it seems irrelevant as the AME is not an equivalent in terms of it's outcomes or payoffs compared to the other energy generation options. A player cannot interchangeably choose between the different power generators as they have different requires and outcomes.

**Comment by ArtisticRoomba** [comment]
degenerate strategy is cool and all but it realistically does not makes sense that 2 cores just nukes power output to the point where its better to just have one core. multi-core AME setups _should_ exist in limited numbers for stations that have such absurd power draws that there is not a 10 minute buffer for engineering to setup a power source.

IMO engineering isn't really having any trouble setting up power roundstart anymore (as long as they are mildly competent) so this is more of a guidebook concern. the 2 core AME being worse than the 1 core AME should be looked at a bit though.

**Comment by Ilya246** [comment]
we need another AME rework, make it into a fast-setup high-risk generator you want to dismantle/turn off as soon as you get alternative power, maybe have it operate like a reactor

**Comment by ArtisticRoomba** [comment]
I disagree, I just don't want the AME to become an inherent noobtrap. AME should be something simple, to get engineering on their feet and buy time. Think of it as engineering's fancy PACMAN. Making it something that needs to be managed when it's only purpose is to power the PA in those first 10 minutes of the shift is not really a good idea.

Everyone already knows that the AME does nothing for the station in the long term. This is just a concern for helping AMEs on larger stations bridge the gap to the 10 minute mark (the amount of time a station can run on battery + AME before browning/blacking out).

**Comment by Savsj** [comment]
> I disagree, I just don't want the AME to become an inherent noobtrap. AME should be something simple, to get engineering on their feet and buy time. Think of it as engineering's fancy PACMAN. Making it something that needs to be managed when it's only purpose is to power the PA in those first 10 minutes of the shift is not really a good idea.
> 
> Everyone already knows that the AME does nothing for the station in the long term. This is just a concern for helping AMEs on larger stations bridge the gap to the 10 minute mark (the amount of time a station can run on battery + AME before browning/blacking out).

I say we just rename the AME to the MSPACMAN and go all on on that comparison.

**Comment by Golinth** [comment]
I did a little bit of messing around with the function, and came up with this
![image](https://github.com/user-attachments/assets/83cb4d77-a353-43d3-b9c2-045b3113f536)

Realistically even with hundreds cores you will never reach above 350kW, which is not enough to power most large stations. You do start with less power, however it does not punish players for making more than 1 core, and the power generation will always increase, if marginally. At one core (what most stations have) the power generation is roughly equal.

**Comment by ArtisticRoomba** [comment]
I like this graph much, much better. A proper logarithm that puts a hard cap on absurd core sizes while still making multi-core setups viable for mappers that want to give engineering some more time. 

Can I have the equation for the graph so I can see about implementing it?

**Comment by Golinth** [comment]
> I like this graph much, much better. A proper logarithm that puts a hard cap on absurd core sizes while still making multi-core setups viable for mappers that want to give engineering some more time.
> 
> Can I have the equation for the graph so I can see about implementing it? I'd probably do some more tinkering and in-game tests to make sure it matches up with the 10 minute goal on most stations.

I never saw this, sorry. I deleted the original message because I realized that formula didnt take the amount of cores into consideration, just injection amount. I have PR'd a new formula, where the power generation at 1 core 2 fuel is the exact same as live. It includes a link to the graph that I used if you want to mess with it yourself.

**Comment by Partmedia** [comment]
The intent of the change that is being proposed to be reversed was:

> the AME is meant to be a bootstrapping / emergency power supply. It shouldn't be able to power full-sized stations completely for 30+ minutes.

Has something changed enough that we need to revisit this? Or are we just ping-poinging?

**Comment by Golinth** [comment]
> The intent of the change that is being proposed to be reversed

I don't think the intent is to reverse the change, and with my PR specifically, I ensured that the maximum power a typically mapped stable AME produces is not changed. This issue just points out that, counterintuitively atm, AMEs larger than 2 cores currently produce _less_ power than a smaller cores would, making the mapped 4 core AMEs that exist a bit of a noob trap. 

I think keeping the AME as the bootstrapping engine that shouldn't be run all round and only used for emergency power is a good thing, it should just be consistent. I hoped to have accomplished that with my PR.

**Comment by Ilya246** [comment]
yes current ame is a big noobtrap, going above 2 cores means less total power production even though you take more fuel

**Comment by ArtisticRoomba** [comment]
Once again I think that having a 2 core AME produce less power than a single core ame is suboptimal, and a noobtrap. Tt should be a super heavy logarithm after you pass 120kW, the base one-core, which is what this PR accomplishes.

This change aims to make mapped multi-core AMEs viable. It's stupid that I have to tell the engineers that the 4 core AME we get on oasis is the "wrong" way of building the AME.

As a CE I DISTINCTLY remember a situation where a 4-core AME was built and it was producing like 60 something kW on oasis. had to tell the poor engineer otherwise.

This is not bringing back the AME as a second, 30-minute power source.

**Comment by UrPrice** [comment]
> The intent of the change that is being proposed to be reversed was:
> 
> > the AME is meant to be a bootstrapping / emergency power supply. It shouldn't be able to power full-sized stations completely for 30+ minutes.
> 
> Has something changed enough that we need to revisit this? Or are we just ping-poinging?

I can see why people want AME to be something simpler than it used to be, and also to have enough for the whole station. 

Could it be a problem that you have the gameplay side forcing engineers to build AME as the first engine?

We (on SS220) had this problem, due to the understaffing of other engines and the rapid drawdown of SMES'es. We solved this problem radically by not making the AME power the whole station, but by adding overcharge for SMES'es (SMES'es are charged to 800% or other number by roundstart and are gradually spent, but cannot be charged above 100%): https://github.com/SerbiaStrong-220/space-station-14/pull/1745

**Comment by UrPrice** [comment]
> We (on SS220) had this problem...

Actually, when we improved SMES'es a bit - we got AME for emergencies only, as it no longer needs to be assembled like the first engine.

**Comment by scrivoy** [comment]
Hey guys, here is what I think about this.

https://github.com/space-wizards/space-station-14/pull/32825#issuecomment-2418026501
