### ISSUE TITLE
Ahelp Popout Button is lets say, fucked

### ISSUE THREAD

**Issue by BlitzTheSquishy** [space-wizards/space-station-14#31752]
## Description

When the ahelp menu is opened and the popout button is pressed the main clients scrreen shifts very dark with high(?) contrast requiring a restart.

**Reproduction**

Open ahelp menu (f1)
press pop out (probably by accident)

**Screenshots**

![image](https://github.com/user-attachments/assets/e9595575-3a17-4d3e-b3b6-a620c4a1f213)

**Additional context**

I dont use the steam overlay nor discord overlay on ss14 as I play windowed (like a weirdo)

**Comment by dffdff2423** [comment]
The ahelp popout menu is so broken that I think the button should just be removed until it is fixed. It really sucks to have to restart the game and lose all the ahelps from your client (so you need to dig through the discord relay).

**Comment by BlitzTheSquishy** [comment]
> The ahelp popout menu is so broken that I think the button should just be removed until it is fixed. It really sucks to have to restart the game and lose all the ahelps from your client (so you need to dig through the discord relay).

Absolutely, either completely removed or repaired post-haste

**Comment by Everturning** [comment]
Playing space game, straight up "ahelping it". And by "ahelping it" let's just say.... _restarts_

**Comment by BlitzTheSquishy** [comment]
> Playing space game, straight up "ahelping it". And by "ahelping it" let's just say.... _restarts_

As an admin, this is a pain in the ass if you accidentally press it as frequently as I do.. restarting the client isnt a fix for a bug, its a solution but not an actual fix.

**Comment by Everturning** [comment]
> > Playing space game, straight up "ahelping it". And by "ahelping it" let's just say.... _restarts_
> 
> As an admin, this is a pain in the ass if you accidentally press it as frequently as I do.. restarting the client isnt a fix for a bug, its a solution but not an actual fix.

wait I thought this was for normal players mb, and also I wasn't claiming it was a fix, I was trying to make a joke out of the bug you're experiencing

**Comment by BlitzTheSquishy** [comment]
> > > Playing space game, straight up "ahelping it". And by "ahelping it" let's just say.... _restarts_
> > 
> > 
> > As an admin, this is a pain in the ass if you accidentally press it as frequently as I do.. restarting the client isnt a fix for a bug, its a solution but not an actual fix.
> 
> wait I thought this was for normal players mb, and also I wasn't claiming it was a fix, I was trying to make a joke out of the bug you're experiencing

All good, also yeah- the admin side of it, the player side its literally just a text box and a close button, while the admin side has a LOT more buttons, one of which being... this fucking broken ass button

**Comment by VasilisThePikachu** [comment]
I think this is not fixed so I will play it safe.

**Comment by Simyon264** [comment]
![image](https://github.com/user-attachments/assets/e57aa82a-0630-4eb2-82fb-99d5a244e81f)
Correct, it is not fixed.

**Comment by JIPDawg** [comment]
It works fine for me. I play full screen, steam overlay off.

![image](https://github.com/user-attachments/assets/19f39934-e38f-4ee1-a06a-cfddc2460536)

**Comment by Simyon264** [comment]
Yeah, the issue is with the steam overlay being on.

**Comment by JIPDawg** [comment]
Just turn steam overlay off. :godo:

**Comment by BlitzTheSquishy** [comment]
This issue is actually fixed now.
