### ISSUE TITLE
Cargo needs roundstart Ripleys on more maps

### ISSUE THREAD

**Issue by K-Dynamic** [space-wizards/space-station-14#31768]
## Description

Idea is to integrate more Ripley gameplay with station, especially cargo as they lack bulk crate transportation.

Related to #17353 and other discussions on improving cargo loop.

(As of 2024/09/03, excludes Atlas, Train, Cluster, Origin, Saltern)
- [x] Fland
- [x] Bagel
- [X] Core
- [x] Marathon
- [x] Meta
- [ ] Reach (too small?)
- [x] Box
- [x] Omega
- [x] Oasis
- [X] Cog
- [x] Packed

**Comment by UbaserB** [comment]
wait has this been discussed yet

**Comment by Spessmann** [comment]
Cog has ripley as of #31815
