### ISSUE TITLE
Vox air alarm is buggy

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#31770]
## Description

While the air alarm does functionally work as intended, the UI states otherwise and it additionally continues to show a "warning" in a pure nitrogen environment when it should be green.

**Screenshots**

![image](https://github.com/user-attachments/assets/e15af97c-3142-4043-9c0e-1c26e0425ddb)

**Comment by deltanedas** [comment]
you have to link it to vox suffix devices, devices are what have the settings

**Comment by UbaserB** [comment]
o h
