### ISSUE TITLE
Core Station: Two Grilles Rotated Wrong

### ISSUE THREAD

**Issue by PanzerVo** [space-wizards/space-station-14#31786]
## Description
On Core, two grilles in the section between the two reinforced walls are facing north, while the rest of the grilles are facing south. Located by the bar, just under the plasma glass. 

**Reproduction**
Observe as a ghost with full lighting
Look at the grilles below the plasma window by the bar
Cry cause you now noticed two of them are misrotated

**Screenshots**
![image_2024-09-03_192321312](https://github.com/user-attachments/assets/a6ff8ae2-3fcb-4f55-8aed-567151cf2ada)

**Additional context**

**Comment by Emisse** [comment]
how did you notice this

**Comment by PanzerVo** [comment]
> how did you notice this

Same way you found out. Have someone else point it out to you.
