### ISSUE TITLE
Disaster pods need a normal minifan

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#31825]
## Description

The normal evacuation pods got fixed but not the disaster one, currently causing all the air to escape the pod immediately.

**Screenshots**

![image](https://github.com/user-attachments/assets/e7e41ea4-7759-4cc1-812e-b13f0b0505b4)

**Comment by Errant-4** [comment]
Isn't this already merged? #31601

**Comment by Errant-4** [comment]
Fixed by #31915
