### ISSUE TITLE
vox area sign has obvious parallels to real world discriminatory language and signage. Should consider change or removal.

### ISSUE THREAD

**Issue by APOCAMANDER** [space-wizards/space-station-14#31840]
## Description
The wall mount sign "voxcrossing.png" labeled in game as "vox area sign" has several reasons to be changed or removed.

\SS14\Resources\Textures\Structures\Wallmounts\signs.rsi\voxcross.png

Most obviously, it parallels discriminatory treatment, language, and signage in the United States. In particular, the name, "vox area sign" is egregiously similar. The notion that signs need to be put up to indicate where certain species should or could go is an issue in itself. The stations, while not equally accessible to all, should at least avoid language and signage that organizes space by species. "voxcrossing.png" is a dehumanizing name as well, which could be interpreted to indicate that vox are animals or should be treated as animals.

Additionally, the sign is meant to indicate an area of exclusively N2 atmosphere, which is already easily accomplished with atmos_n2.png labeled in game as "N2 warning sign". The addition of a sign to indicate a space for vox is inferior at communicating, especially to new players, that the area has a different atmosphere composition.

There are no "area signs" equivalent for any other species, and they would be unnecessary in almost all cases. Singling the vox out as both different and to be treated different. Signs should indicate what is different about an area not who should go there.

Voxboxes as they've come to be called are also expected to be tacked on to the station as an afterthought, indicating NT did not plan for N2 breathing species. Having signage specifically for them changes the implication from "lacking in planning" to "intentionally inferior", at least to me.

**Additional context**
I could add example of signs that might better explain why I have created this issue, but I think most have seen them. If necessary, I will add them later at request.

I am no expert at communicating on such sensitive matters, but I felt this issue should be brought up immediately. If my wording or format is lacking in some way, please let me know and I apologize ahead of time.

**Comment by DogZeroX** [comment]
what

**Comment by engineer-pearl** [comment]
Honestly, I have been interpreting it as "Vox are relatively new, so stations are not yet updated". Only relatively though. My Vox is still cranky about lack of facilities. (Not even the occasional pre distributed canister? Come on guys!)

**Comment by deltanedas** [comment]
slimepeople can live perfectly fine in vox boxes so a description-changed n2 sign will do

**Comment by APOCAMANDER** [comment]
> what

I can provide clarification. What's the unclear portion?

**Comment by Dutch-VanDerLinde** [comment]
where even is "voxcrossing.png" i cant find it in the game files

**Comment by APOCAMANDER** [comment]
> where even is "voxcrossing.png" i cant find it in the game files

t\SS14\Resources\Textures\Structures\Wallmounts\signs.rsi\voxcross.png

**Comment by LordEclipse** [comment]
Vox get poisoned by breathing in oxygen.

**Comment by Emisse** [comment]
i didnt know this was even a thing, it should jsut be changed to a nitrogen saturated environment sign

**Comment by Geekyhobo** [comment]
What

**Comment by APOCAMANDER** [comment]
> What
Which part is unclear?

**Comment by PJB3005** [comment]
The sprite was *apparently* taken from /vg/station, where Vox are *haha slur slur*. Part of that means that it intentionally looks worn/damaged like other Vox-specific infrastructure. How this managed to pass by review of art directors is kind of baffling to me and I am going to light a fire under somebody's ass for this.

/vg/ does have a lot of useful "material" related to the Vox species, as they're actually uniquely developed there. But the 4chan humor can stay at the door.

Agree that it should probably be one of those blue sprites that is used to indicate rooms. I don't really care too much about whether the iconography should include a Vox or just be generic N2. To me having an actual icon of a Vox is no worse than a bathroom sign as long as it uses more neutral colors (look I know split gender bathrooms are cringe but you get the point).

**Comment by engineer-pearl** [comment]
I would like to argue in favor of using a "no oxygen" sign instead of a nitrogen sign. The station air is already nitrogen saturated, the issue vox have is the presence of oxygen. The issue most other species will have in the vox box is similarly, the absence of oxygen.

**Comment by APOCAMANDER** [comment]
> I would like to argue in favor of using a "no oxygen" sign instead of a nitrogen sign. The station air is already nitrogen saturated, the issue vox have is the presence of oxygen. The issue most other species will have in the vox box is similarly, the absence of oxygen.

the O2 sign with a big Red Circle with a slash through it might be worthwhile?

**Comment by PJB3005** [comment]
> I would like to argue in favor of using a "no oxygen" sign instead of a nitrogen sign. The station air is already nitrogen saturated, the issue vox have is the presence of oxygen. The issue most other species will have in the vox box is similarly, the absence of oxygen.

Indicating "no oxygen" does indeed make sense from a hazard perspective, but if we want to do that I think it'd be better if we had both.

**Comment by SlamBamActionman** [comment]
It feels like this issue fails to consider that the "Voxbox" and the accompanying Vox sign is implemented as an accessibility aid indicator for the species, and the comparison to real life race discrimination does not hold up in that context.

The voxbox is not implemented as an "if you're Vox, stay in your little cornered off area, we don't want you over here" area. Rather it's designed as an area to serve specific physiological needs for Vox since they can't perform some basic life functions without difficulty without it. No one is stopping a Vox from sitting down at the bar to order a drink, and no one is stopped from sitting with the Vox in the voxbox. But if the Vox is gonna take a sip from that drink then, yeah, they probably wanna do it in a nitrogen-rich environment or else they get poisoned. 

To me this reads like complaining that an office has a dedicated accessibility toilet. "How dare you mark out the area designed to accommodate wheelchair users?" 

Personally I think the sign should be made less scrappy and/or changed to N2, and the Vox area shouldn't be decorated in any poorer condition than the rest of the station, but I disagree with the thesis presented in the original post.

**Comment by APOCAMANDER** [comment]
![atmos_no_n2](https://github.com/user-attachments/assets/3b43b0d3-94d2-4c2e-b611-b667a085efcc)
How's this for a quick version? will rough it up a bit if this is a good start. Then make a matching _no_o2 version as well.

**Comment by APOCAMANDER** [comment]
> It feels like this issue fails to consider that the "Voxbox" and the accompanying Vox sign is implemented as an accessibility aid indicator for the species, and the comparison to real life race discrimination does not hold up in that context.

According to PJB above, the intention of the original source was to emulate early USA treatment of racial discrimination and segregation. Also, Vox aren't disabled.

**Comment by APOCAMANDER** [comment]
> I see what you're thinking, but I am worried it isn't likely to be eye catching or clear without close inspection. Worse, it may not be easy to distinguish between the no-o2 sign without in game inspection.

That's a good point. is there a specific color pallet that should be used for this context? Red/Black is the easiest to catch the eye and notify the user "hey, this is different"

**Comment by engineer-pearl** [comment]
> > I see what you're thinking, but I am worried it isn't likely to be eye catching or clear without close inspection. Worse, it may not be easy to distinguish between the no-o2 sign without in game inspection.
> 
> That's a good point. is there a specific color pallet that should be used for this context? Red/Black is the easiest to catch the eye and notify the user "hey, this is different"

So not at a useful device for this so excuse the fidelity. 

I would likely take inspiration from Hazard Diamonds in the overall design of the sign. Keep it simple, with minimal details.

This is for public areas rather than specialized areas, so deviation from the air sines in engineering should be fine. It is a different audience, after all. 

I would then likely match the color associated with the gas to the gas label, to make it stand out. 
 
![Screenshot_20240904-122743](https://github.com/user-attachments/assets/c68181ee-4982-4617-a972-187fe5ede6ed)

**Comment by Errant-4** [comment]
I think it would make sense to make the "no oxygen" sign a hazard diamond _the color of nitrogen_, with a crossed out black O2 in it

**Comment by APOCAMANDER** [comment]
All current hazard signs are triangle, not diamond. in fact, only diamond currently is voxcross.png should I use triangle instead?

**Comment by SlamBamActionman** [comment]
> > It feels like this issue fails to consider that the "Voxbox" and the accompanying Vox sign is implemented as an accessibility aid indicator for the species, and the comparison to real life race discrimination does not hold up in that context.
> 
> According to PJB above, the intention of the original source was to emulate early USA treatment of racial discrimination and segregation. 

Pending clarification I don't think that's what PJB said, other than indicating that Vox came from a community where Vox were mistreated as a species.
`The sprite was apparently taken from /vg/station, where Vox are "haha slur slur". Part of that means that it intentionally looks worn/damaged like other Vox-specific infrastructure.`
That does not say anything about them emulating USA racial discrimination in their design, and disregards that Vox went through its own design document for SS14, where the species was evaluated on its own.


> Also, Vox aren't disabled.

I specifically worded my post to make sure I did not say that. They _do_ however have a specific physiological need that is not shared with the majority of the population on the station, and it's one that _requires_ specific accommodations for healthy living. While we do not have alien species in our human society, the closest comparison _would_ be to an individual with a health condition, so the comparison is apt, much more than comparing it to forceful segregation.

**Comment by engineer-pearl** [comment]
> All current hazard signs are triangle, not diamond. in fact, only diamond currently is voxcross.png should I use triangle instead?

No issue with that here. Based on my clumsy scribbles, I am not sure I can sketch that for now. I will need to wait a few hours for better tools. 



> I think it would make sense to make the "no oxygen" sign a hazard diamond _the color of nitrogen_, with a crossed out black O2 in it

I hear where you are going, but I have two concerns. First, it would limit use of the sign to nitrogen filled areas with no oxygen. (So no applying it to a burn chamber.) Not a deal breaker, but an odd choice. 

The second: is that easily drawn and read at the relevant size? Especially with 02 being what is crossed out? That kind of sign would need more pixels to work well.

**Comment by PJB3005** [comment]
> > It feels like this issue fails to consider that the "Voxbox" and the accompanying Vox sign is implemented as an accessibility aid indicator for the species, and the comparison to real life race discrimination does not hold up in that context.
> 
> According to PJB above, the intention of the original source was to emulate early USA treatment of racial discrimination and segregation. Also, Vox aren't disabled.

This isn't really an important point to debate but implying that 4channers were thinking more specifically than "haha racism funny" is giving them too much credit tbh.

**Comment by EthanQix** [comment]
I think having the sign displaying the atmos type (i.e. N2) is much more neutral and has no unfortunate implications.

**Comment by APOCAMANDER** [comment]
I'll post a couple versions to debate on soon. I have never done a PR tho, so once we decide I might need help.

**Comment by Errant-4** [comment]
Quick version of nitrogen-colored diamond signs

![image](https://github.com/user-attachments/assets/408a23ef-73dd-4f5d-981c-d700a26e489c)

**Comment by engineer-pearl** [comment]
Now I see what you are thinking. If you sacrifice nitrogen colored for either neutral or yellow background, the red cross should pop more.

**Comment by Tyzemol** [comment]
alternative sign idea:
![image](https://github.com/user-attachments/assets/9d99c846-b8ac-4e88-a5b1-e76bbca1f509)

**Comment by Errant-4** [comment]
> alternative sign idea: 

There are not enough pixels to write all of that in a readable way

The N2 diamond kinda grew on me becausse with the black border, it not only is an N2 sign - it _literally depicts an enclosed area containing N2_

**Comment by APOCAMANDER** [comment]
![K5621](https://github.com/user-attachments/assets/37dd2075-5f3d-400c-8c7b-26cf169ecea8)
This is what a real one looks like. And I like the enclosed diamond idea. My signs are turning out bad. so I'll leave it to better spriters. not the kind of thing I normally make.

**Comment by EmoGarbage404** [comment]
![image](https://github.com/user-attachments/assets/fb56198e-7fd1-46b3-a61a-f01e61d0962c)

workshopped design with art directors

**Comment by engineer-pearl** [comment]
> ![K5621](https://private-user-images.githubusercontent.com/52253882/364534098-37dd2075-5f3d-400c-8c7b-26cf169ecea8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0ODEzNzcsIm5iZiI6MTcyNTQ4MTA3NywicGF0aCI6Ii81MjI1Mzg4Mi8zNjQ1MzQwOTgtMzdkZDIwNzUtNWYzZC00MDBjLThjN2ItMjZjZjE2OWVjZWE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDIwMTc1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5MGNmN2E2YmEyNzUzYjc0OGNlZjI1MjA3YjM3ZGJlNjAwMTg0NzgxZWQ1ZjJiNjVlNjY3NjEwZjQxMjA0MWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.idvcv22p2uV_DYWmkJiat_mJTW4YSr5HhdkPHP8sqWo) This is what a real one looks like. And I like the enclosed diamond idea. My signs are turning out bad. so I'll leave it to better spriters. not the kind of thing I normally make.

If you feel bad about it, I recommend looking at the rules for designing a flag. They may be helpful for designing sprites.

**Comment by Errant-4** [comment]
(alternate "n2 boxed in" with a blue trim, indicating the surrounding oxygen)

![image](https://github.com/user-attachments/assets/82a6db44-b9c0-4f59-a91c-91b6cae51254)

**Comment by engineer-pearl** [comment]
I wouldn't want to use the diamond if what you are describing is not a warning. The primary reason for this is that some people have done a lot of work to associate the yellow diamond with WARNING. 

If it's being used as "boxed in" rather than "warning" (as it would be in the 02 and NO O2 case) can the diamond be a square or other shape?
