### ISSUE TITLE
Diagonal grilles and clockwork diagonal grilles can only be built in one orientation

### ISSUE THREAD

**Issue by SBBurzmali** [space-wizards/space-station-14#31868]
## Description
Whenever you place the metal rods to complete a diagonal grille or clockwork diagonal grille, the grille will orient to the "default" position with edges down and to the right.

**Reproduction**
Open the construction menu
Select diagonal grille
Clock the construction ghost button
Rotate the ghost between one and three times
Place the ghost on a valid tile
Complete the construction by adding two metal rods to the ghost.

**Additional context**
Looking at the file Resources/Prototypes/Recipes/Construction/Graphs/structures/grille_diagonal.yml it looks like the parameter southRotation is set to true, if my understanding of the construction system is correct, this will override the ghost position and reset the angle of the constructed diagonal grille to zero at completion.

**Comment by dvir001** [comment]
Same issue that was fixed at https://github.com/space-wizards/space-station-14/pull/29687 probably.

**Comment by SBBurzmali** [comment]
Look like I missed #31627, you can close this as a duplicate, I search for "grille" not "grill".
