### ISSUE TITLE
Arrivals FTL deletes AI

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#31860]
## Description

When arrivals FTLs directly on the AI eye, the eye gets deleted forever and you get teleported back to your core where you're basically immobilised (radio, actions and typing still works).

**Reproduction**

- be roundstart ai
- go to arrivals with the ai just below it before it FTLs (you can see the blue circles)
- when arrivals deletes your ai also deletes so now your core is your main body

**Screenshots**

What it looks like after it happens:

![image](https://github.com/user-attachments/assets/ba9fef23-89fc-432e-bfd5-ef8ed54ffa0e)

**Comment by ScarKy0** [comment]
This and singulo eating AI Eye are my favourite bugs of all time

**Comment by Dragonjspider** [comment]
At this point maybe a failsafe to check if an eye is active would be better? so then when there isn't it could just make a new one on the AI? Then again maybe not, there's probably not many edge cases this kind of thing can happen with anyway.

**Comment by dan6798** [comment]
I'd like to add, that this also might prevent rejoining. (Had this happen to me.) Just straight up says connected upon rejoin but can hear game audio and such.

**Comment by dan6798** [comment]
Just letting you know, I fixed it by typing ghost in console chat. Among other things like a certain children's story.

**Comment by slarticodefast** [comment]
Fixed by #32094
