### ISSUE TITLE
Box Station does not have ai upload

### ISSUE THREAD

**Issue by nymhole** [space-wizards/space-station-14#31877]
## Description
Box station does not have AI upload.

**Screenshots**
![image_2024-09-05_173554538](https://github.com/user-attachments/assets/66f48c33-628b-4243-b459-0d7f7e890be7)
this is ss14 Box Station bridge tech vault-ish type place, the placeholder for ai upload.

**Additional context**
![Screenshot 2024-09-05 173128](https://github.com/user-attachments/assets/5d07fefd-248f-4500-9c4a-b43925621ce7)
this is ss13 Box Station ai upload

**Comment by Scribbles0** [comment]
fixed in #32608
