### ISSUE TITLE
Whitlist issues with autolathe materials (seismic charge uncraftable)

### ISSUE THREAD

**Issue by iaada** [space-wizards/space-station-14#31887]
## Description
Silver can not be feed into the autolathe, making seismic charges impossible to craft. Despite `Whitelist` inside of `MaterialStorageComponent` allowing the Ingot tag, the separate `MaterialWhiteList` inside the same component does not include silver, likely causing the issue.

Additionally sheets of reinforced glass are uncraftable in the autolathe due to the inability to insert coal. The autolathe recipe for reinforced glass probably shouldn't require coal, since it's there for convenience over hand crafting.

**Reproduction**
Try to put coal or silver in the lathe.

**Comment by deltanedas** [comment]
coal is a tag issue, silver is an issue of checking (emag) static/dynamic recipes but not all blueprints

**Comment by iaada** [comment]
still untriaged and still in the game

**Comment by Zylofan** [comment]
I'll take a crack at this.
