### ISSUE TITLE
Zombies have nearly no zombie blood

### ISSUE THREAD

**Issue by thebadman4662** [space-wizards/space-station-14#31912]
## Description
Round 65014 on Levi, could not make any reasonable amount of ambuzol as one zombie body full of blood have barely any zombie blood in it.

**Comment by EthanQix** [comment]
Zombies tend to die violently so they bleed a lot before reaching chem. As a side note, you can replenish even a dead zombie blood with a bloodpack.

**Comment by thebadman4662** [comment]
> Zombies tend to die violently so they bleed a lot before reaching chem. As a side note, you can replenish even a dead zombie blood with a bloodpack.

No it was literally a full zombie killed with heat. I drained them directly into dylo-ammonia jug mix cause medbay was rushed, later when it was safer I tested multiple zombies and warned crew that zombies do not contain zombie blood so they REALLY do not want to get infected.

**Comment by Plykiya** [comment]
reproduced, you only get a decent amount of zombie blood by using blood packs on zombies...
