### ISSUE TITLE
welding fuel/whatever firestack increasing is broken

### ISSUE THREAD

**Issue by Ilya246** [space-wizards/space-station-14#31927]
## Description
splashing or drinking welding fuel/napalm/whatever increases your firestacks, but will extinguish you if you're on fire

you do burn for longer if you get set on fire afterward though

**Reproduction**
1. set yourself on fire
2. inject yourself with welding fuel or splash some on yourself
3. no more fire
4. set yourself on fire again
5. big fire

**Comment by Dutch-VanDerLinde** [comment]
Dupe https://github.com/space-wizards/space-station-14/issues/28445

**Comment by Ilya246** [comment]
duplicate
