### ISSUE TITLE
No job alt name preferences

### ISSUE THREAD

**Issue by Peptide90** [space-wizards/space-station-14#3195]
## Description
Not an issue or urgent.

We need job name preferences on character / lobby screen to add more depth to the available roles without creating additional jobs to select. Examples below pulled from paradise station.

E.g. 
medical doctor > nurse, surgeon

Station engineer > maintenance technician,  Engine tech, electrician.

Atmos tech > life support specialist

Scientist > xenobiologist,  Plasma / photon researcher, xenoarchaeologist, anomalist, chemical researcher

Detective > forensic technician

Chef > cook, culinary artist, butcher
Botanist > hydroponocist, botanical researcher
Janitor > custodial technician
Librarian > journalist

List is not definitive and whether these are all alt names or some are jobs is upto you.

**Comment by SweptWasTaken** [comment]
Uh, I think these are all dependent on content being added and furthermore I don't like the renaming of some of this stuff purely because I think it makes the game more complicated for little reason.
