### ISSUE TITLE
Arrivals shuttles delete surrounding walls and docking ports upon docking.

### ISSUE THREAD

**Issue by Merrokitsune** [space-wizards/space-station-14#31979]
## Description

The arrivals shuttle deletes the surrounding walls and docking ports upon docking.
Might be the same with the evacuation shuttle, though I am not sure.

**Reproduction**

Just watch the arrivals shuttle arrive to a docking port and see.

**Screenshots**

![Screenshot 2024-09-08 215603](https://github.com/user-attachments/assets/a25c8aa5-52f9-4101-90d7-339efcd14368)

https://github.com/user-attachments/assets/27321a6b-59ae-4c59-b97e-7849a0389b45

**Additional context**

I suspect it has something to do with how shuttles clear obstacles upon arrival to the destination.
I was told by someone that this is related to how "FTL now uses NoFTLComponent and FTLSmashImmuneComponent instead of relying upon other components for dumping entities upon starting FTL and avoiding crushing them upon arrival respectively."

**Comment by 0x6273** [comment]
This was caused by https://github.com/space-wizards/space-station-14/pull/31952 and there's a PR up that fixes it: https://github.com/space-wizards/space-station-14/pull/31968

**Comment by Merrokitsune** [comment]
Okay, thanks.
