### ISSUE TITLE
auto whitelists need to be reverted

### ISSUE THREAD

**Issue by Everturning** [space-wizards/space-station-14#31988]
auto whitelists need to be reverted. salamander has too many players streaming in from LRP that dont know what EORG is, or dont listen to spacelaw, or such like that. it might have reduced work for discord staff, but the amount of nonantags that eorg when that screen pops up is too much. not to mention how LRP players are, well, acting LRP because "oh last round was pretty LRP" (an actual reason i heard)

it just isnt good.

**Comment by lzk228** [comment]
wait, so the players get auto whitelisted on salamander after playing a lot on other wizden servers??

**Comment by Dutch-VanDerLinde** [comment]
salamander needs to have its pop lowered because its just the overflow server rn

**Comment by Nairodian** [comment]
Auto whitelisted isn't even turned on for Wizard's Den. All that you described has nothing to do with auto whitelists.
