### ISSUE TITLE
No Way To Get A New Salvage Magnet IC

### ISSUE THREAD

**Issue by Kezu02** [space-wizards/space-station-14#31994]
## Description

Whenever a meteor blows it up and the board's gone, they'd need an admin to spawn a new one. Maybe either make the board indestructible or salv can somehow buy/craft a new one that gets locked when one already exists?

**Comment by EmoGarbage404** [comment]
magnet pulls are tied to the station so technically having multiple isn't really an issue. just for reference for whoever tackles this.
