### ISSUE TITLE
Late join crew spawning on nukie planet

### ISSUE THREAD

**Issue by LeIronGoat** [space-wizards/space-station-14#32017]
## Description
Join round, spawn on nukie planet. During nuke-ops.

**Reproduction**
Choose job late join. Spawn on nukie planet. Have not had chance to attempt reproduction for other factors.

**Screenshots**
![image](https://github.com/user-attachments/assets/2281e2b8-87ba-4070-a3c9-e07e0dc8ccee)

**Additional context**
Saw chemist, engineering, clown, security...all I did was was join round a moment after it started

Map: Cog
Round: 65297
Server: Leviathan

**Comment by TurboTrackerss14** [comment]
For any people willing to investigate who have access to logs. round ID was 65297, station was cog.

**Comment by LeIronGoat** [comment]
> For any people willing to investigate who have access to logs. round ID was 65297, station was cog.

Thanks, was just grabbing that.

**Comment by muburu** [comment]
this is easily bug of the year by a longshot

**Comment by LeIronGoat** [comment]
Assumed fix by Revert "Fix spawnpref" #32018
