### ISSUE TITLE
Planetside Arrivals screen no longer shows time for shuttle arrival or departure

### ISSUE THREAD

**Issue by JIPDawg** [space-wizards/space-station-14#32027]
## Description

The screens at arrivals should show the arrival time of the shuttle and how long till departure.

**Reproduction**

Spawn in at arrivals
**Screenshots**

![image](https://github.com/user-attachments/assets/2f02fd3e-fb68-4062-963a-f97bf6b4a0fc)

**Additional context**

**Comment by slarticodefast** [comment]
I think this was broken in #31823 where the screen network channel was set to wireless
@ScarKy0

**Comment by ScarKy0** [comment]
@slarticodefast 
Yup realized this as soon as I left for school
Will fix when Im home
