### ISSUE TITLE
Portals/Gateways can no longer be right clicked

### ISSUE THREAD

**Issue by LordEclipse** [space-wizards/space-station-14#32038]
## Description
You can't open the context menu of portals of any kind. They are unable to be traveled through as a ghost, and you cannot figure out their EID to VV them as an admin.

**Reproduction**
Place portal, attempt right click

**Screenshots**

https://github.com/user-attachments/assets/a04d181b-9fce-48c2-a96d-2a4c6266e248

**Additional context**
Gateways themselves are also unusable.

**Comment by leonidussaks** [comment]
you can use alt+click combination btw

this also concerns prototypes with all fixtures  have `hard: false` like ChemistryHotplate, SpiderWeb, etc.

**Comment by deltanedas** [comment]
examine shouldnt even use fixtures like this it broke **so many** things
