### ISSUE TITLE
Your implementation of LINDA has a broken comparison check

### ISSUE THREAD

**Issue by LemonInTheDark** [space-wizards/space-station-14#32053]
## Description

`compare()` (in /tg/ code) and `CompareExchange()` (in ss14) as they apply to linda have been broken for a while.
Because they do not account for archived moles they introduce order of operations issues to gas sharing, meaning some turfs that SHOULD be made active and gain gas just... don't. This makes gas flow technically directional.

See the second issue described in https://github.com/tgstation/tgstation/pull/86602

**Additional context**
From a brief check this may be mildly annoying since you seem to have moved archive moles (and temperature) off the gasmixture in the name of cleanly supporting multiple systems.

**Comment by mirrorcult** [comment]
wonky

**Comment by LemonInTheDark** [comment]
swinging by for my biyearly "something is wrong with linda" post, hope you're all well

**Comment by metalgearsloth** [comment]
Time to tell all 0 of our active atmos coders.
