### ISSUE TITLE
banana peel stunlocks when dragged over repeatedly (stun)

### ISSUE THREAD

**Issue by Peptide90** [space-wizards/space-station-14#3210]
[Bug]
## Description

Reported by @Herbert Falsevor#3037 on discord.
Haven't self verified.

Apparently dragging someone over a banana peel constantly stunlocks them?

Maybe banana peel should take damage when walked on so that after 2 to 3 slips / steps it destroys itself into a mess for janitor to clean up.
**Screenshots**

**Additional context**

**Comment by AJCM-git** [comment]
This is certainly not the case
