### ISSUE TITLE
You can no longer right click things inside of a container to select them

### ISSUE THREAD

**Issue by Plykiya** [space-wizards/space-station-14#32116]
## Description

1. Put item in locker
2. Put yourself in the locker
3. Close the locker
4. Right click the locker
5. Be unable to select anything

**Reproduction**

**Screenshots**

**Additional context**

**Comment by Plykiya** [comment]
https://github.com/space-wizards/space-station-14/pull/31792 possibly related?

**Comment by ElectroJr** [comment]
At a glance, yeah that's probably it. I think it also prevents being able to use the context menu debug commands to examine contained entities (i.e., right click player to see their organs).

It should probable be reverted. And we need to figure out whatever engine change caused this? https://github.com/space-wizards/space-station-14/issues/31756#issuecomment-2324990035

**Comment by metalgearsloth** [comment]
If it does get reverted then remove AI job in the interim as it will break.

**Comment by ElectroJr** [comment]
Why does the AI job the context menu to exclude sensors?

**Comment by deltanedas** [comment]
should just list contents of a container if you are inside it, regardless of where you right clicked
