### ISSUE TITLE
Left click interactions don't work sometimes

### ISSUE THREAD

**Issue by ike709** [space-wizards/space-station-14#3212]
I latejoined on EUW2 and left click interactions didn't work at all. Couldn't open airlocks or any machine UIs unless I right clicked them first then left clicked their name in the popup.

No, I was not in disarm mode. I tried toggling it several times. I also tried resetting my keybinds. I also tried relogging. Didn't work.

I latejoined on EUW1 and it worked fine. Went back to EUW2, still didn't work.

**Comment by ike709** [comment]
Someone in chat also reported issues with interacting.

**Comment by ike709** [comment]
![image](https://user-images.githubusercontent.com/5714543/107887646-28fdba00-6ecd-11eb-9023-7f274121f795.png)

**Comment by DrSmugleaf** [comment]
Closing in favor of https://github.com/space-wizards/space-station-14/issues/3213
