### ISSUE TITLE
Reconnecting sometimes disables interactions

### ISSUE THREAD

**Issue by DrSmugleaf** [space-wizards/space-station-14#3213]
## Description
When reconnecting on one of the dedicated servers, picking up items directly by clicking on them, using the entity/tile spawner panels and opening lockers is broken. Using the pick up verb or clicking them in the right click context menu works just fine however. It was consistent until the servers updated, but I can't reproduce it anymore.
On every failed interaction, the server prints a warning on grafana.

**Screenshots**
For placing tiles:
```
DrSmugleaf tried to place at invalid coordinate EntId=c1340, X=-25.06, Y=5.47
DrSmugleaf tried to place at invalid coordinate EntId=c1340, X=-24.32, Y=5.49
DrSmugleaf tried to place at invalid coordinate EntId=c1340, X=-23.99, Y=8.08
DrSmugleaf tried to place at invalid coordinate EntId=c1340, X=-23.99, Y=8.08
DrSmugleaf tried to place at invalid coordinate EntId=c1340, X=-24.02, Y=8.69
DrSmugleaf tried to place at invalid coordinate EntId=c1340, X=-24.02, Y=8.72
DrSmugleaf tried to place at invalid coordinate EntId=c1340, X=-23.85, Y=8.86
```

![chrome_8IP45XfIWr](https://user-images.githubusercontent.com/10968691/107890363-f8dc0880-6f18-11eb-9107-30ddf779fafe.png)

For placing entities:

![chrome_IUWheLiWqj](https://user-images.githubusercontent.com/10968691/107890367-fd082600-6f18-11eb-9062-a35dfba69154.png)

**Additional context**
See also https://github.com/space-wizards/space-station-14/issues/3212
The issue was first reported on the 14th of February 2021 2PM UTC, after we did the first batch of commits that day.
It stopped being able to be reproduced by me or Vera after the servers restarted to update to the holiday month fix commit.
The coordinates are correct and is what the client is clicking on, but it is sending a client entity uid, which is the problem.
It does not seem related to input contexts or the item pickup animation.

<details>
<summary>The forbidden logs</summary>

```
Zumorica:asay "btw smug"
DrSmugleaf:asay "ye"
Zumorica:asay "I can't spawn anything"
DrSmugleaf:asay "wh"
Zumorica:asay "do you also have this issue"
```

```
DrSmugleaf tried to place at invalid coordinate EntId=c1340, X=-25.06, Y=5.47
DrSmugleaf tried to place at invalid coordinate EntId=c1340, X=-24.32, Y=5.49
DrSmugleaf tried to place at invalid coordinate EntId=c1340, X=-23.99, Y=8.08
DrSmugleaf tried to place at invalid coordinate EntId=c1340, X=-23.99, Y=8.08
DrSmugleaf tried to place at invalid coordinate EntId=c1340, X=-24.02, Y=8.69
DrSmugleaf tried to place at invalid coordinate EntId=c1340, X=-24.02, Y=8.72
DrSmugleaf tried to place at invalid coordinate EntId=c1340, X=-23.85, Y=8.86
```
</details>

**Comment by metalgearsloth** [comment]
Is it possible the client isn't sent the grid / map entity?

**Comment by metalgearsloth** [comment]
I think I may have debugged this:

When I pressed F3 there were 2 UI outlines showing up and these blocked interactions / interaction outline so it seems like something may not be getting cleaned up properly.

There's 2 things showing up for the UI highlight and both of these block interactions / outlining which may be the interaction issue people describe having.

![image](https://user-images.githubusercontent.com/31366439/108930863-be056d80-769a-11eb-90eb-afad20a719f5.png)

1 is ConstructionMenu and I forgot to get the other.

I think the main issue is UI stuff potentially not getting disposed of on round resets.

**Comment by Acruid** [comment]
The construction window should be fixed in https://github.com/space-wizards/space-station-14/commit/a9a336595a07383e86f1123355a6a55a59b84258.

**Comment by AJCM-git** [comment]
probably most certainly not an issue, i think
