### ISSUE TITLE
can't climb over objects while choking (oxygen damage)

### ISSUE THREAD

**Issue by Peptide90** [space-wizards/space-station-14#3214]
[BUG]
## Description

Reporter by @Herbert Falsevor#3037 on discord.
Have not verified myself.

"-Cant jump over obstacles while choking. it makes it impossible to escape vacuum"

**Comment by metalgearsloth** [comment]
Vaulting do_after should probably ignore userdamage OR DoAfter needs a damage threshold.

**Comment by AJCM-git** [comment]
Superseded by #5203
