### ISSUE TITLE
Hot Chocolate does not poison lizards

### ISSUE THREAD

**Issue by MissKay1994** [space-wizards/space-station-14#32142]
## Description
I learned today that chocolate, coffee, and tea all poison lizards if consumed. For whatever reason, despite it supposedly metabolizing into theobromite, apparently doesn't for lizards. I assume it's because lizards stomach type just can't metabolize chocolate, meaning they can infinitely drink hot chocolate without consequence

Edit: Additional testing has revealed they appear not to metabolize things into theobromite at all when drinking only one reagent

**Reproduction**
Examine the container of a reptilian and consume hot chocolate

**Screenshots**
![image](https://github.com/user-attachments/assets/a120efc8-b679-43df-9cbb-139ecee220b9)

**Comment by slarticodefast** [comment]
I gave it a test and it seems like the theobromine is correctly added the the lizard's bloodstream, but immediately metabolized as well, so it never reaches the 3u threshold needed to deal damage. To fix this the ReagentThreshold should be removed.
