### ISSUE TITLE
Reagent metabolism is broken

### ISSUE THREAD

**Issue by MissKay1994** [space-wizards/space-station-14#32146]
## Description
Drinking reagents that create another through metabolism does not work until you drink other reagents that metabolize into the same reagent. I found this bug because of [32142](https://github.com/space-wizards/space-station-14/issues/32142)

**Reproduction**
Consume as much hot chocolate as you want as a lizard. You can even drink a full 200u of it. It will never metabolize past the initial 0.05u of theobromine instead of metabolizing 0.05u per 1u of consumed hot chocolate/coffee/tea. It only starts metabolizing more theobromine when you drink say, coffee, after you drank tea or hot chocolate first.

**Video**
https://discord.com/channels/310555209753690112/310555209753690112/1284439127840002049

**Comment by thebadman4662** [comment]
Thats because those reagents never get queue assigned to them, they simply spawn inside container(stomach).

**Comment by MissKay1994** [comment]
> Thats because those reagents never get queue assigned to them, they simply spawn inside container(stomach).

So it's just never queuing the metabolism into theobromine? In the actual code it's supposed to when consumed and metabolized in the stomach make theobromite, but it never does.

Reagent code for coffee as an example:
![image](https://github.com/user-attachments/assets/b4b7e852-6230-436f-ab8f-7148b4347703)

You can see, that it's fully intended to make a lot of theobromine when consumed, but in the video in #development it just never does until you add a second reagent to your stomach, meaning it is indeed a bug

**Comment by thebadman4662** [comment]
> > Thats because those reagents never get queue assigned to them, they simply spawn inside container(stomach).
> 
> So it's just never queuing the metabolism into theobromine? In the actual code it's supposed to when consumed and metabolized in the stomach make theobromite, but it never does.
> 
> Reagent code for coffee as an example: ![image](https://private-user-images.githubusercontent.com/15877268/367546322-b4b7e852-6230-436f-ab8f-7148b4347703.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzODgxMDEsIm5iZiI6MTcyNjM4NzgwMSwicGF0aCI6Ii8xNTg3NzI2OC8zNjc1NDYzMjItYjRiN2U4NTItNjIzMC00MzZmLWFiOGYtNzE0OGI0MzQ3NzAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDA4MTAwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5YmM1NzZiNTdmMGNlZDNkZjI4ODdiMzM4ZDY4MzgwZmMxNWJiNmJjNTc0ZmU0M2VlYzIzMDdkODczZjFhNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A73St8uW_ZgjvEqhWXIk5OGoFXH7AVQ4iZsCBpX-gwA)
> 
> You can see, that it's fully intended to make a lot of theobromine when consumed, but in the video in #development it just never does until you add a second reagent to your stomach, meaning it is indeed a bug

Drinking and eating puts reagents into 20s queue in stomach CONTAINER.
After that they get put into bloodstream(if its not full, otherwise it just despawns) container where they are metaboilized by heart(medicine, narcotic, toxin)/stomach(food, drink)... or both which causes its own bugs https://github.com/space-wizards/space-station-14/issues/29393.

So if you drink/eat things and thru chemical reaction generate new chemicals in stomach container they never gets assigned 20s food queue and never leave it.
