### ISSUE TITLE
Plant produce spams ghost roles

### ISSUE THREAD

**Issue by slarticodefast** [space-wizards/space-station-14#32191]
## Description
#31163 refactored plant mutations
Before the plant holder became sentient, now the produce does, causing massive ghost role spam.
It should either be changed back to the plant holder or only a single produce item becoming sentient.
Also fix the description mentioning cognizine.

**Reproduction**
- mutate a sentient plant
- harvest the produce
- see how each harvested item becomes its own ghost role

**Screenshots**
![grafik](https://github.com/user-attachments/assets/ecd88506-41fe-41fb-a6d5-7c7bc8caf9d6)
![grafik](https://github.com/user-attachments/assets/1519f5b0-43b6-41a8-8602-8742a2bbfac9)

@drakewill-CRL

**Comment by lzk228** [comment]
bug of the year candidate?
