### ISSUE TITLE
reinforced glass can't me made on autolathe

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#32206]
it uses ore processor's recipe

![Screenshot_20240916_102706](https://github.com/user-attachments/assets/ac63602c-a77c-4227-be6f-fbca12850e02)

**Comment by Calecute** [comment]
I think this may have been introduced by https://github.com/space-wizards/space-station-14/pull/32069 .It seems the problem might be every machine uses the same recipes in Resources/Prototypes/Recipes/Lathes, if that's the case reinforced glass should only be available either in the ore processor or in the autolathe

**Comment by VlaDOS1408** [comment]
it doesn't work because you can't put coal in the autolight. And the recipe is the same. Write down which solution you would like to see and I will probably do it.
