### ISSUE TITLE
Seeds From Vendor Are Mutated

### ISSUE THREAD

**Issue by Kezu02** [space-wizards/space-station-14#32229]
## Description

Somehow, apple seeds directly from the seed vendor grew to have the slip and light mutations.

**Comment by JIPDawg** [comment]
Did a little bit of testing and wasn't able to reproduce in dev environment. Vended multiple different types of seeds planted all and all did not exhibit any mutations. 

Wondered if maybe the Hydro tray is keeping the mutagen but needs more testing as I wasn't able to reproduce any mutations after reusing a tray that was previously used to mutate  plant.

**Comment by slarticodefast** [comment]
Should be fixed by #32257
