### ISSUE TITLE
Red blood splitting itself in containers

### ISSUE THREAD

**Issue by thebadman4662** [space-wizards/space-station-14#32278]
## Description
So as usual some dumbo atmos blinded themselves and I needed to make some Ocu, handed them syringe to come back later with blood but got some of it off SSD myself in the end, when combined in chemmaster I had multiple stacks of same reagent

**Screenshots**
![obraz](https://github.com/user-attachments/assets/d1234ce9-622a-4273-a3fd-c80966941e29)
![obraz](https://github.com/user-attachments/assets/a3c2a58e-cd40-4582-bbd4-f9f80c9a59c8)

**Comment by deltanedas** [comment]
its not the same, they have different dna

**Comment by thebadman4662** [comment]
> its not the same, they have different dna

Only original things used to have DNA, did that change? But even then, shouldn't they simply get merged?

**Comment by deltanedas** [comment]
they do not or the information would be lost
