### ISSUE TITLE
remove intern roles from syndie kill objectives 

### ISSUE THREAD

**Issue by baddiePRO** [space-wizards/space-station-14#32271]
it's very sad to watch new players trying to learn the game ask why they just got blown up in deadchat, intern roles are locked after so long anyways so I don't see why this can't be a thing

**Comment by Everturning** [comment]
same bro I once was an atmos tech with only kill objs for interns so I ignored my objectives, I am in support

**Comment by lzk228** [comment]
> same bro I once was an atmos tech with only kill objs for interns so I ignored my objectives, I am in support

![image](https://github.com/user-attachments/assets/6e67989f-3aa6-4df8-b59b-82cf6025e5d0)

**Comment by slarticodefast** [comment]
We had a maintainer vote and decided this is not something we want. See the comment in #32288
