### ISSUE TITLE
The Drowsiness status effect should show an alert icon

### ISSUE THREAD

**Issue by slarticodefast** [space-wizards/space-station-14#32289]
## Description
This should help communicate the status effect better to the player and make it consistent with other status effects like mute, pacified or adrenaline. All that is needed is a good-looking icon for it.

**Comment by lzk228** [comment]
ah... drowsiness has visual effects, like drunk or blurred vision after welding
do they also require alert icons?

**Comment by slarticodefast** [comment]
good point, should probably be fine without
