### ISSUE TITLE
Capitalization

### ISSUE THREAD

**Issue by DamianX** [space-wizards/space-station-14#323]
Not talking about Patreon money, I'm talking about Jaden Smith's writing style.
![image](https://user-images.githubusercontent.com/6307265/64145354-bf910500-ce18-11e9-9d2a-1d7a9bedc48a.png)

see the parallel here:

![image](https://user-images.githubusercontent.com/6307265/64145399-e3ece180-ce18-11e9-9c7f-2b5f4cda4702.png)

Everything Is Using The Wrong Capitalization.
On good old BYOND capitalization was especially important because of the ubiquity of text macros. What's our stance on this?

Let's give proper nouns capital initials and improper nouns lowercase initials, yeah?

**Comment by AJCM-git** [comment]
Moved to the [HackMD](https://hackmd.io/Awj5TvdXTaOmhU2XZOsdQg), and is kinda addresed in #834. Should be closed now
