### ISSUE TITLE
admin ghost features / requests

### ISSUE THREAD

**Issue by Peptide90** [space-wizards/space-station-14#3230]
Creating this as a feature thread for admin ghost (aghost).
## features / issues

- [ ] Be able to teleport to ahelp locations as aghost by clicking on the name of the requester.

- [ ] Be able to interact with the map such as doors and containers as aghost (Like AI can).

**Comment by AJCM-git** [comment]
Second request is done

**Comment by Peptide90** [comment]
> Second request is done

Is it merged or does it require more permissions?

**Comment by Pangogie** [comment]
Trial admins can only open access-less doors.
