### ISSUE TITLE
Teleported away as a pAI into space

### ISSUE THREAD

**Issue by MarzieK** [space-wizards/space-station-14#32316]
## Description
I was the RD's pAI. Artifact needed to have medicinal chems spilled on it. RD put an epi pen into a beaker and threw the beaker at the arti. I was then teleported into space with an SSD version of the RD and later I was taken back to real life. 

**Reproduction**
Be a pAI for some sci person
Get sci person turned into a plant anom monster or similar (I believe they were the blue glowy one)
Get teleported away while they're the plant anom

**Evidence**

https://github.com/user-attachments/assets/930a7789-97d2-49ae-a770-fa71090196e9

**Additional Context**
Apparently, the RD had turned into a plant anom creature or something along those lines, therefore, I was teleported away.

**Comment by Golinth** [comment]
I think that this is because of how polymorphing currently works, your body (and all your items including pAIs) gets taken to the shadow realm while you turn into whatever creature.

**Comment by slarticodefast** [comment]
duplicate of #28781
