### ISSUE TITLE
If the AI has an APC UI open, nobody else can toggle the APC on

### ISSUE THREAD

**Issue by Plykiya** [space-wizards/space-station-14#32312]
## Description

Saw a round where the AI was holding people hostage in a room by bolting all the doors and then toggling the APC off while keeping the UI open so that they couldn't turn on power to unbolt the doors

**Reproduction**

**Screenshots**

**Additional context**

**Comment by Slava0135** [comment]
I don't even think its specific to AI, try opening APC when its already opened by another person
