### ISSUE TITLE
Voice mask speech style changer does not work

### ISSUE THREAD

**Issue by ilyamikcoder** [space-wizards/space-station-14#32351]
## Description
Only "None" speech style is selectable in a voice mask.

**Reproduction**

1. Put on a voice mask
2. Open it's voice changer menu
3. Try to change the style
4. Observe that it only has one style, "None"
5. Be sad

**Screenshots**
![изображение](https://github.com/user-attachments/assets/afa075d6-12ec-442c-8510-11538bd51966)

**Additional context**

**Comment by slarticodefast** [comment]
The refactor fixes this #30798
