### ISSUE TITLE
2 Issues with the omega map update in security.

### ISSUE THREAD

**Issue by BramvanZijp** [space-wizards/space-station-14#32406]
## Description
The new omega update is great, but does come with 2 oversights.
1. The left door in the HoS's office is a general command airlock instead of a HoS airlock, so the HoS cannot bolt it.
2. The armory has 2 wardens hardsuit lockers, instead of 1 warden hardsuit locker and one sec hardsuit locker.
Bonus. There is no implanter crate in sec roundstart, something all other maps do come with.

**Reproduction**
Load into omega and run into the issues above.

**Screenshots**
![image](https://github.com/user-attachments/assets/c2c551cf-ab5e-4259-9eca-4fcc8edbddfa)

**Additional context**
Not neccesary.

**Comment by spanky-spanky** [comment]
I’ll address these today, I don’t recall touching security in my update but I could have made a mistake. May make a minor armory expansion to comfortably fit an implant crate.

**Comment by BramvanZijp** [comment]
> I’ll address these today, I don’t recall touching security in my update but I could have made a mistake. May make a minor armory expansion to comfortably fit an implant crate.

Omega armory in general just really needs a slight expansion

**Comment by UbaserB** [comment]
ah wait nvm it got fixed
