### ISSUE TITLE
Items hidden by hacking in vending machines are inaccessable. 

### ISSUE THREAD

**Issue by Golinth** [space-wizards/space-station-14#32421]
## Description

Cutting the manager wire on a vending machine normally shows a secret hidden item that is either contra, harder to obtain, or silly. This was recently broken, and cutting the manager wire does nothing unless the machine is emagged afterward.

**Reproduction**

1. Spawn a YouTool (or any other vending machine with hidden items)
2. Cut the MNGR wire
3. Check vending machine contents, see that nothing has changed. 

**Additional context**

Caused by #32376 - tested locally with commit reverted and the hacks function normally. 

Emagging vending machines works fine, and even updates the UI to show the hacked item if the wire was cut before the machine was emagged.

**Comment by goet** [comment]
Just to be clear, in vending machines emagged and hacked inventories are completely different things, one does not give you access to the other. The hacked items never showing up is a bug though.

Emagging probably should give you both? I could easily add this to the fix but from the codebase it looks like this is intentional.

**Comment by Golinth** [comment]
> Just to be clear, in vending machines emagged and hacked inventories are completely different things, one does not give you access to the other. The hacked items never showing up is a bug though.
> 
> Emagging probably should give you both? I could easily add this to the fix but from the codebase it looks like this is intentional.

Yeah, I mentioned that emag works fine. It updates the UI to allow the hacked item to show up, if the MNGR wire was cut before the emagging took place.

**Comment by Golinth** [comment]
> > Just to be clear, in vending machines emagged and hacked inventories are completely different things, one does not give you access to the other. The hacked items never showing up is a bug though.
> > Emagging probably should give you both? I could easily add this to the fix but from the codebase it looks like this is intentional.
> 
> Yeah, I mentioned that emag works fine. It updates the UI to allow the hacked item to show up, if the MNGR wire was cut before the emagging took place. Never implied that they were the same thing.

**Comment by goet** [comment]
My bad, this was new information for me so I read the issue with that assumption.
