### ISSUE TITLE
Torch is battery powered

### ISSUE THREAD

**Issue by Visne** [space-wizards/space-station-14#3243]
## Description
The torch makes clicky noises when turned on and off, and when it's empty it says "dead cell!".

**Comment by SweptWasTaken** [comment]
Cool?

**Comment by mirrorcult** [comment]
im pretty sure he means these torches
![image](https://user-images.githubusercontent.com/19853115/108003938-8cf9ae80-6fb1-11eb-9bdf-9d20b7695284.png)
which are. uh. fire. they're fire-powered

**Comment by Visne** [comment]
Yeah I meant actual wooden torches. Who came up with using 'torch' for electronic lighting anyways?

**Comment by mirrorcult** [comment]
the best solution to this is to just give them a description like "Now with Nanotrasen© brand Realistik-Fire® technology"

**Comment by Visne** [comment]
I think you mean 'easiest' solution.

**Comment by SweptWasTaken** [comment]
> 
> 
> Yeah I meant actual wooden torches. Who came up with using 'torch' for electronic lighting anyways?

Br*tish people
