### ISSUE TITLE
AI can bolt/unbolt unpowered airlocks

### ISSUE THREAD

**Issue by AsnDen** [space-wizards/space-station-14#32449]
## Description
AI can bolt/unbolt unpowered airlocks. I guess it shouldn't.

**Reproduction**
Bolt an airlock
Turn off power
Unbolt the airlock
Turn on power
You can open an airlock

(Same for bolting)

**Screenshots**

https://github.com/user-attachments/assets/1be3a0cf-6919-4968-ab35-2ec85ec08bec

**Comment by ScarKy0** [comment]
Fixed in #32012
Whenever that gets merged

**Comment by AsnDen** [comment]
Solved
