### ISSUE TITLE
Bug with held animated sprites. 

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#3245]
## Description

Definitely related to #1144 

Reproduce: 

1. Spawn torch
2. Turn on, turn off, turn back on
3. Animation on Held sprite should have stopped

**Screenshots**

![2021-02-15_16-45-38](https://user-images.githubusercontent.com/49448379/108005330-4ecfaf80-6ff0-11eb-88a3-10caeaf0a3ad.gif)

**Additional context**

**Comment by AJCM-git** [comment]
Not the case anymore
