### ISSUE TITLE
Trying to drag actions does not work, and when you try to click down to drag, the actions are triggered.

### ISSUE THREAD

**Issue by baddiePRO** [space-wizards/space-station-14#32476]
## Description
when you try to drag a button off of the action bar, it activates the action on button down, and won't let you drag the button around/off the bar.

**Reproduction**
-try to drag the action button off the bar
-does nothing, try again
-get acidified because you pushed the button twice trying to drag it
-repeat 3x and have 3 nukies die before reaching the station

**Additional context**
pretty sure it's related to #31821

**Comment by thebadman4662** [comment]
Dupe. https://github.com/space-wizards/space-station-14/issues/32462

**Comment by slarticodefast** [comment]
closing as duplicate
