### ISSUE TITLE
Station anchors allow the station to FTL

### ISSUE THREAD

**Issue by ImWeax** [space-wizards/space-station-14#32470]
## Description

Normally you cannot FTL the station. When you put a station anchor, thruster, and shuttle console on it, you can FTL it.

**Reproduction**

Was able to reproduce this using the Centcom map, attempted to FTL with just a console + thruster, no go. Added station anchor (ON), FTL works.

**Screenshots**

**Additional context**

FTLing station bad (round removes anyone outside, does not bring singulo/tesla with it)

**Comment by MilenVolf** [comment]
Pretty sure it was fixed by #32558
