### ISSUE TITLE
More character preference shennanigans

### ISSUE THREAD

**Issue by PotatOverlord** [space-wizards/space-station-14#32491]
## Description

I decided to observe on mander, but I couldn't see my character preferences, but I had heard that the long loading issue had been fixed so I figured it was a problem on my end, so I decided to observe anyway. When I loaded in, I couldn't see walls, people, objects, wires, etc., just the floor tiles and the hull but I could see people's chatboxes and lights and hear music. I took smile's ghost role to see if that could fix it but that didn't work either (see screenshots 3-5)
**Reproduction**

1. Observe before the image of your character is loaded but the name and age are there
2. Enjoy
**Screenshots**

![20240927191849_1](https://github.com/user-attachments/assets/8cde0778-2d66-4da0-b706-9bbb5c6310a9)
![20240927191908_1](https://github.com/user-attachments/assets/8c1d586e-a236-4c24-b368-259c0e19f375)
![20240927191920_1](https://github.com/user-attachments/assets/8368dd44-b163-4d1e-ba05-ad255172ef08)
![20240927191930_1](https://github.com/user-attachments/assets/1d054862-2730-476f-bead-9ea714b39735)
![20240927191938_1](https://github.com/user-attachments/assets/069605b8-c009-4803-a63e-60e9085f35ff)

**Additional context**

I think this is a different issue than joining when your preferences aren't loaded at all and being sent to the shadow realm but it might be the same thing idk

**Comment by lzk228** [comment]
bug with loading textures, probably because memory/videomemory (or what part is responsible for that) is too bloated

**Comment by PotatOverlord** [comment]
ah, that makes sense. I have vscode open in the background which might be leeching off it.

**Comment by PJB3005** [comment]
Yeah I doubt this has anything to do with character preferences.
