### ISSUE TITLE
Execution doesn't use identity

### ISSUE THREAD

**Issue by bruhmogus** [space-wizards/space-station-14#32509]
It uses the name of the character as opposed to their identity.

![20240928144922_1](https://github.com/user-attachments/assets/136db2bc-09db-4173-827d-fc4edea41196)

![20240928144924_1](https://github.com/user-attachments/assets/bde543fa-c267-45d3-9228-8d4fda4b4e1c)

**Comment by lzk228** [comment]
dupe

**Comment by bruhmogus** [comment]
of WHAT? i searched for identity and execution

**Comment by lzk228** [comment]
oh sorry i was thinking about wielding

**Comment by bruhmogus** [comment]
oh aight
