### ISSUE TITLE
The slippery plant mutation affects the plantholder instead of the produce

### ISSUE THREAD

**Issue by slarticodefast** [space-wizards/space-station-14#32529]
## Description
It used to be the harvested produce that was affected by the mutation.
Must have happened unintentionally in #31163
Also the slippery effect stays even if the plant is removed from the plantholder.

**Reproduction**
- Plant something in the plantholder.
- Add mutagen to the plantholder until you get the slippery mutation.
- The plantholder is now slippery.
- Remove the plant.
- The plantholder still has the SlipperyComponent.

**Screenshots**
![Screenshot (297)](https://github.com/user-attachments/assets/83b450df-289c-4fea-bc54-19c1d5d3ee86)

@drakewill-CRL

**Comment by slarticodefast** [comment]
The same thing seems to happen with the bioluminiscent mutation: The plantholder is affected as well and keeps glowing after the plant is removed.
![grafik](https://github.com/user-attachments/assets/1e5edd8a-bb29-4b66-aa38-aef117cfcba1)

**Comment by drakewill-CRL** [comment]
Right now, I don't think theres a way to undo EntityEffects directly, and they get applied to the tray because the tray is the plant code-wise.

The correct fix for this is to implement #31941, which will apply the effect to the plant and it will go away as part of the plant's removal as expected.

**Comment by slarticodefast** [comment]
Yeah, but they should be only applied to the produce in the first place, not on the tray.
