### ISSUE TITLE
Doors get held open by things that should not effect them.

### ISSUE THREAD

**Issue by BramvanZijp** [space-wizards/space-station-14#32544]
## Description
There are certain physics things that can prevent a door from closing that really shouldn't do that, like the invisible physics sphere around a mounted flasher used to detect if anyone is nearby and thus if it should trigger.

**Reproduction**
Load into a map like packed.
Open the security main airlocks.
Realise that the top right one cannot be closed through any means (jaws, crowbar, ai, normal close, etc.)
Try everything to fix it, replacing the door, removing and replacing the entire tile and then the door, to no avail.
Realise much later on that the invisible physics sphere around the portable flasher was responsible for holding it open.

**Screenshots**
![image](https://github.com/user-attachments/assets/917566f9-5d8c-4c36-b9c3-f02fdde48b47)
![image](https://github.com/user-attachments/assets/86740378-fe6f-441c-816b-6cb3b498b3b1)
Sidenote: I tried a bit to fix it, but I'll just issue it for now and then maybe (probably not) look into it later.

**Additional context**
Problem started happening after #32483.
The issue, now that the cause is identified, can be solved midround by just getting rid of portable flashers near doors, though that is a bit of an annoyance to do every time.

**Comment by slarticodefast** [comment]
fixed by #32591
