### ISSUE TITLE
Cap gun cartrigde does not have a texture

### ISSUE THREAD

**Issue by Visne** [space-wizards/space-station-14#3254]
![image](https://user-images.githubusercontent.com/39844191/108075365-9135d280-706a-11eb-9489-5231c3924a36.png)

**Comment by Visne** [comment]
![image](https://user-images.githubusercontent.com/39844191/108075557-ccd09c80-706a-11eb-9b2f-ab6e7eeb6c2b.png)
This is probably related.

**Comment by Peptide90** [comment]
Can't see anything wrong with `Resources/Textures/Objects/Consumable/Trash/ash.rsi/meta.json` other than it's formatted differently to most other .json files (one line as opposed to multiline).

Also can't find a texture for cap cartridges in TG or cev eris icons so might need created unless @SweptWasTaken has some ideas?

Reformatted the Json below not that it should matter:
`{
  "version": 1,
  "size": {
    "x": 32,
    "y": 32
  },
  "license": "CC-BY-SA-3.0",
  "copyright": "https://github.com/discordia-space/CEV-Eris/raw/f7aa28fd4b4d0386c3393d829681ebca526f1d2d/icons/obj/trash.dmi",
  "states": [
    {
      "name": "icon"
    },`
