### ISSUE TITLE
Marathon dorms spawn easily wall people in.

### ISSUE THREAD

**Issue by thebadman4662** [space-wizards/space-station-14#32595]
**Screenshots**
![obraz](https://github.com/user-attachments/assets/2f95b2ef-3fe5-4dc1-811d-615c0d8ede82)
![obraz](https://github.com/user-attachments/assets/7b2b43ba-741e-4c6e-a324-bf7b913303da)

**Comment by SaphireLattice** [comment]
Honestly I feel like this isn't an issue with map but with pods. They really should dump people out in "front" of them...

**Comment by Emisse** [comment]
people should probably just spawn on the center of the tile the entity is on

**Comment by lzk228** [comment]
they do spawn on the center, but somehow cryo structure becomes hard and people can't go through it
