### ISSUE TITLE
Discord activity is wrong

### ISSUE THREAD

**Issue by Callmore** [space-wizards/space-station-14#32613]
## Description

Max players is stuck at zero, and the time played seems to reset whenever someone joins/leaves

**Reproduction**

i guess just go play ss14 and check discord

**Screenshots**

![image](https://github.com/user-attachments/assets/153eee25-6ba2-458e-8f58-99a6f510d62d)

**Comment by metalgearsloth** [comment]
It uses engine max players which servers almost never config. Just needs an event if content wishes to override but pre sure there's an open issue for it.

**Comment by Callmore** [comment]
oh
