### ISSUE TITLE
Voting suggestions

### ISSUE THREAD

**Issue by Injazz** [space-wizards/space-station-14#3265]
## Description
1.  Public preset "End the Shift" instead of Restart Round,
2.  Votes should have quorum requirements
3.  Cooldown for votes
4. Hide button on vote notification window (which minimizes the window into button)
5. Preference to minimize ALL vote notifications into a top bar button (see screenshot)

## Screenshots
![image](https://user-images.githubusercontent.com/43905364/108114477-a9cdd900-70ba-11eb-9d77-fa9e7a59fcbb.png)

**Comment by Peptide90** [comment]
End the shift should be initiate a crew transfer so shuttle in 5 / 10 mins after vote ends +2 for shuttle leaving. There should be a cool down from round start for say 30 minutes before it can be voted (obviously anything time based is configurable), 

This then obviously leads into shift scoring for station integrity, cleanliness and antag scoring but that's something else.
