### ISSUE TITLE
AI chip can only be created with two stacks of one capacitor, rather that one stack of two

### ISSUE THREAD

**Issue by ARMOKS** [space-wizards/space-station-14#32671]
Title
This works:
![image](https://github.com/user-attachments/assets/2c0014db-e2d4-446c-a2e3-929d447ebced)

This does not:
![image](https://github.com/user-attachments/assets/d14e6118-b04b-4714-b05f-dec0fd1f56cf)

**Comment by lzk228** [comment]
i think it's a dupe issue

**Comment by Ilya246** [comment]
duplicate i already reported

**Comment by ARMOKS** [comment]
Dupe issue
