### ISSUE TITLE
Ghost roles menu should be collapsible

### ISSUE THREAD

**Issue by flashgnash** [space-wizards/space-station-14#32695]
## Description

When there are many of the same type of ghost role present, it can take up a lot of space and prevent people from seeing others further down the list

Since there are already headers for each kind of ghost role, a solution to this would be to have these sections be collapsible, and start collapsed if they contain more than 2 or 3 items. There could also be a button on this header that will enter the player for a random role raffle for any of the duplicates of that type.

**Reproduction**

Open the ghost roles menu when there are 500 sentient hydroponics trays available

**Screenshots**

![image](https://github.com/user-attachments/assets/9f701e3e-6d68-4112-b7ea-4e663d617f81)

**Additional context**

These two issues would be resolved by having a collapsible ghost role UI element

https://github.com/space-wizards/space-station-14/issues/20825

https://github.com/space-wizards/space-station-14/issues/31424

**Comment by MilenVolf** [comment]
I'm on it. In the process of implementing it

![image](https://github.com/user-attachments/assets/294d86bc-6a05-4416-867e-661ea595a62b)
