### ISSUE TITLE
Clownspider corpses can open bolted doors

### ISSUE THREAD

**Issue by eoineoineoin** [space-wizards/space-station-14#32699]
## Description

Clownspider corpses have a PryingComponent with `Force` and `PryPowered` both true, making them more powerful than a jaws of life.

Same is true for the corpses of regular spiders, zombies, and xenos.

**Reproduction**

Grab a corpse and click on the door you want to access. 

**Screenshots**

https://github.com/user-attachments/assets/a68aabf6-5aad-4f57-ad9e-e9030fe283c4

**Additional context**

**Comment by lzk228** [comment]
dupe of https://github.com/space-wizards/space-station-14/issues/30157

**Comment by eoineoineoin** [comment]
Yup, didn't see that in a search. Thanks
