### ISSUE TITLE
Pocket fire extinguisher description syntax error

### ISSUE THREAD

**Issue by ThatGuyUSA** [space-wizards/space-station-14#32708]
## Description
The description of the pocket fire extinguisher has a spelling error.

**Reproduction**
Read the description of it!!

**Screenshots**
![image](https://github.com/user-attachments/assets/f9bdf7a0-116a-4cb6-be8a-3c536a39df31)

**Additional context**
It should be 'than' not 'then', because it's comparing itself.

**Comment by beck-thompson** [comment]
@slarticodefast finally actually a beginner friendly issue!

**Comment by slarticodefast** [comment]
The easy ones always get done immediately though 😆
