### ISSUE TITLE
AI action capitalisation mistake in the description

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#32709]
## Description

Interface is only capitalised for the Station Records Interface in the action description.

**Screenshots**

![image](https://github.com/user-attachments/assets/ba00eeee-7010-455d-9ed7-e13690468ce4)

**Comment by scrivoy** [comment]
Hello,

I'd like to take on this issue. I'm confident I can get it done, though I'm still relatively new to this. I'm looking forward to learning more as I work through it, and any pointers would be really helpful!

I believe I've found the file related to these descriptions in the code:
`space-station-14/Resources/Prototypes/Entities/Mobs/Player/admin_ghost.yml.`
Am I on the right track?

Thanks in advance!

**Comment by lzk228** [comment]
> Am I on the right track?

yes, it's
https://github.com/space-wizards/space-station-14/blob/bc6467674752db3199cae15fed83ad1da2ca3cf5/Resources/Prototypes/Entities/Mobs/Player/admin_ghost.yml#L159

**Comment by scrivoy** [comment]
okay, thanks. I'll have a look on it later today.

cheers
