### ISSUE TITLE
Loadouts do not respect role timer cvar

### ISSUE THREAD

**Issue by nootsponge** [space-wizards/space-station-14#32722]
## Description
title

**Reproduction**
1. ensure cvar `game.role_timers` is false
2. go to edit a loadout that requires role times (station engineer for example)
3. items that require role times are still greyed out
4. obviously you must have under the specified role time to reproduce this

**Screenshots**
![image](https://github.com/user-attachments/assets/1827cc6f-5e1b-4fff-a8ac-390037cfe35c)
![image](https://github.com/user-attachments/assets/4f1cad30-e358-430d-a231-91377ed10bcf)

**Additional context**
https://github.com/space-wizards/space-station-14/blob/ac16a05fef3b7bb029e62c8d0e354999027dca7d/Content.Shared/Roles/JobRequirement/RoleTimeRequirement.cs does not respect cvar

**Comment by lzk228** [comment]
dupe issue

**Comment by nootsponge** [comment]
> dupe issue

gimme

**Comment by nootsponge** [comment]
#27169
