### ISSUE TITLE
Talking vending machines (adverts)

### ISSUE THREAD

**Issue by Peptide90** [space-wizards/space-station-14#3273]
[FEATURE]
## Description

It would add more depth to the server if vending machines had a way of advertising. Speech bubbles above them when someone walks past would be a good start.

They could be smaller than regular text, a different shape to indicate synthetic voice rather than human or player or could be slightly transparent not to obstruct play too much. A cooldown so that no more than one per minute or so would be good too so that you aren't spammed by vending machines all the time but this is the age of the corporate overlords.

Will be especially good when we get sentient evil vending machines that throw things at people.
**Screenshots**

**Additional context**

Excerts from TG vending code:
**Cola**
`product_slogans = "Robust Softdrinks: More robust than a toolbox to the head!"
product_ads = "Refreshing!;Hope you're thirsty!;Over 1 million drinks sold!;Thirsty? Why not cola?;Please, have a drink!;Drink up!;The best drinks in space."`
**Coffee**
`product_ads = "Have a drink!;Drink up!;It's good for you!;Would you like a hot joe?;I'd kill for some coffee!;The best beans in the galaxy.;Only the finest brew for you.;Mmmm. Nothing like a coffee.;I like coffee, don't you?;Coffee helps you work!;Try some tea.;We hope you like the best!;Try our new chocolate!;Admin conspiracies"`
**Dinnerware**
`Mm, food stuffs!;Food and food accessories.;Get your plates!;You like forks?;I like forks.;Woo, utensils.;You don't really need these...`
**Nutrimax**
`product_slogans = "Aren't you glad you don't have to fertilize the natural way?;Now with 50% less stink!;Plants are people too!"
	product_ads = "We like plants!;Don't you want some?;The greenest thumbs ever.;We like big plants.;Soft soil..."`
**SecTec**
`product_ads = "Crack capitalist skulls!;Beat some heads in!;Don't forget - harm is good!;Your weapons are right here.;Handcuffs!;Freeze, scumbag!;Don't tase me bro!;Tase them, bro.;Why not have a donut?"`
**Megaseed**
`product_slogans = "THIS'S WHERE TH' SEEDS LIVE! GIT YOU SOME!;Hands down the best seed selection on the station!;Also certain mushroom varieties available, more for experts! Get certified today!"
	product_ads = "We like plants!;Grow some crops!;Grow, baby, growww!;Aw h'yeah son!"`
**BODA (Soviet Soda)**
`product_ads = "For Tsar and Country.;Have you fulfilled your nutrition quota today?;Very nice!;We are simple people, for this is all we eat.;If there is a person, there is a problem. If there is no person, then there is no problem."`

**Comment by Visne** [comment]
I'm working on this.
