### ISSUE TITLE
Bananium reagent still references it being radioactive

### ISSUE THREAD

**Issue by TurboTrackerss14** [space-wizards/space-station-14#32784]
## Description
https://github.com/space-wizards/space-station-14/blob/0e3f3536ff565732f5d90833e479cfe801e2c8a7/Resources/Locale/en-US/reagents/meta/elements.ftl#L65
**Reproduction**
n/a

**Screenshots**
n/a

**Additional context**
Someone forgor to edit the reagent info when the radiation comp was removed.

**Comment by Golinth** [comment]
it will always be radioactive in my heart

**Comment by scrivoy** [comment]
This isn't my first PR, but I'm excited to learn more and contribute! It's really fun :)
