### ISSUE TITLE
Meta station sec bomb closet doesn't even have a screwdriver and wirecutters

### ISSUE THREAD

**Issue by Plykiya** [space-wizards/space-station-14#32781]
## Description

**Reproduction**

**Screenshots**

**Additional context**

**Comment by JIPDawg** [comment]
The bomb closest are random what they contain. 
![Screenshot_20241013-091327](https://github.com/user-attachments/assets/22b9cedf-9558-43c1-b6c4-baf3cf1c7ca3)
