### ISSUE TITLE
Remove SizeFlagsVerticals from code base.

### ISSUE THREAD

**Issue by Ygg01** [space-wizards/space-station-14#3279]
## Description
Obsolete yet used massively

**Screenshots**
![Discord_YJZyMpcJcz](https://user-images.githubusercontent.com/1146204/108225360-2b198000-713c-11eb-90e6-2f422c66bba1.png)

**Comment by Ygg01** [comment]
Assign to me plz.

**Comment by PJB3005** [comment]
Well this was a massive misunderstanding.
