### ISSUE TITLE
Evac via escape pod just... doesn't count for objectives

### ISSUE THREAD

**Issue by bruhmogus** [space-wizards/space-station-14#32790]
## Description
Evac pods don't work for "Escape to CentComm alive and unrestrained"

**Reproduction**
Step 1. Steal nuke
Step 2. Evac on pod
Step 3. Be alive and unrestrained
Step 4. Redtext

**Screenshots**
![20241013151000_1](https://github.com/user-attachments/assets/da7947f0-1c31-4f1b-bf98-d3ec691d630f)

**Additional context**
Aeiou.

**Comment by UbaserB** [comment]
intentional

**Comment by bruhmogus** [comment]
> intentional

in that case it should probably say to escape to centcomm on the evacuation SHUTTLE as opposed to just "escape to centcomm:
