### ISSUE TITLE
Add more technologies and lathe recipes from SS13.

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#328]
Now that #40 is done, we can start adding new technologies, and lathe recipes that go along those as well. This also relates to #277.

For now, #264 added a few example technologies. Those should probably be removed once a PR adds actual technologies.

**Comment by CC-4477** [comment]
Trying my best to work on this, will probably be done with most of it or the majority of it by this weekend.

**Comment by Decappi** [comment]
For me please

**Comment by Zumorica** [comment]
Sure, assigned

**Comment by SweptWasTaken** [comment]
I guess i'll assign myself this, hopefully it'll kill me like it did the last two who asked to be assigned to this.

**Comment by Decappi** [comment]
It's not that hard of a task, I just didn't have time to finish it.

**Comment by Peptide90** [comment]
#3151 and #2883 (closed PR) related.

**Comment by SethLafuente** [comment]
this should probably be closed

**Comment by Zumorica** [comment]
Yeah, you're right. They will all be deleted and rewritten when the research rewrite comes one day, anyway...
