### ISSUE TITLE
Hovering over window blocks sign in front of it

### ISSUE THREAD

**Issue by Visne** [space-wizards/space-station-14#3281]
![image](https://user-images.githubusercontent.com/39844191/108240774-738c6a00-714b-11eb-82e1-443da7a021c2.png)
![image](https://user-images.githubusercontent.com/39844191/108240792-77b88780-714b-11eb-8aec-5206ad83402a.png)

**Comment by SweptWasTaken** [comment]
Signs shouldn't be placed on windows. Next mapping PR i'll fix this.
