### ISSUE TITLE
Sandbox panel toggle buttons don't stay green after closing and reoping panel

### ISSUE THREAD

**Issue by Visne** [space-wizards/space-station-14#3282]
Before:
![image](https://user-images.githubusercontent.com/39844191/108241081-bd755000-714b-11eb-820e-489ce20ee97a.png)

After clicking:
![image](https://user-images.githubusercontent.com/39844191/108241114-c7974e80-714b-11eb-9b17-2e9d47b6afc4.png)

After closing and reopening sandbox panel:
![image](https://user-images.githubusercontent.com/39844191/108241159-d2ea7a00-714b-11eb-923f-ba1fb6be1451.png)

**Comment by SweptWasTaken** [comment]
Fixed by #3334.
