### ISSUE TITLE
Proximity detectors keep beeping after leaving range of their target

### ISSUE THREAD

**Issue by chromiumboy** [space-wizards/space-station-14#32857]
## Description

I was doing some testing and happened to find out that if you detect an entity with a proximity detector (e.g. anomaly locator) and walk away from the detected entity, the detector will continue to beep even after you leave its range. If you turn the device off and on again while out of range of the entity, the beeping will not resume until you enter range again

**Reproduction**

- Debug spawn in an anomaly somewhere nearby while holding the anomaly locator
- The locator will start to beep
- Walk far away from the anomaly and the detector will continue to beep
- Turn the locator off and then on again will stop the beeping until you enter range again
- Rinse and repeat as often as you like

**Screenshots**

N/A

**Additional context**

N/A

**Comment by Ilya246** [comment]
i fixed this a while ago, the fix just wasn't in my spectral locator branch

**Comment by chromiumboy** [comment]
Ah! No worries, thanks for the heads up
