### ISSUE TITLE
You can butcher multiple objects at once

### ISSUE THREAD

**Issue by K-Dynamic** [space-wizards/space-station-14#32919]
## Description
See title. Exacerbated by long 8 second doafter time on butchering, so players are almost required to gather multiple objects to butcher to be efficient.

**Reproduction**

1. Get sharp object and multiple objects (such as jumpsuits)
2. Butcher each item
3. Watch the doafter bars stack

**Screenshots**

![image](https://github.com/user-attachments/assets/3e51e395-9f7c-48c2-91af-5ce3ec758560)

**Additional context**
If fixed, butchering objects probably needs to be dropped from 8 seconds to 3 seconds to compensate, while butchering mobs should remain at 8 seconds.

Better fix would be to make a doafter queue that simply delays the next action, as shown in concept here
![image](https://github.com/user-attachments/assets/0c038402-1905-4fcb-a315-687e97ef9fd4)

**Comment by muburu** [comment]
considering that you can strip multiple items off of someone at once i think this might fit in the same category of intendedness as just being a jank-ish QOL thing

**Comment by LittleNyanCat** [comment]
^^
very likely intended, the same way you can pry multiple tiles and wrench multiple pipes at once just like you can in SS13
![image](https://github.com/user-attachments/assets/843562f5-a102-4ba2-8d29-d113c4a0048f)
