### ISSUE TITLE
Meta map TEG layout (or lackthereof) is painful

### ISSUE THREAD

**Issue by K-Dynamic** [space-wizards/space-station-14#32923]
## Description

TEG on Meta is basically just stapled to the outside of the station, with no burn chamber, canisters or pipes ready.

This makes it incredibly trivial to steal TEG parts, sabotage it or have it be bombarded by meteors.

**Comment by scrivoy** [comment]
Absolutely, this could be improved. As someone who loves using the TEG for power, this would be really nice. I'm not sure if that's intentional and meant to be that way, so it would be great if someone could clarify. If not, I'd love to build a proper TEG room. I've only done a little bit of mapping so far, but it's really fun, and I'd like to learn more.

**Comment by scrivoy** [comment]
> so it's worth moving the TEG there and expanding on that.

That sounds like a great idea, giving those rooms a purpose. Would that be a 'go' from you for me to start working on it? If so, I can create a draft PR and begin in the next few days. It would also be great to hear a Head Mapper's thoughts on this. Do you know who that is?

**Comment by ArtisticRoomba** [comment]
So in ss13, that little room actually housed the gas turbine, a machine that generated power by atmos burning the shit out of some plasma and running it through the machine.

![image](https://github.com/user-attachments/assets/e358bd4a-4749-4a3e-a63d-7e8b224fa8d6)

I certainly would love it if it was expanded to a proper TEG room, right now atmos doesn't really use it. I think I've only used it myself as a frezon mixing area (never do this ever, it was a horrible, horrible thing to work with).

There was previous discussion on the discord in ideaguys that asked if the gas turbine was going to see implementation. I said probably not, considering the gas turbine goes against the approved atmos design doc (set and forget power setups and atmos systems are not something we want). 

A second idea is to simply flesh out the TEG area more and leave the gas turbine as a "faded past" type thing for nostalgia. You never know, it might be added in someday. I wouldn't mind a TEG room on Meta. Although, it was a nice fun project to build a shitty r-wall room around it when things were slow. But as of right now it's hilariously easy to explode and sabotage.

**Comment by scrivoy** [comment]
> A second idea is to simply flesh out the TEG area more and leave the gas turbine as a \"faded past\" type thing for nostalgia. You never know, it might be added in someday.


Okay, good point, I didn't know about the gas turbine, thanks for the info!
Then I'm also for the second solution and build "from scratch". I took a look at the SS13 map and you can see that this "construction site" already exists. So it would fit the "lore" if you will.

**Comment by ArtisticRoomba** [comment]
Off topic but if someone drafted a design doc for the turbine that's good enough then it might make it in. You'd have to make sure it conforms to the approved Atmos design doc though. 

Maybe you could make it require a cooling gas? Although, this would just make it a reskinned TEG.

The upgrades part about it is cool though. And I would like to see TEG upgrades in the future.

**Comment by scrivoy** [comment]
> Off topic but if someone drafted a design doc for the turbine that's good enough then it might make it in.

Also off topic:
The USP for the gas turbine might be that you just burn gas. So its easier to get up and running, but it also costs more to run (like the AME). With the TEG, you can 
can be much more efficient with the resources, but its also harder to set up and you could use your burn mix for other purposes too.



But back to the topic, who can we ask to make this change on the map?

**Comment by scrivoy** [comment]
I have created a branch and a draft PR for this. I think I can start working on this in the next few days. If a Head Mapper sees this, it would be great to get some feedback.
Cheers!

**Comment by scrivoy** [comment]
Hi, the PR is finished.
