### ISSUE TITLE
Antimov and other law changes do not have sound notification

### ISSUE THREAD

**Issue by thebadman4662** [space-wizards/space-station-14#32952]
## Description
Yesterday or two days ago I was AI in nukie round and nukies seemingly skipped me and rushed for telecomms on fland, I never had and antimov sound so just assumed I was on nutimov the whole time. OOC mald ensued which made me double check if PR for sounds that I thought was already merged is in and... counting from now it should be merged 5 days ago? https://github.com/space-wizards/space-station-14/pull/32625

There is single red line at best for antimov just like for other lawsets and because I was working with service, command, engineering, security, medbay and supply all at same time that shift I had whole rainbow in my chat... I only saw antimov basically at evac because I rebooted game due to lag and my lawset no longer was nutimov which made me feel bad for nukies, regardless of their mald level.

Over course of multiple shifts I changed to: Nutimov, Paladin, Antimov; and not a single time I had a sound notification.

**Reproduction**
1. Be AI
2. Get your laws changed

**Comment by ScarKy0** [comment]
The game follows a new update schedule and only actually updates every 2 weeks
The PR will prooobably be out by the end of the week

**Comment by muburu** [comment]
i thought they were doing updates in big batches now instead of semi-daily ones??
unless the changelog broke again there shouldn't have been an update yet (i don't recall needing to update the game when joining a server recently either)

**Comment by thebadman4662** [comment]
> The game follows a new update schedule and only actually updates every 2 weeks The PR will prooobably be out by the end of the week

Huh? Why wasn't this announced?

**Comment by ScarKy0** [comment]
> Huh? Why wasn't this announced?

It was on the 4th on their [discord](https://discord.com/channels/310555209753690112/310555407711993871/1291572108685737994)
