### ISSUE TITLE
Cargo sale computer can sell using the Cargo shuttle cargo pallets

### ISSUE THREAD

**Issue by Minemoder5000** [space-wizards/space-station-14#32977]
## Description

If the ATS cargo sale computer is put on the cargo shuttle, the cargo pads on the cargo shuttle function as sell pads.
**Reproduction**

Use crowbar on sale computer, unanchor computer, anchor and reconstruct computer on cargo shuttle, sell bounty directly from cargo shuttle
**Screenshots**

![2CJjRhX](https://github.com/user-attachments/assets/954f54a9-10cd-42f8-af3d-499970f2065c)
![CB9jEJZ](https://github.com/user-attachments/assets/87682ab7-45dc-4cfd-a20e-c99cbc9bd69c)

**Additional context**

**Comment by deltanedas** [comment]
they should just be replaced with catwalk to be non functional
