### ISSUE TITLE
MIDI broken on linux

### ISSUE THREAD

**Issue by waylon531** [space-wizards/space-station-14#32980]
## Description

Recently ss14 midi instruments have broke on linux. I'm running the steam release and now I get an error when opening the instrument UI, and this error in the console:
```
/games/SteamLibrary/steamapps/common/Space Station 14 Playtest/bin/loader/fluidsynth.so: cannot open shared object file: No such file or directory
/games/SteamLibrary/steamapps/common/Space Station 14 Playtest/dotnet/shared/Microsoft.NETCore.App/8.0.0/fluidsynth.so: cannot open shared object file: No such file or directory
/games/SteamLibrary/steamapps/common/Space Station 14 Playtest/bin/loader/libfluidsynth.so: cannot open shared object file: No such file or directory
/games/SteamLibrary/steamapps/common/Space Station 14 Playtest/dotnet/shared/Microsoft.NETCore.App/8.0.0/libfluidsynth.so: cannot open shared object file: No such file or directory
/games/SteamLibrary/steamapps/common/Space Station 14 Playtest/bin/loader/fluidsynth: cannot open shared object file: No such file or directory
/games/SteamLibrary/steamapps/common/Space Station 14 Playtest/dotnet/shared/Microsoft.NETCore.App/8.0.0/fluidsynth: cannot open shared object file: No such file or directory
/games/SteamLibrary/steamapps/common/Space Station 14 Playtest/bin/loader/libfluidsynth: cannot open shared object file: No such file or directory
/games/SteamLibrary/steamapps/common/Space Station 14 Playtest/dotnet/shared/Microsoft.NETCore.App/8.0.0/libfluidsynth: cannot open shared object file: No such file or directory
```
Is it a packaging problem with the steam release? Could it be a weird local version conflict and I have the wrong version of fluidsynth or something?
**Reproduction**
Open instrument UI or be near an instrument and the message appears.

**Additional context**
I'm running arch linux if that helps at all

**Comment by deltanedas** [comment]
install fluidsynth2 (or symlinking fluidsynth3 works fine it turns out)

**Comment by waylon531** [comment]
I do have fluidsynth installed, and instruments were working fine until very recently. I just checked on master, and building everything myself makes instruments work fine, it seems like a problem with the steam release somehow

**Comment by waylon531** [comment]
Symlinking my fluidsynth libraries everywhere doesn't seem to fix it for whatever reason, I still get the same error message. My system libraries are for sure in the search path for libraries too. I tried to figure out what was going wrong with LD_DEBUG and I can confirm that /lib is in the search path and that libfluidsynth.so exists there

**Comment by Coolsurf6** [comment]
I am also having this issue. I had it working once after it broke before, but still unable to get anything out of it. I have reinstalled fluidsynth before and still no luck. 
![image](https://github.com/user-attachments/assets/0a53743c-99de-41b0-ba9e-cab9e8ffe4cb)

**Comment by deltanedas** [comment]
you have to make a symlink in bin/loader/ because it doesnt try to load from a standard directory /usr/lib for WHATEVER REASON

**Comment by Coolsurf6** [comment]
I have, I found the libfluidsynth.so file and symlinked it, even tried putting a copy of the file in there. Still gives me that error. 
It also says someting about /dotnet as well but I have no idea.

**Comment by Coolsurf6** [comment]
This is the version I am using 
![image](https://github.com/user-attachments/assets/7d0ebc7b-5fc7-494e-8989-46cd9f5ea02e)

**Comment by deltanedas** [comment]
i use 3.2.3 and it works, probably just major version difference

**Comment by Coolsurf6** [comment]
> i use 3.2.3 and it works, probably just major version difference

How did you get 3.2.3? I can't find this version on AUR or the normal Repo?

**Comment by deltanedas** [comment]
oh its much simpler
its looking for `bin/loader/fluidsynth.so` not `libfluidsynth.so` that any distro would package

**Comment by Coolsurf6** [comment]
Now it is giving me this
![image](https://github.com/user-attachments/assets/221e5197-9469-417e-9e00-9d5c1ec794b8)

**Comment by deltanedas** [comment]
thats just missing dependency

**Comment by Coolsurf6** [comment]
I have it already installed, can find the file it asks for in /lib anyway.

**Comment by Coolsurf6** [comment]
Wait yeah, I can run midis on my local host but they give me a bunch of errors. Doesn't work while running through steam.

**Comment by Coolsurf6** [comment]
![image](https://github.com/user-attachments/assets/f35bc918-988a-4d3b-bd07-92c18492df0d)

**Comment by waylon531** [comment]
> oh its much simpler its looking for `bin/loader/fluidsynth.so` not `libfluidsynth.so` that any distro would package (so `mv {lib,}fluidsynth.so`)

I already tried this, no dice. I've tried both symlinking and copying those into both of the directories the client asks and it still doesn't work. 

Here's something that works, running the binary from steam directly by setting the launch options: `/games/SteamLibrary/steamapps/common/Space\ Station\ 14\ Playtest/SS14.Launcher # %command%`

Using this as the launch option for the game lets it start and use fluidsynth fine. It's for sure a steam runtime issue. The command steam is running is `/home/uelen/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- /home/uelen/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=1482520 -- /games/SteamLibrary/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point --verb=waitforexitandrun -- /games/SteamLibrary/steamapps/common/SteamLinuxRuntime/scout-on-soldier-entry-point-v2 -- /games/SteamLibrary/steamapps/common/Space Station 14 Playtest/SS14.Launcher` but that gives zero information about libs or what part of the runtime is breaking it. Not sure how to debug this more ...

**Comment by waylon531** [comment]
One more workaround, this time forcing specific system libraries to be used instead of steam's:
`LD_PRELOAD="/usr/lib/libportaudio.so /usr/lib/libfluidsynth.so /usr/lib/libinstpatch-1.0.so.2 /usr/lib/libreadline.so.8 /usr/lib/libglib-2.0.so.0 /usr/lib/libpcre2-8.so.0" %command%`

**Comment by VasilisThePikachu** [comment]
This is an issue with steam, this issue is now tracked at https://github.com/space-wizards/RobustToolbox/issues/5512
