### ISSUE TITLE
Droppers can draw and inject locked containers

### ISSUE THREAD

**Issue by thebadman4662** [space-wizards/space-station-14#33007]
## Description
Bit odd to put chems out and in locked can without damaging it, no? Droppers are not syringes after all.

**Reproduction**
1. Get soda can and dropper.
2. Make sure soda is closed.
3. Draw with dropper

**Comment by thetolbean** [comment]
Should syringes be able to inject and draw past seals?
I think it would be interesting to poison a soda.

But I agree, droppers should not be able to draw from closed containers

**Comment by lilazero** [comment]
Does this behavior happen because the dropper is of the injector type? 
If injectors should still be able to inject and draw from closed containers(makes sense because they can pierce cans and stuff) Should a DropperComponent be created with a new behavior SharedDropperSystem that doesn't allow drawing and injecting into closed containers

**Comment by thetolbean** [comment]
Yes

> Does this behavior happen because the dropper is of the injector type? If injectors should still be able to inject and draw from closed containers(makes sense because they can pierce cans and stuff) Should a DropperComponent be created with a new behavior SharedDropperSystem that doesn't allow drawing and injecting into closed containers

Yes it does. Anything with the injector component does (did, if my pr gets merged) not check if the container was closed before injecting/drawing. My pr adds a check to see if the injector can ignore seals and if not, check if the container is closed.

**Comment by lilazero** [comment]
> My pr adds a check to see if the injector can ignore seals and if not

Yours is a good solution. I was thinking of a whole new Component
