### ISSUE TITLE
damage examine should not be available if the damage is zero

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#33052]
like what
![image](https://github.com/user-attachments/assets/74bcc6ec-aa66-4cd0-b1fd-a9b80437f9ca)

**Comment by PJB3005** [comment]
Re-opening since PR did not fix this.

**Comment by thetolbean** [comment]
I mistakenly thought this was specifically about the plushies.
From what I've seen about this issue, it looks like the consensus is to provide the button, but have alternative text that it deals no damage if the damage is 0.
I'll go back and provide a more robust fix.
(Second try is the charm)

**Comment by thetolbean** [comment]
Alright, try two. This fix is more general and works for any item that is a weapon, but has a damage of 0
