### ISSUE TITLE
AI in Intelicard can see through walls

### ISSUE THREAD

**Issue by thebadman4662** [space-wizards/space-station-14#33107]
## Description
Bug? Feature? No idea.

**Reproduction**
1. Be AI.
2. Get inserted into Intelicard.

**Comment by Everturning** [comment]
I think it should be feature 👍

**Comment by ScarKy0** [comment]
Not intended but I think It's all fine to be honest

**Comment by ScarKy0** [comment]
> No, seeing through walls is a bug

Boooooriiiing
I'll fix it when I continue my work on the intellicard

**Comment by chromiumboy** [comment]
The contract is sealed

**Comment by ScarKy0** [comment]
> The contract is sealed

Fuck
