### ISSUE TITLE
Spooder web boots are too cheap

### ISSUE THREAD

**Issue by thebadman4662** [space-wizards/space-station-14#33117]
## Description
You can get 200% cloth for your silk by making them into boots before cutting into cloth as making cloth from silk is twice as expensive.

**Reproduction**
1. Make silk
2. Make boots
3. Make cloth, put on ground
4. Cut boots, compare.

**Comment by thetolbean** [comment]
Turns out, this is not an issue in accordance to their cost, but how they butcher into the wrong item
If #33121 is merged they will break down into silk like the jumpsuits
