### ISSUE TITLE
Fix rotations to 0

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#3313]
Currently all rotations default to south which is -90 degrees and is silly.

At least if my farseer port is to be used this needs to be fixed for 0 for anything that's an AABB for collision to work properly (all new entities as well as existing ones).

There's a command called fixrotations but the that A) only goes to south and B) doesn't catch every entity.

**Comment by Acruid** [comment]
Requires https://github.com/space-wizards/RobustToolbox/pull/1551.

**Comment by PJB3005** [comment]
This is done.
