### ISSUE TITLE
Station anchor has shit collision box.

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#33137]
## Description
Please just make the station anchor 4 tiles or 1.
After the 100th aHelp about someone being stuck on the cooked collision box for this, it is time.

**Reproduction**
Go run around it, get stuck in between wall and the anchor.

**Screenshots**
![image](https://github.com/user-attachments/assets/b428c8aa-60ad-40df-813b-705e6e6e86b9)

**Additional context**
NA

**Comment by ArtisticRoomba** [comment]
duplicate of #32013
