### ISSUE TITLE
Core Telecoms/Cameras air alarms are not connected to atmos devices.

### ISSUE THREAD

**Issue by thebadman4662** [space-wizards/space-station-14#33162]
**Screenshots**
![GuysAIISDead](https://github.com/user-attachments/assets/408700e0-7780-4903-888b-b94a9aec1ebb)

**Comment by UbaserB** [comment]
thanks for pointing it out

**Comment by thebadman4662** [comment]
Np, can we have criminal console in sec for normal secoffs as a treat for reporting it? :trollface:

**Comment by scrivoy** [comment]
When I'm doing the other two reports from you, i could also do this one.
