### ISSUE TITLE
Should be able to specify catalysts in constructionGraphs

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#3316]
## Description

Stuff like, using a handheld mortar and pestle that doesn't get consumed on crafting something.

**Comment by Acruid** [comment]
Isn't that the same thing as any other tool, like a screwdriver?

**Comment by Zumorica** [comment]
Pretty much, but currently crafting (construction graphs that don't target structures) don't support tools.
And construction graphs cooould use a way to use arbitrary items as tools without needing ToolComponent, too.

**Comment by Zumorica** [comment]
(Although that's only for the initial construction, refer to the construction document for more details)

**Comment by Zumorica** [comment]
Not really needed anymore, can just make new tool prototypes for this
