### ISSUE TITLE
Omega satation CMO atmos have few issues

### ISSUE THREAD

**Issue by thebadman4662** [space-wizards/space-station-14#33182]
## Description
1. Scrubber not connected.
2. Vent not connected.
3. Air alarm is too far to interact with it.

**Screenshots**
![Omega](https://github.com/user-attachments/assets/ef852174-13f6-4bc6-a7db-552fa7eb3517)

**Comment by scrivoy** [comment]
Hey, i should be able to work on it later this evening.
