### ISSUE TITLE
Station Events never run

### ISSUE THREAD

**Issue by ewokswagger** [space-wizards/space-station-14#33187]
## Description
Station Events never run which is very unfortunate if you want to test something with events.

**Reproduction**
Start survival round
Wait an hour
Nothing happens

**Screenshots**
![image](https://github.com/user-attachments/assets/7ca8325b-5f16-489b-9d90-fe3b59416c0e)

**Additional context**
I am running this server on the most recent build with playercount overridden to 100.

**Comment by deltanedas** [comment]
you have to enable events
