### ISSUE TITLE
Telescopic shield doesn't change sprite when extended, doesn't change stats when extended

### ISSUE THREAD

**Issue by K-Dynamic** [space-wizards/space-station-14#33194]
## Description

The telescopic shield used to change sprites in the past but doesn't currently.

It also doesn't seem to change stats when activated compared to the energy shield, though it seems like the active and passive blocking components were never coded to begin with.

**Reproduction**
1. Acquire telescopic shield
2. Interact inhand to activate
3. Shield doesn't change sprite

**Screenshots**
![image](https://github.com/user-attachments/assets/7483bf0e-cbe0-4b7b-8ed7-94e910acbaf6)
![image](https://github.com/user-attachments/assets/3d63caf3-b94c-4da9-acec-ecbccc92832d)
![image](https://github.com/user-attachments/assets/1a859799-fbd4-4e96-b3e9-6ba84e623a26)

**Comment by BramvanZijp** [comment]
Known issue except nobody seems to know how to fix it.

**Comment by BramvanZijp** [comment]
#31755 Covers it (mentioned in comments since its related.)

**Comment by beck-thompson** [comment]
Good report but I'll close it because of the older one 🫡!
