### ISSUE TITLE
AI can knock on blastdoors

### ISSUE THREAD

**Issue by gostt899** [space-wizards/space-station-14#33229]
## Description
 The AI eye can knock on blast doors, and other people can hear it.

**Reproduction**
 click a blast door as the AI eye.

**Additional context**
 I was able to do this on the Salamander server.

**Comment by Errant-4** [comment]
The same issue happens with shutters and radiation shutters

**Comment by Errant-4** [comment]
Actually I just noticed that this was already reported as #32567 so I am closing this one as duplicate. Thank you for reporting it
