### ISSUE TITLE
Remove player joined/left messages.

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#3323]
To avoid metagaming and allow admins to be slightly more stealthy.

**Comment by DrSmugleaf** [comment]
Should they be kept for admins to see?

**Comment by Peptide90** [comment]
> Should they be kept for admins to see?

Maybe in admin log? IMO a system like char name (role)[ID/playername]. Or even just player and their role.

That way if it's significant you can care.

**Comment by Zumorica** [comment]
> Should they be kept for admins to see?

Sounds good and fair
