### ISSUE TITLE
Ninjas can teleport with dragged objects

### ISSUE THREAD

**Issue by K-Dynamic** [space-wizards/space-station-14#33243]
## Description

Ninjas will often cheese the RD server or console objectives by teleporting into space with it. They may also stun someone (#33242) and teleport into space to kill them.

**Reproduction**

1. Drag object
2. Dash

**Additional context**
I recall a similar issue when activating a scram implant while being dragged

**Comment by thetolbean** [comment]
PR 33252 does not address the ninjas stun, but it does address the teleporting
