### ISSUE TITLE
Pests like mice, mothroaches and cockroaches can't be picked up by clicking on them.

### ISSUE THREAD

**Issue by Callmore** [space-wizards/space-station-14#33263]
## Description

It does work if you right click and select pick up but not if you just click on them. Also the trashbag picks them up.

**Reproduction**

- spawn mouse
- click on mouse
- the mouse should remain on the floor

- right click mouse
- select pick up
- mouse is now in your hand

**Screenshots**

**Additional context**

**Comment by cwestkaemper** [comment]
I am unable to replicate this in the master branch build. Grabs work fine on mice and mothroaches. Does not work on hamlet because the "pet" interaction takes priority over grabbing.

**Comment by thebadman4662** [comment]
Same issue, can't do much against roundstart chemlab griefers, you literally have to fight UI and predicitons to grab them with rightclick.

**Comment by MilenVolf** [comment]
I've found the reason. It has something with BuckleComponent. Try VV mouse and delete BuckleComonent, then mouse and others can be picked up again

**Comment by MilenVolf** [comment]
> I think I found the reason. It has something with BuckleComponent. Try VV mouse and delete BuckleComonent, then mouse and can be picked up again

Alright, I was wrong. I made some investigation by rebasing custom branch to commits and found out that this PR #27111 is the reason why this doesn't work. Need to dig deeper to understand how it's even connected
