### ISSUE TITLE
Nukie, Loneop, and Xeno Ghost roles don't show the relevant rules

### ISSUE THREAD

**Issue by Eternally-Confused** [space-wizards/space-station-14#33272]
## Description

So Xenos, Nukies, and Loneops don't show their rules when you select the ghost role, as they should. Instead it just shows the names of their rules "ghost-role-information-rules-default-solo-antagonist" and "ghost-role-information-rules-default-team-antagonist".

**Reproduction**
See a Xeno, Loneop, or Nukie Ghostrole. Try to select the ghost role, and don't see any rules.

**Screenshots**

Here's a screenshot of one of em, but it looks the same for the other ghost roles
![Screenshot 2024-11-11 211026](https://github.com/user-attachments/assets/573faca6-6692-46c0-a0c4-c2622a9bf1b7)

**Additional context**

It looks like the issue showed up with #28098. That switched them from their role specific rules to "ghost-role-information-rules-default-solo-antagonist" and "ghost-role-information-rules-default-team-antagonist". The problem seems to be that they were never actually defined in ghost-role-component.ftl? I'd try fixing it myself if I knew what the correct rules actually _are_.

**Comment by JIPDawg** [comment]
I'll work on addressing this as well in #32457
