### ISSUE TITLE
QM's Requsition Digi-board will be turned into cardboard if it falls into the recycler.

### ISSUE THREAD

**Issue by JIPDawg** [space-wizards/space-station-14#33301]
## Description

Take the digiboard and put it in a recycler. Now you have a piece of cardboard.
**Reproduction**

1. Take digiboard.
2. Accidentally drop it into the recycler.
3. Pick up cardboard.
**Screenshots**

**Additional context**

**Comment by thetolbean** [comment]
If the QM can't have it then no one can
Have we verified that every other high value item is recycle proof?
