### ISSUE TITLE
Cryopods access

### ISSUE THREAD

**Issue by AliasHere** [space-wizards/space-station-14#33319]
The only way i see to get items from cryopods is to get AA. Which is kinda meh considering you cant even emag the thing to get items out of it. Just had a game as a syndie where CMO cryod with a hypospray, captain god knows where.

**Comment by deltanedas** [comment]
you dont need AA every head and det or something has cryo access
you can also microwave ops

**Comment by slarticodefast** [comment]
Yeah, command, the detective, security and even cadets all have cryo access. All you need to do is steal an ID.
