### ISSUE TITLE
Improve the targeting doll

### ISSUE THREAD

**Issue by AJCM-git** [space-wizards/space-station-14#3337]
OUR BENEVOLENT LEADER HAS APPROVED THE PEOPLE'S REQUEST
![old](https://user-images.githubusercontent.com/60196617/108594445-6f7d6980-7350-11eb-9325-ae9f4edad268.png)

- Make a dynamic target doll which is constructed based on the target bodyparts offsets. Should probably include a flag or something to mark which bodyparts we want to render and which dont.

- A way to target yourself/your target. My idea was to have a "target" button below the doll and a keybinding. (so it would be combat mode upwards, doll in the middle and target downwards)

- For humans can be discussed whenever or not to include hands/feet but i would say to include them because they don't change how you target that part too much (normally you always click the upper-part of the arm to aim at it) and it makes it so surgery/healing doesn't require a new UI

- Bring back/improve the old doll sprite? (its a little tiny in my opinion and we will probably have vector UI in the future)

- Make zones switching keybindings. My idea was having `tab` switch between the 3 main body zones (up, middle, down) and then specify the bodypart with `shift + tab  `  but this can get a little slow in places like the body.

**Comment by Peptide90** [comment]
Need me hands and feet for them amputations and damage.

**Comment by Emisse** [comment]
this is gone
