### ISSUE TITLE
Broken vending machines still display light

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#33382]
## Description

They're supposed to be broken, the screen is completely dark??

**Screenshots**

![image](https://github.com/user-attachments/assets/798f0c0b-ddfe-4ca3-a200-8fe459c59811)

**Comment by red15** [comment]
Vending machines have a `PointLight` and `LitOnPowered` component, broken machines are technically still powered thus the light stays on.

VendingMachineSystem.cs does change visual state when broken but it should possibly also disable PointLight.
