### ISSUE TITLE
Unequipping clothing in closed lockers causes it to flash over the locker briefly

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#3341]
## Description

To replicate:
1. Go inside locker
2. Start un-equipping clothes

**ADDITIONALLY**, when you finally get out of the locker even if you equipped your clothing again you'll burst out naked.

In fact, if you mess around with any gear inside the locker it'll just drop all your stuff when you reopen the locker.

**Screenshots**

![2021-02-20_11-48-46](https://user-images.githubusercontent.com/49448379/108606872-bef58100-73b4-11eb-9428-68197e50e4f2.gif)

**Comment by ShadowCommander** [comment]
It happens less often, but it still happens.

**Comment by PaulRitter** [comment]
what the fuck.

my suspect for this is handcode parenting the items to the locker.

**Comment by ShadowCommander** [comment]
Seems to have been fixed at some point.
