### ISSUE TITLE
Voting can override the current gamemode rules

### ISSUE THREAD

**Issue by AJCM-git** [space-wizards/space-station-14#3349]
For example: Suspicion normally doesn't allow late joins but when a vote decides another gamemode that does allow it, the gamemode will change automatically and people will be able to latejoin (also im pretty sure suspicion weapons despawn and you loose all access)

**Comment by PaulRitter** [comment]
is this a feature request or a bug request

**Comment by AJCM-git** [comment]
I dont think players being able to change the rules of a gamemode mid-round is intended, so a bug report i would say.
