### ISSUE TITLE
Non-scrambled ion laws have wrong order

### ISSUE THREAD

**Issue by thebadman4662** [space-wizards/space-station-14#33511]
## Description
They are in order of 132 instead of proper one,

**Screenshots**
![laws order](https://github.com/user-attachments/assets/5c1afaba-92dc-4d52-919f-ae258837fa2e)

![laws order 2](https://github.com/user-attachments/assets/79cb27a8-7d34-49a7-91cd-444d9f18cf5e)

**Comment by ScarKy0** [comment]
Probably fixed with #33311

**Comment by ScarKy0** [comment]
Yeah it probably is fixed but if for some reason it isnt, make a new issue or reopen this one
