### ISSUE TITLE
Can't open PDA UI interface second time

### ISSUE THREAD

**Issue by CrafterKolyan** [space-wizards/space-station-14#33519]
## Description
Currently you can open PDA UI interface only once per game session.

**Reproduction**
1. Open PDA UI interface
2. Close PDA UI interface
3. Try to open PDA UI interface again

**Comment by Winkarst-cpu** [comment]
Can't replicate this issue.

**Comment by CrafterKolyan** [comment]
This is video of replicating this issue on the current `master`. The issue is also present on Wizard's Den servers.
https://github.com/user-attachments/assets/226ac2ee-6c25-4380-9496-537c29301a7c
