### ISSUE TITLE
Need to predict stuns

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#3356]
Specifically:
1. The important one is predicting when the timer elapses as currently after you get up from a slip you'll teleport because client doesn't anticipate the end of the stun
2. Being able to paralyze from client-side in anticipation of the server stun will be useful for melee combat.

**Comment by AJCM-git** [comment]
related to #3350

**Comment by Zumorica** [comment]
Fixed by #3552
