### ISSUE TITLE
Space debris will spawn with no loot, scraps, or lockers

### ISSUE THREAD

**Issue by 3P5I7ON** [space-wizards/space-station-14#33592]
## Description

When pulling in debris from the salvage magnet, it happens frequently/all the time that the debris will be completely bare, no mobs or loot, just the lattice and tiles. I've had this happen on three shifts now (on Cog and Core, no idea if the map matters here) while playing salvage, and it's inconvenient to lose a good source of mats for the station.
**Reproduction**

- Pull in any space debris option from the salvage magnet
- Despair
 
**Screenshots**

Currently away from my PC, but I'll add screenshots once I'm able to.

**Additional context**

This only started happening approximately 24 hours ago, when the biweekly updates dropped.

**Comment by slarticodefast** [comment]
@TheShuEd Maybe related to #33113?

**Comment by deltanedas** [comment]
reverting that commit fixes it yes

**Comment by TheShuEd** [comment]
Yea, my fault

**Comment by TheShuEd** [comment]
I see into it

**Comment by kipdotnet** [comment]
Github says its been a week, are there any updates on a potential fix? This has been a big issue on our fork since our last upstream merge.

**Comment by deltanedas** [comment]
revert the commit
