### ISSUE TITLE
Fland secoff fab is... spillable?

### ISSUE THREAD

**Issue by thebadman4662** [space-wizards/space-station-14#33603]
**Screenshots**
![spillable secfab](https://github.com/user-attachments/assets/d1fbb3ba-3d87-433e-9a79-a3b4a58f3894)

**Comment by liltenhead** [comment]
Lathes that accept glue/lube are spillable.

**Comment by deltanedas** [comment]
yes this isnt a bug

**Comment by thebadman4662** [comment]
> yes this isnt a bug

Could have sworn I never had any of ma lathes ever spill lube for speeding up production though, so is spilling not implemented or that misleading part is a bug?

**Comment by deltanedas** [comment]
you can spill it so if you add non-lube it doesnt lock you out of lubing it forever

**Comment by Callmore** [comment]
just realised this lets you just completely invalidate an attempt to glue a lathe
