### ISSUE TITLE
Dungeon Master lawset name is copyrighted/trademarked and needs to be changed

### ISSUE THREAD

**Issue by ArtisticRoomba** [space-wizards/space-station-14#33671]
## Description
Unfortunately the term "Dungeon Master" is trademarked by WIZARDS OF THE COAST LLC (the people who made Dungeons & Dragons).

https://tsdr.uspto.gov/#caseNumber=74264094&caseSearchType=US_APPLICATION&caseType=DEFAULT&searchType=statusSearch

This conflicts with the Dungeon Master Lawset (`DungeonMasterCircuitBoard`) currently in-game. It should be changed.

All relevant info relating the lawset under a "Dungeon Master" should be changed to something more friendly like "Storyteller" or "Game Master". Might be a nice easy first PR for anyone who wants to take a crack at it before someone else does.

**Reproduction**
1. See board and lawset named "Dungeon Master" in game.
2. See copyright status of the term "Dungeon Master".
3. Cry.

**Screenshots**
![image](https://github.com/user-attachments/assets/ad14e996-1f14-467c-a9ac-bf33032846e8)
![image](https://github.com/user-attachments/assets/9a142dd2-5389-4e69-81a6-53d4dcac791e)

**Comment by metalgearsloth** [comment]
> Unfortunately the term "Dungeon Master" is trademarked by WIZARDS OF THE COAST LLC (the people who made Dungeons & Dragons).

They actually let it expire in my country when TSR died.

**Comment by ArtisticRoomba** [comment]
> > Unfortunately the term "Dungeon Master" is trademarked by WIZARDS OF THE COAST LLC (the people who made Dungeons & Dragons).
> 
> They actually let it expire in my country when TSR died.

Is this issue still relevant then? I don't understand much when it comes to copyright and trademark law but it seems like this is still an issue.

**Comment by hyphenationc** [comment]
> > > Unfortunately the term "Dungeon Master" is trademarked by WIZARDS OF THE COAST LLC (the people who made Dungeons & Dragons).
> > 
> > 
> > They actually let it expire in my country when TSR died.
> 
> Is this issue still relevant then? I don't understand much when it comes to copyright and trademark law but it seems like this is still an issue.

it is. don't worry, your original post remains correct.
