### ISSUE TITLE
Mobs are rotating crazily

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#3370]
## Description

This will be fixed by me.

**Screenshots**

![2021-02-21_18-12-16](https://user-images.githubusercontent.com/49448379/108651828-83dd7580-74ba-11eb-9da5-ea963e2516f9.gif)

**Comment by Acruid** [comment]
The `noRot: true` flag needs to be set on the sprite component in the yaml to stop it from rotating (the player in the video has this set).

**Comment by SweptWasTaken** [comment]
> 
> 
> The `noRot: true` flag needs to be set on the sprite component in the yaml to stop it from rotating (the player in the video has this set).

Yep, already addressed in the PR I made.
