### ISSUE TITLE
Logic gates don't work correctly with signal buttons

### ISSUE THREAD

**Issue by slarticodefast** [space-wizards/space-station-14#33716]
## Description
They work properly with signal switches or door states, but not with pulsed signals.

**Reproduction**
![grafik](https://github.com/user-attachments/assets/ba82c55f-3283-4522-b98d-9979077b4810)
![grafik](https://github.com/user-attachments/assets/5edfe8ef-a03b-465e-9f1b-2f7e35db2317)

- Spawn two signal buttons, an or-gate and a wall light
- link the buttuns to inputs A and B of the or gate
- link the output of the or gate to the toggle of wall light.
- Press button A: The light flashes for one tick.
- Press button B: The light will stay one.

`**Expected behaviour**
The output should be symmetric for both inputs for an or gate. This might affect other gates as well, but I did not test this.

**Comment by deltanedas** [comment]
they do work you just have to use an edge detector to separate the instant high and ignore the low

**Comment by 0tito** [comment]
If you link a constant 1 like a nand to a gate, and delink it, the input stays on

**Comment by 0tito** [comment]
Pretty sure it is because it doesnt check on delink, only on signal recived
