### ISSUE TITLE
No borg recharger on the Nukie station or Nukie ship.

### ISSUE THREAD

**Issue by TaoNewt** [space-wizards/space-station-14#33758]
## Description
Currently, a syndicate assault borgs first task when attacking the station is to find somewhere to recharge rather than to fight, on top of being already overpriced, they divert the teams initial goal to needing a recharging station. 
Not putting a recharger on either the ship or the station was a mapping oversight.

**Reproduction**

**Screenshots**

**Additional context**

**Comment by ArtisticRoomba** [comment]
Wouldn't this behave like an anti-stall? Without the recharger, nukies would be forced to make an advance, considering the fact that their borg's batteries might run out before they complete the mission (if they prolong it considerably).

If there's a recharger on the ship, it promotes nukies taking potshots and running back to their ship, prolonging the round.

I agree with mapping one on the outpost, though.

**Comment by TaoNewt** [comment]
> Wouldn't this behave like an anti-stall? Without the recharger, nukies would be forced to make an advance, considering the fact that their borg's batteries might run out before they complete the mission (if they prolong it considerably).
> 
> If there's a recharger on the ship, it promotes nukies taking potshots and running back to their ship, prolonging the round.
> 
> I agree with mapping one on the outpost, though.

Nukies cant practically stall, the longer they wait the more prepared the station is.
If they hit and run for ages, the crew will evac.
If they take a long time and an admin is online, ERT will be sent.

I think having one on the ship as well as the station would have no serious stalling effects, and just make syndi borgs nicer to use.

**Comment by thebadman4662** [comment]
They can still swap batteries, but if someone fucks up with EMP borg could recover, surely not ALL cells on ship and world got wrecked? One could even disassemble SMES or substation I guess

**Comment by thebadman4662** [comment]
> Nukies cant practically stall, the longer they wait the more prepared the station is. If they hit and run for ages, the crew will evac. If they take a long time and an admin is online, ERT will be sent.

Nukies can't stall? Heard of SSD war ops(they are so common at that 😭)? And admin won't let crew call evac till nukies stall for 60 minutes which is long ass time during war ops.

**Comment by TaoNewt** [comment]
damn, how do i undo that?

**Comment by thebadman4662** [comment]
Make new issue? :trollface: Or have someone reopen it for you I tihnk.

**Comment by TaoNewt** [comment]
> Nukies can't stall? Heard of SSD war ops(they are so common at that 😭)? And admin won't let crew call evac till nukies stall for 60 minutes which is long ass time during war ops.

in 700 hours, SSD war ops is not a term ive ever heard.
This is irrelivant regardless, if the nukies so wanted, they could wrench up a borg charger. This is about making the game nicer to play for the syndicate assult borg ghost role without meaningfully buffing it.

**Comment by Emisse** [comment]
ill throw one on the ship
