### ISSUE TITLE
Some UI windows are opening up incorrectly scaled to fit their text

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#3376]
## Description

**Screenshots**

![image](https://user-images.githubusercontent.com/19853115/108670553-4964e000-749c-11eb-856b-c857b3aa1575.png)
![image](https://user-images.githubusercontent.com/19853115/108670568-4f5ac100-749c-11eb-8efc-c378153fac06.png)

**Additional context**

Caused by the last day of commits since a 2 day-old branch couldn't repro

**Comment by mirrorcult** [comment]
also happens with viewvars windows

**Comment by PJB3005** [comment]
The new UI system can't measure an absolute minimum size for UI controls anymore so we now need to manually specify it via `MinSize` in the controls. I guess I missed some spots.

**Comment by Peptide90** [comment]
Similar to #3294
