### ISSUE TITLE
April fools branch when

### ISSUE THREAD

**Issue by notquitehadouken** [space-wizards/space-station-14#33771]
please I have funny ideas and need somewhere to put them before the motivation wears off

**Comment by slarticodefast** [comment]
Keep them waiting in a branch in your github repository and hope there won't be any merge conflicts.
I got some fun stuff prepared already and am doing the same.

**Comment by notquitehadouken** [comment]
> Keep them waiting in a branch in your github repository and hope there won't be any merge conflicts.
> I got some fun stuff prepared already and am doing the same.

based
