### ISSUE TITLE
Singuloose on Meta after about 7 minutes in without any outside help

### ISSUE THREAD

**Issue by Callmore** [space-wizards/space-station-14#33786]
## Description
Singuloose happened on round 73091 with no outside intervention after it ate the lattices connecting the containment field generator to the station, causing it to sever and release the singularity.
![image](https://github.com/user-attachments/assets/68d2e37c-0011-46db-8c3d-baffe971deb1)
Pictured is a replay on the tick that the singularity ate the lattice and broke containment. No extra lattice was added.
This is probably an issue since on this station the singularity is setup from the start, minus turning on the generators and emitters. The round start setup being not safe from this is probably an issue.
From a quick check of the map viewer, only other map that seemed potentionally of issue was core, the corners of the containment isn't directly connected, instead being connected a tile away.

**Comment by ArtisticRoomba** [comment]
My mapping changes addressing this got merged, let me know if it happens in 2 weeks for if it happens on a master branch fork. In the meantime, I guess you could add scaffolding where I added it in my PR and see if it looses or not.
