### ISSUE TITLE
Greytide Virus bolts open all department doors it targets, including doors that are a part of different grids

### ISSUE THREAD

**Issue by ArtisticRoomba** [space-wizards/space-station-14#33793]
## Description
PR #33547 introduced the Greytide Virus, an event that bolts open doors and unlocks lockers of the department it targets, depending on severity.

Unfortunately it appears that the event targets doors/lockers on entirely different grids, so grids like the Evac Shuttle and CC are affected by the virus as well.

**Reproduction**
1. Experience the Greytide Virus event
2. Go to CC or Evac Shuttle
3. Witness doors bolted open, lockers unlocked on those grids

**Screenshots**
![image](https://github.com/user-attachments/assets/37341423-94b7-4995-b4f8-453a590b2e0a)
![image](https://github.com/user-attachments/assets/7fd69cb4-c896-46e8-a936-1e629d2af257)

**Comment by thebadman4662** [comment]
Feature? :trollface: 
Greytide worldwide memes and all that I mean.
