### ISSUE TITLE
Protolathes and Autolathes don't show insertion of materials

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#3382]
## Description

Idk what broke this. No errors or anything, they're just not showing the insertions. They insert fine, just no sprite.

**Comment by SweptWasTaken** [comment]
To add to this, I think the LatheVisualizer is just shitcode and needs a total rewrite.

**Comment by metalgearsloth** [comment]
Animations are fixed BUT it definitely needs a cleanup because AutoLathe and Protolathe are copy-pastes.

**Comment by mirrorcult** [comment]
`[ERRO] root: Failed to load RSI Constructible/Power/protolathe.rsi`
might be related

**Comment by mirrorcult** [comment]
or maybe thats unrelated to this entirely

**Comment by SweptWasTaken** [comment]
Unrelated, this was fixed by @metalgearsloth IIRC.
