### ISSUE TITLE
Grappling gun defies the Pauli Exclusion principle

### ISSUE THREAD

**Issue by notquitehadouken** [space-wizards/space-station-14#33880]
## Description

Grappling gun let you phase through walls

**Reproduction**

1. Shoot gun of grappling
2. Run behind wall
3. Right click
4. Phase directly through wall

**Screenshots**

**Additional context**

**Comment by deltanedas** [comment]
dupe issue

**Comment by notquitehadouken** [comment]
> dupe issue

damnmmnmm,,.,.,.,.z.,.,...,.,,.
