### ISSUE TITLE
You can mass clone people to lag the server

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#3389]
## Description
Reported by Alpha Passive#4841

**Screenshots**

![image](https://user-images.githubusercontent.com/19853115/108907831-da909f80-75df-11eb-9b39-b24e7e4f5f5c.png)

**Additional context**

**Comment by Peptide90** [comment]
Cloner needs to take like 5 minutes IMO or have a 2 minute cooldown or something. Most servers require biomass to run it but even then that will probably let people spam it at least like 10 times.

**Comment by AlphaPassive** [comment]
Thanks for crediting me, this was so much fun to do but yeah it needs to be fixed right away.
