### ISSUE TITLE
Space background does not properly update when the window is resized

### ISSUE THREAD

**Issue by Moneyl** [space-wizards/space-station-14#339]
I'm experiencing this issue on Windows 10. The problem is that if you resize your window once in game, the parallax does not resize along with it reliably, and results in part of the background being pitch black:
![Robust Client_bpQxQ125PI](https://user-images.githubusercontent.com/8206401/64927604-e9fc9e00-d7da-11e9-827b-687c607b93bb.png)

Something interesting I noticed, is that if you move far enough down, part of the bottom of the parallax will fix itself. If you move back up it'll go back to the previous appearance: 
![Robust Client_Xv9t0du6dd](https://user-images.githubusercontent.com/8206401/64927611-12849800-d7db-11e9-95dd-a8857ad1c0ce.png)

The same thing happens if you move far enough to the right:
![Robust Client_FGoVC9snGc](https://user-images.githubusercontent.com/8206401/64927622-2cbe7600-d7db-11e9-9686-b072eb36d82b.png)

Or if you move to the bottom right of the map the whole thing will fix itself:
![Robust Client_ZpByxh8FQF](https://user-images.githubusercontent.com/8206401/64927634-4790ea80-d7db-11e9-95fd-b5fbf8aee1ca.png)

Steps to reproduce:
1. Start the game with the default resolution and join a server.
2. Maximize/resize your window
3. The bottom and right sides of the parallax should look as they do in the first image.

**Comment by PJB3005** [comment]
Pretty sure the root problem here is that I was too lazy to make parallax work properly with resolutions greater than 1080p.

**Comment by metalgearsloth** [comment]
@Zumorica this has been fixed for ages
