### ISSUE TITLE
Pen varients dont count for bounties

### ISSUE THREAD

**Issue by IProduceWidgets** [space-wizards/space-station-14#33995]
## Description

The bounty asks for pens, but some players spawn with alternate pens that dont work for this.

**Reproduction**

Have pen bounty > ask lawyer for pen > for some reason NT hates luxury pens

**Screenshots**

**Additional context**

**Comment by lzk228** [comment]
very weird

**Comment by lzk228** [comment]
looking at the pens prototypes it looks like should work
should be replicated with screenshot/video

**Comment by lzk228** [comment]
cannot reproduce

https://github.com/user-attachments/assets/0a3e43f7-2ce5-41fe-80a8-8ed91e90e196
