### ISSUE TITLE
While having no usable limbs, you can still interact with certain objects

### ISSUE THREAD

**Issue by Anynamedman** [space-wizards/space-station-14#34003]
## Description
Whilst not having any usable limbs (all are broken exept the torso) and being conscious, you are still able to interact with certain objects such as nearby curtains, doors, worn masks (wearing and unwearing them via actions) and other stuff I probably havent found yet

**Reproduction**
1. Have no usable limbs or break them all, includes head, arms, hands, legs and feet, but dont break your torso so you can still be conscious.
2. You are still able to interact with certain objects in game such as the ones mentioned before

**Screenshots**

**Additional context**
Not sure if its intentional but im pretty sure that if you dont have any usable limbs, you shouldnt be able to open and close curtains

**Comment by beck-thompson** [comment]
Are you sure this is the correct repository? There isn't any surgery on upstream! (I could be misunderstanding though)

**Comment by deltanedas** [comment]
shitmed issue

**Comment by beck-thompson** [comment]
OK sounds good then! Try making this report to the downstream your playing on 🫡
