### ISSUE TITLE
Spray painters only work once

### ISSUE THREAD

**Issue by IProduceWidgets** [space-wizards/space-station-14#34000]
## Description

You can only spray paint an airlock once with a spray painter then it breaks.

**Reproduction**

Be aghost > spray paint airlock > attempt to spray paint second airlock > be annoyed.

**Screenshots**

**Additional context**

**Comment by lzk228** [comment]
reproduced and maybe found why it happens only with aghost

https://github.com/user-attachments/assets/3471969e-98c8-4718-8eac-185f0015492f

the painter somehow doesn't delete the doafter
left - normal painter
right - used by aghost

![Screenshot_20241222_031834](https://github.com/user-attachments/assets/d062a68d-e3de-4e61-a34e-4d7211db4c8d)
