### ISSUE TITLE
Loop's Security Department is WAY too vulnerable.

### ISSUE THREAD

**Issue by BramvanZijp** [space-wizards/space-station-14#34009]
## Description
Security in Loop is EXTREMELY vulnerable:
The armory walls are 1 thick, with a convenient maint shaft running right behind it which is perfect for a c4 charge, and there is no easy way to see who actually placed it untill the hole is already broken open, by which point the bomber can be long gone.
It is very easy to break somebody out of perma through the windows.
The security locker room also has easy to breach windows simular to perma.
There are no blast doors or even shutters on any of these vulnerable windows, so even if you realise they got broken open before it is too late, you cannot seal the breach without help from engineering or a forcefield projector, which is not in my standard security loadout. (Security holobarrier is not gonna keep people from hopping over them to take a look around the armory.)

**Reproduction**
Play Loop on Harmony.
Oh deer god.

**Screenshots**
Just look at the Map.

**Additional context**
Uh, bonus issue: Theres a CC Pen in captains office, which if thats going to stay it should probably be changed to command contra instead of cc contra.

Other then that I really like the map, its just security is such an easy target, one of my first rounds playing it as HoS on harmony had it bombed 3 seperate times in the same shift, with each of these being a massive problem, plus a prisoner being broken out of perma with EASE.

**Comment by TytosB** [comment]
genuine question, why do you think people are so quick to bomb open loop armory, when fland and bagel both also have an armory you can bomb into with a single c4 charge from maints, yet no one seems to do so for those maps? it seems like a psychological thing but im not sure whats triggering it. ofc that one round may have just been an outlyer.

**Comment by slarticodefast** [comment]
Not sure about the other stuff, but centcom items should not be mapped onto stations, so the pen should probably be removed.

**Comment by ArtisticRoomba** [comment]
Yeah, looking at the map, I can see a number of issues. Perma being easy to break out is one, usually perma is airgapped from the station for this very reason with the windows being observable from security on the stations where this is the exception.

The CC pen shouldn't be mapped at all.

Armory is unfathomably easy to break into, nukies can just dock or spacewalk to evac and walk through a whopping one all access door and C4 armory for free access.
![image](https://github.com/user-attachments/assets/05d0d081-974b-44c4-abc4-aee7306126d8)

**Comment by BramvanZijp** [comment]
Fixed by #34067
