### ISSUE TITLE
Ghost glitch

### ISSUE THREAD

**Issue by SomeoneElsHere** [space-wizards/space-station-14#34047]
## Description
If done successfully, you can phase through walls like a ghost, but can still take damage. Going into any container does not make the container phase through walls. 

**Reproduction**
As a rodenta, place a barrel on a counter. Then, try to vault onto the barrel. 

Replay
https://replay.unstablefoundation.de/replay/deltav/Server%203/18085

Photos ![20241223_203653.jpg](https://github.com/user-attachments/assets/0767d4ef-8cec-4810-9a8f-f955df4801af)

**Comment by beck-thompson** [comment]
Is being a rodenta necessary for recreation? If so make the bug report on [Deltav's bug issues](https://github.com/DeltaV-Station/Delta-v/issues)!

**Comment by SomeoneElsHere** [comment]
Oops, gotcha
