### ISSUE TITLE
More construction recipes

### ISSUE THREAD

**Issue by Peptide90** [space-wizards/space-station-14#3405]
## Description
To align ourselves with the roadmap we need the following construction recipies / graphs:
***Things marked with an * are not / likely aren't in the game yet***

- [ ] Fake Walls
- [x] Air Alarm & Fire Alarm
- [ ] Security Camera*
- [x] Light Fixture
- [x] Windoor
- [ ] Button
- [ ] Reflectors #5635 *
- [x] Airlock
- [ ] Turret*
- [ ] AI Core*
- [x] Solar Panels
- [x] Solar Tracker
- [x] Disposals Chute
- [ ] Disposals "exit"
- [ ] Modular consoles*
- [x] Railings
- [ ] Sink - Peptide
- [ ] Shower - Peptide

**Furniture**
- [x] Chairs
- [ ] Closet
- [ ] Rack
- [ ] Beds
- [ ] Bookcase
- [ ] Drying rack
- [ ] Display
- [x] Crates
---
### Completed
**Barricade**
![barricadewooden](https://user-images.githubusercontent.com/78795277/109173381-ad78f400-777b-11eb-81c3-6d9c6fc5828f.png)

**Comment by Zumorica** [comment]
A few of these can't be implemented as construction recipes/graphs yet because they haven't been coded yet

**Comment by mirrorcult** [comment]
im working on some of the furniture ones, i want to make a better wallmount system in the future as well

**Comment by Peptide90** [comment]
> 
> 
> A few of these can't be implemented as construction recipes/graphs yet because they haven't been coded yet

Yeah I started putting a * beside ones that weren't in but I was super tired so left formatting for today.

**Comment by Peptide90** [comment]
> 
> 
> im working on some of the furniture ones, i want to make a better wallmount system in the future as well

I'll avoid furniture for now and stick my name beside some above.

**Comment by Peptide90** [comment]
[#5018] contributes to this. Only just realised this old issue was still open. I'll continue work on it gradually as I know others have been too.

**Comment by Peptide90** [comment]
Closing as we have most of these now that matter and any new PRs for entities will include the graphs.
