### ISSUE TITLE
Amber emergency shuttle timer doesn't show on screens.

### ISSUE THREAD

**Issue by DinnerCalzone** [space-wizards/space-station-14#34058]
## Description
When the emergency shuttle is called on Amber Station, it's ETA timer does not display on screens around the station.

**Reproduction**
Call the emergency shuttle on Amber Station.

**Additional context**
This seems to be the result of the emergency shuttle lacking a DeviceNetwork component that transmits a shuttle timer. Adding this component to the emergency shuttle's grid with the following configuration should fix the issue.
```
- type: DeviceNetwork
  configurators: []
  deviceLists: []
  transmitFrequencyId: ShuttleTimer
  deviceNetId: Wireless
```

**Comment by southbridge-fur** [comment]
I will resolve this tomorrow
