### ISSUE TITLE
Port tg cooking

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#3409]
Currently you just put stuff into the microwave to wzhzhzhz but being able to have some more depth to it would be nice. You might be able to get away with using the construction system for it too.

**Comment by metalgearsloth** [comment]
Also cooking should use the existing data-driven construction system as well.

**Comment by Willhelm53** [comment]
Anyone working towards this should refer to the design doc created since this issue was put in:
https://docs.spacestation14.io/en/design/kitchen

**Comment by Peptide90** [comment]
Related to #3809 +#8145 +  #8143

**Comment by Nitro-Express** [comment]
Related to #8488

**Comment by mirrorcult** [comment]
should just be docced properly, not really actionable
