### ISSUE TITLE
Clickmap finnicky

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#3422]
Might have something to do with the recent sprite rotation changes but drag-dropping onto a table to vault is very finnicky now.

**Comment by metalgearsloth** [comment]
GetEntitiesUnderScreenPosition is highly suss and this is passing in the carpet as the dropped-on entity:
![image](https://user-images.githubusercontent.com/31366439/109415279-ddd6c180-7a0b-11eb-8a1e-05c37112544b.png)

**Comment by mirrorcult** [comment]
fixed by #3480
