### ISSUE TITLE
Make windows anchorable

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#3423]
I'm not exactly sure how eris handles it in regards to re-anchoring (does it need a low-wall?) and the sprite change, code is here https://github.com/discordia-space/CEV-Eris/blob/604fb7ab7b314f119167f0a640e355a984c14b67/code/game/objects/structures/window.dm

Also anchorable needs support for setting do_after via yaml + Anchoring toolquality should probably be renamed to wrenching (given screwdrivers unanchor windows).

**Comment by mirrorcult** [comment]
eris windows need a low wall, any windows that arent on a low wall fall to the ground and shatter

**Comment by PaulRitter** [comment]
imo the obvious solution would be to not anchor windows but just connect(?) to lowwalls, so that if lowwalls get unachored you can pull the combo

**Comment by Zumorica** [comment]
Not a problem anymore, low walls are dead :relieved:
