### ISSUE TITLE
Its not obvious enough when disarm/other actions are enabled

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#3429]
## Description

Some proposed solutions:
- make the border around 'active action' more obvious
- make disarm an action that deselcts when you do something with it (disarm someone, have to press it again to disarm)--which also makes it less like a clone of intents
- change cursor (sort of working on this)

**Screenshots**

![image](https://user-images.githubusercontent.com/19853115/109365290-12048380-784e-11eb-8b4f-9d1adebffa8f.png)
![image](https://user-images.githubusercontent.com/19853115/109365310-1a5cbe80-784e-11eb-8262-950ec406747b.png)
![image](https://user-images.githubusercontent.com/19853115/109365331-29dc0780-784e-11eb-81c7-19f98ef8e08d.png)

**Additional context**

**Comment by metalgearsloth** [comment]
My thoughts on the disarm side:
* It should either: not be usable when in combat mode or not allow punches to go through (probably the former?)
* IMO it shouldn't fallback to regular interactions if the target isn't disarmable as it just leads to confusion.
* I doubt just doing the border will make it clearer, disarm icon itself probably needs changing.

**Comment by PaulRitter** [comment]
Ye just make the disarm icon light up in some more significant way
