### ISSUE TITLE
DO NOT make any changes to Drink YAML

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#3434]
## Description

I can't sum all this up in a single issue but people keep asking for food/drink stuff and how to craft etc etc.

I am working on a large PR to rectify this crisis. It is top priority for me but requires a Herculean amount of organization and grunt-work. Again, if you have to make a PR do, but I'll close anything that conflicts.

**Comment by SweptWasTaken** [comment]
Still applies, working on drinks which will take much less time than the last PR.

**Comment by PaulRitter** [comment]
@SweptWasTaken does this still apply? its been a few months

**Comment by SweptWasTaken** [comment]
> 
> 
> @SweptWasTaken does this still apply? its been a few months

Yeah I got side-tracked by other projects and I was waiting for food to be added to construction system. Still got it in the works but i'll just deal with any conflicts.
