### ISSUE TITLE
DamageOtherOnHit causes thrown items to collide with all entities

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#3441]
## Description

Replicate
1. Spawn bottle 
2. Throw bottle towards any entity lying on the ground. (A spill, an item, etc.)
3. It will break on that entity.

This should ideally only break on mobs.

**Comment by mirrorcult** [comment]
this sounds like its just a collision layer/mask problem, stuff like that should be able to collide with walls, structures, mobs etc and still break, but not tables or spills or something

**Comment by AJCM-git** [comment]
This isn't reproducible anymore.
