### ISSUE TITLE
NodeContainer bug with anchored: false

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#3444]
## Description

Not really sure how to go into this, but if you have a prototype with `- type: NodeContainer` and `Physics: anchored: false` on it, it will throw this.

```
[FATL] unhandled: System.ArgumentException: An item with the same key has already been added. Key: Content.Server.GameObjects.Components.NodeContainer.Nodes.AdjacentNode
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
```

The easiest way to replicate this is to go to `Prototypes\Entities\Constructible\Specific\Engines\Singularity\emitter.yml` and change `anchored: true` to `anchored: false`.

**Comment by collinlunn** [comment]
Will look at it
