### ISSUE TITLE
Smoke crash / lag

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#3447]
Still getting reports of it:
https://discord.com/channels/310555209753690112/566749927372357632/815462865447682110

![image](https://user-images.githubusercontent.com/31366439/109413447-93e8de00-7a01-11eb-9703-83b21a4f07b9.png)

**Comment by ElectroJr** [comment]
Probably fixed by one of the various smoke and reagent bug fixes.
