### ISSUE TITLE
Regular walls can no longer be deconstructed

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#3451]
On the most recent build, regular walls can no longer be deconstructed using a welder. Using a welder will cause a progress bar to appear, but the metal sheet will not separate from the girder. This applies to crafted walls as well as ones that spawn at round start, but was not the case a few days ago when I was freely able to construct and deconstruct walls.

I'm assuming this is a bug and not intended behavior because reinforced walls can still be deconstructed and I haven't seen any patch notes indicating otherwise.

![image](https://user-images.githubusercontent.com/7907891/109423777-ca493d80-79ae-11eb-9ff6-5de37f26289b.png)

![image](https://user-images.githubusercontent.com/7907891/109423785-cfa68800-79ae-11eb-974c-f307991b8733.png)

**Comment by Zumorica** [comment]
Fixed by 71e6effd48cad0a16e03f95d10cb923d574ebcb6
