### ISSUE TITLE
Physics branch issues

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#3464]
Blockers:
- [x] Pulling joints can be done infinitely
- [x] Prediction. The tradeoff is ending contacts will look like shit until a more robust solution is found but it's probably the better one for now. The exact line is PhysicsMap.CS:520
*Player movement should be okay now though we'll need to play around with predicted items being pushed to stabilise them a bit maybe.

QOL:
- [x] Lag -> This mainly comes from Contact evaluation (shit ton of allocs and perf in general) so probably better to port existing AABB solver sooner rather than later
- [ ] Tunnelling -> Needs TOI solver.
- [x] Wall jitter, uhhhh edge shapes on walls probably. Can probably adjust some of the cvars to fix it as well.

**Comment by Macoron** [comment]
**From latest playtes (07.03.2021):**

- [ ] When you are pulling and moving towards object this happen:

https://user-images.githubusercontent.com/6161335/110250773-41259e00-7f8e-11eb-92f1-2eb29e46cc2b.mp4

- [ ] Buckling teleports you to (0, 0):

https://user-images.githubusercontent.com/6161335/110250797-6a462e80-7f8e-11eb-9f44-ec1b73c8faff.mp4

- [ ] Sometimes client dies with 5 FPS, lost transform syncs completely and hangs. Rejoin hepls. Can't tell more information, maybe someone have logs.

- [ ] Throwing item doesn't give you momentum in 0g.

- [ ] You can't place items on racks:

![image](https://user-images.githubusercontent.com/6161335/110250854-b2fde780-7f8e-11eb-9bfc-8d568f823371.png)

**Comment by Macoron** [comment]
Also throwing small items in zero G will tunnel them trough collision:

https://user-images.githubusercontent.com/6161335/110251088-df663380-7f8f-11eb-8ef5-fed242aeba21.mp4

**Comment by SweptWasTaken** [comment]
**Originally reported by TimrodDX on GitHub**

Picking up a pulled object breaks your hands and hurls you into space

How to reproduce:

Step 1. Drop an item that you can normally hold in your hands. Your PDA will work just fine.
Step 2. Ctrl + Click to pull the item.
Step 3. Switch to the hand you're not using to pull the item.
Step 4. Pick up the item you are currently pulling without dropping the pull.

Expected behavior would be for the pull to cease as you no longer have anything to pull.

Instead, you get into a softlock situation where you can't move (you'll automatically warp back to wherever the pulled object was after a single step), can't use your hands (can't drop the item, can't stop the pull) and after a minute or so will be warped to space.

**Comment by SweptWasTaken** [comment]
**Originally reported by @moonheart08 on GitHub**

Objects need a speed cap

At the moment you can end up with thrown items bouncing around at insane speeds, fast enough they're jumping from one part of the screen to another.

**Comment by TimrodDX** [comment]
If someone dies while in zero gravity, and you turn gravity back on to attempt to drag them, the body will break much in the same way as picking up a pulled object. This can also happen if you go too close to the body - I simply touched it and could no longer move or use my hands.

![image](https://user-images.githubusercontent.com/7907891/110251741-e705e800-7f4f-11eb-82b4-d7cc35bcd778.png)

**Comment by TimrodDX** [comment]
Actually, corr

> 
> 
> If someone dies while in zero gravity, and you turn gravity back on to attempt to drag them, the body will break much in the same way as picking up a pulled object. This can also happen if you go too close to the body - I simply touched it and could no longer move or use my hands.
> 
> ![image](https://user-images.githubusercontent.com/7907891/110251741-e705e800-7f4f-11eb-82b4-d7cc35bcd778.png)

Actually, correction - it looks like an unrelated desync. The bodies are, however, un-pullable and immobile. Can't even loot them.

**Comment by moonheart08** [comment]
> **Originally reported by TimrodDX on GitHub**
> 
> Picking up a pulled object breaks your hands and hurls you into space
> 
> How to reproduce:
> 
> Step 1. Drop an item that you can normally hold in your hands. Your PDA will work just fine.
> Step 2. Ctrl + Click to pull the item.
> Step 3. Switch to the hand you're not using to pull the item.
> Step 4. Pick up the item you are currently pulling without dropping the pull.
> 
> Expected behavior would be for the pull to cease as you no longer have anything to pull.
> 
> Instead, you get into a softlock situation where you can't move (you'll automatically warp back to wherever the pulled object was after a single step), can't use your hands (can't drop the item, can't stop the pull) and after a minute or so will be warped to space.

To elaborate on this, the game desyncs, and you wind up here:
![image](https://user-images.githubusercontent.com/7806367/110251870-4829bd80-7f48-11eb-86c8-1353192c6152.png)

**Comment by Tarlan2** [comment]
I got these issues in two different rounds, one after the other. While it may look that it's a bug related to the audio, what happened was that I pretty much got stuck, not being able to move at all, with the movement controls not responding whatsoever.


https://user-images.githubusercontent.com/76408146/110252888-70abba80-7f3c-11eb-96bd-70e08ee619ef.mp4


https://user-images.githubusercontent.com/76408146/110252897-7a352280-7f3c-11eb-8b3d-248b6789c0a2.mp4

**Comment by metalgearsloth** [comment]
> 
> 
> **Originally reported by @moonheart08 on GitHub**
> 
> Objects need a speed cap
> 
> At the moment you can end up with thrown items bouncing around at insane speeds, fast enough they're jumping from one part of the screen to another.

There is a cvar for a speedcap which is at the box2d default so someone find a reasonable one for the default.

**Comment by metalgearsloth** [comment]
Okay I set the speedcap close to what it was (it's not 35m/s).

**Comment by TimrodDX** [comment]
The new speedcap breaks zero gravity, in that now instead of floating when gravity is off, you still have complete movement control as if it were on but you move at a fraction of normal speed.

**Comment by TimrodDX** [comment]
I also know pulling has become sus but if you start pulling an object that can be anchored to the floor (lockers, computers, PA parts, etc) and then switch hands and unanchor the object, it'll slide toward you at high speed and probably pin you between it and a wall.

**Comment by moonheart08** [comment]
I think the solution to pulling would be intelligent pulling, where it tries to unstick the object automatically. However this is, to say the least, complicated. An easy stopgap would be to have pulled objects tend toward the cardinal the player is moving on, so they try and stay roughly in-line with the player. This'd mostly solve the door issue (you'd get stuck briefly at most before the object centers itself enough to get through)

**Comment by metalgearsloth** [comment]
> 
> 
> The new speedcap breaks zero gravity, in that now instead of floating when gravity is off, you still have complete movement control as if it were on but you move at a fraction of normal speed.

That's not the speedcap

**Comment by metalgearsloth** [comment]
Closing as all of these were solved except TOI
