### ISSUE TITLE
The amount of starting credits cargo gets makes it practically impossible to get a particle accelerator.

### ISSUE THREAD

**Issue by WlarusFromDaSpace** [space-wizards/space-station-14#3474]
## Description

Due to the starting amount of credits cargo starts with(1000) and the slow rate at which it is passively generated(20c every 10s) and because there is no way to actively get credits(That I am aware of) the required amount of time for a round to be in progress to get a particle accelerator(10000) is 1 hour and 15 minutes.
A completely unreasonable amount of time for setting up any engine.

**Comment by SweptWasTaken** [comment]
Ye
