### ISSUE TITLE
Tensioner/Threat AI/Storyteller/AI Director/Game Pacing System

### ISSUE THREAD

**Issue by ghost** [space-wizards/space-station-14#35]
(thanks to @DeityLink for concept which I shamelessly copied from ivory tower)
When the server loads up, it generates "threat level" based on playercount/playerprefs/randomseed
(possibly weighted toward the center)

- if the number is closer to 0, there won't be many antags, the round will be akin to "extended"
- if the number is above 75, large threats like malf, blob, nuke are more likely
- And near 100, anything could happen.

The longer the round goes without any player being ghosts, the more chances the AI will decide to spawn new threats:

- If there are many ghosts, it'll spawn antag-type threats like raiders, operatives, or if the threat level is low it'll just autotator someone
- If there aren't many ghosts, it'll spawn random disastrous events 

What should be in a "disaster spawning" equation?
- [ ]  The length of the round?
- [ ]  The current number of antags?
 - [ ]  The number of living players?
 - [ ]  The number of ghosts?
 - [ ] The threat level?
 - [ ] The map size?

 - [ ] Should Tensioner/Threat AI/Storyteller/AI Director/Game Pacing System also manage other game progressing mechanics? (Science? Goals for you wagecucking job? Station goals?)

**Comment by Silvertorch5** [comment]
The AI will only speak in moos.

mooalerts

"10/10" IGN

**Comment by acvzy** [comment]
Moved [here](https://hackmd.io/@ss14/docs/https%3A%2F%2Fhackmd.io%2F%40ss14%2FBkwGWGDTr)
