### ISSUE TITLE
Notification for instruments when playing a file over the limit

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#3503]
## Description

A little piece of text saying (2mb limit) or something.

**Screenshots**

![image](https://user-images.githubusercontent.com/49448379/110017891-9c515980-7d1e-11eb-9da5-d91f116fb261.png)

**Comment by Zumorica** [comment]
Nah. I'd rather just display an error message when you try to load a MIDI file that's over the limit

**Comment by SweptWasTaken** [comment]
> 
> 
> Nah. I'd rather just display an error message when you try to load a MIDI file that's over the limit

Fair, i'll change the issue title.
