### ISSUE TITLE
(serv3) Cargo telepad is unpowered now

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#3507]
## Description

**Screenshots**

![image](https://user-images.githubusercontent.com/19853115/110049320-db77ae80-7d0e-11eb-9545-c2b4aceef423.png)
![image](https://user-images.githubusercontent.com/19853115/110049332-e16d8f80-7d0e-11eb-9f06-356e0105290d.png)

**Additional context**

**Comment by SweptWasTaken** [comment]
Not working cause it's unanchored.

**Comment by SweptWasTaken** [comment]
This issue was fixed but cargo console still fucked so i'll make an issue for that.
