### ISSUE TITLE
IconComponent default "state" needs to be icon

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#3511]
## Description

I can't tell if this was the way it was before, but some of the errors are stemming from this issue.

For example, before serv3 merge guns had this and it worked. [IconComponent.cs before the merge](https://github.com/space-wizards/RobustToolbox/blob/2183cd7ca1b2dde947cff1aeb6b493cb30c828aa/Robust.Client/GameObjects/Components/Icon/IconComponent.cs).
```yaml
  - type: Icon
    sprite: Objects/Weapons/Guns/Rifles/calico.rsi
```
and since there was an `icon` in their RSI they worked.

Now with serv3 merged they are broken and the console prints [IconComponent after the merge](https://github.com/space-wizards/RobustToolbox/blob/2183cd7ca1b2dde947cff1aeb6b493cb30c828aa/Robust.Client/GameObjects/Components/Icon/IconComponent.cs).

`[ERRO] go.comp.sprite: Layer has no RSI to load states from. Cannot use 'state' property. (icon)`

You can tell it's this issue by going into the guns yaml and adding `state: icon` to the `- type: Icon`.

**Comment by PaulRitter** [comment]
again these are errors due to the serializationhook running to early. that being said the default might be a good idea

**Comment by juliangiebel** [comment]
`IconComponent` is dead afaik. This can probably be closed.
