### ISSUE TITLE
Cargo Console's Magic Teleporting Circuit Board

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#3512]
Step 1. Attempt to deconstruct the cargo console inside cargo itself.
Step 2. Get to the step where you crowbar out the circuit board.
Step 3. The circuit board will magically materialize on the cargo console on the bridge for some reason instead of on the computer in cargo itself.

**Comment by TimrodDX** [comment]
I should mention that right after discovering this bug, I also found that deconstructing the cargo console can also cause other computers on the station to randomly spawn circuit boards - I found one on the communications console in the captain's office and one on the arcade machine in the bar.

**Comment by SweptWasTaken** [comment]
Fixed.
