### ISSUE TITLE
Constructions that require cables will take cables infinitely

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#3525]
How to reproduce:

Step 1. Build something that requires cables. I did this with the Particle Accelerator.
Step 2. Get to the stage at which you add cables to the construction.
Step 3. Add cables, but continue clicking on the construction with a cable in your hand.

The construction will continue depleting cables from your cable coil even if the cables it needs are already in place.

**Comment by Zumorica** [comment]
Can't replicate, can you give me more details as to how you did this?

**Comment by TimrodDX** [comment]
I just tried it again building a PA, and it looks like it might just be a lag thing - what happens is sometimes if I click on a part that needs wires it'll take more even if it already has some. This happens in both the initial wiring stage and later on when you put wires in the finished parts.

**Comment by Zumorica** [comment]
not really a thing anymore, could never replicate
