### ISSUE TITLE
Using a gun disables click-and-drag actions

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#3527]
How to reproduce:

1. Pick up any gun, I know this happens with the Cargo SMG.
2. Put the gun down or stow it.
3. You will no longer be able to loot people via clicking and dragging (right-click -> strip still works)
4. This also seems to apply to putting people in disposals or onto the meat spike.
5. This happens regardless of combat mode/disarm status, and occurs even if both are off.

**Comment by AJCM-git** [comment]
Cant reproduce
