### ISSUE TITLE
Parallax additions

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#3528]
Currently parallax loads in the layers and bakes it all into the 1 texture. Ideally it'd support:
* Multiple layers being drawn with different speeds.
* Some layers being generated and some being existing sprites
* Being able to set a colour (random or otherwise) for the above.

See https://github.com/BeeStation/BeeStation-Hornet/blob/87cd7d8345cf0e9b7b06bc55102b2cb8ff8ed650/code/_onclick/hud/parallax.dm for a general idea on what it needs to support.

**Comment by mirrorcult** [comment]
Addressed by #7654
