### ISSUE TITLE
Action hotbar UI looks wrong when grid container only has one column

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#3533]
![image](https://user-images.githubusercontent.com/6766154/110208665-d474ab80-7e88-11eb-8117-9bf64c0b44f4.png)

**Comment by ShadowCommander** [comment]
It seems to happen when the window is too short. It'll do the same with double row when making the window shorter.

**Comment by Zumorica** [comment]
True, screenshot of that:
![image](https://user-images.githubusercontent.com/6766154/110208723-29b0bd00-7e89-11eb-8575-37ec71593b75.png)
