### ISSUE TITLE
Protolathe needs recipes

### ISSUE THREAD

**Issue by Peptide90** [space-wizards/space-station-14#3544]
## Description

As title suggests, protolathe needs recipes for machine boards etc and needs tied to research at some point.

Already existing issues for lathes needing a refactor so could play into that. Plus we have more electronics to add.
**Screenshots**

**Additional context**

For tag purposes. Lathe

**Comment by Peptide90** [comment]
#328 linked

**Comment by PaulRitter** [comment]
Question would be if we want to produce machine boards using the lathe or if we should go the /vg/-way of having a seperate curcuit printer

**Comment by Zumorica** [comment]
I think that in the future we should absolutely have a circuit printer. But given lathes need a refactor, for now we should just use the protolathe.

**Comment by Peptide90** [comment]
Is this sufficiently covered now that research is in etc? 

Could be replaced with a feature request for circuit board printer?

**Comment by PaulRitter** [comment]
> Could be replaced with a feature request for circuit board printer?

yes, probably
