### ISSUE TITLE
Picking up a pulled object breaks your hands and hurls you into space

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#3551]
How to reproduce:

Step 1. Drop an item that you can normally hold in your hands. Your PDA will work just fine.
Step 2. Ctrl + Click to pull the item.
Step 3. Switch to the hand you're not using to pull the item.
Step 4. Pick up the item you are currently pulling without dropping the pull.

Expected behavior would be for the pull to cease as you no longer have anything to pull.

Instead, you get into a softlock situation where you can't move (you'll automatically warp back to wherever the pulled object was after a single step), can't use your hands (can't drop the item, can't stop the pull) and after a minute or so will be warped to space.

**Comment by SweptWasTaken** [comment]
Closing to add to physics megathread - #3464.
