### ISSUE TITLE
There's an ammo thing at 0,0 that cant be picked up

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#3554]
## Description
whats he doing there

**Screenshots**

![image](https://user-images.githubusercontent.com/19853115/110251686-e44ec700-7f3e-11eb-8935-182130c36cf8.png)

**Additional context**

**Comment by SweptWasTaken** [comment]
That's a battery? Are you sure that's an issue on master or is it just server-based?

**Comment by mirrorcult** [comment]
both

**Comment by SweptWasTaken** [comment]
![image](https://user-images.githubusercontent.com/49448379/110251775-fbf77100-7f79-11eb-9cc9-1ce623f477dc.png)

**Comment by SweptWasTaken** [comment]
Strange, this is on master, looks like it's a random entity each time?

**Comment by mirrorcult** [comment]
im pretty sure this is serv3 related since I think I got it after that got merged

**Comment by SweptWasTaken** [comment]
So look at this. If you check the armory you can see that the tasers and the SMG don't have a mag in them.

![image](https://user-images.githubusercontent.com/49448379/110251856-7fb15d80-7f7a-11eb-9e22-56ca8ea5b33b.png)

Yet in the saltern.yml...

```yaml
- uid: 4254
  type: SmgWt550
  components:
  - parent: 853
    pos: -8.457222,21.596565
    type: Transform
  - maxAngle: 59.99999999999999
    type: MagazineBarrel
  - containers:
      MagazineBarrel-chamber: !type:ContainerSlot {}
      MagazineBarrel-magazine: !type:ContainerSlot
        ents: 4255
    type: ContainerContainer
- uid: 4255
  type: MagazinePistolSmgTopMounted
  components:
  - parent: 4254
    type: Transform
  - containers:
      RangedMagazine-magazine: !type:Container {}
    type: ContainerContainer```

So are magazines in weapons not saving properly? Could this be another issue like the FoodContainer plates spawning from 0,0 and teleporting into a player's hand except the other way around?
