### ISSUE TITLE
Cargo Telepad Unpowered at Round Start

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#3556]
No real steps to reproduce, the telepad just begins the round unpowered. Unlike the previous issue involving the telepad, it does not start unanchored. Moving the telepad doesn't seem to power it up either.

![image](https://user-images.githubusercontent.com/7907891/110253762-128dd000-7f5a-11eb-816b-ebdcb5d12777.png)

**Comment by mirrorcult** [comment]
supposedly closed by #3559
