### ISSUE TITLE
Unwrenching things won't unpower it

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#3558]
## Description

You can also drag it around and rewrench it. This is when stuff is set to `bodytype: Static`

**Screenshots**

![Content Client_2021-03-07_13-05-39](https://user-images.githubusercontent.com/49448379/110254874-f2c1d080-7f88-11eb-829d-c51e7b8e77b8.png)
**Additional context**

**Comment by metalgearsloth** [comment]
Fixed by https://github.com/space-wizards/RobustToolbox/commit/dc3af45096e8f513638278f0427e16902f5a544b
