### ISSUE TITLE
Randomizing your character can have their age be randomized outside the limits

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#3560]
## Description

**Screenshots**

![unknown](https://user-images.githubusercontent.com/49448379/110255401-6369ec80-7f8b-11eb-9215-cf69391fecc6.png)
**Additional context**

**Comment by Peptide90** [comment]
Rimworld moment. Biological Vs chronological. Might not play well with species either if we set a limit unless it's in lore / law somewhere.

**Comment by SweptWasTaken** [comment]
> 
> 
> Rimworld moment. Biological Vs chronological. Might not play well with species either if we set a limit unless it's in lore / law somewhere.

I set a limit, it's just broken on clientside now. It shows you can enter whatever age but on server-side it'll change it from 18-120 (Within the limits)
