### ISSUE TITLE
Trying to buckle to a chair teleports you to the bar

### ISSUE THREAD

**Issue by ike709** [space-wizards/space-station-14#3564]
## Description
1. Try to buckle yourself to a chair via clickdrag, or just click a chair.
2. Get teleported to the bar.

**Screenshots**
https://streamable.com/8bfn05

**Additional context**

**Comment by mirrorcult** [comment]
dupe (though i dont blame you for not noticing), new physics-related bugs will go here https://github.com/space-wizards/space-station-14/issues/3464

**Comment by mirrorcult** [comment]
keeping open so it can get closed by a PR
