### ISSUE TITLE
Add a disposable tag

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#3576]
Just like recyclable or whatever it should be cleaner than just checking for storeable or IBody IMO.

**Comment by SweptWasTaken** [comment]
I'll take this

**Comment by DrSmugleaf** [comment]
I did this originally in the first disposals pr but it was decided against because it was considered to be redundant.

@PJB3005

**Comment by metalgearsloth** [comment]
Disposals checks for IBody which means if Nar'sie has a body then you can disposals it so it at least needs improvement at some point.

**Comment by juliangiebel** [comment]
I would rather go for a not disposable tag (or component as we are using components as tags afaik) tbh. So we can exclude things that are storable but shouldn't be able to be disposed.

**Comment by juliangiebel** [comment]
What's the verdict on this?
Should we implement a tag/component for preventing things to be put into disposals?

**Comment by EmoGarbage404** [comment]
we have both trash and recyclable tags so this is covered
