### ISSUE TITLE
Remote Action possible while locked in locker

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#3589]
How to reproduce:

Step 1. Get locked into a locker. This presumably would also work if welded into a locker, but as welding is currently broken I am unable to verify that this works. It also works if you teleport in via the cursed locker.

Step 2. Attempt to move. You can still move your camera, but will generate a "It's locked!" message every time you do so. If you move and then attack, you will be able to see the weapon attacking from wherever your camera is. You can also move any pushable objects from inside the locker this way. 

![image](https://user-images.githubusercontent.com/7907891/110409917-071fcf00-8056-11eb-90c4-38a876590403.png)

This also allows you to do things like potentially cause a welder tank explosion remotely in Engineering.

![image](https://user-images.githubusercontent.com/7907891/110410086-5665ff80-8056-11eb-9e90-5421f6da4a4e.png)

I was also able to remotely pick up objects after exploding the welder tank, and once I attacked the walls I was able to move remotely all the way to Arrivals from Engineering, at which point I tried remotely picking up an item and dropping it. Then I got shunted to nullspace.

![image](https://user-images.githubusercontent.com/7907891/110410524-03407c80-8057-11eb-9fa3-3396c95ebd9f.png)

**Comment by metalgearsloth** [comment]
1. Need to check locker's IRelayMoveInput and 2. HandleMobMovement needs to account for this (I don't think we can just do ActionBlockerSystem, probably just add an IsInContainer() check).

**Comment by TimrodDX** [comment]
I believe this has been fixed, and in any case the cursed locker is no longer on the map. Closing to avoid confusion.
