### ISSUE TITLE
Need a plate component

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#3600]
Requirements:
* ContainerSlot to hold food
* Increases nutrition gain from consumption (probably a multiplier of something like 1.25 for nutriment)
* Shatters on throw collision
* Plate sprite should be detached from the food sprite entirely

![image](https://user-images.githubusercontent.com/31366439/110436379-44449980-8108-11eb-8507-75c0e0129a1d.png)

**Comment by mirrorcult** [comment]
closed in favor of #3674
