### ISSUE TITLE
Need flaps

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#3608]
Flaps need adding in general but adding one to the chem table would help until we get doors to stop people raiding it for potassium bombs.

Should probably just have VaultImpassable collision layer and then Impassable mask maybe.

**Comment by SweptWasTaken** [comment]
What the hell is a flap lol

**Comment by metalgearsloth** [comment]
![image](https://user-images.githubusercontent.com/31366439/110572869-5f69e480-81ae-11eb-91ee-8a37adca5c75.png)

**Comment by ShadowCommander** [comment]
Usually chem and most other places have sliding glass doors.

**Comment by ike709** [comment]
Windoors should be feasible by ripping code from edge firelocks.

**Comment by metalgearsloth** [comment]
Assuming PhysShapeRect currently works post-physics 
![image](https://user-images.githubusercontent.com/31366439/110579550-297f2d00-81bb-11eb-912e-9ba2266ac28a.png)

**Comment by Peptide90** [comment]
Yeaah flaps are for cargomules n crates. Windoor is what we need.
https://tgstation13.org/wiki/Guide_to_construction#Windoor_.28Window-door.29

![]https://tgstation13.org/wiki//images/f/f7/Windoor.gif)

**Comment by juliangiebel** [comment]
Flaps are implemented already so this issue can probably be closed now
