### ISSUE TITLE
Throwable items (grenades) should default to throw

### ISSUE THREAD

**Issue by Peptide90** [space-wizards/space-station-14#3612]
## Description

When a grenade is activated the action should default to throw. Not that big a deal since shift + Q throws but it should reduce the amount of clicks where logical.

**Comment by mirrorcult** [comment]
this makes sense in SS13 where throw is a toggleable thing but I don't think we have that. we also don't have a button labeled "throw" on the screen at all times so it might be non-obvious that activating a grenade makes you throw it instead of drop it

**Comment by Peptide90** [comment]
> this makes sense in SS13 where throw is a toggleable thing but I don't think we have that. we also don't have a button labeled "throw" on the screen at all times so it might be non-obvious that activating a grenade makes you throw it instead of drop it

This is true, hadn't entirely thought of that. I guess this could be down to preference then. A "throw" overlay on hands could be a thing. Current way isn't bad and would teach people to get used to the controls (the hard way when a traitor blows themselves up)

**Comment by SweptWasTaken** [comment]
Nah, I think it's fine how it is.
