### ISSUE TITLE
Non-Human mobs aren't affected by guns

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#3616]
How to reproduce:

Step 1. Spawn any non-human mob. I've personally tested this with monkeys spawned from monkeycubes and with mice.
Step 2. Spawn any firearm. Tested with most of the traitor firearms (CR-20, Inspector, L6 SAW) as well as the cargo ones.
Step 3. Attempt to kill a mouse or monkey with overwhelming firepower. All of your shots will pass through without doing damage.

**Comment by moonheart08** [comment]
Fixed.
