### ISSUE TITLE
Dead mice aren't removed from ghost role list

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#3618]
How to reproduce:

Step 1. Be in a game where one or more mice dies, presumably to some kind of explosion or to being exposed to space.

Step 2. Attempt to become a mouse via the ghost roles list. Because the ghost roles list has every mouse in the station on it, it may take some time to find the dead ones.

Step 3. Become a dead mouse.

**Comment by AJCM-git** [comment]
This isn't reproducible anymore. Dead and in crit mobs are removed from the list now.
