### ISSUE TITLE
If you ghost while holding movement keys, your character will continue moving

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#3619]
## Description

**Screenshots**

![2021-03-11_14-06-13](https://user-images.githubusercontent.com/49448379/110861455-1309cc00-82b6-11eb-93ab-0aadedd67a26.gif)
**Additional context**

**Comment by Clyybber** [comment]
feature

**Comment by wcollins37** [comment]
I'll take a look at this

**Comment by dmnct** [comment]
Issue could not be reproduced anymore. Seems fixed

**Comment by Visne** [comment]
Definitely fixed.
