### ISSUE TITLE
Move interfaces and component messages to bus

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#3622]
Acruid's now added the component bus https://github.com/space-wizards/RobustToolbox/pull/1601

This means we can take more of an ECS approach to stuff and components can be more data-oriented (plus it also has the performance increase from not needing to iterate every component).

This mainly involves moving stuff like IAfterInteract out of components and on to systems instead so it will require a large amount of work to refactor everything. At the least the maintainers can police new things to ensure they're on the bus.

**Comment by ElectroJr** [comment]
See also #8422. Going by `Component.Initialize()` usage, there's only 45 or so components left to ECS.

**Comment by metalgearsloth** [comment]
I did dis.
