### ISSUE TITLE
Solar Parts and Solar Panels don't have names.

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#3633]
![image](https://user-images.githubusercontent.com/7907891/111011413-4193af80-8367-11eb-83fd-adf63dbf53b5.png)

The items from cargo show as "item" instead of having a name or description.

**Comment by mirrorcult** [comment]
this is because entity localization is fucked

**Comment by RemieRichards** [comment]
> this is because entity localization is fucked

*this is because serialization3 fucked entity localization by re-implementing it wrong.

**Comment by Peptide90** [comment]
Yeah same goes for the barricade. Was mentioned on my PR for them.
