### ISSUE TITLE
Storage windows open in the very top left of the screen

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#3647]
## Description
Not necessarily an 'issue' but I find it very annoying and would prefer if it spawned in the center or off to the side (as easy as just changing Open to OpenCentered or some other helper)

Furthermore, it spawns in the 'top left' of whatever the window size was when you first opened the game, so if you make the window bigger or smaller then it doesn't spawn in the top left anymore

**Screenshots**

![image](https://user-images.githubusercontent.com/19853115/111024481-3f981380-839c-11eb-9c0d-ad8ef8a01f07.png)

**Comment by ShadowCommander** [comment]
Unless UI has changed much, this just requires a one line replace `Open()` with `OpenCentered()` or some other spot.

**Comment by mirrorcult** [comment]
> 
> 
> Unless UI has changed much, this just requires a one line replace `Open()` with `OpenCentered()` or some other spot.

i was going to include that in #3648 but realized that, idk it might be contentious so I'll let people discuss where the windows should open by default
