### ISSUE TITLE
Mass-cloning with potential server crash still possible after clone time increase

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#3654]
I'm putting this issue back up because #3650 didn't solve the underlying problem first reported in #3389. 

![image](https://user-images.githubusercontent.com/7907891/111035098-ceca1900-83e6-11eb-889f-ba1fd1b2d477.png)

How to reproduce:

- Get the body of a braindead player into the cloner.
- Scan the braindead body
- Go to the cloning pod and attempt to clone the braindead player
- The cloner will still output as many failed clones (Urist McHands) as fast as you can click the button, leading to eventual lag and/or server crashes.

![image](https://user-images.githubusercontent.com/7907891/111035163-210b3a00-83e7-11eb-885d-8c346c030054.png)

![image](https://user-images.githubusercontent.com/7907891/111035166-27011b00-83e7-11eb-8657-b38a8470b11c.png)

Here, I spawned 36 Urists in under five seconds.

**Comment by mirrorcult** [comment]
oops, couldnt repro that specifically so i assumed it was just a timing thing, I'll fix this later

**Comment by TimrodDX** [comment]
This issue was fixed by Swept's recent cloning PR. There's a similar edge case issue that's got slightly different reproduction steps than this one - I'm going to close this and put up a second issue for that.
