### ISSUE TITLE
Emitters won't rotate under any conditions

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#3656]
![image](https://user-images.githubusercontent.com/7907891/111043169-1795c800-840f-11eb-850e-2ea02e38711e.png)

I don't know what broke this, but you can no longer:

- Rotate emitters even when unwelded via the right-click -> rotate verb
- Rotate emitters by pulling them (they'll stay in the south-facing position at all times)

**Comment by mirrorcult** [comment]
fixed in my emitter pr thats open

**Comment by mirrorcult** [comment]
nvm it does not, this doesn't just happen to emitters but all rotatable objects, nothing can rotate right now
