### ISSUE TITLE
Light fixtures can't be constructed on surfaces that don't face south.

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#3659]
![image](https://user-images.githubusercontent.com/7907891/111053425-96036180-8431-11eb-99ac-76bf7c14adde.png)

How to reproduce:

- Go into construction mode and attempt to build a light fixture. Either kind will work.
- The light fixture will only appear on south-facing walls (see picture) even though there's clear support for them on east-west walls and the northern side of walls.
- Expected behavior would be for the construction to snap to wall surfaces so it can be placed on any free wall surface.

**Comment by ShadowCommander** [comment]
Light fixtures can be constructed on any wall face. You just need to rotate the light construction ghost using `middle click`.
