### ISSUE TITLE
Disposals outlets can cause pressure damage to nearby players under certain circumstances

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#3660]
I've only seen this once, but here's how it works as far as I know:

- Have a disposal outlet that is full or has items in it prior to a room being exposed to space (such as the bar)
- Repair the breach and let air back in
- You'll still take pressure damage standing near the disposal outlet, even though the breach has been fully repaired.

The disposal outlet in the bar also seems to act strangely in that sometimes it'll cause the fire lock next to it not to trigger in the event of a breach, and standing in the fire lock is fine even if the room beyond is spaced.

**Comment by mirrorcult** [comment]
firelock thing is unrelated and i thiiiink known

**Comment by mirrorcult** [comment]
i dont think this has been reported once since, tried to repro and couldnt
