### ISSUE TITLE
Behavior on thrown items landing is a little weird

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#3661]
## Description
Since items bounce off of stuff now stuff like drinking glasses, plushies, etc don't shatter when they hit entities but only when they stop moving after the bounce which is strange. Feels like ILand should be changed to IThrowCollide or something

**Screenshots**

https://user-images.githubusercontent.com/19853115/111055041-28563600-842f-11eb-980c-3d659460e8e9.mp4

**Comment by metalgearsloth** [comment]
Most stuff for ILand should probably also pop on IThrowCollide yeah. Given componentbus is in it's probably better to do a refactor of it all instead of just messing with the interfaces.

You've also found my throwing shitcode because ILand is only checked when the body falls asleep.

**Comment by mirrorcult** [comment]
IMO ILand should get called when the velocity gets sufficiently low to make it less jank?

**Comment by SweptWasTaken** [comment]
This needs to be fixed asap since a lot of stuff uses it and it looks very goofy.

**Comment by AJCM-git** [comment]
This has been fixed
