### ISSUE TITLE
Need a component to break entity on collide / landing

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#3675]
Useful for plates and glasses. Should have a percentage chance to smash.

You'll also need a system subscribing to do additional behavior on smash as well (plates dropping their food and glasses spawning a puddle underneath).

**Comment by Zumorica** [comment]
So... Like the DamageOnLand component?

**Comment by metalgearsloth** [comment]
Yeah but it would also need triggering on IStartCollide as well

**Comment by AJCM-git** [comment]
We have a DamangeOnLand component now
