### ISSUE TITLE
SMGs in Cargo still have incorrect magazine type

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#3678]
![image](https://user-images.githubusercontent.com/7907891/111210801-0fbb5c80-85a4-11eb-9ec3-002fb433b9ff.png)

The SMGs in Cargo have been correctly changed to Drozds, but the .40 magnum magazines that come with them are incompatible. The magazine closest to the guy in the CE outfit in the screenshot is the incorrect magazine, while the one in front of it is the compatible magazine that comes with the gun.

**Comment by Peptide90** [comment]
Happy to be assigned this if nobody has done it
