### ISSUE TITLE
Fix the spaghet that is collision layers

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#3682]
https://discord.com/channels/310555209753690112/770682801607278632/819085060862902334

![image](https://user-images.githubusercontent.com/31366439/111259523-30061c80-8673-11eb-99ec-f0b5edb8e0f1.png)

![image](https://user-images.githubusercontent.com/31366439/111258900-00a2e000-8672-11eb-8796-769ede9922dc.png)

![image](https://user-images.githubusercontent.com/31366439/111258999-2e882480-8672-11eb-9ffb-98e35cc2803c.png)

IMO:
* Layers should be impassable rather than passable so stuff doesn't implicitly collide.
* Layers should generally be for collision only unless a particular raycast has an expensive predicate.
* Anything else should probably go with EntityManager's stuff (or whatever Acruid replaces PVS with) given items don't have collision unless moving and won't show up in physics lookups.

As such here's a draft of what layers we need I think:
* Opaque. This isn't used for collision but it saves doing a lot of TryGets when raycasting.
* LowImpassable
* MidImpassable (from Impassable)
* HighImpassable
* GhostImpassable
* MapGrid
* AudioOcclusion, maybe

The limit is effectively infinite given it's backed by an int but adding more just bloats it so it'd be better to keep these as tight as possible.

Currently I have collision disabled for anything underplating (now the broadphase prunes anything that's not collidable) but if we really need it we can add it back in.

We might also need a MobImpassable as I can't see an easy way to have combat-mode enable / disable collisions when toggled; all I can see is using an ICollideSpecial but adding the layer would be significantly faster (and given these are mob collisions are very frequent).

**Comment by ShadowCommander** [comment]
So, basically the list I have in my mind is

- Humans
  - Vaulting
- Crabs/Cats/Dogs/etc
- Mice
- Birds

So I was thinking something like
Small, Low, Mid, High
where
Small is for mice going under doors
Low is for pets going under tables
Mid is for tables and low walls blocking humans
High is for vaulting and fliers. Though I'm wondering if vaulting should be this and fly should be a separate layer.

We also probably want something for bullets going through grills/girders.

**Comment by metalgearsloth** [comment]
We talked about it on disc and Small / Mid / High it is.

**Comment by DogZeroX** [comment]
Fixed by shadow
