### ISSUE TITLE
Vending machine interface needs a scroll bar

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#3687]
![image](https://user-images.githubusercontent.com/7907891/111359670-3049ec00-8662-11eb-824e-eaa7ab7ef57f.png)

Currently, if a vending machine has too many items in it, you can't get to all the items in windowed mode (and may not even be able to in fullscreen, depending on what your resolution is). Scroll bars would fix this.

**Comment by mirrorcult** [comment]
you should be able to scroll already? either way it shouldn't open that large by default so I'll fix that

**Comment by AJCM-git** [comment]
This has been fixed. Vending machines have scrollbars
