### ISSUE TITLE
Airlock deconstruction doesn't show the proper steps

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#3695]
![image](https://user-images.githubusercontent.com/7907891/111511905-8df33c80-8725-11eb-8ad9-9211b726418c.png)

How to reproduce:

- Right click on an airlock and begin deconstruction.
- The examine instructions will correctly tell you to weld the airlock and open the panel.
- On the next step, the examine verb won't tell you what to do (cut the power and use a crowbar)
- All other steps (including deconstructing the airlock assembly) work fine.

**Comment by AJCM-git** [comment]
It tells you the steps now
