### ISSUE TITLE
Gun magazines go over playmodel when dropped on floor.

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#370]
![image](https://user-images.githubusercontent.com/49448379/65733718-c829d380-e084-11e9-8985-1839b57bad85.png)

**Comment by Zumorica** [comment]
Related: #651

**Comment by ShadowCommander** [comment]
Currently everything goes over the player model when dropped.

**Comment by PrPleGoo** [comment]
```
public enum DrawDepth
{
...
        Mobs = 8,
        Items = 9,
...
}
```
This seems to be desired behaviour. Should I switch the values?
