### ISSUE TITLE
Crafted stacks don't sum up in hands and drop on the floor

### ISSUE THREAD

**Issue by Macoron** [space-wizards/space-station-14#3704]
## Description

Steps to reproduce:
1. Take metal sheet in one hand
2. Go to crafting menu and try craft metal rod
3. Two rods will be placed in your free hand
4. Do it again

Expected: The stack amount will be increased by two rods.
Actual: Two new rods will be dropped on the floor as separate entity.

**Additional context**

This is really annoying when you need to craft a lot of rods or tiles.

**Comment by ShadowCommander** [comment]
Would be part of hands refactor #3477
