### ISSUE TITLE
The entity/floor placement overlay is affected by darkness

### ISSUE THREAD

**Issue by DamianX** [space-wizards/space-station-14#372]
You might not be able to tell but there's supposed to be a green square here:
![image](https://user-images.githubusercontent.com/6307265/65801556-a8c0a280-e179-11e9-9460-3c27d5825cf7.png)

**Comment by PaulRitter** [comment]
afaict this was fixed

**Comment by Zumorica** [comment]
This is still an issue, just tested on EUW2

**Comment by PaulRitter** [comment]
frick

**Comment by SweptWasTaken** [comment]
Fixed. Closing.
