### ISSUE TITLE
Able to move while in disposal pipes

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#3722]
This one's kind of tricky to explain, but here's how to reproduce. Credit to Miriam for finding it.

Step 1. Get into a disposals outlet and flush yourself.

Step 2. While you are being flushed, hold any directional input. Your camera will temporarily go to nullspace.

Step 3. Once the camera comes back from nullspace, you'll be out of the disposal pipe somewhere near where you started holding down the input. It's possible to get into security this way without breaking any windows or hacking any doors.

**Comment by mirrorcult** [comment]
probably physics-related?

**Comment by metalgearsloth** [comment]
ActionBlockerSystem.CanMove should check this maybe.

The check is ultimately in UseMobMovement so fixing this also fixes the cursed locker issue.

**Comment by AJCM-git** [comment]
This doesn't happen anymore.
