### ISSUE TITLE
Guns don't work

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#3723]
I'm not sure what broke it, but guns don't work anymore, at least on players.

How to reproduce:

Step 1. Acquire gun
Step 2. Acquire partner
Step 3. Aim gun at partner and fire repeatedly
Step 4. Marvel as your partner is completely unharmed

**Comment by Zumorica** [comment]
*probably* #3610's fault

**Comment by SweptWasTaken** [comment]
> 
> 
> _probably_ #3610's fault

I swear I tested these, it might be something to do with ICollideSpecial
