### ISSUE TITLE
Melee weapon collision should take bounding boxes into account.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/space-station-14#373]
Right now it's just using `GetEntitiesInArc` which purely goes by entity position.

**Comment by Acruid** [comment]
I suggest making a new struct to hold your Arc/Sector/Cone (whatever we are calling it), then we need two functions:

Getting the bounds of a Sector, for easy Box-Box tests:
https://math.stackexchange.com/questions/45303/how-to-get-rectangular-size-of-arbitrary-circular-sector

Box-Sector intersection test:
https://stackoverflow.com/questions/21132816/intersection-between-rectangle-and-a-circle-sector-in-libgdx

After all that, you need to change the melee weapon Fire code to use `GetEntitiesIntersecting` with the box, then call the intersection test to see if the other object really got hit.

**Comment by PJB3005** [comment]
Oh I forgot to close this. I changed the melee code to use 5 raycasts instead, which works pretty decently.

Though I guess "proper" intersection tests couldn't hurt.

**Comment by Acruid** [comment]
Melee weapons do not use collision, so this is not an issue anymore.
