### ISSUE TITLE
Floating windows possible if certain actions done at same time

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#3730]
![image](https://user-images.githubusercontent.com/7907891/112734316-610c0a00-8f1b-11eb-9b5f-1ea251dbdacb.png)

How to reproduce:

- Have a low wall placed with no window on it. You'll need two people to reproduce.

- Have person one use a welder on the low wall while person two attempts to construct a window on it.

- There will be a floating window with no wall underneath it. As far as I can tell it doesn't block atmos, so the game knows there's no wall under it.

**Comment by TimrodDX** [comment]
A clarification: the easiest way to reproduce is to have the person with the welder start welding, and then the person with the glass build the window.

**Comment by AJCM-git** [comment]
Not possible anymore since we dont have low walls
