### ISSUE TITLE
Items can be pulled through windows, even if you can't actually reach them.

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#3733]
![image](https://user-images.githubusercontent.com/7907891/112739029-aa218580-8f3e-11eb-9cdd-fbdc71d5556b.png)

How to reproduce:

- Find an object that is next to a window. I believe as long as it's within one tile you can do this. Possible locations on Saltern include the bedsheets in the brig cells, the chairs in the medbay lobby, and the chair behind the desk in R&D. You could also do this in cargo by putting something on the table by the window.

- Do the pull shortcut (ctrl + click) and pull the item. You'll be able to pull it through walls, though pulling the bedsheet in the corner brig cell may cause your camera to nullspace while pulling.

- You can use this to pull items to a hole (such as an open airlock or a desk) where you can pick them up.

**Comment by metalgearsloth** [comment]
Pretty sure this was fixed.
