### ISSUE TITLE
Implement Vision / Fog of war

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#374]
You shouldn't be able to see through opaque walls or doors.

**Comment by tentekal** [comment]
I've kind of wanted to do this for a while but I'm not sure if I'm capable. 

I guess I'll take it until I'm in over my head ¯\_(ツ)_/¯

**Comment by PJB3005** [comment]
The most bare bones implementation of this can probably be done in an overlay.

That said, actually implementing the drawing isn't possible without having Clyde draw arbitrary triangles... which it can't do yet.

**Comment by Injazz** [comment]
it is done so might close it
