### ISSUE TITLE
Refactor StorageFillComponent into a more generic ContainerFillComponent

### ISSUE THREAD

**Issue by PaulRitter** [space-wizards/space-station-14#3743]
imo storagefill should be refactored into

-  a generic containerfill that takes containerid, as well as prototypes to fill
-  a inherited (yes its not nice, but it means less work for yaml monkeys) storagefill that just has the containerid hardcoded to "storagebase" (the storagecontainer id)

**Comment by ShadowCommander** [comment]
Fixed by #11772
