### ISSUE TITLE
Spam examining overlapping objects can sometimes mess up the descriptions

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#3745]
## Description

**Screenshots**

![2021-03-29_15-10-35](https://user-images.githubusercontent.com/49448379/112906407-a9722600-90db-11eb-9e08-4f7a1839e2b1.gif)

**Additional context**

**Comment by AJCM-git** [comment]
Cant reproduce anymore

https://user-images.githubusercontent.com/60196617/140632565-a020c8ed-c0bb-46f9-9d50-fdee96754f21.mp4

**Comment by ShadowCommander** [comment]
Still happened two weeks ago, so I'll try to see if I can reproduce it still.

**Comment by SweptWasTaken** [comment]
I couldn't reproduce it at all so I think it's fine.
