### ISSUE TITLE
Player is very strong

### ISSUE THREAD

**Issue by Miniwoffer** [space-wizards/space-station-14#375]
Plz nerf powerwalking!
![recording](https://user-images.githubusercontent.com/6328564/66241869-627ebc80-e700-11e9-9b6d-69a4b3e9d329.gif)

**Comment by ShadowCommander** [comment]
This was also pointed out a few days ago.
https://discordapp.com/channels/310555209753690112/560845886263918612/628263053938524161

Basically, players are supposed to be able to push multiple lockers, but it should get incrementally slower for each one pushed.

**Comment by PrPleGoo** [comment]
Working as intended, what's the issue here?

**Comment by PrPleGoo** [comment]
Alright I've changed the friction code around resulting in not being able to push more than 1 locker. I can reduce the friction on floors to counteract this or reduce mass of lockers or increase mass of the spaceman. 
How many lockers do people want to push in most cases?

**Comment by Miniwoffer** [comment]
When trying to imagine pushing a locker that size (about human width) i would say 1 or at most 2.
