### ISSUE TITLE
Inertial rotation persists after items are picked up

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#3752]
![image](https://user-images.githubusercontent.com/7907891/113038130-28ab3c80-9164-11eb-80fd-04c0b8406280.png)

![image](https://user-images.githubusercontent.com/7907891/113038152-2f39b400-9164-11eb-8517-68b6be695651.png)

![image](https://user-images.githubusercontent.com/7907891/113038168-3660c200-9164-11eb-8b03-9e4502b58713.png)

![image](https://user-images.githubusercontent.com/7907891/113038185-3b257600-9164-11eb-9cee-2c3ab6c87f75.png)

How to reproduce:

- Pick up an item
- Throw the item and watch as it rotates
- Pick it up again and drop it, the item will still be rotated instead of placed down flat again.

**Comment by metalgearsloth** [comment]
Closed in https://github.com/space-wizards/RobustToolbox/pull/1653
