### ISSUE TITLE
Refactor LatheDatabase and GalacticMarket

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#3762]
## Description

These lists embedded in the prototype are terrible. Just makes updating them a chore. Would be good even to just have them separated from the prototype and in /Catalog.

**Additional context**

AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
![image](https://user-images.githubusercontent.com/49448379/113095317-ba598f00-91e2-11eb-8868-c315cc8c30a9.png)

**Comment by mirrorcult** [comment]
fixed by #8686, at least fo galactic market

**Comment by EmoGarbage404** [comment]
galactic market is kil and lathe databases are fine.
