### ISSUE TITLE
Computers can still pin people when unwrenched

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#3769]
Originally reported by hubismal#5912

Reproduction:

- Unanchor and rotate a computer so that it is facing south (screen facing north)
- Anchor the computer again
- Unanchor the computer a second time, it will now have broken physics and pin people to walls if touched or pulled.

**Comment by AJCM-git** [comment]
Cant reproduce anymore

https://user-images.githubusercontent.com/60196617/140632655-0aeb92ec-9a3a-469d-a1a9-246b70d3120d.mp4
