### ISSUE TITLE
Strange flashes when pushing against pulled objects momentum

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#3771]
## Description

Idk why this happens. The gif won't embed since it's so big.

**Screenshots**

https://cdn.discordapp.com/attachments/790656972801572905/826922144419676211/2021-03-31_13-40-28.gif

**Additional context**

**Comment by AJCM-git** [comment]
Pulled objects dont have much momentum anymore and you dont collide with them so this is out of date

**Comment by metalgearsloth** [comment]
It can still happen but a combination of camera lerp + non-subtick physics should fix it.
