### ISSUE TITLE
Weightlessness tile friction

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#3775]
Box2D has something called damping (linear and angular) for slowly decreasing an object's velocity over time (to avoid an object moving forever unnecessarily).

Currently no tile friction is applied to a weightless object regardless of whether it's on the station or not but IMO there should be a slight amount of tile friction for objects on the station just so they come to rest faster as an optimisation. We could also bump up lineardamping from 2% to either 5 or maybe 10% as well. There's another issue similar to this but it's about increasing tile friction generally (which would also need throwing to be fixed).

**Comment by 20kdc** [comment]
Some notes from the future:
1. this actually appears to have been introduced
2. it's pretty much the factor that broke meteor swarms
3. The damping is so high that someone attempts to fling something into space and fails because it's basically an anchor
