### ISSUE TITLE
Inventory UI bug <3

### ISSUE THREAD

**Issue by MehimoNemo** [space-wizards/space-station-14#3783]
Item pile pop-ups are overlayed on top of inventory UI, clicking on an item from a pile will go through to the bottom layer and hit the items in your inventory.
Attempting to pick something up causes you to accidently unequip items.

**Comment by AJCM-git** [comment]
Cant reproduce anymore

https://user-images.githubusercontent.com/60196617/140632848-57656273-cc8f-4908-a043-aaa8cef43e97.mp4
