### ISSUE TITLE
Vending machine textures should all be Baystation style

### ISSUE THREAD

**Issue by Visne** [space-wizards/space-station-14#3787]
We have some vending machines from Bay, some from Eris, some from somewhere else, and I believe the mining vending machine doesn't even have a texture (might be others as well).

Ideally all vending machines are either ported from Bay or sprited if Bay does not have a texture.

**Comment by SweptWasTaken** [comment]
Nah, I don't mind the mish-mash of vending machine sprites because it makes me think that they all come from different manufacturers. Some of them could be improved with other sprites, but i'm happy with how they look.
