### ISSUE TITLE
Space Tiles Exist

### ISSUE THREAD

**Issue by clusterfack** [space-wizards/space-station-14#379]
I'm not really sure how space tiles are brought into existence in the first place, maybe its just on demand when the client requests info on them. But space tiles shouldn't have any reason to exist.

How it should work: 
- The map on which the grids are placed should itself define the appearance for any tiles which don't have a grid. 
- Interactions with tiles in general should be minimized
- For space specifically I think there is already a star scroller somewhere to control what the space background looks like
- A global quadtree should control the locality of things in space vs a local grid quadtree for things on grids

**Comment by YotaXP** [comment]
I wouldn't say that space tiles exist.  It's just that any tile with the special `tileId` of 0 is nothingness.  When you query a tile that doesn't exist, you're just told that the tile at that location has a `tileId` of 0.

**Comment by clusterfack** [comment]
Well it seems space tiles do not, in fact, exist then.
