### ISSUE TITLE
"Cooked" component

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#3809]
## Description

Something that would increase the nutrient value of any dish and change a sprite or color of a sprites layer.

**Comment by mirrorcult** [comment]
can you elaborate on this a bit? like just a basic component that allows something to be cooked to increase its nutriment and sprite?

**Comment by SweptWasTaken** [comment]
> 
> 
> can you elaborate on this a bit? like just a basic component that allows something to be cooked to increase its nutriment and sprite?

Yes. When you're not making a specific dish in the microwave/cooking machine/fire, have the item become "cooked" by applying a brown layer to it. (This can be substituted for a unique sprite too).

This would also be useful for deep-frying and burned/overcooked things.

This component would also add something on to the name and description of the item such as "Cooked" or "Deep-fried".

**Comment by Peptide90** [comment]
Just to add some notes. I believe the component should have a options for prefix, suffix and appearance.

Prefix and suffix giving you a field to add "fried", "cooked", "steamed" etc and insert this relevant to the name but also add to the end of the description "this one is xxxx" xxxx being the adjective.

Appearance would add a layer also relevant as swept said such as making it fuzzy and brown for deep fried for example or golden brown in the case of pastry.

This could even just be condensed into one line I imagine where you'd give it type: cooked then have a field for fried etc which will affect all of the above without having to define eac one. This would leave space for other fields like nutrient amount.

**Comment by mirrorcult** [comment]
this is more or less superseded by the other cooking issues and planned cooking refactor, needs more discussion on the specifics
