### ISSUE TITLE
Power Cell battery charge level visualiser doesn't update during recharge

### ISSUE THREAD

**Issue by Peptide90** [space-wizards/space-station-14#3815]
## Description

To put simply when you drain a power cell which has the recharge ability it will go to empty state where it flashes but during the recharge the battery level will not go back up to indicate it has charged. It only updates when the cell is activated somehow again.

The example gif below is after I have added recharge to a cell used in the hardsuit helmet. I let it drain to 0 then the recharge starts but this is not indicated at all until I activate the light again which it jumps to its current state which is at that point (after a wait period) full charge.
**Screenshots**

![empty cell glitch](https://user-images.githubusercontent.com/78795277/113775229-507c4080-9720-11eb-863e-cb28fb9191d6.gif)

**Comment by ElectroJr** [comment]
#6579 will fix this for energy weapons, but not flashlights, though the solution is probably similar.
