### ISSUE TITLE
Objects cast shadows on themselves

### ISSUE THREAD

**Issue by clusterfack** [space-wizards/space-station-14#382]
Objects should cast shadows coming from themselves, rather than having a shadow directly cover themselves, this prevents opaque from ever being illuminated.

**Comment by PJB3005** [comment]
I figured out a solution to this. Using unclosed & culling occlusion polygons this can be solved. All it needs is a smooth walling system.

Basically, every "open" wall face gets an unclosed 2-point occlusion polygon covering the entire wall. Set the line's points in the correct order according to a cull mode and the light can *enter* from one side but not exit. The result?

![image](https://user-images.githubusercontent.com/8107459/41206784-21ce2598-6d0a-11e8-9193-058d15c81b63.png)
