### ISSUE TITLE
Motherboard serial numbers aren't a reliable hardware ID for bans.

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#3821]
![image](https://user-images.githubusercontent.com/7907891/113917553-566d3280-97af-11eb-9cf1-b3980c75ac83.png)

As I understand it, right now SS14 is using motherboard serial numbers as a hardware ID for enforcing bans. The problem is that motherboard serial numbers are notoriously unreliable - they're often not put in at all (or are a non-serial text string). Here's a couple of examples from the Discord:

![image](https://user-images.githubusercontent.com/7907891/113917682-7d2b6900-97af-11eb-96a1-b9cede989b3d.png)

![image](https://user-images.githubusercontent.com/7907891/113917716-874d6780-97af-11eb-8374-91d46e956b04.png)

![image](https://user-images.githubusercontent.com/7907891/113917745-93392980-97af-11eb-9af6-3a50bbda0a12.png)

There's a couple of very common ones, such as "To be filled by O.E.M." or simply having nothing at all in the serial number field. This means that people can potentially be hit with a ban meant for someone else because their motherboard serial number (or lack of one) is the same.

It would probably be better to explore an alternate avenue for getting a hardware ID.

**Comment by moonheart08** [comment]
It's likely advisable to build it from a hash of multiple values.
For _all platforms_, I'd suggest: CPU info (Management data on windows, Subset of /proc/cpuinfo on linux, namely excluding information about clock rate, bogomips, and online cores), amount of installed RAM, boot drive size, MAC Address, etc.

**Comment by SweptWasTaken** [comment]
> 
> 
> It's likely advisable to build it from a hash of multiple values.
> For _all platforms_, I'd suggest: CPU info (Management data on windows, Subset of /proc/cpuinfo on linux, namely excluding information about clock rate, bogomips, and online cores), amount of installed RAM, boot drive size, MAC Address, etc.
> NOTE: CPU info in particular is quite coarse-grained, but beyond the ability of the average user to change.

What about for MacOS?

**Comment by moonheart08** [comment]
> > It's likely advisable to build it from a hash of multiple values.
> > For _all platforms_, I'd suggest: CPU info (Management data on windows, Subset of /proc/cpuinfo on linux, namely excluding information about clock rate, bogomips, and online cores), amount of installed RAM, boot drive size, MAC Address, etc.
> > NOTE: CPU info in particular is quite coarse-grained, but beyond the ability of the average user to change.
> 
> What about for MacOS?

On MacOS, due to how similar all devices are, most of this won't be useful for distinguishing between systems.
I have too little experience with it to really say, unfortunately.

**Comment by PJB3005** [comment]
We can access x86 CPUID with zero hassle because .NET 5 has an intrinsic for it now. 

MAC address is too easy to change AFAIK.

**Comment by mirrorcult** [comment]
we arent using this for hwid anymore
