### ISSUE TITLE
Picking up thrown lights parents them to you when they break

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#3823]
Really easy to replicate.

![image](https://user-images.githubusercontent.com/31366439/114024152-0f6a6480-98b7-11eb-86a9-e98f2a63cc3b.png)

These should drop to the ground instead and attach to grid / map.

**Comment by AJCM-git** [comment]
Cant reproduce anymore. Broken light tubes or broken glasses don't parent to you if you threw them anymore
