### ISSUE TITLE
Map tiles stop snapping to the grid if you go beyond the map's edge

### ISSUE THREAD

**Issue by ike709** [space-wizards/space-station-14#3830]
## Description
If you attempt to place a tile beyond the furthest edge of the map in any cardinal direction, the tile placer will no longer snap to the grid. See the video below for an example.

**Screenshots**
https://streamable.com/c31nbf

**Additional context**

**Comment by Absolute-Potato** [comment]
Not necessarily a full solution, but I found that dragging out with lines by shift clicking helps a lot. (works with control clicking for filling areas, too)

**Comment by ike709** [comment]
Apparently the grid isn't expanding properly? /shrug

**Comment by ShadowCommander** [comment]
Fixed by https://github.com/space-wizards/RobustToolbox/pull/1724
