### ISSUE TITLE
Items can be thrown through or into walls and windows if aimed precisely

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#3841]
This was originally reported by Nyaronock#0296 on Discord.

https://cdn.discordapp.com/attachments/675078881425752124/831339983804825600/Space_Station_14_2021-04-12_21-15-37.mp4

https://cdn.discordapp.com/attachments/675078881425752124/831342652883599361/Space_Station_14_2021-04-12_21-35-06.mp4 

I've been unable to reproduce this personally, but it appears that if you have pixel-perfect or near-pixel-perfect positioning, you can throw items through seams in walls and windows. Some items will instead be thrown into the wall and can be picked up from either side.

**Comment by metalgearsloth** [comment]
Moving to Robust as it's related to CCD https://github.com/space-wizards/RobustToolbox/issues/1693
