### ISSUE TITLE
Ejecting from medical scanner puts you inside its hitbox, making it impossible to move.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/space-station-14#385]

**Comment by Sauberstaub** [comment]
Should it act similar to SS13? Where exiting many machines places you on the same tile as the machine, superimposed on it.  
I don't know how this is done in SS13 to be honest. What are the options? Something like one-way-collision, where you can leave the hitbox but cannot enter it.

**Comment by PJB3005** [comment]
SS13 uses one way collision, yes.

**Comment by Sauberstaub** [comment]
Oh. I dunno how to implement that into the collidable component in ss14. 🤷‍♀

**Comment by partyaddict** [comment]
Should mention that it also disallows you to use guns after you eject from one
