### ISSUE TITLE
Projectiles and thrown items originate way behind moving players.

### ISSUE THREAD

**Issue by MehimoNemo** [space-wizards/space-station-14#3851]
## Description
Bullets and thrown items originate from where the player was rather than is. To replicate, shoot a gun/throw an item forwards whilst walking in the same direction.

**Screenshots**
https://cdn.discordapp.com/attachments/611773758331420703/832409681057284166/Inkedbruhbm_LI.jpg

**Comment by mirrorcult** [comment]
caused by a lack of prediction for guns or throwing

**Comment by metalgearsloth** [comment]
We already have issues for predicting this stuff
