### ISSUE TITLE
Vending machine windows open at minimum dimensions for a frame

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#3871]
![image](https://user-images.githubusercontent.com/31366439/115141892-18f78780-a082-11eb-9685-eb033c767ff5.png)

Yes I did screenshot this.

**Comment by Visne** [comment]
Whats the expected result? A normal sized window with no products? A small text saying "Empty."?

**Comment by PJB3005** [comment]
Presumably the latter, yeah.

**Comment by SweptWasTaken** [comment]
Replicated the same thing with the Arcade UI.
![image](https://user-images.githubusercontent.com/49448379/115917189-5df63200-a465-11eb-999b-73a8ba9b428e.png)

**Comment by mirrorcult** [comment]
see #4069, doesn't fix entirely but makes it a little more palatable

**Comment by EmoGarbage404** [comment]
this got fixed with #10465
