### ISSUE TITLE
Unbuckling from north/south facing chairs closes backpack and toolbelt inventories

### ISSUE THREAD

**Issue by MehimoNemo** [space-wizards/space-station-14#3873]
## Description
So, I made a shit ton of chairs to figure this out, since at first I thought it was only a few chairs that had this bug, but upon experimentation, I found out it was the rotation of the chairs that affects this bug.
To recreate: 
Step 1) Sit in any chair facing north or south.
Step 2) Open a backpack or toolbelt.
Step 3) Unbuckle.

This does NOT happen in east/west facing chairs.

**Comment by metalgearsloth** [comment]
Fixed in https://github.com/space-wizards/RobustToolbox/commit/c54b1572f53a43a6bad56ba9e3d5655f0511d3fd
