### ISSUE TITLE
Throwing items in disposal bin can appear broken

### ISSUE THREAD

**Issue by Visne** [space-wizards/space-station-14#3875]
## Description
When throwing an item in a disposal bin, theres a 25% of failing. In my opionion, this can just feel broken to a player (see #3768 😳). I think we should either remove the random chance, or make a small message pop up that says "Missed!" or something.

**Comment by metalgearsloth** [comment]
Does it even collide? It feels like it doesn't even go in for me so definitely needs sussing.

**Comment by Visne** [comment]
Pretty sure it worked for me quite often

**Comment by MehimoNemo** [comment]
Doesn't work for me.........
