### ISSUE TITLE
SolutionContainerVisualizer doesn't set color on spawn

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#3877]
## Description

1. Spawn the "solution container vis cut-out"
2. Drink from it

This contains watermelon reagent, but it spawns white and it's icon does not have the color applied in the spawn menu. Only when you take a sip does it update.

**Screenshots**

https://user-images.githubusercontent.com/49448379/115653934-a277b580-a31f-11eb-864c-2b0f023f552f.mp4

**Additional context**

@Macoron

**Comment by Silvertorch5** [comment]
SolutionContainerVisualState Is not present in the initialization of AppearanceComponent for this prototype it seems.
