### ISSUE TITLE
Issue to track conversion of codebase to fluent system

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#3888]
## Description

NOTE: Submitting this since i'm scared of losing work, compiling this was an absolute ass.

Was gonna make this a project but I think an issue is good 'nuff. This issue is only tracking components and UI/Menus, **NOT** entities.

[Our docs on Fluent](https://hackmd.io/@ss14/localization). Basically fluent replaces the content Loc.GetString() with a identifier that reads from the .flt files in our [locale directory](https://github.com/space-wizards/space-station-14/tree/master/Resources/Locale/en-US). 

Most of the Loc.GetStrings in the codebase have not been converted over to this new system, so get crackin' and fix em. It's pretty easy to do, but do **NOT** web-edit it or I will close your PR.

Ngl this is pretty tedious and since I expect you to check in-game that you've done this right I don't recommend you make massive PRs for this. However, I also will not approve of a million tiny PRs for each component.

Not touching any BodySystem stuff to make stuff easier on @DrSmugleaf .

**Components/Systems**
- [ ] CharacterInfoComponent.cs
- [ ] GasAnalyzerComponent.cs
- [ ] HyposprayComponent.cs
- [ ] InjectorComponent.cs
- [ ] ConstructionGhostComponent.cs
- [ ] CrayonComponent.cs
- [ ] HumanInventoryInterfaceController.cs
- [ ] WelderComponent.cs
- [ ] ActionSlot.cs
- [ ] DisarmAction.cs
- [ ] Seed.cs
- [ ] ToiletLidClosed.cs
**Content.Server starts here I think, so some repeats.**
- [ ] WirePanel.cs
- [ ] IdCardComponent.cs
- [ ] IdCardConsoleComponent.cs
- [ ] CuffableComponent.cs
- [ ] HandcuffComponent.cs
- [ ] SpaceVillainArcadeComponent.cs
- [ ] FirelockComponent.cs
- [ ] FlammableComponent.cs
- [ ] GasAnalyzerComponent.cs
- [ ] GasTankComponent.cs
- [ ] BarSignComponent.cs <- This is such a shitty bit of code rewrite it please.
- [ ] PlantHolderComponent.cs
- [ ] SeedComponent.cs
- [ ] SeedExtractorComponent.cs
- [ ] BuckleComponent.cs
- [ ] ChemMasterComponent.cs
- [ ] HyposprayComponent.cs
- [ ] InjectorComponent.cs
- [ ] PillComponent.cs
- [ ] ReagentDispenserComponent.cs
- [ ] RehydratableComponent.cs
- [ ] ConfigurationComponent.cs
- [ ] ConfigurationComponent.cs
- [ ] ConstructionComponent.cs
- [ ] MachineBoardComponent.cs <- Only first entry needs it.
- [ ] MachinePartComponent.cs
- [ ] CrayonComponent.cs
- [ ] SliceableFoodComponent.cs
- [ ] DisposalMailingUnitComponent.cs
- [ ] DisposalRouterComponent.cs
- [ ] DisposalTaggerComponent.cs
- [ ] DisposalTubeComponent.cs
- [ ] DisposalUnitComponent.cs
- [ ] AirlockComponent.cs
- [ ] ExtinguisherCabinetComponent.cs
- [ ] BucketComponent.cs
- [ ] MopComponent.cs
- [ ] PuddleComponent.cs
- [ ] SpillableComponent.cs
- [ ] SprayComponent.cs
- [ ] InventoryComponent.cs
- [ ] StrippableComponent.cs
- [ ] HumanInventoryControllerComponent.cs
- [ ] HeadsetComponent.cs
- [ ] InstrumentComponent.cs
- [ ] HandheldLightComponent.cs
- [ ] WelderComponent.cs
- [ ] DiceComponent.cs <- This one is funky,
- [ ] FireExtinguisherComponent.cs
- [ ] RCDAmmoComponent.cs
- [ ] RCDComponent.cs
- [ ] EntityStorageComponent.cs
- [ ] ItemComponent.cs
- [ ] SecretStashComponent.cs
- [ ] SecureEntityStorageComponent.cs
- [ ] LightReplacerComponent.cs
- [ ] KitchenSpikeComponent.cs
- [ ] MicrowaveComponent.cs
- [ ] ReagentGrinderComponent.cs
- [ ] SignalButtonComponent.cs
- [ ] SignalReceiverComponent.cs
- [ ] SignalSwitchComponent.cs
- [ ] SignalTransmitterComponent.cs
- [ ] SignalTwoWayLeverComponent.cs
- [ ] MagbootsComponent.cs
- [ ] MagicMirrorComponent.cs
- [ ] WarpPointComponent.cs
- [ ] MedicalScannerComponent.cs
- [ ] MetabolismComponent.cs
- [ ] MindComponent.cs
- [ ] StunnableComponent.cs
- [ ] BodyBagEntityStorageComponent.cs
- [ ] CrematoriumEntityStorageComponent.cs
- [ ] MorgueEntityStorageComponent.cs
- [ ] NodeContainerComponent.cs
- [ ] CreamPiedComponent.cs
- [ ] DrinkComponent.cs
- [ ] FoodComponent.cs <- Partially done, don't be fooled.
- [ ] GhostComponent.cs
- [ ] ParticleAcceleratorControlBoxComponent.cs
- [ ] PDAComponent.cs
- [ ] PottedPlantHideComponent.cs
- [ ] AMEControllerComponent.cs
- [ ] AMEPartComponent.cs
- [ ] ApcComponent.cs
- [ ] PowerReceiverComponent.cs
- [ ] BaseCharger.cs
- [ ] EmergencyLightComponent.cs
- [ ] PoweredLightComponent.cs
- [ ] PowerCellComponent.cs
- [ ] PowerCellSlotComponent.cs
- [ ] RadiationCollectorComponent.cs
- [ ] PullableComponent.cs
- [ ] HandheldRadioComponent.cs
- [ ] RecyclerComponent.cs
- [ ] FlippableComponent.cs
- [ ] RotatableComponent.cs
- [ ] StrapComponent.cs
- [ ] SuspicionRoleComponent.cs
- [ ] TraitorDeathMatchRedemptionComponent.cs
- [ ] VendingMachineComponent.cs
- [ ] ToiletComponent.cs
- [ ] FlashComponent.cs
- [ ] StunbatonComponent.cs
- [ ] AmmoBoxComponent.cs
- [ ] AmmoComponent.cs
- [ ] RangedMagazineComponent.cs
- [ ] SpeedLoaderComponent.cs
- [ ] BoltActionBarrelComponent.cs
- [ ] PumpBarrelComponent.cs
- [ ] RevolverBarrelComponent.cs
- [ ] ServerBatteryBarrelComponent.cs
- [ ] ServerMagazineBarrelComponent.cs
- [ ] ServerRangedBarrelComponent.cs
- [ ] ServerRangedWeaponComponent.cs
- [ ] WiresComponent.cs
- [ ] PresetTraitorDeathMatch.cs
- [ ] RuleDeathMatch.cs
- [ ] RuleInactivityTimeRestart.cs
- [ ] RuleMaxTimeRestart.cs
- [ ] RuleSuspicion.cs
- [ ] RuleTraitor.cs
- [ ] GameTicker.cs <- Partially done, don't be fooled.
- [ ] GameTicker.JobController.cs
- [ ] DefaultHolidayGreet.cs
- [ ] SuspicionTraitorRole.cs <- Partially done?
- [ ] TraitorRole.cs
- [ ] DieCondition.cs
- [ ] KillPersonCondition.cs
- [ ] StayAliveCondition.cs
- [ ] StealCondition.cs
- [ ] PowerGridCheck.cs
- [ ] RadiationStorm.cs
- [ ] VoteOptions.cs

**System**
- [ ] VerbSystem.cs
- [ ] DragDropSystem.cs
**Content.Server starts here.**
- [ ] ExamineSystem.cs
- [ ] ConstructionSystem.cs
- [ ] HandsSystem.cs
- [ ] PointingSystem.cs
- [ ] RoundEndSystem.cs
- [ ] StationEventSystem.cs

**Manager**
- [ ] AdminManager.cs
- [ ] ChatManager.cs

**Verbs** <- This list is kinda fucky, as there are Verbs embedded in components so ctrl-f if you wanna do it in one PR.
- [ ] ExamineVerb.cs
- [ ] ViewVariablesVerb.cs
**Content.Server**
- [ ] SolutionTransferVerbs.cs
- [ ] ConstructionComponent.Verbs.cs
- [ ] AttachToGrandparentVerb.cs
- [ ] AttachToGridVerb.cs
- [ ] AttachToSelf.cs
- [ ] ControlMobVerb.cs
- [ ] DeleteVerb.cs
- [ ] InRangeUnoccludedVerb.cs
- [ ] MakeGhostRoleVerb.cs
- [ ] MakeSentientVerb.cs
- [ ] PointingVerb.cs
- [ ] RejuvenateVerb.cs

**Commands**
- [ ] ControlMob.cs
- [ ] DeleteEntitiesWithComponent.cs
- [ ] DSay.cs
- [ ] Rejuvenate.cs
- [ ] SetAdminOOC.cs
- [ ] SetMindCommand.cs
- [ ] SetOutfitCommand.cs
- [ ] FactionCommand.cs
- [ ] SuicideCommand.cs
- [ ] TubeConnectionsCommand.cs
- [ ] StationEventCommand.cs
- [ ] VoteCommands.cs

**XAML UI**
- [ ] AdminMenuWindow.xaml.cs
- [ ] SetOutfitMenu.xaml.cs
- [ ] StationEventsWindow.xaml.cs
- [ ] ConstructionMenu.xaml.cs
- [ ] LauncherConnectingGui.xaml.cs
- [ ] SuspicionGui.xaml.cs
- [ ] VoteCallMenu.xaml.cs

**Menu
- [x] BlockGameMenu.cs
- [x] SpaceVillainArcadeMenu.cs
- [x] CommunicationsConsoleMenu.cs
- [x] ConstructionMenuPresenter.cs
- [ ] GasAnalyzerMenu.cs
- [x] ConfigurationMenu.cs
- [x] WiresMenu.cs
- [x] LatheQueueMenu.cs
- [ ] ResearchConsoleMenu.cs
- [ ] MainMenu.cs
- [ ] ActionMenu.cs
- [ ] CargoConsoleMenu.cs
- [ ] CargoConsoleOrderMenu.cs
- [ ] GalacticBankSelectionMenu.cs

**Window**
- [ ] IdCardConsoleWindow.cs
- [ ] GasCanisterWindow.cs
- [ ] SurgeryWindow.cs
- [ ] ChemMasterWindow.cs
- [ ] ReagentDispenserWindow.cs
- [ ] CloningPodWindow.cs
- [ ] CrayonWindow.cs
- [ ] DisposalMailingUnitWindow.cs
- [ ] DisposalRouterWindow.cs
- [ ] DisposalTaggerWindow.cs
- [ ] DisposalUnitWindow.cs
- [ ] MedicalScannerWindow.cs
- [ ] AcceptCloningWindow.cs
- [ ] AMEWindow.cs
- [ ] GasTankWindow.cs
- [ ] CreditsWindow.cs
- [ ] RoundEndSummaryWindow.cs

**UI/Misc**
- [ ] GasCanisterBoundUserInterface.cs
- [ ] BodyScannerDisplay.cs
- [ ] ChemMasterBoundUserInterface.cs
- [ ] ReagentDispenserBoundUserInterface.cs
- [ ] MicrowaveBoundUserInterface.cs
- [ ] ReagentGrinderBoundUserInterface.cs
- [ ] MagicMirrorBoundUserInterface.cs
- [ ] PDABoundUserInterface.cs <- Some stuff is localized, not everything.
- [ ] StrippableBoundUserInterface.cs
- [ ] GravityGeneratorBoundUserInterface.cs
- [ ] ResearchClientServerSelectionMenu.cs
- [ ] TraitorOverlay.cs
- [ ] SandboxManager.cs
- [ ] LobbyState.cs
- [ ] AdminAddReagentUI.cs
- [ ] CharacterSetupGui.cs
- [ ] GameHud.cs
- [ ] GhostGui.cs
- [ ] HumanoidProfileEditor.cs
- [ ] LateJoinGui.cs
- [ ] LobbyCharacterPreviewPanel.cs
- [ ] ParticleAcceleratorControlMenu.cs
- [ ] PermissionsEui.cs
- [ ] ServerInfo.cs

**Content.Shared few files**
- [ ] MaterialConstructionGraphStep.cs
- [ ] ToolConstructionGraphStep.cs
- [ ] SharedSolutionContainerComponent.cs
- [ ] SharedGasAnalyzerComponent.cs <- Maybe.
- [ ] SharedInteractionSystem.cs

**Comment by Visne** [comment]
#3893

**Comment by Visne** [comment]
> 
> 
> #3893

@SweptWasTaken This is merged now, you can tick them off.

**Comment by SweptWasTaken** [comment]
> 
> 
> > #3893
> 
> @SweptWasTaken This is merged now, you can tick them off.

Done.
