### ISSUE TITLE
Fix ghost hitboxes

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#3889]
Currently they're squares and rotatable but should be circles. This affects ghosts and aghosts.

**Comment by AJCM-git** [comment]
![screenshot](https://user-images.githubusercontent.com/60196617/140633301-c0a7304e-99ee-4edd-a98f-e2af5563dd29.png)

They seem to be circles in master, is that enough to close this?

**Comment by Clyybber** [comment]
Normal ghosts have circles now, only aghost hitboxes are square and rotatable.
