### ISSUE TITLE
Make sharp objects like knife/swords etc. stick in certain collidable objects when thrown

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#3904]
## Description

Kinda like how in Rust you can throw axes and shit so that they embed in wood. Since we have sprite that rotate on throwing, this would require  figuring out which end of the sprite is the pointy bit when it touches the collidable object. Since a handle ain't gonna embed itself in a wall.

Embedding could also work for mobs, so you could throw a spear that embeds in someone.

**Comment by AJCM-git** [comment]
done with spears
