### ISSUE TITLE
Airlocks sound weird

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#3916]
## Description
It kind of sounds like their sounds play 2x, when I'm throwing the crowbar at the doors, it sometimes sounds normal but other times does not. I'm guessing that stuff is colliding with it twice? for some reason? @metalgearsloth 

https://user-images.githubusercontent.com/19853115/116831051-01c89780-ab62-11eb-9fe6-55d65607789a.mp4

**Comment by metalgearsloth** [comment]
Dupe. Animation is playing twice.
