### ISSUE TITLE
Windows can exist without low walls beneath them

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#3919]
## Description
windows shouldnt be able to float like that, eris' solution is to just have the window fall and break after a delay if the low wall is destroyed first

related to #3730

**Screenshots**
![image](https://user-images.githubusercontent.com/19853115/116831441-49502300-ab64-11eb-9b47-93094a71512f.png)

**Additional context**

**Comment by TimrodDX** [comment]
An easier solution might be to make it so that it's impossible to interact with the low wall (ie; can't deconstruct, can't attack) as long as there's a window on top of it or if a window is being added to it. That would solve both 3730 and this being able to happen in the first place.

**Comment by mirrorcult** [comment]
you would have to make it impossible to damage the low wall at all if there's a window on top of it, which runs into issues with stuff like explosions (and is just a little snowflakey), i.e.
- an explosion happens, it goes through the stuff it needs to damage
- it tries to damage the low wall first, but can't because theres a window on it
- it destroys the window fine, but now the low wall is just kinda, there, even though it should probably be destroyed
it would be easier though. although i like eris' looney tunes 'window falling when it realizes there isnt a low wall' thing

**Comment by metalgearsloth** [comment]
Having every piece of damage / interaction code check for low wall sounds painful.

Pretty sure snapgrid replacement will fix it.

**Comment by AJCM-git** [comment]
We no longer have low walls.
