### ISSUE TITLE
Items cant collide with a lot of things while thrown, including players

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#3920]
## Description
see title--intended behavior is that they should, but only while being thrown and not on the ground

https://user-images.githubusercontent.com/19853115/116831538-e8751a80-ab64-11eb-914c-ada992f0db5b.mp4

**Comment by metalgearsloth** [comment]
I don't think items should implicitly collide with mobs IMO considering it will cause weird situations where you need to pickup the item or wait for it to stop moving to get past it

**Comment by mirrorcult** [comment]
> 
> 
> I don't think items should implicitly collide with mobs IMO considering it will cause weird situations where you need to pickup the item or wait for it to stop moving to get past it

i suppose that makes sense but how would you handle items that are supposed to collide with mobs (spears, hatchets, bolas)

**Comment by metalgearsloth** [comment]
IMO they'd still be non-hard so still able to generate collision events.

If you want the item affected by the collision you could just apply an impulse to the item during the collision event (probably make it a one-off or give it a cooldown so it doesn't look too jank).

**Comment by PaulRitter** [comment]
> I don't think items should implicitly collide with mobs IMO considering it will cause weird situations where you need to pickup the item or wait for it to stop moving to get past it

couldn't this be tied into the throwing system? enable collision when in air, disable when landing

**Comment by metalgearsloth** [comment]
that's how we currently do it (both the item colliding with walls and mobs are turned off when velocity hits 0).

**Comment by PaulRitter** [comment]
> that's how we currently do it (both the item colliding with walls and mobs are turned off when velocity hits 0).

how come it doesnt collide in the video then

**Comment by metalgearsloth** [comment]
They're not set to hard collide with players. As above if it hard-collided only when moving then you'd have weird situations where the velocity is low and you have to stop moving to get past it.

**Comment by SweptWasTaken** [comment]
This needs to be addressed in some way because there's things that cause damage when hitting people like spears or shards. 

![2021-08-05_17-34-16](https://user-images.githubusercontent.com/49448379/128438272-f168a242-8191-40e2-b1a4-c67526438460.gif)

I think #3904 would be a good idea but it looks very dumb when you throw something and it goes under/over someone.

**Comment by tom-leys** [comment]
@metalgearsloth This issue appears to be resolved now.
