### ISSUE TITLE
Light pop-in issues

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#3922]
## Description

i dont really know how to explain this beyond visuals. i might be insane or very dumb

**Screenshots**
harsh light: (near arrivals, or in bridge is easy to test)
![image](https://user-images.githubusercontent.com/19853115/116831781-33436200-ab66-11eb-8fb4-7b9ee57f5aea.png)

non-harsh light: (near tool storage is where i tested)
![image](https://user-images.githubusercontent.com/19853115/116831771-2757a000-ab66-11eb-8f21-460481d1ef02.png)

**Additional context**

**Comment by AJCM-git** [comment]
Is this related to #2379?

**Comment by mirrorcult** [comment]
fixed with paulvs
