### ISSUE TITLE
You can't pull dead people

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#3923]
## Description
it is what it says on the tin--it doesn't just not move them, it seems like the joint never gets made for some reason. named fixtures? idk @metalgearsloth 

**Screenshots**

https://user-images.githubusercontent.com/19853115/116831809-79002a80-ab66-11eb-8e11-6d54b9d1cbbc.mp4

**Comment by metalgearsloth** [comment]
Dupe
