### ISSUE TITLE
Buckets have a lot of issues, BucketComponent should probably die

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#3926]
## Description
- handheld buckets have a volume of 500u which seems.. like.. a lot?
- bucketcomponent snowflakes a lot of stuff that SolutionContainerComponent should handle, and it snowflakes a lot of interactions with mops specifically. i feel like you should be able to dip a mop in something that isn't a bucket, right? like i should be able to dip a mop in my open can of soda if i please. imo this functionality should go on SolutionContainerComponent and only apply if certain caps are right
- handheld buckets and mop buckets don't have visualizers for their contents like beakers do (mop buckets i think change their sprite, but they have water hardcoded i think)
- you can't add fluid to mop buckets, only steal from it with a mop. let me put 500u of blood in my mop bucket goddamnit. also if you wet a bloody mop in a mop bucket it should transfer some of the blood to the bucket like viscera cleanup detail but thats bikeshed

also it just feels bad because '[noun]Component' is usually a sign that its not good

**Comment by metalgearsloth** [comment]
I agree but with that being said multiple people prefer the mop destroying solutions (for whatever reason) compared to just transferring them which is what it originally did.

I assume the 500u was a copypaste

**Comment by Willhelm53** [comment]
* handheld buckets - definitely agree, and I want to nerf. I'm thinking 150-200 units based on the mop bucket's 500u.
* BucketComponent could die and have any special interactions moved to MopComponent with some checks.
    * The mop should be able to take liquid from any container, I agree, even if that's "I spill the soda on my mop."
    * IMO, transferring liquid from mop to any container should be possible, but nerfed unless there's a wringer on it (e.g. you use your hands to squeeze liquid out - it takes twice as long and you can only squeeze half the liquid out of the mop, reducing its capacity until properly wrung)
    * Stuff like "is the mop interacting with something with a wringer" could be handled within MopComponent
    * I'll add this to my list but probably won't get to it for a little while yet. Would like to hear your thoughts as well @mirrorcult!
* Visualizers: Ooh yes interesting, I want to take a closer look at how that color/visualizer piece works. That'd be really cool
* [Did somebody order uhhhhhhhhhhhhhh bucket full of blood?](https://github.com/space-wizards/space-station-14/pull/6193)

**Comment by metalgearsloth** [comment]
> The mop should be able to take liquid from any container

How do you define container? SolutionContainerManager isn't usable for obvious reasons so is it something like drainable?

**Comment by Willhelm53** [comment]
good point - I hadn't thought that far ahead yet. Still getting my head around all these systems to be honest - another reason I won't tackle this one right away 😁

**Comment by ShadowCommander** [comment]
In SS13, small beakers hold 20u, large beakers 100u, buckets 100u, and mop buckets 500u.

**Comment by Willhelm53** [comment]
>handheld buckets have a volume of 500u

I addressed this just now in [#6273]. And now that I know my way around visualizers I think I can tackle the rest of this issue as well

**Comment by RandomDeathMatch** [comment]
Worth noting handheld buckets cannot be placed in pockets and take up literally 100 space in your bag.

Honestly, I don't get the bucket hate. They seem completely reasonable at 500 considering the above. You can carry 20 large beakers in your bag as well as fit them in dispensers and such. At 100 volume a bucket is useless compared to a large beaker which can fit anywhere. Arguably a 500 unit bucket is still worse than 5 large beakers, but it had a good use in mixing chemicals time efficiently.

Maybe if they could fit in your belt slot they would have a niche use? Or maybe what I am missing is that you cannot interact with non-buckets with the mop, but that seems a little strange to me if so. Presumably you could be mopping into a beaker? Or maybe large beakers just need a nerf, but I personally like them.

Did buckets have any other use in SS13?

**Comment by Willhelm53** [comment]
Someone can assign me to this issue if they like. I now intend to fully solve it, by adding a MoppingSystem to make all of mopping ECS-compliant. However for simplicity I think I'll wait for #6273 to get reviewed first in case there's changes needed. I can work on other areas in the meantime though 🙂

**Comment by Willhelm53** [comment]
> > The mop should be able to take liquid from any container
> 
> How do you define container? SolutionContainerManager isn't usable for obvious reasons so is it something like drainable?

I understand what you mean now - learned a lot in three weeks! 😁
Yes, DrainableSolutionComponent is the way I would go. After checking all the entities with this component, the only one that doesn't make sense is in shotgun.yml, where ammo is a "solution." Although the meme potential of "you fill your mop with hot lead" is pretty tempting, I think that needs fixing 😂

And because I now know more about datafields work, I absolutely agree that bucketComponent needs to die. I plan to do it by adding a bool: hasWringer datafield to RefillableSolutionComponent that defaults to false, and make this true on proper mop buckets. As part of this issue, mop buckets need to just be given Refillable and Drainable instead of BucketComponent.

hasWringer would currently be true for just the one mop bucket prototype, but I may wish to add others later (e.g. a 2-compartment mop bucket, or nerfed small portable bucket with wringer). If hasWringer is true, the transfer would take place with a shorter doAfter delay, and with different popup text (e.g. "You use the wringer to quickly wring out the mop into the bucket" versus "You use your hands to wring the mop into the soda can").

Any thoughts on my approach? I think I want to tackle this after I'm finished my current WIP PR.

**Comment by Matz05** [comment]
As far as I knkow, shotguns only use DrainableSolutionComponents in their tranquilizer dart shells, to allow you to add and remove drugs. I suppose you could squeeze a tranquilizer dart out into a mop. Drawing out of a mop into a dart is a little sketchier, but if you can do it with a syringe I suppose it makes sense to stay consistent.

**Comment by Willhelm53** [comment]
> As far as I know, shotguns only use DrainableSolution components in their tranquilizer dart shells

Ah, you're correct. I was skim-reading that code the first time.

>Drawing out of a mop into a dart is a little sketchier, but if you can do it with a syringe I suppose it makes sense to stay consistent.

This gives me another idea. Maybe MopComponent should include a field for minimumRefillableSolutionVolume (say, 20 units). Then in the MoppingSystem, a check to make mops unable to deposit into impractically small containers.

**Comment by ShadowCommander** [comment]
> And because I now know more about datafields work, I absolutely agree that bucketComponent needs to die. I plan to do it by adding a bool: hasWringer datafield to RefillableSolutionComponent that defaults to false, and make this true on proper mop buckets. As part of this issue, mop buckets need to just be given Refillable and Drainable instead of BucketComponent.
> 
> Any thoughts on my approach? I think I want to tackle this after I'm finished my current WIP PR.

If only mops will use the hasWringer bool, then it'd probably be better to use a tag in TagComponent and check it with the MopSystem, since not every Refillable needs wringer data. Or depending on needs make a WringerComponent.

**Comment by Willhelm53** [comment]
That's true! In retrospect that IS way cleaner than adding "bool hasWringer = false" to every Refillable in the game 😂 

I know how to do this now too, since learning about how Tags work these past few days 😁

**Comment by mirrorcult** [comment]
this is p much done with #6718 as far as im concerned
