### ISSUE TITLE
Transfer liquid verbs are weird and incorrect

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#3929]
## Description
- they dont tell you unit size for transfer
- i'm not positive why they exist
- they show up even if you only have one thing in your hand
- message for transferring between objects in hands is incorrect, its actually the reverse of what it should be
- no message for how much was transferred when it happens

**Screenshots**

https://user-images.githubusercontent.com/19853115/116833090-2a558f00-ab6c-11eb-8372-1117e0e29478.mp4

**Additional context**

**Comment by SweptWasTaken** [comment]
I think just straight up removing this would be for the best.

**Comment by mirrorcult** [comment]
same, imo should just be removed

**Comment by PaulRitter** [comment]
agree
