### ISSUE TITLE
Need clearer indicator that combat mode is on.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/space-station-14#394]
Right now combat mode still basically locks up most interactions. It's not *that* bad anymore because there's a button now at least, but it could still be better.

Maybe like make the cursor red? Would require custom mouse cursors.

**Comment by tentekal** [comment]
I'll take this one up if that's ok.

**Comment by tentekal** [comment]
Picked up work on this again. I'll have a prototype out soon.

**Comment by SweptWasTaken** [comment]
> 
> 
> Picked up work on this again. I'll have a prototype out soon.

Still waiting on that prototype.

**Comment by mirrorcult** [comment]
working on custom mouse cursors partially for this, i swear ill actually have something done

**Comment by mirrorcult** [comment]
> 
> 
> working on custom mouse cursors partially for this, i swear ill actually have something done

i lied i don't understand opengl or glfw enough to do this but I still want to at some point

**Comment by SweptWasTaken** [comment]
We have it in the hotbar now which I think it good 'nuff.
