### ISSUE TITLE
Dropping items with Q should reset their rotation

### ISSUE THREAD

**Issue by PaulRitter** [space-wizards/space-station-14#3949]
freshly dropped glass:
![grafik](https://user-images.githubusercontent.com/16618384/117555708-da8e3080-b061-11eb-9720-3be7af4f3844.png)

**Comment by metalgearsloth** [comment]
Dupe of #3867?

**Comment by PaulRitter** [comment]
i would literally go crazy if it were random

**Comment by PaulRitter** [comment]
i found a middleground: dropping with random rotation on unintentional drop, dropping with reset rotation on intentional

**Comment by PaulRitter** [comment]
done in c136755df267c641426a0f588852b99938aa77cf
didn't mean to direct commit but im just gonna roll with it dont mind me
