### ISSUE TITLE
Storage ui sometimes cuts off the Stored indicator

### ISSUE THREAD

**Issue by PaulRitter** [space-wizards/space-station-14#3951]
a story in two pictures

how it initialised
![grafik](https://user-images.githubusercontent.com/16618384/117555840-e9c1ae00-b062-11eb-83f6-895960710e70.png)

dragged out
![grafik](https://user-images.githubusercontent.com/16618384/117555845-ee866200-b062-11eb-9b02-aab016711451.png)

**Comment by AJCM-git** [comment]
i think the minsize is sufficient now?
