### ISSUE TITLE
Losing a head doesn't mean you lose your eyes

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#3956]
## Description

Suicide microwave your head. Your eyes will remain.

**Comment by scrato** [comment]
How do I suicide by microwaving my head? 
I tried everything but I'm not able to get my head inside the microwave.

**Comment by scrato** [comment]
nvm... found out... Clever that the "suicide" command in the menu checks what items you have in hand or your sourroundings...
