### ISSUE TITLE
Can't unbuckle mob from chair after pulling

### ISSUE THREAD

**Issue by Macoron** [space-wizards/space-station-14#3999]
## Description
1. Spawn Urist and a chair
2. Drag Urist on a chair and pull it for some time
3. You are not able unbuckle Urist from chair anymore

**Screenshots**

https://user-images.githubusercontent.com/6161335/118340147-96000a80-b523-11eb-9fd6-8a768b1bda8e.mp4

**Additional context**

**Comment by GalacticChimp** [comment]
I'll try this one next

**Comment by GalacticChimp** [comment]
@Macoron cannot reproduce this on newest master. Are there any additional steps needed?
