### ISSUE TITLE
Simple Research

### ISSUE THREAD

**Issue by ghost** [space-wizards/space-station-14#40]
Raise tech levels, unlocks using materials to create new object types.
Simple various types of possible tech (steal from ss13)
Assign a few parts these tech levels
A simple machine that you use attackhand on, brings up a UI, select a research type, after certain amount of time has passed research completes and new tech level unlocks.
Finally a second machine with another UI that lets you input materials and print objects if you have the requisite tech level unlocked

**Comment by Zumorica** [comment]
This is my proposal for simple research stuff. 

**Gameplay stuff**
Research points are used in an RD Console to unlock new technologies. These technologies get synced with an RD Server, which syncs them to every RD Console connected to it.
RD Consoles then update their connected devices (protolathe, maybe circuit imprinter in the future) with the latest recipes unlocked. At first, there’ll only be a type of protolathe, which can print every recipe unlocked, but in the future this can be changed to allow for departmental protolathes.

RD Servers keep track of research points, and get a certain amount passively. 
Researching special items, setting up the engine, or making big explosions could potentially boost the point influx, or give an amount of points at once.
Eventually, all technology is researched. However, the rate at which it’s unlocked can be sped up by cooperating with your fellow crew members.

**Technical stuff**
- Research prototype: 
    - Has a name, description, icon, codename/ID and a list of lathe recipes it unlocks. Also has a list of “required researches” which will be needed to unlock this research in the first place.

- Research Database Component:
    - Component which stores unlocked researches. 

- Remote Research Database Component:
    - Component for RD servers. Research databases can sync with it, and it’s listed on the Research System.

- Research System:
    - System that keeps track of remote research databases, and manages research points as well, since those will be global.

- Research Console Component:
    - Component for RD consoles. Can interact with nearby Protolathe Databases to update its recipes. Can also interact with a Research Database on the same component to unlock new recipes once enough points are obtained.

- Protolathe Recipe Database Component:
    - Inherits Lathe Recipe Database Component. Its recipes can be updated and might have support for different department lathes, so not every protolathe gets the same recipes.

- Research Point Source Component:
    - A component which grants research points per minute, and is listed on the Research System. Other components/systems might interact with it, to enable/disable it, or make the research point rate higher/lower.
