### ISSUE TITLE
Examine icons for objects in your hand are rotated

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#4003]
https://user-images.githubusercontent.com/19853115/118354307-5afbd800-b51f-11eb-92e1-5ec3b6409377.mp4

**Additional context**
???????????????????

**Comment by metalgearsloth** [comment]
If it uses SpriteView you can look at https://github.com/space-wizards/space-station-14/pull/3764 for reference on how to fix.
