### ISSUE TITLE
Cable coil stack visualizer is a little off

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#4004]
## Description
at around 22/23 cable (still the majority of the cable left) the sprite is just a single strand of cable which doesn't match how much is left

**Screenshots**
![image](https://user-images.githubusercontent.com/19853115/118354463-09a01880-b520-11eb-9231-95984db07ac0.png)

**Additional context**

**Comment by SweptWasTaken** [comment]
This is not an issue with the visualizer more the sprite. Visualizer works as in the first and last sprite will only be the first and last of the stack.
