### ISSUE TITLE
Objects with rotation cause physics issues

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#4010]
![image](https://user-images.githubusercontent.com/7907891/118378924-f1bea800-b5a4-11eb-9ed2-9c694eb6a876.png)

Originally reported by CCCJPEG1312K#5073

It looks like this might be unique to live, as I've been unable to reproduce it in a dev environment.

**Comment by TimrodDX** [comment]
Couple of notes on this:

The ability of the disposal unit to clip you through things seems largely based on lag. Even with the Boda machine (which gives a much stronger push) I was never able to clip through a wall in a dev environment, but I can get it to happen consistently on live.

**Comment by TimrodDX** [comment]
![image](https://user-images.githubusercontent.com/7907891/118506614-77ed0280-b6fb-11eb-8749-7db331207b70.png)

I did some looking into it, and it looks like this is an issue with objects having a rotation value equal to pi. This was the case with the Boda machine before I hotfixed it. You can test this yourself by going into saltern.yml and adding the line:

-rot: 3.141592653589793 rad

to any object that has collision. This will make any vending machine behave like the Boda machine did, and I believe is the cause of the disposals units pushing people through walls, as several of these are rotated to pi.

**Comment by Zumorica** [comment]
This is incorrect, by the way. This happens with ANYTHING that has a rotation.

**Comment by metalgearsloth** [comment]
Yeah this has literally been an issue since I ported box2d and should prolly be on RobustToolbox.

**Comment by metalgearsloth** [comment]
I'm 90% sure the cause is that WorldRotation has 0 as South and I ported under the assumption 0 was East. This bug is a blocker for grid rotations but on the plus side grid rotations made it easy to debug.
