### ISSUE TITLE
Implement more chemical reaction effects

### ISSUE THREAD

**Issue by Moneyl** [space-wizards/space-station-14#402]
Chemical reactions can have effects on the world via reaction effects (ie: explosions, fire, smoke, emp, etc). Currently we only have one reaction effect, `ExplosionReactionEffect`. It causes an explosion when it's reaction occurs. We need more to be implemented as part of making chemicals functional.

To add one, create a class which implements `IReactionEffect`. Once you do that, you'll be able to use that effect in chemical reaction prototypes. See `ExplosionReactionEffect` for an example of how they're implemented, and the potassium + water explosion reaction in `Resources/Prototypes/Reactions/chemicals.yml` for an example of how their prototypes work.

This is related to #170.

**Comment by Sauberstaub** [comment]
Is there a **somewhat** comprehensive list of existing reactions that should definitely be implemented? Basically just a point towards the right .dm file.

**Comment by Moneyl** [comment]
It might vary by codebase but all the effects that occur upon reaction are [here](https://github.com/discordia-space/CEV-Eris/blob/228a15b1b296df83bd13db79070e2e51960297a2/code/modules/reagents/recipes.dm#L555) for CEV Eris. Look for reactions that define an `on_reaction` proc. They should all be on the line I linked and afterwards. Here's the main ones I found:
- [x] Explosions (potassium and nitroglycerin explosions on eris). Implemented with `IExplosionReaction`
- [x] Flash powder. `IExplosionReaction` has flash range.
- [ ] EMP effect. An effect that temporarily de-powers electronics in a certain range. Could have range scaling by reaction size like `IExplosionReaction` does.
- [ ] Chemical smoke effect. A smoke that contains the other reagents in it's solution. Those caught in it would metabolize the reagents it contains.
- [ ] Foam effect. A foam that spreads the other reagents it's solution to tiles the foam touches. 
- [ ] Heating/Cooling effect. Seen as thermite or napalm in SS13, a reaction that heats/cools the container it's in, or the objects it's coating.
- [ ] Metal foam. Creates several metal foam walls around the reaction which could used to seal breaches or block movement.

Other than the EMP effect, each of these will need additions to the chemistry system before they're possible. For example, the chemical smoke and foam effects would likely coat entities caught inside of them with chemicals, and the smoke would be inhaled and metabolized. Currently we're missing:
- Chemical metabolism
- Coating tiles / entities with chemicals and the effect of that such as making tiles slippery, or acid damaging entities when coating them.

I should note that we have most of the recipes from vg station already in `Resources/Prototypes/Reactions/`, it's just that none of them do anything beyond the potassium + water explosion.

**Comment by ElectroJr** [comment]
Pretty sure this can be closed now? At the very least, it's very out of date.

**Comment by Moneyl** [comment]
I haven't been following development lately so I don't know what's changed. Probably better to have someone who's following it create a new issue. Closing for now.

**Comment by mirrorcult** [comment]
pretty much all of these have been done and more are coming
