### ISSUE TITLE
No default animated sprite

### ISSUE THREAD

**Issue by clusterfack** [space-wizards/space-station-14#402]
The resource cache has no default for animated sprites like it does for having no sprite.

**Comment by Silvertorch5** [comment]
it should return the noimage sprite iirc

**Comment by Silvertorch5** [comment]
https://github.com/space-wizards/space-station-14/blob/master/SS14.Client/ResourceManagement/ResourceCache.cs#L607

**Comment by clusterfack** [comment]
That's normal sprites, not the animated sprites.

It used to actually do what you said due to the type returning 'object', however the only reason that worked is that it was *never accessed* and the second I fixed it so that it was accessed it would cause an exception.

**Comment by PJB3005** [comment]
Irrelevant now as the only sprite component is `SpriteComponent` (not animated) and it'd just be the regular no sprite sprite.
