### ISSUE TITLE
A singularity shader on-screen causes visual bugs in entity placement

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#4022]
## Description

Basically if you have one of them on-screen anything you select in the entity spawner will be a green square. It also shows a grid on placement of grid-based objects. This stops when the shader entity is deleted.

Replicate
1. Place singulo toy
2. Try to place something else

**Screenshots**

![2021-05-18_22-41-22](https://user-images.githubusercontent.com/49448379/118762303-82c3a680-b865-11eb-9a66-fbceb4337cf5.gif)
![image](https://user-images.githubusercontent.com/49448379/118762366-97a03a00-b865-11eb-9240-548630ec515e.png)

**Comment by PaulRitter** [comment]
seems like the shader shits itself, paging @PJB3005

**Comment by DogZeroX** [comment]
Haven't seen that happening anymore
