### ISSUE TITLE
Singularity doesn't move on initial spawn

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#4023]
## Description

Don't know if this is intentional but on initial placement the Singularity doesn't move at all. It just sits there. The only way to get it to move is with another singularity pulling it, wherein it will travel in the same direction that it was being pulled in (even if the other singularity is destroyed until it gets to stage 2 when it will start moving around like normal.

Even if this is intended behavior, when spawned from the entity spawner it should move around.

**Screenshots**

![2021-05-18_22-56-18](https://user-images.githubusercontent.com/49448379/118763199-f7e3ab80-b866-11eb-8664-76d76eccfe95.gif)

**Comment by PaulRitter** [comment]
this is quite literally intended and normal behaviour. did you play ss13?

**Comment by SweptWasTaken** [comment]
> When spawned from the entity spawner it should move around.

**Comment by PJB3005** [comment]
> when spawned from the entity spawner it should move around.
Why?

**Comment by SweptWasTaken** [comment]
> > when spawned from the entity spawner it should move around.
> 
> 
> 
> Why?

Because when spawning it from the entity spawner 99% it's to make it cause havoc and if it just sits there like a lemming it's not fun.

**Comment by Zumorica** [comment]
> > > when spawned from the entity spawner it should move around.
> > 
> > 
> > Why?
> 
> Because when spawning it from the entity spawner 99% it's to make it cause havoc and if it just sits there like a lemming it's not fun.

Just edit it with VV or add a prototype for a full-level singularity or something.

**Comment by SweptWasTaken** [comment]
> 
> 
> > > > when spawned from the entity spawner it should move around.
> > > 
> > > 
> > > Why?
> > 
> > 
> > Because when spawning it from the entity spawner 99% it's to make it cause havoc and if it just sits there like a lemming it's not fun.
> 
> Just edit it with VV or add a prototype for a full-level singularity or something.

I guess. But "just edit it with VV" is a bit of a slippery slope.

**Comment by PaulRitter** [comment]
> > > when spawned from the entity spawner it should move around.
> > 
> > 
> > Why?
> 
> Because when spawning it from the entity spawner 99% it's to make it cause havoc and if it just sits there like a lemming it's not fun.

then create a lvl 2 variant to spawn. much easier than delving into shitcode giving it special behaviour because it got spawned by the entitymanager. what???
