### ISSUE TITLE
Singularity can't destroy some objects

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#4024]
## Description

Tin. It just can't destroy these entities. Carpets/Catwalks probably have a refactor coming in the future so I wouldn't worry about them, but the rest probably need their collision layers tweaked.

- Signs
- Wires/Cables
- Lights
- Carpets/Catwalks

**Comment by metalgearsloth** [comment]
Problem is it needs to use GetEntitiesIntersecting on its inner fixture rather than using collision as a bunch of stuff has collision turned off for perf reasons (e.g. subfloor entities).

Maybe after acruid's tile entities pr we won't need collisionwake anymore but this is how to fix it currently.

**Comment by AJCM-git** [comment]
They seem to be eating everything just fine now
