### ISSUE TITLE
Don't make changes to guns

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#4041]
I'm currently refactoring so please don't make changes to it until it's done as it will just make the PR much more painful.

**Comment by BulletGrade** [comment]
Is it fine to make changes to explosives?

**Comment by metalgearsloth** [comment]
Explosive and flash grenade sure.

**Comment by SweptWasTaken** [comment]
Compilation of issues/suggestions related to guns for your PR.

#3732 #3527 #913 #2595 #2164 #1839

**Comment by scaly-chimp** [comment]
I think this is a minor bug you might wanna check out, but if you're refactoring guns for maximum pick n mix of functionality it should be fine. #4174

**Comment by PaulRitter** [comment]
@metalgearsloth is this still relevant?

**Comment by metalgearsloth** [comment]
Yeah, depending what the changes are I may be able to work around it. Its mainly avoid touching the code side as it's all liable to be bulldozed.

**Comment by leonsfriedrich** [comment]
In order for #4262 to work, it makes minor changes to HitscanComponent, ProjectileComponent and HitScansystem (making damage type datafields get damage prototypes, and changing a damageableComponent change damage call). its only a couple of lines, but might still be annoying if it were to be merged before the gun refactor is.

**Comment by metalgearsloth** [comment]
Just make the changes then I won't hold up body system for it.

**Comment by clement-or** [comment]
This is a related issue that might be worth fixing in the refactor 
[https://github.com/space-wizards/space-station-14/issues/2283](#2283)
