### ISSUE TITLE
Multiple UI buttons open duplicates of the windows

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#4045]
## Description

You can click these buttons multiple times and they will open the same window over and over. Looks like it's mostly an issue with the XAML UIs. 

**ChangelogButton.cs** and **VoteCallMenuButton.cs** both do this.

All the buttons in the admin menu that open separate windows do this. **Kick, Ban, Teleport, Permissions Panel** etc.

You can open multiple of the **Set Outfit** and **VV** menus when you right click an entity.

On the lobby GUI you can open multiple of the **credits, changelog, call vote** and **options menu**.

**Screenshots**

https://user-images.githubusercontent.com/49448379/119173387-ba457500-ba56-11eb-8e5a-58defdab3692.mp4

**Additional context**

The expected function for these buttons is that they toggle on when you click them and open a window. When you click the button again they toggle off and the window closes. The button also needs to toggle off when the window closes through other means, such as the X on the top right of the window.

**Comment by PaulRitter** [comment]
xamlui just emits a regular ui, just how you'd define it in c#. so it most definitely is not related to xamlui. seems like the (uicommand?)buttons aren't keeping track about the window instance they opened

**Comment by EmoGarbage404** [comment]
this still exists for the vote menu. huh.

**Comment by mirrorcult** [comment]
uimanager.createwindow uicontroller stuff largely fixes this afaict should make issues for specific cases
