### ISSUE TITLE
Substation batteries drain even if the substation is not connected to (or powering) anything.

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#4053]
How to reproduce:

- Go into sandbox mode (not mapping) and build a room off the station that is not connected to the station's power grid.
- Spawn a substation. It'll spawn with a full battery that will deplete pretty rapidly even if it's not connected to anything.

**Comment by AJCM-git** [comment]
Can't replicate. Placing a substation in a grid far from the station doesn't drain the `BatteryComponent` `CurrentCharge`

**Comment by mirrorcult** [comment]
this predates pow3r so not surprised it got fixed inbetween
