### ISSUE TITLE
Protolathe is broken.

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#4054]
![image](https://user-images.githubusercontent.com/7907891/119210303-7f086d80-ba79-11eb-9e76-abc2db75a20f.png)

How to reproduce:

- Do research and get all the research done
- Sync the protolathe and put materials inside
- You won't be able to print anything even with the materials in

**Comment by Zumorica** [comment]
This is due to every single lathe recipe not having the correct material IDs.

**Comment by SethLafuente** [comment]
> This is due to every single lathe recipe not having the correct material IDs.

But with the changes in my pull request thing it has those changes how convenient (:

**Comment by Zumorica** [comment]
Fixed by bbfc0c320a80c674eeef38eccb640fa667282d23
