### ISSUE TITLE
Cargo computer can be overflowed, which also overflows the cargo point values

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#4056]
![image](https://user-images.githubusercontent.com/7907891/119242997-eaf9dd00-bb30-11eb-996c-a64480e1ee3e.png)

Originally found by (Eris#Zero521)

How to reproduce:

- Go to the cargo computer. Order an internals crate, and in the quantity section, type a very big number (ex: 99999999)
- Click order.
- The cargo console will order 20 of whatever you picked, and set the cargo point count at a very big number.
- After a delay you now have infinite cargo points
- Order all the guns and turn SS14 into a battle royale with shotguns

**Comment by TimrodDX** [comment]
Correction: This only seems to work with internals crates. I've tested with all other crates, including other crates that cost <1000 (AME fuel) and only the internals crate can overflow.

**Comment by mirrorcult** [comment]
fixed in #4057 presumably
