### ISSUE TITLE
Body doesn't show on kitchen spike after being placed on

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#4070]
## Description
it just shows an empty kitchen spike after you put someone on it, tested with a urist mchands and a catatonic version of myself after i respawned

needs visualizer

**Screenshots**
![image](https://user-images.githubusercontent.com/19853115/119440569-672f2480-bcd9-11eb-92df-c960d9726914.png)

**Additional context**

**Comment by Swirl-droid** [comment]
This also occurs for monkeys.

**Comment by GalacticChimp** [comment]
I'll try this one
