### ISSUE TITLE
Need proper sprite y-sorting

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#4079]
## Description

I don't know if this'll be fixed by Acruid's layering stuff but firelock hatches need a mask so that entities are drawn over the bottom part and under the top part.

**Screenshots**

**Bad**
![image](https://user-images.githubusercontent.com/49448379/119698718-0ae71480-be41-11eb-96d6-7985c42681c2.png)

**Bad**
![image](https://user-images.githubusercontent.com/49448379/119698748-14707c80-be41-11eb-808d-67b5552ee0e6.png)

**Comment by Zumorica** [comment]
This is an issue with EVERYTHING, not only firelocks. Rather than a mask, what this needs is some proper y-sorting so entities that are "visually down" are always drawn on top of entities that are "visually up"

**Comment by metalgearsloth** [comment]
Y-sorting implemented in some PR I CBF'd searching up on robust.
