### ISSUE TITLE
Solution containers don't change color depending on their solution

### ISSUE THREAD

**Issue by Moneyl** [space-wizards/space-station-14#408]
Transparent solution containers like beakers or glass bottles should change color and appearance depending on the solution they contain and how much of it they contain. This would provide visual information for containers about what they contain and how much of it is left.

`SolutionComponent` already has a color value `SubstanceColor` that it updates as it's contents change. To do this the entity sprite for the solution needs to change depending on the solution color/volume. 

I'm not entirely sure how this should be implemented. My initial thought is that you'd have a different sprite for each fill level of the container. On that sprite you'd have some preset color for the solution that would be replaced by a shader with the solutions `SubstanceColor` whenever the solution changes. It'd be ideal if this was a reuseable component with it's fill level sprites specified in it's prototype. That way it could be used on various containers (beakers, drinking glasses, water bottles, etc).

**Comment by nuke-makes-games** [comment]
assign me 😎
