### ISSUE TITLE
Tables have broken clickmap hitboxes

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#4080]
## Description

Dunno what's wrong with this, they just seem to hate getting clicked on. This is true for vaulting, placing items and erasing. In all the gifs I was spam-clicking.

**Screenshots**

![2021-05-26_09-50-22](https://user-images.githubusercontent.com/49448379/119700278-86959100-be42-11eb-848a-33587740c3a9.gif)
![2021-05-26_09-49-40](https://user-images.githubusercontent.com/49448379/119700282-87c6be00-be42-11eb-8bb1-002526ccd4ca.gif)
![2021-05-26_09-48-32](https://user-images.githubusercontent.com/49448379/119700286-885f5480-be42-11eb-866c-4752177fb92d.gif)

**Comment by mirrorcult** [comment]
there was a PR that fixed this and was merged but got reverted due to it being hacky or something

**Comment by metalgearsloth** [comment]
In addition to icon smoothing being funky noRot also doesn't work as intended.
