### ISSUE TITLE
Manually constructing an airlock causes the game to freeze

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#4084]
Originally reported by Hardly#1296

How to reproduce:

- Attempt to build an airlock manually. This will also trigger if deconstructing an airlock and rebuilding it.
- Get to the last step, where you insert the electronics and screw it together.
- The game will freeze until you restart. This apparently affects everyone near the door.
- This may also happen to computers.

**Comment by TimrodDX** [comment]
I can now confirm that this can happen on anything that has to be screwdrivered to complete - I had it happen to me with a PA part. 

![image](https://user-images.githubusercontent.com/7907891/119898285-a2b33400-bf0f-11eb-9b8c-9edda8021fd8.png)

**Comment by Zumorica** [comment]
> I can now confirm that this can happen on anything that has to be screwdrivered to complete - I had it happen to me with a PA part.

This doesn't make any sense, screwdrivers aren't treated differently from other tools

**Comment by Zumorica** [comment]
Also tried this locally, can't replicate with your steps.

**Comment by SweptWasTaken** [comment]
Tried to replicate and couldn't. Will reopen if it arises again.
