### ISSUE TITLE
Getting stuck between a disposal unit and a wall, lag from alt-tabbing

### ISSUE THREAD

**Issue by Swirl-droid** [space-wizards/space-station-14#4086]
**Description**
Currently it is possible to get stuck between a garbage chute and a wall. In this state, alt-tabbing causes the client to lag severely. To perform: 
1. Enter the chute by click-dragging yourself onto it.
2. Exit the chute towards the wall using WASD.
3. Press Alt+tab.

**Screenshots**
![SS14 chute glitch](https://user-images.githubusercontent.com/84341487/119834637-6d531a00-bf00-11eb-907f-4de262bd3975.jpg)

**Additional info**
Ver. 0.1

**Comment by esguard** [comment]
I can't reproduce the lag on local but I managed to get stuck between the wall and disposal unit with no way to get out. Climbing in the disposal and getting out ejects me against the wall again.

**Comment by metalgearsloth** [comment]
Fix is to keep track of the entity when it exits somewhere and use PreventCollideEvent, then when the collision ends remove it from the list (similar to what tables do).

The old (broken) functionality for this was removed in a recent PR I did.

**Comment by metalgearsloth** [comment]
Disposals part fixed, lag sounds completely unrelated.
