### ISSUE TITLE
Movement of larger objects awkward during pulling

### ISSUE THREAD

**Issue by Swirl-droid** [space-wizards/space-station-14#4087]
**Description**
Moving larger objects such as lockers and fuel tanks feels awkward during pulling, with the objects frequently getting stuck in doorways and around corners. It is also possible to get tethered by smaller objects such as trash if they are crammed behind larger ones. The H-key does not seem to drop objects as suggested in the controls menu.

**Screenshots**
https://user-images.githubusercontent.com/84341487/119843550-f3269380-bf07-11eb-9e4c-22dcd32abf14.mp4
https://user-images.githubusercontent.com/84341487/119846345-587b8400-bf0a-11eb-8210-51f9058a368b.png

**Additional context**
v 0.1
Server: Wizard Lizard Den [US West]

**Comment by metalgearsloth** [comment]
You should mention this is about pulling specifically which needs a refactor to be more similar to the old behaviour

**Comment by wrexbe** [comment]
I turned on rotation for lockers, and they didn't get stuck anymore. I feel like if the fixed items could rotate a little bit, they wouldn't get stuck.

**Comment by ShadowCommander** [comment]
> I turned on rotation for lockers, and they didn't get stuck anymore. I feel like if the fixed items could rotate a little bit, they wouldn't get stuck.

The main problem with lockers is that they have tall rectangular hitboxes that are the height of a tile. So going through a doorway to the right or left is much harder than going through a doorway up or down. I'll put it up as a topic for the next maintainer meeting.

**Comment by AJCM-git** [comment]
Bob fixed the main complaints in this issue, pulling still needs some tweaks but that should be defined in detail on a new issue.
