### ISSUE TITLE
Refactor machine YAML

### ISSUE THREAD

**Issue by ShadowCommander** [space-wizards/space-station-14#4096]
## Description

A bunch of machines have duplicate YAML like clickable, draggable, anchorable and such. It's getting to the point where some are getting forgotten so I created a BaseMachine prototype.

Need someone to go through all of the machine prototypes and change the parent to BaseMachine as well as remove duplicate components.

**Comment by ShariaThotPatrol** [comment]
Can you provide an example and I will get on it?

**Comment by ShadowCommander** [comment]
Basically a lot of machines have common components like:

https://github.com/space-wizards/space-station-14/blob/5c9921e81bd7a2b477396be2442475d7242c3840/Resources/Prototypes/Entities/Constructible/Specific/Medical/cloning_machine.yml#L1-L48
https://github.com/space-wizards/space-station-14/blob/5c9921e81bd7a2b477396be2442475d7242c3840/Resources/Prototypes/Entities/Constructible/Specific/Medical/medical_scanner.yml#L1-L49
So the common things I combined into a parent entity BaseMachine and BaseMachinePowered, so now they look like this:
https://github.com/space-wizards/space-station-14/blob/9d7094fbd72b557d567afa09841b625353a9c401/Resources/Prototypes/Entities/Constructible/base_machine.yml#L1-L37
https://github.com/space-wizards/space-station-14/blob/9d7094fbd72b557d567afa09841b625353a9c401/Resources/Prototypes/Entities/Constructible/Specific/Medical/cloning_machine.yml#L1-L32
https://github.com/space-wizards/space-station-14/blob/9d7094fbd72b557d567afa09841b625353a9c401/Resources/Prototypes/Entities/Constructible/Specific/Medical/medical_scanner.yml#L1-L23

**Comment by ShariaThotPatrol** [comment]
I noticed some machines likes microwaves and reagent grinder don't have destructible or damageable types. Do you want these included as well?

**Comment by ShadowCommander** [comment]
Those two are tabletop machines so they're a bit different. They aren't full tile so they shouldn't be included in this.

**Comment by AJCM-git** [comment]
Seems like all machines now inherit BaseMachine or BaseMachinePowered
