### ISSUE TITLE
Chat messages visible through walls

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#4098]
## Description
1. stand inside the range of a vendor but where it is not visible to you
2. wait for it to advertise
3. its visible

this maybe applies to normal chat as well??? i cant tell

**Screenshots**
![image](https://user-images.githubusercontent.com/19853115/119945430-4cafb200-bf4a-11eb-9405-1ebb7ed4cc48.png)

**Additional context**

**Comment by Swirl-droid** [comment]
I've also encountered this bug for the message when you impale a monkey on a spike.

**Comment by metalgearsloth** [comment]
Pretty sure advertisingcomp goes through normal chat

**Comment by Visne** [comment]
Yes, vending machines use `IChatManager.EntitySay()`, just like every other chat command. So I'm pretty sure this also happens with normal chat, and the issue should probably be renamed.
