### ISSUE TITLE
Gas overlays are drawn on top of FOV

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#4099]
## Description

repro
1) spawn like 10000 moles of gas in a room
2) open the door
3) watch it flood everywhere and break a lot

in the screenshot:

1) rooms that should not be visible to me at all have gas overlays drawn on them, which also outlines walls
2) gas overlays are drawn on top of the FOV, which they probably shouldn't be

these might be the same underlying issue

**Screenshots**
![image](https://user-images.githubusercontent.com/19853115/119953586-014dd180-bf53-11eb-8bea-01e1b75e1206.png)

**Additional context**

**Comment by mirrorcult** [comment]
i think the actual underlying issue is just that gas overlays are drawn on top of the FOV for some reason

**Comment by Zumorica** [comment]
yeah, that's the real issue here

**Comment by Zumorica** [comment]
also, for the record: this didn't use to be a thing a few weeks ago

**Comment by metalgearsloth** [comment]
The new WorldSpaceBelowFov doesn't actually work so this is an engine issue @GraniteSidewalk

**Comment by metalgearsloth** [comment]
Done by PJB.
