### ISSUE TITLE
Atmospherics

### ISSUE THREAD

**Issue by ghost** [space-wizards/space-station-14#41]
A zone based atmospherics system. 
Implement a flood fill algorithm to create a number of zones that are blocked off from each other with an airblocking component. Establish connection edges to space on any zones touching space.
When zones connect begin to equalize pressure and cause airflow movement from one zone to the other based on pressure differential. If blockers are destroyed create an airflow connection and finally merge after pressure equalizes sufficiently. If walls are created check to see if a new zone has been walled off.
Implement damage from under/overpressure and from not having the right gases in the atmosphere to breath.

**Comment by acvzy** [comment]
Moved [here](https://hackmd.io/fUPCP7RDTe6mN6lroa0K_w?both#Ghost-2018-03-06)
