### ISSUE TITLE
hacking ideas/improvements

### ISSUE THREAD

**Issue by The-Scout** [space-wizards/space-station-14#410]
pjb3005 said on reddit it would be good if i left a github issue about this.

/u/HeatLiquid posted this modification to the hacking mock up from the most resent update post. https://i.imgur.com/9Ly0tIM.png
"It would be great if the hacking system allowed to swap the connected wires."

I think this should be worked on being implemented, but sadly don't have the coding knowledge to do it myself so an issue seems most worthwhile.

Some wire crossing ideas.

High Voltage Ground linked to id scan, shocks person trying to open the door if they have a valid or invalid id.
High Voltage Ground linked to bolt wire, when bolts are down, shocks people.
Safety wire linked to bolt wire, crushes people like a safety wire cutting, but bolts down after.
Bolt lights wire linked to power, bolt lights always on, even if door is not bolted.
Open linked to id scan enables emergency access?
Goes without saying wireless transmitter taped onto interface is the best thing ever.

Any other ideas?

**Comment by PJB3005** [comment]
I guess you could define it as "each wire can be 'pulsed' such that if it is crosswired, it will act as if the wire it connects to was pulsed"? 

So basically the ID lock wire "gets pulsed" when you try to open the airlock, so if you connect that through to bolts it'll pulse the bolts wire.

**Comment by acvzy** [comment]
Game design issues are now being removed from Github and added to the [HackMD docs](https://hackmd.io/@ss14/docs).

Your issue was moved to [here](https://hackmd.io/96HHKT-VQ2KO91c9i75V8A?both#2019-10-23-The-Scout%E2%80%99s-suggestion).
