### ISSUE TITLE
Plasma and tritium don't hurt you

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#4100]
## Description

**Screenshots**

https://user-images.githubusercontent.com/19853115/119954400-c9935980-bf53-11eb-948d-1368aadd696d.mp4

**Additional context**

**Comment by Zumorica** [comment]
related #3981

**Comment by mirrorcult** [comment]
didn't plasma/tritium used to hurt people, though? or am i misremembering
