### ISSUE TITLE
Gas spreading behavior seems off

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#4101]
## Description
the gas spreads really  fast initially, but then just... kinda stops spreading almost entirely and doesn't seem like it tries to equalize at all even though there's a ton of pressure to be equalized; when it does equalize, its very jerky and does it all at once like 5-10 seconds too late

**Screenshots**

https://user-images.githubusercontent.com/19853115/119955573-06138500-bf55-11eb-9f9f-4e842f1d6498.mp4

**Additional context**

**Comment by Zumorica** [comment]
This seems like a non-issue to me. Also, rather than rely on gas overlays use the `showatmos` command to debug anything atmos.

**Comment by Zumorica** [comment]
Like, you added 1000 moles of gas to a small room, then you open an airlock and let it spread to a bigger room... Of course it's not gonna fill the entirety of it if there's not enough pressure difference

**Comment by mirrorcult** [comment]
its more obvious with a much larger quantity of moles, the video i took is kind of bad

**Comment by mirrorcult** [comment]
regardless probably not a 'bug' just seems a little off

**Comment by Zumorica** [comment]
The higher the pressure, the faster the gas spreads. The lower the pressure, the slower it spreads.
Here's a video with the atmos debug overlay on to show what I mean, focus on the colors (green less pressure, blue more pressure)
https://streamable.com/msvmcu

**Comment by mirrorcult** [comment]
ill chock this up to a its 2 am moment
