### ISSUE TITLE
Crafting a stack of something reports incorrect stack numbers and visualizers.

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#4107]
![image](https://user-images.githubusercontent.com/7907891/120089371-7e9a5300-c0c7-11eb-8e5e-c558928a05a3.png)

![image](https://user-images.githubusercontent.com/7907891/120089374-83f79d80-c0c7-11eb-871e-8092ad9f544b.png)

How to reproduce:

- Craft two metal rods. 
- The game will show a full stack on the ground, but right-click examining will show the correct amount.
- Pick the stack up. It will show in your hand as there being 30 rods in the stack.
- Attempt to use the rods for something (placing lattice or crafting reinforced glass). After one craft, the stack will show the correct number.

This also happens with reinforced glass.

**Comment by Zumorica** [comment]
Fixed by 1ec2f3929165df65b6545f2d46643dbfc41ccdec
