### ISSUE TITLE
Spears do contact damage when dropped

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#4113]
How to reproduce:

- Make a spear.
- Go into combat mode.
- Repeatedly drop the spear onto something while mashing clicks to pick it up as soon as it's dropped.
- The spear will rapidly chew through pretty much anything it touches, up to and including reinforced walls.

![image](https://user-images.githubusercontent.com/7907891/120112465-fad27c00-c143-11eb-8d72-e37f5d12458e.png)

It seems like this bug is kind of inconsistent and lag-dependent, but it does work for some people.

**Comment by ShadowCommander** [comment]
Tested and it happens when picking up a spear after throwing before it lands. Dropping the glitched spear triggers ThrowCollide.DoHit.

**Comment by ShadowCommander** [comment]
Actually and spear that has been thrown. Doesn't have to be moving.
