### ISSUE TITLE
Portal refactor

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#4125]
We "technically" have them but they're pure shit and 2 years old so would need a refactor anyway.

Ideally:
* Non-hard fixture (probably make it a circle given it'll likely rotate with shuttles)
* Whenever a StartCollideEvent is raised try to send the entity to the connected portal (probably make each portal 1-way so you can have a chain of them rather than having each one bi-directional).
* Make them use snapgrid
* unshaded so they show up in the dark (maybe also give them a pointlight)
* Teleported entity should maintain velocity (which means you need no work if the portal doesn't have any hard fixtures).
* *Ideally* you'd have PVS support for it but that'd also be annoying to do and require engine work to support.
* Add in hand tele / event or whatever after.
* Teleport needs to also make sure stuff like contacts / joints are destroyed for physics.

**Comment by Zumorica** [comment]
Portals? Don't know 'em.
