### ISSUE TITLE
Bullet flyby sounds

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#4129]
When a bullet goes past you it should have a sound play.
How I would personally go about it:
* Add another fixture to bullets that's non-hard.
* When StartCollideEvent is raised play a random sound to that player (client-side only).

**Comment by PJB3005** [comment]
It sounds better to me to just make the sound system capable of prioritizing and toggling sounds and then having a short-range sound effect.

Make sure to add doppler effect.
