### ISSUE TITLE
Add Meth

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#4139]
## Description

Should make you zoom

**Comment by scaly-chimp** [comment]
assign me to status of meth-man

**Comment by SethLafuente** [comment]
I can add meth it won’t do anything but I can add it and the other products necessary to make it

**Comment by SethLafuente** [comment]
Also will Lodine be added to the chem dispenser?

**Comment by scaly-chimp** [comment]
nah meths mine man back off

**Comment by SethLafuente** [comment]
No meth-man status for you then

**Comment by SweptWasTaken** [comment]
> 
> 
> I can add meth it won’t do anything but I can add it and the other products necessary to make it

No.

**Comment by Ygg01** [comment]
Swept is right. Adding just a prototype without any behavior is considered an anti-gamer move.
