### ISSUE TITLE
AMEs no longer explode properly

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#4152]
![image](https://user-images.githubusercontent.com/7907891/120954272-cdc23280-c71c-11eb-850e-0d003e1e1ce6.png)

How to reproduce:

- Make an AME
- Set injection to 100, inject fuel
- AME will only blow up in a one-tile radius and destroy nothing but itself

Expected behavior is an explosion strong enough to create breaches.

**Comment by DogZeroX** [comment]
It creates big breaches last time i saw
