### ISSUE TITLE
Prototypes Reorganization

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#4167]
## Description

Need to reorganize the Prototypes folder to reflect the guidelines set in https://github.com/space-wizards/space-station-14/issues/4165.

Probably gonna be a nightmare to do but since i've done a lot of the reorganization myself lately i'll be doing this. I will likely mirror @DrSmugleaf's PR and split every section of the Prototypes folder into commits to make reviewing less of a pain.

Mostly making this PR so I can claim it and stop Smug from working on it.

**Comment by DrSmugleaf** [comment]
> Mostly making this PR so I can claim it and stop Smug from working on it.

Why live

**Comment by SweptWasTaken** [comment]
> 
> 
> > Mostly making this PR so I can claim it and stop Smug from working on it.
> 
> Why live

To finish BodySystem and map diff.

**Comment by DrSmugleaf** [comment]
wyci

**Comment by mirrorcult** [comment]
tbh i'm not sure if the way I laid out it to reorganize prototypes makes that much sense but we'll see I suppose

**Comment by moonheart08** [comment]
Pretttty sure this got done?
