### ISSUE TITLE
Containers are spawning the items they contain on top of them

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#4168]
![image](https://user-images.githubusercontent.com/7907891/121458842-1f1a2e00-c978-11eb-93e8-61a022f826e0.png)

![image](https://user-images.githubusercontent.com/7907891/121458944-5092f980-c978-11eb-9a05-8d44fd918470.png)

This is very similar to the 0,0 bug in that it's just spawning the sprites, not the actual items. Seems to happen in some places (HoP office, science) and not others.

**Comment by metalgearsloth** [comment]
Looks like someone did mapping without pausing it if this is on live.

**Comment by SweptWasTaken** [comment]
> 
> 
> Looks like someone did mapping without pausing it if this is on live.

Sigh. Hotfixing...

**Comment by SweptWasTaken** [comment]
I don't think this is on live. Closing.
