### ISSUE TITLE
Verb names are not localized

### ISSUE THREAD

**Issue by DamianX** [space-wizards/space-station-14#417]
The value returned from `Verb.GetText()` should be passed through `LocalizationManager.GetString()`.

**Comment by PJB3005** [comment]
It shouldn't be passed through `GetString`. The return value may be the result of string formatting based on certain factors, in which case that wouldn't work.

It's probably best to add an `ILocalizationManager` parameter to `Verb.GetText()`.

**Comment by DamianX** [comment]
That increases the amount of boilerplate, though. Now instead of returning a string you have to *always* call a method on that ILocalizationManager parameter, if I'm understanding it right. Why not have the caller deal with it?

**Comment by PJB3005** [comment]
> Why not have the caller deal with it?

Because it can't in every case. If the caller deals with it there should be a way to turn off said behavior to prevent issues.

**Comment by PJB3005** [comment]
Somewhere along the way this was solved, I think.
