### ISSUE TITLE
Grindable/Juiceable needs to be reworked

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#4198]
## Description

So as [bike-shedded on Discord](https://discord.com/channels/310555209753690112/310555209753690112/854566238339989504) we talked about how confusing Grinding/Juicing are and blah blah. Anyway we need to make clearer the distinction between juicing and grinding something. There's also the matter of #4179 which technically is already fixed by using JuiceableComponent.

Do we want to remove dual functionality from the Juicer/Grinder?

Do we want to just merge Grindable/Juiceable? Juiceable seems to mostly be for food related objects like apples and oranges in SS13 so maybe do mirrorcult's idea about having a [dedicated food processor](https://discord.com/channels/310555209753690112/310555209753690112/854570622091788348)? 

I think having a dedicated food processor is a good idea because juicing your apples into a beaker is kinda weird anyway. I also think merging Juiceable/Grindable into one thing is good as then we can just automatically use a SolutionContainer if no `result:` is specified.

**Comment by Ygg01** [comment]
Closed by #4407

**Comment by SweptWasTaken** [comment]
> 
> 
> Closed by #4407

This won't link the issue you need to put "Closes #IssueNumber" in your PR itself for the automation to work properly.
