### ISSUE TITLE
Mob statuses

### ISSUE THREAD

**Issue by ghost** [space-wizards/space-station-14#42]
Statuses that affect the mob directly and can be queried to ask if the mob is capable of actions.
Asking if mob is currently able to do an interaction
Preventing mob movement
Taking away sight
Adding screen overlays based on status such as health, darkness on unconsciousness, jelly screens when dead/heavily damaged

## Mob Huds
A part of inventory handling and mob statuses. Implementing huds to represent things held in inventory, mobs statuses, and updating them

Implementing mob death, and unconsciousness.

**Comment by Injazz** [comment]
done in #130

**Comment by Acruid** [comment]
The status effects appear to not be implemented yet in #130, so this stays open.

**Comment by Acruid** [comment]
Combination of Health (#130) and Hunger[(#363) demonstrates all of this.
