### ISSUE TITLE
Implement cooldowns on melee weapons.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/space-station-14#420]
Right now melee weapons attack as fast as you can click. 

There should be some cooldown specific to the weapon to make this more reasonable.

Bonus points if there was an indicator on your hands showing how much cooldown is left. I'm imagining one of those circle animated things overlayed over the weapon:

![image](https://user-images.githubusercontent.com/8107459/68512161-e08e3000-0277-11ea-9ffd-be12fbd44011.png)

**Comment by Erisfiregamer1** [comment]
wasted a perfectly good 420 here

**Comment by Zumorica** [comment]
> wasted a perfectly good 420 here

Please stop posting useless comments in our repos.
