### ISSUE TITLE
New lighting reverts in certain areas

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#4211]
![image](https://user-images.githubusercontent.com/7907891/122683716-0eb35000-d1cf-11eb-868c-b867f0c1ef38.png)

![image](https://user-images.githubusercontent.com/7907891/122683718-1a067b80-d1cf-11eb-968d-ffbce5ab4b43.png)

For some reason, there's a line right by the library where the game will get noticeably brighter.

**Comment by metalgearsloth** [comment]
Dupe https://github.com/space-wizards/space-station-14/issues/3922
