### ISSUE TITLE
Loc.GetString refactor issues

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#4213]
## Description

Keeping track of any issues caused by the big fluent refactor by @GalacticChimp in #4155

PA computer is messed up (Seþ # 2464)
![image](https://user-images.githubusercontent.com/19853115/122694123-40d5a980-d1f1-11eb-8bac-94311edb6f86.png)

AME number labels don't have spaces before them (Seþ # 2464)
![image](https://user-images.githubusercontent.com/19853115/122694134-47642100-d1f1-11eb-988a-fd64480d6477.png)

**Comment by SethLafuente** [comment]
R&D console is messed up (Seþ # 2464)
![image](https://user-images.githubusercontent.com/84478872/122700108-80a38d80-d1ff-11eb-8c3f-f9ab4a2e9071.png)

**Comment by SethLafuente** [comment]
Medical scanner verb eject is messed up (Seþ # 2464)
![image](https://user-images.githubusercontent.com/84478872/122701924-25739a00-d203-11eb-9d5f-db507c2777df.png)

**Comment by metalgearsloth** [comment]
![image](https://user-images.githubusercontent.com/31366439/122719115-1ba87000-d2b1-11eb-9f48-2a9febdd0649.png)

**Comment by PJB3005** [comment]
![image](https://user-images.githubusercontent.com/8107459/122732510-a622ac80-d27c-11eb-9d4c-7b4e6753f255.png)

Connecting dialog is broken.

**Comment by GalacticChimp** [comment]
ok, I'll take a look at these

**Comment by SethLafuente** [comment]
![image](https://user-images.githubusercontent.com/84478872/123000197-1c4e0e80-d364-11eb-8dde-a6dfb462f635.png)
Character inventory menu is broken

**Comment by mirrorcult** [comment]
#4226

**Comment by GalacticChimp** [comment]
so far I've fixed all of the above issues + a few more. Perhaps let's wait a week more, and collect a few more errors.
