### ISSUE TITLE
Vendor advertisements visible on other maps

### ISSUE THREAD

**Issue by Acruid** [space-wizards/space-station-14#4215]
## Description
Vendor advertisement chat bubbles and local text are visible on other maps.

## How to reproduce
* join the game
* add a new map
* tp to 0,0 on new map
* see chat bubbles and local text where the position of the vending machine is on the other map

**Comment by Zumorica** [comment]
I can't replicate this, the bubbles don't show up.

**Comment by Zumorica** [comment]
Nevermind, I moved around and replicated it.
