### ISSUE TITLE
Fire extinguisher spray doesn't go anywhere

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#4216]
## Description
Broke sometime between now and #4154 

**Screenshots**

https://user-images.githubusercontent.com/19853115/122720730-ac853a00-d224-11eb-9e1e-774da621ca12.mp4

**Additional context**

**Comment by Zumorica** [comment]
Fixed by ff6cd0043843207d11f8eb067e413940b734469e
