### ISSUE TITLE
EmitSoundSystem needs to be able to take both soundCollections and sounds

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#4219]
## Description

Currently Vox/Snake/Mouse plushies make no sound when squeezed because whoever refactored ToysComponent into EmitSound component forgot to update the `sound:` fields in the yaml. 

I don't think creating a sound collection for single sounds is good practice so EmiteSoundSystem needs to take both soundCollection IDs and sound paths.

**Comment by RemieRichards** [comment]
agree

**Comment by GalacticChimp** [comment]
I did  the refactor. The first version of the PR had support for both sound collections and single sounds, but I got suggestions about not needing both. I'll revert the removal of sound collections from EmitSoundSystem

**Comment by Zumorica** [comment]
Honestly, we should just have an union-like data structure that can hold either a single sound or a collection and use that everywhere. Duplicating so much code across anything that could ever play sound is awful, honestly...

**Comment by Zumorica** [comment]
#4239 will help with this
