### ISSUE TITLE
Taser Bolt Spawning Error 

### ISSUE THREAD

**Issue by SethLafuente** [space-wizards/space-station-14#4223]
## Description

When a taser bolt is shoot from a taser the bolt will spawn on the shooting entity and not were ever the mouse is placed
 
**Screenshots**

![8EK7TT9O4b](https://user-images.githubusercontent.com/84478872/123327035-cd80b000-d4ee-11eb-86a7-9aaa8d31cf37.gif)

**Comment by Zumorica** [comment]
Can't replicate on latest master

**Comment by SethLafuente** [comment]
Currently I'm on the USwest server and every time you shoot a taser this happens it has being like this for a while I have no idea why you can't replicate it

**Comment by metalgearsloth** [comment]
> Currently I'm on the USwest server and every time you shoot a taser this happens it has being like this for a while I have no idea why you can't replicate it

Maybe because you didn't provide the steps to replicate?

**Comment by SethLafuente** [comment]
> > Currently I'm on the USwest server and every time you shoot a taser this happens it has being like this for a while I have no idea why you can't replicate it
> 
> Maybe because you didn't provide the steps to replicate?

I think I was pretty clear just shoot the taser

**Comment by Zumorica** [comment]
This cannot be replicated so closing until someone else gets it on latest master
