### ISSUE TITLE
`construction-insert-material-entity` appears instead of actual construction examine text.

### ISSUE THREAD

**Issue by 20kdc** [space-wizards/space-station-14#4226]
## Description
See screenshot.

**Screenshots**
![image](https://user-images.githubusercontent.com/22304167/123523553-205b9280-d6bc-11eb-867e-acf3ce5b69c5.png)

**Additional context**
This can be seen by examining the particle accelerator at roundstart.

**Comment by mirrorcult** [comment]
should go in #4213
