### ISSUE TITLE
Singularity forcefield no longer works at all

### ISSUE THREAD

**Issue by 20kdc** [space-wizards/space-station-14#4227]
## Description
It's all unanchored and the rotations are all wrong...

**Screenshots**
![image](https://user-images.githubusercontent.com/22304167/123523593-72041d00-d6bc-11eb-89e8-4ca0d9ea3c84.png)

**Additional context**

**Comment by mirrorcult** [comment]
probably somehow caused by entity anchoring changes

**Comment by SweptWasTaken** [comment]
Some things that spawn spawn facing south which is the issue with these force-fields.

**Comment by metalgearsloth** [comment]
I broke it when porting box2d because of this extremely cursed class that should be refactored https://github.com/space-wizards/space-station-14/blob/ff1a2d97ea214de6d393da1b86fc6109cb528a07/Content.Server/Singularity/Components/ContainmentFieldConnection.cs#L93

**Comment by 20kdc** [comment]
I have a decent guess as to why it's unanchored.
Simply put, as you can see, all unanchored containment field objects have *the tiles underneath them missing*.
Removing the tile underneath an anchored object appears to now unanchor it.

**Comment by 20kdc** [comment]
Reasonably sure metalgearsloth didn't break it

If I had to guess what did it, see the reasoning above and this code:
pinging @Acruid
https://github.com/space-wizards/RobustToolbox/commit/713f702064dd529a11ff3a75c2eaac2056d7466e#diff-8688ace28a96e9151b5439400fc55927c8af16a9e16a6118dc62b478edc96ce5R28

**Comment by metalgearsloth** [comment]
I commented out the repel lines so.

**Comment by 20kdc** [comment]
thing is, repel wasn't the only thing acting there anyway, during the Jazz PRs I set things up so physics collision masks took over for it so that the singulo would at least actually be contained
Means that particular part is probably a mess of dummy code but w/e
the point is, singularity was usable again after the Jazz PRs

Some other notes about the Acruid PR are that it looks like it implements some functionality which... to be honest, should engine really be deciding that empty tiles specifically are the unanchorable ones?
...Should engine really be deciding to do something that content can trivially implement anyway?
...I feel like it'd be easier if it was in content, and then it could trivially implement some tag or something it could use to make containment fields exempt.

As for rotation, the lead on that so far appears to be that anchorable objects aren't allowed to rotate themselves anymore. This breaks *all* the things, especially since I'm not aware of a "spawnentity with rotation" which this implicitly absolutely requires.

**Comment by 20kdc** [comment]
further notes on rotation:
Assuming that the problem is anchoring deciding that stuff cannot ever under any circumstances be rotated, note that a "SpawnEntity with rotation" wouldn't even be a be-all-end-all solution, as there are cases where an entity that is anchored needs to rotate itself.
Point being, the code in space-wizards/RobustToolbox/Robust.Server/Placement/PlacementManager.cs:122 to spawn an entity is 2 lines that make sense and breaking this code would just lead to "wtf why doesn't my code work" moments in future.

**Comment by metalgearsloth** [comment]
The end goal of anchoring is to fix PVS major perf problems so it does need to be engine.

**Comment by 20kdc** [comment]
With that part I'm referring specifically to the `MapManagerOnTileChanged` part of the anchoring PR, where it just unanchors something if it's on an empty tile. I'm not sure how this affects PVS.

**Comment by metalgearsloth** [comment]
Was fixed
