### ISSUE TITLE
Tile friction is too low

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#4263]
## Description

Stuff slides around super easily, making pulled objects like lockers and fuel tanks look like they've got soap under them.

**Comment by GalacticChimp** [comment]
as per @metalgearsloth suggestion, I'll try this one

**Comment by SweptWasTaken** [comment]
> 
> 
> as per @metalgearsloth suggestion, I'll try this one

Already being done - https://github.com/space-wizards/space-station-14/pull/4329

**Comment by GalacticChimp** [comment]
ayy, nevermind then
