### ISSUE TITLE
Assembling the AME with parts causes it to break

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#4276]
## Description

If you assemble the AME just by spawning the shielding and the controller then it'll work when injecting but if you assemble it by placing down the parts, multi-tooling them all and then connecting a controller it won't function.

1. Spawn parts in 3 by 3
2. Multi-tool them all
3. Connect a controller
4. Try to insert fuel jar and inject

![UhFcPgX](https://user-images.githubusercontent.com/49448379/126002110-d893c3d8-0bc6-434f-b83a-4b0d026aede1.png)

It shows it's injecting and you'll see fuel status but the AME itself won't appear lit. Maybe an issue with the visualizer?

**Comment by AJCM-git** [comment]
Works just fine in latest master. Closing
