### ISSUE TITLE
Throwing an item while buckled to a chair will attach the item to the chair you were buckled to

### ISSUE THREAD

**Issue by Fiftyllama** [space-wizards/space-station-14#4279]
Throwing an entity while buckled will attach the entity to the thing you're buckled to,
aditionally, if you throw an item from a chair you've moved the item will be "thrown" from the opposite of the length of the chair origin point.

steps to reproduce:
1. get an item.
2. buckle yourself.
3. throw item.
4. unbuckle and move chair.
for bonus points:
5. rebuckle to the chair.
6. throw item.
7. see how the item teleports the same distance from the chairs current possition as the chairs current possition from the chairs origin.

https://user-images.githubusercontent.com/45442346/126044574-09ab1de6-22f4-404c-8994-fed005c83f8d.mp4

**Comment by metalgearsloth** [comment]
I can't replicate this so I assume it's fixed.

**Comment by ShadowCommander** [comment]
Fixed by #4528
