### ISSUE TITLE
Disability-oriented customization options like high-contrast mode and filters for color-blindness

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#4280]
## Description

High-contrast mode for UIs and text boxes like in the Division 2.

![servlet](https://user-images.githubusercontent.com/49448379/126044680-e11a848b-cd46-4465-8cc7-68f9659eb94d.jpg)

We also need some colorblind modes. And don't do them crappily like Overwatch did.

![3rth9c4zjbocnxvfxsfoy6yew6k3lgcuk1evhczvjewfi7ky4xqhxyqp6smurwii](https://user-images.githubusercontent.com/49448379/126044891-bc95a641-2c26-4562-89d2-024f0a559619.jpg)

**Comment by mirrorcult** [comment]
too generic + we have some of these now anyway
