### ISSUE TITLE
Breaking a container while you're inside of it crashes the game

### ISSUE THREAD

**Issue by Fiftyllama** [space-wizards/space-station-14#4291]
Steps to reproduce:
1: Get gun
2: Get into locker
3: So anyways, i started blasting (destroy locker)
4: sit back and enjoy the crash

This is also true for crates, but not for disposals 

https://user-images.githubusercontent.com/45442346/126218244-22232772-ed19-4f33-ab8b-8bdf984f8e54.mp4

**Comment by PaulRitter** [comment]
cannot replicate on master. i tried:
- breaking the container with a second client
- breaking the container myself

to no avail
