### ISSUE TITLE
Backpacks/Boxes/Holdable Containers should be openable by clicking on it.

### ISSUE THREAD

**Issue by GraniteSidewalk** [space-wizards/space-station-14#4298]
As opposed to the tiny box that currently pops up. This needs to be a setting in options (click to open v.s. no click to open). Maybe remove the tiny box entirely, not sure if anyone at all likes that.

**Comment by Zumorica** [comment]
I'm personally against this

**Comment by SweptWasTaken** [comment]
> I'm personally against this

I am too. I like how it is currently. However I think the resizing of tiny buttons like this would be nice, simply because pixel-hunting for them on small UIs might be annoying.

**Comment by ShadowCommander** [comment]
The tiny button is there for people that like to use mouse for everything.

For everyone else we already have the ActivateItemInWorld (E) hotkey that opens backpacks. Making Use (Click) also do so would make storage items inconsistent with how every other item works, where Use is for picking it up, and ActivateItemInWorld is for activating it.

**Comment by SweptWasTaken** [comment]
Closing this as i'm pretty sure we've decided to stick with what we've got.
