### ISSUE TITLE
Create a custom mouse pointer for the game and make it change color depending on the intent.

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#4302]
## Description
Common issue from SS13 itself is not realizing you're in harm intent and accidentaly smashing/killing/shooting, this feature should make the player more aware of the current intent to avoid oopsies.

**Screenshots**
~~Awful~~ Example of:
![image](https://user-images.githubusercontent.com/43253663/126401796-e3dadbc0-c1fd-4010-862b-38eca5856542.png) Harm
![image](https://user-images.githubusercontent.com/43253663/126401843-ecb1da52-3c17-4b7a-8c95-6b078bc3073f.png) Disarm

**Additional context**
There could also be a variant that says you can't interact, either because the hand selected is "off-hand" or crippled.

**Comment by Visne** [comment]
Kind of a duplicate of #3429

**Comment by mirrorcult** [comment]
ill keep both up
