### ISSUE TITLE
Pick up distance is determined by distance to cursor, not distance to entity

### ISSUE THREAD

**Issue by Visne** [space-wizards/space-station-14#4303]
If you click the far side of an item barely out of range, you can't pick it up. If you click the close side you can.

**Comment by Visne** [comment]
This is caused by `InteractionSystem.UserInteraction` using mouse coordinates instead of entity location. Personally I feel like using the entity location (so the center of the entity) is fine, but I don't think @metalgearsloth agrees. Would like to hear more opinions.

**Comment by mirrorcult** [comment]
check if the coordinates are in range unobstructed, and if that fails check if the entity's center is

**Comment by Visne** [comment]
> 
> 
> check if the coordinates are in range unobstructed, and if that fails check if the entity's center is

What's the point of checking both?

**Comment by mirrorcult** [comment]
if an entity is really big (or just larger than one tile), then just checking the center might fail even if you probably should be able to interact with it

**Comment by metalgearsloth** [comment]
I think it should check either cursor range or nearest BB point (If cursor out of range) which required physics work. Currently you can't interact with the grav gen on the corners.

**Comment by Visne** [comment]
> 
> 
> if an entity is really big (or just larger than one tile), then just checking the center might fail even if you probably should be able to interact with it

But that wouldn't fix this issue; if the entity center is out of range, then you can pick it up when hovering over the near side but not the far side.

**Comment by Visne** [comment]
Maybe small items should just use entity center, larger ones should use mouse coordinates. Assuming the green/red outline actually matches:

If you hover over the far side of a toolbelt for example and you can't pick it up, but on the near side you can, that just feels weird and inconsistent. On the other hand, hovering over the far side of the gravity generator and not being able to interact, while being able to interact when hovering over the near side makes sense.

**Comment by Visne** [comment]
Final solution: first check if the center is in range (cheap calculation), if not check if the bounding box is in range (but decrease the range a little because the bounding box is larger).

This avoids using the distance to the cursor completely, which would always lead to inconsistent behaviour.

**Comment by PaulRitter** [comment]
i suppose the final solution is fine, gotta ask @metalgearsloth if getting the range to the bounding box is possible.

don't know why you would decrease the range a little when checking against the bounding box tho.

**Comment by Visne** [comment]
> 
> 
> i suppose the final solution is fine, gotta ask @metalgearsloth if getting the range to the bounding box is possible.
> 
> don't know why you would decrease the range a little when checking against the bounding box tho.

It is possible, but the current implementation for that isn't tested well.

If you don't decrease the range for bounding boxes, then you would get a different pick up range for the two checks. To me that doesn't make sense.

**Comment by metalgearsloth** [comment]
https://github.com/space-wizards/space-station-14/pull/11660 Fixes the nearest edge part.

I think ideally to improve interaction angles for stuff like airlocks we should check for penetration below a certain amount and allow it, then update InRangeUnobstructed to use the nearest edge points.
