### ISSUE TITLE
HandHeld radios are broken

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#4306]
## Description

Looks like they were broken by the chat update maybe?

**Screenshots**

![2021-07-20_19-45-04](https://user-images.githubusercontent.com/49448379/126422534-e9db4c4e-7e7a-4e3e-b65d-bcfb8e7398c3.gif)

**Comment by mirrorcult** [comment]
can't replicate, even with a headset off as demonstrated

https://user-images.githubusercontent.com/19853115/126892050-f68970db-de7c-46ff-8842-3f6559396187.mp4
