### ISSUE TITLE
Shuttle/vehicle movement structure seems dodgy

### ISSUE THREAD

**Issue by 20kdc** [space-wizards/space-station-14#4335]
## Description

This issue is very much an abstract code-structure issue right now, but I think it'll be a problem later.
I was told to open an issue on this.

Right now, there is no actual concept of movement states (i.e. no interface for such).

However, there are three movement modes regardless. They are laid out in an order which is not respective of priority in code that otherwise seems like it's supposed to use this information to achieve prioritization (server `MoverController`):
+ Mob Movement - Always applied if `IMobMoverComponent` is available. Adds to `_excludedMobs`, does not read. Standard movement. Cares about CanMove (but this is 'interior', not relevant for mode prioritization)
+ Shuttle Movement - Applied if `PilotComponent` is available *and* it is connected to a console. Adds to `_excludedMobs`, does not read. Shuttle control.
+ Kinematic Movement - Always applied if `IMoverComponent` (required for any movement processing whatsoever) is available. Reads and ignores those entities in `_excludedMobs`. Ghost movement - ignores CanMove, etc.

This points to some attempt to use `_excludedMobs` to use prioritization to keep the states consistent, but this wasn't actually made use of properly, so instead `PilotComponent` is also a marker that enacts a movement block if it's connected to a console.

## Specific concerns

The specific concerns I have with this approach are that adding states to this will inevitably require those states trigger movement blocks, which will prevent *other* movement blocks from being tested for even when they really should be.

(In particular, I was looking into how this might have an effect on the development of ~~clown cars~~ non-shuttle vehicles. The answer appears to be that to implement those, one would need to either handle it via buckling (likely not an option for various reasons under normal circumstances) or implement some sort of mirror system to piloting for the driver of a vehicle, doing a movement block, etc.
The worry I have is that doing such a thing would interact badly with if someone driving a vehicle then went on to attempt to pilot a shuttle while driving a vehicle. In this case, both movement states would then be in effect simultaneously.)

## Citations

Relevant code (as of master at time of writing) with their roles in shuttle control is here:
+ Ignores shuttle control but gets disabled by movement blocker: https://github.com/space-wizards/space-station-14/blob/master/Content.Client/Physics/Controllers/MoverController.cs
+ Contains the action blocker call which causes movement attempt events: https://github.com/space-wizards/space-station-14/blob/master/Content.Shared/Movement/SharedMoverController.cs
+ The actual server-side authoritative movement logic, including the priority-disable of kinematic movement: https://github.com/space-wizards/space-station-14/blob/master/Content.Server/Physics/Controllers/MoverController.cs
+ Shuttle movement blocker: https://github.com/space-wizards/space-station-14/blob/master/Content.Shared/Shuttles/SharedShuttleConsoleSystem.cs

**Comment by metalgearsloth** [comment]
Done in movement refactor.
