### ISSUE TITLE
Throwing looks weird

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#4344]
## Description

Not *sure* if this is a legitimate issue but the spinning when throwing looks unnatural as fuck.

**Screenshots**

![2021-07-22_22-57-44](https://user-images.githubusercontent.com/49448379/126742619-d0b31cab-5cab-4328-9ad3-9e0ae8149fdb.gif)
![2021-07-22_22-58-59](https://user-images.githubusercontent.com/49448379/126742696-19daf59d-714a-4925-a615-ec5a9d19d330.gif)

**Comment by PaulRitter** [comment]
appears to be rotating around 0,0, not the center

**Comment by PJB3005** [comment]
That's because sprites like the screwdriver aren't centered properly.

**Comment by SweptWasTaken** [comment]
Fixed by Sloth's changes and 0a1b79d.
