### ISSUE TITLE
Singularity Shader needs value tweaking

### ISSUE THREAD

**Issue by ghost** [space-wizards/space-station-14#4352]
In SingularityOverlay.cs, two values are passed into the shader: intensity and falloff. Intensity determines the intensity of the warping at the center of the singularity and falloff determines how the intensity lowers as distance increases from the center of the effect.
Currently the values for each level of singulo are ad-hoc values that are somewhat inconsistent between levels. These values simply need tweaking.
Personally I think it looks best when the effect ends shortly after the sprite itself.

**Comment by AJCM-git** [comment]
related to #2721
