### ISSUE TITLE
EntityWhitelist throws a false-positive warn whenever a component is used in ItemCounter whitelist

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#4353]
## Description

Example is in this commit build log - https://github.com/space-wizards/space-station-14/runs/3151796361

This happens whenever a component is used in ItemCounter's EntityWhitelist, regardless if it's valid or not.

**Screenshots**

![unknown](https://user-images.githubusercontent.com/49448379/126879479-13c6bc0c-3f1a-493d-b9d7-64fc358db12b.png)

**Comment by mirrorcult** [comment]
fixed in dcc9f02e55738b0584569bff5606162443b5a7f3
