### ISSUE TITLE
Dropping materials after building an anchored object causes the client to freeze.

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#4354]
![image](https://user-images.githubusercontent.com/7907891/126883929-336ef00f-1e3d-48cc-832d-c2d19551eb0b.png)

How to reproduce:

- Get a stack of steel, enough that you can build a single girder and still have at least one steel left.
- Go into the construction menu, and pick the "wall" option. Place the construction ghost.
- Use the steel on the ghost to make a girder.
- Drop the leftover steel stack.
- The client will freeze, with above error repeating infinitely.

**Comment by TimrodDX** [comment]
It looks like this actually happens with any crafted object that starts anchored. I've tested this with:

Wooden barricades and stacks of wood
Tables and stacks of metal rods
Machine frames and stacks of steel
Windows/reinforced windows and glass/reinforced glass.

All testing was done on a dev environment without moving the station.

![image](https://user-images.githubusercontent.com/7907891/126884185-d0d683a3-8838-4dc8-b2a4-178c205f03a5.png)

**Comment by ShadowCommander** [comment]
That's the container state apply error. It happens when a container contains an entity, but the entity does not exist on the client. I'm working on a partial fix right now that stops this error from happening. The not getting sent part still needs to be fixed, though it might just be late.

**Comment by TimrodDX** [comment]
I just tested this again after ShadowCommander's PR and it no longer occurs, appears this bug has been resolved.
