### ISSUE TITLE
Many vending machines don't have inventories

### ISSUE THREAD

**Issue by Moneyl** [space-wizards/space-station-14#436]
The following vending machines don't have inventories at this moment, they can be found [here](https://github.com/space-wizards/space-station-14/tree/master/Resources/Prototypes/VendingMachines):
- [x] Booze-O-Mat
- [ ] PTech
- [x] Piety Vend
- [ ] Cigarette Machine
- [x] Hot Drinks Machine
- [x] Robust Softdrinks
- [x] Dinnerware
- [x] Discount Dan's
- [ ] MagiVend
- [x] Dwarven Mining Equipment
- [ ] NutriMax
- [ ] Robotech Deluxe
- [ ] Sales
- [ ] SecTech
- [ ] MegaSeed Servitor
- [ ] Getmore Chocolate Corp
- [ ] KomradeVendtink
- [ ] BODA
- [ ] AutoDrobe
- [ ] Vendomat
- [ ] Trader Supply
- [ ] NanoMed

Some of these, like "Hot Drinks Machine" and "Robust Softdrinks" can have items added to them right now, while others need their items to be added to the game first.

**Comment by Moneyl** [comment]
The list above should now be up to date.

**Comment by ike709** [comment]
The list needs to be updated after #648 got merged

**Comment by Moneyl** [comment]
Thanks, updated.
