### ISSUE TITLE
Lockers dont stop bullets

### ISSUE THREAD

**Issue by PaulRitter** [space-wizards/space-station-14#4362]
![image](https://user-images.githubusercontent.com/16618384/126897456-42716122-a6df-4699-ad01-563fc18f4b89.png)
also happens when you shoot a locker on the outside

**Comment by mirrorcult** [comment]
probably has wrong layers/mask

**Comment by SweptWasTaken** [comment]
> 
> 
> probably has wrong layers/mask

Yep, gonna hotfix.

**Comment by Elijahrane** [comment]
This issue is now a bit worse since it affects so many steal objectives.

https://user-images.githubusercontent.com/60792108/148635216-551e9517-93fa-4408-82d1-5a38fafeffcc.mp4

**Comment by Peptide90** [comment]
Similar issue to thrown objects not hitting people. Not sure if shooting crates works either.

**Comment by metalgearsloth** [comment]
> Similar issue to thrown objects not hitting people. Not sure if shooting crates works either.

This has its own issue https://github.com/space-wizards/space-station-14/issues/3920

**Comment by Elijahrane** [comment]
Lockers need MobImpassible when they're closed and no MobImpassible when they're open to behave right vs bullets

**Comment by AJCM-git** [comment]
This is no longer the case.
