### ISSUE TITLE
Add portable flasher

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#4369]
Now that FlashOnTrigger exists this is much more doable.

Requirements:
* Need a ProximityTriggerComponent that has a non-hard circular fixture to represent the trigger.
* When collided with calls HandleTrigger on TriggerSystem and issues a TriggerEvent for the entity.
* ProximityTrigger probably also needs a cooldown.

**Comment by scaly-chimp** [comment]
shouldn't this be closed now?
