### ISSUE TITLE
You can relight burnt torches

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#4373]
## Description

Haven't tested yet, reported on Discord.

**Screenshots**

![unknown](https://user-images.githubusercontent.com/49448379/126947661-3bc72c34-f25a-4793-ae4f-9dcfeb4a1df0.png)

**Additional context**

**Comment by PaulRitter** [comment]
this is true

**Comment by PaulRitter** [comment]
fixed in 8357fcd7
