### ISSUE TITLE
Implement hardsuits properly

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#4378]
## Description

Currently hardsuits are two pieces, a helmet and a torso. They are functional in-game currently as they protect against depressurization through PressureProtection.cs.

However the hardsuit should be one piece. A torso that when donned puts a "helmet" icon in your hotbar that toggles the helmet of the suit on or off. When the helmet is toggled on, the suit should draw from an oxygen tank on the players belt, hand, back or "suit-slot". 

What should happen when a player dons a hardsuit:
1. A helmet hotbar icon appears that toggles the suits helmet on/off.
2. A suit-slot should appear as a separate slot on the users hotbar. This can be used for hooking stuff like tanks, tools and other gadgets.
3. When toggled off, the user should be able to eat, drink, and wear hats like normal. However, a worn hat will prevent the hardsuit helmet from closing when pressed.
4. When toggled on, the suit should draw from an oxygen tank on the players belt, hand, back or "suit-slot". It also should provide another hotbar icon for the flashlight on the hardsuit. The flashlight powercell will be swappable by screwdrivering the hardsuit and removing the cell.

I think that hardsuits should be a rarer find in SS14. I also think the order you put a hardsuit on should effect some stuff, like if you put the hardsuit on over your belt, your belt would be inaccessible, but if you put your hardsuit on and then your belt, you'd be able to access it.

**Comment by juliangiebel** [comment]
All of the mentioned points are implemented in some way so this can probably be closed now
