### ISSUE TITLE
SolutionContainerComponent should function like ContainerManagerComponent

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#4386]
Except in an ECS way. i.e.
* Support for multiple solutions on 1 entity
* Possible for components to reference solutions by name
* Possible to get all solutions on an entity.
* Other code shouldn't have to worry about the manager and should just worry about the solution itself.

**Comment by Ygg01** [comment]
To document things from the Discord:

In addition of `SolutionContainerManager`
There was an agreement to completely gut Capabilities and turn them into Systems/Components on their own.

So each Capability like for example `Injectable` -> `InjectableComponent`/`InjectableSystem`.
Vera also mentioned that relation between `SolutionContainer` and `SolutionContainerManager` should be the same as between  `SlotContainer` and `ContainerManagerComponent`
