### ISSUE TITLE
Throwing stuff in space does not change your momentum

### ISSUE THREAD

**Issue by SethLafuente** [space-wizards/space-station-14#4392]
## Description

when you throw stuff into space it either barely changes your direction or does not change your direction at all 
**Screenshots**

**Additional context**

**Comment by metalgearsloth** [comment]
Woops.
https://github.com/space-wizards/space-station-14/blob/c9c6bd685b345cda5a0664f9a3ad1b2cb038f199/Content.Server/Throwing/ThrowHelper.cs#L99 just needs the same multiplication https://github.com/space-wizards/space-station-14/blob/c9c6bd685b345cda5a0664f9a3ad1b2cb038f199/Content.Server/Throwing/ThrowHelper.cs#L72 has

**Comment by scaly-chimp** [comment]
shouldn't this be closed?
