### ISSUE TITLE
Gravity generator is thrown when unanchored.

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#4402]
![image](https://user-images.githubusercontent.com/7907891/127750308-b07c0d22-817e-4530-9cb7-d68deabd9a76.png)

This was originally reported by Swept, but I wanted to verify it and put up a report here. 

How to reproduce:

- Unanchor the gravity generator.
- The gravity generator will begin moving in the opposite direction that you unanchored it from (in the above screenshot, I unanchored it from the east)
- While moving, it will ignore most walls, though it seems to respect the northern and southern walls of the chamber it's in.
- It is possible to put the gravity generator into space this way.

![image](https://user-images.githubusercontent.com/7907891/127750370-1dfbd760-ef5a-4429-a5cc-0e9dd3d366a2.png)

This was done on a local client without moving the station.

EDIT: Should mention that it does not appear the gravity generator has collision when pulled, which may be part of why it ignores certain walls when moving.

**Comment by metalgearsloth** [comment]
Fixed in https://github.com/space-wizards/space-station-14/commit/34defef80f51fa96366fa8567ac70bbec1b57524
