### ISSUE TITLE
Cutting a power cable noticeably hangs server.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/space-station-14#441]
This is probably because powernet generation uses `GetEntitiesInRange` instead of snap grid.

**Comment by Tyler-IN** [comment]
I'll take a shot

**Comment by Zumorica** [comment]
What's the state of this issue after #596?

**Comment by TYoung86** [comment]
Querying the entity list was unavoidable for power nodes.

Now it's a fast tree. More power components are snap grid based now.

Wire selection is now based on snap grids and is fast.

_afaik it's all done_

**Comment by Zumorica** [comment]
Good, then we can close this one
