### ISSUE TITLE
Pickup animation is broken

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#4427]
## Description

So basically I was picking up and throwing this popcorn bag and noticed a weird flicker of popcorn bag in my cornea. I recorded and did a frame by frame analysis of the popcorn bag and discovered that a single frame *after* picking up the bag it appears as if teleporting from the bottom right of my screen.

Then I used my brain and realized that offsetting the station broke @RemieRichards's pickup animation.

**Screenshots**

**Frame before picking up**
![vlc_2021-08-06_08-53-29](https://user-images.githubusercontent.com/49448379/128538642-527a4ddb-77bd-4ac7-9638-6d10ef948cab.png)
**Next Frame**
![vlc_2021-08-06_08-53-53](https://user-images.githubusercontent.com/49448379/128538810-6a89b02f-19c3-4db5-a2fc-ddd91aa91ca0.png)
**Next Frame**
![vlc_2021-08-06_08-54-03](https://user-images.githubusercontent.com/49448379/128538828-80da5dd6-75a9-4c58-8ebc-8908d1d5e594.png)

**Additional context**

I know what the bug is but I compiled this report nicely so I included that shit anyway.

**Comment by metalgearsloth** [comment]
I already put it on shuttle issues m8

**Comment by Zumorica** [comment]
Fixed by 41ddf3d7ebfc24f283e5aa3c92f10a26b4faaff1
