### ISSUE TITLE
Firelock frames make it hard to interact with windoors

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#4430]
## Description

Just a nag I had while mapping them.

**Screenshots**

![2021-08-06_10-04-36](https://user-images.githubusercontent.com/49448379/128546862-fc187b4b-7350-4dee-8664-f48b5f31e50b.gif)

**Comment by mirrorcult** [comment]
imo windoors should render above firelocks, could just give them a different drawdepth

**Comment by Zumorica** [comment]
This is tricky because firelocks are on a drawdepth *above mobs* so perspective is fine, but windoors should be on a drawdepth *below mobs*. In short, pain

**Comment by PaulRitter** [comment]
aren't there small firelocks which adress this issue? iirc at least vg has them

**Comment by Zumorica** [comment]
> aren't there small firelocks which adress this issue? iirc at least vg has them

Yes, we have these already.

**Comment by PaulRitter** [comment]
> > aren't there small firelocks which adress this issue? iirc at least vg has them
> 
> Yes, we have these already.

solved? :D

**Comment by Zumorica** [comment]
> solved? :D

Not really, they're still a hard to interact with even with those.
