### ISSUE TITLE
You can place things on a table and pick things up through a windoor

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#4431]
## Description

To replicate just do a basic windoor setup as seen in the gifs. You cannot drop things through the windoor. You can however place things on tables and pick things up through them.

**Screenshots**

![2021-08-06_10-07-45](https://user-images.githubusercontent.com/49448379/128547093-af89b3f5-52fe-4c1b-a912-c4fb26b6c888.gif)

![2021-08-06_10-11-38](https://user-images.githubusercontent.com/49448379/128547556-224da431-1c7e-4be8-b62f-154117d33eaf.gif)

**Comment by PaulRitter** [comment]
>windoor literally not doing the one thing its good for

what gives

**Comment by metalgearsloth** [comment]
Unless it's been changed clicking on a table is an entirely separate interaction to a drop which probably isn't raycasting.

**Comment by AJCM-git** [comment]
This is no longer the case
