### ISSUE TITLE
You can hear A lot of sounds across the station 

### ISSUE THREAD

**Issue by SethLafuente** [space-wizards/space-station-14#4437]
## Description

You can hear every single door on the station open reject to open or close all around the station you can also hear people reload  
and other stuff it makes everyone go somewhat insane 

Also maybe unrelated but you can hear emitters from far to far away when they are on space

**Screenshots**

**Additional context**

Not just me I have asked everyone can hear it

**Comment by metalgearsloth** [comment]
Audio occlusion mask is 0 for whatever reason hence nothing collides with it.

Also an engine issue but whatever.

**Comment by ShadowCommander** [comment]
The `SoundSystem.Play` calls don't specify an entity or coordinate, so they play at full volume for the area that they are heard instead of based on distance. Just needs either specified and it'll be fixed. Waiting for #4401 before fixing it.

**Comment by ShadowCommander** [comment]
Fixed by #4453
