### ISSUE TITLE
Items without sprites won't show an error in the console

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#4457]
## Description

Don't know if this is an issue with just BaseItem but for example in [this file](https://github.com/space-wizards/space-station-14/blob/10baebae7988aeebbc60ca0b4bd60f5d31c33ed4/Resources/Prototypes/Entities/Objects/Fun/toys.yml#L5) BasePlushie was not abstracted (not intentional). However in-game this would not throw an error in the console even when placed.

**Screenshots**

![Content Client_2021-08-11_14-08-09](https://user-images.githubusercontent.com/49448379/129104497-02fe7e47-83b7-4ab7-82c7-c9c601a81e7b.png)

**Comment by PaulRitter** [comment]
iirc this is since i removed the error log calls in afterdeserialize since it would run before pushing inheritance.

should be easily fixable by just adding those calls back to the afterdeserialize of spritecomponent
