### ISSUE TITLE
When there's only one of something in a storage inventory like a backpack do not display a number in the UI

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#4463]
## Description

Thought I had with the recent StorageComponent changes. 

Additionally it'd be nice if there was some padding on the storage UI count like this.

![11121](https://user-images.githubusercontent.com/49448379/129261555-de4ff894-a7a9-4188-802f-cf5c46639322.png)

**Comment by mirrorcult** [comment]
the number is the weight, why would it not show up just because there's one thing

**Comment by ShadowCommander** [comment]
![image](https://user-images.githubusercontent.com/10494922/129278238-57c9356d-1366-40ba-904c-5acc780f39dc.png)

If you mean the yellow part, that's the size of the item, not the count of how many items there are. If you mean the red part, I don't really think it's worth it to code a hiding thing for when there's only one item.

For padding, where do you want more padding?

**Comment by SweptWasTaken** [comment]
Sorry, I meant the weight of the item on the right side of each item entry.

**Comment by ShadowCommander** [comment]
It's kinda hard to hide just the number on the side of the button. It can be done, but why though?

**Comment by Visne** [comment]
In my opinion displaying the weight like this is very ugly anyways. It makes it look like you have that amount of that item in the bag.

**Comment by mirrorcult** [comment]
doesnt seem be to desirable behavior
