### ISSUE TITLE
Bullets knock and the door opens

### ISSUE THREAD

**Issue by ShadowCommander** [space-wizards/space-station-14#4468]
Bullets can open doors. Something's up with the collision flags, since bullets count for opening Airlocks and Windoors.

**Comment by TimrodDX** [comment]
It's not just bullets. Any random item placed near a door will attempt to open it.

**Comment by metalgearsloth** [comment]
> 
> 
> It's not just bullets. Any random item placed near a door will attempt to open it.

That's intended

**Comment by PaulRitter** [comment]
I dunno i kinda dig airlocks opening by being shot at. Its funny.

Lorewise it also kinda makes sense. If you throw items at a door it opens, so having bullets have the same effect kinda makes sense imo

**Comment by scaly-chimp** [comment]
ID bullets whence?

**Comment by PaulRitter** [comment]
this man gets it

**Comment by Zumorica** [comment]
Fixed by 883cbf40b2ff76b14b216890fdd9bf6d39c05148
