### ISSUE TITLE
Being inside a locker or crate does not stop you from constructing things

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#4473]
![image](https://user-images.githubusercontent.com/7907891/129465556-c3239f94-f2e0-4fb2-a3f6-29741bd68036.png)

This issue was originally reported by Raven#1990 on the Discord. I have replicated it locally.

How to reproduce:

- Have a stack of steel or wood in hand or in a backpack.
- Go into a locker or crate.
- Open the construction menu. Place the construction ghost directly outside the locker.
- Click the construction ghost with the corresponding material. The construction will finish as if you were not in the locker.

![image](https://user-images.githubusercontent.com/7907891/129465606-01154795-f351-4bc0-b353-7db8be8f76c0.png)

It appears that the radius where you can do this is within one tile of the locker or crate.

![image](https://user-images.githubusercontent.com/7907891/129465723-53b161bf-2582-4be5-8ed7-07cf21739b6a.png)

The livestock crate may need to be addressed separately, as it is instead dropped outside the container and can be used to push yourself into (or through) a wall.

![image](https://user-images.githubusercontent.com/7907891/129465761-94bdd7dd-98c6-4bb9-890a-7e0dd6143de9.png)

![image](https://user-images.githubusercontent.com/7907891/129465788-2fc55383-8d8c-4df2-8809-5b0a1b911c80.png)

![image](https://user-images.githubusercontent.com/7907891/129465819-05a85c59-4ccc-44da-bd01-ead32e32d565.png)

![image](https://user-images.githubusercontent.com/7907891/129465845-a7e1ee4b-4fe1-4028-a1e6-2ec568808f36.png)

**Comment by mirrorcult** [comment]
construction should check actionblocker before allowing ghost placement or construction interactions

**Comment by mirrorcult** [comment]
if it does already then entitystorage needs to disable interactions
