### ISSUE TITLE
Removing an item from a backpack while in a locker or crate causes the container to move.

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#4474]
![image](https://user-images.githubusercontent.com/7907891/129465928-6d495574-39ae-415b-aff4-4adccb4436ec.png)

![image](https://user-images.githubusercontent.com/7907891/129465940-e9ff86aa-90b5-4f7d-a969-157937a4e1ea.png)

![image](https://user-images.githubusercontent.com/7907891/129465960-5bc7b518-2d38-47ec-9ff8-12fe4240f7e8.png)

It appears that the locker will always move west, and moves proportionally to how much mass the object you're taking out has. It will also move more the first time you take an object out while inside of it.

![image](https://user-images.githubusercontent.com/7907891/129466032-8beeb1be-c7cf-4c4d-9dd0-22ac35ffe6a2.png)

As an example, this locker was as far as it could go against the wall, and moved about half a tile when I took an AKMS out of a backpack once I got inside.

**Comment by ShadowCommander** [comment]
Can't replicate this. Is it still a problem on your end?

Throwing things while inside the locker does move it though.

**Comment by TimrodDX** [comment]
> 
> 
> Can't replicate this. Is it still a problem on your end?
> 
> Throwing things while inside the locker does move it though.

Yeah, I think it may have been incidentally patched out by something else. I just updated my dev environment (note that the last time I updated it was yesterday) and it's no longer happening. As you mentioned, throwing still moves it though.
