### ISSUE TITLE
Virtual Pulls show up in hands when being pulled.

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#4477]
![image](https://user-images.githubusercontent.com/7907891/129642012-04e956d9-f819-442c-8fe7-bd5722fb4721.png)

How to reproduce:

- Get pulled by someone.
- A virtual pull will show up in your hand.
- Looking at yourself will give the description pictured above.

**Comment by Zumorica** [comment]
Fixed by 36514f4bbd154b0d8fac8dfee2dbd95cc3d64b92
