### ISSUE TITLE
Need a test to validate PhysShapeAabb bounds

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#4490]
Currently WindoorAssembly has invalid bounds and this wasn't picked up.

**Comment by mirrorcult** [comment]
what does this even mean, how do you determine what the "correct" bounds are

**Comment by PaulRitter** [comment]
what mirror said, what *are* invalid bounds?

**Comment by metalgearsloth** [comment]
left should always be less than or equal to right, and bottom should always be less than or equal to top.

**Comment by PaulRitter** [comment]
fair nuff. seems like an easy test
