### ISSUE TITLE
RSIDiffBot

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#4491]
## Description

It would be nice to have an action/bot for PRs that displays diffs/additions in RSIs like [tgstation's IconDiffBot](https://github.com/tgstation/IconDiffBot).

[Example of IconDiffBot running on a PR](https://github.com/tgstation/tgstation/pull/60522/checks?check_run_id=3317692342).

**Screenshots**

![image](https://user-images.githubusercontent.com/49448379/130003418-1a20d2d2-25f7-4bc3-93f9-3f3ae5b191f8.png)

**Comment by mirrorcult** [comment]
will work on this when i'm done moving
