### ISSUE TITLE
Improve status effects

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#450]
Using injazz's design:
![image](https://user-images.githubusercontent.com/31366439/69242658-6eadd300-0bf5-11ea-987d-4329f868c833.png)

- [ ] Add tooltips
- [ ] Add a background to the effects box
- [ ] Add a toggle for whether something should be clickable (and also what the sprite looks like if clicked). This may eventually be superseded by the actionbar.
- [ ] Potentially update sprites (at least the effects themselves and not necessarily the background) to eris style https://github.com/discordia-space/CEV-Eris/tree/master/icons/mob/screen

**Comment by PJB3005** [comment]
As for clickables, the general design we've been shooting for is that "fixable" alerts should be clickable. This basically would serve as a replacement for resisting in SS13. You'd click the restrained item to resist or click the "you're on fire!" icon to stop drop & roll.

**Comment by metalgearsloth** [comment]
Implemented in https://github.com/space-wizards/space-station-14/pull/2529
