### ISSUE TITLE
Protolathe freezes if items are added to the queue too quickly.

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#4518]
This bug was originally reported by Raven#1990 on Discord. I reproduced it in a local environment.

How to reproduce:

- Fill the protolathe with enough materials to make more than one of a given item. I was able to make this happen with around half a stack of steel.

- Rapidly click on an item. 

- The protolathe will continue queuing the item you're mashing clicks on until you stop clicking, and will then break. The sprite will go into its "off" state and while it will continue to add the items into the queue, it won't print anything else out. 

You can fix the problem by unscrewing the protolathe and crowbarring it back into a machine frame, but this will eat all the materials that were in the lathe.

Ideally, the protolathe should probably subtract the materials when the button is clicked, and deny the ability to queue more items than it physically has resources for. Alternatively, put a cooldown on how fast items can be added to the queue and how long the queue can be.

**Screenshots**

![image](https://user-images.githubusercontent.com/7907891/130530555-e271ba5b-1bba-43f6-b224-11c824b82a11.png)

![image](https://user-images.githubusercontent.com/7907891/130530797-5b8d8ebe-ce67-484b-b07c-77bad27cf5c7.png)

![image](https://user-images.githubusercontent.com/7907891/130530866-eb99d427-00f7-4c8a-9aab-d3a0b262a5e8.png)

![image](https://user-images.githubusercontent.com/7907891/130531074-82cb3e1e-3d2a-4c7f-8abd-56c86645e67b.png)

![image](https://user-images.githubusercontent.com/7907891/130531436-13845da5-87c6-4348-b8b2-864feb0368b3.png)

**Comment by PaulRitter** [comment]
I dig story-bugreports.

Queuing items you dont have resources for is fine, the freezing shouldn't happen though

**Comment by 20kdc** [comment]
Current state of the Lathe is that even clicking it just twice or so (without running out of materials) will freeze it.
Notably, this does not happen if the `TimerComponent.RemoveOnEmpty` default is false, suggesting the timer that completes the recipe is lost.

**Comment by 20kdc** [comment]
Aaaand I worked out why *that* is.
EntityManager defers deletion and removal of the `TimerComponent` - so the result is, it can't be re-added because it still exists, but any timer that gets added there will be lost.
The Lathe then starts the next production on the same tick as it finishes the previous production.
