### ISSUE TITLE
Throwing items while in a locker causes the locker to move.

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#4526]
This was originally reported by ShadowCommander in a different report for a bug that has (apparently) been resolved. 

How to reproduce:

- Acquire a lot of small objects, as this is the easiest way to see this bug in action.
- Get into a locker.
- Start throwing objects. The locker will begin moving to the right, regardless of which direction you throw.

**Screenshots**

![image](https://user-images.githubusercontent.com/7907891/130721575-58e8c334-884a-478e-b5c9-86b6cc65c91d.png)
![image](https://user-images.githubusercontent.com/7907891/130721689-feb1ed97-54e7-4a1a-becb-a9f53f40fb2a.png)
![image](https://user-images.githubusercontent.com/7907891/130721721-30d11690-cc3a-481e-8cb3-1b70d2bade87.png)
![image](https://user-images.githubusercontent.com/7907891/130721769-918c9815-2130-4503-8e49-f1c66ca04ee0.png)
![image](https://user-images.githubusercontent.com/7907891/130721814-cadadec4-5124-433a-8a00-4aa199a90297.png)

**Comment by metalgearsloth** [comment]
Throwing in lockers disallowed now.
