### ISSUE TITLE
Singularity radiation is extremely long-range and extremely lethal.

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#4527]
This issue was originally reported by Martintrojan#0249 on Discord. I have verified it on a local test environment. 

How to reproduce:

- Set up the singularity engine.
- Turn the PA on to achieve singularity.
- Almost as soon as the singularity spawns, it will instantly kill anyone in the PA room, even if they're at a range that did not previously cause radiation damage. 

The range seems to be almost exactly where the PA room door is at level 3 - the second you walk in you will die instantly. This makes it impossible to maintain a singularity.

![image](https://user-images.githubusercontent.com/7907891/130722851-87424c6b-0d21-4035-9826-d01010eec5ee.png)
![image](https://user-images.githubusercontent.com/7907891/130722924-a6448d81-7f8a-422f-8843-0c26e10d5779.png)

**Comment by mirrorcult** [comment]
please for the love of god radiation needs to be refactored

**Comment by AJCM-git** [comment]
related to #3504

**Comment by ElectroJr** [comment]
#6045 should nerf damage. Range is still large though. Should that also scale with the singularity level? What's the minimum distance required to ensure that the radiation reaches the collectors?

**Comment by Pangogie** [comment]
> #6045 should nerf damage. Range is still large though. Should that also scale with the singularity level? What's the minimum distance required to ensure that the radiation reaches the collectors?

6 - 9 I believe.

**Comment by dmnct** [comment]
Radiation is now blocked by walls. A stage 3 singularity generated approximately 4 rads/s when measured right behind the PA room window. Crits an unprotected crewmember in 25 seconds. Seems fine
