### ISSUE TITLE
ClientStorageComponent has a window per component

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#4543]
This isn't so bad on its own but it's the fact each window is active on every component which is then disposed when it's deleted is very suss.

**Comment by ShadowCommander** [comment]
This is one of those more involved than it looks issues, if you want to do it right. Right now the functionality is that the player can have multiple inventory windows that can be repositioned and resized. If the player closes and reopens the UI it'll go right back to the previous position and size.

So if this is redone to create the window when opened and dispose when close at least those two things should to be tracked.

**Comment by mirrorcult** [comment]
not relevant now
