### ISSUE TITLE
Fix Reagent verbs

### ISSUE THREAD

**Issue by Ygg01** [space-wizards/space-station-14#4547]
## Description
Updates to Solution Container logic, means there isn't a single solution always to add or remove. This will break a bunch of Verbs that depended on there being an existing solution to tinker with. E.g. `AdminAddReagentVerb`

**Comment by ElectroJr** [comment]
I'm currently working towards ECSing verbs. Assuming the solution refactor is merged before that is done I guess I can try address this. For now I just won't bother ecsing that admin verb or the SetTransferAmount verb.

**Comment by Ygg01** [comment]
@ElectroJr Very nice, ECSing is good. However, the issue here is verbs need to be able to choose which solution to insert reagent into. 

Before you could have only one one solution to insert into. Now you can have any number. I think the Verbs need to be able to pick solution and then add to that solution.

**Comment by Zumorica** [comment]
> However, the issue here is verbs need to be able to choose which solution to insert reagent into.

In my opinion this should be handled by certain components like we talked once, "Refillable", "Injectable" and so on.
Those would specify a solution, and their verbs would always use that specific solution

**Comment by ElectroJr** [comment]
> Before you could have only one one solution to insert into. Now you can have any number. I think the Verbs need to be able to pick solution and then add to that solution.

The way I'm setting it up already supports displaying arbitrary numbers of verbs. Ideally whatever system sets up the add-reagent verbs would have access to something like a solution name or something, and then it shouldn't be too hard to support multiple solutions. For example: unbuckling multiple objects buckled to an office chair looks like this:
![mutliple](https://user-images.githubusercontent.com/60421075/131546328-9993c7f5-fa14-4e3d-ae71-faa014156101.png)
 and the verbs can still contract down when there is only a single target, like so:
![Single target](https://user-images.githubusercontent.com/60421075/131546318-cde61155-bbd2-45d3-b835-14b9f05e06f3.png)

**Comment by Ygg01** [comment]
Will probably be closed by #4954
