### ISSUE TITLE
Need a decent way to do audio attribution

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#4564]
Textures have the .rsi format with licence and copyright but there's not really a consistent way to do it for audio so often it's not done which is bad.

This might be more of a content issue.

**Comment by SweptWasTaken** [comment]
Transferred this issue from RobustToolbox since it's definitely more relevant on the content side of things.

**Comment by AJCM-git** [comment]
Reminder to close this once https://github.com/space-wizards/RobustToolboxSpecifications/tree/master/RobustGenericAttribution is implemented

**Comment by EmoGarbage404** [comment]
we have been reminded.
