### ISSUE TITLE
Context menu entries have rotation applied

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#4565]
They really shouldn't

**Comment by mirrorcult** [comment]
..screenshot?

**Comment by metalgearsloth** [comment]
![image](https://user-images.githubusercontent.com/31366439/132157744-cb0a3ae3-e080-4197-90ba-596a02a37a9c.png)

secret grid rotation technology

**Comment by mirrorcult** [comment]
😳

**Comment by AJCM-git** [comment]
It is indeed fixed
