### ISSUE TITLE
Add more ambient sounds

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#4574]
Off the top of my head stuff that could use it:
* SMES
* Generators (when active)
* Singulo (though I think it has its own sound already so just needs converting)
* Arcade machines
* ReagentDispensers
* Computers (in command)
* Potentially stuff like stun batons when on

Just ping me if you need help making it sound nice when looping

**Comment by SweptWasTaken** [comment]
I'm taking care of this one.
