### ISSUE TITLE
Linter should verify SoundCollection paths

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#4580]
https://github.com/space-wizards/space-station-14/pull/4576 had a typo in a soundcollection path and linter didn't pick it up

**Comment by PaulRitter** [comment]
this will need functionalities to be added to its serializer: https://github.com/space-wizards/space-station-14/blob/master/Content.Shared/Sound/SoundSpecifierTypeSerializer.cs#L36-L45

**Comment by Zumorica** [comment]
I'm gonna assume by `SoundCollection` you actually mean `SoundSpecifier`.
How is this even possible? When I specifically typo some path or collection ID locally, the linter detects the error correctly

**Comment by metalgearsloth** [comment]
No I mean SoundCollection. Here's the PR that led to me making it
https://github.com/space-wizards/space-station-14/pull/4576

Swept typod a path in the collection but still passed CI.

**Comment by Zumorica** [comment]
Ah, so Paul confused it with `SoundSpecifier` I guess?

**Comment by PaulRitter** [comment]
i honestly have no clue what i was thinking, i cant find what i was looking at before. kinda all over the place rn, sorry.

just make this datafield a `list<resourcepath>`, right?
https://github.com/space-wizards/space-station-14/blob/master/Content.Shared/Audio/SoundCollectionPrototype.cs#L15
