### ISSUE TITLE
Drinks exploding on landing is broken

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#4583]
SolutionContainerManager issue on TryGetDrainable @Ygg01

**Comment by ElectroJr** [comment]
So after the solution refactor tomatoes & eggs no longer leave puddles behind when destroyed after throwing. Not sure if it is directly related to this throw-able solutions issue (AFAIK they don't have solutions, they just spawn puddles directly on destruction). But if it is related, then the associated PR doesn't yet appear to have fixed this.
