### ISSUE TITLE
ViewVariables as is does not work with ECS

### ISSUE THREAD

**Issue by PaulRitter** [space-wizards/space-station-14#4587]
How should we design the new vv system?

Discuss.

**Comment by Ygg01** [comment]
The view part of VV is working, the problem is changing the properties. 

Changing stuff outside of EntitySystem in ECS is always going to be awkward.

**Comment by Ygg01** [comment]
@Zumorica you had some ideas regarding this, right?

**Comment by Zumorica** [comment]
Duplicate of https://github.com/space-wizards/RobustToolbox/issues/1772, this is not the repo for this
