### ISSUE TITLE
Ambience system

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#4589]
## Description

A system that would play ambience in certain areas, either randomly or set.

Not really sure how to do this yet without a marker for a place - such as ambience that can only be heard in maintenance, space etc.

SS13 does it by tile type I seem to remember.

In SS14 I think this would be achieved by having a SoundCollection of certain ambiences then randomly playing them when you're over a certain tile. So for regular steel tiles it would play a spacestation ambience, techmaint tiles would be - blah blah. Pretty certain this would be a client-side only system.

Additionally if we do it by tiles I think having a short waiting period before quickly cutting off the playing ambience when you step onto a different tile, so for example if you're just popping out of maint and back in the currently playing ambience would still play but if you come out of maint into the station proper it would stop.

## Additional Context

This system likely could also be used to play small clips of ambient music but I wouldn't want peaceful ambient music playing while you were in a gun-fight the like so that would probably be a more complex system.

**Comment by SweptWasTaken** [comment]
Examples of ambience sound effects. 

[Ambience.zip](https://github.com/space-wizards/space-station-14/files/7146157/Ambience.zip)

**Comment by mirrorcult** [comment]
![image](https://user-images.githubusercontent.com/19853115/132911951-f3efafbf-555e-4b9a-93f2-fb3604928fa7.png)

**Comment by SweptWasTaken** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/19853115/132911951-f3efafbf-555e-4b9a-93f2-fb3604928fa7.png)

I don't like the *certainty* of playing music when a number of tiles are in an area - at least not as the main function for the system. I do like the idea of going into a place with a bunch of church tiles and hearing soft music or something.

At the same time I kinda thought it'd be nice to have that be a player made thing like a speaker system hooked up in the church but /shrug.
