### ISSUE TITLE
Context menu should "stack" similar items

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#4596]
## Description

Even with the scrollbar I think this is not good.

![](https://user-images.githubusercontent.com/60421075/132991007-1bc416b2-0ade-45d0-8e90-2abc2cfd31b3.png)

Similar items like this should be use the same "stacking" thing that stacks use in the context menu.

![image](https://user-images.githubusercontent.com/49448379/132997681-cac15891-8be1-4518-b93a-937dea3e45fc.png)

Although personally I find this feature inconsistent as well, as demonstrated in this gif.

![2021-09-12_10-47-00](https://user-images.githubusercontent.com/49448379/132997690-fe344666-ee6d-4b7f-a2ff-91b330eb64ef.gif)

**Comment by ElectroJr** [comment]
The current behaviour is that it just automatically expands the collection/grouping when there would only be a single menu entry. ​I agree that it's inconsistent/jarring when it switches from showing a large menu of 10 identical entities to showing just 2 (single entity + group of entities).

I think the rationale was just that if you wanted to actually use the menu, you'd have to hover over the group anyways and it would automatically expand, so you might as well actually save space and show only the expanded group. But it does mean that if you just want to use the menu to examine a pile and see what types of entities are on the pile, without actually using the menu, then the menu takes up way more space than it needs to.

Would the preferred behaviour be to just not auto-expand lone groups?

**Comment by mirrorcult** [comment]
i think swept was just misunderstanding the behavior here, it's fine as it is imo

**Comment by AJCM-git** [comment]
This has been fixed for a while
