### ISSUE TITLE
Y-sorting or Masks for some walls and entities

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#4597]
## Description

Due to how the player's BB is setup when walking southward into something your sprite will always float menacingly above it like so

![Content Client_2021-09-12_11-22-34](https://user-images.githubusercontent.com/49448379/132998736-faf45f8e-c669-44b3-bfba-7bca354fd529.png)
![Content Client_2021-09-12_11-22-42](https://user-images.githubusercontent.com/49448379/132998738-8f3e9f7a-963a-4aea-aea4-68acaefc6630.png)
![Content Client_2021-09-12_11-22-48](https://user-images.githubusercontent.com/49448379/132998740-2769d074-2ae7-43fe-9fa2-e2e5a3e1a251.png)

With bb

![Content Client_2021-09-12_11-26-53](https://user-images.githubusercontent.com/49448379/132998749-44144169-89af-4f8f-818d-94585cdae88b.png)

Not sure what the correct way to fix this is but with y-sorting in general fixed it shouldn't be too hard.

**Additional context**

Also this might be impossible but being able to move up against walls on the x-axis would be nice.

![Content Client_2021-09-12_11-28-44](https://user-images.githubusercontent.com/49448379/132998775-c7ec9ec5-16fa-416e-bd6c-af474198b2e7.png)

**Comment by SweptWasTaken** [comment]
With y-sorting fixed by @metalgearsloth this issue can be resolved by setting the drawdepth on the SpriteComponent of these entities to "Mobs".

![2021-09-12_13-33-14](https://user-images.githubusercontent.com/49448379/133002037-009f71d1-16b0-4569-aa57-c54aefdc8574.gif)

This of course fucks up other stuff.

![Content Client_2021-09-12_13-34-00](https://user-images.githubusercontent.com/49448379/133002084-cd3bdb8b-348e-4869-bb7a-ddca35405141.png)

Objects/Items need to display above tables, disposal units etc. but can't display above mobs.

**Comment by metalgearsloth** [comment]
Kinda hard to resolve because you need FloorItems > Mobs > Items y-sorting but also need to put the mob up 1 layer when vaulting.

Only way to "fix" moving up to walls is make the BB smaller because it needs to be a circle for grid rotation.
