### ISSUE TITLE
Anchored entities show up double in the context menu

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#4598]
## Description

![Content Client_2021-09-12_11-27-19](https://user-images.githubusercontent.com/49448379/132998833-8e492e2c-323b-4843-805b-4534a82199d4.png)
![2021-09-12_11-17-45](https://user-images.githubusercontent.com/49448379/132998835-1fb72c1e-309a-4994-8693-cc8b59e33295.gif)

**Comment by SweptWasTaken** [comment]
This doesn't happen with entities anchored on spawn, you need to manually unanchor something and reanchor it to replicate it.

**Comment by metalgearsloth** [comment]
Engine issue, anchored events aren't being raised as broadcast so lookups are fucked.

@Zumorica is there a need that these are directed-only or can we make it broadcast again?

**Comment by Zumorica** [comment]
> @Zumorica is there a need that these are directed-only or can we make it broadcast again?

You can make 'em broadcast without problem, I think

**Comment by metalgearsloth** [comment]
Fixed in https://github.com/space-wizards/RobustToolbox/commit/42a137d106bdd27d5c91a03702f2b0c7c782ebee
