### ISSUE TITLE
Cock and balls poke through clothing

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#4600]
## Description

Part of a larger issue but still funny. My first reaction would be to hide the body sprite underneath when covered by clothing but then stuff like shorts, tshirts and other stuff would be broken.

In Fig. 2 the bit sticking out from the female is the hand I believe but i'm thinking it should be hidden on both sprites. Maybe it could only show when someone actually has an inhand sprite for something?

**Screenshots**

![Content Client_2021-09-12_12-17-36](https://user-images.githubusercontent.com/49448379/133000057-540bd23c-c72c-4cf3-98c0-93e31a184a09.png)
![Content Client_2021-09-12_12-19-52](https://user-images.githubusercontent.com/49448379/133000061-123853cb-c1c4-45c4-b0f5-60235b9ae7b1.png)

**Comment by Visne** [comment]
good first issue

**Comment by mirrorcult** [comment]
good first issue

**Comment by PaulRitter** [comment]
had me do a double take

**Comment by theOperand** [comment]
return of the dixel

**Comment by EmoGarbage404** [comment]
no more dixel
