### ISSUE TITLE
Extend functionality of ItemCooldown to more components

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#4603]
## Description

I was trying to fix #3732 by adding ItemCooldown to guns.

Currently ItemCooldown is tied to MeleeWeapon functions. Putting ItemCooldown on something that isn't a melee weapon does nothing. Additionally you can put MeleeWeapon and ItemCooldown on something like a gun and it will look like it's functional but it will not stop you from interacting with the gun (reloading, firing etc.).

ItemCooldown should be untied from MeleeWeapon and be refactored to mean general interaction with an entity.

**Comment by mirrorcult** [comment]
its not 'tied to melee weapon', melee weapon is just the only thing that refreshes the cooldown right now

**Comment by mirrorcult** [comment]
https://github.com/space-wizards/space-station-14/blob/ff1a2d97ea214de6d393da1b86fc6109cb528a07/Content.Server/Cooldown/ItemCooldownSystem.cs#L13

right now meleeweaponsystem is the only thing that raises this event. if you want guns to work then have it raise this event too

if you want it to specifically always refresh on hand switch (like what melee weps does) then change https://github.com/space-wizards/space-station-14/blob/c209e3f29b6560b65776bc1103e0b1a8c87307fb/Content.Server/Weapon/Melee/MeleeWeaponSystem.cs#L34 to direct to something else, or copy the call for guns and stuff too
