### ISSUE TITLE
Fire extinguishers no longer have foam in them

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#4613]
## Description
I ate all the fucking firefighting foam. Fuck

**Screenshots**
![image](https://user-images.githubusercontent.com/19853115/133138045-8c65e798-8c58-4bae-b31d-9fae45b0f84c.png)

**Additional context**

**Comment by Cintra2** [comment]
what did i say son?

STOP EATING THE DAMM FIRE FOAM ITS GONNA GET YOU KILLED

**Comment by metalgearsloth** [comment]
@Ygg01
