### ISSUE TITLE
Welder Fuel Tanks don't work properly.

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#4630]
This was originally reported by hubismal#5912 on Discord. I have reproduced it on local.

How to reproduce:

- Have a welder.
- Attempt to refuel the welder from a tank. Nothing will happen, and you won't get the "You refuel the welding tool" message.
- The tank will still explode if touched with a lit welder.
- Interestingly, empty welder fuel tanks will still give you the "You refuel the welding tool" message.
- 
![image](https://user-images.githubusercontent.com/7907891/133862278-14918c71-75b2-49fc-a77c-4de581d55f6b.png)

- On a side note, there's now two entries for "Fuel Tank [Empty]" in the spawn menu.

![image](https://user-images.githubusercontent.com/7907891/133862315-e738bfc0-a3a0-4d96-8297-e8b25aac2660.png)

![image](https://user-images.githubusercontent.com/7907891/133862124-25f56ed7-cf25-4c1f-b678-9e85a4f1f227.png)

![image](https://user-images.githubusercontent.com/7907891/133862090-00de2587-587b-4f21-9aaf-708fca78ea8a.png)

![image](https://user-images.githubusercontent.com/7907891/133862398-ae4ed467-d296-4df8-a370-b3fd70a6c712.png)

![image](https://user-images.githubusercontent.com/7907891/133862444-72d2c6fe-c0d8-4a20-8e6f-45cb0fc795c2.png)

![image](https://user-images.githubusercontent.com/7907891/133862456-f961ef12-fe4b-48df-a991-ae19fe42e577.png)

**Comment by mirrorcult** [comment]
issue with new solution re factor, most likely
