### ISSUE TITLE
Throwing stuff into disposals is hard now

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#4654]
## Description

Dk if it was just me but chucking stuff into the disposals is hard as fuck now.

**Screenshots**

![2021-09-19_09-45-28](https://user-images.githubusercontent.com/49448379/133935727-b229a503-8019-48ac-8381-15e6f628bf2f.gif)

**Comment by metalgearsloth** [comment]
@mirrorcult maybe landing when timer is out is a bad idea.
