### ISSUE TITLE
Singularity effect breaks tabletop games when nearby

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#4656]
**Screenshots**
![image](https://user-images.githubusercontent.com/19853115/133941067-e562c24b-33d7-49b1-b9ab-5bfb58f97b64.png)

**Comment by Ygg01** [comment]
How?

**Comment by mirrorcult** [comment]
probably has to do with viewports

**Comment by Ygg01** [comment]
@mirrorcult more like is there a picture of it breaking the board? As in a screenshot of the effect?

**Comment by TimrodDX** [comment]
> 
> 
> @mirrorcult more like is there a picture of it breaking the board? As in a screenshot of the effect?

I was going through singularity-related bugs looking for one related to the PA (which I'm going to put up after I make this post) but here's some screenshots and reproduction steps.

How to Reproduce:

- Step 1: Be playing Chess.
- Step 2: Spawn a Singulo toy anywhere within the 12-tile PVS view limit.
- Step 3: The Chess window will break as long as the shader is within reach of where the chessboard is.

![image](https://user-images.githubusercontent.com/7907891/135788052-9d2d2042-91e8-4cac-878d-d53b845590a0.png)

![image](https://user-images.githubusercontent.com/7907891/135788159-1cd87bae-388f-4e12-9022-e18650739e5b.png)

![image](https://user-images.githubusercontent.com/7907891/135788180-1230cb49-f990-44ce-b5ae-7e05006c7db9.png)
 
![image](https://user-images.githubusercontent.com/7907891/135788211-f13699fc-eec2-4ccd-96a8-e342dbf854ed.png)

**Comment by PJB3005** [comment]
Probably because overlays aren't per-viewport.

**Comment by PaulRitter** [comment]
> Probably because overlays aren't per-viewport.

![image](https://user-images.githubusercontent.com/16618384/135858884-17a59d9a-814c-40ba-b9cc-a7096b3b7711.png)

**Comment by AJCM-git** [comment]
![image](https://user-images.githubusercontent.com/60196617/176568337-99b00694-f8df-4be0-b150-fe4891b0fdf7.png)
This doesnt happen anymore
