### ISSUE TITLE
Proposing UI changes for Action Bar

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#4661]
## Description

So after recent discussion on the Action Hotbar one of the major issues with it is that it looks ugly and cumbersone. Chairbender made it exact to the Figma spec but unfortunately it does not blend in with our current UI.

#3285 #3533 #3429 #11895 are all tangentially related to this.

I've provided some sample screenshots below of scale/opacity changes that were suggested for the Action Hotbar in Discord. These are all at 100% UI scale, 720p.

**Screenshots**

**Current Hotbar for reference**
![current](https://user-images.githubusercontent.com/49448379/133946760-91179a5e-d621-470d-b50e-b37422771626.png)

**Hotbar set to 70% opacity**
![70](https://user-images.githubusercontent.com/49448379/133946769-4f690d7d-0eb0-450c-ae21-793754475c8b.png)

**Hotbar scale decreased by 20%**
![80](https://user-images.githubusercontent.com/49448379/133946775-d2dbe921-6669-4fc2-859b-d590370bf427.png)

**Opacity to 70% and Scale decreased by 20%**
![70plus80](https://user-images.githubusercontent.com/49448379/133946794-5a4f61f8-eb42-408d-aca1-eaca2858601b.png)

**Elongated version of the hotbar with scale decreased by 20% and 0th slot removed**
![80long](https://user-images.githubusercontent.com/49448379/133946814-3e5e22f7-b5fa-4397-b8c2-86aebd07ece0.png)

**Same as above but at 70% opacity**
![70plus80long](https://user-images.githubusercontent.com/49448379/133946831-48f004d3-ca00-4342-9517-1313f65fbdd5.png)

**A modified version based off some of @mirrorcult's comments.**
![mirror70op](https://user-images.githubusercontent.com/49448379/133947046-06decfc9-70be-4c63-8fc6-a268e218946f.png)
**Additional context**

If you'd like to see additional mockups let me know I can make them pretty quickly.

**Comment by Zumorica** [comment]
I think it'd look better if the action buttons themselves weren't transparent, and empty action buttons were hidden

**Comment by SweptWasTaken** [comment]
> 
> 
> I think it'd look better if the action buttons themselves weren't transparent, and empty action buttons were hidden

Like this? 

(Moved over tiles so you can actually make out the transparency)

![image](https://user-images.githubusercontent.com/49448379/134051565-53881eaf-8b57-4134-8214-541160d781f1.png)

**Comment by Zumorica** [comment]
Something like that, yeah. That looks pretty good to me

**Comment by mirrorcult** [comment]
i also quite like that

**Comment by PaulRitter** [comment]
imo we can shrink it down much more than that, we dont need such massive icons imo

**Comment by lzk228** [comment]
solved?
