### ISSUE TITLE
Drinking glasses don't shatter when thrown

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#4665]
## Description
1. Get drinking glass
2. Throw it at the nearest wall or floor
3. Glass doesn't shatter.

Seems that due to the `Glass` damage modifier set, blunt damage has a 5 flat reduction.
Currently, when glasses land they get damaged by 5 blunt. Therefore, they never get damaged.

**Comment by Zumorica** [comment]
Partially fixed by 1b44da19ae4a5777cad5c08cc4ce769de6a78e65, however the glass resistance is still pretty bad.

**Comment by SweptWasTaken** [comment]
Can't reproduce, closing.
