### ISSUE TITLE
Ghosts can point and regular players can see them.

### ISSUE THREAD

**Issue by 20kdc** [space-wizards/space-station-14#4685]
## Description

as stated

**Screenshots**

from player's perspective:

https://user-images.githubusercontent.com/22304167/134548545-08b858d6-0a81-4701-82a0-5bf163c84b96.mp4

attempt from the ghosts's perspective:

https://user-images.githubusercontent.com/22304167/134549335-a42a6b8d-d649-4148-b235-6f35bbaecc55.mp4

**Additional context**

**Comment by Zumorica** [comment]
Fixed by fcb23627eb15c752429446a3ec7ad4d3ea352e2d
