### ISSUE TITLE
Grown bananas are "empty"

### ISSUE THREAD

**Issue by 20kdc** [space-wizards/space-station-14#4693]
## Description

It is important to note first of all that this only applies to bananas grown via botany.

(There was a note here about plasma spawned on the map i.e. in medical, but it's probably unrelated. probably.)

**Screenshots**

![image](https://user-images.githubusercontent.com/22304167/134730442-54aeab7c-4201-4f6c-b32d-9136f1a913e9.png)

**Comment by SweptWasTaken** [comment]
Unsure of why this is happening since the seed just spawns FoodBanana. Maybe it's messing up due to the banana peel thing being a trash.

**Comment by 20kdc** [comment]
Something to note is that grown bananas also don't grind into reagents properly.
So the banana peel is probably not related, though still worth poking at.

**Comment by 20kdc** [comment]
So at some point or another this was fixed. I have long since forgotten when.
