### ISSUE TITLE
Add option to change keyboard default language

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#4712]
## Description

This might need to go in RobustToolbox since Keys.cs is in there.

Currently if your system default language is not English (Russian in this example) your hot-bar visual keybinds will change to that languages native alternatives.

![unknown](https://user-images.githubusercontent.com/49448379/135513272-d3848077-911b-4882-9afd-a5592bffc18e.png)

There should be an option in the controls menu to allow you to switch this to something else.

**Comment by lvvova1** [comment]
I have a question on how best to do it:

Give a choice of which language use hotkeys
(via drop down menu, if you have EN, RU, languages you will have only EN, RU option)
Or leave a checkbox: "use English keys"

**Comment by mirrorcult** [comment]
'use english keys' or 'use latin alphabet for keys' is best imo

**Comment by ShadowCommander** [comment]
Fixed in #4898
