### ISSUE TITLE
IC names don't show up on the kick menu for players other than your own

### ISSUE THREAD

**Issue by DrSmugleaf** [space-wizards/space-station-14#4716]
## Description
- Open the admin panel (F7)
- Open the kick menu
![image](https://user-images.githubusercontent.com/10968691/135668488-a414c217-3819-4ab6-b58d-1925a0b76edc.png)

**Comment by PaulRitter** [comment]
could probably refactor the playerlistmenu to just save the playerlist in the adminmenumanager, then use that for all these windows
