### ISSUE TITLE
You can examine entities hidden behind the viewport size cutoff

### ISSUE THREAD

**Issue by DrSmugleaf** [space-wizards/space-station-14#4718]
## Description
- Find an entity.
- Make sure to not hide it behind FOV, maintain line of sight with it
- Move so it's outside of the viewport and in the black regions on the side.
- Right click it.

The airlocks at spawn work well for this.
![image](https://user-images.githubusercontent.com/10968691/135669880-f5eb3ca9-48e9-4950-b9ff-91c974d001f3.png)

**Comment by mirrorcult** [comment]
dupe #4651
