### ISSUE TITLE
Gun features design sheet

### ISSUE THREAD

**Issue by brndd** [space-wizards/space-station-14#472]
I had a couple of thoughts on this so I figured I'd post them here instead of having them be buried on the Discord. 

Detailed semi-realistic handling is underrated in video games, and SS~~13~~14 is the kind of game where that kind of thing is right at home IMO. Most SS13 codebases already have this to some degree, but it would be a wasted opportunity to not expand on it further with this reimplementation.

As a caveat it should be said that I am not a gun nut, though I would consider myself generally informed on the basic principles of this stuff. If something here is wrong, especially in a way that makes a gameplay difference, please do point it out. I'm also assuming the reader knows what the basic parts of a gun generally are; the core concepts here are the magazine, the bolt, the chamber, and the trigger.

## Projectile weapons

Projectile weapons should work like real-life guns do. By this I mean not taking typical video game shortcuts like not simulating the chamber, or treating magazines as a simple two-pile system of "ammo in the gun vs. ammo in reserve".

However, going too deep with the simulation will make things confusing for players, so some parts will have to be simplified. The goal here is to have enough detail in the simulation that you feel like a real tough and cool action guy while handling a gun in-game, but don't need extensive knowledge of firearms to operate them.

For simplicity's sake, I think it makes sense to treat all weapons as closed-bolt weapons. Open-bolt weapons have some differences with the way rounds are chambered, but I don't think adding this distinction wouldn't provide enough gameplay value to make up for the added complexity.

### Most guns

Most guns have enough in common that they can be covered by generic, shared logic. This is an attempt at detailing this generic logic. This should cover things like pistols, assault rifles, submachine guns, shotguns of all kinds, bolt-action rifles, single-shot weapons like flare guns or single-shot grenade launchers... as well as weapons with both detachable and internal magazines.

Please let me know if you can think of situations where this logic fails. 

- The state of the chamber should be simulated in a realistic fashion. Inserting a magazine does not chamber a round, and therefore pulling the trigger will not fire the weapon. A round is only chambered when the action is cycled by pulling the charging handle (on a rifle) or racking the slide (on a pistol).
    - It should be possible to manually insert rounds into the chamber one at a time if the gun does not have a magazine. Chambering a round this way is only possible if the bolt is open (see next point).

- The gun's action should be simulated *superficially*. We don't care about every single part inside, but we care about what those parts *do*. In practice this means we care about the state of the bolt. The state of the firing pin/hammer does not need to be simulated (in other words, pulling the trigger will always fire the round if it *can* be fired).

    - The action can be cycled by the player at will, regardless of the current state of the gun (*how* will be detailed in the Controls section).

    - Cycling the action will:
        - Eject the cartridge currently in the chamber, regardless of whether it has been fired or not. The cartridge will in most cases be dropped on the floor somewhere nearby.
        - Move a cartridge from the magazine into the chamber.
        - Close the bolt, making the gun ready to be fired.

    - For (semi)automatic weapons, firing the weapon will automatically cycle the action. For manual weapons the action must be cycled by the player after every shot. This should be the only functional difference between the two types, allowing basically all of the code to be shared between them.

    - The bolt will automatically lock open when the magazine is empty, ie. when it fails to chamber a round. When the gun is in this state, the player manually cycling the action will toggle the bolt between its open state and closed state. For simplicity's sake manually locking the bolt open on an automatic gun (a feature on some real firearms) is not possible; it will only lock open when the gun is empty.
        - Bolt-action guns, such as Mosins, are an exception to this; for them the bolt should always toggle between an open state and a closed state. This is because the bolt must be open in order to load the internal magazine of these guns (either one round at a time or via a stripper clip). This will also serve to give bolt-action guns something of an unique feel.

- Guns need a fire selector, ie. the ability to toggle the gun between safety, semi-auto, full-auto, burst-fire etc., whatever is applicable for the gun in question.

- The magazine should be modeled realistically. We already mostly have this. Some weapons have detachable magazines (eg. C-20r), while others have internal magazines (eg. pump-action shotguns). The primary functional difference between the two is rather obviously the ability to detach the magazine.
    - Some guns will allow you to load rounds into the magazine without detaching the magazine, while others will not. In general weapons with internal magazines allow reloading the magazine without detaching it (for obvious reasons), while those with detachable magazines do not. However, to catch edge cases this should be a separate flag; someone might want to make a gun with a detachable magazine that can reloaded without detaching it, or alternatively a gun with an internal magazine that cannot be reloaded without detaching it (ie. cannot be reloaded).
    - Magazines need to remember and respect the order rounds are loaded into them, to enable eg. alternating beanbag/stun shell shotguns, or assault rifles with a flare round every 4 rounds.

### Outliers and how to (maybe) deal with them

Not all guns fit nicely into the generic mould suggested above. Here are some examples that may exist and how they can be dealt with.

**Revolvers**

- Could be presented by a semi-automatic weapon with an internal 6-round (or however big the cylinder is) magazine. If this is done, they will need some snowflake logic to keep empty cartridges inside of the gun until the magazine is reloaded.

- However, it would probably be better to just implement them as their own subclass of weapon, because revolvers are very common and *everyone* knows how they're supposed to work. If this is done, it should be possible to manually rotate the cylinder in order to enable eg. Russian roulette (only one round in the cylinder, cylinder spun to a random position) and cowboy loads (one chamber in the cylinder is empty and the hammer is resting on this chamber to avoid bump-firing the gun; no practical advantages in the context of spess, but it's cool).

- It might be cool to simulate double-action/single-action on these. Cycling the action would cock/uncock the hammer. If the hammer is cocked when you pull the trigger, you'll immediately fire. If the hammer is not cocked, on a double-action revolver you'll fire after a small delay (to simulate the much heavier trigger pull of a double-action system), and on a single-action revolver you won't fire.

**Caseless ammunition**

- The Lawgiver uses this in SS13, I think. Could simply be an ammunition subtype that has no empty casing defined. This means that when a round is fired, no empty casing is ejected. However, if the action is cycled with an unfired cartridge in the chamber, the cartridge would naturally be ejected intact.

**Belt-fed guns**

- These can probably just be represented as regular magazine-using guns except the magazines are ammunition boxes. This is common in video games already (see: M249 in CS:GO), and the ability to splice belts together for continuous machine gun fire is probably not that useful in spess.

- For extra gun porn factor belt-fed guns should eject the disintegrated links of the belt along with empty casings, but this is a pointless detail.

## Energy weapons

I might write more about these later, but they're pretty simple. They have a power cell and a certain amount of charge is drained from it whenever the weapon is fired.

Eris has detachable power cells on energy weapons, which is cool. If we want detachable power cells, they should probably handle similarly to magazines as far as controls go. The fire selector on energy weapons would be pretty much the same as on projectile weapons: safe, stun, kill for the e-gun for instance.

## Controls

I'm not completely up to speed with the control scheme plans for SS14, so this section could do with some input.

- Cycling the action needs to be its own key on the keyboard. Players will need to be constantly hitting this key when using eg. a pump-action shotgun. The "activate item" key `Z` might be good for this.

- Detaching the magazine can be done in a couple of ways. One would be just clicking on the gun with an empty hand, but I don't like this because it makes it difficult to move the gun from one hand to another. Personally I prefer the way Eris does this: drag-and-drop from the gun's sprite to an empty inventory slot (or anywhere in the world) to take the magazine out and put it where you dragged it to. However, this may or may not align with the control schemes you have planned for SS14.
    - Additionally, a right-click menu option for detaching the magazine should be present for whenever the primary option is inconvenient.

- Loading ammunition into a magazine should just entail clicking on the magazine with a cartridge, a pile of cartridges, an ammo box, etc. This will automatically load all the rounds the magazine was clicked with into the magazine up to the magazine's capacity, with a delay that depends on the number of rounds being loaded.

- Loading ammunition into a gun is similarly just a matter of clicking on the gun with the ammunition in hand. The exact behaviour of this will depend a little on the gun: for shotguns the rounds are inserted into the internal magazine regardless of bolt state; for bolt-action rifles like Mosins the rounds are inserted into the internal magazine only when the bolt is open (otherwise they cannot be inserted at all); for automatic weapons like the C-20r a single round can be inserted into the chamber if the bolt is open, and the magazine must be detached in order to be reloaded.

- The fire selector could be done as a contextual button somewhere near the gun's icon in the hands GUI. There should be the possibility for an optional keybind for this.

- Holstering/unholstering a gun should have an optional keybind, unless you believe that clunkiness is a gameplay mechanic.

## References for other games that have done this well

CEV-Eris (you know, the place we get our sprites from) has pretty good gun management.

[Receiver](https://store.steampowered.com/app/234190/Receiver/) is an indie FPS game with highly detailed gun management, and it manages to do this with a somewhat reasonable amount of controls on a standard keyboard. We don't need that amount of complexity, but I still recommend giving it a try. It'll teach you how an M1911 works, too.

**Comment by acvzy** [comment]
Game design issues are now being removed from Github and added to the [HackMD docs](https://hackmd.io/@ss14/docs).

Yours is already on the [gameplay design](https://hackmd.io/@ss14/docs/https%3A%2F%2Fhackmd.io%2F%40ss14%2Fgameplaydesign) page in its entirety.

Closing
