### ISSUE TITLE
singularity shader has major pop-in

### ISSUE THREAD

**Issue by PaulRitter** [space-wizards/space-station-14#4722]
![grafik](https://user-images.githubusercontent.com/16618384/135680968-d493b9d2-564d-4a89-b251-dfce9cef4a6b.png)
moving three tiles to the left...
![grafik](https://user-images.githubusercontent.com/16618384/135680980-aeffa778-d234-4b73-a8a5-217b96cab546.png)

**Comment by AJCM-git** [comment]
related to #3504

**Comment by PaulRitter** [comment]
> related to #3504

why?

**Comment by DogZeroX** [comment]
Fixed
