### ISSUE TITLE
popup spam be annoying as fuck

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#4729]
## Description
it stays in place on your UI and not world, so if you move around it looks extra jarring
+ you can see thru walls but i think thats reported

**Screenshots**
![image](https://user-images.githubusercontent.com/19853115/135693511-06139c3d-f9c2-49ac-b901-daeacb9671d3.png)

**Additional context**

**Comment by Zumorica** [comment]
The dice now has a roll cooldown so the popup cannot be spammed btw.

**Comment by Willhelm53** [comment]
Dice seems to be quite spammable still.

I think it correctly stays in place in the world now though.

**Comment by AJCM-git** [comment]
No longer an issue and the second point already has an issue.
