### ISSUE TITLE
Ghosting from a mob without a name creates a ghost without a name

### ISSUE THREAD

**Issue by ShadowCommander** [space-wizards/space-station-14#4731]
## Description

Users who control a mob with no name and then become ghosts have no name as a ghost and also in chat.

e.g. cats, UristMcHands, dogs, and other mobs.

**Screenshots**

![image](https://user-images.githubusercontent.com/10494922/135697674-be70301b-056d-4ba5-94a9-a2bb2706e7c8.png)

**Comment by moonheart08** [comment]
Also occurs if you observe then aghost.
