### ISSUE TITLE
Unicode spam causes server to lag or crash

### ISSUE THREAD

**Issue by Derpyhsi** [space-wizards/space-station-14#4733]
## Description
Certain unicode characters can be used to cause server memory to spike and therefore cause the server to lag or worse crash.
Steps to Reproduce:

1. Find paper and pen
2. Use a wide/very long unicode character [(Source)](https://www.reddit.com/r/Unicode/comments/5qa7e7/widestlongest_unicode_characters_list/)
3. Copy and paste/spam the character until you are not able to anymore. 
4. View the paper to cause lag or a crash.

**Screenshots**

**Additional context**
Problem could be fixed by either preventing certain unicode letters to be used or by setting a character limit for anything with user input. It is also replicable in cargo console as well (either the name or reason text field).

**Comment by zapjaffe** [comment]
May have been solved for paper by #6213

**Comment by moonheart08** [comment]
this is long fixed and the server does no unicode processing.
