### ISSUE TITLE
Broken cablecuffs can be worn as a belt

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#4734]
![image](https://user-images.githubusercontent.com/7907891/135699053-8cbba3c5-764f-4d9b-9634-f9021e7d8bfa.png)

How to reproduce: 

 - Make some cablecuffs
 - Break the cablecuffs by uncuffing someone who has them on
 - You can now wear the cablecuffs as a belt.
 - The cablecuffs can be taken off, but won't be replaced by a real belt if you use the equip shortcut.

![image](https://user-images.githubusercontent.com/7907891/135699154-a7328f75-a1ff-4169-9781-d4fa6026ca36.png)

![image](https://user-images.githubusercontent.com/7907891/135699164-779ab71e-a1f1-4530-a6ad-754ddd9ec853.png)

![image](https://user-images.githubusercontent.com/7907891/135699185-a0c2a4a8-7d30-4548-a7ad-e94cfe775b03.png)

**Comment by SweptWasTaken** [comment]
Cuff broken states aren't a separate entity so it's a little tough to stop them being worn. I think i'm just going to remove cuffs being wearable on your belt at all.
