### ISSUE TITLE
Conveyor belts block pulls and strip attempts and melee attacks completely.

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#4735]
![image](https://user-images.githubusercontent.com/7907891/135699352-ced9a944-aa76-418c-93e8-1aa6917ea0bf.png)

How to reproduce:

- Spawn a conveyor belt
- Spawn an item on top 
- Attempt to pull the item
- You'll get the "You can't reach there!" message even if you're right next to it.

Alternatively,

- Spawn a conveyor belt
- Spawn an Urist and put a clothing item on them.
- Put the Urist on the conveyor belt.
- You will be unable to pull, strip, or otherwise move the Urist.
- You also can't loot or pull others if you are standing on a conveyor belt.

This will block punches and disarm attempts but will not block attacks with melee weapons.

![image](https://user-images.githubusercontent.com/7907891/135699364-c5aecd0f-c991-4c40-85ed-f1f3909b8113.png)

![image](https://user-images.githubusercontent.com/7907891/135699505-2f97abb8-948e-4066-9705-41dd0839e4d4.png)

![image](https://user-images.githubusercontent.com/7907891/135699553-ffa20d6d-2f7e-4a07-b6a4-86ff1499f4c3.png)

**Comment by AJCM-git** [comment]
related to #5203

**Comment by AJCM-git** [comment]
no longer the case
