### ISSUE TITLE
Multiple handheld radios can cause radio spam

### ISSUE THREAD

**Issue by Derpyhsi** [space-wizards/space-station-14#4738]
## Description

Turning on and packing multiple handheld radios in a bag can cause radio channels to be spammed/cluttered with messages.

Steps to Reproduce:
1. Get handheld radios
2. Turn on handheld radios
3. Put them in a bag
4. Say something in local chat

**Screenshots**
[Screenshot](https://imgur.com/a/f9FbdPb)

**Additional context**
Unsure on how to fix this.

**Comment by mirrorcult** [comment]
IMO this is something that should be allowed but handled IC, or admin intervention if you're a loser

**Comment by Derpyhsi** [comment]
Maybe if it gets to the point of lagging/crashing the server, then admin intervention should be required.

**Comment by TimrodDX** [comment]
> 
> 
> Maybe if it gets to the point of lagging/crashing the server, then admin intervention should be required.

The thing is, I tested this at one point with something like a hundred radios on sandbox (granted, I was alone) and it didn't cause any noticeable lag even with me spamming it. The only time I've ever seen this be a problem was on Goon a long time ago when the messages were multiplied per radio.

**Comment by mirrorcult** [comment]
ye ill just close this on the grounds of 'either man up and murder whoever does this or ban them'

**Comment by Derpyhsi** [comment]
I think thats fair.
