### ISSUE TITLE
Rules popup for first-time players on a server

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#4756]
## Description

Servers should communicate their rules better to players and have them understand that their actions can lead to permanent bans. A popup directing a first-time player to read the rules and communicating the former should be implemented. 

The popup should proc whether you join mid-round or into the lobby.

**Comment by DrSmugleaf** [comment]
Done in https://github.com/space-wizards/space-station-14/pull/5715
