### ISSUE TITLE
Singularity and PA don't update often enough.

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#4763]
## Description

Right now, the singularity only checks for things to eat every 0.5 seconds, which causes issues with the particle accelerator. The singularity is now MUCH slower to spawn (taking up to 5 shots from the PA where before it only took 2 or 3) and almost impossible to upkeep. At Power 1, the singularity will die. At Power 2, it will eventually eat containment. 

The amount the PA feeds the singularity probably needs to be updated to account for this. Ideally, Power 1 should maintain a singularity's size while Power 2 is slow growth and Power 3 is rapid growth.

**Comment by metalgearsloth** [comment]
Just use collision for the particle accelerator.

If it updates every tick it's gonna take up 1ms of server time again which is ridiculous.

**Comment by AJCM-git** [comment]
related to #3504

**Comment by mirrorcult** [comment]
this was fixed at some point
