### ISSUE TITLE
Pulling is laggy again

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#4769]
Think it was https://github.com/space-wizards/space-station-14/pull/4695 that did it

I checked out dacbfff and it's not laggy but on master (aa9518e) it is.

**Comment by metalgearsloth** [comment]
So turns out pulling isn't networked anymore for reasons

**Comment by 20kdc** [comment]
So it turns out I completely forgot about `HandleComponentState` and didn't notice because of a lack of sufficient lag
