### ISSUE TITLE
Eject/Insert functionality should be standardized

### ISSUE THREAD

**Issue by ElectroJr** [space-wizards/space-station-14#4770]
Currently every component that has eject/insert functionality implements its own `TryInsert`, `TryEject` and `InteractUsing` functions and its own insert/eject verbs. This functionality should probably be standardised by making all those interactions instead go through the newly added `SharedItemSlot` system/component, or some other new system that works similarly.

The systems/components that need changing include:
- [X] PDA
- [X] ItemCabinet
- [X] IdCardConsole
- [X] ChemMaster
- [X] ReagentDispenser
- [x] PowerCellSlot
- [x] BaseCharger
- [x] ~ServerBatteryBarrel~ (now just uses power cell slot)
- [ ] ServerMagazineBarrel

**Comment by mirrorcult** [comment]
PneumaticCannon should probably be given itemslots

**Comment by mirrorcult** [comment]
this is done with gun refactor i believe, or at least it was considered and anotehr solution used, dont remember
