### ISSUE TITLE
Player notes system

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#4792]
## Description

Admins need the ability to leave notes on players. These notes should be stored in the database and carry across to servers in the same "cluster". (For example if an admin leaves a note for someone on SS14 USWest it would show to an admin on EUW but not on say Hyperion Station).

Notes will expire after a set amount of time. You should be able to enter this at note creation but there should also be a default of a year that applies if you leave nothing in the box.

In the future players should be allowed to see their notes, ideally by logging into a web-panel but displaying them in-game would be acceptable for now since we don't have much of a player web-presence. 

This is a big project so i've left made rough mockups I made for what i'd like the UI to look like. I'd like to avoid admins opening a cascade of windows when making a note so try and handle stuff in the window itself instead of opening new "textbox entry" windows.

**Screenshots**

![111](https://user-images.githubusercontent.com/49448379/136434437-e50e5b23-6b3c-4781-b7ea-dafc1084972a.png)
![ii](https://user-images.githubusercontent.com/49448379/136434477-14c8caf7-d34b-40db-aad9-87b793a203e0.png)

**Comment by ike709** [comment]
Currently working on this.

**Comment by SweptWasTaken** [comment]
> 
> 
> Currently working on this.

K I assigned you.

**Comment by DrSmugleaf** [comment]
Done in https://github.com/space-wizards/space-station-14/pull/7259
