### ISSUE TITLE
Screwdrivers aren't working on doors and machines.

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#4795]
This bug was originally reported by Raven#1990. I have replicated it on a local environment updated to latest master as of 10/07/2021 at around 9:30 PM EST.

How to Replicate:
- Pick up a screwdriver.
- Attempt to use it on a door.
- The interaction bar will not show up, and the panel on the door will not open.

Screwdrivers still work properly on windows and in construction, just not on existing doors or machines.

![image](https://user-images.githubusercontent.com/7907891/136483981-da23e2a5-b30b-46a6-b219-138ca6170284.png)

![image](https://user-images.githubusercontent.com/7907891/136484005-fa9774f1-c9c6-4997-ab00-3806295bb2e8.png)

**Comment by mirrorcult** [comment]
@Zumorica last touched tools

**Comment by moonheart08** [comment]
This also is an issue with wrenches, can't advance the PA's construction.
