### ISSUE TITLE
You can cremate yourself

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#4802]
i imagine the cremate button is on the outside so

**Screenshots**

https://user-images.githubusercontent.com/19853115/136611479-b9e0e442-2a71-4afe-b2bc-c1c8da8f4f6a.mp4

**Additional context**

**Comment by mirrorcult** [comment]
actually ive decided i dont care and this is funny

**Comment by PJB3005** [comment]
In SS13 the cremater is controlled by a separate button on the wall.
