### ISSUE TITLE
In-game way to view subfloors

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#4830]
## Description

Currently sub-floors can only be viewed in admin mode.

Adding a component to the meson scanners that enables this for players is the solution. The sub-floor visibility should be toggleable through the action menu.

**Comment by mirrorcult** [comment]
mesons dont let you view subfloor, T-rays do

**Comment by SweptWasTaken** [comment]
> 
> 
> mesons dont let you view subfloor, T-rays do

Well mesons are already in-game

**Comment by mirrorcult** [comment]
mesons don't work ingame

**Comment by Peptide90** [comment]
Can now be closed.
