### ISSUE TITLE
Need hand labelers

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#4834]
## Description
- Should allow you to set the label name through a simple bound UI
- Should append/prepend the label to an entity's name that you click on, and maybe specify in the description that it has been labeled

**Screenshots**
![image](https://user-images.githubusercontent.com/19853115/136869710-986a6070-52ef-4445-aab1-7b408db61e90.png)

![image](https://user-images.githubusercontent.com/19853115/136869797-c8fc0060-9519-4991-88ab-5c342fc75b4b.png)

![image](https://user-images.githubusercontent.com/19853115/136869833-e7a8d30b-0b7e-4028-9d88-cfc1cec7758e.png)

**Comment by MLGTASTICa** [comment]
> i think there was someone on discord who said they were working on this?

That was me , don't count on it , my knowledge in the general ECS arhitecture is still very very barebones
