### ISSUE TITLE
Need intercoms

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#4838]
## Description
Might want to wait for a radio/headset refactor. Should obviously reuse that code

**Screenshots**
![image](https://user-images.githubusercontent.com/19853115/136870508-5a91887f-4b45-4ff7-b750-082022d7c118.png)

**Additional context**

**Comment by Willhelm53** [comment]
Has such a radio/headset refactor been done since this was written? If so I can attempt.

**Comment by Willhelm53** [comment]
This one seems like it should wait on the chat portion of #5438. I'll leave it alone.

**Comment by EmoGarbage404** [comment]
so this got done.
