### ISSUE TITLE
MV and LV wires can't be placed if an HV wire exists on the tile.

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#4850]
How to reproduce;

- Place an HV wire on a tile.
- Attempt to place an MV or LV wire on the same tile.
- You will be unable to do so unless you cut the HV wire first.

Unless this is a balance change I'm unaware of, you've always been able to place any kind of wire on any tile, so long as the wire wouldn't be a duplicate.

**Comment by mirrorcult** [comment]
note that placing HV wires on tiles with LV/MV still works

**Comment by Zumorica** [comment]
Pretty sure this was fixed recently
