### ISSUE TITLE
Game needs little robots like beepsky and medsky.

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#4853]
Means there's got to be a way to give them a route to follow.
There's also got to be an arrest warranty console for beepsky to work properly

**Comment by mirrorcult** [comment]
https://hackmd.io/x-Jab8MvTOmOJnHDeJzr_w i shill my  silicon redesign for this

**Comment by mirrorcult** [comment]
no beepsky but make a separate issue for that !! there are little robots now
