### ISSUE TITLE
Implement opening the inventory pane of another mob

### ISSUE THREAD

**Issue by ShadowCommander** [space-wizards/space-station-14#486]
Implement opening the inventory UI of another mob to strip or clothe them.

It would be nice if a sound played when the inventory UI is opened.

Something to think about is what hotkeys or input should be used to open the inventory of other mobs. In Space Station 13 this is a click drag input #200.

**Comment by pss88** [comment]
"E" key?

**Comment by Qustinnus** [comment]
I'm gonna throw my hat in the ring for this.

**Comment by Zumorica** [comment]
Assigning myself as it has been almost half a year already.
