### ISSUE TITLE
Walking between two windoors is finicky

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#4867]
How to reproduce:

- Spawn two windoors on a tile, with one on the north side and one on the south side.
- Try to walk between them.

I've noticed that a couple of things can happen, including getting stuck (if there's a wall or window on one end), one of the windoors becoming permanently opened (if they're powered) and having jerky collision on the way through. Since this is a common feature in a lot of SS13 maps (along with small spaces made by thin windows) it's something that probably should be resolved.

![image](https://user-images.githubusercontent.com/7907891/137236183-24d87d35-f61c-4b33-87a0-2a2341fd7d97.png)

![image](https://user-images.githubusercontent.com/7907891/137236209-8283012c-3716-4665-8b50-060f93e82233.png)

**Comment by TimrodDX** [comment]
> 
> 
> How do you propose resolving it because your bounding box is larger than the area between them?

I'm not sure. It's obviously kind of a complex issue, given the movement differences between SS13 and SS14 - and if in the end the solution is "just don't map windoors that way" that's fine - but I think there should probably be a slight bounding box change so that you wouldn't be able to get in between two windoors placed close together like that.

**Comment by metalgearsloth** [comment]
Could suss out using 2-sided edge shapes instead though I haven't optimised the polygon <> edge code in the slightest.

**Comment by mirrorcult** [comment]
should be fixed in #5195 since i updated windoors bounds, can you check?

**Comment by mirrorcult** [comment]
![image](https://user-images.githubusercontent.com/19853115/140627653-471cf778-6e4d-447b-a66e-b6af56b9552d.png)
