### ISSUE TITLE
Machine-Linking is broken

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#4876]
## Description

It's just busted. The button in sandbox menu for linking doesn't work since the command was removed. Additionally the mapped in conveyor in the South of Saltern doesn't function. 

Trying to link switches/levers with other stuff doesn't function, even if it has the right ports.

**Comment by mirrorcult** [comment]
machine linking with multitool still works

conveyor just needs to be fixed, and the command needs to be reimplemented (tho i think you can just aghost and use a multitool inhand while mapping)
