### ISSUE TITLE
Nanotrasen Block Game(TM) nonfunctional

### ISSUE THREAD

**Issue by ike709** [space-wizards/space-station-14#4879]
## Description

I opened an NBG arcade game during the playtest and I can't actually use any of the buttons.

**Screenshots**

![image](https://user-images.githubusercontent.com/5714543/137503784-2ed80ee0-9fc7-4bb8-b7ff-193534a4b823.png)

**Additional context**

**Comment by AJCM-git** [comment]
are you sure somebody else wasnt playing? i think it blocks you if another player is already there

**Comment by ike709** [comment]
Definitely didn't look like anyone else was in range, and even if that was the issue it needs better feedback.
