### ISSUE TITLE
Typing "a" sometimes switches to admin chat

### ISSUE THREAD

**Issue by DrSmugleaf** [space-wizards/space-station-14#4894]
## Description
- Make sure you don't have any characters entered into the chat
- Switch to admin chat
- Make sure it's empty again
- Type [ to start typing in OOC
- Type anything
- Type a
- Repeat this a bunch of times because it's very inconsistent
- It deletes what you have currently written and changes to admin chat
- You can no longer use the letter a in your message

Once you get it to happen once you can get it to happen reliably if you backspace every character you wrote before clicking outside of chat and repeating steps 4 to 6.
Using tab seems to help with getting into the loop sometimes.

**Screenshots**

https://user-images.githubusercontent.com/10968691/137563157-aaf6d2a6-07e1-4bed-ab2c-118eb7b59444.mp4

**Comment by AJCM-git** [comment]
Not reproducible and hasnt been reported in months
