### ISSUE TITLE
Game lacks LOOC

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#4930]
Local out-of-character, so you can salt without everyone seeing your message.

**Comment by mirrorcult** [comment]
i absolutely do not want LOOC

**Comment by Zumorica** [comment]
A tutor system might come in handy instead then. And also sending ahelps to discord so admins can see

**Comment by PaulRitter** [comment]
might even expand the mentor system to "forum"-esque system where people can:
- opt into getting notifications if someone asks a question
- ask questions, duh

imo this would be miles more effective than looc

**Comment by AJCM-git** [comment]
The consensus is that we won't have a LOOC. Maybe another codebase will implement it
