### ISSUE TITLE
Torches cause a seizure-inducing flashing

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#4943]
https://user-images.githubusercontent.com/43253663/137777156-2f0919be-918f-41dd-a574-9f28da0e5c15.mp4

**Comment by thevinter** [comment]
I'm taking it. Also it looks like torches turn off after a couple of seconds in my build, not sure if someone else can replicate it as well.

**Comment by thevinter** [comment]
It has been confirmed on Discord that the light does indeed disappear after ~10 seconds

**Comment by Zumorica** [comment]
Fixed by a67c866319104e178c7ff500bb45e5288190f28f
