### ISSUE TITLE
All the doors in the station have yellow above them like their on emergency open mode

### ISSUE THREAD

**Issue by Hoolny** [space-wizards/space-station-14#4964]
## Description

everyone has probably already notice this but making it an issue doesn't harm 
**Screenshots**

![image](https://user-images.githubusercontent.com/84478872/138199762-10ef49d8-310f-4d3f-8805-641ed316756f.png)

**Additional context**

**Comment by ike709** [comment]
I can confirm this is an issue.

**Comment by metalgearsloth** [comment]
Due to drawdepth and y-sorting yes
