### ISSUE TITLE
Add Sec-hud and medihud glasses functionality

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#4967]
The sec-hud requires a "Sec database" because it displays people with arrest warranty, medhud just displays HP.

**Comment by AugustEymann** [comment]
I began work on the sec database what is going to be the best way to get an array of players with their characters names.

**Comment by Peptide90** [comment]
> I began work on the sec database what is going to be the best way to get an array of players with their characters names.

I'm not familiar with it but we have the crew monitoring console as an example of player names.

Our admin player menu also has roles info so could be an amalgamation of the two.
