### ISSUE TITLE
Round restart is breaking constantly on production servers

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#4970]
## Description
what the fuck, it happens every few rounds it seems like

**Comment by moonheart08** [comment]
> is this.. actually true though
> 
> haven't seen a manual round restart in a while. besides euw2 failing because of a cert thing that's unrelated

I've personally been manually restarting the entire server, as `restartround` stops functioning in this fail state.

**Comment by AJCM-git** [comment]
might be related to #3984
