### ISSUE TITLE
Implement pocket slots.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/space-station-14#499]
Pocket slots are implemented on the HUD and I think there's slot defines for them, but they definitely don't work properly yet.

**Comment by Zumorica** [comment]
What's the state of this, can it be closed?

**Comment by PrPleGoo** [comment]
>they definitely don't work properly yet.

What do you mean by this?
Does taking off your jumpsuit not drop your pocket contents?

**Comment by PJB3005** [comment]
Old issue, this can be closed.
