### ISSUE TITLE
Glass shards are OP

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#4991]
You can break glass by throwing them three times, they can break chairs in two throws, I'm sure you can do it with other furniture too haha.

**Comment by mirrorcult** [comment]
shards should probably break as well, just into dust or something

**Comment by DogZeroX** [comment]
Worth to mention that you can kill people with them by spamming throw and grab.

**Comment by Peptide90** [comment]
Sounds like they need a throw do after then to stop spam throwing.

**Comment by Pangogie** [comment]
I count 25 throws to break a normal window tile. That seems fine? Seems like it was already fixed.

**Comment by mirrorcult** [comment]
yes this was already fixed
