### ISSUE TITLE
Examine System

### ISSUE THREAD

**Issue by clusterfack** [space-wizards/space-station-14#50]
This uses an entity component system for examine.

First we want a description variable on entity prototypes, and then an IExamine interface for components which returns a string or possibly a struct. Upon receiving a shift + left click message from the client the server should assemble the description and then append the IExamine returned values and then send that to the client.

Simultaneously you should improve the message to user system, so that it has some replacement macros which it knows like $name of certain entities/components and span classes. The system that sends messages to users could be similar to ss13 such as having places to define blind messages or hallucination messages.

(Old Design to potentially keep in mind for future expansion of this system)
```
Examine
While holding E the player gets the examine information of object he’s hovering over as a semi-transparent tooltip with short text. Clicking while holding the examine key (default E) pops out a window with either the same information or more detailed (depends on the object) with a tickbox for “close automatically” (defaults to ticked). 

The window only displays the information while the object is visible to the player. If the tickbox is ticked, then as soon as the object leaves the player’s sight and at least 1 second has passed since the window was opened the window will close automatically. Regardless of the tickbox, the window can be closed normally via the close button in the corner.
```

**Comment by clusterfack** [comment]
Done in a basic form for now, more advanced implementation can be done later

**Comment by Acruid** [comment]
The advanced implementation will be using a tooltip box, for both inventory and world examines. The box will open up, and float next to the item until the cursor is removed from the item. The text inside the tooltip box will be fetched once when the box is opened, so it will not update its content. This makes keeping the window open with a checkbox, or pinning the window, useless.

This can easily implemented as a single network RPC, so you don't need any sort of subscription system. The tooltip boxes should not be used as a replacement for the machine GUI systems. The range to examine an item should be within interaction range. You may want to rate-limit how often a client can examine an object.

Some visual inspiration on how these tooltip boxes can look:
![Diablo Tooltip.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5946ece4f5b8b6001a072a4b/125516c66e82c728ace21e0d46cc9d9b218e8ce9bbe6b04fb054e0d665043761260ea62864c7b96aea1b2f525f0d1ca412590c12aafd892ba4e56e72d80d03e8c3714d36976345f3e5db55ea43a82a994d84bcbd8f48c0ef3b21ee8d86473f1a1755.PNG)

**Comment by Injazz** [comment]
it can be closed i think, we have examine system, it's just it should be expanded further

**Comment by Acruid** [comment]
Yep, examine system is good enough right now.
