### ISSUE TITLE
Door lights do not blink red when access is denied

### ISSUE THREAD

**Issue by Efruit** [space-wizards/space-station-14#5005]
## Description
Bug present (approximately) since the recent large sprite merge.

**Comment by mirrorcult** [comment]
issue is that the yellow light overlay is above the deny lights. easy fix

**Comment by mirrorcult** [comment]
actually idk if thats what this is considering the opening animation works but closing doesn't

**Comment by SweptWasTaken** [comment]
The yellow light was a placeholder in my PR that I forgot to fix since cev-eris doors has an "always on" yellow light and tg doors don't.

**Comment by PaulRitter** [comment]
> 
> 
> The yellow light was a placeholder in my PR that I forgot to fix since cev-eris doors has an "always on" yellow light and tg doors don't.

we've decided to keep the "always on" light. no longer a placeholder

**Comment by mirrorcult** [comment]
did we decide that? its ugly

**Comment by PaulRitter** [comment]
we did, ye. I'm not opposed to changing it either tho

**Comment by SweptWasTaken** [comment]
> 
> 
> > The yellow light was a placeholder in my PR that I forgot to fix since cev-eris doors has an "always on" yellow light and tg doors don't.
> 
> we've decided to keep the "always on" light. no longer a placeholder

It looks really ugly.

**Comment by Efruit** [comment]
>Difficulty: 1-Easy
gonna have to disagree on that one

**Comment by metalgearsloth** [comment]
isn't it just a matter of fixing the states?
