### ISSUE TITLE
Keep Examine on Screen

### ISSUE THREAD

**Issue by ShadowCommander** [space-wizards/space-station-14#501]
Make the examine popup always appear on screen. Currently, the examine window isn't fully visible when examining things on the right/bottom of the screen.

**Comment by PJB3005** [comment]
I believe unusual Crow fixed this and I then broke it again when I refactored UI layout.

**Comment by PJB3005** [comment]
We need a generic control that will handle this for *all* popups. Modal popups, context menus, etc... all need this kind of behavior. Tagging it as engine for that reason.
