### ISSUE TITLE
Carpet doesn't hide wires if there's plating (but no tile) underneath.

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#5019]
## Description

How to reproduce:

- Spawn a carpet in a maint tunnel, or another place that uses tile-less floors.
- Put wires underneath it.
- The wires will show up on top of the carpet.

**Screenshots**

![image](https://user-images.githubusercontent.com/7907891/138613464-aa9c8880-e793-4d5e-a846-f6eccd60463d.png)

**Additional context**

**Comment by Visne** [comment]
Fixed in #5130.
