### ISSUE TITLE
Character sheet window is too small by default

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#5056]
.

**Comment by SweptWasTaken** [comment]
Does it need to be bigger? 

![image](https://user-images.githubusercontent.com/49448379/140624671-de6c8058-8afe-4c29-a696-584e2741efb5.png)

**Comment by mirrorcult** [comment]
> 
> 
> Does it need to be bigger?
> 
> ![image](https://user-images.githubusercontent.com/49448379/140624671-de6c8058-8afe-4c29-a696-584e2741efb5.png)

try it with objectives
