### ISSUE TITLE
Character turning seated on click is based on world rotation

### ISSUE THREAD

**Issue by aamonz** [space-wizards/space-station-14#5070]
## Description
If for example, the spaceship is rotated 180 degrees, and you click somewhere **while seated**, your character will turn towards the opposite direction.

**Screenshots**
![](https://cdn.discordapp.com/attachments/470226736219553794/903286675000668170/XvVdA5XnsS.gif)

**Comment by AzzyIsNotHere** [comment]
Working on this right now

**Comment by mirrorcult** [comment]
im pretty sure thsi got fixed actually

**Comment by AzzyIsNotHere** [comment]
> im pretty sure thsi got fixed actually

cringe
i'll take a look right now, thanks for mentioning

**Comment by Visne** [comment]
Fixed in #5134.
