### ISSUE TITLE
Unanchoring objects on tables collides the object with table

### ISSUE THREAD

**Issue by aamonz** [space-wizards/space-station-14#5074]
## Description
When the station is rotated (around 120 degrees or more) wrenching something (the bartenders machines in this case) cause the machines to clip through the walls.

**Screenshots**
![](https://cdn.discordapp.com/attachments/470226736219553794/903328457935704114/gFE93O7C0a.gif)

**Comment by Visne** [comment]
> 
> 
> Dragged/thrown items seem to clip through walls sometimes too

Please create a seperate issue.

**Comment by metalgearsloth** [comment]
This has nothing to do with rotation and is to do with the fact that the bartender machines collide with the table, hence unanchoring pushes it to nearest edge (which happens to be towards the wall).
