### ISSUE TITLE
Returning to body causes the "Died" timer to restart

### ISSUE THREAD

**Issue by aamonz** [space-wizards/space-station-14#5076]
## Description
Whenever you die, when examining yourself or someone else, it shows how long ago they died, but if you return to body while dead, the timer gets set back to 0.

**Screenshots**
![](https://cdn.discordapp.com/attachments/470226736219553794/903337511055671326/RLwhKaPuvT.gif)

**Comment by misnor** [comment]
The GhostSystem currently sets the TimeOfDeath via OnGhostStartup. Returning to your body and then becoming a ghost again is creating a new GhostComponent each time - thus the resetting.

Storing the TimeOfDeath closer to the player and populating the GhostComponent with it should fix this bug. Hardest part is deciding where to store that TimeSpan for storage when the GhostComponent needs it.

**Comment by ShadowCommander** [comment]
It should probably go in the `mind`, since that transfers to the ghost.
