### ISSUE TITLE
Can't select text inside LineEdit

### ISSUE THREAD

**Issue by DamianX** [space-wizards/space-station-14#509]
Needs to be implemented.
Should support but both Shift+Arrow keys and mouse selection.

**Comment by ShadowCommander** [comment]
Linking to the LineEdit issue on RobustToolbox space-wizards/RobustToolbox#748

**Comment by tentekal** [comment]
I'll try and take care of this too, I kinda know how chat works at this point.

**Comment by AJCM-git** [comment]
This needs to be closed
