### ISSUE TITLE
walking out into space is so cbt on a rotated station its not even funny

### ISSUE THREAD

**Issue by PaulRitter** [space-wizards/space-station-14#5091]
we did this to ourself

basically: since it rotates you immideatly, your controls switch so you often walk right back onto the station

**Comment by metalgearsloth** [comment]
Just get higher ping and it's way better, sinple.

Also https://github.com/space-wizards/space-station-14/issues/4593

**Comment by mirrorcult** [comment]
fixed a little bit by saphire's PR, still not great so leaving it open

**Comment by AJCM-git** [comment]
The only thing that's needed to close this is make the controls update to the new grid once you finish rotating. Currently, it changes them as soon as you touch the rotated grid, which ends up in confusion and pain
