### ISSUE TITLE
Deconstructing a disposal outlet destroys any items inside and eats your crowbar

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#5106]
## Description:

How to reproduce:

- Take some items and put them in a disposal outlet.
- Take a crowbar. Use it to begin deconstructing the disposal outlet.
- Your crowbar will disappear after the deconstruction is complete. Any items inside the outlet will be lost.

**Comment by Ephememory** [comment]
i try fix ok

**Comment by Zumorica** [comment]
Essentially, this just needs construction to empty the disposal container on destruction. I'd just add that container to the list of construction containers and call the "empty all containers" action on deconstruction

**Comment by Ephememory** [comment]
> Essentially, this just needs construction to empty the disposal container on destruction.

yup, had that intention but was expecting to need to do it in CS not yaml, np. also, it seems the crowbar just straight up gets deleted. tried VVing the container and it doesn't appear to be contained. guess it could be sucking it into the vent system really quickly? or are crowbars consumable now :confused:

**Comment by Ephememory** [comment]
cant fix

**Comment by TimrodDX** [comment]
> cant fix

Story of my life right there

**Comment by Ephememory** [comment]
i tried adding an ejectall action to the construction graph. changed nothing.
