### ISSUE TITLE
Need a way to kick open locked lockers from the inside

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#5110]

**Comment by PaulRitter** [comment]
why?

**Comment by metalgearsloth** [comment]
Probably better solved with suit sensors if a griefer is locking you in a locker without comms?

**Comment by PJB3005** [comment]
SS13 allows you to resist inside lockers to break out of them but it takes two minutes. I'd say that's a pretty fair compromise.

> why? doesnt it kinda defeat the point of the lock

New meta: security uses impenetrable closets instead of handcuffs.

**Comment by PaulRitter** [comment]
> 
> 
> SS13 allows you to resist inside lockers to break out of them but it takes two minutes. I'd say that's a pretty fair compromise.

agreed

**Comment by JustinTether** [comment]
Would this ideally be similar to how it works with resisting handcuffs? Not sure if it can just re-use the 'Resist' indicator for handcuffs and perform the same kind of operation or if we'd prefer to have it's own UI indicator

**Comment by PaulRitter** [comment]
Good question, no clue. Maybe have it trigger if the player tries to move?

**Comment by JustinTether** [comment]
Yea, you could make it automatically happen if you try to move, that way you don't have to mess with an indicator like you do with handcuffs. We don't have a standard 'resist' button so just doing it on player move might be the easiest
