### ISSUE TITLE
Substations do not unanchor/unwrench properly, remain attached to network until anchored elsewhere

### ISSUE THREAD

**Issue by 20kdc** [space-wizards/space-station-14#5116]
## Description
see title. tested on 1b8b5b5d1670658bb608daad918fc990d805b99c.

Just to clarify, it's not a visual bug with nodevis, this connection is fully usable and the involved APCs do not show signs of disconnection.

**Screenshots**
![image](https://user-images.githubusercontent.com/22304167/139601486-bd5646e0-f730-4e13-b278-a3bcd1b027f7.png)

**Comment by SweptWasTaken** [comment]
Happens with SMES' too.
