### ISSUE TITLE
You can put things into containers through walls.

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#5118]
## Description

How to reproduce:

- Find a wall where you know there's a container on the other side. This works with most potted plants, as well as the medkits inside Chemistry and the gold toolbox in the Vault. 
- Have an object in your hand and click on the other side of the wall.
- You'll hear the object go inside. 
- To test this visibly, you can find the sweet spot and drop a lit minibomb inside.

![image](https://user-images.githubusercontent.com/7907891/139614335-0823140f-6d94-485f-8352-2b162a471c72.png)

![Content Client_Hk6UPO1Jww](https://user-images.githubusercontent.com/7907891/139614339-5a4271fe-3c04-476a-b1c7-f12ad2bc695e.png)

**Comment by metalgearsloth** [comment]
These are all separate issues in that they never raycast to check because InteractUsing never does.

I think InteractUsing should just always raycast and provide it as a bool for subscribers to use, then any callers that care can just use that IMO.

**Comment by metalgearsloth** [comment]
Okay turns out https://github.com/space-wizards/space-station-14/blob/94579d18779e5d08eb5263cbdaa1901f3ed0089d/Content.Shared/Interaction/SharedInteractionSystem.cs#L159 is the real problem and that InteractUsing gets unobstructed checked higher up in the normal code path.
