### ISSUE TITLE
Please change the firelock's layer

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#5120]
![unknown](https://user-images.githubusercontent.com/43253663/139616640-39af88fa-f497-4f6d-b911-c02d340196b7.png)
It makes climbing onto tables harder and also blocks windoors, yes, there are windoors on that image

**Comment by metalgearsloth** [comment]
Do you mean drawdepth

**Comment by DogZeroX** [comment]
Yes.

**Comment by ElectroJr** [comment]
So I just started looking at the drawdepth stuff, and I'm quite confused. When VVing objects, many of the entities just don't seem to be at the draw depth that I assume they should be at. In the case of vents/scrubbers their current depth directly contradicts the existing comments (they should be -4, but are instead -6?).

Basically, looking at `Content.Shared.DrawDepth.DrawDepth.cs` (with some added comments):
```cs
public enum DrawDepth
{
    LowFloors = DrawDepthTag.Default - 7,
    /// <summary>
    /// Things that are beneath regular floors, such as wires.
    /// </summary>
    BelowFloor = DrawDepthTag.Default - 6, // <-- vents/scrubbers are here??
    FloorTiles = DrawDepthTag.Default - 5,  // <-- tables are here??
    /// <summary>
    /// Things that are actually right on the floor, like vents.
    /// </summary>
    FloorObjects = DrawDepthTag.Default - 4, // <-- windoors are here? shouldn't they be walls or higher? 
    Walls = DrawDepthTag.Default - 3, // <-- walls are here, where they should be
    WallTops = DrawDepthTag.Default - 2,
    WallMountedItems = DrawDepthTag.Default - 1,
    Objects = DrawDepthTag.Default,
    Items = DrawDepthTag.Default + 1,
    Mobs = DrawDepthTag.Default + 2, // <-- firelocks
    HighlightedItems = DrawDepthTag.Default + 3,
    Effects = DrawDepthTag.Default + 4,
    Ghosts = DrawDepthTag.Default + 5,
    Overlays = DrawDepthTag.Default + 6,
}
```

Is there a reason for this (i.e., are the comments & names just out of date)? If not, then more than just firelocks need have their drawdepth adjusted.

**Comment by metalgearsloth** [comment]
Some code adjusts drawdepth (e.g. interactionoutline brings it to top) and also not everything actually specifies its drawdepth.

A lot of this is likely "someone wanted this to be below X layer" e.g. windoors being below walls or tables being below floorobjects.
