### ISSUE TITLE
Power cells have no collision when thrown.

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#5137]
How to reproduce:

- Spawn in a power cell of any size and any type. Alternatively, remove the power cell from a device.
- Throw the power cell.
- In full gravity, it will go through walls. With no gravity (or if the station's moving) it will potentially go through the entire station.

**Screenshots**

![Content Client_yGCUThTslG](https://user-images.githubusercontent.com/7907891/140004698-6190aafe-9e88-432d-9f6e-31b8cdc140fd.png)

**Comment by AJCM-git** [comment]
fixed by #5199
