### ISSUE TITLE
Pulling doesn't know what newton's 3rd law is.

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#5139]
## Description
You can abuse pulling to recover from being spaced, as you can magically induce a force on what you're pulling using the Move Pulled Object action without any reaction force. In short: Pull a locker or something in space to be able to steer around like a ship if you know how.

**Comment by BasedUser** [comment]
demo
https://user-images.githubusercontent.com/21104932/140015318-4938b679-b439-4132-85be-346a472d8830.mp4

**Comment by metalgearsloth** [comment]
Should have a weightless check on either the puller or the pullable (or both?) and we should probably also look at a cooldown on the ctrl-rightclick behavior itself (maybe via do_after?)

**Comment by BasedUser** [comment]
More content, for after this gets removed
https://user-images.githubusercontent.com/21104932/140019384-e1cbdd75-31ee-4321-96e4-08eeeb066918.mp4

**Comment by 20kdc** [comment]
Primary problem I had with this was that setting up an AME while weightless is already painful, so I decided pulling had to work while weightless.
As it is, hint to a good solution may be in the title - apply an equal and opposite force to the player (puller) while weightless?

**Comment by BasedUser** [comment]
That's what Newton's third law *is*, @20kdc
