### ISSUE TITLE
Make Lights not shine while in a Container

### ISSUE THREAD

**Issue by ShadowCommander** [space-wizards/space-station-14#515]
Currently flashlights work while inside backpacks. The light shouldn't be visible while inside a backpack.

**Comment by DamianX** [comment]
In SS13 the light is visible if the item is in SOME containers such as pockets, hands, or equipped as an accessory on armor or helmet. I think it should be that way in SS14 as well.

**Comment by ShadowCommander** [comment]
Yeah. I forgot that inventory and hands count as containers due to it being a parenting check.

**Comment by Zumorica** [comment]
Fixed by #687
