### ISSUE TITLE
Gas canisters being busted open doesn't seem to work

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#5176]
## Description
They don't dump any gas at all, ruining the parade of a clever traitor who, say, uses an emitter to destroy the plasma canister inside atmos.

**Comment by Zumorica** [comment]
I knew adding that destruction behavior without coding the actual gas dumping behavior was a bad idea. But they didn't listen to me.

**Comment by mirrorcult** [comment]
dupe #4832
