### ISSUE TITLE
Allows admins to access the sandbox panel in all gamemodes

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#5185]
## Description

Basically the admin menu replicates a lot of the functionality of the sandbox menu for no reason. Instead of this admins should just be able to access the sandbox panel instead.

**Comment by Peptide90** [comment]
Has this been fixed with flags or is it still an issue / discussion?

Sandbox panel is nice for quick access to commands however everything in there should be in a unified admin panel imo.

**Comment by Peptide90** [comment]
Believe this is fixed now.
