### ISSUE TITLE
Character window rotation is broken

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#5189]
## Description

It looks like it might be pulling rotation from the middle of your screen? I'm not *exactly* sure why there's a copy of yourself in the character window anyway since you have your character right in front of you.

**Screenshots**

![2021-11-06_14-46-01](https://user-images.githubusercontent.com/49448379/140624741-5f33a2e3-dccc-42b1-8fae-65bc5bf71839.gif)

**Comment by AzzyIsNotHere** [comment]
I've replicated this, it appears to be based on the station's orientation. Seems relatively minor to fix, I'll take this one
