### ISSUE TITLE
Deleting the gravity generator doesn't disable gravity

### ISSUE THREAD

**Issue by AJCM-git** [space-wizards/space-station-14#5198]
## Description
1. Delete the gravity generator with the entity spawner eraser
2. Gravity will remain on

**Comment by thevinter** [comment]
It looks to me like the [Gravity System](https://github.com/space-wizards/space-station-14/blob/master/Content.Server/Gravity/EntitySystems/GravitySystem.cs) doesn't actively check for Gravity Generators and no events get emitted when the Gravity Generator gets destroyed.

**Comment by mirrorcult** [comment]
gravity generator system should hook into when the component is deleted and disable gravity on the grid accordingly
