### ISSUE TITLE
Need a component for explosions to not affect tiles above certain entities

### ISSUE THREAD

**Issue by AJCM-git** [space-wizards/space-station-14#5200]
## Description
The component should specify the following things
1. Priority, so for example we know to run the entity logic before the floortiles logic
2. Whether to further go down the tile, example (walls -(if destroyed)> flooring), maybe also how much to reduce explosion intensity by
3. Explosion behavior, my idea would be to merge this into the explosionact interface (and possibly merge points 2 & 3 together, not sure if it's a good idea tho(probably is))

**Additional context**
Supersedes #2979

**Comment by ShadowCommander** [comment]
Acruid was working on anchor bitflags to solve some of this. I'm not sure what the status is on that though.

**Comment by AJCM-git** [comment]
This is very outdated
