### ISSUE TITLE
do_after gets cancelled when hurt

### ISSUE THREAD

**Issue by AJCM-git** [space-wizards/space-station-14#5203]

**Comment by mirrorcult** [comment]
this is intentional?

**Comment by Zumorica** [comment]
yeah, the coder defining the DoAfter can decide if it will be cancelled if the user is hurt. This is not an issue.

**Comment by ElectroJr** [comment]
I do still think there is an issue here that needs to be fixed, it maybe just needs a better description. There should be some way for do after to treat different sources of damage differently. Or maybe combat should just have some way of interrupting do-afters without relying on damage.

For example. you should be able to try break out of handcuffs while suffocating or starving, but it should be interrupted when someone punches you. Currently you can't do that. Similarly, you should be able to vault tables to try escape out of a low-pressure room, but can't.
