### ISSUE TITLE
Returning to body as a ghost resets Boo cooldown.

### ISSUE THREAD

**Issue by pointer-to-null** [space-wizards/space-station-14#5207]
1. Do Boo
2. Return to body
3. Exit the body
4. Do Boo again

Realy spooky.

**Comment by jessicamaybe** [comment]
Example of bug being reproduced:

https://user-images.githubusercontent.com/31836813/170586549-2826bb3e-363c-423a-ad01-e670ee32af55.mp4

**Comment by deltanedas** [comment]
this was fixed a week ago, someone close

**Comment by DrSmugleaf** [comment]
Fixed by https://github.com/space-wizards/space-station-14/pull/12936
