### ISSUE TITLE
Infinite cuffing glitch

### ISSUE THREAD

**Issue by AzzyIsNotHere** [space-wizards/space-station-14#5214]
## Description
If you put two pairs of handcuffs on a person at the same time, that person can have at least nine total pairs of handcuffs added to them from that point forwards. After the first two cuffs are put on, the character's sprite appears to have two handcuffs on. Once you go higher than that, their sprite is covered by an error. I'm convinced being able to add even two cuffs is a bug, as if you attempt to cuff an already-cuffed person normally, it states something about their hands being full.

An interesting thing to note: The amount of "hands" the person is considered as having goes up with each subsequent handcuffing.
Steps to replicate:

1. At the same time, have you and another person attempt to handcuff a third person.
2. Add as many cuffs as you want to that person.

**Screenshots**
![nfrehiOGyQ](https://user-images.githubusercontent.com/29222142/140687062-57748bb3-839f-4582-8caa-c49d1a300185.png)
![SS14 Loader_JgxP2Fh8ZW](https://user-images.githubusercontent.com/29222142/140687080-24b31a1f-ce37-4e2d-87da-b0850596b260.png)
![SS14 Loader_42gf4i4qvD](https://user-images.githubusercontent.com/29222142/140687129-0d031a05-a2da-4f94-a540-93dade255c22.png)

**Additional context**
Nothing to add here, but I'll update this if I learn more

**Comment by PaulRitter** [comment]
what bodysystem does to a mf
