### ISSUE TITLE
Make vaulting and other do_afters not cancel when you take damage

### ISSUE THREAD

**Issue by AJCM-git** [space-wizards/space-station-14#5224]
## Description
There should be some way for do after to treat different sources of damage differently. Or maybe combat should just have some way of interrupting do_afters without relying on damage.
For example. You should be able to try to break out of handcuffs while suffocating or starving, but it should be interrupted when someone punches you. Similarly, you should be able to vault tables to try to escape out of a low-pressure room.

**Additional context**
Based on https://github.com/space-wizards/space-station-14/issues/5203#issuecomment-962775679

**Comment by mirrorcult** [comment]
theres a bool for TryChangeDamage calls to ignore resistances, can probably use something similar to block doafters/not block doafters

**Comment by ElectroJr** [comment]
closed by #5459
certain damage types should no longer interrupt do-afters
