### ISSUE TITLE
Items with their own GUI (Instruments, Air Tanks) can be used after being placed into a pneumatic cannon.

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#5237]
## Description

This was originally reported by Raven#1990 on Discord. I have verified it on a local environment updated to master as of around 12:30 AM on 11/09/2021, and subsequently wish I hadn't.

How to reproduce:

- Get instruments and a couple of pneumatic cannons.
- Start playing a MIDI on one of the instruments. Leave the interface open (or just set it to loop).
- Put the instrument into the pneumatic cannon (thankfully, only one will fit).
- Put the pneumatic cannon into the trash bag.
- Repeat until you've got All Star by Smash Mouth playing 8 times on loop, because that's about the limit of human sanity.
- Question your life choices.

https://www.youtube.com/watch?v=K6E8E6yUQgM

This also works if you do the following:

- Get a breath mask, two oxygen tanks (one large) and a pneumatic cannon.
- Put the large oxygen tank on the cannon, wear the breath mask.
- Toggle your internals on using the small tank and put it in the pneumatic cannon.
- Fire the small tank from the cannon.
- You'll still be breathing from the air tank. 

**Screenshots**

![image](https://user-images.githubusercontent.com/7907891/140943504-31878ac9-8837-4d20-8394-7cb21d00a346.png)

![image](https://user-images.githubusercontent.com/7907891/140943586-1f77a79c-d162-4b77-940e-ebdcffff3d4d.png)

**Comment by lzk228** [comment]
fixed 

https://github.com/space-wizards/space-station-14/assets/124214523/916b4e9c-b536-45b5-88fb-57494ebe6ddf
