### ISSUE TITLE
inserting instruments into containers makes them not realize they've been let go of

### ISSUE THREAD

**Issue by PaulRitter** [space-wizards/space-station-14#5258]
from ga#8181 on discord:
i can take a acoustic guitar, start to play some midi file, put it into microwave and it continues play! Then i can start microwave and it will give me playing guitar back. I can grab it with CTRL and walk with music 😄

this works with any musical instrument
you dont need to cook, only ejecting works too

**Comment by moonheart08** [comment]
I would've called this "Microwaving instruments allows you to play them remotely", but this works too.

**Comment by mirrorcult** [comment]
underlying issue here is that InstrumentComponent uses a bunch of random interfaces like IDropped and IThrown to determine that it left someone's instead of just using `UnequippedHandEvent`

**Comment by 20kdc** [comment]
preparing a fix now as part of https://github.com/space-wizards/space-station-14/pull/5184 now I know what event to look for

**Comment by 20kdc** [comment]
so apparently, my attempted fix would work, but microwaves bypass `UnequippedHandEvent`.
