### ISSUE TITLE
Ctrl+rightclick on drag creates some weird stuff

### ISSUE THREAD

**Issue by Mith-randalf** [space-wizards/space-station-14#5263]
## Description
Videos attached, I think most of it just looks janky but might have weird mechanical implications?

https://user-images.githubusercontent.com/84274729/141221060-4d7becc5-f041-4b8c-abe2-019541a421b4.mp4

https://user-images.githubusercontent.com/84274729/141221090-0435e117-e1fe-4a69-813a-969c75e79143.mp4

https://user-images.githubusercontent.com/84274729/141221126-924a5ae1-1ea9-43ee-aa31-4cb461f77da4.mp4

in the top two im actively using ctrl+rightclick to move stuff, the last one im just trying to move towards the tile im dragging

I couldnt find a plate, but you can accelerate them to super speeds with it too

**Comment by mirrorcult** [comment]
it doesnt really have this behavior anymore
