### ISSUE TITLE
Atmos doesn't properly pressurize underneath airlocks.

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#5266]
## Description

I don't know exactly what steps are needed to reproduce this, but I can show an area where it always happens.

![image](https://user-images.githubusercontent.com/7907891/141234244-adc36463-c4bb-4e90-9aef-9e11107a621e.png)

The dirty tile room will never properly pressurize unless the doors to the hallway are held open for a while, at which point the atmos will stabilize.

**Comment by TimrodDX** [comment]
[packedstationpiped.zip](https://github.com/space-wizards/space-station-14/files/7517629/packedstationpiped.zip)

If you'd like to test it yourself, the map file is here.

**Comment by 20kdc** [comment]
um... I have a question
+ if the doors are closed and it has no vents, how is air supposed to get in in the first place?
+ Have you tried `fixgridatmos`?

**Comment by 20kdc** [comment]
Ok, so you've mentioned on the discord that you did try fixgridatmos
new question - what does `showatmos` show for these areas?

**Comment by TimrodDX** [comment]
![image](https://user-images.githubusercontent.com/7907891/141305828-b6cd003f-0514-42ba-8daf-88bfbc265101.png)

I think I figured out what it is. When loading Packed to take that screenshot, I walked through a bunch of hallway airlocks and kept taking barotrauma damage the first time I walked through them. These were rooms that did have vents in them.

**Comment by Zumorica** [comment]
Fixed by 1b01247c5f23fc29bc1ed89830db8d171489b39d
