### ISSUE TITLE
Re-add exosuit slot

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#5272]
Literally unplayable, can't equip big oxygen tanks with the hardsuit.

**Comment by Peptide90** [comment]
Related PR if anyone wants to see how to readd the slot #1975

We need it to only show up and or be usable when an exosuit is equipped (hardsuit). Maybe look at what stops you equipping a PDA without a jumpsuit (probably inventory refactor involved).

**Comment by juliangiebel** [comment]
The suit slot is back in. This can be closed now
