### ISSUE TITLE
Implement more player preference customization options

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/space-station-14#528]
~~* Skin tones~~
* Eye color
* Underwear
* Backpack type (satchel or not).

**Comment by DamianX** [comment]
Skin tones require us to decide which human sprites we're gonna use for good. TG uses completely different body sprites for skin tones, while other servers like /vg/ simply apply the color to a base sprite. Not sure what Eris does.

**Comment by PJB3005** [comment]
I already switched us over to TG body sprites, actually. Eris/Bay wasn't happening because you need explicit separate female variants and they're harder to sprite for.

**Comment by EmoGarbage404** [comment]
these are all done (minus undies because we don't have them)
