### ISSUE TITLE
PackedStation: Chef and Botanist don't have access to their own areas, Bartender does.

### ISSUE THREAD

**Issue by Streaky-Haddock** [space-wizards/space-station-14#5285]
## Description
Bartender has access to the Kitchen, Hydroponics Lab and Freezer. However the Chef doesn't have access to the Hydroponics Lab or Kitchen.
So Anybody can access Kitchen and Hydroponics from the main corridors. This doens't impede the Botanist much, but the Chef has to repeatedly go the long way around in order to do anything.

**Screenshots**
![image](https://user-images.githubusercontent.com/93771043/141454444-9f7bd1ab-afdf-40a8-b3ac-b7e3e9b9bebb.png)

**Additional context**
TBH Given how Kitchen functions, i'd rather if Botanist, Bartender and Chef all shared the same Id accesses so they could cover eachother's jobs but I know that's not ideal for antagging and secret spaces.

**Comment by Elijahrane** [comment]
Redid this area in https://github.com/space-wizards/space-station-14/pull/5707
