### ISSUE TITLE
No Job Management for admins

### ISSUE THREAD

**Issue by Streaky-Haddock** [space-wizards/space-station-14#5294]
## Description
At the moment Admins can't job ban, open up new/close filled job slots for late-joiners nor are there any time requirements for roles.
**What I encounter frequently**:

-  First Timers join as command/sec they are either very new and don't know basic fundamentals, and haven't even read server rules. Time Requirements would fix this issue.
- People join as a Command Role, or are Assigned Command Role and they disconnect very soon after without informing admins. I would like to job-ban these people.
- People who DO Ahelp like they're supposed to, I can't do anything for. I can't open up a new latejoin slot or respawn them after they DC. What often happens is command goes AFK and can't be replaced en masse or are completely new. or both. One of them is also often an antagonist. So frequently rounds go without command at all.

**Screenshots**

**Additional context**

I'm just filing this to make it known that these tools and mechanisms would be very helpful to solve a frequently occurring issue right now. However, I can deal without this for the time being. There are just some people who... i don't want to ban... but I also don't want to see as Captain or HoS any time soon.

**Comment by ike709** [comment]
Job bans are in: https://github.com/space-wizards/space-station-14/pull/6703

**Comment by moonheart08** [comment]
You can manipulate job slots with `liststations`, `liststationjobs` and `adjstationjob`

**Comment by ike709** [comment]
Seems like everything in this issue has been addressed except playtime tracking, which is already noted in other issues.

**Comment by Pangogie** [comment]
> Seems like everything in this issue has been addressed except playtime tracking, which is already noted in other issues.

plz sir, can I have some playtime tracking?

**Comment by Streaky-Haddock** [comment]
Everything I requested here is implemented, including (I think) the ability to adjust role timers and department ban. Closing.
