### ISSUE TITLE
Framerate at the center of Packed is significantly worse than saltern.

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#5298]
## Description
I've had to turn on low-res viewport and lower lighting quality to Low, something that wasn't necessary before. Not sure what could be causing this, unless Toolbox is rendering more things than it should be.

**Comment by metalgearsloth** [comment]
Can't replicate, also not sure on the position as 0,0 is the west side so I just guessed but my fps was 80 to 150

**Comment by moonheart08** [comment]
> 
> 
> Can't replicate, also not sure on the position as 0,0 is the west side so I just guessed but my fps was 80 to 150

Bar area.

**Comment by AJCM-git** [comment]
This is part of a larger issue in client performance and cant reproduce currently.
