### ISSUE TITLE
Admin overlays hold a party around 0,0

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#5302]
## Description
![image](https://user-images.githubusercontent.com/7806367/141505563-de5b6649-9bf5-474d-9f0b-6bf01d72cb10.png)

**Comment by moonheart08** [comment]
By sheer chance this round spawned saltern close to 0,0 and i noticed.

**Comment by AJCM-git** [comment]
Havent seen this reported in a long while and cant repro locally.
