### ISSUE TITLE
On Packed, vending machines talk too much when you are dead

### ISSUE THREAD

**Issue by xRiriq** [space-wizards/space-station-14#5312]
## Description

I think there's just so many vending machines on packed it spams the chat.
**Screenshots**

![image](https://user-images.githubusercontent.com/94037592/141582019-ad220c5c-703e-4afb-8081-1f3e2807c731.png)

**Additional context**

**Comment by metalgearsloth** [comment]
These should probably be popups or the likes so they don't show up in local at all.
