### ISSUE TITLE
Server Info during Lobby/Ready screen probably should tell you what map

### ISSUE THREAD

**Issue by xRiriq** [space-wizards/space-station-14#5313]
## Description

**Screenshots**

![image](https://user-images.githubusercontent.com/94037592/141587642-2317accb-0736-46c1-b63c-32cadf9ea2e8.png)

**Additional context**

**Comment by SweptWasTaken** [comment]
I don't think there's any easy way to get the current name of the map from the server.

**Comment by mirrorcult** [comment]
there is now with game map prototypes

**Comment by Zumorica** [comment]
Fixed by #5849
