### ISSUE TITLE
Packed has a weird science door in medical?

### ISSUE THREAD

**Issue by xRiriq** [space-wizards/space-station-14#5315]
## Description

See screenshot, it blocks off the other two analyzers for no apparent reason.
**Screenshots**

![image](https://user-images.githubusercontent.com/94037592/141599184-d694689f-eea4-4eb6-acdd-705a2ea4f5f9.png)

**Additional context**

**Comment by TimrodDX** [comment]
This is because that room is intended to be Genetics, which is considered a part of Science. Normally, the RD would access that through the little room in maint right next to it, but because there's no dual sci/med maint doors yet it's blocked off to him.

**Comment by xRiriq** [comment]
Ah ok. This makes sense then.

**Comment by xRiriq** [comment]
@TimrodDX, I added a mixed authorization dual sci/med door for both the main type of airlock and the maintenance door on the other side. I went into more details in #5342.
