### ISSUE TITLE
Define basic starting gear for all jobs.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/space-station-14#532]
Right now only a few select jobs have starting gear set. Others are falling back to assistant.

Somebody should fill these in with various bits of clothing we have defined. If necessary we should probably import more clothing items to fill the gaps.

**Comment by PKPenguin321** [comment]
This file seems to be a good example on how to tackle this: https://github.com/space-wizards/space-station-14/blob/master/Resources/Prototypes/Jobs/Civilian/Assistant.yml

You'd want to do this for every job under [this folder](https://github.com/space-wizards/space-station-14/tree/master/Resources/Prototypes/Jobs), for example [the HoS who currently has AssistantGear as his startingGear.](https://github.com/space-wizards/space-station-14/blob/master/Resources/Prototypes/Jobs/Security/HeadOfSecurity.yml#L6)

May look into it more when I have more time.

**Comment by ike709** [comment]
I'm working on this.
