### ISSUE TITLE
Firelocks should respond to fires

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#5320]
## Description

![image](https://user-images.githubusercontent.com/7907891/141652304-575e90a2-2f2c-434e-8cc0-884021e26b7e.png)

One thing I've noticed now that I've mapped in firelocks on packed (and will probably map in more) is that they'd totally stop most single-canister plasma floods if they actually responded when there's a fire. In the above screenshot, someone lit a plasma fire that ordinarily would've been stopped by the firelocks immediately above it.

**Comment by harry3124** [comment]
If I recall, fire locks responds to the fire alarm, which said fire alarm responds from the fire and a trigger of someone else. Not directly from fire locks to fire.
