### ISSUE TITLE
Airlock Boards cannot have their accesses programmed

### ISSUE THREAD

**Issue by Streaky-Haddock** [space-wizards/space-station-14#5353]
## Description
An assistant with a screwdriver, welding tool, crowbar and wirecutters can permanently turn any secure airlock or windoor into  a generic all-access airlock.

Step 1) Follow the Deconstruction Guidelines laid out in the Construction Menu
Step 2) Reinsert the door electronics
Step 3) You now have a generic green airlock

Issue: Door Airlock electronic boards cannot be reprogrammed and do not store their old access restrictions. So I'm actually seeing some people who are not antag just turning the HoP door into all-access, or making security/brig all-access.  

**Screenshots**
![image](https://user-images.githubusercontent.com/93771043/141793022-d57a8d85-be79-47cb-96d9-cde330e80277.png)

**Additional context**

**Comment by mirrorcult** [comment]
they can now
