### ISSUE TITLE
Hardsuits protects when they are in your pocket

### ISSUE THREAD

**Issue by DummeHytteOst** [space-wizards/space-station-14#5357]
Putting a hardsuit helmet or hardsuit suit in your pockets will protect you from pressure

![20211115165401_1](https://user-images.githubusercontent.com/94384139/141812774-68910b19-8df1-4fd7-8d65-4d6fb388bc72.jpg)

This might also be the case with something like the ballistic vest and any other types of armor, but i have not tested that as i don't know how to test it.

**Comment by mirrorcult** [comment]
i kind of assumed you wouldn't be able to put armor in your pockets, why on earth do they fit

**Comment by xRiriq** [comment]
also you probably shouldn't be able to put hardsuits in outerclothing pockets like cmo lab coat
