### ISSUE TITLE
Wall Fixture Optimization

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#5358]
## Description
Packed and Saltern both have well over 1000 walls, resulting in 1000+ physics fixtures, many of which are trivially reducible (merging rows/columns of walls into one fixture)
Probably worth doing this at some point for physics gains.
This would complicate handling damage, though.

**Comment by metalgearsloth** [comment]
Dupe https://github.com/space-wizards/RobustToolbox/issues/1882
