### ISSUE TITLE
Starting Location of Player Character is NaN

### ISSUE THREAD

**Issue by clusterfack** [space-wizards/space-station-14#536]
Specifically the location of the initial character has a proper map and grid of 2 and 4, but it's position is a vector2 of NaN, NaN

**Comment by Acruid** [comment]
How do you reproduce this bug. The F3 location menu properly displays 0,0 as the initial location of the player.

**Comment by clusterfack** [comment]
Its been a few months but IIRC, spawn in and try to fire a laser. The effect wont appear after firing until you move first because NaN is passed to it.

**Comment by Acruid** [comment]
I spawned in, spawned myself a laser gun, equipped the gun and fired. The laser works perfectly fine. I am going to assume the bug is fixed and close this issue. If someone can actually reproduce it feel free to re-open this issue.
