### ISSUE TITLE
Need supporting code for planets

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#5369]
## Description
Will SS14 have them? No.
Should we provide the basics (like making sure you can set it up so space is impossible)? Yes.
Needed functionality:
- [ ] Better way of describing the relationship between tile types. Maybe it's time to bite the bullet and keep track of what is *under* things.
As is, having dirt instead of space under something requires massive amounts of duplication and messy logic.
- [ ] Adjust RCD and explosions to account for "ground" tiles that cannot be destroyed.
- [ ] Tool for automated conversion of maps, so that accidentally making some tiles have space underneath isn't a pain in the ass.

**Comment by metalgearsloth** [comment]
Here's my list of what would be required:

- [ ] Ground parallax
- [ ] Weightless / gravity support on maps (trivial)
- [ ] Ability to serialize maps to files. This is for planetmos + parallax to get saved. This should be a fairly simple engine change I would imagine.
- [ ] Turn grids on planets into static bodies (at least for now).
- [ ] Lighting, even just ambient lighting for the entire screen.
- [ ] Support for gridcomponent on maps so they can have tiles that can be updated at runtime.
- [ ] Clientside decals for grass or whatever, + procgen foliage

**Comment by UbaserB** [comment]
Uh, planets exist now so this can be closed lol.

**Comment by EmoGarbage404** [comment]
> Uh, planets exist now so this can be closed lol.

Most of these arent done so this issue should remain.

**Comment by UbaserB** [comment]
> > Uh, planets exist now so this can be closed lol.
> 
> Most of these arent done so this issue should remain.

Really?

**Comment by deltanedas** [comment]
> Will SS14 have them? No.

:trollface:

**Comment by mirrorcult** [comment]
> ## Description
> 
> Will SS14 have them? No.

hehe

this is mostly done just needs planet lighting which has separte issue and also is kind of engine
