### ISSUE TITLE
Suggestions for shuttles/battleships/ship construction

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#5382]
- [ ] A more ship-like wall, with extra protection from projectiles. Windows too. (I'm sure eris has those)
- [x] A radar to identify other ships, stations, showing where the docking ports are when close.
- [ ] A shield generator that mitigates damage
- [x] A small gravity generator
-  Ship weaponry:
- [ ] Some sort of fixated cannons that cannot be rotated. (Does it deal more damage?)
- [ ] Mounted turrets, can rotate and aim, can either use ballistic or laser
- [ ] Missiles?
- [ ] Some sort of oxygen generator?

**Comment by metalgearsloth** [comment]
ideaguys? on my github?

**Comment by Peptide90** [comment]
2 can be done when moonys mass scanner is ported.
4 is pretty easy to do so I can probably take a look at that at some point.

**Comment by mirrorcult** [comment]
small gravgen already exists on outer-rim, can probably port that

**Comment by Peptide90** [comment]
> small gravgen already exists on outer-rim, can probably port that

I was just about to edit my comment, I realise it's easily done but if it's been done can port. But it presumably just applies gravity to the grid so what's to stop it being built on the main station as a powergamey backup gen? Maybe if it had AoE on grids that could work and just set this one real small? Out of my scope then.

**Comment by moonheart08** [comment]
> small gravgen already exists on outer-rim, can probably port that

Well it needs it's own sprite.
