### ISSUE TITLE
Got to add suit sensors and health status monitor

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#5384]
Makes medical more useful.

**Comment by Macoron** [comment]
I would like to assign myself to this one. Sounds relatively easy.

**Comment by Willhelm53** [comment]
Related to #1614. I believe we have suit sensors now since this issue was made. Is "Health status monitor" just the one that anyone can step on to see their own damage? Might try for that as part of #1614 but we'll see.

**Comment by Willhelm53** [comment]
#5521 is the PR, and if you just meant the crew monitoring console, then this issue could be closed. It was indeed merged since this issue was created.
