### ISSUE TITLE
Weapon effects are all kindsa wrong on rotated stations

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#5387]
## Description

![image](https://user-images.githubusercontent.com/19853115/142369824-95e10ad5-0fd8-4f68-961c-b55af565de78.png)

wrong direction and wrong rotation

**Comment by Streaky-Haddock** [comment]
Lasers have it pretty bad. I tried to upload the video but it's too large. Search "Lasern't" on discord, CrudeWax has posted some video of lasers attack rotation.
