### ISSUE TITLE
BRAINS CAN TALK AGAIN

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#5397]
## Description
FUCK
Get gibbed, Return To Body, profit

**Screenshots**
![image](https://user-images.githubusercontent.com/7806367/142520493-0110fe7d-6d51-45ff-9be4-2e7e1a331e64.png)
![image](https://user-images.githubusercontent.com/7806367/142520540-ff868352-e4be-4081-940e-31e1eccdf74b.png)

**Comment by ElectroJr** [comment]
Seems to have been fixed again. Though they can still click to rotate.
