### ISSUE TITLE
Atmos pumps can't be turned off in mapping mode.

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#5399]
## Description

How to replicate:

- Be in mapping mode.
- Map in some atmos pumps. 
- Go into VV and disable them, making sure to save.
- The pumps will still be on when you load the map in normal gameplay.

This is kind of a problem because it means that Atmos will be pumping small amounts of plasma/CO2/N2O by default.

**Comment by UbaserB** [comment]
This issue should be closed, pumps are off by default.
