### ISSUE TITLE
Edge firelocks under doors cause them to get stuck open.

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#5400]
## Description

How to replicate:

- Be in mapping mode
- Map an edge firelock under any standard door. This is more noticeable with doors that start locked (such as command airlocks).
- The door will ignore access (at least, it did for me) and open, then get stuck open.

Expected behavior is that the door won't get stuck open unless the firelock is up.

**Comment by EmoGarbage404** [comment]
this is no longer the case
