### ISSUE TITLE
centcomm and server announcements are timid

### ISSUE THREAD

**Issue by Streaky-Haddock** [space-wizards/space-station-14#5405]
## Description
Admin Announcements delivered ICly or OOCly (Centcomm and Server announcements respectively) have no audio queues and routinely go ignored or unseen. Having a special centcomm voice line (like in SS13) for Admin Centcomm announcements and some audio cue for the server announcements would help a lot.

**Comment by PJB3005** [comment]
My original plan (when I was coding voting) was for these to drop down from the top center of the screen with some special popup. I decided to do voting different but there's the idea.
