### ISSUE TITLE
Flashlight toggle sound needs to be mono

### ISSUE THREAD

**Issue by xRiriq** [space-wizards/space-station-14#5417]
## Description

1. spawn seclite
2. click click click

Warning reads:
[WARN] clyde.oal: Attempting to set position on audio source with multiple audio channels! Stream: '/Audio/Items/flashlight_off.ogg'

**Screenshots**

**Additional context**

**Comment by metalgearsloth** [comment]
Fixed in https://github.com/space-wizards/space-station-14/commit/c5ba483be5a37db10424bc384f3ea67ac11f3e00
