### ISSUE TITLE
Using pick up verb on items on your inventory will cause them to show in both slots

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#542]
Steps to replicate:
1. Equip an item (such as an ID, backpack, etc.)
2. Use the pick up verb on that item
3. Now the item shows in both slots

![bug](https://user-images.githubusercontent.com/6766154/72926879-7a348c00-3d55-11ea-8188-3f892531e69c.png)

**Comment by ShadowCommander** [comment]
Fixed by removing Pick Up verb from items in containers. #567
