### ISSUE TITLE
Wires, pipes, and disposals need drawdepth fixes

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#5434]
## Description
They can never agree on if they go above or below each-other, so it's probably best to force the matter as so:
LV & MV > Pipes > HV > Disposals

Maybe also adjust MV's sprite to be offset like LV is.

**Comment by vulppine** [comment]
i attempted to solve this in #5420 for t-ray scanner visuals only, but just having it be forced would be much more simpler than the draw depth ordering i have to do in that PR

**Comment by ElectroJr** [comment]
If you just want them to have consistent draw-depths for all the sub-floor entities, you could just add more draw-depth definitions to `Content.Shared/DrawDepth/DrawDepth.cs` and updating the yaml files. 

I have no idea if having "too many" draw depths will ever become an issue. To make it easier to insert draw depths in the future without reshuffling existing ones, maybe the draw-depths should not be consecutive integers but have gaps?

**Comment by metalgearsloth** [comment]
From memory the integer matters for interacting with overlays and ZIndices (though overlays drawing between draw depths may be reverted someday), but it has no bearing on sprite draw order outside of sorting (and more draw depths is better as it makes the sorting faster).
