### ISSUE TITLE
High-priority systems to ECS

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#5438]
## Description

These are some systems that should be prioritized heavily for conversion to ECS/refactoring, since they interface with lots of other things:
- [x] Alerts (#5559)
- [x] Actions (#6791)
- [x] Wires (#7699) 
- [x] Inventory (#5807) 
- [x] EntityStorage (#9291)
- [x] Hands (#7081)
- [x] Chat (#7337)
- [x] Item/Clothing (#9706)
- [x] Mind / Roles (https://github.com/space-wizards/space-station-14/pull/16826 and https://github.com/space-wizards/space-station-14/pull/19591)
- [x] Objectives (#19967)

There are probably more that I can't think of but those are big (actions alone is blocking a lot of stuff from potentially being done)

**Comment by Ygg01** [comment]
What about hands and containers. Aren't those last few bastions of EC code in content.

**Comment by ElectroJr** [comment]
Hands definitely need to be ECS-ed. 

>bastions of EC code in content.

Containers are currently in engine. Even if you move the logic in `ContainerManagerComponent`/`ContainerHelpers` into a system, for the most part I don't think it would significantly impact how systems use containers, so probably not as high priority as alerts, actions & hands?

**Comment by Ygg01** [comment]
`s/Container/Inventory/` or whatever still uses inheritance to share functionality.

**Comment by mirrorcult** [comment]
inventory and hands, yes. also entitystorage

**Comment by Ygg01** [comment]
@ElectroJr are hands partially ECSed? I saw #5634

**Comment by ElectroJr** [comment]
Well once/if its merged they will be 20% more ECS. There's still a lot of work to do, and hands code is still pretty scuffed. But hopefully that PR will at least reduce the workload for a future refactor.

In reality, that PR started because I wanted to change hands in order to get some basic interactions predicted. I just wanna pick up items w/o the awkward delay. In the process, I just ended up moving quite a few functions to the shared hands system & removing some component messages.

**Comment by Acruid** [comment]
Another high priority is to migrate everything that still uses Component Messages, and then Interface Events, in that order.

**Comment by DogZeroX** [comment]
Oldchat.

**Comment by Macoron** [comment]
I'm starting ECSing `EntityStorage`. Wish me luck.

**Comment by vulppine** [comment]
wires is done via #7699

**Comment by mirrorcult** [comment]
another one down #9291

**Comment by deltanedas** [comment]
@DrSmugleaf i was refactoring some objective condition stuff and got annoyed now i want to refactor it to be ecs
should i:
- make objectives entities, their ids listed on the mind component
- make objective conditions entities, their ids listed in the objective component
- both of them

currently i am focusing on conditions

**Comment by mirrorcult** [comment]
we did it reddit

**Comment by VasilisThePikachu** [comment]
![image](https://media.tenor.com/g16jQZqbvWoAAAAM/yippee-happy.gif)

**Comment by DogZeroX** [comment]
High-priority systems to FLECS now
