### ISSUE TITLE
Request to remove all my code from repo

### ISSUE THREAD

**Issue by GraniteSidewalk** [space-wizards/space-station-14#5442]
Hi! This is a formal request to remove all code I have made for ss14. This won't include things like basic bodysystem work that has been heavily modified since my pushes, but this will include many shaders and other work I have done, including engine work on graphics flow.
I can provide a list of all code I want to remove by looking at my commits. 
Thanks!

**Comment by LemonInTheDark** [comment]
Wew

**Comment by N3X15** [comment]
🍿

**Comment by PaulRitter** [comment]
Hi,
interesting choice to connect yet another account to your unacceptable and disturbing behaviour, but of course, i'm happy to oblige.

To cut it short: **No.**
Your code contributions are licensed under the MIT, which cannot be retroactively revoked.
This entirely depends upon our goodwill, and we don't have much left for you.
Why do we not have anymore goodwill, well, a short catchup for anyone reading this:

This person has been banned from our community three times, with us making the last one permanent: https://forum.spacestation14.io/index.php?/topic/77-ban-appeal/
An excerpt from the ban appeal above:
```
That being said, this is somewhat roughly pulled together what admins remember:
- History of being a conflictive person causing drama in the community (ex: the /vg/ hack threat incident, which got you banned before the ban was later lifted for some reason)
- History of blatant transphobia in the community, banned once for this and unbanned again without other admins being consulted.
- Compared pedophile rights to trans rights, went on to rabidly defend pedophile rights publicly in the server and didn't stop after being asked to, got banned for this and later unbanned without other admins being consulted.
```

After the ban, came back with an alarming number of alts to:
```
- let loose the average insecure transphobic bullshit: "you are all mentally ill", "you are on the verge of suicide", "they were triggered!!!" etc
- offer admins 5k to unban & admin him because "thats the amount of money where friendships break" (lmao, maybe yours)
- continue to larp about being a millionare. sure bud, we all heard it, you got money :P
```

All in all, read up on this:
```
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
```

**Comment by LemonInTheDark** [comment]
Bi-Daily reminder that contrib guidelines can be helpful sometimes. Implying anyone actually reads them but still
![image](https://user-images.githubusercontent.com/58055496/142828089-fb8677d4-7797-4bec-9226-345985e89e89.png)

**Comment by d3athrow** [comment]
lol

**Comment by ShiftyRail** [comment]
5k ? We didn't even get pocket change compared to that.

**Comment by mirrorcult** [comment]
i offered to take the 5k if he'd agree to donate it to charity but he just blocked me instead

**Comment by N3X15** [comment]
> Bi-Daily reminder that contrib guidelines can be helpful sometimes. Implying anyone actually reads them but still ![image](https://user-images.githubusercontent.com/58055496/142828089-fb8677d4-7797-4bec-9226-345985e89e89.png)

Should probably add them to CONTRIBUTING.md, PULL_REQUEST_TEMPLATE.md, or something so people are forced to read them.

**Comment by PaulRitter** [comment]
Sure, altough i doubt we'll get someone quite so disturbed again. Glass is unique, just not in a good way.

**Comment by N3X15** [comment]
> Sure, altough i doubt we'll get someone quite so disturbed again. Glass is unique, just not in a good way.

Trust me, there is no shortage in stupidity on this planet.

**Comment by PaulRitter** [comment]
i fear you might be correct

**Comment by Eneocho** [comment]
bababooey

**Comment by DeityLink** [comment]
You'll be glad to know that I've successfully removed most of your code from /vg/'s cult then 😌

**Comment by GraniteSidewalk** [comment]
Please. Do I need to remind how many times "nigger" was said in the server? Nigger was said hundreds, thousands of times by the very people who banned me. But transphobia is bad since, well, you're trans, and not black. I can go into /vg/station logs and get hundreds of instances of PJB being racist, if you want. This is a 4chan project, or should I say, was. Nobody is left from the original squad.

Unfortunately MIT license is a GPL-compatible license, which means users can indeed revoke their code. You are incorrect. I will be filing a DCMA takedown if this behavior is not rectified. This is not a matter of "good will", this is a legal issue.

**Comment by GraniteSidewalk** [comment]
> You'll be glad to know that I've successfully removed most of your code from /vg/'s cult then 😌

I don't recall every doing anything with /vg/ cult beyond trying to work with that abhorrent mess to add a couple of features, lol.

**Comment by Eneocho** [comment]
jesus christ man touch some grass, this is some unhealthy autism

**Comment by LemonInTheDark** [comment]
WEW

**Comment by PaulRitter** [comment]
> Please. Do I need to remind how many times "nigger" was said in the server? Nigger was said hundreds, thousands of times by the very people who banned me. But transphobia is bad since, well, you're trans, and not black. I can go into /vg/station logs and get hundreds of instances of PJB being racist, if you want. This is a 4chan project, or should I say, was. Nobody is left from the original squad.

luckily, people can admit their fault & change, just how pjb has done. I'll denounce racism as well as transphobia.
sidenote: I'm also not trans, not black. I'm probably the most average looking hetero white guy you'll meet, I'm simply not an asshole.

All in all, its quite simple, just dont be a dick.

as for your dmca takedown, glhf

**Comment by N3X15** [comment]
> Unfortunately MIT license is a GPL-compatible license, which means users can indeed revoke their code. You are incorrect. I will be filing a DCMA takedown if this behavior is not rectified. This is not a matter of "good will", this is a legal issue.

oh no I have defeated you by merely having a clone of the repository on my hard disk drive that I can then immediately reupload to any of a number of Russian-hosted gitlab servers

also counter-claims are a thing, if we're taking legal avenues

**Comment by GraniteSidewalk** [comment]
I urge you to read https://docs.github.com/en/github/site-policy/dmca-takedown-policy if you have any more desire to counteract my claims. You will have 14 days to submit a counter-filing to my DCMA claim, during which the github will be taken down entirely. After 14 days, the case will be reviewed and you may or may not win the case, at which point it will be taken down indefinitely until the offending material is removed.

And as a side note, PJB hasn't changed. He just needs you to devote every waking hour of your life to finish the project, just as he has. He still moderates and has collaborator access to /vg/station. He also plays on there sometimes. I can find recent racist material, if you want.

**Comment by GraniteSidewalk** [comment]
And surprising that you only say "PJB" has changed. You think he was the ONLY one being racist?

**Comment by N3X15** [comment]
> I urge you to read https://docs.github.com/en/github/site-policy/dmca-takedown-policy if you have any more desire to counteract my claims. You will have 14 days to submit a counter-filing to my DCMA claim, during which the github will be taken down entirely. After 14 days, the case will be reviewed and you may or may not win the case, at which point it will be taken down indefinitely until the offending material is removed.
> 
> And as a side note, PJB hasn't changed. He just needs you to devote every waking hour of your life to finish the project, just as he has. He still moderates and has collaborator access to /vg/station. He also plays on there sometimes. I can find recent racist material, if you want.

![image](https://user-images.githubusercontent.com/110073/142837247-2f55b9e8-df1d-4a42-97c1-45107fa3f2bb.png)

**Comment by PaulRitter** [comment]
> And as a side note, PJB hasn't changed. He just needs you to devote every waking hour of your life to finish the project, just as he has. He still moderates and has collaborator access to /vg/station. He also plays on there sometimes. I can find recent racist material, if you want.

glad to know you know the person I interact with on a daily basis, as well have interacted with while coding for vg.

> And surprising that you only say "PJB" has changed. You think he was the ONLY one being racist?

i haven't seen anyone at ss14 being racist or transphobic.

**Comment by GraniteSidewalk** [comment]
If you so wish to live in the shadows with ss14, that's fine. So long as copyrighted code is not on public display.

> i haven't seen anyone at ss14 being racist or transphobic.

You should learn about the thousands of instances of the word "nigger" being deleted from server history, then.

**Comment by Eneocho** [comment]
I find it fascinating that you jumped on the PJB being racist thing instead of the code, license or whatever. Kinda makes your DMCA threat have little weight.

**Comment by PaulRitter** [comment]
> If you so wish to live in the shadows with ss14, that's fine. So long as copyrighted code is not on public display.
> 
> > i haven't seen anyone at ss14 being racist or transphobic.
> 
> You should learn about the thousands of instances of the word "nigger" being deleted from server history, then.

lmao there might be a reason we cleaned house... like... not supporting it?

**Comment by N3X15** [comment]
Should probably go ahead and lock this thread since he's just shitposting now.

**Comment by PaulRitter** [comment]
yep

**Comment by GraniteSidewalk** [comment]
Very well. I will file the DCMA.

**Comment by Zumorica** [comment]
DMCA yourself some bitches

**Comment by PaulRitter** [comment]
I'm done entertaining your bullshit, stop acting like a child and get help dude.

**Comment by DeityLink** [comment]
![image](https://user-images.githubusercontent.com/7573912/142838875-b75f01f3-12d3-46cd-903b-e966c5f29591.png)

**Comment by DrSmugleaf** [comment]
Mate I already had to replace most of your code here because it's absolute dogshit, what are you gonna DMCA, use the money on lawyers to learn coding instead please
