### ISSUE TITLE
Shuttle Consoles are not constructible, deconstructible or orderable

### ISSUE THREAD

**Issue by Streaky-Haddock** [space-wizards/space-station-14#5450]
## Description
Usually this results in people screwdrivering the shuttle console and breaking it permanently. However with the stealth addition of thrusters and gyroscopes into cargo, it might be worth making an issue just to check this isn't an oversight.

**Screenshots**
![image](https://user-images.githubusercontent.com/93771043/142861238-f3289db8-fa1b-436d-a215-d401781e8a6a.png)

**Additional context**

**Comment by Peptide90** [comment]
Closing for now. Ordering a whole shuttle seems OP when some salvages have a working shuttle computer and in future we will defer this to experisci.
