### ISSUE TITLE
Half of the thruster goes missing when you hoover over it 

### ISSUE THREAD

**Issue by SethLafuente** [space-wizards/space-station-14#5455]
## Description

Half of the thruster goes missing in all positions 
**Screenshots**
![image](https://user-images.githubusercontent.com/84478872/142913359-61809c50-2271-482d-88b2-b3d0b4861740.png)
![image](https://user-images.githubusercontent.com/84478872/142913409-93d2e9d3-d706-4f97-ab1b-a43b46fe4dea.png)

**Comment by metalgearsloth** [comment]
interaction outline shader needs update for layer position support.

**Comment by Efruit** [comment]
> Half of the thruster goes missing when you hoover over it 

It is not recommended to vacuum the thrusters.
