### ISSUE TITLE
Roundstart is 100% fucked.

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#5467]
## Description
![image](https://user-images.githubusercontent.com/7806367/142962854-574fd11e-4f8e-4e18-828c-d238a66e2992.png)

**Comment by metalgearsloth** [comment]
Works fine locally, need more info.

**Comment by moonheart08** [comment]
This is happening with full lobbies on production servers directly after a restart.

**Comment by Streaky-Haddock** [comment]
![image](https://user-images.githubusercontent.com/93771043/142996074-d3fce45a-11d4-425c-a0fc-4d57d35d6ab0.png)

**Comment by DrSmugleaf** [comment]
> Works fine locally, need more info.

This only happens with PostgreSQL.
