### ISSUE TITLE
Water smoke crash

### ISSUE THREAD

**Issue by BasedUser** [space-wizards/space-station-14#5483]
## Description
~~Step 1. Acquire a cryobeaker, two large beakers, a chemistry set (and multiple stomachs? see #Additional context).
Step 2. In the two large beakers, make >25u of fluorosurfactant acid and dispense 75u of water.
Step 3. Put 20 potassium, 19 phosphorus, 19 sugar into the cryobeaker.
Step 4. Drink some water, dump all the acid (25u pour amount) into the water beaker, switch to the cryobeaker, set pour amount to 5, and pour all of the contents of the cryobeaker into the now empty water beaker in quick succession.~~
Step 1. Acquire a cryobeaker with 30u of smoke mix, 15u hydrogen and 15u oxygen.
Step 2. Spam the hell out of it onto an empty beaker.

**Additional context**
This crash happened on Miros at 16:04 UTC. ~~I'm not entirely sure this was the cause of the server's crash, but it happened both times with this compound active and with at least two players being inside the cloud/foam hybrid.~~

**Comment by mirrorcult** [comment]
cause identified
![image](https://user-images.githubusercontent.com/19853115/143083710-a7968aec-13a0-470f-b21a-8aad4c89f49f.png)
