### ISSUE TITLE
Space Carp can go into critical, but it looks like they're dead

### ISSUE THREAD

**Issue by 20kdc** [space-wizards/space-station-14#5485]
## Description

See carp.yml: Critical state is at 50 damage, then they die at 100 damage, but visually there's no distinction.

**Screenshots**
From Delete#2526:
![image](https://user-images.githubusercontent.com/22304167/143076117-dc4071d6-4664-4b9c-9004-72b3bc352ebe.png)

**Comment by FoLoKe** [comment]
I can make bunch of "cross-eyes" sprites for animals dead state based on existing ones since they under CC BY-SA 3.0, or completely disable CritState for them (I don't think second one is a good idea)
