### ISSUE TITLE
Aghost can kill people with gun.

### ISSUE THREAD

**Issue by pointer-to-null** [space-wizards/space-station-14#5487]
## Description
If spawned via sandbox menu or admin menu.

This is part of broad issue where Aghost can pick up all items on the ground and use some of them.
Also, if Aghost picks up an item inside the client viewport, that client will crush. (Picking up items outside the viewport is fine)

**Screenshots**

https://user-images.githubusercontent.com/91910481/143085555-2eae0c43-9640-4e7c-97d6-42b8d279a0d1.mp4

**Additional context**

**Comment by DogZeroX** [comment]
That's really not an idea, like, that kind of the purpose, to use stuff.

**Comment by mirrorcult** [comment]
aghosts being able to pick up items is not an issue, aghost pickups being broken because of PVS is known
