### ISSUE TITLE
Heated (not superheated) air is not filtered

### ISSUE THREAD

**Issue by Streaky-Haddock** [space-wizards/space-station-14#5488]
## Description
Temperatures that can cause burn damage that do not involve water vapour or gas can result in unprotected players slowly roasting over and over and over again. The air is not filtered out by atmos and replaced by normal temperature air. 
To reproduce: 
Gas Leak Event, have someone light a welder. Vent the area and seal it. The vapour will be gone but the temperature may still be quite high. Fire Suits and Atmos Hardsuits will be fine, but as the temperature propagates throughout the station you may find freshly cloned bodies slowly roasting, and dead corpses gradually ticking 1-4 burn damage until they have 2,400 damage by round's end.

**Screenshots**

**Additional context**

**Comment by mirrorcult** [comment]
p[robably fixed by the air alarm PR
