### ISSUE TITLE
Sitting in a pilot chair 2 times crashes the client

### ISSUE THREAD

**Issue by AJCM-git** [space-wizards/space-station-14#550]
Steps to reproduce:
1. Place a pilot chair
2. Doble click on it to sit
3. Right click above the pilot chair > Unlock
4. Repeat step 2 and 3
5. Crash

Note: After sitting one time the chair name changes to the character name. My codelet theory is that the chair creates a new player entity above of it, and since two players cant coexist in the same place at the same time the client chimps out.
@Acruid

**Comment by PJB3005** [comment]
This same crash seems to happen by just aghosting a couple times.
