### ISSUE TITLE
Crash when launching local server with lobby enabled

### ISSUE THREAD

**Issue by Elijahrane** [space-wizards/space-station-14#5504]
## Description

`dotnet run --project Content.Server --cvar game.lobbyenabled=true`

Running the server on latest master will crash with some error related to admin logs. Please see the attached log.

**Output Log of Above Command**

[lobby.log](https://github.com/space-wizards/space-station-14/files/7596092/lobby.log)

**Comment by PJB3005** [comment]
@DrSmugleaf admin logging related
