### ISSUE TITLE
Define cargo crate prototypes

### ISSUE THREAD

**Issue by ShadowCommander** [space-wizards/space-station-14#553]
The CargoConsole doesn't have any crates currently, this needs to be fixed. Add crates and fill them with stuff.

**Comment by CC-4477** [comment]
Attempting to do this currently. I am follwoing /vg/'s page on crates: https://ss13.moe/wiki/index.php/Supply_Crates. Let me know if I should be using something else.

**Comment by ShadowCommander** [comment]
If no one else does it I'll get to implementing a StorageFill component later.
