### ISSUE TITLE
Chat redesign (classic BYOND chat)

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#5535]
## Description
As discussed on the September 19th meeting, we should add "wide chat" (or BYOND chat) as an option.
In the future, we can re-evaluate whether to make it the default or not.

**Screenshots**
Classic injazz mockup of what it _could_ look like, not necessarily how we should do it.
![image](https://user-images.githubusercontent.com/6766154/143565590-43b5fe64-1d54-418e-ae12-75ead7a6a188.png)

**Comment by Jezithyr** [comment]
Going to be taking a crack at this, I'm probably also going to end up needed to refactor the hud code while working on this too. Has there been a decision if oldchat will be default or not?
