### ISSUE TITLE
YAML base files rename

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#5540]
## Description
As discussed on the October 2nd meeting, we should rename all `base.yml` files to have descriptive names.
`base.yml` -> `base_xyz.yml`

**Comment by Peptide90** [comment]
Sign me up, I'll start it start of next week :)

**Comment by SweptWasTaken** [comment]
> Sign me up, I'll start it start of next week :)

You still doing this?

**Comment by Peptide90** [comment]
> > Sign me up, I'll start it start of next week :)
> 
> You still doing this?

Yeah will hop on this tomorrow. There weren't many examples I had found that didn't have a reasonable base ID but will go through all the entity bases.

**Comment by Peptide90** [comment]
I've just checked a large number of examples and they're currently a combination of xyzBase and BaseXyz and are fairly descriptive.

So just to be sure we're on the same page do we want to transition them all to the same format I.e Base_xyz.

For example "ClothingShoesBase" would become "Base_ClothingShoes" or is this really a non issue? Unless someone can point out an obvious non descriptive base.

**Comment by Zumorica** [comment]
@Peptide90 this issue is about YAML filenames, not prototype IDs

**Comment by Peptide90** [comment]
> @Peptide90 this issue is about YAML filenames, not prototype IDs

My bad, fair enough should be a quick fix then. I'll take a quick look.
