### ISSUE TITLE
Most commands need localization.

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#5543]
## Description
As discussed on the October 30th meeting, we should localize command messages.
Please note, this does NOT mean localizing command names. (e.g. a "help" command should still be "help" in a different locale than english)

**Comment by NootSponge** [comment]
How about we do something similar to prototypes and have it automatically get the localization for commands? 

This would probably require editing of the LocalizationManager to add some helper functions. Just might be easier to define if all the command locs are like `cmd-call-vote-desc` and have an attribute for `.help` or something.

I can work on this either way, just a thought.
