### ISSUE TITLE
Identity System

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#5545]
## Description
As discussed on the October 30th meeting, we should have some sort of Identity system for mobs.
This would handle obscuring the name, voice, face, etc... Also, chamaleon traitor items.
Essentially, we should stop using entity names for this to work. We could just pipe the entity through a system to get the string representation.

**Comment by mirrorcult** [comment]
going to try a very basic impl of this

**Comment by Willhelm53** [comment]
I'd hate to be a "scope creep 👴" but... #6296 maybe as part of this, if it's not out of your way? 🥺

**Comment by mirrorcult** [comment]
done
