### ISSUE TITLE
Examining Tooltip Improvements

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#5546]
## Description
As discussed on the November 13th meeting, the examining tooltip should be improved.
Some ideas:
- Hold shift to see name, click to see description
    - Hold shift for name + short description, click for long description
    - Short descriptions should make it obvious that a long description is available, i.e. having a "..." symbol/button etc.
- We gotta show characters equipment on examine
- Show armor values, such as how protective it is.
- Button in the tooltip that opens a close examination

**Comment by Acruid** [comment]
Another thing is that the error message reports the entity does not exist when it does exist but out of range.
![image](https://user-images.githubusercontent.com/1685952/145623164-dbb596fb-ccf6-4cab-aab3-b52670ae8f84.png)
This occurs when PVS fails or some other desync happens. The examine system should report that the entity is out of range. This generally won't be seen if the range check fails on the client, but our code isn't 100% deterministic so it is possible for this message to be visible.
