### ISSUE TITLE
Thruster sprite should be inverted

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#5578]
I ported it as is but realised its SpriteView is inverted. You'll also need to invert the stuff under ThrusterSystem too.

**Comment by Peptide90** [comment]
Sloth you beautiful human is this code related or do you just want the sprites inverted? Hovering over thruster also makes half the sprite disappear or is that related?

**Comment by metalgearsloth** [comment]
interactionoutline is a separate issue.

it will also need a minor code update when the sprites are inverted; all of it is in thrustersystem.

**Comment by metalgearsloth** [comment]
Since some context menu update I don't think this matters anymore.
