### ISSUE TITLE
popups move with the viewer

### ISSUE THREAD

**Issue by PaulRitter** [space-wizards/space-station-14#5585]
pictured: me moving as ghost and the person circled drinking
![grafik](https://user-images.githubusercontent.com/16618384/143720518-9f74d174-210a-41b4-9ac4-7e0e4f752583.png)
*slurp*

**Comment by metalgearsloth** [comment]
Do we have it stay at the same entitycoordinates or move with the entity that it generated on?

I think the former is probably better so you can still read it if someone's moving around.

**Comment by PaulRitter** [comment]
i'd say stay at the same entitycoordinates. iirc that used to be the behaviour too, something just cooked it

**Comment by moonheart08** [comment]
> i'd say stay at the same entitycoordinates. iirc that used to be the behaviour too, something just cooked it

This then needs to handle falling back correctly if the entity it's attached to goes caput.

**Comment by PaulRitter** [comment]
> > i'd say stay at the same entitycoordinates. iirc that used to be the behaviour too, something just cooked it
> 
> This then needs to handle falling back correctly if the entity it's attached to goes caput.

true, would need mapcoordinates as fallback

**Comment by Willhelm53** [comment]
Are we still experiencing this issue?

**Comment by PaulRitter** [comment]
p sure it is
