### ISSUE TITLE
Speech shouldn't invoke a console command

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#5586]
## Description
Right now it's impossible to use `"` in chat due to console commands being aware of quotes.

**Comment by Zumorica** [comment]
I don't see anything wrong with speech being a console command. If anything, we should allow escaping `"` in command arguments

**Comment by Peptide90** [comment]
I just came across this when trying to do ... in OOC and it defaulted back to local making me look questionable.
