### ISSUE TITLE
Traitors can get other traitors as kill objectives

### ISSUE THREAD

**Issue by aamonz** [space-wizards/space-station-14#5600]
## Description
Self explanatory.

**Screenshots**
![image](https://user-images.githubusercontent.com/92693280/143779202-cd78543e-859c-445b-918f-d3b41b4e3c1e.png)

**Comment by moonheart08** [comment]
This is an intended game mechanic. Other traitors are not your friends.

**Comment by PaulRitter** [comment]
intended
