### ISSUE TITLE
Sentinent monkeys can be cloned into humans.

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#5602]
## Description

How to replicate:

- Spawn a bunch of monkeys. I think they become ghost roles automatically on spawn, but I'm not sure on that.
- Wait for the monkeys to be inhabited by bored ghosts. 
- Take a sentient monkey to a medical scanner. They'll go into the scanner the same way a human does, and the entry in the cloner will read "monkey".
- Kill the monkey, then clone them. They will clone into whoever they were before they went ghost role. 
- Wonder if we're all just really sentient monkeys at heart.

**Comment by Veritius** [comment]
Even weirder: your character doesn't have to spawn in to get cloned into a monkey. If you get monkey-cloned without ever spawning your human character in the round, the game will just... use the character you had selected when you hit Observe.
