### ISSUE TITLE
Space doesnt cool

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#5605]
## Description

Venting an area to space only reduces its pressure, not temperature

Going into space doesn't make you take temperature damage, only pressure damage

**Comment by Zumorica** [comment]
Misleading title, space _is_ cold
![image](https://user-images.githubusercontent.com/6766154/143793023-6b64cb90-2546-4fb9-9c51-a64d518674d0.png)

**Comment by mirrorcult** [comment]
weird, when you go into space the cold alert doesn't show up, and space never cools down areas exposed to it

**Comment by Ygg01** [comment]
To be fair. Space is excellent insulation. Unless you emit radiation.

**Comment by mirrorcult** [comment]
game design-wise it should definitely be cold though
