### ISSUE TITLE
Machine frames not accepting chemmaster and chem dispenser circuit boards on Saltern

### ISSUE THREAD

**Issue by KRAMDARADMARK** [space-wizards/space-station-14#5637]
## Description

In the main large engineering room, against the window on the right side under the long supply table, I was trying to build my own ChemMaster/dispenser, and the circuit boards would not go in. They were anchored, and I tried to do any other step in the build process to no avail.

**Comment by PaulRitter** [comment]
@Zumorica

**Comment by Peptide90** [comment]
So process /should/ be
- Build machine frame
- Add 5 steel sheets
- Anchor
- Add cable
- Add board and parts
- Screwdriver?

Vera added a type:BuildMachine so can look at it later if they're busy see if it's anything I can do.

**Comment by Zumorica** [comment]
Can't replicate
