### ISSUE TITLE
Instruments just don't network

### ISSUE THREAD

**Issue by 20kdc** [space-wizards/space-station-14#5639]
## Description

Instruments are presently incapable of sending their played notes to other players.

Reproduction instructions:
1. Start two clients. Have the MIDI or Master volume on one of these clients at some low/zero volume to confirm which client the notes are playing on.
2. With both clients near a piano or other instrument, on the client with zero volume, play the instrument.
3. You won't hear anything.

**Comment by Zumorica** [comment]
Cannot reproduce on latest master.
