### ISSUE TITLE
AME is indestructible and people are using it as a cage.

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#5643]
## Description
powergamer's delight.
*sigh*

**Comment by Peptide90** [comment]
AME currently is damageable and destructible and has the damageset modifier metallic and damage trigger 100. Will do some testing to see what it takes to break it but IIRC metallic can't be broke with fists, as it should be.

Sec should be using the actual brig so I'd suggest reporting it if you're getting caged with no hope of escape.

**Comment by ShadowCommander** [comment]
If it's being used as a quick setup cage, then we can add a DoAfter delay to the setup from boxes.

**Comment by Peptide90** [comment]
Think this can be closed really since the AME is in fact destructible.

Will add construction graphs for it I think.
