### ISSUE TITLE
Lag when things are thrown into space

### ISSUE THREAD

**Issue by ShadowCommander** [space-wizards/space-station-14#565]
If you fire bullets off screen, the game lags a lot for a while until the bullets despawn.

**Comment by ShadowCommander** [comment]
Same thing happens when throwing things out into space. Bullets aren't as much of a problem since they despawn, but if floor tiles are thrown, it keeps lagging.

**Comment by PJB3005** [comment]
This is significantly less bad now that the collision system isn't a nonperforming mess.

We still need a way for things that leave the map to eventually get deleted, but I'm closing this for now in favor of a new issue.
