### ISSUE TITLE
Welder fuel tanks blow up if wideattacked/attacked with an unlit welder

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#5674]
## Description

How to replicate:

- Have a welder that is unlit
- Wideattack near a fuel tank (or attack the fuel tank directly)
- The fuel tank will explode even though the welder is not lit.

This makes trying to get kudzu out of Packed's maint nearly impossible without Plant-B-Gone.

**Comment by ElectroJr** [comment]
Welders need a way of modifying the melee weapon component's damage value depending on whether they are lit or not.

I guess you could do this via a modify-damage event that gets raised by the MeleeWeapon system to allow other systems to modify the damage. But I'm not sure whether that even would even ever be used by anything other than welders.
