### ISSUE TITLE
Client crash when you try to reconnect to a server you disconnected from

### ISSUE THREAD

**Issue by ike709** [space-wizards/space-station-14#569]
Console closed before I could copypaste the error but I got a screencap.
(Open in new tab if you want to be able to read it).
![image](https://user-images.githubusercontent.com/5714543/73140111-d12eaf80-403a-11ea-9684-6786bc9a36c7.png)

**Comment by PJB3005** [comment]
That one's definitely my bad.

**Comment by PJB3005** [comment]
Fixed by 5243530d813c695057c08027e024a0b4e7ec9cd7
