### ISSUE TITLE
Singularity eating things breaks the UI extremely hard

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#5702]
## Description
Game ends up hardlocked in a almost unplayable state, requires a restart.

**Comment by Efruit** [comment]
any thing in particular, or just things in general?

**Comment by moonheart08** [comment]
> any thing in particular, or just things in general?

I couldn't tell, it just broke everyone online's UI repeatedly.

**Comment by mirrorcult** [comment]
this was a PVS thing that hasnt been reported in ages and i think was fixed
