### ISSUE TITLE
overlays should use the drawing args bounds

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#5705]
Most of them resolve IEyeManager and get the current eye's viewport but the args already includes the bounds in Box2 and Box2Rotated terms.

**Comment by Efruit** [comment]
A few also seem to re-resolve `IOverlayManager` despite it being available in a field (`OverlayManager`).

**Comment by Efruit** [comment]
Are there others, or did #5709 clean them all up?
