### ISSUE TITLE
Client console flooded with errors about discord

### ISSUE THREAD

**Issue by ike709** [space-wizards/space-station-14#571]
I have discord installed but not running. I assume it's something to do with rich presence?

![image](https://user-images.githubusercontent.com/5714543/73150207-d0be0500-408a-11ea-97f0-c61f2d1469e7.png)

**Comment by ShadowCommander** [comment]
That's normal. The Discord rich presence library that we're using spams those errors. It'd be a problem to bring up on their GitHub.
