### ISSUE TITLE
Manual gas valves don't close properly.

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#5714]
## Description

This issue was originally reported by Hyperdrift#0935 on Discord. I have verified it in an updated local environment as of around 8PM on 12/06/2021. 

https://cdn.discordapp.com/attachments/790656972801572905/917566718648414248/valve.mp4

How to replicate:

- Spawn a simple Atmos loop with a connector port, a valve, and a passive vent.
- Turn the valve off, which should prevent the gas from flowing past it.
- Wrench a plasma canister to the connector port.
- The plasma will still be released even though the valve is off.

**Comment by hubismal** [comment]
thank you for making this. i thought i was going insane or was just an atmos noob or something.

**Comment by Peptide90** [comment]
Fixed by #6121
