### ISSUE TITLE
Missing launcher/engines/0.7.21.zip causes client to fail on joining server

### ISSUE THREAD

**Issue by dhakim87** [space-wizards/space-station-14#5726]
## Description
Seems to be a bug on mac os build when switching servers.  Had the game working fine yesterday, switched from Wizard's Den Lizard (US West) to the Oceania server for some late night testing of shuttles.  Tried starting it up today and it would immediately complain that the client was crashing on trying to join Wizard's Den Lizard again.

Crash was:
Unhandled exception. System.IO.FileNotFoundException: Could not find file '/Users/<me>/Library/Application Support/Space Station 14/launcher/engines/0.7.21.zip'.

And indeed, there is no 0.7.21.zip in that folder.

I restart several times to no avail.

Finally, I go back to Oceania and it downloads a bunch of server content, then loads the player correctly.
Then I go back to Wizard's Den Lizard and it downloads a bunch of server content and loads the player correctly.

And there is now a 0.7.21.zip in that folder.

**Comment by Zumorica** [comment]
I'm gonna guess the engine publish action took a bit more than usual, probably not an actual issue.

**Comment by Zumorica** [comment]
Closing, most likely just a one-time thing.
