### ISSUE TITLE
Thunderdome ghost role event

### ISSUE THREAD

**Issue by Peptide90** [space-wizards/space-station-14#5735]
More changes need to be made to ghost roles such as a mob list to assign ghost roles to easily or just spawning mobs with the ghost role component instantly.

But having an easy button press event that spawns thunderdome NPCs and sets a timer and allows the station to view the event would also be ideal and give ghosts some fun if there's lots dead and the round isn't progressing much.

May require maps to include a centcom location with an area or have an area on station.

**Comment by Peptide90** [comment]
Was this ever added as an event that admins can trigger @Emisse ? I know deathmatch was added but that looks like a separate gamemode.

The charm in 13 of Thunderdome is it's for ghost roles and station can watch it from TVs. Still think that's a fun / valuable idea to break up an extended shift watching sports in the bar.

**Comment by deltanedas** [comment]
arena deltav
