### ISSUE TITLE
Pulling something with ctrl + RMB and slipping causes issues

### ISSUE THREAD

**Issue by aamonz** [space-wizards/space-station-14#5761]
## Description
As the title says, pulling something (default keybinds ctrl + RMB) puts you in a weird state where you can move while stunned on the ground.

**Steps to replicate**
1. Find a puddle
2. Find something to pull (preferably not alive)
3. Spam CTRL + RMB to move the object
4. You'll end up like in the video

**Video**

https://user-images.githubusercontent.com/92693280/145728060-c15ca3cd-fca7-42ed-8995-56160e5086b2.mp4

**Comment by Willhelm53** [comment]
#5225

**Comment by metalgearsloth** [comment]
Slipping should probably just break pulling.
