### ISSUE TITLE
View Subfloors and Show Spawners buttons can no longer be toggled in mapping mode.

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#5789]
## Description

How to replicate:

- Go into mapping mode.
- Attempt to turn off the "View Subfloors" button in the menu.
- You will be unable to do this, and the subfloors view will be stuck on.
- Similarly, you can no longer view spawners.

This seems to have something to do with admin permissions, which should be ignored in mapping mode.

**Comment by Zumorica** [comment]
Fixed by #5899
