### ISSUE TITLE
Cannot form a conga line / train of people dragging other people in chairs

### ISSUE THREAD

**Issue by dhakim87** [space-wizards/space-station-14#5804]
## Description
People B and C buckle to chairs
Person A grabs person B's chair
Person B grabs person C's chair

Person A begins walking

Rather than forming a nice conga line, person B will automatically unbuckle at some point.  Can slightly lengthen the duration that the conga works by walking very very slowly as person A.  

Unclear if this is due to physics and/or networking

**Comment by UbaserB** [comment]
I see conga lines all the time now, this can be closed.

**Comment by deltanedas** [comment]
yep krill issue
