### ISSUE TITLE
Deconstructing a crate deletes items (or people) in the crate.

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#5806]
## Description

This bug was originally reported by Raven#1990 on Discord. I have replicated it with a fully-updated local environment as of 12/16/2021 at 7:00PM EST. This will throw an exception in VS2022's Debug mode.

How to replicate:

- Find an (un)willing assistant
- Get them in a crate
- Use a screwdriver on the crate

**Screenshots**

![image](https://user-images.githubusercontent.com/7907891/146466771-996b48d6-1343-430f-98ed-bbd66319cdfa.png)

![image](https://user-images.githubusercontent.com/7907891/146466815-a109d88f-ff5c-477c-892c-82481d8fc7db.png)

![image](https://user-images.githubusercontent.com/7907891/146467125-5776ac35-8dc5-453d-8647-435e5647e341.png)

**Comment by Zumorica** [comment]
Fixed by 22d1e8a4272cc1c4af6019f51ffccb492f061fc9

**Comment by Peptide90** [comment]
Is this the same issue we have with disposals too?

**Comment by Zumorica** [comment]
> Is this the same issue we have with disposals too?

Fixed in 47b341f4a39e24678eb1cc86a1b469bc5a2f3265
