### ISSUE TITLE
Sec Ticketing

### ISSUE THREAD

**Issue by Nousagi37** [space-wizards/space-station-14#5809]
## Description

Sec doesn't really have anything for punishments besides throwing people into the Brig. Ticketing can bring more role-play instead of having the clown being thrown into brig for throwing a pie at someones face.

**Comment by Matz05** [comment]
Maybe printing off a ticket should at the same time make a 'security logs' entry the other Sec can check from their PDAs or something? Station records would be a larger project, though.

**Comment by Peptide90** [comment]
We need crew manifest computers first so we can have a list of the crew and their jobs.

Then expanding that to a security log that can have notes shouldn't be too much more work (for someone competent).

**Comment by metalgearsloth** [comment]
Not sure github is the best place to bikeshed content?
