### ISSUE TITLE
Gas tanks cannot be inserted into radiation collectors

### ISSUE THREAD

**Issue by Exojets** [space-wizards/space-station-14#5815]
How to reproduce:
- Hold a gas tank in your hand, such as the plasma tank that spawns next to the radiation collectors on PackedStation
- Click on a radiation collector

Radiation collectors are supposed to require the insertion of plasma tanks in order to generate power, but this is not currently possible. As a result, radiation collectors are currently unable to generate power.

**Comment by Charlese2** [comment]
Radiation collectors do generate power when hit with radiation. You can get power if the radiation storm hits a collector. It seems the singularity isn't generating radiation.

**Comment by Peptide90** [comment]
Referenced this issue in 6240 as generators in general don't take any fuel and should also take plasma tanks and produce power in proportion to the plasma used plus external factor such as radiation absorbed or time passage.
