### ISSUE TITLE
Extra newlines in the endgame round information

### ISSUE THREAD

**Issue by Acruid** [space-wizards/space-station-14#5825]
There are extra newlines in the endgame round information report around the syndicate objectives. It is unknown if it's a formatting issue for this specific text or an actual bug in engine.

This is using engine v0.8.9

![image](https://user-images.githubusercontent.com/1685952/146654991-55e0aad9-a538-4b19-ba77-63892638fe64.png)

**Comment by Efruit** [comment]
Known. Will be triaged/addressed when I get a chance to make the round end summary screen use more of the new rich text features.

**Comment by Efruit** [comment]
This was fixed (or rather, un-broken) by the rich text revert.
