### ISSUE TITLE
Traitor mode will continuously restart when there aren't enough players

### ISSUE THREAD

**Issue by ShadowCommander** [space-wizards/space-station-14#5826]
## Description

Currently traitor mode will continuously restart every 60 seconds if it's set as the default game mode.

Every time it restarts it loads another map.

Launch args:
`--cvar game.defaultpreset="Traitor" --cvar game.fallbackenabled=false --cvar game.lobbyenabled="true"`

Additional helpful launch args:
`--cvar traitor.min_players=2 --cvar traitor.min_traitors=1 --cvar game.lobbyduration=30`

**Comment by Zumorica** [comment]
Is this an issue? The gameticker specifically attempts to start a preset, and if fallback isn't enabled and the preset fails to start, it will restart the round again, delaying the start incrementally every time.

**Comment by ShadowCommander** [comment]
It doesn't need to initialize the map. It could just restart the timer.
