### ISSUE TITLE
Hard time watering the trays

### ISSUE THREAD

**Issue by BozoDel** [space-wizards/space-station-14#5827]
I'm having trouble filling botany trays with water. I keep adding water, but when I shift+click on the trays, it seems little to no water is actually added.

Not sure if it matters, but the trays either had dead plants or no plants at that time.

Also I seem to be unable to properly set transfer amounts. I set it to 100, but the bucket only added 5u at a time.

**Comment by ElectroJr** [comment]
So the specific botany watering issue should be fixed by #5831, but that doesn't address the issue of buckets and other containers generally not respecting the requested transfer amounts.

**Comment by ElectroJr** [comment]
Transfer amount issues should have been fixed by #5833, so closing this.
