### ISSUE TITLE
Admin logs next button is broken

### ISSUE THREAD

**Issue by DrSmugleaf** [space-wizards/space-station-14#5838]
## Description
Refresh sends 1000 logs and stores the last log id it sent, which next is supposed to use to know where to continue from when sending the next 1000 logs. The second part is broken and pressing next instead sends 0 logs.

**Comment by DrSmugleaf** [comment]
Fixed for cached logs in https://github.com/space-wizards/space-station-14/commit/1f8152cb02f6191da5462ceb34810a061c03a98a, but not for any logs in non cached rounds

**Comment by Peptide90** [comment]
@DrSmugleaf fixed the other day?
