### ISSUE TITLE
Plasma is all risk, no reward

### ISSUE THREAD

**Issue by Efruit** [space-wizards/space-station-14#5843]
## Description
Plasma is currently useless aside from toasting the station.

Until we have more for it to do, we should consider removing canisters and severely limiting miner output.

**Comment by Pangogie** [comment]
One of my thoughts was limiting the pressure output to like 50 kPA so that it cannot spread instantaneously.
Could also be locked in CE and RD's rooms for safe keeping.

**Comment by Efruit** [comment]
@Pangogie That would REALLY crowd the CE and RD's offices. Regardless, I don't think the solution is to move it around; I think we just need less of the damn pink stuff.

**Comment by Pangogie** [comment]
Well ya. Like 1 or 2 tanks. Not the 8 that are currently available.

**Comment by Efruit** [comment]
Addressed on Packed in #5975, but the overall issue is still present.

**Comment by Peptide90** [comment]
Fairly sure plasma miners are now gone on all stations as are canisters. We now have air alarms and fire alarms so should be much mess of an issue and syphon on scrubbers is working to remove plasma.

This issue should be converted to a feature request for things for plasma to do such as using it as fuel for the TEG or thrusters but that's ideaguys discussion that we've been over.[ HackMD doc, thruster rework](https://hackmd.io/@nb5RBcIJQfqTbITE_hj4Iw/BJqEZoSat) is at the bottom for ref.
