### ISSUE TITLE
Item context popup update/draw call order might be backwards.

### ISSUE THREAD

**Issue by Acruid** [space-wizards/space-station-14#5851]
The intrinsic order of the game loop is Input -> Ticks(s) -> Update -> Draw. The item context popup update/draw call order might be backwards.

# How to test
* Get into game, equip a drill.
* Put breakpoints in the gameloop and at the item context draw/frameupdate functions
* Keep running the program between breakpoints to make sure frameupdate and draw breakpoints are properly hit in pairs.
* If a problem is detected, figure out if it's a content or engine issue.

**Comment by Efruit** [comment]
Context: https://github.com/space-wizards/RobustToolbox/issues/2339 

Rich Text (R.I.P.) labels required text to be laid out before it could be displayed.

Before https://github.com/space-wizards/RobustToolbox/commit/eac789cae60d2b18a95df7ad45deeea36e7509f5, it made the assumption that `Update` would always be called before `Draw`, and did no checking to see that the layout data had, in fact, been calculated.

The following was responsible for calculating the layout data (`_ld`):
```cs
        // Last maxSizeX, used to detect resizing.
        private int _lmsx = 0;
        // Layout data, which needs to be refreshed when resized.
        private ImmutableArray<TextLayout.Offset> _ld = default;

        public void Update(IFontLibrary font, float maxSizeX, float uiScale)
        {
            if ((int) maxSizeX != _lmsx)
            {
                _ld = TextLayout.Layout(Message, (int) maxSizeX, font, scale: uiScale);
                Height = 0;
                Width = 0;
                foreach (var w in _ld)
                {
                    if (w.x + w.w > Width) Width = w.x + w.w;
                    if (w.y + w.h > Height) Height = w.y;
                }
                _lmsx = (int) maxSizeX;
            }
        }
```

Later...
```cs
        public void Draw(
            DrawingHandleScreen handle,
            IFontLibrary font,
            UIBox2 drawBox,
            float verticalOffset,
            float uiScale,
            Color defColor)
        {
            var flib = font.StartFont();
            foreach (var wd in _ld) // Crashes here
            {
                var s = Message.Sections[wd.section];
...
```

I'm unaware of any cases where `TextLayout.Layout` would have returned an invalid object reference, meaning `Update` must not have run before `Draw`.

**Comment by mirrorcult** [comment]
this is not very actionable
