### ISSUE TITLE
Doors sometimes can't be unbolted despite standing on a powered LV wire

### ISSUE THREAD

**Issue by zlodo** [space-wizards/space-station-14#5854]
## Description
Sometimes, in some unexplained condition, doors that have been bolted can not be un-bolted with the multitool, despite very obviously being powered (LV cable having power running right underneath them as in the screenshot). Reading the door code, it seems to me that receiving power from the APC is supposed to be the only requirement to unbolt the door.

**Screenshots**
![image](https://user-images.githubusercontent.com/9020266/146966010-0a3d424c-3097-4f76-94cd-05d9e8df2a94.png)

**Additional context**
I don't know of any particular pattern. Yesterday we once had a few doors affected by this issue after their external power had been cut off and then restored. Multiple players tried to unbolt these doors to no avail. For one of the affected doors, another player had no issue getting the bolts off.

**Comment by zlodo** [comment]
I must add that relogging didn't fix the issue for me yesterday.

**Comment by zlodo** [comment]
I can confirm that it may be the case that it doesn't work for a player, but works for another. I just experienced the same issue with someone asking me to unbolt a door, it wasn't working. I passed them the multitool and they did it without issue.

**Comment by ElectroJr** [comment]
The actual door hacking logic is done server side, so unless it has something to do with the hacking interface itself I'm not sure how this could affect only one player. Having steps to reliably reproduce would help.

**Comment by zlodo** [comment]
Turns out it was skill issues all along: I didn't notice the part of the code where the door gets unpowered while the power led is blinking. This only happened when I was in a hurry to try to unbolt a door, didn't remember which wire was the bolt wire, and pinged the power wire first, thus being unable to unbolt the door right after because it had just cut its power.
