### ISSUE TITLE
The Lobby does not respect the map change vote.

### ISSUE THREAD

**Issue by pointer-to-null** [space-wizards/space-station-14#5865]
## Description

Technically, this works correctly. Voting changes the map for the next round. 
But I believe that voting in the Lobby should change the map of the current (or upcoming) round.

**Comment by Zumorica** [comment]
As a note, while you're on the lobby the map is already loaded. "Fixing" this would mean the existing map would have to be deleted, and the chosen map would have to be loaded. Given that deleting/loading maps is pretty expensive, this would most likely cause the server to freeze for a few seconds until it finishes changing the map.
