### ISSUE TITLE
Add item status to solution containers

### ISSUE THREAD

**Issue by Moneyl** [space-wizards/space-station-14#587]
Using `IItemStatus` you can add custom status info for entities being held based on their components. For example, here's one showing ammo counts on guns:

![dijEg87YLX](https://user-images.githubusercontent.com/8206401/73629955-a89e4b00-4622-11ea-9977-3e9463b3080a.png)
Here's a WIP one for injectors:
![sc4xEfobSU](https://user-images.githubusercontent.com/8206401/73629972-b653d080-4622-11ea-8746-c33263543dda.png)

We should add this for solution containers. If possible we could try to fit the exact contents in the status, but if not just having `volume used / total volume` like the injector would be useful.

**Comment by PJB3005** [comment]
No way there's enough space for exact contents. Leave that to examine (IMO). Showing the reagent of highest volume would be a good idea though since then you can distinguish similarly-colored chemicals easily.

**Comment by SweptWasTaken** [comment]
![image](https://user-images.githubusercontent.com/49448379/108606358-9fa92480-73b1-11eb-9120-d1e38612683c.png)

Is this not already done?

**Comment by SweptWasTaken** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/49448379/108606358-9fa92480-73b1-11eb-9120-d1e38612683c.png)
> 
> Is this not already done?

Assuming it is.
