### ISSUE TITLE
Carp die to space again

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#5889]
Can't debug rn but I'd bet they're dying to the cold

**Comment by Delete69** [comment]
I put Xenos down on a map today and they died. Are they supposed to be spaceproof?

**Comment by Peptide90** [comment]
To update. Space carp actually survive on space, but as soon as they land on a lattice in space they die to cold damage.

Pressure nerf PR makes it so Xeno follow same base as space carp so should help with them but will need to look into the cold damage.
