### ISSUE TITLE
Killing yourself with a microwave turns you into a talking head that can enter ghost form and return at will

### ISSUE THREAD

**Issue by Fishfish458** [space-wizards/space-station-14#5896]
## Description

So...this one is hilarious but it could turn into a meta thing...somehow.

to reproduce:
Go to a microwave
/suicide
after your head is done baking, you'll be able to talk freely and creepily look around using the mouse.
using wasd will put you in ghost form, able to talk and ghost about
return to body puts you back into your talking head form.

**Screenshots**

![image](https://user-images.githubusercontent.com/47410468/147376808-f7b34c1f-c3e9-4174-a633-074001f17cde.png)

![image](https://user-images.githubusercontent.com/47410468/147376812-119a5a1e-ce51-4037-a0db-6566a929e3e9.png)

![image](https://user-images.githubusercontent.com/47410468/147376826-8eb0789b-d76f-40e5-aa91-921150281c4f.png)

**Additional context**

**Comment by Nousagi37** [comment]
Dear lord
