### ISSUE TITLE
There is a pixel-sized hole in the clown's pants and you can see through it.

### ISSUE THREAD

**Issue by pointer-to-null** [space-wizards/space-station-14#5905]
![изображение](https://user-images.githubusercontent.com/91910481/147408474-b320b8c3-2645-4e1c-9b64-019cd4b1b64c.png)

The clown jumpsuit sprite is fine, by the way.

**Comment by mirrorcult** [comment]
reverse dixel

**Comment by moonheart08** [comment]
Apparently might have something to do with how SS13 handles adjusting jumpsuits for female characters.

**Comment by PJB3005** [comment]
Somebody screwed up and removed `femaleMask: UniformTop` from the clown jumpsuit.
