### ISSUE TITLE
Saltern Atmospherics gas storage chamber air vents use the default pressure cap

### ISSUE THREAD

**Issue by Matz05** [space-wizards/space-station-14#5922]
## Description

The air vents used to insert gas into the storage chambers in the Atmospherics wing of Saltern appear to use the default 101.325 kPa/1atm limit used by vents all around the station, despite assurances I've received that they're supposed to be more powerful to enable returning filtered gas to the storage chambers under pressure or unpacking gas canisters into the storage chambers.

**Additional context**

In combination with the lack of any spare atmospherics network components (pipes, pumps, vents, etc.) on the station, lack of any ability to produce more, and #5714, this renders the Atmospherics department largely impotent and without mechanical effect, other than the ability to somewhat clumsily change or cut off the air mix and the ability to enable scrubbing-to-space (but not scrubbing-to-storage).

**Comment by Peptide90** [comment]
Probably will involve altering [GasVentPumpComponent.cs](Content.Server/Atmos/Piping/Unary/Components/GasVentPumpComponent.cs) to allow a high pressure variant so the component can have a data field for standard and high pressure output variants. Ortherwise we're looking at another component just for high pressure vents for a total of 3 ([passive, current](https://github.com/space-wizards/space-station-14/blob/master/Resources/Prototypes/Entities/Structures/Piping/Atmospherics/unary.yml) and high).
