### ISSUE TITLE
body bag and body bag [Folded] refuse to be placed on tables

### ISSUE THREAD

**Issue by Delete69** [space-wizards/space-station-14#5955]
## Description

Will not sit anywhere on a table except the very edge.

Exists across PlaceFree, PlaceNearby, SnapgridCenter, SnapgridBorder

**Screenshots**

![image](https://user-images.githubusercontent.com/95458399/147729855-ac519adb-44de-4636-8ebe-3de96dceb6af.png)
![image](https://user-images.githubusercontent.com/95458399/147729886-d2817456-7cf2-4ad0-bbfe-b78c7f251a2b.png)

**Additional context**

**Comment by Elijahrane** [comment]
I encountered this too when mapping

**Comment by PaulRitter** [comment]
this is probably due to it not properly resetting the layer/mask when folded

**Comment by Delete69** [comment]
> this is probably due to it not properly resetting the layer/mask when folded

It's unfolded body bag too.
