### ISSUE TITLE
Botany has no ways of increasing potency (Robust Harvest doesn't work)

### ISSUE THREAD

**Issue by Elijahrane** [space-wizards/space-station-14#5969]
## Description

I'm not sure if I'm missing something, but potency works in that it does modify the reagents inside (you can see the difference when spawning in produce.)

EDIT: You can increase potency with Robust Harvest, but this is rather opaque because there's no non-destructive ways of testing potency

Reproduction:
1. Grow a packet of a plant with obvious reagents (nettles are a good one), maybe do a few generations. All packets start at 20 potency.
2. Notice when grinding all plants give the exact same yield, so potency is not changing at all.
3. Spawn one of the produce and grind it (they spawn at 100 potency)
4. That produce will have about 5x as many reagents

**Screenshots**

**Additional context**

**Comment by PaulRitter** [comment]
@Zumorica

**Comment by Zumorica** [comment]
> However, there's no way to increase potency in-game from what I can tell
Use Robust Harvest, it's *specifically* for increasing potency.

**Comment by Elijahrane** [comment]
Botany usually (i.e. in SS13) has minor random potency gain or loss every time a plant is harvested doesn't it? At least there's one way in game.

**Comment by MeltedPixel** [comment]
> Botany usually (i.e. in SS13) has minor random potency gain or loss every time a plant is harvested doesn't it? At least I can tell people to use Robust Harvest when they ask now.

You are correct, in SS13 harvested plants had a random chance to either gain or lose potency. You could also boost potency with Robust Harvest but doing so would also raise the toxicity of the hydroponics tray and eventually the plants would need to be grown from new seeds. 

This keeps botany role engaged on trying to produce the perfect crop.

**Comment by Zumorica** [comment]
> Botany usually (i.e. in SS13) has minor random potency gain or loss every time a plant is harvested doesn't it? At least I can tell people to use Robust Harvest when they ask now.

Not on /vg/ (where our botany is based from) from what I can tell?

**Comment by Elijahrane** [comment]
Actually I can't get

> > However, there's no way to increase potency in-game from what I can tell
> 
> Use Robust Harvest, it's _specifically_ for increasing potency.

I tried this today and all the seed packets were still at 20 the entire round

**Comment by DummeHytteOst** [comment]
this one can probably get closed since robust harvest does work, just very weird #6979

**Comment by Elijahrane** [comment]
Yeah, I think it was fixed after the botany ECS or something

**Comment by Elijahrane** [comment]
This is broken again

**Comment by Elijahrane** [comment]
The seed extractor is resetting the potency
