### ISSUE TITLE
Make it more obvious when getting burnt by lights

### ISSUE THREAD

**Issue by Moneyl** [space-wizards/space-station-14#597]
If you attack lights with an empty hand and inadequate protection you can get burnt. There's no popups or notifications when this happens, making it easy to accidentally crit yourself without knowing what happened.

We should notify the player they've been damaged. Simplest way would be to have a popup via `IServerNotifyManager` or equivalent for client/shared. Another option would be some kind of damage overlay or screen effect for all damage, or a sound effect specifically for being burnt by lights.

**Comment by Moneyl** [comment]
[Relevant code](https://github.com/space-wizards/space-station-14/blob/dfe08d126295299d7b7219c66119c76c6a79effb/Content.Server/GameObjects/Components/Power/PoweredLightComponent.cs#L51)

**Comment by PJB3005** [comment]
Honestly it might just be best to remove lights burning your hand.

**Comment by PKPenguin321** [comment]
I've burned myself on a light in the permabrig, told Officer X that Officer Y lasered me and I wanted a trial, then escaped when he opened the door, so no it should stay because it is emergent gameplay

**Comment by Tyler-IN** [comment]
Being able to disguise burns from a lightbulb as laser burns... Hm.

**Comment by PJB3005** [comment]
You make a convincing argument.

**Comment by PJB3005** [comment]
Maybe make it so you need to click twice to burn yourself. Then you don't accidentally do it but can still intentionally do it.
