### ISSUE TITLE
Conveyor belts broke (again)

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#5970]
## Description
whelp.
## Reproduction
literally attempt to use a conveyor. The ones in packed's cargo work well as an example.

**Comment by metalgearsloth** [comment]
Actually fixing it is irrational https://github.com/space-wizards/space-station-14/issues/4542

**Comment by PaulRitter** [comment]
![image](https://user-images.githubusercontent.com/16618384/147861705-c2646866-70b7-4077-af46-c5b786cbe401.png)
