### ISSUE TITLE
Whisper chat function

### ISSUE THREAD

**Issue by Peptide90** [space-wizards/space-station-14#5987]
## Feature request

Having a chat option to whisper to people in a one tile range. Can be selected by tabbing through the current chat selection or /w I guess.

Possibly show an empty chat bubble to those out of range to show lips moving or if you're in s 2 tile range possibly overhear the odd bit? But maybe too much and the original 1 tile whisper is enough.

**Comment by MeltedPixel** [comment]
You can assign me to this one. I have already wrote the functionality and have tested it in game. Still have a couple minor things to do before its PR ready.

![image](https://user-images.githubusercontent.com/1194692/147866787-d650c5d6-209e-48e6-8226-53101a0752c8.png)
