### ISSUE TITLE
adminwindow playerlist sort barely works

### ISSUE THREAD

**Issue by PaulRitter** [space-wizards/space-station-14#6002]
this is because it uses the trygetchannel of bwoinksystem.
issue with that? the actual channels dont get replicated to the client, a channel on the client is actually the ui-panel. if a given admin has never clicked on the playername, ensuring the panel, the comparison will fail since there hasn't been a panel created yet.

**Comment by Efruit** [comment]
Known. Right now, there is no history system, meaning each admin is only aware of bwoinks from the time they connect, onward. There is an upcoming PR to address this, and it's part of the reason a `SentAt` timestamp was added to the `BwoinkTextMessage`.

The server's `BwoinkSystem` is also not aware of when admins actually *read* messages, so we can't sync that info anyway.

**Comment by PaulRitter** [comment]
i fixed the sorting in 33572c5cc8ddd225e0d2e77d9f4341dc568529ed, i think admins only getting the messages since they joined is fine *for now*, to be fixed by your pr currently open
