### ISSUE TITLE
Hiding AHelp player list

### ISSUE THREAD

**Issue by Efruit** [space-wizards/space-station-14#6011]
## Description
@Pangogie requested a way to toggle the player list on `BwoinkWindow`

**Comment by PaulRitter** [comment]
but why (genuinly curious)

**Comment by Pangogie** [comment]
To save some space while keeping the current AHelp open.

**Comment by Efruit** [comment]
Probably gonna try it using a plain `Button` with `VerticalExpand`.

**Comment by Peptide90** [comment]
Is this still valid since #6017 was up and was closed due to EFR leaving. @Pangogie ? If it's wanted we can resurrect that PR.

**Comment by Pangogie** [comment]
> Is this still valid since #6017 was up and was closed due to EFR leaving. @Pangogie ? If it's wanted we can resurrect that PR.

Close it for now.
