### ISSUE TITLE
Solar tracker controls all panels not just connected ones

### ISSUE THREAD

**Issue by Peptide90** [space-wizards/space-station-14#6055]
## Description
Solar tracker controls all solar panels on the station rather than just the panels it's connected to on it's LV circuit.

Reported by Mr_T#1313 on discord, not locally confirmed.

**Comment by UbaserB** [comment]
I'm pretty sure this is a thing now

**Comment by deltanedas** [comment]
solar tracker literally does nothing

**Comment by UbaserB** [comment]
> solar tracker literally does nothing

what

**Comment by MACMAN2003** [comment]
they literally do nothing. you have to manually adjust the solar panels' spin speed to match the sun's rotation

**Comment by deltanedas** [comment]
read their prototype they have absolutely no behaviour

**Comment by Peptide90** [comment]
> Is their _intended_ behavior only to show the star's direction on the solar computer, meaning that after initial alignment the trackers would still be nearly completely irrelevant for the rest of the round unless game events could mess with panel alignment?

Solar tracker control computer was IIRC just for taking in the solar tracker info and then assigning it to all the solar panels on it's LV network. So you should have one controller per bank of panels.

It is pretty set and forget so an event to scramble them could be good. Raises the question of if we want the solar tracker to just automatically feed into the panels though.
