### ISSUE TITLE
AK icon magazine length

### ISSUE THREAD

**Issue by ShadowCommander** [space-wizards/space-station-14#606]
The magazine in the AK is the regular size until out of bullets when it changes to the short version.

It should stay the same length.

It should use the short version when a short magazine is inserted.

**Comment by PJB3005** [comment]
Pretty sure there's multiple weapons that do this.

@metalgearsloth

**Comment by metalgearsloth** [comment]
From memory and a quick look I only did it for the rifles as I didn't know how they functioned on Eris.
I don't think there's anything to handle different magazines being inserted at the moment so it's probably better to remove the short versions for now as this would also likely tie into any sort of weapon attachment system.

**Comment by metalgearsloth** [comment]
Alright I have a branch with the fixes (6 guns with issues) but I'm getting a dotnet issue so when that's fixed / I workaround it I'll pr it.

**Comment by SweptWasTaken** [comment]
Looks like this has been fixed by #734 so i'm going to close it.
