### ISSUE TITLE
Bot to support adding CODEOWNERS that don't have write perms

### ISSUE THREAD

**Issue by DrSmugleaf** [space-wizards/space-station-14#6067]
## Description
From the [GitHub documentation](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners):
- The people you choose as code owners must have write permissions for the repository.

We agreed that we should organize the CODEOWNERS file better to assign people (with consent, obviously) to areas that they have an expertise in.
It is not possible without any additional tooling to do this for people without write perms to the repo.
We should either find or code a bot/action that can do this for us.

**Comment by Efruit** [comment]
# No.

I can't speak for any other contributors, but If I start getting _"assigned"_ maintainer work for a repo I can't even *tag issues for*, **I will report the bot**. Either trust your contributors to work on the project (w/ AT LEAST group membership and triage perms), or don't _"assign"_ us work.

Anything else is unacceptable.

**Comment by mirrorcult** [comment]
with efr on this one tbh if someone is expected to maintain their stuff so much that they're getting pinged for it on every pr they should probably just be a maintainer or at least triage

**Comment by ike709** [comment]
Fellas it can simply be opt-in, which it is every single time I've seen it used.

**Comment by moonheart08** [comment]
> # No.
> 
> I can't speak for any other contributors, but If I start getting _"assigned"_ maintainer work for a repo I can't even _tag issues for_, **I will report the bot**. Either trust your contributors to work on the project (w/ AT LEAST group membership and triage perms), or don't _"assign"_ us work.
> 
> Anything else is unacceptable.

what are you on about
any such system should be opt-in.

**Comment by moonheart08** [comment]
> Please point out where, in the original issue, an opt-in flow was described. I'll wait.
> 
> In the meantime, here's some light reading:
> 
> > We agreed that we should organize the CODEOWNERS file better to **assign people** to areas that they have an expertise in.
> 
> I personally resent that you all are expecting even more of your contributors while giving them absolutely no consideration. You lock us out of almost everything needed to do a good job.
> 
> I can't shake the feeling that almost everyone in charge has forgotten how to empathize with anyone outside of the leadership.

We have discussed what the intent was in discord many, many times. It is not our problem that you refuse to use the one method of communication we expect people to use.

**Comment by mirrorcult** [comment]
> with efr on this one tbh if someone is expected to maintain their stuff so much that they're getting pinged for it on every pr they should probably just be a maintainer or at least triage

forgot that this was gonna be opt-in so i rescind this

**Comment by ike709** [comment]
> I personally resent that you all are expecting even more of your contributors while giving them absolutely no consideration. You lock us out of almost everything needed to do a good job.

Buddy, take a deep breath. Nobody's making anybody do anything. Being a codeowner doesn't make anyone do reviews. Codeowners is a useful feature for enabling someone to be notified of other people ~~breaking~~ altering the code they often work with. It being restricted to people with write access is a shortcoming on GitHub's part.

> I can't shake the feeling that almost everyone in charge has forgotten how to empathize with anyone outside of the leadership.

Literally what are you on about?

**Comment by juliangiebel** [comment]
I can only agree to what ike709 said, I see beeing codeowner for device networking for example as means to  be notified if someone changes how device networking works.
Additionally I want to help people use the system I wrote so I welcome being notified about someone adding something to the device networking folder (You specify what folders you are codeowner of right?).

**Comment by PaulRitter** [comment]
> Please point out where, in the original issue, an opt-in flow was described. I'll wait.
> 
> In the meantime, here's some light reading:
> 
> > We agreed that we should organize the CODEOWNERS file better to **assign people** to areas that they have an expertise in.
> 
> I personally resent that you all are expecting even more of your contributors while giving them absolutely no consideration. You lock us out of almost everything needed to do a good job.
> 
> I can't shake the feeling that almost everyone in charge has forgotten how to empathize with anyone outside of the leadership.

EFR, somehow we find ourselves again at this impass of you. You keep refusing to join discord to get proper information. You keep running at staff with an almost rabid attitude because of wrong (and often the worst) assumptions you've made about decisions we've taken. I've had about enough of this, and curiously, you are also the only contrib we keep having this issue with.

This isn't an **assignment** of any kind, this is purely a notification. We dont even require our maintainers to be available for their areas of expertise, what the hell gave you the idea we'd require it from contribs?

**The IRC-Relay will not give you all the necessary recent information, nor will we garantuee it will. If you want to be properly included in the discourse, join discord. Otherwise: bugger off and take your toxicity with you.**

**Comment by Efruit** [comment]
@DrSmugleaf would you mind amending the issue description to include the opt-in requirement? Any other relevant-but-missing details would also be welcome.

Since the above thread is in response to my (admittedly emphatic, and partially off-base) posts, which were in turn based on incomplete information, I'd request that it be marked outdated/off-topic to avoid continued derailment.

**Comment by Matz05** [comment]
Can't you get a sandboxed web browser of some kind, and use it to occasionally check the Discord conversation from the web client, in addition to what the IRC bridge gets you? Or install the desktop client on a virtual machine? Even if you consider the desktop client malware, it seems like there are plenty of ways to view the conversation that you just... refuse to try. I'd hate for there to be more misunderstandings upsetting you and others, but sometimes it seems to me almost like you _want_ to feel slighted or persecuted by misunderstandings, like you're searching for reasons to leave the project. I'm really sorry if you feel that way, but I think you might feel better making up your mind on whether to stay or leave and not keep tormenting yourself and building bad blood with these misunderstandings. It's actually starting to turn people against you, and that really sucks when you have so much to offer the community.

**Comment by Efruit** [comment]
@Matz05 I don't know pings from Gists show up on Github proper, so I'll link this here as well: https://gist.github.com/Efruit/b3852feb06f8a55d3f1c99bb6f50551f

**Comment by mirrorcult** [comment]
we've kind of gone back on codeowners even being useful at all i think i will just close this
