### ISSUE TITLE
Add lizarb

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#6071]
## Description
When #6066 is merged, we need the lizard species.
We will fail as a remake without it.

**Comment by DogZeroX** [comment]
Moony does a funny and adding lizards suddenly becomes priority 2.
Mfw not priority 1

**Comment by Willhelm53** [comment]
#6099 you folks already know about this one but I'm linking it for the trail 😁

**Comment by SweptWasTaken** [comment]
Are the lizards going to have the gameplay mechanics from SS13 or are they just going to be a skin?

**Comment by Peptide90** [comment]
> Are the lizards going to have the gameplay mechanics from SS13 or are they just going to be a skin?

It was decided when species were finally going to get upstreamed that all species need to have unique mechanics and can't be reskins. There was much bikeshedding around it and nothing is final but SS13 had some fairly decent species with good drawbacks and perks (para in particular).

**Comment by metalgearsloth** [comment]
This was done.
