### ISSUE TITLE
Duplicate stations when restarting round to force map.

### ISSUE THREAD

**Issue by Pangogie** [space-wizards/space-station-14#6077]
>Forcemap
>startround
>Restart the round to get onto the forced map. (I think the bug occurs when you restart too quickly after starting the round.)
>Presto 2 stations (sometimes.)

The 2nd station doesn't actually init so it's sorta okey, but there is 2 job lists so there can be doubled roles on the proper station.

**Comment by ShadowCommander** [comment]
Is this fixed?
