### ISSUE TITLE
Connecting to server with no lobby enabled will break if no jobs slots are available

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/space-station-14#6081]
Easiest way to test this is to connect to knightship with a character slot allowing only assistant. You'll get stuck on the connecting screen.

**Comment by moonheart08** [comment]
The best fix would probably be to force the lobby?

**Comment by PJB3005** [comment]
I should have clarified: if no job slots *in your character profile* are available. You can have 10 slots open for various jobs but if you only have assistant active and that's not available, it'll break.

Really there are two possible fixes here:
1. always allow spawning as assistant
2. spawn as observer instead.

**Comment by moonheart08** [comment]
> I should have clarified: if no job slots _in your character profile_ are available. You can have 10 slots open for various jobs but if you only have assistant active and that's not available, it'll break.
> 
> Really there are two possible fixes here:
> 
>     1. always allow spawning as assistant
> 
>     2. spawn as observer instead.

Yea the former would effectively be removing a feature (maps don't have to use assistant at all and aren't even required to have overflow jobs)

**Comment by ShadowCommander** [comment]
I know Colonial Marines just puts the player back in lobby if none of their preferences get picked. Then they have to pick from late join choices.
