### ISSUE TITLE
Uplink can still be viewed by non traitors (9th january 2022)

### ISSUE THREAD

**Issue by Kromabae** [space-wizards/space-station-14#6087]
## Description
Patchie said that PDA checks are gone and uplinks are hidden from non antags.
Can however still be seen if you take ID card out and put it back in again

I picked up a (assumed) traitors PDA that was dead and his ID said chemist but was in a engineering PDa he owned so i took ID out to check the icon and it was engineering ID too so i was like meeh and put it back. Thats when the Uplink option came up

**Comment by ElectroJr** [comment]
There was a flaw in the original fix. An hour before you opened this issue another PR was merged that should have fixed this (#6083). Did the issue happen just before you opened the issue (i.e. is it still broken), or is it fixed now?

**Comment by Kromabae** [comment]
this post was made like an hour or two after it's discovery. i was with anohter person that said they already reported it, then moony said there was no such report so i made one just incase

**Comment by ElectroJr** [comment]
Ok then hopefully that just happened before it was merged. I'll close this for now, but lemme know / reopen this if it still isn't fixed.
