### ISSUE TITLE
Change UplinkAccounts to use Mind instead of body

### ISSUE THREAD

**Issue by ShadowCommander** [space-wizards/space-station-14#6097]
## Description

Currently the UplinkAccountsSystem uses EntityUid, which means that if the Traitor gets cloned, they aren't registered in the accounts database, and so due to recent access changes are unable to access their uplink.

**Comment by Macoron** [comment]
Aren't this access changes temporal, until #5842?

**Comment by ShadowCommander** [comment]
That PR doesn't change the Uplink system so even when it gets merged, a cloned traitor still won't have access to their account.

**Comment by Macoron** [comment]
> That PR doesn't change the Uplink system so even when it gets merged, a cloned traitor still won't have access to their account.

Wdym? Anyone who knows code can access Uplink.

**Comment by ElectroJr** [comment]
To clarify, AFAIK the idea was to just have uplinks accounts linked to a secret code / login, that any player can access if they know it (and have an entity with an uplink component available), with no entity/mind restrictions. The ringtone PR doesn't actually make any changes to uplink stuff, but is intended to be the how the secret code is entered.

You could instead just add a "phone" button and recycle the nuke key-code entry UI or something if that were easier than finishing the ringtone PR.

**Comment by TheDarkElites** [comment]
> To clarify, AFAIK the idea was to just have uplinks accounts linked to a secret code / login, that any player can access if they know it (and have an entity with an uplink component available), with no entity/mind restrictions. The ringtone PR doesn't actually make any changes to uplink stuff, but is intended to be the how the secret code is entered.
> 
> You could instead just add a "phone" button and recycle the nuke key-code entry UI or something if that were easier than finishing the ringtone PR.

It's not difficult I've just been busy lately, but I am currently working on finishing up the changes sloth requested and pushing it for review sometime soon.

**Comment by EmoGarbage404** [comment]
uplink accounts are getting nuked from orbit so this will not longer be accurate.

**Comment by ElectroJr** [comment]
> uplink accounts are getting nuked from orbit so this will not longer be accurate.

Are the changes going to involve actually linking the account/credits to a login/secret, or will it still be tied to a player's entity somehow?
