### ISSUE TITLE
Rounds are failing to restart automatically

### ISSUE THREAD

**Issue by Efruit** [space-wizards/space-station-14#6102]
## Description
Calling the shuttle causes the round-end window to show, but the game does not to return to the lobby, leaving the players stranded. Manual restarts appear to work, but whether votes work is undetermined.

Observed by @Pangogie and myself on lizard ~2022-01-10 from 4:00-5:00 AM EST.

cc @wrexbe

**Comment by metalgearsloth** [comment]
Dupe https://github.com/space-wizards/space-station-14/issues/6077 ?

**Comment by Pangogie** [comment]
> Dupe #6077 ?

Nah, this is definitely a different thing.

**Comment by moonheart08** [comment]
Almost definitely the fault of #5990, reverted until it can be fixed.
