### ISSUE TITLE
You can mine bees.

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#6123]
They play the rock mine sound and everything.

**Comment by mirrorcult** [comment]
not for long

**Comment by ElectroJr** [comment]
>  Bug of the Year 2021 Candidate

Label needs updating. Awards ceremony when?

**Comment by SweptWasTaken** [comment]
Can't replicate

**Comment by DogZeroX** [comment]
Feature

**Comment by mirrorcult** [comment]
asteroidrock was converted into mineable and a different comp, so this is fixed now
