### ISSUE TITLE
Teleporting things using pull

### ISSUE THREAD

**Issue by RandomDeathMatch** [space-wizards/space-station-14#6128]
## Description

This is a couple bugs technically.
1. If you get in a disposal unit then pull something else in that disposal, when you get out you are still "pulling" it, but may walk freely. If someone ejects or deconstructs the unit, the thing you are pulling sort of teleports to you. 

2. If you drag an object, then sit on a chair or something, then someone drags your chair, the object is not pulled with you. However, when you get off the chair, the object sort of teleports to you. This doesn't work with everything (sometimes you slide off the chair or the object is pulled correctly) but did work with banana peels and gas canisters. Seems most consistent using a roller bed not a chair.

**Screenshots**

**Additional context**

The teleport is probably pull working as intended. Depending on what you pull it can teleport you both to a kind of half-way point.

**Comment by IProduceWidgets** [comment]
I'm pretty sure these were both fixed. I tried and could not replicate them. 

Looked for a relevant PR, but this was the best I could find. 
https://github.com/space-wizards/space-station-14/pull/24936
https://github.com/space-wizards/space-station-14/pull/26309
https://github.com/space-wizards/space-station-14/issues/24900
