### ISSUE TITLE
Trash bags need an entity whitelist.

### ISSUE THREAD

**Issue by ElectroJr** [space-wizards/space-station-14#6131]
![snip](https://user-images.githubusercontent.com/60421075/148986690-110a78e9-4031-4279-b3a8-29eae101b523.png) 
Screenshot stolen from peptide

**Comment by Peptide90** [comment]
Don't mind doing this tomorrow if nobody has nabbed it.

**Comment by Peptide90** [comment]
Unless we want the whitelist to be 30 ID's long is there a preferable way of doing this? Trash tag?
