### ISSUE TITLE
Butchered slimes produce human meat

### ISSUE THREAD

**Issue by Peptide90** [space-wizards/space-station-14#6145]
Not desirable. Slimes should either produce Jelly food or water puddle (until we have blood).

**Comment by mirrorcult** [comment]
this should be a 1 or 2 line fix on the slime prototype

**Comment by Peptide90** [comment]
Started work on this. Making Vox butcher to bird meat and making slimes butcher to slime balls.

Not sure how real it is having slimes be spikable but the alternative is making them not inherit butcherable from human.

**Comment by Peptide90** [comment]
I've done the work for this so far as to make it so slimes now butcher to slime balls (a meat type for now). But ran into #6170 So not sure on PRing it yet.

Also slime balls currently don't do anything so instead of implementing into cooking might make them blend down into a reagent. Any ideas?
