### ISSUE TITLE
Character Preview in lobby is incorrect

### ISSUE THREAD

**Issue by ZeroDayDaemon** [space-wizards/space-station-14#6154]
## Description
LobbyCharacterPreviewPanel doesn't account for species and is hardcoded to spawn a MobHumanDummy

**Screenshots**
Slimeperson but it uses a Human in the preview
![image](https://user-images.githubusercontent.com/60460608/149440505-c3ce6615-9921-48cb-82ad-70c81bdc3c00.png)

**Comment by moonheart08** [comment]
> LobbyCharacterPreviewPanel

Ah shoot did I miss a file

**Comment by ZeroDayDaemon** [comment]
seems so

https://github.com/space-wizards/space-station-14/blob/512d6a38c3cf0da68ddd17868f12f2f6dd4a316d/Content.Client/Lobby/UI/LobbyCharacterPreviewPanel.cs

**Comment by moonheart08** [comment]
Well the solution is easy, literally just checkout LobbyCharacterPreviewPanel from Outer Rim 14, as it's already correct there.

**Comment by ZeroDayDaemon** [comment]
> Well the solution is easy, literally just checkout LobbyCharacterPreviewPanel from Outer Rim 14, as it's already correct there.

I have done just that
