### ISSUE TITLE
Context menu + FOV preformance issue.

### ISSUE THREAD

**Issue by pointer-to-null** [space-wizards/space-station-14#6163]
## Description

Opening the context menu on a stacked items cause performance drop. But toggling FOV sort of "fix" this.
The video below shows how to replicate this.

https://user-images.githubusercontent.com/91910481/149550878-4f40c6d1-887d-4b3e-ba36-1fa2711fc24a.mp4

**Comment by ElectroJr** [comment]
Yeah it checks if the entity is visible and removes it from the menu if it isn't (e.g., if you rounded a corner).
toggling FOV means it just skips that check altogether, so it makes sense that it removes the performance hit.

Never really though about what would happen if there are far too many entities in one spot.
I guess the check can just be done less frequently / optimized somehow? Or removed altogether.

**Comment by ElectroJr** [comment]
Should be significantly better now.
