### ISSUE TITLE
Explain entity spawn window in tutorial

### ISSUE THREAD

**Issue by Moneyl** [space-wizards/space-station-14#621]
We should explain some of the snap/align options, and placement options in the tutorial. Also, shift + click is line placement mode, and ctrl + click in box placement mode for both the entity and tile spawners.

**Comment by KroshkaMu** [comment]
I'm doing this. If I'm not finished until 1.02.2020 - feel free to take over.

**Comment by AJCM-git** [comment]
This can be closed
