### ISSUE TITLE
Rewrite access component + ID Computer UI

### ISSUE THREAD

**Issue by Peptide90** [space-wizards/space-station-14#6218]
## Description
So access component needs to support:
- [x] Hidden access levels that don't show on the ID card (for antags).
- [ ] An all access flag for captain and centcom (to reduce duplicated access tags).
- [ ] Rework ID console to have nicer segreagation?

And from other issues:
- [ ] Support being written to an airlock board when hit with an ID #5353, similarly for private crates.
- [ ] Support per station access #5683

**Comment by ShadowCommander** [comment]
Related:
Change AccessReader to use bitmasks for faster AI pathfinding #3595

**Comment by mirrorcult** [comment]
not super actionable + mostly done
