### ISSUE TITLE
Spawners need to handle parent changes / de-anchoring.

### ISSUE THREAD

**Issue by ElectroJr** [space-wizards/space-station-14#6226]
If you delete the tile underneath a spawn point (e.g., the one of the late join ones), the it de-parents from the grid and just sits in space. Using the sandbox menu to respawn leads to a debug assert error. I think this might've only become apparent after space-wizards/RobustToolbox/pull/2415.

The spawn points should probably just delete themselves when the grid tiles underneath them are deleted? I'm not sure. Does the server handle there being no spawn points if the whole station is wiped?

**Comment by mirrorcult** [comment]
im like 90% sure this is not a problem now
