### ISSUE TITLE
Ghosts can warp / spectate holoparasite (we need a way to hide players from ghosts).

### ISSUE THREAD

**Issue by Peptide90** [space-wizards/space-station-14#6232]
## Description
Ghosts can currently follow / warp to a holoparasite, potentially giving away a traitor. This is meta knowledge but can we trust players not to use this knowledge even unknowingly or passively when they're brought back into the round?

Also it makes sense to have the ability to hide certain players / characters from the spectate menu depending on conditions like if they're set foot on the station yet (so nukies aren't revealed while still preparing for example).

**Comment by mirrorcult** [comment]
i dont think this is necessarily an issue but being able to hide people from the spectate menu is probably good anyway
