### ISSUE TITLE
Magboot stomping

### ISSUE THREAD

**Issue by PaulRitter** [space-wizards/space-station-14#6236]
from Beter#9960 on discord
> How it works on /vg/: deactivate magboots, aim for someone on the floor( head for best results) click them, boots activate and they get slammed into the floor

this has a chance to gib the head

**Comment by mirrorcult** [comment]
this needs further elaboration as to why it would be beneficial, we dont even have targeting currently so i dont see why this would be a feature request

**Comment by PaulRitter** [comment]
i really dont get the request, how is it not clear how this would be "beneficial"? this could also be implemented without targeting

**Comment by PJB3005** [comment]
> this needs further elaboration as to why it would be beneficial

It's epic and I get to roleplay as Isaac Clarke

**Comment by mirrorcult** [comment]
i was right 2 years ago this is really not actionable and we dont even have targeting
