### ISSUE TITLE
Generators don't consume fuel

### ISSUE THREAD

**Issue by Peptide90** [space-wizards/space-station-14#6240]
## Description
Currently generators are an infinite source of power as they don't consume any fuel.

We need a generator component that consumes fuel from an inserted tank to produce power and that stops producing power when the fuel runs out (maybe even spit the container out as an indicator or at least stops playing the sound of the generator to indicate it is off).

**Additional context**

Similar issue to #5815 except they will consume plasma (in proportion to?) the amount of radiation they take, but still produce power in relation to the amount of plasma used so I can see generator component being quite versatile. E.g.

```
- type: Generator
   fuel: PlasmaTank
   trigger: time (or radiation in case of rad collectors).
```

Whether generator component is responsible for power output or not is up to whoever is taking this on.

**Comment by lajolico** [comment]
Working on this now. I am making a generator component and system, allowing for other generators to be included.

**Comment by Peptide90** [comment]
> Working on this now. I am making a generator component and system, allowing for other generators to be included too

Excellent! Will complement #6455 very well. If you'd like to discuss it any hmu on discord.

I should add it would be nice to specify if and how much fuel the generator should start with on round start. Also slightly related would be having the generator make noise or change sprite state depending on fuel status (like apc visualiser) but that's fine being out of scope - simply consuming fuel would be a good start point so thanks for taking it on.

**Comment by lajolico** [comment]
@Peptide90 Yeah, I am just got it to accept a fuel and then start. Now I am working on consuming fuel, then ejecting. And yes I would like to add functionality, where if the fuel is spent either change the icon state or make a noise. I'll message you on discord sometime this week, just busy with school and life, haha.

**Comment by deltanedas** [comment]
this was done
