### ISSUE TITLE
Flares and Torches don't start fires

### ISSUE THREAD

**Issue by Peptide90** [space-wizards/space-station-14#6243]
## Description
As title.

Similar issue we've had in the past with lots of things. Matches ignite fires now and lighters use a welder component to achieve this.

Whether we rewrite the whole thing to have a consistent component or not I'll leave that to you.

**Comment by Insineer** [comment]
Shouldn't this be closed? Looks like issue should be linked to PR #13555 with `fix` or `close` tag.

**Comment by Jrpl** [comment]
PR https://github.com/space-wizards/space-station-14/pull/13555 fixes this. This can be closed.
