### ISSUE TITLE
Implement placement of TableParts

### ISSUE THREAD

**Issue by ShadowCommander** [space-wizards/space-station-14#627]
Currently TableParts don't do anything. They should create a table when activated.

**Comment by chairbender** [comment]
Taking on this one to get my feet wet. Not sure if it still makes sense to use table parts to construct stuff since it's easier to just use the construction menu, but it's a good learning exercise anyway.

**Comment by chairbender** [comment]
decided to just remove table parts - doesn't seem to be a reason to make construction more complicated, building tables directly from 2 metal is good enough
