### ISSUE TITLE
Permissions channel should sort by username

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#6274]
Right now it's by chronological order which is very annoying.

**Comment by manfredlarsson** [comment]
I'll take a look at this

**Comment by Jrpl** [comment]
This looks to be fixed. Admins are sorted by username in Permissions Panel.
https://github.com/space-wizards/space-station-14/blob/9d3fb0883cd7f3ae0ba66c4680525cb14a970813/Content.Client/Administration/UI/PermissionsEui.cs#L206
![image_2023-11-12_013649780](https://github.com/space-wizards/space-station-14/assets/30051988/d5a3c340-a3f0-4937-8fbd-719e58fb6fec)
