### ISSUE TITLE
Show the name and job/role from a character's ID on right-click

### ISSUE THREAD

**Issue by Willhelm53** [space-wizards/space-station-14#6296]
## Description

More of a feature request, and it may tie in with oldchat / examinelog but I wanted to capture it on Github.

When a user right-clicks on a character, it should show the job or role from their ID in brackets next to their name. This will help newer players establish the link between the different jobs and their uniforms, and will help people identify each other in general.

@Peptide90 if you happen to find any issues this is related to, would you please link them to this one?

**Comment by Willhelm53** [comment]
I might be interested to tackle this part, but I heard this piece would need more discussion on the maintainer side about how it would work. I'm not quite up to speed on ECS just yet so I might leave it alone for now.

**Comment by EmoGarbage404** [comment]
we have ID examine in the examine menu
