### ISSUE TITLE
Energy Sword sprite doesn't update when hacked

### ISSUE THREAD

**Issue by Mirino97** [space-wizards/space-station-14#6298]
## Description
If you hack an Energy Sword, the inhand sprite doesn't update to the rainbow version, nor does the RBG lighthing effect gets applied.
Just writing this down since I plan to fix it, that last part of the sprite coloring and lighthing effect wasn't added before it got merged.

**Comment by Delete69** [comment]
I spawned some just now and when turned on the light emitted from the sword is the correct color, but the blade comes out white until I put it down and pick it back up, then the sprite takes on its real color.
