### ISSUE TITLE
Lights block lockers from being pushed by them. 

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#630]
Looks like their bounding box sticks out half a tile, stopping the locker dead in its tracks. Not the player though.
![2020-02-08_00-59-43](https://user-images.githubusercontent.com/49448379/74082411-7455d080-4a0e-11ea-8d9b-c266568154e6.gif)

**Comment by AJCM-git** [comment]
fixed by physics rewrite
