### ISSUE TITLE
Holoparasite can hit itself to do damage to its owner

### ISSUE THREAD

**Issue by BasedUser** [space-wizards/space-station-14#6306]
## Description
Ditto.
1. Infest yourself with a holoparasite.
2. Have someone else become your holoparasite (or aghost+ghost role)
3. If you're visible (#5964) click on yourself with harm intent. Otherwise, rightclick and click yourself in the menu.

**Additional context**
Found live on Wizard's Den Lizard.

**Comment by lzk228** [comment]
seems fixed
