### ISSUE TITLE
Sitting on a chair causes the player to flicker between the station and deep space

### ISSUE THREAD

**Issue by Veritius** [space-wizards/space-station-14#6316]
## Description
Sitting on a bar stool makes you flicker in between the station and space. Getting off at the wrong time may send you into space.

**Screenshots**
https://user-images.githubusercontent.com/45957058/151116994-c3d4b31c-558a-4559-8ede-2a1c7ca5212e.mp4

**Additional context**

**Comment by Veritius** [comment]
After further testing, this appears to happen on everything you can sit on.

**Comment by metalgearsloth** [comment]
> Screenshots
> video file of it happening.zip

Yeah I'm not downloading a zip, you're gonna have to embed.

**Comment by wrexbe** [comment]
Sometimes it flickers, sometimes you just get warped into space

**Comment by Veritius** [comment]
No further issues found after a recent update
