### ISSUE TITLE
Directional windows prevent items from being picked up on the same tile.

### ISSUE THREAD

**Issue by Pangogie** [space-wizards/space-station-14#6323]
1: Place a directional window.
2: Place an item on the same tile.
3: Presto, you (sometimes) cannot grab it anymore.

I suspect this has to do with the draw depth change in #6279.

**Comment by Delete69** [comment]
#6305

**Comment by metalgearsloth** [comment]
Probably related to https://github.com/space-wizards/space-station-14/issues/6324

**Comment by Delete69** [comment]
I've tested extensively, this seems fixed.
