### ISSUE TITLE
Windoor, railing, thindow, 50% unsecure. Easily walked right over.

### ISSUE THREAD

**Issue by Delete69** [space-wizards/space-station-14#6324]
## Description
If you approach either one of these entities from the adjacent tile, you can walk right over it. Tested on local host.

**Screenshots**

https://user-images.githubusercontent.com/95458399/151205459-7a8e6227-46d5-4763-8b1d-d63fefa224d9.mp4

**Additional context**

**Comment by metalgearsloth** [comment]
Fixed in https://github.com/space-wizards/RobustToolbox/pull/2463
