### ISSUE TITLE
Disposal Units will endlessly pressurize

### ISSUE THREAD

**Issue by Fishfish458** [space-wizards/space-station-14#6332]
## Description

When attempting to flush an object quickly after flushing the previous, the disposal unit will endlessly pressurize.
If you hit the flush button the pressure will reset but still endlessly pressurize

if you restart the power it will function again, can break upon attempting to flush quickly again.

**Screenshots**

![won't send](https://user-images.githubusercontent.com/47410468/151285116-31b10031-980d-4f1e-a170-399fc880006a.gif)

**Additional context**

**Comment by Willhelm53** [comment]
Seems related: "if you flush disposals a few times, it starts to flush itself automatically every time its ready"
https://discord.com/channels/310555209753690112/790656972801572905/938837697227812925
