### ISSUE TITLE
Gravity Generator should be constructible.

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#6333]
This would mainly be a feature for servers focused more on construction, but it's also a nice way to de-magic more of the game, and to make sure the gravity generator is always repairable.

**Comment by Peptide90** [comment]
Would a precursor to this be large machine construction (4x4, 4x6)? Or would we be happy sticking it in current construction?

**Comment by mirrorcult** [comment]
not super agreed on + tiny one is not that hard to procure
