### ISSUE TITLE
Applying RGBController to a person then removing it makes them invisible.

### ISSUE THREAD

**Issue by Pangogie** [space-wizards/space-station-14#6347]
1: Apply RGBController to a player.
2: Remove it.
3: Presto, they're invisible until you replace the RGBController.

¯\_(ツ)_/¯

**Comment by ElectroJr** [comment]
I can't seem to reproduce this locally, neither with myself or with Urists, with or without point light components.
Though there does appear to be some odd behaviour when adding point lights to entities I never noticed before, but unrelated to RGB sutff.

Also you dropped this \\

**Comment by Pangogie** [comment]
Ya, I'd guess it's some PVS shenanigans.
