### ISSUE TITLE
Construction graphs for SMES are broken

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#6363]
## Description

How to replicate:

- Build a machine frame
- Wire it and put the SMES board in
- Add the 10 capacitors
- Screwdriver it
- The board will shoot out instead of finishing the construction, and the capacitors will be lost.

**Comment by Kromabae** [comment]
you dont loose the capacitors, if you put board back in and then crowbar you get them back, but yes this broken and if Traitors ever decide to break all the SMES on a station then they can kill the power completely since no new SMESes can be built

**Comment by Peptide90** [comment]
Fixed in #6290
