### ISSUE TITLE
Crates can no longer be welded shut.

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#6365]
## Description

Because of a change in construction graphs, using a welder on a crate deconstructs it, making them unable to be welded shut.

**Comment by Peptide90** [comment]
This was the original reason I used screwdrivers but the graph should check to make sure the crate is open first...maybe it's only checking for locked so easy fix, will do it later today.

**Comment by Elijahrane** [comment]
@mirrorcult changed the deconstruction back to using a screwdriver, so I assume this is fixed?
