### ISSUE TITLE
Unify DoAfter interactions

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#6367]
Vaguely related to https://github.com/space-wizards/space-station-14/issues/6132

Currently do_afters are done different ways in order to make them unique / cancellable. From having ECSd a few recently I think using the cancel token and then cancelling on repeat interactions is probably best rather than using a bool on the entity.

i.e.
tile prying -> Repeated clicks do nothing
Injecting -> 2nd click cancels, 3rd click would start a new one, etc.

It seems to be a bit cleaner for handling and would be better as the unified approach IMO.

**Comment by keronshb** [comment]
Fixed with #14609
