### ISSUE TITLE
The t ray scanner can leave pipes and cables visible.

### ISSUE THREAD

**Issue by juliangiebel** [space-wizards/space-station-14#6373]
## Description

I found a dropped t ray scanner and still visible pipes and cables. The pipes where far enough away from the t ray scanner that they shouldn't be visible anymore.

**Screenshots**

![T-Ray_scanner_bug](https://user-images.githubusercontent.com/8915246/151657335-275bf069-7dab-4cf9-b1b4-8f9dd545ac29.PNG)

**Comment by crizzeone** [comment]
I was not able to reproduce that behaviour

**Comment by Pangogie** [comment]
It's probably something to do with PVS or missing a tile update.

**Comment by Willhelm53** [comment]
I've seen this as well! Didn't connect it to the t ray scanner at first but it makes sense. Not sure how to reproduce.

**Comment by mirrorcult** [comment]
i havent se en this replicated in forever, and there was a fix PR
