### ISSUE TITLE
Seal classes (mainly systems and components)

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#6376]
tl;dr change stuff like `public class <WhateverSystem/Component>` to `public sealed class <WhateverSystem/Component>`

https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-6/#peanut-butter

Free performance right on the table (mainly for systems).

**Comment by PJB3005** [comment]
Have I got the analyzer for you https://github.com/space-wizards/RobustToolbox/pull/2469
