### ISSUE TITLE
LineEdit doesn't scroll along when you type long messages

### ISSUE THREAD

**Issue by ProfanedBane** [space-wizards/space-station-14#639]
What it says on the tin, you can't see the full contents of what you're typing.

**Comment by tentekal** [comment]
Addressing this in RobustToolbox. So far I've got a rudimentary fix.

**Comment by tentekal** [comment]
Done in my PR for RobustToolbox. Do we want to merge that before I finish other upgrades to LineEdit.cs? I'm not sure how quickly we need "polish" features like this.
