### ISSUE TITLE
Glass airlocks are opaque

### ISSUE THREAD

**Issue by WlarusFromDaSpace** [space-wizards/space-station-14#6395]
## Description

Glass doors are opaque and as such do not let lasers through.
**Screenshots**

![opaqueglassairlocks](https://user-images.githubusercontent.com/44726328/151712640-4ba4d214-8f27-4f19-aadf-fe4928b76e28.png)

**Additional context**

![pjbsaidso](https://user-images.githubusercontent.com/44726328/151712676-1d7f12e2-b4ae-4a06-929a-bf594840adfb.png)

**Comment by Willhelm53** [comment]
This looks closeable
