### ISSUE TITLE
Server can enter a lagged state until a player leaves

### ISSUE THREAD

**Issue by ProfanedBane** [space-wizards/space-station-14#641]
Unsure what causes this but the server started lagging hard, with f3 saying we were getting 0.2kb/s bandwidth down. Issue completely disappeared when a player left the server (whether it's specific or just the first player to leave is unknown).

This happened twice today so it wasn't a one-off, the events leading up to it was spawning several hundred thousand hand grenades to bring bandwidth up to 500kb/s then restarting the round before the process completed.

The player who fixed the issue by leaving said they were lagging with the game alt-tabbed.

**Comment by ProfanedBane** [comment]
@PJB3005 did a trace, seems to be netserializer that's having a bad time.

**Comment by PJB3005** [comment]
[trace.speedscope.zip](https://github.com/space-wizards/space-station-14/files/4174567/trace.speedscope.zip)

Here's the trace for what it's worth. I think it's just the sheer size overloading the connection and Lidgren choking on that.

**Comment by AJCM-git** [comment]
Is this fixed?

**Comment by PJB3005** [comment]
It should be.
