### ISSUE TITLE
Holoparasites can attempt to uncuff their host breaking the uncuff action.

### ISSUE THREAD

**Issue by Pangogie** [space-wizards/space-station-14#6410]
1: Have a holoparasite attempt to uncuff their host.
2: Attempt to uncuff any other way.
3: You cannot never be uncuffed. You must be killed.

Only witness account I have. Haven't tested it myself.
![image](https://user-images.githubusercontent.com/7548248/151757714-4e05af36-c585-4aca-a250-760b94831687.png)

**Comment by lzk228** [comment]
cannot reproduce
