### ISSUE TITLE
Pilotted grids don't have physics interaction with each other

### ISSUE THREAD

**Issue by ProfanedBane** [space-wizards/space-station-14#642]
This was previously a thing so I'm unsure what happened.
We had two separate shuttles that could fly through each other, collision with the non-shuttle station grid worked fine.

**Comment by PJB3005** [comment]
Pretty sure this is the same issue as #643

**Comment by ProfanedBane** [comment]
Yup I just tested it, once a grid is turned into a shuttle it loses all collisions.
