### ISSUE TITLE
Not all water sources have a delay when drinking from them

### ISSUE THREAD

**Issue by aaronmell** [space-wizards/space-station-14#6423]
## Description

Example, you can drink from a bucket, or a hydroponics bay with no delay.

**Screenshots**

**Additional context**

**Comment by metalgearsloth** [comment]
Probably fixed in https://github.com/space-wizards/space-station-14/pull/6406

**Comment by HoofedEar** [comment]
Closing, appears to be fixed by #6406 (tested bucket for example, has delay now)
