### ISSUE TITLE
Sunrise map missing while being voteable.

### ISSUE THREAD

**Issue by Charlese2** [space-wizards/space-station-14#6424]
## Description

Sunrise is voteable, but doesn't actually exist.
```
No map found: /Maps/sunrise.yml  
Sawmill=map
```

**Screenshots**

![image](https://user-images.githubusercontent.com/1207515/151913926-18bfceb2-8f6d-436f-9b22-fefd06e4fd07.png)

**Additional context**

**Comment by Pangogie** [comment]
What in the world. Sunrise is an escape pod, by the way.
