### ISSUE TITLE
When grids are turned into shuttles they lose all collisions.

### ISSUE THREAD

**Issue by ProfanedBane** [space-wizards/space-station-14#643]
Placed a seat on the station grid and found it was locked in place from some collision, teleported it west a bit and all the players that came with it could start walking and shooting through walls.

**Comment by PJB3005** [comment]
This is probably because of the `DynamicTree` stuff @Tyler-IN

**Comment by SweptWasTaken** [comment]
Not an issue. Source: Sloth.
