### ISSUE TITLE
People spawn inside of an escape pod on pillar

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#6459]
Rane says this apparently happens on saltern and packed too. But no one else has testified to that

**Screenshots**
![image](https://user-images.githubusercontent.com/19853115/152614918-f9d2e3ac-9404-402b-aca6-bc6b62f013ff.png)

**Additional context**

**Comment by Peptide90** [comment]
I think this is related to the escape pod being a second grid with its own 0,0 (as that's apparently the issue).

I've added more spawns but in the meantime it's probably best to remove the pod till we get pod power anyway.
