### ISSUE TITLE
Clear default components from stationstation.yml

### ISSUE THREAD

**Issue by ShadowCommander** [space-wizards/space-station-14#647]
Right now `stationstation.yml` contains old component values, so it overwrites the new ones that get added to the prototype YAML files. If someone could go through all the components and remove the ones that are the same as default, that would be great.

Currently this causes a bug where the `PowerCellSmallHigh` that get spawned on the map go through walls when thrown.

https://github.com/space-wizards/space-station-14/blob/5e58ae8a0aa07af7f1ed6a8558cf65fbb2941163/Resources/Maps/stationstation.yml

**Comment by PJB3005** [comment]
The problem here is that the serialization system can't detect correctly that the physics bodies are value-wise equal.
