### ISSUE TITLE
Hand Labeler only removes labels.

### ISSUE THREAD

**Issue by Pangogie** [space-wizards/space-station-14#6471]
Hand Labeler only removes labels.
It will not add a label to something.

**Comment by ElectroJr** [comment]
It seems to work fine for me on master. Are you using it in your hands to set the label? (you don't set label by clicking on something else)

**Comment by Pangogie** [comment]
Okey... It's working now when I try to reproduce it... I have no idea why it wasn't working before.

**Comment by ElectroJr** [comment]
I guess its possible theres some other bug that causes it to stop working after some time or something.... I guess re open this if it happens again?

**Comment by Kromabae** [comment]
it's a bug where the label on the machine doesn't apply properly, same issue on the disposal taggers and routers

**Comment by civilCornball** [comment]
The ‘delay’ between equipping a labeler and being able to change its label is oddly similar to the ‘delay’ that occurs when you pick one up.
Spitballing here, ‘cause I currently can’t test: What if the ‘use delay’ was removed? Would that fix it?
