### ISSUE TITLE
Spinning (moving?) a grid unbuckles everyone on grid

### ISSUE THREAD

**Issue by BasedUser** [space-wizards/space-station-14#6478]
## Description
1. Equip a grid with gyroscopes/thrusters
2. Start rotating with the shuttle console
#. Everyone currently buckled will be unbuckled, and attempting to buckle will teleport and unbuckle you.

**Screenshots**
N/A.

**Additional context**
Discovered on a random Saltern shift.

**Comment by BasedUser** [comment]
can't reproduce locally anymore

**Comment by ElectroJr** [comment]
Trying to buckle yourself while the station is spinning is still buggy. Not sure about it un-buckling people who are already buckled though.

**Comment by Acruid** [comment]
Around Jan 10th I was reproducing this. I'm assuming the radial velocity of the player from the grid spinning is messing with the "too far away, unbuckle the player" code.

**Comment by moonheart08** [comment]
Cannot repro, eshuttle regularly moves great distances with buckled players.
