### ISSUE TITLE
You take too little oxygen to breathe

### ISSUE THREAD

**Issue by BasedUser** [space-wizards/space-station-14#6479]
## Description
When using an internals oxygen tank, you only need 3.1 kPa to breathe without the o2 level popping up. Normally it's be somewhere around 16 kPa. You can also survive indefinitely on 2.5 kPa of pure oxygen, but if you were asphyxiating prior 2.6 is recommended.

**Screenshots**
![image](https://user-images.githubusercontent.com/21104932/152653473-4ec961e4-e24c-4821-97f9-9fe6337e7ea9.png)

**Additional context**

**Comment by mirrorcult** [comment]
fixed by #6022
