### ISSUE TITLE
Pillar Armoury has basically no weapons

### ISSUE THREAD

**Issue by ghost** [space-wizards/space-station-14#6488]
## Description
Not sure if this should go into 'issue' but it is an issue and may be a WIP thing. There is currently nothing weapons-wise for sec, which means no lethals and barely any non-lethals on Pillar. On packed there are 2 SMGs, 1 shotgun with MANY shells of non lethal and lethal, and two cog carbines which are good for basic sec work. On pillar there is 1 kammerer shotgun with minimal ammo and that's it. HOS doesn't get his SMG. Is there a reason for this?

To fix this I'd like HoS to get his SMG back with some ammo, and for at least 3 drozd guns to be put in the armoury.

**Comment by Peptide90** [comment]
Resolved in map update 3
