### ISSUE TITLE
Implement y-sorting

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#651]
Right now, there doesn't seem to be any kind of sorting for mobs and other entities. This can make things look weird at times:
![sort](https://user-images.githubusercontent.com/6766154/74089915-59cf3600-4aa6-11ea-8c3f-763ffdf3494e.png)
Ideally, draw order for some (but not all, maybe?) entities should be relative to their Y position on the screen, making the ones that are further up drawn first, and the ones below drawn later.

**Comment by PrPleGoo** [comment]
Working on this and #370
