### ISSUE TITLE
Tooltips can open at 0,0

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#6518]
To replicate (and to see what I'm talking about):
- Mouseover alerts a little bit
- Take mouse offscreen (i.e. to the right)
- Tooltip now opens at 0,0

Ideally tooltip either never opens or opens at the hover spot.

**Comment by ElectroJr** [comment]
If the mouse leaves the screen, does it just never call mouse exist or whatever? I guess you could fix it by changing that, or making tooltips check if the position is valid (i.e., like #6191).

Also I think this should be an engine issue.

**Comment by metalgearsloth** [comment]
mousepos gets set to 0,0 when off screen.

**Comment by mirrorcult** [comment]
i havent seen this in forever
