### ISSUE TITLE
Map shouldn't be created until StartRound

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#6520]
If it's deleted somehow between PreRoundSetup and StartRound the game crashes. This shouldn't happen normally but apparently it can and it'd be better to just protect against it IMO.

Another benefit is if people could vote on another map during lobby then we aren't needlessly making it beforehand.

**Comment by moonheart08** [comment]
I was gonna do this but I believe @Zumorica or @mirrorcult told me it wasn't a great idea?
dr
