### ISSUE TITLE
'mapping 2 emptymap.yml' no longer creates a blank map for mapping.

### ISSUE THREAD

**Issue by Delete69** [space-wizards/space-station-14#6535]
## Description

This has been an issue for a month or so now, I keep seeing people run into the issue with new mappers in #cartography and having to guide them through a band-aid fix, shown below. Looked up the issue here and nobody has bothered to add it yet. 

**Screenshots**

![image](https://user-images.githubusercontent.com/95458399/152842227-fb0ca8a8-053d-4414-b8bf-17f75f2d89e8.png)
![image](https://user-images.githubusercontent.com/95458399/152842438-d6bf684c-90d0-41c9-9bda-78bdba3cbcd7.png)
![image](https://user-images.githubusercontent.com/95458399/152842947-dbb7bc14-32f4-4fb8-9474-e921d08d468a.png)

**Additional context**

**Comment by SweptWasTaken** [comment]
I might be OOTL but I don't think this is how this command ever worked.

If you want an empty map you could use the one in `Maps/Test/empty.yml`.  And do `mapping 2 Maps/Test/empty.yml`.

**Comment by Delete69** [comment]
Definitely not up to date on that. https://docs.spacestation14.io/en/content/mapping

It worked as described in the mapping tutorial, but broke like a month ago. I'm just being the guy to finally report it.
