### ISSUE TITLE
"Current map" can lie to you

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#6537]
## Description

Loaded in and the map was actually Pillar, not Bagel

This is probably caused by the map vote picking Bagel during the lobby which changes the "current map" even though Pillar was loaded in when the lobby actually started

The "current map" should probably really be "next map", and "current map" should use a different mechanism for figuring out what map is currently loaded

![image](https://user-images.githubusercontent.com/19853115/152852660-9de6920e-933a-44f3-82e5-716c66f04edd.png)

**Additional context**

**Comment by themias** [comment]
Steps to reproduce:
1. Set server config map_rotation = false
2. Start server, join, and start round
3. Call a map vote
4. Start a second client and late-join the lobby
5. The current map will wrongly display as the next map from the vote

The also happens with game mode.  Repeat the steps with game mode vote and see the same results. The wrong/next game mode is also displayed on the Round End window. Not sure if we want to fix that as part of this or make a separate issue.

(I'm not sure if map voting is intended to work with map rotation, but the code looks like it ignores vote results with map rotation on. Should map voting be disabled if rotation is on?)
