### ISSUE TITLE
Clientside movement

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#6540]
We agreed to try it, mainly for people with Argentinian levels of internet.
I had a potential idea on implementing it:
- Subscribe to ComponentGetStateAttemptEvent for transforms + physics and where the entity has a specific component (e.g. clientauthrotiativecomponent) then ignore them for netsync. This is mainly because we can use it for their own actor entity + stuff like board games. Main thing is to work out how expensive this may be given it's adding a HasComp to every time transform is dirty (probably nowhere near as bad as MoveEvent itself) and means they always have to use the slow path for PVS.
- Whenever the client moves during IsFirstTimePredicted have them send a message with their new position

**Comment by Acruid** [comment]
Allowing the client to inform the server where the player is positioned is how you get speed and teleport hacks.

**Comment by metalgearsloth** [comment]
another another conversation if we can make pushing not bad
https://discord.com/channels/310555209753690112/310555209753690112/940387150111858768
