### ISSUE TITLE
Welders cannot be refueled.

### ISSUE THREAD

**Issue by Pangogie** [space-wizards/space-station-14#6545]
1: Use a welder.
2: Try and refuel it on a fuel tank.
3: Be disappointed.

I've been vaguely hearing that this has been a bug for around a week, but no one ever confirmed it.

**Comment by Pangogie** [comment]
Same thing appears to be happening with syringes.

**Comment by SweptWasTaken** [comment]
> 1: Use a welder. 2: Try and refuel it on a fuel tank. 3: Be disappointed.
> 
> I've been vaguely hearing that this has been a bug for around a week, but no one ever confirmed it.

I believe this is because it's conflicting with the welder/fuel tank interaction between a lit welding torch and the fuel tank exploding.

**Comment by ElectroJr** [comment]
Actually it looks like I broke it with some anchorable changes. The welder tries to anchor the tank....
