### ISSUE TITLE
MIDI device interactions continue in crit/death

### ISSUE THREAD

**Issue by Veritius** [space-wizards/space-station-14#6555]
## Description
MIDI devices will only close the UI/stop playing music when you move away from them. Even unconsciousness, crit, and death, cannot stop those sick jams. This also applies to ghosts. As long as you stay near the device, it keeps playing.

**Screenshots**
https://user-images.githubusercontent.com/45957058/152953672-6b9c2edd-e5c1-4486-ba10-d25244418a7e.mp4

**Additional context**
Start playing some tunes on a MIDI device. Open an airlock or do something that'll kill you.

**Comment by Willhelm53** [comment]
Can ghosts play instruments? Or is it more a case of "becoming a ghost doesn't interrupt your playing?"

Can a ghost approach a new instrument and begin playing it?

**Comment by Pangogie** [comment]
> Can ghosts play instruments? Or is it more a case of "becoming a ghost doesn't interrupt your playing?"
> 
> Can a ghost approach a new instrument and begin playing it?

Yes. Ghosts currently can hit Toggle UI and play instruments.

**Comment by Willhelm53** [comment]
#5226 exists but there's some nuance it seems. Behaviour may have changed over time.

**Comment by Mirino97** [comment]
Revived in #9221
