### ISSUE TITLE
PA Control Computer does not update power setting.

### ISSUE THREAD

**Issue by Pangogie** [space-wizards/space-station-14#6559]
1: Mess with the PA computer.
2: Notice that occasionally it won't sync the power level correctly.

I believe that the power level of the emitters is not syncing properly and it can get stuck with power 3, while the computer says power 1.

**Comment by UbaserB** [comment]
I havent seen this issue ingame nowadays

**Comment by Pangogie** [comment]
I am also pretty sure this has been resolved.
