### ISSUE TITLE
Status Effect Alert sidebar disappears and reappears sporadically

### ISSUE THREAD

**Issue by Willhelm53** [space-wizards/space-station-14#6570]
## Description

The sidebar window on the right side of the screen displaying health, hunger/thirst, buckled, handcuffed, stunned, and other status effects seems to disappear and reappear at random.

So far no one has been able to determine the steps to reproduce. Reported by multiple users in the Discord, and I've experienced it myself.

**Screenshots**

![image](https://user-images.githubusercontent.com/97707302/153088444-07509dab-4bd6-4818-a1d4-f661fd7cbc56.png)

It seems to collapse into this little square here. (I annotated this screenshot originally posted in Discord by user Raya Nebula)

**Additional context**

First reported on 2022-01-06 from what I can tell.

It has been speculated that the disappearance/reappearance can be triggered by a change in status effects (e.g. hunger or thirst getting worse over time).

**Comment by ElectroJr** [comment]
TODO: revert #6574 whenever this is fixed

**Comment by Willhelm53** [comment]
Discord user AbsolutePotato reports that this happens when they resize their chat window.

**Comment by ElectroJr** [comment]
I have come to the conclusion that drones are pilfering our alerts and running off with them.

https://user-images.githubusercontent.com/60421075/156610227-7a660ae1-6854-4e8e-b974-f45dc7b0c05b.mp4

So yeah, looks like somehow alerts get cleared when the sandbox menu spawns some client-side dummy entities. This also seems to happen with monkeys? There might just be entities somewhere on the map causing the same effect during regular gameplay.
