### ISSUE TITLE
MapRenderer can't paint decals

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#6575]
## Description

need to make a DecalPainter that runs before entity painting and after grid painting, and sorts by z-index

**Comment by AreaDenial** [comment]
This needs to be reopened, once again MapRenderer isn't painting decals.

**Comment by AreaDenial** [comment]
Step 1: clone the repo
Step 2: enter command `dotnet run --project Content.MapRenderer bagelstation`
Step 2: see that there are no decals
