### ISSUE TITLE
Airlock visuals ideaguys

### ISSUE THREAD

**Issue by ElectroJr** [space-wizards/space-station-14#6582]
Currently you can't construct various airlock types. There's already an issue for access permissions (see #5353), but visuals also need to be configurable. While this could just be done by somehow setting the door sprite, IMO:
- [ ] Airlock sprites should be made out of re-colourable layers. Make the door types just use different colour palettes.

Then do either (or both) of these:
- [ ] Make it so that door electronics used in construction set the colour palette of the door.
- [x] Add an airlock painter that can apply custom & pre-defined palettes (#7261)

And maybe:
- [ ] Add a new machine / device for editing the colour palettes of door electronics.
  - Possibly combine with door electronics access editing machine.
  - Put it somewhere in engineering.

**Comment by UbaserB** [comment]
This should be marked as completed because there are airlock painters and door accesses can be changed now using that new access changer thing
