### ISSUE TITLE
Hovering over pot plants cuts the sprite in half

### ISSUE THREAD

**Issue by Veritius** [space-wizards/space-station-14#6586]
## Description
As the title says. Hovering your mouse over a pot plant will cut the sprite in half.

**Screenshots**
![image](https://user-images.githubusercontent.com/45957058/153144063-c0eea115-d7b9-4ea8-8094-45839a00e7f4.png)
![image](https://user-images.githubusercontent.com/45957058/153144077-f35c43e9-65df-487d-b825-c1dfaec983a6.png)
![image](https://user-images.githubusercontent.com/45957058/153143102-a76efc01-9fbd-4bb8-82a0-72d1bcbf0cc3.png)
![image](https://user-images.githubusercontent.com/45957058/153143083-9edca699-cc34-4a34-917b-44aef5c237ca.png)

**Additional context**

**Comment by metalgearsloth** [comment]
Dupe https://github.com/space-wizards/space-station-14/issues/5455 (easy to miss when there's a typo in the title)

Fix PR https://github.com/space-wizards/RobustToolbox/pull/2511
