### ISSUE TITLE
Admin Commands

### ISSUE THREAD

**Issue by ShadowCommander** [space-wizards/space-station-14#659]
- [ ] Teleport other players
- [ ] Kick player
- [ ] Delete verb
- [ ] Delete items in space
- [ ] List players

**Comment by Moneyl** [comment]
I know we have erase mode but would also be handy to have a "delete entity" option in the right click menu for one off deletions

**Comment by Zumorica** [comment]
As a heads up, there's already a [kick command](https://github.com/space-wizards/RobustToolbox/blob/76956448e6698c24da709234fcca4352cb9d733e/Robust.Server/Console/Commands/PlayerCommands.cs#L89) implemented in the engine.

**Comment by Zumorica** [comment]
...And as I check the link in my comment above as well, I realize there's also a command for [teleporting players to other coordinates](https://github.com/space-wizards/RobustToolbox/blob/76956448e6698c24da709234fcca4352cb9d733e/Robust.Server/Console/Commands/PlayerCommands.cs#L19) as well.

**Comment by ShadowCommander** [comment]
Well, we have player teleport, but that doesn't allow teleporting other players. It would also be nice to have a teleport command that works with teleporting one player to another.

**Comment by Zumorica** [comment]
Oh, I misunderstood then! It shouldn't be too difficult to add such a command in that case. Whoever decides to do it can take a look at the other teleport command to get an idea of what to do.

**Comment by Moneyl** [comment]
There's also a [listplayers](https://github.com/space-wizards/RobustToolbox/blob/76956448e6698c24da709234fcca4352cb9d733e/Robust.Server/Console/Commands/PlayerCommands.cs#L57) command, but neither it nor kick have been added to any groups so can only be used from the server console.
![Content Server_nLeSRpkfSd](https://user-images.githubusercontent.com/8206401/74127076-87e86f00-4ba7-11ea-9761-54a73b411c55.png)
Gonna run through and make sure everything is at least registered to the admin role and PR it.

**Comment by Moneyl** [comment]
Maybe would be useful to have a kick verb though.

**Comment by PJB3005** [comment]
A verb requires you to actually track down the mob they're currently in, so that seems quite inconvenient.

**Comment by Moneyl** [comment]
You're right, didn't think of that. Maybe would be useful for very clear cut cases of "hey this assistant just blew up half of medbay and they aren't an antag". What might be more useful in situations like that is a freeze verb so admins can ask them what the hell they're doing before kicking/banning and keep them from doing more.

**Comment by Moneyl** [comment]
Update: `listplayers` and `kick` are now accessible to the admin group via the client console.

**Comment by Jackw2As** [comment]
- [ ] List Roles
Would be another useful command.

**Comment by SweptWasTaken** [comment]
Fixed by #1648 , closing.
