### ISSUE TITLE
Targeting doll is global

### ISSUE THREAD

**Issue by ShadowCommander** [space-wizards/space-station-14#660]
This should not be.

**Comment by Zumorica** [comment]
The targetting doll also seems to be global.

**Comment by ShadowCommander** [comment]
Oops yeah, targeting doll

**Comment by ShadowCommander** [comment]
Toggling this lags the server a lot

**Comment by RemieRichards** [comment]
presumably BECAUSE it's global.
everyone's sending toggles and receiving other people's toggles (combat mode/doll)
