### ISSUE TITLE
Grenade and Syndicate minibomb timer sounds don't play

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#6606]
## Description

Spawn either, activate and listen. No countdown. I think the light on the sprite should flash too.

**Comment by SweptWasTaken** [comment]
> It was removed intentionally in a PR. Personally I think should be reverted.

Oh. Well i've had both blow up in my hand after activating them since I thought the trigger didn't work since the sound wasn't playing nor the blinking animation working on the sprite itself. 

The timer sound effects shouldn't have been removed with the blinking sprite not working imo.

**Comment by Fishfish458** [comment]
Could have a REALLY shortrange "CLICK" that plays, if someone is right next to you they could hear it
