### ISSUE TITLE
Gas canister slider event spam

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#6626]
Turns out this is more involved than I thought.

The problem is that a bunch of states are getting sent every 0.5s from the server which means that even if the client doesn't send a message every frame the slider changes you're still getting the text bulldozed by the server in the interim.

Ideally when it's actually stateful you won't get the uggo mispredicts where the slider snaps to the new value either.

**Comment by ElectroJr** [comment]
I Just moved the ui-dirty call after the "has the pressure actually changed" check and it seems to work fine
