### ISSUE TITLE
Salvage Grids are Causing Poison Damage upon contact with the grid.

### ISSUE THREAD

**Issue by Kromabae** [space-wizards/space-station-14#6630]
## Description
Walk onto grid, start taking poison damage. at first we thought it was space carps having poison added to them but it isn't.
it's as if there's a constant poison gas over the salvage
**Screenshots**
no screenshot sorry

**Additional context**
so far the tested grids are the theater and the one that used to have a magic cloest and now has a botanist locker instead. did test another grid but wasn't on it that long to notice poison damage

**Comment by Pangogie** [comment]
Can confirm. Did some tests with them. 
There's no gas on the salvage grids. Space Carp aren't doing weird poison damage.

I have how this is happening.

**Comment by Kromabae** [comment]
will test if slime is affected

**Comment by mirrorcult** [comment]
this is likely because you're exhaling CO2 and then inhaling it again, need to add a lower threshold for how much can damage you
