### ISSUE TITLE
Drone tools mispredict

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#6636]
## Description

`DroneToolComponent` is shared, but `DroneSystem` is server, so client doesn't know theyre un-droppable

https://user-images.githubusercontent.com/19853115/153513452-03a27a13-1dba-4aac-a3bd-12bc5a92cf16.mp4

**Comment by Elijahrane** [comment]
Is the solution moving the system to shared? I have no clue how prediction works

**Comment by mirrorcult** [comment]
yeah the drone tool event stuff should just be moved to shared

**Comment by Elijahrane** [comment]
You can assign this to me I'll get it done some time this weekend

**Comment by ElectroJr** [comment]
> Is the solution moving the system to shared? I have no clue how prediction works

If all you want is to prevent drop-mispredicts, but not adding other predicted interactions or something, then all you need is to move the event subscriptions that block the interactions into shared code, so the client knows the event should get cancelled when it tries to drop it.

Also didn't get round to reviewing it, but just looking at the PR you could probably make use of container events. Specifically:
- `ContainerIsRemovingAttemptEvent` is directed at the container
- `ContainerGettingRemovedAttemptEvent` is directed at the entity being removed.
If you cancel those, it should prevent almost all removal from containers, both inventory & hands, which I think is what you want for drones? The one exception is if someone uses `ForceRemove`, but at that point the hand-events also wouldn't stop it.
