### ISSUE TITLE
Drones AA is a bit dangerous

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#6637]
## Description
Allows them to accidentally or purposefully let people into places they shouldn't be.

**Comment by ElectroJr** [comment]
Unless the stations are meant to get some sort of AI-free zones or something eventually in case of malf AI, all access makes sense and I don't think it should be changed.

I'd say people following others with more access and sneaking in behind them is a valid strategy and people with access sometimes need to be careful and close doors behind them. Though obviously if they're abusing / purposefully letting people in then uuhhh role bans when?

Also something I'm not clear on/up to date on, given that they can't talk and #6640, I assume these drones are meant to be the type that just completely ignores players and just exists to maintain the station?

**Comment by ike709** [comment]
https://github.com/OracleStation/OracleStation/pull/622

**Comment by metalgearsloth** [comment]
IMO the best solution is just letting them go under doors yeah. Giving them AA to open any door is just too much grieferbait for a ghost role and steps on engiborgs toes a bit too much.

**Comment by moonheart08** [comment]
Yea hatches are what i'm familiar with, and they're p easy to add, being just an overlay over the original sprite.

**Comment by ElectroJr** [comment]
It might be a little weird w/o tile based movement because of the ability to move around "inside" of the door, but yeah I guess this would be a pretty good fix. And if its just disabling the collision & doing a little animation on collide, the actual door code wouldn't be that hard. & prediction is trivial.
