### ISSUE TITLE
Delete grid when all tiles are removed

### ISSUE THREAD

**Issue by ShadowCommander** [space-wizards/space-station-14#664]
When all the tiles of a grid are removed it should delete the grid.

**Comment by AJCM-git** [comment]
Tried to reproduce doing the following: 
Create a grid by placing tiles in space.

**Comment by AJCM-git** [comment]
Tried to reproduce doing the following:

1. Create a grid by placing tiles in space
2. Check if the grid exists with the f3 menu
3. Delete tiles
4. Check f3 menu
5. Grid doesnt exist anymore

This is fixed
