### ISSUE TITLE
Ghosts can hold doors open.

### ISSUE THREAD

**Issue by Pangogie** [space-wizards/space-station-14#6659]
1: Open a door.
2: Jam a ghost/aghost in it.
3: -audible confusion-

![image](https://user-images.githubusercontent.com/7548248/153646151-a63a6420-1d3c-4814-a6a3-24178712ccbc.png)

**Comment by metalgearsloth** [comment]
Dupe https://github.com/space-wizards/space-station-14/issues/6508
