### ISSUE TITLE
Emergency Shuttle can be called by anyone who reaches the console

### ISSUE THREAD

**Issue by Willhelm53** [space-wizards/space-station-14#6675]
## Description

Calling the emergency shuttle should require command permissions/ID like cargo ordering does.

Could maybe use a system similar to cargo console or HoP ID console.

**Comment by Peptide90** [comment]
Back in ye olde days of 13 there was a special wall card swipe thing that meant at least 2 heads had to swipe to call shuttle or request ERT. I think this would be a nice solution to the problem so you need 2 competent heads that agree.

Similar was used to go to code red and open the armory.

**Comment by Lamrr** [comment]
> Back in ye olde days of 13 there was a special wall card swipe thing that meant at least 2 heads had to swipe to call shuttle or request ERT. I think this would be a nice solution to the problem so you need 2 competent heads that agree.
> 
> Similar was used to go to code red and open the armory.

Swipe calling shuttle / armoury varied depending on code base (/tg/staiton did neither). I reckon let anyone be able to call the shuttle and then use the swiping for red alert which would give you a shorter shuttle arrival time.

**Comment by Willhelm53** [comment]
> There's many rounds where the command IDs are just lost. The playerbase needs to grow into this.

Yeah that's fair.
