### ISSUE TITLE
Tinted directional windows need nuking from the repo

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#6690]
They don't work properly atm.

Prototype + pillar + packed + packedxmas changes req'd.

**Comment by Delete69** [comment]
Besides all the current open issues that effect thindows as a whole, what about tinted windows don't work properly?

**Comment by mirrorcult** [comment]
> What about tinted windows don't work properly? I don't see what's working improperly with them, and I use them to clever effect on a few spots in my map. Please no nukerino.
> 

non fulltile occluders aren't currently supported, in some situations they look fine but a lot of the time they completely break
