### ISSUE TITLE
Bagel.yml is in the root directory of the repo. Oops.

### ISSUE THREAD

**Issue by Veritius** [space-wizards/space-station-14#6700]
## Description
@Emisse accidentally put bagel.yml in the root directory of the repo, here: https://github.com/space-wizards/space-station-14/commit/7add459ae3e8c40e87dd631519a5cbdb00145d94

**Screenshots**
![image](https://user-images.githubusercontent.com/45957058/153784691-5a9041cb-c477-460b-8809-8cc1f368be03.png)

**Comment by Pangogie** [comment]
Ya know... I did see that happen, but I forgot to say something. :V

**Comment by Emisse** [comment]
sorry i do not know github very well

**Comment by Pangogie** [comment]
#6701
