### ISSUE TITLE
More animal sound effects needed for pettable animals

### ISSUE THREAD

**Issue by Willhelm53** [space-wizards/space-station-14#6702]
## Description

Now that we can pet the station's animals, more sound effects are needed. We currently just have dog, cat, chicken and duck sounds, but many more animals than that can be pet.

**Additional context**
See animals.yml and pets.yml for anything that has an InteractionPopup component but no interactSuccessSound. Chances are, it could use a sound effect (barring animals that are actually silent). Just make sure the sound effect meets the licensing requirements (creative commons is usually fine) and you're all set!

**Comment by CrzyPotato** [comment]
I can do this

**Comment by CrzyPotato** [comment]
#7532 Added more animal sounds for animals you can pet
