### ISSUE TITLE
Sprites for Drinking Glasses Are Not Changing with Drinks

### ISSUE THREAD

**Issue by likowski1** [space-wizards/space-station-14#6713]
## Description
Sprites for Drinking Glasses Fail to Change when Adding Various Mixed Drinks. [Manly Dorf Failing to change Drinking Glass into Wooden Mug for Example] 

**Additional context** 
I believe this has Something to do with the Connection With the Sprite List. or the Value Corresponding with Swapping Sprites based on What Liquid is inside the Drinking glass

**Comment by Fishfish458** [comment]
This issue occurred when netsync: false was added to drink sprites, they never really had a visualizer.

**Comment by Zymem** [comment]
Is there a reason why netsync should be kept off? Not really familiar with this side of the code.
