### ISSUE TITLE
You can damage multiple walls with the spear

### ISSUE THREAD

**Issue by partyaddict** [space-wizards/space-station-14#673]
![](https://i.imgur.com/WxRTvtL.gif)

It's a spear, it makes a bit more sense if it was a crowbar/swing weapon.

**Comment by PrPleGoo** [comment]
It's hitting everything inside the arc in range. 

Could put a maximum targets var on weapons to prevent hitting too many things in cases like this. This could however lead to not being able to hit an intended target. Plus I imagine it is desirable to skewer two people standing behind each other.
