### ISSUE TITLE
The highlighting hitboxes are fat

### ISSUE THREAD

**Issue by partyaddict** [space-wizards/space-station-14#674]
![](https://i.imgur.com/MMd5MLO.gif)
![image](https://user-images.githubusercontent.com/52793290/74100240-89248800-4b24-11ea-8f6c-cf19cd77a8a4.png)
Prevents you from placing floor tiles over wires and getting floortiles from under airlocks

Another complimentary .gif

I already reported this on the discord but I'm just showing more cases of hitboxes being horrible.

**Comment by ShadowCommander** [comment]
Duplicate of #601

**Comment by partyaddict** [comment]
Still shows off a new case, the airlock

**Comment by AJCM-git** [comment]
fixed by #1133
