### ISSUE TITLE
Teleporting to somewhere outside of PVS range puts you in nullspace briefly.

### ISSUE THREAD

**Issue by Pangogie** [space-wizards/space-station-14#6762]
1: Go away from station.
2: Teleport somewhere far away in station.
3: AAAAAAAAAAAAAA for a bit before the world loads in.

**Comment by Acruid** [comment]
The way the networking is set up, it should be similar to Minecraft where you teleport in and only see the void while the world loads in around you. The game does not have loading screens to hide this.

Working as expected, or are you teleporting to nullspace and then to the location after it starts loading?

**Comment by Pangogie** [comment]
No, it works as you described. It just hasn't happened until after the PVS changes.
