### ISSUE TITLE
Kitchen shutters on Bagel are rotated

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#6774]
## Description

**Screenshots**
![image](https://user-images.githubusercontent.com/19853115/154630574-d23303e8-2892-4496-8507-fc9bbe478c35.png)

**Additional context**

**Comment by Emisse** [comment]
theyre supposed to be because vertically they look weird, should i change this back

**Comment by mirrorcult** [comment]
they look way weirder rotated imo
