### ISSUE TITLE
Interacting with walls/wallmounts is broken in many cases.

### ISSUE THREAD

**Issue by Elijahrane** [space-wizards/space-station-14#6782]
## Description

Two that I discovered:

1: Try to RCD a wall. You'll get a "you can't reach that!" message
2: Build an air alarm. You can successfully put the metal on the ghost. The next step is putting the wires in the frame. There, you also get a "You can't reach that message!" no matter where you are relative to the wall.

**Comment by ElectroJr** [comment]
A related problem is that the construction ghost placing logic should probably also be more restrictive if the entity it would create has some directional interaction restrictions.

**Comment by Elijahrane** [comment]
I haven't had this in a while.
