### ISSUE TITLE
Animal limbs have no sprite

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#6785]
## Description

**Screenshots**
![image](https://user-images.githubusercontent.com/19853115/154787634-4e439b5e-cad2-4c2c-9bf6-867399a7050d.png)

**Additional context**

**Comment by Carou02** [comment]
Would a mascot-like design would work here?
![exam](https://user-images.githubusercontent.com/87671971/158038276-daa7b417-249e-473e-9634-0747b70f4318.JPG)

**Comment by Carou02** [comment]
I'm simply redrawing over "human parts", multiple 64x64 sprite sheets for each part. Or it should be only draw on a 32x32 face view parts?
