### ISSUE TITLE
Space Station 14 launcher not closing on linux

### ISSUE THREAD

**Issue by OctoRocket** [space-wizards/space-station-14#6799]
The Space Station 14 launcher is unable to be closed if you try to close it after trying to join a game, trying to close it will cause the window to freeze and you have to close it by PID through the terminal which can get quite annoying. This does not happen if you want 2-3 min after you join the game. I don't know if windows has this issue but manjaro/arch linux does.

**Comment by Zumorica** [comment]
Wrong repo + duplicated https://github.com/space-wizards/SS14.Launcher/issues/37
