### ISSUE TITLE
Kangas can not be clicked on

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#6812]
## Description

not sure what to make of this one

**Screenshots**

https://user-images.githubusercontent.com/19853115/154828134-8079f1ef-39e2-4366-9145-eb9bfea96dcd.mp4

**Additional context**

**Comment by Rember** [comment]
I couldn't reproduce this bug, can you provide more context?

**Comment by mirrorcult** [comment]
i have nfi what was up with this
