### ISSUE TITLE
Deconstruction needs some kind of hotkey

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#6827]
## Description
It's pretty annoying to deconstruct stuff right now with the amount of right clicks required.

**Comment by Zumorica** [comment]
I'm confused-- You can deconstruct anything without the deconstruction guide, so why does it need a hotkey?

**Comment by moonheart08** [comment]
> I'm confused-- You can deconstruct anything without the deconstruction guide, so why does it need a hotkey?

Really? I couldn't get this to work in testing but maybe I was just dumb as it seems to work now lmao. Nevermind.
