### ISSUE TITLE
Singulo doesn't eat decals

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#6851]
## Description

**Screenshots**

![unknown](https://user-images.githubusercontent.com/43253663/155048151-e67e705f-cdb2-4fd8-b478-dcfdef472136.png)

**Additional context**

**Comment by metalgearsloth** [comment]
See https://github.com/space-wizards/space-station-14/issues/6610

**Comment by keronshb** [comment]
I've tested this on a local and the singulo eats them.
