### ISSUE TITLE
Restricting access to user PII behind a +CHECKUSER admin permission.

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#6859]
This would mean obscuring the IP and HWID of the user in some non-reversible manner or just hiding it outright, and not allowing non-checkuser staff to apply IP bans (and simply presenting a "sticky ban" button that does so but with the details obscured).
This requires changes to SS14.Admin as well.

**Comment by PaulRitter** [comment]
prob best to hide it behind an adminflag. this should be easily carried over to SS14.Admin as well since you can check for adminflags there too

**Comment by moonheart08** [comment]
> prob best to hide it behind an adminflag. this should be easily carried over to SS14.Admin as well since you can check for adminflags there too

(so, +CHECKUSER per the title)

**Comment by Geekyhobo** [comment]
linking these two issues together, space-wizards/ss14.admin#35, ideally this should be done first then it can be done on ss14.admin with flags

**Comment by Geekyhobo** [comment]
Also working on this
