### ISSUE TITLE
Gamehud cleanup issue (AKA Oldchat)

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#6865]
What needs to happen:
1. Rip out GameHud and put it onto GameScreen as presenters (gamehud just duplicates GameScreen's job)
2. Once the above is done then add in support for oldchat

For each UI (e.g. combat mode) that needs doing:
- **Make a `CombatUI : Control, ICombatModeView`.** This handles all of the UI code like button presses or the likes. This also will probably need a reference to the presenter class. This will just be the UI control(s) ripped out of gamehud
- **A presenter class needs to be made that handles the viewer <> Game code.** The presenter should be as general as possible and re-usable regardless of what the UI code looks like and is mainly concerned with passing on stuff like a button press to the relevant system. If the UI has a reference to the presenter then it can just call the presenter's method directly (e.g. if the targetingzone changes on the doll)
- Any alternative layouts (e.g. horizontal alerts instead of vertical) should be its own UI that inherits the I<Something>View with the ability for the State to pass in which one it wants to use.
- For situations where you may want to parent the CombatUI to another control then the presenter should be able to take that control in.

This may end up changing in the distant future but it's still going to be significantly less CBT than the state of gamehud.

- [ ] Combat panel
- [ ] Top notifications
- [ ] "Button bard"
- [ ] Hands
- [ ] Inventory (left side / right side / top)
- [ ] Suspicion
- [ ] Votes

**Comment by Jezithyr** [comment]
This is being addressed in the UI/Hud refactor PR, however it isn't using presenters. A bespoke system is being made for HUD UI called widgets
