### ISSUE TITLE
Material doors don't have a mouseover highlight.

### ISSUE THREAD

**Issue by Pangogie** [space-wizards/space-station-14#6866]
(Trust me, I'm hovering over it in this screenshot.)
![image](https://user-images.githubusercontent.com/7548248/155271756-d2e90af8-fc5b-4f3c-bd6e-9ec2a6f9b9d3.png)

**Comment by metalgearsloth** [comment]
Just need InteractionOutline on it

**Comment by Delete69** [comment]
should these be powered while someone's digging around in the yaml?

**Comment by Lamrr** [comment]
> should these be powered while someone's digging around in the yaml?

Nah not really. They're akin to household doors.
