### ISSUE TITLE
Client sometimes fails to get the memo that decals are removed.

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#6873]
## Description
This appears to be **RANDOM**.
However, simply trying to clean up the grime on bagel, and drawing some crayon scribbles to clean, should reproduce the issue, as all the grime appears to be cleanable.

**Comment by Peptide90** [comment]
Easy to reproduce in mapping also. Seems to happen after some time and or generally only works on some decals but not all.

**Comment by metalgearsloth** [comment]
Any more info e.g. what's in the decalrenderindex?
