### ISSUE TITLE
Mop/Soap can't clean decals

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#6874]
## Description
Useless soap smh.

**Comment by Peptide90** [comment]
#6851 semi related. 

If decal is cleanable then mop / soap will need to remove it (will need do after or tool speed modifier).

For 6851 we need to delete decals that are not cleanable. This will be useful for an actual decal removal tool too.

**Comment by Emisse** [comment]
would it be possible to just delete the decal if the tile its on is destroyed. i could see this being a problem with ones that are offset on multiple tiles though, but i think making a way to remove decals would be good

**Comment by lzk228** [comment]
why is it closed?
