### ISSUE TITLE
Able to respawn after picking observer

### ISSUE THREAD

**Issue by Kromabae** [space-wizards/space-station-14#6890]
## Description
If you late join, and press join but dont pick a job and then press observe you still have the jobs window up while observing. And at any time you can press a job to respawn in even after being a drone or other ghost role for a while

**Screenshots**
Will provide vid if needed
**Additional context**
You guys are neato

**Comment by moonheart08** [comment]
I could've sworn I fixed this earlier on

**Comment by DrSmugleaf** [comment]
Fixed by https://github.com/space-wizards/space-station-14/commit/a3bc28476df8aa4d9123b0573b4cc652a4ca3999
