### ISSUE TITLE
Something weird with spacing and fire locks

### ISSUE THREAD

**Issue by Kromabae** [space-wizards/space-station-14#6921]
## Description
Not all firelocks go down during a spacing, but they somehow still block the atmos changing even though you can walk through it

**Screenshots**
None

**Additional context**
I dunno how else to explain it tbh, just test firelocks and spacing an area

**Comment by Peptide90** [comment]
There was a similar issue a long time ago where people were able to move through firelocks while they were down. Probably related but can't find a filed issue for it.
