### ISSUE TITLE
The parts and pieces of silicons and AI

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#6923]
- [x] "Intrinsic" UIs
	You should be able to attach existing computer UIs to an intrinsic action, and have multiple of them per entity.
	This will allow giving the AI the comms console, crew monitor, etc UIs without reinventing the wheel.
	Also this means you can give admin ghosts built-in versions of all these computers which is simply convenient.
	Solved by #6926
- [x] Cameras
	Should support both a computer UI, and calling up camera UIs directly as floating viewports.
- [ ] Station Minimap
	Should be built using what can be seen on camera, maybe a 12x12 area in front of (and including) the camera,
	accounting for visiblity. This will be how the AI sees the station as a whole, instead of the free floating eye
	used in SS13 (for both technical reasons, and because a minimap showing the crew seems more useful/interesting)
- [ ] Door remote as an instrinsic action
	The door remote, and perhaps other systems, should be made to support being instrinsic alongside being provided
	by a tool.
- [x] MMIs/Posibrains
	These are actually pretty easy. Huh.
	Drones should be made to accept them instead of being possessed directly.
- [x] Robot Chat
	Oh god. After the chat refactor this should be easy. Before the chat refactor, it's rather annoying/kludgy but
	can be done. Should be given to drones.

**Comment by Veritius** [comment]
MMIs/Posibrains were done in #18136

**Comment by Veritius** [comment]
also robot chat at some point

**Comment by Emisse** [comment]
station map is almost at the point it can be used for AI, need to a robust camera mapping pass to make sure each room has a cam  and adding intrinsic remote support should be fairly easy, should probably add chat alerts/clicking so you can teleport to the nearest camera of someone specifics chat

**Comment by slarticodefast** [comment]
All implemented by now.
