### ISSUE TITLE
Exception from attempting to resize chat window

### ISSUE THREAD

**Issue by collinlunn** [space-wizards/space-station-14#693]
Caused by clicking bottom left corner and trying to drag it out.

System.ArgumentOutOfRangeException: 'Specified argument was out of the range of valid values. (Parameter 'startIndex')'

This exception was originally thrown at this call stack:
	string.Insert(int, string)
    Robust.Client.UserInterface.Controls.LineEdit.TextEntered(Robust.Client.UserInterface.GUITextEventArgs) in LineEdit.cs
    Robust.Client.UserInterface.UserInterfaceManager.TextEntered(Robust.Client.Input.TextEventArgs) in UserInterfaceManager.cs
    Robust.Client.GameController.TextEntered(Robust.Client.Input.TextEventArgs) in GameController.Input.cs
    Robust.Client.Graphics.Clyde.Clyde.OnGlfwChar(OpenToolkit.GraphicsLibraryFramework.Window*, uint) in Clyde.Windowing.cs
	System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    Robust.Client.Graphics.Clyde.Clyde.ProcessInput(Robust.Shared.Timing.FrameEventArgs) in Clyde.Windowing.cs
    Robust.Client.GameController.MainLoop.AnonymousMethod__56_2(object, Robust.Shared.Timing.FrameEventArgs) in GameController.Standalone.cs
    Robust.Shared.Timing.GameLoop.Run() in GameLoop.cs
    Robust.Client.GameController.MainLoop(Robust.Client.GameController.DisplayMode) in GameController.Standalone.cs
    ...
    [Call Stack Truncated]

**Comment by ShadowCommander** [comment]
Was this in game or lobby?

**Comment by collinlunn** [comment]
in-game

**Comment by ShadowCommander** [comment]
Can you try it again? Right now I'm not able to reproduce the bug.

**Comment by collinlunn** [comment]
I'm reproducing this consistently on localhost with an up-to-date clone, but it might just be me messing something locally

**Comment by ShadowCommander** [comment]
Oh found it. The bug is clicking the LineEdit further to the left than the selectable area, which sets the `_cursorPosition` to `-1`.
