### ISSUE TITLE
Slime and Dwarf issue collection

### ISSUE THREAD

**Issue by Peptide90** [space-wizards/space-station-14#6947]
## Description

Pointed out by Old Dance jacket on discord, slimes are supposed to take damage from water and do from fire extinguishers but not from ingestion.

This brings into question species having unique features such as Dwarves being notorious for drinking alcohol. 

If anyone has any further suggestions for issues please point them out:

- [ ] Slimes should take damage from ingesting water and should have other chemical attributes.
- [x] Dwarves should have a unique characteristic with alcohol such as having it as a component of their blood or it healing poison damage or something. This means dwarves should probably have a weakness too such as to O2 deprivation (smaller lungs or something).
- [x] #6162 

**Screenshots**

**Additional context**

**Comment by metalgearsloth** [comment]
Probably better to work out if we want to keep them first. ATM they're useful for debugging species but don't offer much in terms of gameplay when we want species to significantly mechanically different.

**Comment by Elijahrane** [comment]
I think it's clear people like having a short species with a funny squashed sprite like dwarves. I think even if we decide to remove dwarves, some sort of short species is a good fit for a comedy spaceman game.

**Comment by Mith-randalf** [comment]
make dwarves unable to climb tables
