### ISSUE TITLE
onion seeds don't have prototype and are unused, oat seeds are unused

### ISSUE THREAD

**Issue by Fishfish458** [space-wizards/space-station-14#6951]
## Description

These are two working plants that have some related food in game at the moment but cannot be obtained.

onion seeds can be made by inserting an onion into a seed extractor, but lack an actual prototype to directly insert into a seed crate.

Oats currently work as a plant though might need to be linked to some of its recipes, it also unable to be obtained currently.

**Comment by Willhelm53** [comment]
r/onionlovers in shambles
r/onionhate rejoicing

Naturally this needs to be remedied. Good reporting!
