### ISSUE TITLE
Missing Onion Seeds

### ISSUE THREAD

**Issue by DummeHytteOst** [space-wizards/space-station-14#6953]
Onion seeds are missing from the MegaSeed Servitor and the normal seed crate

Currently the only way to get onions are from a maintenance spawn on bagel 
![image](https://user-images.githubusercontent.com/94384139/156243867-f1183beb-ae4f-4c41-839c-c423d43f5e04.png)

**Comment by Fishfish458** [comment]
looks like we both had the same idea #6951

**Comment by DummeHytteOst** [comment]
oh yeah

**Comment by DummeHytteOst** [comment]
do i just close this one?
if i even can
