### ISSUE TITLE
You can steal things from people's inventories using crafting

### ISSUE THREAD

**Issue by RandomDeathMatch** [space-wizards/space-station-14#6966]
## Description

If you are standing near a person with ingredients in their inventory, you can make things from the crafting menu (spears, tiles, pneumatic cannon, etc) using their ingredients. You can also just move to interrupt the craft and steal the materials.
**Screenshots**.

**Additional context**

Works through walls, from inside cloners, etc. Can pop out of a cloner with a spear and handcuffs ready to take down your oppressors.

**Comment by Peptide90** [comment]
Sounds like crafting needs to do a check to make sure the entities are on the person or on the floor, and not in any other storage containers like other people.
