### ISSUE TITLE
Consider changing security/syndicate color schemes to distinguish the two more clearly.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/space-station-14#6967]
Right now, both syndicates and security have a red colorscheme. This can easily be confused with syndicates which are *also* red. BlitzGunner225 brought this up on Discord and I agree it should be given some thought.

Changing security's color scheme to something like blue would avoid this confusion. The downside is that it's a drastic departure in aesthetic.

**Comment by PJB3005** [comment]
Some shade of blue can match many peacekeeping/security/police organizations both in real life and in media, so it's not a big stretch. But yeah not as much of a sinister security vibe.

Another option is to keep them red but figure out a better way to distinguish them from syndies. Could make syndies a more consistently "black with red outlines" theme, and then change security to something like "red with light blue outlines". You get to keep your red but it should be far more clear to distinguish.

**Comment by HoofedEar** [comment]
It's an interesting topic, because I think a lot about the color association with certain departments and how that is reflected in game. For example, orange being Engineering and Cargo. Green being Botany. Purple being Science, etc.

I propose that Sec should have it's color changed to match the color of the Captain. Some type of darker blue or steel blue. For a real world parallel, think of the UN Military Police. You can keep much of the same design aesthetic, but it won't make Sec as "menacing". But is Sec supposed to be menacing? They are there to keep the station safe and in order. Their goals align with the Captain.

**Comment by Peptide90** [comment]
There is in fact a grey security outfit already. Grey and red isn't a far stretch since all of the department is typically red (since blue is command).

Going all blue would potentially conflict with other NT / command roles.

Syndie hardsuit is their only red thing usually and it's very clearly different. Most syndi wear black webbing etc under it.

**Comment by PJB3005** [comment]
> orange being Engineering and Cargo.

Engineering is more of a yellow-orange while cargo is dull brown, to be clear.

> I propose that Sec should have it's color changed to match the color of the Captain.

Captain (and HoP) have the color of command, which is a dark blue. These should still be clearly kept separate from security. Keep in mind that the HoS is in charge of security, not the captain directly (ideally). Brighter shades of blue would probably also conflict with this (too little contrast) if I'm being honest, like Peptide said.

> But is Sec supposed to be menacing?

Well ideally not but this isn't supposed to be a perfect normal space station either. Security being somewhat menacing is still good in my opinion.

> There is in fact a grey security outfit already.

Grey isn't really an active color here, it's "neutral" space that doesn't go either way IMO.

> Syndie hardsuit is their only red thing usually and it's very clearly different. Most syndi wear black webbing etc under it.

Yeah I think making the blood-red hardsuit a different color scheme would probably be in order.

I think my idea of making sec have a red-with-blue-highlights scheme is best.

**Comment by HoofedEar** [comment]
> I think my idea of making sec have a red-with-blue-highlights scheme is best.

Definitely should test this with sprites first, as red and blue are contrasting colors and may clash poorly

**Comment by Emisse** [comment]
logically i think making them blue would make the most sense however im not sure a mega corporations police force should need to have to follow common color conventions; and the red is just so classic

**Comment by DogZeroX** [comment]
Syndicate and security are red, making security blue will leave us with us medical, command, and security being shades of blue, won't that be more confusing?

**Comment by PJB3005** [comment]
Medical at least is white and blue to distinguish that.

**Comment by Fishfish458** [comment]
thought I'd at least post a visual here for reference
![image](https://user-images.githubusercontent.com/47410468/156384093-8207d532-ab5f-4dcc-a341-89674810c3eb.png)

**Comment by BlitzGunner225** [comment]
I said this in discord and I’ll say this again.
The people _protecting_ you should not be the same color as the people trying to _kill_ you.
Now for what should be changed, I suggest having the syndie stuff be red. Red is already programmed into our minds to mean danger so it’s a perfect fit. Sec should take the blue and red from HOP as it keeps a bit of that dangerous red while also using the NT blue. Hop should also switch out it’s red for something like a grey or white as there aren’t supposed to be threatening.
Sidenote: Maybe wizards should be red too. They have a more unique silloette and design so that might be enough but it depends on how they’re made for ss14.

**Comment by BlitzGunner225** [comment]
> > The people protecting you should not be the same color as the people trying to kill you.
> 
> At the moment, this doesn't really work. Very rarely do people actively go out of their way to buy the Syndicate Hardsuit with TC (there are better purchase options available) and then go on a murder spree in said hardsuit (bear in mind you've already spent TC, so resources are limited as a result). Typically you either have a traitor who saves their TC up and kills another T in order to buy a bigger gun, or in more recent memory, people opening up gun crates in cargo, in their salvage hardsuits, who then go out of their way to kill the station _in their salvage hardsuits._
> 
> That said, I'm onboard with the idea of changing security/syndicate schemes anyway because accessibility options. I could see someone with various degrees of colorblindness having an issue with the current arrangement.

1. When nuke ops come in, people are really gonna need to know.
2. I don’t think salvage hard suits give any  armor so it sorta balances out. If it does give armor then the gear needs to be nerfed. Also sec should prob deal with that before that’s a problem. 
3. Ye

**Comment by BlitzGunner225** [comment]
> Syndicate and security are red, making security blue will leave us with us medical, command, and security being shades of blue, won't that be more confusing?

Well all of them are supposed to help you so it’s not that much of a problem. Also medical will be light blue with a bit of white and sec will prob be blue with a bit of red so you can still tell the difference. If you need medical help you usually just go to med so that also isn’t a problem.

**Comment by NicoSGF64** [comment]
In all my time in ss13 (mostly /TG/ and fulp) and ss14 I've never seen someone confuse the two:

Sec officers are black and red; syndie suits are blood-red. 
Same deal with the HoS: The HoS's hardsuit (if they are wearing one and not their regular uniform, which is also mostly black) is almost completely black except for the helmet. They also have a cape that's also black and slightly red.

Red clothes are also a staple of ss13, so I'd be a very controversial change.

> When nuke ops come in, people are really gonna need to know.

If someone in a blood-red hardsuit comes and is trying to shoot you then isn't it obvious who's the nukie? Even if they don't shoot or it's not exactly clear who's shooting or whatever the hardsuit is a very light red compared to the HoS's almost black.

**Comment by mirrorcult** [comment]
i really do not see the need for such a large overhaul, syndies and sec are already very distinct in other ways, and blue infringes on the command colorscheme (captain and HoP are VERY blue)

**Comment by Elijahrane** [comment]
Grey sec works IMO, with some really muted blues thrown in

**Comment by hubismal** [comment]
throwing my two cents in: if any scheme is changed it should be syndicate. security is way too iconic and established in SS13, making it blue or grey would make them just normal cops. syndicate has red in their hardsuit and like... their balloon? it wouldn't be as big a deal if syndies got changed.

**Comment by moonheart08** [comment]
the syndicate blood red hardsuit is, itself, extremely iconic.

**Comment by mirrorcult** [comment]
i just dont think anything should get changed at all, its fine

**Comment by Peptide90** [comment]
Are we settled on leaving things as is? Or should we ask the sprites for some updated uniforms (not colour changed, just some fresh ideas).

**Comment by mirrorcult** [comment]
i dont think this is getting changed
