### ISSUE TITLE
Toilet is not craftable

### ISSUE THREAD

**Issue by Absolute-Potato** [space-wizards/space-station-14#6969]
## Description

Toilet never finishes crafting. You can place a ghost and add 5 steel, but instead of constructing it just stays as a ghost and tells you "you are already building this" when attempting to do anything with it. It can still be removed using the eraser mode in the crafting menu (stealing the steel you added)

![image](https://user-images.githubusercontent.com/29511823/156453963-d6ca5dba-8340-4572-a6c5-cdfd6a976691.png)

**Comment by BasedUser** [comment]
nice

**Comment by Elijahrane** [comment]
Apparently this was fixed at some point in the past 2 days, I can't figure out when
