### ISSUE TITLE
Potency being remembered and not capped 

### ISSUE THREAD

**Issue by DummeHytteOst** [space-wizards/space-station-14#6979]
potency on plants gets remembered, so after round start you could dispense a seed that had a high potency last round and it would have the same amount of potency.

Potency is not capped it can go way above 100, but the effect of the plant does not increase after 100 potency

![20220303190253_1](https://user-images.githubusercontent.com/94384139/156626258-cd2081ec-e469-45a8-a3da-1d42ef5637a9.jpg)
![20220303190251_1](https://user-images.githubusercontent.com/94384139/156626300-002f5a35-bf59-40d9-8a2a-6c00ddac8bd1.jpg)

Potency is shared with every seed of the same type https://youtu.be/hq8KPgaEgwk (file was too big to put in)

**Comment by DummeHytteOst** [comment]
i will update this issue whenever i get more info

**Comment by Elijahrane** [comment]
People are also reporting potencies above 100 (although the yields still cap at 100)

**Comment by Elijahrane** [comment]
What happens to already spawned seed packets when the potency of the same plant type increases? Or is it only on newly created ones?

**Comment by DummeHytteOst** [comment]
@Elijahrane it is shared as seen in the video i just added

**Comment by Elijahrane** [comment]
I came across a similar issue while writing diseases, it seems like it's not too easy to make separate instances of prototypes. I solved it by copying each one with ISerializationManager before applying it, but I'm not sure how awful an idea that is or if it can have any unintended consequences
