### ISSUE TITLE
Add an ahelp button to the game lobby

### ISSUE THREAD

**Issue by Willhelm53** [space-wizards/space-station-14#6987]
## Description

The lobby needs a button or some other way to open the admin help window.

**Screenshots**

**Additional context**

Requested by multiple people in the Discord.

**Comment by Willhelm53** [comment]
@Peptide90 added in Discord that it would be nice to have it added to the HUD permanently. Anyone looking into adding this should consider it.

**Comment by Peptide90** [comment]
For context, a lot of new players don't know to hit escape to speak to an admin and even telling them that still yield no ahelp.

This should be akin to the F1 button sending you to the help page.

**Comment by Jezithyr** [comment]
Actively being worked on :3 as part of an ongoing lobby refactor
