### ISSUE TITLE
Decals can't be removed visually while mapping

### ISSUE THREAD

**Issue by Delete69** [space-wizards/space-station-14#6993]
As per title. Deleting a decal does actually work though, and when you save/reload the map your efforts are visualized properly again. It feels like this function broke a few days after the decal system was added. Probably the same issue as #6874 #6851 and #6610.

## Description

**Screenshots**

**Additional context**

**Comment by metalgearsloth** [comment]
Unrelated to #6851 and #6610

**Comment by Peptide90** [comment]
Pretty sure this is quite related to if not the same: #6873. When decals were first merged the remove by right click did work. Now it only updates once you reload the map.

**Comment by Delete69** [comment]
This was fixed, but the decal curse continues via other demonic pathways
