### ISSUE TITLE
Lights can shine through walls in certain setups and orientations.

### ISSUE THREAD

**Issue by Delete69** [space-wizards/space-station-14#6994]
@moonheart08 mentioned knowing about this and forgetting to fix it. I didn't see an issue open so here you go

## Description

**Screenshots**

https://user-images.githubusercontent.com/95458399/156828799-77679959-13fc-4809-aeed-ce17a917cb25.mp4

**Additional context**

**Comment by ShadowCommander** [comment]
Last time this came up, the problem was rotated walls don't block light properly. Need someone to see if this is still reproducible or if it was fixed.

**Comment by mirrorcult** [comment]
this isnt even really fixable like yeah if you offset the lights too much it's gonna be offset too much so just gonna close
