### ISSUE TITLE
Tests are failing in debug

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#7010]

**Comment by ElectroJr** [comment]
AFAIK issue started after 950ead9, which adds a code snippet differentiates between debug & release. But I have no idea what actual problem is / why this is causing misc tests to fail..

**Comment by wrexbe** [comment]
In RobustIntegrationTest.Netmanager, there is ProcessPackets
This method calls a local async void DoConnect() method
That method makes a database call, which after this change, the database calls in debug do a Task.Delay(1)
So the tests continues onward, with this, and any other async void methods that use the database completing at the wrong time, potentially during a different test, and it falls apart.

I did a little bit of work trying to get it working.
https://github.com/space-wizards/space-station-14/pull/8233
