### ISSUE TITLE
Opening a window with default size greater than resolution is bugged

### ISSUE THREAD

**Issue by ghost** [space-wizards/space-station-14#702]
Say SS14 is running on a 500x600 window. You open a CargoConsole, which is maybe 300x800. The top bar of the CargoConsole interface is above the screen, unclickable meaning you can't drag it down or press the X out button.

**Comment by PaulRitter** [comment]
@PJB3005 this still a thing?

**Comment by slarticodefast** [comment]
In- game windows are properly resizing with the game window size now.
