### ISSUE TITLE
Can't click-drag the corners of the VV window to change the height and width at the same time

### ISSUE THREAD

**Issue by GraniteSidewalk** [space-wizards/space-station-14#703]
At least on my machine, I can't. Just does nothing.

**Comment by ShadowCommander** [comment]
There's a square of 6x6 or so pixels that allow you to change the height and width at the same time.

**Comment by GlassEclipse** [comment]
Did more testing and it seems that it's conditional. Whenever I open the VV menu, that size menu never allows me to click that 6x6 pixel area. If I make the VV menu a little taller and wider, I can do it just fine.

**Comment by DrSmugleaf** [comment]
Can't reproduce this bug https://streamable.com/avq3i1
