### ISSUE TITLE
Movement doesn't work when mapping

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#7030]
Specifically:
- Load game in normally
- Run mapping on new map
- mapinit it
- Spawn urist
- Mispredicted movement; client thinks it can move but server doesn't.

**Comment by Delete69** [comment]
#6751

**Comment by metalgearsloth** [comment]
Issue sounds a bit different?

In this case the map correctly unpauses but any new entities stay paused.
