### ISSUE TITLE
Discord outages halt the project

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#7039]
Sure they ain't frequent buuuuuuuuut
![image](https://user-images.githubusercontent.com/7806367/157302256-525cfbaf-6745-4931-838e-c19dd39a7b34.png)

Maintainers probably need at least a backup communication method, game admins too.

**Comment by moonheart08** [comment]
![image](https://user-images.githubusercontent.com/7806367/157305923-a2d35f6d-5466-4cc3-97a7-3e5946f71b62.png)

**Comment by PJB3005** [comment]
I can self host backup instances of things if we need, but the problem will always remain that most people won't be in them in the first place when they're necessary.

**Comment by Peptide90** [comment]
For coordinating the upper echelons like game admins, maintainers, badmins etc I think there should probably be an easy to access backup solution (web accessible so we're not installing more crap?)(No not IRC ;) ) I assume most badmins / maintainers have eachother on steam though.

**Comment by mirrorcult** [comment]
by god that's EFR with a steel chair

**Comment by RemieRichards** [comment]
reject modernity, embrace tradition, back to #spacebus irc we go

**Comment by Ygg01** [comment]
> For coordinating the upper echelons like game admins, maintainers, badmins etc I think there should probably be an easy to access backup solution (web accessible so we're not installing more crap?)(No not IRC ;) ) I assume most badmins / maintainers have eachother on steam though.

Like a forum?

**Comment by Peptide90** [comment]
> > For coordinating the upper echelons like game admins, maintainers, badmins etc I think there should probably be an easy to access backup solution (web accessible so we're not installing more crap?)(No not IRC ;) ) I assume most badmins / maintainers have eachother on steam though.
> 
> Like a forum?

People group chat on the forum? Fair if someone wants to write that into procedure. Or we just do without a backup and deal with it.

**Comment by Veritius** [comment]
Something that came to mind was [Matrix](https://matrix.org/) but I'm not sure how applicable that is. It's decentralised so it can take a server going down, but at least one person has to host a server. There's also a web client called [Element](https://app.element.io/).

**Comment by metalgearsloth** [comment]
> Something that came to mind was [Matrix](https://matrix.org/) but I'm not sure how applicable that is. It's decentralised so it can take a server going down, but at least one person has to host a server. There's also a web client called [Element](https://app.element.io/).

I think we had a matrix bridge but it got spammed with porn.

**Comment by PJB3005** [comment]
And it was also broken as hell because we didn't host our own homeserver.

**Comment by ghpsk** [comment]
There's also XMPP, if you want to feel like you're using Windows Live Messenger.

**Comment by juliangiebel** [comment]
> There's also XMPP, if you want to feel like you're using Windows Live Messenger.

That is a meme, there are clients that don't feel like Windows Live Messenger.
XMPP is also used in the background a lot. Even Whatsapp started as a locked down XMPP client basically.
[Ejabberd](https://www.ejabberd.im/ ) is even used in nintendos funny switch update and news infrastructure.

It's hard to find a good (looking) client for it because of the locked down prettier services like whatsapp and discord.
This is a decent (also somwewhat good looking imo) client:
[https://conversejs.org/](https://conversejs.org/)

I'm not suggesting we run anything in parallel to discord here. Just that we could set something up so admins can still communicate with each other outside of the game. 
~We could even integrate it into the administration website so you don't even need a seperate account for that~

**Comment by ghpsk** [comment]
> That is a meme
It is indeed a meme. I am, in truth, a prolific XMPP user.
I would suggest it more seriously, but I feel like it'd only work if I wyci'd it in.

**Comment by Peptide90** [comment]
Unironically teams? Recorded maintainer meetings ;) Otherwise if we can get a hosted group chat on the forums for admins and for any other important group so we know to revert to that for coordinating.

**Comment by mirrorcult** [comment]
we have discourse now and gh thats probably good enough. not sure what someone is supposed to do looking at this issue
