### ISSUE TITLE
Destroying an object while VVing it causes an exception

### ISSUE THREAD

**Issue by 4dplanner** [space-wizards/space-station-14#704]
An unhandled exception of type 'System.ArgumentException' occurred in Robust.Client.dll: 'Tried to draw an entity has been deleted.'

**Comment by 4dplanner** [comment]
I'll be giving fixing this a go

**Comment by moonheart08** [comment]
@PJB3005 is this issue not fixed now?

**Comment by PJB3005** [comment]
Oh, GitHub didn't autoclose this. Weird.
