### ISSUE TITLE
Lizard temperature mechanics

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#7056]
People seem most keen on these as a step towards making them interesting:
- Slower rate of temperature change compared to human
- Temperature related to movement speed. Having this be instantaneous / granular is impossible. You need to communicate any changes well in advance (e.g. 1 second+) so the client can anticipate the change for prediction to avoid a lurch, and you should also communicate it via UI somehow.

**Comment by Emisse** [comment]
outdated, not sure if temp scaling move speed is still wanted but sounds like cbt
