### ISSUE TITLE
Some machines do not respect loss of power

### ISSUE THREAD

**Issue by collinlunn** [space-wizards/space-station-14#706]
Fully functional when depowered:
- Chemical Disperser
- Cargo Shuttle Console
- Vending Machines
- Medical Scanner

If you open the UI before it depowers you can still use:
- R&D Computer

If you open the UI before it depowers you can look around in the UI and open new windows:
- Autolathe
- Protolathe

**Comment by SweptWasTaken** [comment]
Eh probably gonna be remedied when someone gets around to implementing the power rewrite that's on the hackmd. For now I think they're powered by default just to not give devs headaches.
