### ISSUE TITLE
Some inputs for some reason repeat multiple times

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#7061]
## Description
In some occasions, you will get spammed with "You cannot reach here" or another message for a second, out of nowhere.

**Comment by ElectroJr** [comment]
Probably due to #6856. Each interaction needs to be fixed individually, so if you know of any add the to a list here I guess.

**Comment by ElectroJr** [comment]
#7070 will remove some of the pop-up spam, but probably not all of it.

**Comment by Soupstraw** [comment]
I get input spam when using an emag. It usually uses like 2-3 charges when I use it on a door and I get a wall of popups.
