### ISSUE TITLE
Add injected reagents and metabolism

### ISSUE THREAD

**Issue by Moneyl** [space-wizards/space-station-14#707]
We should support injected reagents and metabolism for them. Currently reagents can only be metabolized if consumed by a mob with a `StomachComponent`. This would include a few things:
- [ ] Syringes that can draw/inject reagents from containers
- [ ] Single use injectors that can only inject reagents and aren't refillable
- [ ] Some component that accepts injected reagents and metabolizes them

**Comment by Moneyl** [comment]
I'm already working on this and should have a PR + design write up ready in the next few days. While #170 is related it's very broad and there was no issue specifically for this so I wanted to make it so multiple people didn't try working on it at the same time. Can this be assigned to me?

**Comment by SweptWasTaken** [comment]
Can you edit the issue and link to the hackmd docs when you finish them?

**Comment by Moneyl** [comment]
Yup. Will do.

**Comment by ancientpower** [comment]
>some component to metabolize injected reagents

perhaps some kind of `BloodComponent`?

**Comment by Moneyl** [comment]
Yup, I was thinking something similar. Currently have `BloodstreamComponent` that injectors inject into. Not going to have actual blood that can be drawn/bled for now to keep the PR from getting any bigger. Current design is looking something like this:

![Metabolism-NewDesign--2-14-2020](https://user-images.githubusercontent.com/8206401/74576571-6695d300-4f59-11ea-88ef-11919709b169.jpg)

Still need to change `StomachComponent` so it gradually sends it's contents to `BloodstreamComponent`, make my code less garbage, and document it.

**Comment by ShadowCommander** [comment]
There was a discussion about making a bloodstream reagent container that would hold reagents that were absorbed into the bloodstream. Things like the brain would take the reagents from the bloodstream and metabolize them.

**Comment by Moneyl** [comment]
I think that would over complicate things. Similar behavior should be possible with `IMetabolizable` (what the bloodstream would use to metabolize each reagent) since it passes the entity metabolizing the reagent. This would let certain metabolism effects interact with other organs like the brain or depend on them being present to have an effect. 

This should be cleaner since it'd keep all the metabolism code in classes inheriting `IMetabolizable` and not strewn across multiple components. Easier to find and keeps components from getting bloated. I understand that it makes sense in real life but for our purposes it'd be simpler to have the bloodstream handle it and let `IMetabolizable` implementations to interact with other organs when needed.

**Comment by ancientpower** [comment]
I was thinking about having a liver organ metabolize chems specifically but having metabolism be handled by ANY organ sounds interesting. Most of them would probably still be metabolized by the liver but it would allow for more robust treatments for certain conditions.

**Comment by Moneyl** [comment]
While I still think having the bloodstream handle metabolism is simpler, the good thing is that the changes I'm suggesting work as a precursor for either path. 

What I'm suggesting is that once reagents are in the bloodstream it gradually runs their `IMetabolizable` implementations and discards them after they're metabolized. If we wanted other organs to do this instead you could cut the bottom half of that graph off and pass reagents to other organs and run their metabolism code instead once they're in the bloodstream. The bloodstream would essentially be the interface between different delivery methods and the organs.

**Comment by SweptWasTaken** [comment]
Cum chem metabolized by reproductive organ
