### ISSUE TITLE
Dead mobs can be revived through healing

### ISSUE THREAD

**Issue by Fishfish458** [space-wizards/space-station-14#7076]
## Description

A dead mob can come back to life simply by getting their injuries healed.

**Screenshots**

https://user-images.githubusercontent.com/47410468/158003675-0bc7d1c7-8625-41d8-8552-9088c06570a0.mp4

**Comment by mirrorcult** [comment]
a proper solution to this (no amount of healing can make you un-dead) will have to wait for mobstate rework but #7224 fixes this specific bug
