### ISSUE TITLE
Animals can use computers by using Toggle UI.

### ISSUE THREAD

**Issue by Pangogie** [space-wizards/space-station-14#7078]
1: Become Ian.
2: Locate computer.
3: Right click > Toggle UI
4: Become Supreme Commander Ian.

![image](https://user-images.githubusercontent.com/7548248/158013352-62444408-ed9f-46ea-a024-e6491617aa66.png)

**Comment by Veritius** [comment]
Does this also work with regular corgis, or mice and such?

**Comment by Veritius** [comment]
Also, related to #7079

**Comment by Veritius** [comment]
And also very likely related to #7080 
Seems like it's only checking left-click interactions, but not context menu or Open UI interactions.

**Comment by Pangogie** [comment]
Works with any animal. Does not work with pAI oddly. But that means something is up with a component that animals have, but not pAI.

**Comment by ElectroJr** [comment]
> And also very likely related to #7080

That just sounds like a collision issue and is probably unrelated.

> Works with any animal. Does not work with pAI oddly. But that means something is up with a component that animals have, but not pAI.

Consoles just check whether a mob `CanInteract`, which most living mobs should be able to. pAIs explicitly block most interactions.

Without having to add hand checks to many different UI/systems, I guess the easiest fix for this is to add a requires-hands bool to something like activatable UI component and have that block interactions with UIs that require hands. Probably best to wait until after #7028 is merged.

**Comment by HoofedEar** [comment]
>Probably best to wait until after #7028 is merged.

Looks like it was merged :)
