### ISSUE TITLE
Animals can press E to open doors without having hands.

### ISSUE THREAD

**Issue by Pangogie** [space-wizards/space-station-14#7079]
1: Become Ian
2: Press E on a door.
3: Enjoy freedom.

![image](https://user-images.githubusercontent.com/7548248/158013475-908183c4-5974-458f-8d88-b8a02e5dafda.png)

**Comment by Veritius** [comment]
Does this also work with regular corgis, or mice and such?

**Comment by ElectroJr** [comment]
I guess its weird for them to be able to open "dumb" doors but, I feel like its fine for things like airlocks w/o access requirements. I always assumed they were using a motion sensor or something.

Or should they just be able to open no doors at all?
