### ISSUE TITLE
Animals can walk through tables (vaultables).

### ISSUE THREAD

**Issue by Pangogie** [space-wizards/space-station-14#7080]
1: Become Ian
2: Find a table to disrespect.
3: Walk through table like a Chad.

![image](https://user-images.githubusercontent.com/7548248/158013560-fb1786e8-cb00-45c3-b8cc-6daf705f02c4.png)

**Comment by mirrorcult** [comment]
needs layer/mask cleanup probably

**Comment by EmoGarbage404** [comment]
this has since been corrected.
