### ISSUE TITLE
Ghost roles should be better organized

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#7090]
## Description
Needs a bigger window, and the roles need to be categorized by type
Ex:
"Ghost role "Image here" "Amount available" 
Description: "text"
Rules: "Text"

Maintance drone "image" x5
Description: Fix the stuff
Rules: No grieff!

**Comment by Veritius** [comment]
While we're at it, why not a button that lets you jump to the body you'll be taking, just to make sure you're not a pAI thrown into deep space or something.

**Comment by HoofedEar** [comment]
> While we're at it, why not a button that lets you start spectating the body you'll be taking, just to make sure you're not a pAI thrown into deep space or something.

Maybe when you click request, it brings you over to the body to see it as you wait and **read** the rules before accepting
