### ISSUE TITLE
Pointing arrows are bent

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#7126]
## Description

**Screenshots**
![image](https://user-images.githubusercontent.com/43253663/158257957-0e18de5d-3219-4702-aa24-1790b22b2d47.png)

**Additional context**

**Comment by ElectroJr** [comment]
Probably due to space-wizards/RobustToolbox/pull/2594
I'm guessing this is a world vs local rotation problem where the grid is rotated but the arrows aren't.

**Comment by metalgearsloth** [comment]
Putting noRot on the sprite should fix it.

**Comment by ElectroJr** [comment]
> Putting noRot on the sprite should fix it.

Only complication might be the rogue pointing arrows, which are initially upright but then turn to face where they're going. But I guess they can just turn off no-rot when they start chasing.
