### ISSUE TITLE
Entities currently do not receive temperature damage.

### ISSUE THREAD

**Issue by Pangogie** [space-wizards/space-station-14#7134]
1: Spawn spaceman in space.
2: Alas they do not receive temp damage.

1: Spawn spaceman in fire.
2: Alas they do not take temp damage.

**Comment by ElectroJr** [comment]
Fire still seems to work fine for me, but space seems to no longer cool you down. Again. The `AtmosExposedUpdateEvent` doesn't get fired at entities outside of atmospheres, and there's no form of passive radiative cooling or anything..
