### ISSUE TITLE
Add interaction checks to all interactions

### ISSUE THREAD

**Issue by ShadowCommander** [space-wizards/space-station-14#717]
Since #698 got merged. We need to find and change all interactions to use it to check whether the interaction is valid.

It got added to Drop and Pickup, but many other interactions still need the check.

**Comment by chairbender** [comment]
Taking this on.

**Comment by chairbender** [comment]
As per the mentioned unmerged PR, it also seems I should add checks for bound UIs to a common base class so I will see about that too.
