### ISSUE TITLE
chessboard doesn't have interactionoutline

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#7175]

**Comment by Elijahrane** [comment]
This is a bit more complicated than it first seems because it actually does already inherit the component from BaseItem, it's just not working for some reason
![image](https://user-images.githubusercontent.com/60792108/162657177-fc529564-419a-4123-81bf-8e1b9fb3b88f.png)

**Comment by ElectroJr** [comment]
The problem is that there is a bug with sprite bounding box calculations that meant the outline didn't work. I think this just happens to be the only texture/sprite that doesn't currently have a size that is a multiple of 32.

See space-wizards/RobustToolbox/pull/2714
