### ISSUE TITLE
Container Items/Lockers are gunked

### ISSUE THREAD

**Issue by ProfanedBane** [space-wizards/space-station-14#719]
- If an item is placed in a locker the locker can no longer be pushed
- Sometimes when opening/closing a lock you can no longer pickup any items inside the locker
- Toolboxes can get in a weird state that cannot be picked up, instead they just open their inventory on click

**Comment by PrPleGoo** [comment]
I'm going to take a look at this

**Comment by PrPleGoo** [comment]
Unable to reproduce:

- Sometimes when opening/closing a lock you can no longer pickup any items inside the locker
- Toolboxes can get in a weird state that cannot be picked up, instead they just open their inventory on click

Please provide more details

**Comment by SweptWasTaken** [comment]
This might have been fixed by this

https://github.com/space-wizards/RobustToolbox/pull/1004

**Comment by PrPleGoo** [comment]
I will look at fixing this then:
- If an item is placed in a locker the locker can no longer be pushed
