### ISSUE TITLE
Mice and other animals can make monkey noises when they definitely shouldn't be able to (due to diseases)

### ISSUE THREAD

**Issue by Veritius** [space-wizards/space-station-14#7191]
## Description

Mice can just... make monkey noises if they're infected by AMIV.

**Screenshots**
![image](https://user-images.githubusercontent.com/45957058/159109204-7e4546e4-0eea-4dab-a3d6-52a715b54e1e.png)

**Additional context**

Discovered in a live round on USW1

**Comment by moonheart08** [comment]
diseases got removed

**Comment by lzk228** [comment]
solved in the most unusual way :trollface:
