### ISSUE TITLE
Admin Logs register every attack even if it doesn't hit.

### ISSUE THREAD

**Issue by Pangogie** [space-wizards/space-station-14#7212]
1: Spam click attack someone.
2: Open Admin Logs.
3: Recoil in horror as you see the amount of logs for "attacked" despite only being hit a couple times.

**Comment by ShadowCommander** [comment]
I wonder if there's a way to add log stacking for multiple that happen in quick succession in the same area or if that'd be too vague when trying to recreate the scene.
