### ISSUE TITLE
Adding AimShootLife AI trips an assert

### ISSUE THREAD

**Issue by 4dplanner** [space-wizards/space-station-14#722]
specifically in Ray.cs line 36:
`DebugTools.Assert(FloatMath.CloseTo(_direction.LengthSquared, 1));`

**Comment by 4dplanner** [comment]
this is because it's normalising a zero length vector (presumably to the entity itself)

**Comment by metalgearsloth** [comment]
@DrSmugleaf no longer an issue because bulldozed
