### ISSUE TITLE
Moose Station continuously vents air

### ISSUE THREAD

**Issue by ElectroJr** [space-wizards/space-station-14#7244]
Not that big of a problem, but it generates a continuous stream of explosive-depressurization admin logs, which is quite annoying.
Could be fixed by just having some valves default to closed, or by updating the definition of "explosive" depressurisation. Possibly both should be done, given that those logs will probably appear whenever someone attempts to pressurize a room with a breach.
 
![a](https://user-images.githubusercontent.com/60421075/159683433-2944c856-d284-4a83-8061-7830e2025613.png)

**Comment by Emisse** [comment]
I believe valves can start off. I'll do this next moose update.
