### ISSUE TITLE
DoAfter damage threshold

### ISSUE THREAD

**Issue by Fishfish458** [space-wizards/space-station-14#7264]
## Description

(Adding this from a small discussion on discord)

Currently BreakOnDamage cancels for any damage whatsoever, which means as little as 1 tick of toxin damage can cause a DoAfter to cancel.

A DamageThreshold should be available when setting arguments for the DoAfter, allowing up to a certain amount of damage per tick and possibly a second threshold for TotalDamage over the course of the DoAfter.

**Comment by ShadowCommander** [comment]
This should also be per damage type, since oxygen and radiation damage probably won't prevent someone from doing most things.

**Comment by keronshb** [comment]
I'll take a look at this.

**Comment by mirrorcult** [comment]
oop

**Comment by mirrorcult** [comment]
why did i reopen this
