### ISSUE TITLE
Lemon Cake Slicing bug

### ISSUE THREAD

**Issue by Kromabae** [space-wizards/space-station-14#7295]
## Description
When Being draged, the lemon cake from salvage can be cut an infinite amount of times. It will provide a huge amount of food for the station but also make the station messy

**Screenshots**
![bild](https://user-images.githubusercontent.com/97402700/160268285-d4685bec-43ac-4e11-957f-3243ec3a7e54.png)
Example pic of what is to come, pretty much all of bagel looked like this after a while

**Comment by mirrorcult** [comment]
pretty sure this is the same as #7285
