### ISSUE TITLE
Smoke fork bomb

### ISSUE THREAD

**Issue by BasedUser** [space-wizards/space-station-14#7357]
## Description
Ditto.
1. Acquire enough chemstreams in 1 tile. 50 monkeys should do the trick
2. Blockade the monkeys somehow. (i.e. by killing them with vacuum)
3. Give any monkey a 25u+25u phosphorus+potassium pill.
4. Affect the monkey pile with sugar-overdosed smoke. Good: 80u+10u+10u
5. Watch the UPS drop to 0.
    Sugar smoke reacts with monkey stomach to make phosphorus and potassium enriched smoke. Sugar smoke and potassium+phosphorus smoke reacts with EVERY MONKEY's stomach to make more sugar and potassium+phosphorus smoke.

**Additional context**
I was testing mixing chlorine smoke with fluorine smoke to cause explosions for anything and everything inside but HOLY FUCK YOU CAN DUPLICATE CHEMS WITH THIS AAAAAAAAAAAAAA

**Comment by BasedUser** [comment]
Side note, restartroundnow causes a memory leak.

**Comment by BasedUser** [comment]
update: it doesnt last forever, only until all the chemstreams inside are filled with one chem

**Comment by ElectroJr** [comment]
Given that this can cause severe lag this should probably be fixed somewhat quickly. #6223 Is another foam/smoke issue that is related, and should also be fixed.
