### ISSUE TITLE
Somebody map in some windows

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/space-station-14#736]
Like seriously we have FOV now, they actually matter.

**Comment by SweptWasTaken** [comment]
So mapping is currently megabroken.

- Doing addmap or loadbp while a client is loaded into the server crashes everything.
- savebp 4 foo.yml saved the map for me, but it was just the default map again basically wasting an hour of progress for me.
- The mapping documentation is the shittiest.
- Rotating stuff like wall lights is a pain in the ass.
- Sometimes when you're going in and out of aghost, your character will get stuck and be unable to move until you respawn him, which in my case also reset the map wasting progress.
- Going into aghost breaks FOV a bit.

**Comment by AJCM-git** [comment]
Fixed by [65d46899c06df813e2a355bbeeaa9a14c32d9022]
