### ISSUE TITLE
The bar on marathonstation has a real nuke instead of a keg

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#7369]
## Description
Damn it'd be a shame if someone gave them the nuke codes, eh?

**Comment by moonheart08** [comment]
![image](https://user-images.githubusercontent.com/7806367/161151376-cefd31d0-e04a-40c0-9374-5cbc1709eac3.png)

**Comment by StanberyTrask** [comment]
keep it, its an easter egg now
