### ISSUE TITLE
Backpack fills for jobs are different depending on preference(backpack/satchel/duffelbag)

### ISSUE THREAD

**Issue by Fishfish458** [space-wizards/space-station-14#7393]
## Description

Roles don't have matching fills for satchels and sometimes duffel bags compared to backpacks.

Example:
 clown with backpack will spawn ClothingBackpackClownFilled which is giggles von honkerton which has a box of hugs in it.
 if instead they choose a satchel, they will get a generic ClothingBackpackSatchelFilled which contains the survival kit.

Pack fills for jobs should be the same no matter what container is chosen.

**Comment by AugustEymann** [comment]
https://github.com/space-wizards/space-station-14/pull/7976

**Comment by Mervill** [comment]
Cannot reproduce as of d43ed3210c254caeacf2ca1e7e2056e15c9fb73e

**Comment by ElectroJr** [comment]
>Cannot reproduce as of https://github.com/space-wizards/space-station-14/commit/d43ed3210c254caeacf2ca1e7e2056e15c9fb73e

Haven't tried reproducing, but just based on the yaml this is still an issue.

Either #7976 needs to be revived (which is missing a `ClothingBackpackSatchelClown` prototype), or the satchel customization option just needs to be removed from the clown's starting gear.

**Comment by Willhelm53** [comment]
#3743 would likely help with part of this one.

**Comment by IProduceWidgets** [comment]
I think this is resolved? At least I have not seen anyone complain about it in thousands of rounds.

Maybe also partially addressed by https://github.com/space-wizards/space-station-14/pull/25715

**Comment by mirrorcult** [comment]
loadout fixd
