### ISSUE TITLE
Weird generator thingy with no name

### ISSUE THREAD

**Issue by Kromabae** [space-wizards/space-station-14#7407]
## Description
This thing has no name

**Screenshots**
![bild](https://user-images.githubusercontent.com/97402700/161445953-39d74963-457f-47e1-908f-20a51c47e040.png)

**Comment by Peptide90** [comment]
Huh idk if this is my fault for not naming them or not but they should at least inherit generator as a name.

I'll fix this tomorrow night and move the stuff from abstract to noSpawn if that's the current convention.
