### ISSUE TITLE
Clippers and Seed Extractor not able to make seed packets

### ISSUE THREAD

**Issue by Kromabae** [space-wizards/space-station-14#7408]
## Description
Clippers and Seed Extractor dont produce seed packets when used the way they are intended to be used. Botany is now forever dependant on cargo to be supplied by seeds

**Screenshots**

https://user-images.githubusercontent.com/97402700/161451192-f92b89b0-70a2-414a-89f9-956b7055d18a.mp4

**Comment by mirrorcult** [comment]
this is 100% because of the abstract/nospawn changes, seeds are probably abstract
