### ISSUE TITLE
MIDI files can have high amount of notes for a short song (Can crash own game)

### ISSUE THREAD

**Issue by dan6798** [space-wizards/space-station-14#7421]
## Description

MIDI files can be rather large with high notes per measure (Rush E). After playing the song I noticed the game would lag when the song's ending is played so I edited the MIDI to play only the two measures near the end (650 KB, two measures). This can be enough to lag/crash the user's own game if set to loop and if you wait long enough (And is annoying anyway to others) and can't be prevented if you set the MIDI sound to 0. 

Steps to Reproduce:
1. Spawn in any MIDI instrument, preferably the Musician's PDA as it can play MIDI files without being held.
2. Find or create a MIDI file with large amounts of notes. (I took a fan-made Rush E and shortened it down to the two measures near the ending)
3. Set the instrument in-game to loop.
4. Watch as the game slows down more and more each loop.

I haven't been able to test if it lags/crashes the server/others as I tested it on a mostly empty server in the mode sandbox (Other was a Mac user.) Also if the user disconnects/crashes, the Music PDA stops playing anyway so it's hard to see if it would crash the server/other people. 

**Screenshots**

![image](https://user-images.githubusercontent.com/63944747/161645865-5971d85c-30b2-48fc-b6b8-777dcc4bf51e.png)

An image of the MIDI file in an editor. There are notes stacked upon each other.

**Additional context**

Here is the the MIDI file that I used to perform the bug. Alternatively, you can find any MIDI file or create one that has a large amount of notes but is under the file limit.
[RushEShort.zip](https://github.com/space-wizards/space-station-14/files/8413642/RushEShort.zip)

**Comment by Veritius** [comment]
Isn't this less a bug and more just a consequence of trying to play all those notes at once? The server doesn't even accept this many notes, only the client properly suffers. This is only really a problem you cause to yourself.

**Comment by Zumorica** [comment]
Not really an issue, in my opinion. I second what Veritius said.
