### ISSUE TITLE
Fire suits/fire helmets offer too much pressure protection

### ISSUE THREAD

**Issue by Zymem** [space-wizards/space-station-14#7442]
## Description

While a fire suit alone isn't enough to survive in space, if you combine it with a fire or hardsuit helmet then you'll become immune to low pressure damage.

This basically makes them cheaper and faster hardsuits.

**Comment by Peptide90** [comment]
#6169 duplicate effectively.

I've made these comments before when people have complained about or messed with the fire suit and emergency suit. They either are protected or are not, there's no scale or reduction in damage and there should be.

**Comment by Emisse** [comment]
i nerfed them. they dont survive low pressure anymore
