### ISSUE TITLE
You can take bites of out mice when they're still alive.

### ISSUE THREAD

**Issue by Fishfish458** [space-wizards/space-station-14#7494]
## Description

crit state mice are edible

**Screenshots**

https://user-images.githubusercontent.com/47410468/162631469-4f8fa946-4558-40a3-aeb1-810f8fc8f0bc.mp4

**Comment by EmoGarbage404** [comment]
Can this really be seen as an issue? I think eating live mice is just a neat feature

**Comment by ShadowCommander** [comment]
Seems fine. From the video it looks like there's a bug where it doesn't get eaten. It probably isn't but check if it's giving infinite nutriment like the cake.

Also I don't think we have a prevent revive state so enough healing just resurrects mobs right now.

Maybe making eat verb only while not dead would be good to make sure the holder doesn't accidentally eat the mouse?

**Comment by Fishfish458** [comment]
guess I'll close this, I just think it's a bit weird to remove nutriment from something living with no repercussions to the mob.

**Comment by mirrorcult** [comment]
if you want to be really funny the food component should target their actual blood solution
