### ISSUE TITLE
Portable Flashers can flash very quickly

### ISSUE THREAD

**Issue by Mirino97** [space-wizards/space-station-14#7498]
## Description
Portable Flashers seem to randomly flash quickly (maybe every tick?) resulting in hundreds of flash a minute. It seems like they have no delay, detecting and reacting to every frame of player movement.

**Comment by ScalyChimp** [comment]
I can't replicate this, could you list some specific steps to replicate it? Trying it out on locally, it seems to be working just as intended.

**Comment by Mirino97** [comment]
Sure can! I wrote this at like, 4 am and I was dead tired, so I didn't go out and test it.
If I can replicate it successfully, I'll write the steps down here.
If not, I'll close the issue 'till I see the problem again.

**Comment by Mirino97** [comment]
I couldn't reproduce the issue I saw while in-game.
It is either a very flasher bug that somehow happens when 3 or more people are involved, or it's somehow related to latency.

I shall make a new issue if I ever get it happen again!

**Comment by Emisse** [comment]
ive had it happen on server but cannot replicate it locally, might be latency involved or something

**Comment by Mirino97** [comment]
I've managed to record it.

It possibly has something to do with latency AND also, possibly, with lack of energy?
Maybe it somehow flashes once for every time the area's apc ran outta juice? Just guessing here.
[LOUD VOLUME AT END OF VIDEO WARNING]
https://user-images.githubusercontent.com/52474532/163295936-c76704e9-e634-49e0-9548-51d54d057e21.mp4

**Comment by SlamBamActionman** [comment]
I have not seen this happen in ages. Needs replicating in current-day builds of the game.
