### ISSUE TITLE
Vending machine animation syncing

### ISSUE THREAD

**Issue by ShadowCommander** [space-wizards/space-station-14#755]
The vending machines don't sync their animations well.

Some of them like the NanoMed Plus only play the animation opening, then at the end instantly change back to the closed frame.

Others like the engineering vendors play the opening and closing animation, but close too early.

**Comment by RemieRichards** [comment]
is this before or after #749 ?

**Comment by ShadowCommander** [comment]
I think this is different. The NanoMed Plus might only have half the animation compared to the engineering ones. So to fix it, the engineering animations might need to be split and the NanoMed needs to have a close animation added.
