### ISSUE TITLE
Airlock visuals issue

### ISSUE THREAD

**Issue by collinlunn** [space-wizards/space-station-14#756]
Touching an opened access locked airlock with insufficient access breaks the visuals temporarily, causing it to appear closed

**Comment by SweptWasTaken** [comment]
Still an issue, video for demonstration.

![2020-07-01_22-31-35](https://user-images.githubusercontent.com/49448379/86319989-4e330600-bc25-11ea-9017-71327012578a.gif)

**Comment by tentekal** [comment]
Should be closed by #1341, Zumorica just merged it.
