### ISSUE TITLE
Ability to open end round statistics page after closing it

### ISSUE THREAD

**Issue by Fishfish458** [space-wizards/space-station-14#7567]
## Description

Currently if you're overly reactionary you can click out of the end round stats and won't be able to see it again.

Ideally there should be a button that can open end round stats back up after closing it.

bonus points for being able to open it in the next round lobby as well.

**Comment by wafehling** [comment]
Just a useful note: I'm not sure if this is always the case, but the trigger to load the end round stats works and can be repeatedly triggered in replays.

**Comment by wafehling** [comment]
https://github.com/space-wizards/space-station-14/pull/25884
