### ISSUE TITLE
Lights stop working if removed and replaced.

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#7574]
## Description

This was originally reported by Diego Armando#5075 on Discord. I have not verified it myself, but have had multiple reports of the same thing so at this point I consider that verified.

How to replicate:

-  Take a light tube or light bulb out of its fixture.
-  Put the tube or bulb back in.
-  The tube/bulb will be off, even though the fixture is powered.
-  Light switches can fix this but then have to be removed and can cause other issues.

**Screenshots**

https://images-ext-1.discordapp.net/external/mtMEF6ZuqmsD4rs1a_7BFUlSdNM2LstRAF10O1_ErDE/https/i.imgur.com/8ohiw4Z.png?width=1028&height=545

https://media.discordapp.net/attachments/790656972801572905/964633363984031774/unknown.png

**Additional context**

**Comment by Mirino97** [comment]
Dibs : D
