### ISSUE TITLE
Toggle internals on another person

### ISSUE THREAD

**Issue by Fishfish458** [space-wizards/space-station-14#7577]
## Description

In the examing worn/pickpocket UI there needs to be an additional button to toggle the internals usage on the person.

**Comment by mirrorcult** [comment]
if this is implemented i really wouldnt want it to be in the stripping menu, very weird place for that to be

**Comment by ZeroDayDaemon** [comment]
> if this is implemented i really wouldnt want it to be in the stripping menu, very weird place for that to be

where else would it logically be?

**Comment by ZeroDayDaemon** [comment]
the only other method i can think of is the examine text, but thats also still weird imo

**Comment by ElectroJr** [comment]
Stripping menu does seem like the most reasonable place to put it, especially seeing as you need to use the stripping menu anyway to place equipment on them if you're tying to anesthetize someone.
But before this is done the stripping menu just needs to be overhauled to not look like shit.

**Comment by ProfanedBane** [comment]
The stripping menu is also where this lives in ss13 iirc.

**Comment by Fishfish458** [comment]
It is in ss13 this way, which I know isn't a good excuse, though it would be the most relevant spot after you actually put the equipment on them.

I do agree with electro in that stripping menu could use a cleanup and would help facilitate it better.
