### ISSUE TITLE
Medical Beds are OP

### ISSUE THREAD

**Issue by Kromabae** [space-wizards/space-station-14#7590]
## Description
Medical Beds can heal people out of dead state all by their own it's ummm kinda OP, only thing they dont seem to heal is airloss but epi that while they comeo out of dead state and they are back again with no resources taken except some time

Maybe change it to be similar to how tricord is and make it not do healing if someone is above 200 damage?

**Comment by juliangiebel** [comment]
Medical beds should have a damage threshold where they won't heal if your above that.

**Comment by Elijahrane** [comment]
I thought this bug was fixed? People were doing it with bruise packs and bibles an other non-reagent healing methods since forever.

**Comment by Elijahrane** [comment]
Should be fixed by https://github.com/space-wizards/space-station-14/pull/7224

**Comment by Emisse** [comment]
i believe this was unfixed some how, ive seen multiple medical doctors raising the dead as of late

**Comment by Fishfish458** [comment]
There needs to be a dead and alive state on mobs that can be flicked off or on vs just some damage threshold.

currently long as anything is beyond 200 damage it just means dead, under means alive.

**Comment by Elijahrane** [comment]
The fix never got merged, this is a duplicate issue of https://github.com/space-wizards/space-station-14/issues/7076

**Comment by Elijahrane** [comment]
This issue is fixed
