### ISSUE TITLE
Pointing in mapping mode creates an unremovable arrow

### ISSUE THREAD

**Issue by EmoGarbage404** [space-wizards/space-station-14#7606]
## Description

When you point in mapping mode (shift middle-click by default) the arrow will stay stationary in position where you clicked and not go away. It is saved into the map as well, and can only be removed by going into the yaml. A simple fix would just be to disable pointing in mapping mode.

**Screenshots**

**Additional context**

**Comment by TimrodDX** [comment]
Pointing has a purpose, mostly for being able to tell where certain things are that you can't see (such as pipes under doors).

**Comment by EmoGarbage404** [comment]
the issue isn't pointing in general, it's that while in mapping mode, the arrow doesn't go away and it has to be manually scrubbed from the yaml, which is annoying.
