### ISSUE TITLE
Nettle Seed texture is inappropriately displayed when it is held in hand 

### ISSUE THREAD

**Issue by UKNOWH** [space-wizards/space-station-14#7607]
## Description

When holding a nettle seed , it will show you holding a nettle instead. 

**Screenshots**

<img width="1280" alt="nettle seed texture issue" src="https://user-images.githubusercontent.com/60119809/163700697-e08ecaed-45f2-4ed6-92a2-cccb2e1ae1d6.png">

**Additional context**

I looked into it a bit and concluded the reason why this doesn't happen to any other plant : all other plant doesn't have a texture for when you are holding them in the hand , only nettle do. 
I suggest spliting the texture file of the plant and its seed, it should avoid the engine being confused of the texture.

**Comment by Peptide90** [comment]
If non other seeds have inhands textures it's probably because nobody went to the effort or they were ported and they didn't exist before (see point 1).

Nettles are new and hence probably took the low effort (but not zero like other plants) and used the plants texture for the inhands to save time.

The fix is to create a generic inhands sprite for all seeds (since the detail is pointless tbh).

**Comment by UKNOWH** [comment]
> The fix is to create a generic inhands sprite

Is there any models I can follow to make the sprite

**Comment by Peptide90** [comment]
> > The fix is to create a generic inhands sprite
> 
> 
> 
> Is there any models I can follow to make the sprite

All clothing and a lot of items will have inhands if you look in the textures objects directory. You'll have to experiment in game to make sure the placement is right but you can probably find something similar as a base like donk pockets or some food item. Doesn't have to be perfect, just look like it's in a hand.

Then the inhands texture will have to be applied to the base if possible so all seeds inherit the same texture for it. Not sure if it'll get overridden by each item though.

**Comment by Elijahrane** [comment]
> Nettles are new and hence probably took the low effort (but not zero like other plants) and used the plants texture for the inhands to save time.

It was unintentional. The behavior is caused by the fact that seed.png and produce.png share the same rsi, so any inhands intended for the produce will also apply to the seed.

**Comment by Elijahrane** [comment]
> > > The fix is to create a generic inhands sprite

The fix is to somehow make seeds not use inhands meant for produce

> Then the inhands texture will have to be applied to the base if possible so all seeds inherit the same texture for it. Not sure if it'll get overridden by each item though.

It will get overwritten, and you will have the reverse of this bug where the seed packet inhands will display when you are holding any produce.
