### ISSUE TITLE
Open airlocks block raycasts

### ISSUE THREAD

**Issue by collinlunn** [space-wizards/space-station-14#762]
Blocks melee, hitscan laser, likely other things

**Comment by collinlunn** [comment]
After investigating with showrays, item pickup/drop raycast in not blocked, but melee and laser gun are. Might be an incorrect collision mask in melee/laser gun.

**Comment by Zumorica** [comment]
Related: #748, https://github.com/space-wizards/RobustToolbox/pull/1008
Basically, the raycasts need to ignore hard collidables. I added support for this in the engine PR linked above. Check the content PR for a simple example.

**Comment by tentekal** [comment]
rip
