### ISSUE TITLE
Destroyer pulse rifle doesn't work

### ISSUE THREAD

**Issue by Veritius** [space-wizards/space-station-14#7622]
## Description
When activated, it uses power but doesn't actually shoot a laser, nor do any damage.

**Additional context**
Discovered live in Lizard during an admeme event. The deathsquad died because their guns didn't work.

**Comment by TaralGit** [comment]
> ## Description
> When activated, it uses power but doesn't actually shoot a laser, nor do any damage.
> 
> **Additional context** Discovered live in Lizard during an admeme event. The deathsquad died because their guns didn't work.

I don't know what happened. It actually worked before the PR was merged, but now that I fetched upstream and tested it, it's not working anymore.

**Comment by mirrorcult** [comment]
worked when i tested the PR before merge as well so /shrug

**Comment by Veritius** [comment]
This also seems to affect the nightfall laser rifle.

**Comment by TaralGit** [comment]
> This also seems to affect the nightfall laser rifle.

Is there a limit on how many hitscan weapons the code can support? I was thinking that maybe for my next PR I should make pulse weapons into projectile guns. And I also noticed another thing: BarrelPump (shotguns) does not support automatic firing mode.

**Comment by Veritius** [comment]
> Is there a limit on how many hitscan weapons the code can support?

It's a modern game engine, I don't know why there would be a limit. Regardless, I don't think that's the issue at play here at all.

**Comment by Veritius** [comment]
Pancake said this was fixed so

**Comment by Pangogie** [comment]
The Deathsquad successfully used the Destroyer Pulse Rifle to eradicate a crew that was glorifying the Syndicate.
