### ISSUE TITLE
Lathe still breaking

### ISSUE THREAD

**Issue by AugustEymann** [space-wizards/space-station-14#7639]
## Description
Was able to print a single chemical payload and then tried another and it was not possible.

**Screenshots**
![image](https://user-images.githubusercontent.com/29801840/163878000-a1421cc1-91f7-40d5-9e87-a24b10a34c86.png)

**Comment by Elijahrane** [comment]
Anyone else able to reproduce?

**Comment by mirrorcult** [comment]
is this on the servers cause it just might not be updated yet

**Comment by AugustEymann** [comment]
yeah it was on Lizard Den i was able to print a timer trigger and a singular payload. but then it stopped
