### ISSUE TITLE
Chat eats my text

### ISSUE THREAD

**Issue by Mirino97** [space-wizards/space-station-14#7642]
## Description
I wouldn't be surprised if I'm the only one having this issue, but chat eats my text. Doesn't matter what I type in, after a certain threshold, it just deletes everything. Happens anywhere I can type, and when it happens, it's kinda global (happens in all typeboxes at once).

It is also seemingly random, coming and going as it pleases. All I can do when it happens is copy the text from somewhere else and send it.

I have tried reinstalling and all, no dice.

**Screenshots**

https://user-images.githubusercontent.com/52474532/163902127-f0935716-e318-4b5f-ba22-9669577e3d67.mp4

**Comment by Zymem** [comment]
Is this specifically when writing the 'a'? I had a similar issue, ended up realizing my computer kept either alt or ctrl pressed down.
Smashing the key a couple of times should fix it.

If this is related to ss14 itself and not the window lagging after switching tabs and stuff, then not sure what's happening.

**Comment by Mirino97** [comment]
It is not specific to one letter, sadly. It seems to be a set number of characters (about 15), but the characters are all.

**Comment by Mirino97** [comment]
@Zymem You know, you were right the first time. It is actually related to writing 'a'. I can guarantee my other buttons are not pressed down tho, I installed a visualizer.

**Comment by Mirino97** [comment]
I am now inclined to believe it actually has something to do with my keyboard/pc. Doesn't register in any visualizers, but instantly goes away if I press ctrl. Weird shit.
