### ISSUE TITLE
Hugging is only visible clientside

### ISSUE THREAD

**Issue by EmoGarbage404** [space-wizards/space-station-14#7644]
## Description

Simple as the title suggests. The hugging action can only be seen from the client side perspective. It's not a big deal, but it just is kind of weird. This is probably due to repurposed petting code.
**Screenshots**

**Additional context**

**Comment by UKNOWH** [comment]
it is wierd that when I hug someone they say they can't see me hugging them on their side

**Comment by ShadowCommander** [comment]
Need to do something like this
```cs
var othersMessage = Loc.GetString("comp-climbable-user-climbs-other", ("user", uid), ("climbable", args.Climbable));
uid.PopupMessageOtherClients(othersMessage);

var selfMessage = Loc.GetString("comp-climbable-user-climbs", ("climbable", args.Climbable));
uid.PopupMessage(selfMessage);
```

**Comment by Mirino97** [comment]
Ah look, my shitcode comes back to haunt me.

Ai'ight I shall be taking a look at this.

**Comment by BozoDel** [comment]
Now, if players can occasionally play as pets, they should know if they're being pet, no?
