### ISSUE TITLE
Component you can add to maps to change default gas mixture mobs are exposed to

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#7651]
## Description
Example: Add `MapSpaceGasComponent`, set gas mixture to 20% oxygen, 80 % nitrogen. Boom, instant EASY planet atmosphere...
Need to unhardcode a bunch of current atmos logic for this, though!

(Pair this with custom per-map parallax and a component to modify the movement behavior while walking on space tiles and you get simple planets.)

**Comment by metalgearsloth** [comment]
@Zumorica this was done right, or is this something else?

**Comment by Zumorica** [comment]
> @Zumorica this was done right, or is this something else?

Indeed. Closed by #8134
