### ISSUE TITLE
ALT+LMB hotkey to open containers not implemented

### ISSUE THREAD

**Issue by Victor239** [space-wizards/space-station-14#7660]
## Description
Rather than having to do RMB a container -> `Open UI`, this is a one-step hotkey which allows instantly opening the container menu. Has been implemented on /tg/ for many years now. 

**Screenshots**
N/A

**Additional context**

**Comment by ElectroJr** [comment]
FWIW, you can just use `e` by default.

Its a different binding and takes some time getting used to, but its also keeps things consistent, given that `e` is (or at least should) always open the UI on entities that have a UI, while alt-clicking often does other things. E.g., the chem-master UI opens via `e`, while alt clicking ejects beakers. Same scenario for the pda.

**Comment by Victor239** [comment]
> FWIW, you can just use `e` by default.

This `activate item in world` hotkey acts differently than an `open container` hotkey would act.

For example using `activate item in world` whilst holding an empty survival box in your active hand would unfold the box into cardboard, though on SS14 unfolding isn't implemented yet it seems and it will still act like `open container` instead.

It would be good for it to be separate to minimise any conflicts between existing muscle memory for migrating spessmans also.

**Comment by ShadowCommander** [comment]
I'll bring it up at the next maintainers meeting to figure out hotkey priority. It's going to be different from SS13, since we're going for consistency in how each hotkey works if possible. So E has been turned into the open UI button so far. Alt+Click has been the secondary function button since it's not quite as intuitive to non-SS13 players.

We have key rebinding, so feel free to swap it in your personal keybinds though.

**Comment by Victor239** [comment]
Makes sense, I avoid click dragging also except for jumping on tables also.

I tried rebinding it to ALT+LMB, the first thing I noticed is that I can't press the X close button for container pop-ups whilst still holding ALT which is a bit annoying. 

I should probably create an issue regarding the E hotkey as well, as I found not having generalised quick equip key to be almost as frustrating as well.

**Comment by Victor239** [comment]
Have created an issue regarding it now #7667

**Comment by mirrorcult** [comment]
we don't need a separate hotkey for this, E already exists

**Comment by mirrorcult** [comment]
if your problem is that E can potentially conflict with other actions, so will alt+click. the solution is to just make ordering explicit and make UI opening an important action

**Comment by mirrorcult** [comment]
for example if "unfolding a cardboard box" (which we don't even have) would conflict.. then it just shouldn't be on Z, and should be an alt interaction or verb instead

**Comment by ElectroJr** [comment]
> we don't need a separate hotkey for this, E already exists

activate-in-world still behaves differently from a dedicated `open UI` key. It might still be worth adding UI opening as a separate keybinding/interaction that just defaults to also using `E`, in case people want to change that.


> I tried rebinding it to ALT+LMB, the first thing I noticed is that I can't press the X close button for container pop-ups whilst still holding ALT which is a bit annoying.

Having modifiers not affect window closing might be useful and shouldn't be that hard to do.

> Makes sense, I avoid click dragging also except for jumping on tables.

FIY alt-interact on tables should also work start climbing

**Comment by helladamnleet** [comment]
I'm pretty sure he's saying instead of having to pick up a container, open it, then set it back down we should be able to ALT-Click the container to see what's in it..... Hitting "E" wouldn't do that.

**Comment by ShadowCommander** [comment]
> I'm pretty sure he's saying instead of having to pick up a container, open it, then set it back down we should be able to ALT-Click the container to see what's in it..... Hitting "E" wouldn't do that.

Hover over the backpack on the ground then hit E, it'll open the backpack without having you pick it up.

**Comment by PJB3005** [comment]
> activate-in-world still behave differently from a dedicated "open-UI" key. It might still be worth adding UI opening as a separate keybinding/interaction that just defaults to also using E, in case people want to change that.

This just devolves into having tons of special-case interaction bindings for various interactions, which is not a good idea long-term.

If an entity is complex enough to warrant having an UI then *it should be controlled by that UI*. I can think of **zero** examples of an entity that has a UI that *wouldn't* have activate be actually opening its UI. Misc actions like folding the box should be in the right-click menu if they even exist in the first place. (hell, I'd wager that they should be in the UI too, actually). 

Activate in SS14 is "use this ignoring your hands", left click is "use this in relation to your hands", and I think this model is very straightforward. The only way to make this clearer IMO would be to literally make left click do nothing if your hands are empty (and you aren't clicking to pick up an item). This would be somewhat similar to how Minecraft went and removed the ability to interact with doors/levers/buttons on left click (which was a good change for MC, despite the fact it screwed up everybody's muscle memory). I do not think this is a good idea for us though: the critical difference is that in MC, left click always still has a function. In SS14, it would not if your hands are empty.

**Comment by mirrorcult** [comment]
> I'm pretty sure he's saying instead of having to pick up a container, open it, then set it back down we should be able to ALT-Click the container to see what's in it..... Hitting "E" wouldn't do that.

have you played SS14 before? E does do that

**Comment by helladamnleet** [comment]
> > I'm pretty sure he's saying instead of having to pick up a container, open it, then set it back down we should be able to ALT-Click the container to see what's in it..... Hitting "E" wouldn't do that.
> 
> Hover over the backpack on the ground then hit E, it'll open the backpack without having you pick it up.

Thanks, that worked. I appreciate the actual helpful advice instead of a rude rhetorical question. I was confused by the fact it's not the same as SS13. Again, thank you.

**Comment by mirrorcult** [comment]
> I appreciate the actual helpful advice instead of a rude rhetorical question.

you'll get that if you assume that 4 separate developers must be misunderstanding the issue before assuming that the keybinds are just different from SS13
