### ISSUE TITLE
Gibbing balance discussion - making it harder to dispose of bodies.

### ISSUE THREAD

**Issue by Fishfish458** [space-wizards/space-station-14#7681]
## Description

Currently whenever someone wants someone gone, after they kill the person they'll just attack the body until it gibs to render them from being cloned(ignoring the current clone saving, hopefully soon to go). This makes taking someone out of the game pretty instantaneous long as they have something that can cause a decent amount of damage.

Rather than just being a general amount of damage until gib, I think it should return to the way it is on a various ss13 builds in that the minimum threshold to do gibbing damage is something like a minibomb right on an unarmored target.

This would mean that for someone needing to get rid of a body, methods such as using the kitchen gibber(spike), chaplain cremator, disposals grinder, spacing,  surgical tools to remove the brain, or hiding the body as sneakily as possible would need to be applied.

**Comment by freeman2651** [comment]
I agree with the need for some kind of specialized equipment to dispose of bodies permanently. It already kinda sucks if you get killed and your body stashed in a maint locker for nobody to find, but for another player to be able to completely destroy your corpse without any real added risk kind of removes any aspect of needing to dispose of bodies. It also makes you balance the need of permanently disposing the body and possibly getting caught (gibber, cremator, etc) versus stashing the body where hopefully nobody can find it and tie it back to you.

**Comment by mirrorcult** [comment]
not actionable enough
