### ISSUE TITLE
The arrows are wonky again

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#7743]
## Description

wonky
**Screenshots**

![unknown](https://user-images.githubusercontent.com/43253663/164954598-6d06d127-4cc7-48db-9043-d08b2270013a.png)

**Additional context**

**Comment by metalgearsloth** [comment]
I think they were changed to point from the person pointing weren't they? I still don't like it over noRot may not be a bug.

**Comment by ElectroJr** [comment]
Dupe of #7126
