### ISSUE TITLE
Weird reparenting issues when an entity moves across grids

### ISSUE THREAD

**Issue by Emisse** [space-wizards/space-station-14#7752]
Ghosts orbiting a player who moves across grids get left behind on the grid where the player last was. Players on ATVs traversing across grids ie crashing into a wall in space; get teleported to a random coordinate on said grid (not 0,0.) Probably more issues with this but this is just what I noticed and believe theyre related. Easy to repro both of the examples I listed.

**Comment by Elijahrane** [comment]
![Screenshot from 2022-04-24 21-52-00](https://user-images.githubusercontent.com/60792108/165008430-268490c3-d309-4a84-8527-fd344f16d5e2.png)
Containers in general seem pretty janky - this guy is alive and intact

**Comment by ElectroJr** [comment]
> which parenting basically is?

Things in containers should always be parented to the entity that contains them, but parenting is separate from containers. Things like roller beds don't use containers.
