### ISSUE TITLE
You can't unequip your hardsuit helmet because you need to unequip your hardsuit helmet first.

### ISSUE THREAD

**Issue by Elijahrane** [space-wizards/space-station-14#7762]
## Description

Not every time, but it happened to me last round.
1. Put on RD hardsuit.
2. Remove current helmet, use action to put helmet up.
3. Try to put helmet back down.
4. "You need to remove the experimental hardsuit helmet first" (or some similar message)

So basically I need to unequip the helmet I'm wearing before I can unequip the helmet I'm wearing. This is not possible.

**Screenshots**

**Additional context**

**Comment by Elijahrane** [comment]
Looking at it, this is probably because it has the equip verb when it should have the unequip verb?

**Comment by ElectroJr** [comment]
I can't manage to reproduce this. Using the RD suit & some generic hat. Was there some specific hat you were using?

The pop-up itself gets sent in `ToggleableClothingSystem.OnToggleClothing()`. It should only get sent if the action is used while an item is currently in the inventory slot AND there is some entity inside of the suit's container slot (i.e., helmet is retracted and not currently equipped).

The only way I can currently see that going wrong is if somehow some other item somehow gets inside of the suit's container while the helmet is equipped, but I don't see how that would have happened.

**Comment by TimrodDX** [comment]
I just saw this happen on a server. 

![image](https://user-images.githubusercontent.com/7907891/165659865-0418ade2-9f9b-4133-8c6d-6ee0c5a3a93c.png)

It looks like what happens is that the helmet can become de-parented from the suit, and then things get real confusing. I know after I got it off (you have to have someone strip you), my game would make the hardsuit helmet noise any time I put a hat on.

**Comment by ElectroJr** [comment]
If this happens again, it'd be good to get an admin with VV to check if there is some entity inside of the suit's container.

> my game would make the hardsuit helmet noise any time I put a hat on.

That's even more confusing. The sound is played by the inventory system when an item gets equipped or unequipped. I have no clue what would cause it to start playing that sound for unrelated hats.
