### ISSUE TITLE
Security Riot Shields

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#7778]
## Description
As of now there's no way to buckle down and stop people from running past you. A riot shield should:
- Have an action to enable blocking other players, in exchange for losing your movement unless you stop blocking (avoiding prediction cbt, yay!)
- Reduce damage somewhat, and significantly when blocking.

It should not require being wielded imo.

**Comment by metalgearsloth** [comment]
> (avoiding prediction cbt, yay!)

**Comment by keronshb** [comment]
This is something else I can look into. Are there any free keys to have as a block key. And if so, where would I look to find an example of it?
