### ISSUE TITLE
Make T-Rays only display subfloor clientside

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#7781]
## Description
GOD PLEASE I AM TIRED OF ENGINEERS LEAVING THEM OPEN AND SEEING THE CABLES AND TUBES EVERYONE I'M GOING INSANE
**Screenshots**

**Additional context**

**Comment by Mirino97** [comment]
HMMMMMMMMMMMMMMMMMMMMMMMMM

**Comment by Vordenburg** [comment]
Fixed by #14826
