### ISSUE TITLE
Vehicles are rendered above alien fungus

### ISSUE THREAD

**Issue by Froozigiusz** [space-wizards/space-station-14#7803]
I don't remember specific name for this plant, but it doesn't matter. Newly added vehicles (or maybe just this one) is placed above space  bush for some reason.
![image](https://user-images.githubusercontent.com/77325322/165317422-3484d10e-db90-4459-a7ab-7f0336ddb73c.png)

**Comment by Elijahrane** [comment]
Should be as simple as setting the max drawdepth lower (and hope that doesn't break anything else)
