### ISSUE TITLE
The road to MRP

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#7809]
# Easy features
- [x] The rules file to use needs to be made into a CVar and rules text needs sent from the server instead of bundled with the client, so servers can have their rules changed without modifying the codebase per server. (Done in https://github.com/space-wizards/space-station-14/pull/8365)
- [x] Map rotation map list and votable map list need made into `List<string>?` CVars that default to whatever the YAML says (null). This is so we can swap around map prototypes on MRP to, say, add additional MRP only roles (why would you play Prisoner on LRP for any reason except to murder sec?)
- [ ] CVar-controlled respawn, as an optional server feature. This isn't required, but experimenting with, say, a 15-min respawn timer that requires joining in with a different character might be nice, as MRP rounds will definitely last longer.
- [x] Admin buttons to manipulate what antags are in play. Especially to allow adding/removing traitors.
# Hard features
- [ ] LORE. We're currently incredibly light on lore, and MRP definitely needs more flavor and lore to build off of. LRP can simply disregard most of it.
- [x] Typing icons. (Done in https://github.com/space-wizards/space-station-14/pull/8215)
- [x] Radio channels, so that all departments can have their own internal radio channel.
- [x] Minimum play time requirements for important roles (esp command and sec)
- [ ] Dynamic needs finished, otherwise MRP rounds will stagnate, especially if all antags die.
- [x] Player character flavor text. This should be an examine button that lets you examine someone more closely. Bonus points if it's generic, so servers that have multiple types of flavor text don't suffer. Should be a CVar. (Done in #8070)
- [ ] Support for generalized whitelists. This would be mostly of help for other servers, but might let us whitelist specific features if they prove difficult to get consistently good experiences out of.
# Administrative changes
- [x] MRP Rules needs mocked up, written, and added to the codebase next to the normal rules file. This ties in to the rules CVar.
- [x] Administrative guidelines for MRP need written.
- [ ] A way to make server-specific/server-group-specific bans would be welcome, so we can ban players from all MRP servers we run (if we ever run more than one) without kicking them out of LRP if necessary.
# Open discussions
- What features do we need to make MRP engaging? More roleplay fluff definitely needs added, but ones to focus on are welcome (Don't make your own checkbox list, I'll add them under the features lists myself if you ping me on github)
- What existing features might we want to make configurable, so they can be disabled on MRP?
- Do we want to introduce an MRPPrototypes folder, containing MRP-exclusive content, or should we keep it with the existing prototypes data? (This also applies to LRP, so that could have an LRPPrototypes folder if necessary. Load order would be Prototypes first, then the RP level specific prototypes)
- Karma shop? #7842

**Comment by Elijahrane** [comment]
>Do we want to introduce an MRPPrototypes folder, containing MRP-exclusive content, or should we keep it with the existing prototypes data? (This also applies to LRP, so that could have an LRPPrototypes folder if necessary. Load order would be Prototypes first, then the RP level specific prototypes)

I think splitting content in two like that isn't very good for what's supposed to be the model upstream for all forks. That seems outside the scope of what this is for. The most I'd like to see is server configuration to disable specific events in dynamic

**Comment by WTCWR68** [comment]
> What features do we need to make MRP engaging? More roleplay fluff definitely needs added, but ones to focus on are welcome (Don't make your own checkbox list, I'll add them under the features lists myself if you ping me on github)
@moonheart08 
Perhaps adding in crew records could help people build characters (Medical, employment, security and general records).

Alongside this possibly paperwork could be a useful tool along with more strict job requirements (for head and AI in particular)

**Comment by moonheart08** [comment]
> > Do we want to introduce an MRPPrototypes folder, containing MRP-exclusive content, or should we keep it with the existing prototypes data? (This also applies to LRP, so that could have an LRPPrototypes folder if necessary. Load order would be Prototypes first, then the RP level specific prototypes)
> 
> I think splitting content in two like that isn't very good for what's supposed to be the model upstream for all forks. That seems outside the scope of what this is for. The most I'd like to see is server configuration to disable specific events in dynamic

It is less a split and more a "add a handful of features on MRP"
For example Prisoner would be enabled this way.
Many servers that do an RP/No-RP split either have one side prioritized, or have two separate codebases, one of which has been dead for the past year because it's diverged too hard and nobody can maintain it.
This allows for a much smaller scale split.

**Comment by ike709** [comment]
> The rules file to use needs to be made into a CVar

Is it really better to have the entirety of the rules stored in a cvar instead of like... a txt file?

**Comment by mirrorcult** [comment]
> > The rules file to use needs to be made into a CVar
> 
> Is it really better to have the entirety of the rules stored in a cvar instead of like... a txt file?

 ..pretty sure she means a cvar for the path to the rules file

**Comment by ike709** [comment]
Oh right I did misread that yeah.

**Comment by Morb0** [comment]
Some thoughts on what's missing for MRP.

- Icon that shows that person is typing is very helpful for RP.
- Station threat levels. Adds a lot of content. From compliance with special rules by crew for specific level and more variety for Sec, to great opportunities for CentCom.
- Minimum number of hours for certain roles - it has often happened that newcomers take important roles and do not understand what to do on them.
- The white list for races. At the MRP level, players for other races must know at least lore of their race and be able to correctly role play. Behavior of many players on other races is no different from humans.
- Now there is chaos in common channel and it is easy to miss important messages, for example from the captain, it is necessary to divide the channels into departments or/and add job tag after name. (it seems that someone has already worked on this)
- Also, setting highlighting of certain text in chat is very helpful to see when you are approached and do not miss messages in general channel.
- Will be nice to see an advanced text editor (Markdown?) for papers and revive bureaucracy (with ability draw on paper by mouse PogChamp).
- Adding/removing traitor roles by admins and manage traitor goals (CRUD) will be very usefull for event makers.
- ~~Flavor text that could be reviewed by analogy with health information.~~
- Emotions directed at other players. For example, give five. I liked how this is done on tg in form of skills in the active hand.
- Ability to give an item from hand to hand.

**Comment by WTCWR68** [comment]
> The white list for races. At the MRP level, players for other races must know at least lore of their race and be able to correctly role play. Behavior of many players on other races is no different from humans.

I actually am hoping to discuss this next maintainer meeting @Morb0

**Comment by Fishfish458** [comment]
Extensively knowing race lore actually sounds more along the HRP lines. Understanding mannerisms yes but whitelisting species no.

**Comment by Peptide90** [comment]
> Extensively knowing race lore actually sounds more along the HRP lines. Understanding mannerisms yes but whitelisting species no.

Agree. As long as they understand the minimum which is name convention and mannerisms (wiki will do) but in general whitelist ability is needed for special cases, forks etc. 

All other good points raised by others though, tcoms will be a lot more important for MRP than LRP but as a minimum product we can live without I think.

**Comment by TimrodDX** [comment]
The problem with playtime tracking is that there's a large potential audience for MRP/HRP servers coming from SS13 who have hundreds of hours logged there, but haven't played SS14 yet. Forcing them to unlock stuff might be a turn-off for that kind of player.

The races I think would also need to be modified in that most of the ones we have are kind of parodies of existing material that lend themselves more to comedy than to "serious" roleplay.

**Comment by Fishfish458** [comment]
> The problem with playtime tracking is that there's a large potential audience for MRP/HRP servers coming from SS13 who have hundreds of hours logged there, but haven't played SS14 yet. Forcing them to unlock stuff might be a turn-off for that kind of player.

Playtime tracking would be fine if it's just for job unlocks specifically, but not a fan of it for unlocking anything else.

**Comment by Morb0** [comment]
> The problem with playtime tracking is that there's a large potential audience for MRP/HRP servers coming from SS13 who have hundreds of hours logged there, but haven't played SS14 yet. Forcing them to unlock stuff might be a turn-off for that kind of player.

From my observations, percentage of players who came from SS13 is very low, and I understand why. In SS14, the main players are those who, for whatever reason, can not or do not want to play SS13.
Even an experienced SS13 player would do well to play on assistant and get to grips with new controls.

**Comment by juliangiebel** [comment]
> All other good points raised by others though, tcoms will be a lot more important for MRP than LRP but as a minimum product we can live without I think. More of a "nice to have" category of things that make it run smoother.

Having proper departmental channels and knowing **who just ordered you over common** by having their job next to the name is essential to MRP imo.

PDA messages would be really good in the future, with an option for them that makes them additionally display in chat.

**Comment by Froozigiusz** [comment]
Third tab in the Information menu giving a bit of introductory lore for the specific map/server. Short description of what's happening is enough and it's in convenient place.

**Comment by Peptide90** [comment]
> Third tab in the Information menu giving a bit of introductory lore for the specific map/server. Short description of what's happening is enough and it's in convenient place.

Think this is embodied in our need for ingame guides and stuff in general, so probably file that there as an good option but not necessary to get going.

**Comment by Froozigiusz** [comment]
> > Third tab in the Information menu giving a bit of introductory lore for the specific map/server. Short description of what's happening is enough and it's in convenient place.
> 
> Think this is embodied in our need for ingame guides and stuff in general, so probably file that there as an good option but not necessary to get going.

There is a difference between in-game tutorial/wikipedia and short introduction of _what_ and _where_ per station/session, but I can see your point. I just thought of something similar to the EU4 opening screen talking about region, politics, religion , etc. and not needing to search them in a wiki.

**Comment by Peptide90** [comment]
> > > Third tab in the Information menu giving a bit of introductory lore for the specific map/server. Short description of what's happening is enough and it's in convenient place.
> 
> > 
> 
> > Think this is embodied in our need for ingame guides and stuff in general, so probably file that there as an good option but not necessary to get going.
> 
> 
> 
> There is a difference between in-game tutorial/wikipedia and short introduction of _what_ and _where_ per station/session, but I can see your point. I just thought of something similar to the EU4 opening screen talking about region, politics, religion , etc. and not needing to search them in a wiki.

My bad I guess I misunderstood, this the F1 menu? In general there's roadmap stuff we need in for the server browser for things like MOTD but yeah if maps can have a pre packaged blurb and picture that would be ideal for both map voting if servers use that as well as an info page.

**Comment by KuroReaper** [comment]
So far I concur with most of the ideas for MRP. But the PDA messaging and radio channels is a must before you establish that sort of setting.

**Comment by Snowni** [comment]
I think there's a lot of proposed items here that are necessary to make MRP smoother. They'd benefit LRP as well but these are QoL stuff that we could sorely benefit from, to make the experience better for players. The typing indicator is pretty huge. I think we need that one before we launch it. Radio channels and what not would be a huge help, but might not necessarily be required. At minimum, just having the job title beside their name might suffice, but that's at a bare minimum. As is, it's way too difficult to lose the plot when looking through common.

How soon did we want this server to go up? Seems to me we may want to implement more features first.

**Comment by moonheart08** [comment]
> I think there's a lot of proposed items here that are necessary to make MRP smoother. They'd benefit LRP as well but these are QoL stuff that we could sorely benefit from, to make the experience better for players. The typing indicator is pretty huge. I think we need that one before we launch it. Radio channels and what not would be a huge help, but might not necessarily be required. At minimum, just having the job title beside their name might suffice, but that's at a bare minimum. As is, it's way too difficult to lose the plot when looking through common.
> 
> How soon did we want this server to go up? Seems to me we may want to implement more features first.

There is no assigned timeline.

**Comment by Snowni** [comment]
Probably for the best that it doesn't get rushed then, despite the excitement.

**Comment by Mannybrado** [comment]
PDA messaging isn't *needed*, but radio channels are incredibly important for RP. Everyone talking on the same radio channel at the same time is not exactly great for RP. PDA messages let people communicate without using the common channel, which is to say that asking "Hey Jimmy, where are you?" over the main station comms channel is cringe.
Typing indicator is utterly essential, like, completely. 

My current worries for an MRP server generally stem from, well... the game's just not ready. Enforcing rules is one thing, but when you only have the bare-minimum for higher-level roleplay in place, all you have holding everything together is going to be the rules. If people aren't pressed to interact and to play their character, the roleplay environment will eventually suffer. The best possible roleplay experience is one where the gameplay holds up the roleplay, and its just nowhere near that point yet. I do guess that experimenting by letting people do more character-driven roleplay with tighter expectations could be interesting, but I just REALLY REALLY hope that this doesn't end up as a version of LRP code but with stricter rules. 
This is kind of precedent-setting for this project and I hope it goes well.
🤓

**Comment by Mannybrado** [comment]
the lore channel should be brought back for discussing it on the discord

**Comment by ike709** [comment]
Species need naming conventions and the name randomizer needs to follow it. For example, lizards are `Verbs-the-Noun` like `Mops-the-Floor`, but other middle-words are often allowed.

**Comment by ike709** [comment]
Space law needs to be added to the TODO list

**Comment by Veritius** [comment]
@moonheart08 Typing indicators were done in #8215

**Comment by ike709** [comment]
Rules cvar can be ticked off the list

**Comment by Androidonator** [comment]
In my honest opinion adding PDA DM's is a must for MRP and whispering like literally one character whispering to another.

**Comment by mirrorcult** [comment]
we have whispering

**Comment by juliangiebel** [comment]
> In my honest opinion adding PDA DM's is a must for MRP and whispering like literally one character whispering to another. Also station goals and points to incentivise good behavior.

I will be working on PDA DMs in the near future.
It comes after PDA Cartridges on my list of things I want to implement.

**Comment by Visne** [comment]
> Minimum play time requirements for important roles (esp command and sec)

Think this can be ticked off now.

**Comment by Morb0** [comment]
A very important but forgotten thing - the fax machine
The communication of the station and the centcom through announcements is terrible...

**Comment by DogZeroX** [comment]
Still relevant I suppose

**Comment by UbaserB** [comment]
i thought we didnt want lore for MRP

**Comment by moonheart08** [comment]
> i thought we didnt want lore for MRP

last I was involved, we didn't want it for LRP but were okay with it for MRP.

**Comment by mirrorcult** [comment]
we have mrp now should be separated into diff issues now
