### ISSUE TITLE
Driving an ATV to space teleports you to 0,0 and deletes the ATV.

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#7810]
## Description

How to replicate:

- Spawn or otherwise acquire an ATV.
- Drive the ATV out an external airlock. 
- You will be warped to wherever 0,0 is on the map (for Delta, this is the AI chamber).
- The ATV will be deleted.

This is particularly egregious on Bagel, because 0,0 on Bagel is in the bridge.

**Screenshots**

![image](https://user-images.githubusercontent.com/7907891/165404610-1b74df80-e3ed-4ec0-b9db-7e61586f88e5.png)

![image](https://user-images.githubusercontent.com/7907891/165404632-4bb03974-e90b-4da5-bc50-30ad4d2ab3d4.png)

**Additional context**

**Comment by mirrorcult** [comment]
AFAICT it's not always to 0,0 because on pillar people were getting teleported to somewhere in science, whereas 0,0 was near engineering

**Comment by TimrodDX** [comment]
> AFAICT it's not always to 0,0 because on pillar people were getting teleported to somewhere in science, whereas 0,0 was near engineering

I did some testing on it, using a couple of different airlocks on Delta. I went to 0,0 every time.

**Comment by TimrodDX** [comment]
Gluttony#1167 on Discord also found that closing a locker around someone on a vehicle teleports them to 0,0.

![image](https://user-images.githubusercontent.com/7907891/165415596-4afe35e3-f23d-4a9b-9a0f-5297842b817c.png)

![image](https://user-images.githubusercontent.com/7907891/165415636-c9e7d0ff-f282-4f96-8d17-109134079e59.png)

![image](https://user-images.githubusercontent.com/7907891/165415657-74e267a7-ff86-47cf-ae3b-091529d82fd5.png)

![image](https://user-images.githubusercontent.com/7907891/165415674-d244ac4d-be58-43c5-9de4-0d82a8c274bd.png)

**Comment by Elijahrane** [comment]
https://github.com/space-wizards/space-station-14/issues/7752

**Comment by 0Pdude** [comment]
It never deletes the ATV or any vehicle from my experience with the bug.

**Comment by Elijahrane** [comment]
Tried reproducing this, got this error
[atvinlockerlog.txt](https://github.com/space-wizards/space-station-14/files/8567776/atvinlockerlog.txt)

**Comment by PaulRitter** [comment]
> Gluttony#1167 on Discord also found that closing a locker around someone on a vehicle teleports them to 0,0.

discount cursed locker
