### ISSUE TITLE
Traitor guns really need a buff.

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#7812]
## Description

Right now, even the most basic Security officers are so armored that they can eat an entire pistol magazine to the face and not die. This is all tested on local, with the sec officers having the gear they spawn with (so no armory gear):

Predator vs. Sec Officer: 7 shots to crit (1 full cylinder plus a single round). This is half of a traitor's TC to crit (not kill) a single sec officer.
Clarissa vs. Sec Officer: 11 shots to crit (1 full magazine plus a single round). This is also half of a traitor's TC.
Mandella vs. Sec Officer: 8 shots to crit (this is probably the best performer, only costing all but one bullet in a full magazine).
Kardashev-Mosin vs. Sec Officer: 10 shots to crit (1.5 clips). 
Energy Sword vs Sec Officer: 5 hits to crit

Now let's compare this to the guns orderable from Cargo:

Drozd vs Sec Officer: 8 shots to crit (roughly 1/3 of a magazine)
Gladstone vs. Sec Officer: 3 shots to crit (roughly 25% of capacity)

What this tells me right away is that there's almost no point buying any of the guns when the e-sword exists, because you're just as likely to get disarmed but it'll take several times as long to kill even the most basic sec officer. This gets even worse with the Warden (who can generally absorb one more hit) and the HoS (who can eat almost two full Mosins to the face) in play. It also tells me that Cargo has much better traitor gear than the actual traitors do.

**Screenshots**

**Additional context**

**Comment by Fishfish458** [comment]
This definitely doesn't sound like the guns need a buff, just that body armor needs to get looked at. Currently you can waste anyone else with no armor really quickly if you get the jump on them.

**Comment by BlitzGunner225** [comment]
While I though at first that nerfing armor would be good, it doesn’t account for cargo stuff being just far better 
So slightly buff all the syndie weapons so most need one entire mag to kill. While the one mag and one bullet balance sounds good on paper, it doesn’t account for the fact that everyone will miss at least once with 7-11 shots needed. It should still stay at an entire mag for most guns as you can kinda close in for one melee swing before they fully stun you. Not only would this make the guns compete better against cargo, but it would also make syndie guns more complicated as you would have to use up the ammo as wisely as possible or be forced to buy more with your precious tc.

**Comment by Peptide90** [comment]
> While I though at first that nerfing armor would be good, it doesn’t account for cargo stuff being just far better
> So slightly buff all the syndie weapons so most need one entire mag to kill. While the one mag and one bullet balance sounds good on paper, it doesn’t account for the fact that everyone will miss at least once with 7-11 shots needed. It should still stay at an entire mag for most guns as you can kinda close in for one melee swing before they fully stun you. Not only would this make the guns compete better against cargo, but it would also make syndie guns more complicated as you would have to use up the ammo as wisely as possible or be forced to buy more with your precious tc.

People use standard ammo as syndie? :heck:
Bulldog with dragons breath is the bomb. If syndie don’t have access to the different ammo’s then that’s something we can look at for AP and HV rounds.

**Comment by metalgearsloth** [comment]
Someone let me know if this is still an issue after gun refactor. Ballistic stuff got heavily tweaked and syndie weapons should outclass NT weapons.
