### ISSUE TITLE
There is texture for welded vents and scrubbers , but no in game function

### ISSUE THREAD

**Issue by UKNOWH** [space-wizards/space-station-14#7818]
## Description

There are textures for welded vents and scrubbers but is game if you weld a vent/scrubber you just deconstruct it.
**Screenshots**

![vent_welded](https://user-images.githubusercontent.com/60119809/165506607-8243679c-2a03-40c6-9b5d-12e5089a6c6f.png)
![scrub_welded](https://user-images.githubusercontent.com/60119809/165506622-649bb9d2-8277-49cd-a7b0-37e18953e148.png)

**Additional context**
A possible fix is add an additional "screw" step to the deconstruction of vents and scrubbers

**Comment by Peptide90** [comment]
Pretty sure the visualiser supports the welded states so yeah construction issue. Easy fix if anyone wants this assigned or I can do it tomorrow.

**Comment by Peptide90** [comment]
#7896 related but not a full fix as welding them doesn't seem to work.
