### ISSUE TITLE
InRangeUnobstructed bug

### ISSUE THREAD

**Issue by collinlunn** [space-wizards/space-station-14#782]
Using insideBlockerValid = true has an edge case. If the target is behind something of the collision mask but still under 1 range away, you can interact through the mask. Ex: through a diagonal line of walls. 

An example of building an apc through a diagonal wall
https://gyazo.com/bfb742e539f9f4c1e48571d5a284defc

**Comment by Zumorica** [comment]
#759
fuck. I'll try to come up with a better solution for this in the near future, but for now I think this low priority
