### ISSUE TITLE
AI has trouble pathing through open doors

### ISSUE THREAD

**Issue by Elijahrane** [space-wizards/space-station-14#7851]
## Description

A lot of space mobs seem to get stuck. Some, like carp, seem to be able to go through doors but space ticks, etc can't

Repro steps:
1. Launch local sandbox
2. Spawn a space tick or something on the other side of a door
3. Open the door
4. Walk into the room then immediately out
5. The space tick will stop at the open door

**Comment by DogZeroX** [comment]
Haven't seen this happen recently.
