### ISSUE TITLE
Medical Techfab Wont accept plastic

### ISSUE THREAD

**Issue by Kromabae** [space-wizards/space-station-14#7865]
## Description
Title

tried putting plastic in the techfab but it wont accept it, even though it has items in it that need plastic

**Comment by ShadowCommander** [comment]
Can you test whether that is after queuing something that didn't have enough materials? There's another bug with lathes where they don't accept materials if more recipes were queued than there were materials to build it.

**Comment by Kromabae** [comment]
HAven't had time to test it any futher, but did see some sci bois running into the same issue and i told them to test making a new lathe and see if that solved it. It did now, so something is scuffed with lathes or weird at least

**Comment by Peptide90** [comment]
> This was fixed with #7862 and #7863, not sure when it will get pushed to the server tho
> 
> > There's another bug with lathes where they don't accept materials if more recipes were queued than there were materials to build it.
> 
> Unrelated to this though 0.0

Closing this in favour of the other bug and the fixes. Will open if still an issue.
