### ISSUE TITLE
Pneumatic Cannon No longer shoots it's contents

### ISSUE THREAD

**Issue by Kromabae** [space-wizards/space-station-14#7871]
## Description
stuff cannon full of plushies to test shot it, uses the gas but doesn't shot it's content out, big sad

**Comment by BlitzGunner225** [comment]
Are you using the tiny tank cuz the tiny tank won’t work

**Comment by Kromabae** [comment]
no the one you make in crafting, but tiny tank hello now you got my senses peaked

**Comment by Kromabae** [comment]
sorry for not responding, haven't had time to test that but i did see some sci bois running into the same problem and i told them to make a new proto lathe and see if it fixes the issue. It did not so something is scuffed

**Comment by asperger-sind** [comment]
Pretty sure this bug also applies to pie cannons, probably some refactor borked it.
