### ISSUE TITLE
We need more sound effects to use

### ISSUE THREAD

**Issue by juliangiebel** [space-wizards/space-station-14#7874]
## Description
We need more generic sound effects with licenses we can use when implementing new content. Especially generic ones so you don't have to reuse the same deny sound over and over or can make more sound collections to randomly pick sounds from so the sound that plays is different each time.

Some generic effects that come to mind:
* Beebs and bloobs for computer or machine interactions
* Generic machine noises
* Alarm and notification sounds
* Deny sounds

We should probably collect them somewhere until someone uses them.

**Comment by nearlyNonexistent** [comment]
Oh, I have a list of places that store royalty-free sound effects back from when I did stuff on baystation 12's codebase (never got around to using them, got distracted porting tg content). Hold on:

https://github.com/zulubo/Zulubo-Sounds
https://www.zapsplat.com/sound-effect-categories/
https://sonniss.com/gameaudiogdc
https://99sounds.org/free-sound-effects/
https://freesound.org/
https://opengameart.org/art-search-advanced?keys=&field_art_type_tid%5B%5D=13&sort_by=count&sort_order=DESC
http://raisedbeaches.com/octave/
https://www.playonloop.com/sound-effects-for-videos/riser-crescendo-sounds/

And a tool for making pure synthesized sound effects: https://www.bfxr.net/

The majority of them are CC-BY, some are likely public domain, some are indexes.

**Comment by mirrorcult** [comment]
really not actionable
