### ISSUE TITLE
Airlock construction duplicates door electronics

### ISSUE THREAD

**Issue by ShadowCommander** [space-wizards/space-station-14#7878]
## Description

Repeatedly doing the last step of airlock construction creates another door electronics.

This is caused by DoorSystem check for the board container being in MapInit which is run before the board container is transferred by the ConstructionSystem. This causes the DoorSystem to add a new board container and door electronics, then ConstructionSystem adds the existing board container and door electronics to the newly completed airlock.

**Screenshots**

**Additional context**

A temporary fix can be created by spawning the board during deconstruction instead of MapInit like it was initially implemented, though that would have to be redone when door electronics access is implemented.

The real solution is to implement door electronics access and add that in a container to every door instead of spawning it through the DoorSystem.

**Comment by ElectroJr** [comment]
> and add that in a container to every door instead of spawning it through the DoorSystem.

I'm not sure what you mean by this, whatever you do it will have to be spawned via some system, unless you mean the container should always spawn empty and mappers have to somehow manually insert the board.

The only easy-ish fix I can think of is having a empty & filled variants of the prototypes and making sure that construction steps use the empty variants.

**Comment by ElectroJr** [comment]
#11772 Tries to fix this by just having the construction system prevent some on-map-init container filling for managed containers. Tough that also feels kinda icky.
