### ISSUE TITLE
Rejuvenate doesn't cure diseases.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/space-station-14#7879]

**Comment by Peptide90** [comment]
#5743 also related to rejuvenate for anyone taking a look.

**Comment by Elijahrane** [comment]
Works on my machine, I closed https://github.com/space-wizards/space-station-14/issues/7485 via https://github.com/space-wizards/space-station-14/pull/7495 a while ago. Did it stop working? I can't reproduce

**Comment by UKNOWH** [comment]
Pretty sure it does cure

**Comment by Peptide90** [comment]
Just tested locally and it seems to work. Tested by giving myself OwO and rejuventaing. It still shows under all diseases but passes it to "past diseases" so closing.
