### ISSUE TITLE
Lathe que bug

### ISSUE THREAD

**Issue by UKNOWH** [space-wizards/space-station-14#7881]
## Description

If you manage to que up something that the lathe had no resource to produce at the time , it would clog up the lathe's que , rendering it useless. And the issue would persist even if you inserted the nessary resource.

Step to reproduction :
1. Put 30 glass/steel/plastic into the lathe
2. spam click the crew monitor until it turns black
3. insert more resource and the lathe will not produce more and is now broken
**Screenshots**

https://user-images.githubusercontent.com/60119809/166107356-d56bbef1-0092-4df1-ae8c-4cc53cdca7ef.mov

**Additional context**

**Comment by Elijahrane** [comment]
Was able to reproduce, I'll attempt to fix it

**Comment by ElectroJr** [comment]
Is this the same bug that caused #7639?

**Comment by UKNOWH** [comment]
> Is this the same bug that caused #7639?

I think so
