### ISSUE TITLE
No singul is spawned when you put a bag of holding into a bag of holding

### ISSUE THREAD

**Issue by UKNOWH** [space-wizards/space-station-14#7888]
## Description

<img width="1280" alt="Screen Shot 2022-05-01 at 8 02 44 PM" src="https://user-images.githubusercontent.com/60119809/166145602-e297ca96-5398-4510-92d4-2f607bb93b68.png">

**Screenshots**

**Additional context**

Also pizza boxes are broken but I am trying to fix them

**Comment by slarticodefast** [comment]
Sounds like an admin nightmare if we would implement that. Closing.
