### ISSUE TITLE
The singularity bounces off of tiles.

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#7924]
## Description
Currently the singularity has little threat, because it tends to simply take a tiny bite out of the station and then bounce away, rendering it harmless (unless you trip)

**Additional context**
Can be reproduced on any station, most evident on stations with a large, enclosed singularity cage.

**Comment by mirrorcult** [comment]
its scawed

**Comment by Emisse** [comment]
just witnessed a round where a playermade shuttle rammed a lvl1 singulo and the singulo bounced off the shuttle without it taking any damage. some thing mayyy be up with it

**Comment by metalgearsloth** [comment]
Might be from collision group refactor? Singularity's fixture probably just needs fixing.

**Comment by mirrorcult** [comment]
was collision group refactor even merged?
