### ISSUE TITLE
"Toggable" Component

### ISSUE THREAD

**Issue by AJCM-git** [space-wizards/space-station-14#793]
Currently you have to mess around/make components to make an item change its sprite depending if its On/Off. This behviour should be a component itself.

**Comment by Hugal31** [comment]
As discussed on Discord, in #howdoicode the 29 April 2020 around 7:00 AM UTC (sorry, I don't know how to link), it is very hard to have a clearly defined, generic and useful behavior for a Toggleable component.

For instance, the Welder component cannot be toggled on if there is not enough fuel. Implemeting it with a Toggleable component would require some work to make the two components (Toggleable and Welder) communicate with each others, which is not worth compared to just implement IUse for now.

**Comment by RemieRichards** [comment]
@Hugal31 you can right-click a message in discord to get a link to it.

Your question, for example:
https://discordapp.com/channels/310555209753690112/560845886263918612/704955322019610645

**Comment by AJCM-git** [comment]
I have come to the conclusion that this is not a good idea and that there are better ways to implement this behavior
