### ISSUE TITLE
Drones need more nerfing

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#7930]
A single drone managed to ruin 2 rounds in a row again (see game-admin-general) and require admin intervention. A ghost role shouldn't require admins to actively babysit them not griefing, especially considering 90% of the time an admin isn't available to immediately deal with the problem.

1. They should be noticeably slower than a normal mob so they can be caught if causing problems
2. Scooting under doors is problematic as they can easily get away and continue spacing, messing with the engine, cutting wires, etc. It should be changed back to access but limited access not the AA they had before that also caused problems.

**Comment by metalgearsloth** [comment]
tl;dr make them more like goon drones.

**Comment by BlitzGunner225** [comment]
I think they should instead be more of a personal assistance drone. 
* It is an item and must be started up to search for a soul and shut done to destroy the soul like a pai. It will also shut down if it is not in someone’s inventory or if another is turned on.
* The drone can be deployed and returned like a holo, including returning when too far. 
* The drone must do what the user says.
* No drones exsist at round start 
* Drones cost 15 more metal and plastic
Now the drone would always have rough supervision on it and it would be more useful for everyone.

**Comment by Peptide90** [comment]
> I think they should instead be more of a personal assistance drone. 
> 
> * It is an item and must be started up to search for a soul and shut done to destroy the soul like a pai. It will also shut down if it is not in someone’s inventory or if another is turned on.
> 
> * The drone can be deployed and returned like a holo, including returning when too far. 
> 
> * The drone must do what the user says.
> 
> * No drones exsist at round start 
> 
> * Drones cost 15 more metal and plastic
> 
> Now the drone would always have rough supervision on it and it would be more useful for everyone.

This mostly goes against what drones are. They should not interact with crew.

Long term there should be a cool-down on picking the role and they should provably be produced by engineering in a drone fab rather than available at round start.

Additional limitations as Sloth suggests are easily the minimum and are traditional to SS13 (slower, very weak so easy to kill, Engi access only). There are other limitations we could add but that's a wyci.

What you want is pAI pets which are easy to add.

**Comment by DogZeroX** [comment]
They are not playable currently

**Comment by Hmeister-fake** [comment]
Close cause drones are phased out pretty much?
