### ISSUE TITLE
Particle Accelerator gets stuck if it's in the singularity shader.

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#7933]
## Description

This is a problem that's mostly on Delta due to how bad Delta's singularity area is, but it's still applicable on other stations because of how big the singularity shader can get.

How to replicate:

- Spawn (or construct) a particle accelerator. I did this in Delta's PA room when testing an unrelated bug.
- Turn the PA to 2 in order to spawn a singularity.
- Once the singularity spawns and the shader turns on, you will no longer be able to interact with the PA computer.

**Comment by 20kdc** [comment]
> Is this because ScreenToMap looks different from a player's perspective? Because that one's not really fixable.

It's fixable but the consequences are potentially worse than what it's curing (as it would likely make clicking anything near the singularity a complete nightmare when the singularity is in motion, and it requires a separate C# copy of the shader's logic)
