### ISSUE TITLE
View Rotation bugs

### ISSUE THREAD

**Issue by AJCM-git** [space-wizards/space-station-14#794]
- Rotating the view make the lighting go crazy. It seems like the camera rotation is not compatible with the lighting system

![image](https://user-images.githubusercontent.com/60196617/77534262-af9d4900-6e6e-11ea-991b-b38c1870f70b.png)

- It also seems to unload chunks of the map sometimes when in a weird angle EDIT: I think its a PVS issue, it happened while the camera was zoomed out while driving a shuttle.

![image](https://user-images.githubusercontent.com/60196617/77534428-ff7c1000-6e6e-11ea-97a6-b859a73ac441.png)

- I dont know if this is intended as a design feature, but changing the rotation doesnt change the way you move.

**Comment by metalgearsloth** [comment]
Most of these are done apart from FOV so just gonna close as PJB will do it when he has time.
