### ISSUE TITLE
Throwing a tile at a panel window destroys the tile, not the window.

### ISSUE THREAD

**Issue by vulppine** [space-wizards/space-station-14#7952]
https://user-images.githubusercontent.com/76629141/166940235-364586a1-e566-4461-8042-b3cb2315bc4c.mov

**Comment by asperger-sind** [comment]
Rather certain that this is intended and the offspring of https://github.com/space-wizards/space-station-14/pull/7858

**Comment by vulppine** [comment]
alright, disregard this then
