### ISSUE TITLE
Drones have the ability to toggle harm/disarm

### ISSUE THREAD

**Issue by retequizzle** [space-wizards/space-station-14#7953]
## Description
Pretty straightforward bug report here. At some point in the last 24-48 hours, drones apparently got the ability to toggle both harm and disarm modes. This does allow them to hit certain objects/entities that do not violate their laws _directly_, such as windows, doors, etc. 

You still cannot melee within 4 tiles of a sentient being, but it also potentially allows them to bypass whitelist restrictions in terms of destroying items they may not be able to pick up. Appears to be limited to furniture and some minor entities, but there is potential for abuse here. May not be necessary to fix right away in the event #7931 does get merged.

Steps to repro:
1. Select any drone ghost role.
2. There is no Step 2. You should have the options available in your hotbar.

**Screenshots**
![image](https://user-images.githubusercontent.com/67210376/166966036-3c45b94f-ea36-4f42-9152-9759aac466be.png)

**Additional context**

I am fairly certain they can also hit and destroy other drones, though with the average drone gameplay we've had lately that might be more of a benefit than anything. Also looks like they can hit non-sentient animals including Ian and Renault.

**Comment by Macoron** [comment]
Rise of the machines

**Comment by Elijahrane** [comment]
The original way I prevented them from being able to do that was just not giving them the combat mode or disarm actions. Something must be causing those to populate when they weren't before.
