### ISSUE TITLE
QoL update for the new Markings system

### ISSUE THREAD

**Issue by Froozigiusz** [space-wizards/space-station-14#7954]
Markings system is a great mechanic for broader customisation of characters, but the experience of using it is leaving much to be desired:
~~- [ ] Unused markings list should stop changing order of it's content upon removing a marking / Static order of elements in a list~~ Current system doesn't have mutch problem with that (mainly because of lack of markings)
~~- [ ] Button to quickly match marking colour with a body one / Default marking colour to the body one~~ done by default
~~- [ ] Double click adds and removes applied markings / Draging Marking elements should add, remove and change order of them~~ Not a problem anymore with applied body markings split into their own categories
- [x] Change points system to compatibility denial system / Block specific marking combinations to ensure no visual problems
- [ ] #7950 
- [ ] Toggle for tail to turn to the other side (Reptilian specific, maybe also others when new species will also have a dragged tail
- [ ] Add temporary removal of clothes when editing markings

All propositions are up for discussion, addition and removal; This is just a collection of my complaints on the ease of use front.

**Comment by Froozigiusz** [comment]
Added
> Add temporary removal of clothes when editing markings

**Comment by mirrorcult** [comment]
clothing toggle is done rest is not actionable or also done (or separate issue)
