### ISSUE TITLE
Unique name IDs broke somehow

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#7968]
## Description
round 9583 on lizard

SOS

**Screenshots**
![image](https://user-images.githubusercontent.com/19853115/167075108-236bf7a4-bf7e-43cf-b88a-a7201399483a.png)

**Additional context**

**Comment by mirrorcult** [comment]
cant repro locally by doing basic testing so maybe this is map specific?

**Comment by mirrorcult** [comment]
but its happened 2 rounds in a row on live, and no exceptions on grafana

**Comment by Veritius** [comment]
did this just magically fix itself or

**Comment by mirrorcult** [comment]
no fucking idea

**Comment by mirrorcult** [comment]
not replicated since. no fucking idea what happened
