### ISSUE TITLE
AHelp and verb "teleport to" functionality should use following

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#7969]
## Description

If you're following someone and tp to someone else it breaks since you're still parented to the other person. IMO  the ahelp button should just use following instead like what ghost roles do

The verbs should also use following (at least TP to should obv)

The actual command is in engine so can't change that, but the content stuff can be changed to just use something else

**Screenshots**
these

![image](https://user-images.githubusercontent.com/19853115/167076687-4fea5c94-4b1d-4791-9879-41a2c7ac105f.png)

![image](https://user-images.githubusercontent.com/19853115/167076708-51724ee1-6081-4085-9538-08e291c66b89.png)

**Additional context**

**Comment by ShadowCommander** [comment]
Replace with Follow command and it'll work better.
