### ISSUE TITLE
Forker's MegaIssue [Daemon/Rane]

### ISSUE THREAD

**Issue by Elijahrane** [space-wizards/space-station-14#7979]
# Forker's Megaissue
These are the issues Daemon and I encountered during our recent launch of our fork, Nyanotrasen.

## Setup
1. There's a lack of in depth documentation on some programs like SS14.Changelog and SS14.Admin and others required to start a server, particularly one on a custom fork. Things have to be solved through asking people in DM's or the discord's Host channels.
2. There's no "Dummy's guide to making and hosting a fork".
3. There is no publicly documented way to generate manifest files for the CDN and SS14.Watchdog.
4. Only two public Grafana panels are available in the documentation.
5. Theres no documentation on redbot or how to use wizard-cogs.
6. There isn't a good way to get help for hosting besides asking in DMs or the host chat, a public hosting help channel in the discord would help with this.
7. There isnt a unified list of cvars or config options for hosting programs.
 
## Content-Space Code
1. The title of the rules.txt window is located in a .ftl file, and defaults to "Official SS14 server rules". It's not immediately obvious to look at localization files for that on an English server.
2. There's no good way to mix changelogs from upstream and the fork itself.
3. People complain about having to make new characters.  I understand this, but storing characters locally and trying to autoupload them to new servers would help. Sometimes people will join and keep reconnecting and disconnecting. If I ask them why, they say they are going back and forth trying to port their character from another server. This doesn't have to port everthing, but just a basic attempt to do stuff like name and species would be nice. Maybe this can be a cvar for how much it can attempt to port using a common standard.
 

## Launcher/Server Browser
1. The launcher showing favorites by default means that once players have favorited a server, they are unlikely to ever view the server browser again. This is the only game I've ever seen that behaves that way, and it's unhealthy.
2. The server browser does not show ping, round time, or other information that can help people make a decision.
3. The server browser does not show what "game" the server is running, something critical to any platform for custom games.

## Social
1. Wizard's Den branding is pretty inconsistent, making it unclear to anyone not hyper active that it's one branch of the game Space Station 14 and not the only thing available in the RobustToolbox launcher.

**Comment by mirrorcult** [comment]
not very actionable + needs separate issues + some already exists
