### ISSUE TITLE
Eris Paletted Sprite Removal Mega Issue(tm)

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#7984]
Goal: resprite all of these.

- [x] Disposals
  - [x] [disposals.rsi](https://github.com/space-wizards/space-station-14/tree/master/Resources/Textures/Structures/Piping/disposal.rsi)
  - [x] [high_pressure_machine_frame.rsi](https://github.com/space-wizards/space-station-14/tree/master/Resources/Textures/Structures/Piping/high_pressure_machine_frame.rsi)
- [ ] Chemistry
  - [ ] [beaker_bluespace.rsi](https://github.com/space-wizards/space-station-14/tree/ece403ca57b2c7616b6558a64c3e9bcbdb5793f5/Resources/Textures/Objects/Specific/Chemistry/beaker_bluespace.rsi)
      Also needs an emissive layer, currently has glow-y bits that don't actually glow.
- [ ] Weapons
  - [ ] Secondary option: Completely tear out our existing gun selection and redesign it.
  - [ ] [pickaxe.rsi](https://github.com/space-wizards/space-station-14/tree/ece403ca57b2c7616b6558a64c3e9bcbdb5793f5/Resources/Textures/Objects/Weapons/Melee/pickaxe.rsi)
  - [ ] [mateba.rsi](https://github.com/space-wizards/space-station-14/tree/ece403ca57b2c7616b6558a64c3e9bcbdb5793f5/Resources/Textures/Objects/Weapons/Guns/Revolvers/mateba.rsi)
  - [ ] [inspector.rsi](https://github.com/space-wizards/space-station-14/tree/ece403ca57b2c7616b6558a64c3e9bcbdb5793f5/Resources/Textures/Objects/Weapons/Guns/Revolvers/inspector.rsi)
  - [ ] [combat_knife.rsi](https://github.com/space-wizards/space-station-14/tree/cc896568c5746734fa83ac213fdb29e52603888a/Resources/Textures/Objects/Weapons/Melee/combat_knife.rsi)
  - [ ] [pirate_revolver.rsi](https://github.com/space-wizards/space-station-14/tree/e6f2239afeee72d3dba3b97145f8024683009d71/Resources/Textures/Objects/Weapons/Guns/Revolvers/pirate_revolver.rsi)
  - [ ] [pump.rsi](https://github.com/space-wizards/space-station-14/tree/ece403ca57b2c7616b6558a64c3e9bcbdb5793f5/Resources/Textures/Objects/Weapons/Guns/Shotguns/pump.rsi)
  - [ ] [gladstone.rsi](https://github.com/space-wizards/space-station-14/tree/ece403ca57b2c7616b6558a64c3e9bcbdb5793f5/Resources/Textures/Objects/Weapons/Guns/Shotguns/gladstone.rsi)
  - [ ] [predator.rsi](https://github.com/space-wizards/space-station-14/tree/e5bf2192cf6ae2c534450d382c91612d2635b014/Resources/Textures/Objects/Weapons/Guns/Revolvers/predator.rsi)
  - [ ] [dallas.rsi](https://github.com/space-wizards/space-station-14/tree/ece403ca57b2c7616b6558a64c3e9bcbdb5793f5/Resources/Textures/Objects/Weapons/Guns/Rifles/dallas.rsi)
  - [ ] [olivaw_civil.rsi](https://github.com/space-wizards/space-station-14/tree/ece403ca57b2c7616b6558a64c3e9bcbdb5793f5/Resources/Textures/Objects/Weapons/Guns/Pistols/olivaw_civil.rsi)
  - [ ] [flintlock.rsi](https://github.com/space-wizards/space-station-14/tree/e6f2239afeee72d3dba3b97145f8024683009d71/Resources/Textures/Objects/Weapons/Guns/Snipers/flintlock.rsi)
  - [ ] [musket.rsi](https://github.com/space-wizards/space-station-14/tree/e6f2239afeee72d3dba3b97145f8024683009d71/Resources/Textures/Objects/Weapons/Guns/Snipers/musket.rsi)
  - [ ] [flaregun.rsi](https://github.com/space-wizards/space-station-14/blob/e6f2239afeee72d3dba3b97145f8024683009d71/Resources/Textures/Objects/Weapons/Guns/Shotguns/flaregun.rsi/)
  - [x] [hm_pistol.rsi](https://github.com/space-wizards/space-station-14/tree/ece403ca57b2c7616b6558a64c3e9bcbdb5793f5/Resources/Textures/Objects/Weapons/Guns/Pistols/hm_pistol.rsi)
  - [x] [sawn.rsi](https://github.com/space-wizards/space-station-14/blob/ece403ca57b2c7616b6558a64c3e9bcbdb5793f5/Resources/Textures/Objects/Weapons/Guns/Shotguns/sawn.rsi/)
  - [x] [heavy_sniper.rsi](https://github.com/space-wizards/space-station-14/blob/ece403ca57b2c7616b6558a64c3e9bcbdb5793f5/Resources/Textures/Objects/Weapons/Guns/Snipers/heavy_sniper.rsi/)
  - [x] [china_lake.rsi](https://github.com/space-wizards/space-station-14/blob/ece403ca57b2c7616b6558a64c3e9bcbdb5793f5/Resources/Textures/Objects/Weapons/Guns/Launchers/china_lake.rsi/)
  - [x] [colt.rsi](https://github.com/space-wizards/space-station-14/blob/ece403ca57b2c7616b6558a64c3e9bcbdb5793f5/Resources/Textures/Objects/Weapons/Guns/Pistols/colt.rsi/)
  - [x] [bolt_gun_wood.rsi](https://github.com/space-wizards/space-station-14/blob/ece403ca57b2c7616b6558a64c3e9bcbdb5793f5/Resources/Textures/Objects/Weapons/Guns/Snipers/bolt_gun_wood.rsi)
  - [x] [bolt_gun.rsi](https://github.com/space-wizards/space-station-14/blob/ece403ca57b2c7616b6558a64c3e9bcbdb5793f5/Resources/Textures/Objects/Weapons/Guns/Snipers/bolt_gun.rsi/)
  - [x] [mk58.rsi](https://github.com/space-wizards/space-station-14/blob/ece403ca57b2c7616b6558a64c3e9bcbdb5793f5/Resources/Textures/Objects/Weapons/Guns/Pistols/mk58.rsi/)
  - [x] [mk58_wood.rsi](https://github.com/space-wizards/space-station-14/blob/ece403ca57b2c7616b6558a64c3e9bcbdb5793f5/Resources/Textures/Objects/Weapons/Guns/Pistols/mk58_wood.rsi/)
  - [x] [db_shotgun.rsi](https://github.com/space-wizards/space-station-14/blob/ece403ca57b2c7616b6558a64c3e9bcbdb5793f5/Resources/Textures/Objects/Weapons/Guns/Shotguns/db_shotgun.rsi/)
  - [x] [lamia.rsi](https://github.com/space-wizards/space-station-14/blob/cc896568c5746734fa83ac213fdb29e52603888a/Resources/Textures/Objects/Weapons/Guns/Pistols/lamia.rsi/)
- [ ] Ammo
  - [ ] [caps.rsi](https://github.com/space-wizards/space-station-14/tree/ece403ca57b2c7616b6558a64c3e9bcbdb5793f5/Resources/Textures/Objects/Fun/caps.rsi)
  - [ ] [cl_rifle_short.rsi](https://github.com/space-wizards/space-station-14/tree/818bdb3c63b30afa1a884dd03fcca102b298d6cd/Resources/Textures/Objects/Weapons/Guns/Ammunition/Magazine/ClRifle/ClRifle-NEW/cl_rifle_short.rsi)
  - [ ] [cl_rifle.rsi](https://github.com/space-wizards/space-station-14/tree/818bdb3c63b30afa1a884dd03fcca102b298d6cd/Resources/Textures/Objects/Weapons/Guns/Ammunition/Magazine/ClRifle/ClRifle-NEW/cl_rifle.rsi)
  - [ ] [cl_pistol.rsi](https://github.com/space-wizards/space-station-14/tree/818bdb3c63b30afa1a884dd03fcca102b298d6cd/Resources/Textures/Objects/Weapons/Guns/Ammunition/Magazine/ClRifle/ClRifle-NEW/cl_pistol.rsi)
  - [ ] [10x24.rsi](https://github.com/space-wizards/space-station-14/blob/818bdb3c63b30afa1a884dd03fcca102b298d6cd/Resources/Textures/Objects/Weapons/Guns/Ammunition/Magazine/ClRifle/ClRifle-NEW/10x24.rsi/meta.json)
- [ ] Clothing
  - [ ] [cosmonaut.rsi](https://github.com/space-wizards/space-station-14/tree/818bdb3c63b30afa1a884dd03fcca102b298d6cd/Resources/Textures/Clothing/Head/Helmets/cosmonaut.rsi)
  - [ ] [ihscombat.rsi](https://github.com/space-wizards/space-station-14/tree/818bdb3c63b30afa1a884dd03fcca102b298d6cd/Resources/Textures/Clothing/Hands/Gloves/ihscombat.rsi)
  - [ ] [bombsuit.rsi helmet](https://github.com/space-wizards/space-station-14/tree/818bdb3c63b30afa1a884dd03fcca102b298d6cd/Resources/Textures/Clothing/Head/Helmets/bombsuit.rsi)
  - [ ] [bombsuit.rsi suit](https://github.com/space-wizards/space-station-14/tree/818bdb3c63b30afa1a884dd03fcca102b298d6cd/Resources/Textures/Clothing/OuterClothing/Suits/bombsuit.rsi)
  - [ ] [scaf.rsi helmet](https://github.com/space-wizards/space-station-14/tree/818bdb3c63b30afa1a884dd03fcca102b298d6cd/Resources/Textures/Clothing/Head/Helmets/scaf.rsi)
  - [ ] [scaf.rsi suit](https://github.com/space-wizards/space-station-14/tree/818bdb3c63b30afa1a884dd03fcca102b298d6cd/Resources/Textures/Clothing/OuterClothing/Armor/scaf.rsi)
  - [ ] [hoshat.rsi](https://github.com/space-wizards/space-station-14/tree/818bdb3c63b30afa1a884dd03fcca102b298d6cd/Resources/Textures/Clothing/Head/Hats/hoshat.rsi)
  - [ ] [riot.rss](https://github.com/space-wizards/space-station-14/tree/818bdb3c63b30afa1a884dd03fcca102b298d6cd/Resources/Textures/Clothing/OuterClothing/Armor/riot.rsi)
  - [ ] [armor_reflec.rsi](https://github.com/space-wizards/space-station-14/tree/818bdb3c63b30afa1a884dd03fcca102b298d6cd/Resources/Textures/Clothing/OuterClothing/Armor/armor_reflec.rsi)
  - [ ] [bulletproof.rsi](https://github.com/space-wizards/space-station-14/tree/818bdb3c63b30afa1a884dd03fcca102b298d6cd/Resources/Textures/Clothing/OuterClothing/Armor/bulletproof.rsi)
  - [ ] [ihsvoid.rsi helmet](https://github.com/space-wizards/space-station-14/tree/818bdb3c63b30afa1a884dd03fcca102b298d6cd/Resources/Textures/Clothing/Head/Hardsuits/ihsvoid.rsi)
  - [ ] [ihsvoid.rsi suit](https://github.com/space-wizards/space-station-14/tree/818bdb3c63b30afa1a884dd03fcca102b298d6cd/Resources/Textures/Clothing/OuterClothing/Hardsuits/ihsvoid.rsi)
- [ ] Structures
  - [ ] [inflatable_wall.rsi](https://github.com/space-wizards/space-station-14/tree/ece403ca57b2c7616b6558a64c3e9bcbdb5793f5/Resources/Textures/Objects/Misc/inflatable_wall.rsi)
  - [ ] [bookshelf.rsi](https://github.com/space-wizards/space-station-14/tree/e34888373a9436af3f09672c2d92757721b5a94c/Resources/Textures/Structures/Furniture/bookshelf.rsi)
  - [ ] [substation.rsi](https://github.com/space-wizards/space-station-14/blob/5ad6f99de8acaf15530f2309a9b4c64c7f39c759/Resources/Textures/Structures/Power/substation.rsi/meta.json)

**Comment by Emisse** [comment]
is this because of that legal mumbo jumbo from the other day

**Comment by moonheart08** [comment]
No. It's because Eris sprites look bad mixed with non-Eris sprites.

**Comment by triplezeta** [comment]
spriter sees amongbus task list
neuron activation

**Comment by juliangiebel** [comment]
Removal of the disposal unit allready came up once and we decided to keep it in. Why remove it now? Have you seen how ugly the tg disposal unit is?.
The high pressure machine frame is a custom sprite I made!
Also I think that most of the sprites mentioned don't look bad with non-eris sprites (except for the weapons)

**Comment by Emisse** [comment]
i think our disposals look good

**Comment by ZeroDayDaemon** [comment]
Continuation of https://github.com/space-wizards/space-station-14/issues/7821

**Comment by Peptide90** [comment]
> Removal of the disposal unit allready came up once and we decided to keep it in. Why remove it now? Have you seen how ugly the tg disposal unit is?.
> 
> The high pressure machine frame is a custom sprite I made!
> 
> Also I think that most of the sprites mentioned don't look bad with non-eris sprites (except for the weapons)

Agree, I think this is a non issue. There are some sprites that are out of place but there is an issue for that. It was primarily structured like walls and objects like weapons. Eris has some cool sprites we don't use too and I think we should strive to add a TG style of them (things like decals for shuttle walls).

**Comment by moonheart08** [comment]
> Removal of the disposal unit allready came up once and we decided to keep it in. Why remove it now? Have you seen how ugly the tg disposal unit is?. The high pressure machine frame is a custom sprite I made! Also I think that most of the sprites mentioned don't look bad with non-eris sprites (except for the weapons)

I have, which is why this is an issue about **respriting.**

**Comment by EmoGarbage404** [comment]
Eris's hue-shifted palette lives in a lot of things. For future reference of spriters, should art stay neutral in hue for the most part, or should it have the general tints and color of the eris sprites?

**Comment by moonheart08** [comment]
> Eris's hue-shifted palette lives in a lot of things. For future reference of spriters, should art stay neutral in hue for the most part, or should it have the general tints and color of the eris sprites?

The hue-shifted palette needs to go, it does not fit with the majority of our assets.

**Comment by ZeroDayDaemon** [comment]
going to do some work on this

**Comment by ZeroDayDaemon** [comment]
> going to do some work on this

this was a lie

**Comment by UbaserB** [comment]
this is so useful thank you now i know what i can resprite

**Comment by Emisse** [comment]
superceded by #19739
