### ISSUE TITLE
Labcoats have suit storage

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#8028]
## Description

**Screenshots**

**Additional context**

**Comment by mirrorcult** [comment]
or basically any over-jumpsuit clothing

**Comment by Peptide90** [comment]
Iirc they did on 13? Like a coat pocket. But yes we need to make sure it can’t hold a gas tank.

**Comment by Emisse** [comment]
id like to restrict large tank storage to hardsuits and softsuits but not sure where thats specified to whitelist them

**Comment by mirrorcult** [comment]
this is a much bigger issue with #9330 merged

**Comment by Peptide90** [comment]
To add context, suit storage is aka exosuit slot is hard coded which is bad. The clothing should add the slot and have its constraints defined with the storage component like everything else - that way you can use blacklists or storage limits.

**Comment by ShadowCommander** [comment]
SS13 had two different storages for clothing. Some had suit storage which unlocked the large item slot (this is what hard suits have). And some were containers with one or two slots that fit small items (like labcoats. In CM helmets were also containers for smokes and nutrient bars.).
