### ISSUE TITLE
Pulling is broken on master currently

### ISSUE THREAD

**Issue by Emisse** [space-wizards/space-station-14#8037]
when you pull an entity, if you stop moving the entity will return to its previous position. this does not happen with mobs.

**Comment by Emisse** [comment]
it seems that you can only pull entities client side and server side it doesnt recognize you as pulling them at all

**Comment by HoofedEar** [comment]
I tried recreating this on local, and I feel like this is somehow related to that map pausing thing that was recently fixed, because based on your description and [#8039], the thing being dragged is acting the same way players do when (either the map, grid, player, idk) is still paused

**Comment by metalgearsloth** [comment]
Can't replicate
