### ISSUE TITLE
Dragging has become weird

### ISSUE THREAD

**Issue by Kromabae** [space-wizards/space-station-14#8039]
## Description
Map Delta
only odd things prior i can think of happening before this started was a restart vote happend in the lobby screen
most lockers and other machinery cannot be moved after this bugg happend

**Screenshots**

https://user-images.githubusercontent.com/97402700/167317523-e3acdfea-2d46-42df-9f48-e5929e370df9.mp4

tried to attempt recreate it all i got was this, item keeps teleporting back to the it OG spot

**Comment by Emisse** [comment]
happens with all entities except npc mobs
