### ISSUE TITLE
Rework attackcode

### ISSUE THREAD

**Issue by PrPleGoo** [space-wizards/space-station-14#804]
Current situation:
You go into attackmode and hold down the attack button to swing.
Swing has the same cooldown as attacking.

Desired situation:
You push a button on your keyboard to swing.
Swing has a longer cooldown than attacking.

Suggestion:
Make it the spacebar, everyone thumb should be on that.

**Comment by Zumorica** [comment]
Fixed by e2677bab51e702ca26aa7c46b2db1ff0546c3727
