### ISSUE TITLE
Bruise packs are once again OP (ointment too)

### ISSUE THREAD

**Issue by Kromabae** [space-wizards/space-station-14#8053]
## Description
bruise packs and ointments (probably all other similar things) no longer interupts whne used again so you can spam using it without autoclicking
Intended?
**Screenshots**

https://user-images.githubusercontent.com/97402700/167459253-802ce17c-b2c9-4147-9bcb-acff3dd56efd.mp4

**Additional context**

**Comment by metalgearsloth** [comment]
> Same thing is happening for drinks and I think food too

Are you sure because they haven't been touched in a while. At any rate the others are fixed on master.
