### ISSUE TITLE
Many tiles are missing their item equivalent.

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#812]
Many floors, such as the techmaint floor in engineering, are missing their correct item drop. This causes the wrong floor item to drop when crowbarring them.

**Comment by PJB3005** [comment]
Could maybe do with something like a tile painter for some of them.

**Comment by FL-OZ** [comment]
Steel floor is a fallback. I believe at the time I added this there weren't a lot of floor item sprites. I'll  take a look at this though.

**Comment by FL-OZ** [comment]
closed by #1055
