### ISSUE TITLE
Airlocks should not create a vacuum on their tile when closed

### ISSUE THREAD

**Issue by Emisse** [space-wizards/space-station-14#8135]
It should probably trap gas inside it or set the tile to default air mix because things passing under doors get crushed by pressure (not the door shutting damage) and suffocate. It also makes things like holofan projectors downstream absolute cbt. I feel like this will become more of an issue later on than it is now but I think future proofing it is a good idea. Making this an issue at request of vera.

**Comment by Zumorica** [comment]
As a related note: Firelocks should still create a vacuum, given they could trap plasma or a fire in their tile otherwise.

**Comment by Froozigiusz** [comment]
Cavuumed doors are a real choking hazard for the chaplains bat, saying that from the first hand perspective
