### ISSUE TITLE
Gravity

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#814]
This should be handled on a grid-per-grid basis. Grids can have a machine that generates gravity when powered up. Ideally, some grids (such as those of small shuttles) shouldn't require a gravity generator to have gravity. 
Related #705

**Comment by InquisitivePenguin** [comment]
What if a single gravity generator could supply gravity to all grids on the same Z-level? That way, shuttles on the same Z-level as the main station would have gravity but leaving that Z-level would cause everything to become weightless.

**Comment by PJB3005** [comment]
Might be more convenient to give shuttles miniature gravity generators so they don't lose gravity if you leave the map.

**Comment by InquisitivePenguin** [comment]
I can work on this: I'll probably use the gravity generator sprite from /tg/ for now.
