### ISSUE TITLE
Microwave code is horrific

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#8143]
## Description

Ideally needs full rewrite with a better idea in mind of what niche microwaves occupy for the cooking rework (see design docs on `docs.ss14.io`)

**Screenshots**

**Additional context**

**Comment by Ephememory** [comment]
So that makes two of my major contributions being marked as "horrific code". Woot!

**Comment by ike709** [comment]
> Sorry for trying, I'll stop contributing from now on.

Since you're going to be sassy instead of accepting that most people just get better at contributing over time (with effort)...

> Only 10 merged PRs in almost 2 years
> Only 1 PR merged in the last 6 months
> Even that 1 PR was 3 months ago

I think SS14 will live.

**Comment by Ephememory** [comment]
I think it needs a refactor and _is_ old, sure, but throwing ad-hominem around and calling my code "horrific" (especially when no one put in any effort to answer my calls for help and guide me down a better path whilst I was writing it BTW.), is uncalled for. 

I had more PRs on a now deleted GH account as well. Finally, I never implied SS14 *won't* live without me, there's no need to be so ugly and snide to people trying to help you on a volunteer project. The "holier-than-thou" and smug attitude from the top rung of contributors/maintainers doesn't seem like the best way to attract new contributors, in my opinion. 

You will be just fine without me and, being realistic, **better off** without me! This was already a needless comment on my part and I'll be ending this spurt of drama _and_ my interaction with this codebase right here.

**Comment by metalgearsloth** [comment]
Arguing on github.

**Comment by jamessimo** [comment]
There was a UI update I designed. 
![Slice 1](https://github.com/space-wizards/space-station-14/assets/4888377/42b4fd16-057a-49dd-890a-9ba0f1cd4061)

I wanted to implement it myself but the code is so rough that I couldn't make any headway. I did get the UI looking close to whats in my design however.

**Comment by mirrorcult** [comment]
its good enough now
