### ISSUE TITLE
Tedium, Tedium, Tedium

### ISSUE THREAD

**Issue by youarereadingthis** [space-wizards/space-station-14#8155]
Because this may matter to some: I currently have nearly 250 hours played of SS14 according to Steam.
My BYOND account is at least 8 years old, but it's stuck in frozen hell from inactivity with no sign from support.

## Forcing Social Interactions ##

**- The SS14 team wants its successor to be much more socially engaging.**
This in itself is a great idea. Players are such wildcards. They can make things infinitely interesting if given the right mechanics and motivations. They are at the core of all my favorite memories of SS13/14. The simulation mechanics are cool but not exactly enough on their own to play for a thousand hours and still want more.

**- The way they want to accomplish this is forcing you to interact with others to accomplish your job.**
Okay. It is a multiplayer game after all. Learning(and sometimes mastering) the mechanics in SS13 did not always lead to outside interactions. This isn't the biggest issue really if the player is having fun, but not all of the mechanics are particularly interesting enough to support the singleplayer experience and certainly have the _potential_ to be spiced up by forcing social interaction. So why not?

However..

**- The way you're forced to interact with others right now is (and I'm sorry to say this) mostly very boring.**
Here is an outline of a story I've experienced far too many times in SS14.
1. You either want or need to do TASK.
Might be as simple as not starving. Might be as ambitious as building a shuttle.
2. You have not enough RESOURCE(S) to accomplish TASK and must leave your space to get it.
This basically means y
4. You must walk to the department(s) to ask nicely for the RESOURCE(S).
This opens
5. You

**Comment by youarereadingthis** [comment]
I accidentally posted this too early.
It's not ready. Please remove it.

**Comment by metalgearsloth** [comment]
github's not really the right place for this.
