### ISSUE TITLE
Implement General Mobs

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#816]
With utility AI around the corner, someone needs to put some general mobs in the game. 

Like Spacecarp, Ian, Monkey, etc.

**Comment by SweptWasTaken** [comment]
I can do that!

**Comment by SweptWasTaken** [comment]
Oh ok, thanks Swept!

**Comment by PJB3005** [comment]
Why did I give you triage permission...

**Comment by SweptWasTaken** [comment]
Fixed by me #1502
