### ISSUE TITLE
Space is still far too deadly

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#8172]
## Description

You die in like 10 seconds or less generally when something gets spaced. With how easy it is to space areas and with the movement debuff damage brings it needs to be significantly less deadly

**Screenshots**

**Additional context**

**Comment by juliangiebel** [comment]
Did you use the space medipen?

**Comment by mirrorcult** [comment]
it often kills you so fast that you barely have time to even use it

**Comment by Peptide90** [comment]
I buffed it awhile back so pressure is like 30-45 seconds to dead. Is that not the case anymore?

**Comment by metalgearsloth** [comment]
I think it should be at least 60 seconds to kill you tbh.

**Comment by juliangiebel** [comment]
Look at my PR for space medipens: #7880.
It is not pressure damage that kills you in 12 seconds it is temperature damage. Even if you remove pressure damage, temperature will still kill you in 12 seconds. For Lizards it's even faster.

**Comment by keronshb** [comment]
Is this more looking at the values on how space damages you (not sure where to look for that) or is it more like an atmos change with how explosive atmos works?

**Comment by keronshb** [comment]
Nevermind looks like someone else has it
