### ISSUE TITLE
Asteroid rocks give way too many ores / ores redeem for way too many materials

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#8184]
## Description

You can get absolutely loaded with everything with basically one salvaged asteroid. Every single roid gives some kind of ore when hit (iirc this is a bug with entity spawn collections, they cant pick nothing?)

**Screenshots**

**Additional context**

**Comment by EmoGarbage404** [comment]
This isn't the place to post people malding. If its a problem open an issue.
