### ISSUE TITLE
Flying mobs can go through doors

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#8199]
ezfix.

**Comment by ShadowCommander** [comment]
Just a change to the FlyingMobMask. Wasn't sure whether to make them go through doors or not, so went with going through doors.

**Comment by Rinzii** [comment]
Can I have this assigned to me?

**Comment by Rinzii** [comment]
This should be solved once my PR is accepted. See #8236

**Comment by ike709** [comment]
Needs to be closed @metalgearsloth
