### ISSUE TITLE
Some chairs should be able to be picked up

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#8206]
I want my immersive rage cage experience.

**Comment by Emisse** [comment]
just add folding chairs that can be used as weapons

**Comment by efzapa** [comment]
at this rate just add dedicated wrestling rings to the maps

**Comment by Rinzii** [comment]
I support the increase of the power of wrestle mania. So @metalgearsloth would you kindly assign me to this issue ^^
