### ISSUE TITLE
Ghost issues

### ISSUE THREAD

**Issue by AJCM-git** [space-wizards/space-station-14#822]
- Sometimes you cant see other ghosts as a ghost
- Ghosting requires admin permissions
- You can see ghost bubble speech as a human

**Comment by partyaddict** [comment]
Trying to aghost after respawning doesn't work (i think)

**Comment by Zumorica** [comment]
Also: joining as observer doesn't set the correct name

**Comment by Zumorica** [comment]
> * Ghosting requires admin permissions

Just a small correction: Aghosting (`aghost` command) requires admin permissions. Regular ghosting (`ghost` command) doesn't require admin permissions
