### ISSUE TITLE
No way to stop bad admin music

### ISSUE THREAD

**Issue by ike709** [space-wizards/space-station-14#8230]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH

**Comment by metalgearsloth** [comment]
working as intended

**Comment by metalgearsloth** [comment]
survey says so

**Comment by 20kdc** [comment]
For context to other people here, metalgearsloth is the one who force-plays a lot of music.

**Comment by PaulRitter** [comment]
grudgecode inbound

**Comment by Emisse** [comment]
i think a volume slider for announcements, round start and round end audio, and admin sounds would be appreciated

**Comment by AugustEymann** [comment]
i see no issue

**Comment by wrexbe** [comment]
Regardless of anything else here, being able to trust the game will be muted is important, it could really ruin someones day. Other then that, if we did have someone recording the game, and they wanted to upload it, or stream, they would probably get really upset if a copyrighted song started playing.

**Comment by OldDanceJacket** [comment]
Memes aside this is an actual issue in a number of ways; If I want the game muted, I want the game muted.

**Comment by PaulRitter** [comment]
ss13 just has a "disable/enable admin music" toggle

**Comment by ike709** [comment]
Bad music tyranny will soon be at an end.

**Comment by youarereadingthis** [comment]
I had to disable the startup menu song as well because none of the volume sliders affected it.
I don't necessary want to mute things like this but I wish they weren't so fucking loud in general.
