### ISSUE TITLE
help autocomplete crashes

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#8250]
Already pinged pjb on it but in case anyone else asks.

**Comment by ElectroJr** [comment]
Seems to be fixed? Or was there more to reproducing it than just looking at help completions?

**Comment by Peptide90** [comment]
> Seems to be fixed? Or was there more to reproducing it than just looking at help completions?

Yeah going to close this, I recall it happening on master but was fixed on the master after. Someone can reopen if still an issue.
