### ISSUE TITLE
Nukies issue

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#8252]
## Description

The shuttle and the mobs spawned, but it didn't grabbed the players, we had to ghost role them.
The shuttle needs to be changed to infiltrator
The shuttle spawned too far away to be picked up by mass scanner
Nukies need their own access ID and doors
**Reproduction**

**Screenshots**

**Additional context**

**Comment by metalgearsloth** [comment]
Nuke detection needs to be more robust i.e. right now it only checks for detonation. Should check if it's detonated within the area of the correct station.

Also needs minor / major victory I think.

**Comment by Emisse** [comment]
could we make it an antag opt in role so it can grab players like it normally does for round start syndies

**Comment by youarereadingthis** [comment]
> Also needs minor / major victory I think.

I would also like to see the old humiliating defeats such as when it's detonated on a Syndicate base(just the shuttle for now).

**Comment by Emisse** [comment]
shuttle does get spawned pretty far but it might be helpful for a syndi shuttle console with a 512x512 range instead of 256

**Comment by Peptide90** [comment]
- Syndie shuttle now has 500 range I'm sure.
- Nukies are opt in.
- Seems to work but idk about access
