### ISSUE TITLE
Battery cells are bloated

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#8279]
Someone decided to port eris cells but they're bloated and most aren't used:
There's
- small
- medium
- large

Then for each type:
- Hyper
- High-capacity
- High
- Super

What is the ordering of these capacities?

It's unnecessary bloat and unless someone opts to actually maintain it this time round we just need to cull them. They should just be a standard size that's obvious which stores more power.

**Comment by Emisse** [comment]
we could make each size have a normal and large size and reduce the bloat by half

**Comment by metalgearsloth** [comment]
What takes advantage of sizes atm?

**Comment by Emisse** [comment]
laser guns are the main thing that comes to mind

**Comment by metalgearsloth** [comment]
Laser gun balancing is non-existent atm so I'd rather just standardise sizes as it will make balancing significantly easier.

**Comment by Emisse** [comment]
just dont cull the potato battery, microreactor, antique prototype, or hardsuit helmet

**Comment by Emisse** [comment]
only things i think that would be effected by an ID change or culling of sized batteries would be the hardhats with lights

**Comment by youarereadingthis** [comment]
I think that there should still be at least one higher capacity battery since it's fun to upgrade, but honestly the "flashlights are just free lasergun battery upgrades" meta is just weird and there's not even a way to craft/research the upper capacity ones AFAIK.

**Comment by juliangiebel** [comment]
> What takes advantage of sizes atm?
Ideally there should be a small and large size. Small for handheld things and large for battery powered machines. The self recharging ones shouldn't be capable of providing enough energy for things more powerfull than a flashlight tbh.

**Comment by juliangiebel** [comment]
We could consolidate small and medium ones by having low capacity and recarging cells be "small" i.e, they provide a low amount of energy.

**Comment by Peptide90** [comment]
> > What takes advantage of sizes atm?
> 
> Ideally there should be a small and large size. Small for handheld things and large for battery powered machines. The self recharging ones shouldn't be capable of providing enough energy for things more powerfull than a flashlight tbh.

The hardsuit one I made because it was the only way to make hardsuit lights drain slowly and regen and should not be used for anything else because OP. That’s why it can’t be ejected.

Personally I don’t see an issue with 3 cell sizes as it means small can be used for accessories like flashlights, medium for weapons and large for machines and borgs etc. keeping them separate makes balancing their actual power capacity easier as it means you aren’t worrying about people putting them in guns. 

High > super > hyper. Agreed super is a lil sus but eh.

**Comment by Peptide90** [comment]
As discussed in discord - energy guns will be recharger only so it makes little sense to have cell sizes. 

At a maximum have small and large, small being small capacity for handheld stuff and large being for borgs and machines etc.

**Comment by metalgearsloth** [comment]
Sizes seem needless, additionally helmet / hardsuits / anything with a non-ejectable powercell needs to be changed to just have battery on the item itself.
