### ISSUE TITLE
Pronoun handling

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#828]
We need a way to handle pronouns in a similar way to how [BYOND text macros](http://www.byond.com/docs/ref/index.html#/DM/text/macros) work.

**Comment by Hugal31** [comment]
Any idea on how Byond is doing this, and how we should do it? Do they use a NLP library, or just search for the previous / next "argument" word?

**Comment by DamianX** [comment]
It does look for the nearest arguments and it's terrible. TG ended up having to come up with [helpers to work around it](https://github.com/tgstation/tgstation/blob/master/code/__HELPERS/pronouns.dm).
