### ISSUE TITLE
Cargotelepad should not collide when anchored

### ISSUE THREAD

**Issue by abregado** [space-wizards/space-station-14#8284]
## Description
The cargo telepad has its canCollide property set true. It seems on most maps this is manually set to false. Ive tried changing its PhysicsComponent in its prototype but it seems that when transforms receive the anchoring event they automatically set canCollide to true without respect for the original protoypes setting.

Not sure how to change this myself. Happy to fix it "myself" if I can get some guidance.

**Reproduction**
Unanchor and reanchor a cargo telepad on any map, then order a crate. 

**Additional context**
I'm not sure what effect this will have on other objects. I guess the PhysicsComponent will need canCollide to be set by default to true.

**Comment by metalgearsloth** [comment]
there's a component for this that just needs adding for whoever fixes it, collideonanchoredcomponent iirc.

**Comment by abregado** [comment]
ok, that is really simple. Ive made a pull request for the fix.

**Comment by HoofedEar** [comment]
Fixed, closing now
