### ISSUE TITLE
If you start eating food on the floor you can run away to finish eating

### ISSUE THREAD

**Issue by jessicamaybe** [space-wizards/space-station-14#8297]
## Description
This bug is very beneficial to mice gameplay, it's the current mouse meta

**Screenshots**

https://user-images.githubusercontent.com/31836813/169421711-331606ca-0a8a-4eb3-b744-2d3acd4279ff.mp4

**Comment by metalgearsloth** [comment]
do_afters probably just need a BreakOnDistance nullable float.
