### ISSUE TITLE
Editing the PDA ringtone crashes client.

### ISSUE THREAD

**Issue by gidgeesheep** [space-wizards/space-station-14#8298]
## Description
The text box in the PDA is causing a problem that's crashing clientside. I've tried understanding what it is. But I'm too inexperienced. Some sort of null exception in the text box.

**Reproduction**
1. Open PDA
2. Select "Ringtone" tab
3. Attempt to edit any textbox

**Comment by ElectroJr** [comment]
> Some sort of null expectation in the text box.

It would be helpful if you posted the actual error as well. Just following those steps doesn't crash my client or cause any errors to get logged.
