### ISSUE TITLE
Computer System.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/space-station-14#83]
After some bikeshedding on Discord, we've had some ideas regarding how computers should work.

No special circuit board computers. Different functions are software based. Most computers either interact with say servers on a network, or tell *other* machines to do things.

**Comment by captkirk88** [comment]
Create a full on kernel with all the nuts and bolts.

Example:
https://github.com/ZaneDubya/YCPU

Maximum effort!

**Comment by outbools** [comment]
linux kernel is open source what are you waiting for

**Comment by acvzy** [comment]
Moved [here](https://hackmd.io/96HHKT-VQ2KO91c9i75V8A?both#PJB-amp-CaptKirk-2018-07-26)
