### ISSUE TITLE
Undeletable entities

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#8305]
## Description

R:10105 on Lizard, a carp was somehow created that could be infinitely butchered. Did some testing and found out it wasn't being gibbed, and it wasn't being gibbed properly because it wasn't being deleted properly. Weird. Tried to delete it with admin tools--this failed as well. Okay. Sure.

Other things of note:
- Exploding it failed
- Removing all components except essential ones and trying to delete it failed
- Checking metadata, not already deleted and not set to terminating lifestage. Entity still also, like, had a metadata component
- No exceptions to be found in grafana
- Round restart was successful, and the entity -was- deleted as it no longer existed during the next round
- Queuedel and regular del both failed to delete it

**Reproduction**

we have no idea. but this happened with salvage carps and im almost positive this has been reported before and has been happening for months, just very rarely. so good luck

**Screenshots**

![image](https://user-images.githubusercontent.com/19853115/169525153-2acb9e9a-e7d1-4bd0-8b68-3ebb1de9d3e3.png)

![image](https://user-images.githubusercontent.com/19853115/169525227-33e1e79a-7ea6-42d0-bbf7-c257c43f0ef9.png)

**Additional context**

??????????

**Comment by Veritius** [comment]
the fish have evolved. they are too powerful now. fear them.

**Comment by Just-a-Unity-Dev** [comment]
all hail fish. they are the new emperor of SS14.

**Comment by metalgearsloth** [comment]
Paul said memory graph has been bloating since May 14th and that's when salvagemobrestriction was merged sooooo
