### ISSUE TITLE
Multitool opens wiring panel prematurely (without using screwdriver to expose panel)

### ISSUE THREAD

**Issue by retequizzle** [space-wizards/space-station-14#8330]
## Description

Pretty straightforward. If you use a multitool on a door/vending-machine while the panel is closed, it bypasses the need for a screwdriver at all and opens the panel. This allows you to use wirecutters on the wires in the panel without the need for ever accessing the panel, and thus bypasses one of the noisiest parts of the breaking into stuff.

**Reproduction**
Detailed above but here:

1. Find a door/vending machine of choice.
2. Use multitool on your desired entity.
3. If entity has a wiring panel, it opens the wiring panel whether the maintenance panel is open or closed.
4. You can now use wirecutters on the panel as if the panel was exposed. Insuls still required to avoid electrocution, applies to both doors and vending machines.
5. Close the wire panel menu when complete, does nothing with breaking the door or the vending machine other than the intended effects depending on wires cut.

**Additional context**

Crossposting this from someone else who reported it in Discord but had no Github access, but did verify the report in-game before posting it here.

**Comment by Just-a-Unity-Dev** [comment]
OH MY DUMBASS THOUGHT THAT WAS INTENTIONAL

(i thought multitool automatically opened the maint panel or something)
