### ISSUE TITLE
Danger Too Close - GL rounds detonate immediately upon firing, usually at the player's feet

### ISSUE THREAD

**Issue by retequizzle** [space-wizards/space-station-14#8334]
## Description

China lake rounds either have no travel velocity and fall out of the barrel armed, or detonate at the person who's wielding the GL's coordinates because of faulty collision check. This started happening within the last few days, unsure if any PRs would have directly impacted this.

**Reproduction**

1. Take a China Lake as a player mob, use either Blast Rounds or Frag Rounds. Blast rounds I have confirmed at least once, unsure on frag rounds but they're probably safer to test this with as well because they do little damage by comparison.
2. Toggle harm, close bolt.
3. Fire in any direction, click anywhere on screen. Will not matter, explosion happens at your feet aka your coordinates.

**Screenshots**

**Additional context**

I advise using player mob first because that's the only way I've seen it happen, unsure if it happens with admin ghost powers but merits investigation to determine if it's a collision issue or a velocity issue for sure.

**Comment by metalgearsloth** [comment]
just add the projectile ID to fixtures should do it I think.

**Comment by EmoGarbage404** [comment]
Fixed in #8467
