### ISSUE TITLE
You can spill closed liquid containers

### ISSUE THREAD

**Issue by jessicamaybe** [space-wizards/space-station-14#8337]
## Description
Right Click -> "Spill Liquid" while container is closed, container should stay closed and not spill or open and spill.

https://user-images.githubusercontent.com/31836813/169670291-62e30e2f-46f6-45ab-aeb5-131895bf6df1.mp4

**Comment by youarereadingthis** [comment]
Unless a liquid container can be locked, I'd prefer the convenience of not having to do so as you can easily interpret it as being implied you open it first.

But it makes sense that there should be an open-first check in case you're blocked from opening it.

**Comment by gidgeesheep** [comment]
Yeah, some containers make sense. Should we get a separate item like a cap to come with openable items? Like a thermos to hold hot liquids and a cup on the side.
