### ISSUE TITLE
Dead bodies can be revived without cloning, can not control body.

### ISSUE THREAD

**Issue by AugustEymann** [space-wizards/space-station-14#8339]
## Description
CMO continued to try and revive me with hypo and im already dead but he can't tell because theirs not dead text, i think if you hit a dead body enough with meds it shows alive.
**Reproduction**
no idea but maybe if you hit a dead body enough with meds it shows alive.
**Screenshots**
![image](https://user-images.githubusercontent.com/29801840/169676044-edc037da-de1c-43e9-ba4b-0eeb7f952a76.png)

**Additional context**

**Comment by AugustEymann** [comment]
![image](https://user-images.githubusercontent.com/29801840/169676075-5108d0a4-b8a7-498e-82db-74df3f813d61.png)
Dead body stands up and can not re enter round because of this bug.

**Comment by AugustEymann** [comment]
disregard i guess if you press return to body you reenter.

**Comment by themias** [comment]
What is the expected/desired behavior in this case?
If a patient is Dead (with or without a ghost observer spawned), should medicine still work on them?
If we allow this, would the ghost be automatically brought back to the body if it is returned to a Critical/Normal state?

**Comment by Kromabae** [comment]
just make beds not able to heal if someone is dead?
the same thing that happend to bruise packs and ointment, cant use used on dead targets
