### ISSUE TITLE
YAML File Cleanup

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#834]
Due to #831 

We are now using `PascalCase` for `ids` in our YAML files and `camelCase` for everything else.

Best way to do this would be writing a quick VIM script to go through all our YAML files....

Or just do it by hand.

**Comment by Zumorica** [comment]
Here are the [guidelines](https://hackmd.io/@ss14/code-quality-control) regarding resource naming.

**Comment by SweptWasTaken** [comment]
I _think_ this was fixed in a cleanup pr so i'm closing it.
