### ISSUE TITLE
Slipping mispredicts

### ISSUE THREAD

**Issue by keronshb** [space-wizards/space-station-14#8362]
## Description

**Reproduction**

Just slip on anything, you'll fall down twice. The first one gets cancelled exceptionally quick.

**Screenshots**

https://user-images.githubusercontent.com/54602815/169722784-ee35291d-e229-4bd3-ab2a-2196652f62ac.mp4

**Additional context**

**Comment by DogZeroX** [comment]
Added to The List.txt

**Comment by mirrorcult** [comment]
its fine now
