### ISSUE TITLE
Fire axes are too weak against glass

### ISSUE THREAD

**Issue by youarereadingthis** [space-wizards/space-station-14#8364]
## Description

Attacking a reinforced window with a fire axe in one hand does virtually if not literally zero damage.
In my test, when dual wielded it took 46 hits to destroy a single reinforced window.
And it took 7 hits against a regular glass window.

Giving them a flat damage bonus is not the way to go, I think. But they should do much more damage specifically against glass.
It shouldn't take more than 7-10 hits against reinforced windows while dual wielded in my opinion.

**Additional context**

In SS13 they could break windows with a single hit. Not how I would do it personally but that's just how they worked.

**Comment by DogZeroX** [comment]
Have you tried dual wielding

**Comment by youarereadingthis** [comment]
>In my test, when dual wielded it took 46 hits to destroy a single reinforced window.

ye 👨‍🚒

**Comment by Emisse** [comment]
i agree they should get a massive buff to windows. unsure if there is a structure/glass damage buff component but ill check

**Comment by keronshb** [comment]
On SS13 when wielded it would 1 shot regular full tiles and 2 shot reinforced. I could probably change it to that.

**Comment by youarereadingthis** [comment]
Solved by #9289
