### ISSUE TITLE
All explosive weapons are rigged

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#8367]
## Description

RPG, Grenade launchers explode on your feet

**Reproduction**

Shoot a grenade launcher or RPG
**Screenshots**

https://user-images.githubusercontent.com/43253663/169737895-c9e9f23d-7a23-4c5e-943d-de6a23fd69fb.mp4

**Comment by ike709** [comment]
See: https://github.com/space-wizards/space-station-14/issues/8334

**Comment by ike709** [comment]
@metalgearsloth
