### ISSUE TITLE
HoP doesn't have brig access

### ISSUE THREAD

**Issue by NicoSGF64** [space-wizards/space-station-14#8378]
## Description

The HoP, while having access to security, can't enter it due to not having brig access. This has been a problem since brig access was introduced.
**Reproduction**

**Screenshots**

**Additional context**

**Comment by Emisse** [comment]
![image](https://user-images.githubusercontent.com/99158783/169845471-8de606b9-1336-4909-899b-1af077aa5296.png)
hop current access for reference

**Comment by Laus4Deus** [comment]
This could be an issue when MRP rules are implemented, because for now it is LRP.

**Comment by metalgearsloth** [comment]
I just had an ahelp the other day where the HoP tried to act like they were head of security and not the HoS themselves so this might encourage the wrong impression.

**Comment by wrexbe** [comment]
I think the real problem is the access on the doors is wrong. I checked saltern, and I see security on the brig door, and brig on the security door.

**Comment by wrexbe** [comment]
So after doing some research, the brig permission is what lawyer + security are supposed to be able to get into. That means it is meant to be a more public permission then security. I think the names confusing, but that is a different issue.
