### ISSUE TITLE
PDA/ID painter

### ISSUE THREAD

**Issue by NicoSGF64** [space-wizards/space-station-14#8380]
## Description

The HoP should have a PDA and ID painter so that missing PDAs and IDs can be properly replaced (getting the ID and PDA "look" right) and getting promoted isn't just "job name and access change".
**Reproduction**

**Screenshots**

**Additional context**

**Comment by NicoSGF64** [comment]
> I like being able to tell immediately that it wasn't a standard issue card.

Does it really matter if it was standard issue or not? I'd prefer to make it so that it has the full design, as it's more "official" and more MRP-y.
 
> Having the HoP start with multiple basic colors(not the full design) in their locker/vend would be alright IMO.
They can run out, and if they are in their locker it'd be too much clutter.

**Comment by youarereadingthis** [comment]
I have nothing else to say about the first point but, but in regards to clutter they could just be in a "colored ID box".

**Comment by Laus4Deus** [comment]
Maybe heads could have the colored IDs. Extra people can get the access and job, etecetera, but only heads can give you the ID.

**Comment by Veritius** [comment]
ideaguys is leaking again

**Comment by mirrorcult** [comment]
not agreed on
