### ISSUE TITLE
Round Restart Vote Percent Required

### ISSUE THREAD

**Issue by HoidC** [space-wizards/space-station-14#8390]
Due to the addition of the abstain option by default, round restarts (which require like 60 percent iirc) are now commonplace instead of shuttle. This has lead to many a nukie or syndie round - my own included, I count three times since the change - being cut short because a few people too many were dead. It interrupts the gameplay and it sucks to have happen to you. I would like it to be 80 or 90 percent: if the round is DRASTICALLY ruined it should happen, otherwise not at all. If there's no possibility of shuttle, I mean, as I believe that is the intended purpose.

Cool, thanks

**Comment by metalgearsloth** [comment]
> which require like 60 percent iirc)

It's 70%.

Having to sit there waiting for the engis to finish their building their own shuttle for 30 minutes also sucks for example. Could try 80% but I'd rather have the odd round cut too short than extend many like before.

**Comment by moonheart08** [comment]
> > which require like 60 percent iirc)
> 
> It's 70%.
> 
> Having to sit there waiting for the engis to finish their building their own shuttle for 30 minutes also sucks for example. Could try 80% but I'd rather have the odd round cut too short than extend many like before.

Rounds are cut short way too often at the moment. Often before nukies even have a chance to end the game.

**Comment by metalgearsloth** [comment]
If it's nukies specific just make it not able to be restarted when the nuke is on for the first time.

**Comment by Laus4Deus** [comment]
In my experience when rounds are cut short because of a voting passing, it was well deserved.
Considering how often votings are made and from those, how many do pass, is it too often? Maybe we could run a short poll on the discord about it
