### ISSUE TITLE
Admin ghosts are somehow cargo computers.

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#8399]
## Description

How to replicate:

- Become an admin ghost.
- Pick up a multitool.
- Click the multitool on yourself.
- The multitool will pick you up as a valid machine linking target for some reason.
- Click anything that can be machine linked, such as a shutter, blast door, conveyor belt, or light.
- You apparently count as a cargo computer.

**Screenshots**

![image](https://user-images.githubusercontent.com/7907891/169937146-7bff721c-db9e-4896-8e58-14bd9cc05532.png)

**Comment by metalgearsloth** [comment]
intrinsicUI moment

**Comment by moonheart08** [comment]
intrinsicUI moment
this was a concession I made to allow admins to look at cargo orders remotely.
