### ISSUE TITLE
Remilia can drag and drop people into garbage chutes

### ISSUE THREAD

**Issue by LordEclipse** [space-wizards/space-station-14#8404]
For whatever reason, Remilia can drag and drop people into garbage chutes, and only garbage chutes, this has to be an oversight as every other attempt to drag and drop people onto things (i.e. chairs, beds, secways) says "you don't have hands"

**Comment by EmoGarbage404** [comment]
this no longer works.

**Comment by EmoGarbage404** [comment]
actually wait no. i lied.

**Comment by lzk228** [comment]
no
![image](https://github.com/space-wizards/space-station-14/assets/124214523/cedd8109-fdc1-4de3-b861-6962c0c65c72)

**Comment by JIPDawg** [comment]
As Lzk pointed out this is not currently possible and seems resolved. I tested myself as well and cannot replicate.
