### ISSUE TITLE
Interacting with lockers and other storage containers is not predicted.

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#8414]
## Description
EntityStorage and all that needs made shared, pretty much.

**Reproduction**
Try opening a locker.

**Additional context**
Makes lockers feel jank on laggy connections.

**Comment by ElectroJr** [comment]
@Macoron mentioned they had started ECSing entity storage in #5438. If most of the code is already being re-written anyways, its probably a good time to move a good chunk of it to shared?

**Comment by mirrorcult** [comment]
it is now
