### ISSUE TITLE
Vending machine sprite tracking issue

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/space-station-14#842]
I ported a bunch of vending machine sprites from bay in ef4bde53995982b6737d6176b9e98f1ad5256ce2.

That said, I got kinda lazy, and these things have to be addressed:
1. I didn't cut out unlit layers for them, even though they would benefit greatly from them.
2. I didn't port any outside of the ones I would see immediate use for in Slatern.
3. They all use the wrong maintenance panel sprite. Right now it's a stock one, whereas Bay's vending machines have unique maintenance panel sprites.

Also of note is that I cut out multi-directional variants of the sprites so they're purely front facing.

**Comment by SweptWasTaken** [comment]
Pretty sure this is fixed by #1549 , closing.
