### ISSUE TITLE
Mice revive into humans when scanned and cloned.

### ISSUE THREAD

**Issue by dan6798** [space-wizards/space-station-14#8424]
## Description
Might be a duplicate (someone said it wasn't) or intentional, but if you scan a mouse you can revive them after they die and they will turn into a human including their original player. It will show them as a mouse in a scanner.

**Reproduction**
Kill a mouse, scan and revive through the cloner.

**Screenshots**
![image](https://user-images.githubusercontent.com/63944747/170155839-0551710f-3170-4eb3-961a-5139504439eb.png)

**Additional context**

**Comment by mirrorcult** [comment]
this is getting fixed in a PR by @EmoGarbage404 i believe, mice unintentionally have humanoid appearance comp

**Comment by EmoGarbage404** [comment]
> this is getting fixed in a PR by @EmoGarbage404 i believe, mice unintentionally have humanoid appearance comp

Fixed in #8413
