### ISSUE TITLE
Shift+Click menu shows HP Bar for destroyable objects

### ISSUE THREAD

**Issue by chris2shehu** [space-wizards/space-station-14#8429]
It would be great to have an indicator that shows the damage done to a destroyable object. There are graphic indicators but sometimes you can't tell if an object is taking any damage at all...example would be a reinforced wall. Adding a HP bar to the Shift Click description would be a neat way to check the status of an object.

**Comment by ElectroJr** [comment]
AFAIK feature request are fine as long as they are reasonable.

For this specific feature, adding some sort of better health indicator might work for some entities, but getting an actual health percentage is surprisingly hard, and would in general require changes to how the destruction system works.
