### ISSUE TITLE
Electrified doors can't be un-electrified

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#8432]
## Description

How to reproduce:

- Cut a door's power wire.
- The door will now shock anyone who touches it.
- Repair the power wire.
- The door will still shock anyone who touches it.

Witnessed in a live round.

**Comment by themias** [comment]
I think you also need to pulse it (after mending) to remove the short?
It seems to be fine after I mend and pulse it.

**Comment by lzk228** [comment]
fixed
