### ISSUE TITLE
Change the naming of "Run" to "Walk" in the code

### ISSUE THREAD

**Issue by AJCM-git** [space-wizards/space-station-14#844]
Walking is called running in the code. That is a bit confusing

**Comment by Zumorica** [comment]
I'm pretty sure this is intended behavior. You run by default, and you use shift to walk.

**Comment by AJCM-git** [comment]
![image](https://user-images.githubusercontent.com/60196617/80205986-94526480-85f9-11ea-8b2b-e934b3d81a6c.png)
Im not sure about that

**Comment by Injazz** [comment]
You should run by default, as in original game. We actually changed this button from run to move but we forgot to rename it.

**Comment by TheChosenEvilOne** [comment]
> 
> 
> I'm pretty sure this is intended behavior. You run by default, and you use shift to walk.
I would assume this is correct as this is what happens in most SS13 codebases.

> 
> 
> ![image](https://user-images.githubusercontent.com/60196617/80205986-94526480-85f9-11ea-8b2b-e934b3d81a6c.png)
> Im not sure about that
Probably just labeled wrong.

**Comment by AJCM-git** [comment]
Okay, changed the issue
