### ISSUE TITLE
Sprays stopped working recently (Fire extinguisher, spray bottle with contact chems, etc.)

### ISSUE THREAD

**Issue by Elijahrane** [space-wizards/space-station-14#8441]
## Description

Some people said it might be due to collision groups.

**Reproduction**

1. Solution edit a spray bottle with something like phlogiston.
2. Spray people.
3. Observe that it doesn't work.
4. Use an incendiary shell in a gun to verify it's not the fire part that broke.
5. Try to put them out with a fire extinguisher.
6. Fire extinguisher doesn't work either.

**Comment by mirrorcult** [comment]
fixed by #8612
