### ISSUE TITLE
Item stacks have constant size no matter the stack size

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#8442]
## Description

This is primarily an issue for ore as you can stack a shit ton of them together but other stuff has the same issue. Ideally stack comp specifies the max size at max stack and it just scales linearly with stack size, flooring since item size has to be an int (iirc)

Stack merging might need to be tweaked a bit for this to make sure that you cant stack merge into something that's already in an inventory and have it go above the storage limit (if you can even do that, im not sure)

**Reproduction**

1. Spawn multiple steel ore
2. See that each individually weighs 5 in your inventory
3. Stack them together
4. See that the combined stack still weighs 5

**Comment by metalgearsloth** [comment]
Do stackables stack in storage? If so it will also need a check that it doesn't go above the bag's weight limit.

**Comment by Vordenburg** [comment]
Fixed by #17623
