### ISSUE TITLE
Some machines are missing an Anchorable component.

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#846]
Machines such as lathes are missing the anchorable component to allow them to be anchored/unanchored with tools.

**Comment by remove32** [comment]
I can take this one on I think. Adding a component to some machines shouldn't be too bad. Here's the list I made in testing: 

- protolathe
- autolathe
- base R&D point source
- medical scanner
- chem dispenser
- generator
- gravity generator?

I don't remember grav gen being wrenchable but it seemed worth noting

**Comment by remove32** [comment]
woops - this should be resolved by #1115

**Comment by ike709** [comment]
This should be closed.
