### ISSUE TITLE
Reassembling yourself as a skeleton when joining the game as a human will reassemble you as a human.

### ISSUE THREAD

**Issue by Veritius** [space-wizards/space-station-14#8463]
## Description
Apparently it just picks whatever you spawned/ghosted as. This is probably related to the monke cloning bug. Obligatory @EmoGarbage404

**Reproduction**
Pick a human or other species character. Delete yourself or something. Spawn a skeleton. Become the skeleton. Get disassembled. Reassemble. You are now whatever species you started as.

**Screenshots**

**Additional context**
Discovered round 10309 in Lizard

**Comment by Peptide90** [comment]
Related to the cloning issue etc

**Comment by Veritius** [comment]
We probably need a better system to determine what the hell your character is and storing that.

**Comment by EmoGarbage404** [comment]
fixed with #8972
