### ISSUE TITLE
MIDI issues

### ISSUE THREAD

**Issue by AJCM-git** [space-wizards/space-station-14#847]
~~- All instruments sound the same~~
~~- Audio volume depends on how low/high a key is (if you play a low note, it will sound low and barely recognizable, if you play a high note it will sound high) ~~
~~- Notes are always sustained~~
~~- Outline is always red for some instruments (piano and minimog, for example)~~
- You can play multiple handheld instruments at the same time (by clicking on them, activating MIDI input/file, dropping them and repeating the process with the next instrument).
~~- Some instruments dont have a sound font (like the saxophone and glockenspiel, for example)~~

**Comment by PJB3005** [comment]
> All instruments sound the same

Do you have soundfonts installed (since you're on Linux)?

**Comment by AJCM-git** [comment]
Oh, i didnt knew, let me try

**Comment by Zumorica** [comment]
> * Outline is always red for some instruments (piano and minimog, for example)

This is fixed by #848
