### ISSUE TITLE
Relogging only lets you chat in LOOC and OOC

### ISSUE THREAD

**Issue by Emisse** [space-wizards/space-station-14#8478]
reproduction steps
-be in a game
-relog
-all other chat channels gone

**Comment by Veritius** [comment]
maybe server thinks you just joined the lobby or something

**Comment by wrexbe** [comment]
Do you not see the chat channels on the selector?

**Comment by Emisse** [comment]
you do not

**Comment by Veritius** [comment]
you can fix this by /ghost-ing and going back into your body too

**Comment by wrexbe** [comment]
Thanks to test subject Kaishiba, the issue has been narrowed down. The console say command still works, and their doesn't appear to be anything wrong about the person in VV, so it is probably related to the UI not being updated correctly on re-login, the issue does not appear to happen to admins.

**Comment by VanicGame** [comment]
I have a similar problem. However, along with chats, the pause menu does not work, and the oxygen tank icon does not switch it.
