### ISSUE TITLE
The singularity can eat the abstract representation of the station.

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#8487]
## Description
This removes all latejoin slots and disbands the station instantly.

Please fix spawning entities in nullspace

**Comment by Pangogie** [comment]
Jesus. That's amazing.

**Comment by ElectroJr** [comment]
A.. uhh.. feature?

**Comment by EmoGarbage404** [comment]
I think the solution is more random pocket dimensions

**Comment by ElectroJr** [comment]
Fixed by #10348 (fixes the singularity issue, station entity might still be getting deleted via some other means).
