### ISSUE TITLE
Goat milk does not produce Cheese when mixed with Universal Enzyme 

### ISSUE THREAD

**Issue by Nitro-Express** [space-wizards/space-station-14#8489]
## Description
If you mix 40 Goat Milk with 5 Universal Enzyme, it does not produce a Cheese Wheel.

**Reproduction**
1. Milk a goat to obtain Milk.
2. Add Univerzal Enzyme to that Milk.
3. No Cheese Wheel is produced.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Peptide90** [comment]
Related: reagents don’t support tags.

then your construction step could take tag: milk and this would be fine.

**Comment by lzk228** [comment]
Chevre was added for goat milk in #17968
