### ISSUE TITLE
Better information on soul presence or lack thereof required

### ISSUE THREAD

**Issue by 20kdc** [space-wizards/space-station-14#8495]
## Description

It seems like at least one new player had trouble with the way soul information appears on examine.
Note there may be a colouring issue with this also, see below table.
It's worth noting that `red` is used for pretty much the one case when you absolutely never want to gib the body as a non-antag.

**Reproduction**
Examine bodies in various soul-related states.

**Screenshots**
Screenshots TODO, but here's quotes of the text, categoried by severity:

*Maybe just a temporary issue:*
+ SSD: yellow `{ CAPITALIZE(SUBJECT($ent)) } { CONJUGATE-HAVE($ent) } a blank, absent-minded stare and appears completely unresponsive to anything. { CAPITALIZE(SUBJECT($ent)) } may snap out of it soon.`

*Clone this person:*
+ Dead and ghosted but clonable: red `{ CAPITALIZE(POSS-ADJ($ent)) } soul has departed.`

*Braindead and okay to pass to chef:*
+ Prematurely ghosted: mediumpurple `{ CAPITALIZE(SUBJECT($ent)) } { CONJUGATE-BE($ent) } totally catatonic. The stresses of life in deep-space must have been too much for { OBJECT($ent) }. Any recovery is unlikely.`
+ Ghost roled: yellow `{ CAPITALIZE(POSS-ADJ($ent)) } soul has departed and moved on. Any recovery is unlikely.`

**Additional context**

See: https://discord.com/channels/310555209753690112/675078881425752124/980101663618629642

**Comment by 20kdc** [comment]
I think the biggest implication here is that the `soul has departed` text should be dropped, as it sounds way too much like the `and moved on` line for ghost roles, and the colours should be changed so that "okay to gib" players give red examine text while "non-okay to gib" players give yellow examine text.
Just my opinion on this.

**Comment by Just-a-Unity-Dev** [comment]
I mean, yeah, sure, we could drop the faux-IC stuff but it doesn't feel the same way. Besides, all people need to know is "Red clone yellow or purple bad".

You're kinda asking to drop the apple in an apple pie.

**Comment by Just-a-Unity-Dev** [comment]
> > "Red clone yellow or purple bad"
> 
> As I just demonstrated with my examples, while "red" is pretty much always "clone", "yellow or purple" are not always "bad".

Red clone, yellow possibly bad, purple "wait a few minutes"

**Comment by Just-a-Unity-Dev** [comment]
Honestly, we can solve this problem without removing the faux-IC, that's all I'm saying

**Comment by Zumorica** [comment]
@Myctai I don't agree with straight up using OOC concepts in examine, it should continue to use IC wording and the concept of "souls".

If I leave an upvote/downvote reaction it's because it's an easy and quick way to say "I agree/disagree" when I have nothing else to add, so please don't ping me needlessly, thank you.

**Comment by Tarkken** [comment]
> I think the biggest implication here is that the `soul has departed` text should be dropped, as it sounds way too much like the `and moved on` line for ghost roles, and the colours should be changed so that "okay to gib" players give red examine text while "non-okay to gib" players give yellow examine text. Just my opinion on this.

Perhaps saying "their soul is adrift" instead of "their soul has departed"?

**Comment by dmnct** [comment]
From the POV of crew and medical staff, is there a meaningful difference between "soul is in the body" and "sould has departed but is still around"? As these are the two most clonable states, why not just omit mentioning souls on these, and state something like "There are no lifesigns"
