### ISSUE TITLE
Removing unbroken lights needs a DoAfter

### ISSUE THREAD

**Issue by wrexbe** [space-wizards/space-station-14#8505]
Removing unbroken lights from a fixture should take time

**Comment by themias** [comment]
Should the LightReplacer still be an instant replace, same as by hand, or somewhere in between?

**Comment by wrexbe** [comment]
If it's fixing it, it can be instant. The problem is someone taking working lights. What I saw that prompted this fix was someone going to every light, grabbing it, and throwing it to break the bulb.
