### ISSUE TITLE
Polymorphable ignores damage groups of the polymorphed entity

### ISSUE THREAD

**Issue by Elijahrane** [space-wizards/space-station-14#8525]
## Description

When a repairable component is repaired, it sets all damage values to 0, including ones that their damage container doesn't have. This includes giving genetic and rad damage values to drones, etc.
**Reproduction**

1. Health analyzer a drone
2. Observe their limited damage types
3. Punch drone
4. Weld drone to repair it
5. Now the drone can get radiation and genetic damage, etc...

**Screenshots**

**Additional context**

**Comment by ElectroJr** [comment]
I cant seem to reproduce this using those steps. Did this happen in the downstream?

**Comment by Elijahrane** [comment]
1. Yeah, this is a secondhand report by Ripmorld and all the involved components are the same as upstream.

2. I've isolated the actual issue to polymorph after a bit more debugging ![image](https://user-images.githubusercontent.com/60792108/171073605-b10ee1e7-49fe-474d-9be3-902f374f7480.png)

**Comment by Elijahrane** [comment]
It breaks after both of these occur:
1. Set all damage types from one entity on another (with polymorphing, for example)
2. Repair entity (or maybe other similar things, e.g. rejuvs)

Somewhere along here the damage container gets bypassed, for things that are possible during normal play

**Comment by Elijahrane** [comment]
Recorded on upstream master

Uploading 2022-05-30 21-26-05.mp4…

**Comment by EmoGarbage404** [comment]
> Recorded on upstream master (make a Drone polymorph proto)
> 
>  2022-05-30.21-26-05.mp4

Is it able to take damage from the newfound damage types or do they just appear on the health analyzer menu?

**Comment by Elijahrane** [comment]
> > Recorded on upstream master (make a Drone polymorph proto)
> > 2022-05-30.21-26-05.mp4
> 
> Is it able to take damage from the newfound damage types or do they just appear on the health analyzer menu?

It can take damage from them, yes

**Comment by Elijahrane** [comment]
theres no need for roundstart polymorphs anymore and the system has been rewritten a bunch now, closing
