### ISSUE TITLE
Lockers that are unlocked in mapping mode appear locked in game.

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#8529]
## Description

How to replicate:

- Go into mapping mode.
- Place a locked locker.
- Right-click the locker and unlock it.
- Save the map.
- Load the map in-game.
- The locker will be open, but will appear to be locked.

Ideally, the game would remember that the locker is unlocked and would use the "unlocked" sprite in-game.

**Comment by Peptide90** [comment]
Something something serialisation or initialisation?
