### ISSUE TITLE
Improve text popup

### ISSUE THREAD

**Issue by AJCM-git** [space-wizards/space-station-14#853]
To give it more style they should be in italics. If anyone have more suggestions please write them here
Also the /me command should appear as a popup too

**Comment by Hugal31** [comment]
What about :
- Font size 10
- Italic
- Light gray, so it is a bit more aggressive

![image](https://user-images.githubusercontent.com/9070803/80626802-48ffe200-8a4f-11ea-9219-fa73180456e1.png)

**Comment by AJCM-git** [comment]
Nice, maybe reduce the font size to 8?
Does it work with /me?

**Comment by Hugal31** [comment]
I'll try 8, but it sounds too small for me.

I'm working on something else for /me: a speech "bubble", but in italic, and without the border, so it stick with the rest of the conversation.

**Comment by AJCM-git** [comment]
Sounds good.
If 8 is too difficult to read then dump it

**Comment by unusualcrow** [comment]
> 
> 
> Sounds good.
> If 8 is too difficult to read then dump it

_ring_
'e pushed?
**doomp eet**
_click_

**Comment by Hugal31** [comment]
Full screen picture at 8 for comparison
![image](https://user-images.githubusercontent.com/9070803/80638526-da2b8480-8a60-11ea-9ccb-3d74f4a00e63.png)

**Comment by AJCM-git** [comment]
Hmmmm, yeah, too small

**Comment by Hugal31** [comment]
Here is my proposition for the emotes: instead of using the current popup messages, which look more like "notifications" to me, I implemented the emotes as speech bubble, in italic without border.

![Emote label](https://user-images.githubusercontent.com/9070803/80647594-03531180-8a6f-11ea-93cb-876f023bb678.png)

**Comment by AJCM-git** [comment]
Looks good, i dont have any issues with it, you should commit it
