### ISSUE TITLE
Breaking liquid containers create stupidly big puddles

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#8537]
## Description

**Reproduction**

Break a water tank or a fuel one.
**Screenshots**

![image](https://user-images.githubusercontent.com/43253663/171046967-e41e031d-faf6-4188-98af-d7ce4b9e6d85.png)

**Additional context**

**Comment by moonheart08** [comment]
Great ~~Molasses~~ Welding Fuel Flood

**Comment by TemporalOroboros** [comment]
Honestly, it probably only looks that off because
1. It's instant
2. The sprites aren't one contiguous puddle.

**Comment by Willhelm53** [comment]
Re-evaluate after #11908 maybe? At the very least the new puddle debug-overlay will help.

**Comment by Ygg01** [comment]
It should be closed IMO.

**Comment by Visne** [comment]
The splashes are still pretty massive but not as big as in the screenshot

**Comment by Ygg01** [comment]
@Visne it depends on the vessel. Go to the console, type in `showfluids`, destroy a tank (downticks are due to evaporation), and see how it spreads. It won't be instant, and it won't be as big as in this issue.

**Comment by Visne** [comment]
Oh, back when this issue was opened it was instant?

**Comment by Ygg01** [comment]
> Oh, back when this issue was opened it was instant?

It was instant and spread to like 1 unit, hence huge puddles.

**Comment by Visne** [comment]
Alright, I assume the new behavior is intended then, so I will close the issue.
