### ISSUE TITLE
Physics/Collisions broken

### ISSUE THREAD

**Issue by AJCM-git** [space-wizards/space-station-14#854]
~~- Items have no collision and can go through walls~~ fixed by commit [4c08e66254d6ea265316b777b39e977ead044520]
- Lockers and items do have collisions but when pushed once they dont stop until they meet with a wall

**Comment by InquisitivePenguin** [comment]
I'm working on rewriting the entire physics system, hopefully that will fix this problem.

**Comment by AJCM-git** [comment]
Duplicate of #705
