### ISSUE TITLE
Mice can eat entire shelves of food in mere seconds with no consequences.

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#8547]
## Reproduction
Obtain entire shelf of cheese, spam alt-click on it until it's gone in mere moments.

**Comment by Visne** [comment]
Is this fixed?

**Comment by asperger-sind** [comment]
From my experience yeah, more or so.

**Comment by EmoGarbage404** [comment]
Fixed with the stomach and nutritions overhaul
