### ISSUE TITLE
Container culling

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#8557]
Right now most containers in content are ensured which means they're never default and always get written to yaml.

For prototypes with large entity counts (lights for example) it's probably worthwhile to add the ContainerContainer component onto the prototypes already as it will save several thousand lines of yaml across all of the maps.

**Comment by ElectroJr** [comment]
Would it make sense to have some sort of test that ensures that if entity prototypes are spawned into a pre-map-init map and then serialized, that the yaml entry is empty except for maybe transform/metadata?

**Comment by metalgearsloth** [comment]
> Would it make sense to have some sort of test that ensures that if entity prototypes are spawned into a pre-map-init map and then serialized, that the yaml entry is empty except for maybe transform/metadata?

Probably yeah, I think it's worthwhile enough to enforce containers aren't ensured most of the time IMO. Same with signal transmitters and the likes.

**Comment by Vordenburg** [comment]
I think this got covered by #10274.
