### ISSUE TITLE
Everything is hell I cannot get the game to work again

### ISSUE THREAD

**Issue by Yeeb0** [space-wizards/space-station-14#8582]
## Description
My issue, is that whenever I try to open SS14 to get on Lizard, it takes at least 20-30 minutes to get it to actually connect, and once I'm connected, nothing I do works. I tried latejoining and even observing but it does nothing. I can type in OOC but my texts don't show up. Even when I do join sometimes, it either softlocks me in one position where I cannot see or interact with the world moving around me but can turn and like let music keep playing, or freezes entirely (and in both situations it will not close)

**Reproduction**
Possibly have a shitty PC and connection, may be linked to Midis? Since thats what I'm doing excessively whenever it freezes

**Screenshots**
![Screenshot (45)](https://user-images.githubusercontent.com/104688945/171523064-93f16f56-2262-422d-8c21-145654abf1eb.png) 
![Screenshot (46)](https://user-images.githubusercontent.com/104688945/171523077-32d44bfe-9fef-4855-9c18-59f07b884c98.png)

**Additional context**
My connection is bad and my computer is bad, so both possible factors. However, when I first got SS14 I had none of these problems and it ran perfectly.

**Comment by mirrorcult** [comment]
report what your issue actually is with reproduction steps, spamming issues is not tolerated

**Comment by mirrorcult** [comment]
if you want actual help, you will need logs as well

**Comment by Veritius** [comment]
complex midi files will severely impact the client
if it's only happening when you try to use midis, perhaps your files are too complex

**Comment by Visne** [comment]
Is this still an issue?
