### ISSUE TITLE
Kitchen on Waystation be like

### ISSUE THREAD

**Issue by Kromabae** [space-wizards/space-station-14#8614]
## Description
think there's a lattice thatä's bugged on waystation in hte kitchen
**Reproduction**
just walk onto the same spot

**Screenshots**

https://user-images.githubusercontent.com/97402700/171847269-601697a7-9a29-4e6b-adfd-5f6a2a930485.mp4

**Additional context**
that little area is also spaced for some reason, just that one tile

**Comment by TimrodDX** [comment]
I just tested it using the latest Waystation master (this is the one that's on live right now) and I'm not experiencing that problem. My guess is that something broke on the server and caused that, or someone accidentally made a second grid there. 

![image](https://user-images.githubusercontent.com/7907891/171867287-96be4b39-9a69-4be9-bf86-6d33639e10a8.png)

**Comment by EmoGarbage404** [comment]
this bug has been fixed ages ago
