### ISSUE TITLE
People no longer get announcements in chat.

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#8620]
## Description
The audio still plays, but nothing happens in chat.

## Reproduction
Try `nukearm`.

**Comment by moonheart08** [comment]
This was caused by the communications console ECS PR.

**Comment by Veritius** [comment]
fixing it

**Comment by metalgearsloth** [comment]
3 issues:
1. Colour override isn't used
2. hideChat is set to true
3. GetOwningStation fails on the abstract station itself

**Comment by Veritius** [comment]
all fixed in #8644
