### ISSUE TITLE
Shocked doors are far too lethal

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#8631]
## Description

Right now, shocked doors can shock you even if you don't try to open them - the hitboxes are so large that you can get shocked merely walking by one. They also are guaranteed to shock you at least twice, because the following happens if you wander into the hitbox:

- The door shocks on open
- The door closes while you are still stunned
- The door shocks you again when you attempt to walk away because it opens again

Further, there needs to be a clear visual indicator that a door is shocked, and rules against shocking doors as a non-antag. It's not exactly great game design that late-joining engineers and atmos techs can die from a non-antag CE shocking all the doors into engineering when neither of those roles spawn with gloves.

**Comment by EmoGarbage404** [comment]
Personally, it doesnt make much sense that a door can electrify you just for opening it. It makes sense when youre cutting wires, but just touching the door seems weird.

**Comment by UbaserB** [comment]
How are shocked doors nowadays?

**Comment by mirrorcult** [comment]
theyre fine now pre sure
