### ISSUE TITLE
Some weapons should be wieldable

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#8636]
Their accuracy rn is probably fine but some guns unwielded (like the LMG) should be half as accurate.

**Comment by metalgearsloth** [comment]
Alright now that wielding is predicted I'm thinking nerf the accuracy of most guns when not wielded (unless it's like a pistol / revolver) and when wielded has their current accuracy. Maybe add the wield bonus to a separate component and nerf the base values.

**Comment by fidso** [comment]
i wonder how it would be a sprite of a wielded revolver

**Comment by deltanedas** [comment]
youd have to make the opposite arm move to your hand so its probably best to just leave sprite as it is
