### ISSUE TITLE
Item sizes need balancing

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#8638]
This also ties into "storage is really messy". Right now items are just all standardised sizes but this should probably be changed. Ideally:
* Anything with storage should be the size of its contents + its own size (to avoid nesting providing a benefit).
* Big items like crowbars or guns or spears should be much bigger (e.g. 20+) to encourage people to make decisions on what to take and not hoard everything on themselves like a gremlin. Small stuff is generally okay I think (e.g. mag sizes at 5).

**Comment by lzk228** [comment]
can be closed since new grid inv system?
