### ISSUE TITLE
Economy, Credits and Cash

### ISSUE THREAD

**Issue by Peptide90** [space-wizards/space-station-14#8646]
## Description

This issue is a feature request collection for player driven economy.

It compacts a mish mash of systems from cargo points and research points to role salaries and spending credits. By extension is involved departmental budgets and vendors too.

Related to #8645.

- [ ] Change cargo points to just credits making it shared with all other economy systems.
- [ ] Change research points to credits to further add value to credits.
- [ ] Give all roles on the station a salary. This can be a flat rate or based on grades or a modifier (e.g. basic salary is a 1, experienced or dangerous roles a 2, heads a 3 and special / captain a 4).
- [ ] Add ATMs for accessing your credit account stored on your ID card or PDA, and or accessed through an account number and pin stored in your character menu (C).
- [ ] Vending machines now require credits (physical or by card). Physical is stored on the unit to be emptied or looted, virtual goes to the service department budget.
- [ ] Department budgets - managed by the HoP on the station finances computer. Can adjust department budgets and see cash flow in and out based on salaries, spending on cargo requests / research requests and cash withdrawals.
- [ ] Assign a higher value to certain station produced goods to encourage the sale via cargo to generate money.
- [ ] Possibly tie the galactic economy back in so cargo prices fluctuate and have events that affect certain categories (like food) so it pays to store certain excesses of goods rather than flooding the market with a meta item and crashing the price. Rare event for credit exchange rate diving?

**Comment by moonheart08** [comment]
I'm not sure this can be made to work in any way that's actually engaging. Players themselves have no reason to move significant money around, the economy is far too small.

**Comment by Peptide90** [comment]
> I'm not sure this can be made to work in any way that's actually engaging. Players themselves have no reason to move significant money around, the economy is far too small.

We bikeshedded quite a bit in ideaguys for this and we’re all quite happy with the direction. To be clear everything is intended for MRP. Ideas?

**Comment by ike709** [comment]
Making economy semi-persistent would add actual value to the system's existence but that's a whole can of worms on its own.

**Comment by Emisse** [comment]
me turbo farming cash grind for 5 days straight

**Comment by Peptide90** [comment]
As discussed on discord, if cargo and science are dependent on credits ala the stations budget and are encouraged to make money, that adds your value in players moving money around.

**Comment by DogZeroX** [comment]
Do we actually want this?

**Comment by Emisse** [comment]
doc
