### ISSUE TITLE
Door Remotes shock you

### ISSUE THREAD

**Issue by LordEclipse** [space-wizards/space-station-14#8651]
So if you have a door remote and you use it on a door (i.e. engineering remote, cargo, sec, command, you get the idea) and the door you're using it on is electrified, you get shocked

1. Electrify a door, or find one
2. Use your corresponding door remote to open the door remotely
3. SHOCKED as if you had tried to open the door by hand
![Untitled](https://user-images.githubusercontent.com/106132477/172020751-a5eae9bd-4b91-4613-a5f0-708a1c89c26e.png)
![Untitled1](https://user-images.githubusercontent.com/106132477/172020753-0c25ca83-c207-48ac-8131-5f569b46c1a6.png)

**Comment by EmoGarbage404** [comment]
Can you provide a bit more information. The issue you're reporting is not clear.

**Comment by LordEclipse** [comment]
> Can you provide a bit more information. The issue you're reporting is not clear.

I accidentally hit enter so it submitted before I could write more, my bad.
