### ISSUE TITLE
GenericStatusEffect chemistry effect does not add components

### ISSUE THREAD

**Issue by Elijahrane** [space-wizards/space-station-14#8657]
## Description

It seems totally busted. Adjusting existing effects might work, but it isn't adding new ones. A good example right now is barozine, which is supposed to add the PressureImmunity status effect and component.
**Reproduction**

1. Take barozine
2. Open VV
3. Observe, contrary to what the YAML would imply, you have no pressure immunity component or status effect.

**Comment by 20kdc** [comment]
Did a test on 4fbea3cd1397fe88024713674ff5b16aee59aaac. Keep in mind that the `space medipen` contains Barozine.

Tried it, worked fine on both a human and a slime person.
You mentioned "taking" barozine - how was this performed?

**Comment by Elijahrane** [comment]
> Tried it, worked fine on both a human and a slime person. You mentioned "taking" barozine - how was this performed?
Using VV, it seems like it works some of the time when I test again (on a branch synced with latest master). However, anything other than removing time from an existing status effect seems to be somewhat unreliable. If I can get something more concrete I will reopen
