### ISSUE TITLE
You can place lattice on occupied floor tiles/spaces indoors.

### ISSUE THREAD

**Issue by retequizzle** [space-wizards/space-station-14#8660]
## Description

Lattice placed indoors/in hallways lets you create what I assume to be multiple grids over top of each other simultaneously. Pretty sure this also comes with suffocation hazards and can be used to grief stations.

**Reproduction**

Unsure how to reliably reproduce but I assume it has to do with "reality breaking" with certain people just getting the ability to walk through windows/walls/etc. also getting the ability to build/construct on a separate grid as well. No idea if a git issue is open on THAT yet, either. 

**Screenshots**

![image](https://user-images.githubusercontent.com/67210376/172032867-05ed982d-9073-4109-8927-869845ab9ced.png)

**Additional context**

**Comment by mirrorcult** [comment]
this is already fixed but not published
