### ISSUE TITLE
Stations are way too maneuverable

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#8663]
## Description

Pirates/nukies can just get straight up outrun sometimes. Need to either nerf thrusters for large mass or add station anchors or something

**Reproduction**

**Screenshots**

**Additional context**

**Comment by Peptide90** [comment]
@metalgearsloth can we scale damping with grid mass / tile count? Or do thrusters out run this? 

Otherwise we could manually set the damping on our maps with VV to something stupidly high?

**Comment by metalgearsloth** [comment]
> can we scale damping with grid mass / tile count?

Damping is percentage based and is already set to 5,000% (yes I want to change this).

Better off capping velocity based on thrusters / increasing grid mass / not spawning a station with a billion thrusters (atlas) / adding a tool for nukies to stop shuttle consoles on the target ship.

**Comment by JIPDawg** [comment]
Station Anchor real #26098
