### ISSUE TITLE
Tank issues

### ISSUE THREAD

**Issue by AJCM-git** [space-wizards/space-station-14#868]
- Fuel tank foes inside walls
- Water tank is broken

**Comment by PJB3005** [comment]
I fixed the water tank issue.

**Comment by AJCM-git** [comment]
Closing in favor of #967

**Comment by PJB3005** [comment]
These are completely unrelated issues.

**Comment by ComicIronic** [comment]
Adding to this: water tanks have item components, so you can pick them up.
