### ISSUE TITLE
Remove ghost role delay

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#8707]
No one reads it anyway.

**Comment by Just-a-Unity-Dev** [comment]
i call dibs

**Comment by SirDragooon** [comment]
Maybe leave the message, but remove the timer

**Comment by Just-a-Unity-Dev** [comment]
> i call dibs

i call undibs my devenv is broken

**Comment by Just-a-Unity-Dev** [comment]
> > i call dibs
> 
> i call undibs my devenv is broken

i call dins again i got the devenv working, check out #8817
