### ISSUE TITLE
Following people as a ghost can easily cause the client to break for the round

### ISSUE THREAD

**Issue by jessicamaybe** [space-wizards/space-station-14#8710]
## Description
![image](https://user-images.githubusercontent.com/31836813/172541040-2292c49f-40ec-42eb-9261-da2fba02225a.png)

This has happened to me while:

- Following a holo from the ghost roles menu while someone else takes the role

- Following somebody in the chess dimension 
 
- Following an angry chef (not sure what caused that one)

**Comment by ElectroJr** [comment]
I think #8682 fixes this, unless there is some other similar bug. It would get triggered whenever your original body that you were in prior to ghosting got deleted. So reproduction steps were just spawn in -> aghost -> delete body -> crash.

If it keeps happening after 24 hours (or whenever the servers next updates), re-open the issue.
