### ISSUE TITLE
Matches do not strike on the box unless it is full

### ISSUE THREAD

**Issue by themias** [space-wizards/space-station-14#8713]
## Description

If you attempt to light a match, it now is just inserted into the box. If the box is full, it then lights as expected.

@ElectroJr this might be related to #8290, can you take a look? It looks like the BaseSystem's OnInteractUsing is run first, so it gets handled by inserting before it reaches other systems like MatchboxSystem.

**Reproduction**

1. Hold a (not full) matchbox in one hand and a match in the other
2. Use the match on the matchbox

Expected Results: Match is lit
Actual Results: Match is inserted into the box

**Screenshots**

**Additional context**

**Comment by ElectroJr** [comment]
Its probably just an interaction priority problem where the storage system handles the interaction before whatever system lights it
