### ISSUE TITLE
Can't RMB Pull During Antigrav

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [space-wizards/space-station-14#8724]
## Description

During the no gravity event you can pull stuff behind you, but you can't RMB + ctrl pull it.

**Reproduction**

1. Get no gravity.
2. RMB + Ctrl click
3. No pulling

**Comment by retequizzle** [comment]
has to do with you not having magboots active to "anchor" you to the ground, was pretty sure this has always been the case and is working as intended but i'm also not the one who coded it

i do know if you have magboots active you can RMB + Ctrl click and it'll aggressively reposition the item

**Comment by LudwigVonChesterfield** [comment]
I am pretty sure you should be able to move the item relative to you even if you don't have an "anchor".
