### ISSUE TITLE
Nukies broken on master

### ISSUE THREAD

**Issue by Emisse** [space-wizards/space-station-14#8727]
nukies spawn but nobody is placed in control of them on mapload. happened around the time of the nukie naming PR. unsure if this is the cause though. #8692

**Comment by EmoGarbage404** [comment]
Did someone redo the nukie shuttle recently?

**Comment by Pangogie** [comment]
It was more likely the Opt-In stuff that was merged at the same time. I somehow doubt my like 3 line PR of changing their names had an effect. It worked on local too, so.

**Comment by Emisse** [comment]
#8541 the other pr to touch nukies during the publish that broke it

**Comment by Pangogie** [comment]
So nothing with that PR seems to be the issue. Everything goes through fine. The mind gets put into the Nukies. It seems something is happening in the round start sequence that is putting the Mind back into the normal human. It is probably the same bug that was causing the rounds to not start.

**Comment by EmoGarbage404** [comment]
this should be closed
