### ISSUE TITLE
Containment and powered structures need a unanchor / wrench check

### ISSUE THREAD

**Issue by Peptide90** [space-wizards/space-station-14#8732]
## Description

Unwrenching a containment field generator while it's on to release singularity is a reality and should not be.

This can probably go for a bunch of other stuff that's wired into HVs like so we need a check to turn it off before it can be unwrenched or deconstructed.
**Reproduction**

**Screenshots**

**Additional context**

**Comment by keronshb** [comment]
I don't think this is Dif 1. Field Generator isn't ECS and has... a very interesting way on handling changing anchoring states.

**Comment by metalgearsloth** [comment]
If this takes more than 10 minutes then someone should just bite the bullet and do https://github.com/space-wizards/space-station-14/issues/8891 because singulo / emitters / PA break way too often.
