### ISSUE TITLE
Wrench interaction with microwave both unanchors the micro and steals your wrench

### ISSUE THREAD

**Issue by retequizzle** [space-wizards/space-station-14#8744]
Somehow, unanchoring any microwave also leads to it immediately storing your wrench in the microwave after you finish unwrenching it. This occurs immediately after the do-after timer for the wrench completes, I did not check to confirm if it happens if you cancel the do-after. 

The wrench is retrievable but only after you re-anchor it with another wrench in order to eject contents, which for some reason also needs power.

**Comment by keronshb** [comment]
I'll look into this
