### ISSUE TITLE
Some tweaking needs to be done to charging batons

### ISSUE THREAD

**Issue by Kromabae** [space-wizards/space-station-14#8751]
To Charge a baton you need to take out the battery and put it in a specific charger to re charge it, but charging a normal green battery takes like 5 mins to recharge full and it only hold a couple of stun hits then it's out. This is by far crippling sec a lot and preventing them from doing an efficient job at times.
Sec is not encourged to hold 2-3 batons on them or a bunch of extra batteries just to be able to handle more than one assailant, becuase sometimes it takes up to 3 hits before the stun kicks in on someone.

I'm not even sure why the batons got a double nerf like this in the first place

**Comment by liltenhead** [comment]
Agreed, it's almost better for sec to attempt to disarm shove people over now. Less risk and no down time afterwards.
