### ISSUE TITLE
Need increased interaction range for (larger) multi-tile objects.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/space-station-14#877]
The gravity generator can only be interacted with if you are right hugged up next to it. Could we increase the interaction way or handle the detection better for these?

**Comment by Zumorica** [comment]
As a heads up, this is related to InRangeUnobstructed.
It feels like the check is a bit finicky at times.

**Comment by moonheart08** [comment]
Pretty sure this is long fixed?

**Comment by metalgearsloth** [comment]
Don't think so

**Comment by ElectroJr** [comment]
Currently interaction obstruction checks use the centre of entities, So you might be in range of the edge of the gravity generator, but not in range of the centre.

Fixing this would probably require using the actual mouse coordinates in combination with physics fixtures, or something like that.
