### ISSUE TITLE
You can no longer select a decal with the crayon without the eat interaction taking priority.

### ISSUE THREAD

**Issue by vulppine** [space-wizards/space-station-14#8796]
## Description
Instead of opening the crayon decal window, you instead can only eat the crayon. A workaround exists where you can have this not occur by wearing a mask (thanks Just-A-Unity-Dev/@eclips_e), but I don't think this is a very intuitive way of accessing this menu.

**Reproduction**
1. Have a crayon in hand.
2. Attempt to interact with it.
3. You will only eat it. No UI will pop up.

**Screenshots**

https://user-images.githubusercontent.com/76629141/173248452-e2a668f4-5a79-48b5-8a1f-3829ddaeb117.mov

**Comment by Just-a-Unity-Dev** [comment]
wearing a gas mask allows you to access the UI

**Comment by Peptide90** [comment]
> wearing a gas mask allows you to access the UI

Masks should block mouth interactions so it’s skipping that any letting you do UI whereas without eat is taking priority I imagine.
