### ISSUE TITLE
Improve construction.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/space-station-14#88]
* [ ] You cannot start deconstruction on something that's already built. Deconstruction DOES work on in-progress frames though.
* [ ] Construction state is not stored with `ExposeData`.
* [ ] Deconstruction does not return materials.
* [ ] Construction doesn't actually use the material prototypes defined in #84, it's hardcoded to stack type. It SHOULD use these and then allow storage and re-referencing once say a wall is constructed to change its properties.
* [ ] In-hand construction does not work because the hands GUI doesn't do attackby. Kinda a nuisance.

**Comment by chairbender** [comment]
sounds like @Acruid is working on revamping contruction going off recent discord convo https://discordapp.com/channels/310555209753690112/310555209753690112/723669865008857130
