### ISSUE TITLE
Gravity needs improvements

### ISSUE THREAD

**Issue by AJCM-git** [space-wizards/space-station-14#880]
- Catwallks don't give you support in space, so you start floating without control even if you have one below you. 
- Firing guns and throwing items doesn't stop you nor changes your direction
- There is no animation for when your character doesnt have gravity

**Comment by Zumorica** [comment]
> * Tiles dont stop you from floating. This means that catwalls dont work

Catwalks aren't tiles

**Comment by Fouin** [comment]
Some guns meant for EVA combat shouldn't impulse you (might be useful for nukies once they're in)

**Comment by AJCM-git** [comment]
> Catwalks aren't tiles
Oh, okay

**Comment by PJB3005** [comment]
Add "the gravity generator on animation plays at map load" to the pile.

**Comment by InquisitivePenguin** [comment]
> Firing guns stops you from floating, but dont impulse you

Good point, I'll add that in with my gravity rework

> There is no animation for when your character doesnt have gravity

That was a bit out of scope for my initial PR. But yes, that should be added in.

> There is no "whitout gravity" status effect

I'm not sure status effects have been implemented yet.

> The gravity generator on animation plays at map load

Yes, this is another thing I'm planning to fix

**Comment by PJB3005** [comment]
Oh, another thing. You get pushed back slightly when you throw something even if you're on solid ground.

**Comment by AJCM-git** [comment]
> > There is no "whitout gravity" status effect
> 
> I'm not sure status effects have been implemented yet.

My bad, i was refering to the the screen alerts (the thing that appears in the legt when you are hungry/thirsty a status icon appears at the left)
![image](https://user-images.githubusercontent.com/60196617/81224522-d72b1980-8fb5-11ea-9d79-7286e06dcdb3.png)

**Comment by InquisitivePenguin** [comment]
> You get pushed back slightly when you throw something even if you're on solid ground.

Yeah, I plan on handling throwing impulses as part of the virtual movement controller, which will check whether or not the player is standing on solid ground.

> i was refering to the the screen alerts

That's what I was assuming, though our current implementation of screen alerts is pretty simple if I'm not mistaken. It's a nice thing to have, but definitely not high priority.

**Comment by AJCM-git** [comment]
Yeah, its just a detail, it doesnt really matters much right now
