### ISSUE TITLE
Need the ability to dual wield items.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/space-station-14#882]

**Comment by mirrorcult** [comment]
i assume this means two-handed/wielded items like fire axes in which case I'm working on this

**Comment by SweptWasTaken** [comment]
> 
> 
> i assume this means two-handed/wielded items like fire axes in which case I'm working on this

No. This means stuff like dual-wielding guns so you don't have to switch between them to fire, or like having two melee weapons.

#1516 is the one you want.

**Comment by PJB3005** [comment]
I give it a 95% chance my original intent with this issue *was* fire axes and *not* dual wielded guns (akimbo style), actually.

But we already have an issue for that that's more clear, so...
