### ISSUE TITLE
R&D Point source stops generating points.

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#8836]
## Description
At times the point source for the R&D console stops working and points stop getting generated automatically over time. Usually occurs after a power outage or the server or a console gets wrenched.

**Reproduction**
Usually occurs after the power goes out, or if the console or point source gets moved or unwrenched/rewrenched. Also occurs at round start at times.

**Screenshots**

![R D point source problem](https://user-images.githubusercontent.com/106507028/173535139-4fcb2708-119f-461a-9540-bd9dfbd3d6ec.png)

**Additional context**
Not sure if the issue had already been reported. 

Sometimes the problem is fixed by moving the server/console to a different room. 

Can sometimes be fixed by editing vv.

**Comment by Mirino97** [comment]
![image](https://user-images.githubusercontent.com/52474532/174425905-4a0e79ea-a616-4c04-8988-f5823912f3b1.png)
