### ISSUE TITLE
All battery powered laser weaponry accessible to sec/crew has 50 base weight

### ISSUE THREAD

**Issue by retequizzle** [space-wizards/space-station-14#8838]
Makes stealing the antique laser gun a nightmare if you don't stash it. 

I'm a novice with this but it looks like it's a result of the battery_guns.yml since it's a universal weight problem across the board. There's no provisions for size= flags on any of the laser weaponry to differentiate say, a retro laser pistol or an antique laser pistol from a laser rifle. In fact, only weapons in this yml that have size flags are the pulse carbine and the taser.

**Comment by Peptide90** [comment]
Probably all inherits from the base size instead of having a small and large one. Just give it a new size component and set it lower so it’s more pocketable

**Comment by metalgearsloth** [comment]
The base size is 50; non-pistol guns shouldn't be pocketable.
