### ISSUE TITLE
Entity Spawning doesn't respect map rotation?

### ISSUE THREAD

**Issue by HoofedEar** [space-wizards/space-station-14#8859]
## Description

[Screenshot is from Prim but is taken after interacting with something Gatherable (asteroid wall) which is identical to upstream SS14]
When spawning stuff in using this these coordinates:
<img width="287" alt="Screen Shot 2022-06-15 at 7 45 54 AM" src="https://user-images.githubusercontent.com/1261392/173857272-44c16ecd-1c66-42e9-baa4-51c4f04f3448.png">
It can cause entities to spawn upside down or even sideways
<img width="106" alt="Screen Shot 2022-06-15 at 7 44 16 AM" src="https://user-images.githubusercontent.com/1261392/173857359-0bfcd905-258a-4df1-9b6d-3f2a57c238de.png">

The theory moony and I are thinking is that, for whatever reason, something with spawning doesn't seem to respect the rotation of the map/grid/whatever and the items are spawning in facing "true south"

No clue how to fix so posting this here!

**Comment by HoofedEar** [comment]
So looks like using this might be better practice in the meantime, as it seems to respect rotation
```
if (!TryComp<TransformComponent>(vendComponent.Owner, out var transformComp))
                return;

EntityManager.SpawnEntity(entity, transformComp.Coordinates);
```

**Comment by ElectroJr** [comment]
Entities should just spawn in with zero local rotation. In the first case, you're spawning them parented to the map, while in the second example you're spawning them such that they are parented to the same entity as `component.Owner`, which is presumably the grid.
