### ISSUE TITLE
Hyperspace system

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#8930]
I have had a thonkies and having a list of destinations on the left side of the shuttle console would be nice. This would essentially queue up a request to go to wherever, dump them in the hyperspace dimension for a bit, then drop them at their station, playing sounds when they depart and when they arrive.

**Comment by Emisse** [comment]
like a warp drive

**Comment by Just-a-Unity-Dev** [comment]
> like a warp drive

FTL drive*

**Comment by Veritius** [comment]
we are not bikeshedding the name of how you move fast _please_
