### ISSUE TITLE
Nukie Round end screen is ugly

### ISSUE THREAD

**Issue by EmoGarbage404** [space-wizards/space-station-14#8941]
## Description

It's basically just plain text and no formatting. It should ideally use color markup to look more interesting, like the traitor round end screen. 
**Reproduction**

**Screenshots**

**Additional context**

**Comment by Peptide90** [comment]
Although we have sexy nukes it should end as follows:
1) nuke explodes, giving players about 5-10 seconds to enjoy the aftermath.
2) cut to the nuke cutscene that shows the station explode from afar as the syndie shuttle escapes.
3) round end screen.
