### ISSUE TITLE
Crash when closing SS14.

### ISSUE THREAD

**Issue by aiz2501** [space-wizards/space-station-14#8945]
## Description

Crash when attempting to close SS14 after playing some rounds.

**Reproduction**

Exit game after a few rounds.

**Screenshots**

**Additional context**

(Steam version) - i tried verifying, reinstalling, clearing server content and installed engines to no avail.

**Comment by metalgearsloth** [comment]
DM logs to a maintainer otherwise it's kinda hard  to help.

**Comment by EmoGarbage404** [comment]
no repro + i haven't seen any crashes on shutdown in a while.
