### ISSUE TITLE
Combat-related systems dont work well with high latency

### ISSUE THREAD

**Issue by AJCM-git** [space-wizards/space-station-14#895]
if you have more than 100ms you cant melee attack and if you try to shoot you cant stop shooting even if there is no ammo left

**Comment by metalgearsloth** [comment]
On the shooting side I noticed that because SyncFirePos is spammed the server console is getting flooded with MsgLate (at least for me) so it starts to lag.

In my WIP gun PR I made this slightly better but if someone else wants to fix it by all means do so.

**Comment by PJB3005** [comment]
Shooting getting stuck was fixed by 046834129f36d06fdd01161a45058115c38ed694

The Msg late stuff is because the client isn't running ahead of the server enough but I'm not sure why that is specifically.

**Comment by AJCM-git** [comment]
Havent been able to reproduce this one again, i think its fixed
