### ISSUE TITLE
Observers aren't invisible to non-observers on roundstart

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#896]

**Comment by AJCM-git** [comment]
is this still an issue?

**Comment by Zumorica** [comment]
*Sometimes* it is. I haven't found a reliable way to reproduce this yet so I'd prefer if this was kept open.

**Comment by Zumorica** [comment]
Haven't encountered this bug in ANY of the SSS playtests we did lately, so I'm closing this.
