### ISSUE TITLE
Maps should be organized

### ISSUE THREAD

**Issue by ZeroDayDaemon** [space-wizards/space-station-14#8962]
## Description

Maps are currently just thrown into the mapping folder, ideally stations, shuttles, and salvage (already does), should have their own subfolders for easier identification, as well as a standardized naming scheme like StationName_Station Shuttlename_Shuttle or something of that degree

**Comment by mirrorcult** [comment]
kind of a dupe of #8084 but this is more detailed

**Comment by Peptide90** [comment]
Throwing this out there that I'm still seeing map prototype IDs not using PascalCase and people are mistaking the becomestation ID for the prototype ID, and not keeping them consistent either.

See #8404 for my feedback on each map file not following this format. My opinion now is have all stations in the Maps folder and have anything designed to be a shuttle in it's own folder like salvage is. Furthermore, all IDs should be the name only with no additions e.g. Bagel, Barratry, Delta, Pillar, Reach, Dart, Lighthouse, Split and so on. The only reason you'd ever need station or shuttle on the ID is if there is more than one of the same name, let's cut this stuff down.
