### ISSUE TITLE
You can hear sounds from VERY far away

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#897]
Right now, audio is a mess.
You can hear machines such as R&D consoles and machines from far away, and many sounds (such as the R&D console "key press" sounds, or the slurp sound when drinking) are global for ALL players when they shouldn't be.

**Comment by PJB3005** [comment]
Could definitely do with dropping the attenuation.

**Comment by InquisitivePenguin** [comment]
Is this still an issue after #933? Are there still sounds playing globally when they shouldn’t?

**Comment by Zumorica** [comment]
It is. You can still hear positional audio from veeery far away.

**Comment by InquisitivePenguin** [comment]
Alright, I can work on fixing that.

**Comment by Zumorica** [comment]
> Alright, I can work on fixing that.

I just assigned you!
