### ISSUE TITLE
Players on salvage wrecks despawn with the salvage wreck

### ISSUE THREAD

**Issue by Just-a-Unity-Dev** [space-wizards/space-station-14#8971]
## Description
was salvaging with my boys when we all just fucking disappeared, turns out EVERYTHING on a salvage wreck despawns with it, how nice.

**Reproduction**
1. Salvage
2. Wait for it to despawn
3. ???

**Comment by Just-a-Unity-Dev** [comment]
was told that this is intentional, at least add back the "salvage wreck despawns in 30 seconds" alert so we can get out

**Comment by Mirino97** [comment]
![image](https://user-images.githubusercontent.com/52474532/174656624-6d168e68-3dea-44b6-8166-c8f9c0d1388e.png)
