### ISSUE TITLE
Chat keeps unfocusing while writing

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#898]
And it's quite annoying.

**Comment by PJB3005** [comment]
This is because I made `ActivateItemInWorld` `CanFocus`

**Comment by henry2327** [comment]
hola me podria ayudar

**Comment by SweptWasTaken** [comment]
Can't reproduce. Is this fixed?

**Comment by ShadowCommander** [comment]
I think it was fixed by commit: 6ff691c
