### ISSUE TITLE
Rechargers charge extremely slowly, critical in ERT games.

### ISSUE THREAD

**Issue by asperger-sind** [space-wizards/space-station-14#8986]
## Description

Looking at round #11344, the one where Moony spawned several space dragons, xenos and ERTs in rechargers seem to charge at extremely slow speeds, for context, it took me about 6 minutes to charge 25/25 ammo in a Pulse Carbine ERT squadrons spawn with.
Six. Minutes. Whilst a bunch of Xenos can show up by that point, beat down your ammo-less comrades (and you), gib you afterwards and conduct cultist rituals just because it takes THAT long to recharge, and keep in mind, that's for one rifle, out of about 8, and a load of Retro lasers.

**Possible solutions**

Buff chargers in general.
Make charging speed vary with item (e.g tasers take X seconds to charge, lasers take Y, etc.)
Make the Pulse Carbines charge automatically.
~~Reject lasers, return to spear-throwing and robust combat, add caveman language.~~

**Comment by metalgearsloth** [comment]
See https://github.com/space-wizards/space-station-14/issues/8560

![image](https://user-images.githubusercontent.com/31366439/174694605-f9f591ba-b647-4d5e-a132-de64a7629f4c.png)

**Comment by ZeroDayDaemon** [comment]
> Reject lasers, return to spear-throwing and robust combat, add caveman language.
There's a fork for that already

**Comment by Willhelm53** [comment]
Possibly related, from the discord:
https://discord.com/channels/310555209753690112/1031245507588276244

![image](https://user-images.githubusercontent.com/97707302/196048557-6a028538-d035-4d3c-bb8a-74cbaba4a016.png)
