### ISSUE TITLE
China Lake Reloading mishaps 

### ISSUE THREAD

**Issue by Ablankmannn** [space-wizards/space-station-14#9002]
## Description

The China Lake doesn't accept Flash Grenades nor Frag Grenades, but it does accept Blast Grenades. Trying to load anything besides a Blast round will result in you... not loading them. This is peak Blast Grenade propaganda

**Reproduction**

Unload your China Lake
Take your Frag grenade or Flash grenade round
Attempt to load round
You should notice that the Frag/Flash round refuses to be loaded

**Comment by metalgearsloth** [comment]
Were you on a fork? Works for me.
