### ISSUE TITLE
Shuttle console reads docks facing the wrong direction.

### ISSUE THREAD

**Issue by Stealthbomber16** [space-wizards/space-station-14#9009]
The shuttle console is having issues reading direction.

![image](https://user-images.githubusercontent.com/100171035/174902035-4109ed51-0ec7-46cf-a963-ed128d9a8584.png)
This is an image of a shuttle console in Northwest split. Dock 7 is highlighted and begins facing north.

![image](https://user-images.githubusercontent.com/100171035/174902159-4afa295e-7b93-483a-9628-b28ed5c49799.png)
The console reads it as facing south.

![image](https://user-images.githubusercontent.com/100171035/174902261-d43f340d-f4f0-4896-b355-460ceedd1901.png)
The airlock in question- actually facing north.

This can prevent docking.

All images taken on the live version of the build on 6/21/2022 on Lizard.

I THINK it reads all docks as facing the same way. But I can't confirm that.

edit: formatting

**Comment by metalgearsloth** [comment]
Might be fixed in https://github.com/space-wizards/space-station-14/pull/8686 as I used matrices better.

**Comment by Stealthbomber16** [comment]
Appears to be fixed.
