### ISSUE TITLE
Clicking on an item in your hands double-clicks it.

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#903]
Steps to recreate.
1. Spawn in
2. Spawn a flashlight or unopened soda can or a gun
3. Pick it up 
4. Try clicking on it while it's in your hands

For the Flashlight, it appears to be double-clicking. For the unopened soda can, you're supposed to be able to crack it before you drink it but it just skips it and drinks it. For the gun it ejects the mag and shows "Magazine Ejected" and "No magazine" at the same time.

When using "Z" in the same situation, it functions normally.

![2020-05-10_22-19-21](https://user-images.githubusercontent.com/49448379/81526461-333fc600-9347-11ea-8dda-d6ac01c59d4f.gif)
![2020-05-10_22-04-22](https://user-images.githubusercontent.com/49448379/81526468-376be380-9347-11ea-8d85-c47b3641ee30.gif)

**Comment by Hugal31** [comment]
This was not fixed by #905?

**Comment by ShadowCommander** [comment]
Yeah, fixed by #905
