### ISSUE TITLE
Sparkle animation broke at some point

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#9049]
## Description

**Reproduction**

1) Wet mop
2) Mop floor
3) Edit solutions the puddle to be like 3u, or just wait

**Screenshots**
![image](https://user-images.githubusercontent.com/19853115/175210383-b5e58e27-205f-4655-af6c-fef699df65c0.png)

**Additional context**

**Comment by Willhelm53** [comment]
Does this issue refer to the sparkles being static on one frame instead of being animated? If so, this will be fixed in my upcoming PR.

**Comment by mirrorcult** [comment]
yes
