### ISSUE TITLE
Joints and cigarettes need a bit of love.

### ISSUE THREAD

**Issue by Stealthbomber16** [space-wizards/space-station-14#9052]
Two issues

I think Rolling Papers and Cigarette filters were coded with the intent of not being stackable. Now they are. If you attempt to craft a joint or cigarette with stacks of Rolling Paper, Cigarette Filters, or Ground Tobacco/Cannibis, the craft will consume every item in the stack. This can cause you to lose a lot of rolling paper or filters.

Joints (and I think cigarettes, but I didn't test this) cannot be named with a Hand Labeler. There... isn't a practical reason for this and it should probably be fixed.

**Comment by Visne** [comment]
Related to #10466

**Comment by Visne** [comment]
Hand labeler seems to work fine for me.
