### ISSUE TITLE
Add a DumpContents [Verb] to ServerStorageComponent.

### ISSUE THREAD

**Issue by ghost** [space-wizards/space-station-14#908]
I tried for 4 hours :slightly_smiling_face: . 
Good luck getting around the way that netmessages (telling the client's UI to update when storage is changed) aren't send in the correct order.

**Comment by ComicIronic** [comment]
Could you clarify the netmessages problem? Might be good to have technical detail for anyone who wants to try and fix this in the future.

**Comment by FL-OZ** [comment]
@ComicIronic 

line 252 in [ServerStorageComponent.cs:252]

```cs
        /// <summary>
        /// Updates storage UI on a client, informing them of the state of the container.
        /// </summary>
        private void UpdateClientInventory(IPlayerSession session)
        {
            if (session.AttachedEntity == null)
            {
                Logger.DebugS("Storage", "Storage (UID {0}) detected no attached entity in player session (UID {1}).", Owner.Uid, session.AttachedEntityUid);
                UnsubscribeSession(session);
                return;
            }
            Dictionary<EntityUid, int> storedentities = new Dictionary<EntityUid, int>();
            foreach (var entities in storage.ContainedEntities)
            {
                storedentities.Add(entities.Uid, entities.GetComponent<StoreableComponent>().ObjectSize);
            }
            SendNetworkMessage(new StorageHeldItemsMessage(storedentities, StorageUsed, StorageCapacityMax), session.ConnectedClient);
        }

```
SendNetworkMessage(new StorageHeldItemsMessage(storedentities, StorageUsed, StorageCapacityMax), session.ConnectedClient);

All the storage stuff was made with only 1 item being removed or inserted at a time. While, technically speaking, dumping all is still only removing one at time. The messages getting sent in that block of code do not get sent in the correct order for some ungodly reason.

**Comment by ComicIronic** [comment]
Turns out this is due to a (deliberate?) limitation of the network message system - entity messages are not required to be delivered in order.

**Comment by FL-OZ** [comment]
I sort of figured that's what it was. I guess what could be done is what @ShadowCommander and I were talking about for guns could be implemented here to the verb as well. A "StartShooting" message and then a "EndShootingMessage".

**Comment by EmoGarbage404** [comment]
This exists for plant bags and garbage bags. I think this probably can be closed, and if not, the dumping system used for those systems should be generalized.

**Comment by mirrorcult** [comment]
this has been done for a while yeah
