### ISSUE TITLE
Split Station Warden inconsistencies

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#9084]
## Description
On Split Station the warden's office does not spawn with a wardens locker. Warden also does not have access to the button toggling the blast doors to the leathal armory.

**Reproduction**
N/A

**Screenshots**

Warden Office:
![split station warden office](https://user-images.githubusercontent.com/106507028/175399257-749120cb-a1d4-4078-a980-cc8a33f95b36.png)

Hos Office:   -- Blast door button on right side --
![split station HoS office](https://user-images.githubusercontent.com/106507028/175399288-2f8988d1-3e97-4efa-9f0c-d4694f53279a.png)

Armory:   Note the blast door preventing access to the lethal armory on the bottom
![split station armory](https://user-images.githubusercontent.com/106507028/175399343-e1886c73-1dce-4a72-b583-a005a6374e73.png)

**Additional context**
In every other station, the warden spawns with a wardens locker and they have access to the leathal armory. On split station, the button to open the leathal armory blast door is located in the HoS' office. 

For consistency, the warden should be able to get into the leathal armory without relying on the HoS and a wardens locker should spawn in the warden office.

**Comment by Peptide90** [comment]
Known, adding the locker is on my to do list but I’m on holiday and mapping has been sus for ages for me.

Also the blast door is intended. Guns are for code red only and warden doesn’t have that power. Maybe when we get MRP.
