### ISSUE TITLE
Sanitize capital is broken

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#9094]
## Description

likely by dept chat

**Reproduction**

**Screenshots**
![image](https://user-images.githubusercontent.com/19853115/175455323-0638911c-f3ec-487d-8657-60d10a1c2228.png)

**Additional context**

**Comment by Just-a-Unity-Dev** [comment]
someone told me that it's probably due to it capitalizing the dept character, so when you do `:e hi engineering`, the game sanitizes it and does `:E hi engineering`

**Comment by mirrorcult** [comment]
yeah most likely
