### ISSUE TITLE
Cargo Shuttle needs to be idiot-proofed.

### ISSUE THREAD

**Issue by Stealthbomber16** [space-wizards/space-station-14#9098]
Cargo shuttle blast doors currently open to space even when docked. This isn't a bug, it's just unintended. New players open the blast doors and space everything. Cargo shuttle also lacks firelocks so new players are opening the wrong blast doors and spacing the entire shuttle and by extension cargo.

**Comment by moonheart08** [comment]
Implement the tiny fans/holofans so we can just put them under the doors and prevent it being spaced.

**Comment by Emisse** [comment]
could put flaps under them

**Comment by mirrorcult** [comment]
they should probably just have airtight flaps yeah

**Comment by Emisse** [comment]
ill update it when i go through mapping list and tell people to put flaps under blast doors in their bays

**Comment by Just-a-Unity-Dev** [comment]
crates dont go under flaps tho, holofans is a good idea

**Comment by Peptide90** [comment]
> crates dont go under flaps tho, holofans is a good idea

Sounds like a bug, that’s their sole purpose is cargo mules and crates.

**Comment by Stealthbomber16** [comment]
Would absolutely suggest that holofans are the way to go here.

**Comment by Peptide90** [comment]
> Would absolutely suggest that holofans are the way to go here.

Bolt docks shut that aren’t docked. Shrimple.

**Comment by Just-a-Unity-Dev** [comment]
> > crates dont go under flaps tho, holofans is a good idea
> 
> Sounds like a bug, that’s their sole purpose is cargo mules and crates.

yeah thats def a bug, mirror said they should be going under it. i dont wanna mess will layers so if anyone wants to fix it its fair game

**Comment by Stealthbomber16** [comment]
Tiny fans fixed this issue.
