### ISSUE TITLE
Crates don't go under plastic flaps

### ISSUE THREAD

**Issue by Just-a-Unity-Dev** [space-wizards/space-station-14#9101]
## Description
Title. According to mirror they should, feel free to patch it

**Reproduction**
1. Spawn a plastic flap
2. Spawn a crate
3. Try to move the crate through the plastic flaps

**Comment by Just-a-Unity-Dev** [comment]
fuck it i'll patch it

**Comment by Just-a-Unity-Dev** [comment]
im lazy anyone wanna do it

**Comment by lzk228** [comment]
they do go
![image](https://github.com/space-wizards/space-station-14/assets/124214523/4dac7ccd-904d-44c8-8f43-863ab3a659a1)

**Comment by K-Dynamic** [comment]
The standard steel or plastic crate fit under flaps fine. However, livestock crates should be tested as I feel they've collided with plastic flaps before.

There's also other objects such as welding/water tanks, vending machines and gas canisters that collide with plastic flaps (common things to be sold and ordered at cargo), though that would probably be beyond the scope of this issue.

**Comment by lzk228** [comment]
doesn't that intended? livestock crates are big
btw ill do fix pr

**Comment by IamVelcroboy** [comment]
> doesn't that intended? livestock crates are big btw ill do fix pr

Big, perhaps, but this might be one of those cases where gameplay QoL > realism

I would agree with the other comment that tanks and canisters should go under them as well. Vending machines...maybe. But I could see maybe not.
