### ISSUE TITLE
Fixing power is schadenfreude

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#9103]
1. Laying cables is annoying because sometimes it lays on the tile you clicked on and sometimes it doesn't, especially if there's a SMES or the likes on the tile. If I can't lay it should tell me why.
2. Trying to debug power issues just requires slamming your head into a wall until it turns on. Do you have enough generation? Are the cables unplugged? No idea.
3. Cable terminals are unintuitive even if they need to exist, at a minimum there should be a popup or the likes.

Possible fixes:
1. UIs / examines saying whether something is recharging or not (so even if it's at 0% I know it's getting power at least and feeding it out)
2. Power alerts console, possibly with a drawing of the station like RadarControl that has a list of HV / MV nodes.
3. Anything else anyone can think of.

**Comment by Peptide90** [comment]
Step 1: point people to the wiki till we get books in game for power devices.

That aside, I had a thought about drawing HV circuits on a console, pretty much how real life circuits do it with a mimics board. I imagine it would be fairly easy to do by connecting the lines between entities. Display power info on them etc.

**Comment by Mirino97** [comment]
Regarding your possible fix #1:
In case something is connected but currently not charging (due to a lack of supply), would you show that data in the examine? (i.e "Connected to powernet, but not charging") 
Or would it just say "Recharging" even though it's currently NOT being recharged, as it's not being supplied?

**Comment by Emisse** [comment]
we have swag power ui console
