### ISSUE TITLE
Flash movement debuff doesn't go away

### ISSUE THREAD

**Issue by Ablankmannn** [space-wizards/space-station-14#9113]
## Description

After getting flashed, the debuff granted to you which SHOULD be temporary is, instead, permanent. This means getting flashbanged stops you completely.

**Reproduction**

Grab anything that can flash you (flashbang, flash)
Use it to flash yourself
Once the flash subsides, you should notice that the movement debuff granted to you while you're flashed is still there

**Comment by Mirino97** [comment]
I can't, for the life of me, figure out what's wrong.
RefreshMovementSpeedModifiers() get's called when SlowedDownComponent shutsdown, but for whatever reason the event fired inside doesn't have the default values of 1f, 1f to the Speed modifiers, and I *think* that's what's currently borking everything up.

**Comment by themias** [comment]
> I can't, for the life of me, figure out what's wrong. RefreshMovementSpeedModifiers() get's called when SlowedDownComponent shutsdown, but for whatever reason the event fired inside doesn't have the default values of 1f, 1f to the Speed modifiers, and I _think_ that's what's currently borking everything up.

This seems related to the jetpack update the other day, #9023 
It looks to be the changes to the MovementSpeedModifierSystem. Originally, it wasn't raising the RefreshMovementSpeedModifiersEvent in SharedStunSystem when called from OnSlowRemove(), so the movement speeds were reset to the default 1.
Now, upon shutdown, the event is being called in SharedStunSystem, and it is getting set to the SlowedDownComponent's modifiers.

It looks to me like sloth's changes are good, and the RefreshMovementSpeedModifiersEvent is supposed to be called in both cases, and SharedStunSystem just needs to update the OnRefreshMovespeed() to correctly handle being called both on init and remove?

**Comment by Mirino97** [comment]
> 

I think you're onto something! I did some very crude tests and it does indeed "solve" the issue.
I just gotta figure out how to do what you mentioned without hardcoding the values inside OnRefreshMovespeed

**Comment by metalgearsloth** [comment]
Fixed in https://github.com/space-wizards/space-station-14/pull/9214
