### ISSUE TITLE
Reagents need prices for cargo

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#9115]
Even if we don't balance it having support now would be good.

**Comment by Peptide90** [comment]
For reference, this should look something like a price per unit on the reagent type. That way when cargo sell something it takes into account the container cost as well as the total value of the units within.

**Comment by mirrorcult** [comment]
99% of reagents should also not have a price because uhhh chem dispenser oversupply moment

**Comment by EmoGarbage404** [comment]
we support this
