### ISSUE TITLE
Sliceablefoodcomponent is hecked and meat reagent balances

### ISSUE THREAD

**Issue by Peptide90** [space-wizards/space-station-14#9116]
## Description

Some foods like the raw meat can be sliced and will disappear. Most foods like salami and meat clown will not and can create infinite meat.

The component for sliceable meat has the default count to 5 but this doesn't seem to make a difference. Pretty sure this affects cake too.

Also meat cutlets don't have proportional reagents.

**Reproduction**

1) spawn some salami and some raw meat.
2) cut them
3) infinite meat

**Screenshots**

**Additional context**

See https://github.com/space-wizards/space-station-14/blob/master/Resources/Prototypes/Entities/Objects/Consumable/Food/meat.yml

https://github.com/space-wizards/space-station-14/blob/master/Content.Server/Nutrition/Components/SliceableFoodComponent.cs

**Comment by Git-Nivrak** [comment]
Can't replicate

**Comment by EmoGarbage404** [comment]
This was fixed by #9170
