### ISSUE TITLE
Nukies mode is broken (again)

### ISSUE THREAD

**Issue by Ablankmann** [space-wizards/space-station-14#9132]
## Description

The nukies mode is broken. Like, completely unplayable. It won't start.

**Reproduction**

Start a server, addgamerule NukeOps to make the next mode nukies 
Wait for game to start
When the counter reaches 0 and starts the game, you should notice the round restarts immediety after.

**Additional context**

The bug completely borks nukies in Secret, not just the NukeOps mode. Please fix funny red spessmen mode no worke.

**Comment by Mirino97** [comment]
I may have a fix for this up soon, but in case I don't, here's what I discovered.
Bug:
![image](https://user-images.githubusercontent.com/52474532/175790653-88530f55-d9cd-47a2-b801-48dc7d73c0ed.png)

Issue found:
In NukeopsRuleSystem, in the spawn method, there's:
```csharp
foreach (var uid in _stationSystem.Stations)
        {
            var grid = Comp<IMapGridComponent>(uid).Grid;

            aabb = aabb?.Union(grid.WorldAABB) ?? grid.WorldAABB;
        }
```
        
In Moony's words: "that is in fact the wrong entity
stations are an abstract datum
you want to iterate the grids that compose the station."
