### ISSUE TITLE
Drinking glasses look full of water when they are empty.

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#9144]
## Description
Drinking glasses look like they are filled with water when they are empty.

**Reproduction**
Get drinking glass from Booze-O-Mat.
compare empty glass with a glass filled with water.

**Screenshots**
A empty glass(left) compared with a full glass of water (right)
![drinking glass](https://user-images.githubusercontent.com/106507028/175769009-e8719b0f-5e5d-447f-be1e-f69e360f0ce4.png)

**Additional context**
Not sure if the empty sprite is just a place holder but ckey user Vengie brought it to my attention.

**Comment by Delete69** [comment]
Literally unplayable
