### ISSUE TITLE
Freezers and heaters affect gas in different potency based on the target temperature.

### ISSUE THREAD

**Issue by asperger-sind** [space-wizards/space-station-14#9151]
## Description

Say, a freezer set to 275K is going to cool much, MUCH slower than a freezer set to 75K, resulting in fucky usage like setting a freezer to 75K, cooling down whatever to -200C, then setting it back to 275K to get it back to the target you wanted, which doesn't really make sense.

Is this intentional?
Possibly.

**Comment by asperger-sind** [comment]
Bwomp, MoMMi outage so it didn't relay.

**Comment by Emisse** [comment]
intentional
