### ISSUE TITLE
The singularity can suck entities through full walls.

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#9157]
## Description
The singularly can pull players and items through full solid walls, windows, and field generators.

**Reproduction**
Set up singularity.
Stand next to it behind a wall.
???
You are now a ghost.

**Screenshots**

The area where players and items are being sucked through on delta station. 
(note that anything entering the PA room will be sucked in.)
![singulo bug](https://user-images.githubusercontent.com/106507028/175792756-6c380f89-379b-4c98-88a4-a8cf1069be14.png)

The pull is even sucking players through maintenance on the lower part of the singularity.
![singulo bug2](https://user-images.githubusercontent.com/106507028/175793075-f3db1e29-29b1-4b5b-9e06-891a9cf1282e.png)

**Additional context**
The pull radius is long enough to suck in someone all the way from past the PA computer console and through the windows and shutters on either side.

**Comment by keronshb** [comment]
https://user-images.githubusercontent.com/54602815/183499101-a8b8032b-132f-492a-bf85-32a834a2ba67.mp4

This might be fixed?
