### ISSUE TITLE
Nuke disk insert sound only for other

### ISSUE THREAD

**Issue by Morb0** [space-wizards/space-station-14#9160]
## Description

`NukeSystem` works only on server, because of that `ItemSlotsSystem` calls `SoundSystem.Play` that play sound for other players around only.

**Reproduction**

Insert disk to nuclear bomb.

**Screenshots**

**Additional context**

**Comment by Mirino97** [comment]
Slots are server side and need to get properly networked.
Electro mentioned he plans doing that at some point.
