### ISSUE TITLE
Jetpack mini-thread

### ISSUE THREAD

**Issue by retequizzle** [space-wizards/space-station-14#9177]
Issue 1: **Mini-jetpack does not shut down after running out of propellant.**

To replicate, just fill the jetpack up with any amount of air (I did it from max fill and 100kpa), toggle thrust on, let it drain to 0kpa remaining. Still able to move around in space, no loss in functionality other than not being able to double it as air supply.

Issue 2: **Mini-jetpack/jetpack do not fit in exoslots.**

Honestly, not as big of an issue but we have the exoslot whitelisted for O2 tanks, which this is presumably an extension of. That said, Sloth said he forgor exoslot was a thing and I can go either way on this one. Could be too powerful being an exoslot item, would merit testing though. We're already barring salvage from having this so it'd offset some of the power gain there, engineering does still need the ability to carry materials around for repairs so ditching the bag kind of hinders that. Open to discussion on this one.

Issue 3: **Jetpack speeds affected by thirst/hunger slowdown, presumably other kinds of slowdown as well.**

As I said in the discord, kind of funky interaction, not really opposed to this one either, mostly just reporting this so it doesn't get overlooked if not intentional.

**Comment by Mirino97** [comment]
With #9206, I'm fixing issue 1.

Issue 3 is certainly an unintended interaction, at least in my view. It doesn't make sense for hunger to affect it. 
I'll make another issue to separate it and make it easier to resolve.

Issue 2 is up to the maintainers. Due to that, I'll be adding the "Needs discussion" tag
