### ISSUE TITLE
some air vents in security are connected to waste on bagel station.

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#9179]
## Description
On bagelstation, the air vents in Hos' office and the locker room below are connected to waste.  The scrubbers are connected to distro.

**Reproduction**
N/A

**Screenshots**
Note the air vent connected to the red pipe.
![bagel station hos' office air vent](https://user-images.githubusercontent.com/106507028/175807061-0c8064e7-ff69-4c03-b575-933a16ef4ce4.png)

![bagel station hos' office air vent2](https://user-images.githubusercontent.com/106507028/175807064-eae6914f-e787-41d3-a081-147e1aa88ceb.png)

Note the scrubber connected to the blue pipe.
![bagel station hos' office air vent3](https://user-images.githubusercontent.com/106507028/175807066-7f5ac677-860b-4c12-b6b1-a61328e9394b.png)

**Additional context**

**Comment by Peptide90** [comment]
@Emisse

**Comment by Emisse** [comment]
zamn

**Comment by Emisse** [comment]
ill fix that in a bit

**Comment by TsjipTsjip** [comment]
This issue looks resolved to me.

**Comment by keronshb** [comment]
> This issue looks resolved. Consider closing it.

I'll take your word for it
