### ISSUE TITLE
Stun diminishing returns / stamina

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#9184]
Right now combat meta is to use a taser / stun baton to stunlock your target to death. Ideally repeated stuns would become less effective and do nothing by the 3rd / 4th stun and have a short cooldown (e.g. 30 seconds) before applying the full stun again.

Not sure on the best way to go about it. One solution is using a stamina system with a meter to track how long the stun should be that takes a while before someone can get a full stun on them again. This might need 2 meters, e.g. one that tracks overall stamina damage (to know when a stun should be applied, e.g. when it hits 100 damage apply a stun and reset), and another that tracks their overall stamina to know how long it should be that decays more slowly, multiplying by some kind of exponential curve based on the overall stamina so the first stun for example is ~3 seconds, the second is 1.5 seconds, 3rd is 0.5, etc.

The ideal goal is that security can stun someone to detain them after 2 taser shots but also that they aren't encouraged to keep their taser out and rotate stuns to win.

**Comment by metalgearsloth** [comment]
Also I've looked at /tg/'s stamina and it's stupid because you can still get stunlocked so please don't 1:1 port it.

**Comment by mirrorcult** [comment]
we whave stammerna
