### ISSUE TITLE
Restart votes are getting absurd.

### ISSUE THREAD

**Issue by Emisse** [space-wizards/space-station-14#9189]
restart votes are called about 20 times a round and several times the round ends way before it needs to because they died in an explosion or something that could be remedied in 5 minutes. not sure what we should do about this but its one of the biggest things plaguing game quality right now

**Comment by Elijahrane** [comment]
Make some way for dead people to voice their discontent with the round, but just make succeeding let the admins use their judgement to decide if they should call an unrecallable shuttle. Maybe just give player ghosts an action that says "I am dead and angry that I died" and remove the actual vote

**Comment by Peptide90** [comment]
#8825 duplicate pretty much.
1) prevent people from calling restart in first half hour.
2) prevent people from calling restart for 5 mins after they die.

**Comment by PJB3005** [comment]
Restart votes were primarily intended for (almost) empty servers so if they're messing around and all die they can restart the round. For the actually populated servers I say just disable restart votes entirely above a certain amount of players.

Maybe make sure there are still backup solutions for the round to end in a worst-case scenario with no admins. I know some SS13 servers calls shuttle automatically if all comms consoles are destroyed, and goon auto calls if a large amount of people are dead.

**Comment by Peptide90** [comment]
> Restart votes were primarily intended for (almost) empty servers so if they're messing around and all die they can restart the round. For the actually populated servers I say just disable restart votes entirely above a certain amount of players.
> 
> Maybe make sure there are still backup solutions for the round to end in a worst-case scenario with no admins. I know some SS13 servers calls shuttle automatically if all comms consoles are destroyed, and goon auto calls if a large amount of people are dead.

Shuttle auto calling was discussed earlier on an unrelated matter for comms consoles being destroyed. Imo only do that after a pause like “oh we’ve noticed you’ve bridge is ruined, dispatching a shuttle”. The latter would be better I think as it’s less likely to ruin rounds.

**Comment by metalgearsloth** [comment]
I'm fine increasing the percentage given evac shuttle is in. It was mainly a temporary measure as it was almost impossible to succeed when votes defaulted to no.

**Comment by Peptide90** [comment]
> I'm fine increasing the percentage given evac shuttle is in. It was mainly a temporary measure as it was almost impossible to succeed when votes defaulted to no.

Think it’s vote spam more than anything, not sure they ever pass anymore anyway. It’s just for unrobust Steve who does in the first 5 minutes and calls the shuttle for the whole game.

**Comment by Mirino97** [comment]
IMO, I'm all up for automating all issues with round end and removing vote restart.
Everyone dead? Call shuttle on %death of crew
Boring? Convince Cap to call shuttle
No comms console? Print another one or the game starts a timer for x minutes and then calls it if no console is built.

**Comment by retlaw34** [comment]
a solution for restart votes being too common is to do it how normal ss13 does it, restart votes dont do anything if theres a admin online
