### ISSUE TITLE
AFK players don't get kicked and count toward the popcap limit.

### ISSUE THREAD

**Issue by Stealthbomber16** [space-wizards/space-station-14#9220]
The server can already detect afk players- it does it for admins consistently. Players marked as afk for extended periods of time should be automatically removed from the server to avoid taking up slots.

This is also an easy bandaid fix for space-wizards/RobustToolbox#3012

**Comment by Mirino97** [comment]
@moonheart08 I know players intentionally don't get kicked because the idea is they're allowed to come back.
Should we remove them from limit counter but keep them in the round? Maybe remove from cap after x minutes and kick after y?

Pinging you 'cuz you seem most knowledgeable about it.

**Comment by Stealthbomber16** [comment]
Been fixed twice, presumably.
