### ISSUE TITLE
Ghosts and mice can play instruments

### ISSUE THREAD

**Issue by Mirino97** [space-wizards/space-station-14#9221]
## Description
Be mice or human
if (mice) => just play instrument
if (human) => play instrument, die, don't close window, continue playing from the afterlife.

**Comment by Mirino97** [comment]
Ghosts and mice have complete interaction with the instruments, and instruments only, apparently.
Other machines don't close the open UI on death (and probably should), but don't allow further interaction as ghost.

**Comment by EmoGarbage404** [comment]
Pretty sure this was fixed? I know the mice thing at least is.
