### ISSUE TITLE
Secure windoors are too easy to deconstruct.

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#9226]
## Description
Secure windoors only need to be screwdrivered and wrenched to be deconstructed and thus allowing entry. 

**Reproduction**
N/A

**Screenshots**
N/A

**Additional context**
For something used to secure important areas, they shouldn't be so easy to bypass. Currently it only takes ~5 seconds to get one deconstructed with easily accessible tools.

**Comment by Peptide90** [comment]
From TG:

1) Open the windoor.
2) Screwdriver to open the maintenance panel.
3) Crowbar out the airlock electronics.
4) Remove wires from the assembly with wirecutters.
5) Unanchor it by wrenching.
6) Weld it to deconstruct the assembly into reinforced glass and rods


Not sure we have the door open check but the rest is easy to do if you follow the other examples of construction graphs.

**Comment by Kayek14** [comment]
This issue seems to be resolved. You now need to snip all wires and then use a wrench to remove the board for it to open.
