### ISSUE TITLE
Stop using directional windows on top of grilles

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#9228]
1. It makes re-constructing a pain.
2. They don't smooth.
3. Whenever we get tile layers and actually fix stuff shooting into grilles this won't support it.
4. They have seams on them which means stuff can get through.
5. We'll probably get tile entities someday (to significantly cut down on entity count for walls) which this won't support.
6. They look bad.

I know Atlas and Saltern have them.

**Comment by Just-a-Unity-Dev** [comment]
pretty sure lighthouse also has these
