### ISSUE TITLE
Ventclog event affects the nukie shuttle

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#9229]
## Description
The event VentClog also causes foam to spew from the vents in the nuclear operative shuttle.

**Reproduction**
N/A

**Screenshots**

A ventclog event killed all the nukies this round before they made it to the station.
![ventclognukie](https://user-images.githubusercontent.com/106507028/175906180-75985c35-e3c7-4d33-a1a1-fd9f50672fee.png)

**Additional context**
Not sure if other station events such as breakerflip or gas leak will also trigger on the nukie shuttle.

**Comment by Elijahrane** [comment]
None of the events right now go over every single map/grid. They should be restricted to main stations and choose 1 at random (for multistation support.)
