### ISSUE TITLE
Standard game admins cannot unpause maps due to the command being in shared.

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#9241]
## Description
Client console host runs the command locally instead of relaying it to server, resulting in a confused admin.
## Reproduction
- Try to `unpausemap` central command
- Tp to central command
- Realize you're not actually unpaused and are just mispredicting out the ass.

**Comment by PJB3005** [comment]
There is the `>` command now which forces a command to be executed remotely. Doing `> unpausemap` will work.
