### ISSUE TITLE
Common base class for components that use Bound UIs

### ISSUE THREAD

**Issue by chairbender** [space-wizards/space-station-14#925]
In unmerged PR #771 there was quite a bit of common / duplicated logic that was going to be added between components that used bound user interfaces (like consoles and stuff that has an associated UI popup). It was suggested to create a common base class that these components could inherit to gain this common functionality and avoid duplication. 

For this ticket, also ensure that all necessary validation logic is present on the Bound UIs. Refer to the unmerged PR changes for reference of the sorts of checks that should be done. Ideally most of that stuff should go in the common base class.

If able, also add some user feedback for this stuff as PJB suggested in the PR (I'm not quite sure what that would entail, maybe at least some popup messages when the interaction can't be completed?)

Might be best to wait for #923 to be merged so you can use the new interaction checking convenience methods in InteractionChecks.

**Comment by Zumorica** [comment]
Given that we're going full ECS, this doesn't make sense anymore.

**Comment by AJCM-git** [comment]
> Given that we're going full ECS, this doesn't make sense anymore.

closing then
