### ISSUE TITLE
We have too many job lockers

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#9253]
Put the stuff in the department vending machines instead.

1. Fewer entities
2. Means you don't need to map a billion lockers / adjust storagefills to get the same thing.

**Comment by Peptide90** [comment]
Going to do a salvage / mining vendor in like 3 days. If anyone wants to tackle the others of give suggestions lmk.

suppose to continue sectech theme we could add medtech and engtech if there’s a point (I have other dispensers in works for med stuff).

**Comment by EmoGarbage404** [comment]
Meditech already exists. Engitech wouldnt be bad though.

**Comment by Peptide90** [comment]
How are we feeling on this one now? We have vendors for every dept essentially, and there's been pushed to bring lockers back. I think it can be closed imo.

**Comment by HoofedEar** [comment]
Vibe check on this? Do we need more vendors?

**Comment by UbaserB** [comment]
Are more vendors needed? Get rid of every locker? :clueless:

**Comment by metalgearsloth** [comment]
was this done, last I checked a lot of them had odd mixes

**Comment by Peptide90** [comment]
> was this done, last I checked a lot of them had odd mixes

We've had a lot of vendors added in 2 years, not sure if lockers have been gutted much though. Can reopen it till someone explicitly tags a closing PR.

What's needed? Actually deleting the lockers, reducing their fills or marking them as avoid using suffix?
