### ISSUE TITLE
Put a period at the end of messages

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [space-wizards/space-station-14#9261]
## Description

or don't, right now there is no period

**Reproduction**

press T
write "This is a finished sentence"
exhibit no dot
despair

**Additional context**

muh MRP

**Comment by Visne** [comment]
Not sure if I'm a big fan. While I think it is probably good for RP it still changes the tone of all messages, and it also takes away some power of the user while chatting.

**Comment by Visne** [comment]
Some players sometimes spread out their sentence over multiple messages like this:
`Player: This is just`
`Player: Horrible!`

You could argue that this is bad RP, but in my opinion these types of things can sometimes add more to the RP experience (in this example it adds a pause).

**Comment by Just-a-Unity-Dev** [comment]
This seems more of an HRP thing than an MRP-LRP thing, honestly
