### ISSUE TITLE
Cutting wires should have a do_after

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#9298]
I love it when I get a mispredict or there's 1 transparent pixel in the middle of a simple mob and click the wire underneath it in combat and get stunned. Should just have a short do_after of say 0.5s or 1s.

**Comment by Mirino97** [comment]
They already have a hardcoded default of .25 hun.
Are you implying this should be higher, or did you add them and forgot about this issue? lmao
