### ISSUE TITLE
Items get stuck inside your character

### ISSUE THREAD

**Issue by AJCM-git** [space-wizards/space-station-14#931]
![image](https://user-images.githubusercontent.com/60196617/82473611-d73c1680-9a97-11ea-9650-c4ce4d399fb1.png)
Im not entirely sure how to reproduce this, but its worth notifying

**Comment by AJCM-git** [comment]
an example of this https://cdn.discordapp.com/attachments/310555209753690112/714658987152506960/out.mp4
(in the server with 200ms of latency aprox)

**Comment by SweptWasTaken** [comment]
Never seen this happen personally, even with artificially high ping. I think it's fixed regardless so i'm closing. Correct me if i'm wrong.
