### ISSUE TITLE
Spray exception

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#9321]
Don't compare entitycoordinate positions people

![image](https://user-images.githubusercontent.com/31366439/176822833-3af9b7a5-794f-4b13-950a-7372a93adc47.png)

**Comment by esguard** [comment]
I tried to reproduce this in local by spraying things with space cleaner but couldn't get the exception to appear.

**Comment by HoofedEar** [comment]
According to the attached PR, this can be closed
