### ISSUE TITLE
Floodlight physically pushes players when thrown.

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#9336]
## Description
The item floodlight will physically push players around when it collides into them when thrown.

**Reproduction**
Obtain a floodlight.
Throw floodlight at a player.
The player will be physically pushed by the floodlight.

**Screenshots**
N/A

**Additional context**
Very fun thing to do as a clown! place a banana peel behind someone and use the floodlight to push them into the peel for epic slippage!
Floodlight has the item component, not sure if intended.
Same thing happens with the broken floodlight.

**Comment by Emisse** [comment]
dont see why flood light needs player collision. could just remove it to solve this issue
