### ISSUE TITLE
Pets that get buckled to a horizontal bed remain horizontal when unbuckled.

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#9343]
## Description
Pets will walk around sideways after getting buckled to a medical bed that is sideways.

**Reproduction**
Find or rotate a bed until it is facing east or west.
Buckle an animal to it.
Unbuckle the animal.
The animal's sprite will now be rotated 90 degrees

**Screenshots**
Buckling Morty to the bed.
![sideways pets 2](https://user-images.githubusercontent.com/106507028/176990203-1a205add-117e-4c87-9222-0313d8fbde27.png)

Morty will now moonwalk sideways around the station.
![sideways pets](https://user-images.githubusercontent.com/106507028/176990212-8ec9286c-bd7e-4406-ae80-1298e758c8ae.png)

**Additional context**
Not sure if its specific to only medial beds or will the issue affect all rotated buckleable objects.

**Comment by Peptide90** [comment]
Buckle moment. Ideally it shouldn’t have the 90 degree rotation if it’s already “down”. I guess there would need to be a comp on the animal rather than it relying on the bed for that info.
