### ISSUE TITLE
Need atmos fans

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#9361]
## Description

Magic fans that prevent atmos from going through for the shuttles.
**Reproduction**

**Screenshots**

**Additional context**

**Comment by Peptide90** [comment]
Is this not the holofan projector? If you want it mapped I did a PR for atmos forcefields a long time ago that’s closed.

**Comment by Emisse** [comment]
we could repurpose the holofan fields as generic structures for shuttles

**Comment by mirrorcult** [comment]
this is talking about the tiny fans, which are just airtight entities that are mapped in on the ground but don't block anything. so pretty much the same thing as the projector but can't be removed

**Comment by Peptide90** [comment]
#7527 This but change the sprite or something

**Comment by Emisse** [comment]
we have holofan projector fields in

**Comment by Peptide90** [comment]
> we have holofan projector fields in

We do, I feel like it should still have some sort of static emitter that takes power so they’re not infinite and can be destroyed.
