### ISSUE TITLE
Need a bigger evac shuttle

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#9362]
## Description

All the maps are using a small, cramped shuttle. And it always gets bombed and people suffocate, it stopped being funny.
**Reproduction**

**Screenshots**

**Additional context**

**Comment by Peptide90** [comment]
Feature. Shuttles are massive as it is. 

Having a low pop with <30 seats would make sense and one with about 50+ seats. Not everyone should survive and anyone over that can stand.
