### ISSUE TITLE
Multi-layer inhands

### ISSUE THREAD

**Issue by RemieRichards** [space-wizards/space-station-14#937]
Multi-layer inhands provide the following advantages:

- Directional sprites don't have to be "cut up" to avoid drawing over humans at certain angles.
    - This allows non-humans to use the same inhands with less issue (i.e: borg with a guitar)
- Different layers on the inhands could have different lighting
    - i.e: glowing lights on guns.

The problem is how to go about it.

**Comment by Peptide90** [comment]
Fixed by #6252
