### ISSUE TITLE
The Mass Scanner action that's built into the skulls of AGhosts don't work

### ISSUE THREAD

**Issue by Ablankmann** [space-wizards/space-station-14#9379]
## Description

The name explains itself. The Mass Scanner action that you can use if you're an aghost doesn't work.

**Reproduction**

Observe 
Make yourself an aghost
Attempt to use the Mass Scanner action
Notice that all you see is a black void of nothingness

**Additional context**

This was the case ever since the console was changed, don't know why that wasn't noticed

**Comment by Peptide90** [comment]
Probably not a hard one to fix if you look at the PR that added the actions (intrinsic UI?) and compare it to the recent mass scanner changes by sloth. Could be a 1 line fix.
