### ISSUE TITLE
FOV lets you see animations behind walls

### ISSUE THREAD

**Issue by AJCM-git** [space-wizards/space-station-14#940]
See: https://cdn.discordapp.com/attachments/310555209753690112/713158016610074654/simplescreenrecorder-2020-05-21_18.24.42.mp4

**Comment by PJB3005** [comment]
I've seen this happen on saltern too in the science department. I'll have to investigate what's up with it.

**Comment by PaulRitter** [comment]
is this still a thing? have yet to observe it

**Comment by mirrorcult** [comment]
cant replicate, stale asf
