### ISSUE TITLE
Attack doesnt align with the mouse correctly

### ISSUE THREAD

**Issue by AJCM-git** [space-wizards/space-station-14#941]
https://cdn.discordapp.com/attachments/310555209753690112/713161633484111943/simplescreenrecorder-2020-05-21_18.42.10.mp4

**Comment by SweptWasTaken** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/49448379/82714470-407d7e80-9c7e-11ea-8822-f90f329f3f9b.gif)

**Comment by PJB3005** [comment]
I think it just looks this way because of poor framerate? Both videos are taken with a low framerate and a stun baton (which does an arc). 

[It's fine at 60 FPS.](https://cdn.discordapp.com/attachments/310555209753690112/713779304260960307/simplescreenrecorder-2020-05-23_17.43.52.mp4)

**Comment by AJCM-git** [comment]
yep, the spear works fine. perfomance issue
