### ISSUE TITLE
Escape pods on pillar have a missing floor tile and are spaced.

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#9416]
## Description
The escape pods on the southern part of pillar, under medbay, are exposed to space. Under the substation is only a grille and not a floor tile.

**Reproduction**
N/A

**Screenshots**

Escape pods on pillar.
![pillar shuttle problem 3](https://user-images.githubusercontent.com/106507028/177209664-b792085f-a6cd-414c-a245-f2f76bf6eefd.png)

close up view of the substation and no floor tile under them.
![pillar shuttle problem 2](https://user-images.githubusercontent.com/106507028/177209526-826bd4a8-8530-4b23-87b4-ced0c05129b8.png)

**Additional Information**
No one really uses these and they have no functionality. Kinda sucks though when someone stumbles onto one and ends up spacing all of maint connected down there.

**Comment by Peptide90** [comment]
The map is about to be remade from scratch however, these are currently broken anyway and can’t be undocked. 

Also docked grids don’t transfer their atmos so they shouldn’t be spacing the corridor.
