### ISSUE TITLE
CentComm doesn't have disposals

### ISSUE THREAD

**Issue by BasedUser** [space-wizards/space-station-14#9418]
## Description
Nuff said.

**Reproduction**
Teleport to CentComm.

**Comment by EmoGarbage404** [comment]
I don't know if this is relevant or needed, considering the fact that rounds aren't played on Centcomm and you spend maybe a minute and a half of EORG on it. This is really just at the discretion of @LittleBuilderJane

**Comment by BasedUser** [comment]
It's still a *station*, nevernetheless

**Comment by EmoGarbage404** [comment]
Going to close this because this seems like a non-issue.
