### ISSUE TITLE
Nukies need an incentive to use their own nuke and to evac the station before it explodes.

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#9430]
## Description
Nuclear operatives need an incentive to use their own nuke aboard their shuttle and not the one in the vault. They also should be incentivized to not suicide by team deathmatch on the station after the nuke is armed.

This would add additional layers to the gamemode and can potentially make it more interesting.
Would need a way to prevent crewmembers from boarding the shuttle if parked close. Or a way for operatives to find their way back to the shuttle if parked in deep space away from the station.

**Additional context**
The current meta is to have the nukies rush the vault nuke after obtaining the disk, once armed, they camp the vault until detonation instead of retreating back to their shuttle. 

Relates to issue #8932; nukies should have additional greentext based on how well they do. Full greentext should only be given to operatives that successfully evacuate the station after nuking it.

Might only be useful in MRP.

All this is purely my opinion, but i thought it would be beneficial for the future of the game to discuss additional ways the gamemode could be played out.

**Comment by DogZeroX** [comment]
On TG the on-board nuke cannot be moved. 
![image](https://user-images.githubusercontent.com/43253663/177260443-a35a6444-5d80-4099-9c2c-13e11e0cd5cc.png)

**Comment by metalgearsloth** [comment]
Another idea is making it so the nuke has to be detonated near the centre of the station (which also discourages them from dragging their nuke 1 tile onto the station).

**Comment by Kayek14** [comment]
i think on TG the nukie code is completely different from the one needed for the vault nuke as well.

**Comment by keronshb** [comment]
The two nukes should be considered separate with a different code for each.
