### ISSUE TITLE
Having a second airtight entity under a door makes the tile low pressure even with fixatmos markers, fixVacuum field, etc.

### ISSUE THREAD

**Issue by Elijahrane** [space-wizards/space-station-14#9452]
## Description

This is a minor problem with tiny fans. I tried a few obvious solutions and none worked. We asked Vera in Discord and they weren't entirely sure and said to open an issue.
**Reproduction**

1. Map tiny fan under a door and fixgridatmos.
2. Notice how the area under the door is low pressure.
3. Try FixGridAtmos marker to fill the tile with normal air mix.
4. No dice
5. Try setting tinyfan's airtight component to fixVacuum: true
6. No dice

**Screenshots**

**Additional context**

**Comment by Zumorica** [comment]
The actual problem here was that FixVacuum (which is ran when opening any airlock) was clearing the tile air even when there were no adjacent tiles to get the average gas mixture from.
