### ISSUE TITLE
Lockers trying to mate with players and not letting go.

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#946]
![2020-05-21_22-45-50](https://user-images.githubusercontent.com/49448379/82635381-922af800-9bef-11ea-9d5b-5052c8ae6e35.gif)

Basically if you get into a "sweet spot" between getting shut in the locker and the locker shutting on nothing, you can get the locker stuck on yourself and it'll follow you around relentlessly. 

inb4 "hurr durr physic pr will fix this"

**Comment by InquisitivePenguin** [comment]
Hurr durr the physics PR will actually fix this issue, since objects clipping into each other get pushed apart.

**Comment by InquisitivePenguin** [comment]
Physics rewrite just got merged, this should be fixed now.
