### ISSUE TITLE
Air Alarms are not recieving power from any source

### ISSUE THREAD

**Issue by Cheackraze** [space-wizards/space-station-14#9468]
Constructing air alarms, they are always 'unpowered' now and are not working.  Ran LV, MV, and HV wires under the wall piece to test and still no power.

Steps to Reproduce: Build an Air Alarm anywhere.

Tried to screenshot to save, will reproduce and update with a screenshot asap

**Comment by Peptide90** [comment]
Air alarms are kind of bugged and need fixed.

Can’t see any issues with power though, they take LV wire. Make sure it wasn’t a map error.

**Comment by Cheackraze** [comment]
We have tried on most of the maps in rotation now, after constructing them on a wall they do not get powered up.  The tooltip says 'unpowered' even when we have run all 3 cable types directly underneath them.
