### ISSUE TITLE
Lattices should be deconstructable somewhat easily

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#9472]
If 1 lone cargo tech decides to put some outside of cargo it shouldn't prevent them from docking entirely (yes I saw an idiot do this).

**Comment by Just-a-Unity-Dev** [comment]
i dont understand why we can't just use the wirecutter on a lattice. it's constructed with rods, it looks like a grille so why can't we just use a wirecutter on it

**Comment by Peptide90** [comment]
> i dont understand why we can't just use the wirecutter on a lattice. it's constructed with rods, it looks like a grille so why can't we just use a wirecutter on it

Do whatever SS13 does with a long do after, wyci
