### ISSUE TITLE
Nukies in Zombie Gamemode

### ISSUE THREAD

**Issue by Ablankmann** [space-wizards/space-station-14#9473]
## Description

NukeOps sometimes happens during a zombie round. Praying that this is just a feature, but it doesn't look intentional to me

**Reproduction**

Unsure how to reproduce this issue, but it happens.

**Screenshots**

![image](https://user-images.githubusercontent.com/103340990/177475586-27940c93-a232-4b53-8f8f-c35e6dbf7c53.png)

**Additional context**

It seems to be operating off of Secret rules, meaning that nukies is selected randomly

**Comment by Veritius** [comment]
Are there actually nukies spawning or is this just the round end screen?

**Comment by Just-a-Unity-Dev** [comment]
nukies actually spawned, can confirm

**Comment by Ablankmann** [comment]
> Are there actually nukies spawning or is this just the round end screen?

I can speak from experience that Nukies actually happen during the zombie gamemode. When NukeOps plays, no zombies are spawned

**Comment by moonheart08** [comment]
Judging by the lack of Zombies roundend text i don't think it was actually Zombies mode.
