### ISSUE TITLE
You can set gas tank output pressure on internals to absurdly high pressure vaules.

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#9475]
## Description
Using any internal tank in your hands allows you to set the pressure. You are able to set the output pressure to VERY high kPAs. Using said internal tank does nothing to your character except that will empty very quickly.

**Reproduction**
Obtain a gas tank.
Open interface.
Set out pressure to levels that should not be healthy.

**Screenshots**

Example of setting the output pressure to a high value.
![gas tank pressure 1](https://user-images.githubusercontent.com/106507028/177488534-9f87dcb8-01d7-44f9-9620-78a049a52e38.png)

**Additional context**
Very funny thing to do with a plasma tank because it will quite literally one-tick kill your character if the moles and pressure output are high enough.

Possibility to be expanded on for a way to suicide or kill players by using internals set at high values??

**Comment by Emisse** [comment]
This is needed to empty gas tanks for making bombs

**Comment by Kayek14** [comment]
I can see the need for emptying them quickly, slimes need to do this sometimes to reuse air tanks for nitrogen. Eventually we should be able to use canisters or air pumps to empty gas tanks.

Using internals at such a high pressure should harm the player due to over pressurization but i'm not sure if that is possible as of now.

**Comment by deltanedas** [comment]
its also needed if you want to replace the tank with cold air for pneumatic cannon

could also just have output cap + a button to empty it so you dont need to do the 9999999999kpa shuffle

**Comment by Kayek14** [comment]
Closing as it is an intended feature.
