### ISSUE TITLE
Bolas Don't Work

### ISSUE THREAD

**Issue by liltenhead** [space-wizards/space-station-14#9487]
After the stamina addition, it appears bolas no longer do anything. 

To reproduce just throw a bola at someone, or have them throw it at you.
No stamina damage is taken, and nothing happens.

**Comment by metalgearsloth** [comment]
They do 80 stamina damage which applies the slow but not the knockdown.

**Comment by keronshb** [comment]
Honestly I think I'm going to try to go back to Bolas soonish to finish what I started and do a leg-cuff component.
