### ISSUE TITLE
Pizza Box Pocket Dimension Power Deluxe (broken)

### ISSUE THREAD

**Issue by HoidC** [space-wizards/space-station-14#9501]
You can put people in pizza boxes. They work like crates, even on standing people. Putting them in a garbage bag imprisons them for eternity I believe.. 

**Reproduction**
Step 1. Pizza box. Step 2. Walk over box. Step 3. Close. You are now in the box. You can step out of it though.

**Comment by HoidC** [comment]
okay that's odd, one sec

**Comment by HoidC** [comment]
You can put people in pizza boxes. They work like crates, even on standing people. Putting them in a garbage bag imprisons them for eternity I believe.. 


Step 1. Pizza box. Step 2. Walk over box. Step 3. Close. You are now in the box. You can step out of it though.

**Comment by ElectroJr** [comment]
Can the same bug be nominated for bug of the year twice? (#5255)

This could be fixed separately, but should probably just be done as part of #9291 to avoid unnecessary conflicts.
