### ISSUE TITLE
T-Ray Scanners will sometimes flicker while turned off

### ISSUE THREAD

**Issue by jessicamaybe** [space-wizards/space-station-14#9506]
## Description
Not sure how to reproduce. The issue is contained to specific t-ray scanners so grabbing a new one fixes it.

https://user-images.githubusercontent.com/31836813/177655874-dd3f1464-4e6a-4737-954d-4da009a14204.mp4

**Comment by themias** [comment]
Steps to reproduce:
1. Rapidly activate/deactivate the t-ray scanner for ~5 seconds
2. Start walking
