### ISSUE TITLE
Common and Station Announcements dont share the same color

### ISSUE THREAD

**Issue by Just-a-Unity-Dev** [space-wizards/space-station-14#9515]
## Description
really tiny detail but it's painful

**Screenshots**
![image](https://user-images.githubusercontent.com/67359748/177775613-e3d2e563-210a-43a9-9d15-8ea56f3180bf.png)

**Comment by metalgearsloth** [comment]
Dupe https://github.com/space-wizards/space-station-14/issues/9091
