### ISSUE TITLE
Windoors and shutters y-fight

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#9531]
Looks pretty bad on some maps

**Comment by HoofedEar** [comment]
I know this is marked as easy but could you please explain what "y-fight" means?

**Comment by Just-a-Unity-Dev** [comment]
> I know this is marked as easy but could you please explain what "y-fight" means?

It's when 2 textures overlap each other and start fighting on which is gonna display, it's the 2D equivalent of Z-Fighting

![image](https://user-images.githubusercontent.com/67359748/180361368-c9fafecc-98ed-49cd-9edc-60eda0f398db.png)
