### ISSUE TITLE
Waystation's Shuttle Doesn't Dock 

### ISSUE THREAD

**Issue by Ablankmann** [space-wizards/space-station-14#9532]
## Description

Explains itself, really.

**Reproduction**

Load waystation
Call evac shuttle
Wait for shuttle to arrive
Notice that it doesn't dock with the station, but instead warps "nearby". (Spoiler: It spawns nowhere close to the station)

**Additional context**

I love Waystation!!!!!

**Comment by Peptide90** [comment]
@TimrodDX

**Comment by EmoGarbage404** [comment]
waystation is out of rotation
