### ISSUE TITLE
"Shuttle has warped in nearby" does not work

### ISSUE THREAD

**Issue by HoidC** [space-wizards/space-station-14#9536]
## Description
When the evac is damaged, the shuttle does not warp in nearby, it stays at centcom. This includes if I were to bomb the dock or park cargo shuttle on top of it.

**Reproduction**
Step 1. Break/have a bad dock. Step 2. No shuttle, you're all trapped at station

**Comment by Zumorica** [comment]
> It does warp in.

Well I mean, this issue has been fixed already so of course it does warp in now...
