### ISSUE TITLE
Tiles that should be exposed to space don't always seem to realize.

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#9537]
## Description
This causes areas that should've been spaced to simply Not, the space gods showing mercy upon the crew and simply providing invisible space barriers.

**Reproduction**
This can be reproduced by shooting out windows that are ONLY adjacent to space. If it's next to a lattice it works fine. Easiest to reproduce by exploding the window, deleting it seems to work correctly.

**Comment by Zumorica** [comment]
Can't reproduce locally, needs more testing
