### ISSUE TITLE
Secway on Marathon station spawns stuck in-between a wall and table.

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#9545]
## Description
CrigCrag reported that the secway in the security department on marathon station always spawns between a table and the wall. It is stuck and unable to acquire unless you deconstruct. 

**Screenshots**
![marathon segway stuck](https://user-images.githubusercontent.com/106507028/178063417-cfb524bb-cdfc-4ffe-ae96-89decc321543.png)

**Additional context**
I haven't personally checked weather or not it spawns in like this but it was reported to be like this the past few days.

**Comment by Emisse** [comment]
aight ill fix it

**Comment by Kayek14** [comment]
This issue is resolved.
