### ISSUE TITLE
PDA you spawn with shows red light on sprite, despite having your ID card in it

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#9548]
## Description
PDA you spawn with shows red light on sprite, despite having your ID card in it. Toggling light or ejecting+inserting ID updates sprite to proper one.

**Reproduction**
Spawn, either via readying up or latejoining game.

**Comment by EmoGarbage404** [comment]
This is probably related to the issue with things like belts, crayon boxes, etc not updating and showing the fill sprite.

**Comment by ElectroJr** [comment]
AFAICT space-wizards/RobustToolbox/pull/3184 will fix it.
