### ISSUE TITLE
Request: Add nuke disk to the "Ghost Warp" menu

### ISSUE THREAD

**Issue by jessicamaybe** [space-wizards/space-station-14#9587]
## Description
It would make spectating nukies a better experience

**Comment by mirrorcult** [comment]
i have a general idea for an improved ghost warp system, something like:

- make it three columns
- left hand column is for entities -- alive players, ghosts in a different color at the bottom so you can still follow them. at the very top colored red would be 'objects of notice'--stuff like the nuke disk/nuke during nukies, immovable rods, meteors, space dragons, etc.
- right hand column is for locations -- all the station warps can go here, and more warps should be added for stuff like the emergency shuttle/cargo shuttle/centcomm which can go at the top in red as well

**Comment by EmoGarbage404** [comment]
Pretty sure this was done
