### ISSUE TITLE
Discount dan vendor sprite doesnt match other vendors

### ISSUE THREAD

**Issue by ZeroDayDaemon** [space-wizards/space-station-14#9588]
## Description
Discount dan sprite needs to be updated/replaced since its so, out of place

**Screenshots**

![image](https://user-images.githubusercontent.com/60460608/178136400-38e391d7-5f36-448c-88b5-4d7050b6ca9f.png)

**Comment by moonheart08** [comment]
soul....

**Comment by Vordenburg** [comment]
Fixed by #18609
