### ISSUE TITLE
ChemMaster is a hot mess

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#9592]
1. Server doesn't validate the client's inputs which means a client could lock the server up spawning infinity pills.
2. It should not be possible for someone to spam spawn pills in the first place and this needs to have some kind of cooldown period.
3. It should just have multiple messages instead of chucking all of the data on one message using an enum key to sort it out.

**Comment by Elijahrane** [comment]
Also the custom pill name resets when you pick a different pill sprite.
