### ISSUE TITLE
20 glass shards will instacrit unarmored humanoid

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#9595]
## Description
20 glass shards will instacrit unarmored humanoid. Introduced by #9585.

**Reproduction**
Make pile of 20 shards, step on it barefoot, suffer.

**Screenshots**
![instacrit](https://user-images.githubusercontent.com/108953437/178142842-84a6076e-f105-455b-803f-eb4dd7829e9e.png)

**Additional context**
Stepping on large pile of glass will certainly hurt you but not to the point of instantly killing you. Cap the damage of glass pile, let one walk around glass slowly to avoid damage like one can do with slippery stuff.

**Comment by lzk228** [comment]
now even 30 not doing instacrit
 

https://github.com/space-wizards/space-station-14/assets/124214523/842ee9e2-092e-46f4-ab67-fda2016b73dc
