### ISSUE TITLE
Rejuvenate admin command will fail to update damage visualization on mob body

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#9596]
## Description
Rejuvenate admin command will fail to update damage visualization on mob body.

**Reproduction**
Brutalize some mob. Rejuvenate it. Have mob spook everyone around with wounds.

**Screenshots**
![rejuvenate](https://user-images.githubusercontent.com/108953437/178142955-f522741f-ad27-4dab-a90d-b0f32880bfff.png)

**Comment by mirrorcult** [comment]
dupe of #7543
