### ISSUE TITLE
Emitter beams are blocked by glass windows

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#9597]
## Description
Emitter beams are blocked by glass windows. This is bound to cause issues when Supermatter engine becomes a thing.

**Reproduction**
Do the picture thing.

**Screenshots**
![emitters](https://user-images.githubusercontent.com/108953437/178143907-873642b7-469a-4146-9bee-d83d224a2b07.png)

**Additional context**
Found it when I wanted to improvise gun on gunship shuttle made out of directional plasmarglass. Had to stick emitter into vacuum to get beams out.
![gunship](https://user-images.githubusercontent.com/108953437/178144004-58a20d64-19a9-4cd6-8c2e-79faba97469f.png)
(also pictured: machines z-fighting with directional windows, but unable to reproduce on current game version)

**Comment by TemporalOroboros** [comment]
Noticed this yesterday and nearly turned a chunk of engineering into a fridge as a result.

**Comment by OctoRocket** [comment]
This is because emitters are just a different type of gun, and bullets can't go through glass. I'll keep looking into how to make this work.
