### ISSUE TITLE
Spam clicking microwave buttons makes you press them at the same time

### ISSUE THREAD

**Issue by AJCM-git** [space-wizards/space-station-14#960]
If you spam click the time buttons, you cal press multiple of them at the same time 
![image](https://user-images.githubusercontent.com/60196617/81615181-2ce53480-93af-11ea-8044-94f7de7d3cbe.png)

**Comment by FL-OZ** [comment]
To be clear,  @PJB3005 , @AJCM-git  this does NOT occur only with the microwave. 
![image](https://user-images.githubusercontent.com/58238103/82773984-21f7be80-9e09-11ea-8e2a-e11e8c51b1b6.png)
![image](https://user-images.githubusercontent.com/58238103/82773994-28863600-9e09-11ea-9414-5c228f9a3e5c.png)
![image](https://user-images.githubusercontent.com/58238103/82774023-418ee700-9e09-11ea-8c27-ada25e0eb0b4.png)

**Comment by AJCM-git** [comment]
fixed by #1097
