### ISSUE TITLE
Job-specific Traitor items should be moved out of vendors.

### ISSUE THREAD

**Issue by EmoGarbage404** [space-wizards/space-station-14#9602]
## Description

Will require #9601 

Now that there's support for job-specific traitor items, a lot of emag dependency can be removed by simply moving these into the uplink. This also means that new role-specific items that wouldn't have much use can be made and simply made job-specific as to reduce bloat.

**Comment by Stealthbomber16** [comment]
Seems like a good idea, however the janitorial maid uniform should stay emag-only, because it's cursed.
