### ISSUE TITLE
Diseases should have random spawners

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#9641]
The spawner should also have a low chance of containing a disease. Ideally we'd be able to put these on salvage as an additional hazard for them to contend with.

**Comment by Elijahrane** [comment]
Since diseases aren't entities, what exactly does the spawner spawn?

**Comment by Pangogie** [comment]
I was thinking like an invisible entity that gives you a disease on trigger?

**Comment by metalgearsloth** [comment]
A component that deletes itself on mapinit after trying to apply a disease with a low chance to succeed.

**Comment by Elijahrane** [comment]
Apply a disease to the salv mobs it spawns next to?
