### ISSUE TITLE
28.9999999999999996%

### ISSUE THREAD

**Issue by Just-a-Unity-Dev** [space-wizards/space-station-14#9642]
## Description
The zombie round end screen is stupidly accurate. Could round it down to the 3rd place or something

**Screenshots**
![image](https://user-images.githubusercontent.com/67359748/178414141-8da44b9a-41f9-4e2b-97f6-466a9bfac9cc.png)

**Comment by Elijahrane** [comment]
free one line PR by just using Math.Round wherever that gets passed

**Comment by metalgearsloth** [comment]
Should probably use https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings#use-standard-numeric-format-strings i.e. $"{number:0}"

**Comment by Nikolasfurtado** [comment]
use Math.round or math.floor method to round down or round do nearest number.

**Comment by HoofedEar** [comment]
Would close but no triage, close pls
