### ISSUE TITLE
Mobs that do not breathe (without RespiratorComponent?) will stay in crit forever until killed by something else

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#9651]
## Description
Mobs that do not breathe (without RespiratorComponent?) will stay in crit forever until killed by something else. Makes it required to use /ghost to get out from mob.

**Reproduction**
- Be zombie or space carp
- Be critted
- Wait gazillion years until your body rots away

**Screenshots**
![zombie_and_human_brutalized](https://user-images.githubusercontent.com/108953437/178521696-090de492-e67e-4367-956c-be9f96354737.png)
(pictured: both zombie and human been recently placed into crit with baseball bat, zombie will stick around alive for good while until mix of Blunt and Cellular damage from RottingComponent takes care of body)

**Additional context**
Related to #8914, no one gonna heal zombies with chems or bruise packs.

**Comment by EmoGarbage404** [comment]
i don't think this matters now that we have the succumb sidebar action.
