### ISSUE TITLE
ERROR should be a spawnable item

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#9661]
## Description

Because funny
**Reproduction**

**Screenshots**

**Additional context**

**Comment by moonheart08** [comment]
The only slightly weird thing you need to be aware of is that the error sprite is located at `/EngineResources/Textures/error.rsi` and the state is `error`. Beyond that you're just making something from BaseItem with a specific look and maybe whatever funny behavior you want to tack onto it.
