### ISSUE TITLE
Pressurized atmos pipes deconstructed by a welder while connected to a pipenet will not vent the gas.

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#9663]
## Description
When using a welder to deconstruct a pipe, the gas inside will magically disappear and the pipenet will not vent the air out into the room. If you instead use a wrench to unwrench a pipe that is pressurized, you will get a warning and all the gas will flow out of the disconnected pipe.

Currently all atmos players are using welders to bypass having to depressurize the pipenet if they want to make changes to the pipe layout. 

**Reproduction**
Find a presurized pipe. 
Use a welder on it to deconstruct it.
Observe how the pressurized gas will not flow out into the room.
Test using a wrench instead on a pressurized pipe to see the warning message.

**Screenshots**

not sure if related, but disconnected pipes hold atmosphere and pressure inside them? Observe how the disconnected pipe still shows it has pressure in it.
![broken pipes hold pressure](https://user-images.githubusercontent.com/106507028/178589934-fcf7597a-16f2-4038-abd8-6b7febd71b4c.png)

**Additional context**

It would make sense to depressurize a pipenet before breaking/disconnecting the pipes. 

Should pipes have to be disconnected with a wrench before being able to be deconstructed with a welder?

**Comment by Partmedia** [comment]
The same problem happens if a pressurized pipe is forcibly removed (e.g. bombed).

What should be the desired behavior? I see a few ways forward:

1. Vent the whole pipenet. This would be most realistic to what we see on Earth, but would really mess things up. Most (all?) stations have a single large distro pipenet. Open ends of a pipe would also have to act as a passive vent.
2. Vent a fraction of the pipenet (volume of a pipe / total pipenet volume). The broken ends of the pipes inexplicably hold themselves shut.

(1) is more realistic. (2) requires substantially less re-mapping and re-balancing.

**Comment by Peptide90** [comment]
> The same problem happens if a pressurized pipe is forcibly removed (e.g. bombed).
> 
> What should be the desired behavior? I see a few ways forward:
> 
> 1. Vent the whole pipenet. This would be most realistic to what we see on Earth, but would really mess things up. Most (all?) stations have a single large distro pipenet. Open ends of a pipe would also have to act as a passive vent.
> 2. Vent a fraction of the pipenet (volume of a pipe / total pipenet volume). The broken ends of the pipes inexplicably hold themselves shut.
> 
> (1) is more realistic. (2) requires substantially less re-mapping and re-balancing.

If you’re offering to code it ;) 1 is far too destructive unless there’s automated shut off valves we can add too. Right not it should just vent the sections of pipe that are destroyed and seal the network.

**Comment by Zumorica** [comment]
The real question here is, why the hell can you deconstruct pipes without unanchoring them first?

**Comment by Partmedia** [comment]
@Kayek14 it seems to me that the root issue was recently fixed in #9904.
