### ISSUE TITLE
Crowbar always gives a steel floor. 

### ISSUE THREAD

**Issue by AJCM-git** [space-wizards/space-station-14#973]
1. Place any floor that isnt the steel floor
2. Use the crowbar on it
3. Now you have a steel floor tile
![image](https://user-images.githubusercontent.com/60196617/82738258-6188b280-9d04-11ea-838c-5da0e898d883.png)

**Comment by Zumorica** [comment]
Duplicate of #812

**Comment by FL-OZ** [comment]
Steel floor is a fallback.
