### ISSUE TITLE
You have to do the "dump on table" verb twice for it to work

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#9746]
## Description

Use dump on table with a filled plant bag
The verb doesn't work
Use it again
It actually tries to dump the contents
**Reproduction**

**Screenshots**

**Additional context**

**Comment by fooberticus** [comment]
I can confirm this. In my experience in the last week, it sometimes (rarely) works the first time. Most times it takes 2 attempts. Sometimes it takes 3 or more attempts.
