### ISSUE TITLE
PopupCursor does not popup at cursor

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#9749]
Probably a UIScale issue.

**Comment by Willhelm53** [comment]
https://user-images.githubusercontent.com/97707302/197090527-3e227d7f-75b0-4765-94d5-f3ac5ee6da25.mp4

Seems fine to me when testing locally - perhaps it got fixed since this issue was logged?

**Comment by metalgearsloth** [comment]
Fixed in https://github.com/space-wizards/space-station-14/pull/10016
