### ISSUE TITLE
Need a system for toggling collision properties on "on floor" entities when they are still.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/space-station-14#976]
Stuff like corpses, items, open lockers, etc... all need to have collision while they are *moving*, so that they can actually run into things, but they also need to have their collision gone while they are still, so that you can walk over them.

@InquisitivePenguin

**Comment by ComicIronic** [comment]
Could this be solved with just collision layers in some way? Or is the issue that open lockers should collide with standing humans if the locker itself is the thing moving?

**Comment by InquisitivePenguin** [comment]
We can make that a virtual controller. The controller will check if `LinearVelocity == Vector2.Zero`. If so, it will set `Hard` to false, otherwise it will set `Hard` to true.

**Comment by metalgearsloth** [comment]
Done in physicsrefactor (CollisionWakeComponent).
