### ISSUE TITLE
Sawing an empty double barrel shotgun will make a sawn off spawn with bullets on it

### ISSUE THREAD

**Issue by ikamuse** [space-wizards/space-station-14#9762]
## Description
When you empty a shotgun from it's shells, using a saw to convert it to a sawn off will make the sawn off spawn with bullets inside of it

**Reproduction**
Get a double barrel shotgun
Empty it by interacting
Use a saw on it
Sawn off will spawn with useable bullets

**Screenshots**

**Additional context**
I used a medical circular saw to do it, not sure if that affects it

**Comment by Peptide90** [comment]
Solution is we need empty versions of all guns for crafting. It’s on my radar but need to fix my other gun PR first as it’ll conflict.
