### ISSUE TITLE
Uplinks don't work

### ISSUE THREAD

**Issue by Ablankmann** [space-wizards/space-station-14#9767]
## Description

Title explains itself, uplinks don't work. As a nukie, you're basically fucked

**Reproduction**

Spawn in uplink
Try to buy something
If dont right, nothing happpens. You also get some error in the console about how a sound couldn't be played.

**Comment by EmoGarbage404** [comment]
Fixed in #9765 
this also only applies to handheld uplinks, not pda syndie ones.
