### ISSUE TITLE
Content needs a way to hook into map de/serialization

### ISSUE THREAD

**Issue by ComicIronic** [space-wizards/space-station-14#977]
This is currently blocking atmos, and probably a few other features.

The content layer needs a way to add logic to map saving/loading, which is currently totally handled by the engine.

In particular, for atmos, starting gas values will need to be set in some way.

**Comment by Zumorica** [comment]
While I'm not gonna close this, I don't think this is an issue. For atmos, I simply made a component and slapped it on grids. Then map de/serialization was as simple as an `ExposeData` method.
