### ISSUE TITLE
Station roles can spawn on Nukie Planet

### ISSUE THREAD

**Issue by Ablankmann** [space-wizards/space-station-14#9770]
## Description

Title explains itself. Just watched the poor HoP spawn with nukies

**Reproduction**

Unsure how to reproduce, but it's possible

**Comment by metalgearsloth** [comment]
It's possible the gameticker logic takes random spawn points to use which may explain it though I imagine you would've seen it with the infiltrator as well?

**Comment by EmoGarbage404** [comment]
> It's possible the gameticker logic takes random spawn points to use which may explain it though I imagine you would've seen it with the infiltrator as well?

may be related to the fact that the gamemode and ship use "spawn points" that are essentially just markers to make where to spawn in the mobs for the nukie players.
