### ISSUE TITLE
You can send Syndicate Outpost to station's map

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#9787]
## Description
You can send Syndicate Outpost to station's map. It does not have gyros or thrusters, yet it will happily do one-way trip to station's map, leaving nukie shuttle behind (and nuke there too). Hopefully you brought jetpacks...

**Reproduction**
Be monky, press station FTL destination using shuttle console of Outpost.

**Screenshots**
![who_needs_that_nuke](https://user-images.githubusercontent.com/108953437/179346691-94c48797-b173-41b0-9e91-b5c06d291ec9.png)

**Additional context**
Perhaps make having at least one functioning thruster a requirement for FTL jump?

**Comment by Just-a-Unity-Dev** [comment]
Sloth said something about "If you do this it aint my fault", but my 2c here would be adding a fucking Confirmation Window

**Comment by Emisse** [comment]
idk i think if people are dumb enough to do this thats on them lmao

**Comment by Just-a-Unity-Dev** [comment]
you'd expect a literal FTL engine to have at least a "Hey dumbass are you sure about this" confirmation screen or something.
