### ISSUE TITLE
Armory closets on nukie shuttle start unlocked, yet have red light

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#9788]
## Description
Armory closets on nukie shuttle start unlocked, yet have red light. Toggling lock makes sprite's light correct.

**Reproduction**
- Ready up, forcepreset NukeOps
- Walk up to closet on shuttle, notice red light, notice you can open and close it as much as you want with light staying red

**Screenshots**
![unlocked_red](https://user-images.githubusercontent.com/108953437/179347453-9485e993-3959-445e-b221-b45e8dd2579a.png)

**Additional context**
Similar to issue #9548. Also those closets are not actually ID-locked.

**Comment by lzk228** [comment]
fixed?
