### ISSUE TITLE
Nuke will arm without anchoring

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#9791]
## Description
Nuke will arm without anchoring. If nukies taking disk and running away to bomb station from space with own nuke while staying highly mobile is an issue, this is a problem.

**Reproduction**
- Get disk
- Unlock nuke
- Space nuke
- Arm nuke
- Jetpack in circles around station with armed nuke

**Screenshots**
![spacenuke](https://user-images.githubusercontent.com/108953437/179348604-4fd4c0e4-f604-45d6-8554-ab758607afd1.png)

**Additional context**
Related to issue #9790.

**Comment by mirrorcult** [comment]
mfw
