### ISSUE TITLE
"Nearby" escape shuttle is not nearby

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#9799]
## Description
"Nearby" escape shuttle is not nearby. Finding one with even with jetpack would prove massive pain. It even does not fit aghost's mass scanner range!

**Reproduction**
- Load waystation
- Wait for shuttle
- aghost
- cry

**Screenshots**
![nearby](https://user-images.githubusercontent.com/108953437/179361822-7fbf34bf-16ee-40f6-b574-7b19806eeb10.png)

**Additional context**
Shuttle should aggressively park as close to station's evac dock as possible.

**Comment by Zumorica** [comment]
Also see #9536 and #9532

**Comment by metalgearsloth** [comment]
Also https://github.com/space-wizards/space-station-14/issues/9747

**Comment by metalgearsloth** [comment]
Fixed the bounds being 2x what they needed to be.
