### ISSUE TITLE
Sawing an empty double-barreled shotgun makes a sawed-off shotgun with two rounds loaded

### ISSUE THREAD

**Issue by coolmankid12345** [space-wizards/space-station-14#9803]
## Description

Sawing an empty double-barreled shotgun makes a sawed-off shotgun with two rounds loaded
**Reproduction**

Unload double barreled shotgun
Saw shotgun
Get sawed-off shotgun with two loaded rounds
**Screenshots**

**Additional context**

**Comment by ikamuse** [comment]
yeah i reported it too #9762

**Comment by coolmankid12345** [comment]
I should've checked before I wrote this
