### ISSUE TITLE
Suggestion: emergency shuttle should stay for significantly longer time and call out it's coordinates and side of station it's closest to if docking failure happens

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#9805]
## Description
Emergency shuttle should stay for significantly longer time and call out it's coordinates and side of station it's closest to if docking failure happens. Right now docking failure will lead to issue #9799, and you are not making that trip in time without tweaks suggested.

**Additional context**
Somewhat related to feature already introduced by PR #9564, just for docking failure condition.

**Comment by metalgearsloth** [comment]
3 minutes is already very long. If you can't get to the shuttle in 3 minutes you're probably not making it.

Direction is implemented in https://github.com/space-wizards/space-station-14/pull/9885
