### ISSUE TITLE
Holding a duffel bag in your hand negates the running slowdown

### ISSUE THREAD

**Issue by ikamuse** [space-wizards/space-station-14#9806]
## Description
Holding a duffel bag in your hand will make you run at normal speed compared to when you have it in your back, hardsuits also suffer from this

**Reproduction**
Get or spawn with a duffel bag
Hold it in your hand, you'll run at normal speed unlike having it on your back

**Screenshots**

**Additional context**

**Comment by asperger-sind** [comment]
> You pay for this when you get slipped or disarmed. I consider this a feature.

Whilst I agree with this, it can be negated by holding the hand without the duffel and wearing some form of noslips, but yeah, feature more than issue.

**Comment by lzk228** [comment]
fixed
