### ISSUE TITLE
Events will run even with events.enabled False

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#9808]
## Description
Events will run even with events.enabled False. I tried disabling events on local testing server by adding server_config.toml entry:
```
[events]
enabled = false
```

Both `sudo cvar events.enabled` on client and server console reveal False as value:
```
> cvar events.enabled                                                                                                                                                                                             
False
```
Yet events still run.

**Reproduction**
Try to disable events via cvar in config file, suffer random power outages anyway.

**Comment by Peptide90** [comment]
IIRC maintainers do this when testing locally so maybe they can shine a light
