### ISSUE TITLE
Protolathes show two servers with single ID in Research Server Selection

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#9809]
## Description
Protolathes show two servers with single ID in Research Server Selection. Something is borked.

**Reproduction**
Use protolathe, click the button.

**Screenshots**
![odd_server_list](https://user-images.githubusercontent.com/108953437/179365282-44f101ff-1aef-49c7-b910-42d8fe859b3f.png)

**Comment by Peptide90** [comment]
Something something lathe code stinky and needs a refactor

**Comment by HoofedEar** [comment]
Reproduced in local environment, figured out the issue, will create PR for it

![Screen Shot 2022-07-21 at 6 43 04 AM](https://user-images.githubusercontent.com/1261392/180228445-402d0b4e-608d-47b9-af9b-ef1f7441cbec.jpg)
