### ISSUE TITLE
Makeshift laser requires a fresh full stack of diamond

### ISSUE THREAD

**Issue by EeveeTea** [space-wizards/space-station-14#9810]
There was a problem I encountered trying to create a makeshift laser from the diamond that can be found in the maintenance vault in Lighthouse. It just doesn't work at all with the "not enough materials" message. After further testing, it seems to only be able to work with a full (30) stack of refined diamond. I should also note that creating a full stack out of single diamonds doesn't work either, only a spawned full stack will work. Splitting the spawned stack and recombining breaks the ability to use it as a component in the laser.

I suspect that a full stack of refined diamond is it's own unique item that cannot be created from single diamonds due to this behavior. Maybe a separate bug report can be submitted for that specific issue.

**Comment by Zumorica** [comment]
The problem is that someone used a prototype step instead of a material step in the makeshift laser construction graph.
