### ISSUE TITLE
Capitalization Convention and Standardization

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#983]
Per [this pr](https://github.com/space-wizards/space-station-14/pull/981#issuecomment-633221811) it's probably time to set a standard for capitalization of objects, walls, etc. as it's very inconsistent throughout the codebase.

Currently we have 90% of random stuff capitalized. 

Some "people" think we should only capitalize proper nouns. 

Whichever it is we should decide on it and chisel it in stone. Personally I think just capitalizing everything both looks good and would require 90% less work to get everything up to standard but it's not a big deal either way. 

Just make a decision. Whichever we decide on I can quickly zip through the codebase and standardize it.

**Comment by AJCM-git** [comment]
My vote goes to only capitalize proper nouns

**Comment by SweptWasTaken** [comment]
![capitalist](https://user-images.githubusercontent.com/49448379/82754718-6611a180-9dbe-11ea-956c-cb1001ca03d3.gif)

**Comment by ComicIronic** [comment]
I think only capitalising proper nouns looks better in messages. It's a bit jarring to read "Light Bulb" in the middle of a sentence.

**Comment by PJB3005** [comment]
I vote proper nouns capitalized only.

**Comment by CakeQ** [comment]
^

**Comment by SweptWasTaken** [comment]
Since this has been open for two days i'm going to run through the repo and get it up to the decided upon standard. I'll reference a pr when i'm done.

**Comment by ComicIronic** [comment]
This maybe could be closed now, thanks to #1020 .

**Comment by AJCM-git** [comment]
yep
