### ISSUE TITLE
Syndicate pAI's

### ISSUE THREAD

**Issue by Just-a-Unity-Dev** [space-wizards/space-station-14#9839]
## Description
Feature request. Tint the pAI's red and give them access to see and speak on Syndicate radio instead of Common.

Willing to work on this if I have the chance

**Comment by Just-a-Unity-Dev** [comment]
Maybe draft up basic Silicon laws?

**Comment by LittleBuilderJane** [comment]
Theoretically speaking, Syndicate pAIs could just be regular pAIs but emagged or something like that. Once activated, whatever method we decide for that, they could get access to some abilities so they can help the syndie achieve their objectives. I think it'd add an interesting avenue of gameplay.

**Comment by Just-a-Unity-Dev** [comment]
> Theoretically speaking, Syndicate pAIs could just be regular pAIs but emagged or something like that. Once activated, whatever method we decide for that, they could get access to some abilities so they can help the syndie achieve their objectives. I think it'd add an interesting avenue of gameplay.

What COULD we add to pAI gameplay to make it better? Right now it's a talking MP3 player and the MP3 player part doesn't even work. I guess I could try adding a pAI shop where you can health scan your owner or something? Could be like /tg/'s system with apps. Shrug.

**Comment by Just-a-Unity-Dev** [comment]
> > What COULD we add to pAI gameplay to make it better?
> 
> It's a ghost role, does it need to do everything.

Yeah but right now it just feels so bare

**Comment by metalgearsloth** [comment]
It can play music and talk which is arguably more than what a mouse can do.

**Comment by Emisse** [comment]
in 13 they can choose holoforms to walk around as, i have all the rsi's for this

**Comment by HoidC** [comment]
I think the PAI should be able to play music in a variety of instruments. For an MP3 player the inbuilt music player is pretty shit.

But I can't code that, so this is a WYCI moment

**Comment by Just-a-Unity-Dev** [comment]
shrug, guess im wrong. i'll try to fix it tommorow alongside some other pAI qol additions

**Comment by Vordenburg** [comment]
Fixed by #18625 and #18674
