### ISSUE TITLE
Atlas is no longer able to fly.

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#9846]
## Description
Even after stacking on a ton of thrusters I can't get it to move faster than 0.1m/s.

**Comment by lzk228** [comment]
Atlas isnt in game rn iirc

**Comment by GoodWheatley** [comment]
> Atlas isnt in game rn iirc

It is.

**Comment by deltanedas** [comment]
its no longer a shittle so doesnt apply
