### ISSUE TITLE
Every single sentient object can move

### ISSUE THREAD

**Issue by EmoGarbage404** [space-wizards/space-station-14#9847]
## Description

https://user-images.githubusercontent.com/98561806/179425770-255e01e2-bb4d-4603-9a1a-49c1faaf7e54.mp4

**Additional context**

spams this exception:
`input.context: AttachedEnt has no InputComponent: entId=1294, entProto=EntityPrototype(VendingMachineCola). Setting default "common" context...`

**Comment by fooberticus** [comment]
Making any Entity sentient (including making an inanimate object a ghost role) will always add movement components, apparently by design.

In `Content.Server.Mind.Commands.MakeSentientCommand`

```c#
public static void MakeSentient(EntityUid uid, IEntityManager entityManager)
{
    entityManager.RemoveComponent<AiControllerComponent>(uid);

    entityManager.EnsureComponent<MindComponent>(uid);
    entityManager.EnsureComponent<InputMoverComponent>(uid);
    entityManager.EnsureComponent<MobMoverComponent>(uid);
    entityManager.EnsureComponent<MovementSpeedModifierComponent>(uid);
    entityManager.EnsureComponent<SharedSpeechComponent>(uid);
    entityManager.EnsureComponent<SharedEmotingComponent>(uid);
    entityManager.EnsureComponent<ExaminerComponent>(uid);
}
```

Maybe a good solution would be to add another property to the "Make Ghost Role" dialog to enable/disable movement. This would allow the admin granular control over this behavior.

I'm not sure it's urgent though, more of a nice thing to have for admins to goof with.

**Comment by moonheart08** [comment]
The "fix" here would be to make sure makesentient ensures the presence of InputComponent

**Comment by fooberticus** [comment]
The `MakeSentient` method is in the server code and `InputComponent` is a class in the client, you can't check for that component where this logic is executing.

The original intention was clearly to add movement components if the entity doesn't have them. There must have been a reason for that decision. This seems more like a request for more granular customization of an existing feature, vs a bug.

**Comment by mirrorcult** [comment]
this is in fact a bug because this was not the case 3 days ago before the movement refactor which changed how these movement components work was implemented

**Comment by fooberticus** [comment]
If it was unintentional, the fix would be to remove these three new lines in `MakeSentient`

```c#
entityManager.EnsureComponent<InputMoverComponent>(uid);
entityManager.EnsureComponent<MobMoverComponent>(uid);
entityManager.EnsureComponent<MovementSpeedModifierComponent>(uid);
```

@mirrorcult if you want it gone, I can do it. I just didn't want to clobber something that was added for a purpose.

**Comment by metalgearsloth** [comment]
Prior to movement refactor it was bugged in its own way; the entity was given sharedplayerinputmover and sharedmobmover but because they didn't have movementspeedmodifier they couldn't move so it was effectively useless.

**Comment by fooberticus** [comment]
It looks like `InputMoverComponent` is integral to correctly orienting the camera as well.

**Comment by EmoGarbage404** [comment]
this got fixed with the changes to ghost roles
