### ISSUE TITLE
Cargo is still unplayable on Barratry

### ISSUE THREAD

**Issue by Ablankmann** [space-wizards/space-station-14#9851]
## Description

Cargo STILL doesn't have shuttle stuff on barratry. You can't do anything without admin help. This should not be the case for any map, at all. Come on.

**Reproduction**

Read #9429
Seriously can't believe it's gone on for this long

**Screenshots**

Read #9429

**Comment by EmoGarbage404** [comment]
something something don't open the same issue twice.

**Comment by Ablankmann** [comment]
> something something don't open the same issue twice.

I'll refrain from doing so in the future

**Comment by Just-a-Unity-Dev** [comment]
might wanna close this, it's obv a dupe of #9429
