### ISSUE TITLE
Smiting ghost with chessboard produces odd results

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#9858]
## Description
Smiting ghost with chessboard produces odd results. I dunno. You still can follow mobs on Warp list and random entities in your view. Your view will not use grid's angle. You cannot move, only teleport with Follow/Warp. If you reconnect, you get correct angle, but still cannot move and movement attempt will be mispredicted.

**Reproduction**
- Annoy(?) Pancake by orbiting their ghost
- Be chessboard smited, as observer ghost
- Witness odd things

**Screenshots**
![smited_ghost](https://user-images.githubusercontent.com/108953437/179498804-0b20ce59-7c98-44cd-b1f1-e7ffbf5ec4be.png)

**Additional context**
Probably should introduce feature for admins to make self completely intangible, when I follow admins as observer, I do it to watch the funny.

**Comment by moonheart08** [comment]
This is a smite, it breaks the game to some extent and it's an administrative issue that they applied it to a ghost.
