### ISSUE TITLE
Speedloaders don't Speedload

### ISSUE THREAD

**Issue by Ablankmann** [space-wizards/space-station-14#9896]
## Description

Name explains itself. The only way to use the "speed"loader in its current state is to unload it, and put every bullet in the gun manually. I don't call that speedloading. 
Happy 1000th open issue

**Reproduction**

Get a revolver (any revolver, as long as it has a speedloader)
Get a speedloader for said revolver
Unload revolver
Attempt to use speedloader on revolver
If done correctly, the speedloader will do absolutely nothing. 

**Additional context**

This has been an issue ever since the gun rework I believe, but... Nobody's reported the issue. This says a lot about our society

**Comment by Just-a-Unity-Dev** [comment]
I'm gonna attempt to fix this, as (far as I know) nobody has attempted to.
