### ISSUE TITLE
Moving extra-bright lantern that is turned on from or to pocket will change sprite to inactive one

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#9906]
## Description
Moving extra-bright lantern that is turned on from or to pocket will change sprite to inactive one (while still keeping lamp on).

**Reproduction**
- Get extra-bright lantern
- Turn it on via action bar
- Put it into pocket

**Screenshots**
![lamp_sprite](https://user-images.githubusercontent.com/108953437/179972347-af618e65-cd15-4a26-9d86-938f5d343cea.png)

**Comment by lzk228** [comment]
seems to be fixed

https://github.com/space-wizards/space-station-14/assets/124214523/ec5f7914-fdd3-461d-aa7d-244b66396f2b
