### ISSUE TITLE
Splitstation To Do List

### ISSUE THREAD

**Issue by Peptide90** [space-wizards/space-station-14#9908]
## Description

Opening an issue just so there's a central point for issues to come under, for other feedback not caught and to show people what the proposed solutions are.

PR #9905 proposed removing Splitstation despite having a large amount of supporters in discord and subjective reasons for removing (The map isn't the same map that was originally released many months ago). So issues identified include:

- Boring maints.
- Salvage and Science are still too far apart.
- Various small tweaks to be made to maint around security.
- Bridge needs some sort of maints.
- Bar gets too much through traffic.
- Silver tiles in CMO and HoPs offices.
- Head dorms are underused.
- Decaled floors are ugly.
- Medbay feels like a choke point and big corridor.
- Engineering layout is annoying.
- Emisse wants a bigger still atmos ;)
- Remove the bar in cafeteria.

### Remedial Action:

- [ ] Move chapel and or library somewhere else, maybe south side of station.
- [ ] Move salvage closer to science - probably where clown and mime are but rejig corridor to be more interesting.
- [x] Make maint bend into armoury so it's not straight.
- [x] Make room between cells and security locker room into maint.
- [x] Change orientation of bar so it's wider - remove corridor attached and make it a through corridor with a stage area on the left and the bar on the right (so people can watch cargo fail to dock and so it's easier yet to split)
- [x] Remove silver tiles for wood and carpet.
- [x] Removed decaled floors in shop and bar.
- [x] Redo everything left of botany to allow for bigger maint between service area and medbay. Redo all of medbay as part of this, maybe make it into a donut or loop.
- [ ] Redo engineering layout and add bigger atmos?
- [x] Remove bar in cafeteria.
- [ ] Either move bridge up into park making a mega park and or add a maint tunnel below it.
- [ ] Rejig some maint rooms but ultimately look to a more flavourful mapper to make a pass.

Bearing in mind Pillar needs to be remade before I can do most of this however for small changes like the bar I can probably push out first. Any further issues or suggestions fire away.

**Comment by Cheackraze** [comment]
Replace the air vents inside of the atmos gas chambers with passive vents or air injectors, after air vents were changed the distro system now collapses and can be a death trap.  Most atmos techs bypass the pressure chamber because of the air vent anyway.
