### ISSUE TITLE
Full cable coils spawn as size 10, yet you can assemble one that is size 3

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#9909]
## Description
Full cable coils spawn as size 10, yet you can assemble one that is size 3. Stack does not update it's size properly.

**Reproduction**
- Split away cable from coil stack
- Reassemble coil stack back to 30 items
- Save 7 units of storage

**Screenshots**
First two are spawned, third one is reassembled:
![cable_coil_size](https://user-images.githubusercontent.com/108953437/179997619-5ab84f51-0770-432a-ab66-72d633619a95.png)

**Comment by HoofedEar** [comment]
I guess we'd need to discuss how to tackle this. I see two different options:
1. Easy fix of just making the stack, when at max, equal the same size as a newly spawned stack.
2. Coming up with a way to track/update the size as the stack gets bigger. Maybe adding something to Stack component where you define the size when the stack is at certain values? Maybe just multiplying the base item size by the stack size?

**Comment by Vordenburg** [comment]
Was duped by #11514

**Comment by deltanedas** [comment]
should be closed anyway
