### ISSUE TITLE
"Return to body" ghost button resets "Boo!" action cooldown

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#9915]
## Description
"Return to body" ghost button resets "Boo!" action cooldown.

**Reproduction**
1. Die in way that allows return to body (not gibbing or /suicide command)
2. Exit body
3. Boo!
4. Return to body
5. GOTO 2
6. ???
7. adminhelp.ogg

**Comment by ElectroJr** [comment]
duplicate of #5207
