### ISSUE TITLE
Dart ERT shuttle atmos is messed up

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#9920]
## Description
Dart ERT shuttle atmos is messed up. It is not pressurized by default. Gas miner chambers have normal vents instead of passive ones, and they are in default "Releasing, 101.3 external" configuration.

**Reproduction**
- lsmap to find vacant `mapID`
- loadgamemap Dart `mapID`
- mapinit `mapID`
- tp 0 0 `mapID`
- spawn in mob, control it, enjoy death

**Screenshots**
![Dart_atmos](https://user-images.githubusercontent.com/108953437/180026343-8a4332c8-74fc-4572-b84a-4e1959ee14c4.png)

**Comment by lzk228** [comment]
probably fixed
