### ISSUE TITLE
Wand of instant death does not perform as advertised against things able to survive 300 damage

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#9924]
## Description
Wand of instant death does not perform as advertised against things able to survive 300 damage. That appears to be things like space dragon (takes 2 shots) or xeno queen (takes 5 shots).

**Reproduction**
- Spawn the wand
- Spawn dubiously balanced mobs
- Click mobs with wand in combat mode

**Comment by HoofedEar** [comment]
Is this intended or should this just be upped to 9999? It's easily modified in YAML, but I want to find out if 300 is the intended value

**Comment by EmoGarbage404** [comment]
If you just keep upping the number, eventually it's going to just destroy walls and stuff. It should probably have unique behavior to instantly kill a mob.

**Comment by HoofedEar** [comment]
> If you just keep upping the number, eventually it's going to just destroy walls and stuff. It should probably have unique behavior to instantly kill a mob.

Agreed, but I'm not sure why #9925 was closed as intended then...

**Comment by Elijahrane** [comment]
Make it directly kill a mob bypassing the damage system entirely.

**Comment by moonheart08** [comment]
> Is this intended or should this just be upped to 9999? It's easily modified in YAML, but I want to find out if 300 is the intended value

It's intended.
