### ISSUE TITLE
Wand of instant death will damage non-living things like windows

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#9925]
## Description
Wand of instant death will damage non-living things like windows. It's merely armor-piercing 300 dmg bullet gun after all.

**Reproduction**
- Spawn the wand
- Click window in combat mode

**Additional context**
Related to issue #9924 - might want to rework projectile to:
- Affect mobs only
- Kill mob regardless of mob's health

**Comment by mirrorcult** [comment]
intended

**Comment by EmoGarbage404** [comment]
good thing we're not tgstation.
