### ISSUE TITLE
Getting cuffed and having your hands removed breaks uncuffing

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#9930]
## Description
Getting cuffed and having your hands removed breaks uncuffing. Alert just stays once you turn with cuffs on and attempt to break out once, does nothing once clicked again.

**Reproduction**
- Get infected by zombie virus
- Responsibly ask to get cuffed
- Turn zombie once disease turns you
- Try to break out to get them brains
- Enjoy pacifist zombie playstyle

Alternatively:
- Cuff self
- Delete Hands component off self with VV
- Try to break out
- Experience the bug

**Screenshots**
Those broken cuffs are mine:
![cuffed_zombie](https://user-images.githubusercontent.com/108953437/180085241-7c6ef7f6-2293-433c-b001-8386c20802d1.png)

**Comment by keronshb** [comment]
I believe the desired behavior is that if someone loses a hand they should be uncuffed immediately. Cuffing needs ECS anyway so I think I'll put up an issue for that and mention this as well.
