### ISSUE TITLE
Shuttle Windows have an invalid node

### ISSUE THREAD

**Issue by EmoGarbage404** [space-wizards/space-station-14#9931]
## Description

![image](https://user-images.githubusercontent.com/98561806/180088546-a69bc4bd-1108-42cc-97fc-93c17ef94436.png)

**Reproduction**

exist and see
**Screenshots**

**Additional context**

how was this merged.

**Comment by Peptide90** [comment]
> > how was this merged.
> 
> I guess I gotta set up local build environment to not do that kind of thing... I wanna move onto more difficult things than just messing with YAML.

Huh? If I’m not mistaken they were added in #9306 but don’t have a construction graph, hence shuttleWindow as a node is invalid?

**Comment by Peptide90** [comment]
> I am not one responsible for shuttle window thing, sorry for offtopic. My theory it's all webedits and untested code to blame.

Not necessarily, there should be a test to pick-up invalid nodes. I believe there is but not it checks the construction graph, not the entity for non existent nodes. 

The easy fix to this is just remove the construction component from the shuttle window, the more in depth fix is to add the node to the graph which is pretty simple too. Haven’t checked if shuttle walls are constructible or if they’re even intended to be.

**Comment by Ablankmann** [comment]
> > I am not one responsible for shuttle window thing, sorry for offtopic. My theory it's all webedits and untested code to blame.
> 
> Not necessarily, there should be a test to pick-up invalid nodes. I believe there is but not it checks the construction graph, not the entity for non existent nodes.
> 
> The easy fix to this is just remove the construction component from the shuttle window, the more in depth fix is to add the node to the graph which is pretty simple too. Haven’t checked if shuttle walls are constructible or if they’re even intended to be.

They're not supposed to be able to be created until we get titanium

**Comment by Peptide90** [comment]
> Might want to just make them equal to normal walls, made with steel. Freedom to shuttle builders! But hold on, how do you make girder slapped with steel turn into shuttle wall?..

The issue is people potentially deconstructing the proper shuttles but hey ho. For construction I recommend the page on the development wiki. Essentially you’ll need a new node for the thing you want with steps different to the ones to make a normal wall. Otherwise you’ll need a new graph. We’re mimicking TG construction steps as much as possible.

**Comment by mirrorcult** [comment]
shuttle windows shouldn't be constructible same with walls

**Comment by Ablankmann** [comment]
> > The issue is people potentially deconstructing the proper shuttles
> 
> Well, it would be paying attention to dork with lit welder and doafter above their head to mitigate that. I don't have much faith in players tho, I could do the doafter thing with C4 brick planting just fine.

Meh, I would wait until we have the proper materials for shuttle stuff to be added before we make them constructable
