### ISSUE TITLE
Traitor objectives can get wonky with targeting

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#9935]
## Description
Traitor objectives can get wonky with targeting. Feature?

**Reproduction**
- Adminbus busy server to make everyone syndie I guess

**Screenshots**
![get_that_mouse](https://user-images.githubusercontent.com/108953437/180098518-73fe0418-d400-480c-969a-0f25726095db.png)
![protect_self](https://user-images.githubusercontent.com/108953437/180098531-cb1252b7-6677-4e49-a79a-b14057a54ac2.png)
Don't have screenshot, but I as "latejoin" traitor (turned syndie by adminbus) once been tasked with killing Commander Iota.

**Additional context**
Might want to ensure that Protect objective does not target traitor themselves and Kill objective targets only mobs that are part of station crew.

**Comment by Elijahrane** [comment]
Intended

**Comment by EmoGarbage404** [comment]
> Intended and epic objectives

Clearly not intended and annoying more than anything.

**Comment by Elijahrane** [comment]
![image](https://user-images.githubusercontent.com/60792108/183316078-294954b0-2c07-405e-bc0f-1b9dae033c77.png)

**Comment by EmoGarbage404** [comment]
you can't have PAI or mouse kill objectives anymore and i'm pretty sure you can't get self-protect objectives either.
