### ISSUE TITLE
Suggestion: Implement "humiliating defeat" lose condition for Nukeops

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#9937]
## Description
Implement "humiliating defeat" lose condition for Nukeops. For time being, nuke destroying Syndicate Outpost will count as win for nukies.

**Comment by Just-a-Unity-Dev** [comment]
idea: job-ban the nukies from playing nukies if this shit happens

**Comment by metalgearsloth** [comment]
Dupe https://github.com/space-wizards/space-station-14/issues/8932
