### ISSUE TITLE
Evac Shuttle Docking Announcement Borked

### ISSUE THREAD

**Issue by 5150Con** [space-wizards/space-station-14#9943]
## Description
Had a few rounds recently where the Evac shuttle does not report it docking, only to hear that the shuttle is launching in 10 seconds.

**Reproduction**
No idea.

**Additional context**
Shuttle says it's arriving in X minutes, no docking announcement, boom you're left behind on station.

**Comment by Just-a-Unity-Dev** [comment]
In any of these rounds, did the station disconnect? (via singuloose or whatever)
