### ISSUE TITLE
Does `flatReductions` in `damageModifierSet` function correctly?

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#9944]
## Description
Does `flatReductions` in `damageModifierSet` function correctly? See my comment on PR #9940 - I just assumed that zombies are _meant_ to die to rotting over time. Until I see that `#offsets rotting damage` comment for Zombie modifier set. As far as I know, zombies will reliably rot away.

**Reproduction**
- Be zombie
- Be stinky
- Slowly die

**Additional context**
I personally liked that OP mobs running at full speed and dishing out 20 damage punches had timer ticking for them, but I merely assumed it to be a _feature_.

**Comment by keronshb** [comment]
Flat Reductions do work afaik. Check out riot shields and compare the ones that have flat reductions and the ones that don't.

**Comment by EmoGarbage404** [comment]
these do work. The miasma damage is specified to ignore resistances, which is perfectly fine. I'm closing this because it's a complete non-issue.
