### ISSUE TITLE
Some textures are in RGB color and some are in Indexed color

### ISSUE THREAD

**Issue by EmoGarbage404** [space-wizards/space-station-14#9955]
## Description

end my fucking suffering.
convert to rgb.
**Reproduction**

**Screenshots**

**Additional context**

**Comment by Ygg01** [comment]
What is this issue? As a relative outsider I have no clue what this is.

**Comment by IProduceWidgets** [comment]
> What is this issue? As a relative outsider, I have no clue what this is.

If you open the .png inside an assets .rsi folder, then try to edit the color values, you will find that about half the png's have "indexed colors" which locks the png to only have specific colored pixels. 

Its easy to fix, you can just open it in gimp (or another editing software) and change it then reexport, but, its a lot of tedious work.

I don't think its the biggest problem, it only comes up for me when Im using another sprite as a guide/touchstone for something else Im working on. There might be a reason EMO wants it gone though like in engine recoloring or something.
