### ISSUE TITLE
Handcuffs and Cuffable needs a lot of love and ECS + Fixes.

### ISSUE THREAD

**Issue by keronshb** [space-wizards/space-station-14#9965]
## Description

Handcuff Components and Cuffable Components could use a lot of modernization and they need to be ECS'd.

There's also a bug where if you lose your hand(s) you can't remove your cuffs. The desirable outcome is that if a hand is lost, you immediately become uncuffed and you can't be cuffed with one hand.

#9930 is a related issue.

**Reproduction**

**Screenshots**

**Additional context**

**Comment by mirrorcult** [comment]
#13614 more specific
