### ISSUE TITLE
Damaging a gravity generator after it has been destroyed causes it to shake the station again

### ISSUE THREAD

**Issue by InquisitivePenguin** [space-wizards/space-station-14#998]
This is a fairly simple bug. When damaging the gravity generator after it has been destroyed (i.e. shooting it, blowing it up, etc., the alarm sounds and everyone on the grid shakes, as if the generator had just been destroyed.

I recommend that someone fairly new to SS14 contribution works on this issue, as it's a great learning opportunity. The relevant files to look at are `GravitySystem.cs` and `GravityGeneratorComponent.cs`.

**Comment by AwaitFuture** [comment]
Hey,
Im struggling to reproduce your issue.
https://cdn.discordapp.com/attachments/560845886263918612/715139112402944000/output3.webm

do you know if this was already patched or did I do something wrong?

**Comment by FL-OZ** [comment]
Unable to reproduce at all. Tried explosives, firearms, etc. Tried on local, tried on public server.

**Comment by InquisitivePenguin** [comment]
Interesting. I haven't been able to reproduce the issue since I first saw it either: my guess is that it had to do with something I was working on at the time. Closing this.
