### ISSUE TITLE
Sawing off a double barrel converts the ammo inside to lethals

### ISSUE THREAD

**Issue by Cheackraze** [space-wizards/space-station-14#9981]
## Description
I loaded my bar shotgun with bean bags at the start of the round as always, then a little later sawed it off so it would fit in my pocket.  Then when I went to swap back to lethals, because nukies, it already had lethals inside.

**Reproduction**

Step one: load bean bag or other ammo type into a double barrel
Step two: saw that sucker off
Step three: unload your new free lethal ammo

**Additional context**
I suspect that sawing off an unloaded shot gun may also produce 2 fresh new lethal rounds.  Not sure, haven't tested that, I just had a round where this happened so I figured I would make a report about it.

**Comment by mirrorcult** [comment]
dupe #9762
